### ISSUE TITLE
[Issue] TRENCH console errors.

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#1000]
**Describe the bug**
https://pastebin.com/JdxcJ3bT

**To Reproduce**
Use trench enchanted tools.

**Screenshots / Video**
None

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.15.2
- Plugin Version: 7.5.0-Pre4

**Comment by GC-spigot** [comment]
Fixed
