### ISSUE TITLE
Telepathy Enchant Issue

### ISSUE THREAD

**Issue by BirminghamBoy** [GC-spigot/AdvancedEnchantments#1002]
**Describe the bug**
As reported by a smart player:
"when using the custom enchant "telepathy" it will give items u mine straight to your inventory, this is bugged as mining e.g green concrete gives you white concrete, same thing with terracotta and quarts "

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. Paper version git-Paper-136]
- Plugin Version [e.g. 7.4.3]

**Comment by GC-spigot** [comment]
Update
