### ISSUE TITLE
[Issue] Repair effect spawner dupe

### ISSUE THREAD

**Issue by clarkkentz** [GC-spigot/AdvancedEnchantments#1004]
**Describe the bug**
Spawner dupe with repair effect

**To Reproduce**
A way to reproduce the video
https://streamable.com/h7jdus

**Server Information (please complete the following information):**
 - Minecraft Version: 1.12.2, 1.15.2
- Plugin Version: 7.4.9-3

**Comment by GC-spigot** [comment]
Update
