### ISSUE TITLE
[Issue] cancel event

### ISSUE THREAD

**Issue by CryLegende** [GC-spigot/AdvancedEnchantments#1007]
**Describe the bug**
In minecraft, it is possible to equip an armor from its hotbar with a simple right click.
If another item is already in the helmet slot, it will be replaced.
On a server without AdvancedEnchantments, if another plugin cancel this event, the item is not replaced but with AE, even if the event is cancel by another plugin, the item will be replaced by the helmet.

**To Reproduce**
It is not reproducible without a plugin that cancels the event, but with it, just right click with a helmet in hand.

**Server Information**
- PaperSpigot 1.12.2
- AdvancedEnchantments 7.5.0-Pre7

Thank you for your help ! ^^

**Comment by GC-spigot** [comment]
Disable this https://prnt.sc/s9ly7h
