### ISSUE TITLE
Mobs not dropping Items when defined in Mobs.yml file

### ISSUE THREAD

**Issue by PhantumOne** [GC-spigot/AdvancedEnchantments#1009]
I have setup the Mobs.yml following the format specified in the comment section of the Mobs.yml file.

Here is my file in TXT format:

[mobs.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/4568159/mobs.txt)
 
I am not receiving any errors or warnings on the server or in-game when killing a mob and they are only dropping standard MC items when killed even though I have set all of them to a 100% chance to drop just to see if it was working. 

I am running PaperMC 1.15.2 R0-1 Build 234 with 6GB RAM dedicated to it and
94 Plugins: AdvancedEnchantments, AuctionHouse, AutomaticInventory, AutoPickup, Barrels, BeaconPlus2*, BeehivesPro, BetterShulkerBoxes, BKCommonLib, Brewery, ChestTerminal, ClayTech, ClearLag, ColoredEnderChests, CS-CoreLib, CustomCobbleGen, CustomEnderChest, DungeonsXL, DyedBackpacks, ElectricSpawners, Endrex, EntityTrackerFixer, EpicFarming, EpicFurnaces, EpicHoppers, EpicSpawners, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExoticGarden, ExtractableEnchantments, ExtraGear, ExtraHeads, ExtraToolsPlugin, FabledSkyBlock, GriefPrevention, GSit, GUIWarps, HolographicDisplays, HotbarPets, IronicChest, Jobs, JoinMessagePlus*, LightAPI*, LimitPillagers, LootChest, LuckPerms, MeteoritesPro, MobCapturer, MorphMining, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MySkin, PermissionShopZ, PickupArrows, PlaceholderAPI, PlayerListPlus*, PluginManager*, PrivateStorage, ProtectionLib*, ProtocolLib, QuickShop, RainbowsPro, Realistic-Swimming, ShinyItems, ShopGUIPlus, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimeXpansion, SlimyTreeTaps, SoulJars, SoundMuffler, TabuuCore, TCCoasters, Train_Carts, TridentCraft, UltimateFishing, UltimateKits, UltimateRepairing, UltimateStacker, UltimateTimber, Vault, VeinMiner, volcano, WhatIsThis, Wild, WorldEdit, WorldGuard, WorldSpawn*, XP-Deposit*

thanks

**Comment by GC-spigot** [comment]
Try ZOMBIE mob, it worked for me. It might be 'UltimateStacker' modifying drops for mobs or 'ElectricSpawners'

**Comment by PhantumOne** [comment]
I still can not get any drops from  a ZOMBIE except the standard rotted flesh.

I only have this in my mobs.yml file:

# You can give custom AE items when mobs are killed
# Item names must be same as from '/ae giveitem' command (for future references).

# Current items: whitescroll, renametag, blocktrak, stattrak, soultracker, mobtrak, transmog, randomenchantmentbook, secret:<amount>:<group>

# Format: '<item name>:<count>'

mobs:
  ZOMBIE:
    chance: 100
    items:
      - 'randomenchantmentbook:1'

And I am only running  15 Plugins : 
AdvancedEnchantments, 
Essentials, 
EssentialsAntiBuild, 
EssentialsChat, 
EssentialsProtect, 
EssentialsSpawn, 
LuckPerms, 
Multiverse-Core, 
Multiverse-Inventories, 
Multiverse-Portals, 
PermissionShopZ, (reqires TabuuCore)
TabuuCore, 
Vault, 
WorldEdit, 
WorldGuard

So I don't think it is another plugin causing the issue.

**Comment by PhantumOne** [comment]
I took more plugins out (Multiverse Core, Inventories, and Portals and as well as PermissionShopZ) leaving just your plugin and the basics (Essentials, LuckPerms, Vault, WorldEdit and WorldGuard) and your plugin still is not working.
