### ISSUE TITLE
Using Fireballs as enchant books

### ISSUE THREAD

**Issue by EwansXD** [GC-spigot/AdvancedEnchantments#1012]
Using latest AE (7.5.0-Pre10) and having an issue where fire charges can be used as actual fire charges if they are enchant books.

This was meant to be fixed a few versions ago but its still happening

I'm using stellarspigot 1.8.8

**Comment by GC-spigot** [comment]
Hah! Actually fixed the wrong thing by accident first time - the right-click books setting in config.yml was doing the same, now it's fixed with this as well.
