### ISSUE TITLE
[Issue] Advanced Enchants, auto smelt

### ISSUE THREAD

**Issue by SaltyDonuto** [GC-spigot/AdvancedEnchantments#1015]
**Describe the bug**
Whenever players hit a spawner with a pickaxe with Auto Smelt on it, a spawner just drops, without even having to break the 

here is a short clip of it happening on my server:
[epicenchantsbug.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/4578996/epicenchantsbug.zip)

spawner.

**To Reproduce**
A way to reproduce the video
Im using mineable spawners on my server but I'm not sure if that has anything to do with it

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.15.2]
- Plugin Version [7.5.0-Pre12]

**Comment by GC-spigot** [comment]
What spawner plugin are you using?

**Comment by SaltyDonuto** [comment]
MinableSpawners , that’s it
