### ISSUE TITLE
Unknown Warning relates to - Extra info: effect[TRENCH:3]; enchant [detonate]

### ISSUE THREAD

**Issue by EchocallingEarth** [GC-spigot/AdvancedEnchantments#1018]
**Describe the bug**
Warning in the console that seems to come and go for no reason. Points to Extra info: effect[TRENCH:3]; enchant [detonate]

Console report of warning only:
https://pastebin.com/eeTZNbCg

**IMPORTANT  - The issue occurred before we updated to this version and after. the log is the same and the cause remains unknown. We updated in hopes that it may have been fixed. Apparently we were incorrect.**

**To Reproduce**
Unknown as we can not find the source or reason for warning

**Screenshots / Video**
NA

**Server Information (please complete the following information):**
 - 1.15.2
 - Paper
 - AE 7.5.0-Pre13

**Comment by GC-spigot** [comment]
Should be fixed! Let me know via Discord PM if it's not in upcoming version.
