### ISSUE TITLE
Gkits Redemption Visual Glitch[Issue]

### ISSUE THREAD

**Issue by Samington** [GC-spigot/AdvancedEnchantments#1019]
**Describe the bug**
Redeem a gkit, let the cooldown happen. Look to redeem the gkti again and it says its locked but then when u click it, it redeems the kit.

**To Reproduce**
I tried it on GrimReaper kit.

**Screenshots / Video**
Can provide if needed

**Server Information (please complete the following information):**
 - Minecraft Version - 1.8.8
- Plugin Version Latest - Pre13

**Comment by GC-spigot** [comment]
If you could provide a video would be great - doesn't happen to me

**Comment by Samington** [comment]
It fixe

**Comment by Samington** [comment]
It fixed itself in one of the newer updates
