### ISSUE TITLE
[Issue] Player EXP value not updated

### ISSUE THREAD

**Issue by TechnoVisionDev** [GC-spigot/AdvancedEnchantments#1021]
**Description**
When a enchantment book is purchased from /ae enchanter, the player exp stat is not updated properly. This leads to exp placeholders from placeholderAPI and mvdwplaceholderapi being pretty much unfunctional! The placeholder seems to reset back to normal upon using a command like "/exp take 1".

I know this is an issue with AE and not the placeholder plugins because the problem exists across all placeholder plugins and seems to work fine with other custom enchant plugins. 

**To Reproduce**
Type /papi parse <name> %player_total_exp%
Buy a enchant book from /ae enchanter
Type /papi parse <name> %player_total_exp%
You will notice the value has remained the same

**Server Information (please complete the following information):**
 - Minecraft Version [Spigot 1.8.8]
- Plugin Version [7.5.0-Pre14]

**Comment by GC-spigot** [comment]
Fixed
