### ISSUE TITLE
Enchantments Creator Discussion

### ISSUE THREAD

**Issue by GC-spigot** [GC-spigot/AdvancedEnchantments#1023]
Hello, I'm in process of making an enchantments creator for AdvancedEnchantments, here is a sneak peek of it:
![Creator](https://i.imgur.com/xdZtTY8.png)
![Creator](https://i.imgur.com/jJbloFG.png)

This whole creator is web-based and will be accessible through a website.
As you can see only half is currently finished, conditions and effects creation is still work-in-progress. I will be adding these both before alpha release. All you can see is still work-in-progress and most likely will be changing around in the alpha.

I'm open to ideas so please let me know what else should be implemented or changed.

**Comment by SkriptDeveloper** [comment]
Great idea, Very useful for new buyers who are looking to make enchants easy and efficiently

**Comment by TechnoVisionDev** [comment]
This is amazing! Totally make this a next-level enchants plugin :D

**Comment by SkriptDeveloper** [comment]
> This is amazing! Totally makes this a next-level enchants plugin :D

it's already a next level enchant plugin

**Comment by blek-id** [comment]
Looks good, excited to see the next part of it

**Comment by EarthAgar** [comment]
I'm on my toes about this plugin lol, I'm planning to use it once I switch hosts and I seriously can't wait. It's crazy how I discovered this plugin like 5 days ago and I'm basically sold on everything about it.

**Comment by GC-spigot** [comment]
Some new updates on the progress
![](https://i.imgur.com/MEh00Me.gif)
![](https://i.imgur.com/FtgXefd.png)
![](https://i.imgur.com/dNuJliu.png)

**Comment by EarthAgar** [comment]
God i'm so excited I've been thinking of all the possibilities today and i'm getting really worked up XD

Help a brother out and DM me a possible time frame to ease the pain lol EarthAgar#8806

**Comment by SimplyHate23** [comment]
> Hello, I'm in process of making an enchantments creator for AdvancedEnchantments, here is a sneak peek of it:
> ![Creator](https://camo.githubusercontent.com/90e52d255638280063c4f6f480b8716be74026a0/68747470733a2f2f692e696d6775722e636f6d2f78645a745459382e706e67)
> ![Creator](https://camo.githubusercontent.com/efebe86d23f8b701d283c9933a909ede108fab12/68747470733a2f2f692e696d6775722e636f6d2f6a4a626c6f46472e706e67)
> 
> This whole creator is web-based and will be accessible through a website.
> As you can see only half is currently finished, conditions and effects creation is still work-in-progress. I will be adding these both before alpha release. All you can see is still work-in-progress and most likely will be changing around in the alpha.
> 
> I'm open to ideas so please let me know what else should be implemented or changed.

Where would we find that?

**Comment by ZubeySweet** [comment]
This is pretty amazing. Thank you for putting this level of effort in.

**Comment by EarthAgar** [comment]
I know it says to report issues here but this is also the discussion area, I strongly suggest a Dark Theme for a sensitive gamer eyes 😂
