### ISSUE TITLE
[Issue] Armor equip event on 1.15+ blocks applying potion effect

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#1024]
**Describe the bug**
When you have a piece of armor in hand such as boots with gears on it if you right click 1.15 / newer blocks like looms/lecterns/barrels the armour isnt equipped but the potion effect gets applied. So you can really just right click armour sets on a block and it will apply all their potion effects like speed and jump boost and you can store away the armour in enderchest or otherwise and run around with these potion effects until death or to re-equip the boots.

**To Reproduce**
Get boots (or any armour) with gears (or any potion effect enchant) put boots in hot bar > right click to equip boots whilst looking at a LOOM for example > potion effects applied but boots remain in inventory.

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version Paper Spigot 1.15.2
- Plugin Version 7.5.0-pre14.jar

**Comment by GC-spigot** [comment]
Fixed!
