### ISSUE TITLE
[Request] Ability to use all colored stained glass panes.

### ISSUE THREAD

**Issue by nolky** [GC-spigot/AdvancedEnchantments#1026]
** Describe the Request**

I want to be able to use multiple colors of stained glass panes, if possible of course.

**Comment by Samington** [comment]
You can? i am able to choose any pane i want

**Comment by GC-spigot** [comment]
Yeah it's possible, if you want to be more specific please open another issue. If you're using pre-1.13 you need to use 'data/damage' and with newer versions this works as well but you can use e.g. `GREEN_STAINED_GLASS_PANE`
