### ISSUE TITLE
[Request] Vanilla Enchant Support / Controll

### ISSUE THREAD

**Issue by EarthAgar** [GC-spigot/AdvancedEnchantments#1030]
** Describe the Request**

I have three main suggestions and request as they are pretty important to my server's idea and progression.

#1 Being able to define vanilla enchantments in the plugin. So in a sense allowing us to do the `/ae enchant <enchantment> <level>` command with vanilla enchantments too. Along with allowing us to define the max level like any other custom enchantment does. Reason for this is because my server will be using this command on users to purchase enchantment upgrades without allowing them to bypass our defined max level.

#2 Adding compatibility with the Player placeholder expansion. You could even just make your own similar Placeholders / Conditions (As you explained to me via Discord). The specific Condition i'm talking about is `%player_item_in_hand_level_<enchantment>%`.

#3 Add Repairing Enchanted Items, Upgrade Costs, and add a Refund Cost. I plan to use [MultiEconomy](https://www.spigotmc.org/resources/multieconomy.57245/) so support for that would be cool too but Vault support would make the most sense at the start.

Edit: Found TE's Placeholders that would also be pretty nice having in AE's functionality.
Replace `XXX` with the `enchantment`.

```
**%tokenenchant_XXX_level%**
**%tokenenchant_XXX_cost%**
**%tokenenchant_XXX_max%**
%tokenenchant_XXX_fullrefund% <-- Less Important
%tokenenthcnat_XXX_refund_Y% <-- Less Important
**%tokenenchant_repair_cost%**
**%tokenenchant_repair_cost_num%**
```

**This is a re-post as I never added any tags / labels to my old one. I'll be closing that one in a few moments from this post.**

**Comment by GC-spigot** [comment]
1st - completed.
2nd - added for next update

3rd - I'm not sure where to use these. Price is kind of the same for whole group, maybe level and max could only be properly added.
