### ISSUE TITLE
[Request] instead of exp using currency 

### ISSUE THREAD

**Issue by SirAltF4** [GC-spigot/AdvancedEnchantments#1031]
I would like to be able to use currency instead of exp to buy books in the enchanter and perform other, for example in the config atm there is a bit that says  price: exp:400 be able to change this to 
price: `Emerald`:10 or something similar 

Thank you hope this would be an easy fix or even link it into vault to allow currency 
Tom (SirAltF4)

**Comment by GC-spigot** [comment]
Added
