### ISSUE TITLE
[Request] Hide enchant levels

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#1032]
** Describe the Request**
It would be nice to add the option to format the enchantments differently / not use lore kind of like using max level 0. So instead of having "Gears I / Gears II" If i just wanted a fixed speed enchant for a special item it would be nice to apply gears to a bigger line of text without a I/II/III such as "Applies a mysterious speed boost" for example. Just that one line of text applied under the item as lore which in turn applies the speed effect. Of course this is possible now but the roman numerals have to follow in levels with a minimum being I. Hiding an items enchantments and applying an interesting description which applies an enchant would be nice to make legendary items in appearance / formatting, i'm not sure how possible this is to basically add the functionality to allow for a maximum level of 1 or 0 but 0 being no roman numerals following the enchantment name

**Comment by GC-spigot** [comment]
Added
