### ISSUE TITLE
[Issue] aegive command not displaying enchants

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#1035]
**Describe the bug**
the /aegive command with a unique name for the item and lore and enchants works perfectly except it doesn't display the custom AE enchants only vanilla. I realise this is likely a bug but at the same time i'd like to half feature request this and say it would be great to have the option to display/hide AE enchants using this give command so it could be a true/false statement to the command perhaps that toggles hiding or displaying them. This allows for flexability creating unique enchanted items without a long list of AE enchants on it so can make them appear more unique by having a name, lore and they can still function as custom enchanted item. Basically it would be nice to have a flag or way to hide the AE enchants on items.

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.5.2]
- Plugin Version [e.g. 7.5.0]

**Comment by GC-spigot** [comment]
Try the latest version, they show up fine.
