### ISSUE TITLE
Telepathy + AutoSmelt can get Spawner

### ISSUE THREAD

**Issue by blek-id** [GC-spigot/AdvancedEnchantments#1037]
**Describe the bug**
Having autosmelt enchant and telepathy will make spawner to be able to be taken into player's inventory

**To Reproduce**
In video

**Screenshots / Video**
https://imgur.com/a/dQMC3Mb

**Server Information (please complete the following information):**
- Minecraft Version: PaperSpigot 1.15.2 BUILD 273
- Plugin Version: 7.5.0-Pre20

I've attached a localhost server you can start and try for yourself (still need paper build 273)
--redacted--

**Comment by GC-spigot** [comment]
Fixed
