### ISSUE TITLE
New Triggers [Request]

### ISSUE THREAD

**Issue by vkolasa** [GC-spigot/AdvancedEnchantments#1039]
** Describe the Request**
Can we have some new triggers for some items like:
TRIDENT , TRIDENT_MOB , DEFENSE_TRIDENT , CROSSBOW , CROSSBOW_MOB , DEFENSE_CROSSBOW TRADE (triggered when a trade is done with a villager)
SUFFOCATION (Triggered when player takes drowning damage)
COOK (Cooks the drop caused by the item such as cooking a fish as you fish it up)
WALK (Enchant activates only when walking)
JUMP (Triggered when the player jumps)

**Comment by EarthAgar** [comment]
Yeah these are pretty good... Big +1 here 👍
