### ISSUE TITLE
[Issue] Empty description.

### ISSUE THREAD

**Issue by treyfex** [GC-spigot/AdvancedEnchantments#1041]
Hey, I have a problem with customcommands.yml
Some enchant's descriptions dont show up.
https://i.imgur.com/QbAzXqk.png
The enchant configuration:
shuffle:
  display: '%group-color%Shuffle'
  description: 'Shuffles opponent''s hotbar.'
  applies-to: 'Armor'
  type: 'DEFENSE'
  group: 'MASTERY'
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 5
      cooldown: 20
      effects:
        - 'RANDOMIZE_HOTBAR %attacker%'
    2:
      chance: 6
      cooldown: 18
      effects:
        - 'RANDOMIZE_HOTBAR %attacker%'
    3:
      chance: 8
      cooldown: 15
      effects:
        - 'RANDOMIZE_HOTBAR %attacker%'

**Comment by w41k3r26** [comment]
![image](https://user-images.githubusercontent.com/64218536/81629693-5dfe4d00-9421-11ea-9daa-f568ce5cdbca.png)
Use a statement:
lore:
  - "line1"
  - "line2"

**Comment by GC-spigot** [comment]
as I asked, pastebin.com your enchantments.yml and customcommands.yml files

**Comment by treyfex** [comment]
Enchantments.yml: https://pastebin.com/vc4zPkXQ
customcommands.yml: https://pastebin.com/MnyBQTMf

**Comment by GC-spigot** [comment]
Fixed
