### ISSUE TITLE
Can't remove enchant from MMOItems plugin (After 7.4.8)

### ISSUE THREAD

**Issue by blek-id** [GC-spigot/AdvancedEnchantments#1042]
**Describe the bug**
After the release of 7.4.9, I can no longer remove enchantments with black scroll if the item is an MMOItem. It's not all MMOItem though, only MMOItem with long lores, the one with no lores works fine.

**To Reproduce**
I don't know if you have MMOItem, but I can send you a config of the item in question that is having trouble, and the one with no problem. 

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.15.2
- Plugin Version 7.4.9

**Comment by GC-spigot** [comment]
Try updating, the newer versions are very reliable. Let me know if this happens on latest.

**Comment by blek-id** [comment]
Will be using pre26 as of writing this. Will report in a few hours (don't close yet)

**Comment by blek-id** [comment]
tried pre26, still happening.

**Comment by GC-spigot** [comment]
Can you PM me on Discord? GC#0830

**Comment by blek-id** [comment]
Sent you a friend request Blekdigits#7573

**Comment by GC-spigot** [comment]
Fixed
