### ISSUE TITLE
[Issue]Lapis has NBT tags when mined.

### ISSUE THREAD

**Issue by Geekmakes** [GC-spigot/AdvancedEnchantments#1044]
NBT tags on lapis after being mined with a Hephaestus pickaxe I'm assuming its detonate/auto smelt. 

![Screenshot (36)](https://user-images.githubusercontent.com/16181272/81761192-4eb9e680-9497-11ea-969f-01d63a83a85e.png)

papermc: 281
AdvancedEnchantments-7.5.0-Pre26

**Comment by GC-spigot** [comment]
Minecraft uses NBT internally, so a lot of items will have NBT right out of the box. I don't add NBT to broken items intentionally, maybe it's just minecraft's but it won't cause issues.
