### ISSUE TITLE
NullPointer when using empty hand with Reforged Enchant on an item

### ISSUE THREAD

**Issue by Skizzles** [GC-spigot/AdvancedEnchantments#1049]
Minecraft Version: Paper 1.15.2 latest
Plugin Version: 7.5.0-Pre26 (Occurs before Pre versions as well)

Title says it all:
https://screenshots.voidrealms.net/skizzles/fa8p1zzq.gif

Error
https://pastebin.com/79rThtj9

**Comment by GC-spigot** [comment]
Fixed
