### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by ColeRiggle** [GC-spigot/AdvancedEnchantments#1052]
**Describe the bug**
When using a custom enchanter menu, returning to the menu does not return a player to the custom menu, but rather to the default menu. This only seems to happen when on the second or third page.

**To Reproduce**
Create a custom menu. 
Go beyond the first page of enchantment listings.
Try to return to the menu.

**Screenshots / Video**
[![Screenshot from Gyazo](https://gyazo.com/623929760d2cb56131b694c862584e2b/raw)](https://gyazo.com/623929760d2cb56131b694c862584e2b)

**Server Information (please complete the following information):**
 - Minecraft Version: Spigot 1.14.4
- Plugin Version: 7.3.5

**Comment by GC-spigot** [comment]
Fixed
