### ISSUE TITLE
[Issue] NullPointer Spam

### ISSUE THREAD

**Issue by Skizzles** [GC-spigot/AdvancedEnchantments#1053]
**Describe the bug**
NullPointerException Spam

**To Reproduce**
https://screenshots.voidrealms.net/skizzles/m59iz8ud.png

**Screenshots / Video**
https://screenshots.voidrealms.net/skizzles/m59iz8ud.png

**Server Information (please complete the following information):**
 - Minecraft Version 1.15.2
- Plugin Version Pre32

**Comment by GC-spigot** [comment]
Fixed
