### ISSUE TITLE
[Request] New conditions

### ISSUE THREAD

**Issue by SimplyHate23** [GC-spigot/AdvancedEnchantments#1054]
** Describe the Request**
You should make no conditions for things like %if player is wearing leather% for heroic enchantments.

EX:
%if player is wearing leather% +2% attack% idk I'm not good with conditions but yeah

**Comment by SkellyBG** [comment]
Pretty sure since the plugin supports PAPI, you can add a lot of conditions, including the one you're requesting. (in this case the expansion cloud ARMOR, and %armor_material_slot%.
