### ISSUE TITLE
[Issue] Soul Bug

### ISSUE THREAD

**Issue by mannyseete** [GC-spigot/AdvancedEnchantments#1056]
**Describe the bug**
Souls do not decrease when buying enchantments that are have soul payment

**To Reproduce**
1. Get a Diamond Sword
2. Get a Soul Tracker
3. /ae giveitem <player> soulgem 1 250
4. Apply the Soul Gem
5. Do not put your Sword with soul onto your Player Hand
6. Purchase an Enchantment using Soul Payment.

**Screenshots / Video**
I'll upload it in a few minutes, as the internet here is really slow.

**Server Information (please complete the following information):**
- PaperSpigot 1.8.8
- Plugin Version 7.5.0-Pre33

**Comment by GC-spigot** [comment]
Fixed
