### ISSUE TITLE
Excavation Error [Issue]

### ISSUE THREAD

**Issue by FeroxDrood** [GC-spigot/AdvancedEnchantments#1057]
**Describe the bug**
Excavation sometimes throws this error into console

**Screenshots / Video**
https://pastebin.com/68ScMcrZ

**Server Information (please complete the following information):**
- Paper Spigot 1.15.2 build 284
- AdvancedEnchantments-7.5.0-Pre33.jar

**Comment by GC-spigot** [comment]
Fixed
