### ISSUE TITLE
[Issue] Custom Weapon issue

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#1058]
**Describe the bug**
States the weapon is invalid if you do not include the "Events: ATTACK / Chance" system. It would be nice to allow for all types of normal enchanted weapons to allow to be given through the /asets command and not just custom event based ones

**To Reproduce**
Remove Events on custom weapons

**Server Information (please complete the following information):**
 - Minecraft Version [1.15.2]
- Plugin Version [latest]

**Comment by GC-spigot** [comment]
Added
