### ISSUE TITLE
[Issue] Secret Dust mob drop reward not picking up on group name/color

### ISSUE THREAD

**Issue by rocky143** [GC-spigot/AdvancedEnchantments#1061]
**Describe the bug**
The bug is that you get Secret Dust upon killing the mob and the item name isn't picking up on the group color and group name placeholder.
Only happening to secret dust, all other items work fine.
I used the right format and the item is being dropped, just the name is not working. Lore is working just fine and there are no errors in console as well.
Format I am using:
```
  ZOMBIE:
    chance: 75
    items:
      - 'secret:1:elite'
```

**To Reproduce**
Just try secret in mobs.yml and you will see.

**Screenshots / Video**
![image](https://i.gyazo.com/390ea041d08eed786dea6bbf07ca9b97.png)

**Server Information:**
 - Minecraft Version [e.g. PaperSpigot 1.15.2]
- Plugin Version [e.g. 7.5.0-Pre35]

**Comment by GC-spigot** [comment]
Fixed
