### ISSUE TITLE
Battlepass plugin support [Request]

### ISSUE THREAD

**Issue by Vehzx** [GC-spigot/AdvancedEnchantments#1065]
** Describe the Request**
Hello, on my server (and i'm sure many others use it too) I use the Battlepass plugin. I would like to put a suggestion out there where we can make battlepass missions with advancedenchantments.

For example, a mission could be "Enchant a weapon or armor piece with this tier of enchant"
Or, "Get this specific enchantment on a piece of armor / weapon".

They have an API page for Battlepass here:
https://github.com/Hyfe-JavaDebug/battle-pass-wiki/wiki/Implementing-the-API

If this would be possible i'm sure many would find good use in this, thanks!

**Comment by GC-spigot** [comment]
That sounds like something battle pass should add not me.
