### ISSUE TITLE
Detonate & Atomic Detonate don't lose durability. [Issue]

### ISSUE THREAD

**Issue by Vehzx** [GC-spigot/AdvancedEnchantments#1066]
**Describe the bug**
Using detonate or atomic detonate on a pickaxe makes the pickaxe never lose durability.

**To Reproduce**
Put either enchantment on the pickaxe and mine, the durability never goes down.

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version [paper-214]
- Plugin Version [e.g. 7.5.0-pre38]

**Comment by GC-spigot** [comment]
Fixed
