### ISSUE TITLE
Trench Dupe Glitch[Issue]

### ISSUE THREAD

**Issue by FeroxDrood** [GC-spigot/AdvancedEnchantments#1067]
**Describe the bug**
Add Silktouch and Trench onto a pickaxe and mine either lapis ore or redstone ore and you will get more than what you mined, I mined 8 redstone ore and got given 23 in return

**To Reproduce**
https://www.youtube.com/watch?v=g1GpyWeg70M&feature=youtu.be

**Server Information (please complete the following information):**
- Paper 1.15.2 298
- AdvancedEnchantments-7.5.0-Pre38.jar

**Comment by GC-spigot** [comment]
Fixed
