### ISSUE TITLE
[Issue] Reload and Placeholder bugs

### ISSUE THREAD

**Issue by mannyseete** [GC-spigot/AdvancedEnchantments#1069]
**Describe the bug**
/ae reload - Doesn't refresh configs it's still the same even when changing
%souls% - Missing, was it gone or removed?
%left% - Doesn't work with Soul as a Primary Currency

**To Reproduce**
/

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/25744238/82208437-16565480-993e-11ea-8c4f-8b59b936c3ad.png)
![image](https://user-images.githubusercontent.com/25744238/82208462-21a98000-993e-11ea-8f1b-ce57ad07d682.png)

**Server Information (please complete the following information):**
PaperSpigot 1.8.8
Plugin Version 7.5.0-Pre33

**Comment by GC-spigot** [comment]
/ae reload - shows a warning once used in chat that it only reloads enchantments and some config values, not everything.
%left% only works with EXP at the moment
