### ISSUE TITLE
KillAura enchant spams console

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#1071]
**Describe the bug**
KillAura enchant spams the console once it actives, I'll post the screenshot below

**To Reproduce**
Obtain killaura enchant and kill mobs till the effect happens then check console for errors

**Screenshots / Video**
https://gyazo.com/013f8dc00191d5cd85301542852d17f5

**Server Information (please complete the following information):**
 - Minecraft Version [StellarSpigot 1.8]
- Plugin Version [7.5.0-Pre9]

**Comment by GC-spigot** [comment]
Update
