### ISSUE TITLE
Obsidian Breaker not working

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#1072]
**Describe the bug**
Obsidian Breaker not instantly breaking obsidian even with 100% chance, config is posted below.

**To Reproduce**
Obtain Obsidian Breaker enchant and set to 100% chance and the obsidian won't instantly break

**Screenshots / Video**
https://gyazo.com/a740b17fc7d8cf83a0a5527563bc26e5

**Server Information (please complete the following information):**
 - Minecraft Version [StellarSpigot 1.8]
- Plugin Version [7.5.0-Pre9]

**Comment by GC-spigot** [comment]
It's temporary removed until fixed
