### ISSUE TITLE
[Issue] After right click with ender eye (orb)

### ISSUE THREAD

**Issue by ArcadeFighter** [GC-spigot/AdvancedEnchantments#1073]
**Describe the bug**
When you have ORB as ender eye item and right click, ender eye goes up and trying to find end portal.

**To Reproduce**
Right click with orb (needs to be ender eye)

**Server Information (please complete the following information):**
 - Minecraft Version: Paper 1.12.2
- Plugin Version: 7.5.0-Pre44

**Comment by GC-spigot** [comment]
Fixed
