### ISSUE TITLE
Autosmelt does not work with telepathy

### ISSUE THREAD

**Issue by Vehzx** [GC-spigot/AdvancedEnchantments#1075]
**Describe the bug**
If you have telepathy and autosmelt on the same pickaxe, it doesn't auto smelt ores when telepathy puts them into your inventory, it just gives the ore itself into your inventory.

**To Reproduce**
Enchant a pickaxe with the above enchants, mine.

**Screenshots / Video**

**Server Information (please complete the following information):**
Plugin version 7.5.0-Pre46
Paper verison git-paper-214 for 1.15.2

**Comment by Flirtey** [comment]
Testing this out to try and help confirm bugs, I am not able to replicate this one.

Telepathy 4: Iron Ore goes in inventory

Auto-Smelt 3: Iron Ingot drops

Both: Iron ingot goes in inventory

**Comment by Vehzx** [comment]
Again, very strange, on my other post about the inventory being filled fully and telepathy not dropping the blocks, I sent a google drive link with my AE folder, I will link the same here.

Also just to be certain I will link a screenshot of the exact enchantments I have on the pickaxe that is causing this.

My AdvancedEnchantments folder:
https://drive.google.com/open?id=1vegIcOKJrn4B_GK9E4JWWC0XzBhzidKV

Pickaxe to use:
https://i.gyazo.com/9971081d1aab7f6b22a70a296c4fc11d.png

**Comment by Vehzx** [comment]
Another update, using the exact pickaxe and my setup I gave in the folder above, It seems to only give coal ore in the ore form? Iron ore smelts fine and goes to the inventory etc, but coal ore seems to get dropped to the inventory in the ore form instead of just coal.

Which is strange considering you don't need autosmelt to get coal from the coal ore

**Comment by GC-spigot** [comment]
Fixed
