### ISSUE TITLE
Telepathy enchant not dropping blocks when full inventory [Issue]

### ISSUE THREAD

**Issue by Vehzx** [GC-spigot/AdvancedEnchantments#1076]
**Describe the bug**
When you have the telepathy enchant, and have a full inventory, the blocks you mine are just deleted since it has no space to move the mined blocks.

Not sure how to work around this maybe if inventory is full it just drops blocks like usual?

**To Reproduce**
Fill inventory full, mine with telepathy enchant.

**Screenshots / Video**

**Server Information (please complete the following information):**
Plugin version 7.5.0-Pre46
Paper verison git-paper-214 for 1.15.2

**Comment by Flirtey** [comment]
Unable to replicate, block drops on ground as you suggested already.

**Comment by Vehzx** [comment]
Strange, this could be another plugin causing it maybe, but just to be sure, I'll attach my AdvancedEnchantments folder and a picture of the exact pickaxe it is happening on.

At first I just assumed it was telepathy, but it seems this exact pickaxe is causing it.

My AdvancedEnchantments folder:
https://drive.google.com/open?id=1vegIcOKJrn4B_GK9E4JWWC0XzBhzidKV

Pickaxe to use:
https://i.gyazo.com/9971081d1aab7f6b22a70a296c4fc11d.png

**Comment by GC-spigot** [comment]
Fixed
