### ISSUE TITLE
[Issue] /enchanter (<starting slot>-<ending slot>) Internal Error

### ISSUE THREAD

**Issue by UltimqteGames** [GC-spigot/AdvancedEnchantments#1077]
**Describe the bug**
The new update "Added ability to set enchanter inventory items using `0-8`" doesn't work and displays an internal error when executing /enchanter, the error can be found below

**To Reproduce**
Use default, freshly generated files/configurations

**Screenshots / Video**
https://paste.md-5.net/puhateyapi.bash

**Server Information (please complete the following information):**
 - Minecraft Version: StellarSpigot 1.8.8 (TacoSpigot Fork)
 - Plugin Version: 7.5.0-Pre49

**Comment by GC-spigot** [comment]
Fixed!
