### ISSUE TITLE
Enchantments Not Triggering [Issue]

### ISSUE THREAD

**Issue by ShapedHades** [GC-spigot/AdvancedEnchantments#1078]
**Describe the bug**
When the item is enchanted, both through command and legitimate methods of using the enchanter; the enchantment does not trigger. I read the configs and such to see if it might be me, but I can't find anything. Are there perms for the enchant to trigger?

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.15.2]
- Plugin Version [e.g. 1.9.11]

**Comment by Flirtey** [comment]
Not enough information? Do you have specific enchants working or not working? I'm on a default buuild on 1.15.2 on latest versions and its working fine.

**Comment by ShapedHades** [comment]
It appears to be the trigger on event enchants. Like the if health is low; event triggered. I haven't been able to get the rocket escape or any of the spawn mobs if health is low armors. Sorry for lack of information, I'm new to the plugin and configs in general. What information would help?

**Comment by GC-spigot** [comment]
No perms, most enchants work on players only so take that into consideration along with them having chances / cooldowns
