### ISSUE TITLE
[Issue] Known Bugs

### ISSUE THREAD

**Issue by mannyseete** [GC-spigot/AdvancedEnchantments#1080]
**Describe the bug**
Soul Count doesn't work
Soulbound Enchantment doesn't work
Blackscroll on enchantment that has "Removable: false" can still be black scrolled.

Add feature for black scroll
If players removed the enchantment that has a requirement they should also get the pre-requisite enchantments

**To Reproduce**
/

**Screenshots / Video**
/

**Server Information (please complete the following information):**
PaperSpigot 1.8.8
Plugin Version 7.5.0-Pre33

**Comment by GC-spigot** [comment]
1st - Soul count? Not sure what that is, but assuming it's collecting souls with weapons - https://prnt.sc/sm00bb works when killing players
2nd - Soulbound works on armor & held item only
3rd - removeable: false works, https://prnt.sc/sm01il, https://prnt.sc/sm01o3 
make sure to put it under settings
