### ISSUE TITLE
[Enchantments Can Kill People In Creative]

### ISSUE THREAD

**Issue by ItsNoWorry** [GC-spigot/AdvancedEnchantments#1081]
**Describe the bug**
Damaging enchantments can kill people in creative or even in /god and it's allowing a dupe on my server with our printer plugin.

**Server Information (please complete the following information):**
 - Minecraft Version [Stellar Spigot]
- Plugin Version [7.5.1]

**Comment by GC-spigot** [comment]
Fixed
