### ISSUE TITLE
Enchantments Not Triggering [Issue]

### ISSUE THREAD

**Issue by ShapedHades** [GC-spigot/AdvancedEnchantments#1082]
**Describe the bug:**
Don't Mean To Be Burden, But This Is The Only Help Resource I know Of...
When the item is enchanted, both through command and legitimate methods of using the enchanter; the enchantment does not trigger. I read the configs AGAIN to see if it might be me, but I can't find anything. I've been using rocket escape as my test enchant, and the guided version as well. Every test I have done from the day of download has taken into consideration the cool down and percentage of occurrence. The enchants don't trigger and nothing appears in my console saying why it won't. The status effect enchants such as the ones that give you extra hearts and regeneration from the pre-made kits, work. I just can't get an enchant with a 70% chance and a 5 second cool-down to trigger and I track my death count on tests to see how many times I die. (I have lore weapons on my server and it helps with enchant trigger percent balance) I have died 67 times with this enchant, using various methods all from another admin to simulate PvP. I can leave a full list of plugins and a link to every config I have. I just want it to work. If there is a direct help line, I can use that instead of the forum...

**Server Information:**
Minecraft Version [e.g. PaperSpigot 1.15.2]
Plugin Version [e.g. 1.9.11]

**Comment by GC-spigot** [comment]
Add me on Discord GC#0830

**Comment by ShapedHades** [comment]
THANK YOU!!!!
