### ISSUE TITLE
No durability loss (cant figure out exactly why).

### ISSUE THREAD

**Issue by Vehzx** [GC-spigot/AdvancedEnchantments#1084]
**Describe the bug**
When mining with the pickaxe setup shown, it never loses durability.

**To Reproduce**
Enchant a pickaxe exactly as show in the screenshot (will provide my AE folder to try help replicate for you guys).

**Screenshots / Video**
Create this pickaxe, then mine: https://i.gyazo.com/9971081d1aab7f6b22a70a296c4fc11d.png
My AE folder: https://drive.google.com/open?id=1vegIcOKJrn4B_GK9E4JWWC0XzBhzidKV

**Server Information (please complete the following information):**
 - Minecraft Version [git-Paper-308]
- Plugin Version [ver 7.5.2]

**Comment by GC-spigot** [comment]
Fixed
