### ISSUE TITLE
[Issue] Buggy Inventory Equipping & Unquipping Armor

### ISSUE THREAD

**Issue by UltimqteGames** [GC-spigot/AdvancedEnchantments#1085]
**Describe the bug**
Equipping and unequipping armor is a bit buggy and sometimes teleports the armor back into your inventory, right-clicking the armor to equip from your Hotbar works fine, however, shift-clicking and drag n' dropping armor into your armor slots is buggy

**To Reproduce**
Not sure how to specifically reproduce this inventory bug

**Screenshots / Video**
With AE Loaded: https://gyazo.com/6af4de92200110a2a184363def4c399c
With AE Unloaded: https://gyazo.com/99ab4dce06d0fe30edc999a6f25ee38e

**Server Information (please complete the following information):**
 - Minecraft Version: StellarSpigot 1.8.8 (TacoSpigot Fork)
- Plugin Version: 7.5.4

**Comment by GC-spigot** [comment]
I'm aware of this, however this is just cooldown for reapplying armor as equipping it too quick may cause potion effects to stay permanently, I'll work on improving it.

**Comment by haeiven** [comment]
Having the same issue. Any news?

Best regards,
