### ISSUE TITLE
Lucky enchant instantly killing the player

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#1086]
**Describe the bug**
I was making a customized armor set with loads of enchants and when I put lucky on I noticed that I kept dying each time the lucky effect occured (the person who has the lucky enchant will get insta killed) I was using lucky X and when I disabled the enchantment this issue stopped occuring

**To Reproduce**
Get someone to hit you when you have Lucky X on and when the lucky effect goes off you will be instantly killed

**Screenshots / Video**
https://gyazo.com/c6268888240c1cea330132572bcffffa << This was after just one hit

**Server Information (please complete the following information):**
 - Minecraft Version [StellarSpigot 1.8]
- Plugin Version [7.5.0-Pre9]

**Comment by GC-spigot** [comment]
Lucky has been removed quite a bit time ago from default set up
