### ISSUE TITLE
SoulBound Enchant rework [Request]

### ISSUE THREAD

**Issue by jj136975** [GC-spigot/AdvancedEnchantments#1088]
The soulbound enchantment is a good idea but isn't working as expected... I mean it would be way better if we could keep a soulbound enchanted item not only if equiped or help, in the entire inventory.

 The second problem is that the enchantment itself isn't working nice. Some times, the player don't get back the item on death (with 100% chance) or if he disconnect on death, he don't respawn with the item.

**Comment by GC-spigot** [comment]
Reworked
