### ISSUE TITLE
[Issue] OR conditions does not work

### ISSUE THREAD

**Issue by SkellyBG** [GC-spigot/AdvancedEnchantments#1091]
**Describe the bug**
In condition section of an enchantment, OR statements does not activate the second clause, or breaks the enchants

**To Reproduce**
https://hastebin.com/raw/ukuhoqebeq
The related enchantments.

**Screenshots / Video**
https://imgur.com/a/YgcfRGN
https://streamable.com/deaz43

**Server Information (please complete the following information):**
- Minecraft Version: Waterfall-Bootstrap:1.15-SNAPSHOT:e0795ab:341
- Plugin Version: 7.5.8

**Comment by GC-spigot** [comment]
Fixed
