### ISSUE TITLE
[Issue] Applying blackscroll on non-tool/armor item

### ISSUE THREAD

**Issue by SkellyBG** [GC-spigot/AdvancedEnchantments#1092]
**Describe the bug**
Blackscroll (and possibly slot increasers) can't be used on non-tool/armor items

**To Reproduce**
https://hastebin.com/raw/erixelexom
Apply this on a fishing rod and attempt to use a blackscroll on the rod
**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version: Waterfall-Bootstrap:1.15-SNAPSHOT:e0795ab:341
- Plugin Version: 7.5.8

**Comment by GC-spigot** [comment]
You need to edit this in config.yml to add `FISHING_ROD` material https://prnt.sc/so2pw1
