### ISSUE TITLE
Error CROSSBOW

### ISSUE THREAD

**Issue by ducdzz61** [GC-spigot/AdvancedEnchantments#1093]
link: https://pastebin.com/xHrdCc2F
pls fix, It happened 3-4 today already. please help
It spams constantly !!

**Comment by ducdzz61** [comment]
part 2: https://pastebin.com/Pgj2v38v

**Comment by ducdzz61** [comment]
https://pastebin.com/r6LdSZFZ

**Comment by GC-spigot** [comment]
Fixed
