### ISSUE TITLE
Yijki Armor set broken

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#1094]
**Describe the bug**
The passive ability of 30% damage reduction is broken. I've done multiple tests and when I remove this ability I am actually able to deal damage, even if I reduce to this: NEGATE_DAMAGE:1 the player takes 0 damage from all hits, only time they take damage is when the armor breaks. I have also tried lowering the chance for this ability to proc to 5% but it seems to appears every hit. 

**To Reproduce**
Apply Yijki set and take loads of damage from someone with an op sword and the expected outcome would be you take 0 damage

**Screenshots / Video**
https://gyazo.com/f6fc92d1b658bc57c678faecea1ebfdc

^^ Each time the ability went off I made it so that message displays and I don't take any damage

**Server Information (please complete the following information):**
 - Minecraft Version [StellarSpigot 1.8]
- Plugin Version [7.5.11]

**Comment by GC-spigot** [comment]
Fixed
