### ISSUE TITLE
[Issue] Armor Sets Regenerating

### ISSUE THREAD

**Issue by UltimqteGames** [GC-spigot/AdvancedEnchantments#1095]
**Describe The Bug**
I can't delete the default armor sets in the armorSets folder, they keep regenerating whenever the plugin enables.

**To Reproduce**
delete Phantom.yml, restart the server and it'll regenerate

**Screenshots / Video**
Self-Explanatory

**Server Information (please complete the following information):**
 - Minecraft Version: StellarSpigot 1.8.8 (TacoSpigot Fork)
 - Plugin Version: 7.5.13

**Comment by GC-spigot** [comment]
Changed
