### ISSUE TITLE
[Issue] Enchantments not working

### ISSUE THREAD

**Issue by Alp1352** [GC-spigot/AdvancedEnchantments#1096]
**Describe the bug**
Some enchantments are not working, like Death Bringer / Planetary Death Bringer. It sometimes say an error message about CURE and some other stuff, but I couldn't get a screenshot of them.

**To Reproduce**
Just try to use Death Bringer, it just doesn't work. I will try to make a few more tests to see If I can get more screenshots of it, as I don't think you will be able to reproduce it.

**Screenshots / Video**
I have one, but I am not sure if its the correct one - I only managed to catch one errors in the console, so I am gonna post it here. [https://imgur.com/a/ZPvaW4I](url)

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. Spigot 1.8.8]
- Plugin Version [7.5.8]

**Comment by GC-spigot** [comment]
Death Bringer and Planetary version of it works - confirmed just a second ago. Just make sure to take in mind that most enchants are PVP only.
If you find the errors about CURE please let me know :)
