### ISSUE TITLE
[Issue] Crossbow detected in 1.8 with DEFENSE_BOW

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#1097]
**Describe the bug**
Error in console with DEFENSE_BOW on 1.8

**To Reproduce**
Send an arrow on a player wearing a DEFENSE_BOW arrow

**Screenshots / Video**
https://paste.soleria.eu/pegemerupu.sql

![image](https://user-images.githubusercontent.com/11612016/83140786-eaca2b80-a0ee-11ea-99ee-537eb04fabd8.png)

**Server Information (please complete the following information):**
 - Minecraft Version: Paper 1.8.8
- Plugin Version: 7.5.16

**Comment by GC-spigot** [comment]
Fixed
