### ISSUE TITLE
[Issue] Offhand bow effects do not function

### ISSUE THREAD

**Issue by FuneralShoots** [GC-spigot/AdvancedEnchantments#1099]
**Describe the bug**
When a bow has an enchantment that gives effects nothing happens if the bow is fired from the offhand

**To Reproduce**
Enchant a bow with a custom enchantment (Like Snare) then fire it at someone from your offhand, the effects will not be given to the person shot

**Server Information (please complete the following information):**
PaperSpigot 1.15.2
AE 7.5.17

**Comment by GC-spigot** [comment]
Not supposed to now, support is pending for it because a lot of the plugin has to be reworked to make this work

**Comment by FuneralShoots** [comment]
Is there a estimated time when I could be expecting it to be patched?
Weeks, months? I run a pvp arena style server and in a pvp setting bows are almost always used in the offhand slot.
