### ISSUE TITLE
[Issue] Block trak don't work if no mining enchants are in the config

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#1100]
**Describe the bug**
Block trak don't work if no mining enchants are in the config

**To Reproduce**
Remove all enchants related to mining in the enchantments list

**Screenshots / Video**
/

**Server Information (please complete the following information):**
- Minecraft Version: Paper 1.8.8
- Plugin Version: 7.5.16

**Comment by GC-spigot** [comment]
Fixed
