### ISSUE TITLE
[Issue] %damaged from behind% condition seems to not work 

### ISSUE THREAD

**Issue by FuneralShoots** [GC-spigot/AdvancedEnchantments#1101]
**Describe the bug**
%damaged from behind% condition seems to not work whatsoever, when the condition is used it always returns nothing.

**To Reproduce**
I was attempting to make the following enchant that deals double dmg from behind:

> backstabber:
  display: '%group-color%Backstabber'
  description: 'Double damage from behind'
  applies-to: 'Weapons'
  group: 'LEGENDARY'
  type: 'ATTACK'
  applies:
    - 'ALL_SWORD'
  levels:
    '1':
      chance: 100
      cooldown: 0
      condition: '%damaged from behind% != TRUE : %stop%'
      effects:
        - 'DOUBLE_DAMAGE'
        - 'BLOOD %victim%'

The enchantment works perfectly when `condition: '%damaged from behind% != TRUE : %stop%'` is removed. It also does not work whatsoever with `condition: '%damaged from behind% = TRUE : %allow%'`

**Server Information (please complete the following information):**
1.15.2 PaperSpigot
AE v.7.5.19

**Comment by GC-spigot** [comment]
Sadly have to remove this for the time being, will re-add it when it's possible for me
