### ISSUE TITLE
Auto Smelt Ignores Unbreaking[Issue]

### ISSUE THREAD

**Issue by Ashinos** [GC-spigot/AdvancedEnchantments#1102]
**Describe the bug**
Autosmelt steadily uses 1-2 durability with every block broken regardless of the unbreaking levels on a pickaxe.

**To Reproduce**
Use a pickaxe with Autosmelt and unbreaking, it will ignore the unbreaking enchantment.

**Server Information (please complete the following information):**
- Paper 1.15.2
- Plugin Version 7.5.14

**Comment by GC-spigot** [comment]
Fixed
