### ISSUE TITLE
enchantement menu spam message

### ISSUE THREAD

**Issue by Bricec6** [GC-spigot/AdvancedEnchantments#1104]
**Describe the bug**
When I'm in the enchantment menu and I go back, the message in the chat is always displayed and spam the chat

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/51750055/83332749-2efb2e80-a29d-11ea-8d5d-4d3f1ed80cf1.png)
on back to main menu
![image](https://user-images.githubusercontent.com/51750055/83332774-5225de00-a29d-11ea-9a4b-39b19cad72e2.png)
(retour = back)
![image](https://user-images.githubusercontent.com/51750055/83332783-5f42cd00-a29d-11ea-8bed-d9276692f696.png)
![image](https://user-images.githubusercontent.com/51750055/83332784-6669db00-a29d-11ea-9cce-a73b3a0fb30c.png)

**Server Information (please complete the following information):**
- Server 1.15.2
- AdvancedEnchantments-7.5.1

**Comment by GC-spigot** [comment]
Share your customcommands.yml file (paste it on http://pastebin.com)

**Comment by Bricec6** [comment]
https://pastebin.com/jiQWvTsr

**Comment by GC-spigot** [comment]
That config does not correspond to messages displayed in screenshots and Im unable to recreate this

**Comment by Bricec6** [comment]
Sorry, is here, missing file
https://pastebin.com/GCSWy5KV

I ended up taking the message out by putting it on:
  Message: []
