### ISSUE TITLE
Auto Smelt Duping Ores[Issue]

### ISSUE THREAD

**Issue by Ashinos** [GC-spigot/AdvancedEnchantments#1106]
**Describe the bug**
Breaking an ore with an Auto Smelt Pickaxe will drop stacks of the ore broken

**To Reproduce**
Use an Auto Smelt Pickaxe and mine an ore

**Server Information:**
 - Paper 1.15.2
- Latest

**Comment by GC-spigot** [comment]
Should be fixed
