### ISSUE TITLE
[Issue] Server Crashing Errors

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#1107]
**Describe the bug**
Not sure what the bug is, but I believe it got to do with mining related event

**To Reproduce**
Use a pickaxe to mine, read the console errors.
https://pastebin.com/Xq7X7L77
https://pastebin.com/NGPvHV4z

**Screenshots / Video**
1. https://discordapp.com/channels/537756896606814258/701820848805511189/716502963840876564
2. https://www.youtube.com/watch?v=dNqq6OnxSzE&feature=youtu.be

**Server Information (please complete the following information):**
 - Minecraft Version: 1.15.2 PaperSpigot (328)
- Plugin Version: 7.6.4

**Comment by BboyZeroOne** [comment]
1. Crash exist even on version 7.6.0
2. Not tested on 7.5.19
3. Non-crash version on 7.5.18

**Comment by GC-spigot** [comment]
Seems like it's related to your server only, possibly something else clashing with trench, try the new update and let me know

**Comment by BboyZeroOne** [comment]
Still happens on latest version.

https://pastebin.com/SpYfSYqn

**Comment by GC-spigot** [comment]
This is purely mcmmo issue, what version of it are you using? With my tested one there's no issues

**Comment by BboyZeroOne** [comment]
Issue still exist on 1.15.2 Paper-322 on latest version of AE v7.6.14
https://pastebin.com/YzZNbqzE

@GC-spigot
