### ISSUE TITLE
[Request] Next page of list enchantments

### ISSUE THREAD

**Issue by Bricec6** [GC-spigot/AdvancedEnchantments#1109]
** Describe the Request**
Hello I saw that it was impossible to disable the next page, and previous page of the list of enchantments, would it be possible to make it so that if there is not a lot of enchantment as on the screenshot the next and previous page disappear?

![image](https://user-images.githubusercontent.com/51750055/83361348-9e9a1800-a388-11ea-8a0a-7ffee2a76cb7.png)

thank you!

**Comment by GC-spigot** [comment]
Yes! Added
