### ISSUE TITLE
[Issue] Auto Smelt Durability Issue 

### ISSUE THREAD

**Issue by Ashinos** [GC-spigot/AdvancedEnchantments#1111]
**Describe the bug**
Unfortunately the fix didn't work again. Autosmelt steadily uses 1-2 durability with every block broken regardless of the unbreaking levels on a pickaxe.

**To Reproduce**
Use a pickaxe with Autosmelt and unbreaking, it will ignore the unbreaking enchantment.

**Server Information (please complete the following information):**

Paper 1.15.2
Plugin Version 7.6.8

**Comment by GC-spigot** [comment]
It never did 2 durability damage, only 1. Now it has a chance of not doing that damage.
