### ISSUE TITLE
[Issue] Placeholder %list-of-items% show bad information

### ISSUE THREAD

**Issue by ArcadeFighter** [GC-spigot/AdvancedEnchantments#1113]
**Describe the bug**
Placeholder %list-of-items% show bad items via screen.

**To Reproduce**
Open custom commands menu (/enchants) and open info of enchantment

**Screenshots / Video**
http://prntscr.com/srtb4u

**Server Information:**
 - Minecraft Version: Paper 1.12.2
- Plugin Version: 7.6.9

**Comment by GC-spigot** [comment]
That's sadly how it works because it's more of a system to support all cases rather than specific ones, I'd just recommend not using the placeholder (will remove it from default set up)
