### ISSUE TITLE
[Request] Remove roman numerals for 1-level custom enchantments.

### ISSUE THREAD

**Issue by RheinmetallDev** [GC-spigot/AdvancedEnchantments#1114]
** Describe the Request**
Minecraft removed roman numerals for 1-level enchantments like Infinity and Silk Touch. If the same thing were possible as a changeable option (so it doesn't conflict with old versions) in the config for CEs, it would look more uniform with vanilla enchantments.

**Comment by GC-spigot** [comment]
Already possible (search for 'showFirstLevel' in config.yml)
