### ISSUE TITLE
[Request] Translate (This item has 0 enchantments)

### ISSUE THREAD

**Issue by Bricec6** [GC-spigot/AdvancedEnchantments#1115]
** Describe the Request**
Hello, I'm French and I'd like to translate the sentence below into a picture, except that it can't be found in the black-scroll category. It happens when you put a black-scroll on an item... Thanks u very much
![image](https://user-images.githubusercontent.com/51750055/83451465-4bdb6180-a457-11ea-930c-be0f775cd06c.png)

**Comment by GC-spigot** [comment]
Added!
