### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by IsiDabat** [GC-spigot/AdvancedEnchantments#1116]
**Describe the bug**
I have a problem with the advancement enchantments plugin,
when players have fly boots equipped and right-click others in the inventory they double, and can continue to fly without wearing them

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.12.2]
- Plugin Version [7.6.14]

If it is possible to communicate any progress through my discord IsiDabat#0595 
Thanks!

**Comment by GC-spigot** [comment]
Unable to reproduce this, provide a video please
