### ISSUE TITLE
[Request] Add Levels to an Item with AE Enchant command

### ISSUE THREAD

**Issue by EarthAgar** [GC-spigot/AdvancedEnchantments#1118]
** Describe the Request**

You could add a `/ae enchant add Detonate <level increment>` command or something similar like maybe `/ae enchant Detonate 1 add` argument? We could then add X amount of levels to the held item and if the amount goes over the max then we can simply deny it. Here is the video for TE https://youtu.be/3e0YhoBgCqU

Im doing my best to make my own version of the plugin from the video with AE. If anyone would like to make this custom for me let me know please.

Discord Tag: EarthAgar#8806

**Comment by GC-spigot** [comment]
Few logical problems:
How do you know if it goes over the max? Apart from a custom system, this is not possible with commands only.
That command format means it's player-sided and would require the upgrading user running it, again not good.

I really like this idea but not possible at the moment, if you are interested in a custom addon however feel free to add me on Discord GC#0830
