### ISSUE TITLE
[Issue] AE Permissions 

### ISSUE THREAD

**Issue by Phasma0007** [GC-spigot/AdvancedEnchantments#1120]
**Describe the bug**
All permission nodes for AE doesnt work and shows "AdvancedEnchantments You do not have permission to use this command. | Reverted to AE v7.5.0-Pre16 and it work fine (without changing any permission nodes/settings) 

**To Reproduce**
A way to reproduce the video

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/66235813/83764741-e54f8100-a6ac-11ea-9a58-9e52188c8b6d.png)
![image](https://user-images.githubusercontent.com/66235813/83764846-04e6a980-a6ad-11ea-8d21-d3acc65da2f7.png)

**Server Information (please complete the following information):**
 - 1.15.2
 - version 7.6.14

**Comment by GC-spigot** [comment]
What permissions plugin are you using?

**Comment by Phasma0007** [comment]
LuckPerms

**Comment by SkellyBG** [comment]
Can confirm that this issue occurs to me too. Also using LuckPerms.

**Comment by GC-spigot** [comment]
Just give `ae.*` permission, but main /ae command permission is `ae.help`, will add this to the wiki

**Comment by Phasma0007** [comment]
Won’t this makes default players havin admin perms? Since ae.* is for admins

**Comment by SkellyBG** [comment]
Added ae.help node and everything is working again :D

**Comment by Phasma0007** [comment]
ae.* is for admins isnt it?

If ae.* is added for default wont they have access to everything?

**Comment by Phasma0007** [comment]
Actually now i had another issue (license exceeded ip) but i think the owner of the server already created a ticket

**Comment by SkellyBG** [comment]
yea you don't need ae.*

**Comment by SkellyBG** [comment]
ae.info isn't a real node tho, it's ae.help

**Comment by Phasma0007** [comment]
/ae info <enchantment> - Information about custom enchantment; ae.info

**Comment by SkellyBG** [comment]
ohh wait nvm I misunderstood somehow lol

**Comment by Phasma0007** [comment]
ohh! thanks btw can you take a look at my friend (owner) ticket regarding license issue?
