### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by austinprado** [GC-spigot/AdvancedEnchantments#1122]
MORE_DROPS for Enchantments causes a duplication when killing players.  It duplicates everything in their inventory.
I had it on KILL_MOB
still did it with players

https://gyazo.com/dae62e11457f353093a06c6ea1fe86ec

**Server Information (please complete the following information):**
 - PaperSpigot 1.14.4
- 7.6.14

**Comment by GC-spigot** [comment]
Fixed
