### ISSUE TITLE
[Request] Item flags from custom weapon files

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#1124]
In the plugin you can use ItemFlags to hide enchantments via the /ae give command but you cannot with the /asets weapon files. It would be much easier to have a ItemFlag: option in the yml files for weapons to easily add in - HideAttributes -HideEnchants in the files to allow for ease of use creating custom weapons. Thank you very much!

**Comment by GC-spigot** [comment]
Added
