### ISSUE TITLE
[Issue] Unable to use multiple transmog scrolls on an item.

### ISSUE THREAD

**Issue by markusew** [GC-spigot/AdvancedEnchantments#1129]
**Describe the bug**
The first time I use a transmog item on an item it works as expected. However, if I add a new enchant to that item and want to sort the enchants again it doesn't let me apply the transmog scroll.

**To Reproduce**
To reproduce, simply attempt to use a transmog scoll on the same item twice and see if it lets you do it. 

**Screenshots / Video**
Before the first transmog scroll
https://i.imgur.com/EGmqqxW.png

After the first transmog scroll
https://i.imgur.com/SnkVh5o.png

After adding a new enchant and trying to add a transmog scroll but it doesnt let me add it
https://i.imgur.com/fF8PRIW.png

**Server Information (please complete the following information):**
 - Tuinity build #106 (1.15.2)
- Plugin Version 7.6.1
- Config of the scroll
```transmogscroll:
    type: PAPER
    id: 0
    name: '&6&lEnchants Sorter'
    lore:
    - '&7Organizes enchants by &brarity&7 on item'
    - ''
    - '&e&oPlace on item to apply'
    enchants-count-formatting: ''```

**Comment by GC-spigot** [comment]
Always check the console :) There's an error, will fix for next update.
