### ISSUE TITLE
[Request] GriefPrevention Integration

### ISSUE THREAD

**Issue by Redgames0** [GC-spigot/AdvancedEnchantments#1134]
Allows players to only use an enchant when they are in their personal or trusted grief prevention claim.

This  would work similar to the factions feature but instead for claim plugins like grief prevention.
For example: I want to make a flight enchant, but they can only use it in their own / trusted land claims.

This feature could be useful to many server owners as it allows more customisation and control over where enchants can be activated.

**Comment by GC-spigot** [comment]
Added
