### ISSUE TITLE
[Issue] Detonate Enchantment Crashes Server

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#1136]
**Describe the bug**
Use Detonate enchanted tools and server proceeds to crash with a long error log.

**To Reproduce**
Use an detonate enchanted tool. https://pastebin.com/SYQuTBiw

**Screenshots / Video**
-

**Server Information (please complete the following information):**
 - Minecraft Version: 1.15.2 PaperSpigot 322/328 (Tested on two versions)
- Plugin Version: 7.7.1

**Comment by BboyZeroOne** [comment]
#1107

**Comment by EarthAgar** [comment]
I'm having the same issue, I'm also on 7.7.1

Spigot Version is 1.15.2-R0.1-SNAPSHOT

I have the exact same errors as him, I've tried multiple levels of trench, different worlds, pickaxes, and even on my skyblock with FabledSkyBlock. It just throws insane amounts of errors extremely fast. I've got a short vid of it here: https://gyazo.com/297d33d82a040387bac1e852b5a452dc

**Comment by BboyZeroOne** [comment]
> I'm having the same issue, I'm also on 7.7.1
> 
> Spigot Version is 1.15.2-R0.1-SNAPSHOT
> 
> I have the exact same errors as him, I've tried multiple levels of trench, different worlds, pickaxes, and even on my skyblock with FabledSkyBlock. It just throws insane amounts of errors extremely fast. I've got a short vid of it here: https://gyazo.com/297d33d82a040387bac1e852b5a452dc

I have over *cough* 15 console errors on my Songoda Skyblock on the earlier versions without AE. After the latest update, there's only a few. But I have not tested AE on FabledSkyblock so I'm not too sure if you would have the same console errors too.

Do note the AE console errors existed since v7.6.0

**Comment by EarthAgar** [comment]
Its definitely AE because I've matched the errors with yours.

**Comment by GC-spigot** [comment]
It's an issue with McMMO and AE from what I've tested, please let me know if 7.7.2 fixes the issues if not give me list of your plugins (either here or via PM GC#0830 on discord)
@EarthAgar 
@BboyZeroOne

**Comment by EarthAgar** [comment]
Alrighty will do soon.

**Comment by EarthAgar** [comment]
@BboyZeroOne It is in fact fixed which is awesome, do GC a favor and close the Issue please 😊

**Comment by BboyZeroOne** [comment]
But I'm not using McMMO, let me send u my plugin list on discord GC
