### ISSUE TITLE
[Issue]Crash

### ISSUE THREAD

**Issue by WarnDangerous** [GC-spigot/AdvancedEnchantments#1137]
**Describe the bug**
Hello, 
Before buying the plugin I come to to discord and asked you if you supported "cheated enchants" from vanilla, like efficiency 6 and +, and you said that "cheated enchant" were supported but I got this issue :
https://pastebin.com/gbJVXVyT
Here is the pickaxe I used :
https://prnt.sc/svzmmi
It spammed my server and make it crash

And telepathy do not work with autosmelt ( it works without it, but not WITH it )

**To Reproduce**
Just take the same pickaxe and mine ores

**Server Information (please complete the following information):**
- Server version : Paper 1.12.2 ( build-1618 ) , and same with Paper 1.15.2 (build-343)
- Plugin Version : 7.6.19
--

**Comment by GC-spigot** [comment]
Not related to the 'cheated' enchants but rather an issue with how mcmmo works, will be fixing this

**Comment by GC-spigot** [comment]
It's an issue with McMMO and AE from what I've tested, please let me know if 7.7.2 fixes the issues if not give me list of your plugins (either here or via PM GC#0830 on discord)
@WarnDangerous

**Comment by WarnDangerous** [comment]
The problem wasn't from McMMO as I wasn't using it, but thanks it seems fixed now !
