### ISSUE TITLE
[Issue] Hierarchy issue

### ISSUE THREAD

**Issue by ConnorServers** [GC-spigot/AdvancedEnchantments#1139]
Hi.
I have 2 strength enchantments.

Strength: (Tier 3) 1>2 levels (strength:0 and stength:1)
Ultimate-Strength: (Tier5) 1 level (strength:2)

I have 2 different enchantments for strength so strength 3 is unobtainable from Tier 3 books.
However, if players have Strength II and Ultimate-Strength I on their chestplate, they only get Strength 2 not strength 3 potion effect.

Are you able to add some sort of hierarchy to prevent this?
Cheers.

**Comment by GC-spigot** [comment]
You can make it so the lower-tier enchants are removed when higher tier are applied (just like how default Heroic enchantments work, you can look here: https://github.com/GC-spigot/AdvancedEnchantments/blob/master/enchantments.yml#L6868
