### ISSUE TITLE
[Issue] Applies-to descriptive issue.

### ISSUE THREAD

**Issue by ConnorServers** [GC-spigot/AdvancedEnchantments#1140]
From my belief, "applies-to:" is meant to be for descriptive purposes. So technically anything should be fine?

When i set the value to "applies-to:  Armour" instead of "Armor" my enchantment does not work.
Same goes for other modifications.

**Comment by GC-spigot** [comment]
It will be a different issue then, as said it's only text and isn't used anywhere. If changing it causes issues it will be a configuration issue then.
