### ISSUE TITLE
[Issue] Enchant activating 3 times

### ISSUE THREAD

**Issue by SkellyBG** [GC-spigot/AdvancedEnchantments#1141]
**Describe the bug**
When mining a diamond ore/stone, the enchant is activated 3 times

**To Reproduce**
The enchant used:
https://hastebin.com/raw/agizarenew

**Screenshots / Video**
The first proc (white message) was due to Token Extractor, you can ignore that
https://streamable.com/6c0p2o

**Server Information (please complete the following information):**
 - Minecraft Version:  Waterfall-Bootstrap:1.15-SNAPSHOT:e0795ab:341
- Plugin Version: 7.5.13

**Comment by GC-spigot** [comment]
Update

**Comment by SkellyBG** [comment]
Have updated to 7.7.4, and now it's proccing twice instead of 3 times

**Comment by SkellyBG** [comment]
There's no error in console

**Comment by SkellyBG** [comment]
Now I uploaded some new enchants, and the new enchants + this enchant has gone back to activating 3 times.
new enchants: https://hastebin.com/raw/mehepabulo

**Comment by SkellyBG** [comment]
also, was testing another enchant and it seems that the proc is mostly random. When this enchant proc, I get anywhere from 1-3 ingots.
https://hastebin.com/raw/efutarineb

Would like to note that the give command isn't the problem, as I also have enchants that give item on fish catch and it works fine.

**Comment by SkellyBG** [comment]
#1163
