### ISSUE TITLE
[Issue] MINING console spam

### ISSUE THREAD

**Issue by blek-id** [GC-spigot/AdvancedEnchantments#1144]
**Describe the bug**
I still can't seem to find the way to find why it caused this, but there's a lot of console spam about mining after some update I did a few days ago. Last version I updated to was from 7.6.14.

**To Reproduce**
Can't find a way to reproduce yet. But here's the log that I have https://pastebin.com/72ktDku4 and 
https://pastebin.com/H1jUprA4

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.15.2
- Plugin Version 7.7.4

**Comment by GC-spigot** [comment]
Update and send the errors, these are from 7.6.14 (code changes a lot with updates and now these are useless)

**Comment by blek-id** [comment]
Error no longer showing, sorry for the delay
