### ISSUE TITLE
AE Disabled due to too many IP Addresses

### ISSUE THREAD

**Issue by Ma8ician** [GC-spigot/AdvancedEnchantments#1145]
Ham5teak

Please help 

I have tried to get assistance through the discord server, AE has been down on our server for nearly a week!

We regularly reallocate servers, plus have expanded our network to 7 and are soon going to add an 8th server. Add to that we had a misadventure when we tried out a new Service Provider!

_Magician_
Owner Ham5teak

**Comment by GC-spigot** [comment]
![](https://i.imgur.com/mCekDAC.png)

Resolved this but it will pop up again, if it does you will need to contact me on Discord GC#0830 to get the
