### ISSUE TITLE
[Issue] Revive not working.

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#1147]
**Describe the bug**
Just get killed with a REVIVE enchant.
**To Reproduce**
Equip the enchant.
Get Killed.
Expected:Revive
Result:Stay dead

**Screenshots / Video**
![Screenshot_3346](https://user-images.githubusercontent.com/23641964/84275479-a42df580-ab20-11ea-9f79-8dd83e0442ac.png)
That's the enchant but getting killed and reviving doesn't work.
(I was testing, it was on a chestplate)

**Server Information (please complete the following information):**
Minecraft version 1.13.2 - Spigot 1.13.2
Plugin version  7.7.5

**Comment by GC-spigot** [comment]
Must be another plugin interfering (works fine on my tests)
