### ISSUE TITLE
no sounds play in the 1.15.2 [Issue]

### ISSUE THREAD

**Issue by Feier68** [GC-spigot/AdvancedEnchantments#1148]
**Describe the bug**
no sounds play in the 1.15.2

I have no more information. sry

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.15.2]
- Plugin Version [e.g. 7.7.5]

**Comment by GC-spigot** [comment]
You'd have to change the sounds in configs for your version since they change with every version
