### ISSUE TITLE
CONSOLE_COMMAND not working[Issue]

### ISSUE THREAD

**Issue by AlessioTW** [GC-spigot/AdvancedEnchantments#1150]
**Describe the bug**
when i try to use the function of CONSOLE_COMMAND in a customenchant, the placeholders "%player" or "%player_name" doesn't work.

**Screenshots / Video**
https://prnt.sc/sy21yc

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.8.8]
- Plugin Version [7.7.8]

What placeholder I have to use? thanks

**Comment by GC-spigot** [comment]
Use %attacker name% or %victim name%
