### ISSUE TITLE
[Issue]Potion Effect for Enchantments does not clear when swap item with hotkey

### ISSUE THREAD

**Issue by notynote** [GC-spigot/AdvancedEnchantments#1153]
**Describe the bug**
When player use hotkey to swap item with item that containsthe enchantment that give potion effect to a player. The potion effect will not cleared and remain for half an hour.

**To Reproduce**
Just use hot key to swap equipped item

**Server Information (please complete the following information):**
 - Paper 348
- Plugin Version 7.7.7

**Workaround Fix
I just check the InventoryAction for HOTBAR_MOVE_AND_READD and HOTBAR_SWAP and cancel the event when player try to swap item with hotbar

**Comment by notynote** [comment]
Moreover I tried 7.7.8 and potion effect not clear when remove by hand (without hotkey) aswell

**Comment by GC-spigot** [comment]
Provide a video, can't recreate

**Comment by notynote** [comment]
First of all, Sorry I forgot to mention the bug happen with player head only but not other helmet.

And here is the link to the video
https://youtu.be/J1iwF10CLA8

**Comment by GC-spigot** [comment]
Fixed
