### ISSUE TITLE
[Issue] Can't retrieve sets via command. Error null

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#1154]
/asets give doesn't work
Error: https://pastebin.com/q0Eh6Ncb

Server Info:
![Screenshot_3364](https://user-images.githubusercontent.com/23641964/84556482-8cb65e80-ad12-11ea-813e-56cc1fb32c92.png)

**Comment by GC-spigot** [comment]
Fixed
