### ISSUE TITLE
Gkit gems[Issue]

### ISSUE THREAD

**Issue by MichaelLennik** [GC-spigot/AdvancedEnchantments#1155]
How to get gkit gems, so they are redeemable from opening crates. I am wanting to put them in crates and when received is a gem that they can redeem for themselves or trade/sell. Thanks

**Comment by GC-spigot** [comment]
Use command `/ae giveitem <player> soulgem 1 <souls amount>`

**Comment by MichaelLennik** [comment]
This is a soul gem, I was looking for the gkit gems like cosmic pvp has.

**Comment by GC-spigot** [comment]
There’s no gkit gems - use permissions to give gkits
