### ISSUE TITLE
[Request] Allow the checking of vanilla enchants as conditions

### ISSUE THREAD

**Issue by RheinmetallDev** [GC-spigot/AdvancedEnchantments#1157]
** Describe the Request**
Make it so CEs check for vanilla enchants as required and conflicting enchants.

Example:
Fire Aspect + Rage = Wrath, getting Wrath requires both Fire Aspect and Rage, and when applied, removes both of them.

Example 2:
If Fire Aspect exists, block Ice Aspect from being applied to the item, and vice versa

**Comment by GC-spigot** [comment]
Added
