### ISSUE TITLE
[Request] Separate bow and crossbow enchants

### ISSUE THREAD

**Issue by RheinmetallDev** [GC-spigot/AdvancedEnchantments#1158]
** Describe the Request**
Separate the BOW type into BOW and CROSSBOW, so we can make independent enchantments for both types of bows. Some enchants are just too powerful to be put on a bow due to its faster firing rate and better vanilla enchants.

**Comment by GC-spigot** [comment]
Just change ```  applies:
    - 'BOW'
    - 'CORSSBOW'```
to  ```  applies:
    - 'CORSSBOW'```
