### ISSUE TITLE
[Issue] New item flags on custom weapons don't hide custom enchants

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#1160]
The item flags successfully hide vanilla enchants but they do not hide custom enchants like the /aegive command does, to make it absolutely perfect matching the /aegive commands hide_enchants to hide everything in the custom weapon files would allow for complete creative control on the items as right now only being able to hide some enchants doesn't allow for that as right now custom enchants stay shown above the lore, thanks for the addition based on my request!

**Comment by GC-spigot** [comment]
AEGive does not hide custom enchants either, this item flag is for vanilla enchants only. At the moment this is not possible.
