### ISSUE TITLE
Renamed Items with [ and ] on sword and axe gets removed when using Transmog Scroll

### ISSUE THREAD

**Issue by Gilthunderx** [GC-spigot/AdvancedEnchantments#1161]
Hello , I am using epicrename to rename items , When I rename such item and include [ and ] in it, then use a transmog scroll to organize the ce of that specific item , the name of the items vanishes.

I'm using the build 7.8.7 and on 1.15.2 .

**Comment by GC-spigot** [comment]
Cannot recreate, epic rename must be breaking the item somehow. All I can suggest is switching to a proper renaming plugin (epic rename is known to have many issues like this)
