### ISSUE TITLE
[Issue] Enchant activating multiple time. Continuation of #1141

### ISSUE THREAD

**Issue by SkellyBG** [GC-spigot/AdvancedEnchantments#1163]
**Describe the bug**
When using MINING enchant, the effect activates 2-3 time for a block mined. 

**To Reproduce**
https://hastebin.com/raw/agizarenew
https://hastebin.com/raw/mehepabulo
https://hastebin.com/raw/mehepabulo

**Screenshots / Video**
Enchants activating three times
https://streamable.com/6c0p2o
https://streamable.com/r0w3g7

Enchants activating twice randomly
https://streamable.com/yz5fd5

There's no error in console.

**Server Information (please complete the following information):**
 - Minecraft Version: Waterfall-Bootstrap:1.15-SNAPSHOT:e0795ab:341
- Plugin Version 7.7.4

If the plugin requires another update, please don't close this ticket.

**Comment by SkellyBG** [comment]
I added a cooldown of 0.1 to the first enchant, and now it's proccing 4 times ://

**Comment by GC-spigot** [comment]
Cooldown of `0.x` is not allowed, it's only a number, cannot have a decimal (only allowed e.g. 1, 2, 3, 4, not 0.1, 0.05, 0.9 etc)
Fixed!
