### ISSUE TITLE
[Request] ADD_ENCHANT effect

### ISSUE THREAD

**Issue by SkellyBG** [GC-spigot/AdvancedEnchantments#1164]
** Describe the Request**
Since there's an effect REMOVE_ENCHANT that remove an enchant, would it be possible to have an effect called ADD_ENCHANT that add an enchant? 

Something like ADD_ENCHANT:(enchant):(level)

In the case of the item having full slots, the effect would be ignored.

**Comment by GC-spigot** [comment]
Added
