### ISSUE TITLE
Persistent Haste Effect Glitch

### ISSUE THREAD

**Issue by BurakDorman** [GC-spigot/AdvancedEnchantments#1165]
**Describe the bug**
If you quickly switch your held item with a pickaxe, you get Haste Effect with pickaxe. It only can be done if Haste Effect applied on an illegal item such as stick, shears etc.

**To Reproduce**
If you quickly switch your held item with a pickaxe, you get Haste Effect with pickaxe.

**Screenshots / Video**
https://youtu.be/nrDQbiz-ul0

**Server Information (please complete the following information):**
 - ImanitySpigot (PaperSpigot 1.8.8)
 - I use latest version all the time.

**Comment by GC-spigot** [comment]
Fixed!
