### ISSUE TITLE
[Issue] AAC + Detonate Enchantment

### ISSUE THREAD

**Issue by minemalia** [GC-spigot/AdvancedEnchantments#1167]
**Describe the bug**
When using Detonate the enchantment is blocked by AAC. After repeatedly trying, the player is kicked by AAC. 

**To Reproduce**
Add detonate to a pickaxe and start to mine with AAC installed.

**Screenshots / Video**
https://www.youtube.com/watch?v=5sK_js4_CTo&feature=youtu.be
In the beginning I am not kicked, since I bypasses AAC because I had OP. When removing my OP, the problem occurs.
https://imgur.com/ujFUDZX
This is the console output ^

**Server Information (please complete the following information):**
 - Minecraft Version [Paper-347 1.15.2]
- Plugin Version [AdvancedEnchantments-7.8.16, AAC-4.3.12]

**Comment by GC-spigot** [comment]
Thanks, fixed!
