### ISSUE TITLE
[Issue] When I try to use the menu it lets me drag to inventory

### ISSUE THREAD

**Issue by Tsukii2** [GC-spigot/AdvancedEnchantments#1169]
**Describe the bug**
When I do /enchanter it brings up the menu and when it does instead of clicking on the things it lets me drag them

**To Reproduce**
Not Sure

**Screenshots / Video**
https://streamable.com/18w3as

**Server Information (please complete the following information):**
 - Minecraft Version [Spigot 1.15.2 ]
- Plugin Version [7.8.17]

**Comment by GC-spigot** [comment]
PM GC#0830 on Discord
