### ISSUE TITLE
Error spammm

### ISSUE THREAD

**Issue by ducdzz61** [GC-spigot/AdvancedEnchantments#1170]
Link: https://pastebin.com/VkBDLax1
pls fix

**Comment by ducdzz61** [comment]
https://pastebin.com/eNbQaR6L

**Comment by ducdzz61** [comment]
https://pastebin.com/wu96AsZP

**Comment by GC-spigot** [comment]
Use proper issue report, you give me no information. https://prnt.sc/t3cqus

What worldguard version are you using? last 2 issues either aren't full errors or are not from my plugin.

**Comment by ducdzz61** [comment]
"worldguard-bukkit-6.2.2"
A few days ago there was no problem, I updated the plugin to the new version so today I receive constant spam like that

**Comment by ducdzz61** [comment]
[14:08:33] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AdvancedEnchantments v7.8.17

**Comment by GC-spigot** [comment]
Can you add me on Discord GC#0830 and send me your WorldGuard plugin .jar? This error is not possible according to what I see
