### ISSUE TITLE
[Issue]Severe Console Spamming & Players Being Forcibly Disconnected

### ISSUE THREAD

**Issue by GamingWubba93** [GC-spigot/AdvancedEnchantments#1172]
**Describe the bug**
Was playing on my server and killed a zombie, creeper and skeleton. Next had a zombie swarm attack and decided to check the console to see if there were any errors. Saw a massive generating list of errors. First time this happened i was using the version before 7.8.17 and the log flooding itself caused several players to be disconnected. 

**To Reproduce**
Don't really know if you can reproduce it. I'll just revert to 7.8.17 for now.

**Screenshots / Video**
_Attached console log instead_

**Server Information (please complete the following information):**
 - Minecraft Version 1.15.2
- Plugin Version 7.9.0

Console Log: 
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/4810267/latest.log)

**Edits**
- Removed IP Address from log

**Comment by GamingWubba93** [comment]
Started my server up using the 7.8.17 version and noticed while the server was loading up the console was being flooded by some issue pertaining to life steal. None of the weapons we're using currently have any AE enchantments on them.

Could possibly be connected to #1177 

Console Log:
[latest (1).log](https://github.com/GC-spigot/AdvancedEnchantments/files/4810268/latest.1.log)

**Comment by SnowBees** [comment]
Even with 7.8.17, I start getting an error when trying to attack a mob with any weapon and it loops.
I haven't checked all versions, but if it's 7.8.13 I don't get an error. No other checks have been made.

**Comment by GC-spigot** [comment]
Fixed
