### ISSUE TITLE
[Issue] StatTrak & BlockTrak Formatting

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#1175]
The BlockTrak and StatTrak position in the lore seems completely random, sometimes its at the top below the weapons name, sometimes its perfectly in between Enchants |  Lore then other times it'll have say.. Sharpness X Unbreaking X Wither VII Kills: 0 Reaper V So it has enchants after the Kills: in the lore. This changes per weapon seemingly at random, as i don't believe there is a way to format this it felt appropriate to bug report just in case as i feel it should always be before the lore below the title or somewhere else consistently to make it look appropriately formatted and not inbetween enchants. I believe its when a weapon gets over 4 enchantments it then formats it with the enchantment following the StatTrak lore entry.

On the latest version of the plugin

Thanks

**Comment by GC-spigot** [comment]
Changed this behavior
