### ISSUE TITLE
[Enderman farm causing server to kick players and time out.]

### ISSUE THREAD

**Issue by TSchweiger** [GC-spigot/AdvancedEnchantments#1177]
**Describe the bug**
I made an Enderman farm and the server timed out with this error repeating.
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/4810234/latest.log)

**To Reproduce**
Create a simple Enderman farm like in this video https://www.youtube.com/watch?v=K7fyB-IyY4E and hit the Enderman with a sweeping edge sword. That's what I did and it crashed twice on me.

**Screenshots / Video**
N/a

**Server Information (please complete the following information):**
 - Minecraft Version [git-Paper-354]
- Plugin Version [7.9.1]
- Logfile See Attached

**Comment by TSchweiger** [comment]
I believe this issue is related https://github.com/GC-spigot/AdvancedEnchantments/issues/1172

**Comment by TechnoVisionDev** [comment]
Hi there! I actually get the same error when I hit mobs with no weapon in my hand. It seems this issue is a result of a incorrect casting of enderman into player when it should not.

**Comment by GC-spigot** [comment]
Fixed
