### ISSUE TITLE
Telepathy Bugs

### ISSUE THREAD

**Issue by SirKriSftw** [GC-spigot/AdvancedEnchantments#1178]
For some reason whenever a player attempts to mine a shulker or ice with telepathy the block does not break and instead just places back. Is there a fix for this?
Also, this can easily be somewhat game breaking as you can stack this with the "experience" enchant and just infinitely farm xp by breaking the blocks over and over.

**Comment by GC-spigot** [comment]
Fixed, and this wouldn't drop exp, it just wouldn't drop some blocks but now is resolved
