### ISSUE TITLE
[Issue] EventException on Unarmed EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by TechnoVisionDev** [GC-spigot/AdvancedEnchantments#1179]
**Describe the bug**
Whenever I hit a mob with nothing in my hand, I get this error https://pastebin.com/BiyiRftZ
The error does not occur when I am holding a sword.

It seems like AE is attempting to cast the entities I hit into players, presumably to apply custom enchants? I think you need to check that the victim of EntityDamageByEntityEvent is instanceof player before casting but tbh, i don't know the issue.

`Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftSheep cannot be cast to org.bukkit.entity.Player`

**To Reproduce**
Hit a entity, like a sheep, with your hand and check the console.

**Screenshots / Video**
https://pastebin.com/BiyiRftZ

**Server Information (please complete the following information):**
 - PaperSpigot 1.8.8
- Plugin Version 7.9.2 (Latest)

**Comment by TechnoVisionDev** [comment]
After looking at some of the other issues, this bug report seems very similar to #1177 and is likely the same issue.

**Comment by SnowBees** [comment]
I don't know the cause, but it's better to wait for correction because an error will occur even with bare hands. If you really want to use it, you should use the old version.

**Comment by GamingWubba93** [comment]
> I don't know the cause, but it's better to wait for correction because an error will occur even with bare hands. If you really want to use it, you should use the old version.

I'm currently using 7.8.17 (the last oldest version where i had no major issues and decided to test an unarmed mob hit like @TechnoVisionDev ran. Experienced massive console spam again and even after the entity was killed the log kept sending out errors. 

So it looks like issues #1172 #1177 & #1179 are all correlated. In the meantime I might remove the plugin from my server just because once the errors start sending, players are getting kicked off the server and upon rejoining kicked due to log spam.

**Comment by GamingWubba93** [comment]
> > I don't know the cause, but it's better to wait for correction because an error will occur even with bare hands. If you really want to use it, you should use the old version.
> 
> I'm currently using 7.9 and decided to test an unarmed mob hit like @TechnoVisionDev ran. Experienced massive console spam again and even after the entity was killed the log kept sending out errors. I'll revert to 7.8.17 in the meantime and see if any issues are still occurring there.
> 
> So it looks like issues #1172 #1177 & #1179 are all correlated. In the meantime I might remove the plugin from my server just because once the errors start sending, players are getting kicked off the server and upon rejoining kicked due to log spam.

@TechnoVisionDev @TSchweiger I reverted back to 7.8.17 and currently have experienced no issues. The moment you update to anything past this version is when the errors seem to start overflowing the console. Hope this helps you guys out in your playthroughs!

**Comment by GC-spigot** [comment]
Fixed
