### ISSUE TITLE
Implants doesn't appear to be doing anything.

### ISSUE THREAD

**Issue by Crysillion** [GC-spigot/AdvancedEnchantments#1180]
I can sit for over 15 minutes an Implants never procs, it appears to just not work at all. I recall it working before so it's a bit weird.

**Comment by GC-spigot** [comment]
MC version?

**Comment by Crysillion** [comment]
Sorry! I keep forgetting that people use older versions of Minecraft.

1.15.2

**Comment by asterism-s** [comment]
Implants isn't working for me on 1.16.1 either. Neither is Alien Implants.

**Comment by GC-spigot** [comment]
Should be fixed!
