### ISSUE TITLE
[Issue] Black scrolls and white scrolls can be made in anvils

### ISSUE THREAD

**Issue by ShayneBauzon** [GC-spigot/AdvancedEnchantments#1185]
**Describe the bug**
When players rename ink sacs and empty maps into black scrolls or white scrolls in anvils, it works as a real black scroll or white scroll even if it doesnt have the lore for the black scroll or white scroll.

**Server Information (please complete the following information):**
 - Minecraft Version 1.14.4 [Paper Spigot 1.14.4]
- Plugin Version [7.9.3]

**Comment by GC-spigot** [comment]
This is me 3rd time replying the same text to you: disable renaming for these items in your renaming plugin.
