### ISSUE TITLE
Telepathy still cant pick up shulkers

### ISSUE THREAD

**Issue by SirKriSftw** [GC-spigot/AdvancedEnchantments#1186]
**Describe the bug**
If you have telepathy on a pickaxe you cannot use it to pick up shulker boxes

**Screenshots / Video**
https://youtu.be/5o2M8ZUJ8oI

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [7.9.4]

**Comment by GC-spigot** [comment]
Fixed!
