### ISSUE TITLE
[Request] Change sets owner: to value:

### ISSUE THREAD

**Issue by plusgithub** [GC-spigot/AdvancedEnchantments#1187]
My suggestion is to either change or add a new tag for the helmet of a set to be a head from a value instead of a playersname, these values can be taken from https://minecraft-heads.com/ or a similar website. The values look like this: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmM1YWRhNGNiNjA3NjNmZWFkOGVmZGZhOWI5MGFhMGNhZDQyZWIwNWQzMmI1Yzg0ZWU5NTE5NTRiNDM1MTA2YyJ9fX0='

This would allow for pretty much infinite types of helmets to be created.
Alongside this it would also be good to disable the placing of heads when they are part of a set and maybe even being able to right click the head to put it on just like other armor.
Thanks

**Comment by GC-spigot** [comment]
Added both
