### ISSUE TITLE
[Request] OPPrisons Token Currency

### ISSUE THREAD

**Issue by CaptainRichYT** [GC-spigot/AdvancedEnchantments#1189]
Name your request: Adding an OPPrisons Token Currency

Brief request explanation:
In the config you could have a choice of setting the plugin currency to tokens, then you could use the command /token to open a guy to spend your tokens to buy enchantments or other things. (scrolls etc) Since this would be for an opprisons server you would have to add a setting where there's a small % of getting tokens when mining blocks. 

If you need anymore info dm: Ashaaz#0046

**Comment by GC-spigot** [comment]
Added
