### ISSUE TITLE
Lapis Broken by Detonate Enchant gives lapis an NBT tag of Damage:4[Issue]

### ISSUE THREAD

**Issue by ThaiWRV** [GC-spigot/AdvancedEnchantments#1190]
**Describe the bug**
When players break lapis with detonate, the lapis is unsellable since it was given an nbt data

**Server Information (please complete the following information):**
 - Paper Spigot 1.15.2 #366 
- Plugin Version 7.9.7

**Comment by GC-spigot** [comment]
Fixed
