### ISSUE TITLE
[Issue] MiningSouls NullPointerException Console Spam

### ISSUE THREAD

**Issue by TechnoVisionDev** [GC-spigot/AdvancedEnchantments#1194]
**Describe the bug**
Seems that the new mining-souls feature, when enabled, causes mining blocks to spam the console with nullpointerexceptions. Here is a pastebin of the error: https://pastebin.com/HqrBrxMX

As you can see, there is reference to the "SoulsAPI.addSouls(SoulsAPI.java:64)" during the BlockBreakEvent.

**To Reproduce**
Turn the new mining souls feature on. Mine a block with a pickaxe

**Server Information (please complete the following information):**
 - ImanitySpigot 1.8.8
- Plugin Version Latest 7.9.10

**Comment by Ekute-hub** [comment]
I have the same issue: https://pastebin.com/bprt1q9m

Server Information:
   Paper 1.15.2
   Plugin Version Latest 7.9.10

**Comment by GC-spigot** [comment]
Fixed
