### ISSUE TITLE
Telepathy+Auto Smelt inconsistencies

### ISSUE THREAD

**Issue by SirKriSftw** [GC-spigot/AdvancedEnchantments#1196]
**Describe the bug**
If you have telepathy and auto smelt on the same pick it silk touches some ores (redstone, quartz and lapis from my tests)

**Screenshots / Video** (Left video on in background, just play video muted)
https://youtu.be/jUqK2W7CX-M

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.15.2]
- Plugin Version [e.g. 7.9.4]

**Comment by SirKriSftw** [comment]
Also, with telepathy you do not get XP from mining ores

**Comment by GC-spigot** [comment]
Fixed
