### ISSUE TITLE
[Issue] Inquisitive and Master Inquisitive bug

### ISSUE THREAD

**Issue by ShayneBauzon** [GC-spigot/AdvancedEnchantments#1199]
**Describe the bug**
My players and I have tested the Inquisitive and Master Inquisitive custom enchantments and we noticed that Inquisitive 4 gives more exp than master inquisitive 4. 

**Server Information (please complete the following information):**
 - Minecraft Version 1.14.4 [PaperSpigot 1.14.4]
- Plugin Version [7.9.8]

**Comment by GC-spigot** [comment]
Reworked both enchants, thanks for reporting this
