### ISSUE TITLE
PlayerMoveEvent spamm

### ISSUE THREAD

**Issue by ducdzz61** [GC-spigot/AdvancedEnchantments#1203]
pl ver: v7.9.12
link error: https://pastebin.com/fw3smHyT
server: 1.12.2 (paperspigot)
pls fix

**Comment by ducdzz61** [comment]
https://pastebin.com/7fhP9pHF please

**Comment by GC-spigot** [comment]
I already told you the issue, stop making new issues. Your enchantment 'plaguecarrier' has an issue with conditions
