### ISSUE TITLE
Max health boosted, cannot reset[Issue]

### ISSUE THREAD

**Issue by Lasicarius** [GC-spigot/AdvancedEnchantments#1205]
Boosted health via armor, now the health attribute has been modified and I need a way to reset it

**Server Information (please complete the following information):**
 - Minecraft Version 1.16.1
- Plugin Version 7.9.13

**Comment by GC-spigot** [comment]
Spigot bug, update or download paperspigot

**Comment by Lasicarius** [comment]
Downloaded paperSpigot, that did not seem to help
