### ISSUE TITLE
spammy error in console not so much a bug

### ISSUE THREAD

**Issue by Stoniasawsome** [GC-spigot/AdvancedEnchantments#1207]
**Describe the bug**

**To Reproduce**
A way to reproduce the video

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [7.9.1]

i get this error on my 1.15.2 paper spigot server with your version 7.9.1
any help with what this may be would be grand

ERROR Could not pass event EntityDamageEvent to AdvancedEnchantments v7.9.1 27.06 16:01:24 [Server] INFO java.lang.ClassCastException: org.bukkit.craftbukkit.v1_15_R1.entity.CraftPigZombie cannot be cast to org.bukkit.entity.Player 27.06 16:01:24 [Server] INFO at n3kas.ae.enchanthandler.enchanttypes.PASSIVE_DEATH.onDeath(PASSIVE_DEATH.java:30) ~[?:?] 27.06 16:01:24 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor363.execute(Unknown Source) ~[?:?] 27.06 16:01:24 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:240) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1008) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:990) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:851) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1040) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1691) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1049) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPigZombie.damageEntity(EntityPigZombie.java:138) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.collideNearby(EntityLiving.java:2701) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2645) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:525) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityMonster.movementTick(EntityMonster.java:23) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityZombie.movementTick(EntityZombie.java:209) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2396) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.EntityZombie.tick(EntityZombie.java:179) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:808) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.World.a(World.java:879) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:532) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-372] 27.06 16:01:24 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-372]

**Comment by GC-spigot** [comment]
Update

**Comment by Stoniasawsome** [comment]
i know you publish a great plugin but i cannot constantly update as i have custom titles to you enchants. every time you update i have to go thru my enchantment.yml and reconfigure all your enchants to fit my custom titles. is there anyway you can make the enchantments.yml autoupdate with what i already have in there? your plugin is the only plugin ive ever had to update the config "every" time you update. it makes me not want to update at all. it costs me at least 1 hr to customize mt enchants.ylm back to what i had them before the update. it wouldnt be a big deal except you have like 2 updates a day...

**Comment by GC-spigot** [comment]
I don’t understand what you are talking about. Nothing has to be updated in enchantments.yml, no clue what you’re talking about.
