### ISSUE TITLE
Can't right click to redeem books 1.16.1

### ISSUE THREAD

**Issue by Brand0n1** [GC-spigot/AdvancedEnchantments#1208]
I downloaded the latest version of AdvancedEnchantments and whenever I try to use the books (fireworks stars) from /enchanter I am not able to right-click the firework star. When I try nothing happens and I get the following error in console:
[https://hastebin.com/tomaditino.apache](https://hastebin.com/tomaditino.apache )

**Comment by GC-spigot** [comment]
Seems to be a bug with spigot, try updating
