### ISSUE TITLE
[Issue] WorldGuard Error Spam (LavaWalker)

### ISSUE THREAD

**Issue by TechnoVisionDev** [GC-spigot/AdvancedEnchantments#1209]
**Describe the bug**
Getting this error spammed in my console. Never got this error until updating AE a few days ago to the most recent jar.

https://pastebin.com/mi5a4WhY

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.8.8]
- Plugin Version [e.g. 7.9.14]

**Comment by GC-spigot** [comment]
What worldguard version are you using?

**Comment by TechnoVisionDev** [comment]
Worldguard 6.2 -- for Spigot 1.8.8

**Comment by GC-spigot** [comment]
Should be fixed
