### ISSUE TITLE
[Issue] Telepathy Enchant duplicated beds.

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#1211]
**Describe the bug**
When using a telepathy enchanted pickaxe, it will drop the bed on the floor, and add one more extra bed into my inventory.

**To Reproduce**
No video.

**Screenshots / Video**
https://drive.google.com/file/d/1e9aPAPGIjiHLmkFqJb47JBCEJ8_93hLM/view?usp=drivesdk

**Server Information (please complete the following information):**
 - Minecraft Version: 1.15.2 PaperSpigot git-Paper-322
- Plugin Version AE 7.9.13

**Comment by GC-spigot** [comment]
Seems like you have another plugin which shows the dropped item names, might be related because I'm not able to recreate this.
