### ISSUE TITLE
Player head "ban" 1.16.1

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#1212]
Using decapitation to get player heads having one and duplicating it in creative with middle mouse button to a stack of 64 effectively bans the user until the player data is deleted from the server due to a specific java error and max size in bytes allowed

To recreate
> Obtain player head
> Get lots of them via creative
> Wait a second for "ban"

**Comment by GC-spigot** [comment]
That's a spigot bug not AE
