### ISSUE TITLE
Freezing Server

### ISSUE THREAD

**Issue by Noni16** [GC-spigot/AdvancedEnchantments#1213]
**Describe the bug**
This error makes the server freeze and time everyone out. We do not know what's causing it or what the error means, but we believe its AdvancedEnchantments. The only I have to go off of is console.

**To Reproduce**
N/A

**Console Error**
n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1216)
[3:07 PM]
[Sun, 28. Jun 2020 14:22:24 EDT ERROR]         n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:109)
[Sun, 28. Jun 2020 14:22:24 EDT ERROR]         n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:254)
[Sun, 28. Jun 2020 14:22:24 EDT ERROR]         n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:123)
[Sun, 28. Jun 2020 14:22:24 EDT ERROR]         n3kas.ae.enchanthandler.enchanttypes.MINING.lambda$0(MINING.java:71)
[Sun, 28. Jun 2020 14:22:24 EDT ERROR]         n3kas.ae.enchanthandler.enchanttypes.MINING$$Lambda$7495/2071739857.accept(Unknown Source)
[Sun, 28. Jun 2020 14:22:24 EDT ERROR]         java.util.ArrayList.forEach(ArrayList.java:1257)
[Sun, 28. Jun 2020 14:22:24 EDT ERROR]         n3kas.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:66)
[Sun, 28. Jun 2020 14:22:24 EDT ERROR]         com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1570.execute(Unknown Source)

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [e.g. 7.6.15]

**Comment by GC-spigot** [comment]
Update the plugin, you're behind by a lot
