### ISSUE TITLE
AD ADMIN NOT WORKING [Issue]

### ISSUE THREAD

**Issue by kiloRs** [GC-spigot/AdvancedEnchantments#1215]
When I go to type /ae admin or give perms to players (even before the ae admin breaking) they werent able to open the menu. Even with admin perms for the plugin.

Minecraft Paper Spigot 1.15.2
Latest Build of AE

**Comment by GC-spigot** [comment]
Show the error from console

**Comment by kiloRs** [comment]
The error for which part? My menu works now but the permissions dont work.
I tried many different times and ae.admin never works for people i assign
the permission too who arent op
