### ISSUE TITLE
[Issue] Command to open GUI for players from console

### ISSUE THREAD

**Issue by EnderGamingFilms** [GC-spigot/AdvancedEnchantments#1221]
**Reference:** #1143 

**Describe the bug**
I don't believe there is any documentation on this feature but it seems like it was added. After doing some testing I tired using the command `/ae open` and I got back an error. I don't know if this is the command meant to be used to open the GUI for the player but I would assume it is. It appears that it gives an error when using it and it returns nothing (nothing happens) when you use `/ae open enchanter EnderGamingFilms`.

**Stacktrace**
https://pastebin.com/SACVHiM6

**Server Information (please complete the following information):**
 - Server Version: Paper-307-1.15.2-R0.1
 - Plugin Version: 7.9.16

**Comment by GC-spigot** [comment]
You did `/ae open EnderGamingFilms` not `/ae open EnderGamingFilms enchanter` as mentioned in the help page (`/ae 2`) in-game: https://prnt.sc/t95sik

**Comment by EnderGamingFilms** [comment]
Still have an unhandled exception executing  "half" the command.

**Comment by GC-spigot** [comment]
Execute the full command then.
