### ISSUE TITLE
[Issue] Console Error and cant access enchantment creator

### ISSUE THREAD

**Issue by ShayneBauzon** [GC-spigot/AdvancedEnchantments#1222]
**Describe the bug**
[WARNING] .... java.io.IOException: Server returned HTTP response code: 522 for URL: http://servers.advancedmarket.co/ae/enchantments/share.php?list=true

[WARNING] .... at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)

[WARNING] .... at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)

[WARNING] .... at n3kas.ae.handlers.netsharing.MarketInventory.readUrl(MarketInventory.java:367)

[WARNING] .... at n3kas.ae.handlers.netsharing.MarketInventory.cache(MarketInventory.java:217)

[WARNING] .... at n3kas.ae.handlers.netsharing.MarketInventory.access$0(MarketInventory.java:213)

[WARNING] .... at n3kas.ae.handlers.netsharing.MarketInventory$1.run(MarketInventory.java:48)

[WARNING] .... at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)

[WARNING] .... at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)

[WARNING] .... at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)

[WARNING] .... at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

[WARNING] .... at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

[WARNING] .... at java.lang.Thread.run(Thread.java:813)

**Server Information (please complete the following information):**
 - Minecraft 1.14.4 [PaperSpigot 1.14.4]
- Plugin Version [7.9.17]

**Comment by GC-spigot** [comment]
Fixed
