### ISSUE TITLE
[Issue] How do I disable the shared enchants system

### ISSUE THREAD

**Issue by EnderGamingFilms** [GC-spigot/AdvancedEnchantments#1224]
How do I disable the "shared enchants system" that accesses this URL "http://servers.advancedmarket.co/ae/enchantments/share.php?list=true" it is caused immense console spam and I honestly don't want the system on my server. It's really cool but I don't think I will use it any time soon.

**Stacktrace:** https://pastebin.com/t0YnNZqT

**Comment by GC-spigot** [comment]
Fixed
