### ISSUE TITLE
[Issue] Black scrolls does not seem to work

### ISSUE THREAD

**Issue by ShayneBauzon** [GC-spigot/AdvancedEnchantments#1227]
**Describe the bug**
Everytime me or my players use blackscrolls, it does not seem to work. Nothing happens.

**Server Information (please complete the following information):**
 - Minecraft Version 1.14.4 [PaperSpigot 1.14.4]
- Plugin Version [7.9.18]

**Comment by GC-spigot** [comment]
Share blackscroll configuration

**Comment by ShayneBauzon** [comment]
My blackscroll configuration is the default from which you first install the plugin. I did not change anything. Here's my config

black-scroll:
    type: INK_SACK
    id: 0
    name: '&f&lBlack Scroll'
    lore:
      - '&7Removes a random enchantment'
      - '&7from an item and converts'
      - '&7it into a &f%success%% &7success book.'
      - '&fPlace scroll onto item to extract.'
    success: 95
    destroy: 5
    random: true
    messages:
      noEnchantments: '&c&l(!)&c This item has &l0&c enchantments!'
      cannotBeRemoved: '&c&l(!)&c %enchant% cannot be removed as it''s invalid.'

**Comment by GC-spigot** [comment]
Fixed
