### ISSUE TITLE
[Issue] Detonate enchantment error

### ISSUE THREAD

**Issue by ShayneBauzon** [GC-spigot/AdvancedEnchantments#1228]
**Describe the bug**
Everytime me or my players use tools that has Detonate enchant, it says in chat "Failed to parse effect 'TRENCH' for enchant 'detonate'
Arguments included with effect: '[3]'
Other informations have been printed to console...

**Screenshots / Video**
![2020-07-01_21 21 23](https://user-images.githubusercontent.com/64379231/86250959-d8f31100-bbe3-11ea-9ed4-660da6299bf3.png)

**Server Information (please complete the following information):**
 - Minecraft Version 1.14.4 [PaperSpigot 1.14.4]
- Plugin Version [7.9.18]

**Comment by GC-spigot** [comment]
Show the error from console

**Comment by Dalethium** [comment]
I have the same issue using the master builder shovel on grass from the GKIT

https://pastebin.com/raw/BGqmQW7L

The master builder pickaxe does not work at all either.

**Comment by Dalethium** [comment]
I'd like to also note that my version is 1.16.1 and the plugin version is 7.9.19

**Comment by GC-spigot** [comment]
Fixed
