### ISSUE TITLE
[Issue] AE and LWCX bug.

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#1229]
**Describe the bug**
When a player enters the command `/cinfo`, their armor enchant effects will be 'reset'. Another player of mine had said this.
'It temporarily disables custom enchants although briefly. Like the night vis effect from my glowing helmet will disable temporarily when doing /cinfo'

**To Reproduce**
https://youtu.be/ZW0xgVMefxs

**Screenshots / Video**
My player's custom enchantments: https://imgur.com/a/gCCllwV

**Server Information (please complete the following information):**
 - Minecraft Version: 1.15.2 PaperSpigot git-Paper-322
- Plugin Version: AE 7.9.16

**Comment by GC-spigot** [comment]
What's /cinfo and what plugin has it?

**Comment by BboyZeroOne** [comment]
Its coreprotect. 
https://www.spigotmc.org/resources/coreprotect.8631/

**Comment by BboyZeroOne** [comment]
Its LWCX
https://www.spigotmc.org/resources/lwc-extended.69551/

**Comment by BboyZeroOne** [comment]
Hi, why is this ticket closed? Is it fixed?
