### ISSUE TITLE
[Issue] White Scroll

### ISSUE THREAD

**Issue by bosnav** [GC-spigot/AdvancedEnchantments#1230]
White Scrolls are not working; can't attach/apply to items, no error message from both in-game and console.

**Comment by GC-spigot** [comment]
Share some information, like your server version, mc version (using Bug Report with issues will ask you to fill information for a reason https://prnt.sc/ta05ii)

**Comment by bosnav** [comment]
mc server version 1.15.2
i also tried it on my local host server 1.16.1 and still does not seem to apply to an item

**Comment by TechnoVisionDev** [comment]
I am having the same issue. My server is 1.8.8 but whitescrolls do not work whatsoever. They act as if they are just renamed paper.

**Comment by GC-spigot** [comment]
Fixed
