### ISSUE TITLE
[Issue]Blocktrak not working if there's no mining enchants in the config

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#1231]
**Describe the bug**
Blocktrak not working if there's no mining enchants in the config

**To Reproduce**
Remove all minings enchants from the config

**Screenshots / Video**
/

**Server Information (please complete the following information):**
 - Minecraft Version: Paper 1.8.8
- Plugin Version: 7.9.19

**Comment by GC-spigot** [comment]
Fixed
