### ISSUE TITLE
[Issue] White Scrolls Do Not Work

### ISSUE THREAD

**Issue by TechnoVisionDev** [GC-spigot/AdvancedEnchantments#1232]
**Describe the bug**
White scrolls cannot be applied to any items in-game. They were working fine until I recently updated the plugin to the most recent jar. And before you ask, yes I know the item needs to have custom enchantments on it. I have tried with a diamond sword, helmet, and bow all with enchants from every tier. The white scrolls just acts as renamed paper. No errors in the console or game either.

**To Reproduce**
Attempt to use a whitescroll in-game

**Server Information (please complete the following information):**
 - PaperSpigot 1.8.8
- Plugin Version 7.9.19

**Comment by vanreek** [comment]
I can confirm i've also got the issue. Started from 7.9.16

**Comment by GC-spigot** [comment]
Fixed
