### ISSUE TITLE
[Issue] Impale Enchant in Wrong Tier

### ISSUE THREAD

**Issue by TechnoVisionDev** [GC-spigot/AdvancedEnchantments#1233]
**Describe the bug**
The Impale enchant is found in the legendary section of /enchants but it is colored yellow. I think it's supposed to be an ultimate enchant but was incorrectly placed into legendary.

**To Reproduce**
Get an Impale enchant from a legendary enchant book

**Screenshots / Video**
https://i.imgur.com/u7nKa4X.png
Proof ^^

**Server Information (please complete the following information):**
 - PaperSpigot 1.8.8
- Plugin Version 7.9.19

**Comment by GC-spigot** [comment]
Fixed
