### ISSUE TITLE
[Issue] AE Console Errors SPAM

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#1234]
**Describe the bug**
A spam list of console errors for AE.

**To Reproduce**
-

**Screenshots / Video**
https://pastebin.com/3JfaCENG

**Server Information (please complete the following information):**
- Minecraft Version: 1.15.2 PaperSpigot git-Paper-322
- Plugin Version: AE 7.9.19

**Comment by GC-spigot** [comment]
Fixed
