### ISSUE TITLE
[Issue] Failed to parse effect.

### ISSUE THREAD

**Issue by bosnav** [GC-spigot/AdvancedEnchantments#1235]
![image](https://user-images.githubusercontent.com/67382401/86335966-c4655600-bc81-11ea-8bc9-dc8ee708f3dc.png)
MC Version 1.15.2  Paper-375
AE plugin version latest.

**Comment by GC-spigot** [comment]
Need the error from console

**Comment by bosnav** [comment]
https://hastebin.com/ixoyematus.sql

**Comment by GC-spigot** [comment]
Fixed
