### ISSUE TITLE
[Issue] Enchanter menu not working as intended

### ISSUE THREAD

**Issue by MultiChipModule** [GC-spigot/AdvancedEnchantments#1236]
Whenever someone opens the enchanter menu they can take the items, nothing else happens.
It's the same for the tinkerer and alchemist.

`
02.07 14:11:38 [Server] Server thread/INFO MultiChipModule issued server command: /enchanter
02.07 14:11:53 [Server] Server thread/INFO MultiChipModule issued server command: /enchanter
02.07 14:12:10 [Server] Server thread/INFO MultiChipModule issued server command: /enchanter`

I don't get any error messages in the chat, just the commands.

I couldn't upload my gif so here's a giphy link:
[https://giphy.com/gifs/S85lZDrGABCU8D051m](url)

**Comment by GC-spigot** [comment]
Try restarting

**Comment by MultiChipModule** [comment]
I already restarted my server, I even put the plugin on a new server and it still has the same issue.

Could this be because I just updated my spigot version?
