### ISSUE TITLE
[Issue] Items can be taken from menus, menus not working

### ISSUE THREAD

**Issue by MultiChipModule** [GC-spigot/AdvancedEnchantments#1237]
Whenever someone opens the enchanter menu they can take the items, nothing else happens.
It's the same for the tinkerer and alchemist. Also the same for any other menu.

`
02.07 14:11:38 [Server] Server thread/INFO MultiChipModule issued server command: /enchanter
02.07 14:11:53 [Server] Server thread/INFO MultiChipModule issued server command: /enchanter
02.07 14:12:10 [Server] Server thread/INFO MultiChipModule issued server command: /enchanter`

I don't get any error messages in the chat, just the commands.

I couldn't upload my gif so here's a giphy link:
[https://giphy.com/gifs/S85lZDrGABCU8D051m](url)

 - Minecraft Version Spigot 1.16.1 
- Plugin Version 7.9.19

I have installed the plugin on a new server and still have the same problem.
The issue is not resolved by restarting.
It's also not caused by other plugins because it also happens with only this plugin installed.

**Comment by GC-spigot** [comment]
PM me on Discord GC#0830
