### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by thpafe** [GC-spigot/AdvancedEnchantments#1240]
Mining Lapis Ore with auto smelt drops ink sacs instead of lapis.

To reproduce, just mine lapis ore with auto smelt.

I found a work around for the time being, add a condition that prevents auto smelt from working on Lapis
      chance: 100
      condition:
        - '%block type% = LAPIS_ORE : %stop%'
      effects:
        - 'SMELT'

 - Minecraft Version: Paper 1.15.2
- Plugin Version: 7.9.18

**Comment by GC-spigot** [comment]
Update
