### ISSUE TITLE
[Issue] Black Scrolls not working ver. 7.9.21

### ISSUE THREAD

**Issue by ShayneBauzon** [GC-spigot/AdvancedEnchantments#1241]
**Describe the bug**
After updating the plugin to the latest version (7.9.21) which should fix the black scrolls issue not applying to items, the black scrolls still does not apply to any items. The whitescrolls work fine but the blackscrolls does not apply to any item. it does not do anything. my configuration for the blackscroll is the default. and yes, I did restart my server after updating to the latest version of the plugin.

**Server Information (please complete the following information):**
 - Minecraft Version 1.14.4 [PaperSpigot 1.14.4]
- Plugin Version [7.9.21]

**Comment by GC-spigot** [comment]
Fixed
