### ISSUE TITLE
[Issue] Scrolls not applying

### ISSUE THREAD

**Issue by BrunoR32** [GC-spigot/AdvancedEnchantments#1243]
After updating to 1.16 and using 7.9.21, we are unable to apply blackscrolls, white, randomization, etc etc to any books. 
On 7.8.10 we did not have this issue. Only after updating to 1.16.1 and AE's i believe 7.9.12 did the issue arise.

*To clarify, we went from 1.15 7.8.10 to 1.16 7.9.12, the scrolls all broke, then i updated to 7.9.21 this week to see if it fixed it, and it remained broken.

https://imgur.com/a/90MPxQv
Image shows me trying to put a randomization scroll on a book and the scroll taking the place of the book instead.

**Server Information (please complete the following information):**
 - Spigot 1.16.1
- AE 7.9.21

**Comment by GC-spigot** [comment]
Fixed
