### ISSUE TITLE
[Issue] Plugin not loading (7.9.22)

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#1245]
**Describe the bug**
The plugin don't load
https://paste.soleria.eu/folanuguxu.css

**To Reproduce**
/

**Screenshots / Video**
/

**Server Information (please complete the following information):**
 - Minecraft Version: Paper 1.8.8
- Plugin Version: 7.9.22

**Comment by kiloRs** [comment]
![image](https://user-images.githubusercontent.com/48230591/86499297-14aae980-bd50-11ea-8433-7e1e1b8f91ee.png)
same issue

**Comment by GC-spigot** [comment]
Update
