### ISSUE TITLE
[Issue] Black Scrolls not working ver. 7.9.23

### ISSUE THREAD

**Issue by ShayneBauzon** [GC-spigot/AdvancedEnchantments#1247]
**Describe the bug**
Black scrolls does not apply to items but the white scrolls work fine. I have the default configuration from when you first install the plugin

**Server Information (please complete the following information):**
 - Spigot 1.14.4
-  AE 7.9.23

**Comment by bosnav** [comment]
Same issue with mine.

Paper 1.16.1 build #44

**Comment by GC-spigot** [comment]
Fixed
