### ISSUE TITLE
Randomization scrolls not working

### ISSUE THREAD

**Issue by BrunoR32** [GC-spigot/AdvancedEnchantments#1249]
I recently submitted a bug report for all scrolls not working. 
Now issue is it's just the randomization scrolls not working on 7.9.24.
White/holy white/black/transmog all work just fine.

I tried it on spawned in books, and bought books, of varying %, nothing worked.

Attempt to put randomization scroll on all tiers of books

Can supply another screenshot if needed but issue doesnt give any in-game or console errors

Spigot 1.16, mc: 1.16.1.

**Comment by GC-spigot** [comment]
Fixed
