### ISSUE TITLE
[Issue] Add in a check to the Randomize item

### ISSUE THREAD

**Issue by EnderGamingFilms** [GC-spigot/AdvancedEnchantments#1251]
**Describe the bug**
When you use a randomizer item to re-roll the chances of an enchant, if the enchant is stacked it will delete all the stacked enchants by setting the itemstack to 1.

**To Reproduce**
Use the randomized item to re-roll any stack of enchants.

**Suggestion**
Can you just add a check that will not allow players to use the randomizer item on itemstacks larger than 1. (This should all around get rid of this issue and if you wanted you could add a new message or just reuse one of the messages in the config, either way, I don't really care about a message as long as this issue doesn't happen.)

**Server Information (please complete the following information):**
 - Minecraft Version Paper-1.15.2
- Plugin Version 7.9.26

**Comment by GC-spigot** [comment]
Fixed
