### ISSUE TITLE
[Request] Repeating Held & Effect static

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#1253]
Hello,

The idea is to have the Repeating type combined with HELD & EFFECT STATIC types.

Like giving "slowness" for a random time, with WAIT, etc...

**Comment by GC-spigot** [comment]
Those two only activate once equipped and unequipped, not constantly while wearing to sustain good performance, you're only able to do this with REPEATING enchant type https://github.com/GC-spigot/AdvancedEnchantments/wiki/Æ-Repeating-Enchantments-(timed)
