### ISSUE TITLE
[Request] Add a way to take away durability from an item (REMOVE_DURABILITY_CURRENT_ITEM)

### ISSUE THREAD

**Issue by NightFuryStrike** [GC-spigot/AdvancedEnchantments#1255]
**Request Description:**
Hello, I am requesting the addition of a new enchantment effect (REMOVE_DURABILITY_CURRENT_ITEM) that allows you to remove a set amount of durability from an item. Currently we have many ways to add durability/repair items, but I cannot figure out a way for them to support negative values to remove durability/damage from only the item that executed the enchantment.

The reason I think this effect would be useful is to create powerful enchantments that cost durability upon proc, and also for creating curses that cause the item to take increased durability damage from all sources. Also could be used with the repeating effect to create powerful armor that slowly decays while worn.

Thank you for your consideration.

**Comment by BusterBoys** [comment]
You Could do 'ADD_DURABILITY:-10 %attacker%'
