### ISSUE TITLE
[Request] More tool enchantments

### ISSUE THREAD

**Issue by IITFA** [GC-spigot/AdvancedEnchantments#1258]
** Describe the Request**

I am considering the purchase of this plugin but it is missing some enchantments that I have seen in other (outdated) plugins that I have come to love.

Ax: tree felling, maybe named lumber. When cutting a tree, once broken, the entire tree is felled.

Pickaxe: 3-block high mining, 3-block wide mining, 3-block deep mining, ore mining (mine all connected ores of the same type). Should probably be separate enchantments.

Shovel: Could have the same 3-block breaking enchants as the Pickaxes.

Hoes: Ability to harvest all mature crops within a radius as determined by the enchantment level on right-click. Ability to plant on all tilled soil within a radius as determined by the enchantment level on right-click. Seeds taken from inventory. Ability to till all soil within a radius as determined by the enchantment level on right-click.

I think the addition of these enchantments would improve the plugin and would turn my hesitation into a no-brainer.

**Comment by GC-spigot** [comment]
`Ax: tree felling, maybe named lumber. When cutting a tree, once broken, the entire tree is felled.` - already in the plugin :) Called Timber.
`Pickaxe: 3-block high mining, 3-block wide mining, 3-block deep mining, ore mining (mine all connected ores of the same type). Should probably be separate enchantments.

Shovel: Could have the same 3-block breaking enchants as the Pickaxes`
These are very easy to make yourself, `CUSTOM_TRENCH:3:1:1` and you could copy paste the default `Detonate` enchantment and change items for which it applies.

`Hoes: Ability to harvest all mature crops within a radius as determined by the enchantment level on right-click. Ability to plant on all tilled soil within a radius as determined by the enchantment level on right-click. Seeds taken from inventory. Ability to till all soil within a radius as determined by the enchantment level on right-click.` This is already planned :)
