### ISSUE TITLE
[Issue] MINING set effect + condition = error

### ISSUE THREAD

**Issue by plusgithub** [GC-spigot/AdvancedEnchantments#1259]
When using mining with sets and a condition, spits out an error

Copy the config below

Error message:
https://pastebin.com/Czz2CFYY
Event config:
https://pastebin.com/ePU3epeZ

**Server Information (please complete the following information):**
 - Minecraft Version: TacoSpigot 1.8.8
- Plugin Version: 7.9.31

**Comment by GC-spigot** [comment]
That's only half of the condition, it should be `%block type% = CACTUS : %allow%`

**Comment by plusgithub** [comment]
Added that, still errors,
New config: https://pastebin.com/LvAQeuyq
Error: https://pastebin.com/jjDFxq2U
