### ISSUE TITLE
[Cant open admin gui #3]

### ISSUE THREAD

**Issue by AndresGoat** [GC-spigot/AdvancedEnchantments#1265]
**Describe the bug**
https://pastebin.com/65FqRsyz
**To Reproduce**
A way to reproduce the video
https://pastebin.com/65FqRsyz
**Screenshots / Video**
https://pastebin.com/65FqRsyz
**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version [e.g. 6.7.8]
Spigot version 1.8.8

**Comment by GC-spigot** [comment]
Invalid enchant's description
