### ISSUE TITLE
[Request] Have shields work with Holy White Scrolls

### ISSUE THREAD

**Issue by iMCB4** [GC-spigot/AdvancedEnchantments#1271]
Please allow holy white scrolls to work with holy white scrolls :)

**Comment by GC-spigot** [comment]
They both work already, what do you mean by it?

**Comment by iMCB4** [comment]
I just tested on the latest plugin version (7.11.0) and you can't place white scrolls or holy white scrolls on shields

Proof: https://gyazo.com/cfa5f2a5b02b86594dcc17777efee53d

**Comment by SkellyBG** [comment]
have you added shield to the items -> can-apply-to: in config file?
