### ISSUE TITLE
Obsidian destroyer + detonate [Issue]

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#1273]
**Describe the bug**
On a Pickaxe with Obsidian Destroyer and Detonate, when Obsidian Destroyer activates it will only take the single block rather than the 3x3x3/7x7x7. When OD activates with Detonate on the same pickaxe, Detonate should still activate along with it. Additionally, Telepathy seems to not work with Obsidian Destroyer either. 

**To Reproduce**
Here is what I am doing so you can replicate: use a Pickaxe with Eff5, Fort 3, Unb 3, OD 5, Telepathy 4, Haste 3, Detonate 9, and mine the End Obsidian towns from top to bottom.

**Server Information (please complete the following information):**
 - Minecraft Version: Tuinity 1.15.2
- Plugin Version: 7.10.0

**Comment by GC-spigot** [comment]
Detonate will not be possible to be implemented right now since the actual obsidian has to be 'punched' while detonate requires blocks to be mined, added support for telepathy
