### ISSUE TITLE
[Issue] STEAL_MONEY is inverted

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#1276]
**Describe the bug**
```
'STEAL_MONEY:<random number>250-750</random number> %victim%'
```
This line is taking money from the attacker to give it to the victim instead of taking from the victim to give to the attacker

**To Reproduce**
use pickpocket enchant

**Server Information (please complete the following information):**
 - Minecraft Version: Paper 1.8.8
- Plugin Version: 7.9.33

**Comment by GC-spigot** [comment]
That's how it's designed to work, steal money to the victim
