### ISSUE TITLE
Can Trench please not work with Job Reborn [Request]

### ISSUE THREAD

**Issue by FeroxDrood** [GC-spigot/AdvancedEnchantments#1277]
** Describe the Request**
Previously if you used Trench with the Miner jobs in jobs reborn you would only get paid for mining 1 block. But somewhere in an update it has been changed so that you now get paid for mining the entire 3x3 area which is super over powered and will destroy my servers economy if i re-enable trench. So what i'm asking is can you please make it so you only get paid for mining 1 block again when using trench.

**Comment by GC-spigot** [comment]
Everyone has requested support to be added for jobs / other plugins with it and sadly that's something I can't just go back.
