### ISSUE TITLE
[Issue] Tinkerer XP dupe (CRITICAL)

### ISSUE THREAD

**Issue by Hyronymos1337** [GC-spigot/AdvancedEnchantments#1279]
**Describe the bug**
If you trade a Skull with a Enchantment with the trinkerer you get Milions of XP

**To Reproduce**
Put a enchanted skull into the tinkrer

**Screenshots / Video**
https://cdn.discordapp.com/attachments/730528070162972763/732625421216252015/2020-07-14_17-48-21.mp4

**Server Information (please complete the following information):**
 - Minecraft Version: 1.16.1
- Plugin Version: latest

**Comment by GC-spigot** [comment]
Fixed, update going on spigot asap
