### ISSUE TITLE
Destruction + Self destruct enchant bug [Issue]

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#1280]
**Describe the bug**
These two enchants together deals in overpowered amount of damage and can even kill people in creative mode

**To Reproduce**
Have destruction and self destruct 3 when fighting and you'll see how overpowered it is, you can even go in a corner, let the gamemode 1 person hit you non stop and he'll die.

**Server Information (please complete the following information):**
 - Minecraft Version: Tuinity 1.15.2
- Plugin Version 7.10.2

**Comment by GC-spigot** [comment]
Ok thank you, updated these
