### ISSUE TITLE
[Issue] Jobs payment

### ISSUE THREAD

**Issue by Pandas0** [GC-spigot/AdvancedEnchantments#1283]
**Describe the bug**
In a previous update (a while ago) you fixed a bug relating to the JobsReborn plugin and it paying for every block that TRENCH mined instead of just the initial block that is really mined, as it was giving a crazy amount of money. It seems that some how that patch was reverted as JobsReborn is paying a crazy amount of money again while using TRENCH.

**To Reproduce**
Add JobsReborn to your server with the newest version of AdvancedEnchantments. Join the Miner job and mine some blocks with an enchantment using TRENCH.

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
 - Minecraft Version: 1.16.1 (Also tested on 1.15.2)
- Plugin Version: 7.10.2

**Comment by Insprill** [comment]
Fixed in the next update
