### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by rockbyo5** [GC-spigot/AdvancedEnchantments#1286]
**Describe the bug**
Can't get mobs to drop slotincreaser or orbs

**[Screenshot](https://prnt.sc/tjojr3)**
Enchantment books do drop but `slotincreaser` do not.

**Server Information:**
- Minecraft Version [paper 300]
- Plugin Version [7.10.0]
- default group names/settings.

**Comment by GC-spigot** [comment]
They aren't currently available with drops, will add in near future
