### ISSUE TITLE
[Request] Add support for SuperiorPrisons Plugin + fix ADD_ENCHANT enchantment effect

### ISSUE THREAD

**Issue by BugReporter124** [GC-spigot/AdvancedEnchantments#1289]
I'm wondering if it's possible to add support for SuperiorPrisons plugin, so that when you mine in the Prison mines, MINING enchantment effects activate. I'd also like to see that the mining feature for getting souls can work with SuperiorPrisons mines.

In addition, I was wondering if there could be a fix for the ADD_ENCHANT enchantment effects, because I can't add vanilla enchantments with ADD_ENCHANT, whether they are "safe" or "unsafe" vanilla enchantments.

For example, a pickaxe enchantment that when MINING, it does, let's say, 'ADD_ENCHANT:sharpness:1' doesn't work. Gives me a debug error.

That would be great if you could add all these features, I think this could be really beneficial, especially the latter feature about ADD_ENCHANT. I admit the SuperiorPrisons compatibility is not as useful for most people, but it's the thought that counts... plus I'm using SuperiorPrisons as my prison plugin

-Faraz_YT (badatgaming130)

**Comment by GC-spigot** [comment]
It only adds custom enchants, I'll add support for vanilla effects. For superior prison support, support is coming soon and I'll leave this ticket open until it's added.
