### ISSUE TITLE
[Request] A command that removes specific AE's and gives the player the book /ae remover

### ISSUE THREAD

**Issue by CleanCorpze** [GC-spigot/AdvancedEnchantments#1290]
** Describe the Request**
Basically this command allows players to remove a **specific** enchants from an item, however, when they remove it gives them that **specific** book in their inventory. For example, you have a chest plate with Overload 3 and Cactus 1 the player does the command  /ae remover Overload, what the are left with is a chest plate with Cactus 1 and an Overload 3 book with a random percentage.

**Comment by SkellyBG** [comment]
would like to further request that optional parameter can be added to 'fix' the success rate and destroy rate. So  /ae remover Overload give random percentage.  /ae remover Overload 100 0 for 100% success rate.
