### ISSUE TITLE
[Issue] Smelt cancels fortune enchant

### ISSUE THREAD

**Issue by CC3475** [GC-spigot/AdvancedEnchantments#1291]
**Describe the bug**
Using Fortune + Auto Smelt causes fortune to no longer work

**To Reproduce**
Put fortune + auto smelt on the same pick and mine some ores

**Screenshots / Video**
N/a

**Server Information (please complete the following information):**
 - Minecraft Version Paper 1.15.2 v378
- Plugin Version 7.10.8

**Comment by GC-spigot** [comment]
Should be resolved
