### ISSUE TITLE
[Request] Add support for grave/death chest plugins

### ISSUE THREAD

**Issue by NeuTraLZero** [GC-spigot/AdvancedEnchantments#1294]
Add support for grave/death chest plugin such as Graves, AngelChest, DeathTotems and DeathChests so that KEEP_ON_DEATH effect works properly with them

Currently if a player dies with items enchanted with KEEP_ON_DEATH effect in the armor/offhand slots, the same item will both be given back to the player instantly after death AND after they collect their grave

**Comment by Endphoenix** [comment]
Yes, I have the same request.

**Comment by GC-spigot** [comment]
Support cannot be added to grave plugins at the moment, it's either having this enchant or having a grave plugin on the server.
