### ISSUE TITLE
Souls Collected Bug and console spam.

### ISSUE THREAD

**Issue by Gilthunderx** [GC-spigot/AdvancedEnchantments#1297]
My player was harvesting a lot of cocoa using his axe ( I dont know if it works on other tools.) The axe has a soul tracker in it. Ive noticed his soul collection in his axe went absolutely high. I confirmed the bug and tested . Breaking cocoa really add +1 soul per cocoa harvest.

also this is another bug, I have this spamming my console.

https://pastebin.com/YEWbRB5b

**Server Information (please complete the following information):**\
Tuinity ( Fork of paper) 1.16

Advanceenchantment 7.11.1

**Comment by GC-spigot** [comment]
Fixed error, can you share your config.yml for the cocoa issue?

**Comment by Gilthunderx** [comment]
okay here it is . 
https://pastebin.com/iwwUxcnq

Im using the default one i think.
