### ISSUE TITLE
[Issue] Random numbers with decimals spam in chat and console

### ISSUE THREAD

**Issue by ShayneBauzon** [GC-spigot/AdvancedEnchantments#1298]
**Describe the bug**
Everytime me or my players kill a mob using a weapon with the Inquisitive custom enchantment applied to it, it shows a random number with lots of decimals in chat and in console causing it to spam random numbers in chat whenever my player grinds in my faction server.

**Screenshots / Video**
![2020-07-21_16 30 48](https://user-images.githubusercontent.com/64379231/88075625-a5385500-cbab-11ea-87e6-ce83a9db8200.png)

**Server Information (please complete the following information):**
 - Minecraft 1.14.4 [PaperSpigot 1.14.4]
- Plugin Version 7.11.4

**Comment by GC-spigot** [comment]
Update the plugin
