### ISSUE TITLE
Unbreakable Blocks with the Lava Walker Enchantment

### ISSUE THREAD

**Issue by thatsbs** [GC-spigot/AdvancedEnchantments#1304]
Sometimes with lava walker my players have encountered moments where blocks become unbreakable (even for ops or creative staff players) to the point where the only way to remove them is through commands. The best way to replicate this bug was when you have a pool of lava and pool of water next to each other, you first convert the lava in the lava pool to obsidian and then break the blocks between the two pools and letting the water flow on to that temporary obsidian. Then when the temporary obsidian goes away it gets converted to permanent obsidian but you cannot break it at all. This has also happened with other blocks such as cobblestone or stone bricks although I have not found a way to replicate those.

**Server Information (please complete the following information):**
Paper Spigot 1.16.1
Plugin Version 7.11.5

**Comment by GC-spigot** [comment]
Should be resolved
