### ISSUE TITLE
[Issue] Advanced sets leather armor does not change color

### ISSUE THREAD

**Issue by PeterDorvay** [GC-spigot/AdvancedEnchantments#1306]
**Describe the bug**
Changing the color of leather armor doesn't work, or the syntax is unknown. See screenshots below for more info.

**To Reproduce**
Open any of the default advanced sets

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/21300105/88417275-83e78c80-cd96-11ea-90fa-7aa49df9b5f5.png)
As you can see, it says that leather armor has change-able color. I have no idea how to change it. Not sure if its bugged or what.

![image](https://user-images.githubusercontent.com/21300105/88417451-c9a45500-cd96-11ea-9208-51043ccedd23.png)
These are all the things I've tried. I'm not sure if it's supposed to be a string or if its just broken.

**Server Information (please complete the following information):**
 MC version 1.16, AE version 7.10.2

**Comment by GC-spigot** [comment]
Will be resolved for next update, will include how to set colors in next update
