### ISSUE TITLE
[Issue] BREAK_TREE

### ISSUE THREAD

**Issue by Pandas0** [GC-spigot/AdvancedEnchantments#1308]
**Describe the bug**
The effect doesn't work on the new Crimson + Warped trees, likely due to them being called Stems and not logs.

**To Reproduce**
Go into 1.16.1, get an enchantment using BREAK_TREE, go into the nether and break a crimson or warped tree

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
 - Minecraft Version: 1.16.1
- Plugin Version: 7.12.1

**Comment by GC-spigot** [comment]
Resolved
