### ISSUE TITLE
[Issue]When opening the enchanter GUI and click in your top bar of inventory it will open the clickable items in the lowest bar of the enchanter GUI

### ISSUE THREAD

**Issue by thundereye2k** [GC-spigot/AdvancedEnchantments#1310]
**Describe the bug**
When opening the enchanter GUI and click in your top bar of inventory it will open the clickable items in the lowest bar of the enchanter GUI. So if you use the default config it will open up the Heroic enchanter when you click one bar under it ( So in your inventory )

**To Reproduce**
A way to reproduce the video

**Screenshots / Video**
https://gyazo.com/2a2cdfc74a2ca873c863109a92d6861a

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version [e.g. 6.7.8]
Beerspigot 1.8.8
Plugin version: Newest

**Comment by GC-spigot** [comment]
Thanks for reporting, fixed!
