### ISSUE TITLE
Fly Enchantment issue + 2 more enchantments

### ISSUE THREAD

**Issue by bvc0115** [GC-spigot/AdvancedEnchantments#1313]
**Describe the bug**
There is a small yet important issue with Fly enchantment. When you are flying and your are only one block from the ground and then you take off your boots with that enchantment you fall, but you die like you fell from a really high position. It should work like that.
For Autosmelt and Telephaty (I call it Autopickup) enchantments that works on pickaxes specially; these two while on a pickaxe they work on a way that doesn't count the blocks that you break, I can verify this by Quests where you have to break a specific amount of a specific block, meaning that you cannot longer use this tools to do this Quests

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.8.8 or R3
- Plugin Version: 7.12.2

**Comment by GC-spigot** [comment]
The flying issue is a minecraft bug and nothing can be done, I’ll look through the other issue.
