### ISSUE TITLE
Timber causes unbreakable items to break

### ISSUE THREAD

**Issue by unclesom** [GC-spigot/AdvancedEnchantments#1314]
**Describe the bug**
The timber enchant causes axes with unbreakable attribute or the abiding enchant to break like a normal axe.

**To Reproduce**
-/minecraft:give @p stone_axe{Unbreakable:1} 1    or add abiding enchant onto axe
- add timber enchant
-axe breaks faster than usual and is able to break like a normal axe

**Server Information (please complete the following information):**
 - Minecraft Version 1.16 [e.g. PaperSpigot build #123]
- Plugin Version [e.g.7.12.4]

**Comment by GC-spigot** [comment]
Fixed
