### ISSUE TITLE
[Request] TakeOff can be effective only on claimed land (GriefPrevention)

### ISSUE THREAD

**Issue by bosnav** [GC-spigot/AdvancedEnchantments#1315]
Have an option to make TakeOff enchantment effective on claimed land. (GriefPrevention)

**Comment by ChitterChatter** [comment]
Oh, that would be good if it could hook into towny too and have it for only the plot claims someone owns?

**Comment by bosnav** [comment]
hmmm. ..

**Comment by bosnav** [comment]
hmmmm

**Comment by rockbyo5** [comment]
Agreed! Would be great. Would also like compatibility with the Lands plugin (paid)

**Comment by bosnav** [comment]
im wondering when will this be implemented ... hmmmmmmm

**Comment by GC-spigot** [comment]
Can't be done without custom additions, there are no constant checks for EFFECT_STATIC, that's why it doesn't cause performance issues.
