### ISSUE TITLE
Possibility to enchant very easily with the server Enchanter

### ISSUE THREAD

**Issue by Endphoenix** [GC-spigot/AdvancedEnchantments#1316]
Please add the function that you can place the enchantments in the "Server Enchanter" directly on the handheld item.

That would make so much work easier, so you don't always have to look up the enchantment, then have to close the GUI and then enter the command.

Especially this would be very handy if you make items with a lot of enchantments.

**Comment by Endphoenix** [comment]
Ah, Ok

**Comment by GC-spigot** [comment]
Added something with latest update as well, check it out in the updates changelog

**Comment by Endphoenix** [comment]
Yes, I've seen this. I'm always checking the changelog on Spigot :).
