### ISSUE TITLE
[Issue] Console spam with inquisitive and master inquisitive

### ISSUE THREAD

**Issue by raptexalicious** [GC-spigot/AdvancedEnchantments#1318]
Both of these errors have to do with inquisitive and master inquisitive. No modifications were made to these enchantments at all. There was no update done to the plugin, it just started happening randomly at about 2:30 pm the other day. Players have also been saying the enchant does not work anymore. 

Players with admin permissions are spammed with this error: https://i.gyazo.com/c6266ba62d594e3e0fee81b1ca52f958.png

The console gets this error: https://i.gyazo.com/9a1d655139db9e9316babd553156b3c8.png 

Server information:
- Paper 1.8.8
- Version 7.12.6

Would greatly appreciate help/a fix as this has become very annoying over the course of the past day and a half! Regards.

**Comment by GC-spigot** [comment]
Show the enchant, seems like the enchantment might be faulty

**Comment by bosnav** [comment]
Me too >> https://hastebin.com/nipivulako.pl

**Comment by ExceptedPrism3** [comment]
So do I https://pastebin.com/gM4r8kWc

**Comment by GC-spigot** [comment]
Fixed
