### ISSUE TITLE
[Issue]NPE with Paradox enchant

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#1319]
**Describe the bug**
There's an NPE error with the Paradox enchant

It never happened before, i updated from a version who was released a week ago. (I'm updating AE once per week)

**To Reproduce**
Apply Paradox enchant to an Armor

**Logs**
https://paste.soleria.eu/zojibinepi.md

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8] StellarSpigot 1.8.8
- Plugin Version [e.g. 6.7.8] 7.12.6

**Comment by GC-spigot** [comment]
Fixed
