### ISSUE TITLE
[Issue] Gkits not being affected by showFirstLevel: false

### ISSUE THREAD

**Issue by TrendyPanda** [GC-spigot/AdvancedEnchantments#1323]
**Describe the bug**
When using the   showFirstLevel: false  in the config.yml in gkits it does not do this and puts a I after the enchantment.

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/56000865/89100412-ab6dd300-d3ee-11ea-81c1-0ba1a8eb608e.png)

**Server Information (please complete the following information):**
 - Minecraft Version StellarSpigot 1.8.8
- Plugin Version 7.5.0-Pre34

**Comment by GC-spigot** [comment]
Fixed
