### ISSUE TITLE
[Issue] Random Number not parsed as an Integer

### ISSUE THREAD

**Issue by EarthAgar** [GC-spigot/AdvancedEnchantments#1327]
**Describe the bug**
So basically while mining, my enchant is supposed to run:
``- 'CONSOLE_COMMAND:crystals add <random number>1-5</random number> %attacker%'``

The issue here, is that my command `/crystals` has to have the 2nd argument be an integer. The only reason the command could possibly not work, is if the 2nd argument isn't a number / integer. I've tried making a random number above and then doing %random% in place of the 2nd argument but it still fails to run the command. This can only mean it needs to be known as an integer / number properly. Also one thing to mention is, I can execute the command in the console perfectly find to also back myself up by saying it isn't a console issue. I guess another potential issue, could be that `%attacker%` isn't the proper variable for the person mining, but please let me know.

**To Reproduce**
Can't really reproduce the issue unless you want to go with me to walk you through with my code to test for yourself.

**Screenshots / Video**
Pay attention to the chat and my scoreboard. When mining and the msg sends the amount of crystals I should have got, the scoreboard doesn't change ever. I've checked with my own commands and stuff too, it doesn't change at all.
https://i.gyazo.com/5935399cc623db0d11d8787752c343e9.gif

**Server Information:**
 - Minecraft Version: 
![image](https://user-images.githubusercontent.com/27425322/89112746-76787500-d41c-11ea-8526-a22c9cd604d6.png)

- Plugin Version 7.13.1

**Comment by SkellyBG** [comment]
try using %attacker name% instead of %attacker%

**Comment by SkellyBG** [comment]
is the format /crystals add [integer] [playername]? If so, use %attacker name% instead of %attacker%

**Comment by EarthAgar** [comment]
> is the format /crystals add [integer] [playername]? If so, use %attacker name% instead of %attacker%

Will do, and yeah the syntax you guess is correct.

**Comment by EarthAgar** [comment]
> is the format /crystals add [integer] [playername]? If so, use %attacker name% instead of %attacker%

No that didn't change anything.
