### ISSUE TITLE
[Request] Double support for NEGATE_DAMAGE

### ISSUE THREAD

**Issue by SkellyBG** [GC-spigot/AdvancedEnchantments#1328]
** Describe the Request**
Currently, EXTRA_DAMAGE and NEGATE_DAMAGE's value are in hearts. However, EXTRA_DAMAGE accepts double while NEGATE_DAMAGE doesn't, making it hard to balance offensive and defensive. It would works wonder to add double support for NEGATE_DAMAGE.

**Comment by GC-spigot** [comment]
They are both the same. `NEGATE_DAMAGE` takes 1 heart as 2, half a heart as 1 in value. EXTRA_DAMAGE takes 0.5 as half a heart in value, they both can achieve same thing.
