### ISSUE TITLE
[Issue] Failed to parse

### ISSUE THREAD

**Issue by bosnav** [GC-spigot/AdvancedEnchantments#1334]
![image](https://user-images.githubusercontent.com/67382401/89146785-4ef1eb80-d587-11ea-8fe4-2c8aeb8b6182.png)

Server version: 1.16.1 Paper
AE plugin version: latest.

**Comment by GC-spigot** [comment]
Show your inquisitive enchant

**Comment by bosnav** [comment]
It also occurs on master inquisitive

https://pastebin.com/dett4hFz

**Comment by GC-spigot** [comment]
Resolved
