### ISSUE TITLE
[Issue] Action Bar Color Codes 

### ISSUE THREAD

**Issue by EarthAgar** [GC-spigot/AdvancedEnchantments#1335]
**Describe the bug**
Color codes in my enchant don't seem to work in Action Bars.

```
- 'CONSOLE_COMMAND:megive %attacker name% crystals <random number>1-5</random number>'
- 'ACTIONBAR:&7+&d%random% &d♦ %attacker%'
- 'PLAY_SOUND:BLOCK_END_PORTAL_FRAME_FILL:5:0.5 %attacker%'
```

**To Reproduce**
Use my code as is.

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/27425322/89152559-3991a880-d518-11ea-912d-ae7a5761276e.png)

**Server Information (Server Version and AE Version):**
![image](https://user-images.githubusercontent.com/27425322/89152678-765d9f80-d518-11ea-9fc5-ce45e8840407.png)

**Comment by GC-spigot** [comment]
Fixed
