### ISSUE TITLE
[Issue] Remove enchant dont refund slot of the item.

### ISSUE THREAD

**Issue by Danrique** [GC-spigot/AdvancedEnchantments#1336]
**Describe the bug**
You can test it with the default enchant "restore". It is suppose to remove the enchant and save the item, ok it happens but the slot is not refunded.

**Server Information (please complete the following information):**
 - Minecraft Version paper 1.16.1 build 131
- Plugin Version 7.13.4 Fix

**Comment by GC-spigot** [comment]
It's designed to work like that, to have a consequence, however I don't mind changing it
