### ISSUE TITLE
[Request] Ability to use %applies% placeholder in enchantment book name

### ISSUE THREAD

**Issue by Fr0sto** [GC-spigot/AdvancedEnchantments#1339]
Currently, the %applies% placeholder can only be used in the lore of enchantment book items, but it would be nice to be able to use it in the names too.
![image](https://user-images.githubusercontent.com/15222806/89210245-c4f95100-d58d-11ea-917e-e41b6999281c.png)

**Comment by GC-spigot** [comment]
Added
