### ISSUE TITLE
[Critical Issue] Repair with Custom enchant in anvil will get Creative mode

### ISSUE THREAD

**Issue by ArcadeFighter** [GC-spigot/AdvancedEnchantments#1340]
**Describe the bug**
When you put item with custom enchant into anvil, you will get creative. (via gif)

**To Reproduce**
https://gyazo.com/3bc7443c4e62a5a1be3f9319d94b9f8f

**Server Information (please complete the following information):**
 - Minecraft Version: Paper 1.12.2
- Plugin Version: 7.13.5

**Comment by GC-spigot** [comment]
Not my plugin's fault
