### ISSUE TITLE
[Issue] Item in Hand Placeholder

### ISSUE THREAD

**Issue by EarthAgar** [GC-spigot/AdvancedEnchantments#1345]
**Describe the bug**
I've been trying to use the `%<player/attacker/victim> item in hand level <enchantment>%` placeholder but it seems to not work with PAPI. I need to use it with the Math expansion to add +1 to the lvl and then make the player enchant their item to work around not having a way to upgrade an enchant for a player through console. Also I highly suggest maybe adding a command to upgrade an enchant FOR a player via console to the item the player has in hand.

**To Reproduce**
Use this command with PAPI installed. I'm on PAPI 2.10.6

**Screenshots / Video**
Here is the console error https://paste.helpch.at/uzuxohomap.apache

**Server Information:**
![image](https://user-images.githubusercontent.com/27425322/89351222-69e75d00-d666-11ea-8faa-be07818fbf66.png)

**Comment by GC-spigot** [comment]
It's not a PAPI placeholder it's AE-only
