### ISSUE TITLE
[Issue] Server Crash

### ISSUE THREAD

**Issue by AAigars** [GC-spigot/AdvancedEnchantments#1348]
**Describe the bug**
So basically, my server randomly crashed so I decided to contact my host (DedicatedMC) which told me that the cause of my crash was your plugin.

**To Reproduce**
I have no idea how to reproduce it just randomly happens.

**Screenshots / Video**
Heres the log of the plugin setting a invalid velocity which apparently causes the server to crash: https://paste.dedimc.io/afejesatol.sql

**Server Information (please complete the following information):**
 - Minecraft Version : Paper 1.16.1
- Plugin Version : 7.13.2

**Comment by GC-spigot** [comment]
What server platform? Spigot / Paper?

**Comment by AAigars** [comment]
> What server platform? Spigot / Paper? This shouldn't ever cause a crash it's just a warning, I'll add checks to prevent this but it's supposed to be a warning.

I was using Paper.
