### ISSUE TITLE
Master Inquisitive not working along with other enchants

### ISSUE THREAD

**Issue by ExceptedPrism3** [GC-spigot/AdvancedEnchantments#1349]
If Master Inquisitive is applied along with other enchants it gives the XP as if there's was no Inquisitive on it.

Master Inquisitive alone is working fine but once adding for example [ Rage ] enchant it stops working therefore if we remove the Rage enchant it still doesn't work. the only solution is to get a new sword

**Comment by GC-spigot** [comment]
What stacking / mob plugins do you have?

**Comment by ExceptedPrism3** [comment]
I don't have any, just the normal minecraft settings only thing is the **nerf-spawner-mobs: true** that is in the Spigot.yml
