### ISSUE TITLE
Soulbound Dysfunction

### ISSUE THREAD

**Issue by Yidsir** [GC-spigot/AdvancedEnchantments#1353]
Minecraft: 1.16.1
Paper: 134
AdvancedEnchantments: 7.14.9

The Soulbound enchantment is dysfunctional in two areas:
1. It produces duplicate armor (if armor is on applies list).
2. It only triggers on ONE enchanted item.

When testing:
1. Raise the chance of the enchantment to 100% to ensure that it should be triggering on all items.
2. Reduce the cooldown to ensure that it is not on cooldown when you die.
3. Ensure that the Soulbound enchant is on all of the items to be tested.

Duplicate Armor:
Make sure all_armor is on applies list and enchant the armor with it. When the armor is equipped and the enchant triggers on death, it will produce duplicate copies of the armor.
This ONLY happens when the enchant cooldown is less than 1, and the armor is equipped in the armor slot.

Only triggering once:
Soulbound only keeps all enchanted items on death when the cooldown is less than 1. If the cooldown is equal to or greater than 1, it will only trigger on one of the enchanted items on death.

**Comment by SkellyBG** [comment]
it's intended behaviour, as cooldown are universal across all items (so you can't like, have 9 swords with chain lifesteal). Cooldown can't take value under 1 (only accept integer), so it mean that there was no cooldown. 

Duplicating armor is an issue tho.

**Comment by GC-spigot** [comment]
Cannot recreate the duplication issue, any chance you got other plugins which are saving items on death?
