### ISSUE TITLE
[Issue] /asets give command not working

### ISSUE THREAD

**Issue by ShayneBauzon** [GC-spigot/AdvancedEnchantments#1355]
**Describe the bug**
I did the command /asets give <player> <set> and it won't work. I didn't do anything to the config of the armor sets. This command used to work but now it does not.  The error says "An internal error occured while attempting to perform this command"

**Server Information (please complete the following information):**
 - Paper 1.14.4
- Plugin 7.14.9

**Comment by GC-spigot** [comment]
Show the error

**Comment by ShayneBauzon** [comment]
![2020-08-12_17 58 35](https://user-images.githubusercontent.com/64379231/90002661-88cc9b80-dcc5-11ea-8558-468619ac04a5.png)
![2020-08-12_17 58 38](https://user-images.githubusercontent.com/64379231/90002667-8bc78c00-dcc5-11ea-9d4c-841903cf86db.png)

Here is a screenshot of the command that I type in chat and also the error that pops up.

Error: An internal error occured while attempting to perform this command

**Comment by gazdyy** [comment]
Do you use higher enchants for armor than the default for vanilla? Maybe it's because I have the same problem, if I use enchants higher than the default in vanilla, it tells me an error

**Comment by GC-spigot** [comment]
I'd need the error from console to tell you the issues

**Comment by ShayneBauzon** [comment]
I'll check and send you a console log and a photo

**Comment by ShayneBauzon** [comment]
Okay so here's the screenshot from my test server. Im using the default config of the plugin.
Sometimes it gives me only the helmet and chestplate but sometimes it gives me the whole armor set

![image](https://user-images.githubusercontent.com/64379231/90312974-211f8600-df3b-11ea-8c02-23ad8dc3e39c.png)

And here's the console log

![image](https://user-images.githubusercontent.com/64379231/90312988-3bf1fa80-df3b-11ea-9eb7-e40a406dc22c.png)

**Comment by ShayneBauzon** [comment]
Okay so here's the screenshot from my test server. Im using the default config of the plugin.
Sometimes it gives me only the helmet and chestplate but sometimes it gives me the whole armor set

![2020-08-15_21 07 28](https://user-images.githubusercontent.com/64379231/90312999-588e3280-df3b-11ea-8286-8a0476f81eb1.png)

and here's the console log

![image](https://user-images.githubusercontent.com/64379231/90313003-617f0400-df3b-11ea-82f4-5ca850b5dff2.png)

**Comment by GC-spigot** [comment]
Invalid enchantment level
