### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by YESSIRSK1** [GC-spigot/AdvancedEnchantments#1357]
**Describe the bug**
The Download is a corrupt jar file
**Screenshots / Video**

https://user-images.githubusercontent.com/69567099/89976038-3aaf8d80-dc1c-11ea-9d4b-817df5c5ef76.png

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version [e.g. 6.7.8]

**Comment by GC-spigot** [comment]
How do you expect to launch it? It's not an executable jar, put it in the plugins folder. That message will be displayed to all minecraft plugins as they're not exe's

**Comment by YESSIRSK1** [comment]
I put it in my plugin folder and it doesn't work in game. It says "an internal error occurred while attempting to preform this command".
