### ISSUE TITLE
[Issue] Not getting paid from Jobs plugin when effect SMELT or TP_DROPS

### ISSUE THREAD

**Issue by markusew** [GC-spigot/AdvancedEnchantments#1361]
**Describe the bug**
If players are mining blocks with a tool that has either SMELT or TP_DROPS this user does not get paid from mining the block (Jobs Reborn)

**To Reproduce**
To reproduce, be in a job that should get paid from breaking blocks and use a tool with either of those enchants to break that block. You'll notice that you don't get paid.

**Server Information (please complete the following information):**
- Tuinity 1.16.1
- AdvacedEnchantments 7.14.7

**Comment by Insprill** [comment]
@markusew @nivcoo @WhatsTheBadNews @ArnoPompio (tagging everyone to make sure y'all see it) for 8.0.0-pre21.8 I've added an experimental config option called `fire-block-break-event` under `settings` in the config.yml. When this is enabled, AE will fire a BlockBreakEvent for every block that it breaks. Since I was never able to reproduce this issue I can't say for certain, however, it's likely that this may fix this issue. I am going to leave this open for a little while in case it doesn't fix it. When y'all update please get back as to if enabling it fixes the issue.

**Comment by WhatsTheBadNews** [comment]
@Insprill

Hello, I am reporting back with mixed results:

With this setting enabled, tools with Telepathy *do* pay with Jobs! However, it seems that they pay double. For example if you are supposed to get paid $2.50 for mining stone, you will get paid $5.00 when mining stone with Telepathy. Is it possible that the BlockBreakEvent is getting fired twice? I don't know much about the technical details, but I hope this information helps.

**Comment by Insprill** [comment]
interesting. so with `fire-block-break-event` disabled, it doesn't pay at all, and with it enabled it pays double? that's really weird. I've implemented a *possible* fix for the next update. unlikely to solve it but it's worth a shot

**Comment by nivcoo** [comment]
Hum i've issue with that, look https://pics.revolis.fr/2021-04/01/21-20_1Pt6.mp4

**Comment by nivcoo** [comment]
Update: the latest update fix my previous issue but I've the same issue without pickaxe i am paid 0.48$ and with pickaxe 0.97. Thx

**Comment by nivcoo** [comment]
I have check, the event is called 2 times, i don't tried with 2 enchants on the same item if the event is called more times

**Comment by ArnoPompio** [comment]
I can confirm the event called 2 times from nivcoo when  " fire-block-break-event: true "

By the way, will there is something for the trench thing i mentioned in #1483 ? Paying for only one block instead of the 27 hem (i believe the fire-block-break have no effect on this)

**Comment by Insprill** [comment]
Alright for pre22.2 I removed this config value and added `settings.use-experimental-block-breaking` which handles breaking blocks in a completely different way. pretty confident this should solve the issue. if it does I'll make its method the default

**Comment by WhatsTheBadNews** [comment]
@Insprill This new setting is working great for me so far! 100% improvement over before. I haven't done thorough testing yet, but so far everything is working great.

**Comment by Insprill** [comment]
If any of you are running 1.8-1.11, `use-experimental-block-breaking` will now work on those versions when 8.0.0-Pre22.3 releases

**Comment by WhatsTheBadNews** [comment]
@Insprill I've updated from 8.0.0-Pre22.4 to 8.0.0-Pre22.6 and mining with Telepathy no longer pays with Jobs again despite using `use-experimental-block-breaking: true`
It was working perfectly before I updated.

**Comment by Insprill** [comment]
Alright that's not good. In 22.7 or 22.8 ill add a another option that'll change how it behaves to test multiple ways of handling it in one plugin version

**Comment by Insprill** [comment]
Ok scrap that, reworked how it works on 1.13+ again. went back to the 22.3 method and handle what caused #1849 and #1850 on my own. like always, get back with any feedback

**Comment by nivcoo** [comment]
I am using the latest version and it works if I activate: fire-block-break-event and use-experimental-block-break

**Comment by WhatsTheBadNews** [comment]
So far on 8.0.0-Pre22.9, Jobs seems to work as intended. And #1849 and #1850 don't seem to happen. 😄

Will let you know if any issues pop up over the next few days, but so far so good.

**Comment by WhatsTheBadNews** [comment]
One strange (but minor) note. Before `use-experimental-block-break` was a thing, leaves would actually pay the normal amount with Telepathy + Jobs. Not sure why, but it did when everything else didn't pay at all. Now with `use-experimental-block-break`, leaves pay double. When everything else pays the correct amount.

**Comment by WhatsTheBadNews** [comment]
@Insprill In addition to the leave issue mentioned above, we've discovered #1874

**Comment by Insprill** [comment]
yeah, I noticed #1874 a bit after 22.9's release. as for the leaf issue, that's super weird. no clue why it would be paying twice as there is only one block break event fired by the server

**Comment by ArnoPompio** [comment]
Hi, 

Would it be possible to add an option for trench that make the pay/xp for only one block in the config.yml please ? Or it's already the case with fire-block-break-event/use-experimental-block-breaking (it's this, it's not working hem) ?

**Comment by Insprill** [comment]
@ArnoPompio that isn't possible at the moment due to how it checks for if the player can break the blocks (worldguard, faction plugins, etc)

**Comment by ArnoPompio** [comment]
There is no way to use TRENCH as a mining effect and PERMISSION as a EFFECT_STATIC/HELD with the jobs.boost. permissions at the same time  ?

**Comment by Insprill** [comment]
How's experimental-block-breaking been working for y'all? Thinking about making it the default method.

**Comment by WhatsTheBadNews** [comment]
Haven't come across any major issues with it lately.

**Comment by WhatsTheBadNews** [comment]
Jobs plugin has stopped paying with TP_DROPS & SMELT again on 8.5.9

**Comment by Insprill** [comment]
#2213

**Comment by Insprill** [comment]
Experimental-block-breaking has been set as the default way of handling broken blocks for the next update. Thank you so much to all of you who helped test it <3
