### ISSUE TITLE
[Issue] Negate Damage does nothing.

### ISSUE THREAD

**Issue by Crysillion** [GC-spigot/AdvancedEnchantments#1363]
Straight-forward. I attempted to make a new enchantment like so:

defense:
  display: '%group-color% Defense'
  description: "Take less damage when being hit."
  applies-to: 'Armor'
  type: 'DEFENSE;DEFENSE_MOB'
  group: 'ULTIMATE'
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - 'NEGATE_DAMAGE:1 %victim%'
    2:
      effects:
        - 'NEGATE_DAMAGE:2 %victim%'
    3:
      effects:
        - 'NEGATE_DAMAGE:3 %victim%'
    4:
      effects:
        - 'NEGATE_DAMAGE:4 %victim%'
    5:
      effects:
        - 'NEGATE_DAMAGE:5 %victim%'

It's implied that this negates damage by flat numbers, so NEGATE_DAMAGE:1 for example means I receive 1 less damage. However, when I attack myself on a second client, there is no reduction whatsoever. NEGATE_DAMAGE:5 also yielded the same result.

Am I misunderstanding how this enchant works?

**Comment by GC-spigot** [comment]
It works on a % of damage, 5% wouldn't make a difference
