### ISSUE TITLE
[Issue] TP DROPS not putting items inventory when inventory is full, even if a stack of the item is not full yet

### ISSUE THREAD

**Issue by johnyuki** [GC-spigot/AdvancedEnchantments#1364]
**Describe the bug**
With the TP DROPS effect, or more specifically the Telepathy enchantment, ores don't get put in to the inventory if the inventory slots have been filled. This happens even if the stack isn't full. So if I have a stack of 32 Iron ore in my inventory and I mine some Iron ore, the ore gets dropped on the floor rather than being added to the stack of 32 that's sitting in my inventory. It seems like the items get teleported behind the player when mining an ore with a full inventory.

**To Reproduce**
Fill inventory with non-full stacks of Iron ore (or any other ore), and then mine the ore. It will get dropped on the floor rather than being added to the inventory.

**Screenshots / Video**
https://streamable.com/7vooy0

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. Paper/Tuinity 1.15.2]
- Plugin Version [7.2.5]

**Comment by GC-spigot** [comment]
Fixed
