### ISSUE TITLE
[Issue] TRENCH effect doesn't take in to account Towny plots

### ISSUE THREAD

**Issue by johnyuki** [GC-spigot/AdvancedEnchantments#1365]
**Describe the bug**
I guess this could be a feature request more than a bug report but still. When players break a plot outside of their plot, the TRENCH effect will actually break blocks outside of the plot that is owned by the user. I assume this will be an issue in other plot protection plugins such as WorldGuard too. 

**To Reproduce**
Place two blocks - one on either side of a chunk boundary. Make sure only one of the chunks is owned by the player, and the other one is owned by someone else. Break the block that is in the owned chunk, and the blocks inside the unowned chunk will get broken too.

**Screenshots / Video**
In this video I asked a user to break the dirt blocks I placed. One of the blocks was in his plot, but the chunk that the rest of the dirt blocks were in was not owned by this player. 
https://streamable.com/9ef119

**Server Information (please complete the following information):**
 - Minecraft Version [Paper/Tuinity 1.15.2]
- Plugin Version [7.2.5]

**Comment by GC-spigot** [comment]
Added
