### ISSUE TITLE
KILL_MOB + DROP_HEAD [Request]

### ISSUE THREAD

**Issue by Pandas0** [GC-spigot/AdvancedEnchantments#1366]
** Describe the Request**
Currently the system with KILL_MOB + DROP_HEAD works and will drop a skull, BUT the plugin sources for the IGN of the mob so like a rabbit will drop the skull of the user that has the IGN "Rabbit". Some of the mobs are accurate with this system, but a few of them are not.

I suggest that, if possible, KILL_MOB + DROP_HEAD will source from MHF_<Name> or some other method that would drop the mobs skull as I think almost every mob is stored using that system so MHF_BLAZE will give a blaze skull and MHF_RABBIT will give a rabbit skull instead of the skill of the user with the "Rabbit" IGN.

**Comment by Insprill** [comment]
Added
