### ISSUE TITLE
[Issue] Telepathy + silk touch bed dupe

### ISSUE THREAD

**Issue by minemalia** [GC-spigot/AdvancedEnchantments#1367]
**Describe the bug**
When enchanting a pickaxe with Telepathy and Silk touch and mining a bed, the bed gets duped.

**To Reproduce**
Enchant your pickaxe with silktouch, and telepathy 4, and try to mine a bed.

**Screenshots / Video**
https://www.youtube.com/watch?v=Oocu7HQ8XOA&feature=youtu.be
Telepathy enchant: https://pastebin.com/PTKs12Q6

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. Tuinity 1.16.1]
- Plugin Version [e.g. 7.15.6]

**Comment by GC-spigot** [comment]
Fixed
