### ISSUE TITLE
Items given through commands do not drop if inventory is full

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#1368]
**Describe the bug**
If a player has a full inventory and is supposed to get an item (e.g. ae giveitem <player> mobtrak 1), the item is not dropped. This is particulary annoying, since we added a few AE items to kits, but there is no way for us to check if a player actually got the item or if their inventory was full.

**To Reproduce**
Fill your inventory with items, give an AE item through a command (e.g. enchanted book or dust)

**Server Information (please complete the following information):**
 - Minecraft Version: Paper 1.15.2-378
 - Plugin Version: 7.15.6

**Comment by GC-spigot** [comment]
Resolved
