### ISSUE TITLE
[Issue] Failed to show 'xxxx' particle

### ISSUE THREAD

**Issue by Cryper** [GC-spigot/AdvancedEnchantments#1373]
We try to use some particles as effect. But it always says for example
"Failed to show 'villager_happy' particle"

The particle "villager_happy" is a Minecaft Particle and avaible for 1.16.1 . So please dont respond with " Check the Particle Name for your Version"

**Comment by GC-spigot** [comment]
That's not correct, here are the correct names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
It's 'VILLAGER_HAPPY'

**Comment by Cryper** [comment]
Wont work either
