### ISSUE TITLE
[Issue] Magic dust percentage able to exceed 100% using alchemist

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#1375]
Hello there,

As the title says, one is able to exceed 100% magic dust using the alchemist combining feature. While this is not a serious issue, it does not make sense for a percentage chance exceeding 100%, and a fix should be fairly easy to implement, by either setting it to 100% or not allowing the combination to go through.

To illustrate this, I have combined 2 60% magic dusts in the screenshot below:
![image](https://user-images.githubusercontent.com/17891302/90454457-2817d700-e0a8-11ea-801d-125972678808.png)

Server version: git-Paper-131 (MC: 1.16.1)
Plugin version: 8.0.0-Pre9

Thank you in advance for your time.

**Comment by GC-spigot** [comment]
Fixed
