### ISSUE TITLE
[Issue] Plugin is Disabling

### ISSUE THREAD

**Issue by EarthAgar** [GC-spigot/AdvancedEnchantments#1382]
**Describe the bug**
I installed AE 8.0 PRE-12 for the first time on another one of my local hosted servers and I got an error basically saying the plugin is disabled. There is no other errors in the logs about AE, only the time I try using the command.

**To Reproduce**
Just use the same versions I'm on.

**Screenshots / Video**
https://hasteb.in/nomasuxa.sql

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version [e.g. 6.7.8]
![image](https://user-images.githubusercontent.com/27425322/90581983-78af3300-e181-11ea-87f2-36ea907f042c.png)

**Comment by ChitterChatter** [comment]
Hmm I am too having the same issue :(
