### ISSUE TITLE
[Request] Add Hoe enchantments

### ISSUE THREAD

**Issue by johnyuki** [GC-spigot/AdvancedEnchantments#1385]
** Describe the Request**
The server I play on used to use a different CE plugin, and that plugin had Hoe enchantments such as: 

 - Tills soils in a 3x3 area
 - Breaks crops in a 3x3 area
 - When breaking crops, automatically replants the seeds from your inventory assuming you have the seeds there

It would be nice to see those in this plugin

**Comment by thewillmoss** [comment]
This would definitely be useful. Is it possible to commission this feature?
