### ISSUE TITLE
Telepathy + Autosmelt + Fortune not working [Issue]

### ISSUE THREAD

**Issue by PeterDorvay** [GC-spigot/AdvancedEnchantments#1387]
**Describe the bug**
When drops are sent to your inventory using the telepathy enchantment and autosmelt enchantment, they aren't multiplied by the vanilla fortune enchantment.

Telepathy + Fortune work individually
Autosmelt + Fortune work individually
But Telepathy + Autosmelt + Fortune don't work all together.

**To Reproduce**
run `/aegive GC diamond_pickaxe 1 fortune:3 telepathy:1 autosmelt:3` then break a diamond ore with that. It will always drop 1 diamond.

**Screenshots / Video**
Not necessary in my opinion.

**Server Information (please complete the following information):**
 - Spigot 1.16.1
- Advanced Enchantments 8.0.0pre9

**Comment by PeterDorvay** [comment]
Just a bit more information that I've found: I have my autosmelt chance set to 100, so that ores will always be smelted. It seems that this is the issue. If it tries to autosmelt a diamond, it will only drop one. If I remove the autosmelt enchantment, then fortune will trigger, and it will drop multiple diamonds.

**Comment by GC-spigot** [comment]
Fixed
