### ISSUE TITLE
Failed to parse effect 'PULL_AWAY' for enchant 'quiver'[Issue]

### ISSUE THREAD

**Issue by ExceptedPrism3** [GC-spigot/AdvancedEnchantments#1389]
Its says this after executing it:
Failed to parse effect 'PULL_AWAY' for enchant 'quiver'
Argument included with effect: '[9.0]'

**Comment by ExceptedPrism3** [comment]
Also there's another error with bidirectionalteleportation:

Failed to parse effect 'PULL_CLOSER' for enchant bidirectionalteleportation
Argument included with effect '[5.0]'
additional information: 'Excess velocity, lower the effect value..'

**Comment by GC-spigot** [comment]
Show the error from console

**Comment by ExceptedPrism3** [comment]
Nothing is printed in the console :c
