### ISSUE TITLE
[Request] Critical hit condition

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#1398]
Hello again,

A Minecraft combat feature that is very useful in many cases is critical hits, where you jump and attack while falling to deal 50% more damage. A condition that detects if a hit is critical would be cool. To only apply effects or increase the chance of effects on a critical hit would make combat more interesting I'd say.

Thanks for your time.

**Comment by Skullslice** [comment]
I want this too
