### ISSUE TITLE
[Issue] Permission problem

### ISSUE THREAD

**Issue by Nisutec** [GC-spigot/AdvancedEnchantments#1403]
**Describe the bug**
When I give a group the permission `ae.admin` or `ae.give` the group can’t use the `/ae admin` or `/ae giveitem` command without the `ae.help` permission. 

**To Reproduce**
- GIve a player the `ae.admin` permission.
- Let the player run `/ae admin`.

**Screenshots / Video**
https://www.youtube.com/watch?v=mhRSKXlQCik

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.16.1
- Plugin Version: 8.0.0-Pre25

**Comment by johnyuki** [comment]
Yep I'm having the same problems

**Comment by GC-spigot** [comment]
You need to add ae.help as well

**Comment by Nisutec** [comment]
@GC-spigot is this problem fixed ?
