### ISSUE TITLE
Armor enchants - Hearts bug

### ISSUE THREAD

**Issue by veltrium** [GC-spigot/AdvancedEnchantments#1407]
![image](https://user-images.githubusercontent.com/70343689/91487776-4a65dd80-e87c-11ea-9281-c33497e9963f.png)

Hi, 
I have just bought this pl and i noticed that when you put a armor (I'm using the available kits on /gkits) it gives you a full row of extra hearts, but if you take it off, you keep the hearts. I need to know how can i configure to make users lose extra hearts if they are not using the special armor. 
I write you on Discord, and the solution was to delete the playerdata of the world's folder, indeed, it worked, but the bug stills. 
they also told me that it was my Spigot version. im using Spigot 1.16.1, my plugins are; 

![image](https://user-images.githubusercontent.com/70343689/91488257-08896700-e87d-11ea-882f-198c30f75c51.png)

Thanks for your help ;)

Veltrium from ProyectoZero

**Comment by GC-spigot** [comment]
It’s a spigot bug, update the server jar to a newer version

**Comment by veltrium** [comment]
I did, it didn't work

**Comment by veltrium** [comment]
Is there any other way to do it? i don't want to use Spigot 1.16.2. I want to use 1.16.1

**Comment by GC-spigot** [comment]
It's a spigot bug, there is nothing I can do about it. When you change the server jar delete your playerdata as well. Use latest paperspigot 1.16.1, from my testing works fine
