### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by ImRealsy** [GC-spigot/AdvancedEnchantments#1408]
Hey,

I’m currently using AdvancedEnchants 8.0.0 pre20 and it’s come to my attention that the holy white scroll isn’t keeping items in inventories on death. I understand this is only a test version but just thought I’d let you know in case you haven’t already had a look at it :)

thankyou for the awesome plugin

server version: paperspigot 1.16.1

**Comment by GC-spigot** [comment]
Make sure there's no other plugins interfering.
