### ISSUE TITLE
[Issue] Soul gems can be used in crafting recipe

### ISSUE THREAD

**Issue by dig** [GC-spigot/AdvancedEnchantments#1413]
**Describe the bug**
You can use soul gems to craft items depending on what you set the material to. For example, we have set soul gems to emerald which means the player can craft emerald blocks using soul gems and sell at the shop. Crafting using soul gems should be cancelled.

**To Reproduce**
1. Change soul gems to emerald in config.
2. You can now craft emerald blocks using soul gems.

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
 - Minecraft Version Tuinity 1.15.1
- Plugin Version 7.15.7

**Comment by GC-spigot** [comment]
Fixed
