### ISSUE TITLE
[Issue] Telepathy + Silk Touch Duplication

### ISSUE THREAD

**Issue by dig** [GC-spigot/AdvancedEnchantments#1414]
**Describe the bug**
If you have both telepathy and silk touch enchantment, you can break the top half of a door and it will duplicate. One door drops on the floor and other door goes into your inventory.

**To Reproduce**
1. Get telepathy on your pickaxe.
2. Get silk touch on your pickaxe.
3. Mine top half of any door, door will drop on the floor and goes into your inventory at the same time.

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
 - Minecraft Version Tuinity 1.15.2
- Plugin Version 7.15.7

**Comment by GC-spigot** [comment]
Fixed
