### ISSUE TITLE
[Issue] Weapon Enchantment Orb success rate broken

### ISSUE THREAD

**Issue by Shurelia** [GC-spigot/AdvancedEnchantments#1416]
**Describe the bug**
When you try to apply a weapon enchantment orb (enchant slot increaser) it'll always successful even if the chance is only 1%

**To Reproduce**
Get some weapon enchantment orb with 1% success (ex: /ae giveitem yourname orb 5 weapon 10 1) after that try to apply to 5 different weapon, it'll always successful even if the chance is only 1% (not sure if its broken on armor orb too)

**Screenshots / Video**
i think its not necessary

**Server Information (please complete the following information):**
 - Minecraft Version: Tuinity b360 1.16.2
- Plugin Version: 8.0.0-pre40

**Comment by GC-spigot** [comment]
Fixed
