### ISSUE TITLE
[Issue] Error on command usage

### ISSUE THREAD

**Issue by Geekmakes** [GC-spigot/AdvancedEnchantments#1422]
Error seems to be random, after using the /e command possibly others I don't think there are any effects ingame.

https://pastebin.com/xu5f3HXj 
 
I've been getting it for a while now (at least the last 10 versions) this is from 8.0.0-Pre44 but I've seen it before.
Paperspigot 1.16.2 (178)

EDIT:
Also seems to happen with /tinkerer
https://pastebin.com/2uNvJgzv

Maybe also an issue with tables: https://pastebin.com/rKDyUdm4

**Comment by GC-spigot** [comment]
Fixed
