### ISSUE TITLE
[Issue] Attempting to apply any enchant to an item fails and throws a console error in 1.16.2

### ISSUE THREAD

**Issue by Fr0sto** [GC-spigot/AdvancedEnchantments#1424]
**Describe the bug**
Attempting to apply a custom enchantment book (any) to any item item does not work, and shows an error in console.

**To Reproduce**
Enchantments.yml https://pastebin.com/F9ZnUBSt
Config.yml https://pastebin.com/3Jr0FB8z

**Error**
`02.09 08:56:44 [Server] ERROR Could not pass event InventoryClickEvent to AdvancedEnchantments v8.0.0-Pre45
02.09 08:56:44 [Server] INFO java.lang.NullPointerException: Failed to find Poisoned enchantment
02.09 08:56:44 [Server] INFO at n3kas.ae.api.AEAPI.applyEnchant(AEAPI.java:338) ~[?:?]
02.09 08:56:44 [Server] INFO at n3kas.ae.globallisteners.listeners.ClickListener.onClicks(ClickListener.java:766) ~[?:?]
02.09 08:56:44 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor611.execute(Unknown Source) ~[?:?]
02.09 08:56:44 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2422) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:44 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:?]
02.09 08:56:45 [Server] ERROR Could not pass event InventoryClickEvent to AdvancedEnchantments v8.0.0-Pre45
02.09 08:56:45 [Server] INFO java.lang.NullPointerException: Failed to find Poisoned enchantment
02.09 08:56:45 [Server] INFO at n3kas.ae.api.AEAPI.applyEnchant(AEAPI.java:338) ~[?:?]
02.09 08:56:45 [Server] INFO at n3kas.ae.globallisteners.listeners.ClickListener.onClicks(ClickListener.java:766) ~[?:?]
02.09 08:56:45 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor611.execute(Unknown Source) ~[?:?]
02.09 08:56:45 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2422) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:?]
02.09 08:56:45 [Server] ERROR Could not pass event InventoryClickEvent to AdvancedEnchantments v8.0.0-Pre45
02.09 08:56:45 [Server] INFO java.lang.NullPointerException: Failed to find Stormcaller enchantment
02.09 08:56:45 [Server] INFO at n3kas.ae.api.AEAPI.applyEnchant(AEAPI.java:338) ~[?:?]
02.09 08:56:45 [Server] INFO at n3kas.ae.globallisteners.listeners.ClickListener.onClicks(ClickListener.java:766) ~[?:?]
02.09 08:56:45 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor611.execute(Unknown Source) ~[?:?]
02.09 08:56:45 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2422) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-173]
02.09 08:56:45 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:?]`

**Server Information (please complete the following information):**
- Paper 1.16.2 Build 173
- Advanced Enchantments 8.0.0 Pre-45

**Comment by GC-spigot** [comment]
The enchantments are supposed to be in `lowercase`, e.g. 'Poisoned' -> `poisoned` in enchantments.yml
