### ISSUE TITLE
[Issue] Detonate bugging out another plugin

### ISSUE THREAD

**Issue by b01w** [GC-spigot/AdvancedEnchantments#1426]
"It's because something on his end is resetting the itemmeta of the actual item
cause when testing it gets applied and then instantly reset after
and its deffo his plugin - since items without custom enchants work fine - and items with enchants dont 

then when you i uninstall the plugin - even if they still have the enchants or nbt or whatever it works fine, so its something on his end messing with it"
Is what hes told me
Hes narrowed it down to only being the detonate enchant on the pickaxe
No other enchantment does this, could you please fix

"Adding a persistent data container to an item"
Is what hes trying to do
Since he runs off a similar system which involves vessels (Custom enchantments) which give you unique abilities like advanced enchantments do
```
public static void increaseThrallsKilled(ItemStack pickaxe) {
        if(!Main.hasTag(pickaxe, "ThrallsKilled", PersistentDataType.INTEGER)) return;
        int i = (int) Main.getTag(pickaxe, "ThrallsKilled", PersistentDataType.INTEGER) + 1;
        Main.removeTag(pickaxe, "ThrallsKilled", PersistentDataType.INTEGER);
        Main.addTag(pickaxe, "ThrallsKilled", i, PersistentDataType.INTEGER);
    }
```
Is the code hes using
"Runs this method to begin with on the pickaxe. and then the remove, has, and add tags just adjust the itemmetas persistent data containers like this: "
```
@SuppressWarnings("unchecked")
    public static ItemStack addTag(ItemStack item, String key, Object value, @SuppressWarnings("rawtypes") PersistentDataType pdt) {
        NamespacedKey key1 = new NamespacedKey(Main.getPlugin(Main.class), key);
        ItemMeta itemMeta = item.getItemMeta();
        itemMeta.getPersistentDataContainer().set(key1, pdt, value);
        item.setItemMeta(itemMeta);
        return item;
    }
```
"The same goes for the other two methods."

**Comment by Coolfire02** [comment]
Damn, 10 days ago and no response from GC, he's getting inactive af lol

**Comment by GC-spigot** [comment]
> Damn, 10 days ago and no response from GC, he's getting inactive af lol

it was resolved before your reply
