### ISSUE TITLE
[Request] Include custom AE items in more locations

### ISSUE THREAD

**Issue by baesik** [GC-spigot/AdvancedEnchantments#1428]
It would be great to have AdvancedEnchantments add the custom items to dungeon chests and additionally McMMO fishing rewards.

This would provide an organic method to acquiring these items, rather than an admin having to run a command to give players said items. Additionally, support for Paper's auto-replenishing lootables would be awesome as well. 

[Link to Paper's documentation on "lootables" configuration options.](https://paper.readthedocs.io/en/latest/server/configuration.html#lootables)

Edit: Would like to clarify things like white scrolls, trakers, etc etc.

**Comment by Insprill** [comment]
Added in pre23.0
