### ISSUE TITLE
[Issue] I get this message on my server  Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### ISSUE THREAD

**Issue by SnickoDeadMC** [GC-spigot/AdvancedEnchantments#1431]
**Describe the bug**
Not so much a bug, but I cannot use the plugin at all as I have it on my testing server and the main server yet now they are all locked out and won’t be enabled.

I am a new user, and this makes things very frustrating...

**Comment by GC-spigot** [comment]
Has this been fixed for you?
