### ISSUE TITLE
[Request] Add support for AutoLooting from Graves and AngelChest

### ISSUE THREAD

**Issue by NeuTraLZero** [GC-spigot/AdvancedEnchantments#1432]
** Describe the Request**
Make AutoLooting (auto equip everything from your grave) from [Graves](https://www.spigotmc.org/resources/graves.74208/) and [AngelChest](https://www.spigotmc.org/resources/1-12-1-16-angelchest.60383/) correctly use ArmorEquipEvent, so that Armor effects work immediately after looting instead of after re-logging or re-equipping

**Comment by GC-spigot** [comment]
Unfortunately can't add this with those plugins
