### ISSUE TITLE
[Request] Offset TRENCH radius based on direction

### ISSUE THREAD

**Issue by baesik** [GC-spigot/AdvancedEnchantments#1436]
It would be ideal to have the TRENCH effect to apply in regards to where the player is facing.

Currently: A "CUSTOM_TRENCH:3:3:1" would mine a 3x3 square only one block deep. But if you look up and mine above you, it won't account for the player looking up.

Instead, the desired effect would be if you looked up and mined, it will mine a 3x3 square only 1 block up.

Example video:
https://youtu.be/D471n2D8m3Q

**Comment by GC-spigot** [comment]
Use CUSTOM_TRENCH

**Comment by GC-spigot** [comment]
I’ll explain how in a bit

**Comment by baesik** [comment]
Thanks, hopefully your write up will solve this.

**Comment by baesik** [comment]
I'm anxious to see how to solve this!


> I’ll explain how in a bit
> […](#)
> On 2020-09-07, at 09:22 AM, baesik ***@***.***> wrote: ﻿ It would be ideal to have the TRENCH effect to apply in regards to where the player is facing. Currently: A "CUSTOM_TRENCH:3:3:1" would mine a 3x3 square only one block deep. But if you look up and mine above you, it won't account for the player looking up. Instead, the desired effect would be if you looked up and mined, it will mine a 3x3 square only 1 block up. Example video: https://youtu.be/D471n2D8m3Q — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by GC-spigot** [comment]
I see now, wasn't able to see the video back then but I'll add this for next update with custom trench

**Comment by baesik** [comment]
I don't believe this was ever implemented. For now I'm having to rely on another plugin to achieve the desired behavior.

**Comment by baesik** [comment]
Tagging @Insprill because you seem to be managing the plugin currently.

**Comment by Insprill** [comment]
Looks like it was implemented for yaw with CUSTOM_TRENCH, but not pitch. Do you need pitch?

**Comment by baesik** [comment]
Thanks for the reply.

I guess I would? I'm not sure how else to describe what I'm looking for. ExcellentEnchants has a "tunnel" enchantment that accounts for the player looking up vs looking forward.

**Comment by baesik** [comment]
Can this issue be re-opened please?
