### ISSUE TITLE
Custom enchantments with the enchantment table don't work

### ISSUE THREAD

**Issue by Endphoenix** [GC-spigot/AdvancedEnchantments#1438]
**Describe the bug**

If I try to get custom enchantments through the Enchanting Table, I don't get any.

And yes, I allowed it in the "enchantmentTable.yml". It doesn't work in creative mode as it does in survival mode. No matter what I try, I always don't get custom enchantments, only vanilla enchantments.

**Screenshots / Video**

https://imgur.com/a/6zYonzr

Also here the Plugin Folder:

[AdvancedEnchantments.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/5184102/AdvancedEnchantments.zip)

**Server Information:**
 - Minecraft Version: Spigot 1.14.4
 - Plugin Version: AdvancedEnchantments-8.0.0-Pre2.0

**Comment by Endphoenix** [comment]
And no, there aren't any errors in console.

**Comment by baesik** [comment]
While I don't know specifics of how it's calculated, the pool of possible enchants changes according to rarity. 

Try changing the enchantmenttable.yml chance to 100 and then try lower level enchants to see if any come up.

**Comment by GC-spigot** [comment]
Is the issue that it doesn't work in creative or in both?

**Comment by Endphoenix** [comment]
> Is the issue that it doesn't work in creative or in both?

It doesn't worl in both.

**Comment by Endphoenix** [comment]
Does you know now what the issue is?

**Comment by Endphoenix** [comment]
Ok it works
