### ISSUE TITLE
Detonate can break barrier breaks

### ISSUE THREAD

**Issue by unclesom** [GC-spigot/AdvancedEnchantments#1439]
The enchantment ,detonate, can break barrier blocks if it is in the 3x3 radius when breaking blocks. 

To recreate: 
Place barrier block next to a grass block, break the grass block with a pick that has detonate. The barrier block will break and can be collected.

**Server Information (please complete the following information):**
 - 1.16.2 [e.g. PaperSpigot build 184]
- Plugin Version [8.0.0-Pre46]

**Comment by GC-spigot** [comment]
Add `BARRIER` to 'trench-blacklist' in config.yml (bottom of the file), I'll add it to the default configuration but you will need to do this as well: https://prnt.sc/udfnqj
