### ISSUE TITLE
[Issue] Item Nametags can be used as actual name tags.

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#1441]
Hello again,

Like the title describes, when item nametags can be right clicked on mobs and used as normal nametags. This is an issue because nametags are usually quite rare, and should not be able to be bought from shops at a price. I understand that this is not too large of an issue for the plugin itself, but if you could get it fixed soon that would be nice.

Thanks for your time.

**Comment by GC-spigot** [comment]
Fixed
