### ISSUE TITLE
[Request] FOOD Event

### ISSUE THREAD

**Issue by CptPICHU** [GC-spigot/AdvancedEnchantments#1443]
Hi there!

So i wanted to create enchants for food. (yes i'm serious) and it works fine until you wanna trigger an echant.
There seems to be no FOOD Event to trigger the Enchant.
RIGHT_CLICK would cheat it and ITEM_DESTROY does not trigger it as it seems.

So i'd wish for a FOOD Trigger. Just like ATTACK or DEFENSE or REPEATING.
Would be great! 
(Also the enchant should trigger once, even if the food gets consumed)
Cheers!
-Pichu

**Comment by Insprill** [comment]
Added for 21.5
