### ISSUE TITLE
[Issue] CONSOLE_COMMAND dont work

### ISSUE THREAD

**Issue by Cryper** [GC-spigot/AdvancedEnchantments#1447]
**Describe the bug**
We try to get the Mob Head with CMI (Cause if we just do "DROP_HEAD" , the player Head called MobName will be dropped)
Enchantment:
effects:
        - 'CONSOLE_COMMAND cmi mobhead %attacker name% %victim name%'
**Screenshots / Video**
https://prnt.sc/ufm97h
https://prnt.sc/ufm9h9

**Server Information (please complete the following information):**
 Spigot 1.16.2 (paper-186)
Plugin Version 8.0.0 Pre 2.4

**Comment by GC-spigot** [comment]
It's `- 'CONSOLE_COMMAND:cmi mobhead %attacker name% %victim name%'`, the `'CONSOLE_COMMAND:cmi'` part specifically

**Comment by Cryper** [comment]
Still dont work. "Can't determine mob type from Cryper96 variable"

**Comment by GC-spigot** [comment]
That’s self explanatory, you put attacker name where mob name should be

**Comment by Cryper** [comment]
I already switched them, same result
