### ISSUE TITLE
Aiming Enchant

### ISSUE THREAD

**Issue by Cypphi** [GC-spigot/AdvancedEnchantments#1454]
** Describe the Request** Add an enchant that allows arrows to go towards players, you'll need a way to add effects to an arrow in-air to do that tho. So this is actually 2 suggestions since I would love to see effects on arrows in-air too.

So basically: a way to add effects to an bow enchant working on arrows that are in-air and didn't hit a target yet, if it's not added yet maybe also make it so it's possible to execute effects when an arrow hits anything, for example a wall. This would be useful for creating enchants such as "Aiming" which can be used to have a better aim since arrows will go to the closest target to where you're looking.

Thanks already :)

**Comment by Insprill** [comment]
Added in the next update
