### ISSUE TITLE
[Issue] Custom Weapons chance

### ISSUE THREAD

**Issue by AbooseYou** [GC-spigot/AdvancedEnchantments#1457]
Custom Weapons chance don't feel right when i mined 400 blocks with a 1% and a 90% the 1% pick got more items
below is imgs of what i got and the configs i used so you can test it

Img
1% Chance - https://i.imgur.com/MKdqUuy.png
90% Chance - https://i.imgur.com/IfLPtAg.png

Configs
1% Chance - https://paste.helpch.at/biqogunagi.bash
90% Chance - https://paste.helpch.at/mamayupime.bash

Armor
https://paste.helpch.at/loqiwiwofu.bash

 - Minecraft Version Ispigot 1.8.8
- Plugin Version 8.0.0-pre3.3

**Comment by AbooseYou** [comment]
So any info on this?

**Comment by ludgart** [comment]
Hello,

i have the same problem. I'm using the AdvancedEnchantments-8.0.0-Pre11.7 version. I tried it with 100% and it worked about once every 30 seconds. I also tried to add the "cooldown" option without luck.

A hotfix would be appropriate after 30 days.

Regards
ludgart

**Comment by GC-spigot** [comment]
Fixed, sorry it took so long! Working through a backlog.
