### ISSUE TITLE
[Issue] When an Advanced Enchantment fails the item gets deleted

### ISSUE THREAD

**Issue by cantercrow** [GC-spigot/AdvancedEnchantments#1459]
**Describe the bug**
When an Advanced Enchantment fails the item gets deleted

**To Reproduce**
add an Advanced enchantment to an item and it fails, the item you are trying to add it too gets deleted.

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version Paper 1.15.2
- Plugin Version [e.g. 6.7.8] 1.2.8

**Comment by GC-spigot** [comment]
That is the right outcome, if you want it disabled set `destroy.destroy-item` (config.yml) to false
