### ISSUE TITLE
[Issue] Slot increasers do not work

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#1461]
Hello there,

In the latest pre-release version, there is an issue where slot increasers do not work. Upon trying to apply a slot increaser to a brand new diamond sword (in survival), the message for slots.message in config.yml will appear in chat, even though by default all weapons have 6 slots defined by slots.max. Players do not have the ae.limit permission defined.

Server Version: Paper 191 (MC 1.16.3)
AE Version: Pre4.0

Thank you for your time.

**Comment by GC-spigot** [comment]
It needs custom enchants applied first to limit application from items which cannot have enchants, i'll fix this message
