### ISSUE TITLE
[Issue] Renametag does not accept colors

### ISSUE THREAD

**Issue by WolverStones** [GC-spigot/AdvancedEnchantments#1465]
**Describe the bug**
if I use renametag and put on it, for example &6, the color will not appear as a color but only text without color

**Server Information (please complete the following information):**
 - Minecraft Version git-Paper-198 (MC: 1.16.3)
- Plugin Version 8.0.0-Pre3.9

**Comment by GC-spigot** [comment]
Depends on your chat plugin, colors are removed by it before they come through to my plugin
