### ISSUE TITLE
Add the option to change the command alias /ae

### ISSUE THREAD

**Issue by cantercrow** [GC-spigot/AdvancedEnchantments#1470]
** Describe the Request**

I would like to use AdvancedEnchantments with another plugin but both your plugin and the other one use /ae for commands, can the option like other plugins to choose the alias 
.
thanks

**Comment by myiume** [comment]
You can modify your aliases by opening the plugin jar with something like WinRar and modifying the ae alias from the plugin.yml file in the archive.
