### ISSUE TITLE
[Issue] Add Support for Lands

### ISSUE THREAD

**Issue by Endphoenix** [GC-spigot/AdvancedEnchantments#1471]
**Describe the bug**
With the Plugin "Lands" you can create your land and set flags for specific areas. It would be very nice if this flags would work with enchantments like detonate. 

**To Reproduce**
A way to reproduce the video

/

**Screenshots / Video**

/

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.14.4
- Plugin Version 8.0.0-Pre4.5

**Comment by Endphoenix** [comment]
Why did you closed the issue?

**Comment by GC-spigot** [comment]
Not plans for adding support with lands flags at the moment

**Comment by Endphoenix** [comment]
Yeah but then you could add a label like "wontfix" and not close the issue
