### ISSUE TITLE
[Request] Search option and organizational options

### ISSUE THREAD

**Issue by EchocallingEarth** [GC-spigot/AdvancedEnchantments#1479]
Feature Request Plugin Side (not website side)

1st - Adding the option to search through books when using the /ae admin command. This would be very helpful to admins when seeking to give a specific book or a book for a specific item such as boots. 

2nd, Organization options, this would allow the admin to change the order items appear in with the variations being alphabetic, by enchantment relations (meaning that enchantments of the same tier would be grouped together) or a third option organizing by enchanting type (example: all boot enchantments are together, etc). It is important that the organization be an in-game changeable feature as it may need to be changed based on how it is being used. 

Please note by implementing the second organizational feature you could avoid the need for a search option however I believe having search and organizing would be very very beneficial to all owners of the plugin as well as the admins who use it.

**Comment by Insprill** [comment]
The first one has been added. They currently just sort alphabetically. Will add a button to cycle through other sorting options
