### ISSUE TITLE
[Request] Jobs Reborn support

### ISSUE THREAD

**Issue by ArnoPompio** [GC-spigot/AdvancedEnchantments#1483]
**Describe the Request**
So, I already did a issue about Trench and the money problem, but I believe a complete Jobs Reborn support would be better.

Being able to choose **if we can get the boosted money or not with the enchantments would be good**. For example : 

**With Trench**, when we mine with it, giving the money for the 27 blocks mined (if it's a 3x3x3 Trench) or only for one (the first block that we mined)

**With Guardians, Walking Dead or Blaze**, when our mobs spawn, killing these and earn money or not. 

I hope that you understood what i meant heh.
Thanks a lot for your work !

**Comment by ArnoPompio** [comment]
After thinking a little, I had an idea how to implant it :

So first, you will need the api (I believe) : https://github.com/Zrips/Jobs

Then, you can add some effects to the enchantments ones (so with FLY, PLAYER_COMMAND, REPAIR,...) : 
- JRMONEYMULTIPLY: (coefficient) (time)
- JRPOINTMULTIPLY: (coefficient) (time)
- JREXPMULTIPLY: (coefficient) (time)

In these effects, you put a number (coefficient) to multiply the money that gets the player by using the enchantment. It could be 0.1 (the total of the money is divided by 10) or 2.0 (the total is multiplied by 2) (anyway, it's basic maths).
There is a (time) to know how many seconds the boost will stay on the player when he used the enchantment. It is here to help when Jobs Reborn waits until pay the player. 

So for an example with Excavation, it would be :

excavation:
  display: '%group-color%Excavation'
  description: "Break in 3x3 area."
  applies-to: 'Pickaxes and shovels'
  type: 'MINING'
  group: 'EPIC'
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 100
      effects:
        - 'TRENCH:3'
        - 'JRMONEYMULTIPLY: 0.1 20'
        - 'JREXPMULTIPLY: 0.1 20'

There, the player, when he will uses the enchantment, will only get 0.1 of the money and experience. The boost will stop after 20 seconds.

I hope It will help you to implant the thing. Thanks.
PS: sorry for my english heh.

**Comment by ArnoPompio** [comment]
Quote : 
This is working like if we were setting LP user settemp, but it does not spam the console :

![Capture d’écran (144)](https://user-images.githubusercontent.com/70692501/106353154-c3180c80-62e8-11eb-835e-148c266b614d.png)

**Comment by Insprill** [comment]
Added in next update

**Comment by Insprill** [comment]
Still and issue

**Comment by Insprill** [comment]
We'll just make it work out of the box. no need for more effects. And please comment on the first issue relating to this (#1361) don't create new issues. We are aware of the issue and have bumped it to critical priority so we'll get to it in a couple days
