### ISSUE TITLE
[Issue] null errors

### ISSUE THREAD

**Issue by Yuval270** [GC-spigot/AdvancedEnchantments#1484]
**Describe the bug**
did /enchanter and console sends an error
**To Reproduce**
A way to reproduce the video

**Screenshots / Video**
https://pastebin.com/n7Zd3zea

**Server Information (please complete the following information):**
PaperSpigot 1.8.8
- newst one ( at least at 1/10/2020)

**Comment by GC-spigot** [comment]
Regen your config.yml
