### ISSUE TITLE
When Clicking on epic+ enchants on /enchants gui it gives error

### ISSUE THREAD

**Issue by Silent-Program** [GC-spigot/AdvancedEnchantments#1488]
When i do /enchants, and click on "Epic Enchants" or higher its gives me this error in console.
`03.10 16:06:31 [Server] INFO Silent_Program issued server command: /enchants
03.10 16:06:32 [Server] ERROR Could not pass event InventoryClickEvent to AdvancedEnchantments v8.0.0-Pre6.7
03.10 16:06:32 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 40
03.10 16:06:32 [Server] INFO at java.util.Arrays$ArrayList.set(Arrays.java:3846) ~[?:1.8.0_242]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.NonNullList.set(SourceFile:53) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:108) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at n3kas.ae.features.usercommands.Enchantments.open(Enchantments.java:135) ~[?:?]
03.10 16:06:32 [Server] INFO at n3kas.ae.features.usercommands.Enchantments.onInventoryClick(Enchantments.java:453) ~[?:?]
03.10 16:06:32 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor498.execute(Unknown Source) ~[?:?]
03.10 16:06:32 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2427) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-211]
03.10 16:06:32 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Comment by GC-spigot** [comment]
Fixed
