### ISSUE TITLE
right-click-to-view-enchantments error

### ISSUE THREAD

**Issue by Insprill** [GC-spigot/AdvancedEnchantments#1491]
**Describe the bug**
When you open the `/enchanter` menu and right-click anything higher than Unique, it gives this error in console: https://pastebin.com/nUEdGmHn

**To Reproduce**
Open /enchanter menu and right-click on anything higher than Unique with `right-click-to-view-enchantments` enabled

**Server Information (please complete the following information):**
- Paper-212 (1.16.3)
- 8.0.0-Pre7.0

**Comment by Silent-Program** [comment]
I am having the same issue.

**Comment by Silent-Program** [comment]
You just worded it better

**Comment by GC-spigot** [comment]
Fixed
