### ISSUE TITLE
Issue with Fortune/AutoSmelt/Telepathy and Mending

### ISSUE THREAD

**Issue by nivcoo** [GC-spigot/AdvancedEnchantments#1493]
Hello, when i use AutoSmelt and telepathy the fortune is disabled can you patch that ? And with AutoSmelt, the mending not work because ores doesn't give XP. So it's two issues but two issues with AutoSmelt so to reproduce the first issue you must put Fortune, Telepathy and Autosmelt and you can look the ores given hasn't good number and for the second you must add mending and automelt and with that the ore doesn't give XP so the item will be broken very fast.

- Minecraft Version : 1.12.2
- Plugin Version : 8.0.0-Pre7.3

**Comment by nivcoo** [comment]
So ?

**Comment by nivcoo** [comment]
Any response ? also issue with telepathy and shulker content

**Comment by nivcoo** [comment]
No ?

**Comment by nivcoo** [comment]
So ?

**Comment by nivcoo** [comment]
After 1 month maybe ?

**Comment by GC-spigot** [comment]
I've fixed fortune but can't add support for mending just yet, will be in my todo list.
