### ISSUE TITLE
[Issue] Detonate bypasses Claim protection for Residence / GriefPrevention

### ISSUE THREAD

**Issue by Skizzles** [GC-spigot/AdvancedEnchantments#1495]
**Describe the bug**
Detonate enchant bypasses residence and breaks blocks in there.

**To Reproduce**
Install Residence and try to use detonate outside of a claim, it will delete blocks inside of it.

**Screenshots / Video**
https://youtu.be/CYlCxnnCgaE

**Server Information (please complete the following information):**
 - Minecraft Version [Yatopia 1.16.3]
- Plugin Version [8.0.0-Pre7.6]

**Comment by Insprill** [comment]
Unable to reproduce on the latest version. assuming it was fixed
