### ISSUE TITLE
[Request] Have enchants applied to mobs as well as players.

### ISSUE THREAD

**Issue by Silent-Program** [GC-spigot/AdvancedEnchantments#1496]
I made a custom enchant where it runs /smite on the victim. But when you attack a mob it doesnt even attempt to excecute the command. (i know /smite doesnt work on mobs) but if i were to do a normal enchant it would be really nice if when you hit a mob it did the same as if you hit a player, or vice versa with armor enchants. If a mob hits me no custom enchants are run. 

In summary
Make the enchants work on mobs

**Comment by GC-spigot** [comment]
Use LIGHTNING effect.
