### ISSUE TITLE
Lavawalker turns flowing lava into source blocks

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#1499]
**Describe the bug**
When using Lavawalker on flowing lava, the obsidian created from flowing lava blocks sometimes turn into lava source blocks. This is especially an issue, since players could place a lava block next to a protected area and then spread the lava into it by using Lavawalker.

**To Reproduce**
- Place a lava block
- Wait until it is surrounded by flowing lava
- Walk over the flowing lava using the Lavawalker enchantment
- The flowing lava will turn into obsidian
- Some of the obsidian will turn into new lava source blocks and thus spreading lava further

**Server Information (please complete the following information):**
- Minecraft Version: Paper 1.15.2 - 378
- Plugin Version: 8.0.0 - pre8.0 (also tested on 7.9.35)

**Comment by Insprill** [comment]
this was fixed in 8.0.0-Pre11.7 so you can close it :)
