### ISSUE TITLE
[Issue] Slots + Gkits

### ISSUE THREAD

**Issue by Pandas0** [GC-spigot/AdvancedEnchantments#1502]
**Describe the bug**
When you set "display-in-lore:" to true under the slots section of the config.yml and then you redeem a GKit with a custom enchantment on it, it will display the slots left line twice instead of just once.

**To Reproduce**
Set "display-in-lore:" to true in your config.yml, reload the plugin/restart server, preview or redeem a gkit and look at the lore. It will show the slots left line 2 times.

**Screenshots / Video**
https://prnt.sc/uwgzka

**Server Information (please complete the following information):**
 - Minecraft Version 1.16.3
- Plugin Version 8.0.0-Pre8.2

**Comment by GC-spigot** [comment]
Fixed
