### ISSUE TITLE
[IMPORTANT] AdvancedEnchaments Errors

### ISSUE THREAD

**Issue by TrizzerArts** [GC-spigot/AdvancedEnchantments#1504]
**Describe the bug**
I have a problem when i try to put an enchantment book for example 90% destruction, the book destroy my item.

In the config i put break-item: false

**To Reproduce**
N/A

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
 - PaperSpigot 1.16.3
-  AdvancedEnchantments 8.0.0-Pre8.9

**Comment by TrizzerArts** [comment]
And I have another problem with the plugin, I use AdvancedEnchantments and EpicRename and I enchant my item but when I try to add my custom lore item with EpicRename and the lore of the enchant disappear. In other plugins for example CrazyEnchantments this does not happen.

**Comment by GC-spigot** [comment]
Replied on discord
