### ISSUE TITLE
[Issue] Preview of all Categories is Unavailable

### ISSUE THREAD

**Issue by lucychiii** [GC-spigot/AdvancedEnchantments#1508]
Hello,

I am having trouble using the feature within /e where you can right click a category to preview books. I have
the option enabled, but it only works for the Simple and Unique categories, not Elite/Ultimate/Legendary/Heroic.

**Server Information (please complete the following information):**
- Java 1.16.3 Spigot

**Comment by GC-spigot** [comment]
Update plugin
