### ISSUE TITLE
[Issue] /ae givepiece command does not give AE enchants

### ISSUE THREAD

**Issue by PeterDorvay** [GC-spigot/AdvancedEnchantments#1509]
**Describe the bug**
When using /ae givepiece,  the item that is given does not have AE enchantments on it.

**To Reproduce**
1. Make sure you have the default 'Supreme' armor set in your AdvancedEnchantments\armorSets folder. From there, use the command `/asets givepiece <name> supreme HELMET`. it will give a piece of armor that has no custom enchantments on it.

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/21300105/96210614-1f684380-0f27-11eb-8cfe-a7804d869653.png)

![image](https://user-images.githubusercontent.com/21300105/96210591-14adae80-0f27-11eb-8d4b-75b35015dcbe.png)

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8] Spigot 1.16.2
- Plugin Version [e.g. 6.7.8] 8.0.0pre9.7

**Comment by GC-spigot** [comment]
Fixed
