### ISSUE TITLE
[Issue] RenameTag Glitch

### ISSUE THREAD

**Issue by SnipingMaster** [GC-spigot/AdvancedEnchantments#1511]
**Describe the bug**
So I realized my players can’t use color codes in rename tags for some reason and narrowed it down that DeluxeChat strips the color off it. And if I give my players deluxechat.color it gives them full color in chat but fixes the rename tags. I don’t want them having color chat only color in rename tags. 
**Server Information (please complete the following information):** 
 - Minecraft Version [BeerSpigot 1.8.8]
- Plugin Version 7.15.6

**Comment by GC-spigot** [comment]
It's an issue with chat formatting plugin, it filters out the chat colors before AE gets to see them.
