### ISSUE TITLE
[Request] Support vanilla enchant

### ISSUE THREAD

**Issue by WarnDangerous** [GC-spigot/AdvancedEnchantments#1512]
Hello,

Would it be possible to support every "vanilla enchant" in your plugin ? 
So we can also customize how look every enchant in items' lore, change name, set a color, etc.

**Comment by thewillmoss** [comment]
It would be cool to also be able to add simple things like Fortune X on a pickaxe as a CE

**Comment by Insprill** [comment]
Won't add
