### ISSUE TITLE
[Issue] Problem with customweapons

### ISSUE THREAD

**Issue by OGreenC** [GC-spigot/AdvancedEnchantments#1513]
**Describe the bug**
Hi,
I'm encountering a weird null pointer exception, while attempting to obtain a customweapon.
I'm trying to give myself one of the default weapons.

**To Reproduce**
I don't really know hot to reproduce this be honest.
Might be there from start?

Maybe the error can help? See below.

**Screenshots / Video**
I've pasted the error below.
https://pastebin.com/AtxiV4G8

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.13.2]
- Plugin Version [e.g. 8.0.0-Pre9.9]

**Comment by GC-spigot** [comment]
Fixed!
