### ISSUE TITLE
[Issue] Spam error in console

### ISSUE THREAD

**Issue by MuravlevAS** [GC-spigot/AdvancedEnchantments#1514]
Frequently spams error in console:
![image](https://user-images.githubusercontent.com/46592121/96371567-76228700-118c-11eb-8a17-a982684e6ac7.png)

Plugin version: 8.0.0-Pre9.9
![image](https://user-images.githubusercontent.com/46592121/96371585-85093980-118c-11eb-9604-8ffad8dc1989.png)

Minecraft version: git-Paper-389 (MC: 1.15.2)
![image](https://user-images.githubusercontent.com/46592121/96371602-97837300-118c-11eb-95a0-16e0764404da.png)

**Comment by GC-spigot** [comment]
Fixed
