### ISSUE TITLE
[Issue] Enchantment Table Does Not Work

### ISSUE THREAD

**Issue by ImLevii** [GC-spigot/AdvancedEnchantments#1515]
I have an issue I cant get any custom enchants from the table, like at all even after messing around with the chances. I also get a AnvilPrepare event error on 1.8.8

[AdvancedEnchantments] Plugin AdvancedEnchantments v8.0.0-Pre10.1 has failed to register events for class n3kas.ae.handlers.anvil.AnvilEvent because org/bukkit/event/inventory/PrepareAnvilEvent does not exist.

**Comment by Insprill** [comment]
Is this still an issue on pre12.5?
