### ISSUE TITLE
[Issue] Hellfire FREEZES server

### ISSUE THREAD

**Issue by Insprill** [GC-spigot/AdvancedEnchantments#1519]
**Describe the bug**
When you hit a player with Hellfire on a bow, it freezes the server for upwards of a minute.
Timings: https://timings.aikar.co/?id=b197e97b9ff64153ac9effc60ea8a890

**To Reproduce**
Put hellfire 5 on a bow and shoot another player

**Screenshots / Video**
https://vimeo.com/470002585

**Server Information (please complete the following information):**
- Minecraft Version Paper-240 (1.16.3)
- Plugin Version 8.0.0-Pre10.4

**Comment by GC-spigot** [comment]
I have no idea what the issue is, seems to be some kind of a server related issue. Try updating Paperspigot.
