### ISSUE TITLE
[Request] Success and Destruction level argument through console

### ISSUE THREAD

**Issue by AngellitoX** [GC-spigot/AdvancedEnchantments#1520]
Hello, any chance you guys could add a few more arguments to the console commands to give enchants?

```yaml
>.... [09:06:28 INFO]: AdvancedEnchantments Commands MV(minified version for console)
>.... [09:06:28 INFO]: /ae reload - reload the plugin
>.... [09:06:28 INFO]: /ae giveitem <player> <item> - Give various plugin items
>.... [09:06:28 INFO]: /ae give <player> <enchantment> <level> - Give Enchantment book with enchant
```

It'd be really useful if you were able to setup success and destruction level through console. 
Example:
`/ae give <player> <enchantment> <level> [success] [destruction]` 
<> - Obligatory
[] - Optional

**Comment by Insprill** [comment]
What you're looking for is the /ae givebook command. It can be used in console, it just didn't show in the help menu. It will be added to the help menu in the next update (pre21.7).
