### ISSUE TITLE
Items can be added to the GUIs from the hotbar by using number keys

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#1522]
**Describe the bug**
When opening a GUI like /tinkerer or /enchanter (if there are empty slots due to the configuration), items from your hot bar can be moved into that GUI by hovering over the empty slot in the GUI with your cursor, while pressing the respective number key corresponding to the item in your hot bar. When closing the GUI, the item is deleted.

**To Reproduce**
- Have an item in your hot bar
- Use /tinkerer
- Hover with your mouse cursor over the tinkerer's side of the window
- Press e.g. the "1" key if the item is in the first slot
- Press Esc to close the GUI
- The item should now be gone

**Server Information (please complete the following information):**
- Minecraft Version: Paper 1.15.2-389
- Plugin Version: 8.0.0-Pre10.5

**Comment by Insprill** [comment]
This was fixed a few versions back
