### ISSUE TITLE
[Issue]BOOTS slot: all recent updates make clicking quickly on the boot slot not work properly.

### ISSUE THREAD

**Issue by Mishrathium** [GC-spigot/AdvancedEnchantments#1523]
[bug] BOOTS slot: all recent updates make clicking quickly on the boot slot not work properly.
Quickly Click any armor slot and it picks up / drops back on slot normally.
Do this for boots slot - and doesnt work smoothly or at all sometimes
remove AE - boot slot works fine. This is on 1.16.1 and tried at least 6 most recent versions

**Comment by Skullslice** [comment]
This problem as well on spigot 1.8.8 (private video showing the issue) https://youtu.be/vOTj-8u9Xj4

**Comment by GC-spigot** [comment]
Should be resolved
