### ISSUE TITLE
Infinite stone and exp dupe

### ISSUE THREAD

**Issue by SlimeCody** [GC-spigot/AdvancedEnchantments#1526]
Describe the bug
When mining end portal frames with AutoSmelt it gives stone and exp.

To Reproduce
https://www.youtube.com/watch?v=pu1d5SVvSN0

Server Information (please complete the following information):

Minecraft Version [Paper 1.16.3]
Plugin Version [8.0.0-Pre11.0]

**Comment by SlimeCody** [comment]
You closed my last issue with this as though you had resolved it by adding it to the trench blacklist. The issue is with autosmelt not trench.

**Comment by GC-spigot** [comment]
Sorry about that, fixed now!
