### ISSUE TITLE
[Issue] AE Item repairing fix sub-plugin doesn't work on netherite

### ISSUE THREAD

**Issue by whiskey-iwnl** [GC-spigot/AdvancedEnchantments#1527]
Cannot do /fix on netherite tools, works perfectly fine on everything except netherite, I'm assuming it's just because of how outdated that plugin is. Would really appreciate a fix 😄

**Comment by nivcoo** [comment]
I've same issue ^^

**Comment by Insprill** [comment]
The addon isn't needed anymore as Essentials fixed it on their end.
