### ISSUE TITLE
[Issue] Enchantment descriptions issue with \n

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#1528]
**Describe the bug**
The default configuration has \n to split the line but this seems to be broken.

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/5664135/97547904-b1b02300-19ce-11eb-9ef1-520359e5394f.png)

![image](https://user-images.githubusercontent.com/5664135/97548016-df956780-19ce-11eb-9d01-cfd553b7366c.png)

**Server Information (please complete the following information):**
git-Tuinity-"5df4a4f" (MC: 1.16.3)
8.0.0-Pre11.3

**Comment by GC-spigot** [comment]
Use `"description\nline"` double quotes.
