### ISSUE TITLE
Lavawalker duplicating lava blocks into source blocks even when they are not[Issue]

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#1531]
**Describe the bug**
after a lava non source block turns into obi than turns back it will become a full source block

**To Reproduce**
have lava and walk around it, it will turn the half lava blocks into full source blocks and give more lava the more you walk back and forth.

**Screenshots / Video**
this is my spawn after people abusing this bug
https://prnt.sc/vau9ke

**Server Information (please complete the following information):**
 - Minecraft Version paper 1.16.3
- Plugin Version pre 11.5

**Comment by GC-spigot** [comment]
Fixed
