### ISSUE TITLE
[Issue] Custom Enchants don't apply on wooden tools and players exceeding the limit

### ISSUE THREAD

**Issue by jppabs115** [GC-spigot/AdvancedEnchantments#1532]
**Describe the bug**
Custom enchantment books won't apply to all of the wooden tools. I'm also seeing some players exceeding the enchantment limit that is configured. 

**Screenshots / Video**
[https://gyazo.com/4aa2ff603281a9f968c39e18168d5d0d](url)
[https://gyazo.com/00dac28b47915761786fcebb54a07b92](url)

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.15.2 build 390]
- Plugin Version [e.g. 8.0.0-Pre11.4]

**Comment by GC-spigot** [comment]
Limit issue is fixed I believe, was due to anvil combining. Will fix wooden tools issue.
