### ISSUE TITLE
[Request] PLANT_SEEDS change

### ISSUE THREAD

**Issue by Pandas0** [GC-spigot/AdvancedEnchantments#1533]
** Describe the Request**
Modify PLANT_SEEDS to be PLANT_CROP:[Name]:[Amount].

Enabling you to be able to use the effect to plant other crops like carrots, potatoes, beetroot seeds, netherwart, etc.

**Comment by FighterPilot50** [comment]
I would recommend describing this more as an issue. Seems like a Planter enchantment should be able to plant any crops

**Comment by Pandas0** [comment]
> I would recommend describing this more as an issue. Seems like a Planter enchantment should be able to plant any crops

This isn't an issue, it is a request and the request is straight forward to add a new effect/change the effect to plant other crops that arent wheat seeds.

I have tested time and time again on 1.16 and the enchantment plants nothing but wheat seeds.

**Comment by GC-spigot** [comment]
Changed in next update
