### ISSUE TITLE
Issue with detonate (TRENCH)

### ISSUE THREAD

**Issue by caqb** [GC-spigot/AdvancedEnchantments#1536]
Hey! So I've been using AdvancedEnchants as a developer for a while now. Everything is working fine, though a small issue that has been popping up a few instants ago: 

[Tue, 3. Nov 2020 00:53:23 EET WARN] java.lang.NullPointerException
[Tue, 3. Nov 2020 00:53:23 EET INFO] [AdvancedEnchantments ERROR] Could not pass NullPointerException:
[Tue, 3. Nov 2020 00:53:23 EET INFO] Class:
[Tue, 3. Nov 2020 00:53:23 EET INFO] Extra info: effect[TRENCH:3]; enchant [detonate]; mc[116]; ae[8.0.0-Pre6.8]
[Tue, 3. Nov 2020 00:53:23 EET INFO] If you cannot indentify cause of this, contact developer providing this report.

Contact me via discord: House#8888 or here.

Thanks again for the support, hope to see a response soon!

**Comment by Insprill** [comment]
Is this issue still occurring?

**Comment by Insprill** [comment]
No response - closing. feel free to respond to this if the issue is still occurring on the latest version of AE.
