### ISSUE TITLE
[Issue] Haste stays when tool breaks

### ISSUE THREAD

**Issue by Insprill** [GC-spigot/AdvancedEnchantments#1537]
**Describe the bug**
If you have a tool with the Haste enchantment, when that tool breaks, you keep the haste until you hold another item that also has haste.

**Screenshots / Video**
https://vimeo.com/474931327

**Server Information:**
- Minecraft Version: Paper-253 (1.16.3)
- Plugin Version: 8.0.0-Pre11.9

**Comment by Sikatsu** [comment]
I noticed the same issue.

**Comment by GC-spigot** [comment]
Fixed
