### ISSUE TITLE
[Issue] NPE is thrown when running /ae unenchant <enchantmnet> without holding an item

### ISSUE THREAD

**Issue by Insprill** [GC-spigot/AdvancedEnchantments#1538]
**Describe the bug**
When you run the command `/ae unenchant <enchantmnet>` when you're not holding anything, it throws an NPE.
Error: https://pastebin.com/FniZtvdn

**To Reproduce**
run the command `/ae unenchant <enchantmnet>` when you're not holding anything

**Server Information:**
- Minecraft Version: Paper-253 (1.16.3)
- Plugin Version: 8.0.0-Pre11.9

**Comment by GC-spigot** [comment]
Fixed
