### ISSUE TITLE
[Issue] DROP_HEAD & KILL_MOB drops incorrect heads

### ISSUE THREAD

**Issue by Insprill** [GC-spigot/AdvancedEnchantments#1543]
**Describe the bug**
With `DROP_HEAD %victim%` when you kill a mob, it drops entirely the wrong head, dropping the heads of players that have the same name as the mob.

**To Reproduce**
Get an enchantment, add `KILL_MOB` to the type, ensure `DROP_HEAD %victim%` is one of the effects, and kill some sheep, spiders, fish, or almost any other mob.

**Server Information:**
- Minecraft Version: Paper-253 (1.16.3)
- Plugin Version: 8.0.0-Pre12.0

**Comment by GC-spigot** [comment]
It only works with players
