### ISSUE TITLE
[Request] Damage from placeholder

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#1547]
It would be really nice to have a placeholder for the amount of damage from a certain enchantment. This way the enchantments can become even more complex. %DAMAGE_FROM_<ENCHANTNAME>% boolean would return false if no damage effects are added on the enchantment and return true if they have modified damage. My goal with this is to have a way to deduce certain enchantments and reflect damages back to the attacker so something like:
DISABLE_ACTIVATION:<enchant name>:<seconds> %attacker%
INCREASE_DAMAGE:DAMAGE_FROM_<ENCHANTNAME> %victim%

**Comment by Insprill** [comment]
Assuming I'm understanding what you're saying, as of 8.6.10, all variables can be used inside of effects. You can see more info [here](https://ae.advancedplugins.net/enchantments/enchantment-conditions/variables).
