### ISSUE TITLE
[Issue] Detonate does not fire block break event

### ISSUE THREAD

**Issue by dig** [GC-spigot/AdvancedEnchantments#1548]
**Describe the bug**
Detonate does not fire block break event so other plugins are unable to act when a block is mined.

**To Reproduce**
Mine using detonate on a pickaxe.

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
- Server Version: PaperSpigot 1.16.4
- Plugin Version: 8.0.0-Pre12.4

**Comment by GC-spigot** [comment]
Config.yml, set this to true https://prnt.sc/vklgav

**Comment by dig** [comment]
It's already true, you need to fire the bukkit event "BlockBreakEvent" for all the blocks you set to AIR when the detonate enchantment is executed. I'm not cancelling the event, I'm listening to when a block is broken and when players break blocks using detonate it does not appear on BlockBreakEvent.

**Comment by GC-spigot** [comment]
Events are called for each block mined (3x3x3 mined blocks = 27 events), this way plugin also checks if blocks are mine-able (hence the screenshot information).

**Comment by dig** [comment]
I'm not getting BlockBreakEvent being fired when a detonate pickaxe is breaking blocks, only the one block they mine is firing the event, the blocks around it are being broken but no event.
