### ISSUE TITLE
[Issue] Vanilla Fortune + Telepathy will increase the % drops by 2-3x

### ISSUE THREAD

**Issue by baailey** [GC-spigot/AdvancedEnchantments#1549]
**Describe the bug**
If you have vanilla Fortune + Telepathy applied to the same pickaxe, Telepathy will drastically increase the amount of items dropped from Diamond Ore, for example. 

**To Reproduce**
Give yourself a Diamond Pickaxe with Fortune 3, and then do /ae enchant Telepathy [1-4]

**Screenshots / Video**
https://youtu.be/HqXxaPM6d-Q

**Server Information (please complete the following information):**
- Server Version: git-Tuinity-"576e2cc" (MC: 1.16.3) 
- Plugin Version: 8.0.0-Pre12.4 (I also tested on 8.0.0-Pre45 originally before updating to latest to see if this had been fixed)

**Comment by baailey** [comment]
This issue is still alive, even with the latest hotfix.

**Comment by GC-spigot** [comment]
Not able to recreate the issue anymore, however I updated fortune formula to match minecraft's

**Comment by baailey** [comment]
Hello again, this issue is still present for me even on the latest version. If I use a pickaxe with Fortune I and Telepathy I, it will only increase the % of drops when Telepathy kicks in. If Telepathy doesn't active, Fortune works as intended.

Is there any further testing, or something I could do to aid you in locating the issue?
