### ISSUE TITLE
[Request] Adding new events (SHIFT_LEFT_CLICK & SHIFT_RIGHT_CLICK)

### ISSUE THREAD

**Issue by SkylerBoy** [GC-spigot/AdvancedEnchantments#1550]
I want execute certain effects when player use shift_right_click, another effects when player use shift_left_click and other effects when player use simple right_click, but for the momento I only use "SHIFT" event (right_click).

Is possible add this events? Ty ^^

**Comment by SkylerBoy** [comment]
U can check a example [here](https://i.imgur.com/4XOcESr.png)

**Comment by SkylerBoy** [comment]
At the moment, Im using simple "RIGHT_CLICK", and checking if player.isSneaking(), equals in ATTACK event, but is possible add this?

**Comment by GC-spigot** [comment]
Check if the actual entity is shifting through code.
