### ISSUE TITLE
Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### ISSUE THREAD

**Issue by danielramirezm** [GC-spigot/AdvancedEnchantments#1552]
I'm getting this error message trying to run AdvanceEnchantments

10.11 20:15:12 [Server] WARN [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.
10.11 20:15:12 [Server] INFO [AdvancedEnchantments] Disabling AdvancedEnchantments v8.0.0-Pre12.5
10.11 20:15:12 [Server] WARN [AdvancedEnchantments] Plugin AdvancedEnchantments v8.0.0-Pre12.5 generated an exception while executing task 641049
10.11 20:15:12 [Server] INFO java.lang.LinkageError: loader constraint violation: when resolving method "n3kas.ae.handlers.netsharing.EnchantPreview.<init>(Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ln3kas/ae/api/AEnchantmentType;II)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, n3kas/ae/handlers/netsharing/MarketInventory, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, n3kas/ae/handlers/netsharing/EnchantPreview, have different Class objects for the type n3kas/ae/api/AEnchantmentType used in the signature
10.11 20:15:12 [Server] INFO at n3kas.ae.handlers.netsharing.MarketInventory.cache(MarketInventory.java:240) ~[?:?]
10.11 20:15:12 [Server] INFO at n3kas.ae.handlers.netsharing.MarketInventory.access$0(MarketInventory.java:212) ~[?:?]
10.11 20:15:12 [Server] INFO at n3kas.ae.handlers.netsharing.MarketInventory$1.run(MarketInventory.java:49) ~[?:?]
10.11 20:15:12 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-253]
10.11 20:15:12 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-253]
10.11 20:15:12 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-253]
10.11 20:15:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
10.11 20:15:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
10.11 20:15:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

SPIGOT VERSION: 1.16.3
SPIGOTMC.ORG USERNAME: DanielR1022

**Comment by GC-spigot** [comment]
Resolved
