### ISSUE TITLE
able to drag items out of GUI

### ISSUE THREAD

**Issue by AjtheGreat492** [GC-spigot/AdvancedEnchantments#1553]
When we use the commands to open the GUI and attempt to get an enchant it does not work and you are able to drag the item out of the GUI
To replicate 
1: use /ce or any other alias of the command 
2: click on the window pane in the gui or any other item
3: its now able to be dragged into inventory and kept

**Comment by GC-spigot** [comment]
Your plugin is disabled, check console startup log for more information.
