### ISSUE TITLE
[Issue] Switching items in inventory disables armor sets

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#1554]
**Describe the bug**
When you switch two items around in your inventory, the armor set disables and effects are removed.

**To Reproduce**
Make and wear an armor set bonus, switch items in the inventory.

**Screenshots / Video**
https://cdn.discordapp.com/attachments/762409151887704065/771087999667929139/Minecraft__1.16.3_-_Multiplayer_3rd-party_Server_2020-10-28_20-07-25.mp4

**Server Information (please complete the following information):**
- Server Version: Tuinity 1.16.4
- Plugin Version: Pre-12.6

**Comment by Sikatsu** [comment]
https://www.dropbox.com/s/chjqcw2vbooeoc6/Minecraft_%201.16.3%20-%20Multiplayer%20%283rd-party%20Server%29%202020-10-28%2020-07-25.mp4?dl=0

In case the other video link doesn't work.

**Comment by GC-spigot** [comment]
Fixed

**Comment by Sikatsu** [comment]
If you mean fixed on 12-7, it actually still happens
