### ISSUE TITLE
[Issue] Armor enchants not stacking

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#1555]
**Describe the bug**
When wearing the leggings of the set, this gives the player 6 extra hearts. When wearing the chestplate, this gives the player 10 extra hearts. When wearing both the chestplate and the leggings, this gives the player 10 extra hearts. When un-equipping only either the legging or the chestplate, bonus hearts of the armor piece that is still equipped will not be given.

This may also be the case with other bonusses from the set.

**To Reproduce**
Explained in the upper section.

**Screenshots / Video**
https://www.dropbox.com/s/ax0bmidn98280um/Minecraft_%201.16.4%20-%20Multiplayer%20%283rd-party%20Server%29%202020-11-13%2021-47-10.mp4?dl=0

**Server Information (please complete the following information):**
- Server Version: Tuinity 1.16.4
- Plugin Version: Pre-12.6

**Comment by Insprill** [comment]
Going to close this as it isn't really a bug since the armor is just adding the potion effect it's told to. Maybe we'll add a dedicated EXTRA_HEALTH effect that can stack in the future - but no promises.
