### ISSUE TITLE
[Issue] MobTrak lore position

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#1558]
The mobtrak lore that applies to weapons seems to always go above custom enchantments and looks clunky in the center of the lore. It would be ideal if it was set similarly to stat trak which is always defaulted to a bottom position for formatting reasons. Maybe it could be the same as stattrak but 1 higher above it if both are applied to the same item instead of random positions within the lore for different items

Hope  this makes sense, to reproduce apply mob trak to custom weapons then apply stat trak and see the differences. Maybe the same could be done for blocktrak as i haven't tested it but defaulting that to a bottom position on custom tools would be great too.

Many thanks.

Example: 
![image](https://user-images.githubusercontent.com/50850853/99149571-d969e100-2686-11eb-9a0e-4641c0ee5219.png)

**Comment by Insprill** [comment]
Fixed
