### ISSUE TITLE
[Issue] /ci without permissions removing buffs

### ISSUE THREAD

**Issue by matthew-wiggins** [GC-spigot/AdvancedEnchantments#1560]
**Describe the bug**
When using essentials /ci (Clear inventory) without permission it removes all of my enchant effects even though I don't have permission

**To Reproduce**
 - Install AdvancedEnchantments & Essentials
 - Apply custom enchants to your player (armor or item) that give static effects
 - Without permission, use /ci

**Server Information (please complete the following information):**
- Server Version: Paper-223 (MC: 1.16.3)
- Plugin Version: 8.0.0-Pre12.4

**Comment by GC-spigot** [comment]
There's no proper way of doing this, keeping it without permission checks is the best solution. I added permission checks though for next update, if there's many people having issues will have to think of something else.

**Comment by matthew-wiggins** [comment]
Since the essentials clear inventory permission will most likely never change I can't think of any way someone could have issues.

**Comment by GC-spigot** [comment]
Not everyone uses essentials for clearing inventories ;)

**Comment by matthew-wiggins** [comment]
You are completely right, I didn't even think of that. :P

> Not everyone uses essentials for clearing inventories ;)
> […](#)
> On 2020-11-22, at 10:58 AM, Matthew W. ***@***.***> wrote: ﻿ Since the essentials clear inventory permission will most likely never change I can't think of any way someone could have issues. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
