### ISSUE TITLE
[Issue] Lavawalker can be used to infinitely farm obsidian

### ISSUE THREAD

**Issue by Insprill** [GC-spigot/AdvancedEnchantments#1561]
**Describe the bug**
You can break the obsidian made from the lava walker enchant and infinitely farm it. (very easy with obsidian destroyer)

**To Reproduce**
Find a pool of lava, get the lava walker enchant, get a pickaxe that can break it fast, and start farming.

**Server Information (please complete the following information):**
- Server Version: Paper-288 (1.16.4)
- Plugin Version: 8.0.0-pre-13.8

**Comment by GC-spigot** [comment]
It doesn't turn non source blocks into lava anymore (since last few updates ago), obsidian generated is also not breakable:
https://i.imgur.com/98wlwc4.gif
