### ISSUE TITLE
Enchantments staying on players [Issue]

### ISSUE THREAD

**Issue by MaxShadowWolf** [GC-spigot/AdvancedEnchantments#1563]
Enchantments are staying on players.
Haste 3 is staying on players if their pickaxe breaks.
Armor enchantments are staying on players without the armor on.

To reproduce the haste 3 bug, have the pickaxe break while using it and the affect stays on the player.
To reproduce the armor bug, quickly double click the armor in and out of the armor slot and the enchantment affect stays on the player.

![image](https://user-images.githubusercontent.com/75050567/100295040-2898f700-2f4e-11eb-9c5b-36e14f9bcd01.png)

![image](https://user-images.githubusercontent.com/75050567/100295050-2e8ed800-2f4e-11eb-9da4-f29a99e0c3c4.png)

**Server Information (please complete the following information):**
- Server Version: Spigot-9639cf7-4b9bc9d
- Plugin Version: 8.0.0-Pre10.5

**Comment by GC-spigot** [comment]
Update, has been fixed meanwhile.
