### ISSUE TITLE
[Issue]Assets command doesnt work

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#1564]
**Describe the bug**
/asets heroic <name> <set> doesnt actually return or do anything

**To Reproduce**
do the command

**Screenshots / Video**
None needed

**Server Information (please complete the following information):**
- Server Version: PaperSpigot 1.16.3
- Plugin Version: 8.0.0-Pre14.5

**Comment by GC-spigot** [comment]
That's a mistake in config, command example is `/asets giveHeroicUpgrade GC Yeti 1 1`
