### ISSUE TITLE
[Issue] Autosmelt + telepathy broken

### ISSUE THREAD

**Issue by dig** [GC-spigot/AdvancedEnchantments#1565]
**Describe the bug**
Having autosmelt and telepathy on the same pickaxe will cause non smeltable blocks to disappear when you mine them, you're not given the block. Pickaxe works fine on smeltable blocks such as ores.

**To Reproduce**
1. Add autosmelt to your pickaxe.
2. Add telepathy to your pickaxe.
3. Mine any unsmeltable block (obsidian, glass, etc)

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
- Server Version: Tuinity 1.16.4
- Plugin Version: 8.0.0-Pre14.7

**Comment by Insprill** [comment]
Can confirm https://vimeo.com/484913831

**Comment by nivcoo** [comment]
Same problem (with same version of Tuinity)

**Comment by GC-spigot** [comment]
Fixed
