### ISSUE TITLE
[Issue] Item Repairing Fix addon for the plugin has errors with Netherite

### ISSUE THREAD

**Issue by Kaisiq** [GC-spigot/AdvancedEnchantments#1566]
**Describe the bug**
AdvancedEnchantments Item Repairing Fix addon for the plugin doesnt work with Netherite armor and tools on 1.16.3

**To Reproduce**
Get a Netherite item and break some blocks with it, try to /fix it, it will say that this item cannot be repaired.

**Server Information (please complete the following information):**
- Server Version: [PaperSpigot - 1.16.3]
- Plugin Version: [8.0.0 - Pre 13.0]

**Comment by nivcoo** [comment]
Same issue here : https://github.com/GC-spigot/AdvancedEnchantments/issues/1527

**Comment by ArnoPompio** [comment]
@Kaisiq  @nivcoo 

Remove the addon from your server, /fix CE does not need the addon anymore with the last versions !
