### ISSUE TITLE
[Issue] Telepathy + Silktouch broken

### ISSUE THREAD

**Issue by nivcoo** [GC-spigot/AdvancedEnchantments#1567]
**Describe the bug**
Hello, i have problem with Silktouch and Telepathy, when i use them, the enchant Silktouch isn't applied.

**To Reproduce**

1. Add Telepathy to your pickaxe.
2. Add Silktouch to your pickaxe.
3. Mine any block (stone, ores, etc)

**Screenshots / Video**
https://pics.edensky.fr/2020-11/30/21-24_ANdR.mp4

**Server Information (please complete the following information):**
- Server Version: KSpigot 1.12.2
- Plugin Version: 8.0.0-Pre15.0

**Comment by nivcoo** [comment]
Also i've one server in 1.16.4 and i haven't the issue

**Comment by Insprill** [comment]
Fixed
