### ISSUE TITLE
[Issue] AE conflicts with GadgetsMenu

### ISSUE THREAD

**Issue by baailey** [GC-spigot/AdvancedEnchantments#1569]
**Describe the bug**
GadgetsMenu has 'Emote' gadgets that will apply to the Helmet Slot when the gadget is active. If you right-click a helmet whilst one of those Emotes are active, it will remove the helmet and duplicate the Emote.

**To Reproduce**
1. Right-click the Emote in your hand so it activates and equips onto your head
2. Right-click a helmet to try and equip it

**Screenshots / Video**
With AE + GadgetsMenu: https://youtu.be/VOkJFHWEyDg
Without AE: https://youtu.be/19Qof5q_NrM

**Server Information (please complete the following information):**
- Server Version: git-Tuinity-"576e2cc" (MC: 1.16.3) 
- Plugin Version: AE - 8.0.0-Pre13.8
- Plugin Version: GadgetsMenu - 4.6.3

I submitted a bug report to GadgetsMenu about this which you can find [here](https://github.com/yapzhenyie/GadgetsMenu/issues/815)

**Comment by Insprill** [comment]
Is this still an issue on the latest versions?

**Comment by baailey** [comment]
Any update on this? Have had to disable multiple features due do this conflict.

**Comment by Insprill** [comment]
Fixed in the next update
