### ISSUE TITLE
[Issue] Custom Armour Enchants will remain applied even when removed from the armour slot using OpenInv

### ISSUE THREAD

**Issue by baailey** [GC-spigot/AdvancedEnchantments#1570]
**Describe the bug**
If you apply an enchant to a piece of armour (in this case, Lava Walker), the effect will still remain even after you remove the enchant via the use of [OpenInv](https://dev.bukkit.org/projects/openinv) (allows editing another players inventory)

**To Reproduce**
1. Apply Lava Walker to boots
2. Wear the boots
3. Have an alt / different player remove the boots through OpenInv
4. Walk across lava 

**Screenshots / Video**
https://youtu.be/2BfuDKAgQGE

**Server Information (please complete the following information):**
- Server Version: git-Tuinity-"576e2cc" (MC: 1.16.3)
- Plugin Version: AE: 8.0.0-Pre15.2
- Plugin Version: OpenInv: 4.1.5

**Comment by GC-spigot** [comment]
There's no way to detect armor changes like that, the reason why it doesn't keep constantly checking is for performance - keeping constant checks instead of equip and unequip will plummet the performance.
