### ISSUE TITLE
Config bug + Console error[Issue]

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1572]
**Describe the bug**
Getting these errors https://pastebin.com/x3uWMpSh 

+ I cannot modify this https://gyazo.com/624af7e536d6f151e54e95813f99c845 even tho I modified it in the config.

**To Reproduce**
Right click on a book and for the error Idk how I did it.

**Screenshots / Video**
https://gyazo.com/624af7e536d6f151e54e95813f99c845
https://pastebin.com/x3uWMpSh 
**Server Information (please complete the following information):**
- Server Version: Paper 1.8.8
- Plugin Version: 8.0.0-Pre15.4

**Comment by GC-spigot** [comment]
1st Fixed, 2nd one should be modified in customcommands.yml
