### ISSUE TITLE
[Issue] Failed to show 'LARGE_SMOKE' particle

### ISSUE THREAD

**Issue by Kaisiq** [GC-spigot/AdvancedEnchantments#1573]
**Describe the bug**
Console spamming:
[Server thread/INFO]: [AdvancedEnchantments] Failed to show 'LARGE_SMOKE' particle
[Server thread/INFO]: [AdvancedEnchantments] Failed to show 'LARGE_SMOKE' particle
...

**To Reproduce**
Enchant a sword with epicness enchant and start attacking enemies

**Server Information (please complete the following information):**
- Server Version: [e.g. -Paper-204 1.16.3]
- Plugin Version: [e.g. 8.0.0 Pre-15.5]

**Comment by GC-spigot** [comment]
You need to change particle names in config to ones to match your server version
