### ISSUE TITLE
[Issue] Enchantment Table not working correctly on 1.12.2

### ISSUE THREAD

**Issue by ThePlay3r** [GC-spigot/AdvancedEnchantments#1574]
Enchantment Table not working correctly? I had set the chance for a AdvancedEnchant to drop to 100%, but still it never drops? My configuration: 
`enchantmentTable.yml` https://paste.ubuntu.com/p/VxwSJVMy2M/
`groups.yml` https://paste.ubuntu.com/p/PrdwDtsZxN/

I believe this is some kind of bug, as I tried to completely remove my configuration and let the default one generate, set the `chance` in `enchantmentTable.yml` to `99` and still, nothing dropped at all.

<hr>

Server version: **kSpigo**t fork of **Paper 1.12.2-R0.1-SNAPSHOT**
Plugin version: **8.0.0-Pre14.9**

**Comment by Insprill** [comment]
Is this still an issue on 8.0.0pre21.5/6?

**Comment by GC-spigot** [comment]
Enchantment tables were limited to 1.13+, changed it to 1.11+ for next update
