### ISSUE TITLE
[Issue]Issue with Hide_Dye flag

### ISSUE THREAD

**Issue by OGreenC** [GC-spigot/AdvancedEnchantments#1576]
**Describe the bug**
It seems like I can't apply the flag "Hide_Dye" to leather items, in armor pieces defined in ArmorSets.
When attemting to give myself a piece with the flag "Hide_Dye", an error is trown, see below.

**To Reproduce**
Add the following flag to a custom armor piece:
```
itemFlags:
  - 'HIDE_DYE'
```

**Screenshots / Video**
The error can be found in this pastebin: https://pastebin.com/QYZdt7xM

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-653 1.13.2
- Plugin Version: AdvancedEnchantments-8.0.0-Pre15.7.jar

**Comment by Insprill** [comment]
That flag was only added in 1.16. Upgrade to 1.16 to use it
