### ISSUE TITLE
[Request] Ability to change, add items under Enchantment Items like Dusts/Scrolls/Orbs

### ISSUE THREAD

**Issue by SirCraftypants** [GC-spigot/AdvancedEnchantments#1578]
** Describe the Request**
I spoke to you a few weeks back about being able to change the items that dusts, scrolls and orbs can work on, like say if I'm using 'STICK' to host my Custom Armor Helmets. Being able to add STICK under a certain Dust, Scroll or Orb is my wish.

You agreed to implement it but in case you've forgotten I decided to create a Feature Request.

**Comment by SirCraftypants** [comment]
Hi, back in Dec last year I requested you to make it possible to use Custom Model Data so we can use custom textures for items like Dust and Scrolls.

id:   does not work and we still can not use our own custom textures.

I see that there are quite a few feature requests asking for the exact same thing.

https://github.com/GC-spigot/AdvancedEnchantments/issues/1788
https://github.com/GC-spigot/AdvancedEnchantments/issues/1755
https://github.com/GC-spigot/AdvancedEnchantments/issues/1694

Please can you make this possible.

**Comment by Insprill** [comment]
Added for 8.0.0-pre21.7. Under each item, there will be a field called `custom-model-data`. It will autogenerate, however, you need to do whatever for the item to be created, then it will generate the value.
