### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by GNUBBINI** [GC-spigot/AdvancedEnchantments#1581]
**Describe the bug**

any spells renamed in config with "ALL_ARMOR" will not work on the pieces in the chain

**To Reproduce**

**Screenshots / Video**
look
doctor:
  display: '%group-color%Doctor'
  description: "A chance to absorb enemy\ndamage and heal you"
  applies-to: 'Armor'
  type: 'DEFENSE;DEFENSE_MOB'
  group: 'COMMON'
  applies:
    - 'ALL_HELMET'
    - 'ALL_CHESTPLATE'
    - 'ALL_LEGGINGS'
    - 'ALL_BOOTS'
    - 'CHAIN_BOOTS'
    - 'CHAIN_ARMOR'
  levels:
    1:
      chance: 3
      cooldown: 5
      effects:
        - 'STOP_ATTACK'
        - 'POTION:ABSORPTION:0:80 %victim%'
    2:
      chance: 7
      cooldown: 5
      effects:
        - 'STOP_ATTACK'
        - 'POTION:ABSORPTION:0:80 %victim%'
    3:
      chance: 11
      cooldown: 5
      effects:
        - 'STOP_ATTACK'
        - 'POTION:ABSORPTION:0:80 %victim%'
    4:
      chance: 15
      cooldown: 5
      effects:
        - 'STOP_ATTACK'
        - 'POTION:ABSORPTION:0:80 %victim%'

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.12.2]
- Plugin Version: [8.00 PRE16]
![BUG](https://user-images.githubusercontent.com/75571789/101281383-de760800-37ce-11eb-9f36-776eb3cf9549.PNG)
]

**Comment by MamboTND** [comment]
I think you need to make it
- 'CHAINMAIL_ARMOR'
works for me.

**Comment by Insprill** [comment]
Fixed a few versions back
