### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by GNUBBINI** [GC-spigot/AdvancedEnchantments#1583]
**Describe the bug**

**To Reproduce**
A way to reliability reproduce the bug.

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.12.2]
- Plugin Version: [e.g.  8.0.0-Pre16.1]
[WARNING] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)

[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$1135/0x00000000910fcbe0.run(Unknown Source)

[WARNING] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[WARNING] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[WARNING] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)

[WARNING] at java.lang.Thread.run(Thread.java:823)

[WARNING] java.lang.ArrayIndexOutOfBoundsException

[WARNING] at java.util.Arrays$ArrayList.set(Arrays.java:3846)

[WARNING] at net.minecraft.server.v1_12_R1.NonNullList.set(SourceFile:51)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:107)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:96)

[WARNING] at n3kas.ae.features.gkits.GInventory.openForPlayer(GInventory.java:47)

[WARNING] at n3kas.ae.handlers.commands.GKitsCommand.onCommand(GKitsCommand.java:85)

[WARNING] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor323.execute(Unknown Source)

[WARNING] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)

[WARNING] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)

[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$1135/0x00000000910fcbe0.run(Unknown Source)

[WARNING] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[WARNING] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[WARNING] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)

[WARNING] at java.lang.Thread.run(Thread.java:823)

[WARNING] java.lang.ArrayIndexOutOfBoundsException

[WARNING] at java.util.Arrays$ArrayList.set(Arrays.java:3846)

[WARNING] at net.minecraft.server.v1_12_R1.NonNullList.set(SourceFile:51)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:107)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:96)

[WARNING] at n3kas.ae.features.gkits.GInventory.openForPlayer(GInventory.java:47)

[WARNING] at n3kas.ae.handlers.commands.GKitsCommand.onCommand(GKitsCommand.java:85)

[WARNING] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor323.execute(Unknown Source)

[WARNING] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)

[WARNING] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)

[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$1135/0x00000000910fcbe0.run(Unknown Source)

[WARNING] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[WARNING] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[WARNING] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)

[WARNING] at java.lang.Thread.run(Thread.java:823)

[WARNING] java.lang.ArrayIndexOutOfBoundsException

[WARNING] at java.util.Arrays$ArrayList.set(Arrays.java:3846)

[WARNING] at net.minecraft.server.v1_12_R1.NonNullList.set(SourceFile:51)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:107)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:96)

[WARNING] at n3kas.ae.features.gkits.GInventory.openForPlayer(GInventory.java:47)

[WARNING] at n3kas.ae.handlers.commands.GKitsCommand.onCommand(GKitsCommand.java:85)

[WARNING] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor323.execute(Unknown Source)

[WARNING] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)

[WARNING] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)

[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$1135/0x00000000910fcbe0.run(Unknown Source)

[WARNING] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[WARNING] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[WARNING] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)

[WARNING] at java.lang.Thread.run(Thread.java:823)

[WARNING] java.lang.ArrayIndexOutOfBoundsException

[WARNING] at java.util.Arrays$ArrayList.set(Arrays.java:3846)

[WARNING] at net.minecraft.server.v1_12_R1.NonNullList.set(SourceFile:51)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:107)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:96)

[WARNING] at n3kas.ae.features.gkits.GInventory.openForPlayer(GInventory.java:47)

[WARNING] at n3kas.ae.handlers.commands.GKitsCommand.onCommand(GKitsCommand.java:85)

[WARNING] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor323.execute(Unknown Source)

[WARNING] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)

[WARNING] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)

[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$1135/0x00000000910fcbe0.run(Unknown Source)

[WARNING] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[WARNING] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[WARNING] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)

[WARNING] at java.lang.Thread.run(Thread.java:823)

[WARNING] java.lang.ArrayIndexOutOfBoundsException

[WARNING] at java.util.Arrays$ArrayList.set(Arrays.java:3846)

[WARNING] at net.minecraft.server.v1_12_R1.NonNullList.set(SourceFile:51)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:107)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:96)

[WARNING] at n3kas.ae.features.gkits.GInventory.openForPlayer(GInventory.java:47)

[WARNING] at n3kas.ae.handlers.commands.GKitsCommand.onCommand(GKitsCommand.java:85)

[WARNING] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor323.execute(Unknown Source)

[WARNING] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)

[WARNING] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)

[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$1135/0x00000000910fcbe0.run(Unknown Source)

[WARNING] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[WARNING] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[WARNING] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)

[WARNING] at java.lang.Thread.run(Thread.java:823)

[WARNING] java.lang.ArrayIndexOutOfBoundsException

[WARNING] at java.util.Arrays$ArrayList.set(Arrays.java:3846)

[WARNING] at net.minecraft.server.v1_12_R1.NonNullList.set(SourceFile:51)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:107)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:96)

[WARNING] at n3kas.ae.features.gkits.GInventory.openForPlayer(GInventory.java:47)

[WARNING] at n3kas.ae.handlers.commands.GKitsCommand.onCommand(GKitsCommand.java:85)

[WARNING] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor323.execute(Unknown Source)

[WARNING] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)

[WARNING] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)

[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$1135/0x00000000910fcbe0.run(Unknown Source)

[WARNING] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[WARNING] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[WARNING] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)

[WARNING] at java.lang.Thread.run(Thread.java:823)

[WARNING] java.lang.ArrayIndexOutOfBoundsException

[WARNING] at java.util.Arrays$ArrayList.set(Arrays.java:3846)

[WARNING] at net.minecraft.server.v1_12_R1.NonNullList.set(SourceFile:51)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:107)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:96)

[WARNING] at n3kas.ae.features.gkits.GInventory.openForPlayer(GInventory.java:47)

[WARNING] at n3kas.ae.handlers.commands.GKitsCommand.onCommand(GKitsCommand.java:85)

[WARNING] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor323.execute(Unknown Source)

[WARNING] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)

[WARNING] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)

[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$1135/0x00000000910fcbe0.run(Unknown Source)

[WARNING] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[WARNING] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[WARNING] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)

[WARNING] at java.lang.Thread.run(Thread.java:823)

**Comment by Insprill** [comment]
Please properly fill out the information on the template. it's there for a reason. Also, update to the latest version of AE and get back as to if it's still happening, if it is, also send the updated error in a [hastebin](https://paste.insprill.net/)

**Comment by Insprill** [comment]
Closed due to inactivity & lack of information
