### ISSUE TITLE
TAB Complete Commands

### ISSUE THREAD

**Issue by KasearMC** [GC-spigot/AdvancedEnchantments#1587]
Please finish the TAB complete feature for commands. I am dying here.
I see that TAB complete works for commands like: /tinkerer, /asets, etc (maybe because of spigot/paper?). It doesn't work for any of the commands prefixed with "ae".

Using commands like "/ae giveitem" takes like 3-6 minutes to type everything out, and I have to keep switching tabs to go back and forth from the wiki to see all of the items.

**Comment by Insprill** [comment]
Added in 8.0.0-pre20.6
