### ISSUE TITLE
I disabled custom enchants for enchantment tables, but players are still getting them. [Issue]

### ISSUE THREAD

**Issue by nick990099** [GC-spigot/AdvancedEnchantments#1588]
**Describe the bug**
In the config, I disable the enchantment table feature for custom enchants, but players are still getting them sometimes.

**To Reproduce**
Increase the percentage of getting a custom enchant to 100% then disable it and enchant a few things.

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
PaperSpigot 1.16.4

**Comment by Insprill** [comment]
Is this still an issue on pre21.5? Make sure to restart your server to ensure the changes are applied
