### ISSUE TITLE
[Issue] ADD_DURABILITY_CURRENT_ITEM doesn't work on diamond items

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#1590]
**Describe the bug**
It looks like "ADD_DURABILITY_CURRENT_ITEM" works on iron but not diamond. I didn't test it on other tool types.

**To Reproduce**
I was messing around with:
`      effects:
        - 'ADD_DURABILITY_ITEM:-3'
        - 'ADD_DURABILITY_CURRENT_ITEM:-3'`

Trying to get it to work for both armor and tools, and on diamond it was working fine. Both tools and armor were gaining 3. When I use an iron pickaxe they gain 6. 

I listed both in my config because I couldn't get just one to work for both armor and tools (to the item that gives the effect, not random). 

**Server Information (please complete the following information):**
- Server Version: paper 1.16.4
- Plugin Version: 8.0.0-Pre16.2

**Comment by Insprill** [comment]
Is this still an issue on 8.0.0pre21.5/6
