### ISSUE TITLE
[Issue] McMMO Double drop doesn't work with telepathy

### ISSUE THREAD

**Issue by Insprill** [GC-spigot/AdvancedEnchantments#1594]
**Describe the bug**
With [McMMO](https://www.spigotmc.org/resources/64348/) installed if you have the `Double Drop` perk, Telepathy cancels it out. Doesn't matter what chances you have, you only get 1 drop. On all tools as far as I can tell.

**To Reproduce**
`1.` Install [McMMO](https://www.spigotmc.org/resources/64348/).
`2.` Get the `Double Drop` perk.
`3.` Get any tool with Telepathy.
`4.` Break a block.

**Server Information (please complete the following information):**
- Server Version: Paper-323 (1.16.4)
- Plugin Version: 8.0.0-Pre16.8

**Comment by WhatsTheBadNews** [comment]
Something I've discovered in regard to this, on version 8.2.6 and `use-experimental-block-breaking: true`

It partially works for the Woodcutting Double Drops, but not at all for the Mining Double Drops.

When you are level 1000 Woodcutting and mine a tree with a Telepathy axe, one log is sent to your inventory and one is dropped on the ground.

Steps to recreate:
1.) /mmoedit <player> Woodcutting 1000
2.) Enchant an axe with Telepathy
3.) Chop logs with the axe

From my testing, Mining Double Drops is still completely broken as you described. I hope this information helps.
