### ISSUE TITLE
[Issue] WildStacker related error

### ISSUE THREAD

**Issue by DJGamer98765** [GC-spigot/AdvancedEnchantments#1595]
**Describe the bug**
OPs chats are spammed when a player is breaking a block. WildStacker devs told me it's an issue with AdvancedEnchantments.

**To Reproduce**
Players breaking blocks

**Screenshots / Video**
https://pastebin.com/a03Rzs0R
https://imgur.com/a/KukZm4S

**Server Information (please complete the following information):**
- Server Version: PaperSpigot-390 1.15.2
- Plugin Version: 8.0.0-Pre17.0

**Comment by Insprill** [comment]
Can you update to the latest version and see if it still happens? if it does please also send an updated error

**Comment by Insprill** [comment]
Closing this as you have not responded in over 2 weeks. Feel free to create another issue if this still persists.
