### ISSUE TITLE
Mine Reset - Trench stops working (Block updates)[Issue]

### ISSUE THREAD

**Issue by LukeDKL** [GC-spigot/AdvancedEnchantments#1601]
Hey I'm using Jetsprisonmines and AdvancedEnchantments. If you mine in a mine with trench, everything works fine in the start, but if the mine resets... trench is kinda getting broken then... It only works sometimes after the mine has reset. It only works again if you restart your server. (Have tested this on mineresetlite, jetsprisonmines and mines. none of them work.)

**To Reproduce**
Install a mine plugin. Mine in the mine you have setup. Then reset the mine. Now some blocks trench work on and some it doesn't.

- Server Version: Spigot 1.8.8
- Plugin Version: 8.0.0-Pre17.1

**Comment by Insprill** [comment]
Fixed a few updates back
