### ISSUE TITLE
[Issue] TRENCH issue with cobblestone

### ISSUE THREAD

**Issue by CrashyTop** [GC-spigot/AdvancedEnchantments#1602]
**Describe the bug**
The detonate enchantament doesn´t work correctely.
It is breaking only smooth stones. Cobblestone when it breaks drops to the ground, even with telekinesis enchantment

**To Reproduce**
Enchant the pickaxe with telekinessis and detone.Break cobblestones and stones.

**Screenshots / Video**
My config: https://pastebin.com/aMkxfR0N

**Server Information (please complete the following information):**
- Server Version: paper-1.8.8-443.jar
- Plugin Version: 8.0.0-Pre17.1

**Comment by Insprill** [comment]
TRENCH & TP_DROPS have had significant work done since this issue was made, is it still occurring on 8.0.0pre21.5/6?
