### ISSUE TITLE
Premade Installation Throws NoClassDefFoundError [Issue]

### ISSUE THREAD

**Issue by Zilleyy** [GC-spigot/AdvancedEnchantments#1605]
**Describe the bug**
When I type /ae premade and click on a premade installation, it throws the following error

> [14:14:22] [Server thread/INFO]: Zilleyy issued server command: /ae premade
> [14:14:36] [Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedEnchantments v8.0.0-Pre17.1
> org.bukkit.event.EventException: null
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2277) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:941) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
> Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
>         at n3kas.ae.handlers.netbackend.DownloadSetup.init(DownloadSetup.java:33) ~[?:?]
>         at n3kas.ae.handlers.netbackend.PremadeCommandHandler.onClick(PremadeCommandHandler.java:59) ~[?:?]
>         at n3kas.ae.globallisteners.InventoryClicks.onInvClix(InventoryClicks.java:43) ~[?:?]
>         at sun.reflect.GeneratedMethodAccessor202.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
>         ... 18 more

Looks like the issue is that the "FileUtils" dependancy wasn't compiled with the plugin jar...

**To Reproduce**
Type /ae premade on version 1.16.4, only other plugin is Vault.

**Server Information (please complete the following information):**
- Server Version: Spigot 1.16.4
- Plugin Version: Latest as of 17/12/2020

**Comment by Insprill** [comment]
I couldn't recreate this, if you update to the latest version does it still happen?

**Comment by Insprill** [comment]
Fixed at some point
