### ISSUE TITLE
[Issue] Removed-Enchants was removed? Not working.

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#1610]
**Describe the bug**
Removed-enchants appears to no longer work. (Only noticed now) 
Has it been removed/renamed?

**Server Information (please complete the following information):**
- Server Version: Spigot 1.16.4
- Plugin Version: 8.0.0-Pre17.1

**Comment by GC-spigot** [comment]
Works, just tried it
