### ISSUE TITLE
[Issue] BlockTrak doesn't work on shovels

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1612]
**Describe the bug**
BlockTrak doesn't work on shovels

**To Reproduce**
- /ae giveitem (username) blocktrak 1
- Try to put it on a diamond shovel

**Server Information (please complete the following information):**
- Server Version: Tuinity-176 1.16.4
- Plugin Version: 8.0.0-Pre17.1

**Comment by Insprill** [comment]
Fixed a few versions back
