### ISSUE TITLE
[Issue] Blackscroll not working on all items

### ISSUE THREAD

**Issue by Zairce** [GC-spigot/AdvancedEnchantments#1613]
**Describe the bug**
When players get a Blackscroll item and use it on certain items the blackscroll wont work and give an error. If you do this on an item without vanilla enchants it does work however
**To Reproduce**
I tried it on a Diamond Shovel and Diamond Axe(Netherite seems to be fine) where the items have 4 vanilla enchants and 4 Custom enchants. When you click with the blackscroll on the item it will consume the blackscroll but not do anything.

**Screenshots / Video**
[Blackscroll not working](https://gyazo.com/ebea1c6aaa0d5d0db04ee52be2255fb0)

`
26.12 15:07:00 [Server] ERROR Could not pass event InventoryClickEvent to AdvancedEnchantments v8.0.0-Pre17.1
26.12 15:07:00 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 0
26.12 15:07:00 [Server] INFO at n3kas.ae.utils.nbt.NBTapi.removeEnchantment(NBTapi.java:211) ~[?:?]
26.12 15:07:00 [Server] INFO at n3kas.ae.globallisteners.listeners.ClickListener.onClicks(ClickListener.java:182) ~[?:?]
26.12 15:07:00 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1227.execute(Unknown Source) ~[?:?]
26.12 15:07:00 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2528) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
26.12 15:07:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

Couldnt get it into the right format
[Pastebin of error](https://pastebin.com/u2sVmM52)

**Server Information (please complete the following information):**
- Server Version: git-Tuinity-"cc34294" (MC: 1.16.4)
- Plugin Version: 8.0.0-Pre17.1

**Comment by GC-spigot** [comment]
Fixed
