### ISSUE TITLE
[Issue] Bugs with smelt + experience + Haste

### ISSUE THREAD

**Issue by CrashyTop** [GC-spigot/AdvancedEnchantments#1614]
**Describe the bug**
Haste -> One being kind of important to fix though which is that the haste enchantment does not disappear after a tool breaks. If I apply haste to a diamond pickaxe and I mine until it breaks, I still have haste effect
Smelt + Fortune -> If you mine coal and have these two enchantments, fortune doesn't work.
Experience + Smelt -> If you have these two enchantments on the pick, expericience doesn't work, you just don't get anything.

**To Reproduce**
Just apply these enchantments to the item.

**Screenshots / Video**
There's no need, it's simple to understand.

**Server Information (please complete the following information):**
- Server Version: paper-1.8.8-443
- Plugin Version: 8.0.0-Pre17.3

**Comment by Insprill** [comment]
Closing as all these appear to be fixed
