### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by ludgart** [GC-spigot/AdvancedEnchantments#1616]
Duplication Glitch.
No more infos, because the developer dont want talk about the issues in his plugin. I tried to contact him, but the result was a ban on his discord server. I also dont understand why he is not offering support on his discord server. Very strange for someone who is trying to sell plugins without support - except github for creating bugs.

Regards
ludgart

**Comment by GC-spigot** [comment]
No info = no fix lol

**Comment by ludgart** [comment]
Is that my problem if you ban me on your discord server? I tried to contact you with the problems, but you was not in the situation to help or even to listen to me.
