### ISSUE TITLE
 the detonate destroys private chests

### ISSUE THREAD

**Issue by fin95** [GC-spigot/AdvancedEnchantments#1619]
I use the blocklocker plugin on my server, and with the detonate charm my users can break signs

**Comment by RulerOfEternity** [comment]
Please use the proper form for reporting, I don't mean to mini-mod, I just want to help, maybe record the process as well, meaning show that you locked the chest, and then use the "Detonate" enchantment on your pickaxe, have fun :D

**Comment by Insprill** [comment]
Fixed
