### ISSUE TITLE
Abiding enchant

### ISSUE THREAD

**Issue by naikyys** [GC-spigot/AdvancedEnchantments#1620]
Hello I would like to report this error, its spamming my whole chat in minecraft and console too. I have no idea what to do with that and what does it mean. Maybe its because of /repair all, but sometimes it happens just for no reason. I've reseted enchantments.yml but it didnt help. 

Here is the error log: https://pastebin.com/LQyAsk4F

**Server Information:**
- Server Version: The newest build of Tuinity
- Plugin Version: 8.0.0-Pre17.1

**Comment by GC-spigot** [comment]
Fixed
