### ISSUE TITLE
AdvancedEnchantments Bug [Issue]

### ISSUE THREAD

**Issue by DJGamer98765** [GC-spigot/AdvancedEnchantments#1622]
**Describe the bug**
I cannot apply enchantments to any items through dropping a book onto anything or by command

**To Reproduce**
Dropping an enchantment book on and item or doing the /ae enchant command

**Screenshots / Video**
https://pastebin.com/muZmH3ML

**Server Information (please complete the following information):**
- Server Version: PaperSpigot-364 1.16.4
- Plugin Version: AdvancedEnchantments 8.0.0-Pre17.3

**Comment by rkclayton** [comment]
I have this same problem.  Worked fine last night and suddenly today the /ae enchant generates a console error:  

https://pastebin.com/uGED6sjP 

Testing with a book the item was DUPED and no enchantment

https://pastebin.com/Ahs6u8cq


Tried completely nuking the whole plugin, folder included and reloading.. same problem.    Went through the usual.. removed all recent changes and no luck.    Seems to be isolated to this plugin.   Running paper 1.16

**Comment by GC-spigot** [comment]
Fixed - was an issue with paper's changes, update will be available on https://advancedplugins.net/ in 20 minutes.
