### ISSUE TITLE
[Important Issue] EFFECT_STATIC type enchantment giving permanent effect without wearing armor

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#1623]
**Describe the bug**
Players can get infinite effects with no armors. For example these enchantments: EFFECT_STATIC
- Drunk 
- Gears
- Anti gravity
- Overload
- Obsidianshield
- Glowing
- Aquatic 

**To Reproduce**
This bug is related to enderchest which is some hotkey operation. First, player must be have overload or above enchantments. Second, player needs to place armors in hotkey places which is same to enderchest. Then somehow player gets armor effect permanently which is not having armor. The more info in video:

**Screenshots / Video**
https://user-images.githubusercontent.com/21794143/103459012-0792a580-4d47-11eb-9248-45f918296044.mp4

**Server Information
- Server Version: [Paper 1.8. [143]
- Plugin Version: [8.0.0-Pre17.7]

**Comment by Starkenz** [comment]
It is pretty similiar to [#311](https://github.com/GC-spigot/AdvancedEnchantments/issues/311)

**Comment by GC-spigot** [comment]
Fixed
