### ISSUE TITLE
Blackscroll bug

### ISSUE THREAD

**Issue by Gilthunderx** [GC-spigot/AdvancedEnchantments#1628]
Describe the bug
Hello when I try to blackscroll something , a random and nonexistent CE gets obtained. Its confuses me so much.

To Reproduce
Use a blackscroll to a stuff that has CE.

Screenshots / Video
As you can see in this video there's no Glowing enchantment in my helmet and yet it pops out when using blackscroll.
Video Link : https://streamable.com/0l21cm

Server Information (please complete the following information):

1.16.4 Tuinity
AdvanceEnchantment -8.0.0-Pre16.4.jar

**Comment by GC-spigot** [comment]
Update
