### ISSUE TITLE
Cant place CE on stuffs

### ISSUE THREAD

**Issue by Gilthunderx** [GC-spigot/AdvancedEnchantments#1629]
Hello my players are having trouble placing custom enchants on their stuffs, even tho everything is right.

To Reproduce
Any CE Book and apply on tool/sword/armors

Screenshots / Video
I get this error in the console
https://pastebin.com/cSQkNh2x

and video link https://streamable.com/ui0nyp

Server Information (please complete the following information):

1.16.4 Tuinity
Plugin Version -8.0.0-Pre16.4.jar

**Comment by GC-spigot** [comment]
Update
