### ISSUE TITLE
[Issue] Bed Duplication

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1630]
**Describe the bug**
With Telepathy and Auto Smelt, you can duplicate beds.

**To Reproduce**
- Give yourself a diamond pickaxe
- /ae enchant telepathy 4
- /ae enchant autosmelt 3
- Mine a bed

**Server Information (please complete the following information):**
- Server Version: Tuinity-178 1.16.4
- Plugin Version: 8.0.0-Pre17.5

**Comment by Insprill** [comment]
Fixed
