### ISSUE TITLE
[Issue] Enchant Table - always get custom enchant

### ISSUE THREAD

**Issue by EkonC** [GC-spigot/AdvancedEnchantments#1631]
**Describe the bug**
Hello, a player on my server found a bug where you can get a custom enchant every single time even though there should be just a little probability.

**To Reproduce**
1. Go to the enchanting table, put in the item you want to enchant.
2. Put lapis lazuli in and out until any of the enchant level costs changes.
3. When some of the enchant level cost changed, just click the value that changed and you will always have an item with a custom enchant.

**Screenshots / Video**
https://drive.google.com/file/d/1xqsPsMTz-4T3okQjECyQX_aT3d2nyXPC/view?usp=sharing

**Server Information (please complete the following information):**
- Server Version: [I tested it on Paper-355 and Paper-393 1.16.4]
- Plugin Version: [I tested it on 8.0.0-Pre17.1 and 8.0.0-Pre17.5]

**Comment by EkonC** [comment]
Yeah and it doesn't even take the player's enchantment levels

**Comment by GC-spigot** [comment]
Fixed
