### ISSUE TITLE
[Issue] Spartan Hook seems broken

### ISSUE THREAD

**Issue by Spaex** [GC-spigot/AdvancedEnchantments#1632]
When using the Detonate enchantment (TRENCH) with AE Spartan detects this always as FastBreak (I guess since the Nuker Check is included in the FastBreak check). Before that change everything worked perfectly with the Spartan Hook from AE. 
So I guess it broke it.

**To Reproduce**
Use Spartans newest Version + AE then give yourself a Pickaxe with the Detonate Enchantment and no Spartan Bypass Permissions and you will get kicked instantly for FastBreak.

**Server Information (please complete the following information):**
- Server Version: Paper Spigot 1.16.4 - 393
- Plugin Version: 8.0.0. Pre 17.4

**Comment by Insprill** [comment]
Fixed in next update
