### ISSUE TITLE
Telepathy and Restore

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1633]
When having telepathy and restore on the same pickaxe, restore doesn't work at all, even while at max level.

Self explanatory, having telepathy and restore on the same pickaxe doesn't restore durability after it breaks, even at Restore IV, which has a 100 percent repair rate.

**Screenshots / Video**
Restore and Telepathy not working: https://youtu.be/v2L7VBZOQ4I
Restore without Telepathy working normally: https://www.youtube.com/watch?v=gqQ9MVhZbAI

**Server Information (please complete the following information):**
- Server Version: Spigot 1.16.4 two versions behind
- Plugin Version: 8.0.0 Pre17.5

**Comment by Insprill** [comment]
Fixed
