### ISSUE TITLE
[Request] Add specific piece REMOVE_ARMOR effect

### ISSUE THREAD

**Issue by CryLegende** [GC-spigot/AdvancedEnchantments#1634]
Hello,
I would like to know if you can add effects like REMOVE_CHESTPLATE, REMOVE_LEGGINGS, REMOVE_HELMET... I know which already has the REMOVE_RANDOM_ARMOR effect but I would like to choose more specifically which piece of armor should be removed :)

Thank you ! ^^

**Comment by Insprill** [comment]
Added in the next update. Will be the `REMOVE_ARMOR` effect.
