### ISSUE TITLE
[Issue] Enchanting custom enchant books

### ISSUE THREAD

**Issue by dig** [GC-spigot/AdvancedEnchantments#1635]
**Describe the bug**
You can enchant the custom enchant books (the ones with success / destroy rates).

**To Reproduce**
- Place a custom enchant book in enchanting table.
- Enchant the book with a random enchantment.

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.8.8] Tuinity
- Plugin Version: [e.g. 6.7.8] 8.0.0-Pre17.5

**Comment by GC-spigot** [comment]
Fixed
