### ISSUE TITLE
[Issue] Internal Error when give item enchanted.

### ISSUE THREAD

**Issue by JessyDrew** [GC-spigot/AdvancedEnchantments#1636]
**Describe the bug**
Hi, i come from help. Sorry for my english dude but i'm french.
So, I decided to configure the plugin for my server. Everything was going well. I came back 1 day later, and nothing works anymore.
I deleted the whole folder, put it back, and still internal error.
But, when i do: aegive name diamond_pickaxe 1 . I get a pickaxe. Only internal error with enchantment

**To Reproduce**
I dont really know how to reproduce that.

**Screenshots / Video**
https://haste.athion.net/rezogipabi.bash maybe for the log.

**Server Information (please complete the following information):**
- git-Paper-400 (MC: 1.16.4)
- AdvancedEnchantments-8.0.0-Pre17.1.jar (but i try to dl pre17.5)

**Comment by GC-spigot** [comment]
Update
