### ISSUE TITLE
[Issue] Every attack effect doesn't work on armors

### ISSUE THREAD

**Issue by Shurelia** [GC-spigot/AdvancedEnchantments#1638]
**Describe the bug**
all attack effect (even soul tracker) doesn't work on armors, only work if we hit the enemy using the armor (not wearing them)

**To Reproduce**
take an example enchant, e.g default Chain Lifesteal armor enchant. apply it on an armor and wear it, try hitting a npc/player/mob several times with bare hands, it doesnt work at all, then try holding the armor on hand and try hitting it again several times, it'll trigger the enchant. same case with armor + soul tracker, the soul will increase if we kill player WITH the armor, not if we wears the armor.

**Screenshots / Video**
i dont think this is neccesary, also sorry for broken english

**Server Information (please complete the following information):**
- Server Version: git-Yatopia-"3770a43" (MC: 1.16.4)
- Plugin Version: 8.0.0-Pre17.5

**Comment by GC-spigot** [comment]
It works on armor, and works in hand because at the end of the day it's a plugin limitation: be it armor, a stick or a sword and it's still the same item for the plugin, there's no differentiation between items and armor.
