### ISSUE TITLE
BUG when executing /ae enchant

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#1642]
**Describe the bug**
A bug and console error will show on console when trying to execute "/ae enchant (enchant)

**To Reproduce**
Type "/ae enchant (enchant)"

**Screenshots / Video**
Console Errors
https://pastebin.com/2XHwMgeQ

Not sure if this is related but...
https://pastebin.com/ajTBX7Gh

**Server Information (please complete the following information):**
- Server Version: PaperSpigot git-Paper-267 (MC: 1.16.4)
- Plugin Version: 8.0.0-Pre17.1

**Comment by GC-spigot** [comment]
Update
