### ISSUE TITLE
Menu allows placement of items [Issue]

### ISSUE THREAD

**Issue by SlimeCody** [GC-spigot/AdvancedEnchantments#1643]
Describe the bug
Items can be placed in the right click by default menu of book descriptions of the enchanter, and are removed from existence

To Reproduce

![image](https://user-images.githubusercontent.com/49579480/104789306-4b7ba680-575a-11eb-9b31-960e15c2a94f.png)

**Server Information (please complete the following information):**
- Server Version: airplanelite build 58
- Plugin Version: 8.0.0-Pre17.7

I opened an issue for this back in August, you closed it in October, it was never resolved and still present.

**Comment by Insprill** [comment]
Fixed in next update
