### ISSUE TITLE
[Request] Make Item Slots matter when using Enchanting table.

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#1644]
** Describe the Request**
Right now you can make some pretty op items if you are lucky/keep rolling using the enchanting table. Example:
![Screenshot_476](https://user-images.githubusercontent.com/23641964/104824604-0edba800-584b-11eb-9505-136b9d1f3abf.png)

This is because Item slots are ignored and you can keep enchanting the item if it only has Custom Enchants.
My request is to either not ignore item slots and stop the enchanting, or always give the item some vanilla enchant so it can't be enchanted again.
In addition if you could put Slot Increasers on non-enchanted items it'd make for a quality of life improvement.

**Comment by GC-spigot** [comment]
Fixed
