### ISSUE TITLE
[Issue] Enchanting table doesn't consume xp if only custom enchants appear.

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#1645]
**Describe the bug**
Enchanting table doesn't consume xp if only custom enchants appear when enchanting.
**To Reproduce**
Enchant an item in an enchanting table and get only custom enchants. you will notice xp wasn't consumed.

**Server Information (please complete the following information):**
![Screenshot_477](https://user-images.githubusercontent.com/23641964/104827287-f02ddf00-5853-11eb-8002-a9349cf8a23f.png)
Advanced enchants 8.0.0-Pre18

**Comment by GC-spigot** [comment]
Fixed
