### ISSUE TITLE
[Request] Auto Smelting working with ancient debris

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#1646]
Hi, the auto smelting feature would be really useful if it had an overhaul for 1.16 ore such as ancient debris smelting it into netherite scrap, it would make the enchant overall much more useful overall and i think there is a small bug with it where it currently displays an xp orb dropping for everything mined, even grass and dirt. However the XP isn't granted thankfully so it's not a big deal just something to note.

Thanks,

**Comment by Insprill** [comment]
Added
