### ISSUE TITLE
PLAYER_COMMAND and CONSOLE COMMAND

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#1647]
PLAYER_COMMAND and CONSOLE COMMAND issues.

When I use an enchant to call this command:
> function spells:spells/directory

It marks there was a parse error. When I look at the command log it seems that after the "spells:" it adds a comma and a spacebar on the command, making it :
> function spells, spells/directory

NOTE: the command works fine if ran by player or on a command block and even datapack.

PLAYER_COMMAND
![Screenshot_501](https://user-images.githubusercontent.com/77632389/104950302-66cef780-598e-11eb-9e44-329f95dff22f.png)

CONSOLE_COMMAND
![Screenshot_502](https://user-images.githubusercontent.com/77632389/104950323-73535000-598e-11eb-94a5-87726aaa343c.png)

The code for the Enchant
![Screenshot_504](https://user-images.githubusercontent.com/77632389/104950459-ae558380-598e-11eb-9de9-fe8c79673ab2.png)

- Server Version: paper-1.16.4-342
- Plugin Version: AdvancedEnchantments-8.0.0-Pre17.5

**Comment by GC-spigot** [comment]
This is an issue because enchantment effect lines are based by splitting effect line at `:` symbol, and unfortunately this cannot be resolved directly without redoing how enchantments are processed.
