### ISSUE TITLE
The Advanced Enchantments Admin GUI

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1652]
It is a minor issue with the GUI.

Simply go to page '6', the last page that has any enchantments on it is page 5, but you can keep scrolling further after that, I know it's a minor thing but it is a bit of a cosmetic nuisance in my opinion.

![2021-01-21_16 36 07](https://user-images.githubusercontent.com/76789367/105373677-3a71e000-5c07-11eb-9ab3-e9a9cd28bfc5.png)

**Server Information (please complete the following information):**
- Server Version: Paper 1.16.5 (January 20th version)
- Plugin Version: 8.0.0-Pre18.2

**Comment by GC-spigot** [comment]
Changed
