### ISSUE TITLE
ERROR.

### ISSUE THREAD

**Issue by SirCraftypants** [GC-spigot/AdvancedEnchantments#1653]
**Describe the bug**
Error    https://paste.helpch.at/gibecuqedu.md

**To Reproduce**
I just updated to the latest version stated below and it threw the Error

**Server Information:**
- Server Version: PaperSpigot #434 1.16.5
- Plugin Version: AdvancedEnchantments-8.0.0-Pre18.4

**Comment by SirCraftypants** [comment]
Updated to Paper 1.16.5 #440 and Errors still present.

**Comment by GC-spigot** [comment]
Regen your enchantmentTable.yml file like told in changelogs

**Comment by SirCraftypants** [comment]
My bad, thanks.
