### ISSUE TITLE
[Issue] Better enchants do not transfer when custom enchants are on both weapons/tools

### ISSUE THREAD

**Issue by Jacobwasbeast** [GC-spigot/AdvancedEnchantments#1654]
**Describe the bug**
When you enchant a item that has a custom enchants and a low vanilla enchant with a item with custom enchants and better enchants vis versa vanilla enchants do not transfer.

**To Reproduce**
1. Put sharpness 2 on first weapon
2. Put a couple of custom enchants on same weapon
3. Put sharpness 3 on second weapon
4. Put other custom enchants
5. Put Mending also on second weapon
6. Combine both in enchant table

**Screenshots / Video**
![2021-01-23_17 14 38](https://user-images.githubusercontent.com/38381609/105616707-886d1c00-5d9e-11eb-8ab5-efc78eaf0108.png)
![2021-01-23_17 14 39](https://user-images.githubusercontent.com/38381609/105616709-8905b280-5d9e-11eb-8744-094c27928cfb.png)
![2021-01-23_17 14 41](https://user-images.githubusercontent.com/38381609/105616710-899e4900-5d9e-11eb-904f-ffafecdd68d8.png)
![2021-01-23_17 14 48](https://user-images.githubusercontent.com/38381609/105616711-899e4900-5d9e-11eb-8c96-5d8279faac8f.png)
![2021-01-23_17 14 49](https://user-images.githubusercontent.com/38381609/105616713-8a36df80-5d9e-11eb-834b-e1554f901886.png)
![2021-01-23_17 14 50](https://user-images.githubusercontent.com/38381609/105616714-8a36df80-5d9e-11eb-97af-deceb1a59e1b.png)

**Server Information (please complete the following information):**
- Server Version:  This server ts running Paper version git-Paper-428 (MC: 1.16.5) (Implementing API version 1.16.5-RO.I-SNAPSHOT)
- Plugin Version: 8.0.0-Pre18.4

**Comment by Jacobwasbeast** [comment]
The mending does not transfer in the first arrangement, The sharpness 4 does not transfer in the second.

**Comment by Insprill** [comment]
Should be fixed with the anvil revamp a couple updates ago
