### ISSUE TITLE
[Issue] MCMMO Incompatibilities

### ISSUE THREAD

**Issue by ImHumbug** [GC-spigot/AdvancedEnchantments#1655]
Effect 'TP_DROPS' - doesn't give mcmmo ability bonus drops 
Effect 'BREAK' - doesn't give mcmmo ability bonus drops 
Plugin Version: version 8.0.0-Pre18.5
Server Software: git-Tuinity-"4634206" (MC: 1.16.5)

**Comment by Insprill** [comment]
Duplicate of #1594
