### ISSUE TITLE
[Issue] Lightning sound server-wide

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#1660]
**Describe the bug**
The lightning sound can be heard server-wide, when multiple players have the enchant this becomes a mess.

Hopefully this can be changed, or done through a setting in the config file.

**Comment by EkonC** [comment]
Yes, I would really appreciate this feature as well :)

**Comment by Insprill** [comment]
if you're running Paper you can set the distance lightning sound travels in the paper.yml

**Comment by Sikatsu** [comment]
That would change it for everything, not just the advanced enchantment plugin. So it's not really a great option.
