### ISSUE TITLE
[Issue] Permanent potion effects with walkaround

### ISSUE THREAD

**Issue by emanondev** [GC-spigot/AdvancedEnchantments#1663]
**Describe the bug**
Enchants which adds potion effect to armor equipment adds their effects even when not equipped

**To Reproduce**
Open a chest/doublechest, put your equip on the last 4 slots of the first row of the chest and gain effects, also the effect is not removed when the item is removed/moved from the chest

Probably the plugin treats chest inventory as if it was a player inventory

**Screenshots / Video**
https://i.imgur.com/xSY2vX4.mp4

**Server Information (please complete the following information):**

- git-Paper-443 (MC: 1.16.5)
- Version: 8.0.0-Pre17.6

**Comment by Starkenz** [comment]
it is pretty similiar to #1623. It's been nearly 30 days since i posted issue. No fixes...

**Comment by GC-spigot** [comment]
Fixed
