### ISSUE TITLE
[Request] A damage indicator.

### ISSUE THREAD

**Issue by DisPie** [GC-spigot/AdvancedEnchantments#1667]
A damage indicator that shows how much Total damage you deal per hit.

**Comment by Insprill** [comment]
Can you describe this a little more?

**Comment by Insprill** [comment]
Going to close if you don't respond

**Comment by DisPie** [comment]
hold on i got u. mb about the wait. been logged out for some reason so
didnt get notifications till now that i relogged to email.
u hit something and it shows how much dmg u deal
[image: image.png] this would be great for knowing how much dmg your epicly
enchanted axe does. that or some form of dps stats in its description to
indicate how much dmg u deal. or dps u deal

**Comment by Insprill** [comment]
The DPS stat wouldn't make sense since there's a lot of variables that can modify how much damage you do. As for an actual damage indicator, I feel like while it would be cool, it's outside of the scope of AE. There are plugins out there that do accomplish that, or you could have a custom one made.
