### ISSUE TITLE
[Request] Disable being able to apply books through anvils on custom armor / weapons

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#1668]
**Describe the Request**

I would like it if I can disable the use of anvils for the armorsets, not just repair, but also being able to put even more enchants on it like Mending.

This setting doesn't do the job:

`  anvilCombining: false`

Hope this can be added!

**Comment by SugarBottles** [comment]
this would be nice in general, not just armor sets, i have tools I don't want vanilla enchants applied to.
