### ISSUE TITLE
[Issue] Players getting infinite effects

### ISSUE THREAD

**Issue by kenwoody** [GC-spigot/AdvancedEnchantments#1669]
**Describe the bug**
Players using enderchest/chest to get infinite potion effects. For example if you have overload armor, you can just do hotkey work on enderchest and get its overload effect. And finally you can have permanent effect without armor. Only effect_static type enchantments giving permanent effects.

All players abusing this bug...

**Screenshots / Video**
https://user-images.githubusercontent.com/78399733/106555061-c533d280-6557-11eb-9459-e0f6dcfcf5f3.mp4

**Server Information (please complete the following information):**
- Server Version: [PaperSpigot-123 1.8.8]
- Plugin Version: [8.0.0-Pre17.6]

**Comment by GC-spigot** [comment]
Fixed
