### ISSUE TITLE
[Issue] Permanent Potion effect stats without wearing armor

### ISSUE THREAD

**Issue by Izurumn** [GC-spigot/AdvancedEnchantments#1670]
*Describe the bug*
Players using enderchest to get infinite effect. Overload, Gears, Drunk etc. The thing is player using that bug to get overload effect on health which naked.

*Server Information (please complete the following information):*
- Server Version: [e.g. PaperSpigot-123 1.8.8]
- Plugin Version: [Pre18-17.7]

**Comment by GC-spigot** [comment]
Fixed
