### ISSUE TITLE
Permanent potion effects with SHIFT

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#1671]
Using SHIFT enchants with POTION gives permanent potion effect (ignoring the set duration or the holding shift requirement).

Enchantment used for the example:

flamewalk:
  display: '%group-color%Flamewalk'
  description: "Receive Speed 3 and leave a trail on Fire wherever you walk for 10s"
  applies-to: 'Chestplates'
  type: 'SHIFT'
  group: 'HEROIC'
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 100
      cooldown: 30
      effects:
        - 'PLAY_SOUND_OUTLOUD:ENTITY_FIREWORK_ROCKET_LAUNCH'
        - 'PLAY_SOUND_OUTLOUD:ENTITY_ENDER_DRAGON_SHOOT'
        - 'POTION:SPEED:2:200 %attacker%'

- Server Version: paper-1.16.5-437
- Plugin Version: AdvancedEnchantments-8.0.0-Pre19.0

**Comment by Insprill** [comment]
Fixed in the next update. It'll apply the potion when sneaking & unsneaking so you'll need to use the %is sneaking% condition if you only want it applied when they start sneaking
