### ISSUE TITLE
[Issue] Permanent ae enchantment effects naked

### ISSUE THREAD

**Issue by Imatata** [GC-spigot/AdvancedEnchantments#1672]
**Describe the bug**
Using enderchest or double chest to increase their health(overload), gears(speed), drunk(strength). I think it’s related to effect_static and shift type enchantments.

**To Reproduce**
Need enderchest/chest to get the permanent effect. Probably ae plugin treats chest/enderchest as player inventory. 

**Server Information (please complete the following information):**
- Server Version: [PaperSpigot 1.8.8 latest]
- Plugin Version: [8.0.0-Pre19.1]

**Comment by GC-spigot** [comment]
Fixed
