### ISSUE TITLE
[Issue] Abusing permanent potion effects on itself

### ISSUE THREAD

**Issue by squeezemn** [GC-spigot/AdvancedEnchantments#1673]
**Describe the bug**
Players gets infinite potion effects when not even equipped/wore armor.

**To Reproduce**
1.	You need enderchest/chest.
2.	You need effect_static enchantment type armor
3.	Then put your equip on the last 4 slots of the first row of the chest and gain effects
4.	Then after that effect is not removed when the item is removed/moved from the chest

**Server Information (please complete the following information):**
- Server Version: [PaperSpigot 1.8.8 latest]
- Plugin Version: [8.0.0-17.7]

**Comment by GC-spigot** [comment]
Fixed
