### ISSUE TITLE
Soul Bound not working or duplicating items when used on armor[Issue]

### ISSUE THREAD

**Issue by Alphagetti-Yeti** [GC-spigot/AdvancedEnchantments#1674]
I changed the soul bound enchant so that it could be applied to armor however under 3 different circumstances it would  yield different results upon death.
1- When killed by fall damage, the void, /kill, or lava (Tested could be more death scenarios) armor pieces with the soul bound enchant duplicate upon respawn in the players inventory. (player spawns with 2 of each item in their inventory, not equipped)

2- When killed by a player does as intended, player respawns with all armor pieces that had soul bound on them.

3- When killed by hostile mob items drop to the ground and player does not respawn with any of the soul bound armor.

**To Reproduce**
In the enchantments config, add applicable item/items ALL_ARMOR to soul bound. Place soul bound on armor and die in any of the methods listed above to get corresponding result. 

Enchant config;
----------------------------------------------------------------------------------------------------------------------------------------------
soulbound:
  display: '%group-color%Soulbound'
  description: "A chance to keep item on death."
  applies-to: 'Weapons + Tools + Bows + Armor'
  type: 'DEATH, PASSIVE_DEATH'
  group: 'HEROIC'
  applies:
    - ALL_SWORD
    - ALL_AXE
    - ALL_PICKAXE
    - ALL_SPADE
    - BOW
    - CROSSBOW
    - ALL_ARMOR
    - ELYTRA
  levels:
    1:
      chance: 30
      cooldown: 0
      effects:
        - 'KEEP_ON_DEATH'
    2:
      chance: 60
      cooldown: 0
      effects:
        - 'KEEP_ON_DEATH'
    3:
      chance: 100
      cooldown: 0
      effects:
        - 'KEEP_ON_DEATH'
----------------------------------------------------------------------------------------------------------------------------------------------
^ Changing cooldown around did not seem to have any effect and changing chances only made the expected difference of the effect activating or not.
Server Information:
- Server Version: Spigot Auto updating, presumably most recent version. For minecraft 1.16.4
- Plugin Version: 8.0.0-Pre18.5
- Plugin List:
- Advanced Enchantments
- AutoMessage
- BigDoors
- bigdoorsopener
- CubCustomDrops
- ImageOnMap
- LuckPerms
- Multiverse-core
- WorldBorder
- worldedit
- worldguard

**Comment by Insprill** [comment]
Fixed in the next update
