### ISSUE TITLE
Invincible Effect un-removable

### ISSUE THREAD

**Issue by dramasailor** [GC-spigot/AdvancedEnchantments#1675]
**Describe the bug**
A custom enchant was created to provide Invincible whenever a user hit someone with a sword. Now, we have no way to easily remove this effect or identify who currently has the effect to correct the situation. Not sure if properly a bug or a feature request with personal urgency hopes. 

Enchant in question:

`attractiveness:
  display: '%group-color%Attractiveness'
  description: 'Blinds your opponent '
  applies-to: 'Weapons'
  group: 'SOUL'
  type: 'ATTACK'
  applies:
    - 'ALL_SWORD'
    - 'ALL_AXE'
  levels:
    '1':
      chance: 3
      cooldown: 200
      effects:
        - 'INVINCIBLE %attacker%'
    '2':
      chance: 4
      cooldown: 200
      effects:
        - 'INVINCIBLE %attacker%'
    '3':
      chance: 5
      cooldown: 180
      effects:
        - 'INVINCIBLE %attacker%'`

We've stopped using the enchant currently and want to clear the effect from users.

**Comment by GC-spigot** [comment]
Use EFFECT_STATIC for this effect, it works as it should - makes the player invincible.
If you want to stop the attack, use STOP_ATTACK instead.
