### ISSUE TITLE
Enchantments are not applying to hoe

### ISSUE THREAD

**Issue by rikyriky232** [GC-spigot/AdvancedEnchantments#1676]
Items like mobtrak, blocktrak and other similar ones are not applying to any of the Hoe. I have also made changes in the list of items that the enchantments can be applied to by specifying each of the hoe but it still does not fix the problem.

Config.yml:

items:
  settings:
    can-apply-to:
    - ALL_SWORD
    - ALL_ARMOR
    - ALL_PICKAXE
    - ALL_AXE
    - ALL_SPADE
    - TOOLS
    - WOODEN_HOE
    - DIAMOND_HOE
    - GOLDEN_HOE
    - IRON_HOE
    - NETHERITE_HOE
    - BOOK
    - BOW

==============

The custom enchantment are applying to any of the Hoe hence it's something specific with the transmogscroll, soulgem, trackers

**Comment by GC-spigot** [comment]
Minecraft version? Plugin version?

**Comment by Insprill** [comment]
mobtrak only goes on axes, swords, and bows. blocktrak will be fixed in the next update
