### ISSUE TITLE
Buy book in bulk.

### ISSUE THREAD

**Issue by LoneDevilX** [GC-spigot/AdvancedEnchantments#1677]
**Describe the Request**

Request for buying in bulks in `/ce` menu
able to buy 10x ce book in once, allow us to set the (n) for the player to buy.
eg. 5x, 10x, 20x (n)x

**Comment by GC-spigot** [comment]
We're not adding this, but you can disable confirmation inventory and disable enchanter closing when buying a book. All these settings are located under enchanter and confirmation inventory configuration sections
