### ISSUE TITLE
Shulker box bug - Trench enchant

### ISSUE THREAD

**Issue by naikyy** [GC-spigot/AdvancedEnchantments#1679]
When you try to destroy Shulkerbox with items in it by pickaxe with trench / detonate enchant then the Shulker lose items.

- Server Version: Newest build Tuinity
- Plugin Version: 8.0.0-Pre19.1

**Comment by Insprill** [comment]
You can fix it by doing what antibitcoin did here https://github.com/GC-spigot/AdvancedEnchantments/issues/1692#issuecomment-780836411
