### ISSUE TITLE
Cannot combine tools/armor/weapons together with custom enchants [1.16.5]

### ISSUE THREAD

**Issue by BentoBean** [GC-spigot/AdvancedEnchantments#1680]
**Describe the bug**
When I try to combine any item with different custom enchantments, the xp cost disappears and I cannot combine them. Ive tried to change to rename the item while combining them and the xp cost shows up, the items combine but when you exit out they go back to normal. 

On the home page it shows that you can combine items with different enchantments but it doesn't work for me.

**To Reproduce**
On 1.16.5, enchant 2 of the same armor/tool/weapon with different custom enchantments and then try to combine them in an anvil.

**Screenshots / Video**
![Screenshot (437)](https://user-images.githubusercontent.com/64715744/107097357-a173c500-67c1-11eb-99df-650d83638640.png)

**Server Information (please complete the following information):**
- Server Version: Spigot-1.16.5
- Plugin Version: 8.0.0-pre18.4

**Comment by HappierGore** [comment]
I tried to do the same too, and I discover that it works only if the items has at least, one vanilla enchantment. Now I'm trying to combine and upgrade enchantments. For example:
Comination 1 = Testing I
Combination 2 = Testing I
Result = Testing II

**Comment by Insprill** [comment]
Fixed in the next update
