### ISSUE TITLE
KEEP_ON_DEATH + Totem of Undying = Item Duplication

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#1682]
When using enchants that use KEEP_ON_DEATH while holding a Totem of Undying duplicates the items when a player takes damage that would have killed but negated  the death by Totem of Undying and KEEP_ON_DEATH triggers regardless, granting the player a duplicate of the item that had KEEP_ON_DEATH enchant.

- Server Version: paper-1.16.5-457
- Plugin Version: 8.0.0-Pre19.1

**Comment by GC-spigot** [comment]
Fixed
