### ISSUE TITLE
Error and feature

### ISSUE THREAD

**Issue by TheKlimoT** [GC-spigot/AdvancedEnchantments#1683]
https://pastebin.com/CJ5HWcZd - error

1. Please fix / enchant support for spaces and Russian characters in name
2. Fix the levels in the enchant table, because they are constantly changing and extremely unstable work.
3. And is it possible to add support for formatting spaces in the chat?
4. Another problem in the gui when I flipped to page 5 in /ae admin, I can't go back

- server git-Yatopia-"60fd6b7" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT
- Plugin Version: 8.0.0-Pre19.1

Not \n |
![изображение](https://user-images.githubusercontent.com/26817853/107155937-696cad80-698c-11eb-8981-59af6573e7ed.png)

**Comment by GC-spigot** [comment]
Fixed
