### ISSUE TITLE
[Request] ADD POTION EFFECTS for DEFENSE_MOB

### ISSUE THREAD

**Issue by Hexiss** [GC-spigot/AdvancedEnchantments#1687]
fumigene:
  display: '&7Fumigène'
  description: "When you are near death, you will spawn\na smoke bomb to distract your enemies."
  applies-to: 'Helmet'
  type: 'DEFENSE;DEFENSE_MOB'
  group: 'COMMUN'
  applies:
    - ALL_HELMET
  levels:
    1:
      chance: 100
      cooldown: 500
      condition:
        - '%victim health% > 6 : %stop%'
      effects:
        - 'PARTICLE:CAMPFIRE_SIGNAL_SMOKE:1000:3 %victim%'
        - 'POTION:SLOW:5:60 %attacker%' **<<<< Not working on mob**
        - 'POTION:BLINDNESS:5:60 %attacker%' **<<<< Not working on mob**
        - 'CURE_PERMANENT:SLOW %victim%'
        - 'CURE_PERMANENT:BLINDNESS %victim%

I would like mobs to receive the potion effects configured when attacking a player with the type "DEFENSE_MOB"

**Comment by MamboTND** [comment]
This post only shows what enchantment you used. Try being clear with what the request is with words.

**Comment by Insprill** [comment]
Assuming you meant for enchants to work on mobs, that is now a feature as of 8.6.10.
