### ISSUE TITLE
type "DEFENSE_BOW" isnt trigerred from mob 

### ISSUE THREAD

**Issue by Hexiss** [GC-spigot/AdvancedEnchantments#1688]
Hi,

i would like this setting work from mobs
`#    - DEFENSE_BOW : Effects run only when player gets shot by a bow`

Example:

blindage:
  display: '&eBlindage'
  description: "Chance to prevent enemy arrow from dealing damage."
  applies-to: 'Chestplates'
  type: 'DEFENSE_BOW'
  group: 'COMMUN'
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      chance: 100
      effects:
        - 'STOP_ATTACK'
        - 'MESSAGE:&7[&eBlindage&7] ➤ &eFlèche parée avec succès.'
        
        This configuration work only if player get shot by an another player and not by a mob

**Comment by GC-spigot** [comment]
Added DEFENSE_BOW_MOB enchant type for this
