### ISSUE TITLE
[Issue] Null error in console while starting

### ISSUE THREAD

**Issue by PerchunPak** [GC-spigot/AdvancedEnchantments#1689]
**Describe the bug**
Null error in console while starting

**Screenshots / Video**
https://pastebin.com/RdyZdPqU

**Server Information (please complete the following information):**
- Server Version: Paper-444 1.16.5
- Plugin Version: v8.0.0-Pre19.1

**Comment by GC-spigot** [comment]
Don't use leaked plugins
