### ISSUE TITLE
[Issue] Infinite effects using cake

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#1690]
**Describe the bug**
Obtaining permanent potion effect using right clicking on cake.

**To Reproduce**
When Effect_static type armor users just right clicking on cake it will give you permanent effect without even wore.

**Screenshots / Video**
https://user-images.githubusercontent.com/21794143/107847203-7a05a380-6e24-11eb-8517-ac91cdafef5f.mp4

**Server Information (please complete the following information):**
- Server Version: [PaperSpigot-123 1.8.8]
- Plugin Version: [8.0.0-Pre19.1.4]

**Comment by Starkenz** [comment]
It is pretty similiar to [#1623](https://github.com/GC-spigot/AdvancedEnchantments/issues/1623). But this time if u right click with armor on cake...infinite potion effect

**Comment by GC-spigot** [comment]
Fixed
