### ISSUE TITLE
[Issue] Trench resets shulkers and breaks end portals, it ignores the black list in config file.

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#1692]
**Describe the bug**
Trench resets shulkers and breaks end portals on paper and completely ignores the blacklist from the config file.

**To Reproduce**
I installed a freshly plugin version 8.0.0-Pre19.1.4 on a paper 1.16.5 and restarted, with default configs it still ignores end portals and shulkers, when you break shulkers you lose all items inside and it breaks 3x3, it also breaks end portals, no other plugins are installed.
on my production server same issue and players are abusing it.

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: paper 1.16.5 build #468
- Plugin Version: 8.0.0-Pre19.1.4

**Comment by antibitcoin** [comment]
I am begging for a fix hello?

**Comment by Insprill** [comment]
I just tested it and the blacklist is working fine for me, would you mind sending your config.yml?

**Comment by antibitcoin** [comment]
Here is my full directory
https://www.file.io/download/DEThWd0WBPvg
it might be conflicting with other enchants here is a screenshot of the pickaxe
https://prnt.sc/zw0ui8

**Comment by antibitcoin** [comment]
The shulker on the black list I think refers to the entity instead of the group of shulker, I tried adding shulker_box, red_shulker_box to the blacklist still didn't ignore it, still breaks it and make you lose the content.

**Comment by antibitcoin** [comment]
I have manually fixed it by adding the correct values to the blacklist, kindly push this new config on the next update.
SHULKER is no longer a group for all shulkers as of minecraft 1.16.5 paper latest update <- I assume.
  trench-blacklist:
    - 'AIR'
    - 'BEDROCK'
    - 'LAVA'
    - 'WATER'
    - 'STATIONARY_LAVA'
    - 'STATIONARY_WATER'
    - 'SPAWNER'
    - 'PORTAL'
    - 'SHULKER'
    - 'BARRIER'
    - 'END_PORTAL_FRAME'
    - 'END_PORTAL'
    - 'SHULKER_BOX'
    - 'RED_SHULKER_BOX'
    - 'WHITE_SHULKER_BOX'
    - 'ORANGE_SHULKER_BOX' 
    - 'MAGENTA_SHULKER_BOX'
    - 'LIGHT_BLUE_SHULKER_BOX' 
    - 'YELLOW_SHULKER_BOX'
    - 'LIME_SHULKER_BOX' 
    - 'PINK_SHULKER_BOX'
    - 'GRAY_SHULKER_BOX' 
    - 'LIGHT_GRAY_SHULKER_BOX'
    - 'CYAN_SHULKER_BOX' 
    - 'PURPLE_SHULKER_BOX'
    - 'BLUE_SHULKER_BOX' 
    - 'BROWN_SHULKER_BOX'
    - 'GREEN_SHULKER_BOX' 
    - 'BLACK_SHULKER_BOX'

**Comment by Insprill** [comment]
Alright, glad it's working now :)
I'll leave this open until GC or I get to adding it

**Comment by GC-spigot** [comment]
Fixed
