### ISSUE TITLE
[Request] CustomModelData on AE plugin items.

### ISSUE THREAD

**Issue by ThatOneTree** [GC-spigot/AdvancedEnchantments#1694]
Ability to add custom model data on items used in the AE plugin such as scrolls/dusts. Weapons and tools can already have custom model data, so it'd be nice to have it available for items as well.

**Comment by SirCraftypants** [comment]
I second this, I've attempted with custom model data but i'm guessing id:  is for NBT?  Because it doesn't work with Custom Model Data.

**Comment by Insprill** [comment]
Added for 8.0.0-pre21.7. Under each item, there will be a field called `custom-model-data`. It will autogenerate, however, you need to do whatever for the item to be created, then it will generate the value.
