### ISSUE TITLE
[Issue] SPEED 1 ARMOUR THEN DRINK SPEED 2 POTION (Causes unlimited SPEED 2)

### ISSUE THREAD

**Issue by ConnorServers** [GC-spigot/AdvancedEnchantments#1695]
**Describe the bug**

Say someone has AE that gives them SPEED I
If they drink a SPEED II potion they get infinite SPEED II

**To Reproduce**
A way to reliability reproduce the bug.

Wear SPEED I armour then drink a SPEED II Potion. This will give you unlimited SPEED II.

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

N/A

**Server Information (please complete the following information):**
- Server Version: PaperSpigot 1.8.8
- Plugin Version: Latest

**Comment by MamboTND** [comment]
Lastest doesn't help pinpoint what the problem may arise from.
Please specify the plugin version like this:
AdvancedEnchantments-8.0.0-Pre19.1 
OR 8.0.0 Pre 19.1
ect

**Comment by GC-spigot** [comment]
Cannot recreate.
