### ISSUE TITLE
[Issue] Dragon Doesn't drop assigned loot when killed with ranged weapon

### ISSUE THREAD

**Issue by Tauses** [GC-spigot/AdvancedEnchantments#1697]
**Describe the bug**
The dragon does not drop it's assigned drops when it is killed with a ranged weapon such as a bow or crossbow. 
It only drops it's loot when it is killed with melee weapons.
Drops are set to 100% drop chance

**To Reproduce**
Assign drops to the dragon
Kill with ranged weapon
Watch nothing drop from it

**Server Information (please complete the following information):**
- Server Version: Tuinity-"f8c0db4" (MC: 1.16.5)
- Plugin Version: 8.0.0-Pre18.9

**Comment by GC-spigot** [comment]
Fixed

**Comment by Tauses** [comment]
I'm sorry but this has not been fixed. I just tried killing the dragon multiple times with a bow without getting any assigned drops.

**Comment by GC-spigot** [comment]
> I'm sorry but this has not been fixed. I just tried killing the dragon multiple times with a bow without getting any assigned drops.
Of course it’s not fixed, there hasn’t been an update posted which fixes it.
