### ISSUE TITLE
[Issue] Detonate randomly stops working from version 8.0.0-Pre19.1.2

### ISSUE THREAD

**Issue by Kesims** [GC-spigot/AdvancedEnchantments#1699]
**Describe the bug**
After version 8.0.0-Pre19.1.2 (including that version) detonate enchant activates only sometimes, (even with 100% chance). I cant really tell what is causing it, it seems pretty random. I thought mby you know about that, but 8.0.0-Pre19.1 works fine for me and every version after that some enchants (it seems like those that are using MINING) are randomly not working. Is it possible? I dont have any errors in console. Am I just stupid and I should somehow update config for this version or? Thanks

**To Reproduce**
Cant really tell, it just sometimes activates, sometimes not...

**Server Information (please complete the following information):**
- Server Version: PaperSpigot-416 1.16.4
- Plugin Version: Every version 8.0.0-Pre19.1.2+

**Comment by GC-spigot** [comment]
New update is coming out today, try it and if it causes issues again reply here so we know this issue isn't fixed.

**Comment by Kesims** [comment]
Hey, it does not seem anything is fixed, still the same issue, players are reporting that their enchants actiavte only sometimes...

**Comment by GC-spigot** [comment]
Update with a fix for this was delayed, should be coming out today.

**Comment by Kesims** [comment]
Hello, I dont see any change in new update, so here is my config and a video, so you can take a look what it is doing... 

[AdvancedEnchantments.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/6033932/AdvancedEnchantments.zip)
https://youtu.be/Fkh-NR8BGNo

**Comment by Kesims** [comment]
@GC-spigot

**Comment by Kesims** [comment]
Yep, it seems like it is not working on same place twice - which us very unfortunate for skyblock type generators.. :/

**Comment by Insprill** [comment]
Fixed in next update
