### ISSUE TITLE
[Issue] Uh idk why this is happening but its like duping enchants

### ISSUE THREAD

**Issue by MelonFall** [GC-spigot/AdvancedEnchantments#1700]
**Describe the bug**

**To Reproduce**
A way to reliability reproduce the bug.

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

https://user-images.githubusercontent.com/79421584/108637784-2580aa80-745a-11eb-8018-340e943ff8e0.mp4

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.8.8]
- Plugin Version: [e.g. 6.7.8]

**Comment by Insprill** [comment]
Fixed
