### ISSUE TITLE
Detonate false positives AAC actions.interact check [Issue]

### ISSUE THREAD

**Issue by Vehzx** [GC-spigot/AdvancedEnchantments#1705]
**Describe the bug**
When using detonate, players get kicked due to AdvancedAntiCheat's actions.interact check, as far as i'm aware, Detonate and Atomic Detonate are the only enchantments that cause any issues with AAC, I spent some time testing all enchants.

**To Reproduce**
Have AAC instead, doesn't matter about any certain configs, it happens on default AAC settings, enchant a pick with detonate or atomic detonate, mine and then when it proc's it will kick the player.

**Screenshots / Video**
https://i.gyazo.com/802df3fc9f4d3d828f96ffa3d3a620e2.mp4

**Server Information (please complete the following information):**
- Server Version: git-paper-446
- Plugin Version: 8.0.0-Pre19.1

**Comment by Insprill** [comment]
what version of AAC does this happen with?

**Comment by Vehzx** [comment]
It definitely happens with 8.0.0-Pre19.1.4

I recently updated to 8.0.0-Pre20 and haven't got the chance to test it, since there is no note of this in the patch notes on spigot, I assume it's still an issue

**Comment by Insprill** [comment]
yes but what version of AAC are you running?

**Comment by Vehzx** [comment]
Like I said, right now 8.0.0-Pre20

But I haven't managed to test it yet on this version.

I know on version 8.0.0-Pre19.1.4 it definitely happened.

**Comment by Vehzx** [comment]
My mistake, I read that wrong.

version 5.0.11

**Comment by Insprill** [comment]
Fixed
