### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by GothkittyGirl** [GC-spigot/AdvancedEnchantments#1706]
**Describe the bug**
running /enchanter gives a enternal error

**To Reproduce**
type /enchanter

**Screenshots / Video**
23.02 21:32:16 [Server] INFO RTH3 issued server command: /enchanter
23.02 21:32:16 [Server] ERROR null
23.02 21:32:16 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'enchanter' in n3kas.ae.handlers.commands.EnchanterCommand(enchanter)
23.02 21:32:16 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
23.02 21:32:16 [Server] INFO Caused by: java.lang.IllegalStateException: zip file closed
23.02 21:32:16 [Server] INFO at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_265]
23.02 21:32:16 [Server] INFO at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_265]
23.02 21:32:16 [Server] INFO at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_265]
23.02 21:32:16 [Server] INFO at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_265]
23.02 21:32:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
23.02 21:32:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
23.02 21:32:16 [Server] INFO at n3kas.ae.handlers.commands.EnchanterCommand.execute(EnchanterCommand.java:65) ~[?:?]
23.02 21:32:16 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
23.02 21:32:16 [Server] INFO ... 18 more

**Server Information (please complete the following information):**
- Server Version: Paper 1.16.5
- Plugin Version: 8.0.0-Pre20

**Comment by Insprill** [comment]
Download the latest version and fully restart your server.
