### ISSUE TITLE
[Issue] Tinkerer Glitch

### ISSUE THREAD

**Issue by Truger23** [GC-spigot/AdvancedEnchantments#1707]
I inserted a few axes with custom enchantments into the menu, then closed the menu and the axes clones. 

Video: https://www.youtube.com/watch?v=Oeylw63KGk8

- Server Version: Yatopia version git-Yatopia-ver/1.16.5-24 (MC: 1.16.5)
- Plugin Version: 8.0.0-Pre19.1

**Comment by Insprill** [comment]
I wasn't able to reproduce this issue however in pre20.1 I made some internal changes to the tinkerer, can you see if it still happens?

**Comment by Truger23** [comment]
Hi, yes, this glitch still works :/

**Comment by Insprill** [comment]
can you try on a test server with just AE and see if it still happens? if it doesn't, try adding back plugins one by one until it starts happening again. I have a feeling another plugin is interfering and causing the issue as I'm not able to reproduce and you're the only person who has reported this

**Comment by Truger23** [comment]
Yea, sorry, my fault. Items for those enchant books etc. missing in the config, now it works correctly.

**Comment by Insprill** [comment]
So is it all working now?

**Comment by Truger23** [comment]
Yes
