### ISSUE TITLE
[Request] ENCHANT removes ON DEATH

### ISSUE THREAD

**Issue by ConnorServers** [GC-spigot/AdvancedEnchantments#1708]
**Describe the Request**

When a player dies.
The enchantment removes from the item. OR just make the entire item disappear if you can't do that.

Cheers!

**Comment by Insprill** [comment]
To remove an enchant, you can add `'REMOVE_ENCHANT:name'` in the effects, and to break the item you can add `ADD_DURABILITY_ITEM:%maximum durability%`
