### ISSUE TITLE
Black Scroll not recognizing Tridents or other items [Issue]

### ISSUE THREAD

**Issue by SelinaTL** [GC-spigot/AdvancedEnchantments#1709]
**Describe the bug**
Black Scrolls do not take off or display any message when dragging onto a Trident, or any item we've given the ability to apply an enchant to. Such as a custom stick weapon we've made on our server.

**To Reproduce**
Applying a default Trident enchant onto a trident and attempting to use a black scroll as normal

**Server Information (please complete the following information):**
- Server Version: 1.16.4
- Plugin Version: AdvancedEnchantments-8.0.0-Pre19.1.4

**Comment by GC-spigot** [comment]
Added `TRIDENT` to this list and restart: https://github.com/GC-spigot/AdvancedEnchantments/blob/42c5ba82b99bb6b3f84bf418963c7ecdd627b887/config.yml#L257
