### ISSUE TITLE
New Error /ae admin

### ISSUE THREAD

**Issue by TheKlimoT** [GC-spigot/AdvancedEnchantments#1710]
Error: https://paste.helpch.at/opucoqoxem.pl

Open /ae admin and scroll the page forward and then back, and this error will pop up!

>     Server Version: git-Purpur-993 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
>     Plugin Version: AdvancedEnchantments v8.0.0-Pre20

**Comment by Insprill** [comment]
Fixed
