### ISSUE TITLE
Telepathy makes blocks disappear on full inventory [Issue]

### ISSUE THREAD

**Issue by Pudiaz** [GC-spigot/AdvancedEnchantments#1711]
**Describe the bug**
When you mine with a full inventory, all other blocks disappear.

**To Reproduce**
fill inventory items, and break a block with telepathy

**Screenshots / Video**
https://youtu.be/twOU7tnRO3I

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-497 - 1.16.5]
- Plugin Version: [AdvancedEnchantments-8.0.0-Pre17.1] (we would update but everytime we do the whole advanced enchantments plugin breaks on us)

**Comment by Pudiaz** [comment]
1.16.4 - 1.16.5 mc server ^

**Comment by Insprill** [comment]
Fixed
