### ISSUE TITLE
[Request] Add the ability for 'not-applyable-with' to work with vanilla enchantments

### ISSUE THREAD

**Issue by t-34-2** [GC-spigot/AdvancedEnchantments#1712]
**Describe the Request**
Please add the ability for custom and vanilla enchantments to be mutually exclusive with each other.

Currently, it works like:
#    not-applyable-with:
#      - 'frozen'

With added support for vanilla enchantments, maybe something like:

#    not-applyable-with:
#      - 'FIRE_ASPECT'

You'll probably need to reserve vanilla enchant names for this feature, so it won't conflict with CE names.

**Comment by Insprill** [comment]
This does work, not sure if it did when this request was made but it does currently. You just need to use the names [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html).
