### ISSUE TITLE
[Issue] Ender Dragon not dropping assigned loot when killed via thorns

### ISSUE THREAD

**Issue by Tauses** [GC-spigot/AdvancedEnchantments#1713]
**Describe the bug**
Dragon does not drop assigned loot when it dies because of the Thorns assignment.

**To Reproduce**
Kill dragon by using Thorns enchantment

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: 1.16.5 Tuinity-"f8c0db4"
- Plugin Version: 8.0.0-Pre20

**Comment by Insprill** [comment]
Is it just the dragon or all mobs? and is it still an issue on the latest version?

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by Tauses** [comment]
Great thank you
