### ISSUE TITLE
[Issue] ADD_HEALTH removes health

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1714]
**Describe the bug**
When the ADD_HEALTH effect is activated on a player, it removes health from them.

**To Reproduce**
Use a weapon or armor that has an enchantment with the ADD_HEATLH effect and let the ADD_HEALTH effect activate.

**Server Information (please complete the following information):**
- Server Version: Tuinity 192
- Plugin Version: 8.0.0-Pre20.1. This did not happen on 8.0.0-Pre20

**Comment by nivcoo** [comment]
Yes i've the same issue thx :p

**Comment by CyberStorm3868** [comment]
same issue here.

**Comment by Insprill** [comment]
Fixed in next update
