### ISSUE TITLE
Cancel Use Effect not working

### ISSUE THREAD

**Issue by xXDarkCvBxX** [GC-spigot/AdvancedEnchantments#1715]
**Describe the bug**

The Cancel_use effect is seen not working

**To Reproduce**
Trying to use the cancel_use effect to cancel the use of apples, it is seen that it does not work, this is my enchantment that I create, I tried it without the% victim% and with it and neither of the 2 ways worked

demency:
  display: '&7Demency'
  description: "Probabilidad de bloquear el uso de manzanas al usuario que pegas"
  applies-to: 'Espadas y Hachas'
  type: 'ATTACK'
  group: 'HEROIC'
  applies:
    - ALL_AXE
    - ALL_SWORD
  levels:
    1:
      cooldown: 90
      chance: 30
      effects:
        - 'CANCEL_USE:GOLDEN_APPLE:200 %victim%'
        - 'CANCEL_USE:ENCHANTED_GOLDEN_APPLE:600 %victim%'
        - 'MESSAGE:&aHas cancelado las manzanas al enemigo! %attacker%'
    2:
      cooldown: 80
      chance: 50
      effects:
        - 'CANCEL_USE:GOLDEN_APPLE:300 %victim%'
        - 'CANCEL_USE:ENCHANTED_GOLDEN_APPLE:600 %victim%'
        - 'MESSAGE:&aHas cancelado las manzanas al enemigo! %attacker%'
    3:
      cooldown: 70
      chance: 70
      effects:
        - 'CANCEL_USE:GOLDEN_APPLE:400 %victim%'
        - 'CANCEL_USE:ENCHANTED_GOLDEN_APPLE:600 %victim%'
        - 'MESSAGE:&aHas cancelado las manzanas al enemigo! %attacker%'

**Screenshots / Video**

**Server Information (please complete the following information):**
- Server Version: Paper-481 1.16.5
- Plugin Version: 8.0.0-Pre20 Changelog

**Comment by Insprill** [comment]
Copy pasted your exact enchant and it worked fine. 8.0.0-pre21.7.
