### ISSUE TITLE
[Issue] Detonate not working on the same place twice.

### ISSUE THREAD

**Issue by Kesims** [GC-spigot/AdvancedEnchantments#1717]
**Describe the bug**
This extends issue #1699 , that wasnt resloved, but still got closed.

After version 8.0.0-Pre19.1.2 (including that version) detonate enchant activates only sometimes, (even with 100% chance).  I thought mby you know about that, but 8.0.0-Pre19.1 works fine for me and every version after that some enchants (it seems like those that are using MINING, mby only TRENCH (I couldnt find out) ) are not working on the same twice. By "same place" I mean area where the enchant was already used. Is it possible? That is a pretty big problem for skyblock generators, where you mine on the same spot... I dont have any errors in console. Thanks

**To Reproduce**
Use Detonate enchant on same place twice in version 8.0.0-Pre19.1.2+.
[AdvancedEnchantments.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/6054718/AdvancedEnchantments.zip)

**Screenshots / Video**
https://youtu.be/Fkh-NR8BGNohttps://youtu.be/Fkh-NR8BGNo

**Server Information (please complete the following information):**

    Server Version: PaperSpigot-416 1.16.4
    Plugin Version: Every version 8.0.0-Pre19.1.2+

**Comment by Insprill** [comment]
Fixed in next update
