### ISSUE TITLE
[Request] Support for GenCubes

### ISSUE THREAD

**Issue by Kesims** [GC-spigot/AdvancedEnchantments#1718]
**Describe the Request**
Hello, would it be possible to add support for GenCubes? 

DeadSilence (developer of gen cubes) tried to contact you, but you didnt respond. It would be supper cool if players could use enchants in these cubes. If you want to, I can buy a copy of AE for DeadSilence, so he can test everything himself. Just please, would it be possible to leave him some message about the plugin? It would be advantageous for both plugins and for a lot of players on servers that use both plugins... 

Contact on him: DeadSilenceIV#5307
Link to GenCubes plugin: https://www.spigotmc.org/resources/%E2%9A%A1-gencubes-%E2%9A%A1-%E2%9E%A4-skyblock-prison-utility-%E2%9B%8F-custom-sizes-%E2%AD%90upgrades-%E2%9C%85sells-%E2%9C%A8smelting-fawe.84010/

Thank you very much!

**Comment by Kesims** [comment]
If you are not interested in this, I can pay for implementing it... :)

**Comment by Kesims** [comment]
The problem right now is, that enchants are not working inside the cube. For example if I use detonate inside, it just breaks 1 block instead of 3x3.

I think it has something to do with GenCube protection. But I am not developer, so idk, maybe DeadSilence could tell you more about that.

**Comment by Kesims** [comment]
Here is an example video of Trench not working inside GenCube

https://youtu.be/Lg2bm1TDcgI

**Comment by Insprill** [comment]
Doesn't look like we'd be able to add support. They must be canceling our BlockBreakEvents for TRENCH causing the blocks to... not break. They can check if the block has the `fakeBreak` meta, and if it does, it's from TRENCH.
