### ISSUE TITLE
[Issue] Angelic enchant

### ISSUE THREAD

**Issue by naikyy** [GC-spigot/AdvancedEnchantments#1720]
When you have armor with Angelic and you got shot or healed, you have left just one heart for some reason.

**Server Information:**
- Server Version: Purpur
- Plugin Version: 8.0.0-Pre20.2

**Comment by Sikatsu** [comment]
Same issue with implants.

**Comment by Insprill** [comment]
Fixed in next update

**Comment by Sikatsu** [comment]
Still an issue for me on last night's update..
