### ISSUE TITLE
[Request] Support for UltraSkyblockCore

### ISSUE THREAD

**Issue by harmatosbikafing** [GC-spigot/AdvancedEnchantments#1722]
**Describe the Request**
Hi, can you add support for UltraSkyblockCore?

Ultraskyblockcore is a great system plugin which brings features from a big network. I also mentioned at InsiderAhn's discord too, but i didn't get any answer yet. So I write the idea here too and I hope you will accept this request. It would be advantageous for both plugins and for a lot of players on servers that use both plugins...

UltraSkyblockCore link: https://www.spigotmc.org/resources/ultraskyblock-core-skills-collections-mines-armors-fairy-souls-pets-runes-talismans.83598/

I look forward from hearing you soon.
Your sincerely,
harmatosbikafing

**Comment by Insprill** [comment]
what specifically do you want us to add?

**Comment by harmatosbikafing** [comment]
For example, in UltraSkyblockCore you can give stats to an item like defense, strenght, etc. So it would be cool if we can give attributes for armorsets and weapons too.

**Comment by harmatosbikafing** [comment]
> For example, in UltraSkyblockCore you can give stats to an item like defense, strenght, etc. So it would be cool if we can give attributes for armorsets and weapons too.
> 
> Edit: I noticed that you can add events like INCREASE_DAMAGE in AE, so it would be cool if the stats of the items from AdvancedEnchantments are synchronised with UltraSkyblockCore's attribute system. Also, my another idea is larger customisation of armorsets like at gkits for example changing materials of the items.

.

**Comment by harmatosbikafing** [comment]
> > For example, in UltraSkyblockCore you can give stats to an item like defense, strenght, etc. So it would be cool if we can give attributes for armorsets and weapons too.
> > Edit: I noticed that you can add events like INCREASE_DAMAGE in AE, so it would be cool if the stats of the items from AdvancedEnchantments are synchronised with UltraSkyblockCore's attribute system. Also, my another idea is larger customisation of armorsets like at gkits for example changing materials of the items.
> 
> .

.

**Comment by Insprill** [comment]
UltraSkyblockCore is a fairly small plugin, and deeply integrating into it wouldn't make a lot of sense for multiple reasons; the time to do it being #1. They might be able to use our API to integrate into our plugin to a certain extent, but that's about it.
