### ISSUE TITLE
[Issue] Mining a Shulker Box with a pickaxe that has Telepathy AND Silk Touch deletes the contents of the shulker box

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1724]
**Describe the bug**
Mining a Shulker Box with a pickaxe that has Telepathy AND Silk Touch deletes the contents of the shulker box

**To Reproduce**
1.) Fill a shulker box with items and place it
2.) Give yourself a pickaxe
3.) Enchant the pickaxe with Telepathy 4 AND Silk Touch
4.) Mine the shulker box with the aforementioned pickaxe
5.) Look at the shulker box and see that it has lost its contents

**Server Information (please complete the following information):**
- Server Version: Tuinity 192
- Plugin Version: 8.0.0-Pre20.3

**Comment by Sikatsu** [comment]
Happens for me with the detonate / trench enchantment

**Comment by Insprill** [comment]
@Sikatsu update your trench blacklist in the config.yml. [Here is this most up to date](https://paste.insprill.net/dagiqeluyi.yaml)

**Comment by Insprill** [comment]
Fixed in next update
