### ISSUE TITLE
[Issue] Infinite effects using enderchest/chest

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#1726]
**Describe the bug**
Players can get infinite effects with no armors. 

Enchants:
Gears
Anti gravity

**To Reproduce**
This bug is related to enderchest which is some hotkey operation. First, player must be have overload or above enchantments. Second, player needs to place armors in hotkey places which is same to enderchest. Then somehow player gets armor effect permanently which is not having armor.

**Server Information (please complete the following information):**
- Server Version: [PaperSpigot-123 1.8.8]
- Plugin Version: [8.0.0-Pre20.3]

**Comment by Insprill** [comment]
I'm having a bit of a hard time understanding what you're trying to say, could you send a video of the bug?

**Comment by Starkenz** [comment]
@Insprill [Video](https://user-images.githubusercontent.com/21794143/103459012-0792a580-4d47-11eb-9248-45f918296044.mp4). It is pretty similiar to above video. But this time Gears, Gravity working only.

**Comment by Insprill** [comment]
that video is really laggy, is it related to moving items in inventories via number keys?

**Comment by Starkenz** [comment]
Yes with hotkey interaction. Here's the another [video](https://user-images.githubusercontent.com/78399733/106555061-c533d280-6557-11eb-9459-e0f6dcfcf5f3.mp4).

**Comment by Insprill** [comment]
Fixed in next update
