### ISSUE TITLE
[Issue] Holywhitecroll not working

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#1727]
**Describe the bug**
Holywhitescroll not working on certain armor or gkits.

**To Reproduce**
More info on video:.

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/21794143/109540805-f0c9be80-7afd-11eb-9895-3daab0c03919.png)
https://youtu.be/4KTqfPlPFJc

**Server Information (please complete the following information):**
- Server Version: [PaperSpigot-123 1.8.8]
- Plugin Version: [8.0.0-Pre20.3]

**Comment by GC-spigot** [comment]
Fixed
