### ISSUE TITLE
Shulker box with detonate removes all the items inside the shulker [Issue]

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#1729]
**Describe the bug**
When you break a shulker box with detonate it removes all the items inside the shulker.

**To Reproduce**
- Put items in a shulker.
- Enchant your pickaxe with detonate.
- Break the shulker with that pickaxe

**Server Information (please complete the following information):**
- Server Version: git-Purplane-"b5b6595" (MC: 1.16.5)
- Plugin Version: AdvancedEnchantments version 8.0.0-Pre20.3

**Comment by naikyy** [comment]
Use trench-blacklist and block shulkers in the config.

**Comment by Agaloth** [comment]
Doesn't work, it still gets broken.
