### ISSUE TITLE
[Issue] Holy White Scrolls not applying to items with enchantments on them

### ISSUE THREAD

**Issue by PeterDorvay** [GC-spigot/AdvancedEnchantments#1730]
**Describe the bug**
On the current version, holy white scrolls will not apply to items with enchantments on them. If you try to apply a scroll onto an item, it just swaps places with the item.

**To Reproduce**
1. Give yourself a weapon
2. Give yourself a holy white scroll (/ae giveitem player holywhitescroll 1 100 0)
3. Enchant the weapon (/ae enchant abiding 1)
4. Click and drag the holy white scroll onto the item - it will not apply

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: Tuinity 1.16.4
- Plugin Version: 8.0.0-pre20.3

**Comment by GC-spigot** [comment]
Fixed
