### ISSUE TITLE
Advanced Enchantments not loading into server

### ISSUE THREAD

**Issue by Pudiaz** [GC-spigot/AdvancedEnchantments#1734]
https://mcpaste.io/78d6cb65d9de1c57

Im unsure why advanced enchantments isnt working / loading, can someone help?

**Comment by Pudiaz** [comment]
The old version of advanced enchantment works ^ but i would like to update it but when i do it doesn't load into the server correctly.

**Comment by Insprill** [comment]
what version of AE is this error occurring, what version did it work, and what is the output of `/ver`?

**Comment by Pudiaz** [comment]
"This server is running paper version git-Paper-"60e92c061"(MC: 1.16.5) (Implemented API version 1.16.5-R0.1-SNAPCHAT) Previous version: git-Paper-"06900aef5" (MC: 1.16.5) you are 1 version(s) behind"

The version of AE it is occurring is latest one, the one that is working for me right now is version - AdvancedEnchantments-8.0.0-Pre17.1.jar

**Comment by Insprill** [comment]
Fixed in the next update
