### ISSUE TITLE
[Request] ADD SUPPORT FOR CMI HEADS

### ISSUE THREAD

**Issue by Hexiss** [GC-spigot/AdvancedEnchantments#1735]
add CMI heads support for the effect 'DROP_HEAD %victim%'

Like when we kill a mob heads dropped are them from CMI and not them from AdvancedEnchantments it's avoid to have different NTB TAG and name (huge for server using custom craft)

CMI : https://www.spigotmc.org/resources/cmi-280-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

**Comment by GC-spigot** [comment]
Sorry but we don't add such features. Best case you can give the head with a command.
