### ISSUE TITLE
[Issue] Can't Apply HolyWhiteScroll on Items.

### ISSUE THREAD

**Issue by ShockCharge** [GC-spigot/AdvancedEnchantments#1737]
Appearently if you use HolyWhiteScroll on a normal item it works but if you apply it on items that has higher value that bypass Vanilla values lets just say Protection X aka Protection 10.

Here is an example:
![image](https://user-images.githubusercontent.com/48907444/109835950-a7ed4380-7c7e-11eb-9ff7-8ac7b2db291a.png)
![image](https://user-images.githubusercontent.com/48907444/109835964-ac196100-7c7e-11eb-9a5d-e8b61e68cdfe.png)

git-Purpur-997 (MC: 1.16.5)
![image](https://user-images.githubusercontent.com/48907444/109836200-e4b93a80-7c7e-11eb-9411-000f7c3191f2.png)

8.0.0-Pre20.4
![image](https://user-images.githubusercontent.com/48907444/109836174-dec35980-7c7e-11eb-826f-7941c95eac2b.png)

**Comment by ShockCharge** [comment]
Still happening on 8.0.0-Pre20.5
![image](https://user-images.githubusercontent.com/48907444/110076843-1ab20800-7dc0-11eb-96db-46552988b035.png)
![image](https://user-images.githubusercontent.com/48907444/110076853-1d146200-7dc0-11eb-8e1e-a209cd93e541.png)
![image](https://user-images.githubusercontent.com/48907444/110076865-24d40680-7dc0-11eb-81f3-0190aca580ea.png)

**Comment by ShockCharge** [comment]
Tried it with different enchantments this time:

(Normal Bow) 
![image](https://user-images.githubusercontent.com/48907444/110077582-5ac5ba80-7dc1-11eb-80d9-14a5b970808c.png)
![image](https://user-images.githubusercontent.com/48907444/110077587-5f8a6e80-7dc1-11eb-8a0a-f869462570ac.png)

And it wont apply on Power 3
![image](https://user-images.githubusercontent.com/48907444/110077614-6f09b780-7dc1-11eb-85ea-488b2b5ff358.png)
And Power 10
![image](https://user-images.githubusercontent.com/48907444/110077657-8052c400-7dc1-11eb-873d-527b538ba32b.png)

**Comment by ShockCharge** [comment]
Bump! still not working on 8.0.0-Pre20.6

**Comment by GC-spigot** [comment]
Fixed
