### ISSUE TITLE
Mob Spawner Dupe[Issue]

### ISSUE THREAD

**Issue by ecosyz** [GC-spigot/AdvancedEnchantments#1738]
**Describe the bug**
When you have a pickaxe with detonate

 it will actually dupe the spawners when you try to mine it with silktouch pickaxe (Im using silkspawners plugin)

**To Reproduce**
A way to reliability reproduce the bug.
Download the silkspawners plugin and get your self a detonate pickaxe (in this case it was a detonate 7) and place a spawner it doenst matter just allow yourself to mine the spawner with silktouch. When you mine it with a silktouch detonate 7 pickaxe and when you try to mine the spawner it will dupe the spawner while the spawner doesnt get mined so you will get 3 spawners... 2 spawners will drop on the ground and 1 will stay there.o
**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.
I tried to put the video here but since its too big I dont know where to send 2 my discord is xentiaga#8106
**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.8.8]
- paperspigot 1.16.5
- Plugin Version: [e.g. 6.7.8]
- advancedenchantements 8.0.0 pre

**Comment by Insprill** [comment]
Fixed in next update
