### ISSUE TITLE
[Issue] Black scrolls not removing enchantments from items

### ISSUE THREAD

**Issue by PeterDorvay** [GC-spigot/AdvancedEnchantments#1739]
**Describe the bug**
When using a black scroll to remove an enchantment from an item, the black scroll is used but the enchantment is not removed.

**To Reproduce**
1. Give yourself a pickaxe
2. Enchant the pickaxe with an enchantment, I use telepathy 1 (`/ae enchant telepathy 1` while holding the pickaxe)
3. Give yourself a black scroll (/ae giveitem <name> blackscroll 1 100 0)
4. Apply the black scroll to the item
5. The black scroll is used and disappears, but the enchantment on the pickaxe is not removed

**Screenshots / Video**
N.A

**Server Information (please complete the following information):**
- Server Version: Tuinity 1.16.5
- Plugin Version: 8.0.0-pre20.4

**Comment by PeterDorvay** [comment]
To provide some more information on this, it seems like black scrolls work if there are more than one enchantment on the item. For example, if I have a sword with Epicness 3, Featherweight 3 and Beast Slayer 4 and I apply a black scroll to the item, the first enchantment will be removed and a book will be given to the player (as intended). If I apply another black scroll, the enchantment will again be removed and the player receives the book. However, once there is only ONE custom enchantment left on the item, applying a black scroll will just delete the scroll and give no book to the player.

**Comment by PeterDorvay** [comment]
Here is the error that is printed to console when the black scroll is clicked onto an item with only one AE enchantment on it: https://pastebin.com/hgb2pe3A

**Comment by GC-spigot** [comment]
Fixed
