### ISSUE TITLE
[Issue] Nothing happens when upgrading an enchantment

### ISSUE THREAD

**Issue by eliyash31** [GC-spigot/AdvancedEnchantments#1743]
**Describe the bug**
1. Enchantment won't level up or upgrade after applying any higher level enchantments.

**To Reproduce**
1. Diamond Sword with Nether Slayer I Enchant.
2. Applying Nether Slayer III Enchant on Diamond Sword
3. Result = Nether Slayer I
4. Expected Result = Diamond Sword should now have Nether Slayer III as the upgraded enchant

**Screenshots / Video**
https://pastebin.com/DCxxrjad - Console Log Error

- Server Version: Paper 1.16.5
- Plugin Version: 8.0.0-Pre20.5

**Comment by eliyash31** [comment]
Here is my config 
combining:
  enabled: true
  chances:
    use-chances: true
    break-item: true
    upgrade: true
 also the enchantment book that I applied for upgrade is at 100% success rate

**Comment by PeterDorvay** [comment]
I am also having this issue.

**Comment by eliyash31** [comment]
Bump please , this is really an important issue

**Comment by Insprill** [comment]
Fixed in next update
