### ISSUE TITLE
[Request] Add support for WorldGuard regions with FLY

### ISSUE THREAD

**Issue by Stoniasawsome** [GC-spigot/AdvancedEnchantments#1746]
i cant seem to get the takeoff enchant to disable fully. when entering a world i can get the players flight to false which is good, but then if they take off the boots and put them back on they can fly again. Ive tried the fly deny worldguard flag and a extraworldguardflags flag called command on entry i use /cmi fly %name% false to get this to work upon entry of an area, but like before all they have to do is take off the boots and put them back on. i also tried disabling fly in multiverse but that also had the the same effect as the other attempts.

**Comment by Insprill** [comment]
What flag is this? I can't seem to find a fly flag.

**Comment by Insprill** [comment]
Added in the next update
