### ISSUE TITLE
Some of the custom enchant are bugged[Issue]

### ISSUE THREAD

**Issue by ReBasilisco** [GC-spigot/AdvancedEnchantments#1748]
**Describe the bug**
During the last days we noticed a couple of bugs like Guardian that the Irongolem spawned start attacking the owner of the enchant instead of the enemy.
Another issue is reported to Angelic and other enchant (we didn't understand which one) when someone wearing an armour with custom enchant gets hit with a normal hand punch he recieve from 5 to 9 heart damage. 
We tought it was related to other plugins but since we removed the others and it was still working and only by removing the enchant plugin it stoped we think it's and issues from the plugin.

**To Reproduce**
Removing some of the enchant 

**Screenshots / Video**
https://youtu.be/V-EsjRTm95s
it works also with just the sword:https://youtu.be/dxV7Cnnf4sk

**Server Information (please complete the following information):**
# AdvancedEnchantments
# Made by GC
# Version: 6.5.9
# Release date: 2019.12.17

Server 1.16.4/5

**Comment by Insprill** [comment]
the version of AE you're running is over a year old... update to the latest version
