### ISSUE TITLE
[Issue] Fix NBSP symbol in enchanter

### ISSUE THREAD

**Issue by Kesims** [GC-spigot/AdvancedEnchantments#1751]
**Describe the bug**
XP price for enchant in enchanter has nbsp symbol in it, instead of normal gap.

**To Reproduce**
Use any recent version of AE and open /enchanter.

**Screenshots / Video**
Ingame:
![obrazek](https://user-images.githubusercontent.com/43478239/110198275-aa53c700-7e51-11eb-8d6f-42298b366612.png)

Config:
![obrazek](https://user-images.githubusercontent.com/43478239/110198329-fb63bb00-7e51-11eb-87c2-8b646ffe7a92.png)

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-412 1.16.4]
- Plugin Version: [8.0.0-Pre20.6]

**Comment by GC-spigot** [comment]
Fixed
