### ISSUE TITLE
[Issue] Mining Invalid condition

### ISSUE THREAD

**Issue by Triial** [GC-spigot/AdvancedEnchantments#1752]
When im mining blocks i got and warn ona chat and console:

[**AdvancedEnchantments**] Invalid condition: stonecontainsore=%allow%, enchant was stopped from parsing

Im just start with plugins.
I was trying to find and solve my issue in data and config files and i didn't find anything.

![image](https://user-images.githubusercontent.com/80158258/110207371-5c57b700-7e83-11eb-82b3-fad72cc5d72c.png)
![image](https://user-images.githubusercontent.com/80158258/110207373-611c6b00-7e83-11eb-9fc1-28c249f5e3f2.png)

**Comment by GC-spigot** [comment]
Fixed
