### ISSUE TITLE
[Issue] White Scrolls Not Working

### ISSUE THREAD

**Issue by eliyash31** [GC-spigot/AdvancedEnchantments#1753]
**Describe the bug**
Applying White Scroll or even Slot Orbs on any tools or items is will do nothing.

**To Reproduce**
1. /ae giveitem @p whitescroll 1
2. drag and drop or apply it on diamond_sword
3. nothing happens

Expected output should be that the whitescroll will get vanished and the diamond_sword should have the lore "PROTECTED".

PS, I am on gamemode survival

- Server Version: Paper 1.16.5
- Plugin Version: 8.0.0-Pre20.6

**Comment by GC-spigot** [comment]
Can you upload to pastebin.com your latest.log file? I can't recreate this issue

**Comment by eliyash31** [comment]
Hello that's what I'm worried off since there's no console errors that's happening. Here's a video for the example
https://streamable.com/2jj6wn

**Comment by Insprill** [comment]
Is this still an issue? i wasn't able to recreate it on pre21.7
