### ISSUE TITLE
[Issue] Armor Set Bonuses kept when changing worlds/gamemode even when Inventory changed.

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#1756]
**Describe the bug**
Equipping an armor set and changing world that would change your inventory, still grants that armor set bonus. Even when enchants are disabled in that world.

Edit: Din't test but likely works with normal armor with custom enchants as well.

**To Reproduce**
1-Equip Armor Set
2-Travel to another world, eg: A creative world
3-Bonuses and effects are kept

**Screenshots / Video**
Poisoned an iron golem by hitting it without my poison armor because its equipped in another world.
![Screenshot_831](https://user-images.githubusercontent.com/23641964/110273835-5d90fd00-7fc5-11eb-98b5-bb810844092f.png)

**Server Information (please complete the following information):**
- Server Version: 1.16.5
- Plugin Version: 8.0.0-Pre20.7

**Comment by Insprill** [comment]
Is this still an issue on the latest version?

**Comment by Insprill** [comment]
Fixed in the next update
