### ISSUE TITLE
[Issue] Black Scrolls & Removing Enchants Via Commands Gets Rid Of Item Lore (Including Trackers Like StatTrak)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1758]
**Describe the bug**
If an item has custom lore or a tracker (like StatTrak) below the Enchants, using a Black Scroll or enchantment removal commands removes the custom lore/tracker.

**To Reproduce**
Note: EssentialsX's /lore command makes testing this very easy, so I will use it in my steps to reproduce. I am sure other methods of adding lore will work just as well.

Method 1:
1.) Hold Diamond Sword
2.) /ae enchant decapitation 3
3.) /lore add &lCustom Lore AND/OR use StatTrak
4.) Use a Black Scroll on the Diamond Sword
5.) Look and see that the custom lore has been removed, along with the Decapitation enchantment

Method 2:
1.) Hold Diamond Sword
2.) /ae enchant decapitation 3
3.) /lore add &lCustom Lore AND/OR use StatTrak
4.) /ae enchant decapitation 3
5.) Look and see that the custom lore has been removed, along with the Decapitation enchantment

**Screenshots / Video**
Before Black Scroll Use:
![image](https://user-images.githubusercontent.com/29821149/110374109-e46dc600-8015-11eb-9969-be633f96a98f.png)
After Black Scroll Use:
![image](https://user-images.githubusercontent.com/29821149/110374247-11ba7400-8016-11eb-9811-2fe8dd65e27d.png)

**Server Information (please complete the following information):**
- Server Version: Tuinity-195 Minecraft 1.16.5
- Plugin Version: 8.0.0-Pre20.7

**Comment by sh1mrr4** [comment]
I experience the same issue. Additionally, any extra lore seems to be removed if applying an enchantment removes another one. Example: 
![grafik](https://user-images.githubusercontent.com/47902483/110529694-db661d00-8119-11eb-87be-21458d8838d4.png)

Server Version: Paper 1.15.2-378
Plugin Version : 8.0.0-Pre20.7

**Comment by Insprill** [comment]
Fixed
