### ISSUE TITLE
Anvil or Transfer

### ISSUE THREAD

**Issue by TheKlimoT** [GC-spigot/AdvancedEnchantments#1759]
I suggest adding the ability to use the anvil as an overlay spell, and disable the transfer, but the percentage and destruction of things will remain available, I saw a similar plugin EcoEnchants called there was access to the anvil, I think this is possible to implement, because the mechanics of the anvil do not want to lose.
![изображение](https://user-images.githubusercontent.com/26817853/110377410-6b965a80-8065-11eb-956a-d509ac90ba10.png)

**Comment by Insprill** [comment]
Can you explain this a little better? I have no idea what you're trying to ask

**Comment by Insprill** [comment]
Assuming you mean the ability to use custom enchantment books in anvils like vanilla books, added a few updates ago.
