### ISSUE TITLE
[Issue] Black scrolls + slot increasers not working on fishing rods

### ISSUE THREAD

**Issue by PeterDorvay** [GC-spigot/AdvancedEnchantments#1760]
**Describe the bug**
Black scrolls and slot increasers can not be applied to fishing rods. This is an issue because of the new Bait and Hook enchantments.

**To Reproduce**
Give yourself a black scroll and a fishing rod. Enchant the fishing rod with Hook 1. Try to remove the enchantment with the black scroll and the two items will just swap places.

**Screenshots / Video**
Not necessary

**Server Information (please complete the following information):**
- Server Version: Tuinity 1.16.5
- Plugin Version: 8.0.0-pre20.7

**Comment by GC-spigot** [comment]
Reworked this, but in future if you have similar issues: 
You need to add items to `items.settings.can-apply-to` list in config.yml so they could have these items applied as it automatically doesn't allow it so random items, e.g. blocks wouldn't be applicable
