### ISSUE TITLE
[Issue] Mining with a tool that has Telepathy doesn't pay in Jobs Reborn

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1762]
**Describe the bug**
Mining with a tool (the kind of tool doesn't matter, applies to axe, pickaxe, etc.) that has Telepathy doesn't pay in Jobs Reborn.

**To Reproduce**
1.) Install Jobs Reborn, Vault, and EssentialsX
2.) Hold an axe
3.) /ae enchant telepathy 4
4.) /jobs join woodcutter
5.) Find a tree and chop some logs with the aforementioned axe
6.) Wait a few moments and see that your balance hasn't increased with /bal
7.) You can chop some logs with an unenchanted axe to see that you do get paid and that the issue lies with Telepathy

**Server Information (please complete the following information):**
- Server Version: Tuinity-195 MC 1.16.5
- Plugin Version: 8.0.0-Pre20.7

**Comment by Insprill** [comment]
Added support for Jobs in the next update

**Comment by WhatsTheBadNews** [comment]
I was using the latest versions when I made this issue. I made a new issue using the (as-of-now) latest versions and added a video demonstration. I hope this helps you reproduce it.
