### ISSUE TITLE
AE doesn't recognize Blockregen blocks

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [GC-spigot/AdvancedEnchantments#1763]
I'm looking to get supported added for this plugin. Your plugin doesn't seem to register them as real blocks

https://gyazo.com/e2087517f3519cc36d3b7cc890b47d92 when it isn't managed by block regen

https://gyazo.com/74bae46508dad98bf0da053ce2c09c1b when it is managed 

https://www.spigotmc.org/resources/blockregen.9885/

**Comment by YouSeeMeRunning2** [comment]
Any updates?

**Comment by Insprill** [comment]
Is this still an issue?
