### ISSUE TITLE
[Issue] Soul dupe with name tag

### ISSUE THREAD

**Issue by ReBasilisco** [GC-spigot/AdvancedEnchantments#1764]
Hi, i noticed that if i put a name tag on a mob and i kill it, i can easily collect souls on the souls collector.

are there any ways to change this thing or maybe it's a bug ?

I run the last version of the plugin and the last version of Minecraft

**Comment by Insprill** [comment]
`Latest version` doesn't tell us anything as by the time we get around to issues multiple more versions of both have been released s o we don't know what version the issue is actually last known on. Is this still an issue on 8.0.0-pre21.5/6?
