### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Pudiaz** [GC-spigot/AdvancedEnchantments#1766]
**Describe the bug**
The original lore of my item + enchants disappear 

**To Reproduce**
applying black scroll to item

**Screenshots / Video**
https://youtu.be/z2XeIqfpb3A

**Server Information (please complete the following information):**
- This server is running Paper verison git-Paper-"60e92c061" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) 
- Plugin Version: AdvancedEnchantments-8.0.0-Pre20.7.jar

**To add**
Can you please explain to me this part of the config as i don't know if i set this up right, im trying to make it so there is a default max of 7 custom enchants on all items, with the ability of the orb to be able to apply 1 extra enchant making a maximum of 8 total custom enchants on an item. 

Here is a picture of the config section slot: https://gyazo.com/505de98de066940a2d9203bcd81a90ec

Here is a picture of the orb i am using if you can tell me if i have it set up correctly: https://gyazo.com/d9ec86fb6c64801ab22d6603b28f24f9

**Comment by Insprill** [comment]
Fixed in pre20.8
