### ISSUE TITLE
Small issue with HEALTH_BOOST effect and teleporting to other worlds

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#1767]
**Describe the bug**
When you have an active HEALTH_BOOST (e.g. from the Overload enchantment) and teleport to other worlds like the Nether, your current health is reduced to the default amount. Like if you had 16/16 hearts before teleporting, you will have 10/16 after.

**To Reproduce**
- Enchant an item with a HEALTH_BOOST effect (e.g. Overload) and equip it
- Wait until you have full health
- Teleport to a different world by any means (nether portal, commands, etc.)

**Server Information (please complete the following information):**
- Server Version: Paper 1.15.2-378
- Plugin Version: 8.0.0-Pre20.7

**Comment by Insprill** [comment]
Fixed in next update
