### ISSUE TITLE
Console spamming Trench Related

### ISSUE THREAD

**Issue by EchocallingEarth** [GC-spigot/AdvancedEnchantments#1768]
**Describe the bug**
Player logs in and the spamming of warnings floods the console

**To Reproduce**
Unsure as we have no definitive process for testing to see where a plugin is failing.
Reference from console log -  effect[TRENCH:3]; enchant [detonate]

Console Log
[https://pastebin.com/8MRYR7w4](url)

**Server Information (please complete the following information):**
- paper 16.5
- 8.0.0-Pre20.7 Changelog

**Comment by EchocallingEarth** [comment]
Tools related fail when used as a result of this.

**Comment by Insprill** [comment]
Update AE and get back as to if this is still an issue

**Comment by Insprill** [comment]
Fixed in next update
