### ISSUE TITLE
[Issue] Mining with a tool that has Telepathy doesn't pay in Jobs Reborn

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1772]
**Describe the bug**
This is basically a repeat of #1762 but I'll add a video to demonstrate. If you can't reproduce, please let me know before closing the issue. I'll try to add more details if needed. But I am certain this issue exists. It has plagued my server for months.

Mining with a tool (the kind of tool doesn't matter, applies to axe, pickaxe, etc.) that has Telepathy doesn't pay in Jobs Reborn.

**To Reproduce**
NOTE: This can be done with pickaxe for Miner job, shovel for Digger job, axe for Woodcutter job. The type of tool doesn't matter, the problem point seems to be Telepathy.

1.) Install Jobs Reborn, Vault, and EssentialsX
2.) Hold an axe
3.) /ae enchant telepathy 4
4.) /jobs join woodcutter
5.) Find a tree and chop some logs with the aforementioned axe
6.) Wait a few moments and see that your balance hasn't increased with /bal
7.) You can chop some logs with an unenchanted axe to see that you do get paid and that the issue lies with Telepathy

**Screenshots / Video**
PLEASE watch this video. I think it very clearly displays the issue.

https://www.youtube.com/watch?v=uj0dlkvGwmc

**Server Information (please complete the following information):**
- Server Version: Paper-545 MC 1.16.5
- Plugin Version: 8.0.0-Pre20.9
- Jobs Version: 4.17.0

**Comment by nivcoo** [comment]
Same issue since 1 year

**Comment by Insprill** [comment]
Please comment on the first issue relating to this (#1361) don't create new issues. We are aware of the issue and have bumped it to critical priority so we'll get to it in a couple days
