### ISSUE TITLE
[Issue] TP_DROP and other bug with lava walker

### ISSUE THREAD

**Issue by nivcoo** [GC-spigot/AdvancedEnchantments#1776]
Hello i use AdvancedEnchantment in 1.12.2 and with TP_DROP and colored glass, the droped glass stay white, after that if i use lava walker and i remove the piece of armor with lava walker the enchant stay. thx

**Comment by Insprill** [comment]
The first one fixed for 21.6. The second one I was not able to reproduce. Can you elaborate on how to reproduce it?

**Comment by Insprill** [comment]
Fixed for pre21.8
