### ISSUE TITLE
[Issue] ADD_HEAL Death Animation

### ISSUE THREAD

**Issue by nivcoo** [GC-spigot/AdvancedEnchantments#1778]
Hello i use AdvancedEnchantment in 1.12 and when my player teleport or remove armor with godlyoverload the animation of death start like that : https://pics.revolis.fr/2021-03/13/21-08_ioC2.png (Maybe the massive remove of heal)

**Comment by Insprill** [comment]
Server version? AE version? Can you send the exact enchant that's causing it? ([paste](https://paste.insprill.net/) it from your enchantments.yml)

**Comment by Insprill** [comment]
Along with the information I requested above, can you send a video or something of it happening? I was not able to reproduce this issue.
