### ISSUE TITLE
Fortune and autosmelt doesn't work together [Issue]

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#1781]
**Describe the bug**
Fortune and autosmelt doesn't work together, if you mine coal it will trigger fortune but iron will only trigger autosmelt but not fortune.

**To Reproduce**
Use version 8.0.0-Pre21.1 then enchant your pickaxe with autosmelt and fortune then mine iron.

**Screenshots / Video**
No need, it's self-explanatory.

**Server Information (please complete the following information):**
- Server Version: Purpur version git-Purpur-1012
- Plugin Version: Version 8.0.0-Pre21.1

**Comment by Agaloth** [comment]
It doesn't work on gold ores either.

**Comment by Insprill** [comment]
Not an issue. As of 8.0.0-pre20.8, Iron & Gold getting Fortune applied with CE's is now togglable. It's under the settings section in the config.yml.
