### ISSUE TITLE
Teleportation unactivates current custom enchantements [Issue]

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#1782]
**Describe the bug**
Every time someone uses any types of teleportation, it unactivates their current custom enchantements, this is usually /tp, /back, /tpa, switching worlds. (using essentials, multiverse, worldguard)

**To Reproduce**
Just enchant your armors with any enchantement that adds an effect to a player and use any types of teleportation, going into worldguard regions etc...

**Screenshots / Video**
It's pretty self-explanatory and doesn't really need a screenshot, video.

**Server Information (please complete the following information):**
- Server Version: Purpur version git-Purpur-1012 (MC: 1.16.5)
- Plugin Version: AdvancedEnchantments version 8.0.0-Pre21.1
- Essentials: Essentials version 2.19.0-dev+95-0ce4029
- Multiverse: Multiverse-Core version 4.2.2-b812
- Worldguard: WorldGuard version 7.0.4+f7ff984

**Comment by Agaloth** [comment]
It's a confirmed bug, I've been testing it myself and everyone has been getting the issue.

**Comment by Insprill** [comment]
I tested it with a chestplate that has overload 3 and when teleporting via essentials /tp, or /back, or minecrafts /tp the effect was never removed. can you see if this happens on Paper?

**Comment by Agaloth** [comment]
Have you tried using gears (speed 3) with springs (jump boost) and mixing multiple effects together?
I can't really test paper as my server dies with 120 players on paper.

**Comment by GC-spigot** [comment]
This is most likely multiverse issue, looking into it now.

**Comment by Agaloth** [comment]
It seems to happen when teleporting to spawn which has worldguard flags, didn't get the bug while teleporting.

**Comment by Agaloth** [comment]
Recording a video, uploading it right now to show what's happening + which worldguard flag I'm using right now.

**Comment by Agaloth** [comment]
https://www.youtube.com/watch?v=7UW9ep67iRY

**Comment by Agaloth** [comment]
Using WorldGuard version 7.0.4+f7ff984 + WorldGuardExtraFlags version 4.1.5-SNAPSHOT

**Comment by Insprill** [comment]
Please try to edit your comments instead of spamming

**Comment by Agaloth** [comment]
It seems to still happen, I'll keep you updated.

**Comment by Insprill** [comment]
@Agaloth Is this still an issue on the latest version? (8.6.8 as of right now)

**Comment by Agaloth** [comment]
I couldn't test it since I got busy IRL but I'll try to do it today!
