### ISSUE TITLE
[Issue] Adding lore with /aegive removes Custom Enchants from the item description 

### ISSUE THREAD

**Issue by baailey** [GC-spigot/AdvancedEnchantments#1783]
**Describe the bug**
When using /aegive to give an item with a custom enchant, the lore will override the custom enchants name and it will not display when you hover your mouse over the item. However, the enchant will still work.

**To Reproduce**
1. /aegive baailey diamond_helmet 1 name:&cItem_Name protection:5 glowing:1 lore:&cLore-line_#1|&cSecond_Line
2. Hover mouse over the diamond helmet

**Screenshots / Video**
https://gfycat.com/WellinformedDearCats

**Server Information (please complete the following information):**
- Server Version: git-Tuinity-"4743c34" (MC: 1.16.4)
- Plugin Version: 8.0.0-Pre21.1

**Comment by Insprill** [comment]
Fixed for 21.4
