### ISSUE TITLE
ERROR | AdvancedEnchantment Error Spamming on Console

### ISSUE THREAD

**Issue by WizkhalifaX** [GC-spigot/AdvancedEnchantments#1784]
So basically I do have BattlePass plugin, and we tried to put some GKITS and OTHER ENCHANTMENTS rewards on it but suddenly after I did set my account to access all the tiers, and trying to claim those rewards its spamming and console and in game its says that...
![image](https://user-images.githubusercontent.com/61721730/111210140-d9172d80-8607-11eb-8c49-5555212a0260.png)

And this what on console log But I only got few cause its lagging my pc because of the spam
> https://ghostbin.co/paste/p78u
> https://ghostbin.co/paste/rse9e42

**Comment by Insprill** [comment]
Not an issue with Advanced Enchantments. Like it says in chat, it can't find some of the enchants. You can create an issue on [Battle Pass's GitHub](https://github.com/GC-spigot/battle-pass/issues/new/choose) as it shouldn't be throwing an error if it can't find an enchant.
