### ISSUE TITLE
[Issue] VEIN_MINE Chat spam 

### ISSUE THREAD

**Issue by KCJ11** [GC-spigot/AdvancedEnchantments#1785]
Version: 8.0.0 Pre 21.2

Vein_Mine console error

Recently submitted an issue with veinminer and telepathy not working together. Updated to latest version and still not working together, also getting this error.

16.03 00:56:10 [Server] INFO Extra info: effect[VEIN_MINE:]; enchant [veinminer]; mc[116]; ae[8.0.0-Pre21.2]
16.03 00:56:10 [Server] INFO If you cannot indentify cause of this, contact developer providing this report. 
16.03 00:56:19 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 0
16.03 00:56:19 [Server] WARN at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1829)
16.03 00:56:19 [Server] WARN at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:121)
16.03 00:56:19 [Server] WARN at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:261)
16.03 00:56:19 [Server] WARN at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:126)
16.03 00:56:19 [Server] WARN at n3kas.ae.enchanthandler.enchanttypes.MINING.lambda$onBlockBreak$0(MINING.java:85)
16.03 00:56:19 [Server] WARN at java.util.ArrayList.forEach(ArrayList.java:1257)
16.03 00:56:19 [Server] WARN at n3kas.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:79)
16.03 00:56:19 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor531.execute(Unknown Source)
16.03 00:56:19 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
16.03 00:56:19 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
16.03 00:56:19 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
16.03 00:56:19 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:325)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:284)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:174)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1489)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1140)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1133)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1094)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1008)
16.03 00:56:19 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
16.03 00:56:19 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by Insprill** [comment]
Fixed in the next update
