### ISSUE TITLE
Multiplication can duplicate iron/gold ore.[Issue]

### ISSUE THREAD

**Issue by VerdantWind** [GC-spigot/AdvancedEnchantments#1786]
**Describe the bug**
When mining an iron ore gold ore block you can then mine the multiplied ores, infinitely duplicating them.

**To Reproduce**
Get a pickaxe with Multiplication of any level. Mine an iron ore and place it back down until you get a second one. Place the second one and mine it.

**Screenshots / Video**

**Server Information (please complete the following information):**
- Server Version: Spigot 1.16.5-R0.1-SNAPSHOT
- Plugin Version: 8.0.0-Pre20.9

**Comment by Insprill** [comment]
Fixed for 21.4
