### ISSUE TITLE
Feature for Custom Model Data Items [Request]

### ISSUE THREAD

**Issue by 4Bushona** [GC-spigot/AdvancedEnchantments#1788]
Hello there! Before to explain why this feature will be very usefull (on my opinion) I have to say sorry for my bad English and i hope you understand me what im proposing.

Soo here is the idea - Many servers have texture pack and many custom visions for tools/items and etc. and will be cool if the plugin supports custom model data items, so items like Orbs, White Scrolls, Black Scrolls, scrolls for books (which open with right click and gives the different books) and all other item aspects of the plugin. This will add a lot more freedom of the servers to create unique settings ( visual ) of that plugin.

The config feature can be like " material: BONE                          or                     material: BONE#3
                                                   CustomModelData: 1 "                                      (where the number is the CMD)
                                                   
A lot free plugins/paid has that option and i think this one can be a nice feature for one plugin.

**Comment by SirCraftypants** [comment]
I already requested this long ago and it was supposed to be added, well it was as you can see in the Config under material it says id:

problem is it does not work.

**Comment by Insprill** [comment]
Added for 8.0.0-pre21.7. Under each item, there will be a field called `custom-model-data`. It will autogenerate, however, you need to do whatever for the item to be created, then it will generate the value.
