### ISSUE TITLE
[Issue] "AdvancedEnchantments caught an error with an action involving inventories"

### ISSUE THREAD

**Issue by nolez15** [GC-spigot/AdvancedEnchantments#1789]
**Describe the bug**
When inside the /enchanter menu, trying to right-click any of the enchantment tier buttons, nothing happens and the below error appears in the console.

Error:

17.03 06:34:09 [Server] INFO AdvancedEnchantments caught an error with an action involving inventories
17.03 06:34:09 [Server] WARN java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
17.03 06:34:09 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
17.03 06:34:09 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
17.03 06:34:09 [Server] WARN at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
17.03 06:34:09 [Server] WARN at java.base/java.util.Objects.checkIndex(Objects.java:372)
17.03 06:34:09 [Server] WARN at java.base/java.util.ArrayList.get(ArrayList.java:459)
17.03 06:34:09 [Server] WARN at n3kas.ae.features.usercommands.Enchantments.open(Enchantments.java:161)
17.03 06:34:09 [Server] WARN at n3kas.ae.features.enchanter.InventoryEvent.onClick(InventoryEvent.java:83)
17.03 06:34:09 [Server] WARN at n3kas.ae.globallisteners.InventoryClicks.onInvClix(InventoryClicks.java:30)
17.03 06:34:09 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor518.execute(Unknown Source)
17.03 06:34:09 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
17.03 06:34:09 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
17.03 06:34:09 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
17.03 06:34:09 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2542)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1140)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1133)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1094)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1008)
17.03 06:34:09 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
17.03 06:34:09 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:834)

Server Information
- Server Version: PaperSpigot 1.16.5
- Plugin Version: 8.0.0-Pre21.2

**Comment by Insprill** [comment]
Fixed for 21.4
