### ISSUE TITLE
[Issue] Bug with Trench effect (cannot drop air)

### ISSUE THREAD

**Issue by larssieboy18** [GC-spigot/AdvancedEnchantments#1791]
**Describe the bug**
Using the trench effect (default detonate enchantment), people are able to spam the console and chat of moderators.

**To Reproduce**
Have people mine with the detonate effect.

**Screenshots / Video**
https://bin.bloom.host/yiqocofaru.md

**Server Information (please complete the following information):**
- Server Version: git-Paper-468 (MC: 1.16.5)
- Plugin Version: ae[8.0.0-Pre21.2]

**Comment by larssieboy18** [comment]
Probably the same as issue #1779, but I can confirm it is still present on 21.2 (and also 21.1)

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by Insprill** [comment]
Will be fixed in 21.4, still present in 21.3.
