### ISSUE TITLE
Telepathy and multiplicator not working together [Issue]

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1792]
**Describe the bug**
If you have the telepathy enchant and the multiplicator enchant it won't work and you won't receive the ores for example with iron 

**To Reproduce**
Simply put together to Telepathy enchant and Multiplicator enchant on a pickaxe and mine an iron ore

**Screenshots / Video**
https://gyazo.com/38aac144e01c956d76f30043018adec8

**Server Information (please complete the following information):**
- Server Version: PaperSpigot-123 1.8.8
- Plugin Version: [ 8.0.0-Pre21.2]

**Comment by Insprill** [comment]
Fixed for 21.4
