### ISSUE TITLE
[Issue]Failed to parse effect 'TRENCH'?

### ISSUE THREAD

**Issue by Zaldor12** [GC-spigot/AdvancedEnchantments#1793]
**Describe the bug**

Im spammed with alerts for unknown reasons, asking to help me maybe catch it in the future.

**To Reproduce**
Unsure why this is happening, no one is using detonate whilst these alerts are going off. 

**Screenshots / Video**
![2021-03-17_21 51 14](https://user-images.githubusercontent.com/80866331/111561506-f1538d80-876a-11eb-9200-72252f68931f.png)

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.8.8]
- Plugin Version: [e.g. 6.7.8]

**Comment by Insprill** [comment]
Fixed for 21.4

**Comment by Zaldor12** [comment]
What the fuck does that mean?

**Comment by Insprill** [comment]
Don't get aggressive. I meant the issue will be fixed in 8.0.0-pre21.4.
