### ISSUE TITLE
[Request] Add support for PlaceholderAPI in the /aegive command

### ISSUE THREAD

**Issue by Stoniasawsome** [GC-spigot/AdvancedEnchantments#1795]
could we have support for kits in CMI? a popular spigot plugin like essentials, only better. i cant seem to get any placeholders to work with the aegive command ive tried alot of placeholders but im assuming its not supported. If it is maybe you could help me with the procedure. ive tried this command

/aegive steve_french_ diamond_helmet 1 name:&d&lName protection:5 glowing:1 lore:&a{player}and {playername}{USERNAME}[playerName] ect. id like a custom lore where the players name and date they got the items appears. i used to be able to do it with essentials, but cant with CMI

**Comment by Tom25W** [comment]
I think thats something you should ask CMI to add rather than AE? Once CMI added support, you could add the item with the placeholders inside the kit editor (Tool already enchanted with whatever you want to give to players). Perhaps ask in the CMI discord before opening a ticket.

**Comment by Insprill** [comment]
We can add support for PlaceholderAPI, but not direct support for built-in CMI placeholders.

**Comment by Insprill** [comment]
Support for PlaceholderAPI with the /aegive command will be in pre21.7.
