### ISSUE TITLE
HolyWhiteScroll Death Dupe [Issue]

### ISSUE THREAD

**Issue by ShockCharge** [GC-spigot/AdvancedEnchantments#1797]
Appearently when items have HolyWhiteScroll on my server we call it Ancient Protection when you die
your items doubles aka Dupe. I have received alot of reports of my player by it by now. and unfornately i have to remove AE on my server temporary till this is fixed.
![image](https://user-images.githubusercontent.com/48907444/111713192-0bd05880-888a-11eb-9629-ccec8dc4e7e8.png)
![image](https://user-images.githubusercontent.com/48907444/111713203-0f63df80-888a-11eb-96ec-0ef6ce50e87a.png)
![image](https://user-images.githubusercontent.com/48907444/111713210-12f76680-888a-11eb-933f-7c06a63156ba.png)
![image](https://user-images.githubusercontent.com/48907444/111713214-17238400-888a-11eb-9764-ed9e356bd375.png)

![image](https://user-images.githubusercontent.com/48907444/111713275-43d79b80-888a-11eb-9c31-ccdd9722b0d4.png)
![image](https://user-images.githubusercontent.com/48907444/111713290-4cc86d00-888a-11eb-9b16-f711dab48dca.png)

**Comment by ShockCharge** [comment]
Also tried it on my alt account it worked
![image](https://user-images.githubusercontent.com/48907444/111714467-aa5db900-888c-11eb-8c82-fb9862627f06.png)
![image](https://user-images.githubusercontent.com/48907444/111714480-b0ec3080-888c-11eb-8cf7-181e03ce0674.png)

**Comment by Insprill** [comment]
You didn't give any instructions on how to reproduce so I tried giving myself a helmet with holywhitescroll and falling to my death and it didn't duplicate. I have implemented a possible fix in the next update. get back as to if it fixes it or not

**Comment by RulerOfEternity** [comment]
He did literally say that it happened if you do /suicide

**Comment by RulerOfEternity** [comment]
> You didn't give any instructions on how to reproduce so I tried giving myself a helmet with holywhitescroll and falling to my death and it didn't duplicate. I have implemented a possible fix in the next update. get back as to if it fixes it or not

He did literally say that it happened if you do /suicide

**Comment by Insprill** [comment]
@ShockCharge is this still an issue on the latest version? (8.6.8 as of now). We've made some internal changes to how items are given back between this issue and now so it might've been fixed.
