### ISSUE TITLE
[Issue] Slot Limit Reached

### ISSUE THREAD

**Issue by Pudiaz** [GC-spigot/AdvancedEnchantments#1799]
**Describe the bug**
When your weapon slot is maxed and you continue to add a enchant onto it, if its successful it will say your weapon slots are maxed, if its unsuccessful it will destroy your weapon instead of saying your weapon slot is maxed as well.

**To Reproduce**
Max weapon slot in config (mine is 7) and try to apply a book to the weapon, if its successful in chat it will say weapon slot reached, and when its not successful, it will destroy your item.

**Screenshots / Video**
https://youtu.be/nY0rkUDhRNo

**Server Information (please complete the following information):**
- Server Version: Paper Version git-Paper-532 (MC:1.16.5)
- Plugin Version: Version: 8.0.0-Pre21.0

**Comment by Insprill** [comment]
Fixed for 21.6
