### ISSUE TITLE
[Issue] Anvils not working with items that only have CEs

### ISSUE THREAD

**Issue by Spleggeti** [GC-spigot/AdvancedEnchantments#1800]
**Describe the bug**
I've recently found an issue with Advanced Enchantments, My players cannot seem to merge any items within an anvil that have a Custom Enchantment on them. If both items have a custom enchant, it does not come up with a cost of XP at all and will not let the user combine the tools together. If someone could point me into a direction of getting this fixed somehow please let me know

**To Reproduce**
Put items in an anvil and if they have custom enchants try to merge items together.

**Screenshots / Video**
https://gyazo.com/36dc91e1f5d1214003c80586b7a83d88
**Server Information (please complete the following information):**
- Server Version: [PaperSpigot-379 1.16.3]
- Plugin Version: [Version 8.0.0-Pre13.7]

**Comment by SugarBottles** [comment]
needs to be enabled in the config
https://lithi.io/file/DRlU.png

**Comment by Spleggeti** [comment]
It is currently set to true but still shows no cost to the combine and won't complete the combining.

**Comment by Spleggeti** [comment]
Hi There! I would appreciate a confirmation on how to fix this bug! It is indeed enabled in the config and It's really a bug that needs fixing ASAP for my server as the Prison server depends on it :)

**Comment by Insprill** [comment]
Fixed in the next update
