### ISSUE TITLE
[Issue] Thorn Dragon Drops

### ISSUE THREAD

**Issue by Tauses** [GC-spigot/AdvancedEnchantments#1801]
**Describe the bug**
When the enderdragon dies due to Thorns then it doesn't drop the assigned loot.

**To Reproduce**
kill the dragon using Thorns

**Server Information (please complete the following information):**
- Server Version: git-Tuinity-"f8c0db4" (MC: 1.16.5)
- Plugin Version: 8.0.0-Pre21.2.jar

**Comment by Insprill** [comment]
Fixed in the next update
