### ISSUE TITLE
[Question] [Request] Armor Durability Damage Negation All Sources

### ISSUE THREAD

**Issue by SugarBottles** [GC-spigot/AdvancedEnchantments#1802]
Is it possible to prevent all sources of armor damage(durability reduction)? I still want things to damage the player but the armor piece should take no damage.

If this isn't possible in the current version is there a way to make it possible in a later version?

**Comment by Hallowhead1** [comment]
Just to authenticate the issue, he is working on setting the plugin up on my server, I have purchased the plugin. My name is hallowhead1

I am verified on the discord.  If you need more proof let me know
https://i.imgur.com/gXikphQ.png

**Comment by Insprill** [comment]
The issue tracker is not for questions.
