### ISSUE TITLE
[Question] [Request]

### ISSUE THREAD

**Issue by SugarBottles** [GC-spigot/AdvancedEnchantments#1803]
Currently trying to use the Console_Command to make a custom mob drop enchant. I want there to be a chance that a spawn egg drops(given to the player) from specific mobs. The idea is that per mob type i allow the enchant to activate, there is a percent chance that the console command runs. I'm having issues getting the player_name and mob type to query. For testing purposes all percentages and conditions have been left off.

**To Reproduce**
eggcelent:
  display: '%group-color%Eggcelent'
  description: 'Chance to give players spawn egg of killed mob'
  applies-to: 'Weapons'
  group: 'UNIQUE'
  type: 'KILL_MOB'
  applies:
    - 'ALL_SWORD'
    - 'ALL_AXE'
  settings:
    removeable: false
  levels:
    '1':
      effects:
        - 'CONSOLE_COMMAND:aegive %attacker name% %mob type%_SPAWN_EGG'

https://lithi.io/file/2cmsY.png
in the screen shot the "spawn_egg" section of the command is lowercase, it still returns the same error with the caps "SPAWN_EGG"

we know %attacker name% works because when replacing the mob egg section with DIAMOND, we get a diamond in return, the issue is getting the mob egg to work.

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.8.8]
- Plugin Version: [e.g. 6.7.8]

**Comment by Hallowhead1** [comment]
Just to authenticate the issue, he is working on setting the plugin up on my server, I have purchased the plugin. My name is hallowhead1

I am verified on the discord.  If you need more proof let me know
https://i.imgur.com/gXikphQ.png

**Comment by Insprill** [comment]
The issue tracker is not for questions.
