### ISSUE TITLE
[Issue] ADD_SOULS bug

### ISSUE THREAD

**Issue by laazyCmd** [GC-spigot/AdvancedEnchantments#1804]
**Describe the bug**
Apparently, the effect 'ADD_SOULS' isn't working properly. You'll get 1 soul but when the 'ADD_SOULS' effect activates again, you'll instead get 'Souls Collected: 0', or when you already have souls collected in the item, you'll have 'Souls Collected: -1' instead.

**To Reproduce**
1. Add an enchantment with a 'ADD_SOULS' effect (Soulminer, Soulgrind, etc.)
2. Apply a Soul Tracker
3. Use the item with a 'ADD_SOULS' effect activate and you'll get +1 soul collected
4. Do it again and you'll return at 0 souls collected
5. Or, when you already have souls collected, you'll be stuck at 'Souls Collected: -1'

**Screenshots / Video**
https://user-images.githubusercontent.com/62589492/111976781-f898e380-8b3c-11eb-987d-a231126b1d57.mp4

![image](https://user-images.githubusercontent.com/62589492/111977491-c045d500-8b3d-11eb-9388-36014cba0dd2.png)

![image](https://user-images.githubusercontent.com/62589492/111977550-d2c00e80-8b3d-11eb-9db9-0a69696ba6e3.png)

**Server Information (please complete the following information):**
- Server Version: Tuinity Version git-Tuinity-"7734ef0" 1.16.5
- Plugin Version: 8.0.0-Pre21.3

**Comment by Starkenz** [comment]
Exactly. Soul type enchantments not working.

**Comment by Insprill** [comment]
Fixed in the next update
