### ISSUE TITLE
[Issue] Tools with Telepathy cannot break stairs

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1805]
**Describe the bug**
Tools with the Telepathy enchantment cannot break any kind of stairs

**To Reproduce**
1.) Place some cobblestone stairs
2.) Acquire and hold a pickaxe
3.) /ae enchant Telepathy 4
4.) Try (and fail) to mine the stairs

**Server Information (please complete the following information):**
- Server Version: Tuinity-206 MC 1.16.5
- Plugin Version: 8.0.0-Pre21.4

**Comment by Insprill** [comment]
Will be fixed in 21.6.
