### ISSUE TITLE
[Issue] Take_Away doesn't take last item

### ISSUE THREAD

**Issue by Hallowhead1** [GC-spigot/AdvancedEnchantments#1806]
**Describe the bug**
When using the code below it doesn't take last coal from inventory.
https://i.imgur.com/lMi4X2d.png

**To Reproduce**
Apply exact enchant as shown in link below
https://i.imgur.com/lMi4X2d.png

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: Paper 1.16.5 460
- Plugin Version: 8.0.0-Pre21.5

**Comment by Insprill** [comment]
I tested it by just adding `TAKE_AWAY:COAL:1` and it worked fine. The code for TAKE_AWAY has also been changed slightly for the next update so that might fix it. if you send (in text) the enchant you're using I can test to make sure

**Comment by SugarBottles** [comment]
flux:
  display: '%group-color%Flux'
  description: 'test'
  applies-to: 'TOOLS'
  group: 'UNIQUE'
  type: 'MINING'
  applies:
    - 'ALL_PICKAXE'
  levels:
    '1':
      condition:
        - "%block type% = IRON_ORE or %block type% = GOLD_ORE : %continue%"
        - "%player_item_in_offhand% = COAL : %allow%"
      effects:
        - 'TAKE_AWAY:COAL:1'
        - 'SMELT'

here is updated code, make sure coal is in offhand

**Comment by Hallowhead1** [comment]
With that code, it takes away coal fine except for the last piece, when it gets to the last piece it just remains there and you can continue to mine and auto smelt.

**Comment by Insprill** [comment]
Fixed for 21.6
