### ISSUE TITLE
[Issue] %is hostile% doesn't work for passive mobs

### ISSUE THREAD

**Issue by Hallowhead1** [GC-spigot/AdvancedEnchantments#1807]
**Describe the bug**
When we use the code below with %is hostile% true it doesn't work on hostile mobs, doesn't work on any mobs.
https://i.imgur.com/qX77gcC.png

**To Reproduce**
https://i.imgur.com/qX77gcC.png

**Screenshots / Video**
https://i.imgur.com/qX77gcC.png

**Server Information (please complete the following information):**
- Server Version: Paper 460
- Plugin Version: 8.0.0-Pre21.5

**Comment by Insprill** [comment]
Fixed for 21.6
