### ISSUE TITLE
[Issue] Permanent potion effect

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#1808]
**Describe the bug**
Players can get infinite effects with no armors. For example these enchantments: EFFECT_STATIC. 

Drunk
Gears
Anti gravity
Overload
Obsidianshield
Glowing
Aquatic

**To Reproduce**
The bug related to hotkey operation. But you need some effect static type enchantment. For example above. But you need one Gears and another simple armor. More info belove...

**Screenshots / Video**
https://user-images.githubusercontent.com/21794143/112295447-e0f16480-8cce-11eb-88e8-7b4399118f45.mp4

**Server Information (please complete the following information):**
- Server Version: [PaperSpigot-123 1.8.8]
- Plugin Version: [8.0.0-Pre21.5]

**Comment by Insprill** [comment]
What hotkey causes it?

**Comment by Starkenz** [comment]
In order to get permanent effect you need spare armor just like video. If you do not have spare armor (Normal armor piece), you can t get permanent effect. And then player continues to spam click on his (Mouse, L, Mouse R) Armor equip, unequip... Eventually it gives you permanent effect. Here's more video below:

https://user-images.githubusercontent.com/21794143/112931324-83d23480-914e-11eb-8bfe-1ba0670e077d.mp4

**Comment by Insprill** [comment]
it might have gotten fixed in pre 22.2, could you try that out?

**Comment by Starkenz** [comment]
Tried that... no difference.

**Comment by Starkenz** [comment]
@Insprill Just to let you know. It doesn't fixed. I am using latest version of AE of 22.8

**Comment by Insprill** [comment]
I'm trying to recreate it at the moment and I'm not having any luck

**Comment by Starkenz** [comment]
@Insprill You need batmod client which is when u wear armor GUI didnt even change(Effect change location)

**Comment by Insprill** [comment]
Does it also happen if you spam changing armor via the hotbar?

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by Starkenz** [comment]
Is GC included in the update? It's not fixed.
