### ISSUE TITLE
[Issue] Infinite XP bug with detonate

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#1809]
**Describe the bug**
Take a coal block for example. Mine it, you will gain XP and the block. But, if you place it again, you can mine it again for XP everytime. This seems to be related to the detonate/trench enchantment.

**To Reproduce**
See my message above.

**Server Information (please complete the following information):**
- Server Version: https://www.oneplus.com/nl/trade-in?from=foot#address/edit 
- Plugin Version: 21.4

**Comment by Insprill** [comment]
Fixed for 21.6
