### ISSUE TITLE
It just dont work

### ISSUE THREAD

**Issue by TymonSwinkaYT** [GC-spigot/AdvancedEnchantments#1812]
all of the enchants doesent work maybe a plugin block it
or i have it disabled. One time the config just deleted itself
maybe i have   to verify it in config. Once gears 3 work for a minute but after i died and wear it or any other enchants doesnt work
Please help
PS-Oh and also i cant verify on discord nick: HayWarriorYT

**Comment by Insprill** [comment]
The issue tracker is not for support. It's for reporting bugs and requesting features. If you bought the plugin on spigot/ songoda then you need to transfer your license to our site. In our discord server you can create a ticket and there is a form you can fill out to do so. That is also where you can ask these questions.
