### ISSUE TITLE
[Issue] TRENCH cannot drop air error

### ISSUE THREAD

**Issue by TheKlimoT** [GC-spigot/AdvancedEnchantments#1813]
https://paste.helpch.at/omobewukan.md

- Server Version: git-Purpur-1011 (MC: 1.16.5)
- Plugin Version: AdvancedEnchantments-8.0.0-Pre21.5

**Comment by Insprill** [comment]
How was this caused? I can see it is from the TRENCH effect so obviously when mining, but where & what was the user mining?

**Comment by larssieboy18** [comment]
I can confirm this is also still present on version 21.6:
https://bin.bloom.host/oxuqigumud.md

**Comment by Insprill** [comment]
I'm not able to recreate this issue on Paper-573 1.16.5, nor 1.8.8 or 1.12.2. Can you check to see if this only happens on Purpur? and as i asked before i need to know when and where this happens so i can try better to reproduce it

**Comment by Kesims** [comment]
I can also rarely see it in console on PaperSpigot-412 1.16.4.

**Comment by Insprill** [comment]
Possible fix in the next update. Get back as to if it worked or not
