### ISSUE TITLE
[Issue] Telepathy + Smelting can be used for unlimited cake

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1815]
**Describe the bug**
You can use a tool with Telepathy and Smelting to mine a placed cake that is partially eaten and get back a full cake.

**To Reproduce**
1.) Place a cake
2.) Eat some of it
3.) Hold a pickaxe
4.) /ae enchant telepathy 4
5.) /ae enchant smelting 3
6.) Mine the partially eaten cake with the pickaxe

**Server Information (please complete the following information):**
- Server Version: Paper-570
- Plugin Version: 8.0.0-Pre21.5.2

**Comment by Insprill** [comment]
Fixed for 21.7
