### ISSUE TITLE
[Issue] Telepathy + Silk Touch door break duplication

### ISSUE THREAD

**Issue by Kesims** [GC-spigot/AdvancedEnchantments#1816]
**Describe the bug**
When you break upper block of door with tool enchanted with Telepathy + Silk Touch, it gives you 2 doors instead of 1. When you brake the bottom block of door, it does not do that.

**To Reproduce**
Enchant for example pickaxe with Telepathy + Silk Touch, place doors and break them (the top block, not bottom)

**Server Information (please complete the following information):**
- Server Version: PaperSpigot-416 1.16.4
- Plugin Version: 8.0.0-Pre21.5.2

**Comment by Insprill** [comment]
I wasn't able to reproduce this issue on pre21.6, can you try that and see if it still happens?

**Comment by Insprill** [comment]
#1819 describes it better

**Comment by Kesims** [comment]
Oh, yes, its exactly like in that report.

**Comment by Insprill** [comment]
Fixed for pre21.8.
