### ISSUE TITLE
[Issue] BREAK_TREE ignores Unbreaking

### ISSUE THREAD

**Issue by justaureus** [GC-spigot/AdvancedEnchantments#1817]
**Describe the bug**
When using the BREAK_TREE effect, it bypasses unbreaking and takes a single point of durability for each log broken.

**To Reproduce**
Create an enchantment that uses the BREAK_TREE effect, apply it to an axe, watch the item's durability before and after.

**Screenshots / Video**
https://www.youtube.com/watch?v=Q1aK4WIYBKs

**Server Information (please complete the following information):**
- Server Version: PaperSpigot 545 1.16.5
- Plugin Version: 21.3

**Comment by justaureus** [comment]
I have discovered this also applies to TRENCH and CUSTOM_TRENCH after testing.

**Comment by Insprill** [comment]
Fixed for pre21.8
