### ISSUE TITLE
[Request] Stacking Effects

### ISSUE THREAD

**Issue by justaureus** [GC-spigot/AdvancedEnchantments#1818]
**Describe the Request**
The simplest way to explain this idea is with an example.  
Let's say a player named Steve has a pair of boots which give him a HEALTH_BOOST 1 status effect.  However, Steve also has some leggings which give him HEALTH_BOOST 1 as well.  
I would like to be able to make these "stack" on top of one another, essentially upping Steve's HEALTH_BOOST to 2 so long as he is wearing both the leggings and boots.

**Comment by Insprill** [comment]
Duplicate of #1555
