### ISSUE TITLE
[Issue] Duplicate 2 tall blocks with Telepathy + Silk Touch OR Telepathy + Smelting

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1819]
**Describe the bug**
You can duplicate blocks that are 2 tall (like Rose Bushes or Doors) with Telepathy + Silk Touch or Telepathy + Smelting. You must mine the top/highest part of the block

**To Reproduce**
METHOD 1:
1.) Acquire a tool
2.) Enchant it with Silk Touch
3.) /ae enchant telepathy 4
4.) Use the tool to mine the TOP part of a Door or 2-high flower (i.e. Rose Bush)

METHOD 2:
1.) Acquire a tool
2.) /ae enchant smelting 3
3.) /ae enchant telepathy 4
4.) Use the tool to mine the TOP part of a Door or 2-high flower (i.e. Rose Bush)

**Screenshots / Video**
![Inked2021-03-28_19 07 13_LI](https://user-images.githubusercontent.com/29821149/112772880-e7e2e480-8ff8-11eb-8661-60d961fa59af.jpg)
Mine the circled part, NOT the part with the X

**Server Information (please complete the following information):**
- Server Version: Tuinity-218 MC 1.16.5
- Plugin Version: 8.0.0-Pre21.6

**Comment by Insprill** [comment]
Fixed for pre21.8.
