### ISSUE TITLE
Enderpearls activating enchants of axe/sword

### ISSUE THREAD

**Issue by KnavishMantis** [GC-spigot/AdvancedEnchantments#1820]
When you are holding an axe with custom enchants and you throw an enderpearl and then hold the axe when you land, the enchants activate as if you were hit by someone who had them. I am not entirely sure what enchants this works for but I do know that multipliers affect this, as people have been accidentally killing themselves by throwing a pearl and then holding their axe (if their deathbringers activate for example)

Hold an axe with damaging enchants (I imagine other ones work but I have it set up so only some show up in my chat) while your ender pearl lands. 

https://youtu.be/w0sppWKkdPY

- Server Version: [PaperSpigot-484 1.16.5]
- Plugin Version: [8.0.0-Pre21.5]

**Comment by Insprill** [comment]
I wasn't able to reproduce this on pre21.7. can you send the enchants you had on your axe?

**Comment by KnavishMantis** [comment]
https://gyazo.com/08c5c1fa90e26061403291fa32b0f8af

Not all of my enchants say something in chat when they activate but Devour definitely goes off consistently

**Comment by Insprill** [comment]
can you send the enchants from the enchantments.yml too? just throw them in a pastebin or a gist

**Comment by KnavishMantis** [comment]
https://pastebin.com/2g78kDmt

I also just heard that people are potentially activating cleave on themselves? this makes me feel like there could possibly be something wrong with my configurations because I imagine other people would have noticed this? I have no idea what it could be though.

**Comment by KnavishMantis** [comment]
any update on this?

**Comment by KnavishMantis** [comment]
https://streamable.com/j8agsf

**Comment by Insprill** [comment]
I'm still not able to reproduce this. I used your enchantments.yml and copied your axe and nothing. Can you try on a test server with nothing but AE then add in your plugins 1 by 1 to see if it's a conflict?
