### ISSUE TITLE
[Issue] TP_DROPS overriding Fortune on 1.8.8

### ISSUE THREAD

**Issue by Breany** [GC-spigot/AdvancedEnchantments#1822]
- If the player has the enchantment "Telepathy" as well as Fortune, Fortune doesn't work and gets only one item & can add the enchantment on the weapons (swords and bow)
- Add an enchantment to fire 3 arrows at the same time instead of having a rain of arrows (Striker enchantment)

**Comment by Insprill** [comment]
server version? ae version?

**Comment by Breany** [comment]
1.8.8 tacospigot

**Comment by Insprill** [comment]
Was able to reproduce on 8.0.0-pre21.7 on Paper 1.8.8

**Comment by Insprill** [comment]
Fixed for pre22.3
