### ISSUE TITLE
hello i need some rework / help

### ISSUE THREAD

**Issue by aliadel32** [GC-spigot/AdvancedEnchantments#1823]
so i have this enchant when some attacks me he gets poisoned i want to make it that if i hit my self with a bow (bow boosting) i dont poison my self. thank you 
enchant:display: '%group-color%Acid'
  description: "Chance to give poison to your attacker"
  applies-to: 'Armor'
  type: 'DEFENSE;DEFENSE_MOB;DEFENSE_BOW'
  group: 'ULTIMATE'
  applies:
    - 'ALL_ARMOR'
  levels:
    1:
      chance: 8
      cooldown: 6
      effects:
        - 'POTION:POISON:0:60 %attacker%'
        - 'MESSAGE:&b&l POISONED  %attacker%'
    2:
      chance: 12
      cooldown: 6
      effects:
        - 'POTION:POISON:0:120 %attacker%'
        - 'MESSAGE:&b&l POISONED  %attacker%'
    3:
      chance: 17
      cooldown: 6
      effects:
        - 'POTION:POISON:1:60 %attacker%'
        - 'MESSAGE:&b&l POISONED  %attacker%'
    4:
      chance: 23
      cooldown: 6
      effects:
        - 'POTION:POISON:1:120 %attacker%'
        - 'MESSAGE:&b&l POISONED  %attacker%'

**Comment by aliadel32** [comment]
only myself (i want my enemy if he bows me to get posioned but not myself)

**Comment by Insprill** [comment]
Issue tracker is not for support. join our discord server for help

**Comment by aliadel32** [comment]
hello i was in the discord a mod told me to come here and ask for a rework

‫في الثلاثاء، 30 مارس 2021 في 12:49 ص تمت كتابة ما يلي بواسطة ‪Insprill‬‏ <‪
***@***.***‬‏>:‬
