### ISSUE TITLE
The '/ae reload' command does not unload preloaded asets.

### ISSUE THREAD

**Issue by smyaknti** [GC-spigot/AdvancedEnchantments#1824]
## Details

**Describe the bug**
The `/ae reload` command does not unload the preloaded asets and as a result modifications to the same aset is discarded.

**To Reproduce**
Simply edit the aset configs or create a new one and reload the plugin.

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/13618933/112963058-a1aa9400-9164-11eb-94a6-1aa34c40bf55.png)
Here the old sets are still loaded even after them being deleted form the physical server

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/cixuyicice

**Comment by Insprill** [comment]
Fixed for pre21.8
