### ISSUE TITLE
Custom Model Data issues

### ISSUE THREAD

**Issue by SirCraftypants** [GC-spigot/AdvancedEnchantments#1825]
Hi, As requested.

paper 1.16.5 #570
MC client

There are issues with Custom Model Data on some items

White Scroll first.
I managed to get custom model data working by moving it to the bottom of its coding as follows.

white-scroll:
  delete: true
  lore-display: '&f&lPROTECTED'
  item:
    type: STICK
    id: 0    
    force-glow: false
    name: '&fWhite Scroll'
    lore:
      - '&fPrevents an item from being destroyed'
      - '&fdue to a failed Enchantment Book.'
      - '&ePlace scroll on item to apply.'
  messages:
    applied:
      - '&a&l(!) &aWhite scroll has been applied to your item.'
    failed:
      - '&c&l(!) &cWhite scroll saved the item.'
  custom-model-data: 92    

But with Holy White Scroll, custom model data is refusing to work.

All other Scroll items custom model data are working fine,  just Holy White Scroll not playing ball.

**Comment by Insprill** [comment]
Fixed for pre21.8
