### ISSUE TITLE
Veinminer Enchant block breaking

### ISSUE THREAD

**Issue by Zangerine** [GC-spigot/AdvancedEnchantments#1826]
So I have a plugin that has a chance to drop custom items from mining an ore. The veinminer enchant only drops it from the _block you mine as opposed to having a chance to drop from all of the blocks that are mined_ with Veinminer. **GC** thinks that this is because the _Veinminer sets the blocks that it veinmines to air_ and then creates a **World#dropItemNaturally**. I was wondering if there was a way that we could use **Block#breakNaturally** instead so as to allow each broken block to register as a block being broken in **BlockBreakEvent**.

**Comment by Insprill** [comment]
For pre21.8 I've added an experimental option (config.yml, `settings.fire-block-break-event`, disabled by default) to call a BlockBreakEvent for each block AE breaks.
