### ISSUE TITLE
Repeating enchants repeating when they shouldn't

### ISSUE THREAD

**Issue by Omega105** [GC-spigot/AdvancedEnchantments#1827]
## Details

**Describe the bug**

I have a repeating enchant that continually summons XP even when the player is offline. In other words, the repeating enchant continually works even if the person using the item is offline.
**To Reproduce**

Use a repeating enchantment that summons xp, the marketplace has one, and apply it to the item, then log off in a loaded chunk (spawn chunk or a chunk loaded by a player) and wait, then re log and you would see that there is lots of xp at your feet.
**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/cazoderuno 
- Server log: There is no warning or error in the server log

**Comment by Insprill** [comment]
Fixed in the next update
