### ISSUE TITLE
[Request] More enchantment table customization

### ISSUE THREAD

**Issue by Omega105** [GC-spigot/AdvancedEnchantments#1828]
## Request

**Description**

More customization with enchantment tables! The ability to change each enchant pool based on each enchantment level 1-30. Mabey we can even change the odds per enchantment, mabey even by the level fo the enchantment not just enchantment groups? (Ex. Inquisitive 1-3 can be gotten from level 1-8 enchantments but inquisitive 4 need level 9+ or something)
Also the enchantment table shouldn't give duplicate enchantments, just 1.
**How the feature is useful**

This would allow players to have a much more seamless customer enchanting experience, servers that want this would benefit from being able to recreate actual enchantment odds.

**Comment by Insprill** [comment]
The first and 3rd requests have both been implemented for some time now so I'm marking this as accepted. As for chances per level, it might come if we fully rework enchantment tables, but otherwise I'm going to deny that.
