### ISSUE TITLE
Problem with pinging item into chat with AE enchants

### ISSUE THREAD

**Issue by naikyy** [GC-spigot/AdvancedEnchantments#1830]
Hello, im using CMI and the plugin has feature to ping item in chat by [item]. When I ping just one AE item, its all fine but when I ping Shulker full of AE enchantments it dont crash server but it disconnect all people on the server and they can join back again but its annoying you know when you can "kick" all people on the server like that. I already created bug report on CMI plugin but it could be problem with AE not with CMI.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/quwasajezo
- Server log: https://pastebin.com/nHHz1J7k (there are no errors, just the thing where everybody disconnects)
- This is the shulker box: https://i.imgur.com/m1pMlPw.png

**Comment by Insprill** [comment]
Don't see how this would be an issue with AE. If Zrips says it's not an issue on their end we'll look into but it seems like an issue on their end.
