### ISSUE TITLE
AE Admin doesn't give enchantment

### ISSUE THREAD

**Issue by Tauses** [GC-spigot/AdvancedEnchantments#1832]
## Details
Plugin version: AdvancedEnchantments-8.0.0-Pre21.7.jar
Server Version: Tuinity version git-Tuinity-"f8c0db4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Describe the bug**
I added 5 new custom enchantments and I tried getting one of them by using /ae admin and choosing it from there.
It just reveals the book in the /ae admin GUI and gives me an error in console.
https://mcpaste.io/775dae6a444c4181 <- error is in there.
Its the same with all of the other newly added enchantments.
**To Reproduce**
Add Diploid to your enchantments.yml
Do /ae admin
Click on it
After clicking on it in the GUI, it will go from a firework star to the book and rename itself to 'NullDiploid'
Check console for error

**Screenshots / Video**
<img width="267" alt="nulldiploid" src="https://user-images.githubusercontent.com/63642622/113423784-5f38bf80-93cf-11eb-8518-850998c0dd23.PNG">

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/kogizaviga
- Server log:
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6249946/latest.log)

**Comment by Insprill** [comment]
make sure the enchant has a group that's valid, and the group in the groups.yml isn't missing any values. error will be fixed in the next update

**Comment by Tauses** [comment]
Hi. I forgot to assign them valid groups. I think that might've been the case.
