### ISSUE TITLE
Enderdragon Doesn't drop loot

### ISSUE THREAD

**Issue by Tauses** [GC-spigot/AdvancedEnchantments#1833]
## Details
**Describe the bug**
The dragon does not drop assigned loot when killed with projectiles

**To Reproduce**
Kill dragon with the bow below
Watch loot not drop

**Screenshots / Video**
Killed the dragon using this bow:
![dragon](https://user-images.githubusercontent.com/63642622/113424270-29e0a180-93d0-11eb-8eca-b31260991f7d.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/kogizaviga
- Server log: 
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6249957/latest.log)

- Server version: Tuinity version git-Tuinity-"f8c0db4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by RulerOfEternity** [comment]
Hey I'm kinda curious but what type of server is this? I might want to join in lol

**Comment by Tauses** [comment]
@RulerOfEternity the server is called TinyEarth, it's a towny/adventure server, you can check it out here: play.tiny-earth.com

**Comment by Insprill** [comment]
Is this still an issue on the latest version? I couldn't reproduce it.
