### ISSUE TITLE
Enchant display config request

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1836]
## Request

**Description**

Add a config where you can edit how the enchant is displayed when applied on an item for example : 

EnchantOnItem: 
- "%enchant% %group% &c[ ! ]"

**How the feature is useful**

Instead of having to edit 200+ enchants you can simply do this + for some cases where you only want the enchant name and not the group name next to it.

**Comment by Insprill** [comment]
Is this for how it would display in the item's lore?
