### ISSUE TITLE
Item lore changes colour after applying enchantment

### ISSUE THREAD

**Issue by Veyjinn** [GC-spigot/AdvancedEnchantments#1841]
Hello, 

I've spotted a bug related to enchanting items with custom lore. The lore changes colour after applying enchant. (It changes via command or enchbook)

Before enchanting, the item lore looks like this:
![image](https://user-images.githubusercontent.com/59097595/113597296-c9ee3300-963b-11eb-841a-3dce917d6e13.png)

After enchanting:
![image](https://user-images.githubusercontent.com/59097595/113597353-de323000-963b-11eb-8d69-7fafcc1cc900.png)

## Server Information
- "/ae plinfo" 
![image](https://user-images.githubusercontent.com/59097595/113597493-16397300-963c-11eb-90eb-fc0d89ce48b3.png)

**Comment by Insprill** [comment]
Update to 1.16.5 & AE 8.0.0pre22.6 and see if it still happens. I wasn't able to reproduce this
