### ISSUE TITLE
[Issue] Infinite Armor effects 

### ISSUE THREAD

**Issue by Izurumn** [GC-spigot/AdvancedEnchantments#1842]
**Describe the bug**
Players can get infinite effects with no armors. EFFECT_STATIC types.
Drunk
Gears
Anti gravity
Overload
Obsidianshield
Glowing
Aquatic

**To Reproduce**
The bug related to mouse click operation. But you need some effect static type enchantment. For example above. More info belove...

**Screenshots / Video**
https://user-images.githubusercontent.com/21794143/112931324-83d23480-914e-11eb-8bfe-1ba0670e077d.mp4

**Server Information (please complete the following information):**
•	Server Version: [PaperSpigot-123 1.8.8]
•	Plugin Version: [8.0.0-Pre21.5]

**Comment by Insprill** [comment]
Does it also happen if you spam changing armor via the hotbar?

**Comment by Insprill** [comment]
Fixed in the next update
