### ISSUE TITLE
SoulGrind Enchant issue and Tracker lore positionning

### ISSUE THREAD

**Issue by ShadoW4719** [GC-spigot/AdvancedEnchantments#1844]
## Details

**Describe the bug**

Hello there,
I'm having an issue where the SoulGrind Enchant + "SoulOnMobs:true" don't actually give souls.
Combined with a SoulTracker, it shows 0 or -1 depending on if you killed a mob or not.
I tried setting the chances at 100% and it didnt work either. (SCREENSHOT 1)

Also, is there a way to force the Tracker Lore position itself under the enchantments?
Theres 1 tracker in the middle of the enchantment and 2 under the description, it looks really unprofessional (SCREENSHOT 2)

**To Reproduce**
Simply set SoulOnMobs to true and add the enchantment SoulGrind on your sword

**Screenshots / Video**
https://imgur.com/a/RFsH5Jb

## Server Information
- "/ae plinfo" link: 
- Server log: No error messages

**Comment by Insprill** [comment]
Please don't put multiple bugs/ feature request into one issue and please also provide the ae plinfo link. both issues will be fixed in the next update
