### ISSUE TITLE
Need help with error

### ISSUE THREAD

**Issue by Rmelissa** [GC-spigot/AdvancedEnchantments#1845]
Hello there,
I'm having an issue i created an enchant on the website to create enchants because the experience enchant wasn't working, well a created the enchant and it worked perfect. it works when i drag & drop the book on the pickaxe,shovel,axe but when i go the command /ae enchant (enchant) it says "An error occurred while attempting to perform this command " and the error shows on the link below. 
https://paste.md-5.net/qagulowadi.bash

https://paste.md-5.net/aganakezin.bash

how can i fix this ?
thank you.

https://paste.md-5.net/utozabawuc

## Details

**Describe the bug**

**To Reproduce**

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: 
- Server log:

**Comment by Insprill** [comment]
Fixed in the next update
