### ISSUE TITLE
Add a settings that disables payments for jobs reborn

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#1846]
## Request

**Description**
Basically, I'm looking for a config setting that lets us choose if AdvancedEnchantment enchants like placing 3x3 crops pays the person having a job in jobs reborn or not.

**How the feature is useful**
Because that's really economy breaking and very easy to abuse, and we're mainly looking to make manual labor more rewarding instead of having tons of people getting rich because of 3x3 crop placing enchants. Overall the main goal is to reward the players from manually doing it for money and not giving money to those who place the crops with enchants which is way easier to do, it also keeps players playing way more since they have to grind more to get on top of leaderboards.

**Comment by Agaloth** [comment]
Any possible opinion on this?

**Comment by Agaloth** [comment]
Any news on that one, it would be awesome to get that!

**Comment by Insprill** [comment]
Due to the way things work internally, I don't believe this is possible. Firstly, PLANT_SEEDS now sets the block in a different way, so it shouldn't be paying for all crops planted. As for TRENCH, a toggle for that would need to be done on Jobs' side, not ours.
