### ISSUE TITLE
lower-destroy-with-magic-dust not working (CONFIG)

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1847]
## Details

**Describe the bug**

In the config, the option called "lower-destroy-with-magic-dust" isn't working
**To Reproduce**

go in the config and disable this feature and it won't work 
**Screenshots / Video**

don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
- Paper 1.8.8
- 8.0.0-Pre22.4

**Comment by GC-spigot** [comment]
Fixed
