### ISSUE TITLE
Fortune & telepathy on crops DUPE (urgent)

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1848]
## Details

**Describe the bug**

 With the new fortune patch some stuff got mixed up and when mining for example a melon block with fortune and telepathy (TP_DROPS) it gives like 3 times to amount, for example I mine 1 melon block and I get 15 melon slices and I can dupe.
**To Reproduce**

enchant an axe fortune 3 and with the CE Telepathy and mine a melon block
**Screenshots / Video**

https://gyazo.com/4d44c1c5f9cdb4e36afb0a3df7540e7a

## Server Information
- "/ae plinfo" link: 
- Server log: 
- Paper 1.8.8 
- 8.0.0-Pre22.4

**Comment by Insprill** [comment]
Fixed for 22.5
