### ISSUE TITLE
Breaking a block with a torch or sign attached using a tool with Telepathy will delete the torch or sign when using use-experimental-block-breaking

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1850]
## Details

**Describe the bug**
Breaking a block with a torch or sign (and possible other blocks that hang on/attach to other blocks) attached using a tool with Telepathy will delete the torch or sign (and probably other blocks with similar properties) when use-experimental-block-breaking is set to true.

**To Reproduce**
1.) Set `use-experimental-block-breaking` to true
2.) Place a torch (or sign) on a block
3.) Break the block supporting the torch (or sign) with a tool enchanted with Telepathy

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/29821149/113821603-ed030a80-9741-11eb-89b6-c0987d0d7c95.png)
In this example, you would mine the cobble blocks using a tool enchanted with Telepathy and the torch & sign would be deleted.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/vivugemupu
- Server log: https://gist.github.com/WhatsTheBadNews/ce5c366f0f6369d96687e8709e134e82

**Comment by nivcoo** [comment]
Hello, yes i have the same issue

**Comment by Insprill** [comment]
Fixed for 22.5
