### ISSUE TITLE
AE ETable & Anvil Support (1.8.8)

### ISSUE THREAD

**Issue by ImLevii** [GC-spigot/AdvancedEnchantments#1851]
Spigot 1.8.8 which is the main version used on faction/pvp servers is not compatible with anvil & enchant table support.
I reported this bug months ago, and I'm still waiting for a fix and  its possible ,other plugins have it.

Let me know down below if you plan on fixing it or not otherwise I'll be moving away from this resource, its been far too long already with this issue.

**Comment by Insprill** [comment]
Fill out the proper bug template next time

**Comment by ImLevii** [comment]
When is this getting fixed?

**Comment by ImLevii** [comment]
At this point I'm convinced you guys don't know how to actually support 1.8 w/ETables & Anvils. 
This bug has been an issue for months & you still ignore it.

**Comment by GC-spigot** [comment]
We can't add support for this: all versions till 1.11 don't have features which are required for this featureset.
