### ISSUE TITLE
Lava Walker stay after remove of piece

### ISSUE THREAD

**Issue by nivcoo** [GC-spigot/AdvancedEnchantments#1852]
Hello, I have come back to report the lava walker bug, to reproduce it you have to put the lava walker on boots, change the world and come back to the world then test without the armor piece and it will work as in the video. In addition I normally allowed only one world for the lava walker to test if it works and it is impossible to define a world.

https://pics.revolis.fr/2021-04/08/09-41_Fk9E.mp4

**Comment by nivcoo** [comment]
I use 8.0.0-Pre22.5 in 1.12.2

**Comment by RulerOfEternity** [comment]
Adding onto that, sometimes some obsidian stays over (probably after restart though).

**Comment by nivcoo** [comment]
Also this enchant create lava source so we can duplicate lava

**Comment by Insprill** [comment]
@RulerOfEternity if the server restarts it will stay as obsidian. nothing can be done about that at the moment.

@nivcoo just tested my dev build of 22.8 on 1.12.2 and it doesn't dupe lava. that was fixed a few weeks ago. and I wasn't able to reproduce the issue, could you send a video?
