### ISSUE TITLE
more_drop dose not work with trench

### ISSUE THREAD

**Issue by LXY010327** [GC-spigot/AdvancedEnchantments#1853]
**WHEN I USE** 
  _type: 'MINING'
  applies:
    - ALL_PICKAXE
  settings:
    removeable: false
    disable-in-enchanter: true
  levels:
    '10':
      condition: '%block type% contains ORE : %allow%'
      effects:
        - 'MORE_DROPS:2'_
**AND**
  _type: 'MINING'
  applies:
    - ALL_PICKAXE
  settings:
    removeable: false
    disable-in-enchanter: true
  levels:
    '1':
      effects:
        - 'TRENCH:5'_

**Only "trench" works, i can not get 3 times drop of ores**

**Comment by Insprill** [comment]
Enable `trench-works-with-more-drops` in the config.yml.
