### ISSUE TITLE
Players dying from an attack

### ISSUE THREAD

**Issue by cquelasytb** [GC-spigot/AdvancedEnchantments#1855]
I tested and verified that some enchantments are doing BUG damage.

The REINFORCED enchantment is causing death with just one attack, even without weapons, if the player has ELYTRA with this enchantment.

The KILL AURA enchantment is causing a sword to do over 10,000 damage to a BOSS.

We had other enchantments that we tested, but the list is long, so I reported only the last 2 enchantments that we discovered.

**Comment by Insprill** [comment]
We have issue templates for a reason, fill it out.
