### ISSUE TITLE
Telepathy and fortune not working on axes (melon blocks)

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1858]
## Details

**Describe the bug**

Fortune and the telepathy enchant (TP_DROPS) doesn't work together with an axe

**To Reproduce**

Simply enchant your diamond axe with fortune 3 and telepathy and mine a melon block and bam you only get the normal amount even with fortune
**Screenshots / Video**

(can't be asked to post a 45 mins video of me farming melons)

## Server Information
- "/ae plinfo" link: 
- Server log: 
plugin ver :  8.0.0-Pre22.5
Server ver : paper 1.8.8-443 (latest)

**Comment by Insprill** [comment]
Fixed in the next update
