### ISSUE TITLE
Permanent potion effect using hopper

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#1859]
## Details

**Describe the bug**
This bug is player abusing effect_static enchantment to get permanent effect potion even without wearing.

**To Reproduce**
You need hopper & effect_static enchantment for this. You simply put your armor in hopper. Done. More info in video. 

**Screenshots / Video**
https://user-images.githubusercontent.com/21794143/114076627-70a32f80-98d9-11eb-88e9-0bd3da11f492.mp4

## Server Information
-  Server Version: [PaperSpigot-123 1.8.8]
- Plugin Version: [8.0.0-Pre21.5]

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by Starkenz** [comment]
@Insprill Thanks for the support.
