### ISSUE TITLE
Group-color placeholder bug

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1860]
## Details

**Describe the bug**

The placeholder '%group-color%' no longer works on the enchantment-book section in the config, it's always orange (&6) when in my config it's &3 (blue)
**To Reproduce**

Go in your config, edit the "enchantment-book" part and do this : 
enchantment-book:
  item:
    type: BOOK
    id: 0
    force-glow: false
    custom-model-data: 0
  name: '&dEnchanted book'
  lore:
  - '%enchant%'
  - %group-color%%description%'

**Screenshots / Video**

none

## Server Information
- "/ae plinfo" link: 
- Server log: 
server ; 1.8.8 paperspigot latest
plugin : 8.0.0-Pre22.6 Changelog

**Comment by Insprill** [comment]
I wasn't able to reproduce this on 1.8.8 or 1.16.5. make sure you save the file and fully restart your server to apply the change.

**Comment by LuluxClient** [comment]
> I wasn't able to reproduce this on 1.8.8 or 1.16.5. make sure you save the file and fully restart your server to apply the change.

The issue is the placeholder is bugged, it will take the color from the enchant name and not the groupe color.

**Comment by LuluxClient** [comment]
For example If in my enchantement.yml config I have an enchant where his display is "display: '&6+ Elbow Smash123'" and if I use the %group-color%" and "%group-name%" placeholders together in the "enchantment-book:" section in the config.yml file well it won't display the group color, it will display the color of the enchantment and not the group...

**Comment by Insprill** [comment]
Thats because the color is in the name. It will take the last color before text. Either remove it from the enchantment name or use the placeholder that strips all colors

**Comment by LuluxClient** [comment]
> Thats because the color is in the name. It will take the last color before text. Either remove it from the enchantment name or use the placeholder that strips all colors

Did you change it recently ? Since it's not supposed to be like that. It's supposed to grab the "Group Name" and the group color, not the enchant name color ??? And If I change it the display on the items will also change (I also made a suggestion about editing the enchant display on items)
