### ISSUE TITLE
Godly Transmog Scroll

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1863]
## Request

Add a Godly Transmog Scroll, this scroll will allow you to customize the order of the enchantments on the item, I saw this on an other plugin and I thought it would be a great idea to implement it on here!
![b0b57f33fe7c81dd2aa937baabea62c591e9ad0d](https://user-images.githubusercontent.com/76789367/114311832-9f472300-9af0-11eb-8346-0bd61e7ca6ea.gif)
![e45664fdefbdda7b6c7f46b094a280b290137b19](https://user-images.githubusercontent.com/76789367/114311834-a110e680-9af0-11eb-82a8-545a5678ff1b.jpg)

**How the feature is useful**
It is a cosmetic feature, it doesn't have any power.

**Comment by GC-spigot** [comment]
We're not adding any cosmic-related features anymore, it is not popular and considering we have less than 10% of our userbase 1.8, likely that it won't be used widely either.
