### ISSUE TITLE
Unsucc enchantments when you need another enchantment

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#1864]
## Details

**Describe the bug**

Used default enchantments!!!
Enchantment used: megaheavy
Needed enchantment: heavy (Item don't have it)

megaheavy (or another, for example atomicdetonate) writes that it was unsuccessfully but we don't have enchantment heavy (or another for example detonate)   . _.

**To Reproduce**

Take megaheavy and try to enchant any item without heavy

**Screenshots / Video**

https://drive.google.com/file/d/1jgqOFbcR4697G1hnpK8t_kJ8H-lsqqGp/view?usp=sharing

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://paste.md-5.net/bativeloha

**Comment by Insprill** [comment]
The google drive link you sent is private, but what your describing it sounds like it's working fine? You don't have the required enchant so it doesn't apply

**Comment by iBuseWinner** [comment]
> The google drive link you sent is private, but what your describing it sounds like it's working fine? You don't have the required enchant so it doesn't apply

Fixed link.
Yes, I don't have required enchantment, but when I try to enchant it disappears.

**Comment by Insprill** [comment]
Fixed in the next update
