### ISSUE TITLE
Enchanter inventory size error

### ISSUE THREAD

**Issue by NFLD99** [GC-spigot/AdvancedEnchantments#1866]
## Details

**Describe the bug**

when adjusting the inventory size for enchanter you need to use 1 as your starting number, however when placing items inside the inventory you need to use 0. after using 0 as your starting point for size you will get a null error when you try to open the enchanter

**To Reproduce**

open config.yml and change your enchanter sizing to 26/53 and reload the plugin after tring to open enchanter you will get a null error 

**Screenshots / Video**

Config:
https://i.imgur.com/lclRdhU.png

In-game Error: 
https://i.imgur.com/41dU8JZ.png

Console Error: 
https://i.imgur.com/d4sZnMI.png

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ujivotuxen
- Server log: https://gist.githubusercontent.com/NFLD99/395dfaa42361b17e9cca0ae69b9ea3e1/raw/767a2edcf57148f6918ce687bfff5dde08c22514/latest.log

## Suggested Fix
I would suggest making the size use 0 as its start as that is what the game uses for slots

## More Info
If there is any more information I can provide please do let me know.

**Comment by Insprill** [comment]
Fixed for the next update
