### ISSUE TITLE
Closing the tinkere GUI with ESC doesn't give your items back

### ISSUE THREAD

**Issue by iGabyTM** [GC-spigot/AdvancedEnchantments#1867]
## Details

**Describe the bug**

Closing the tinkerer GUI with ESC doesn't give your items back

**To Reproduce**

1. Put some items in the tinkere GUI
2. Close the GUI using ESC

**Screenshots / Video**

https://streamable.com/s8fe3e

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/nigibitixo
- Server log:

**Comment by Insprill** [comment]
I wasn't able to reproduce this. can you see if it happens on Paper?

**Comment by iGabyTM** [comment]
Forgot to update you guys, me and other 3 people tried this and didn't happened either, guess it is a small chance for this to happen?

**Comment by Insprill** [comment]
Maybe. Seems like some sort of one off issue. I'm gonna close this and if you can find a reliable way to reproduce it feel free comment on here or create a new issue
