### ISSUE TITLE
Item with white scroll still loses enchantment

### ISSUE THREAD

**Issue by Pudiaz** [GC-spigot/AdvancedEnchantments#1868]
## Details

**Describe the bug**
When applying a Heroic enchant on a item that has like dodge 5 on it with a white scroll, When the heroic enchant fails, dodge 5 also disappears even though a white scroll was on the item.

**To Reproduce**
put a white scroll and an enchant that upgrades to a heroic like dodge 5 and apply a low percentage heroic eternal dodge 1 onto it, When it fails the dodge 5 enchant will disappear off the item.

**Screenshots / Video**
https://gyazo.com/63e92dc0f608cc7786adf887d4379208
https://gyazo.com/f4808cf26ae72df700007e78bebbc105

## Server Information
Paper 1.16.5 - 532
AdvancedEnchantments-8.0.0-Pre22.7
--

**Comment by RulerOfEternity** [comment]
Where do you get the symbols for the name? I'd love to know!

**Comment by Pudiaz** [comment]
> Where do you get the symbols for the name? I'd love to know!

What symbols are you referring to?

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by RulerOfEternity** [comment]
> > Where do you get the symbols for the name? I'd love to know!
> 
> What symbols are you referring to?

The things next the name of the Sword 'Piplup'
