### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ecoterrorist** [GC-spigot/AdvancedEnchantments#187]
Ability to distinguish two different max levels for every enchantment.

I request that in a future version of AE we be able to set both a maximum global maximum level for each enchant, AND a maximum level of the enchantment that may be obtained from the ‘/ae’ menu as a random book. The global level applies to users who combine books in he Alchemist.

**Comment by N3kas** [comment]
Do you want configuration to set up to how many levels alchemist allows to combine? I'm not entire sure what you mean by "Ability to distinguish two different max levels for every enchantment.", what are these two different max levels?

**Comment by ecoterrorist** [comment]
Sorry I was unclear. I just want a way to limit the maximum level of enchantments as obtained from "givercbook <group>" separately from the true maximum level of the enchantment. 
Example:
Enchantment "Flame Arrow" has a true maximum level of 5 as defined in your configuration of enchantments.yml. You may combine "Flame Arrow III" books in Alchemist to create a "Flame Arrow IV", as well as combine "Flame Arrow IV" books to create "Flame Arrow V" (The max level of the enchant). That is all default behavior. What I was trying to articulate in my feature request is that in the configuration for every enchantment there should be a `max-giverc: <value>` field, or similar, where you can limit the highest level of that enchantment that a player can receive from a "right-click", or unidentified, book. If "Flame Arrow" had 5 levels, but `max-giverc: 3` was stipulated in "Flame Arrow"'s configuration, the maximum level of "Flame Arrow" that would be possible to get from the right-click book would be 3, but you could still level the enchantment to its true maximum (5) though the Alchemist.
