### ISSUE TITLE
Fortune and telepathy not working together

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1871]
## Details

**Describe the bug**

Simply fortune and telepathy doesn't work together and on some cases (refer to my previous git ticket) some dupes. 
If you use telepathy (tp drops) and fortune to mine for example a diamond ore, it won't work.
**To Reproduce**

Grab a diamond pickaxe, enchant it with telepathy and mine a diamond ore 
**Screenshots / Video**

https://gyazo.com/81e6642fdd3c5fec63819509ac63928b

## Server Information
- "/ae plinfo" link: 
- Server log: 
Plugin ver : 8.0.0-Pre22.9
Server ver : 1.8.8 latest

**Comment by Insprill** [comment]
Fixed in the next update
