### ISSUE TITLE
Too many enchantments

### ISSUE THREAD

**Issue by kiwwwii** [GC-spigot/AdvancedEnchantments#1873]
## Details

**Describe the bug**
 When i execute command /ae list I get kicked out from the server and it shows me. On of developers on Discord told me to report this bug on here. He said that i have too many enchantments

**To Reproduce**

**Screenshots / Video**
 
![45B1BD1F-CBB2-4650-83B8-490931492BE1](https://user-images.githubusercontent.com/82496421/114665539-d9d5d900-9d05-11eb-97fd-bf22b07713ea.jpeg)

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/arukixeneq
- Server log:

**Comment by Insprill** [comment]
Fixed in the next update
