### ISSUE TITLE
Mining block placed above a Sea Lantern with a tool enchanted with Telepathy will drop a Sea Lantern when use-experimental-block-break is set to true

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1874]
## Details

**Describe the bug**
Mining block placed above a Sea Lantern with a tool enchanted with Telepathy will drop (duplicate) a Sea Lantern when use-experimental-block-break is set to true. The Sea Lantern won't break because, as you mined the block above it. However an additional one will be dropped.

**To Reproduce**
1.) Set `use-experimental-block-break` to true
2.) Hold a pickaxe and /ae enchant telepathy 4
3.) Place cobblestone (or another block) above a sea lantern
4.) Mine the cobblestone
5.) Look and see a sea lantern on the ground, in addition to the one you placed

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/114692354-2b6a6d80-9cde-11eb-8376-884a18e84d93.png)
In this example screenshot, just mine the cobble with a tool that is enchanted with Telepathy.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/waqeratili
- Server log: https://gist.github.com/WhatsTheBadNews/5efdd176f9bcaaeb8b57da7b98a1c2a0

**Comment by Insprill** [comment]
Fixed in the next update
