### ISSUE TITLE
Fortune and telepathy not working together

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1875]
## Details

**Describe the bug**

1st issue : Simply fortune and telepathy doesn't work together and on some cases.  
If you use telepathy (tp drops) and fortune to mine for example a diamond ore, it will won't work but not above fortune 3, if you use fortune 10 for example it won't work and it will give you the loot for the fortune 3.

2nd issue : Telepathy and fortune not working on carrots, potatos,

**To Reproduce**

1st issue :Grab a diamond pickaxe, enchant it with telepathy and mine a diamond ore 

2nd issue : Grab a pickaxe, enchant it with fortune 3 or more, apply telepathy on it and it will give 1 carrot / potato instead of more
**Screenshots / Video**

1st issue : 
- With telepathy and fortune 8: https://gyazo.com/e06813d6f69b565907778bdd9652b58c
- Without telepathy but with fortune 8 : https://gyazo.com/12cd6172e81b4e92c1ff8425fd57538d

2nd issue : https://gyazo.com/fd285394cf0450fccd8914c29b93d0dd

## Server Information
- "/ae plinfo" link: 
- Server log: 
Plugin ver : 8.0.0-Pre23.0
Server ver : 1.8.8 latest
Error on startup : https://pastebin.com/sG1JhEWD
Error : https://pastebin.com/LPnnJ98L

**Comment by Insprill** [comment]
send the "/ae plinfo" link. there is a reason we ask for it

**Comment by LuluxClient** [comment]
> can you send the "/ae plinfo" link? i tested this myself and wasn't able to reproduce it

I will and also can you check the 2nd issue too and the errors ? 

And you will see the numbers are way lower, I can test it on your test server if you're on today (I will send the list in 1-2h I'm not home)

**Comment by LuluxClient** [comment]
> /ae plinfo" link

https://paste.md-5.net/rozevanora

**Comment by LuluxClient** [comment]
This might help a lot : https://youtu.be/nPh8uLSxjJk

**Comment by LuluxClient** [comment]
With 64 diamond ores : https://youtu.be/m21u2NCW6iE

**Comment by Insprill** [comment]
Fixed at some point
