### ISSUE TITLE
Permanent effect bug

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1876]
## Details

**Describe the bug**

If you place a book that has a high destroy chance on an item you are wearing for example a pair of diamond boots. the boots are going to be destroyed but the effect is still here (for example Speed II) 

**To Reproduce**

Wear an item with a potion effect or something else (SPEED II) place a book with a high destroy chance on it, destroy the item and bam you have Speed II without having to wear the armor piece

**Screenshots / Video**

https://gyazo.com/19e5708f5a1ef3ea7098bf39b07807d5

## Server Information
- "/ae plinfo" link: 
- Server log: 
Plugin info : 8.0.0-Pre23.0
Server ver : 1.8.8

**Comment by Insprill** [comment]
Fixed in the next update
