### ISSUE TITLE
A bunch of feature requests

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1877]
## Request

Please add mKits/vKits, Titan Attributes and Masks, and most importantly, an "OFFHAND_HELD" effect, or preferably make the "HELD" effect support the offhand too.

**How the feature is useful**
mKits/vKits would be great for server owners, Titan attributes would be great special abilities for weapons, and masks would be great for some tiny boosts like 5% extra damage for example.

https://wiki.cosmicpvp.com/wiki/Vkits

https://wiki.cosmicpvp.com/wiki/Mastery_Kits

https://wiki.cosmicpvp.com/wiki/Titan_Attributes

qwe

https://wiki.cosmicpvp.com/wiki/Masks

**Comment by Insprill** [comment]
Please put feature requests into separate issues. It's hard to stay organized with multiple things in one issue.

**Comment by RulerOfEternity** [comment]
All right, thanks for informing me.
