### ISSUE TITLE
Mining a block adjacent to a sign/torch with a tool with Telepathy can be used to duplicate when use-experimental-block-break is set to true

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1878]
## Details

**Describe the bug**
Similar issue to #1874 
Mining a block adjacent to a sign/torch with a tool that has Telepathy can be used to duplicate when use-experimental-block-break is set to true (see screenshot)

**To Reproduce**
1.) Hold a pickaxe and /ae enchant Telepathy 4
2.) Create a setup like the one in the screenshot
3.) Mine the block adjacent to the sign/torch and it will duplicate the sign/torch

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/114770804-76fa3700-9d31-11eb-8817-a4948085d41f.png)
In these examples, you would mine the cobble

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/hogetocuji
- Server log: https://gist.github.com/WhatsTheBadNews/223346a81f14415f30b06675463bc368

**Comment by Insprill** [comment]
Fixed in the next update
