### ISSUE TITLE
mobtrak and stattrak

### ISSUE THREAD

**Issue by InFiniityxSweety** [GC-spigot/AdvancedEnchantments#1879]
Hey i think i found a bug with mobtrak and stattrak.
When both of these "enchantments" are applied to one item as example Diamond Sword they both count +1 when killing a player.
But not when a mob is killed.

Before any kill: https://i.imgur.com/Mz1WRoc.png
After killing a Cow: https://i.imgur.com/yCRPg2H.png
After killing a Player: https://i.imgur.com/xgj8zZI.png

Minecraft and pluginversion: https://i.imgur.com/JXmmBbF.jpg

**Comment by Insprill** [comment]
Fixed in the next update
