### ISSUE TITLE
Add offhand 'HELD' type

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1881]
## Request

I'd like the 'HELD' type to work on items that are held on the offhand as well as the ones on the main hand.

It would be convenient for players using weapons and holding the item with the HELD type on the offhand to enjoy its effects.

**Comment by Pandas0** [comment]
To support those who may not want this feature, I suggest adding either a setting to disable this or actually make the effect 'OFFHAND_HELD' and leave 'HELD' the same as it is now.

**Comment by RulerOfEternity** [comment]
Yeah I don't mind, but there's a set of enchantments I want to work on involving the 'HELD' effect, and I want it to work ambidextrously, it would be too much of a hassle to code it and then add 'OFFHAND_HELD' later, that's why I'm waiting on the developer to hopefully add this to the plugin.

**Comment by RulerOfEternity** [comment]
This feature has been added, so I will close this thread.
