### ISSUE TITLE
PLANT_SEEDS does not work for potatos or carrots

### ISSUE THREAD

**Issue by justaureus** [GC-spigot/AdvancedEnchantments#1884]
## Details

**Describe the bug**
As the title stats, the PLANT_SEEDS effect does not function for potatos or carrots

**To Reproduce**
Create an enchantment with the PLANT_SEEDS effect (or use the default planter one) and attempt to plant with carrots or potatos

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/zigoredugu
- Server log: Running paper 1.16.5

**Comment by Insprill** [comment]
Can you send the enchantment? I just tested the default carrot planter on Paper-595 1.16.5 and it worked fine.
