### ISSUE TITLE
Bug with the 'GUARD' effect.

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1885]
## Details

Using the 'GUARD' effect with an entity that isn't really a mob (Fireball, Evoker Fangs, etc.....) does work but it spams you with messages saying that it doesn't.

**To Reproduce**
Use the 'GUARD' effect with an entity that isn't a mob like one of the examples I mentioned above.

**Screenshots / Video**
https://cdn.discordapp.com/attachments/377152090088275968/833085634599583753/2021-04-17_23.03.26.png

## Server Information
- "/ae plinfo" link: 
https://paste.md-5.net/eritugutop
- Server log: 
https://gist.github.com/RulerOfEternity/71e5c59ce912239ed7099cb58c5748c6

**Comment by Insprill** [comment]
Fixed in the next update
