### ISSUE TITLE
BREAK ignores other MINING type enchants

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1886]
## Details

**Describe the bug**
Obsidian Destroyer doesn't work with telepathy when mining obsidian.

**To Reproduce**
Use a pickaxe with Telepathy and Obsidian Destroyer to mine obsidian, the obsidian doesn't get transported into the inventory directly, but it drops to the ground.

**Screenshots / Video**
https://www.youtube.com/watch?v=2dgP4sP7PhM

## Server Information
- "/ae plinfo" link:  
https://paste.md-5.net/eritugutop
- Server log: 
https://gist.github.com/RulerOfEternity/a176687a39267b34d3837490e03c936b

**Comment by GC-spigot** [comment]
Fixed
