### ISSUE TITLE
Cannot drop air console spam

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#1887]
## Details

**Describe the bug**

![image](https://user-images.githubusercontent.com/44753872/115141226-c5664900-a043-11eb-8914-13c56a5fb62d.png)

![image](https://user-images.githubusercontent.com/44753872/115141204-b8495a00-a043-11eb-88a9-5b2977c5894e.png)

**To Reproduce**

Use autosmelt enchantment

**Screenshots / Video**

In description

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://paste.md-5.net/yexozizuke
I don't think thank you need all latest.log because it so weigth...

**Comment by Insprill** [comment]
Are you using experimental block breaking? If you aren't try turning it on. If you are, try turning it off

**Comment by iBuseWinner** [comment]
I'll try and answer you tomorrow in 24h.

**Comment by iBuseWinner** [comment]
So it isn't helped me...
![image](https://user-images.githubusercontent.com/44753872/115257378-b44b3400-a138-11eb-8873-593a20cf3a8b.png)

**Comment by Insprill** [comment]
Alright, what block is causing the error?

**Comment by Insprill** [comment]
Fixed in the next update
