### ISSUE TITLE
Upgrading Legendary to Heroic Fail (With WhiteScroll Removes Heroic)

### ISSUE THREAD

**Issue by KnavishMantis** [GC-spigot/AdvancedEnchantments#1892]
## Details

**So when players have a legendary enchant on an item and they also have a whitescroll on that item. If they try to upgrade the legendary to the heroic version, instead of just breaking the whitescroll it will also remove the legendary version of the enchant. (When there is no white scroll the piece just breaks which is intended)**

**Add a legendary enchant to a piece and also add a white scroll. Get a low percent heroic or just get "unlucky" with a high percent one and if the enchant fails the legendary is removed.**

**https://youtu.be/S5UpqkuaWMo**

## Server Information
- "https://paste.md-5.net/eqefemuliw" link: 
-https://gist.github.com/KnavishMantis/6edc3a6df3a451fb70daa34715edfd36:

**Comment by Insprill** [comment]
Send the "/ar plinfo" link. There is a reason we ask for it

**Comment by KnavishMantis** [comment]
my bad player, the arrows had me confused.

**Comment by KnavishMantis** [comment]
edited the link into original post

**Comment by Insprill** [comment]
This issue was actually solved a few updates ago, so just update AE.
