### ISSUE TITLE
Server Hard-Lock

### ISSUE THREAD

**Issue by xxirs** [GC-spigot/AdvancedEnchantments#1893]
## Details

**Describe the bug**
Server hard-locks randomly 

**To Reproduce**
No idea seems to happen at random

**Screenshots / Video**
N/A

## Server Information
- "/ae plinfo" link: Removed plugin because it kept hard locking my server
- Server log: https://gist.github.com/xxirs/f92c625c98a5972d030f9131b4eea521

**Comment by Insprill** [comment]
Fixed in the next update
