### ISSUE TITLE
TP_DROPS + Fortune dupes melons

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1894]
## Details

**Describe the bug**

If you mine a melon block with fortune and telepathy you get like 3 times the amount
**To Reproduce**

Grab a diamond pickaxe, enchant it with telepathy and fortune 3 and mine a melon block with it (you get like 20 per melon blocks)
**Screenshots / Video**

https://gyazo.com/475973fc44abea9a440b5b65d46347f7

## Server Information
- "/ae plinfo" link: 
- Server log: 
plugin info : 8.0.0-Pre23.7 
Server version : 1.8.8 paper spigot

**Comment by Insprill** [comment]
Do you have experimental-block-breaking on? if it isn't try turning it on and vice-versa.

**Comment by GC-spigot** [comment]
Fixed
