### ISSUE TITLE
TP_DROPS sugarcane dupe

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1895]
## Details

**Describe the bug**

If you mine a sugar cane with telepathy you get like 2 instead of 1
**To Reproduce**

Grab a diamond pickaxe, enchant it with telepathy and break a sugarcane with it and boom you get 2 each time instead of 1
**Screenshots / Video**

https://gyazo.com/35fdb46b68140c0ae74c481e98cf2310

## Server Information
- "/ae plinfo" link: 
- Server log: 
plugin info : 8.0.0-Pre23.7 
Server version : 1.8.8 paper spigot

**Comment by Insprill** [comment]
Do you have experimental-block-breaking on? if it isn't try turning it on and vice-versa.

**Comment by GC-spigot** [comment]
Fixed
