### ISSUE TITLE
The slot increaser visual bug 

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1896]
## Details

**Describe the bug**

The slot increaser display isn't showing the correct number

**To Reproduce**

If you set it to 3 in the configs but you have the permission "AE.LIMIT.6" and you put 6 enchants the slot increaser item display will show that you have -3 slots (it doesn't count if you have the permission)

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/62576432/115630939-2f614580-a305-11eb-9671-541e2e9554b7.png)

## Server Information
- "/ae plinfo" link: 
- Server log: 
plugin info : 8.0.0-Pre23.7
Server version : 1.8.8 paper spigot

**Comment by Insprill** [comment]
Permissions are per player, items are not. If one person with ae.limit.6 threw an item to a player with no limit perm, it would still be negative - along with having to update the item's lore every time someone picked it up. And what about putting it in a chest? Do we update the lore depending on who opened the chest? What if multiple people with different limits opened the same chest? Fixing this simply isn't possible and/ or isn't something we're willing to do.

**Comment by LuluxClient** [comment]
> Permissions are per player, items are not. If one person with ae.limit.6 threw an item to a player with no limit perm, it would still be negative - along with having to update the item's lore every time someone picked it up. And what about putting it in a chest? Do we update the lore depending on who opened the chest? What if multiple people with different limits opened the same chest? Fixing this simply isn't possible and/ or isn't something we're willing to do.

An easy fix is when a player is trying to apply a book, the lore will update itself, as easy as that.

**Comment by Insprill** [comment]
The entire slot system is very janky, and modifying the lore just seems like replacing one janky system with another. I do plan on completely reworking the slot system at some point, and when that's done the lore will show properly. But until then, i'm going to keep this marked as denied.
