### ISSUE TITLE
Support Unsafe Enchantments in Anvil Integration

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#1897]
Hello there,

It would be nice if there was a configuration option to allow anvil integration to work with unsafe enchantments in the anvil, since another plugin allows players to enchant items in an anvil past their vanilla defaults. 

Simply, instead of resetting the unsafe enchantment level to its normal value, keep it the same value on the result. Or better yet, allow user defined enchantment limits in the configuration file, with a permission allowing players to use the feature.

Example: Item with Unbreaking VI is added to item with Detonate X and unbreaking VI. Resulting item has Detonate X, but only Unbreaking III. With simple change, result item will have unbreaking VI. With user defined limit of Unbreaking X, result item will have unbreaking VII.

Thank you for your time.

**Comment by RulerOfEternity** [comment]
@Leomelonseeds Can you please tell me what plugin that is? Thank you!

**Comment by Leomelonseeds** [comment]
Hey there, the plugin is called EnhancedEnchants, and the link is here: https://www.spigotmc.org/resources/enhancedenchants.87089/

Thanks!

**Comment by Insprill** [comment]
Added in the next update
