### ISSUE TITLE
White/Black scroll can't be applied on elytras

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#1898]
## Details

**Describe the bug**
White/Black scroll can't be applied on elytras.

**To Reproduce**
Take a white/black scroll and try applying it on an elytra.

**Screenshots / Video**
No need, it is self-explanatory.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/iripomijuk
- Server log: https://gist.github.com/Agaloth/2f67d4a5e0cee9516ba4bb33dce6e744

**Comment by GC-spigot** [comment]
Fixed for next update
