### ISSUE TITLE
BOOST_HORIZONTAL

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#1899]
BOOST is an effect that launches the entity upwards. I want to request a BOOST the launches the entity forward, that way we can create a cool enchant that lets players dash forward.

This can be a player only effect as PULL_AWAY and PUSH_AWAY basically do it with other entities but can't push or pull yourself.

**Comment by RulerOfEternity** [comment]
I wouldn't mind it working on mobs for fun or to demonstrate how it works on players.

**Comment by Insprill** [comment]
Added in the next update. Accepts `UP`, `DOWN`, `FORWARD`, and `BACKWARD`. Example: `BOOST:FORWARD:10`
