### ISSUE TITLE
Add non-living entities as an option for the 'GUARD' and 'CHANGE_ARROW' effects.

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1901]
## Request

**Description**
I'd like non-living entities such as fireballs, dragon fireballs, shulker bullets, etc, etc, etc..... to work with the GUARD and CHANGE_ARROW effects, also I'd like to see that some entities would not be shooting back at you with CHANGE_ARROW
**How the feature is useful**
It has powerful potential with entities such as fireballs.

**Comment by RulerOfEternity** [comment]
This would be great especially with this more recent suggestion: https://github.com/GC-spigot/AdvancedEnchantments/issues/1907

**Comment by Insprill** [comment]
CHANGE_ARROW already supports non-living entities. It supports everything [here](https://wiki.vg/Entity_metadata) except for paintings and XP orbs

**Comment by RulerOfEternity** [comment]
What I meant is, that it wouldn't shoot back at you for stuff like fireballs and skulls, i know the suggestion looked weird at first since i intended it to be for the GUARD effect at first

**Comment by RulerOfEternity** [comment]
Just the enchantment that doesn't shoot back in ur face, unless you're using a shield when blocking the enchantment.

**Comment by RulerOfEternity** [comment]
Closing thread and reopening it with a better explanation.
