### ISSUE TITLE
[Issue] Reforged not working along drunk type potion effects

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#1902]
## Details

**Describe the bug**
The bug is related to Reforged along with Strength type of potion effects. I only tried strength type of potion effect. Who knows if there's another potion effects affect to reforged. If you don't wear drunk 3 armor that strength type, reforged will work. But with drunk 3 armor your reforged will not work.

**To Reproduce**
So imagine u're wearing Drunk 3 armor which is strength type. And now you can test your sword reforged sword.  More details in the video:

**Screenshots / Video**
https://youtu.be/OFdlYiFBNwg

## Server Information
- Plugin Version: Pre23.7
- Server Version: 1.8.8 Paper 123

**Comment by Insprill** [comment]
I have no idea what you're trying to say. can you try to explain it better? the video doesn't help either. can you try to explain it in a more broad sense instead of enchant specific?

**Comment by Starkenz** [comment]
Reforged doesn't work along with drunk III enchantment.

**Comment by Insprill** [comment]
that still doesn't help at all. what is the drunk enchantment?

**Comment by Starkenz** [comment]
Drunk enchantment gives Strength potion effect. And Reforged enchantment protects your weapon, tool durability. But when u use drunk enchantment potion effect, reforged will not work.

**Comment by Starkenz** [comment]
Just /ae enchant drunk 3 or 4 on your helmet and wear it. Now test with your reforged sword with helmet and without armor to see difference.

**Comment by Insprill** [comment]
Is this still an issue on the latest version? If it is can you say what *effects* are conflicting?
