### ISSUE TITLE
[Issue] Infinite potion effect using hotkey operation

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#1903]
Describe the bug
EFFECT_STATIC type enchantments can be infinite. 

To Reproduce
You need item on your slot number 1. And you have to wear effect_static type enchantment(helmet). And now spam your 1 key which is item slot number 1. More info in video in description:
 
Screenshots / Video
https://youtu.be/H9mQTtYcIYU

Server Information
Plugin Version: Pre23.7
Server Version: 1.8.8 Paper 123

**Comment by LuluxClient** [comment]
Tried something similar and it's working for me : https://youtu.be/jiGbi_6mK3c

**Comment by Insprill** [comment]
Fixed for the next update
