### ISSUE TITLE
Make orbs able to have custom model data

### ISSUE THREAD

**Issue by bakaschwarz** [GC-spigot/AdvancedEnchantments#1906]
## Request

**Description**

It would be nice to be able to specify custom model data in addition to the material type inside the `config.yml` file
for the orb item. Items like the black scroll and mobtrak allow for such a customization, but the orb does not.

**How the feature is useful**

It adds another degree of freedom in the configurability of this plugin.
Server operators can make resource packs that can add even more immersion to the server.

It also adds more consistency to the configuration, since the other items can be set to custom model data.

Also i just want to add that you are doing a fantastic job! I just bought the plugin yesterday and was able to already achieve so much with it for my server! Thanks so much!

**Comment by Insprill** [comment]
Added in the next update
