### ISSUE TITLE
BOW enchantment type to modify entity data of projectile being shot

### ISSUE THREAD

**Issue by SocksBX** [GC-spigot/AdvancedEnchantments#1907]
## Request

**Description**

**A BOW Enchantment type that would allow outgoing projectiles to be modified to be separate entities.** 

The immediate thought here might be to shoot Fireworks or Splash Potions, but going one step further, it'd be pretty interesting to lob out entire mobs such as creepers, zombies, or skeletons.

**How the feature is useful**

This would directly benefit the creation of enchantments for myself and other creators, adding a new type of enchantment that's not currently possible with just Advanced Enchantments, to my knowledge. 

Allowing enchantments to modify outgoing projectiles adds a lot potential enchantments, shooting entire swarms of mobs at enemies, but also shooting Splash Potions of Water to clear out fire, or a more visually accurate Fireball enchantment.

Technically already possible using GUARD and a bit of creativity - but GUARD doesn't currently allow entities such as splash potions or snowballs, just mobs - and this only summons the mob **after** the arrow has hit a target. This enchantment would, ideally, **replace** the arrow entirely.

**Comment by RulerOfEternity** [comment]
I'd love to see that feature, I suggested non-living entities for the GUARD effect, perhaps both effects could be added at the same time.

**Comment by RulerOfEternity** [comment]
Also, an enderpearl arrow would be incredibly nice too!

**Comment by RulerOfEternity** [comment]
As much as I'd love to see the entity coming out instead of the arrow, if that isn't possible/easy to implement I wouldn't mind seeing it work after it hits the ground/entity.

**Comment by Insprill** [comment]
what do you guys think should happen when the arrow hit's the ground? should it turn back into a regular arrow, disappear, or just stay as the other entity till it despawns?

**Comment by RulerOfEternity** [comment]
I think it should stay as the other entity, also, can you please consider suggestion #1901 to implement it with this? It would be great to have non living entities as the GUARD type, it really has powerful potential with fireballs/dragon fireballs, etc.....

**Comment by SocksBX** [comment]
> what do you guys think should happen when the arrow hit's the ground? should it turn back into a regular arrow, disappear, or just stay as the other entity till it despawns?

Ideally it would stay as the other entity til it despawns/is killed if its a mob. For mobs like creepers, zombies, etc, a configurable respawn time could also be pretty useful.

**Comment by Insprill** [comment]
Added in the next update. `CHANGE_ARROW` - only works on 1.13+. Has 2 modes, changeable in the config.yml as `change-arrow-mode`. Mode 2 is the one you want to use to get the full effect, but it requires [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/). Format: `CHANGE_ARROW:[ENTITY]:(LAND ACTION):(PICKUP STATUS)` [] = required. () = optional. LAND ACTION can be `NOTHING`, `SUMMON`, or `REMOVE`. `NOTHING` will be exactly the same as a regular arrow, just looks different. `SUMMON` will summon the entity when the arrow lands/ hit's something. `REMOVE` will delete the arrow when it lands/ hits something. PICKUP STATUS can be `DISALLOWED`, `ALLOWED`, or `CREATIVE_ONLY`. This corresponds to if the player can pick up the arrow - pretty self-explanatory.
