### ISSUE TITLE
/ae giveitem tab completion is incorrect for orbs

### ISSUE THREAD

**Issue by Dezkrazzer** [GC-spigot/AdvancedEnchantments#1911]
## Details

**Describe the bug**
When I use the command **/ae giveitem DezkrazzeR orb 1 LEGENDARY 15 100** an error occurred

**To Reproduce**
Maybe the developer can fix this bug

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/43921327/116767985-b3ca6b80-aa5d-11eb-9507-1a1b70486f29.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/useliyaqux
- Server log: https://gist.github.com/Dezkrazzer/8296dcff17dda241dff66a7f25e798cb

**Comment by Insprill** [comment]
Fixed for the next update
