### ISSUE TITLE
Grinder & Item Drop Problem

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#1912]
## Details

**Describe the bug**
When you use the Grider, items fall right to the ground.

**To Reproduce**
It is reproduced by installing AdvancedEnchantments-8.0.0-Pre21.7 in the vanilla bukkit

**Screenshots / Video**
https://youtu.be/8QaIITKAAvA

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yimisuzilo
- Server log: https://gist.github.com/geumu/fcbb3ec6038a60dbf9f3d0e32c6d0401

**Comment by Insprill** [comment]
Does this happen with only AE on the server? i wasn't able to reproduce this

**Comment by geumu** [comment]
yes only AE

**Comment by Insprill** [comment]
can you send your server.properties, bukkit.yml, spigot.yml, and paper.yml? I can't get this to happen
