### ISSUE TITLE
Trench not working

### ISSUE THREAD

**Issue by gwrijasdf** [GC-spigot/AdvancedEnchantments#1914]
**Describe the bug**
trench enchant / effect not working (ver 8.0.1)

**To Reproduce**
/ae enchant trench 9 -> mining block

**Screenshots / Video**
none

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/olacudasun
- Server log: https://gist.github.com/gwrijasdf/73b195a003330ab39e48508e09a648b3

**Comment by Insprill** [comment]
Fixed for the next update
