### ISSUE TITLE
The 'HELD' type in the offhand resets the effect when moving across items in the hotbar

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1915]
## Details

**Describe the bug**
I made an enchantment where you get more hearts if you apply it on a specific item (In this case it's a Totem of Undying).
Whenever you move through the hotbar the hearts reset, even though you're holding it in the offhand where that shouldn't be an issue. Also, I have effect removal with /heal disabled, when it's enabled the hearts go away when I do /heal.

**To Reproduce**
Make a HELD enchantment with health boost and try it. I will try this with other effects and see if it has the same problem there as well, if it does or there's something I'd like to mention, I will mention it in the comments.

**Screenshots / Video**
https://youtu.be/txEXS3aVpUU

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/cilefaladu
- Server log:  https://gist.github.com/RulerOfEternity/3c22c614373f8a65f24c22206be34fdf

**Comment by Insprill** [comment]
Fixed for the next update
