### ISSUE TITLE
Bug with 'HELD' type

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1916]
## Details

**Describe the bug**
As I was experimenting with the last bug, I found an other bug! With the 'HELD' type. when you constantly put the item on and off of the offhand you can have the effect permanently even when not holding the item.

UPDATE: I found yet another bug, this one works with the number keys, see the third video for more details.

**To Reproduce**
Constantly take the item on and off of your main hand until the effect remains.

**Screenshots / Video**
1. https://youtu.be/4NBI82DTKaE
2. https://youtu.be/aR_Rzi-k_BE
3. https://youtu.be/SxIJzqo0Oe4

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/cilefaladu
- Server log:  https://gist.github.com/RulerOfEternity/24f99722451308430e0a6bbdab5d086f

**Comment by RulerOfEternity** [comment]
Current status as to what I know: The bug with the number keys is fixed, only the spam clicking on the offhand (presumably mainhand too? I haven't tried that yet), still works.

**Comment by Insprill** [comment]
Fixed in the next update
