### ISSUE TITLE
No effects are given when wear armor with "F" button (offhand)

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#1917]
## Details

**Describe the bug**
No effects are given when you wear armor with enchantments with "F" button (offhand)

**To Reproduce**
Enchant armor with some enchantments from AdvancedEnchantments plugin and try to wear that armor from offhand by "F" button

**Screenshots / Video**

https://user-images.githubusercontent.com/44753872/116787511-2151b880-aaad-11eb-8f40-a3f681f8de0e.mp4

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/apagaluqan

**Comment by Insprill** [comment]
Fixed in the next update
