### ISSUE TITLE
Can't use this item as a hat (netherite helmet)

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#1920]
## Details

**Describe the bug**
When trying to take helmet and place it in helmet slot in chat sending "Can't use this item as a hat"

**To Reproduce**
Enchant netherite helmet with any AdvancedEnchantments' enchantment (For example aquatic)

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/44753872/116792192-caa5a800-aac7-11eb-8b5c-76d2abc8b293.png)
![image](https://user-images.githubusercontent.com/44753872/116792218-ec9f2a80-aac7-11eb-8f17-0c550c00dc7c.png)

## Server Information
- "/ae plinfo" link: 
- Server log: 
Same as in https://github.com/GC-spigot/AdvancedEnchantments/issues/1917

**Comment by Insprill** [comment]
Not an issue with AE. That message isn't even from our plugin

**Comment by iBuseWinner** [comment]
Ah, it was because if CMI...
