### ISSUE TITLE
Duplication With Telepathy When use-experimental-block-breaking Set To True

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1921]
## Details

**Describe the bug**
You can duplicate torches, soul torches, redstone torches, signs, buttons, and levers with a pickaxe with Telepathy when use-`experimental-block-breaking` is set to true.

**To Reproduce**
1.) Set `experimental-block-breaking` to true
2.) Hold a pickaxe and do /ae enchant Telepathy 4
3.) Recreate one of the setups in the screenshots
4.) Mine the cobblestone with the pickaxe that has Telepathy

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/116794381-35d48780-aa92-11eb-9f68-395249edfdac.png)
![image](https://user-images.githubusercontent.com/29821149/116794389-3a00a500-aa92-11eb-9144-946a7fa0bf3a.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/anaxevowan
- Server log: https://gist.github.com/WhatsTheBadNews/8637593f1e70258a087119337489c3f4

**Comment by Insprill** [comment]
Fixed for the next update
