### ISSUE TITLE
Lantern And Soul Lantern Deletion With Telepathy When use-experimental-block-breaking Set To True

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1922]
## Details

**Describe the bug**
When you mine a block under a Lantern or Soul Lantern using a pickaxe with Telepathy (when `experimental-block-breaking` is set to true), the Lantern or Soul Lantern gets deleted instead of dropped. 

**To Reproduce**
1.) Set `experimental-block-breaking` to true
2.) Hold a pickaxe and do /ae enchant Telepathy 4
3.) Recreate one of the setups in the screenshot
4.) Mine the cobblestone with the pickaxe that has Telepathy

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/116794568-84ceec80-aa93-11eb-92ba-36c685d33cc6.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/anaxevowan
- Server log: https://gist.github.com/WhatsTheBadNews/8637593f1e70258a087119337489c3f4

**Comment by Insprill** [comment]
Fixed for the next update
