### ISSUE TITLE
Head Duplication With Telepathy When use-experimental-block-breaking Set To True

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1923]
## Details

**Describe the bug**
When `use-experimental-block-breaking` is set to true, you can duplicate player heads by mining block behind them with a tool that has Telepathy.

**To Reproduce**
1.) Set `experimental-block-breaking` to true
2.) Hold a pickaxe and do /ae enchant Telepathy 4
3.) Recreate one of the setups in the screenshot
4.) Mine the cobblestone with the pickaxe that has Telepathy

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/116794743-0410f000-aa95-11eb-80b4-89218bc25dca.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/anaxevowan
- Server log: https://gist.github.com/WhatsTheBadNews/8637593f1e70258a087119337489c3f4

**Comment by Insprill** [comment]
Fixed for the next update
