### ISSUE TITLE
Shield Effect Reflection

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1924]
## Request

**Description**
I'd love to see a way that allows for an effect to be reflected when you block attacks with a shield, for example, if you have a shield with an enchantment that allows for say 'Instant Damage' to effect the attacker when they attack while you're blocking with the shield, that would be great.

**How the feature is useful**
This enchantment provides new opportunities for PvP experiences.

**Comment by MamboTND** [comment]
I'd say make the type say

type: 'SHIELD_BLOCK'

Make the enchant trigger if the player blocks dmg with the shield.

**Comment by RulerOfEternity** [comment]
> I'd say make the type say
> 
> type: 'SHIELD_BLOCK'
> 
> Make the enchant trigger if the player blocks dmg with the shield.

Yes that's what I meant exactly.

**Comment by SocksBX** [comment]
An effect that reverses %attacker% and %victim% in an enchantment could offer the same and be really versatile. Just throw this on a shield when its held in main-hand. It would be really cool, I'm all for it.

**Comment by RulerOfEternity** [comment]
> An effect that reverses %attacker% and %victim% in an enchantment could offer the same and be really versatile. Just throw this on a shield when its held in main-hand. It would be really cool, I'm all for it.

And OffHand too

**Comment by Insprill** [comment]
Added in the next beta update :)
