### ISSUE TITLE
TAKE_AWAY bug

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#1927]
**Describe the bug**
TAKE_AWAY removes items from all inventory slots.

**To Reproduce**
Enchants being used:
dash:
  levels:
    1:
      condition: '%player_item_in_offhand% = COAL : %allow%'
      cooldown: 2
      effects:
        - 'CONSOLE_COMMAND:clear %attacker name% coal 1'
     
jetpack:
    1:
      condition: '%player_item_in_offhand% = COAL : %allow%'
      cooldown: 6
      effects:
        - 'TAKE_AWAY:COAL:1'

**Screenshots / Video**
https://youtu.be/OmVRcAtr93o

## Server Information
- Plugin: AE 8.0.1
- Server: paper-1.16.5-457

**Comment by SocksBX** [comment]
In the mean time, you could also use - 'SERVER_COMMAND:clear %attacker_name% coal 1' for the same effect, though this executes it as a command

**Comment by Insprill** [comment]
Fixed for the next update
