### ISSUE TITLE
Enchant Cooldown Message 

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1928]
## Request

**Description**

When an enchant is on cooldown each time you try using it, it will send you a message displaying your cooldown.
**How the feature is useful**

This feature are really useful for enchants that has a cooldown and you have no way to track your cooldown since for some enchants you need to spam right click or take fall damage etc... but no way to see your cooldown, for such an old product it's weird to not have this. 
You can add a config where it can display the cooldown on some specific things : 

CooldownMessageApplyOn: 
- RIGHT_CLICK
- LEFT_CLICK
- FALL_DAMAGE
- etc...

CooldownMessage: 
- "&m------------------------------------"
- "You're in cooldown for %seconds% on %enchantname%"
- "&m------------------------------------"
- "" etc...

**Comment by ProfessionalBoatDrifter** [comment]
To add to this feature request (which really needs to happen), players should get a message when the enchantment is off cooldown either in chat or actionbar IMO.

Example of the ready message:
`[enchant] is ready!`

Right now I've created my own cooldown notifications using `WAIT:ticks` and `MESSAGE:message` which is just ridiculous in hindsight.
Out of the requested features I've seen, this should definitely be the top priority.
