### ISSUE TITLE
Integrate with AngelChest to fix dupes

### ISSUE THREAD

**Issue by denisdnu** [GC-spigot/AdvancedEnchantments#1930]
## Request

**Description**
When a player has an item with enchantment, that saves it after death with some chance < 100%, there is a dupe chance because AngelChest also saves items after death. AngelChest has blacklist.yml that allows filtering items by name, lore, and enchantment name, but it will create a dupe in case of enchantment failure.
The inventory contents of an AngelChest can be changed using this event: 
https://github.com/JEFF-Media-GbR/AngelChestAPI/blob/master/src/main/java/de/jeff_media/angelchest/events/AngelChestSpawnEvent.java

**How the feature is useful**
A player will be able to use AngelChest plugin with Advanced Enchants without dupe issue

**Comment by Insprill** [comment]
If AngelCheat already saves items after death, can't you just remove the enchant that does the same?

**Comment by denisdnu** [comment]
AngelChest saves items, but it can be configured to withdraw money for tp and opening chest so if the player doesn't have enough, he will lose all items. I want the enchanted item to be saved.

**Comment by Insprill** [comment]
This has been fixed on their end
