### ISSUE TITLE
Kill Tracker - Similar to block tracker and mob tracker

### ISSUE THREAD

**Issue by Pudiaz** [GC-spigot/AdvancedEnchantments#1931]
## Request

**Description**
An item like the block tracker that counts the kills (players) you have on the certain weapon

**How the feature is useful**
Players have been asking for some type of kill counter, similar to csgo's stat track which counts the amount of kills you have on a weapon.

**Comment by LuluxClient** [comment]
Already has this feature

**Comment by Insprill** [comment]
This is what the StatTrack does
