### ISSUE TITLE
ClueScroll compatibility

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#1932]
## Request

**Description**
Hi. Please can you add compatibility for ClueScrolls plugin? 
https://www.spigotmc.org/resources/%E2%AD%90-cluescrolls-%E2%AD%90-%E2%95%91-1-8-to-1-16-x-250-clue-types-new-default-config-rewards.30276/

**How the feature is useful**
When player has quest to mine blocks he trying to mine with detonate but blocks isn't counting (count only blocks which you break)

(Sorry for my english)

**Comment by Insprill** [comment]
Try enabling experimental block breaking

**Comment by iBuseWinner** [comment]
Already enabled on the advice from my old issues

![image](https://user-images.githubusercontent.com/44753872/117059634-af85a300-ad28-11eb-9e6d-24be51a6be99.png)

**Comment by iBuseWinner** [comment]
@Insprill ?

**Comment by Insprill** [comment]
While direct support won't be added, experimental-block-breaking has had loads of changes since this and should be fully compatible with all plugins so I'm marking this as accepted.
