### ISSUE TITLE
FALL_DAMAGE class cast exception

### ISSUE THREAD

**Issue by n0tailz-debug** [GC-spigot/AdvancedEnchantments#1933]
## Details

**Describe the bug**
A ClassCastException (EntityDamageEvent -> EntityDamageByEntityEvent) is thrown when falling without taking damage. Error: https://paste.insprill.net/ocebotaquj

**To Reproduce**
This happens when i fall from a high place then land without taking damage

**Screenshots / Video**
https://user-images.githubusercontent.com/78484864/117000097-2152f200-ad13-11eb-9d95-9e58c57393b8.PNG

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/asaxebocap
- Server log: https://gist.github.com/n0tailz-debug/dfc7a0ca7821635bdcbc7dc5dad4de74

**Comment by RulerOfEternity** [comment]
Try to update the plugin, you seem to be running a rather outdated version.

**Comment by Insprill** [comment]
Fixed for the next update
