### ISSUE TITLE
MORE_DROPS not working on KILL and DEATH types

### ISSUE THREAD

**Issue by zestym3m3s** [GC-spigot/AdvancedEnchantments#1934]
![Diploid](https://user-images.githubusercontent.com/83251038/117055335-09667880-ace9-11eb-99b9-26c8beb3b6c2.JPG)
**Describe the bug**
Diploid doesn't drop items from monsters.

**To Reproduce**
Enchant a sword with diploid, give it a soul tracker, add some souls and kill any monster. Even though it uses the souls and activates the enchant it doesn't drop any extra items. I've tried to add %victim% and %attacker% and specify the mobtype but nothing works. 

**Screenshots / Video**
I linked a picture of my config as I last tested it. I also spoke with Mambo and he confirmed the issue on his own personal world, so I think its just an issue with how its been programmed.

**Comment by Insprill** [comment]
*note to myself* RE:448 check against EntityDamageEvent
