### ISSUE TITLE
New 1.13 not working enchantments list after 4.8.0

### ISSUE THREAD

**Issue by DaveTheCamper** [GC-spigot/AdvancedEnchantments#194]
I make a new tests after update 4.8.0 and don't know why closed my last issue...

List of enchantments that work or not at 1.13

Dimish -> working on 1.13
deathgod -> working on 1.13
Rage -> working on 1.13
Drunk -> working on 1.13
Obsidian shield -> working on 1.13
Guardian -> working on 1.13
Stormcaller -> working on 1.13
Endershift -> working on 1.13
Glowing -> working on 1.13
Aquatic -> working on 1.13
Curse -> working on 1.13
antigravity -> working on 1.13
springs -> working on 1.13
Undead Ruse -> working on 1.13
Poisoned -> working on 1.13
Reforged -> works like unbreaking
Cactus -> working on 1.13
Frozen -> working on 1.13
Voodoo -> working on 1.13
Wither -> working on 1.13
Shockwave -> working on 1.13
Smebomb-> working on 1.13
Rocket escape -> working on 1.13
Dodge -> working on 1.13
Block -> working on 1.13
Ragdoll -> working on 1.13
Etheraldodge -> working on 1.13
planetary dethbringer -> working on 1.13
godly overload -> working on 1.13
vengefull dimish -> working on 1.13
deathgod -> working on 1.13
alien implants -> working on 1.13
Oxygenate -> working on 1.13
shackle -> working on 1.13
decapitation -> working on 1.13
headless -> working on 1.13
vengefuldiminish -> working on 1.13
 
 
 
====================================================================
obliterate -> working but sending messege on chat "5, 1" (enchantment level 5)
 
epicness -> not working and send error on console
[21:14:14 INFO]: [AdvancedEnchantments] Failed to show 'LARGE_SMOKE' particle
[21:14:14 INFO]: [AdvancedEnchantments] Couldn't match a sound with name 'GHAST_SCREAM'
 
execute -> working but spam chat with messages like    "6 > 6 : %stop%"    "8 > 6 : %stop%"    "5, 4"
 
farcast -> working but spam chat with messages like
"DIAMOND_SWORD contains SWORD or DIAMOND_SWORD contains AXE : %allow%"
"10 < 6 : %chance%+6"
"5, 2"
 
Greatsword -> working but spam chat with messages like "BOW contains BOW : %allow%"   "5, 5"
 
longbow -> working but spam chat with messages like "BOW = BOW : %allow%"   "5, 5"
 
deathbringer -> working but sending messege on chat "5, 5"
 
rage -> working but sending messege on chat "5 > 5 : %stop%"
 
planetarydeathbringer -> working but sending messege on chat "5, 5"
 
rocketescape  -> working but sending messege on chat "3 > 6 : %stop%"
 
arrowdeflect -> working but sending messege on chat "5, 1"   "5, 2"   "5, 3"
 
Tank -> does't work on 1.13
 
Valor -> working but sending messege on chat "DIAMOND_SWORD contains SWORD : %allow%"
 
Armored -> does't work on 1.13 but spam chat with "DIAMOND_SWORD contains SWORD : %allow%'
 
 
 
====================================================================
 
Trap -> does't work on 1.13
Demon -> does't work on 1.13
Snare -> does't work on 1.13
infernal -> does't work on 1.13
Pummel -> does't work on 1.13
Vampire -> does't work on 1.13
Hardened -> does't work on 1.13
Angelic -> does't work on 1.13
Trickster -> does't work on 1.13
Hijack -> does't work on 1.13
arrow lifesteel -> does't work on 1.13
Arrow break -> does't work on 1.13
Blessed -> does't work on 1.13
Marksman -> does't work on 1.13
Detonate -> does't work on 1.13
Enrage -> does't work on 1.13
Ice aspect -> does't work on 1.13
Implants -> does't work on 1.13
Ender walker -> does't work on 1.13
heavy -> does't work on 1.13
Disintegrate -> does't work on 1.13
Dominate -> does't work on 1.13
Hellfire -> does't work on 1.13
Piercing -> does't work on 1.13
Eagleeye -> does't work on 1.13
Barbarian -> does't work on 1.13
Bleed -> does't work on 1.13
Metaphysical -> does't work on 1.13
Clarity -> does't work on 1.13
Pacify -> does't work on 1.13
Unfocus -> does't work on 1.13
Spirit -> does't work on 1.13
Valor -> does't work on 1.13
Lifesteel -> does't work on 1.13
Enlighted -> does't work on 1.13
DoubleStrike -> does't work on 1.13
Inversion -> does't work on 1.13
Inquisitive -> does't work on 1.13
disarmour -> does't work on 1.13
devour -> does't work on 1.13
Sniper -> does't work on 1.13
Blacksmith -> does't work on 1.13
Insanity -> does't work on 1.13
master blacksmith -> does't work on 1.13
master inquisitive -> does't work on 1.13
Divine enlighted -> does't work on 1.13
Lethal Sniper -> does't work on 1.13
phoenix -> does't work on 1.13
paladinarmored -> does't work on 1.13
demonic lifesteel -> does't work on 1.13
Nathures wrath -> does't work on 1.13
divineimmolation -> does't work on 1.13
obsidiandestroyer -> does't work on 1.13
atomicdetonate -> does't work on 1.13
masterblacksmith -> send message but does't work on 1.13

**Comment by N3kas** [comment]
I'll work through 1.13 enchant fixes shortly. It's very complicated system to make them work on 4 year old version and latest one.
