### ISSUE TITLE
Stairs isn't breaking with TRENCH effect

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#1941]
## Details

**Describe the bug**
When breaking stairs (any) they don't break with TRENCH effect (detonate, atomicdetonate).
use-experimental-block-breaking: true
trench-blacklist:
  - AIR
  - BEDROCK
  - LAVA
  - WATER
  - STATIONARY_LAVA
  - STATIONARY_WATER
  - SPAWNER
  - PORTAL
  - SHULKER_BOX
  - air
  - shulker
  - WHITE_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - RED_SHULKER_BOX
  - PINK_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIME_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - END_PORTAL
  - END_PORTAL_FRAME
  - ENDER_PORTAL_FRAME
  - BARRIER

**To Reproduce**
Enchant any pickaxe with enchantment (*TRENCH* effect) and try to break stairs.

**Screenshots / Video**
https://youtu.be/L9Hc5I8UK04

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ekecelikiv

**Comment by Insprill** [comment]
Update AE
