### ISSUE TITLE
Placeholder not translating and showing wrong enchant

### ISSUE THREAD

**Issue by n0tailz-debug** [GC-spigot/AdvancedEnchantments#1942]
## Details

**Describe the bug**

**To Reproduce**

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/unanakizeg
- Server log: https://gist.github.com/n0tailz-debug/a80955902f0f513821d13159da9015ad

**Comment by Oukaa** [comment]
yeah same me too, how to fix it

**Comment by larssieboy18** [comment]
I can confirm this happens. Updating to the latest version (v 8.0.5) seemed to fix it, until server restart.
