### ISSUE TITLE
SHIFT enchant permanently applies Potion Effects, rather than only when crouching.

### ISSUE THREAD

**Issue by SocksBX** [GC-spigot/AdvancedEnchantments#1946]
## Details

**Describe the bug**
I have several Enchants that grant potion effects only while holding SHIFT. These worked until very recently, when I updated to the most recent version.

**To Reproduce**
Create an enchant that applies a potion effect when holding shift. Example:

hoppy:
  display: '%group-color%Hoppy'
  description: "Jump boost if Sneaking."
  applies-to: 'Armor'
  type: 'SHIFT'
  group: 'ULTIMATE'
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 100
      cooldown: 0
      effects:
        - 'POTION_OVERRIDE:JUMP_BOOST:5'
        - 'PLAY_SOUND:ENTITY_RABBIT_JUMP'

**Screenshots / Video**

## Server Information
https://paste.md-5.net/yelocibiju
https://gist.github.com/SocksBX/5c7621a013485b062d6a811a97494e99

**Comment by Insprill** [comment]
Fixed for the next update
