### ISSUE TITLE
Enchantment confliction

### ISSUE THREAD

**Issue by Adveragejoe** [GC-spigot/AdvancedEnchantments#1947]
## Details

**Describe the bug**
When you Make an enchantment using the 'vein_mine' effect and another enchantment using the 'smelt' effect, and apply both enchantments to the same tool, the smelt still works but the vein_mine effect doesnt work.

**To Reproduce**
Create an enchantment for pickaxes with the type being mining and the effect being smelt. then make another enchantment with the type being mining and the effect being vein_mine. (ex. https://pastebin.com/U5ApZa6K) Then apply them both to the same pickaxe and try to mine a ore vein.

**Screenshots / Video**
https://drive.google.com/file/d/1f5pPpH8XhL4Srs9oqlkD3Z9d6mRVs0le/view?usp=sharing

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/esixinirox
- Server log: https://gist.github.com/Adveragejoe/56465c72db4a0517fe48859736231107

**Comment by Insprill** [comment]
Try on the latest version. It works perfectly fine for me on Paper-671 1.16.5
