### ISSUE TITLE
Duplicate 2 tall blocks with Telepathy when use-experimental-block-breaking is set to true

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1948]
## Details

**Describe the bug**
You can duplicate 2 tall blocks by mining the lower part of the block with Telepathy when `use-experimental-block-breaking` is set to true.

**To Reproduce**
1.) Set `use-experimental-block-breaking` to true
2.) Hold a pickaxe and do /ae enchant telepathy 4
3.) Use the pickaxe to mine the part of the block circled in the screenshot below

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/118142400-f54d0600-b3cf-11eb-9e65-9655ae2fcc1b.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/muxogowoso
- Server log: https://gist.github.com/WhatsTheBadNews/c8c477aa8d442e62bf79af04be73a21a

**Comment by Insprill** [comment]
Fixed for the next update
