### ISSUE TITLE
Carpet deleted when using tool with Telepathy to mine the block under it when use-experimental-block-breaking is set to true

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1949]
## Details

**Describe the bug**
When you are using a pickaxe with Telepathy and use-experimental-block-breaking is set to true, if you mine the block under a carpet, the carpet will get deleted.

**To Reproduce**
1.) Set use-experimental-block-breaking to true
2.) Hold a pickaxe and do /ae enchant telepathy 4
3.) Recreate the setup in the screenshot, and use the pickaxe to mine the block (circled in the screenshot) under the carpet

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/118143461-fcc0df00-b3d0-11eb-97ae-9580344f04f0.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/muxogowoso
- Server log: https://gist.github.com/WhatsTheBadNews/c8c477aa8d442e62bf79af04be73a21a

**Comment by Insprill** [comment]
Fixed for the next update
