### ISSUE TITLE
right-click-to-view-enchants: false not working

### ISSUE THREAD

**Issue by Thefluffypvper1** [GC-spigot/AdvancedEnchantments#1951]
**Describe the bug**
The "right-click-to-view-enchants: false" doesn't work, I set it to false and you can still right click books

## Server Information
https://paste.md-5.net/axaxuzovih

https://gist.github.com/Thefluffypvper1/145161ee7da0c1d233774631257aae58

**Comment by Insprill** [comment]
The setting toggles right-clicking books in the enchanter to see all enchants in that group. The setting works fine. Make sure you fully restart your server for the changes to apply.
