### ISSUE TITLE
Bell deleted when using tool with Telepathy to mine the block supporting it when use-experimental-block-breaking is set to true

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1952]
## Details

**Describe the bug**
When you are using a pickaxe with Telepathy and `use-experimental-block-breaking` is set to true, if you mine the block supporting a bell, the bell will get deleted.

**To Reproduce**
1.) Set `use-experimental-block-breaking` to true
2.) Hold a pickaxe and do /ae enchant telepathy 4
3.) Recreate one of the setups in the screenshot, and use the pickaxe to mine one of the circled blocks

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/118267856-3f8ebf80-b482-11eb-9d6b-1ded9ecdde66.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/terewofiwa
- Server log: https://gist.github.com/WhatsTheBadNews/d4256ddfa7d5bae1bad12b4ca66d1842

**Comment by Insprill** [comment]
Fixed for the next update
