### ISSUE TITLE
TRENCH:3 mines 18 block instead of 27

### ISSUE THREAD

**Issue by poityTMK** [GC-spigot/AdvancedEnchantments#1953]
In game problem.

The TRENCH effect with for example int = 3, so it should dig 27 blocks at a time, instead it always digs 18.

To reproduce the problem just apply an enchant that has the effect TRENCH to a tool.

No console or game errors.

**Comment by Insprill** [comment]
Works fine for me. What anti-cheat do you use? most likely a conflict with that.

**Comment by poityTMK** [comment]
I don't use any, digging with TRENCH: 3 a wall of blocks only digs 18 because it considers the block you dug the absolute center of the 3x3 cube, so it also digs out the air. I see if I can attach a video.

**Comment by poityTMK** [comment]
Here's the video

https://user-images.githubusercontent.com/44748641/118313991-caf46900-b4f3-11eb-8cf7-874721f7bf15.mp4

**Comment by poityTMK** [comment]
> Works fine for me. What anti-cheat do you use? most likely a conflict with that.

I attached the video showing the problem

**Comment by Insprill** [comment]
Thats exactly how its supposed to work. The block you break is the center of the cube
