### ISSUE TITLE
CompatNoCheatPlus Compatibility

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#1955]
## Request

**Description**
Compatibility with the CompatNoCheatPlus plugin. See #1938 

**How the feature is useful**
Would allow for advanced enchantments to work on servers running NoCheatPlus and mcMMO. Currently, either the custom enchants don't work, or mcMMO abilities don't work.

**Comment by Insprill** [comment]
Would you mind sending your cncp & ncp configs? I want to add this however I can't reproduce the original issue. You can join our [Discord Server](https://discord.gg/GzdQdMw) and create a ticket and send the files there if you don't want to send them publicly.

**Comment by Dakotaa** [comment]
NCP: https://pastebin.com/VHJ0DJsC
CNCP: https://pastebin.com/1nure8dM

**Comment by Insprill** [comment]
Alright, I wasn't able to get it to stop me from breaking blocks but in theory, support should be added. If it doesn't work just respond here and I'll take another look at it.

**Comment by Dakotaa** [comment]
I still seem to be having the same issue. Which version of ncp and cncp did you get it working with?
