### ISSUE TITLE
MORE_DROPS does not work with MINING

### ISSUE THREAD

**Issue by poityTMK** [GC-spigot/AdvancedEnchantments#1956]
**Describe the bug**
the MORE_DROPS effect does not multiply the dug blocks and when it should activate it does not even give you the block you just dug

**To Reproduce**
to reproduce the bug just apply any spell that has the effect of MORE_DROPS to the pickaxe and start digging (not hand placed blocks, if hand placed it will drop the block you placed but doesn't multiply anything).

https://user-images.githubusercontent.com/44748641/118529001-4dbf3300-b743-11eb-8d7e-ecb43760f9a5.mp4

This is the configuration of the level
fortuna5:
  display: '%group-color%Fortuna V'
  description: "Hai una chance di duplicare il blocco\nche hai appena scavato."
  applies-to: 'Piccone'
  type: 'MINING'
  settings:  
    required-enchants:
      - 'fortuna4:1'
    removed-enchants:
      - 'fortuna4'
    removeable: true
    not-applyable-with:
      - 'efortuna1'
      - 'efortuna2'
      - 'efortuna3'
      - 'efortuna4'
      - 'efortuna5'
  group: 'LEGENDARY'
  applies:
    - ALL_PICKAXE
  levels:
    1:
      chance: 100
      effects:
        - 'MORE_DROPS:2'

**Comment by Insprill** [comment]
Does enabling/ disabling experimental block breaking have any effect on this?

**Comment by poityTMK** [comment]
> Does enabling/ disabling experimental block breaking have any effect on this?

ok, with that option enabled it works

**Comment by Insprill** [comment]
Fixed in the next update
