### ISSUE TITLE
Restore does not work with TRENCH Enchantments

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#1959]
## Details

**Describe the bug**
When an item with a TRENCH enchantment breaks while mining, the Restore enchantment does not work, and the item just breaks (even with 100% restore chance). Restore works fine on tools without TRENCH.

**To Reproduce**
Enchant a pickaxe with restore, and a TRENCH enchantment. Use the pickaxe until it breaks. The pickaxe will break and the Restore effects will not be triggered.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ugahevasan

**Comment by Insprill** [comment]
Fixed in the next update
