### ISSUE TITLE
BlackScroll issue.

### ISSUE THREAD

**Issue by AbrahamOfficial** [GC-spigot/AdvancedEnchantments#196]
Hello there,

I am a bit confused as to why the blackscroll is not working correctly.

Here is the Item i created.

  black-scroll:
    type: INK_SACK
    id: 0
    name: '&c&nBlack Scroll'
    lore:
    - '&7Removes a random enchantment'
    - '&7from an item and converts'
    - '&7it into a &c&n%success%%&7 success book.'
    - '&7o((&c&oTIP: &7&oPlace scroll onto item to extract.))'
    success: 95
    destroy: 5
    random: true

i have placed it through a YAML Parser and it says its fine. Every time i do the command "/ae giveitem AbrahamOfficial blackscroll 1" it says an internal error has occurred while attempting this command. I have checked CONSOLE and straight after i do the command it says ERROR: null (Image of Error in console: https://gyazo.com/2953755ff58bfa31e16370e18a5d573c?token=d6359c10e4fa79334f0dddb857699724 ) 

I hope you can get back to me soon.

Kind Regards,
AbrahamOfficial

**Comment by UnrealisticBeing** [comment]
I receive this too, here's my error:
https://pastebin.com/b7N1rrWc

**Comment by N3kas** [comment]
I'll add a message next update to pop-up which helps with this. Currently the command to give blackscrolls requires chances at the end of it, like this:
`/ae giveitem AbrahamOfficial blackscroll 1 100`
@UnrealisticBeing same in your situation.

**Comment by AbrahamOfficial** [comment]
Hello,
I have just tried the command and it sadly doesn't work. Still the same error message.

Current version: 4.6.3

**Comment by N3kas** [comment]
Testing that version. It worked just fine: http://prntscr.com/lgtj7t
/ae giveitem GC blackscroll 1 100

**Comment by UnrealisticBeing** [comment]
Worked for me @N3kas, thanks!
