### ISSUE TITLE
EFFECT_STATIC Enchants persist after removing them using black scrolls.

### ISSUE THREAD

**Issue by dm1lk** [GC-spigot/AdvancedEnchantments#1960]
## Details

**Describe the bug**
When using black scrolls to remove EFFECT_STATIC enchantments while wearing the item, the effect will remain until the server reboots. The best example of this being lava walker.

**To Reproduce**
1. Put lava walker onto your boots.
2. Equip the boots.
3. Use a black scroll on the boots while wearing them.
4. You can still walk on lava, even if you log out and back in.

**Screenshots / Video**
https://user-images.githubusercontent.com/77703500/118689382-d6e77000-b7fe-11eb-9bf9-4e7f05a2145d.mp4

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ciyalalani

- Server log: https://gist.github.com/dm1lk/8be0bb897af338e0ebcf082b1d18ffb4

**Comment by Insprill** [comment]
Fixed for the next update
