### ISSUE TITLE
TP_DROPS does not work with Fortune on crops

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#1961]
## Details

**Describe the bug**
When harvesting crops with a TP_DROPS enchantment, the number of drops are not increased by fortune. When harvesting with a tool with just fortune and no TP_DROPS enchantment, the drop numbers are fine. This seems to be with just crops so far, as mining ores with a TP_DROPS/Fortune pickaxe gives the correct increased amount.

**To Reproduce**
Enchant an axe with fortune 3 and a TP_DROPS enchantment. Farm any crops, such as cocoa beans. The number of drops will be the same as they are when farming with the same tool, but without fortune 3.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/acodekuger

**Comment by Insprill** [comment]
Can you try on a regular Paper server, and with only AE? I wasn't able to reproduce this on the latest version
