### ISSUE TITLE
Can't open rcbook if someone opened your inv with [CMI]

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#1963]
## Details

**Describe the bug**
When someone seeing your inventory (/inv nick) and when you trying to open rc book it shoot firework and send a chat message but you don't get this book and rc book didn't clear.

**To Reproduce**
Open player's inventory with CMI /inv [playerName]
Player need to use rc books
Books don't use

**Screenshots / Video**
https://youtu.be/hzG92vG9q2s

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/romilarizo
- Server log: Not needed

**Comment by Insprill** [comment]
This is an issue with CMI. Report it to them
