### ISSUE TITLE
Condition bug report

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1964]
## Details

**Describe the bug**

The condition" %victim name% = %attacker name% : %STOP%'" isn't working. I'm trying to make it so people who bows themselfs won't receive the effect from the bow (for example slow effect) 
**To Reproduce**

Enchant : 
    1:
      chance: 100
      cooldown: 0
      condition:
        - '%victim name% = %attacker name% : %STOP%'
      effects:
        - 'DOUBLE_DAMAGE %victim%'
        - 'POTION:SLOW:4:80 %victim%'   
        - 'MESSAGE:&f&l*** &c&lSlowness V ON &f&l*** %victim %attacker%'

**Screenshots / Video**

Don't need

## Server Information
plugin ver : 8.1.0
Server version : TacoSpigot 1.8.8

**Comment by Insprill** [comment]
Works fine for me. Can you send the entire enchant you're trying to use?
