### ISSUE TITLE
Make the %mob type% Condition work with BOW_MOB 

### ISSUE THREAD

**Issue by Maroon28** [GC-spigot/AdvancedEnchantments#1965]
## Request

**Description**
Essentially, putting %mob type% in an enchantment that uses BOW_MOB doesn't work, and it seems to only be working for KILL_MOB and ATTACK_MOB. 

**How the feature is useful**

It makes the plugin overall a lot more versatile. For example, on my server I've come up with a 'grappling hook' sort of enchantment. The main issue here is that you can shoot OP bosses like the ender dragon/wither and completely humiliate them. It would've been ideal to use something like `%mob type% = ENDER_DRAGON : %stop%` to fix this issue, but sadly it doesn't work.

**Comment by Insprill** [comment]
This already exists and I just tested it and it works on 1.8-1.16.5. You most likely wrote the condition wrong. You can join our [Discord Server](https://discord.gg/GzdQdMw) for help on creating effects.
