### ISSUE TITLE
Tinkerer for %player% bug

### ISSUE THREAD

**Issue by Eur0x** [GC-spigot/AdvancedEnchantments#1966]
## Details

**Describe the bug**
copying items for the command "/ae open %player% tinkerer"

**To Reproduce**
use command " /ae open %player% tinkerer" -> put items to GUI -> close GUI -> open GUI again -> and this way you can copy items

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/64858671/118784960-b2d46f00-b890-11eb-8e51-8d6818f29d78.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/bugicinora
- Server log: no needed / empty

**Comment by Insprill** [comment]
Fixed in the next update
