### ISSUE TITLE
bow-full-power: true not working

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1967]
## Details

**Describe the bug**

The feature bow-full-power: true isn't working in the config
**To Reproduce**

Enable this in the config : bow-full-power: true and it won't work
**Screenshots / Video**

don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
Server ver : 1.8.8 TacoSpigot 
Pl ver : 8.0.6

**Comment by Insprill** [comment]
Fixed for the next update
