### ISSUE TITLE
Enchants no longer working (error)

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1968]
## Details

**Describe the bug**

When I updated the plugin my enchantements are no longer working and I'm getting this error : https://pastebin.com/uF3nsvH2
**To Reproduce**

Place the latest update instead of the 8.0.6 (working ver) 
**Screenshots / Video**

https://pastebin.com/uF3nsvH2 

## Server Information
- "/ae plinfo" link: 
- Server log:

**Comment by Insprill** [comment]
Fixed for the next update
