### ISSUE TITLE
Blocks deleted when supporting block mined with Telepathy (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1969]
## Details

**Describe the bug**
Similar to #1922 and #1949 but with different blocks.

When you are using a pickaxe with Telepathy and `use-experimental-block-breaking` is set to true, if you mine the block under a listed block, the listed block will be deleted.

- Sweet Berries
- Dandelion
- Poppy
- Sea Pickle
- Mushroom (Both Types)
- Fungus (BothTypes)
- Sapling (All Types)

**To Reproduce**
1.) Set `use-experimental-block-breaking` to true
2.) Hold a pickaxe and do /ae enchant telepathy 4
3.) Recreate the setup in the screenshot, and use the pickaxe to mine the blocks circled in the screenshot

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/118898033-429a0d80-b8d1-11eb-8d5b-bf804c2addd5.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/demupufuso
- Server log: https://gist.github.com/WhatsTheBadNews/7249981a99495c78bed0c0a8d34d071e

**Comment by Insprill** [comment]
Fixed in the next update
