### ISSUE TITLE
Buttons/levers deleted when placed in certain orientation and supporting block mined with Telepathy (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1970]
## Details

**Describe the bug**
When you are using a pickaxe with Telepathy and `use-experimental-block-breaking` is set to true, if you mine the block that is supporting a button/lever (in certain orientations) the button/lever will be deleted.

**To Reproduce**
1.) Set `use-experimental-block-breaking` to true
2.) Hold a pickaxe and do /ae enchant telepathy 4
3.) Recreate the setup in the screenshot, and use the pickaxe to mine the blocks circled in the screenshot

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/118898354-f6030200-b8d1-11eb-8ad0-806e702de677.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/demupufuso
- Server log: https://gist.github.com/WhatsTheBadNews/7249981a99495c78bed0c0a8d34d071e

**Comment by Insprill** [comment]
Fixed in 8.1.7
