### ISSUE TITLE
Telepathy and fortune not working together (for the 5th time...)

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#1971]
## Details

**Describe the bug**

Fortune and telepathy doesn't work together

**To Reproduce**

Grab an axe enchanted with telepathy and fortune 3 and you will only get the drops if you were not using fortune 3
**Screenshots / Video**

Don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
Server ver : 1.8.8 taco
Plugin ver : 8.0.6

Experimental block breaking : True / false

**Comment by Insprill** [comment]
Is this still an issue on the latest version? i wasn't able to reproduce it

**Comment by LuluxClient** [comment]
> Is this still an issue on the latest version? i wasn't able to reproduce it

Fixed in latest
