### ISSUE TITLE
8.1.1 Won't enable on server 

### ISSUE THREAD

**Issue by Artfulspy** [GC-spigot/AdvancedEnchantments#1972]
## Details

**Describe the bug**
Added to PaperSpigot 1.16.5, when ever I do an Associated command such as /ae or /ae enchant it appears as 'An Internal Error occurred While attempting to perform this command' it also appears as de-activated in /plugins

**To Reproduce**
Type /ae or any other advanced Enchantment commands on my server

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/84567415/119113790-5fdbf280-ba1d-11eb-9609-5ff7c535262f.png)

## Server Information
Unable to do /ae plinfo But I can show the output on my command line.
![image](https://user-images.githubusercontent.com/84567415/119114016-9b76bc80-ba1d-11eb-84df-1f1d4fc2d45a.png)

**Comment by Insprill** [comment]
Please send your latest.log

**Comment by Insprill** [comment]
I deleted your message. I meant attach the file or put it in a pastebin, not copy paste it into a comment

**Comment by Artfulspy** [comment]
My Mistake
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6523960/latest.log)

**Comment by Insprill** [comment]
this is not a bug, something is blocking the plugins connection to our servers. please join our [support discord](https://discord.gg/GzdQdMw) and create an AE ticket
