### ISSUE TITLE
XRAY effect

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1975]
## Request

**Description**
An xray effect could allow you to see lava, ores, chests, dispensers (If possible then configuration of what blocks could be visible would be fabulous.)

**How the feature is useful**
This allows a legal way of using XRay on a server.

**Comment by Insprill** [comment]
Do you any ideas on how this could be implemented? Something like a glowing entity at the blocks location?

**Comment by RulerOfEternity** [comment]
That sounds amazing, but what I originally thought of is just like spectator mode/hacked client stuff :P

**Comment by MamboTND** [comment]
This honestly has no feasible survival use and may not be server friendly.

**Comment by RulerOfEternity** [comment]
Some McMMO servers that I used to play on allowed XRAY, so for some specific servers I feel like it's okay, and if it's added, you're not _obligated_ to use it.

**Comment by Insprill** [comment]
Way too specific and I really don't see many servers using this
