### ISSUE TITLE
PLANT_SEEDS Effect does not remove renamed seeds from inventory, but still plants

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#1976]
## Details

**Describe the bug**
When using the PLANT_SEEDS effect, if the player has renamed seed items in their inventory, the seeds are planted, but the renamed seed items are not taken from the inventory. This allows infinite planting. If the player has non-renamed seeds in their inventory, they are taken first. It seems that the renamed seeds still limit the number of crops that can be planted (if the enchantment has radius 2, but the player only has 9 renamed seeds, then only a 1 radius will be planted).

**To Reproduce**
Enchant an item with a PLANT_SEEDS effect, acquire a wheat seed that is renamed. Use the tool to plant, and the seeds are not removed from the inventory, but the seeds are planted.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ayorabujiz

**Comment by Dakotaa** [comment]
Similarly, I've found that when the player has seeds in their off-hand, the PLANT_SEEDS effect will use them, but it only takes one seed at a time, even if 9+ are being planted.

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by Dakotaa** [comment]
Latest update, having just renamed seeds in the inventory won't plant, but if you have a single renamed seed and a stack of regular seeds, it will plant, but take neither the named seeds or the unnamed seeds.
