### ISSUE TITLE
CONSOLE_COMMAND supporting ':'

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1977]
## Request

**Description**
I'd like to have CONSOLE_COMMAND supporting the ':'.

**How the feature is useful**
This addition would provide more flexibility with enchants that run commands.

**Comment by RulerOfEternity** [comment]
I know that I can just make an alias for commands in commands.yml but I'd prefer to see this suggestion implemented, thank you for your time <3

**Comment by Insprill** [comment]
Added in the next update
