### ISSUE TITLE
A kill/bow aura effect

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1979]
## Request

**Description**
Killaura/Bowaura that autofocuses on entities.

**How the feature is useful**
It would be a fun challenge for players and would make PvP experiences interesting.

**Comment by RulerOfEternity** [comment]
If Kill Aura is a bit far fetched, bow aura I think is more possible, to make it so that the arrow actually hits the nearest entity, that would be amazing.

**Comment by Insprill** [comment]
Added in the next update, works as explained in #1454
