### ISSUE TITLE
Applying Enchantments

### ISSUE THREAD

**Issue by AbrahamOfficial** [GC-spigot/AdvancedEnchantments#198]
Hello there,

Its me again, i have the same issue with the BlackScrolls as before also enchants are not applying to the set items. i have checked my config fully and i dont see any issues, i can send you the file for it if you wish.

**Comment by GC-spigot** [comment]
Set items? AdvancedSets?

**Comment by AbrahamOfficial** [comment]
no with AdvancedEnchantmnets. None of the enchants are applying to items i have the perm for the Lore Count but that is all

**Comment by GC-spigot** [comment]
You don't need the permission, it's optional. Any console errors? What version are you using?

**Comment by AbrahamOfficial** [comment]
Current Version: 4.6.2

Console: https://pastebin.com/65Vnx3mg

**Comment by GC-spigot** [comment]
Could you send over your configuration via PM on discord?

**Comment by AbrahamOfficial** [comment]
What is your Discord?

**Comment by AbrahamOfficial** [comment]
All files are here  https://discord.gg/JV6ByGc

**Comment by AbrahamOfficial** [comment]
I sent you a friend request.

**Comment by AbrahamOfficial** [comment]
My Discord is " abe#8785 "

**Comment by GC-spigot** [comment]
Update to next update.
