### ISSUE TITLE
Server Crash on Custom Trench with Shovel

### ISSUE THREAD

**Issue by blek-id** [GC-spigot/AdvancedEnchantments#1981]
## Details

**Describe the bug**
Server will crash when using custom trench enchant IV with shovel, and breaking  a lot of blocks with it

Enchantment: https://paste.md-5.net/dufobiwozo.css

**To Reproduce**
1. Get Custom Trench IV on shovel
2. Find desert biome
3. Break a lot of sands

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/xemipuzoji
- Server log: https://gist.github.com/blek-id/0223f9d90fe814ebf48048001c33216a

**Comment by Insprill** [comment]
This is an issue with Aurelium Skills. Report it to them.
