### ISSUE TITLE
Telepathy dupe bug

### ISSUE THREAD

**Issue by iGabyTM** [GC-spigot/AdvancedEnchantments#1983]
## Details

**Describe the bug**

Breaking a double chest with a tool with telepathy, the drops from both chests will be dropped on the ground but when opening the second chests, the items from that side of the double chest are still in there.

**To Reproduce**

1. Apply telepathy on a tool (we used a netherite axe)
2. Break one chest from a double chest
3. Open the second chest

**Screenshots / Video**

https://cdn.discordapp.com/attachments/833284262437453825/845732730171424788/2021-05-22_21-37-33.mp4

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ayajadowos 
- Server log: https://gist.github.com/iGabyTM/4e9edf763bf37256f6b9974a571a2dd8

**Comment by Insprill** [comment]
Update AE to the latest version and see if it's fixed. If not, see if experimental-block-breaking changes anything

**Comment by iGabyTM** [comment]
I just updated to v 8.1.5 and it still happen. Also, experimental-block-breaking is enabled @Insprill

**Comment by Insprill** [comment]
#1989 contains more info

**Comment by Insprill** [comment]
Fixed in the next update
