### ISSUE TITLE
Duplicate enchants check

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1984]
## Request

**Description**
I'd like to see a command where it sweeps the 'enchantments.yml' file and checks if you have any duplicate enchants.

**How the feature is useful**
It would be useful in the back end for server owners and developers who want to keep everything tidy.

**Comment by Insprill** [comment]
do you mean enchants that have the same name? you can't do that with yaml files so it wouldn't load properly

**Comment by RulerOfEternity** [comment]
Yes, I meant for example copying the same enchantment twice in the same file and it detecting that, but if that's not possible I'll close this thread.

**Comment by Insprill** [comment]
That would require a lot of work for something that really isn't need so I'm going to deny this request
