### ISSUE TITLE
ItemDurability NPE when getting item

### ISSUE THREAD

**Issue by kofikkk** [GC-spigot/AdvancedEnchantments#1985]
## Details

**Screenshots / Video**
https://ctrlv.cz/BsFC
https://ctrlv.cz/iErD

## Server Information
https://paste.md-5.net/batefokuha
https://gist.github.com/kofikkk/bd476265cda9c0800527b8d6d65a7d0a

**Comment by Insprill** [comment]
Fixed in the next update
