### ISSUE TITLE
Lantern dupe telepathy

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#1986]
## Details

**Describe the bug**
When breaking block under lantern by pickaxe with telepathy it dupes

**To Reproduce**
Enchant pickaxe with telepathy and break blocks under lantern

**Screenshots / Video**
https://youtu.be/jxotVnVqR6c

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/habemulumi (I know that I need to update AE)
- Server log: Not needed

**Comment by Insprill** [comment]
does experimental-block-breaking have any effect on this?

**Comment by iBuseWinner** [comment]
> does experimental-block-breaking have any effect on this?

It set to true, but I'll check tomorrow with false.

**Comment by iBuseWinner** [comment]
With false dupe isn't working

**Comment by Insprill** [comment]
Unable to reproduce. Is it still an issue on the latest version of AE?

**Comment by iBuseWinner** [comment]
I think it fixed when I updated AE...
