### ISSUE TITLE
5.0.0 Won't Enable On Server

### ISSUE THREAD

**Issue by UnrealisticBeing** [GC-spigot/AdvancedEnchantments#199]
Hi, I know I just made the post about 4.8.0, and that one didn't count (https://github.com/GC-spigot/AdvancedEnchantments/issues/195), but it still won't enable either w/ 5.0.0 on my test server.

I've tried deleting the plugin folder and doing a fresh install already, so that's why I came here. I'm running BeerSpigot Premium, version 1.2 (CraftBukkit version git-TacoSpigot-bf023c7d (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT))

My list of plugins (13): PunishGUI, PermissionsEx, Vault, Multiverse-Core, MythicMobs, Essentials, EssentialsProtect, Parkour, LiteBans, EssentialsSpawn, Factions, AdvancedEnchantments, ChatControl, WorldGuard (6.2)

My error log on startup: https://pastebin.com/Uz1My7PR

Thanks!

**Comment by iAlec** [comment]
I am also having the same issue. Every time I type any AE command in-game I get "/AdvancedEnchantments" in all white and nothing else. No errors in the console either.

**Comment by GC-spigot** [comment]
Fixed in next update.
