### ISSUE TITLE
Obsidian from lava walker enchantment does not switch back to lava

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1990]
## Details

**Describe the bug**
Normally when you use the Lava Walker enchantment, the obsidian switches back to lava after a few seconds. Now the obsidian stays forever and can be mined.

**To Reproduce**
1. Hold some boots and do /ae enchant lavawalker 1
2. Equip the boots and walk on some lava
3. Walk away from the obsidian and see that it doesn't revert back to lava

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/nixififoyi
- Server log: https://gist.github.com/WhatsTheBadNews/8f95737f66540e4fdb932a40c62b5dcb

**Comment by Insprill** [comment]
Fixed in the next update
