### ISSUE TITLE
Auto Smelt bug

### ISSUE THREAD

**Issue by Bipedfriend173** [GC-spigot/AdvancedEnchantments#1992]
## Details

Hey I found an odd bug with the auto smelt enchant
If a pickaxe has silk touch and auto smelt, lapis ore will drop an ink sac

https://user-images.githubusercontent.com/77213949/119296338-9bd5aa00-bc0d-11eb-9f28-2fbe4f8653fd.mp4

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/tafopalufi
- Server log: https://gist.github.com/

**Comment by Insprill** [comment]
Fixed in the next update
