### ISSUE TITLE
Rename Tag for unenchanted items

### ISSUE THREAD

**Issue by CobsMC** [GC-spigot/AdvancedEnchantments#1993]
## Request

**Description**
I believe that adding another rename tag or editing the current one to support not custom-enchanted equipment is beneficial since a lot of servers do not have all the players using custom enchantments but perhaps some want to rename their items and gear with custom colours, features, etc.

**How the feature is useful**
Like I said above, it would be benficial since maybe servers don't allow custom enchantments in certain areas or so however players still want the benefits of renaming items so either making a new tag or adding the ability to rename non-enchanted items onto the current tag would suffice.

**Comment by CobsMC** [comment]
@Insprill u better accept this or imma fire u

**Comment by RulerOfEternity** [comment]
Take what I say with a huge grain of salt but can't you do that with the config?

**Comment by Insprill** [comment]
@RulerOfEternity Thats probably how i'll implement it.

**Comment by CobsMC** [comment]
> Take what I say with a huge grain of salt but can't you do that with the config?

Not possible currently.

**Comment by Insprill** [comment]
> > Take what I say with a huge grain of salt but can't you do that with the config?
> 
> 
> 
> Not possible currently.

What? I can just add a setting that'll toggle whether it can work or all items or not, unless i'm vastly misunderstanding @RulerOfEternity

**Comment by RulerOfEternity** [comment]
I mean, I wouldn't mind a feature like that.

**Comment by Insprill** [comment]
Implemented in the next update. Will be a new config option
