### ISSUE TITLE
/aegive bug

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1994]
## Details

**Describe the bug**
/aegive custom enchants can be more than the maximum level (they don't do anything since the level doesn't actually exist).
When surpassing the maximum level the enchant doesn't actually do anything though.

**To Reproduce**
Get an enchantment like reforged (maximum level for this enchantment is level 10, make it level 11 in the command).

**Screenshots / Video**
The enchantment goes beyond maximum level: https://youtu.be/eBqCiL_qrxU
The enchantment works fine at maximum level: https://youtu.be/JPBUt9TZONk

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/itulegacit
- Server log:  https://gist.github.com/RulerOfEternity/7df668debcf55af8e7ddc5a6ff406659

**Comment by RulerOfEternity** [comment]
Shameless self plug but please check this issue too: #1978

**Comment by CobsMC** [comment]
<img width="409" alt="Screenshot 2021-05-24 at 18 52 26" src="https://user-images.githubusercontent.com/84677780/119387694-33e09b80-bcc1-11eb-877b-33b659ef3535.png">
 Can reproduce, this happens too.

**Comment by RulerOfEternity** [comment]
Oh I totally forgot about that!

**Comment by Insprill** [comment]
Fixed in the next update
