### ISSUE TITLE
Cancellable EffectActivationEvent

### ISSUE THREAD

**Issue by nivcoo** [GC-spigot/AdvancedEnchantments#1995]
Hi, I would like to be able to disable the EffectActivationEvent event, I think just making it cancellable is enough but I'm not sure.

**Comment by Insprill** [comment]
Added in the next update. Also did 2 other things with the event, read the changelogs when it releases.

**Comment by nivcoo** [comment]
Yes thx I will do it

**Comment by nivcoo** [comment]
Huym, i've tried and i think the setCancelled(true); not works

**Comment by nivcoo** [comment]
Oh, the event is also called when item is removed, and getUpcomingEffects contain always []

**Comment by nivcoo** [comment]
It's good I found my error but for example the event is not called each time, I explain myself I would like to deactivate all the custom enchantments when someone enters a specific zone
