### ISSUE TITLE
Custom lore item

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1996]
## Request

**Description**
Firstly, yes, I know there are plugins like EpicRename that can do that, but, one problem is that when I do /lore there, all of the enchants in the lore disappear (they still work, you just don't see what enchantments there are on the weapon). I'd like to have the item **add** a lore line instead of overriding the pre-existing lore that's on the item.

**How the feature is useful**
It would be beneficial if it didn't override the enchantment lore.

**Comment by Insprill** [comment]
I think this is outside the scope of AE. That's more of something that should be suggested to the EpicRename devs rather than us.
