### ISSUE TITLE
/alchem Completely Broken

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1997]
## Details

**Describe the bug**
/alchem works like a chest, you can get all the glass panes and all books. Allows you to easily get infinite high level books.

**To Reproduce**
1.) Open `/alchem`
2.) Take out the glass panes
3.) If you want, add 2 books you want to combine. Then just take the upgraded version at no cost. You can even keep the originals

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/lonogasibi
- Server log: https://gist.github.com/WhatsTheBadNews/b182cfafe41f93ea840421cec5378aae

**Comment by iGabyTM** [comment]
https://user-images.githubusercontent.com/32105478/119692252-ef393980-be53-11eb-9471-b721552960ee.mp4

Error: https://paste.helpch.at/igehalafew.hs

**Comment by Insprill** [comment]
Fixed in the next update
