### ISSUE TITLE
INCREASE_DAMAGE not working properly with any sort of condition. 

### ISSUE THREAD

**Issue by Maroon28** [GC-spigot/AdvancedEnchantments#2000]
## Details

**Describe the bug**

Simple and to the point. If you make an enchantment with a condition, and the INCREASE_DAMAGE effect is there, its basically non-existent. You can test enchantments like EnderSlayer, BeastSlayer, or NetherSlayer (all are default). None of them give any noticable effect. 

**To Reproduce**

Not much testing to do, just use a default configuration for AE, and try any enchantment listed above (EnderSlayer, BeastSlayer, or NetherSlayer) 

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/zolemaquqi 
- Server log:  https://gist.github.com/Maroon28/d5ad6afdda3a79bd765066514554b9ad (There's nothing interesting to see here, nothing AE related so no need to waste your time)

**Comment by Insprill** [comment]
All the default enchants and custom ones using INCREASE_DAMAGE work fine with & without conditions. I see you're on a fairly old version of AE, I'd recommend updating. If you need further help with conditions, please join our [Discord Server](https://discord.gg/GzdQdMw).
