### ISSUE TITLE
'RANDOM_ENCHANTMENT' effect

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#2001]
## Request

**Description**
A 'RANDOM_ENCHANTMENT' effect would be great for if it can apply either any AE enchantment or any AE enchantment from a predetermined list.

**How the feature is useful**
It would provide more customization opportunities.

**Comment by Insprill** [comment]
So something like `RANDOM_EFFECT:SMELT:50` which would be a 50% change of running smelt?

**Comment by RulerOfEternity** [comment]
No, I'm planning on making an enchant that has a chance of giving harvested food a random enchantment (/aegive) out of a specific list of food: for example
/aegive person item random_effect

**Comment by RulerOfEternity** [comment]
or /aegive person item random_effect(insert specified list of enchantments here)

**Comment by RulerOfEternity** [comment]
Sorry if I'm not explaining it that well.....

**Comment by ProfessionalBoatDrifter** [comment]
Do you mean you want an effect that has a chance to drop a random enchanted book when you break blocks?

Or rather, you want an effect that has a chance to run a command when you break blocks?

**Comment by Insprill** [comment]
Yeah i have no idea what you're asking lol. Maybe you could use the chance tag to accomplish what you want?

**Comment by RulerOfEternity** [comment]
I'll try again: I want an effect that can get any random enchantment and apply it on the item kinda like a roulette, and the option where the enchantment can be random, but what the randomness can be limited by putting a list of what you want it to be able to choose from.

**Comment by ProfessionalBoatDrifter** [comment]
I think I understand what you mean.

You want an effect that:
- can be triggered to apply any AE enchantment to your item directly (I assume with some sort of notification)
- can apply either any AE enchantment _or_ any AE enchantment from a predetermined list

I assume you don't care if the enchantment can normally be applied to whatever item it is that has the effect?

**Comment by RulerOfEternity** [comment]
The second option is exactly what I meant.

**Comment by ProfessionalBoatDrifter** [comment]
That could be interesting if it also removes itself

**Comment by RulerOfEternity** [comment]
Yes that's what I want as well, I forgot to mention that, sorry.
