### ISSUE TITLE
TRENCH Flower Dupe

### ISSUE THREAD

**Issue by Pandas0** [GC-spigot/AdvancedEnchantments#2002]
## Details

**Describe the bug**
Flowers  broken with TRENCH duplicate themselves and return 2x. (only tested with wither rose and orange tulip, but I am sure its all flowers) [You also get grass (no grass block) back even without silktouch]

**To Reproduce**
Get an enchantment using TRENCH, place down grass blocks, put flowers on top of that grass, and break the grass.

**Screenshots / Video**
https://streamable.com/c69lre

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/sipaqaguno
- Server log: Removed due to IPs showing [Can be given if 100% needed]

**Comment by Insprill** [comment]
does experimental-block-breaking have an effect on this?

**Comment by Pandas0** [comment]
> does experimental-block-breaking have an effect on this?

Just tested, happens regardless of it being set to true or false

**Comment by SeniorCluckers** [comment]
Yeah this still happens.

**Comment by Insprill** [comment]
Fixed in the next update
