### ISSUE TITLE
Item Nametag + Secret Dust not working

### ISSUE THREAD

**Issue by Pandas0** [GC-spigot/AdvancedEnchantments#2003]
## Details

**Describe the bug**
Rename tags and secret dust do not work.

**To Reproduce**
Get a rename tag or secret dust and try to use it.

**Screenshots / Video**
N/A

## Server Information
"/ae plinfo" link: https://paste.md-5.net/sipaqaguno
Server log: https://gist.github.com/Pandas0/fcf6c2ef9a9bce511432d7f114bb6d35

**Comment by dm1lk** [comment]
Uhh, your gist log showcases the IP Addresses of your players, just to let you know.

Use mcpaste.io to get a log with ip-addresses hidden.

**Comment by Insprill** [comment]
@Pandas0 @steda1985 @Kesims Fixed in the next update
