### ISSUE TITLE
Secret dust not working

### ISSUE THREAD

**Issue by Kesims** [GC-spigot/AdvancedEnchantments#2005]
## Details

**Describe the bug**
The Secret Dust is behaving like a normal item (fire charge), when you click with it, nothing happens.

**To Reproduce**
Give yourself a Secret Dust and click with it.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/upobebuqik
- Server log: https://gist.github.com/Kesims/76903ac41b41bd24d2e775b423f0743d

**Comment by Insprill** [comment]
Duplicate if #2003
