### ISSUE TITLE
AE Admin Equipment-Filter

### ISSUE THREAD

**Issue by xBl4cky3101** [GC-spigot/AdvancedEnchantments#2006]
## Request

**Description**

A filter system into the AdminGUI to filter the enchantments for specific Gear Like: "Only for Bow, Boots, Weapon, Chestplate"
or multiple "I'm looking for Enchantments for Chestplate + Bows" to exclude, Swords, Boots and everything else.

**How the feature is useful**

If you dont know the name of a enchantment and dont want to read every single entchantment of this huge list, you can easily select "Boots" as Filter and get all enchantments which could be added to Boots.

**Comment by RulerOfEternity** [comment]
Adding onto that, I have made a ton of enchantments that do the same thing but apply in different ways or things, so I want a filter for types, for example, a filter for if I want an enchantment that supports DEFENSE, HELD, etc.....
