### ISSUE TITLE
EMERALD AND OTHER POSSIBLE ITEM DUPE GLITCH!

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#2007]
## Details

**Describe the bug**
Basically, if you have any custom items in your hand like player heads, custom swords from itemsadder, crate keys from specializedcrates and do /withdrawsouls it will give you empty soul gems which then can't be moved into any gui's using your mouse but they can be used put into crafting tables with the keyboard and hence creating a "dupe" because it will count it as a real emerald of other tools.

**To Reproduce**
Basically, if you have any custom items in your hand like player heads, custom swords from itemsadder, crate keys from specializedcrates and do /withdrawsouls it will give you empty soul gems which then can't be moved into any gui's using your mouse but they can be used put into crafting tables with the keyboard and hence creating a "dupe" because it will count it as a real emerald of other tools.

**Screenshots / Video**
Here is an exemple with an itemsadder craft, I've tried with other crafts aswell and it worked
![image](https://user-images.githubusercontent.com/33335971/119854111-16097580-bf11-11eb-91f1-56691ad47567.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/imesemijew
- Server log: https://gist.github.com/Agaloth/79ca361358e55d4846163f568c3ebd37

**Comment by Agaloth** [comment]
![image](https://user-images.githubusercontent.com/33335971/119854698-94feae00-bf11-11eb-9515-af1fe5bbb902.png)
Update: You can also put it in an anvil with the keyboard and dupe it to normal emerald that way. (IT WON'T WORK WITH THE MOUSE)

**Comment by Insprill** [comment]
Fixed in the next update
