### ISSUE TITLE
Boost effect no longer working

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2009]
## Details

**Describe the bug**

The boost effect is no longer working
**To Reproduce**

Create an enchant with this effect : 
effects:
        - 'BOOST:FORWARD:25' 
 and it won't work, if I use the version 8.1.5 it will work
**Screenshots / Video**

don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
Ae ver: 8.1.7
Server ver : 1.8.8 tacospigot
(no errors)

**Comment by Insprill** [comment]
can you send the enchant you're trying to use? boost is working fine for me and it hasn't even been touched internally in a while.

**Comment by LuluxClient** [comment]
fixed in latest update
