### ISSUE TITLE
Arrow hit type which would activate whenever an arrow hits an entity or a block

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#2011]
## Request

**Description**
An arrow hit type which would activate whenever an arrow hits an entity or a block: A wither skull arrow, a dragon fireball arrow: whenever it hits the ground it actually causes an explosion or in the case of a dragon fireball, the dragon's breath would start eminating. Also, a developer told me that it's possible to make the arrow run a command, if possible, I'd love to see that implemented as well, thank you for your time!

Also not sure if possible but ender pearl arrows would be super fun <3

**How the feature is useful**
It would provide the ability to make some more fun enchantments.

**Comment by RulerOfEternity** [comment]
Perhaps it could be prevented from spawning if blocked with a shield: SHIELD_BLOCK #1924

**Comment by Insprill** [comment]
Added in the next update :D

**Comment by RulerOfEternity** [comment]
Amazing, I've wanted this feature for months, I'm so excited!
