### ISSUE TITLE
/ae info - broken 

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [GC-spigot/AdvancedEnchantments#2013]
## Details

**Describe the bug**
Using `/ae info planter 1` yields no results or print any errors in console.

**To Reproduce**
1. Install AdvancedEnchantments-8.1.8.jar
2. Use the info command on any enchantment
3. Check the chat and console

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/eyojojawac
- Server log: https://gist.github.com/ProfessionalBoatDrifter/95e8392791ea05cae9b806b54d33918f

**Comment by Insprill** [comment]
There isn't a limit, no. I wasn't able to reproduce either of these issues. I see you're running a pretty old version of Paper, try updating and see if that fixes anything.

**Comment by ProfessionalBoatDrifter** [comment]
> 
> 
> There isn't a limit, no. I wasn't able to reproduce either of these issues. I see you're running a pretty old version of Paper, try updating and see if that fixes anything.

Yeah I deleted the AE folder to let it regenerate on an older version and tried /ae info. It didn't work before but did after generating the default files.
I'll try the latest version of Paper and get back on this.

**Comment by ProfessionalBoatDrifter** [comment]
Update:
- I got the latest version of Paper, nothing happened when I use /ae info.
- I deleted 2 .yml files I created, thinking maybe they were somehow conflicting with enchantments.yml. Nothing changed.
- From my previous comment, I deleted the AE folder again to regenerate the default files. /ae info works. To me that has to mean that something I did got messed up and broke it but I have no idea what or where that would be.

**Comment by ProfessionalBoatDrifter** [comment]
Alright, sorry I'm a pepega.

For some reason, I had replaced all the quotation marks with apostrophes in `en-su.yml`. I changed them all to quotation marks, reloaded and everything seems to be working fine again (8.1.9).

What really lost me on this one was that there were no errors on reloading or command usage. This one's on me but do you think you adding checks for misconfigurations in a future update? I'll happily make a Feature Request if it's something you'd consider adding.

**Comment by Insprill** [comment]
With the amount of things that need done right now, a configuration check like that isn't really worth adding. We'll keep it in mind though if someone else has the same issue
