### ISSUE TITLE
players are able to remove the result product from the alchemist screen without 'confirming' the merge

### ISSUE THREAD

**Issue by Bertman5505** [GC-spigot/AdvancedEnchantments#2014]
## Details

**Describe the bug**

players are able to remove the result product from the alchemist screen without 'confirming' the merge, this results in them being able to dupe nearly anythig including dusts
**To Reproduce**

Steps to reproduce:
1) add the first and second 'input' dusts
2) remove the result by just selecting it and dragging it to your inv
3) drag the inputs back into your inv

**Screenshots / Video**

![2021-05-28_11 26 58](https://user-images.githubusercontent.com/15119175/120016357-c98f6a00-bfe4-11eb-9bc9-f62ab581af53.png)  
![2021-05-28_11 26 59](https://user-images.githubusercontent.com/15119175/120016331-c3998900-bfe4-11eb-8e15-559a409b2841.png)  
![2021-05-28_11 26 42](https://user-images.githubusercontent.com/15119175/120016349-c7c5a680-bfe4-11eb-9127-21953db760fe.png)  
![2021-05-28_11 26 56](https://user-images.githubusercontent.com/15119175/120016353-c8f6d380-bfe4-11eb-9654-a76ea933ef6c.png)  
![2021-05-28_11 26 39](https://user-images.githubusercontent.com/15119175/120016345-c5fbe300-bfe4-11eb-875e-360d5b3092c6.png)  
![2021-05-28_11 26 40](https://user-images.githubusercontent.com/15119175/120016348-c6947980-bfe4-11eb-91ed-4d10ad4eed95.png)  

## Server Information
- https://paste.md-5.net/muviceqipi
- Server log: does not print ouut anything, nothing brealks per-se its just not working
```
[Fri, 28. May 2021 18:53:53 SAST INFO] (A) Bert → something unique started
[Fri, 28. May 2021 18:53:53 SAST INFO] Bertman5505 issued server command: /ce
[Fri, 28. May 2021 18:53:56 SAST INFO] Bertman5505 issued server command: /ce
[Fri, 28. May 2021 18:53:58 SAST INFO] Bertman5505 issued server command: /alchemist
[Fri, 28. May 2021 18:54:00 SAST INFO] Diamond_Hoe_82 issued server command: /rtp
```

**Comment by xpd207** [comment]
Same inssue for me :/

**Comment by Insprill** [comment]
Fixed in the next update
