### ISSUE TITLE
infinite powders and books on the alchemist

### ISSUE THREAD

**Issue by Kunetsa** [GC-spigot/AdvancedEnchantments#2015]
Describe the bug

Players can remove the 3 items from the alchemist without accepting that "exchange" and they would have infinite magic powders with a high percentage  (It also happens with books but the percentage does not increase)

Steps to reproduce:

1. you open the alchemist and place the 2 powders
2. Take out the dust you laid and the new one from the alchemist

![Capturadust](https://user-images.githubusercontent.com/84932498/120021814-8cfa4900-bfb9-11eb-948b-848d39911a06.PNG)
![Capturadust2](https://user-images.githubusercontent.com/84932498/120021893-a7ccbd80-bfb9-11eb-87cc-c02d9e266f7f.PNG)
![Capturabook](https://user-images.githubusercontent.com/84932498/120022108-eb272c00-bfb9-11eb-88a1-ab818caae650.PNG)
![Capturabook2](https://user-images.githubusercontent.com/84932498/120022116-ee221c80-bfb9-11eb-904c-0848b5c6103f.PNG)

**Comment by Insprill** [comment]
Fixed for the next update
