### ISSUE TITLE
Smelting doesn't smelt a number of smeltable blocks (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2016]
## Details

**Describe the bug**
Mining with pickaxes that have the Smelting enchantment does not turn a number of smeltable blocks into their smelted forms.

TESTED BLOCKS:
- Netherrack (Should become Nether Brick)
- Nether Bricks (Should become Cracked Nether Bricks)
- Dyed Terracotta (Should become Glazed Terracotta of the same color)
- Stone Bricks (Should become Cracked Stone Bricks)
- Sandstone (Should become Smooth Sandstone)
- Red Sandstone (Should become Red Smooth Sandstone)
- Stone (Should become Smooth Stone)
- Block of Quartz (Should become Smooth Quartz)

I have only tested this with `use-experimental-block-breaking: true`, though I am not sure if this makes a difference.

**To Reproduce**
1. Set `use-experimental-block-breaking:` to true
2. Hold a pickaxe and do /ae enchant Smelting 3
3. Place any of the listed blocks
4. Use the pickaxe to mine the blocks you placed

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yefonotavu
- Server log: https://gist.github.com/WhatsTheBadNews/0996a6819b5c3aebdae5e8b6553378a4

**Comment by Insprill** [comment]
While yes this is true, SMELT isn't meant to *exactly* mimic a furnace, It's more made to just do the convenient stuff. If more people want this we can add it for for now don't think most people would like it.
