### ISSUE TITLE
Smelting doesn't reward experience for mining Iron Ore, Gold Ore, Cobblestone (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2017]
## Details

**Describe the bug**
The Smelting enchantment is supposed to emulate smelting in a furnace. It should reward some experience for mining smeltable blocks. I believe it used to do this, but it doesn't anymore.

Blocks tested:
- Iron Ore
- Gold Ore
- Cobblestone

I've only tested this with `use-experimental-block-breaking: true`, though I don't know if this makes a difference

**To Reproduce**
1. Set `use-experimental-block-breaking:` to true
2. Hold a pickaxe and do /ae enchant Smelting 3
3. Mine some iron ore, gold ore, and/or cobblestone

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yefonotavu
- Server log: https://gist.github.com/WhatsTheBadNews/0996a6819b5c3aebdae5e8b6553378a4

**Comment by Insprill** [comment]
That was never a feature. You can emulate it using the EXP effect.
