### ISSUE TITLE
No souls required permission node/as op

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#2020]
## Request

**Description**
I'd like to see a feature implemented where if you're an operator or have a specific permission (Example: ae.bypasssoulsrequirement), you won't need to use souls.

**How the feature is useful**
It would make testing far more convenient for developers and make life easier for the admins who like to have fun with the plugin.

**Comment by Insprill** [comment]
Added in the next update. Permission is `ae.bypass.souls`. Will need to be explicitly given, op or * will not give it.
