### ISSUE TITLE
The ability to toggle whether AE item drops can drop from mobs spawned from spanwers

### ISSUE THREAD

**Issue by VoxellOT** [GC-spigot/AdvancedEnchantments#2021]
## Request

**Description**

Having a config setting that allows us to specify whether we want AE items to drop from mobs spawned from spawners. When true, spawner mobs will be treated the same as naturally spawned mobs when it comes to dropping AE items. When false, spawner mobs will not drop AE items, but naturally spawned mobs will.

**How the feature is useful**

This helps balancing in survival servers where players can build mob farms using spawners. Players would no longer be able to AFK and collect these items. This will also prevent sorting systems on mob grinders from being clogged with AE items.

**Comment by Insprill** [comment]
Added in the next update. Spawner mobs now won't drop custom drops by default unless enabled.
