### ISSUE TITLE
Server Hard Crashes

### ISSUE THREAD

**Issue by xxirs** [GC-spigot/AdvancedEnchantments#2022]
[hs_err_pid28.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6565626/hs_err_pid28.log)
[replay_pid28.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6565627/replay_pid28.log)
My server is experiencing hard crashes about once a day due to some unknown issue, talking to Insprill on discord he seemed to could be related to creating fakeblockbreakevent & MCMMO.

See Attached,

**Comment by xxirs** [comment]
[replay_pid28.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6591246/replay_pid28.log)
[hs_err_pid28.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6591248/hs_err_pid28.log)
Attached are more crash reports from my server hard crashing.

**Comment by xxirs** [comment]
[hs_err_pid28.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6603430/hs_err_pid28.log)
[replay_pid28.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6603431/replay_pid28.log)
More crash logs from 6/5/2021

**Comment by Insprill** [comment]
Looks like this might actually be related to the BlockTracker although I have no idea what would actually cause it. Do you happen to know if breaking a specific block triggers it?

**Comment by xxirs** [comment]
@Insprill would you happen to know, or can you provide a list of every block the bloctrack tracks. I.plan on doing this tomorrow. But I'd rather only place the blocks down it actually tracks and not every MC block.

**Comment by Insprill** [comment]
Any updates on this?

**Comment by Microhazard** [comment]
Hello, there we have the same issue as xxirs. Here are the error logs that produce during the server crashed. Also, it rollsback the whole progress and clears some inventory after the crash.
[ERR LOGS.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/6834116/ERR.LOGS.zip)

**Comment by Microhazard** [comment]
When I check all the errors it has
C2:4151426 70214   !   4       net.advancedplugins.ae.items.BlockTrack::addBrokenBlock (476 bytes)

**Comment by Microhazard** [comment]
Heres the pluginlist

https://paste.md-5.net/suvifewaga

**Comment by Insprill** [comment]
Is this still an issue on the latest version?
