### ISSUE TITLE
Action bar time parameter

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2024]
## Request

**Description**

Make it so you can set a time for how long the actionbar is going to be displayed

For example : ACTIONBAR:(message):(time in ticks)
**How the feature is useful**
Well instead of 2s to read the message you can set it to 5s+ etc

They will be able to put longer messages

**Comment by Insprill** [comment]
This isn't possible without doing a bunch of extra work, you can simply use  the WAIT effect and send the message again.
