### ISSUE TITLE
Let us change the item type of each item in a Set

### ISSUE THREAD

**Issue by Potrock** [GC-spigot/AdvancedEnchantments#2025]
There is currently no support for custom models on armor without Optifine, and the way to bypass this for helmets is to use a carved_pumpkin with custom model data and applying armor and durability attributes to it. There is the custom model data option in creating AE sets, but we are restricted to helmets which cannot have models.

**Comment by MamboTND** [comment]
I like this idea but I think the devs would require some more details as to how you see this being implemented like an example or something. Best of luck!

**Comment by Potrock** [comment]
> I like this idea but I think the devs would require some more details as to how you see this being implemented like an example or something. Best of luck!

For the sets, instead of specifying at the top of each Advanced Set definition the material (diamond, iron, leather, etc), let us specify item type of each item in the set. This way we can make the helmet be a CARVED_PUMPKIN with custom model data.
