### ISSUE TITLE
Adding enchant to items

### ISSUE THREAD

**Issue by ItsHuddy** [GC-spigot/AdvancedEnchantments#2026]
## Request

**Description**

I would want enchantment books able to be added through anvils and not just through clicking on an amount. 

**How the feature is useful**

If a server like mine is looking to keep it as vanilla as possible, it would be a fantastic change/ option for servers (in my opinion). It would also work well for servers that are looking for the option of this.

**Comment by Insprill** [comment]
Added in the next update
