### ISSUE TITLE
ALL_BLOCK

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#2028]
## Request

**Description**
I'd like to see an ALL_BLOCK thingy where an enchantment applies to all blocks, also, a variable for that in a command to say what block it is you're holding and a variable for what block you're mining (depending on what block you're holding, if it isn't a block then it just gives a togglable warning saying that you're not holding a block) as I'm planning a fun enchantment.

**How the feature is useful**
It's useful for a bunch of enchantments.

**Comment by RulerOfEternity** [comment]
I'm making an enchantment where you scaffold blocks and that variable for the block you're holding would be extremely useful, thank you!

**Comment by Insprill** [comment]
Added in the next update
