### ISSUE TITLE
Can't parse with multiplication Enchantment

### ISSUE THREAD

**Issue by Tauses** [GC-spigot/AdvancedEnchantments#2029]
## Details

**Describe the bug**
Mutliplication IV Enchant sends an error message saying it can't parse

**To Reproduce**
Put Multiplication IV on your pickaxe
Go mine an ore

**Screenshots / Video**
![multiplication](https://user-images.githubusercontent.com/63642622/120629650-4fd50180-c466-11eb-9a37-b9e745546d2d.jpeg)
![multiplication1](https://user-images.githubusercontent.com/63642622/120629656-519ec500-c466-11eb-889c-6d0f45a3ed7e.jpeg)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/bexaqinuci
- Server log: https://mcpaste.io/6e46038dce6d4ba7
- Plugin version: AdvancedEnchantments-8.2.0.jar

**Comment by Insprill** [comment]
You wrote the condition wrong. You can join our support discord and ask for the proper way to write it
