### ISSUE TITLE
Custom Enchants don't Combine

### ISSUE THREAD

**Issue by Heklo1** [GC-spigot/AdvancedEnchantments#2030]
## Details

**Describe the bug**

Using anvils will combine vanilla enchantments, but they will only keep the first items custom enchantments. 
**To Reproduce**

Spawn in two swords, enchant both of them with sharpness 1 (vanilla) and poison 1 (custom). Place them both in an anvil, the resulting sword will be sharpness 2 but only poison 1. The custom enchantments do not add, instead only the first items enchantments are used. For example, combining a poison 1 sword with a lifesteal 1 sword will result in a poison 1 sword.

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/74341161/120752491-d1b14300-c4d7-11eb-95e8-b89f2e669bb0.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/uyiyenubil
- Server log: https://mcpaste.io/e7fd2043bb490381

**Comment by Insprill** [comment]
Fixed in the next update
