### ISSUE TITLE
Prompt that gets you to write something

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#2033]
## Request

**Description**
So the title doesn't explain what I want well at all apparently lol, but what I want is a variable that you can put in a command where you get a prompt to type what you want, with the option of limiting what you can choose, for example, an enchantment that prompts you to choose between a stack of diamonds/emeralds/whatever.

Example: 'CONSOLE_COMMAND:give %attacker name% %prompt%[diamond, emerald, netherite_ingot] 64 0'

The [] is optional but it limits what you can choose.

I thought of a second thing just now: in addition to what I suggested earlier maybe you can make it so that an enchantment is activated by saying something specific, kind of like a password or something, would provide more lore and stuff.

**How the feature is useful**
It would allow for the expansion of enchantment limits.

**Comment by Insprill** [comment]
Seems way to niche and seems like it would be clunky as an enchantment
