### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2034]
## Details

**Describe the bug**

Just getting this error idk how https://pastebin.com/45DPS1hX
**To Reproduce**

no idea
**Screenshots / Video**

don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
Server : 1.8.8 tacospigot
Ae : 8.2.3

**Comment by xxirs** [comment]
getting this error as well with latest AE version

[message.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/6600734/message.txt)

**Comment by Insprill** [comment]
#2035 is caused by this

**Comment by Insprill** [comment]
Fixed in the next update
