### ISSUE TITLE
Guard effect no longer working

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2035]
## Details

**Describe the bug**

If I use the guard effect and I use a wolf, he will spawn but he won't attack
**To Reproduce**

Put this on your enchant : - 'GUARD:WOLF:&6Frosty' 

**Screenshots / Video**

Don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
Ae; 8.2.3
server ; 1.8.8 tacospigot

**Comment by RulerOfEternity** [comment]
It works for me for attacking mobs but I'm not using a name, it could be the name that's the issue?

**Comment by Insprill** [comment]
This is a result of the error from #2034
