### ISSUE TITLE
REMOVE_ENCHANT

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#2036]
## Details

**Describe the bug**
If there is an enchantment with the REMOVE_ENCHANT effect on a stacked item, the enchantment will remove it from the entire stack, not just one item.

**To Reproduce**
Enchant a stackable item with an enchantment that has the REMOVE_ENCHANT effect and activate it, the enchantment will be removed from the entire stack, not just one item.

**Screenshots / Video**
 https://youtu.be/HKUywUpQej8

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/cilefaladu
- Server log:  https://mcpaste.io/2d2892891a326030

**Comment by Insprill** [comment]
That's not a bug, that's just how it works. It applies changes to the entire stack, the same as every other effect.
