### ISSUE TITLE
Exp option for tinkerer doesn't work

### ISSUE THREAD

**Issue by Thefluffypvper1** [GC-spigot/AdvancedEnchantments#2037]
**Describe the bug**
When using /tinkerer with custom enchant books when traded it doesn't give you exp bottles, but it gives you dust when i set the config option to exp only 

**To Reproduce**
The type: you choose needs to give the right outcome, if I choose exp option it needs to give me xp bottles if I choose money option it needs to give me the money option.

**Screenshots / Video**
https://www.youtube.com/watch?v=7AToeiaSrGw

## Server Information
https://paste.md-5.net/awufiyopex
https://paste.helpch.at/uliquvevug.md

**Comment by Insprill** [comment]
That's how it's supposed to work. That option doesn't apply to books, only items with CE's applied
