### ISSUE TITLE
Using `ADD_DURABILITY_CURRENT_ITEM` on armor can create duplicates of it.

### ISSUE THREAD

**Issue by variananora** [GC-spigot/AdvancedEnchantments#2038]
## Details

**Describe the bug**

`ADD_DURABILITY_CURRENT_ITEM` effects on armor can duplicate the armor that you are using.

In case of duplicates, this is related to #1704 

If you need anymore information feel free to tag me!

**To Reproduce**

1. Make an armor piece
2. Enchant it with effects `ADD_DURABILITY_CURRENT_ITEM`
3. Equip the armor
4. Let a mob damage you and quickly swapping your armor to inventory or with another armor.
5. Armor will be duplicated.

Enchant on use: https://paste.md-5.net/umugiqofos.bash

**Screenshots / Video**

https://youtu.be/enN5LX45lbg

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/kubatevuga
- Server log: https://paste.md-5.net/cepapuvapi.md

**Comment by Insprill** [comment]
Fixed in the next update
