### ISSUE TITLE
Overload Enchant BUg

### ISSUE THREAD

**Issue by thereaperpeper12** [GC-spigot/AdvancedEnchantments#2039]
![image](![image](https://user-images.githubusercontent.com/85433343/120918131-134a1580-c6b3-11eb-87da-cc412818b367.png)

as you can see i enchanted some gear with the overload enchant but when i take my helmet off the effect goes away while my other armor still has the overload enchant. I don't think this is a huge problem but it still is a bug.

**Comment by Insprill** [comment]
Fixed in the next update
