### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.2.4

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2041]
## Details

**Describe the bug**
Console is getting spammed with the error in the title.

**To Reproduce**
1.) Hold a sword and do /ae enchant critical 3
2.) Hit a creeper with the sword
3.) Look in console

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ihoxofapiy
- Server log: https://gist.github.com/WhatsTheBadNews/16df05d59685cfd37f5b220bf311fd85

**Comment by Insprill** [comment]
Fixed in 8.2.5
