### ISSUE TITLE
GUI issue with auction plugin

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2047]
https://youtu.be/sdYO-wlENXY

## Details

**Describe the bug**

**To Reproduce**

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: 
- Server log:

**Comment by NCSV** [comment]
video: https://youtu.be/sdYO-wlENXY

sorry for my poor english.
when i use zAuctionHouse purchase confirm pages and clicked comfirm button,
but it goes aenchantments main pages.

i asked zAuctionHouse delevoper and he said it's not my plugin's bug.
That's why I came here.
can you examine this problem?

spigot 1.16.5 lastest

**Comment by Insprill** [comment]
Fixed in the next update
