### ISSUE TITLE
Random error spamming my console

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2048]
## Details

**Describe the bug**

Just having this spamming my console : https://pastebin.com/gjC4uujJ
**To Reproduce**

Fight someone 
**Screenshots / Video**

Don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
Ae: 8.2.5
Server : 1.8.8 TacoSpigot

**Comment by Insprill** [comment]
You're using an effect with a ludicrously large number. Most effects don't support any numbers higher than 2,147,483,647.
