### ISSUE TITLE
EXTRA_DAMAGE %attacker% %victim% placeholder bugged

### ISSUE THREAD

**Issue by TasmanianNoob** [GC-spigot/AdvancedEnchantments#205]
I made this enchantment to test if the attacker took any damage and he didn't, my alt took 4 hearts of damage instead of taking 2 and me taking 2

test: (https://hastebin.com/examowakun.pl)
  display: "%group-color%Test"
  Description: "A test enchantment!"
  applies-to: "Sword"
  type: "ATTACK"
  group: "TEST"
  applies:
    - ALL_SWORD
  levels:
    1:
      chance: 100
      effects:
        - "EXTRA_DAMAGE:2 %attacker%"
        - "EXTRA_DAMAGE:2 %victim%"

Fairly sure that it's always the victim that gets hurt not the attacker

test: (https://hastebin.com/awituyiyil.pl)
  display: "%group-color%Test"
  Description: "A test enchantment!"
  applies-to: "Armor"
  type: "DEFENSE"
  group: "TEST"
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 100
      effects:
        - "EXTRA_DAMAGE:2 %attacker%"
        - "EXTRA_DAMAGE:2 %victim%" 

because I tried that and the player that got hit also took an extra 4 hearts of damage.

**Comment by GC-spigot** [comment]
EXTRA_DAMAGE is designed to work with victim only.
