### ISSUE TITLE
Duplication Issue with Beds and Trench

### ISSUE THREAD

**Issue by secretshopyyc** [GC-spigot/AdvancedEnchantments#2050]
## Details

**Describe the bug**
You can duplicate beds using Trench 9 and possibly lower.

**To Reproduce**
Place down three beds, and then enchant a pickaxe with Trench 9. Mine the three beds and you'll have many more than you started with.

**Screenshots / Video**
https://streamable.com/dqrgg7

## Server Information
No relevant. This can be reproduced on any server.

**Comment by Insprill** [comment]
Does experimental-block-breaking have an effect on this?

**Comment by Maroon28** [comment]
> Does experimental-block-breaking have an effect on this?

Just tested it, works on my server too. And it has no effect

**Comment by Insprill** [comment]
Fixed in the next update
