### ISSUE TITLE
VEIN_MINE ignores other effects when breaking non-whitelisted blocks

### ISSUE THREAD

**Issue by Maroon28** [GC-spigot/AdvancedEnchantments#2051]
## Details

**Describe the bug**
When having two enchantments that include the type MINE_VEIN and TELEPORT_DROPS on the same tool, only the MINE_VEIN works, and a little buggy too.

**To Reproduce**
1- Install a default version of AE.
2- Enchant a pickaxe with Telepathy and Vein Miner (both are defaults)
3- Mine. If you break normal blocks, they don't teleport to you (even with chances to 100), and if you break a vein, it works just fine. 

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/tucixutolu
- Server log:  https://mcpaste.io/b1ab6dd9a339810d

**Comment by Insprill** [comment]
Is this with both effects being on the same enchant or separate ones?

**Comment by Maroon28** [comment]
> Is this with both effects being on the same enchant or separate ones?

Two different enchantments with nothing but that effect. Like I said, try it with the default Telepathy and Vein Miner enchantments.

**Comment by Insprill** [comment]
Alright. Does experimental-block-breaking change anything?

**Comment by Maroon28** [comment]
Nope, still not working properly.

**Comment by Insprill** [comment]
Can you send the enchants you're using? I can reproduce this. Both effects work fine together

**Comment by Maroon28** [comment]
You may be trying to reproduce it wrong. I made a quick video to illustrate the bug. Anyways, I'll send you the current enchants in a pastebin. https://pastebin.com/j5C98HRD

Here's the video I'm talking about: https://youtu.be/nRgwVDGYldA

**Comment by Insprill** [comment]
Oh so it's only on blocks that aren't whitelisted. Will look into this

**Comment by Insprill** [comment]
Fixed in the next update
