### ISSUE TITLE
Bug when changing items

### ISSUE THREAD

**Issue by SpeedCrazy** [GC-spigot/AdvancedEnchantments#2052]
Basically, today I was testing the latest update of the ae, when a bug happened that I don't know if it is mine or the server's. This is affected with the Godly Overload enchantment every time you regenerate that life bar and switch to another slot these same hearts will disappear I will leave a video here thank you very much and sorry for the poor quality. 

https://www.youtube.com/watch?v=B50Qj-TOc7Q

**Comment by Insprill** [comment]
Fixed for the next update
