### ISSUE TITLE
Overload Enchantment Bugged

### ISSUE THREAD

**Issue by OGDubs** [GC-spigot/AdvancedEnchantments#2054]
Hi so for some reason, both overload and godly overload arent working, upon putting on a piece of gear with either overload or godly overload it does not give me a health boost at all, it will show the health boost, for example health boost V, but it doesnt give you the health boost, however it does damage you for a certain amount of health depending on how high of overload

**Comment by Insprill** [comment]
If you mean it gives you the hearts but doesn't fill them, that's intended. As for it damaging you, I can't reproduce that. Can you please send the link for "/ae plinfo"?

**Comment by OGDubs** [comment]
no, it doesnt give me the hearts at all, i will attach a video really quickly

**Comment by OGDubs** [comment]
Attached is a link to the /ae plinfo as well as a megafile download link to download a video of the issue
[https://paste.md-5.net/zutabivajo](url)
[https://megafile.cc/d/daYo/2021-06-15-23-41-07](url)

**Comment by OGDubs** [comment]
update: overload is WORKING functionally but its a visual error, the hearts that are "added" are actually taken away from our original 20 health...you can see what i mean in the video i attached

**Comment by Insprill** [comment]
Is this still an issue and if it is can you reupload the video? Says it doesn't exist

**Comment by Starkenz** [comment]
> Is this still an issue and if it is can you reupload the video? Says it doesn't exist

https://youtu.be/G1lEo5RHVAg

**Comment by FighterPilot50** [comment]
> Hi so for some reason, both overload and godly overload arent working, upon putting on a piece of gear with either overload or godly overload it does not give me a health boost at all, it will show the health boost, for example health boost V, but it doesnt give you the health boost, however it does damage you for a certain amount of health depending on how high of overload

I am also getting this issue, I'm glad I wasn't the only one. What plugins do you have on your server? Perhaps it's a compatibility issue.

**Comment by Insprill** [comment]
Could be, try removing all other plugins then slowly add back until the issue appears

**Comment by Insprill** [comment]
See #2102
