### ISSUE TITLE
alt + F4 in enchantment table duplicating lore

### ISSUE THREAD

**Issue by tuanhp0** [GC-spigot/AdvancedEnchantments#2055]
When the player combines a higher level enchantment into the equipment, then using the key combination alt + F4, the equipment received will be 2 lines of identical enchantment
![image](https://user-images.githubusercontent.com/37981571/122168704-cfbb8c80-cea6-11eb-97cd-3b8d0ff47688.png)
![image](https://user-images.githubusercontent.com/37981571/122168720-d518d700-cea6-11eb-959d-fae36fb71ab5.png)

## Details

**Describe the bug**

**To Reproduce**

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: 
- Server log:

**Comment by Insprill** [comment]
So it's just the lore that's duplicated? You can look at `/ae unenchant`s tab completion to see what enchants are actually on the item

**Comment by Insprill** [comment]
@tuanhp0

**Comment by tuanhp0** [comment]
> Vì vậy, nó chỉ là truyền thuyết được sao chép? Bạn có thể xem `/ae unenchant`hoàn thành tab của s để biết những gì thực sự có trên mặt hàng

Nope, It makes my server take more time to process and display it, the server will crash if someone uses it

**Comment by Insprill** [comment]
Is this still an issue on the latest version? If it is, please send a video of it happening.
