### ISSUE TITLE
Death message spams when wearing armor with WorldGuard

### ISSUE THREAD

**Issue by MysticKillerBear** [GC-spigot/AdvancedEnchantments#2056]
## Details

**Describe the bug**
When a player gets killed with any piece of armor on, the death event will spam tens if not hundreds of times. 

**To Reproduce**
Install AdvancedEnchants with worldguard, put on some armor and die in any way.

**Screenshots / Video**
https://discord.com/channels/376425582139015168/377152090088275968/854626781348888626

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/uwuzizudub
- Server log: https://mcpaste.io/51e5a241b2b3f082

**Comment by Sikatsu** [comment]
I have this issue as well. Chat is being spammed:
![Screenshot_8](https://user-images.githubusercontent.com/5664135/122233975-c0dfd480-cebc-11eb-9098-65a4f2625e07.png)

**Comment by Insprill** [comment]
Fixed for the next update
