### ISSUE TITLE
Issue with repair enchant

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2057]
Hey the issue #2053 was closed yet absolutely nothing in that issue was fixed on this update. I'm not sure you understood what the issues with it were so I'll go over them again:

**Issue 1:** If an item in your inventory has the repair custom enchant, then even if you use another item that DOES NOT have the enchant (like an unenchanted stone sword), that will also repair too. So every single item becomes unbreakable as long as 1 item in your inventory has the repair enchant

**Issue 2:** Repair enchant does not work on equipped elytras. It simply does not repair. I am using the ELYTRA_FLY type

**Comment by Insprill** [comment]
I have tested these again and neither is an issue for me. Can you confirm this is still an issue on the latest version and if it is can you send a video of it happening?
