### ISSUE TITLE
When player dies they drop 100+ heads (headless enchant bug)

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2058]
## Details
a player dies wearing enchanting gear the other player who kills him with headless the death animation spams and death message spams and drops 100 of heads from headless enchant.
**To Reproduce**
in our case its the pvp arena its a world guard region with no item or exp drop flags, but it happens everywhere else too.
maybe related to your overload fix?
**Screenshots / Video**
https://www.youtube.com/watch?v=oJtumLSL308&t=2s

## Server Information
PaperMC 1.16.5 - 731
AdvancedEnchantments-8.2.9

**Comment by Insprill** [comment]
please send the output of `/ae plinfo`. we do ask for it for a reason

**Comment by antibitcoin** [comment]
I cant I reverted back to 8.2.7 does logs help?

**Comment by antibitcoin** [comment]
> please send the output of `/ae plinfo`. we do ask for it for a reason

https://paste.md-5.net/teqiboxiwa

**Comment by Insprill** [comment]
On a dev server, can you remove WorldGuardExtraFlags and see if the issue goes away? If it doesn't also remove WorldGuard and then see if it goes away. Pretty sure this is the same at #2056

**Comment by Insprill** [comment]
Nevermind, found the cause and it's fixed for the next update.
