### ISSUE TITLE
Config description mistake

### ISSUE THREAD

**Issue by ceze88** [GC-spigot/AdvancedEnchantments#2059]
## Details

**Describe the bug**
This is in the latest release.

There is a misstaka in the config.yml under "chances".
Wrong line: # Can use `<min>-<max` to define range between
A > is missing after "max" so it should be:  # Can use `<min>-<max>` to define range between

Link for the line in github:
https://github.com/GC-spigot/AdvancedEnchantments/blob/d1246ceeeeb5008ec737919d52b197d74220892b/Default%20Files/config.yml#L646

**To Reproduce**
Line 646 in the default config.yml

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/liwereduru
- Server log: No log required for this to fix

**Comment by Insprill** [comment]
Fixed in the next update
