### ISSUE TITLE
Telepathy issuse

### ISSUE THREAD

**Issue by Frostyeiz** [GC-spigot/AdvancedEnchantments#206]
Telepathy doesn't work properly with some blocks:
- Hardened block (terracotta), no matter what color it is, telepathy always give back white terracotta.
- Also happens with slabs, all kind of slabs that are broke by tools /w telepathy turn into stone slab- 
- Also happens with stained glass pane (turn into white stained glass pane), colored glass (turn into white stained glass)
- Also happens with colored concrete (turn into white concrete), colored concrete powder
- Colored carpet blocks (turn into white carpet)
- Banners, armor stand disappear after breaking with telepathy tools
- Any saplings beside oak sapling will turn into oak sapling 
- Any flowers beside poppy will turn into poppy 
- Mossy Cobblestone wall turn into normal cobblestone wall

**Comment by GC-spigot** [comment]
Same issue with all of these, will be fixed.
