### ISSUE TITLE
Fortune and telepathy not working on coco ! (axe)

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2060]
## Details

**Describe the bug**

Telapathy and fortune on coco beans doesn't work, you only get 1 item: https://gyazo.com/ef3813a5ce30e72ed7cb14f26e69c109
**To Reproduce**

grabe an axe enchant it with fortune and telepathy and mine a coco bean
**Screenshots / Video**

https://gyazo.com/ef3813a5ce30e72ed7cb14f26e69c109

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae ver : 8.2.8
server ver : 1.8.8 TacoSpigot

**Comment by Insprill** [comment]
Fixed in the next update
