### ISSUE TITLE
When applying a Haste 2 book the enchantment shows up twice on my pickaxe.

### ISSUE THREAD

**Issue by J14P** [GC-spigot/AdvancedEnchantments#2061]
## Details

**Describe the bug**

When placing a haste 2 book on a netherite pickaxe the enchantment shows up twice on the pickaxe. I tried removing with a black scroll and the enchantments do not disappear from the pickaxe but I still get a haste 2 book with whatever percentage the black scroll was for.
**To Reproduce**

Apply a Haste 2 book to a netherite pickaxe
**Screenshots / Video**

![image](https://user-images.githubusercontent.com/86026838/122302382-078afa00-ced0-11eb-9d8d-c43293329733.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/oyivadedik
- Server log: https://mcpaste.io/5ddce975b2feea08

**Comment by Insprill** [comment]
Can you show a little better what happened? I can't see anything in that screenshot other then an error that isn't related to AE

**Comment by Insprill** [comment]
Why was this closed?

**Comment by J14P** [comment]
Because i can’t recreate and upload a better screenshot
