### ISSUE TITLE
Telepathy and silk touch not working on 1.8

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2062]
## Details

**Describe the bug**

Telepathy and silk isn't working togerther
**To Reproduce**

Grab a diamond pick enchant it with telepathy and silk touch and mine a diamond ore
**Screenshots / Video**

https://gyazo.com/8c9e6d38cc49c711549f1bda207d85d8

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae: 8.2.8 
Server ver : 1.8.8 tacospigot

**Comment by Insprill** [comment]
Fixed in the next update. I've also completely rewritten TP_DROPS & SMELT internally so hopefully there shouldn't be any more issues with them
