### ISSUE TITLE
Trench duplicating blocktrack lore

### ISSUE THREAD

**Issue by arceusxs2** [GC-spigot/AdvancedEnchantments#2064]
## Details

**Describe the bug**

Hello, for some reason when i have trench and blocktrack on same pickaxe, it keeps multiplying stats from the blocktrack in the lore of the pickaxe. When i remove trench enchant, then while mining the cloned blocktracks starts disappearing. Then when i put trench back they again start appearing.
**To Reproduce**

**Screenshots / Video**

https://prnt.sc/15tryjq - when someone mines with trench it clones the blocktrack 

## Server Information
- "/ae plinfo" link: 
- Server log: 
- Plugin 8.3.0 version, 1.16.5 Pupur

**Comment by Insprill** [comment]
Implemented a possible fix for the next version (8.4.5), won't be in the patch notes but please get back as to if it's still an issue

**Comment by Sikatsu** [comment]
On 8.4.5 this happened for a player out of the blue:

![blocktrak](https://user-images.githubusercontent.com/5664135/124969436-fc3a7280-e026-11eb-90f4-0dcb8ea38c7d.png)

**Comment by Insprill** [comment]
Fixed in the next update
