### ISSUE TITLE
spectator walking

### ISSUE THREAD

**Issue by MysticKillerBear** [GC-spigot/AdvancedEnchantments#2066]
## Details

**Describe the bug**
this is a bug with the waterwalking/lavawalking enchant. the boots also work in spectator gamemode.

**To Reproduce**
get boots with waterwalking/lavawalking, go in spectator als fly trough the water/lava
**Screenshots / Video**
![image](https://user-images.githubusercontent.com/58041219/122671620-ec6a0400-d1c7-11eb-998f-7c37121a1ff9.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/acewerenez
- Server log: there are no errors

**Comment by Insprill** [comment]
Fixed in the next update
