### ISSUE TITLE
Fly enchant doesnt work

### ISSUE THREAD

**Issue by Kesims** [GC-spigot/AdvancedEnchantments#2067]
## Details

**Describe the bug**
Fly enchant stopped working after an update. It sends message multiple times when boots are equiped, but doesnt perform fly action.

**To Reproduce**
Enchant boots with enchant (shown bellow), try to fly.

`povzneseni:
  display: '%group-color%Povznesení'
  description: "Umožňuje létat."
  applies-to: 'Boty'
  type: 'EFFECT_STATIC'
  group: 'LEGENDARY'
  applies:
    - ALL_BOOTS
  levels:
    1:
      effects:
        - 'FLY'
        - 'MESSAGE:&eEnchant &6povznesení &ebyl rozpoznán! Příjemný let!'
`

**Screenshots / Video**
https://youtu.be/pNbjaM_rJPg

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ciqoxicupo
- Server log: https://mcpaste.io/a52f36e08c84b019

**Comment by Insprill** [comment]
You have `WorldGuardExtraFlags` with the FLY flag set to false in the global region. You need to set that to allow for FLY to work

**Comment by Kesims** [comment]
Okay, thank you, that solved half of the problem! :) But it is still spamming message when the boots are equiped (as in the video). What should I do with that?

**Comment by Kesims** [comment]
Here is an additional info about the spamming: whenever you change possition in hotbar, it sends 2 messages (i guess 1 disable and right after that 1 enable message).

https://youtu.be/RFP4CBjSc8Q

**Comment by Kesims** [comment]
Also, wtf? When I allow fly in flags, than everyone can fly, even without the enchant...

**Comment by Insprill** [comment]
Sounds like WEGF just handles the flag poorly, ill add a toggle for if AE should use it. as for the spam, working on a fix

**Comment by Kesims** [comment]
Hello, has the issue been resolved, or do we have to wait? I havent seen any news about it in update logs. Has the option to disable the WEGF hook been already added? Or can I somehow fix it myself? Players are complaining a lot about enchant not working.. :/
Thanks.

**Comment by Insprill** [comment]
It's fixed for the next update. GC didn't pull my changes for .9
