### ISSUE TITLE
Telepathy = unbreakable

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2068]
## Details

**Describe the bug**

If you have telepathy on your weapon just right click and bam full dura ! 
**To Reproduce**

Grab a diamond pick and a telepathy book apply it and mine a block and bam unbreakable
**Screenshots / Video**

don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 

ae 8.3.1
server: 1.8.8 taco

**Comment by LuluxClient** [comment]
> Can you send a video of this? I'm not sure what you're trying to say but TP_DROPS is using durability correctly for me.

Ill do this tomorrow

**Comment by LuluxClient** [comment]
enchant : https://pastebin.com/EcvR59cz

Video : https://gyazo.com/6f3b44b70ba9c23bbf05dc2f52e8aa40

**Comment by Insprill** [comment]
Does experimental block breaking have an effect on it?

**Comment by LuluxClient** [comment]
> Does experimental block breaking have an effect on it?

yes I just tried if it's off the tool is no longer unbreakable

**Comment by Insprill** [comment]
Do you know about when this issue started happening?

**Comment by Insprill** [comment]
Fixed for the next update
