### ISSUE TITLE
Duplicate Enchants from Enchatment Table

### ISSUE THREAD

**Issue by Blazaddo** [GC-spigot/AdvancedEnchantments#2069]
## Details

**Describe the bug**
When I ue the enchantment table it duplicates the enchants like crazy. (Not sure if this has something to do with the not-applyable-with setting not working properly.)

**To Reproduce**
First create a test group that will be activated 100% of the time in the enchantment tabel so the results can be found faster. Second enchant chestplates in the enchantment table and occasionally both of these enchants will appear (even with the not-applyable-with setting, this may be a seperate bug but may be intertwined so I left t in here.), and the custom enchants appear multiple times.

**Screenshots / Video**
Here is a screen shot of how many enchants were placed.
![AE error](https://user-images.githubusercontent.com/75510990/122685690-a1092300-d1d2-11eb-87b8-51c9d76c4e70.png)

Here is my enchantment table config, there should only be a max of 3 enchants, which I assume mean no repeats which is obviously not happening here: https://mcpaste.io/662b799455c2b0b8

Here are two test enchantments I've tried using for this setting: https://mcpaste.io/0cbce2432c174bbe

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/irunehogun 
- Server log: https://mcpaste.io/5c0da7eb0b9d5c36

**Comment by Blazaddo** [comment]
Not sure if it has something to do with the not-applyable-with setting not working as well, if you cans ee that is also off in there?

**Comment by Blazaddo** [comment]
Update, it towned down after a server restart, but still ocassionally gives s single duplicate as shown:
![AE Error Duplicate](https://user-images.githubusercontent.com/75510990/122695352-c5322780-d205-11eb-84f5-cb567cc672cb.png)

**Comment by Insprill** [comment]
Should be fixed as of 8.3.5
