### ISSUE TITLE
RIGHT_CLICK limited for Armor

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#2070]
## Details

**Describe the bug**
Testing RIGHT_CLICK enchants and seems that when applied to ARMOR it only triggers when aiming at blocks.
RIGHT_CLICK with mainhand items are responsive luckily.

**To Reproduce**
- Apply this enchant to boots, wear them and proceed to Right Clicking. Aim in different directions, it will proc more often when aiming at the floor. Aiming in the air even after the 2 second cooldown may not proc.
- Apply this enchant to any held item and it will proc no matter the direction.

dash:
  display: '%group-color%Dash'
  description: "Boost yourself into forward by right-clicking."
  applies-to: 'Boots'
  type: 'RIGHT_CLICK'
  group: 'LEGENDARY'
  applies:
    - ALL_BOOTS
  levels:
    1:
      cooldown: 2
      effects:
        - 'BOOST:UP:5'
        - 'WAIT:4'
        - 'PLAY_SOUND:ITEM_TRIDENT_RIPTIDE_1:0.7'
        - 'BOOST:FORWARD:25'
        - 'POTION:SPEED:3:40'

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/olisikahik
- Server log: https://mcpaste.io/658b82b837ddb375

**Comment by Insprill** [comment]
This, unfortunately, isn't possible to fix at the moment due to the fact that the PlayerInteractEvent isn't fired when right-clicking air with an empty hand.
