### ISSUE TITLE
Shift-clicking HELD enchanted items out of containers does not apply effects

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2071]
## Details

**Describe the bug**
When shift-clicking an item with a HELD enchant out of a container (verified to work with enderchests) and into your hand, the effects are not applied, and the item can still be used.

**To Reproduce**
With an empty hotbar, equip ninth slot. Put an item with a HELD enchant in an enderchest, and then shift + click it into your inventory. It should go into your ninth slot and automatically equip it, without applying any effects.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/kixajijuwi

**Comment by Insprill** [comment]
Fixed in the next update
