### ISSUE TITLE
Enchantment table ignoring not-applyable-with

### ISSUE THREAD

**Issue by Blazaddo** [GC-spigot/AdvancedEnchantments#2072]
## Details

**Describe the bug**
To my knowledge, the not-applyable-with setting is supposed to prevent enchantments from being applied if the specified enchantment is already on the item. I have not tested this with the enchanter, however, with the enchantment table this setting is not functioning properly for me.

**To Reproduce**
Enchant two enchants with this setting through the enchantment table (as will be show in configuration) and sometimes they are both applied to an item when only one should be.

**Screenshots / Video**
![AE error NAW](https://user-images.githubusercontent.com/75510990/122695606-7afd7600-d206-11eb-921b-5186da977851.png)

Configuration Info: https://mcpaste.io/9498e45cef3f50ce

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/kazecawaco
- Server log: https://mcpaste.io/20855c708edc5250

**Comment by GC-spigot** [comment]
Fixed
