### ISSUE TITLE
Enchanting Table Out of Bound number of Enchants

### ISSUE THREAD

**Issue by Blazaddo** [GC-spigot/AdvancedEnchantments#2073]
## Details

**Describe the bug**
You can recieve more enchants from the enchantment table than what is set in the configuration.

**To Reproduce**
Just try enchanting with the enchantment table (on a higher rating, I've done 80 or higher for Advanced Enchants)

**Screenshots / Video**
There are 5 Advanced enchants, the config should only allow 1-3:
![OOBE error AE](https://user-images.githubusercontent.com/75510990/122696137-f90e4c80-d207-11eb-8bc2-83908d8ea17a.png)

Config Info: https://mcpaste.io/d105107dd884df85

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/kazecawaco
- Server log: https://mcpaste.io/20855c708edc5250

**Comment by Insprill** [comment]
This should be fixed as of a few updates ago. Comment and I'll reopen if it isn't.
