### ISSUE TITLE
Repeating type is no longer working

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2074]
## Details

**Describe the bug**

The repeating type is no longer working.

**To Reproduce**

try this enchant it won't work anymore
https://pastebin.com/Pc6cZ2AW

**Screenshots / Video**

Don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
Ae : 8.3.1
Server ver : 1.8.8 tacospigot

**Comment by Insprill** [comment]
Fixed in the next update
