### ISSUE TITLE
WorldGuard restriction not working.

### ISSUE THREAD

**Issue by Miwasak** [GC-spigot/AdvancedEnchantments#2075]
Running WorldGuard 7.0.6-SNAPSHOT and WorldGuard Extra Flags 4.1.5
Paper version git-Paper-"1830de5" (MC: 1.17) 

The plugin is bypassing worldguard protected area, so player can destruct everywhere (or planting plant everywhere with planter enchantment)

**Comment by Insprill** [comment]
Fixed in the next update
