### ISSUE TITLE
VeinMiner Duping Spawners

### ISSUE THREAD

**Issue by chrisraj1** [GC-spigot/AdvancedEnchantments#2076]
I believe that Telepathy or another custom enchant is duping spawners when used the SilkSpawners. I am running AdvancedEnchantments version 8.3.2, Purpur version git-Purpur-1169, and SilkSpawners version 7.0.0. The video below is one of my players replicating this.

https://youtu.be/mNCJGVSnPpY

**Comment by Insprill** [comment]
Please do "/ae plinfo" and send the link, and does experimental-block-breaking have an effect?

**Comment by chrisraj1** [comment]
I apologize. It was actually VeinMiner causing the issue. experimental-block-breaking does not have an effect. I have attaced an updated clip.
https://paste.md-5.net/vupolihuke
[https://youtu.be/wMNOBAZAhtE](url)

**Comment by Insprill** [comment]
Oh thats not good. Are spawners in vein miners whitelist in the config?

**Comment by chrisraj1** [comment]
They are not whitelisted
![5A7A8C41-7EA8-460E-9060-F6663F30B2A3](https://user-images.githubusercontent.com/80594307/123025927-63aabe00-d3a9-11eb-89d4-fc0558b467e4.jpeg)

**Comment by chrisraj1** [comment]
I looked into it a little more. VeinMiner III drops 2 spawners of the same kind and 1 blank spawner. For example, If I broke a zombie spawner, it would drop 2 zombie spawners and 1 blank spawner. When you place the blank spawner down it turns into a pig spawner. VeinMiner I & II do the same thing but at a lower chance. It is always 1 spawner (like it should react) or 3 spawners.

**Comment by Insprill** [comment]
Fixed in the next update
