### ISSUE TITLE
Take Off Dont Work - Fly Effect

### ISSUE THREAD

**Issue by xXDarkCvBxX** [GC-spigot/AdvancedEnchantments#2077]
Advanced Enchantments V8.3.3

It seems that the Fly effect is not working correctly, the enchantment has 1 message to warn the player, in my case the message arrives but the Fly never works.

The enchant : 

takeoff:
  display: '&7Take Off'
  description: 'Te permite volar cuando las equipas.'
  applies-to: 'Botas'
  type: 'EFFECT_STATIC'
  group: 'HEROIC'
  applies:
    - ALL_BOOTS
  levels:
    1:
      effects:
        - 'FLY'
        - 'MESSAGE:&aTu modo fly a cambiado!'

**Comment by Insprill** [comment]
That's WorldGuardExtraFlags' FLY flag blocking it. Will add an option to bypass soon
