### ISSUE TITLE
[FEATURE REQUEST] Bow/Crossbow/Trident Load Time

### ISSUE THREAD

**Issue by Blazaddo** [GC-spigot/AdvancedEnchantments#2078]
## Details

**Request**
Add an effect that allows the configureer to change how short or long it take to pull back the bow,cross bow string, and the trident throw.

**Useful**
It would help with a quickshot enchant, or maybe power shot where it takes longer but does a lot of damage, I could see it being used creatively for many things reguarding these weapons.

**Comment by Insprill** [comment]
Feature requests are closed and this is already implemented in vanilla with the Quickcharge enchantment.
