### ISSUE TITLE
AntiCheat false positives with custom enchantments

### ISSUE THREAD

**Issue by ocyt** [GC-spigot/AdvancedEnchantments#2079]
## Details

**Describe the bug**
Custom enchantments from AdvancedEnchantments are being detected as hacked and punishing players. Detections I've noticed were jump, speed, motion, timer, and transaction; there may be more. Some enchants that could be triggering these detections (but I'm sure there's a lot more than just these): Launch, Inquisitive, Abiding, Fuddle, Slayer, Featherweight, Death Punch, Bone Crusher, Ward, Guardian, Plummet, Convulse, Springs. There's a few to hopefully get a start on these false detections!

**To Reproduce**
 Install AdvancedEnchantments with default enchants pack (https://ae.advancedplugins.net/enchantments/list-of-enchantments/default-enchants-200+) with the default Vulcan config (found in their Discord server). Different enchantments trigger different detections (obviously).

**Screenshots / Video**
N/A

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/upefufufac 
- Server log: https://paste.md-5.net/bugezusedu.md

**Comment by Insprill** [comment]
Fixed for the next update
