### ISSUE TITLE
Apply dust on stacked books

### ISSUE THREAD

**Issue by Frostyeiz** [GC-spigot/AdvancedEnchantments#208]
Sometimes when player open enchantment books, they get a book with the same kind, same success/destroy rate, make it stack together, this can be fixed easily by changing enchantment book "book" into "enchanted book", but it might affect my server as I use "book" for AEnchantment books
When the player applies dust into that book stack, the dust & a book from the stack disappear into the abyss.

**Comment by GC-spigot** [comment]
Fixed in next update.
