### ISSUE TITLE
Error while /ae view without any params

### ISSUE THREAD

**Issue by Zoro-6191** [GC-spigot/AdvancedEnchantments#2080]
## Details

**Describe the bug**
Errors in console for not providing any params

**To Reproduce**
Type `/ae view` without any other parameters.

**Screenshots / Video**
![Console Error](https://user-images.githubusercontent.com/52291201/123094424-804b0280-d44a-11eb-9782-51d764654798.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/inuhizifag
- Server log: https://mcpaste.io/43f59752d35e6dc0

**Comment by Insprill** [comment]
Fixed in the next update
