### ISSUE TITLE
MORE_DROPS effect does not work with Crops

### ISSUE THREAD

**Issue by Blazaddo** [GC-spigot/AdvancedEnchantments#2082]
## Details

**Describe the bug**
MORE_DROPS and MINING does not work when used on crops.

**To Reproduce**
Make an enchantment with MORE_DROPS, break a crop with it, and it doesnt activate more drops (my specific enchant will be listed lower).

**Screenshots / Video**
Here is the enchantment I used (harvest 3 to test, make sure crops are fully grown): https://mcpaste.io/efd8af0d890c1df0

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ibodasazeb
- Server log: https://mcpaste.io/798992ac0d1d98e8

**Comment by Insprill** [comment]
This isn't a bug, MORE_DROPS doesn't work on any blocks players have placed to prevent dupes
