### ISSUE TITLE
SMELT effect does not work on the 1.17 Raw_Iron and Raw_Gold

### ISSUE THREAD

**Issue by Blazaddo** [GC-spigot/AdvancedEnchantments#2083]
## Details

**Describe the bug**
The SMELT effect dows not smelt iron mine from raw iron or raw gold.

**To Reproduce**
Enchant something with 100% on Smelt effect, then mine raw iron or gold and it does not smelt.

**Screenshots / Video**
Here is the enchant I used: https://mcpaste.io/13dbc5ff3cd0f7b7

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/uxelanopuk
- Server log: https://mcpaste.io/311e3ac644a6e50c

**Comment by Insprill** [comment]
Fixed for the next update
