### ISSUE TITLE
Strange Thing happening

### ISSUE THREAD

**Issue by jamesipod** [GC-spigot/AdvancedEnchantments#2084]
## Details

**Describe the bug**
Error in Console

**To Reproduce**
No idea. Lots of players on, using AE stuff. Can't really figure out what it is. 
**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/idefapovik
- Server log: https://mcpaste.io/4a49dc41d7720b22

**Comment by Insprill** [comment]
Update AE
