### ISSUE TITLE
MobTrak + Crossbow

### ISSUE THREAD

**Issue by Pandas0** [GC-spigot/AdvancedEnchantments#2086]
## Details

**Describe the bug**
Mobtrak not applicable to CROSSBOW

**To Reproduce**
Get a CROSSBOW and a Mobtrak and try to apply the mobtrak to the crossbow

**Screenshots / Video**
N/A

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/uzesarayex
- Server log: No errors / Don't see the need for it

**Comment by Insprill** [comment]
Fixed in the next update
