### ISSUE TITLE
Random error when reloading (/ae reload)

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2087]
## Details

**Describe the bug**

Getting this error: https://pastebin.com/cLnf1pzY
**To Reproduce**

do /Ae reload
**Screenshots / Video**

don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae: 8.3.5
server: 1.8.8 tacospigot

**Comment by Insprill** [comment]
Fixed for the next update
