### ISSUE TITLE
Error when enchanting an item

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2088]
## Details

**Describe the bug**

Getting this error when I'm trying to enchant an item @ level 30
**To Reproduce**

enchant a diamond pickaxe
**Screenshots / Video**

https://pastebin.com/ikFBuE4F 

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae: 8.3.5
server ; 1.8.8 tacospigopt

**Comment by Insprill** [comment]
How often does this happen and can you send your enchantmentTable.yml?

**Comment by LuluxClient** [comment]
> How often does this happen and can you send your enchantmentTable.yml?

Fixed in 8.4.0
