### ISSUE TITLE
BlockTrak Duping

### ISSUE THREAD

**Issue by dm1lk** [GC-spigot/AdvancedEnchantments#2090]
## Details

Yes I know this is a duplicate issue but I looked at both and found that this might? provide slightly more insight into the issue.

**Describe the bug**
The BlockTrak lore duplicates everytime you mine a block with trench.

**To Reproduce**
Get a pickaxe with BlockTrak and Trench, then mine multiple blocks, you should end up having multiple lines of lore saying "BlockTrak".

**Screenshots / Video**
![Screenshot 2021-06-26 235720](https://user-images.githubusercontent.com/77703500/123527795-43953a80-d6da-11eb-8d0e-c5ee9a34f49a.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/obafagesur
- Server log: https://mcpaste.io/85fba08866ae8096

**Comment by dm1lk** [comment]
Also of note, my server log was too large to upload to mcpaste.io, sorry about that!

**Comment by Insprill** [comment]
Duplicate if #2064. Please comment all this info on that issue.
