### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by itsILAN** [GC-spigot/AdvancedEnchantments#2093]
Hey, 
1. if the black and white scrolls are empty map item if u right click it in build able world its just changing it to the map item.
2. And the Enchant bleed steel damaging players after they respawn in spawn.
3. and also when u open a random book the fireworks effect breaks armorstands.

**Comment by Insprill** [comment]
Please don't put multiple bugs into one issue, and you need to follow the format in the future or your reports will be ignored.

**Comment by itsILAN** [comment]
> Please don't put multiple bugs into one issue, and you need to follow the format in the future or your reports will be ignored.

got it.

**Comment by itsILAN** [comment]
> Please don't put multiple bugs into one issue, and you need to follow the format in the future or your reports will be ignored

where do i see the format

**Comment by Insprill** [comment]
When you create a new bug report it's already there

**Comment by Insprill** [comment]
All issues fixed for the next update.
