### ISSUE TITLE
Putting on or taking off armor restores a player to full HP

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2095]
## Details

**Describe the bug**
Putting on or taking off armor restores a player to full HP

**To Reproduce**
1.) Lose health
2.) Put on or take off armor

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/qegovexori
- Server log: https://mcpaste.io/d7e9e7735d26392b

**Comment by Insprill** [comment]
Fixed in the next update
