### ISSUE TITLE
Enchantment Book not taken when applying to equipped helmet and /hat Plugin (40k download) applied in player.

### ISSUE THREAD

**Issue by chromity** [GC-spigot/AdvancedEnchantments#2096]
## Details

**Describe the bug**
enchantment book is not taken when applying to equipped helmet with /hat applied to player. 

https://www.spigotmc.org/resources/hat.33980/ (40k+ download, 1.17 updated.).

**To Reproduce**
1. Equip helmet.
2. Use /hat.
3. Drag AE book to equipped helmet in inventory. 
4. AE Book is not consumed.

**Comment by Insprill** [comment]
The way the event gets called makes it nearly impossible for us to know what other plugins are doing with it so I'm gonna deny this because it's not that bad for players to need to take it off to apply enchants and it's not worth the possible issues it could cause.
