### ISSUE TITLE
Error if I enchant @ level 30

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2097]
## Details

**Describe the bug**

If I enchant an item @ level 30 I get this error https://pastebin.com/4Nx07TZE and also sometimes I get 4 enchants at once (idk if it's normal)
**To Reproduce**

Enchant one item @ level 30 
**Screenshots / Video**

https://pastebin.com/4Nx07TZE

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae : 8.3.8
Server ver: 1.8.8 TacoSpigot

**Comment by Insprill** [comment]
You already reported this, #2088
