### ISSUE TITLE
Armor Set Upgrades Not Working Properly (Makes armor weaker)

### ISSUE THREAD

**Issue by Seqentix** [GC-spigot/AdvancedEnchantments#2099]
Issue with AdvancedEnchantments armor upgrades:
The "Heroic Upgrade Crystal" makes the armor weaker since it transforms it into leather armor which only fills 3.5/10 armor bars while the default armor set fills 10/10. The latest AE version, running 1.16.5

The armor simply turns into default leather armor, the durability values from the setUpgrades.yml file do not apply.

**Comment by Insprill** [comment]
Fixed in the next update
