### ISSUE TITLE
Soul Tracker/BlokTrack/MobTrak/StatTrak Glitched out in 8.4.0

### ISSUE THREAD

**Issue by J14P** [GC-spigot/AdvancedEnchantments#2101]
## Details

**Describe the bug**
Whenever I applied a bloktrak tracker to my pickaxe it wasn't working and glitched out and added a new line of code to my pickaxe. Plus I am not able to apply the mobtrak tracker to my bow and I cannot put a new bloktrack tracker on pickaxes after updating to 8.4.0

**To Reproduce**
Spawn in any of the custom trackers and try to apply to an item

**Screenshots / Video**
![2021-06-30_21 32 41](https://user-images.githubusercontent.com/86026838/124051798-2cf92700-d9eb-11eb-9d52-506517f05694.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ufifosafog
- Server log: https://mcpaste.io/f81cb4e2b8d48847

**Comment by Insprill** [comment]
Fixed for the next update
