### ISSUE TITLE
enable bug

### ISSUE THREAD

**Issue by liliLimpan2000** [GC-spigot/AdvancedEnchantments#2103]
## Details

**Describe the bug**

the bug do so i cant use my plugin 
**To Reproduce**

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: 
https://paste.md-5.net/pequcifopo
- Server log: 
 https://mcpaste.io/25e29bfee5f472f7

**Comment by Insprill** [comment]
You have a syntax error most likely in the enchantments.yml.
