### ISSUE TITLE
Trackers Completely Broken

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2104]
## Details

**Describe the bug**
You can't apply trackers. And ones that people applied in previous versions are completely busted.

**To Reproduce**
1.) Do `/ae giveitem <name> blocktrak 1` or `/ae giveitem <name> stattrak 1`
2.) Try to apply them to appropriate weapon/tool

To get the problem in the screenshot
1.) Use version 8.3.9
2.) Do `/ae giveitem <name> blocktrak 1`
3.) Apply it to a tool
4.) Update to version 8.4.0
5.) Use the tool

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/124171938-d0d7e680-da6e-11eb-80c5-60df87e412b4.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/abikucuqad
- Server log: https://mcpaste.io/8a2a0a8514b0e0c0

**Comment by Insprill** [comment]
Them not being able to be applied is fixed for the next update, and them duplicating is already reported #2064

**Comment by WhatsTheBadNews** [comment]
@Insprill We don't have any enchantments that use the Trench effect
