### ISSUE TITLE
Anvil NPE getting rename text

### ISSUE THREAD

**Issue by divingross** [GC-spigot/AdvancedEnchantments#2105]
Getting an NPE from anvils trying to modify the result of AnvilInventory#getRenameText which is null.
https://pastebin.com/JB9ZNDiz

AE: 8.3.9
Server: Paper-1.16.5

**Comment by Insprill** [comment]
Please follow the provided format next time or your issue will be closed.

**Comment by divingross** [comment]
first time using github, bare with me

**Comment by Insprill** [comment]
Fixed in the next update
