### ISSUE TITLE
TP_DROPS doesn't increment statistics

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2106]
## Details

**Describe the bug**

If you mine a block with telepathy it won't count as you mining 1 block in the statistic placeholder wich is %statistic_mine_block% 

(https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#statistic)
**To Reproduce**

Mine a block with telepathy 
**Screenshots / Video**

Don't need.

## Server Information

Ae : 8.4.0
Serveur : 1.8.8 TacoSpigot

**Comment by Insprill** [comment]
does experimental-block-breaking have an effect on this?

**Comment by LuluxClient** [comment]
> does experimental-block-breaking have an effect on this?

Ill try when I can (sleeping atm ahah)

**Comment by LuluxClient** [comment]
> does experimental-block-breaking have an effect on this?

Nop it doesn't after testing it.

**Comment by Insprill** [comment]
Looks like it just isn't adding to the actual statistic, which papi gets it's info from

**Comment by LuluxClient** [comment]
> Looks like it just isn't adding to the actual statistic, which papi gets it's info from

How does telepathy works, what event does it use since a lot of my plugins are bugged because of that..

**Comment by Insprill** [comment]
Listens to the BlockBreakEvent. With experimental-block-breaking enabled it doesn't cancel the event so i don't know why it wouldn't increment the stat

**Comment by Insprill** [comment]
Fixed in the next update
