### ISSUE TITLE
All weapons and armorsets are invalid after the 8.4.0 update

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2107]
## Details

**Describe the bug**
I have updated to 8.4.0 last night, once I woke up people told me the vote crates no longer worked.
Apparently the command to retrieve my weapons or armorsets return ''Invalid'' and the plugin can only find the default weapons and armorsets.

**To Reproduce**
Not exactly sure, update?

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/eledayakan
- Server log: https://mcpaste.io/2a7c12c950817817

My armorsets and weapons:
[AdvancedEnchantments_July_2021.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/6750318/AdvancedEnchantments_July_2021.zip)

**Comment by GC-spigot** [comment]
Fixed next update
