### ISSUE TITLE
Newest update in AE is not 1.16 and earlier Particle-friendly

### ISSUE THREAD

**Issue by FighterPilot50** [GC-spigot/AdvancedEnchantments#2108]
## Details

**Describe the bug**
Particles that have different names in 1.17 compared to 1.16 are not loading in AE - such as explosion and smoke, which have different names in 1.17, but if 1.17 names are used in 1.16 it still doesn't function.

**To Reproduce**
Use any particle effect that has a different name in 1.17 compared to 1.16 (in a 1.16 or earlier server)

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/regimolafo
- Server log: https://mcpaste.io/41b05172b02f56de

**Comment by Insprill** [comment]
That's down to Bukkit changing the names. You can find the 1.17 particles [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html) and for other versions go [here](https://helpch.at/docs/1.12.2/org/bukkit/Particle.html) replacing the version in the URL with the one you want.
