### ISSUE TITLE
TP_DROPS Damages items when it shouldn't

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2109]
## Details

**Describe the bug**
Enchanting an item with a TP_DROPS enchant will cause it to lose durability when it normally wouldn't. For example, a regular hoe breaking wheat will not lose durability, but one with a TP_DROPS enchant does.

**To Reproduce**
Enchant a hoe with a TP_DROPS enchant, break wheat. The hoe will lose durability.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ratozejidi

**Comment by Insprill** [comment]
Fixed for the next update

**Comment by Dakotaa** [comment]
It appears this was fixed for hoes, but breaking crops with a TP_DROPS tool still damages axes, pickaxes, etc. when these tools are not regularly damaged when breaking crops.

Also, apparently this fix has caused mcMMO herbalism experience to no longer be rewarded when breaking crops with TP_DROPS tools.
