### ISSUE TITLE
Latest update is less compatible with NoCheatPlus

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2110]
## Details

**Describe the bug**
When using 8.4.0, I'm having issues with players being kicked from the server by NCP for "block breaking out of sync". This specifically happens when they use a TRENCH tool.

**To Reproduce**
Use AE 8.4.0 with NCP, try to mine with a TRENCH tool.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/matipawaye
- Server log: https://mcpaste.io/96915e494cd3895d

**Comment by LuluxClient** [comment]
Don't use NCP ! quite laggy and broken

**Comment by Dakotaa** [comment]
> Don't use NCP ! quite laggy and broken

From the multiple paid, popular anticheats I've tried for 1.16, NCP is still the least resource-intensive and has the fewest false positives.

**Comment by Insprill** [comment]
Fixed for the next update
