### ISSUE TITLE
[Issue] Health Boost Problem (Overload)

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#2111]
## Details

**Describe the bug**
When i wore overload enchantment it just inverts my health instead of adding health. 

**To Reproduce**
Just wore overload or godly overload armor.

**Screenshots / Video**
https://youtu.be/G1lEo5RHVAg

## Server Information
- Server Version: [PaperSpigot 1.12.2]
- Plugin Version: 8.3.9. It also works on 8.4.0

**Comment by Starkenz** [comment]
The issue related to #2102 #2054

**Comment by Insprill** [comment]
Duplicate of #2102

**Comment by Starkenz** [comment]
Hello, why is this issue closed? Is it completely server problem?

**Comment by Insprill** [comment]
It was closed since it's a duplicate of another issue. We only allow one issue per bug/ feature request to keep organized and find things easier
