### ISSUE TITLE
Bug with planter enchant whan inventory is full

### ISSUE THREAD

**Issue by Miwasak** [GC-spigot/AdvancedEnchantments#2112]
When we have the inv full **except** 1 slot with 1 or 2 seeds, the planter enchant does not use seed at all

there is a small video who show the bug: https://youtu.be/SGdBy2Az9QY

_PS: I also tried in survival, its not a creative bug, i'm in creative only for the vid'_

**Comment by Insprill** [comment]
Fixed for the next update
