### ISSUE TITLE
Mobtrak wont work on tridents as of 8.4.1

### ISSUE THREAD

**Issue by J14P** [GC-spigot/AdvancedEnchantments#2113]
## Details

**Describe the bug**

I am not able to apply a mobtrak tracker to tridents. When I try to drag and drop the tracker it just swaps places with the trident instead of applying.
**To Reproduce**

Try to put a mobtrak tracker on a trident.
**Screenshots / Video**

https://user-images.githubusercontent.com/86026838/124314816-f59c8e80-db40-11eb-80a7-4caae981bddf.mp4

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ocojubifoz
- Server log: https://mcpaste.io/02a45f95ec690f7c

**Comment by Insprill** [comment]
Fixed for the next update
