### ISSUE TITLE
Incompatibility with togglepvp plugins

### ISSUE THREAD

**Issue by celciusjj** [GC-spigot/AdvancedEnchantments#2115]
Hi anyway to disable Ae with deluxe combat with togglepvp
The users die for enchantments without pvp, this in previous versions did not happen

I install the version 8.2.7 and dont bypass
but in the new version bypass the ae and kill the user.

I think the functionality that causes it to break is ADD_HARM because enchantments like bleed, double hit are the ones that kill the player, not the direct hit.

![image](https://user-images.githubusercontent.com/37490999/124361626-816ff280-dbf5-11eb-9eda-8e41e5ebf558.png)

**Comment by celciusjj** [comment]
Today I returned to the minecraft servers, and the bug is still present. Try trying other toggle pvp plugins

**Comment by celciusjj** [comment]
![image](https://user-images.githubusercontent.com/37490999/147025032-a3de0130-0113-4249-accf-16d07704716a.png)

**Comment by Insprill** [comment]
I am no longer the developer so you'll have to wait for GC.

**Comment by celciusjj** [comment]
I think that it is a issue for deluxe combat that is my pvp plugin, because i try to with pvp manager and this does not happens
