### ISSUE TITLE
Ae overrides BanItem and bypasses the protection of ae

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2116]
## Details

**Describe the bug**

If you try enchanting an item that can't be enchanted for example you banned "leather armor" to be enchanted it bypasses the check if you get a custom enchant on your item and it also bypasses the enchant limitation of AE even it has this in the lore : 
enchantLimitation:
  enabled: true
  lore: '&4[!] Enchantements runiques incompatibles.'
  

**To Reproduce**

Enchant an item that is banned in banitem & on the EnchantLimitation in an enchant table and it will work

**Screenshots / Video**

https://gyazo.com/50cb8944b86fce077b4074f7364811f3

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae: 8.4.2
Server; 1.8.8

**Comment by Insprill** [comment]
Support added in the next update.
