### ISSUE TITLE
God kits cooldown broken in 8.4.2 for 1.17

### ISSUE THREAD

**Issue by JazzBroMC** [GC-spigot/AdvancedEnchantments#2117]
The god kit cooldowns do not work. They were working perfectly fine before i updated from version 8.3.4

I then tried going back on 8.3.4 and the cooldowns work again on it but not 8.4.2

I am using paper build 68 minecraft 1.17

I also have a server running on 1.12.2 it did not have this problem so i think it's just related to 1.17

There was no console errors either.

**Comment by Insprill** [comment]
Fixed in the next update
