### ISSUE TITLE
Essentials /heal does not work with Overload

### ISSUE THREAD

**Issue by Complex1tive** [GC-spigot/AdvancedEnchantments#2118]
## Details

**Describe the bug**
When using the essentials /heal command, the player does not get healed to full health.

**To Reproduce**
Have a Purpur 1171 server with AdvancedEnchantments 8.4.3 and Essentialsx 2.18.2.0. Execute /heal.

**Screenshots / Video**
https://i.imgur.com/5fX0vTt.mp4

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/paguzepazi
- Server log: https://bin.bloom.host/ejecacikut.yaml

**Comment by Insprill** [comment]
This isn't a bug, but I'll implement it. Essentials only heals you to 20 points and removes all potion effects so this normally wouldn't be an issue, either way, fixed/ added for the next update
