### ISSUE TITLE
Stone duplicating when using smelting 3 fortune 3 pickaxe with fortune-works-on-iron-gold set to true

### ISSUE THREAD

**Issue by iiPyro** [GC-spigot/AdvancedEnchantments#2120]
## Details

**Describe the bug**
To preface this only happens with fortune-works-on-iron-gold set to true. On my server I have a pickaxe with smelting 3 and fortune 3 and several other enchants whenever I mine normal stone or cobblestone the fortune has a chance to proc giving multiple cooked stone for both. It doesn't matter if it is player placed or naturally generated also.

**To Reproduce**
Get the pickaxe posted in the below screenshot and mine stone and or cobblestone with fortune-works-on-iron-gold set to true.

**Screenshots / Video**
https://user-images.githubusercontent.com/86937282/124406866-566dc780-dcf7-11eb-95c9-317bef74c2d7.png
https://user-images.githubusercontent.com/86937282/124407288-60dc9100-dcf8-11eb-96f8-24d7787ee154.mp4

## Server Information
https://paste.md-5.net/ufawenohog
https://mcpaste.io/329fff10af1ae313

**Comment by Insprill** [comment]
Fixed for the next update
