### ISSUE TITLE
Getting spike on the 1.17 server till crashed whenever plugin is installed

### ISSUE THREAD

**Issue by pakgm** [GC-spigot/AdvancedEnchantments#2121]
Hi there! Recently our 1.17 server installed AE plugins, but the admin said it was unstable and caused a lot of crashes. Here is the log. Can you help?

Thanks!
[message.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/6762737/message.txt)

**Comment by GC-spigot** [comment]
Will be fixed in next update.

**Comment by pakgm** [comment]
Do you have any estimation when will the next update released?

**Comment by GC-spigot** [comment]
Few hours

**Comment by pakgm** [comment]
Thank you

**Comment by pakgm** [comment]
Hello there, is the error fixed on the 8.4.4?
