### ISSUE TITLE
Enchant packs missing groups

### ISSUE THREAD

**Issue by NathanF03** [GC-spigot/AdvancedEnchantments#2123]
## Details

**Describe the bug**
All enchants in enchantments bundle 1 does not download while some enchants on other bundles do not download either.

**To Reproduce**
Using most recent version of plugin with 1.17 spigot server.

**Screenshots / Video**
<html>
<body>

</body>
</html>

## Server Information
- "/ae plinfo" link: 
https://paste.md-5.net/lomihozuhe
- Server log: 
[14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "venom" enchantment! Reason: specified group "BASIC" does not exist!
--
428 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "inky" enchantment! Reason: specified group "BASIC" does not exist!
429 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "quickdraw" enchantment! Reason: specified group "BASIC" does not exist!
430 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "ravenous" enchantment! Reason: specified group "BASIC" does not exist!
431 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "explosive" enchantment! Reason: specified group "BASIC" does not exist!
432 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "furnace" enchantment! Reason: specified group "BASIC" does not exist!
433 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "glowing" enchantment! Reason: specified group "BASIC" does not exist!
434 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "diver" enchantment! Reason: specified group "BASIC" does not exist!
435 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "saturated" enchantment! Reason: specified group "BASIC" does not exist!
436 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "freeze" enchantment! Reason: specified group "BASIC" does not exist!
437 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "reflector" enchantment! Reason: specified group "BASIC" does not exist!
438 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "ghast" enchantment! Reason: specified group "BASIC" does not exist!
439 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "strength" enchantment! Reason: specified group "RARE" does not exist!
440 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "thor" enchantment! Reason: specified group "RARE" does not exist!
441 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "springs" enchantment! Reason: specified group "RARE" does not exist!
442 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "speed" enchantment! Reason: specified group "RARE" does not exist!
443 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "hefty" enchantment! Reason: specified group "RARE" does not exist!
444 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "nausea" enchantment! Reason: specified group "RARE" does not exist!
445 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "selfdestruct" enchantment! Reason: specified group "RARE" does not exist!
446 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "shield" enchantment! Reason: specified group "RARE" does not exist!
447 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "escapist" enchantment! Reason: specified group "RARE" does not exist!
448 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "kevlar" enchantment! Reason: specified group "RARE" does not exist!
449 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "counter" enchantment! Reason: specified group "RARE" does not exist!
450 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "summoner" enchantment! Reason: specified group "RARE" does not exist!
451 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "wolves" enchantment! Reason: specified group "RARE" does not exist!
452 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "pushed" enchantment! Reason: specified group "RARE" does not exist!
453 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "virus" enchantment! Reason: specified group "RARE" does not exist!
454 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "experience" enchantment! Reason: specified group "DIVINE" does not exist!
455 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "lifesteal" enchantment! Reason: specified group "DIVINE" does not exist!
456 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "immolation" enchantment! Reason: specified group "DIVINE" does not exist!
457 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "pyro" enchantment! Reason: specified group "DIVINE" does not exist!
458 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "barbarian" enchantment! Reason: specified group "DIVINE" does not exist!
459 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "enrage" enchantment! Reason: specified group "DIVINE" does not exist!
460 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "souvenir" enchantment! Reason: specified group "IMMORTAL" does not exist!
461 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "rage" enchantment! Reason: specified group "DIVINE" does not exist!
462 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "blast" enchantment! Reason: specified group "DIVINE" does not exist!
463 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "ninja" enchantment! Reason: specified group "IMMORTAL" does not exist!
464 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "blocking" enchantment! Reason: specified group "IMMORTAL" does not exist!
465 | [14:41:54] [Server thread/ERROR]: [AdvancedEnchantments] Failed to load the "protected" enchantment! Reason: specified group "IMMORTAL" does not exist!

**Comment by Insprill** [comment]
Going to close as this isn't a bug per se, more of a broken configuration. I will make sure GC knows about it though to update it.
