### ISSUE TITLE
Obsidian Destroyer Duplicating Obsidian

### ISSUE THREAD

**Issue by 69werdna** [GC-spigot/AdvancedEnchantments#2125]
**Describe the bug**
Obsidian duplicating? Attempting to break a obsidian with obsidian destroyer pickaxe will drop an obsidian and will not destroy the obsidian

**To Reproduce**
Enchant pickaxe with obsidian destroy and try to destroy an obsidian before it actually breaks. 

**Screenshots / Video**
https://youtu.be/HJ-lmyOAXjE

## Server Information
https://paste.md-5.net/jomalabere

**Comment by Insprill** [comment]
Fixed in the next update
