### ISSUE TITLE
Shift + clicking items into inventory gives HELD effects permanently

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2128]
## Details

**Describe the bug**
On the latest version, when shift + clicking an enchanted item with HELD potion effects from a container into the inventory, the effects are applied to the player permanently, and they stay even when the player moves the item out of their inventory.

**To Reproduce**
Enchant an item with a HELD enchantment that grants a potion effect, put the item in a chest, shift + click it in to the inventory. You will now have the effect permanently.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ipewupokag

**Comment by Insprill** [comment]
Fixed in the next update
