### ISSUE TITLE
Master Blacksmith healing mobs

### ISSUE THREAD

**Issue by Vehzx** [GC-spigot/AdvancedEnchantments#2129]
## Details

**Describe the bug**
When using master blacksmith, hitting a mob / animal will heal them when the enchant procs. Also just a heads up, in my log you will see devour enchant doesn't have it's tags and is pasting errors, I fixed this already but this log is still the latest one I can get so you will see it in the log.

**To Reproduce**
Use master blacksmith and hit a mob / animal.

**Screenshots / Video**
Here is a clip of it happening: https://clips.twitch.tv/BoringTsundereEmuThunBeast-2u12yUh4NWAZarQs

## Server Information
- "/ae plinfo" link: REQUIRED! Replace this with the command output's https://paste.md-5.net/usixuyuviv
- Server log: REQUIRED! Upload `logs/latest.log` to https://mcpaste.io/64ee8cadbe7bce1a/

**Comment by Insprill** [comment]
Please send the enchant
