### ISSUE TITLE
kill monsters by customenchant  is treated by natural death?

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2130]
## Details

**Describe the bug**
i'm using dungeonsxl plugin.
i was setted that player kill over 70% monsters, move into boss room.
but when player kill monster with custom enchanted weapons, dungeon plugin didn't count that.
this problem is dungeon? or advanced enchantment?

**Comment by Insprill** [comment]
Next updated I've changed how we apply damage to credit the attacker, but I also added a new option called `use-experimental-damage` that changes how we handle damage so if you could please give that a try and get back with your finding. Going to keep this open until i know one of those 2 changes fixes this
