### ISSUE TITLE
Plugins disables itself while running (Error)

### ISSUE THREAD

**Issue by DarkKingKaanMC** [GC-spigot/AdvancedEnchantments#2131]
## Details

**Describe the bug**

Plugin sometimes throws an error and disables itself. A server restart is required to make it work again.

**To Reproduce**

I wouldn't know a way to reproduce this issue, perhaps the error contains useful information for the developers. The plugin simply runs normally, then suddenly stops working.

**Screenshots / Video**

Here's the error: https://pastebin.com/jknQCye7

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/yuhuyusagi
- Server log:

**Comment by Insprill** [comment]
Not a bug. Firewall is blocking us from making license checks. Join out discord for more support.
