### ISSUE TITLE
Blocktrack is bug

### ISSUE THREAD

**Issue by gmovd** [GC-spigot/AdvancedEnchantments#2133]
Please solve this, blocktrack + trueminer
![2021-07-04_11 19 28](https://user-images.githubusercontent.com/50750719/125117507-a29d7b00-e0ee-11eb-945b-1a2d8f553e37.png)
after move this item on inventory
![20210708_014729](https://user-images.githubusercontent.com/50750719/125117607-c660c100-e0ee-11eb-9b19-cb3b4202111f.jpg)
Please solve this or 0 starts, how a plugin can ban player from my server (glith them)

**Comment by Insprill** [comment]
Duplicate of #2064
