### ISSUE TITLE
HALF_DAMAGE [Issue]

### ISSUE THREAD

**Issue by ArefyNetwork** [GC-spigot/AdvancedEnchantments#2134]
Hello, while installing latest version, HALF_DAMAGE stopped worked for me and prints and error on console every 5 seconds or so:

https://pastebin.com/JdHQ5udF

It was working in older versions, so I assume it's a bug on latest versions.

I'm using 1.8.8 paper

Enchant: https://pastebin.com/U0H87Czx

/aeplinfo: https://paste.md-5.net/hokeyuqamu

xNekio on spigot

Thanks!

## Details

**Describe the bug**

**To Reproduce**

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: 
- Server log:

**Comment by Insprill** [comment]
Please send the enchant you're using

**Comment by ArefyNetwork** [comment]
> Please send the enchant you're using

I attached it on a pastebin on the main post

**Comment by Insprill** [comment]
HALF_DAMAGE needs to be used with an ATTACK or DEFENSE type. You can't use it with RIGHT_CLICK since there is no damage to half
