### ISSUE TITLE
Vein miner bed dupe / duplication

### ISSUE THREAD

**Issue by SlyyJacob** [GC-spigot/AdvancedEnchantments#2136]
## Details

**Describe the bug**
Mining a bed with Vein miner enchantment duplicates said bed. Bed isn't on the whitelist (in config file) for vein miner.

**To Reproduce**
Mine a bed with Vein miner enchantment.

**Screenshots / Video**
https://user-images.githubusercontent.com/36818957/125200770-963f2c80-e26c-11eb-94e7-a235d9702bd1.mp4

## Server Information
https://paste.md-5.net/komohibaki

**Comment by Insprill** [comment]
Fixed in the next update
