### ISSUE TITLE
KillAura CE

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2138]
## Details

**Describe the bug**

KillAura CE kills any zombies nearby regardless of health amount, so for example we have bosses and minions, players are spamming the minions and its killing the bosses that have 2000+ HP just because it's nearby. I think you should fix this by making it deal 20 HP damage to nearby zombies, rather than outright killing them.

**To Reproduce**

Create a mob that has a ridiculous amount of HP and spawn regular zombies around it. Use KillAura CE on the regular zombies and watch the high HP mob die with them.

**Screenshots / Video**

N/A

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://paste.md-5.net/tarexucisa
https://mclo.gs/lQI2tyn

**Comment by gmovd** [comment]
this bug can kill 7k ender dragon

**Comment by Insprill** [comment]
Not a bug. That's just what the enchant does. If you don't like it, you can modify the enchantment to your liking. [Here](https://github.com/GC-spigot/AdvancedEnchantments/blob/master/Default%20Files/enchantments.yml#L4473) is where it's located in the enchantments.yml.
