### ISSUE TITLE
/ae admin not working, language pt-br not present

### ISSUE THREAD

**Issue by louanbastos** [GC-spigot/AdvancedEnchantments#2139]
https://user-images.githubusercontent.com/2886066/125205237-a26cbf00-e257-11eb-8a61-dff52647a4e1.mp4

I have a problem
the command /ae admin is not working correctly
There is no error on console
![unknown](https://user-images.githubusercontent.com/2886066/125205246-b6182580-e257-11eb-9546-94b66ccfe133.png)
I'm using the latest version of AE and the Purpur (paper fork)
It is not changing the plugin language even changing its settings and restarting the server.

**Comment by louanbastos** [comment]
anyone?

**Comment by Insprill** [comment]
Fixed for the next update
