### ISSUE TITLE
Armor Sets Issue regarding smelt effect

### ISSUE THREAD

**Issue by Spleggeti** [GC-spigot/AdvancedEnchantments#2141]
## Details

**Describe the bug**
When my armor sets proc the Auto smelt Effect, it instead makes my Pickaxe turn into a duplicate of the Helmet i am wearing. 

**To Reproduce**
So the Armor set that i currently use has the effect of when they mine an ore it's a 30% chance to auto smelt. But when it activates, the ore smelts but the Pickaxe i use gets replaced by a copy of the helmet i have on. I believe it might have something to do with the Auto TP drops plugin we have but i want to know if there is another thing causing a problem. Prison Inventory Plus is the plugin we use for Inventory stuff. 

Config for Armor Set:
name: '&8&lMiner''s Galore'
material: DIAMOND
settings:
equipped:
- '&4&l(&c&l!&4&l) &aYou have activated the &8&lMiner &7set &4&l(&c&l!&4&l)'
unequipped:
- '&4&l(&c&l!&4&l) &7You have deactivated the &8&lMiner &7set &4&l(&c&l!&4&l)'
items:
helmet:
name: '&8&lHard Hat of the Dedicated Miner'
lore:
- '&7Always wear your Hard Hat in the Mine!'
- ''
- '&8&lMiner''s Galore &7&lSET BONUS'
- '&7* Gain McMMO XP for MINING when Mining a block.'
- '&7* Smelts ores that have been mined.'
- '&7* Gain a Speed Boost'
- '&7&o(Requires all 4 &8Miner &7&oitems.)'
enchants: # Supports AdvancedEnchantments CE
- "protection:4"
- "unbreaking:3"
- "protection_fire:3"
- "mending:1"
chestplate:
name: '&8&lChestplate of the Galactic Guardian'
lore:
- '&7Strong Chestpiece to hold off the Boulders.'
- ''
- '&8&lMiner''s Galore &7&lSET BONUS'
- '&7* Gain McMMO XP for MINING when Mining a block.'
- '&7* Smelts Ores when Mined'
- '&7* Gain a Speed Boost'
- '&7&o(Requires all 4 &8Miner &7&oitems.)'
enchants: # Supports AdvancedEnchantments CE
- "protection:4"
- "unbreaking:3"
- "protection_projectile:3"
- "mending:1"
leggings:
name: '&8&lLeggings of the Miner'
lore:
- '&7Leggings of the Most dedicated Miner.'
- ''
- '&8&lMiner''s Galore &7&lSET BONUS'
- '&7* Gain McMMO XP for MINING when Mining a block.'
- '&7* Smelts Ores when Mined'
- '&7* Gain a Speed Boost'
- '&7&o(Requires all 4 &8Miner &7&oitems.)'
enchants: # Supports AdvancedEnchantments CE
- "protection:4"
- "unbreaking:3"
- "protection_projectile:3"
- "mending:1"
boots:
name: '&8&lSteel Cap Boots'
lore:
- '&7These boots were made to be roughed up.'
- ''
- '&8&lMiner''s Galore &7&lSET BONUS'
- '&7* Gain McMMO XP for MINING when Mining a block.'
- '&7* Smelts Ores when Mined'
- '&7* Gain a Speed Boost'
- '&7&o(Requires all 4 &8Miner &7&oitems.)'
enchants: # Supports AdvancedEnchantments CE
- "protection:4"
- "unbreaking:3"
- "protection_fire:3"
- "mending:1"
- "gears:3"
events:
MINING:
chance: 25
condition:
- '%block type% = STONE or %block type% = LEGACY_STONE : %allow%'
- '%attacker player_world% = world : %allow%'
effects:
- 'ADD_EXP_MCMMO:MINING:30'
MINING:
chance: 25
condition:
- '%block type% = COAL_ORE or %block type% = LEGACY_COAL_ORE : %allow%'
- '%attacker player_world% = world : %allow%'
effects:
- 'ADD_EXP_MCMMO:MINING:100'
MINING:
chance: 25
condition:
- '%block type% = IRON_ORE or %block type% = LEGACY_IRON_ORE : %allow%'
- '%attacker player_world% = world : %allow%'
effects:
- 'ADD_EXP_MCMMO:MINING:250'
MINING:
chance: 25
condition:
- '%block type% = GOLD_ORE or %block type% = LEGACY_GOLD_ORE : %allow%'
- '%attacker player_world% = world : %allow%'
effects:
- 'ADD_EXP_MCMMO:MINING:350'
MINING:
chance: 25
condition:
- '%block type% = REDSTONE_ORE or %block type% = LEGACY_REDSTONE_ORE : %allow%'
- '%attacker player_world% = world : %allow%'
effects:
- 'ADD_EXP_MCMMO:MINING:150'
MINING:
chance: 25
condition:
- '%block type% = DIAMOND_ORE or %block type% = LEGACY_DIAMOND_ORE : %allow%'
- '%attacker player_world% = world : %allow%'
effects:
- 'ADD_EXP_MCMMO:MINING:750'
MINING:
chance: 30
effects:
- 'SMELT'

Screenshots / Video
https://gyazo.com/e501a469e70f1731975ec4d9f3d84a1e

## Server Information
https://paste.md-5.net/hefiyoridu

Cannot include the Server Log due to it being on a server with alot of console logs. Doesn't come up with any errors in console.

**Comment by Insprill** [comment]
You're running a very old version of AE, and the only one in fact to have that issue. Update to the latest version.
