### ISSUE TITLE
Frequent Error: PrepareAnvilEvent

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2143]
## Details

**Describe the bug**

https://pastebin.com/vQUB56dp - Happens quite often

**To Reproduce**

Unsure, apologies

**Screenshots / Video**

N/A

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://paste.md-5.net/mamiqusofi
https://mclo.gs/HgAVEjB

**Comment by Insprill** [comment]
Update AE.
