### ISSUE TITLE
TP_DROPS applies fortune to blocks that shouldn't

### ISSUE THREAD

**Issue by iGabyTM** [GC-spigot/AdvancedEnchantments#2144]
## Details

**Describe the bug**

TP_DROPS applies fortune to all blocks when is combined with autosmelt.

**To Reproduce**

Get a pickaxe with fortune, apply autosmelt first and then TP_DROPS. In some cases might be the other way around.

**Screenshots / Video**

*I don't think is needed*

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/epodurenon
- Server log: https://paste.helpch.at/imitofigup.md

**Comment by Insprill** [comment]
Please update AE and your server to 1.17.1 and see if this still occurs. Wasn't able to reproduce.

**Comment by iGabyTM** [comment]
Yup, works with latest AE and 1.17.1
