### ISSUE TITLE
Latest jobs reborn update no longer works with AdvancedEnchants

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2145]
## Details

**Describe the bug**

The hook with jobs reborn 5.0.0.2 no longer works (block breaking is on true and tried on false)
**To Reproduce**

Mine a melon block with telepathy with this config for the farmer job : https://pastebin.com/FDmAZHs5 
and you won't get money etc
**Screenshots / Video**

don't need 

## Server Information
- "/ae plinfo" link: 
- Server log: 
Server ver: 1.8.8
ae: 8.4.5

**Comment by Insprill** [comment]
Fixed in the next update
