### ISSUE TITLE
Combos inconsistent

### ISSUE THREAD

**Issue by Neekokaiinn** [GC-spigot/AdvancedEnchantments#2146]
## Details

**Describe the bug**
Combo work randomly, for exemple i have an enchant which need 7 hit to proc, but when i had an other enchant without any link with that enchant or combo mechanics, the first enchant now need only 4 hits. 
Actually it divide per 2 the number of hit required 

**To Reproduce**
Server version : 1.8.8
plugin version : 8.5.1

put this enchant on enchant file
gardien:
  display: '%group-color%Gardien'
  description: 'with a combo of 7, give absorption to ally and weakness to enemy'
  applies-to: 'Weapon'
  group: 'ULTIMATE'
  type: 'ATTACK'
  applies:
    - 'ALL_SWORD'
  levels:
    '1':
      chance: 100
      cooldown: 10
      condition: "%attacker combo% = 8 : %allow%"
      effects:
        - "RESET_COMBO %attacker%"
        - "POTION:WEAKNESS:0:200 %victim%"
        - "POTION:ABSORPTION:0:500 <aoe> radius=3 target=undamageable </aoe>"
    "2":
      chance: 100
      cooldown: 10
      condition: "%attacker combo% = 8 : %allow%"
      effects:
        - "RESET_COMBO %attacker%"
        - "POTION:WEAKNESS:0:400 %victim%"
        - "POTION:ABSORPTION:1:500 <aoe> radius=5 target=undamageable </aoe>"
    "3":
      chance: 100
      cooldown: 10
      condition: "%attacker combo% = 8 : %allow%"
      effects:
        - "RESET_COMBO %attacker%"
        - "POTION:WEAKNESS:0:300 <aoe> radius=5 target=damageable </aoe>"
        - "POTION:ABSORPTION:2:500 <aoe> radius=8 target=undamageable </aoe>"
        - "POTION:ABSORPTION:2:500 %attacker%
do /ae reload
put that enchant too
comunisme:
  display: '%group-color%Comunisme'
  description: '50% chance to share golden apple with your teamates'
  applies-to: 'Armor'
  group: 'ULTIMATE'
  type: 'EAT'
  applies:
    - 'ALL_ARMOR'
  levels:
    '1':
      chance: 50
      cooldown: 10
      condition: '%player is holding% = GOLDEN_APPLE : %allow%'
      effects:
        - 'POTION:ABSORPTION:0:2400 <aoe> radius=12 target=undamageable </aoe>'
        - 'POTION:REGENERATION:1:100 <aoe> radius=12 target=undamageable </aoe>'
 do /ae reload
now the enchant need 4hit and not 7

**Screenshots / Video**
video
first i do a combo of 7
gardien work
then i add comunism enchant
after i do a combo of 4
gardien work too
https://youtu.be/SOHzlasdBuA

UPDATE: actually comunism enchant is not required bc i added a new enchant, the combo bug came again, so i delete the enchant, and now the combo bug still here :/ (16/07/2021 17h06 (paris hour)

UPDATE2: actually i'm not sure how reproduce this bug bc its just random, the bug fixed himsefl for 2 days but now it came back
(19/07/2021 16h18)

Update 3 : https://youtu.be/vkonEzlo8cE
i'm just lost (enchant in desc)

## Server Information
server 1.8.8
Ae : 8.5.1
Nothing on log expect /ae reload and other comand (like heal or /gm 1)

**Comment by Insprill** [comment]
Yeah Combos are a bit broken atm when it comes to adding/ resetting them. When the condition placeholder rework is pushed this will also be fixed

**Comment by Insprill** [comment]
Fixed in the next update
