### ISSUE TITLE
Weird Enchant Lore Bug

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2148]
## Details
I have reported this before in discord , every time a player enchant something the lores includes ugly characters at the start.
I cannot identify the cause, this started since like 2 weeks ago and is still not fixed.
**Describe the bug**
some weird characters on enchantment lore, it was not the case for old versions of the plugin, so older enchanted weapons don't have this weird lore thing.

**To Reproduce**
Enchanting anything will have an ugly lore.

**Screenshots / Video**
https://prnt.sc/1btcvh3

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ekeginabez
- Server log: https://mcpaste.io/7d925e23ae6119c2

**Comment by antibitcoin** [comment]
All I need is a solution to fix this, what files should I reset or delete etc.
please help.

**Comment by Insprill** [comment]
Fixed in 8.5.0
