### ISSUE TITLE
REPLANT enchant issue

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2149]
## Details

**Describe the bug**

Hi there, I noticed a bug with the REPLANT enchantment effect, where if the player using an item enchanted with `REPLANT` has some items in their offhand, the item will use up the offhand item instead of seeds in their inventory.

For example, someone with a hoe enchanted with REPLANT uses the enchantment, and holds 64 cobblestone in their offhand while having seeds in their hotbar, the enchantment will use up the cobblestone, reducing it to 63, and replant.

**To Reproduce**

Just use the REPLANT enchant on a hoe and hold something in your off hand.

**Screenshots / Video**

None, if needed please request.

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://paste.md-5.net/sutorosuya

**Comment by iGabyTM** [comment]
#2124

**Comment by Insprill** [comment]
Changing how the default replanter works. Check the default enchantments.yml when the next version releases for the new version of it.
