### ISSUE TITLE
VEIN_MINE drops blocks that can't be harvested in vanilla

### ISSUE THREAD

**Issue by iGabyTM** [GC-spigot/AdvancedEnchantments#2150]
## Details

**Describe the bug**
On 1.17, VEIN_MINE drops blocks that can't be harvested in vanilla, such as [Budding Amethyst](https://minecraft.fandom.com/wiki/Budding_Amethyst).

**To Reproduce**
Break a Budding Amethyst block with VEIN_MINE.

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/obehohelib
- Server log: https://mcpaste.io/17498af53e482a03

**Comment by iGabyTM** [comment]
#2124

**Comment by Insprill** [comment]
Fixed for the next update
