### ISSUE TITLE
Trench not give mcmmo exp

### ISSUE THREAD

**Issue by gwrijasdf** [GC-spigot/AdvancedEnchantments#2151]
If the block is destroyed using 'trench' effect, the mcmmo EXP is not given.
advanced enchantments - version  8.4.10
mcmmo version 2.1.200

**Describe the bug**
If the block is destroyed using 'trench' effect, the mcmmo EXP is not given.

**To Reproduce**
1. Give the pickaxe an Trench effect.
2. break stone, ore etc
3. not gain mcmmo exp

**Screenshots / Video**
none

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/dewofifaxe
- Server log: https://mcpaste.io/edefc038b8f38986

**Comment by Insprill** [comment]
This is intended. You only get XP for the source block if experimental-block-breaking is enabled
