### ISSUE TITLE
Color Codes & /ae reload not applying

### ISSUE THREAD

**Issue by AkaUlti** [GC-spigot/AdvancedEnchantments#2152]
## Details

**Describe the bug**
Color codes aren't registering https://gyazo.com/d8db0ae9dd43a83630902a9a9aac78a3 & /ae reload doesn't apply changes (ex. changing soul gem)

**To Reproduce**
self explanatory 

**Screenshots / Video**
https://gyazo.com/d8db0ae9dd43a83630902a9a9aac78a3

## Server Information
- https://paste.md-5.net/qisowokilu
- Server log: https://mcpaste.io/4cd37c7a891a8e4d

**Comment by iGabyTM** [comment]
I can confirm I have the same issue on 1.17.1

**Comment by Insprill** [comment]
Update to 8.5.0-HOTFIX see if that fixes it
