### ISSUE TITLE
Tp_drops and fortune broke again (5th time xd)

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2154]
## Details

**Describe the bug**

If you mine a melon block with an axe that has Fortune III and Telepathy you will only get 1 melon slice
**To Reproduce**

Grab a diamond axe with the fortune and telepathy enchant and mine a melon block
**Screenshots / Video**

https://gyazo.com/f11e5dcf060f53fe5c4884059b525aa9
## Server Information
AE: 8.5.0
server ver : 1.8.8

**Comment by Insprill** [comment]
Completely rewrote how the number of drops is calculated. All drops should be identical to Vanilla now.
