### ISSUE TITLE
Suggestion: Add Perms for Holy White Scrolls

### ISSUE THREAD

**Issue by EndaarF** [GC-spigot/AdvancedEnchantments#2155]
Would it be possible to add a permission that allows or denies the player the ability for a holy white scroll to retain their item on death? This would solve a problem where items get duped when a holy white scroll is used in conjunction with another plugin that retains items. Thanks for considering.

**Comment by RulerOfEternity** [comment]
Feature requests are disabled for a reason, can you please close this thread and wait until the official 'Feature Request' thingy is added? It's unfair to push your suggestion when other people aren't allowed.

**Comment by EndaarF** [comment]
OK didn't know that. I followed the link on the Discord which said to post suggestions at GitHub. Sorry.
