### ISSUE TITLE
Lost Enchantment Effect

### ISSUE THREAD

**Issue by Regerta** [GC-spigot/AdvancedEnchantments#2156]
## Details

**Describe the bug**
I haven't tried it with other items yet, but i'am think it will be the same.

**To Reproduce**
Please try this:
- Set your character to creative mode
- Claim item from GKits
- Equip the item (tested with Heroic Pickaxe of Hephaestus and Ghostly Call of the Banshee)
- Open inventory by pressing "E"
- Wait 3-5 seconds (don't do anything, just open it and close)
After that you will lost the enchant effect (Obsidian destroyer on the pickaxe, and speed+jump on the boots).

**Screenshots / Video**
https://streamable.com/utufr5

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/disobinavu
- Server log: No errors or warning from AE on the console logs

**Comment by Insprill** [comment]
Can you get the NBT data of the item with the `/data` command after the effect goes away and send a screenshot of it?

**Comment by Regerta** [comment]
Nevermind, i think it already fixed in the latest version.
