### ISSUE TITLE
SHIFT enchant type give permanent potion

### ISSUE THREAD

**Issue by Neekokaiinn** [GC-spigot/AdvancedEnchantments#2158]
**Describe the bug**
The shift type in echant type give permanant effect potion

**To Reproduce**
try with this enchant
jumpp:
  display: '%group-color%jumpp'
  description: 'When sneaking give a high jump boost'
  applies-to: 'Armor'
  group: 'LEGENDARY'
  type: 'SHIFT'
  applies:
    - 'ALL_ARMOR'
  levels:
    '1':
      chance: 100
      cooldown: 20
      effects:
        - 'POTION:JUMP:25:100'

**Screenshots / Video**

## Server Information
AE version :  8.5.0
Server version : 1.8.8

**Comment by Insprill** [comment]
Fixed in the next update. Removing the cooldown will fix it until it's out.
