### ISSUE TITLE
Type MORE_DROPS issue

### ISSUE THREAD

**Issue by Neekokaiinn** [GC-spigot/AdvancedEnchantments#2159]
## Details

**Describe the bug**
the enchantement type MORE_DROPS doesn't work

**To Reproduce**
try with this enchant
multipl:
  display: '%group-color%multipl'
  description: 'multiply drop'
  applies-to: 'Sword'
  group: 'LEGENDARY'
  type: 'KILL_MOB'
  applies:
    - 'ALL_SWORD'
  levels:
    '1':
      chance: 10
      effects:
        - 'MORE_DROPS:2'
    '2':
      chance: 20
      effects:
        - 'MORE_DROPS:3'
    '3':
      chance: 100
      effects:
        - 'MORE_DROPS:10'

**Screenshots / Video**

## Server Information
Server 1.8.8
Ae 8.5.0

**Comment by Insprill** [comment]
Fixed for the next update
