### ISSUE TITLE
Telepathy + Smelting Duplicate Shulkers & Their Contents (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2161]
## Details

**Describe the bug**
When `use-experimental-block-breaking:` is set to true, mining a shulker with a pickaxe that has Telepathy AND Smelting will duplicate the shulker and the contents of the shulker.

**To Reproduce**
1.) Set `use-experimental-block-breaking:` to true
2.) Place a shulker
3.) Put items in the shulker
4.) Hold a pickaxe and do `/ae enchant telepathy 4` and `/ae enchant smelting 3`
5.) Use the pickaxe to mine the shulker you placed in step 2

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/umifuhudaz
- Server log: https://mcpaste.io/11a467262f462468

**Comment by Insprill** [comment]
Fixed in the next update
