### ISSUE TITLE
Telepathy + Silk Touch Sign Deletion Issue (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2162]
## Details

**Describe the bug**
When `use-experimental-block-breaking:` is set to true, mining signs that are placed on walls with an axe that has Telepathy AND Silk Touch will delete the sign.

**To Reproduce**
1.) Set `use-experimental-block-breaking:` to true
2.) Place a sign on a wall
3.) Enchant a pickaxe with Silk Touch
4.) Hold the pickaxe and do `/ae enchant telepathy 4`
5.) Use the pickaxe to mine the sign you placed in step 2

**Screenshots / Video**
This is an example of a sign on a wall that you could delete with the steps above.
![image](https://user-images.githubusercontent.com/29821149/126132828-33f1a770-039d-41bd-8511-18bd8fd3d72b.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/umifuhudaz
- Server log: https://mcpaste.io/11a467262f462468

**Comment by Insprill** [comment]
Fixed in the next update
