### ISSUE TITLE
Telepathy Redstone Deletion Issue (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2163]
## Details

**Describe the bug**
When `use-experimental-block-breaking:` is set to true, placing redstone on a block and then breaking that block with Telepathy makes the redstone vanish.

**To Reproduce**
1.) Set `use-experimental-block-breaking:` to true
2.) Place a block
3.) Place redstone on the block
4.) Hold a pickaxe and do `/ae enchant telepathy 4`
5.) Use the pickaxe to mine the block you placed in step 2

**Screenshots / Video**
In this example screenshot, you would mine the cobblestone.
![image](https://user-images.githubusercontent.com/29821149/126133487-21224ad3-a530-49c3-8888-990525ac02cc.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/umifuhudaz
- Server log: https://mcpaste.io/11a467262f462468

**Comment by Insprill** [comment]
Fixed in the next update
