### ISSUE TITLE
/reapply cooldown message broken

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2164]
## Details

**Describe the bug**
When you `/reapply` twice, it says "You will be able to use this command in %seconds% seconds."

**To Reproduce**
1. Do `/reapply` twice

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29821149/126134896-43baff8e-5c33-457f-83e7-3f09042f4a1d.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/umifuhudaz
- Server log: https://mcpaste.io/11a467262f462468

**Comment by Insprill** [comment]
Fixed in the next update
