### ISSUE TITLE
Equip an armor set break combo mechanic

### ISSUE THREAD

**Issue by Neekokaiinn** [GC-spigot/AdvancedEnchantments#2166]
## Details

**Describe the bug**
Equip an armor set break combo mechanic

**To Reproduce**
do like in the video with this enchant or an other who requiere a combo

peauselenite:
  display: '%group-color%Peau sÃ©lÃ©nite'
  description: 'diana Z'
  applies-to: 'Sword'
  group: 'ELITE'
  type: 'RIGHT_CLICK'
  applies:
    - 'ALL_SWORD'
  levels:
    '1':
      chance: 100
      cooldown: 40
      souls: 50
      condition: 
        - '%player is sneaking% = true : %allow%'
      effects:
        - 'CURE:ABSORPTION %attacker%' 
        - 'POTION:ABSORPTION:2:600 %attacker%'
        - 'ADD_HARM:3 <aoe> radius=3 target=damageable </aoe>'
    '2':
      chance: 100
      cooldown: 40
      souls: 50
      condition: 
        - '%player is sneaking% = true : %allow%'
      effects:
        - 'CURE:ABSORPTION %attacker%'
        - 'POTION:ABSORPTION:3:600 %attacker%'
        - 'ADD_HARM:5 <aoe> radius=5 target=damageable </aoe>'

**Screenshots / Video**
https://youtu.be/nfkkrAoMQvs
(we hear ghast scream when a combo of 3 is done , it add 1 soul and do 2.5 heart damage)

## Server Information
AE : 8.5.1
Server : 1.8.8

**Comment by Insprill** [comment]
Completely rewrote combo handling in the next update so that should fix it.
