### ISSUE TITLE
REPLANT Beetroot consumes beetroot instead of beetroot seeds

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2167]
## Details

**Describe the bug**

REPLANT enchantment, when trying to replant beetroot, uses "beetroot" fruits instead of "beetroot_seeds".

**To Reproduce**

Have replant on a tool, put Betroot in your off-hand and it would work. Putting beetroot seeds in your off-hand doesn't work as the plugin doesn't seem to recognise it.

**Screenshots / Video**

## Server Information
- https://paste.md-5.net/epoqapenuk
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6844568/latest.log)
 
- Server log:

**Comment by Insprill** [comment]
Update your replant enchant with the latest one in the default file.

**Comment by Jupitour** [comment]
Hi there, it was a typo. I'm using the REPLANTER enchant, the latest one in the default file, but this still happens.
