### ISSUE TITLE
Condition variables %victim is on fire% does not work on mobs

### ISSUE THREAD

**Issue by BarkeeCode** [GC-spigot/AdvancedEnchantments#2168]
## Details

**Describe the bug**
The condition %victim is on fire% works only on players and not mobs. (Enchantment does not activate on burning mobs like zombies, skeleton, etc)

**To Reproduce**
Create an enchantment with the condition involving '%victim is on fire%.
Example: 
extinguisher:
  display: '%group-color%Extinguisher'
  description: "Does double damage to enemy\nwhilst on fire"
  applies-to: 'Swords'
  type: 'ATTACK;ATTACK_MOB'
  group: 'ULTIMATE'
  applies:
    - 'ALL_SWORD'
  levels:
    1:
      chance: 100
      cooldown: 0
      condition:
        - '%victim is on fire% = true : %allow%'
      effects:
        - 'DOUBLE_DAMAGE %victim%'
        - 'EXTINGUISH %victim%'
Then attack a mob using the enchantment.
**Screenshots / Video**

## Server Information
https://user-images.githubusercontent.com/87682102/126253368-35a1f462-f853-4154-97e0-038ed2e3080c.mp4

**Comment by Insprill** [comment]
Reworking how all condition placeholders are handled so this will be fixed soon

**Comment by Insprill** [comment]
Fixed in the next update
