### ISSUE TITLE
Enchant books with armor

### ISSUE THREAD

**Issue by ElMoha943** [GC-spigot/AdvancedEnchantments#2169]
## Details

**Describe the bug**

People can enchant books with enchanted armor:

**To Reproduce**

Put togheter a vanilla enchanted book with an enchanted piece of armor, it will add the armor enchants to the book.

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/25410859/126256714-90daee52-79b0-4f84-a86d-266351b784ab.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/anuhesuveq 
- Server log: 
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6845270/latest.log)

**Comment by Insprill** [comment]
Fixed in the next update. Will be an option in the anvil.yml to toggle it.
