### ISSUE TITLE
Autosmelt don't work on copper

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2171]
## Details

**Describe the bug**
Autosmelt don't work on copper on 1.17.1

**To Reproduce**
Mine copper with a pick that have autosmelt

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ivohelirev
- Server log: https://mcpaste.io/c678e39c41eb24a0

**Comment by Insprill** [comment]
Fixed in the next update
