### ISSUE TITLE
Enchant book destroy rate doesn't work in anvil

### ISSUE THREAD

**Issue by crazymarty** [GC-spigot/AdvancedEnchantments#2174]
Players can enchant an item with custom enchant in anvil if they don't want to increase the success rate. It doesn't matter how much destroy rate is, it will still apply it to the item. The only way to fix this is to disable that feature from config.

**Comment by GuNanOvO** [comment]
The priority should be the highest! Hope to fix it soon. This is very important.

**Comment by Insprill** [comment]
@GuNanOvO you can [disable it in the config](https://github.com/GC-spigot/AdvancedEnchantments/blob/master/Default%20Files/config.yml#L680). 

if anyone has any ideas on how to implement this that'd be awesome

**Comment by RulerOfEternity** [comment]
This will sound very obvious but can't you just implement the same mechanism on an anvil? That's the only thing I can think of to be honest, or that your book has to either be at a 100% success rate or a 0% destroy rate for it to apply. @Insprill

**Comment by Insprill** [comment]
Well it's a bit trickier then that. With drag & drop combining, we know that the player is intending to enchant the item. In an anvil however, just putting the book in, they might just be seeing if it can be applied, or if they can afford it. I guess the best bet would be to calculate it when they take the item from the anvil. Ill mess around with that and see how it feels.

**Comment by ProfessionalBoatDrifter** [comment]
It should work the same as with drag n drop IMO.

**Comment by Insprill** [comment]
Read my comment above lol

**Comment by ProfessionalBoatDrifter** [comment]
I just wanted to voice my support for the issue :)

**Comment by GuNanOvO** [comment]
Has this bug been fixed? Enchantment failure chance still doesn't work on anvils.

**Comment by GC-spigot** [comment]
It’s not a bug. It’s not been designed to work like that.
