### ISSUE TITLE
Gkit No Cooldown

### ISSUE THREAD

**Issue by thepagon** [GC-spigot/AdvancedEnchantments#2176]
## Details

**Describe the bug**
Gkits have no cooldown. I've tried denying the ae.nocooldown permission, and made sure they have a cooldown in the config.

**To Reproduce**
Give yourself access to a gkit and see if it has a cooldown

**Screenshots / Video**

## Server Information
https://paste.md-5.net/ofipijilif
https://mcpaste.io/60b7c999bca4d202

**Comment by Insprill** [comment]
Fixed in the next update
