### ISSUE TITLE
Telepathy duping chorus fruit

### ISSUE THREAD

**Issue by bipedd** [GC-spigot/AdvancedEnchantments#2177]
## Details

**Describe the bug**
Mining a piece of chorus fruit with a silk touch pickaxe and telepathy (I used level 4) dupes the chorus fruit.

**To Reproduce**
Place a piece of chorus fruit on a piece of endstone, and mine it with a silk touch pickaxe with telepathy.

**Screenshots / Video**

https://user-images.githubusercontent.com/77213949/126417233-585c6c3f-a9a2-4a56-b3b7-51fd12f0bacf.mp4

## Server Information
- https://paste.md-5.net/riwixigiso
- Server log: https://mcpaste.io/fd4cf7ee715b3d60

**Comment by Insprill** [comment]
Does experimental-block-breaking have an effect on this?

**Comment by Insprill** [comment]
Update AE
