### ISSUE TITLE
Console Spam "1" when hit the block with enchantment that contains PLANT_SEEDS and MINING

### ISSUE THREAD

**Issue by notynote** [GC-spigot/AdvancedEnchantments#2178]
## Details

**Describe the bug**
Console Spam "1" when hit the block with enchantment that contains PLANT_SEEDS and MINING

**To Reproduce**
Neterite Hoe with an enchantment below spam "1" in console when break a block

`
plantminer:
  display: "%group-color%Plantminer"
  description: "Plant seeds in a 3x3 area\nby shift and harvest"
  applies-to: "Hoes"
  type: "MINING"
  group: "ULTIMATE"
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
    - ALL_HOE
  levels:
    1:
      condition:
        - "%player is sneaking% = true : %allow%"
      cooldown: 3
      effects:
        - "PLANT_SEEDS:9"
`

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/32334875/126447624-a06d3f41-5bf8-4f73-b021-72fff3909c2c.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/jikuvavequ

**Comment by Insprill** [comment]
Fixed in the next update
