### ISSUE TITLE
Enchant with cooldown and soul are broken when connect

### ISSUE THREAD

**Issue by Neekokaiinn** [GC-spigot/AdvancedEnchantments#2179]
## Details

**Describe the bug**
When you connect on a server enchant with cooldown and souls no longer need soul and have cooldown, it can be fixed by reloading but for a server reload everytime a player connect is not an answer to this issue

**To Reproduce**
have an enchant with cooldown and soul
connect on a server
spam this enchant (actually you are not supposed to do that but the issue is you can do that

enchant in video:

impactlunaire:
  display: '%group-color%Impact lunaire'
  description: 'diana r'
  applies-to: 'Sword'
  group: 'ELITE'
  type: 'RIGHT_CLICK'
  applies:
    - 'ALL_SWORD'
  levels:
    '1':
      chance: 100
      cooldown: 120
      souls: 100
      condition:
        - '%player time% > 13000 && %player time% < 23000 && %player is sneaking% = true : %allow%'
      effects:
        - 'PULL_CLOSER:4 <aoe> radius=10 target=damageable </aoe>'
        - 'PLAY_SOUND:GHAST_MOAN:30:100 <aoe> radius=10 target=damageable </aoe>'
        - 'TNT:1 <aoe> radius=10 target=damageable </aoe>'
        - 'WAIT:10'
        - 'PULL_CLOSER:3 <aoe> radius=8 target=damageable </aoe>'
        - 'PLAY_SOUND:GHAST_MOAN:30:150 <aoe> radius=8 target=damageable </aoe>'
        - 'TNT:1 <aoe> radius=8 target=damageable </aoe>'
        - 'WAIT:10'
        - 'PULL_CLOSER:2 <aoe> radius=7 target=damageable </aoe>'
        - 'PLAY_SOUND:GHAST_MOAN:30:200 <aoe> radius=7 target=damageable </aoe>'
        - 'TNT:1 <aoe> radius=7 target=damageable </aoe>'
        - 'WAIT:10'
        - 'PLAY_SOUND:GHAST_SCREAM:30:300 <aoe> radius=7 target=damageable </aoe>'
        - 'PULL_CLOSER:1 <aoe> radius=6 target=damageable </aoe>'
        - 'LIGHTNING <aoe> radius=6 target=damageable </aoe>'
        - 'TNT:1 <aoe> radius=7 target=damageable </aoe>'
        - 'ADD_HARM:5 <aoe> radius=8 target=damageable </aoe>'
        - 'POTION:SLOW:1:300 <aoe> radius=6 target=damageable </aoe>'
        - 'BOOST:UP:8 <aoe> radius=8 target=damageable </aoe>'

( 100 souls, 2minutes cooldown, do ghast sound, explosion lightning and dammage to other player and pull closer
to activate: night, sneak and right click (and have enough souls)

**Screenshots / Video**
https://youtu.be/-Hw-2wYEyHs

## Server Information
AE : 8.5.1 (8.5.2 don't fix it (i tried))
Server : 1.8.8

**Comment by Insprill** [comment]
Can you try to explain that better? I have no idea what you mean

**Comment by Neekokaiinn** [comment]
idk if you saw the video but what i mean is my cooldown are broken, there is no cooldown, and /reload don't fix this problem anymore 
I've enabled   enchants-debug-mode and i've saw than the enchant was activated 2 times, and in the console it write this when i use an enchant
[16:28:40] [Server thread/INFO]: 1
[16:28:40] [Server thread/INFO]: 1
idk if it have a link but i also have this error
[16:28:20] [Server thread/INFO]: Neekokaiinn issued server command: /ae reload
[16:28:20] [Server thread/ERROR]: [AdvancedEnchantments] Plugin AdvancedEnchantments v8.5.2 has failed to register events for class net.advancedplugins.ae.enchanthandler.enchanttypes.MINING because org/bukkit/event

**Comment by Insprill** [comment]
I've made some changes around this recently, can you see if it's still an issue on 8.5.9?
