### ISSUE TITLE
DEFENSE_BOW_MOB does not work

### ISSUE THREAD

**Issue by Complex1tive** [GC-spigot/AdvancedEnchantments#2181]
**Describe the bug**
The DEFENSE_BOW_MOB type generates an error in the console and does not function.

**To Reproduce**
Open a Purpur-1171 server with Java 11.0.9 with AdvancedEnchantments 8.5.2. Have this enchantment (https://bin.bloom.host/onivupepov.less) in enchantments.yml. Apply this enchantment to any armor piece, and get shot by a skeleton.

NOTE: This bug does not occur with AE 8.4.9.

**Screenshots / Video**
Video: https://i.imgur.com/RcH6kYq.mp4
Error: https://bin.bloom.host/adihimigoy.properties

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/alegifawit
- Server log: https://bin.bloom.host/ezohinuxem.yaml

**Comment by Insprill** [comment]
Fixed in the next update
