### ISSUE TITLE
Constant console spam

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2182]
## Details

**Describe the bug**

Constant console spam

**To Reproduce**

Not sure honestly.

**Screenshots / Video**

N/A

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://pastebin.com/dsM2xin1 - Error
https://paste.md-5.net/okucufezew - /ae plinfo
https://mclo.gs/EMzYSBu - Startup Log

**Comment by itslukemango** [comment]
Edit: Often comes with debug messages I presume:
`[01:11:15 INFO]: 1
[01:11:15 INFO]: 1
[01:11:15 INFO]: 1
[01:11:15 INFO]: 1`

**Comment by Insprill** [comment]
Fixed in the next update
