### ISSUE TITLE
REPLANTER Beetroot consumes Beetroot fruit instead of Beetroot seeds

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2183]
## Details

**Describe the bug**
REPLANT enchantment, when trying to replant beetroot, uses "beetroot" fruits instead of "beetroot_seeds".

**To Reproduce**
Have replanter on a tool, put Betroot in your off-hand and it would work. Putting beetroot seeds in your off-hand doesn't work as the plugin doesn't seem to recognise it.

**Screenshots / Video**
autoplant:
  display: "&7Autoplant"
  description: "Replants crops when you break them."
  applies-to: "Hoes"
  type: "MINING"
  group: "UNIQUE"
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
    - ALL_HOE
  levels:
    1:
      condition:
        - "%is crop% = false : %stop%"
        - "%is fully grown% = false : %stop%"
        - "%offhand item% = %block drop type% : %allow%"
      effects:
        - "TAKE_AWAY:%block drop type%"
        - "SET_BLOCK:%block type%"

I've copied and pasted the default configuration, but the bug persists. Reference to #2167 as the resolution didn't work, but it's been closed and there has been no reply to it.

## Server Information
/ae PLinfo: https://paste.md-5.net/ogapagaloq
server log: https://paste.lucko.me/gaZxw3YN7c
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6859449/latest.log)

**Comment by Insprill** [comment]
Use the [new replanter](https://github.com/GC-spigot/AdvancedEnchantments/blob/master/Default%20Files/enchantments.yml#L160).
