### ISSUE TITLE
overload conflict with mini

### ISSUE THREAD

**Issue by NightLife-SG** [GC-spigot/AdvancedEnchantments#2185]
**Describe the bug**
When overload enchantment is apply on armor,it conflict with my other plugin it give more health whenever player changes world,the plugin conflicting is TheLab, i contacted the author of the plugin but he say it cant be fixed due to how the plugin work,it store whatever player have before joining and give back whatever have been store after game finished.So that why im having the bug health is being added eveyrtime i join and leave game.I can fix this issue by removing overload in enchantment.yml,but can you guy have solution to fix this without me removing it?
Blacklisting it doesnt work for what i wanted. Since my player is playing with AE
**To Reproduce**
apply overload enchantment on armor,join game and quit game.

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yutalopati
- Server log: 
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6867940/latest.log)

**Comment by NightLife-SG** [comment]
i cant get the video upload here,because it doesnt let me upload over 10mb,if you could reply my ticket on discord then i could send on discord.

**Comment by Insprill** [comment]
You can upload it somewhere like vimeo or youtube and make it unlisted. It would be great if you could do that

**Comment by Insprill** [comment]
@NightLife-SG please upload a video of what you're experiencing.

**Comment by NightLife-SG** [comment]
https://youtu.be/KeB0KcWCkV4

**Comment by Insprill** [comment]
Not an issue with us. Please tell the dev to join our [Discord Server](https://discord.gg/GzdQdMw) so we can try to find a fix.
