### ISSUE TITLE
TP_DROPS no longer working 

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2186]
## Details

**Describe the bug**

The tp_drops enchantement no longer works 
**To Reproduce**

Grab a pick or an axe and mine a block with the telepathy enchant and they won't get tped in your inventory. experiemental-block-breaking doesn't change anything
**Screenshots / Video**

don't need

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae: 8.5.3
Ver: 1.8.8 TacoSpigot

**Comment by LuluxClient** [comment]
Getting this error : https://pastebin.com/uzLq4LWc

**Comment by LuluxClient** [comment]
After some search I found out that 1.8.8 doesn't have "BlockDropItemsEvent" or "BlockDropItemEvent" apparently it's an 1.7.10 event

**Comment by Insprill** [comment]
fixed in 8.5.6 i believe
