### ISSUE TITLE
Plugin disables itself after an internet outage

### ISSUE THREAD

**Issue by DarkKingKaanMC** [GC-spigot/AdvancedEnchantments#2187]
## Details

**Describe the bug**

The plugin disables itself after the server loses internet connection.

**To Reproduce**

Have the plugin installed, forcefully cut internet connection from the host machine, the plugin won't be able to do checks, therefore disabling itself.

**Screenshots / Video**

There are no screenshots needed.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/eweremivuv
- Server log: https://mcpaste.io/1b0390337b80a692

**Comment by Insprill** [comment]
Not a bug, that is intended.
