### ISSUE TITLE
Often Console Spam

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2188]
## Details

**Describe the bug**

Constant console spam
**To Reproduce**

Unsure.
**Screenshots / Video**

N/A

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://pastebin.com/Md25aX4c - Error
https://mclo.gs/3XSZFMp - Startup Log
https://paste.md-5.net/torukekoyo - /ae plinfo

**Comment by Insprill** [comment]
Fixed for the next update
