### ISSUE TITLE
RENAME TAG BUG.

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#2191]
## Details

**Describe the bug**
If you use a rename tag in anyway, but then cancel it by 1. canceling, or 2 renaming an item you cannot name, an your inventory is full, you lose the nametag entirely. It doesn't drop and doesn't display a message that they inventory was full and that it was dropped.

**To Reproduce**
1. Fill every slot with 64 items, besides one slot, the name tag.
2. Use the name tag by right-clicking.
3. Before entering a name, unstack one of the existing stacks of items and put it into the last slot where the name tag was.
4. Try to rename one of the non-renameable items.

**Screenshots / Video**
N/A

## Server Information
- "/ae plinfo" command is invalid for me.
https://mcpaste.io/770e4ac70bc028ed

**Comment by Insprill** [comment]
Fixed in the next update
