### ISSUE TITLE
AE has a /heal command

### ISSUE THREAD

**Issue by baailey** [GC-spigot/AdvancedEnchantments#2192]
## Details

**Describe the bug**

If you have a server with only AE on it and you try do the /heal command, it will tell you the command does not exist but will heal your health anyway. This conflicts with the EssentialX command and permission as well. 
**To Reproduce**

1. Make sure AE is the only command in your plugin folder
2. Start the server
3. Jump off a cliff and lose some health
4. Do /heal
**Screenshots / Video**

https://youtu.be/A5ab-ck8vzE

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/uwatiduvun 
- Server log: https://mcpaste.io/99923cbaacdcf70c

**Comment by baailey** [comment]
This issue occurs on 8.5.6 as well.

**Comment by Insprill** [comment]
We need to do this to avoid issues with it. It only works if you have the essentials help permission or cmi's. i don't see how that's an issue...

**Comment by baailey** [comment]
[Then I guess this is a bug?](https://youtu.be/o0-0U8N92AQ)

**Comment by Insprill** [comment]
Oh yikes. Yeah looks like the permission check got removed at some point. Fixed for the next update

**Comment by SenPr** [comment]
This is a bug in 8.6.5
