### ISSUE TITLE
Aqua Enchant - Instant Death

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2194]
## Details

**Describe the bug**

Aqua enchant kills players, if they are in water and they kill a mob, they die as well.

**To Reproduce**

Enchant an item with Aqua and kill a mob.

**Screenshots / Video**

Will add in the comments shortly.

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://paste.md-5.net/bafakipiju- /ae plinfo
https://mcpaste.io/4baa46968a86e3fa - Log

**Comment by itslukemango** [comment]
https://www.youtube.com/watch?v=H0IZE5xu2pI

**Comment by Insprill** [comment]
Can you send the enchant? With the default aqua i can't reproduce it, nor do I see how it would even happen.

**Comment by itslukemango** [comment]
> 
> 
> Can you send the enchant? With the default aqua i can't reproduce it, nor do I see how it would even happen.

https://pastebin.com/buCWA5zz

Here's a bug report a player filed on our server on it: https://lukemango.s-ul.eu/POlH7Owc

**Comment by Insprill** [comment]
Are you sure it's Aqua causing the issue? What all enchants are on the item?

**Comment by itslukemango** [comment]
> 
> 
> Are you sure it's Aqua causing the issue? What all enchants are on the item?

Yeah we've tested it with just a tool with Aqua on it

**Comment by Insprill** [comment]
On a dev server, can you try removing all your plugins then see if it's still an issue then if it isn't add them back until it pops up again? On airplane 55 1.17.1, with a plain axe and boots with Aqua i can't get this to happen
