### ISSUE TITLE
Sometimes monsters become invincible or invisible when hit by a monster or entity.

### ISSUE THREAD

**Issue by GANJI0170** [GC-spigot/AdvancedEnchantments#2195]
Let me explain the situation.
Sometimes monsters become invincible or invisible, wearing human-made armor as the Advanced Enchantments plug-in and posting those phrases when hit by a monster or entity.
This does not happen in non-enchantments armor.
Plug-in version 8.4.3
I'd like to hear some solutions.

**To Reproduce**

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/63225665/126886321-a991c87e-cea9-4738-a759-ff3c8c188ac1.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/tukecucote
- Server log: https://mcpaste.io/c9e65e382eb408f0

**Comment by Insprill** [comment]
Update AE.
