### ISSUE TITLE
Blocks destroyed disappearing with Obsidian Destroyer

### ISSUE THREAD

**Issue by 69werdna** [GC-spigot/AdvancedEnchantments#2196]
**Describe the bug**
Blocks destroyed disappearing with obsidian destroyer

**To Reproduce**
Mine with a pickaxe enchanted with obsidian destroyer, and occasionally, blocks magically disappears...?

**Screenshots / Video**
https://www.youtube.com/watch?v=av2k3Hlcwls&ab_channel=Alibaba

## Server Information
https://paste.md-5.net/vehiveporu

**Comment by Insprill** [comment]
Thats... what that enchant does?

**Comment by 69werdna** [comment]
> Thats... what that enchant does?

If you were to look at the last few seconds video, I mined the obsidian and the iron block, the iron block disappeared into thin air and didn't drop at all. So what happened on my server was, someone placed a shulker box on a obsidian layer and mined it, the shulker box didn't drop and lost everything in the shulker box.

**Comment by Insprill** [comment]
@69werdna Is this still an issue on 8.6.8?
