### ISSUE TITLE
gear issue

### ISSUE THREAD

**Issue by NightLife-SG** [GC-spigot/AdvancedEnchantments#2197]
[Sun, 25. Jul 2021 14:00:14 UTC WARN] java.lang.ClassCastException: class net.advancedplugins.ae.utils.ArmorEquipEvent cannot be cast to class org.bukkit.event.entity.EntityDamageByEntityEvent (net.advancedplugins.ae.utils.ArmorEquipEvent is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2f910e20; org.bukkit.event.entity.EntityDamageByEntityEvent is in unnamed module of loader 'app')
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:980)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:140)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:127)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.runCheck(EFFECT_STATIC.java:90)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.updateWornArmor(EFFECT_STATIC.java:37)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.lambda$onArmorChange$3(EFFECT_STATIC.java:171)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[Sun, 25. Jul 2021 14:00:14 UTC WARN] at java.base/java.lang.Thread.run(Thread.java:831)
[Sun, 25. Jul 2021 14:00:14 UTC INFO] [AdvancedEnchantments ERROR] Could not pass ClassCastException: class net.advancedplugins.ae.utils.ArmorEquipEvent cannot be cast to class org.bukkit.event.entity.EntityDamageByEntityEvent (net.advancedplugins.ae.utils.ArmorEquipEvent is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2f910e20; org.bukkit.event.entity.EntityDamageByEntityEvent is in unnamed module of loader 'app')
[Sun, 25. Jul 2021 14:00:14 UTC INFO] Class: net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:980)
[Sun, 25. Jul 2021 14:00:14 UTC INFO] Extra info: effect[KILL_MOB:5]; enchant [gears]; mc[117]; ae[8.5.4]
[Sun, 25. Jul 2021 14:00:14 UTC INFO] If you cannot indentify cause of this, contact developer providing this report.

**Comment by Insprill** [comment]
Configuration error. Join the discord server for support
