### ISSUE TITLE
Abiding Duplication Glitch 

### ISSUE THREAD

**Issue by James-Cotterill** [GC-spigot/AdvancedEnchantments#2204]
## Details

**Describe the bug**
As discussed in discord ticket #aenchantments-0651  can dupe bows when they are in the off-hand as you can see here https://youtu.be/rT0bb-VSL1A. This seems to be linked to the abiding enchant 

**To Reproduce**
Place abiding bow in of-hand and shoot. 

**Screenshots / Video**
https://youtu.be/rT0bb-VSL1A

## Server Information
https://paste.md-5.net/opikehidef
https://mcpaste.io/02113377df38eadd (This is also spammed with AdvancedSpawners Errors)

**Comment by Insprill** [comment]
Fixed for the next update
