### ISSUE TITLE
Planter enchant breaking seeds in low light

### ISSUE THREAD

**Issue by sebastiantho** [GC-spigot/AdvancedEnchantments#2205]
## Details

**Describe the bug**

The Planter enchant attempts to plant seeds even if there is too little light for it to plant it, meaning it breaks immediately. If this is done with an autoclicker, it can crash the server in a minute or so.

**To Reproduce**

1. Place farmland
2. Ensure the farmland has too little light for seeds to be planted.
3. Attempt placing seeds with PLANTER enchant.

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: 
https://paste.md-5.net/
- Server log: 
Server lastest log doesn't go back to the bootup. But there are no AE issues and it shouldn't be required to reproduce the bug.

**Comment by Insprill** [comment]
Fixed for the next update
