### ISSUE TITLE
Any Potion Effect CE | Permanent Effect

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2206]
## Details

**Describe the bug**

When you replace a helmet with a CE that gives a potion effect with any item using /hat it retains the potion effects from the replaced helmet, for example, put obsidian shield on a diamond helmet, hold a dirt block and do /hat

**To Reproduce**

Put obsidian shield on a diamond helmet, hold a dirt block and do /hat

**Screenshots / Video**

https://streamable.com/0x9vg5

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/kaquwunaro
- Server log:  https://mclo.gs/Yv9B0fY

**Comment by Insprill** [comment]
Duplicate of #2096
