### ISSUE TITLE
Planter causing low TPS when turning dirt to farmland

### ISSUE THREAD

**Issue by sebastiantho** [GC-spigot/AdvancedEnchantments#2207]
## Details

**Describe the bug**

Whenever you turn dirt / grass into farmland with the planter enchant, it causes very low TPS. Why? I am unsure.

**To Reproduce**

Simply turn farmland into dirt using the Planter enchant.

**Screenshots / Video**

https://streamable.com/z8n3wq

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://paste.md-5.net/
Log doesn't go back to bootup. Restart would be required, although no AE errors.

**Comment by sebastiantho** [comment]
Note: The TPS was at a very steady 20 prior to the video.

**Comment by Insprill** [comment]
This doesn't show me much of anything. Please run timings while doing it and if you could a spark report would be very helpful.

**Comment by sebastiantho** [comment]
What kinda report do you want from spark? Here's timings, it's pretty clear to see when I started the test: https://timings.aikar.co/?id=a9672a0e1b704d03b6788975432f2d9f

**Comment by Insprill** [comment]
Just a regular profiler report from Spark would be great.

**Comment by sebastiantho** [comment]
https://spark.lucko.me/8ZtJt3sysm 
Here you go, I recorded this while spamming right click on grass with the planter enchant. TPS dropped to 17 from 20. I stopped about halfway through the 30 seconds of this recording.

**Comment by Insprill** [comment]
Fixed in the next update
