### ISSUE TITLE
Vein miner and fortune doesn't work

### ISSUE THREAD

**Issue by SlyyJacob** [GC-spigot/AdvancedEnchantments#2209]
## Details

**Describe the bug**
Vein miner + fortune doesn't work and doesn't yield extra resources

**To Reproduce**
Have fortune and vein miner on a pickaxe

**Screenshots / Video**

https://user-images.githubusercontent.com/36818957/127476299-e14ea7f1-4094-4958-8064-7edec4415335.mp4

## Server Information
https://paste.md-5.net/oruwigejoq

**Comment by Insprill** [comment]
I couldn't reproduce this, but for the next version, I redid the internal fortune calculations so that might fix it. going to leave this open until I know it fixed it or didn't fix it.

**Comment by SlyyJacob** [comment]
I have just tried it again with the AdvancedEnchantments-8.5.9 version but to no avail. Still getting to extra drops with vein miner + fortune. I've tried it in creative, survival, as op, as non-op. It gives out no error in the console.

**Comment by Insprill** [comment]
Yeah waiting on GC to update his local repo. You'll see it in the changelog

**Comment by SlyyJacob** [comment]
@Insprill So far no luck with making it work. Are there any changes to config files that are needed? I don't want to be reconfiguring the files every update, last time I checked the main config file, it didn't have many changes, just some values being inside " "

**Comment by Insprill** [comment]
As long as `fortune-works-on-iron-gold` is true it should work

**Comment by SlyyJacob** [comment]
Okay, that fixed it. Thanks
