### ISSUE TITLE
Dupe ae armor

### ISSUE THREAD

**Issue by Yoloman0013** [GC-spigot/AdvancedEnchantments#2210]
Describe the bug:
Take with ur mouse armor away and it will dupe only works in survival 
Server version 1.8

To Reproduce
in survival mode click on any equiped armor

Screenshots / Video
https://gyazo.com/1fcf0eb5f8782e8da8b51ee6837da0a0

https://paste.md-5.net/erudemubap

**Comment by Insprill** [comment]
I don't think this is an issue with AE. Please remove all other plugins and see if it goes away then slowly add them back one by one until it starts happening again then get back with the results.

**Comment by Yoloman0013** [comment]
> I don't think this is an issue with AE. Please remove all other plugins and see if it goes away then slowly add them back one by one until it starts happening again then get back with the results.

well when ae is removed armor doesnt dupe and when armor doesnt have any ces u cant dupe it

**Comment by Insprill** [comment]
Please do what i asked
