### ISSUE TITLE
java fatal error 

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2212]
## Details

**Describe the bug**
i just installed AE in my server for 2 hours and my server crashed with the following java crash report.
i never see such problem in the pass when i have no AE in my server

Java fatal error server crash report
https://mclo.gs/AJOXgYu

**To Reproduce**
cannot reproduce, don't know how does this can occur but before server crash , it show

![image](https://user-images.githubusercontent.com/61608872/127597867-6a7ae7d5-2703-428f-93d2-8b9df1490ba5.png)

**Screenshots / Video**
this is the only screenshot
![image](https://user-images.githubusercontent.com/61608872/127597879-a50766a4-26d1-4e4e-9615-1768ca63c53e.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/vusijeyuro
- Server log: https://mcpaste.io/82ed794078b1d6ce

**Comment by Insprill** [comment]
Please send the actual crash log

**Comment by hkkongou** [comment]
> Please send the actual crash log. It's located at `/home/kelvin2/Desktop/1.16.5main2/hs_err_pid45283.log`
should be this one
https://mclo.gs/AJOXgYu

**Comment by Insprill** [comment]
Has this happened more then once?

**Comment by hkkongou** [comment]
> Has this happened more then once?

no
but i have adjust some enchantment related to health to be not so high since that crash...

but the health warning still appearing

**Comment by Insprill** [comment]
Ok, the health error is known, it's a couple of issues back. The crash seems very one-off so I'm going to close this. If it happens more then comment and I'll reopen this.
