### ISSUE TITLE
use-experimental-block-breaking: true but not gain mcmmo exp

### ISSUE THREAD

**Issue by gwrijasdf** [GC-spigot/AdvancedEnchantments#2214]
## Details

**Describe the bug**
config- use-experimental-block-breaking: true
However, it does not give mcmmo exp when digging stones with the "Trench" effect.

**To Reproduce**
Server version / 1.17.1
AdvancedEnchantments / version 8.5.8
mcMMO - Original Author Returns! / version 2.1.200

1. Give the pickaxe an Trench effect.
2. break stone, ore etc
3. not gain mcmmo exp

**Screenshots / Video**
none

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/afarevapok
- Server log: https://mcpaste.io/9b2037a88f7062bf

**Comment by Insprill** [comment]
Do you mean it doesn't give any XP for just not for the other blocks TRENCH breaks?

**Comment by gwrijasdf** [comment]
When all blocks (stone, ore, etc...) are destroyed with Trench, mcmmo exp is not given.

**Comment by Insprill** [comment]
Ok, so even the source block doesn't give any XP?

**Comment by gwrijasdf** [comment]
yes

**Comment by Insprill** [comment]
Pretty sure this is related to #2213. Possible fix in the next update. Please respond once it comes out and you are able to test it.
