### ISSUE TITLE
Trench/Detonate duplication glitch

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2215]
## Details

**Describe the bug**
Players able to use pickaxes with detonate to duplicate blocks and probably shulks.

**To Reproduce**
He had a tower of obsidian and place stuff on top and break that stuff, he duped obsidian 100% sure but he said it works for other things too, I am in vanish so I am just watching him.
I have included my configs.
config: https://mcpaste.io/dd557ae137cee6dc
enchantments: https://mcpaste.io/3a536e164b1cd026

I don't mind the dupes since my server is not pay to win, but it will be nice if you save the in-game economy by fixing this asap, as am not planning to reset the economy. so the less millions they have the better.

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/vatozexapu
- Server log: https://mcpaste.io/b0f5231e16958b08

**Comment by Insprill** [comment]
Fixed for the next update
