### ISSUE TITLE
AE removes custom player heads when placed in the helmet slot while in Creative Mode

### ISSUE THREAD

**Issue by baailey** [GC-spigot/AdvancedEnchantments#2217]
## Details

**Describe the bug**

When using HeadDatabase, EssentialsX etc to obtain a custom skull, AE will delete the head when you remove it from your helmet slot.
**To Reproduce**

1. /hdb random [your name] or /skull [player]
2. Place the head on your helmet slot so you are wearing it
3. Click the head to remove it from your helmet slot. The head should disappear.
**Screenshots / Video**

https://youtu.be/H_Zrc8Hbp6g

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/daqobozafe
- Server log: https://mcpaste.io/f0aa9109e86b3be2

**Comment by Insprill** [comment]
Looks like its all armor according to #2223

**Comment by baailey** [comment]
Can recreate with armour as well.

**Comment by Insprill** [comment]
Fixed in the next update
