### ISSUE TITLE
Wierd enchantment description

### ISSUE THREAD

**Issue by Regerta** [GC-spigot/AdvancedEnchantments#2218]
## Details

**Describe the bug**
Wierd enchantment description. 

**To Reproduce**

- Use AE 8.5.7 or 8.5.8 (I try this on my test server, it's normal on 8.5.6)
- Do /ae premade and download pvp enchantment
- Restart server
- Check some item's descriptions on /gkitz

**Screenshots / Video**
Screenshot: https://ibb.co/Z6S0SMN

## Server Information
- Fresh installation Purpur 1.17.1 with Java 16

**Comment by Insprill** [comment]
Fixed in the next update
