### ISSUE TITLE
All files were re-generated & won't recognize any backup files

### ISSUE THREAD

**Issue by owensto** [GC-spigot/AdvancedEnchantments#2219]
## Details

**Describe the bug**
All files were re-generated & it won't recognize any of my backup files for enchants

**To Reproduce**
Yesterday after server restart all of my AE files were re-generated

**Screenshots / Video**
N/A

## Server Information
https://paste.md-5.net/ecidopopus
https://mcpaste.io/c5fb0098cefc2825

Find me on Discord if you need anything further. I can upload all past files that worked fine if you'd like to see them.

**Comment by Insprill** [comment]
Can you send the backup file that it won't take?

**Comment by owensto** [comment]
[AdvancedEnchantments.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/6911786/AdvancedEnchantments.zip)
Here is a zip of the files. It won't let me upload .yml, but the enchantments.yml is in there.

**Comment by Insprill** [comment]
@owensto Is this still an issue? I just tested the zip on the latest version and it all loads fine and doesn't get reset.
