### ISSUE TITLE
TP_DROPS & SMELT can lead to vanishing blocks (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2222]
## Details

**Describe the bug**
When you mine a block with Telepathy or Smelting, then place a block in the same spot, mining the newly placed block will cause the new block to disappear. 

**To Reproduce** 
1.) Set `use-experimental-block-breaking` to true
2.) Mine a block with a tool that has Telepathy or Smelting
3.) Place a block back in the spot
4.) Mine the newly placed block without Telepathy or Smelting

NOTE: If you mine X blocks with Telepathy/Smelting in the same spot, you can make X blocks disappear by placing them in that spot and mining them without Telepathy/Smelting

**Screenshots / Video**
https://youtu.be/RWxxK9aLFgk

Shows basic demonstration first. Then shows the thing I mentioned in my note.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/xavoqufasu
- Server log: https://mcpaste.io/ad82b65edd4a4f3a

**Comment by Insprill** [comment]
Can you upgrade to Java 16, then see if it still happens? if it does, try removing all your plugins then see if it happens. if it doesn't, add them back one by one until it starts happening again.

**Comment by Insprill** [comment]
@WhatsTheBadNews

**Comment by WhatsTheBadNews** [comment]
I've tested it again:

Version 8.6.4
MC 1.17.1 Tuinity 33
Java 16

The issue no longer seems to persist on these versions.
