### ISSUE TITLE
disappearing armor

### ISSUE THREAD

**Issue by RAPHAEL599** [GC-spigot/AdvancedEnchantments#2223]
## Details

**Describe the bug**
- When you try to take off the armor with the mouse it just disappears

**To Reproduce** 
- To reproduce the bug, just put on any armor and try to take it off with the mouse

**Screenshots / Video**
- https://youtu.be/5D0p5DG5AT8

## Server Information
-https://paste.md-5.net/poqucuguni

**Comment by Insprill** [comment]
Duplicate of #2217
