### ISSUE TITLE
Bugs with advanced achievements

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2224]
kill monsters by customenchant is treated by natural death? #2130 (BUG CONFIRMED)
-> i was reported bug when player kill monster with custom enchanted weapons, a dungeon plugin didn't count that.

this problem is simmilar that bugs. when player break blocks with custom enchanted weapons, advanced achievements didn't count that. 
so player can't break with custom enchanted tools to achivement

**Comment by Insprill** [comment]
Not identical but same cause as #2213
