### ISSUE TITLE
BREAK_TREE only drop oak wood on versions prior 1.13

### ISSUE THREAD

**Issue by CryLegende** [GC-spigot/AdvancedEnchantments#2226]
## Details

**Describe the bug**
BREAK_TREE only drop oak wood on versions prior 1.13 since in 1.8-1.12 Minecraft use data for many blocks like woods

**To Reproduce** 
Enchant a axe with the BREAK_TREE effect and break a tree (other than oak tree)

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/iwiripuheb
- Server log: There is no error, no warning and AE starts normally like all of my other plugins

Thank you for your help

**Comment by Insprill** [comment]
Fixed for then next update
