### ISSUE TITLE
REPLANTER Beetroot consumes Beetroot fruit instead of Beetroot seeds

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2231]
## Details

**Describe the bug**
Did you guys even read my last bug report? I was USING the NEW REPLANTER enchantment, as was suggested in #2183, when trying to replant beetroot, but it still uses "beetroot" fruits instead of "beetroot_seeds". The bug still persists but you guys closed my issues anyway.

Reference to #2167 as the resolution didn't work, but it's been closed and there has been no reply to it. You can now include #2183 in it as well.

**To Reproduce** 
Have replanter on a tool, put Betroot in your off-hand and it would work. Putting beetroot seeds in your off-hand doesn't work as the plugin doesn't seem to recognise it.

**Screenshots / Video**

## Server Information
/ae PLinfo: https://paste.md-5.net/ogapagaloq
server log: https://paste.lucko.me/gaZxw3YN7c

**Comment by Insprill** [comment]
Just to make sure we're on the same page, when i said the *new replanter*, i mean the new revision of it. Can you send the enchants from your enchantments.yml?

**Comment by Jupitour** [comment]
Yes, that's what I've been trying to tell you. It's an issue with the new one, not the old. The first few were typos but replying to them did nothing so I had to open a new issue.

Here's my enchantments.yml REPLANTER bit:

`autoplant:
  display: "&7Autoplant"
  description: "Replants crops when you break them."
  applies-to: "Hoes"
  type: "MINING"
  group: "UNIQUE"
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
    - ALL_HOE
  levels:
    1:
      condition:
        - "%is crop% = false : %stop%"
        - "%is fully grown% = false : %stop%"
        - "%offhand item% = %block drop type% : %allow%"
      effects:
        - "TAKE_AWAY:%block drop type%"
        - "SET_BLOCK:%block type%"`

**Comment by Jupitour** [comment]
I changed the name yes, but it's the same thing

**Comment by Insprill** [comment]
Like I thought, that is, in fact, the old one. The new one can be found [here](https://github.com/GC-spigot/AdvancedEnchantments/blob/master/Default%20Files/enchantments.yml#160).

**Comment by Jupitour** [comment]
You mean this replanter??

replanter:
  display: "%group-color%Replanter"
  description: "Replants crops when you break them."
  applies-to: "Hoes"
  type: "MINING"
  group: "UNIQUE"
  applies:
    - ALL_HOE
  levels:
    1:
      condition:
        - "%is crop% = false : %stop%"
        - "%is fully grown% = false : %stop%"
      effects:
        - "PLANT_SEEDS:0:%block drop type%"

**Comment by Jupitour** [comment]
Because this replanter still has the bug where it uses whatever item is in your off-hand, like it will remove a cobblestone from your off hand to replant a carrot.

**Comment by Jupitour** [comment]
how is that considered fixed?
