### ISSUE TITLE
Lore persists when you use black scroll

### ISSUE THREAD

**Issue by RuizoxVIRTUALHIT** [GC-spigot/AdvancedEnchantments#2232]
**Describe the bug**
When you black scroll an item enchanted with
lore descriptions:
    enabled: true

activated in config, enchantment is removed but lore (description) doesnt

**To Reproduce** 
1. Enable lore-descriptions on config
2. /ae give blackscroll YOU 1 1-100
3. Drag the scroll to the enchanted item
4. Everything works fine, but the lore persists.

**Screenshots / Video**

https://user-images.githubusercontent.com/88433119/128166723-8053ae62-9f20-48d3-92d5-b1f21b180532.mp4

- https://paste.md-5.net/pohiqewore
- Server log: https://mcpaste.io/902fdf02d86f8140

**Comment by Insprill** [comment]
Fixed in the next update
