### ISSUE TITLE
malfunction between vein and telepathy

### ISSUE THREAD

**Issue by Jennlovee** [GC-spigot/AdvancedEnchantments#2233]
https://paste.md-5.net/ulamiwapoh

Version jar  :AdvancedEnchantments-8.0.0-Pre24.0.

When I add the "telepathy" enchantment alone to a pickaxe, all blocks go into my inventory immediately.
But if I also add the "vein" enchantment to mine the entire ores streaks, then telepathy only works with ores and not with the other blocks left on the ground.

**Comment by Insprill** [comment]
You're running a version that is months old... update ae
