### ISSUE TITLE
Error with thunder enchant

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2234]
## Details

**Describe the bug**

Just getting this error in console with the thunder effect https://pastebin.com/7RHN0QmN 
**To Reproduce** 

No idea 
**Screenshots / Video**

https://pastebin.com/7RHN0QmN

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae: 8.6.0
server ver: 1.8.8 taco

**Comment by Insprill** [comment]
Fixed in the next update
