### ISSUE TITLE
Can't combine disarmor enchantment

### ISSUE THREAD

**Issue by crazymarty** [GC-spigot/AdvancedEnchantments#2235]
## Details

**Describe the bug**

You can't combine 2 same levels of disarmor enchantment. For example, if you try to combine 2 swords with disarmor V on both, instead of leveling up its enchantment level, it will just have no effect or it will give disarmor V back.

**To Reproduce** 

Enchant 2 swords with any level of disarmor and try to combine them in an anvil. It will have no effect or it will give result has the same enchantment level. 

**Screenshots / Video**

 
 ![image](https://user-images.githubusercontent.com/62768595/128336772-714e5213-569b-4672-afd4-39f9c0553ddf.png) 
![image](https://user-images.githubusercontent.com/62768595/128336824-0a605e04-6e24-40e6-9ea2-262e8ddc6348.png)
![image](https://user-images.githubusercontent.com/62768595/128336876-689f9862-a8f6-4d41-8b30-28b9c4f436f0.png)

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/ataciboniy 
- Server log:  Can't post it for some reason on MCPaste. It is too big and it even lags my PC.

**Comment by Insprill** [comment]
Just to confirm, disarmour does have a 6th level and anvils are enabled in the ancil.yml?

**Comment by crazymarty** [comment]
Yes, anvils are enabled and they are higher level of disarmour too but I was just giving example

**Comment by Insprill** [comment]
Fixed in the next update
