### ISSUE TITLE
Advanced Enchantments not compatible with Eco Enchantments in the last update

### ISSUE THREAD

**Issue by WizardGtG** [GC-spigot/AdvancedEnchantments#2236]
Advanced Enchantments not compatible with Eco Enchantments in the last update
-lore-descriptions: Not working when the plugin Eco Enchantments is enabled, also I think other stuff not compatible with Eco Enchantments.

I hope you look into it

## Server Information
 https://paste.md-5.net/urufeqowed/

**Comment by Insprill** [comment]
What do you mean it doesn't work?

**Comment by WizardGtG** [comment]
i mean when i use eco enchantments and set | lore-descriptions: true | on advanced enchantments it doesn't show any thing it's not working when you use eco enchantments that's what i mean

**Comment by SNokerYT** [comment]
+1

**Comment by SNokerYT** [comment]
https://imgur.com/a/Ced438a

**Comment by AliveSteve** [comment]
You shouldn't be using two CEs in the first place, that is a recipe for disaster

**Comment by Insprill** [comment]
Yeah, that's never going to end well. But you guys are saying EcoEnchants and Eco, those are 2 very different things. Once is an enchant plugin, the other is a spigot library for devs; so which one is causing issues? I personally don't see how either would considering we have nothing to do with them.
