### ISSUE TITLE
Obsidian destroyer and telepathy not working together

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2237]
## Details

**Describe the bug**

Title says it all
**To Reproduce** 

Grap a telepathy enchant and obsidian destroyer enchant and it won't work. The obsidian will drop on the ground and sometimes it gets glitched under and burns since you are mining in lava etc...

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae: 8.6.0
server ver : 1.8.8

**Comment by Insprill** [comment]
Please send the `ae plinfo` link instead of only saying the ae & server version. There is other info in there we need to fix bugs.

**Comment by LuluxClient** [comment]
> Please send the `ae plinfo` link instead of only saying the ae & server version. There is other info in there we need to fix bugs.

Sure I'll do when I can

**Comment by LuluxClient** [comment]
> Please send the `ae plinfo` link instead of only saying the ae & server version. There is other info in there we need to fix bugs.

Hey I do not wish to show my server plugins in the public, I can send them in your dms or privately.

**Comment by Insprill** [comment]
You can copy all the stuff above plugins and put it in a new bin. Ill add an option to skip plugins in the next update

**Comment by Insprill** [comment]
Fixed in the next update
