### ISSUE TITLE
Weapons damage decreased considerably!

### ISSUE THREAD

**Issue by Shehzad777** [GC-spigot/AdvancedEnchantments#2241]
The latest update has probably nerfed the weapons or there is some bug, all weapons do like 70-80% less damage with the same enchants. You can compare e.g. 8.5.6 or older to 8.6.1. Please advise. We cannot downgrade because the last version had a very critical bug with /heal. Where everyone could use /heal without any permission during combat, but that seems to be resolved in 8.6.1. For now, we urgently need a fix to this or advice on how to tackle this damage issue. It has made the server very unbalanced. Thanks

**Comment by Insprill** [comment]
We did revamp how damage is handled in 8.5.7 and I've made a few more changes in the next version. When the next version comes out, please see if it's still an issue, and if it is, try enabling experimental-damage in the config and see if that has any effect on it.

**Comment by Shehzad777** [comment]
Sure sir. I will try as soon as I can.

**Comment by Insprill** [comment]
@Shehzad777 any updates?
