### ISSUE TITLE
Problem with Guard creepers

### ISSUE THREAD

**Issue by arceusxs2** [GC-spigot/AdvancedEnchantments#2242]
## Details

**Describe the bug**

Hello im having problem with the GUARD:CREEPER:%victim%' is basically also summons cloud of infinite strengh effect that players can get.
**To Reproduce** 

1:
      chance: 100
      cooldown: 3
      condition:
        - '%victim health% > 8 : %stop%'
      effects:
        - 'GUARD:CREEPER:%victim%'
        - 'GUARD:CREEPER:%victim%'
        - 'GUARD:CREEPER:%victim%'
**Screenshots / Video**

https://www.youtube.com/watch?v=-sCePNylyrc

## Server Information
- "/ae plinfo" link: 
- Server log: 
AE: 8.6.1
Git Revision: 2bf0907
Server: git-Purpur-1117 (MC: 1.16.5)
API: 1.16.5-R0.1-SNAPSHOT
Java: 16.0.1

**Comment by Insprill** [comment]
Fixed in the next update
