### ISSUE TITLE
NEW REPLANTER issue, takes whatever you use in your off hand.

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2245]
## Details

**Describe the bug**
So this is from #2231, the bug, afaik, is not fixed.

So when I use the "old replanter", it works as intended but it doesn't work on beetroot, as I've mentioned in the multitude of previous tickets which all just ignored the issue and forced me to use this new one. So I did, and now another issue's popped up - one which I believe I ALSO reported but alas was ignored yet again.

So using the NEW REPLANTER resulted in a bug where, REPLANTER uses whatever is in your OFF-HAND, rather than the seeds. So I could be using the REPLANTER enchanted item to harvest carrots, with some cobblestone in my off hand, and it'll consume cobblestone instead of carrots.

This is the config I'm using:
replanter:
  display: "%group-color%Replanter"
  description: "Replants crops when you break them."
  applies-to: "Hoes"
  type: "MINING"
  group: "UNIQUE"
  applies:
    - ALL_HOE
  levels:
    1:
      condition:
        - "%is crop% = false : %stop%"
        - "%is fully grown% = false : %stop%"
      effects:
        - "PLANT_SEEDS:0:%block drop type%"

I got it from this link: https://github.com/GC-spigot/AdvancedEnchantments/blob/master/Default%20Files/enchantments.yml#160

I sincerely pray that I'm just looking at the wrong REPLANTER because I've now opened 4 tickets on the same topic and the fact that it keeps getting closed without making sure the issue is solved for me is kind of unproductive for both of us.

**To Reproduce** 
Put cobble in your off hand or any random item, enchant the "NEW REPLANTER" on a hoe, the enchantment consumes cobblestone instead of whatever seed should have been used.

**Screenshots / Video**

## Server Information
/ae PLinfo: https://paste.md-5.net/numadibasa

**Comment by Jupitour** [comment]
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6948919/latest.log)

**Comment by Jupitour** [comment]
Can we please make sure the bug is fixed for me this time before closing the ticket, instead of just throwing out a dismissive comment and hoping whatever you said would fix the bug, instead of waiting for me to update that it's fixed?

**Comment by Jupitour** [comment]
Look at #2149 for the description of basically this, but you guys closed it.

**Comment by hkkongou** [comment]
bug confirmed with the following video , can reproduce in my server too, same AE enchantment
https://www.youtube.com/watch?v=rB2LV6GiVL4

**Comment by Insprill** [comment]
Fixed in the next update
