### ISSUE TITLE
AdvancedEnchantments API

### ISSUE THREAD

**Issue by GamendeCat** [GC-spigot/AdvancedEnchantments#2246]
I want to use AdvancedSpawners with SpawnerCollectors. But the API doesn't have that many options.
If you guys could add a way to check itemstacks for spawn type, not just blocks and locations. And also a method to create an itemstack based on spawn type it would be able to work.
Thank you if you could add this to the API.

**Comment by Insprill** [comment]
This is the repo for AdvancedEnchantments, not AdvancedSpawners
