### ISSUE TITLE
Player invincible forever if they use this AXE

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2247]
## Details

**Describe the bug**
Some of the AXE enchants causing players to become invincible to all types of damage somehow, this didn't happen with older versions of AE, also not whats going on or how to fix it.

**To Reproduce** 
Have a AXE with the enchants below on the screenshot, attack someone with it, than become invincible forever until you relog to lose that.

**Screenshots / Video**
https://ibb.co/VHJqRXt

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/aqaderamar
- Server log: https://mcpaste.io/ad8d1f0d7a0e895e

**Comment by Insprill** [comment]
Does it only happen when the McMMO bleed effect is active? might be the same as [this issue](https://github.com/GC-spigot/AdvancedEnchantments/issues/2012).

**Comment by antibitcoin** [comment]
> Does it only happen when the McMMO bleed effect is active? might be the same as [this issue](https://github.com/GC-spigot/AdvancedEnchantments/issues/2012).

players reported that ender dragon and withers become invincible too, so i guess maybe the same, which enchant to disable for a temp fix?

**Comment by Insprill** [comment]
any enchantment that modifies damage. just left a comment #2012, would you mind doing the same?

**Comment by antibitcoin** [comment]
> Any enchantment that modifies damage. I also just left a comment [#2012](https://github.com/GC-spigot/AdvancedEnchantments/issues/2012#issuecomment-894966184), would you mind doing the same?

I don't use MMO items.

**Comment by Insprill** [comment]
That issue is about McMMO, not MMO Items.

**Comment by antibitcoin** [comment]
> That issue is about McMMO, not MMO Items.

They have just updated something about skills staying in weapons
https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/update?update=418219

**Comment by antibitcoin** [comment]
> That issue is about McMMO, not MMO Items.

still having the issue, players telling me its destruction enchant.

**Comment by antibitcoin** [comment]
> Can you send the enchant?

https://mcpaste.io/9f85c81f4d97a317

one of the players abusing this said:
the immortality doesnt have to do with mcmmo at all
its an axe and helmet enchant together
destruction and mighty cleave
destruction for helmet and mighty cleave for axe

I hope this doesn't take any longer to fix, I have already lost lot of my player base cuz of these 10 guys having unfair advantage abusing your plugin.

**Comment by Insprill** [comment]
We can't fix bugs we don't know how to reproduce. I'll take a look at it later today, does use-experimental-damage have any effect on this? For now, you can just disable the enchants causing issues.

**Comment by antibitcoin** [comment]
> We can't fix bugs we don't know how to reproduce. I'll take a look at it later today, does use-experimental-damage have any effect on this? For now, you can just disable the enchants causing issues.

  use-experimental-damage: false

I have no idea, as I said I am not able to preproduce my self but I confirm they are invnicible because I tried killing them with everything, the only way to kill someone is /kill command when he is on that  status, or if he relogs.

what makes you think they are saying the truth I have no idea which enchants causing this, all I know is this was not the case, it was introduced in the update you pushed which fixed the enchantment lore being weird characters.

I am not complaining I know you have too many things to do and bugs to fix, this is the price you pay for being so active, maybe make the plugin stable and stop adding new features or make a dev build for that, its really really a bad idea to push nightly builds on spigotmc sometimes not even compiled.

**Comment by Insprill** [comment]
The next update has a few more changes to how damage is handled with experimental-damage enabled. Once it's out please give it a go and see if there are any differences.

**Comment by Insprill** [comment]
@antibitcoin

**Comment by Insprill** [comment]
Closing since it's the same root cause as #2012 and there hasn't been a response in awhile.
