### ISSUE TITLE
Timber on logs give out logs with NBT damage

### ISSUE THREAD

**Issue by SlyyJacob** [GC-spigot/AdvancedEnchantments#2248]
When using timber enchant on logs, it gives out logs with NBT damage. 
I have tested all logs and oak, spruce, acacia give out normal logs
while dark oak log (nbt damage: 1), birch log (nbt damage: 2), jungle log (nbt damage: 3) give out logs with nbts.

![2021-08-09 13_54_21](https://user-images.githubusercontent.com/36818957/128702222-52098be8-fdf0-43bf-b8ba-61e39de851a1.jpg)
![2021-08-09 13_54_17](https://user-images.githubusercontent.com/36818957/128702225-edd7509c-5732-460c-84a6-4666913eadcd.jpg)
![2021-08-09 13_54_12](https://user-images.githubusercontent.com/36818957/128702226-51a47590-263a-4e3b-b087-491e49a954c5.jpg)

https://paste.md-5.net/juzowufogi

**Comment by Insprill** [comment]
Fixed in the next update
