### ISSUE TITLE
Trench Enchantment glitch?

### ISSUE THREAD

**Issue by rjs06** [GC-spigot/AdvancedEnchantments#2249]
## Details

**Describe the bug**
You can use the trench enchantment to break other blocks other than the targeted block.

**To Reproduce** 
If you place a dirt block down in the end on the obsidian pillars, then proceed to mine the dirt block and it also breaks the obsidian.

**Screenshots / Video**
https://streamable.com/qxizw5

## Server Information
- https://paste.md-5.net/loxaduxuyu
- https://mcpaste.io/11143f2e63472a06

**Comment by Insprill** [comment]
That's literally the point of the enchantment. It breaks blocks around the one you broke.
