### ISSUE TITLE
The pickaxe with abiding enchant could be unlimited copied when place on hat

### ISSUE THREAD

**Issue by AnLan1214090013** [GC-spigot/AdvancedEnchantments#2250]
After using command ‘/hat’ to wear a pickaxe with abiding enchant, holding anything to attack any entity, the holding item will become the pickaxe same as the hat one. So the pickaxe could be unlimited copied.
The server version is 1.12.2 with paperspigot

**Comment by Insprill** [comment]
Please send the `/ae plinfo` link and what plugin is /hat from?

**Comment by AnLan1214090013** [comment]
link: https://paste.md-5.net/wageyorabi
and the hat is using CMI

**Comment by AnLan1214090013** [comment]
> Please send the `/ae plinfo` link and what plugin is /hat from?

link: https://paste.md-5.net/wageyorabi
and the hat is using CMI

**Comment by Insprill** [comment]
Fixed in the next update
