### ISSUE TITLE
Angelic and Ward enchant not work.

### ISSUE THREAD

**Issue by Zetthh** [GC-spigot/AdvancedEnchantments#2251]
## Details

**Describe the bug**
Angelic and ward enchant not work, no error in console.

**To Reproduce** 
Place the enchants on any armor and you will see that it does not work.

**Screenshots / Video**
https://youtu.be/BX2Kj9SnATM

## Server Information
https://paste.md-5.net/emikixewuw

**Comment by Insprill** [comment]
Both of these have pretty low chances of activating and large cooldowns by default, can you try removing the chance & cooldown and see if it works? You can add a MESSAGE effect to see when it procs.
