### ISSUE TITLE
Thorns and REPAIR effect cause item duplication

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2252]
## Details

**Describe the bug**
If a player holds a piece of armour with a REPAIR effect enchantment in their hand, and the armour also has thorns, then the item is duplicated and put onto the player when they take damage.

**To Reproduce** 
Enchant a piece of armour with a REPAIR enchantment and thorns. Hold the item in your hand, and take damage. Eventually, the item will duplicate and appear on your player.

**Screenshots / Video**
https://streamable.com/dpbs4r

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/bagajifuqa

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by Dakotaa** [comment]
This can still be done in the latest version by holding the item in the offhand.
