### ISSUE TITLE
HELD doesn't properly toggle PERMISSION when shift-clicked away

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2253]
## Details

**Describe the bug**
The HELD enchantment type, in my case when used with the PERMISSION effect, does not toggle as expected. When players mouse-scroll on/off the item in the hotbar, the enchant toggles the perm as expected, but if the player, WHILE STILL HOLDING the item, shift-clicks the enchanted item into a container such as a chest or enderchest, the enchantment does not recognise that the item is NO LONGER HOLDING the item, and the player keeps the permission/effect.

However, when the item is re-equipped, the enchantment now REMOVES the effect from the player - inverting its function.

The expected behaviour is that even if shift-clicked off the inventory, the enchantment should recognise that the player is no longer holding the item.

**To Reproduce** 
Create an enchantment with HELD type and PERMISSION effect. Put enchantment item in hotbar and hold it, thus activating the effect. Shift-click said item into a chest or container. Effect is retained permanently despite no longer holding the item.

Here is an example of the bugged enchant from my enchantments.yml:

spawnertouch:
  display: '&7Spawner Silk'
  description: '&oPick up spawners!'
  applies-to: 'Pickaxes'
  type: 'HELD'
  group: 'UNIQUE'
  applies:
    - ALL_PICKAXE
  levels:
    1:
      effects:
        - 'PERMISSION:purpur.drop.spawners'
        - 'PERMISSION:purpur.place.spawners'

**Screenshots / Video**

## Server Information
PLinfo: https://paste.md-5.net/ucojihiboz

**Comment by Insprill** [comment]
Can you try with POTION to see if its just PERMISSION that breaks?

**Comment by Jupitour** [comment]
POTION seems to work, unless you do **/hat** with it (an Essentials vanity command); then it'll stay forever until you hold the enchanted item again.

**Comment by Insprill** [comment]
Fixed the /hat issue, its weird that the PERMISSION isn't working properly. It works as a toggle each time its triggered but if potion gets taken away i don't see why permission wouldn't. Will need to look into it

**Comment by Jupitour** [comment]
Any updates to this?

**Comment by Jupitour** [comment]
Still no fix for this issue?

**Comment by Insprill** [comment]
Fixed in the next update
