### ISSUE TITLE
Server crash anvil

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#2255]
## Details

**Describe the bug**
When someone using anvil

**To Reproduce** 
idk what is that enchantment or what is it...

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/uqipexesud
- Server log: https://mcpaste.io/f0f407df7acba6e5

**Comment by Insprill** [comment]
Duplicate of #2254 - same cause
