### ISSUE TITLE
[BUG] Infinite Effects

### ISSUE THREAD

**Issue by Blazingshadow17** [GC-spigot/AdvancedEnchantments#226]
Can you fix bug where the player holds the right mouse button while holding armor that gives potion effects (speed, jump boost, etc...) and after a while, they get those effects without wearing the armor? (simple fix would be to make auto equip work).

Example.
I have diamond boots that have gears 1,
I hold the diamond boots in my hand,
I hold the mouses right click button,
The armor does not go on my body but gives me speed 1.

**Comment by GC-spigot** [comment]
Fixed in next version.
