### ISSUE TITLE
Right click enchantment info crash

### ISSUE THREAD

**Issue by juancruzdal** [GC-spigot/AdvancedEnchantments#2260]
## Details

**Describe the bug**
Server crash when you display too many times the info of enchantments in /e menu

**To Reproduce**
Right click a enchant group in /e menu too many times (right click -> back -> right click -> back)

## Server Information
- https://paste.md-5.net/itamawizeh
- https://mcpaste.io/d81e62ddfa2b48f3

**Comment by Insprill** [comment]
Duplicate of #2254
