### ISSUE TITLE
Telephaty Have Chance to Duplicate Item From Plugins Slimefun

### ISSUE THREAD

**Issue by LowScarlet** [GC-spigot/AdvancedEnchantments#2261]
## Details

**Describe the bug**
It doesn't always do a dupe, but the chance is very random, I don't know how the bug works

**To Reproduce** 
1. Instal Slimefun Plugins on latest dev build
2. Enchant pickaxe with Telephaty
3. Break block from slimefun

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/oruyopitod

**Comment by Insprill** [comment]
I can't reproduce this. I tried placing & breaking a bunch of random SlimeFun blocks with a pickaxe that has Telepathy and it all worked fine. Can you give more specific reproduction instructions & send a video of it happening?
