### ISSUE TITLE
TP_DROP drops only one slab instead of two double slab in a doubleslab block

### ISSUE THREAD

**Issue by xCloudiness** [GC-spigot/AdvancedEnchantments#2263]
## Details

**Describe the bug**
When mining with an enchant like telepathy that uses 'TP_DROP' and mine a double slab it only returns one slab instead of two. This works with both silktouch and non silktouch tools

**To Reproduce** 
Have an enchant that uses telepathy or something like this
  levels:
    1:
      effects:
        - 'POTION:FAST_DIGGING:0'
        - 'TP_DROPS'

Place it on a tool and mine a doubleslab and it'll only drop one instead of two
**Screenshots / Video**
 https://imgur.com/a/b5fJZ88

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/enociluxap
- Server log:  https://mcpaste.io/be5043b6171e507a

**Comment by Insprill** [comment]
Fixed for the next update
