### ISSUE TITLE
server crashed after player executed enchants; autosmelt with fortune get much more items

### ISSUE THREAD

**Issue by ShallowAi** [GC-spigot/AdvancedEnchantments#2267]
## Details

**Describe the bug**

First one, player executed _/enchants_ too much times, then server crashed.(not confirmed is ae problems)
Second one, if any one use items enchanted with fortune and autosmelt to  break seeds (eg. carrot and potato) even it not grow  still get more seeds.

**To Reproduce** 

Enchant a item with fortune III and autosmelt, break a seeds. then u will get more seeds.

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: 
- https://paste.md-5.net/ixobelaxib
- Server log: 
- crash log https://mcpaste.io/fd2a27a6f0c79849

**Comment by Insprill** [comment]
Fixed in the next update
