### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Shehzad777** [GC-spigot/AdvancedEnchantments#2268]
We are getting this error with the latest version fo the plugin,

> [06:04:42] [Server thread/INFO]: [AdvancedEnchantments ERROR] Could not pass ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
> [06:04:42] [Server thread/INFO]: [AdvancedEnchantments] Class: net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:751)
> [06:04:42] [Server thread/INFO]: [AdvancedEnchantments] Extra info: effect[GUARD:BLAZE]; enchant [spirits]; mc[116]; ae[8.6.4]
> [06:04:42] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [06:04:42] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
> [06:04:42] [Server thread/WARN]: at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:751)
> [06:04:42] [Server thread/WARN]: at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:220)
> [06:04:42] [Server thread/WARN]: at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:323)
> [06:04:42] [Server thread/WARN]: at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:148)
> [06:04:42] [Server thread/WARN]: at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE.playerHitPlayer(DEFENSE.java:64)
> [06:04:42] [Server thread/WARN]: at jdk.internal.reflect.GeneratedMethodAccessor323.invoke(Unknown Source)
> [06:04:42] [Server thread/WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [06:04:42] [Server thread/WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> [06:04:42] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
> [06:04:42] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> [06:04:42] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
> [06:04:42] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
> [06:04:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:249)
> [06:04:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:964)
> [06:04:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:851)
> [06:04:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:807)
> [06:04:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:996)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1761)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:828)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1145)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:745)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:719)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1068)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1632)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2001)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:74)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:13)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851)
> [06:04:42] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
> [06:04:42] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
> [06:04:42] [Server thread/INFO]: [AdvancedEnchantments ERROR] Could not pass ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
> [06:04:42] [Server thread/INFO]: [AdvancedEnchantments] Class:

**Comment by Insprill** [comment]
Fixed in the next update. Use the new GUARD format to fix it until then
