### ISSUE TITLE
Server still crashing

### ISSUE THREAD

**Issue by NightLife-SG** [GC-spigot/AdvancedEnchantments#2269]
Updated to lastest version available right now and server is still crashing

https://github.com/GC-spigot/AdvancedEnchantments/issues/2254#issuecomment-897980721

error ->https://pastebin.com/SZw2aAtj

**Comment by LowScarlet** [comment]
still Crashing..

**Comment by LowScarlet** [comment]
developers are quick on adding issues, but a little lazy in fixing critical issues

**Comment by itslukemango** [comment]
Can confirm this is happening to us too.

**Comment by therbz** [comment]
Also, can confirm this is happening

**Comment by Insprill** [comment]
I pushed the fix a couple of hours after 8.6.4 was released so it will be fixed in 8.6.5.
