### ISSUE TITLE
[HELP / REQUEST] Condition

### ISSUE THREAD

**Issue by Blazingshadow17** [GC-spigot/AdvancedEnchantments#227]
I'm not sure if there is already a way to do this (if there is please tell me how), could you make a condition where it has every _ number of hits/shots/hits taken.

For example, I want to make explosive arrows I-III enchant.
Level I - every 5 shots the arrow explodes on contact.
Level 2 - every 4 shots the arrow explodes on contact.
Level 3 - every 3 shots the arrow explodes on contact.

Also, I'm not sure if there is a way to do a multishot type of thing from the bow.

For example, I want to make a multishot I-V enchant.
Level 1 - every 5 shots shoot three arrows (horizontal to each other).
Level 2 - ...
Level 3 - ...
Level 4 - ...
Level 5 - shoots 3 arrows every shot

(In this situation I would want to make all three arrows explosive if the explosive arrows enchant and multishot enchant were combined)

Please help me out! Thanks!

**Comment by GC-spigot** [comment]
Can't be done.
