### ISSUE TITLE
Duplicated enchants

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2270]
## Details

**Describe the bug**

When adding a custom enchant book on an item it duplicates it. 
**To Reproduce** 

Grab the same enchantement with different levels and apply it on your item
**Screenshots / Video**

https://gyazo.com/b59da8ed589097996eb496feea1288ca

## Server Information
- "/ae plinfo" link: 
- Server log: 
ae plinfo: private
server log: private / no errors

**Comment by Insprill** [comment]
you can do `/ae plinfo skipPlugins` to skip adding plugins to it

**Comment by Insprill** [comment]
Fixed in the next update
