### ISSUE TITLE
Block break counter is broken

### ISSUE THREAD

**Issue by vlaetansky** [GC-spigot/AdvancedEnchantments#2271]
## Details

**Describe the bug**
Block tracker counter dupes in the item's lore. It is causing very heavy lags on both server and client.

**To Reproduce** 
I have no idea how it's happening

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/87545780/129380746-6edc87d6-3ebf-41fd-8111-fa0c5d4ffae9.png)
![image](https://user-images.githubusercontent.com/87545780/129380897-1a5fdecd-0378-43f0-b63e-1d87a7d22b9c.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ihayasevew
- Server log: https://mcpaste.io/e6788f58c986c58d

**Comment by Insprill** [comment]
Update AE.

**Comment by vlaetansky** [comment]
Fix AE and learn what "quick fix" is.

![image](https://user-images.githubusercontent.com/87545780/129384567-b28d7a28-8470-47ab-94a9-e3c81ffe88f5.png)
