### ISSUE TITLE
Failed to parse effect 'GUARD' for enchantments with GUARD 

### ISSUE THREAD

**Issue by n0tailz-debug** [GC-spigot/AdvancedEnchantments#2273]
## Details

**Describe the bug**
Failed to parse effect 'GUARD' for enchantments with any enchants that have the GUARD effect

**To Reproduce** 
once the player gets hit it appears

**Screenshots / Video**
![123](https://user-images.githubusercontent.com/78484864/129442848-af13b7b0-fd3d-41fc-a9b7-2bb661a58dd1.PNG)

## Server Information
- https://paste.md-5.net/nogakicomo
- Server log: https://mcpaste.io/bb832bb9a742e366

**Comment by Insprill** [comment]
Fixed in the next update
