### ISSUE TITLE
Enchantment tables don't persist show enchants when used

### ISSUE THREAD

**Issue by Sealflipper** [GC-spigot/AdvancedEnchantments#2274]
Hi, a player reported this big to me.
He said when he tried enchanting at lvl 40, it showed protection 3 would be in the enchant, but when he accepted it, it turned into unbreaking 3.
He was recording at the time and caught the bug. I attached a link here
[Players video](https://media.discordapp.net/attachments/837061011127140362/876156518691635280/Minecraft_1.17.1_2021-08-14_18-30-56.mp4)

**Comment by Sealflipper** [comment]
Also wanted to mention that it happened twice to him.

**Comment by Insprill** [comment]
Please do `/ae plinfo` and send the link.
