### ISSUE TITLE
TPS loss when right click with a AE enchantment book!

### ISSUE THREAD

**Issue by kn-km** [GC-spigot/AdvancedEnchantments#2277]
## Details

**Describe the bug**

Hold a enchant book then right-click air continuously. Then it starts.
**To Reproduce** 

Hold a enchant book then right-click air continuously.
**Screenshots / Video**

https://timings.aikar.co/?id=ac967028f9954e36b5cc936687437165

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://paste.md-5.net/afapiqeveg
https://mcpaste.io/deff9202ad759827

**Comment by Insprill** [comment]
Same cause as the recent crashes. Foxed in 8.6.5
