### ISSUE TITLE
EXP dupe in grindstone with AE enchanted MMOItems weapon.

### ISSUE THREAD

**Issue by kn-km** [GC-spigot/AdvancedEnchantments#2278]
## Details

**Describe the bug**

If trying to remove a MI weapon with AE enchant in the grindstone. The Enchantment will not lose and EXP will return to the player.
Please try to change EventPriority and check if the event is canceled. 
**To Reproduce** 

Try to remove a MI weapon with AE enchant in the grindstone, this will happen. 
**Screenshots / Video**

Not needed.

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://paste.md-5.net/afapiqeveg
Nothing to show and not needed.

**Comment by Insprill** [comment]
Should be fixed in the next update. If not comment and I'll reopen this.
