### ISSUE TITLE
AE Enchantment book's name was not removed after grindstone removement.

### ISSUE THREAD

**Issue by kn-km** [GC-spigot/AdvancedEnchantments#2279]
## Details

**Describe the bug**

Put an AE Enchantment book in the grindstone, and use it. The result book's display name was not removed.
**To Reproduce** 

Put an AE Enchantment book in the grindstone, and use it. The result book's display name was not removed.

**Screenshots / Video**

Not needed.

## Server Information
- "/ae plinfo" link: 
- Server log: 
Not needed.

**Comment by Insprill** [comment]
Can't fix until we find a way to access grindstone results at a lower level.
