### ISSUE TITLE
[ISSUE] Config

### ISSUE THREAD

**Issue by Blazingshadow17** [GC-spigot/AdvancedEnchantments#228]
I tried adding white scroll into the /e (shop area), I copied and pasted the example from the wiki, and it didn't work, it just gives me a simple enchant, can you show me how to add the special items to this shop? thanks!

This is what I copied from the wiki:

https://pastebin.com/3RypNMw5

**Comment by GC-spigot** [comment]
Remove `enchant-group: SIMPLE` from that item.
