### ISSUE TITLE
The Item with only AE enchantment can not use in the grindstone.

### ISSUE THREAD

**Issue by kn-km** [GC-spigot/AdvancedEnchantments#2280]
## Details

**Describe the bug**

Drag an enchantment book onto a weapon, then put it in the grindstone. The grindstone does not work at all. 
But if with vanilla enchantment and AE enchantment, it works.
It is really weird.
**To Reproduce** 

Drag an enchantment book onto a weapon, then put it in the grindstone. The grindstone does not work at all. 
But if with vanilla enchantment and AE enchantment, it works.
**Screenshots / Video**

Not needed.

## Server Information
- "/ae plinfo" link: 
- Server log: 
Not needed.

**Comment by Insprill** [comment]
Fixed in the next update
