### ISSUE TITLE
Trench giving non-obtainable blocks

### ISSUE THREAD

**Issue by Yomaxdog** [GC-spigot/AdvancedEnchantments#2281]
## Details

**Describe the bug**
A player with a pickaxe using the Trench 8 and Telepathy 1 enchants and vanilla fortune 3 enchant was able to pick up a Budding Amethyst block, a block that cannot typically be obtained even with silk touch.

**To Reproduce** 

Use a Trench pickaxe (any level seems would do, I tested with trench 5 and trench 8) mine next to a budding amethyst (ajacent to the block, so trench's effect mines it) then check if it drops, I recommend Telekinesis on the pickaxe aswell to make this easier.

**Screenshots / Video**

![AE_Pickaxe_That_gives_Budding_Amethyst_Blocks](https://user-images.githubusercontent.com/76832152/129461972-3b0a2dd3-e846-4ac8-92cd-21bc814b4c23.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/juvopidoru
- Server log: https://mcpaste.io/64d9d5dcf0b631a4

**Comment by Insprill** [comment]
Add it to the trench blacklist in the config. Will put in an internal system to always have unobtainable blocks be blacklisted

**Comment by Insprill** [comment]
The next update will ensure blocks that aren't obtainable can't be broken with TRENCH.
