### ISSUE TITLE
Firework Star is Now book after update

### ISSUE THREAD

**Issue by TheLeby9** [GC-spigot/AdvancedEnchantments#2283]
## Details

**Describe the bug**

So basically when u go /e and buy any enchant book it usually looks like a firework star with the color of the enchant group. but for some reason when i updated the plugin its now a book and idk if it a bug or if its something in the configs but its very bad and i want it to be nether star again.

**To Reproduce** 

Go /e and buy any enchnatment book. as you can see in the video below the old enchantments unopened books are firework stars but now they are books for some reason.

**Screenshots / Video**

https://streamable.com/psnsu5

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/epolitiwov
- Server log: 
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/6989128/latest.log)

**Comment by Insprill** [comment]
We changed the groups.yml format recently, it should've been upgraded keeping your values. What version did you upgrade from and upgrade to? Also please send your groups.yml.

**Comment by TheLeby9** [comment]
it seemed like there was an issue in groups.yl  the item was changed from FIREWORK_CHARGE to BOOK by itself . nobody had touched or changed that since am the only one how touches that plugin .

**Comment by Insprill** [comment]
Please still provide the information i asked for

**Comment by TheLeby9** [comment]
from 8.6.2 to 8.6.4

**Comment by Insprill** [comment]
Was in fact a bug, fixed in the next update

**Comment by TheLeby9** [comment]
it was indeed a bug cz the new updated version was causing the server to crash also, and when i downgraded and tried changing back groups.yml to the star it stayed as book its very buggy. hopefully its fixed in next update

**Comment by Insprill** [comment]
It was fixed in 8.6.6
