### ISSUE TITLE
BREAK_TREE works if the enchanted item is held in your off hand, and you break a tree with an axe in your main hand

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2285]
## Details

**Describe the bug**
On my server I have an iron axe enchanted with the BREAK_TREE effect with the MINING type, for the purpose that due to the Iron Axe's low durability it would break after a few trees. However, someone can just hold the enchanted BREAK_TREE axe in their off-hand, and break a tree with a netherite/diamond axe in their main hand, and no durability loss would have been suffered by the enchanted item, despite the BREAK_TREE effect activating and destroying the tree with one block broken.

**To Reproduce** 
Hold axe enchanted with BREAK_TREE in off hand, use a netherite axe to break a tree in main hand. No durability loss suffered by the enchanted axe but BREAK_TREE activates anyway.

**Screenshots / Video**
treefeller:
  display: '&7Treefeller'
  applies-to: 'Pickaxe'
  description: '&oTreefeller'
  type: 'MINING'
  group: 'UNIQUE'
  applies:
    - ALL_PICKAXE
  levels:
    1:
      effects:
        - 'BREAK_TREE'

## Server Information
https://paste.md-5.net/exucoquvop

**Comment by Insprill** [comment]
Fixed in the next update
