### ISSUE TITLE
Fortune and telepathy broke again only for ores

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2286]
## Details

**Describe the bug**

If you mine an ore such as diamonds you will ALWAYS get between 1 and 2 diamonds
**To Reproduce** 

Grab a diamond pickaxe, enchant it with fortune and telepathy, grab a second pickaxe with only fortune 3 and you will see on the telepathy pickaxe you only get between 1 and 2 diamond and on the fortune default one you get more than that (real drops)
**Screenshots / Video**

With telepathy : https://gyazo.com/689fa62f213521fd44cf5a6aea4c4198
Without telepathy: https://gyazo.com/e4938fe15e5dc09d8d038b0d60daba47
## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/ledoyikife
- Server log:  no erros

More info : 

It only broke on ores not on crops, please don't change the crops. Please.

**Comment by Insprill** [comment]
Fixed in the next update
