### ISSUE TITLE
Plugin does not enable if default groups are modified

### ISSUE THREAD

**Issue by SenPr** [GC-spigot/AdvancedEnchantments#2287]
## Details

**Describe the bug**
If I deleted, or modify the default groups in groups.yml, the plugin will not enable with this error:
https://pastebin.com/GuEsNM3M

**To Reproduce** 
Rename any of the default groups, or delete them in groups.yml

**Screenshots / Video**
Logs: https://pastebin.com/GuEsNM3M
No screenshot/video.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ezukokohiy
- Server log: https://mcpaste.io/d6b1e4f892b466da

**Comment by Insprill** [comment]
Temp fix is to make sure the enchantmentTable.yml groups are synced with the groups.yml groups

**Comment by Insprill** [comment]
Fixed in the next update
