### ISSUE TITLE
TP_DROPS drops only one cocoa bean when breaking cocoa beans

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2289]
## Details

**Describe the bug**
When harvesting cocoa beans with a TP_DROPS enchantment, only one cocoa bean is dropped, which is not vanilla behaviour. 

**To Reproduce** 
Enchant a tool with a TP_DROPS enchantment, break a fully grown cocoa bean pod. Only one cocoa beans will drop.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yadisemepi

**Comment by Dakotaa** [comment]
Same issue with nether warts.

**Comment by Insprill** [comment]
Fixed in the next update
