### ISSUE TITLE
Feature Request Condition

### ISSUE THREAD

**Issue by Alucat98** [GC-spigot/AdvancedEnchantments#229]
a `%has tag%` condition would be great.
since vanilla and some plugins use tags for mobs or player you could check if they have one
e.g. `condition: '%victim has tag% = cursed : %continue%`
      `condition: '%attacker has tag% = blessed : %continue%`

**Comment by GC-spigot** [comment]
Is this some kind of a minecraft feature or a plugin feature? Can you elaborate more and possibly link some wiki page if this is a minecraft feature.

**Comment by Alucat98** [comment]
https://minecraft.gamepedia.com/Commands#tag
It's a minecraft feature but plugins which summon mobs with a minecraft nbt-tags would also be supported if you add this

egmythicmobs:
https://mythicmobs.net/manual/doku.php/skills/mechanics/addtag

**Comment by GC-spigot** [comment]
Thank you, I'll look into this!

**Comment by Alucat98** [comment]
> 
> 
> Only 22.7% of all servers are 1.13 or higher, Im pretty sure thats not "most people".
> 
> 1.13 was a big backend update and Im still focusing on versions that are used mostly - 77% of minecraft servers use.
> 
> That does not say that it wont be fixed on 1.13, it says that theres a priority for lower versions.

Is that also the reason why this request got closed without a comment?
Just asking since I'am curious about the closing-reason

> "I'll look into this!"
