### ISSUE TITLE
BREAK enchantments don't drop the broken block

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2290]
## Details

**Describe the bug**
When instantly breaking a block with a BREAK enchantment (in this case, obsidian with a pickaxe), the block does not drop.

**To Reproduce** 
Enchant a pickaxe with an enchantment with the BREAK effect, break the block instantly, and it will not drop.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yadisemepi

**Comment by Insprill** [comment]
Fixed in the next update
