### ISSUE TITLE
TP_DROPS tools still don't reward mcMMO exp

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2291]
## Details

**Describe the bug**
When breaking blocks with a TP_DROPS enchanted tool, no mcMMO exp is rewarded.

**To Reproduce** 
Enchant a tool with a TP_DROPS enchantment, break a block. For example, a pickaxe with TP_DROPS to mine stone. You will receive no mcMMO exp when using this tool.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yadisemepi

**Comment by Insprill** [comment]
Is experimental-block-breaking enabled? If not enable it.
