### ISSUE TITLE
TP_DROPS gives XP on Ores that aren't supposed to

### ISSUE THREAD

**Issue by SenPr** [GC-spigot/AdvancedEnchantments#2292]
## Details

**Describe the bug**
As title suggests, Using TP_DROPS on ores such as Iron Ore, Gold Ore for whatever reasons, gives XP.

**To Reproduce** 
You could use default Telepathy, or make an enchant that has 100% chance TP_DROPS to test this.

**Screenshots / Video**
None

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ezukokohiy
- Server log: no errors

**Comment by Insprill** [comment]
Fixed for the next update
