### ISSUE TITLE
HEX Color Problem | not removing enchant lore when you use colors on a group

### ISSUE THREAD

**Issue by SNokerYT** [GC-spigot/AdvancedEnchantments#2293]
## Details
**When you use a Hex color on a group global-color and you add Enchants on items you will not be able to remove it again
Because you using Hex Color**

1 - i'm using a last Version of advancedEnchants v8.6.5
2 - go to Groups and put a Hex color inside the global-color For Example and save the file
```
  ELITE:
    global-color: "{#5b0d82}"
    group-name: "Elite"
    item:
```
3 - Restart you server 
4 - type | /advancedenchantments enchant etheral 1 | you will see that Enchant has been added
5 - type this command to remove the Encahnt | /advancedenchantments enchant etheral 1 | you will see that Enchant still there the Enchant Did not removed 
![image](https://user-images.githubusercontent.com/68678154/129776038-9315fcd8-27fb-48d9-87d8-6dc8d9d166a8.png)
![image](https://user-images.githubusercontent.com/68678154/129776272-61a33464-fb3e-41a6-82ec-1d8314b2fab7.png)

_**this problem tested on 2 different servers and same problem happend**_

**Screenshots / Video**
![advancedenchants3f1](https://user-images.githubusercontent.com/68678154/129776442-e6910e81-4a91-40c0-89e7-91510d0f501c.gif)

## Server Information
/ae plinfo https://paste.md-5.net/lelopazise

**Comment by Insprill** [comment]
Fixed in the next update
