### ISSUE TITLE
VEIN_MINE works if the enchanted item is held in your off hand, and you break a tree with an axe in your main hand

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2295]
## Details

**Describe the bug**
Refer to #2285, this bug is exactly the same but with VEIN_MINE as the effect, instead of BREAK_TREE.

**To Reproduce** 
Hold pickaxe enchanted with VEIN_MINE in off hand, use a netherite axe to break a tree in main hand. No durability loss suffered by the enchanted axe but VEIN_MINE activates anyway.

**Screenshots / Video**
veinminer:
  display: '&7Veinminer'
  applies-to: 'Pickaxe'
  description: '&oVeinminer'
  type: 'MINING'
  group: 'UNIQUE'
  applies:
    - ALL_PICKAXE
  levels:
    1:
      effects:
        - 'VEIN_MINE'

## Server Information
https://paste.md-5.net/exucoquvop

**Comment by Insprill** [comment]
As you said the bug is exactly the same lol. Fixed in the next update
