### ISSUE TITLE
Enchants from lore line are not updating

### ISSUE THREAD

**Issue by n0tailz-debug** [GC-spigot/AdvancedEnchantments#2297]
## Details

**Describe the bug**
The Lore is not updating i reported this before the update Example Bleed 3 and i need bleed 3 book to upgrade it to 4 but it still says its bleed 3

**To Reproduce** 
Upgrade any enchantment but mostly try bleed just to be sure.

**Screenshots / Video**

## Server Information
![3123](https://user-images.githubusercontent.com/78484864/129888516-ffedb827-45e2-47f3-8547-ca0538c43444.PNG)

- "/ae plinfo" link: https://paste.md-5.net/wipudajuda
- Server log: https://mcpaste.io/c7aeff913f156a0f

**Comment by Insprill** [comment]
Duplicate of #2293
