### ISSUE TITLE
Gkit stopped working throwing java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by denisdnu** [GC-spigot/AdvancedEnchantments#2298]
## Details

**Describe the bug**
Commands /gkit and /ae givegkit fails to give kit. 
**To Reproduce** 
Execute command /ae givegkit Dinikin Viking 
or /gkit
and select any kit in GUI
**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ucimafucez
- Server log: https://mcpaste.io/b9182fd6b260c57b

**Comment by Insprill** [comment]
Not a bug. You have a configuration error. Please join our [Discord server](https://discord.gg/GzdQdMw) for support.
