### ISSUE TITLE
Enchantment TRENCH stops working after switching from survival to creative mode and back

### ISSUE THREAD

**Issue by denisdnu** [GC-spigot/AdvancedEnchantments#2299]
## Details

**Describe the bug**

Enchantment TRENCH stops working after switching from survival to creative mode and back.
Actually different enchantments were observed to stop working after these steps. So it's not trench only related issue.
**To Reproduce** 

1. Switch to survival mod.
2. Take any pickaxe and apply trench enchantment. 
3. Switch to creative mode.
4. Open inventory.
5. Close inventory.
6. Switch to survival mode.
7. Try using the pickaxe. 
8. The enchantment trench is not working.
**Screenshots / Video**

https://youtu.be/vgHQgyrt0tg

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ucimafucez
- Server log: https://mcpaste.io/b9182fd6b260c57b

**Comment by Insprill** [comment]
Works fine for me. Is this still an issue in 8.6.7? If it is, use the /data command and send a screenshot of it after it stops working.
