### ISSUE TITLE
[BUG] Premade Setups

### ISSUE THREAD

**Issue by Alucat98** [GC-spigot/AdvancedEnchantments#230]
If I use /ae premade and click an item I only can move it around
but it doesn't download anything
![2018-11-27_12 08 55](https://user-images.githubusercontent.com/7283243/49078645-d88fd880-f23e-11e8-89aa-561e5b7ac82c.png)

**Comment by GC-spigot** [comment]
Check console for errors. Your internet connection might be slow/my server was down at the time of trying this. Works now perfectly, comment on this issue if it happens again.
