### ISSUE TITLE
VEIN_MINE effect does not drop items as of 8.6.5

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2300]
## Details

**Describe the bug**
As of 8.6.5, VEIN_MINE effect works but does not drop items anymore - it removes all the connected ores (they disappear, or get "veinmined" as they should) but nothing drops at all.

**To Reproduce** 
Simply mine any ore with an item enchanted with VEIN_MINE and nothing drops.

**Screenshots / Video**
veinminer:
  display: '&7Veinminer'
  applies-to: 'Pickaxe'
  description: '&oVeinminer'
  type: 'MINING'
  group: 'UNIQUE'
  applies:
    - ALL_PICKAXE
  levels:
    1:
      effects:
        - 'VEIN_MINE'

## Server Information
https://paste.md-5.net/savicicije

**Comment by MrKrisy1234** [comment]
I am having this issue too

**Comment by Insprill** [comment]
Fixed in the next update
