### ISSUE TITLE
Vein Miner / Telepathy Dupe (add a blacklist for these)

### ISSUE THREAD

**Issue by zestym3m3s** [GC-spigot/AdvancedEnchantments#2301]
## Details

**Describe the bug**
Basically my friend made a plugin so players could pick up placed spawners with silk touch. We found it duped the spawners with telepathy and veinminer. If a blacklist for these enchants could be added I believe it would fix the problem. A blacklist would be non-intrusive and would probably solve any future issues of this kind. 

**To Reproduce** 
Reproducing this is a bit tricky since it requires the plugin he made. Essentially, the plugin tracks if a spawner has been placed by a player and if it was it can be broken with silk touch. If you try to silk touch a natural spawner it will not drop an item. We think that telepathy and vein miner are registering block break events and are giving the player multiple spawners (1 from my friends plugin, one from telepathy, and one from vein miner I think). If there was a way to blacklist spawners from telepathy and vein miner I think this problem would be solved. 

## Server Information
- "/ae plinfo" link: 
- Server log: 
I’m typing this on my phone so I won’t be able to provide any server information. This post is a mix of a suggestion and an unofficial bug since its related to his plugin. If there was a blacklist for these enchants I think this problem would be resolved.

**Comment by Insprill** [comment]
What AE version are you running? Vein mine has operated off a whitelist only for awhile now and all the other mining type enchants should just ignore spawners

**Comment by zestym3m3s** [comment]
8.4.1. I'll update to the newest version to check. 

When I enchant Vein Miner III and Silk Touch on a pickaxe and break a default Spawner drops to the ground.

When I use a default silk touch pickaxe it doesn't drop a Spawner. Only with AE Vein Miner III will the spawner drop.

When I enchant with Telepathy IV and Silk touch it doesn't drop a Spawner.

(While using my friends plugin) When I enchant Telepathy IV, Vein Miner III, and Silk Touch it teleports a default spawner, plus 2 of the plugins "custom spawners" to my inventory.

(While using my friends plugin) When I enchant Telepathy IV and Silk Touch it teleports 1 of my friend's plugin's "custom spawners" to my inventory. 

Vein miner is somehow messing with something. If there was a blacklist I could just blacklist Spawners and there shouldn't be a dupe issue. Or maybe theres something else that could be changed in the code. I'll update and let you know if theres still an issue.

**Comment by zestym3m3s** [comment]
Looks like its working as intended now, not sure what the problem was but updating it fixed it. Sorry for taking up your time.
