### ISSUE TITLE
Cannot wear Helmet manually

### ISSUE THREAD

**Issue by SenPr** [GC-spigot/AdvancedEnchantments#2302]
## Details

**Describe the bug**
If a helmet is enchanted with a helmet only enchantment, it cannot be worn manually.
It can be worn through right-clicking on hot-bar and everything works as usual.

**To Reproduce** 
Enchant your helmet with an enchant that only applies to helmets.
Open inventory and drag your helmet on manually.
It will says: "Can't use this item as a hat"
Right Clicking the helmet while holding it in hotbar will still put the helmet on as normal.

**Screenshots / Video**
None

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ewiruvofab
- Server log: No errors in logs.

**Comment by SenPr** [comment]
Want to also add that shift-clicking the helmet would still works.

**Comment by Insprill** [comment]
Not an issue with AE. Whatever plugin you use for hats is blocking it.
