### ISSUE TITLE
TP_DROPS inconsistant with KGenerator blocks

### ISSUE THREAD

**Issue by SenPr** [GC-spigot/AdvancedEnchantments#2303]
## Details

**Describe the bug**
TP_DROPS enchants will sometimes drop the item.

**To Reproduce** 
Enchant pickaxe with TP_DROPS enchantment
Mine as usual

**Screenshots / Video**
https://gyazo.com/bf19599c39161b878b40601ac02a3053
Will note the blocks I'm mining are from the plugin KGenerators.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ebupixahiv
- Server log: No errors on logs

**Comment by Insprill** [comment]
Please send the enchantment. You most likely have a chance on it.

**Comment by SenPr** [comment]
There is no chance on it.
Enchant: https://pastebin.com/2t8XKPQk

**Comment by Insprill** [comment]
Can you send a video of it happening?

**Comment by SenPr** [comment]
There is a short clip above?

But if you want me to record it happening again, heres a video
https://youtu.be/IB45VVb5M_g

Happened once early on the video, happened another time near the end.

**Comment by Insprill** [comment]
Oh sorry missed the first video, does it still happen without the plugin changing the blocks?

**Comment by SenPr** [comment]
Tested it for a while, seems to work fine if its not a KGenerator block.
Guess its some sort of conflict

**Comment by Insprill** [comment]
Looking at [their code](https://github.com/Kryniowesegryderiusz/KGenerators/blob/main/core/src/main/java/me/kryniowesegryderiusz/kgenerators/listeners/BlockBreakListener.java) around handling blocks being broken, besides it being a mess, it looks like they're listening to the event at a lower priority and canceling it, then breaking the block on their own; which means that there isn't anything we can do to add support, unfortunately.
