### ISSUE TITLE
PLANT_SEED no longer works as of 8.6.6

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2304]
## Details

**Describe the bug**
As of 8.6.6 the PLANT_SEEDS effect has simply stopped working.

**To Reproduce** 
Items enchanted with the PLANT_SEED effect no longer works

**Screenshots / Video**
replanter:
  display: "&7Replanter"
  description: "Replants crops when you break them."
  applies-to: "Hoes"
  type: "MINING"
  group: "UNIQUE"
  applies:
    - ALL_HOE
  levels:
    1:
      condition:
        - "%is crop% = false : %stop%"
        - "%is fully grown% = false : %stop%"
      effects:
        - "PLANT_SEEDS:5:%block drop type%"

## Server Information
https://paste.md-5.net/wenesiceqe

**Comment by Jupitour** [comment]
On further testing, this seems to work:

autoplant:
  display: "&7Autoplant"
  description: "Replants crops when you break them."
  applies-to: "Hoes"
  type: "MINING"
  group: "UNIQUE"
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
    - ALL_HOE
  levels:
    1:
      condition:
        - "%is crop% = false : %stop%"
        - "%is fully grown% = false : %stop%"
        - "%offhand item% = %block drop type% : %allow%"
      effects:
        - "TAKE_AWAY:%block drop type%"
        - "SET_BLOCK:%block type%"

but runs into the same issue as specified in #2183

**Comment by Insprill** [comment]
Fixed in the next update
