### ISSUE TITLE
RIGHT_CLICK working when Action.LEFT_CLICK_BLOCK

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#2305]
## Details

**Describe the bug**
RIGHT_CLICK type working when PlayerInteractEvent.getAction() == Action.LEFT_CLICK_BLOCK

**To Reproduce** 
Use this type and try to left click on block

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/evugugasid

**Comment by Insprill** [comment]
Fixed in the next update
