### ISSUE TITLE
'TP_DROP' only gives 1 book instead of 3 in a bookshelf

### ISSUE THREAD

**Issue by xCloudiness** [GC-spigot/AdvancedEnchantments#2307]
## Details

**Describe the bug**
 I have mentioned this on a previous issue but since it was completely unrelated i think i have to make a new one. When mining a bookshelf using an enchant like telepathy or that uses 'TP_DROP' it only drops 1 book instead of 3

**To Reproduce** 

Have an enchant like telepathy, or an enchantment that uses 'TP_DROP' and mine a bookshelf it'll drop 1 instead of 3
**Screenshots / Video**

https://cdn.discordapp.com/attachments/723628259576643664/877966371647012884/TicsIfWm7Y.gif

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/pecuzokiri
- Server log:   https://mcpaste.io/ba77c2ac363dbd70

**Comment by Insprill** [comment]
Fixed in the next update
