### ISSUE TITLE
ADD_HARM not ignore armor

### ISSUE THREAD

**Issue by Neekokaiinn** [GC-spigot/AdvancedEnchantments#2308]
## Details

**Describe the bug**
the effect ADD_HARM does'n not ignore armor, but it did before a snapshot 

**To Reproduce** 
do an enchant with a high harm like ADD_HARM:15 , test on someone with diamond armor and P5 or P4 enchant and see

**Screenshots / Video**

## Server Information
AE : 8.6.5
SERVER : 1.8.8

**Comment by Insprill** [comment]
Not a bug. We changed how damage is handled internally, and this is a side effect that we aren't going to fix. You can adjust your enchants to compensate.
