### ISSUE TITLE
[ISSUE] Repeat 'TYPE'

### ISSUE THREAD

**Issue by Blazingshadow17** [GC-spigot/AdvancedEnchantments#231]
Can you help me make this auto repair stuff?

https://pastebin.com/L9Qz2fJJ

**Comment by GC-spigot** [comment]
What issues are you having with this? Also, what's your Minecraft version and AE's?

**Comment by Blazingshadow17** [comment]
It is just not auto repairing the items, no config errors or loading errors, or anything, it just does nothing...
I am using 5.0.2 currently.

**Comment by Blazingshadow17** [comment]
> What issues are you having with this? Also, what's your Minecraft version and AE's?
It is just not auto repairing the items, no config errors or loading errors, or anything, it just does nothing...
I am using 5.0.2 currently.
