### ISSUE TITLE
bug with REMOVE_ENCHANT and ADD_ENCHANT duplication

### ISSUE THREAD

**Issue by Neekokaiinn** [GC-spigot/AdvancedEnchantments#2310]
## Details

**Describe the bug**
REMOVE_ENCHANT and ADD_ENCHANT can duplicate item, for ADD_ENCHANT when an enchant is added to a victim item actualy it duplicate the item attacker is holding 
And for REMOVE_ENCHANT, using the enchant is enough

**To Reproduce** 
activate these enchant
ADD_ENCHANT:
givingtest:
  display: '%group-color%giving test'
  description: 'test give'
  applies-to: 'Sword'
  group: 'SIMPLE'
  type: 'ATTACK'
  applies:
    - 'ALL_ARMOR'
  levels:
    '1':
      chance: 100
      effects:
        - 'ADD_ENCHANT:poule:1 %victim%'

REMOVE ENCHANT : 
magie:
  display: '%group-color%Magie'
  description: 'protect magic'
  applies-to: 'all'
  group: 'SIMPLE'
  type: 'HELD'
  applies:
    - 'ALL_ARMOR'
  levels:
    '1':
      chance: 100
      cooldown: 10
      effects:
        - 'REMOVE_ENCHANT:lamewither'

**Screenshots / Video**
ADD_ENCHANT:
https://user-images.githubusercontent.com/87507334/130260319-371af818-0b29-4d4d-b49e-881a00fd386d.mp4
(look at enemy hand before and after the hit)

REMOVE_ENCHANT
https://user-images.githubusercontent.com/87507334/130260098-b5b1ed0e-18f4-4357-a885-99d244f09b15.mp4

## Server Information
AE : 8.6.5
MC : 1.8.8

**Comment by Insprill** [comment]
Fixed in the next update
