### ISSUE TITLE
Lang Chinese (Simplified) is garbled code and something unreadable

### ISSUE THREAD

**Issue by Chinese-Cyq20100313** [GC-spigot/AdvancedEnchantments#2311]
## Details

**Describe the bug**

I am Chinese, I edit the plugin config language to zh-cn
Then I issue /ae reload command
I check the language changed, And then I saw some text turn to garbled code
**To Reproduce** 

Change language to zh-cn,
reload this plugin
send command like /ae info abiding
you will see garbled code
**Screenshots / Video**

![image](https://user-images.githubusercontent.com/68551684/130261052-a65c870e-3732-4648-b781-4d7a6debf16a.png)
![image](https://user-images.githubusercontent.com/68551684/130261086-409516dd-ad46-4251-81b5-963681f74167.png)
![image](https://user-images.githubusercontent.com/68551684/130261109-c03ef5b7-c2fd-4700-be80-ed19968b9c66.png)

## Server Information
- "/ae plinfo" link: 
- https://paste.md-5.net/ujalaqinuf
- Server log: 
https://mcpaste.io/e3f33548e0157266

**Comment by SenPr** [comment]
adding -Dfile.encoding=UTF-8 into your start script might help
