### ISSUE TITLE
EFFECT_STATIC does not work with Turtle Shells

### ISSUE THREAD

**Issue by Complex1tive** [GC-spigot/AdvancedEnchantments#2312]
## Details

**Describe the bug**
EFFECT_STATIC with ALL_ARMOR does not work with Turtle Shells

**To Reproduce** 
Apply an EFFECT_STATIC enchantment onto a Turtle Shell and wear it.

**Screenshots / Video**
[https://i.imgur.com/OlD4nIA.mp4](https://i.imgur.com/OlD4nIA.mp4)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ututumufer
- Server log: https://bin.bloom.host/urekinacul.yaml

**Comment by Insprill** [comment]
Not really a bug but I've added it into ALL_ARMOR for the next update.
