### ISSUE TITLE
Enchants upgrades no longer works

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2314]
## Details

**Describe the bug**

If you try to put a level 3 book on an item that already has the same enchant of the same level, it won't go up a level but in chat it tells you that it got upgraded 
**To Reproduce** 

Grab a telepathy 3 book and a pick with teleapthy 3 book, apply it and bam you see the message saying it's level 4 but it's still level 3 
**Screenshots / Video**

https://gyazo.com/f65e13de9d09948f1d59d44a54dc3d3e

## Server Information
- "/ae plinfo" link: 
- Server log: no errors

**Comment by hkkongou** [comment]
confirmed this bug with AE 8.5.7 and AE 8.6.6
8.5.7 have no problem with upgrade but 8.6.6 upgrade does not work, only work with alchem

https://youtu.be/89PMi_JvCkw

**Comment by LuluxClient** [comment]
> confirmed this bug with AE 8.5.7 and AE 8.6.6
> 8.5.7 have no problem with upgrade but 8.6.6 upgrade does not work, only work with alchem
> 
> https://youtu.be/89PMi_JvCkw

Thanks for the video <3 !

**Comment by Insprill** [comment]
Fixed in the next update
