### ISSUE TITLE
Blocktracker and Telepathy enchant

### ISSUE THREAD

**Issue by PiruSax** [GC-spigot/AdvancedEnchantments#2315]
## Details

**Describe the bug**
If the item has the premade enchant "Telepathy" and then I apply the "Blocktracker" the enchant function but the blocktracker doesn't count the blocks, it stays in "Blocks Broken: 0". And if I try to enchant after the blocktracker is on, then it removes the blocktrackers lore and I can't even put a new one on the item.

**To Reproduce** 
Enchant an item with Telepathy and then put the Blocktracker on the item. Or Put the Blocktracker and then put any other enchant

**Screenshots / Video**

## Server Information
- https://paste.md-5.net/wayuxubala 
- https://mcpaste.io/e2424f9f15b4a98d

**Comment by Insprill** [comment]
Does enabling experimental-block-breaking fix it?

**Comment by PiruSax** [comment]
Yes it does solve the issue, thank u very much for ur help. U have a great plugin

**Comment by PiruSax** [comment]
Im sorry for reopening this, Now I have this issue, not sure if its because of the experimental-block-breaking or other thing.
![2021-08-24_03 48 47](https://user-images.githubusercontent.com/54513971/130587419-72fb51ed-a104-4183-b68e-a059b2c75168.png)

**Comment by PiruSax** [comment]
This only happens with the telepathy enchant and the blocktracker. Also, I have found that when I have "Unbreakable" and "Soul Miner" the souls doesn't add to the soul tracker

**Comment by Insprill** [comment]
Fixed in the next update
