### ISSUE TITLE
Issue with /hat

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2316]
## Details

**Describe the bug**
Having any tools/weapons that give effects - when doing /hat or putting them on your head slot. They keep their effects while not using it.

**To Reproduce** 
Example:
Using Trench Pickaxe on your head item slot.
Then using a regular pickaxe- Gives the same 3x3 mining area without damaging the Trench pickaxe.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/eletariwov
- Server log: https://mcpaste.io/

**Comment by Insprill** [comment]
Added a config option to toggle this behavior in the next update
