### ISSUE TITLE
Lore still not getting updated if I upgrade the custom enchant 

### ISSUE THREAD

**Issue by n0tailz-debug** [GC-spigot/AdvancedEnchantments#2318]
## Details

**Describe the bug**
Lore still not getting updated if I upgrade the custom enchant ( this is working on 8.6.2 )

**To Reproduce** 
Example, get bleed 3 ( or any custom enchant ) on any weapon then upgrade it using a book bleed 3 too. 

**Screenshots / Video**
![Capture](https://user-images.githubusercontent.com/78484864/131208062-ac423da4-cb23-43de-9a76-c1304d30581b.PNG)

## Server Information
- https://paste.md-5.net/avasiqanof
- Server log: https://mcpaste.io/40298a4ad377d194

**Comment by Insprill** [comment]
Duplicate of #2314
