### ISSUE TITLE
Double Enchantment Level Showcase

### ISSUE THREAD

**Issue by Arcanetrix** [GC-spigot/AdvancedEnchantments#2319]
**Describe the bug**
Double level showcased in the book examining message. Instead of Battlecry I it would show Battlecry I I

**To Reproduce** 
Not sure what exactly is causing it or how it's happening the config is normal and has only 1 %level%

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/88311176/131210496-d97d892f-4d07-4558-a512-eea9bae0d306.png)

https://paste.md-5.net/ahejananos
https://mcpaste.io/98a59c9eda167811

**Comment by Insprill** [comment]
Fixed in the next update
