### ISSUE TITLE
[REQUEST] New 'type' DEFENSE_ALL

### ISSUE THREAD

**Issue by Blazingshadow17** [GC-spigot/AdvancedEnchantments#232]
For enchants like this:

shroud:
  display: '&7Sightless'
  description: 'Chance to give ANY attacker blindness.'
  applies-to: 'Armor'
  type: 'DEFENSE'
  group: 'SIMPLE'
  applies:
  - ALL_ARMOR
  levels:
    1:
      chance: 25
      cooldown: 1
      effects:
      - 'POTION:BLINDNESS:0:30 %attacker%'
    2:
      chance: 30
      cooldown: 2
      effects:
      - 'POTION:BLINDNESS:0:45 %attacker%'
    3:
      chance: 100
      cooldown: 3
      effects:
      - 'POTION:BLINDNESS:0:60 %attacker%'

I want to have it affect both ranged and melee players, which I'm not sure if that's possible right now, so would there be a way you could add multiple types in the type section or another defense type for DEFENSE_ALL or something? Thanks!

**Comment by ZeddyOG** [comment]
You can you multiple types in a single enchantment, simply do 'TYPE;TYPE2'.  Example: 'DEFENSE;DEFENSE_MOB'
