### ISSUE TITLE
Telepathy slabs anti-dupe

### ISSUE THREAD

**Issue by iBuseWinner** [GC-spigot/AdvancedEnchantments#2320]
## Details

**Describe the bug**
When we breaking double slabs with telepathy enchantment we will get only 1 slab.

**To Reproduce** 
Enchant pickaxe with telepathy, place double slabs and break this block. You will get 1 slab.

**Screenshots / Video**
https://youtu.be/aBrftXgrS-A

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/elatekotew

**Comment by Insprill** [comment]
Update AE. Fixed in 8.6.5.
