### ISSUE TITLE
MORE_DROPS blocks other MINING type enchants on blocks placed by players

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2322]
## Details

**Describe the bug**

If you add "MORE_DROPS" with "SMELT", the ore will no longer melt and won't be duplicated (more_drops)
**To Reproduce** 

Add this to autosmelt: https://pastebin.com/aqTABTBa and mine a gold ore and the item won't be melted and duplicated. 
**Screenshots / Video**

https://gyazo.com/69d5c35402bcacd789d0ddeb45c344c6 

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/onifolugap.css
- Server log:  no errors

**Comment by Insprill** [comment]
The reason MORE_DROPS isn't working is because you placed down the blocks. It only works on blocks not placed by players so people can't infinitely dupe them. It does look like it's stopping the other effects from activating though, which is a bug.

**Comment by LuluxClient** [comment]
> The reason MORE_DROPS isn't working is because you placed down the blocks. It only works on blocks not placed by players so people can't infinitely dupe them. It does look like it's stopping the other effects from activating though, which is a bug.

I didn’t know that, that’s pretty good 👍

**Comment by Insprill** [comment]
Fixed in the next update
