### ISSUE TITLE
Trench duplicating blocktrack lore - again

### ISSUE THREAD

**Issue by arceusxs2** [GC-spigot/AdvancedEnchantments#2324]
## Details
Same as https://github.com/GC-spigot/AdvancedEnchantments/issues/2064
**Describe the bug**

Hello, theres bug with trench and blocktrack that i reported 2 months ago and was supposed to be fixed, but its not,
Thats the problem https://github.com/GC-spigot/AdvancedEnchantments/issues/2064
**To Reproduce** 

**Screenshots / Video**

https://prnt.sc/1qr7ukp

## Server Information
- "/ae plinfo" link: 
- Plugins version 8.6.7, Break Checks trues
- Server log:

**Comment by Insprill** [comment]
Update AE.

**Comment by arceusxs2** [comment]
Hello, i did that but it still didnt fix it.

**Comment by Insprill** [comment]
Does experimental-block-breaking make a difference?

**Comment by arceusxs2** [comment]
Turned it on but still having the same problem

**Comment by arceusxs2** [comment]
https://paste.md-5.net/upidehowig

**Comment by Insprill** [comment]
On 8.6.9 i can't reproduce this, can you update to that and see if it's still an issue? @arceusxs2

**Comment by arceusxs2** [comment]
Tried, but sadly it didnt help.

**Comment by Insprill** [comment]
Try with a fresh pickaxe. Maybe something is broken with the NBT data of that one.

**Comment by arceusxs2** [comment]
Tried, but didnt help. Also i tried it on completly fresh server with unmodified configs of AE at all and so far what i can see, it happenes only when i have trench 9 + reforged 9 and unbreakable 1 on the pickaxe.

**Comment by Insprill** [comment]
Fixed in the next update
