### ISSUE TITLE
REPEATING enchantments stop functioning on World Change/Joining

### ISSUE THREAD

**Issue by Complex1tive** [GC-spigot/AdvancedEnchantments#2325]
## Details

**Describe the bug**
Enchantments with the REPEATING type will stop functioning occasionally upon teleporting across dimensions. Additionally, REPEATING enchantments occasionally fail to function upon joining. Note that this does not occur on every occasion of dimension change/joining; you would have to do it multiple times to reproduce.

**To Reproduce** 
To reproduce the bug occurring when changing dimensions:
Equip an item with an enchantment type of REPEATING with a message under effects. Change across multiple dimensions using essentials' /warp commands. Repeat several times to see it randomly stop functioning.

To reproduce the bug occurring upon joining:
Equip an item with an enchantment type of REPEATING with a message under effects. Rejoin the server multiple times to see it randomly stop functioning.
Enchantment used in video: [https://pastebin.com/FkqPSWsL](https://pastebin.com/FkqPSWsL)

**Screenshots / Video**

When changing dimensions: [https://www.youtube.com/watch?v=OyRwPS-mKdc](https://www.youtube.com/watch?v=OyRwPS-mKdc)
When joining: [https://www.youtube.com/watch?v=kiElY1wFrcQ](https://www.youtube.com/watch?v=kiElY1wFrcQ)

## Server Information
- "/ae plinfo" link: [https://paste.md-5.net/ihayujocol](https://paste.md-5.net/ihayujocol)
- Server log: [https://pastebin.com/379WMXrg](https://pastebin.com/379WMXrg)

**Comment by Insprill** [comment]
Fixed in the next update
