### ISSUE TITLE
EFFECT_STATIC Armor Command Bug

### ISSUE THREAD

**Issue by tyepavitt** [GC-spigot/AdvancedEnchantments#2326]
**Describe the bug**
EFFECT_STATIC armor console/player command won't run when equipping and unequipping armor by dragging it in the slot but shift clicking it in or equipping it in hand will work.

**To Reproduce**
Create an enchantment with the type set to EFFECT_STATIC, make it apply to all armor and make it run a toggleable console/player command for example: 
'fly %player_name%'. 

Apply the enchant on a piece of armor and try to shift click it in and out of the armor slot. The command should run.

Then try to drag the armor in and out of the slot and the command doesn't run.

Then try to equip the armor by right clicking with the armor in your hand and the command will run.

**Screenshots / Video**

https://user-images.githubusercontent.com/35017430/131833534-693e993c-2196-4bfd-adb3-d90df7fa8952.mp4

I'm using Minecraft paper 1.17.1 and Using the latest version of AdvancedEnchantments (8.6.9)

**Comment by Insprill** [comment]
Have a feeling another plugin is causing this. Works fine for me with just AE, Essentials, LuckPerms, PAPI, ProtocolLib, Spark, and Vault. Please remove all other plugins and see if it goes away then figure out which one is causing it. I *think* there was an issue similar to this and he said CMI/CMILib was the issue so if you have that it'd be a good starting point.
