### ISSUE TITLE
Server reboot leaves obsidian from lava/water walker

### ISSUE THREAD

**Issue by Thefluffypvper1** [GC-spigot/AdvancedEnchantments#2327]
## Details

**Describe the bug**
When rebooting the server the obsidian trail from lava/water walker enchant leaves obsidian on the water when makes the water disappear and doesn't set it back to normal.

**To Reproduce** 
Go on water with water walker and have Ulimaterestart showing a 5 second count down with /ar now 5 and start walking around on water till the server stops and kicks you, when you relog in the obsidian will still be there.

**Screenshots / Video**
https://gyazo.com/a513fd30a6d446bdb8d0b830e9b07307

## Server Information
- "https://paste.md-5.net/leheroweqe"
- Log https://paste.helpch.at/pevevugumo.md

**Comment by Insprill** [comment]
Fixed in the next update
