### ISSUE TITLE
mcMMO incompatible

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2328]
mining level was not increase when using Trench enchant.
There was a problem updating to the latest version.

**Comment by Insprill** [comment]
Enable experimental-block-breaking in the config

**Comment by NCSV** [comment]
> Enable experimental-block-breaking in the config

i Enable experimental-block-breaking in the config, but still same issue.
also this enchant not work though.

검성:
  display: '%group-color%검성'
  description: '검 데미지가 대폭 증가합니다.'
  applies-to: '검'
  type: 'ATTACK;ATTACK_MOB'
  group: '레전더리'
  applies:
    - ALL_SWORD
  levels:
    1:
      effects:
        - 'INCREASE_DAMAGE:<random number>50-100</random number> %victim%'
    2:
      effects:
        - 'INCREASE_DAMAGE:<random number>100-150</random number> %victim%'
    3:
      effects:
        - 'INCREASE_DAMAGE:<random number>150-200</random number> %victim%'

-> also i toggled on use-experimental-damage: true

**Comment by NCSV** [comment]
i Enable experimental-block-breaking in the config, but still same issue.
also this enchant not work though.

==============================================

2021-09-06_13 44 29

player can putout tinkerer gui's glass pane.

**Comment by NCSV** [comment]
> Enable experimental-block-breaking in the config

i Enable experimental-block-breaking in the config, but still same issue.
also this enchant not work though.

==============================================

![2021-09-05_13 54 28](https://user-images.githubusercontent.com/25452835/132232368-954ad2fc-240f-486b-b7d9-e1f973cacc30.png)

player can putout tinkerer gui's glass pane.
