### ISSUE TITLE
mcMMO incompatible 2

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2329]
https://github.com/GC-spigot/AdvancedEnchantments/issues/2328<< closed issue.
name: mcMMO
version: 2.1.201

i Enable experimental-block-breaking in the config, but still same issue.
also this enchant not work though.

==============================================

![2021-09-06_13 44 29](https://user-images.githubusercontent.com/25452835/132161907-e8bb3050-0ef6-4b69-80a6-60107ebb31eb.png)

player can putout tinkerer gui's glass pane.

**Comment by Insprill** [comment]
Don't create new issues. Comment on the original like you did and i will reopen it. Update AE.

**Comment by NCSV** [comment]
> Don't create new issues. Comment on the original like you did and i will reopen it. Update AE.

replied. i'm sorry.

**Comment by Insprill** [comment]
Did updating fix it?

**Comment by NCSV** [comment]
> Did updating fix it?

no. this is lastest version AE (8.6.9)

**Comment by Insprill** [comment]
Do you mean it doesn't increase for the source block or all blocks around it? Also no need to say you replied in other issues as i get notifications

**Comment by NCSV** [comment]
> Do you mean it doesn't increase for the source block or all blocks around it? Also no need to say you replied in other issues as i get notifications

Both are not worked.

**Comment by Insprill** [comment]
Do `/ae plinfo` and send the link

**Comment by NCSV** [comment]
![2021-09-07_10 50 24](https://user-images.githubusercontent.com/25452835/132272100-1592786a-15d4-4c9b-8d5d-4d6e80898e27.png)

**Comment by Insprill** [comment]
Can you try again? If it doesn't work please contact your host. The domain it needs to access is `paste.md-5.net`

**Comment by Insprill** [comment]
@NCSV

**Comment by NCSV** [comment]
> @NCSV

host doesen't want that.
close the ticket please.
