### ISSUE TITLE
[REQUEST] Custom "trench" area

### ISSUE THREAD

**Issue by Coverosi** [GC-spigot/AdvancedEnchantments#233]
I feel like it would be a great feature if we could customize the area that trench breaks, beyond the current system of either 3x3, 5x5, 7x7. If we could control the radius _and_ the depth of the enchantment, that would be great

**Comment by Blazingshadow17** [comment]
also, if you added on the option to 'trench' to drop all blocks broken by it as well.

**Comment by GC-spigot** [comment]
> Also, if you added on the option for 'trench' to drop all blocks broken by it as well, it would be very useful for a drill enchant.
> 
> Thanks!

It does do this, if there's another enchant that stops from doing it is because it adds it right to the inventory.

**Comment by GC-spigot** [comment]
Added!
