### ISSUE TITLE
Enchants dont activate after login in BSkyBlock world

### ISSUE THREAD

**Issue by Kesims** [GC-spigot/AdvancedEnchantments#2330]
## Details

**Describe the bug**
When player logs in in BSkyBlock world (I am not sure why that is, mby it is because the world uses custom generation? Or mby because of island protection? I couldnt figure it out), enchants dont work for him. When he goes to spawn world and then back on his islands, than they work as they should.

I recently updated server to 1.17, but it was also present on 1.16

**To Reproduce** 
Start server on 1.17, using BentoBox BSkyBlock and enchants. Login in skyblock world with your enchanted armor on (for example fly boots).

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/ruquhiyuci
- Server log: https://mcpaste.io/eb7fb0dd036e23b2 -- I didnt notice any errors about this in particular.

**Comment by Insprill** [comment]
What type of enchants stop working? Is it just EFFECT_STATIC?

**Comment by Kesims** [comment]
It seems like it applies on all types of enchants, not only STATIC ones. Its like they werent even there.

**Comment by Insprill** [comment]
Can you check if the world is blacklisted in the config, and if it isn't take a screenshot of the item's NBT data when the enchants aren't working

**Comment by Kesims** [comment]
Sorry for late response. NBT seems to be same. Also somehow it now doeasnt activate also in other worlds like spawn. So probbably it shouldnt be a problem of BSkyBlock. 

BUT: I found another bug while testing this.. If you unequip armor with right click, it doesnt disable enchants.
https://youtu.be/0JDItOWASAU -- its shown here. Boots have fly efect enchant and invisibility efect. It didnt disable when i used right click to move boots to my inventory. And it also doesnt enable enchants when right clicked.

**Comment by Insprill** [comment]
Can you try to single out what plugin(s) cause this issue? There shouldn't be anything to globally stop enchants from working in certain worlds or just at all unless you've disabled enchants in those worlds in the config.yml
