### ISSUE TITLE
Armor Duplication/Stuck Bug

### ISSUE THREAD

**Issue by XILegendIX** [GC-spigot/AdvancedEnchantments#2332]
When applying books directly to worn armor, the armor piece becomes unremovable by all means and will duplicate itself if removal is attempted. Tried falling into void, burning, using commands, reloading and restarting server, reloading the enchant files, nothing worked to get it off. 

To replicate, apply a book to a piece of worn armor in MC 1.16 using the most recent Advanced Enchantments version.

**Comment by Insprill** [comment]
Please do `/ae plinfo` and send the link
