### ISSUE TITLE
Effect TNT not reduced by Blast Protection or DECREASE_DAMAGE

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [GC-spigot/AdvancedEnchantments#2335]
## Details

**Describe the bug**
The effect "TNT" cannot be reduced by vanilla Blast Protection or AE's DECREASE_DAMAGE effect (when activated by EXPLOSION).

**To Reproduce** 
1. Create an armor enchantment with a damaging TNT effect, activated by FALL_DAMAGE.
2. Create an armor enchantment that decreases EXPLOSION type damage by 75%.
3. Take fall damage from the same height
    a) First without anything.
    b) Then with the TNT effect.
    c) Finally with the EXPLOSION damage reduction effect.
4. Damage will be the same in all three 

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/sotureroni
- Server log: No messages from or related to AE.

**Comment by Insprill** [comment]
Fixed in the next update
