### ISSUE TITLE
Effect ADD_DURABILITY_CURRENT_ITEM does not work with TRENCH

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [GC-spigot/AdvancedEnchantments#2338]
## Details
The ADD_DURABILITY_CURRENT_ITEM does not roll the chance per each block broken by TRENCH.
However, vanilla Unbreaking does seem to work just fine with TRENCH.

**Describe the bug**
ADD_DURABILITY_CURRENT_ITEM does not check to reduce durability damage on tools.

**To Reproduce** 
1. Enchant a tool with the ADD_DURABILITY_CURRENT_ITEM effect
2. Enchant the same tool with the TRENCH effect
3. Mine blocks

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/kefiqopivi
- Server log: No messages from or related to AE.

**Comment by Insprill** [comment]
Fixed in the next update
