### ISSUE TITLE
TRENCH Light Block Bug

### ISSUE THREAD

**Issue by MasonX3** [GC-spigot/AdvancedEnchantments#2340]
## Details

**Describe the bug**
Even in survival, players are able to break light blocks with the Trench Enchantment despite the blocks not being visible.

**To Reproduce** 
Place light blocks in creative mode, then any block that can be mined with Tunnel in the center or around them. Break the block that you can near the light blocks and the lights will drop. 

**Screenshots / Video**
https://gyazo.com/f9d291595c167187186d9462c09f5187

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/falohexugu
- Server log: No messages from or related to AE.

**Comment by Insprill** [comment]
Fixed in the next update
