### ISSUE TITLE
'or' on enchantments.yml counted as letters

### ISSUE THREAD

**Issue by Regerta** [GC-spigot/AdvancedEnchantments#2341]
## Details

**Describe the bug**
'or' operator counted as letters and causing an error

**To Reproduce** 
- Update to 8.6.10
- Try to use sword with an enchantment that has 'or' operator on condition, like nightwalker / nightowl
- Hit a mobs and you will see errors on chat (Screenshot attached)

**Screenshots / Video**
- Screenshot: https://ibb.co/gRYTFR2

## Server Information
- Running at my test server with Purpur 1.17.1

**Comment by Insprill** [comment]
Fixed in the next update
