### ISSUE TITLE
Unknown connection error when come across specific item

### ISSUE THREAD

**Issue by Soldier233** [GC-spigot/AdvancedEnchantments#2343]
## Details

**Describe the bug**
Server using ViaBackwards,player(1.12.2 client) open the loot chest generated in the world, and some specific item with enchantment[ae_glow] will cause the connection aborted.
Log:
```
[11:34:05 INFO]: NXGY lost connection: Internal Exception: java.lang.IllegalArgumentException: Missing enchantment Enchantment[minecraft:ae_glow, ] legacy id
```

Via* Config
[Downloads.zip](https://github.com/GC-spigot/AdvancedSpawners/files/7147199/Downloads.zip)

**To Reproduce** 
Unknown.
But it may have something to do with ViaBackwards.

**Screenshots / Video**
None

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/tucodureka
- Server log: https://mcpaste.io/e9c4af6fcc545019

**Comment by Insprill** [comment]
Not our issue. Some plugin is coming across one of our registered enchantments and freaking out. It could be ViaBackwards, but lots of people use ViaBackwards so if it was an issue with that i think a lot more people would be reporting it.
