### ISSUE TITLE
When claiming a gkit with the inventory almost full, several items are lost

### ISSUE THREAD

**Issue by rmalca** [GC-spigot/AdvancedEnchantments#2344]
## Details

**Describe the bug**
When claiming a gkit with the inventory almost full, several items are lost. 

**To Reproduce**
Use "/ae givegkit player gkit" command with full inventory.

**Screenshots / Video**

https://user-images.githubusercontent.com/3759745/132957445-e8825744-1eb1-4466-abe5-86f5afdd9947.mp4

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/udofuxojug

**Comment by Insprill** [comment]
Can you try on a server with only AE? Testing this myself it drops all the extra items on the ground as it should.

**Comment by rmalca** [comment]
> Can you try on a server with only AE? Testing this myself it drops all the extra items on the ground as it should.

Done, same problem. An important detail is that it only happens with the command, if I do it with the /gkits interface it works fine (the items fall to the ground).

**Comment by Insprill** [comment]
Ah alright, I was getting it from the GUI. Will test it with the command tomorrow.

**Comment by Insprill** [comment]
Fixed in the next update
