### ISSUE TITLE
AE view permission problem

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2345]
## Details

**Describe the bug**
![image](https://user-images.githubusercontent.com/61608872/132990727-63805a1b-e0e0-4dd6-80fd-7e497d72bff0.png)

According to the wiki, The permission for "/ae view (enchant)" command is "Same as enchantment-info permission". But i cannot use ``/ae view`` even with ``/ae info`` permission ``ae.info``

**To Reproduce** 
1. use luckperms, set ae.info permission to default group
2. use command ``/ae view XXX`` enchantment

**Screenshots / Video**

https://youtu.be/qie1k1tLNMQ

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/unafaqozer
- Server log: https://paste.gg/p/anonymous/89a09d1dcee64b1791ce737e7894f0fe
- Luckperms editor permission list: https://luckperms.net/editor/XbeYBM9jbX

**Comment by Insprill** [comment]
[This](https://github.com/GC-spigot/AdvancedEnchantments/blob/master/Default%20Files/customcommands.yml#L10) is the permission it uses. Is that not working?

**Comment by hkkongou** [comment]
> [This](https://github.com/GC-spigot/AdvancedEnchantments/blob/master/Default%20Files/customcommands.yml#L10) is the permission it uses. Is that not working?

i have ``permission: ""`` set too, i can open ``/enchant`` without having any permission, but ``/ae view`` is not working

**Comment by Insprill** [comment]
Can you try setting the permission to something? `ae.test` would work and give it to yourself and see if it works
