### ISSUE TITLE
Duplication Telepathy + Smelting

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2348]
### Describe the bug

If you use a pickaxe with Telepathy + Smelting and have experimental-block-breaking set to true, you can dupe shulkers.

### How to reproduce

Enable experimental block breaking
Enchant a pickaxe with Telepathy & Smelting
Mine a shulker (with items) with the pickaxe

### "/ae plinfo" link

https://paste.md-5.net/wajogeyebu

**Comment by Insprill** [comment]
Fixed in the next update
