### ISSUE TITLE
Aquatic enchantment (water breathing) broken

### ISSUE THREAD

**Issue by Madcow5** [GC-spigot/AdvancedEnchantments#2350]
### Describe the bug

If we have enchantment 'Aquatic' on helmet, it won't work on latest version of AE

### How to reproduce

After update to latest AE, enchantment 'Aquatic' on helmet, it won't work.
I think 'Water_breathing' mechanic is broken.

### "/ae plinfo" link

https://paste.md-5.net/qojecabojo

### Server Log

https://mcpaste.io/cc1c4cc2c0216f44

**Comment by Insprill** [comment]
I can't reproduce this on Paper-263 1.17.1. Make sure the enchantment looks like [this](https://github.com/GC-spigot/AdvancedEnchantments/blob/master/Default%20Files/enchantments.yml#L322) and if it doesn't, replace it with that.

**Comment by Madcow5** [comment]
> I can't reproduce this on Paper-263 1.17.1. Make sure the enchantment looks like [this](https://github.com/GC-spigot/AdvancedEnchantments/blob/master/Default%20Files/enchantments.yml#L322) and if it doesn't, replace it with that.

Its exactly same with my config. but not works.

**Comment by Insprill** [comment]
Can you do `/ae zip` and send the file it creates? You can create a ticket on Discord if you don't want to send it here.
