### ISSUE TITLE
Telepathy Enchantment doesn't give MCMMO Exp

### ISSUE THREAD

**Issue by ShadoW4719** [GC-spigot/AdvancedEnchantments#2351]
### Describe the bug

When a pickaxe is equipped with the Telepathy Enchant (places blocks directly in your inventory), it doesn't give MCMMO Experience.
![image](https://user-images.githubusercontent.com/82054058/133705652-e046753b-6bce-4d55-941d-8e463650f389.png)

### How to reproduce

Create an enchantment that uses the TP Block mechanic and mine block/ores.
It shouldn't give mining experience.

### Screenshots / Videos

N/A

### "/ae plinfo" link

N/A

### Server Log

N/A

**Comment by Insprill** [comment]
Enable experimental-block-breaking in the config
