### ISSUE TITLE
ProjectileLaunchEvent generating an error while shotting with a bow in 1.8.8

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#2352]
### Describe the bug

Shotting an arrow with a bow is generating an error in the console.

### How to reproduce

Shot an arrow with a bow or throw a potion / fishing rod

### Screenshots / Videos

/

### "/ae plinfo" link

https://paste.md-5.net/lazojufite

### Server Log

https://paste.soleria.eu/bowineyodi.properties

**Comment by Insprill** [comment]
Fixed for the next update
