### ISSUE TITLE
8.6.13 NoClassDefFoundError BanAction inventoryclickevent

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2354]
### Describe the bug

Console is showing this error message

### How to reproduce

idk how

one thing can sure, 8.6.11 does not have this error or problem

### Screenshots / Videos

![unknown](https://user-images.githubusercontent.com/61608872/133868505-c5d131b7-47d0-48e7-9ff1-5bdd3f3f46e0.png)

### "/ae plinfo" link

https://paste.md-5.net/jubabiqoyi

### Server Log

https://paste.gg/p/anonymous/1d929bed429645c79a315c65faa2e0db

**Comment by SirCraftypants** [comment]
Also have this issue 

https://paste.helpch.at/cocoyijuxo.sql

Paper 1.17.1
MC 1.17.1

Advanced Enchantments 8.6.13

**Comment by Insprill** [comment]
Fixed for the next update
