### ISSUE TITLE
8.6.13 Cannot invoke "java.util.List.add(Object)" because "effects" is null

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2355]
### Describe the bug

Console is showing this error message

### How to reproduce

idk how

one thing can sure, 8.6.11 does not have this error or problem

### Screenshots / Videos

![unknown](https://user-images.githubusercontent.com/61608872/133868579-6f5edc19-8466-41c3-8fe5-3e31c1a1165c.png)

### "/ae plinfo" link

https://paste.md-5.net/jubabiqoyi

### Server Log

https://paste.gg/p/anonymous/1d929bed429645c79a315c65faa2e0db

**Comment by Insprill** [comment]
Fixed in the next update
