### ISSUE TITLE
8.6.13 Could not pass ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2356]
### Describe the bug

console spamming error

### How to reproduce

seems like some problem with mining

Does not happen in 8.6.11

### Screenshots / Videos

![Uploading unknown.png…]()

### "/ae plinfo" link

https://paste.md-5.net/jubabiqoyi

### Server Log

https://paste.gg/p/anonymous/7219ae1110ea47a18c4a89ec15ae126b

**Comment by Insprill** [comment]
Fixed in the next update
