### ISSUE TITLE
GKits

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#2358]
### Describe the bug

When attempting to obtain some GKits, they do not work, other GKits, however, work perfectly fine, an example of a GKit that doesn't work is the Destroyer GKit, Insprill has said the following: "you have enchants with the %min-max% level format that's broken. min needs to be less then max"

### How to reproduce

Simply attempt to spawn a specific GKit, it will say in chat that you got it, but in reality you're not removed from the GUI nor do you get anything.

### Screenshots / Videos

https://youtu.be/Zo2ZLo69VJQ

### "/ae plinfo" link

https://paste.md-5.net/ciwevafope

### Server Log

https://mcpaste.io/0c43d0c46fb36614

**Comment by Insprill** [comment]
Fixed in the next update. You *won't* need to update the config.
