### ISSUE TITLE
NPE on SHIFT Enchantments

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2359]
### Describe the bug

When using a SHIFT enchantment, the enchantment doesn't work and an NPE is thrown in console when the player shifts.

Enchantment: https://pastebin.com/AE9vre7p

Console error:
> 19.09 13:10:50 [Server] ERROR Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
> 19.09 13:10:50 [Server] INFO java.lang.NullPointerException: null

### How to reproduce

Equip a SHIFT enchantment.
Press shift.

### "/ae plinfo" link

https://paste.md-5.net/xuhipedijo

**Comment by Insprill** [comment]
Unable to reproduce with the enchant provided. Please send the full error and/or your latest.log. The error snippet you sent doesn't tell us anything.

**Comment by Dakotaa** [comment]
That is the full error - those two lines are all that shows when trying to activate the enchantment.

> [15:40:28] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
java.lang.NullPointerException: null
[15:40:28] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
java.lang.NullPointerException: null
[15:40:28] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
java.lang.NullPointerException: null
[15:40:28] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
java.lang.NullPointerException: null
[15:40:29] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
java.lang.NullPointerException: null
[15:40:29] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
java.lang.NullPointerException: null
[15:40:29] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
java.lang.NullPointerException: null
[15:40:30] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
java.lang.NullPointerException: null
[15:40:31] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
java.lang.NullPointerException: null
[15:40:32] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
java.lang.NullPointerException: null

**Comment by Dakotaa** [comment]
After updating to the latest version (8.16.4), I now get a more detailed error:

> 25.09 15:44:23 [Server] ERROR Could not pass event PlayerToggleSneakEvent to AdvancedEnchantments v8.6.13
25.09 15:44:23 [Server] INFO java.lang.NullPointerException: null
25.09 15:44:23 [Server] INFO at net.advancedplugins.ae.enchanthandler.variables.Variables.replaceVariables(Variables.java:55) ~[?:?]
25.09 15:44:23 [Server] INFO at net.advancedplugins.ae.enchanthandler.effectsreader.EnchantsReader.get(EnchantsReader.java:243) ~[?:?]
25.09 15:44:23 [Server] INFO at net.advancedplugins.ae.enchanthandler.enchanttypes.SHIFT.onCrouch(SHIFT.java:32) ~[?:?]
25.09 15:44:23 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1771.execute(Unknown Source) ~[?:?]
25.09 15:44:23 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2374) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInEntityAction.a(SourceFile:43) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInEntityAction.a(SourceFile:9) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1151]
25.09 15:44:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by Dakotaa** [comment]
Fixed by changing "%player name%" (previously worked) to "%player_name%".
