### ISSUE TITLE
/ae reload + enchantment table bug

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2360]
### Describe the bug

CE wont work on enchantment table once you do /ae reload

### How to reproduce

Start the server, try some enchanting on an enchantment table, it will work, but once you do /ae reload, it will never proc again, Ench table wont give you CE anymore no matter how many times you try.

### "/ae plinfo" link

https://paste.md-5.net/ogicivucek

### Server Log

https://mcpaste.io/8cd75c09efed0fc7

**Comment by Insprill** [comment]
Fixed in the next beta update
