### ISSUE TITLE
Grindstone mechanics broken infinite exp gain

### ISSUE THREAD

**Issue by Shurelia** [GC-spigot/AdvancedEnchantments#2362]
### Describe the bug

Unenchanting items with grindstone using keyboard hotkey is broken

### How to reproduce

Bring 2 items, ones putted on first hotbar slot
And put the other with ench on the grindstone
Hover to grinstone result and then press 1 key (first hotbar key to get the item)
Since you already got item on the first hotbar, the disenchant event will got canceled and you'll got the exp result.

### Screenshots / Videos

https://streamable.com/sjj3cg

another example by my player on a live server
https://cdn.discordapp.com/attachments/889480497447723018/889480963476820008/2021-09-20_18-51-06_Trim.mp4

### "/ae plinfo" link

https://paste.md-5.net/ayeyamuris

**Comment by Insprill** [comment]
Fixed in the next update
