### ISSUE TITLE
Anvil + Enchantment Book

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2364]
### Describe the bug

You can put CE books into anvil with items, and then even with low success rate, it just applies no matter what.
I thought we werent suppsoed to be able to put CE books in anvil? only drag and enchant? and anyway im using 8.6.9 as dev said its the most stable version yet, idk if this bug was already reported and fixed in later versions.

### How to reproduce

Get item and CE book with low success rate, put them both in anvil, then boom, free CE.

### Screenshots / Videos

https://www.youtube.com/watch?v=G2SdhMCFvhw&feature=youtu.be

### "/ae plinfo" link

https://paste.md-5.net/oleriruhod

### Server Log

https://mcpaste.io/019ad76fa568cc50

**Comment by Insprill** [comment]
Duplicate if #2174
