### ISSUE TITLE
1.17 Copper, Iron, and Gold Ore Drops Unaffected By Fortune When Pickaxe Also Has Telepathy (use-experimental-block-breaking: true)

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2365]
### Describe the bug

When `use-experimental-block-breaking` is set to true, Fortune doesn't work on Iron, Gold, and Copper Ore when the pickaxe has Telepathy. You will only get the standard amounts.

### How to reproduce

1.)  Set `use-experimental-block-breaking` to true
2.) Get a pickaxe with Fortune
3.) Hold the pickaxe and do /ae enchant Telepathy 4
4.) Use the pickaxe to mine Iron, Gold, and Copper Ore

You will only get 1 Raw Iron, 1 Raw Gold, and 2-3 Raw Copper, when you should be getting more because of Fortune.

### "/ae plinfo" link

https://paste.md-5.net/facozoxuve

**Comment by Insprill** [comment]
Enable [this](https://github.com/GC-spigot/AdvancedEnchantments/blob/master/Default%20Files/config.yml#L720) in your config
