### ISSUE TITLE
%raw damage% not working since it has been implemented on spigot 1.8.9

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#2366]
### Describe the bug

%raw damage% is not working, while debugging, it's printing %raw 1%. 

### How to reproduce

`- 'MESSAGE:%raw damage% %attacker%'`

### "/ae plinfo" link

https://paste.md-5.net/ixuzofejam

**Comment by haeiven** [comment]
Probably related to #2367

**Comment by Insprill** [comment]
Fixed in the next update
