### ISSUE TITLE
Invalid syntax or outcome while trying to calculate something with %damage% since 8.6.10

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#2367]
### Describe the bug

` - 'ADD_HEALTH:<math>0.14 * %damage%</math> %attacker%'`

This effect is generating an error since version 8.6.10 (working well in 8.6.9 and before)

While debugging, i notified %damage% was returning %1% instead of just the number.

while using:
` - 'ADD_HEALTH:<math>0.14 * damage</math> %attacker%'`

it started to work again.

### How to reproduce

` - 'ADD_HEALTH:<math>0.14 * %damage%</math> %attacker%'`

### "/ae plinfo" link

https://paste.md-5.net/medayiqexe

### Server Log

https://paste.soleria.eu/ririsiyeqe.md

**Comment by Insprill** [comment]
Fixed in the next update
