### ISSUE TITLE
VeinMiner does not work with 1.17 ores

### ISSUE THREAD

**Issue by Jupitour** [GC-spigot/AdvancedEnchantments#2368]
### Describe the bug

When using VeinMiner on 1.17.1 ores such as copper or any deepslate variant, it doesn't work

### How to reproduce

Simply use a tool enchanted with VeinMiner on any 1.17 ore

### "/ae plinfo" link

https://paste.md-5.net/afadecupip

**Comment by Insprill** [comment]
Add them to VeinMiner's whitelist in the config
