### ISSUE TITLE
Multiple event types in armor sets

### ISSUE THREAD

**Issue by AkaUlti** [GC-spigot/AdvancedEnchantments#2370]
### Describe the bug

I cannot use multiple of the same event types in armor sets, an example of what im trying to achieve is having a permanent attack damage booster, but also a unique attack ability, they both require the ATTACK event but it cancels them out and only procs one ATTACK event if that makes sense.

### How to reproduce

use two of the same events like ATTACK

events:
  ATTACK:
    chance: 100
    effects:
      - 'INCREASE_DAMAGE:15'
  ATTACK:
    chance: 2
    cooldown: 900
    effects:
      - 'FREEZE:140 %victim%'
      - 'PARTICLE:SNOW_SHOVEL:300:2 %victim%'
      - 'PARTICLE:SNOWBALL_BREAK:300:2 %victim%'
      - 'MESSAGE:&b&l** SNOWIFY &7(%victim name% [7s]) &b&l** %victim%'
      - 'MESSAGE:&b&l** SNOWIFY &7(%victim name% [7s]) &b&l** %attacker%'

### "/ae plinfo" link

https://paste.md-5.net/zopajukaci

### Server Log

not required

**Comment by Insprill** [comment]
Thats not a bug. Thats a limitation of YAML.
