### ISSUE TITLE
Many bug reports from different versions

### ISSUE THREAD

**Issue by vubaolinh123** [GC-spigot/AdvancedEnchantments#2371]
### Describe the bug

Errors appear on the console when players use Enchants to hit Mobs or other players, specific error details are below and images

### How to reproduce

I don't know how to fix it

### Screenshots / Videos

- Versions 8.6.9 -8.6.13 all have this error: [Server thread/ERROR]: [AdvancedEnchantments] Tried to parse "ADD_HARM" effect with invalid argument. Expected a number, got %0%.
- I tried to upgrade the version to 8.9.10 and started getting this error : https://paste.gg/p/anonymous/0894df0c692244efae6b8be301b83f80
- Starting from version 8.6.13 there are these errors: https://paste.gg/p/anonymous/39ed5874ce70426887966241346cf095
and add this one error like in the video
https://user-images.githubusercontent.com/73287503/134609379-2d244833-315c-45dc-92d2-f3f9666d68ba.mp4
And some error more: 

![9](https://user-images.githubusercontent.com/73287503/134610209-d7d05380-22e2-44c6-93a7-7e3dd14ba95f.png)
![89](https://user-images.githubusercontent.com/73287503/134610224-02679b3d-11d6-49da-8d28-95737788bdc5.png)

 

### "/ae plinfo" link

https://paste.md-5.net/atorokulay

### Server Log

https://paste.gg/p/anonymous/cb4993f129b7425291abb1637a1c322b

**Comment by Insprill** [comment]
Don't put multiple bugs into one issue. All issues have been fixed for the next update.
