### ISSUE TITLE
Anvil Bug (Error in console)

### ISSUE THREAD

**Issue by EdgarGDE** [GC-spigot/AdvancedEnchantments#2375]
### Describe the bug

It only happens that when I use plugins that allow changing amounts and digits (such as AuctionMaster) an error appears in the console, I will copy and paste it for review ... It is only that, apparently there are no changes on the server or problems "physical"
Currently I already have the most updated version "8.6.14" but that error still shows "8.6.13" I don't know why...

### How to reproduce

It only happens that when I use plugins that allow changing amounts and digits (such as AuctionMaster) an error appears in the console, I will copy and paste it for review ... It is only that, apparently there are no changes on the server or problems "physical"

### "/ae plinfo" link

https://paste.md-5.net/fagejuropa

### Server Log

https://mcpaste.io/143a37734b24b961

**Comment by Insprill** [comment]
Fixed in the next update
