### ISSUE TITLE
TRENCH enchant still can break nearby unbreakable block

### ISSUE THREAD

**Issue by ShallowAi** [GC-spigot/AdvancedEnchantments#2377]
### Describe the bug

trench enchant still can get some items like ender_portal_frame, other plugins like kingdomsX nexus(a unbreakable beacon).
and i see the version said its 8.6.13, but im sure i downloaded latest version of ae.

### How to reproduce

enchant pickaxe with TRENCH, then break near block of ENDER_PORTAL_FRAME will get ENDER_PORTAL_FRAME item.

### "/ae plinfo" link

https://paste.md-5.net/fivafuduci

**Comment by Insprill** [comment]
Fixed in the next update
