### ISSUE TITLE
Downgrade version

### ISSUE THREAD

**Issue by vubaolinh123** [GC-spigot/AdvancedEnchantments#2380]
### Describe the bug

why i installed version 8.6.14 but when i run it, it shows as version 8.6.13 and error as in the description

### How to reproduce

Hmm

### Screenshots / Videos

https://paste.gg/p/anonymous/0d7e26980f7f465aaa0e81661a5a27d1
![1](https://user-images.githubusercontent.com/73287503/134772380-9f92f328-0957-4d7f-ac3b-463609961ace.png)

### "/ae plinfo" link

https://paste.md-5.net/etakovihoh

### Server Log

https://paste.gg/p/anonymous/a5976ceb861340868ef513e84dc7452e

**Comment by Insprill** [comment]
Not a bug, GC just forgot to update the version number.

**Comment by vubaolinh123** [comment]
Oh how to fix it :<

**Comment by vubaolinh123** [comment]
what is GC ? :<

**Comment by vubaolinh123** [comment]
> Not a bug, GC just forgot to update the version number.

Can you help me, i want to run the correct version i installed plss

**Comment by Insprill** [comment]
You are running 8.6.14. It just shows as 8.6.13 but I can assure you, you are running 8.6.14.
