### ISSUE TITLE
STRUCK does not activate from effect LIGHTNING or commands

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [GC-spigot/AdvancedEnchantments#2382]
### Describe the bug

Enchantments with type `STRUCK` only seem to activate from natural lightning.
Getting hit by the effect `LIGHTNING` does not trigger effects, neither do commands such as /smite.
   After some testing, /summon seems to work if used accurately on a players location. Earlier testing didn't trigger it at all.

### How to reproduce

1. (Optional) Create an enchantment with effect `LIGHTNING`
2. Create an enchantment with type: `STRUCK` with optional debug message
3. Get hit by `LIGHTNING` effect, or use /smite
4. No message.

The attached `/ae plinfo` link is using AE 8.6.14.
Version is not updated on the Spigot release. Verified it.

### "/ae plinfo" link

https://paste.md-5.net/osurofopoq

**Comment by Insprill** [comment]
This isn't actually possible for us to fix due to the way (Essentials) at least damages the player for the lightning strike.

**Comment by ProfessionalBoatDrifter** [comment]
> 
> 
> This isn't actually possible for us to fix due to the way (Essentials) at least damages the player for the lightning strike.

What about the LIGHTNING effect?

**Comment by ProfessionalBoatDrifter** [comment]
Bump

**Comment by Insprill** [comment]
Will look into it.
