### ISSUE TITLE
Slots display message positioning

### ISSUE THREAD

**Issue by baailey** [GC-spigot/AdvancedEnchantments#2384]
### Describe the bug

The display message for remaining slots is above item lores

### How to reproduce

Enable 'display-in-lore' in the config and do `/aegive [name] diamond_boots 1 name:&bExample protection:6 lore:&aExample_Lore`

### Screenshots / Videos

https://i.imgur.com/XsqcsOa.png

### "/ae plinfo" link

https://paste.md-5.net/onomevucer

**Comment by Insprill** [comment]
Put the enchants after the lore in the command
