### ISSUE TITLE
Essentials /Ci interfering with some custom enchants.

### ISSUE THREAD

**Issue by Thefluffypvper1** [GC-spigot/AdvancedEnchantments#2386]
### Describe the bug

When you do /Ci it gives the player a hitting animation.

### How to reproduce

Have a health boost enchant that gives you extra hearts with the most updated version of  essentials. Do /Ci with the custom enchant on the armour peace and you will see the action happen.

### Screenshots / Videos

https://gyazo.com/f924146f2021dd2a7f0f5a23eebbaf80

### "/ae plinfo" link

https://paste.md-5.net/rudemuzixi

### Server Log

https://paste.helpch.at/ebujibulut.md

**Comment by Insprill** [comment]
That's just what the vanilla Minecraft client does. Nothing we can do about it.

**Comment by Thefluffypvper1** [comment]
could you please add faction territory support were fly custom enchant doesn't work?
Example
- Warzone (People can't fly here with custom enchant boots)
