### ISSUE TITLE
ARROW_HIT error on legacy servers

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#2389]
### Describe the bug

https://paste.soleria.eu/ateravetir.properties

### How to reproduce

throw an arrow on an entity

### "/ae plinfo" link

https://paste.md-5.net/itowodomoh

**Comment by RulerOfEternity** [comment]
Wait it's working with you? ARROW_HIT didn't work with me at all...

**Comment by Insprill** [comment]
Fixed in the next update
