### ISSUE TITLE
[Issue] %attacker% doesn't affect mobs

### ISSUE THREAD

**Issue by Blazingshadow17** [GC-spigot/AdvancedEnchantments#239]
When I use %attacker% on a DEFENSE or a DEFENSE_BOW 'type' it only works against players and not mobs.

For example,
https://pastebin.com/AVLLd6Ga

This enchant only withers other players when hit, and not mobs (I tested with a zombie so having no DEFENSE_BOW shouldn't affect this).

This is very detrimental for servers like mine who are mainly PVE, please fix give me a solution as soon as possible, thanks!

**Comment by GC-spigot** [comment]
Only certain effects are compatible with mobs, but enchant types like 'DEFENSE' or 'DEFENSE_BOW' are only against players.

**Comment by Blazingshadow17** [comment]
Is there any solution to this, if not I would appreciate it if you added a DEFENSE_MOB or something like that...
