### ISSUE TITLE
Item Lore Override

### ISSUE THREAD

**Issue by Thereaperpeper** [GC-spigot/AdvancedEnchantments#2391]
### Describe the bug

When i apply an enchantment to a item with lore, it overwrites the lore completely. I have tried multiple lines of lore to see if the other lines would be unchanged, but it overwrites it completely. This issue is new, since 3-7 updates ago. No errors are displayed.

### How to reproduce

Hold a item with lore and use the /ae enchant (enchantment) command or a book, this will overwrite the lorecompletely

### "/ae plinfo" link

https://paste.md-5.net/lozokezeha

**Comment by Insprill** [comment]
I gave myself a netherite pickaxe with 3 custom lore lines and tried adding & removing enchants in various ways and it never cleared the lore. Can you try updating to AE 8.6.17 (or the latest whenever you read this) and see if it happens with only AE on the server?
