### ISSUE TITLE
[Spigot 1.8.8] TRENCH do not work on shovels

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#2392]
### Describe the bug

TRENCH do not work on shovels. It was working on AE 8.6.8, but since i've updated to 8.6.16, it doesn't

### How to reproduce

Use an enchant using TRENCH effect with a shovel

### "/ae plinfo" link

https://paste.md-5.net/kavulibeye

**Comment by GC-spigot** [comment]
Works on latest
