### ISSUE TITLE
Enchants they do not work - (Attack Type)

### ISSUE THREAD

**Issue by xXDarkCvBxX** [GC-spigot/AdvancedEnchantments#2393]
### Describe the bug

Some enchants with x cooldown seem to be that although the cooldown seconds pass, the enchantment still does not work, in addition to that in some players it does not work from the beginning.

### How to reproduce

Simply using an enchantment in the latest version.
Trial enchantment:

twinge:
  display: '& 7Twinge'
  description: "Make your enemy bleed with melee attacks."
  applies-to: 'Trident, Sword and Ax'
  type: 'ATTACK'
  group: 'ULTIMATE'
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
    - TRIDENT
    - ALL_SWORD
    - ALL_AXE
  levels:
    1:
      chance: 15
      cooldown: 50
      effects:
        - 'POTION: SLOW: 0: 100% victim%'
        - 'MESSAGE: & 4You're bleeding! % victim% '
        - 'MESSAGE: & the enemy is bleeding! % attacker% '
        - 'BLEED: 3: 6: 5% victim%'
    2:
      chance: 30
      cooldown: 40
      effects:
        - 'POTION: SLOW: 0: 200% victim%'
        - 'MESSAGE: & 4You're bleeding! % victim% '
        - 'MESSAGE: & the enemy is bleeding! % attacker% '
        - 'BLEED: 4: 8: 5% victim%'
    3:
      chance: 50
      cooldown: 30
      effects:
        - 'POTION: SLOW: 0: 300% victim%'
        - 'MESSAGE: & 4You're bleeding! % victim% '
        - 'MESSAGE: & the enemy is bleeding! % attacker% '
        - 'BLEED: 5: 10: 5% victim%'

Advanced Enchantments V. 8.6.16
MC: 1.16.5

### "/ae plinfo" link

https://paste.md-5.net/zefivuhifo

**Comment by Insprill** [comment]
Can't reproduce on the latest version and we have reports that this has been fixed. Will reopen if it's still an issue in the next update.
