### ISSUE TITLE
Enchantment description still there, after i disenchant using grindstone

### ISSUE THREAD

**Issue by Rigyurai** [GC-spigot/AdvancedEnchantments#2395]
### Describe the bug

I want to remove the enchantment, so i used the grindstone. but the description still there after removing the enchantment

### How to reproduce

the enchantment need to be remove after disenchantment

### Screenshots / Videos

![2021-10-05_04 53 33](https://user-images.githubusercontent.com/91918185/135924145-5958fe72-bd8a-4e9b-95da-35e53044bf4a.png)

### "/ae plinfo" link

https://paste.md-5.net/rawotalivu

**Comment by Insprill** [comment]
Couldn't reproduce. Try updating Paper (you're running a very old version) and update AE to 8.6.17.
