### ISSUE TITLE
too many bugs after update (effect enchantments, mcMMO incompatible)

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2396]
### Describe the bug

purpur : 1.16.5
plinfo: https://paste.md-5.net/anececamat
AdvancedEnchantments - lastest(8.6.17)
use-experimental-block-breaking: true (i tested both of them)

too many enchantment bugs after update (8,6.9 -> 8.6.17)

TP_DROPS
Some mcmmo skills (ex: double drop - Mining,Herbalism / Green Thumb - Herbalism)
are not applied when TP_DROPS effects are being used.

TRENCH
mcmmo experience are not gaied with use the tool that trench effect are applied.

### How to reproduce

TP_DROPS - can it applies effect with mcmmo?
TRENCH - can fix gain experience with this effect?

### "/ae plinfo" link

https://paste.md-5.net/anececamat

**Comment by NCSV** [comment]
+ this 2 enchantment are not applied together (after update lastest)

구세주:
  display: '%group-color%구세주'
  description: "자신과 인근 플레이어에게 재생을 부여합니다. \n레벨이 오를수록 범위와 성능이 올라갑니다."
  applies-to: '투구'
  type: 'REPEATING'
  time: 5
  group: '신화'
  applies:
    - 'ALL_HELMET'
  levels:
    '1':
      effects:
        - 'POTION_OVERRIDE:REGENERATION:0:100 <aoe> radius=16 target=all </aoe>'
        - 'POTION_OVERRIDE:REGENERATION:0:200'
    '2':
      effects:
        - 'POTION_OVERRIDE:REGENERATION:1:100 <aoe> radius=20 target=all </aoe>'
        - 'POTION_OVERRIDE:REGENERATION:1:200'     


지도자:
  display: '%group-color%지도자'
  description: "자신과 인근 플레이어에게 신속과 성급함을 제공합니다. \n레벨이 오를수록 범위와 성능이 올라갑니다."
  applies-to: '투구'
  type: 'REPEATING'
  time: 5
  group: '신화'
  applies:
    - 'ALL_HELMET'
  levels:
    '1':
      effects:
        - 'POTION_OVERRIDE:SPEED:0:100 <aoe> radius=12 target=all </aoe>'
        - 'POTION_OVERRIDE:FAST_DIGGING:0:100 <aoe> radius=12 target=all </aoe>'
        - 'POTION_OVERRIDE:FAST_DIGGING:0:200'
        - 'POTION_OVERRIDE:SPEED:0:200'
    '2':
      effects:
        - 'POTION_OVERRIDE:SPEED:1:100 <aoe> radius=16 target=all </aoe>'
        - 'POTION_OVERRIDE:FAST_DIGGING:1:100 <aoe> radius=16 target=all </aoe>'
        - 'POTION_OVERRIDE:FAST_DIGGING:1:200'
        - 'POTION_OVERRIDE:SPEED:1:200'
    '3':
      effects:
        - 'POTION_OVERRIDE:SPEED:2:100 <aoe> radius=20 target=all </aoe>'
        - 'POTION_OVERRIDE:FAST_DIGGING:2:100 <aoe> radius=20 target=all </aoe>'
        - 'POTION_OVERRIDE:FAST_DIGGING:2:200'
        - 'POTION_OVERRIDE:SPEED:2:200'

**Comment by Insprill** [comment]
Both issues are duplicates and have existed for a very long time.

**Comment by NCSV** [comment]
> Both issues are duplicates and have existed for a very long time.

second issue are worked before AE update.

can't fix these issues?
