### ISSUE TITLE
AdvancedEnchantments Essentials Kits Addon Breaks With AdvancedEnchantments Version 8.6.16 and Up

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2398]
### Describe the bug

I know it is an older plugin and it may not be supported. But AdvancedEnchantments Essentials Kits Addon still works great until you upgrade past AdvancedEnchantments 8.6.15. Version 8.6.16 breaks something and if it isn't too much hassle, I'd very much appreciate it being fixed as my server heavily relies on it.

Here is the error message I get when tying to use /kit https://mcpaste.io/969fbfb703dfac32

### How to reproduce

Download this plugin and try to use /kit with the latest version of AdvancedEnchantments https://www.spigotmc.org/resources/advancedenchantments-essentials-kits-addon.65548/

### "/ae plinfo" link

https://paste.md-5.net/misokurawu

### Server Log

https://mcpaste.io/969fbfb703dfac32

**Comment by GC-spigot** [comment]
[You can ](https://ae.advancedplugins.net/configuration/enchantments-in-essentials-kits)
