### ISSUE TITLE
trench is not give vanila EXP 

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2399]
### Describe the bug

when player break ore block, trench is not give exp. (not mcmmo, it's valina)
so player can't gain durability through mending

### How to reproduce

can it fix to gain exp when player break ore blocks?

### "/ae plinfo" link

https://paste.md-5.net/izageyiyiz

**Comment by Insprill** [comment]
Does experimental-block-breaking have an effect on this?

**Comment by NCSV** [comment]
> Does experimental-block-breaking have an effect on this?

yes. both i have tried.
also mcmmo exp are not gained
