### ISSUE TITLE
Permission not working for /ae view

### ISSUE THREAD

**Issue by FrontierPixelmon** [GC-spigot/AdvancedEnchantments#2402]
### Describe the bug

In the wiki, the permission listed for **/ae view** is the same as **/ae info**.
When I gave the players access to **ae.info** and **ae.list** they can use **/ae list** but not **/ae view**.
Also when the enchantments are listed in chat, they cannot click on any to view them. They just get an error message:
"You don't have permission to do that!"

Did the permission node change for **/ae view** and if so please update the wiki. If not then this is a bug.

### How to reproduce

give defaults permission to ae.info and try using the command /ae view

### Screenshots / Videos

https://gyazo.com/9a87d18c689b218820a8f723620907ce
https://gyazo.com/bc181493b411224bd58a5463a23bcc05
https://gyazo.com/b9e2ccb9165901f7b4d02ba91b16a16e

### "/ae plinfo" link

https://paste.md-5.net/bayeyucuna

### Server Log

https://mcpaste.io/6615137108207fb0

**Comment by FrontierPixelmon** [comment]
Also can you please fix / add support for non case sensitive commands. 
If a player uses _/ae info Telepathy_ then it will say "Telepathy is not a valid enchant"
Where if they use _/ae info telepathy_ then it will work and list the information

**Comment by GC-spigot** [comment]
`/ae view` permission will be set in customcommands.yml file, `enchantment-info.permission` is the path to it. That's what we mean by it in wiki.

Fixed the case sensitive issue
