### ISSUE TITLE
BOW_SHOOT event not working

### ISSUE THREAD

**Issue by ArefyNetwork** [GC-spigot/AdvancedEnchantments#2403]
### Describe the bug

I am using latest version of AE plugin. My developer made me a custom effect extension that triggers on BOW_SHOOT type of event.
The enchant with the effect loaded with no problems, but it does not triggers.

### How to reproduce

This error message pops out everytime I shoot

### Screenshots / Videos

https://m.arefy.net/gZGxSqf.png

### "/ae plinfo" link

https://paste.md-5.net/yaqapofota

### Server Log

https://mcpaste.io/aecc803ca8ef75ec

**Comment by GC-spigot** [comment]
Unfortunately this enchant type only works for 1.11+ servers  right now

**Comment by wellnesscookie** [comment]
It does work fine on 1.8 with AE 8.6.15 version, and why would this be closed?
If it's 'for now', then it can at least stay as a feature request.
