### ISSUE TITLE
Smelting enchant PlayerItemDamageEvent

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2405]
### Describe the bug

When using the smelting enchant (Im using it on a pickaxe), the playerItemDamage event gets cancelled and I am not sure why. However, the item durability still goes down. What is the code behind this and how can I cancel the playerItemDamageEvent if it is not being called when using this enchant?

### How to reproduce

Mine with the smelting enchant

### "/ae plinfo" link

https://paste.md-5.net/ewehelelak

**Comment by GC-spigot** [comment]
Fixed
