### ISSUE TITLE
Armor sets no longer work in the latest version

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2407]
### Describe the bug

When giving an armor set, I get an error and also none of the armor sets work. here is the error https://pastebin.com/a86TuHC1

### How to reproduce

Give an armor set

### "/ae plinfo" link

https://paste.md-5.net/cuzomihusa

**Comment by FN-FAL113** [comment]
> @FN-FAL113 They are Armor sets in the armorSets directory. Default ones for example are KOTH. When I try /asets give jharris koth on a DEFAULT config, they dont work with the error above

try downgrading or updgrading your AE Version, had a lot of issues with latest ones, Im using 8.2.8 rn. Latest ones are really buggy I could tell you myself
