### ISSUE TITLE
Could not pass PlayerAmorChangeEvent

### ISSUE THREAD

**Issue by SwartZCoding** [GC-spigot/AdvancedEnchantments#2411]
### Describe the bug

When i equip or unequip an armor AdvancedEnchantments throws errors.

I use paperspigot 1.12.2 & last AdvancedEnchantments version.

### How to reproduce

Just put or unequip armor, the plugin throws errors No class deffounderror : /org/bukkit/inventory/meta/Damageable

### Screenshots / Videos

https://gyazo.com/262f42d68862f5b702b2d3d49d536354

### "/ae plinfo" link

https://paste.md-5.net/odajiveloc

**Comment by kyousuke33** [comment]
Hi, SwartZCoding, I had the same error as you.
After I changed to an older version (AE 8.6.14), the error was gone
I use paper-1.12.2-1618
Hope this information can help you

**Comment by SwartZCoding** [comment]
> Hi, SwartZCoding, I had the same error as you. After I changed to an older version (AE 8.6.14), the error was gone I use paper-1.12.2-1618 Hope this information can help you

Hi ! Thanks for your reply, i know that. But i prefer udpate the plugin to fix others issues 😅.

**Comment by GC-spigot** [comment]
Fixed
