### ISSUE TITLE
AESETS with Heroic Upgrades unrepairable and 0 durability bug

### ISSUE THREAD

**Issue by FN-FAL113** [GC-spigot/AdvancedEnchantments#2413]
### Describe the bug

we are unable to repair aesets that has heroic upgrades through anvil, and its not breaking even though the durability is already at value 0. 
We implemented aesets as crate rewards over loreattributes, now we didn't realize that it is not even repairable through an anvil when it is upgraded using a Heroic Uprade item.

### How to reproduce

AESET Armors that are upgraded with Heroic Upgrades cannot be broken even after hitting it many times at 0 durability and it 
doesn't work on anvils by using the same material as the armor to repair it. Normal AEsets without heroic upgrades works fine though and they can be repaired.

### Screenshots / Videos

https://prnt.sc/1vok12y

### "/ae plinfo" link

https://paste.md-5.net/fijewerime

**Comment by FN-FAL113** [comment]
Update: The AE sets can't be repaired only when it is upgraded to heroic or an Heroic upgrade is applied to an armor

**Comment by GC-spigot** [comment]
Fixed
