### ISSUE TITLE
Issue with negating/removing damage and %mob type%

### ISSUE THREAD

**Issue by CrystallizedAtrophy** [GC-spigot/AdvancedEnchantments#2414]
### Describe the bug

Told to make a ticket here by one of the staff on discord, said it might be something internal.

Trying to get this enchant to work: https://pastebin.com/t5Pv0GhX

Trying to get when a certain mob attacks the player then it negates/lessens the damage. Tried switching between all the variables that lessen damage but still doesn't work. Tried using not equals to in the code with no affect.

The enchant will work when you add ATTACK or ATTACK_MOB but not with DEFENSE or DEFENSE_MOB, it seems when its on DEFENSE or DEFENSE_MOB it tries putting it onto the mob instead when the target should be player. 

### How to reproduce

Try to get specific mobs to attack you and have a defense enchant trying to protect you.

### Screenshots / Videos

https://gyazo.com/95458fafb213f114fd5d6c735d7f6232

### "/ae plinfo" link

https://paste.md-5.net/uludececud

### Server Log

https://mcpaste.io/84ebe50ed2c88190 or https://mcpaste.io/dcb3a43cfe21755a

**Comment by GC-spigot** [comment]
Fixed
