### ISSUE TITLE
Enchant was stopped from parsing

### ISSUE THREAD

**Issue by baailey** [GC-spigot/AdvancedEnchantments#2415]
### Describe the bug

Unsure if this is a bug or not, but when using the condition `%mob_type% = ENDERMAN` with the effect `STOP_ATTACK`, it will send a message in chat and console saying `Invalid condition: ENDERMAN=enderman, enchant was stopped from parsing`. This occurs when the enderman is killed. If you look at another mob there will be no error, but when you hit the mob it'll repeat the same message, except `ENDERMAN` will be replaced with the name of the mob you hit https://i.imgur.com/LYt3g4b.png

### How to reproduce

Use this enchant, look at the enderman, and kill it. Or, look at another mob and hit it.

`example:
  display: '%group-color%Example'
  description: "Example lore"
  applies-to: 'Helmet'
  type: 'ATTACK_MOB'
  group: 'ULTIMATE'
  applies:
    - ALL_HELMET
  levels:
    1:
      chance: 100
      condition:
        - '%mob type% = ENDERMAN'
      effects:
        - 'STOP_ATTACK'`

### "/ae plinfo" link

https://paste.md-5.net/sonaficata

**Comment by GC-spigot** [comment]
The condition is not complete, e.g. would be `%mob type% = ENDERMAN : %allow%` - you didn't include what it should do after it's met

**Comment by baailey** [comment]
@GC-spigot using this players cannot hit endermen, how do I resolve this?
