### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by HaruNishino** [GC-spigot/AdvancedEnchantments#2417]
### Describe the bug

I'm really not sure where this is coming from and I can't identify where as well.

### How to reproduce

This only appears whenever server is being started. 

### "/ae plinfo" link

https://paste.md-5.net/aweyipuviw

### Server Log

https://mcpaste.io/6cbe82cd46348858

**Comment by GC-spigot** [comment]
Switch from Purpur to something else, it's extremely broken.
