### ISSUE TITLE
1.17.1 | v8.6.19 | ClassCastException for Arrows against shield

### ISSUE THREAD

**Issue by EnderGamingFilms** [GC-spigot/AdvancedEnchantments#2418]
### Describe the bug

There seems to be a missing check in the plugin where when a player is shot with an arrow (only tested from mobs) the plugin attempts to cast the arrow to a `LivingEntity` rather than using `getShooter()` attribute first and then casting.

### How to reproduce

Get shot by different skeleton mobs and block with a shield (I noticed a shield object in the stacktace).

### "/ae plinfo" link

https://paste.md-5.net/icutahejob

### Server Log

https://hastebin.com/jezuzovoja.bash

**Comment by GC-spigot** [comment]
Fixed
