### ISSUE TITLE
%chance%-amount not wokring

### ISSUE THREAD

**Issue by TheLeby9** [GC-spigot/AdvancedEnchantments#2421]
### Describe the bug

i created a new enchant that works fine with condition %chance%+2 but doesn't work and send spam errors in console when i put %chance%-2 or any amount . please check the reproduce for the config . everything works fine with + chance or without condition but with - chance it doesn't work and spam errors.

### How to reproduce

condition:
- %mob type% = BLAZE : %chance%+2

this works

condition:
- %mob type% = BLAZE : %chance%-2

this doesn't work and spam errors

### "/ae plinfo" link

https://paste.md-5.net/documents

**Comment by GC-spigot** [comment]
Try this, it works:
```poison:
  display: "%group-color%Poison"
  description: "A chance of giving poison effect."
  applies-to: "Swords, Axes"
  type: "ATTACK;ATTACK_MOB"
  group: "ELITE"
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    1
      condition: '%mob type% = BLAZE : %chance%+100'
      chance: 0
      effects:
        - "MESSAGE:yes %attacker%"```
        
        Make sure your formatting matches
