### ISSUE TITLE
Rgb-color: color don’t work on anything but the groups yml 

### ISSUE THREAD

**Issue by spacemex** [GC-spigot/AdvancedEnchantments#2422]
### Describe the bug

The rgb-color: 255;255;255 this is an example do not work in other yml file I added firework_star to such as config.yml only works in the group.yml there is no errors in the console 

### How to reproduce

All said in description 

### Screenshots / Videos

N/a

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by GC-spigot** [comment]
```groups:
  SIMPLE:
    global-color: "&7"
    group-name: "Simple"
    # Use this to change the type of item per group
    item:
      type: FIREWORK_CHARGE
      id: 0
      custom-model-data: 0
      # Use this to set firework charge's color only! Uses RGB
      # Find colors here: https://htmlcolorcodes.com/color-picker/
      rgb-color: 200;200;200```
      
      Works just fine!
