### ISSUE TITLE
MINING type has issues

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2424]
### Describe the bug

When using the MINING type it seems to not give off ANY events. I've tried to listen to so many different events but none work. The durability of the item still goes down without throwing the PlayerItemDamageEvent for example

### How to reproduce

Put an enchant with the MINING type on and try to listen to the PlayerItemDamageEvent

### "/ae plinfo" link

https://paste.md-5.net/sowulonuyi

**Comment by GC-spigot** [comment]
Should be better now
