### ISSUE TITLE
Method applyenchant() from API Problem

### ISSUE THREAD

**Issue by TAPGODYT** [GC-spigot/AdvancedEnchantments#2426]
### Describe the bug

when using the method _applyenchant()_ to an ItemStack the method only adds the lore making the enchantment not working only the lore show up.

### How to reproduce

here is my code for example
----------------------------------------------------------------
```
private ItemStack generateItemFromConfig(String kitname, ItemStack customItem, int itemSlot) {
        AEAPI EnchantAPI = new AEAPI();

        if (kitConfigGenerator.get().getString(kitname + ".item" + itemSlot + ".type") != null) {
            int itemsamount = kitConfigGenerator.get().getInt(kitname + ".item" + itemSlot + ".amount");
            customItem = new ItemStack(Material.valueOf(kitConfigGenerator.get().getString(kitname + ".item" + itemSlot + ".type")), itemsamount);
            ItemMeta meta = customItem.getItemMeta();

            List<String> lores = new ArrayList<>();
            for (String l : kitConfigGenerator.get().getStringList(kitname + ".item" + itemSlot + ".lores"))
                lores.add(ChatColor.translateAlternateColorCodes('&', l));
            meta.setLore(lores);
            meta.setDisplayName(ChatColor.translateAlternateColorCodes('&', kitConfigGenerator.get().getString(kitname + ".item" + itemSlot + ".DisplayName")));
            meta.addItemFlags();
            customItem.setItemMeta(meta);
            EnchantAPI.applyEnchant("speed",1,customItem);
            return customItem;
        }
        return null;
    }
```
after this, I give the ItemStack to a player, and here is what I get.
![2021-10-15_23 18 21](https://user-images.githubusercontent.com/92544259/137571733-e0b5474b-1fbb-430c-8c9c-6e2245044cef.png)

only the lore is applied (Server Version is 1.8.8 Spigot)

### "/ae plinfo" link

https://paste.md-5.net/nekugaqija

**Comment by Insprill** [comment]
All the AEAPI methods are static so you can access them directly. For it to work properly you need to set customItem to the return value of the applyEnchant method.
