### ISSUE TITLE
Spartan Hook

### ISSUE THREAD

**Issue by mesl** [GC-spigot/AdvancedEnchantments#2427]
### Describe the bug

Some enchantments get flagged by the spartan anticheat such as launch and trench

### How to reproduce

Setup a server with the latest spartan & AE plugin; Get trench on a pickaxe and mine around (use netherrack for the fastest effect)
for launch, get the launch enchantment and just use it

Also make sure you're not Opped / have spartan exempt permission otherwise you won't get flagged or punished

### "/ae plinfo" link

https://pastebin.com/WZtHHwe4

**Comment by GC-spigot** [comment]
Fixed
