### ISSUE TITLE
FALL_DAMAGE not working

### ISSUE THREAD

**Issue by TasmanianNoob** [GC-spigot/AdvancedEnchantments#243]
Version: 1.12.2 TacoSpigot (https://hastebin.com/zezetifuga.md)

Plugins: AdvancedEnchantments (https://hastebin.com/etaxunazar.md)

Plugin Version: 5.0.5 - latest (https://hastebin.com/semohexaki.md)

Issue: I was trying to make an enchantment using the FALL_DAMAGE type but nothing would work when I took fall damage, here is the enchantment - https://hastebin.com/ahawahadil.bash and nothing happened, I took the fall_damage and nothing was sent to the player with no errors in the console and I also took the fall damage, I also tried using CONSOLE_COMMAND to see if anything came up in console as a debug but nothing did so I believe that the FALL_DAMAGE type is either broken/just isn't triggering.

**Comment by GC-spigot** [comment]
Fixed!
