### ISSUE TITLE
Armor duplication glitch

### ISSUE THREAD

**Issue by MaeTF** [GC-spigot/AdvancedEnchantments#2430]
### Describe the bug

It causes armor to be easily duplicated with a simple right click/auto equip

### How to reproduce

While holding an armor piece (version 8.7.1) and right clicking to equip from inventory, there is a random chance that it will duplicate and equip into your specific armor region, and leave behind a duplicate armor piece with enchants and everything. 
However, you're only able to perform this if looking up at the air, and then throwing the armor piece out from your inventory **then**, trying to right click equip. It happens at random equip amounts which range from 1 up to 30 tries, so it tends to happen. I know this is caused from the described version because the issue stopped happening once the plugin has been removed.

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by MaeTF** [comment]
The server I help manage also utilizes 80gb of ram, so I believe its purely a plugin issue let alone a server issue.

**Comment by GC-spigot** [comment]
My assumption is that your factions plugin has an armor equipping feature of some sorts. I couldn't recreate this.

**Comment by LeitoCc187** [comment]
i also am having this issue with the dupe ive tryed updateing the the news viroson of the plugin at this time witch is 8.8.1 and it has not fixed the issue
