### ISSUE TITLE
Telepathy + Silktouch; Redstone

### ISSUE THREAD

**Issue by FrontierPixelmon** [GC-spigot/AdvancedEnchantments#2431]
### Describe the bug

Breaking redstone (dust) with telepathy works just fine!
However if the tool also has silktouch, it no longer picks up the redstone, instead it just breaks it.

### How to reproduce

^ I described how to reproduce it with the report above.
I can take a video if need be. However it seems to be a similar issue to some of the other posts about telepathy + silktouch. So I figured, you wouldn't need it.

### "/ae plinfo" link

https://paste.md-5.net/iyixekorol

**Comment by GC-spigot** [comment]
Fixed
