### ISSUE TITLE
Bug with NightWalker enchantment

### ISSUE THREAD

**Issue by Kiran-GC** [GC-spigot/AdvancedEnchantments#2432]
### Describe the bug

So ive noticed that the enchantment Nightwalker which freezes mobs during night time gives the player slowness X or something while killing mobs on day.

### How to reproduce

Enchant a sword with NightWalker enchant and while the time is day simply kill a mob. It will give the player 20 seconds of slowness

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/84382139/138122085-64495e93-f9d3-4e22-9c33-b46e3b61ac37.png)

### "/ae plinfo" link

https://paste.md-5.net/sogipezaqi

**Comment by GC-spigot** [comment]
Fixed
