### ISSUE TITLE
1.17.1  matierials and items & veinminer

### ISSUE THREAD

**Issue by spacemex** [GC-spigot/AdvancedEnchantments#2433]
### Describe the bug

the plugin don't support any of the new items with 1.17.1 eg Vein_Mine don't break deepslate ores and the %block type% contains (ore name) : %allow% don't work as well 

### How to reproduce

try useing vein mine  enchant for deepslate ores 

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by GC-spigot** [comment]
You will need to add DEEPSLATE ores to vein whitelist, will be updated with default files for next update
