### ISSUE TITLE
Description-Related on Loot crates, envoys plugin, Koth

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2435]
### Describe the bug

When you remove the enchantments of items that came from lootcrates plugins, such as envoys, King of the hill rewards, it removes the enchantments, yes, but the lore stays.

### How to reproduce

Need a loot crate plugin or some envoy plugin or King of the hill one, add it to rewards, then blackscroll it. and you will see.

### Screenshots / Videos

https://i.imgur.com/AKV0cQU.png

### "/ae plinfo" link

https://paste.md-5.net/mimahokezo

**Comment by GC-spigot** [comment]
Try disabling descriptions, they change how lores are formatted and we can't really do anything about this unfortunately
