### ISSUE TITLE
Unable to upgrade existing CE on item

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2436]
### Describe the bug

If an item has Explosive I and I want to upgrade it and add Explosive V, it won't accept it.
There are no errors.

### How to reproduce

Put a lower tier enchant on an item, and try to put a higher tier variant of the same enchant on the item.

### Screenshots / Videos

https://streamable.com/qpxeg9

### "/ae plinfo" link

https://paste.md-5.net/ufaduzumoq

**Comment by GC-spigot** [comment]
Set `combining.chances.upgrade` in config.yml to true
