### ISSUE TITLE
Issues with Enchanter

### ISSUE THREAD

**Issue by NordicGamerFE** [GC-spigot/AdvancedEnchantments#2437]
### Describe the bug

Each time you press the enchants in /enchanter nothings happens and it throws an error in console, Legendary GUI works tho

### How to reproduce

get all the premade enchants and just do /enchanter and try to press any of the enchants

### "/ae plinfo" link

https://paste.md-5.net/amogibeley

### Server Log

https://mcpaste.io/b89612e1441865b7

**Comment by GC-spigot** [comment]
Invalid groups in config's enchanter configuration

**Comment by NordicGamerFE** [comment]
Well, should this be an issue tho?. we didn't do anything except install the plugin and install the premade things
