### ISSUE TITLE
KILL_MOB doesn't work with bows

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#2438]
### Describe the bug

In the past KILL_MOB used to be triggered when shooting mobs with bows, but currently it only seems to work when the mob is killed when being hit with the bow directly.

### How to reproduce

I used this exemplary enchantment to verify the bug (only slight adjustments to makre the readout easier):

devour:
  display: "%group-color%Devour"
  description: "Chance to restore food while killing mobs."
  applies-to: "Weapons"
  type: "KILL_MOB"
  group: "UNIQUE"
  applies:
    - ALL_SWORD
    - ALL_AXE
    - BOW
  levels:
    1:
      chance: 10
      effects:
        - "ADD_FOOD:1"
    2:
      chance: 15
      effects:
        - "ADD_FOOD:1"
    3:
      chance: 100
      effects:
        - "ADD_FOOD:10"
        - 'MESSAGE:&b&l** Triggered **'

After applying it to a bow, simply start shooting mobs, the effects should not be triggered.

### Screenshots / Videos

---

### "/ae plinfo" link

https://paste.md-5.net/ovucarumor

### Server Log

https://mcpaste.io/b055f604c0b539c3

**Comment by GC-spigot** [comment]
Fixed
