### ISSUE TITLE
TRENCH issue with JobsReborn

### ISSUE THREAD

**Issue by Pandas0** [GC-spigot/AdvancedEnchantments#2440]
### Describe the bug

The new TRENCH change (only breaks the blocks the tool can) causes issues with JobsReborn.

When running JobsReborn and being in the miner job (gets paid from stone and such), and you use a shovel on dirt with stone under it, the TRENCH will still pay for the stone blocks under it even though its not being broken.

### How to reproduce

Install AE + JobsReborn (and dependencies), join the Miner job and get a shovel using an enchantment with TRENCH. Find a patch of dirt with stone under it (within the TRENCH range) and mine the dirt.

You will be paid for both the stone, when it shouldn't pay for anything (or only the dirt, if the job pays for that).

### Screenshots / Videos

N/A (Can be provided if needed)

### "/ae plinfo" link

https://paste.md-5.net/vebahudifa

**Comment by GC-spigot** [comment]
Fixed
