### ISSUE TITLE
BOOT DUPE AND IMMORTALITY BUG ON USERS

### ISSUE THREAD

**Issue by GeRmAnAnToNiO124** [GC-spigot/AdvancedEnchantments#2442]
### Describe the bug

People become immortal with life-giving incantations and the enchanting soul siphon makes the boots double.
I tried with the new version and the old one and the same problem happens, in the new version there are both errors and in the previous version that I downgraded the immortality bug is the only one that works.

### How to reproduce

Attack a user, with spells that give generation or healing the user is disconnected and becomes immortal.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/895568753033617457/901195678385045554/VID-20211022-WA0143.mp4

### "/ae plinfo" link

https://paste.md-5.net/saleyagubi

### Server Log

https://mcpaste.io/e62fe714ad580b2c

**Comment by GC-spigot** [comment]
Do you have the errors? Which enchants are causing your issues? Haven't had any reports from anyone else
