### ISSUE TITLE
Specific GKits aren't giving you the loot

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#2443]
### Describe the bug

Specific GKits (Hyperdrive, Valentine, Trickster, Templar, Cannoner, Loki, Grim Reaper) aren't giving the promised loot

### How to reproduce

Just try to give urself the kit 

### Screenshots / Videos

No need, just try getting it from the GUI/commands.

### "/ae plinfo" link

https://paste.md-5.net/xuneyutera

### Server Log

https://mcpaste.io/e662b8851e163b7d

**Comment by GC-spigot** [comment]
Fixed
