### ISSUE TITLE
LEFT_CLICK Not working on types 

### ISSUE THREAD

**Issue by SNokerYT** [GC-spigot/AdvancedEnchantments#2444]
### Describe the bug

right-click working fine but left click not working | please fix this problem fast
type: 'LEFT_CLICK'

### How to reproduce

right-click working fine but left click not working | please fix this problem fast
type: 'LEFT_CLICK'

### Screenshots / Videos

https://paste.md-5.net/

### "/ae plinfo" link

https://paste.md-5.net/

### Server Log

https://paste.md-5.net/

**Comment by GC-spigot** [comment]
Not even an enchant type, where'd you get that from? Use `SWING`
