### ISSUE TITLE
Plugin Fails To Function

### ISSUE THREAD

**Issue by Cyndergate** [GC-spigot/AdvancedEnchantments#2445]
### Describe the bug

https://pastebin.com/Sx40d8kU
Line: 1431

Plugin will fail to launch after it loads.
When doing /ae in the server it will only say /AdvancedEnchantments

Any related command will result in the same.

### How to reproduce

I tried this in both 8.7.2 and 8.7.3

Any plugin related command just comes up with /AdvancedEnchantments and in the error logs it fails to initiate properly.

### "/ae plinfo" link

The plugin doesn't work for me to do this.

### Server Log

https://pastebin.com/Sx40d8kU [Line 1431]

**Comment by GC-spigot** [comment]
Fixed, will be available in next update 8.7.6
