### ISSUE TITLE
Transmog Scroll not working/applicable

### ISSUE THREAD

**Issue by TheLeby9** [GC-spigot/AdvancedEnchantments#2446]
### Describe the bug

Transmog scroll is not working, you cannot apply the transmog scroll, nothing happen when you drag it on the item. This occured after i updated the plugin. Please look into it asap.

### How to reproduce

Be on the latest plugin version
Apply a transmog scrroll.

### "/ae plinfo" link

https://paste.md-5.net/itosucabuh

**Comment by GC-spigot** [comment]
Check console for errors
