### ISSUE TITLE
armor with enchantments damages without being equipped

### ISSUE THREAD

**Issue by AlbertoHinojosa** [GC-spigot/AdvancedEnchantments#2447]
### Describe the bug

the enchantments have effects even if the armor is not equipped an example poisoned IV takes effect just by having the piece of armor in hand as far as this happens with all enchantments

### How to reproduce

applying an enchantment that damages whoever hits you or that heals you, if it is healing, it will be enough to equip it in your hand and change the slot to the one where the armor is and if it is damage, it will be enough to have it in your hand and someone hits you

### Screenshots / Videos

https://youtu.be/4ag0tQoEfMw

https://youtu.be/jd7h0WtTQG0

### "/ae plinfo" link

https://paste.md-5.net/yedeleqapu

**Comment by GC-spigot** [comment]
Fixed
