### ISSUE TITLE
Not being able to use custom model data on alchemist, confirm and tinkerer menus

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#2448]
### Describe the bug

I'm trying to use the custom model data feature to make invisible buttons and making custom guis for advancedenchantments but on the tinkerer and alchemist gui it's not possible to actually use the custom model data feature because there isn't the custom-model-data string so I tried adding my custom model data id on the id string but it didn't work at all.

### How to reproduce

Just try to use custom model data on the alchemist, confirm and tinkerer menu.

### Screenshots / Videos

https://imgur.com/a/yPVwz05

### "/ae plinfo" link

https://paste.md-5.net/ogozezipiy

**Comment by Fenix61718** [comment]
Yes! I'm trying to do this for my server too but it just doesn't work and it's really sad, this plugin is really nice but this feature is _so_ important in my opinion it's a pity it doesn't work. Hope it gets fixed soon because I really need it working and it is a key feature!

**Comment by 10lulu** [comment]
Same here, I'm currently remodeling my GUIs and kinda got stuck bc the alchemist and tinkerer don't work with the custom model data feature. It would be really nice if that feature was implemented as soon as possible, since I cant continue with the GUIs until this is done. Would be a pity to remake everything just because those don't work.

**Comment by i-Elijah** [comment]
i don't know what's going on but i agree.

**Comment by Btrav21** [comment]
I run a SMP server, and I plan to make a total rework on my gui's and implement some new ones where making invisible buttons would be useful to let more space for arts, pictures/drawings. I thought that feature was implemented but now i'm struggling a bit between continue without art or just looking at another plugin for the next reset incoming..

**Comment by EternalWolff** [comment]
Custom-modal-data sounds dupe

**Comment by Agaloth** [comment]
> Custom-modal-data sounds dupe

wdym dupe lmao

**Comment by EternalWolff** [comment]
I meant dope 😂 (good)

**Comment by lucian929** [comment]
+1

**Comment by Stuart-BimboJimbo** [comment]
+2

**Comment by Ataruu** [comment]
+3

**Comment by NikV2** [comment]
+4

**Comment by MrMcyeet** [comment]
+5

**Comment by EchoRapidz** [comment]
+6

**Comment by democracycraft** [comment]
Would be a useful feature!

**Comment by MadenTo20** [comment]
This sounds really useful, i want that

**Comment by BRASHEXODUS** [comment]
+100 could use aswell

**Comment by Agaloth** [comment]
May I know why that was closed without any comments? Let me know as soon as possible! Thanks a lot!
