### ISSUE TITLE
Blinking HP bar

### ISSUE THREAD

**Issue by naikyys** [GC-spigot/AdvancedEnchantments#2449]
### Describe the bug

The bug is maybe with enchant Overload, when I got it on the HP bar is blinking

### How to reproduce

Enchant armor by enchant Overload

### Screenshots / Videos

https://i.gyazo.com/80a12e92aa06dea33dae14bb4f4a5c35.mp4

### "/ae plinfo" link

https://paste.md-5.net/eveyodifat

**Comment by GC-spigot** [comment]
Weird, can you try a different minecraft version (client)? May be visual, unsure. Seems like something else is healing / setting health.

If that doesn't work you may need to start removing plugins.
