### ISSUE TITLE
[Request] DEFENSE_MOB

### ISSUE THREAD

**Issue by Blazingshadow17** [GC-spigot/AdvancedEnchantments#245]
Please add a 'type' such as DEFENSE_MOB, for when mobs attack you something happens to them.

For example,
https://pastebin.com/AVLLd6Ga

This enchant will only work versus players who melee attack, and will not affect mobs. If you can add another DEFENSE 'type' for against mobs (separate melee and ranged would be cool if possible) that would be great (especially for PVE servers)!

Thanks, 
Blazingshadow17 (SoggyCraft)

**Comment by GC-spigot** [comment]
Added!
