### ISSUE TITLE
Effect "BREAK_TREE" breaks every log.

### ISSUE THREAD

**Issue by Darkytz** [GC-spigot/AdvancedEnchantments#2453]
### Describe the bug

Hello,

I'm running the latest version of AE, when players mine a tree with the enchant "Timber" which has an effect of "BREAK_TREE" this also inflicts to their houses and not only trees.

If you need more info please ask, I will give it then! 

### How to reproduce

Put the Timber enchant on your tool (code):

`timber:
  display: "%group-color%Timber"
  description: "Chance to break a tree in one hit"
  applies-to: "Axes"
  group: "LEGENDARY"
  type: "MINING"
  applies:
    - "ALL_AXE"
  levels:
    1:
      chance: 15
      cooldown: 5
      effects:
        - "BREAK_TREE"
    2:
      chance: 35
      cooldown: 5
      effects:
        - "BREAK_TREE"
    3:
      chance: 55
      cooldown: 6
      effects:
        - "BREAK_TREE"`

Use the axe at a home with logs as fundament (for example), it will remove most of the logs of the house if connected.

Thats all.

### "/ae plinfo" link

https://paste.md-5.net/kayepequta

**Comment by GC-spigot** [comment]
There's no way to check if a log is naturally generated or placed by a player unfortunately.
