### ISSUE TITLE
Crossbow enchants are not working

### ISSUE THREAD

**Issue by t347549** [GC-spigot/AdvancedEnchantments#2454]
### Describe the bug

I even tried with the default enchantments on crossbows but they do not activate. using BOW and BOW_MOB as the type, the effect should activate when arrow hits target. Works fine for regular bows, but refuses to work for Crossbows. 

### How to reproduce

Use any of the default crossbow enchants on a crossbow

### "/ae plinfo" link

https://paste.md-5.net/dorebaqabu

**Comment by hemanth4121** [comment]
Bump. Verified on my server as well.

**Comment by GC-spigot** [comment]
Fixed
