### ISSUE TITLE
Trench is not give mmo xp after update 8.4.4 -> 8.4.5

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2456]
### Describe the bug

After updating to the latest version, mcmmo does not give experience.
I looked it up while comparing the versions one by one.
Problems was happend after 8.4.5 version (The previous version works well)

### How to reproduce

I think block break event's chages something problems after update version of 8.4.5

### "/ae plinfo" link

https://paste.md-5.net/gufewasita

**Comment by GC-spigot** [comment]
Fixed
