### ISSUE TITLE
Lags in the newest version

### ISSUE THREAD

**Issue by naikyys** [GC-spigot/AdvancedEnchantments#2457]
### Describe the bug

In the newest version is something happening that causing lags. I was using for a long time old version and updated like after 1/2 monhts and now getting these lag spikes so I did timings reports:
- https://timings.pl3x.net/?id=73f8121bc3b949609ec4655f8c42782e#plugins
- https://timings.pl3x.net/?id=80073ddc41e045aabee93708067f7934#plugins

### How to reproduce

Try the newest version otherwise I dont know.

### Screenshots / Videos

https://imgur.com/a/cksF2xu

### "/ae plinfo" link

https://paste.md-5.net/iqukusarip

**Comment by naikyys** [comment]
Its still going. Please help :/ https://timings.pl3x.net/?id=83a6efa257324c28a1c693c4058a056f#plugins

**Comment by GC-spigot** [comment]
Cannot recreate
