### ISSUE TITLE
Extreme lag when mining End pillars

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2458]
### Describe the bug

A player is lagging the server by only breaking the end pillars, even after I have blacklisted obsidian on the TRENCH configs, how I know it's advanced enchantments plugin?
simple check my timings:
https://timings.aikar.co/?id=a59991def5c74f52af9aa8410bcb4b19
`AdvancedEnchantments::Event: n.a.a.e.e.MINING (BlockBreakEvent)count(5515)  total(60.22% 212.619s, 154.74% of tick)avg(38.55ms per - 77.37ms/2.01 per tick`

### How to reproduce

Break end pillars as fast as you.

### "/ae plinfo" link

https://paste.md-5.net/oyetufikuz

### Server Log

https://mcpaste.io/64a14728880857d8

**Comment by GC-spigot** [comment]
Try disabling ItemSoulBind plugin and see if it helps
