### ISSUE TITLE
VeinMiner and SET_BLOCK Conflict

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#2459]
### Describe the bug

Self explanatory, watch the video to understand in more detail as I can't explain it that well.

### How to reproduce

Self explanatory, watch the video to understand in more detail as I can't explain it that well.

### Screenshots / Videos

https://youtu.be/zxfArwmV7k8

### "/ae plinfo" link

https://paste.md-5.net/anosupihit

### Server Log

https://mcpaste.io/a1cc6d5f402ee9e2

**Comment by GC-spigot** [comment]
Fixed
