### ISSUE TITLE
Issuse /w FactionMCore and tools

### ISSUE THREAD

**Issue by Frostyeiz** [GC-spigot/AdvancedEnchantments#246]
Player can't use tools that have AEnchants in the wilderness, they can use them normally in their own faction lands. (OP players can, don't really know why)

**Comment by FrontierGamers** [comment]
Permission node/anticheat issue it sounds like

**Comment by baticag** [comment]
Having the same problem, doesn't seem like a permission problem. Can somebody help please?

**Comment by GC-spigot** [comment]
Should be fixed in new update (will be posted very soon)
