### ISSUE TITLE
UltimateCore-Enchantments and AdvancedEnchaments problem

### ISSUE THREAD

**Issue by SalomonPicos** [GC-spigot/AdvancedEnchantments#2460]
### Describe the bug

UC-E give me the opportunity to hook AE enchantments in its config
But it won't works and just bug the UC-E plugin 
i contacted my dev and he told me it's a AE problem
saying "Seems like there's a missing class"

### How to reproduce

Try to hook a advancedenchanments enchant into ultimatecore-enchantments and reload/restart the server. AdvancedEnchaments will stop working.

### "/ae plinfo" link

https://paste.md-5.net/atuxetexer

**Comment by GC-spigot** [comment]
Provide a video, an example config or something we can work with. I'm not familiar with this plugin neither I understand what "try to hook ae enchant" means. Ask your dev for detailed explanation of what class is missing as well.

**Comment by SalomonPicos** [comment]
2021-11-01 15-20-17.mp4
<https://drive.google.com/file/d/1UDf4fC98DLDuKW3alMIu_o-pFbsxiKkL/view?usp=drive_web>
Here's a video of me trying to hook AE enchant to UC-E config. Asked my dev
but in these days he's so busy and have no time to help me with this. Hope
this will be helpful. If you need something else let me know!

Il giorno lun 1 nov 2021 alle ore 14:16 GC-spigot ***@***.***>
ha scritto:
