### ISSUE TITLE
%exp% Placeholder in succesful-purchase not working

### ISSUE THREAD

**Issue by Jozo7** [GC-spigot/AdvancedEnchantments#2461]
### Describe the bug

-   successful-purchase: "&c&lXP Left&c: %exp%.", it is not working it shows as %exp% in chat, as you can see in the gyazo link.

### How to reproduce

I want to have https://gyazo.com/8afec6b883d7ab4da480556f049a0f2f this working, so they can see their amount of XP they have.

### Screenshots / Videos

https://gyazo.com/8afec6b883d7ab4da480556f049a0f2f

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by Felaxocraft** [comment]
Please check your /ae plinfo link, it does not seem to be correct.
Also have you installed PlaceholderAPI ?

Please include your latest.log / startup logs.

**Comment by Jozo7** [comment]
Hey, yes i do have installed PlaceholderAPI.

here the /ae plinfo link & the latest logs.
md_5 paste - ahonefesux (md-5.net)<https://paste.md-5.net/ahonefesux>

Thanks already.

Kind Regards,
Ahmed

________________________________
