### ISSUE TITLE
Placeholders in chat not working

### ISSUE THREAD

**Issue by Jozo7** [GC-spigot/AdvancedEnchantments#2463]
### Describe the bug

Placeholder not working in chat %group-name% and %enchant-no-color% 
Only the level of the enchantment book is viewing, if you are using the placeholder %enchant-no-color%

### How to reproduce

https://gyazo.com/097a56f7cb6b2d62b23583b3a7e383da here is how it has to be, it is from an other server.

### Screenshots / Videos

https://gyazo.com/d13e17e721e9152cce2ce9ad555dce63

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by Felaxocraft** [comment]
Please check your /ae plinfo link, it does not seem to be correct.
Also have you installed PlaceholderAPI ?

Please include your latest.log / startup logs.

**Comment by GC-spigot** [comment]
Fixed
