### ISSUE TITLE
Issue with buffs.

### ISSUE THREAD

**Issue by GodKiko123** [GC-spigot/AdvancedEnchantments#2464]
### Describe the bug

There is a problem that if I put an item in my AuctionHouse, I still have his buff... 
For example, If I put a pickaxe with haste 3 in the AH (AuctionHouse) the item even though I'm not in my hand continues to give me the haste ...

### How to reproduce

Placing an item on an AuctionHouse...

### "/ae plinfo" link

Lattest 1.16.5 - Purpur

**Comment by GC-spigot** [comment]
Fixed
