### ISSUE TITLE
Unbreaking enchant not working

### ISSUE THREAD

**Issue by Thefluffypvper1** [GC-spigot/AdvancedEnchantments#2465]
### Describe the bug

When using the unbreaking custom enchant it doesn't work and the armour takes damage.

### How to reproduce

Get diamond armour put unbreaking onto it and get hit by a alt to see if your armour takes damage

### Screenshots / Videos

Proof that the armour has unbreaking on it:
https://gyazo.com/e25b18b1314e77791ed6ba8024025b01

Proof the armour takes damage:
https://gyazo.com/c0646bf81cc6d36f9fe2884db7734f72

### "/ae plinfo" link

https://paste.md-5.net/joyexehovi

### Server Log

I wanna send this privet due to player security

**Comment by GC-spigot** [comment]
It's only for tools in hand
