### ISSUE TITLE
/heal doesn't fill health boost hearts

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#2466]
### Describe the bug

When using the /heal command, the extra health boost hearts added via enchants do not get filled.

### How to reproduce

Use /heal with empty extra hearts.

### Screenshots / Videos

https://youtu.be/Arkt45EMzpk

### "/ae plinfo" link

https://paste.md-5.net/ikumizuqat

### Server Log

https://mcpaste.io/cb5e1eab04da3e30

**Comment by Thefluffypvper1** [comment]
Happends on my server also

**Comment by GC-spigot** [comment]
Not really an issue on AE's end but rather on heal plugin's. Can't do much.

**Comment by RulerOfEternity** [comment]
But it worked on Essentials just fine before, what happened now?
