### ISSUE TITLE
Guided Rocket Escape not working

### ISSUE THREAD

**Issue by Jozo7** [GC-spigot/AdvancedEnchantments#2468]
### Describe the bug

Here a list with enchants that aint working: 
RocketEscape
Guided Rocket Escape
Phoenix

(Cosmic Config's)

### How to reproduce

No logs will be needed for this fix..

Those enchantments has to be fixed, i need it for mine server release. I've tested every effect and only those 3 ain't working, on phoenix it ain't even heal me or show me the title message.

### Screenshots / Videos

Rocket Escape >> https://gyazo.com/45ff743880ae4a92ff584ab34b627528

Guided Rocket Ecape >> https://gyazo.com/48e210ffdfe4ed69fd7915fc3b9ec0f1

Phoenix (I did it even on 0 souls + 100% chance and ain't working still.) >> https://gyazo.com/357adf915a044d1a3e637d0485a63a9d

### "/ae plinfo" link

https://paste.md-5.net/amanemibab

**Comment by GC-spigot** [comment]
1st - Change rocketescape values to lower ones
2nd - same goes to guidedrocketescape
In next update default values will be lowered
3rd - Works
