### ISSUE TITLE
Server Crashing incompatibility with the oraxen plugin

### ISSUE THREAD

**Issue by BookWyrm114** [GC-spigot/AdvancedEnchantments#2469]
### Describe the bug

When using the "Trench" (And possibly other mining enchants) on a Hammer added by Oraxen, and attempting to mine a block, the server spits out a ton of errors, disconnects all players, and the TPS drops to 1, forcing the owner to forcibly close the server. There might also be other enchantment bugs with Oraxen, but I have not found any others as of yet

### How to reproduce

Install oraxen and advancedenchants, then enchant an oraxen hammer with trench and try to mine something with it.

### "/ae plinfo" link

https://paste.md-5.net/carifisile

### Server Log

[2021-11-03-2.log.gz](https://github.com/GC-spigot/AdvancedEnchantments/files/7470119/2021-11-03-2.log.gz)

_No response_

**Comment by BookWyrm114** [comment]
One possible solution would be to prevent Oraxen hammers from being able to get the trench enchantment, or add some sort of oraxen integration so that it's possible to manually add a tag to an Oraxen item to prevent it from having the trench enchantment

**Comment by GC-spigot** [comment]
New update will call a unique event, you will need to ask Oraxen developer to ignore `FakeAdvancedBlockBreakEvent` event
