### ISSUE TITLE
And its back again

### ISSUE THREAD

**Issue by Stager83** [GC-spigot/AdvancedEnchantments#247]
After this last update the hundreds of console errors is back again that was fixed before. Do I really need to pastebin it? I am sure the dev knows about it.

**Comment by GC-spigot** [comment]
I do not get any errors neither a server with 250+ users that have AE installed which i havr access to.

**Comment by Stager83** [comment]
Ok lemme get my error reports and maybe figure out if it is AE or something else

**Comment by Stager83** [comment]
This is the error - https://pastebin.com/ST569ubQ

**Comment by GC-spigot** [comment]
You're 2 versions behind from the latest - update.
