### ISSUE TITLE
Spam Error in Console

### ISSUE THREAD

**Issue by Cosenzino** [GC-spigot/AdvancedEnchantments#2470]
### Describe the bug

i don't understand why it spam so much time this error.

### How to reproduce

the error probably happen when a player get off or wear a piece of Armor.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/93714240/140313768-31ea7ba7-bf6c-47b2-94c4-fdded39c57d9.png)

### "/ae plinfo" link

https://paste.md-5.net/jaxemumeyu

### Server Log

https://mcpaste.io/c9e1d464a3c28d00

**Comment by GC-spigot** [comment]
Fixed
