### ISSUE TITLE
INCREASE_DAMAGE does not work

### ISSUE THREAD

**Issue by AtlasMCOfficial** [GC-spigot/AdvancedEnchantments#2471]
### Describe the bug

The INCREASE_DAMAGE effect is not functional / extremely unpredictable. Even using the pre-made enchants, there seems to be no difference between the effect activating and not activating. For enemies without armor, values above 100 function as percentages (ex. INCREASE_DAMAGE:150 will deal 50% extra damage). For enemies who have some kind of armor / protection, the percentage increase stops making any sense. INCREASE_DAMAGE:3000 on a player with 4 Netherite Protection IV pieces deals an extra 0.03 damage (?!). I am using version 8.7.

### How to reproduce

Simply use the INCREASE_DAMAGE effect on any item and attack an enemy with armor (tested on prot 4 netherite and prot 4 diamond)

### Screenshots / Videos

https://youtu.be/AAQH8774v64

### "/ae plinfo" link

https://paste.md-5.net/epoqisigog

**Comment by plasmaplasma** [comment]
Also having same issue on my server.

**Comment by GC-spigot** [comment]
It calculates using final damage given by Spigot, we changed it to raw damage, should act different
