### ISSUE TITLE
TRANSLATION NOT WORKING

### ISSUE THREAD

**Issue by el211** [GC-spigot/AdvancedEnchantments#2472]
### Describe the bug

Describe the bug
I translated all the enchantments yml to french but its not working well, i am not getting anything in frnench its stays in english i opened a ticket on discord on staff replicated the issue he used my yml translated file , he also noticed that if we have 10 enchantments it will work but more it wont , so he told me to open the issue here

### How to reproduce

JUST ADD MY YML THAT I DID

### Screenshots / Videos

[enchantments.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/7490835/enchantments.zip)

### "/ae plinfo" link

https://paste.md-5.net/sutafakule

**Comment by el211** [comment]
and not willing to wait 2 weeks for an anwnser....

**Comment by GC-spigot** [comment]
Issue with your configuration, replied in pm
