### ISSUE TITLE
Gkit error

### ISSUE THREAD

**Issue by KingFouX** [GC-spigot/AdvancedEnchantments#2473]
### Describe the bug

Hello certain Gkit no longer works and is no longer recoverable / viewable.

AdvencendEnchant: 8.7.6
Server Paper1.16.5

(Use of Gkit.yml by default)

### How to reproduce

/gkit (right click to recover, left click to view)

Gkit which does not work:

Hyperdrive Kit (slot 1)
Loki Kit (slot 25)
Grim Reaper Kit (26)
Enchantment Kit (slot 14)
Cannoner Kit (slot 21)
Templar Kit (slot 9)
Trickster Kit (slot 8)

### "/ae plinfo" link

https://paste.md-5.net/ividogayav

### Server Log

https://mcpaste.io/54e473c2f3d7fd07

**Comment by GC-spigot** [comment]
Fixed
