### ISSUE TITLE
Explosive enchants do not work with the crossbow

### ISSUE THREAD

**Issue by poityTMK** [GC-spigot/AdvancedEnchantments#2474]
### Describe the bug

every crossbow ench with explosive effects does not even work at 100% chance when it hits the target, I use the plugin's default ench

### How to reproduce

Put any compatible spell that has an explosive effect on a crossbow and hit any mob / player

### "/ae plinfo" link

https://paste.md-5.net/elexomipoy

### Server Log

https://mcpaste.io/463266478cd48707

**Comment by GC-spigot** [comment]
Fixed
