### ISSUE TITLE
[Issue] AE enchant problem with WildStacker

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#2475]
### Describe the bug

In AdvancedEnchantment, there is Inquisitive enchant that gets extra xp from killing mobs. But when using WildStacker, i am not getting exp or getting extra xp. But strange one is: I used other stacking plugin, it works correctly like getting extra xp and not losing xp. So i thought it was either AE or WildStacker's issue.

### How to reproduce

Reproduce will be in video.

### Screenshots / Videos

Here's the video and extra information on description:
https://youtu.be/lhEBL3AEM2g

This is the different plugin without WildStacker that i tested on my test server. Make sure you first watched video that above.
https://youtu.be/1zturIw4YUA

WildStacker config.yml:
https://www.toptal.com/developers/hastebin/yorafoboqu.yaml

### "/ae plinfo" link

https://paste.md-5.net/hepijumola

**Comment by GC-spigot** [comment]
Seems to be working for me, on the otherhand wildstacker seems to have issues and errors on latest Minecraft version, which is what we're mainly supporting now.
