### ISSUE TITLE
[Issue] AE Slot not working properly

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#2476]
### Describe the bug

Can't put new enchant on tools/armor/weapons because it said no free slot. Don't know why, but i set ae.limit.15 on player permission but all players can't put new enchant.

Permission set: ae.limit.15 (LuckPerms)

### How to reproduce

AE config.yml: https://ghostbin.com/URROa

Server Version: 1.8.8 PaperMC

### Screenshots / Videos

https://youtu.be/nwF2B-plUOk

### "/ae plinfo" link

https://paste.md-5.net/udayahojah

### Server Log

https://ghostbin.com/Bl2HP

**Comment by GC-spigot** [comment]
Change `slots.max` to `15` as well in config.yml
