### ISSUE TITLE
FILL_OXYGEN, CANCEL_USE and MORE_DROPS are not functional

### ISSUE THREAD

**Issue by AtlasMCOfficial** [GC-spigot/AdvancedEnchantments#2477]
### Describe the bug

MORE_DROPS doesn't seem to work, regardless of number or condition.

FILL_OXYGEN does not work as intended. It seems to fully fill your bar when no amount is added, and when an amount is added, it breaks completely. For numbers smaller than 10, it completely removes all your oxygen, and for bigger numbers, it sets your oxygen to a specific level, seemingly nonsensically (ex. "100" sets your oxygen level to 4 bubbles) 

CANCEL_USE is not working with food items. For whatever reason, CANCEL_USE does not seem to work if the item whose use it is trying to cancel takes an animation to consume. We have been trying to make an enchant that stops the consumption of Golden Apples, and finally resorted to using the pre-made one, but it doesn't work. Is there an issue with it? It does seem to work with other right-clickable items (we successfully made an e-pearl one).

### How to reproduce

Simply enchant any item with the enchants above and observe how they do not work as intended.

### "/ae plinfo" link

https://paste.md-5.net/epoqisigog

**Comment by AtlasMCOfficial** [comment]
[1st Addendum]
It seems like CANCEL_USE is functional, but it can only be used once per enchant. The first argument to be added is the one that takes priority. For instance, if the enchant effect is: 
- 'CANCEL_USE:GOLDEN_APPLE'
- 'CANCEL_USE:ENCHANTED_GOLDEN_APPLE'
only the use of Golden Apples will be blocked, because Enchanted Golden Apples are the second argument in the effects list.

**Comment by GC-spigot** [comment]
Fixed everything
