### ISSUE TITLE
Stackoverflowerror could not pass event TerraformBlockBreakEvent to AdvancedEnchantments

### ISSUE THREAD

**Issue by ziggykac** [GC-spigot/AdvancedEnchantments#2478]
### Describe the bug

Hi!
My server kept chrashing and spamming thousands of lines of errors to the console. Thought the plugin might be conflicting with aureliumskills, but got told on the discord that that might not be the case and that I should report it here

Btw I temporarily disabled aureliumskills so it won't show up on /ae plinfo but this is the plugin: https://www.spigotmc.org/resources/aurelium-skills-advanced-skills-stats-abilities-and-more.81069/

### How to reproduce

I'm not 100% sure, but I think it has to do with one of the digging enchantments

### Screenshots / Videos

https://prnt.sc/1zwh33n

### "/ae plinfo" link

https://paste.md-5.net/nuxahudoba

**Comment by GC-spigot** [comment]
Should be fixed in next update
