### ISSUE TITLE
Can't give glowing enchantment with /ae give

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2479]
### Describe the bug

The Glowing enchant (one of the default custom enchants) doesn't work with /ae give command because it overlaps with the glowing parameter (that takes true or false).

### How to reproduce

/aegive {player} diamond_helmet 1 glowing:1

### "/ae plinfo" link

https://paste.md-5.net/hetotiyama

**Comment by GC-spigot** [comment]
Will have to rename the enchant unfortunately, as replied on discord
