### ISSUE TITLE
Could not pass event PrepareAnvilEvent

### ISSUE THREAD

**Issue by Bronzwar** [GC-spigot/AdvancedEnchantments#2480]
### Describe the bug

I just stood on the spawn and edited the plugin for the dtltrades store

### How to reproduce

I have clicked on buttons in the DTLtrades plugin

### "/ae plinfo" link

https://paste.md-5.net/eneqomiteb

### Server Log

https://paste.helpch.at/sasifonije.md

I tested this on two Froks 
https://paste.helpch.at/sukucicoje.cs
https://paste.helpch.at/utaxixivur.sql
And different versions of AE as you can seep

**Comment by GC-spigot** [comment]
Fixed
