### ISSUE TITLE
[SUGGEST] enchantLimitation with multiple lores/nbt

### ISSUE THREAD

**Issue by SliderKP** [GC-spigot/AdvancedEnchantments#2481]
### Describe the bug

hi, for first, AdvancedEnchantments its amazing, but in my case i really need a way to add more lores to enchantlimitation.

for example:
enchantLimitation:
  enabled: true
  lore: '&c&lSecret', '&eNot Enchantable', '&4Prohibido'
  
  i think is a simple feature you can add and give a lot of possibilities for owners, in my case i need to use to prevent enchant of some old items enchanted with a old plugin, just i cant remove the items with old enchants to my users but i dont want combinating of old plugin enchants and AE enchants.

### How to reproduce

srry for my bad english im from argentina, have a nice day.

### "/ae plinfo" link

www.google.com

**Comment by GC-spigot** [comment]
```# Enchantments limitation
# If an item contains the specified lore, or the specified NBT tag, custom enchants
# will not be able to be applied.
enchantLimitation:
  enabled: true
  lore: "&c&lUnmodifiable"
  NBT-tag: "unmodifiable"```
Add `&c&lUnmodifiable` to lore

**Comment by SliderKP** [comment]
> ```
> # If an item contains the specified lore, or the specified NBT tag, custom enchants
> # will not be able to be applied.
> enchantLimitation:
>   enabled: true
>   lore: "&c&lUnmodifiable"
>   NBT-tag: "unmodifiable"```
> Add `&c&lUnmodifiable` to lore
> ```

srry for my ignorance but for example i can do this? example:

enchantLimitation:
  enabled: true
  lore: `&c&lUnmodifiable``&3Blocked``&5Disabled`
  
  its possible? this i want to question in this github issue
