### ISSUE TITLE
Interrupt CE - Applying Mining Fatigue

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2482]
### Describe the bug

Interrupt CE applies mining fatigue to player when used

### How to reproduce

Add Interrupt to a sword, use it on a mob.

### Screenshots / Videos

https://streamable.com/3p9glu

### "/ae plinfo" link

https://paste.md-5.net/ubasemuxut

**Comment by itslukemango** [comment]
It applies mining fatigue to the person using the CE, not the person hit by it. Changed %attacker% to %enemy% in enchantments and testing to see if that fixes it

**Comment by GC-spigot** [comment]
Fixed by changing to `%victim%` - changed in default starting next update
