### ISSUE TITLE
BUG ENCHANT WINGS

### ISSUE THREAD

**Issue by hironasi0165** [GC-spigot/AdvancedEnchantments#2483]
### Describe the bug

Hi author, i see one bug - enchant Wings.
I recently discovered a bug about enchant Wings. Players when wearing that star open inventory, just click on any number 1-9, they will be able to fly the bug forever.

### How to reproduce

Error console: https://pastebin.com/yL3rPrXT 

### Screenshots / Videos

Clip: https://youtu.be/EzaEL0SEWHI

### "/ae plinfo" link

/ae plinfo skipPlugins

### Server Log

https://pastebin.com/yL3rPrXT

**Comment by GC-spigot** [comment]
Fixed
