### ISSUE TITLE
Crossbow enchants do not work

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2484]
### Describe the bug

There are multiple issues open for crossbow enchants just not working. It has been over 2 months with them not working it's getting pretty annoying now so I am just bumping with another post :)

### How to reproduce

Put enchants on a crossbow

### "/ae plinfo" link

https://paste.md-5.net/xuvotohaqo

**Comment by GC-spigot** [comment]
Fixed
