### ISSUE TITLE
PASSIVE_DEATH isn't working correctly

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#2485]
### Describe the bug

Unable to get "PASSIVE_DEATH" to work with the Soulbound enchant (default)

 type: "DEATH;PASSIVE_DEATH"
  group: "FABLED"
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - "KEEP_ON_DEATH"

### How to reproduce

I died by drowning, jumping in lava, and falling to my death. Wore armor with the enchant and had one on my hand as held. 
I know at one point PASSIVE_DEATH did work on these. 

### "/ae plinfo" link

https://paste.md-5.net/tunoyugece

**Comment by GC-spigot** [comment]
Fixed
