### ISSUE TITLE
AdvancedEntityDeathEvent

### ISSUE THREAD

**Issue by Ghosflot** [GC-spigot/AdvancedEnchantments#2486]
### Describe the bug

This keeps spamming in my console even tho I already updated the plugin

### How to reproduce

Just kill a mob and it happens

### Screenshots / Videos

https://pastebin.com/xBF1iEZU

### "/ae plinfo" link

https://pastebin.com/xBF1iEZU

### Server Log

https://pastebin.com/xBF1iEZU

**Comment by GC-spigot** [comment]
Wrong github
