### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Bronzwar** [GC-spigot/AdvancedEnchantments#2487]
### Describe the bug

After update and start my server i got it https://paste.helpch.at/ligusosuja.md

### How to reproduce

just update and start server 

### "/ae plinfo" link

https://paste.helpch.at/unugofadax.sql

### Server Log

https://paste.helpch.at/woxusekaci.md

**Comment by Bronzwar** [comment]
https://paste.helpch.at/abahokecar.md

AdvancedEnchantments v8.7.12 work without any issue

**Comment by Bronzwar** [comment]
latest version https://paste.helpch.at/bijimeyoke.md (error) 
version 8.7.12 https://paste.helpch.at/omoyerubij.md

**Comment by GC-spigot** [comment]
Fixed
