### ISSUE TITLE
CUSTOM_TRENCH mechanic not working as intended

### ISSUE THREAD

**Issue by Pure376** [GC-spigot/AdvancedEnchantments#2488]
### Describe the bug

The CUSTOM_TRENCH:3:3:3 doesn't seem to be working as intended. 
3:3:2 and 3:3:1 works as intended but 3:3:3 carves a 3x3x2 into stone as if it were 3:3:2

### How to reproduce

This is my enchants config and it is listed under the "Blast" enchant: https://pastebin.com/SKB5LTvF
This can be tested by testing a Blast I and Blast II pickaxe on stone, then a Blast III pickaxe seeing it will have the same results of the Blast II pickaxe.

### "/ae plinfo" link

https://paste.md-5.net/enodinesev

**Comment by GC-spigot** [comment]
Trench counts broken block as middle of the area, so if you break the block, it will break blocks behind (near you) as well, increase by 1 to where you want blocks to be broken, and it will act as intended
