### ISSUE TITLE
8.7.13 disables without a reason?

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2489]
### Describe the bug

For some reason this plugin disables without a reason..?

[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/7611743/latest.log)

### How to reproduce

See above

### "/ae plinfo" link

Can not grab this for this issue.

### Server Log

https://mcpaste.io/0fa3c27faef38afe

**Comment by GC-spigot** [comment]
Should be fixed, try latest version
