### ISSUE TITLE
Enchantment Orbs are weird if you set the max enchants lower then 9

### ISSUE THREAD

**Issue by Moosebobby** [GC-spigot/AdvancedEnchantments#2490]
### Describe the bug

The orb lore is super wonky and doesnt make sense. 

### How to reproduce

Just change the max enchants to lower then 9. Mine is 4 for example. 

### Screenshots / Videos

https://gyazo.com/f537e76d9111a5b2bf297895fdbc3eb4

### "/ae plinfo" link

https://paste.md-5.net/ojimixumif

**Comment by GC-spigot** [comment]
Fixed
