### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2492]
### Describe the bug

Launching AE commands give error

### How to reproduce

launch an AE command

### Screenshots / Videos

https://pastebin.com/H3kKCLqV

### "/ae plinfo" link

cant even do /ae plinfo since its an AE command, it gives the error above.

### Server Log

https://mcpaste.io/13154e56924bec30

**Comment by GC-spigot** [comment]
Fixed in latest version
