### ISSUE TITLE
Pumpkin effect using the wrong block

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#2493]
### Describe the bug

The Pumpkin effect should replace the current helmet with a carved pumpkin for some time. 
(As stated on the effects list).

Its placing a regular pumpkin instead of a carved pumpkin. 

MC 1.17.1

### How to reproduce

- "PUMPKIN:60 %victim%"

### "/ae plinfo" link

https://paste.md-5.net/isocojoler

**Comment by GC-spigot** [comment]
Fixed
