### ISSUE TITLE
You can equip armour even though you already have armour equpped at that slot

### ISSUE THREAD

**Issue by ziggykac** [GC-spigot/AdvancedEnchantments#2494]
### Describe the bug

You can equip armour even though you already have armour equpped at that slot, swapping them like on bedrock, and this doesn't take into account curse of binding

### How to reproduce

1. Equip armour with curse of binding
2. Hold another armour piece
3. Right click (with inventory closed)

### "/ae plinfo" link

https://paste.md-5.net/yawikasase

**Comment by GC-spigot** [comment]
Can you record a video or a gif showing how this works? Thanks

**Comment by GC-spigot** [comment]
Nvm - fixed
