### ISSUE TITLE
Config.yml changes does not work

### ISSUE THREAD

**Issue by Jozo7** [GC-spigot/AdvancedEnchantments#2495]
### Describe the bug

When i try to change the config.yml file, and i reload the plugin or restart the server, it doesn't change the stuff, that i've changed in the plugin. Sometimes it even resetted my entire config.yml!

### How to reproduce

When i try to change the config.yml file, and i reload the plugin or restart the server, it doesn't change the stuff, that i've changed in the plugin. Sometimes it even resetted my entire config.yml!

### Screenshots / Videos

Here you can see that im changing the message in config.yml 
https://gyazo.com/3200008373b5f5d68958868ee9ab3da6

Here you can see it doesn't show the message up, i already have restarted the server, reloaded the plugin, stopped & started the server.
https://gyazo.com/a310ee581187e4e2c82d1472d48bfbc9

### "/ae plinfo" link

https://paste.md-5.net/anoyoyekix

### Server Log

https://mcpaste.io/a42165b116bd796b

**Comment by GC-spigot** [comment]
Change language in language files, lang is no longer editable through config.yml
Check `AdvancedEnchantments/locale/en-us.yml` file
