### ISSUE TITLE
Potion effects from armour are not applied when drag + dropping to equip armour.

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2497]
### Describe the bug

When armour with static potion effect enchants are equipped by drag + dropping onto an armour slot, they do not apply the effects. They are only applying effects when they are shift + clicked or right + clicked from the toolbar. The effects are also not removed when regular left-clicking them out of the armour slot.

### How to reproduce

Drag + drop to equip a piece of armour with a potion effect enchantment.
No potion effects are applied.

### "/ae plinfo" link

https://paste.md-5.net/fuqigiloqo

**Comment by GC-spigot** [comment]
Try restarting, no clue what could be the issue - it's working for me.

**Comment by Dakotaa** [comment]
Still happening after a restart. This only began to be an issue after updating from 8.7.10 to 8.7.15

**Comment by Dakotaa** [comment]
It also seems that drag + dropping works fine in the creative inventory, just not in the survival inventory.

**Comment by Dakotaa** [comment]
This is still an issue as of the latest version.
