### ISSUE TITLE
enchantLimitation not working

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2498]
### Describe the bug

enchantLimitation:
  enabled: true
  lore: '&8v2.0'
  message: '&cDit item kan niet worden aangepast!'
  NBT-tag: unmodifiable

Using this, I want to prevent them from adding mending to our custom armor sets, however it does not seem to function.

https://gyazo.com/bd06f87dd3318a969d5a45a5d191be26

### How to reproduce

See the above message.

### "/ae plinfo" link

https://paste.md-5.net/onitaqivij

**Comment by GC-spigot** [comment]
Fixed

**Comment by Sikatsu** [comment]
Also in terms of applying mending using anvils? @GC-spigot

**Comment by Sikatsu** [comment]
This does not appear to be solved, I am still able to put mending on an item even though it contains the above lore. @GC-spigot
