### ISSUE TITLE
KEEP_ON_DEATH - issues with pvp death

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#2499]
### Describe the bug

Hello! Now that PASSIVE_DEATH works fantastically, I've noticed that DEATH is not fully functional.

Only the gear that is worn or held returns to the players inventory. Any gear that was in the inventory that was not held or worn drops to the ground. PASSIVE_DEATH returns all items, including the ones just in the inventory.

type: "DEATH;PASSIVE_DEATH"
group: "FABLED"
applies:
- ALL_ARMOR
levels:
1:
effects:
- "KEEP_ON_DEATH"

### How to reproduce

PvP kill. Kept some gear in inventory with the enchant, some gear on hand, and some equip.
Only equip and on hand return. 

type: "DEATH;PASSIVE_DEATH"
group: "FABLED"
applies:
- ALL_ARMOR
levels:
1:
effects:
- "KEEP_ON_DEATH"

### "/ae plinfo" link

https://paste.md-5.net/oracuwimeg

**Comment by MamboTND** [comment]
I believe thats the intended use

**Comment by Kbryst** [comment]
Its not, it should be working while in their inventory just like PASSIVE_DEATH

**Comment by MamboTND** [comment]
I see, then that would make sense.

**Comment by GC-spigot** [comment]
Fixed
