### ISSUE TITLE
NPE with /advancedenchantments givercbook playername SIMPLE 1

### ISSUE THREAD

**Issue by ishopify** [GC-spigot/AdvancedEnchantments#250]
Any ideas why this command is throwing an error? "/ae givercbook ishopify SIMPLE  1" https://hastebin.com/avuvayekek.apache Paper spigot 1.13.2 latest AE ver 5.0.6

**Comment by ishopify** [comment]
Also to confirm that is the default inside the groups.yml

**Comment by ishopify** [comment]
Tested this in regular spigot 1.13.2  - same issue

**Comment by GC-spigot** [comment]
according to that 'SIMPLE' group doesn't exist.

**Comment by ishopify** [comment]
Hey GC SIMPLE is a group that exisits - I've renamed the groups.yaml to groups.txt to allow me to upload into this ticket and attach
[groups.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/2690981/groups.txt)
