### ISSUE TITLE
EFFECT_STATIC Enchantments cause errors with AAC

### ISSUE THREAD

**Issue by Complex1t** [GC-spigot/AdvancedEnchantments#2500]
### Describe the bug

Equipping any items with an EFFECT_STATIC enchantment results in errors saying "Failed to parse effect." From a brief look it seems like it's caused by integration with AAC.

### How to reproduce

1. Obtain any armor
2. Apply an EFFECT_STATIC enchantment (Overload, Glowing, etc)
3. Error will show in chat and in the console.

### Screenshots / Videos

https://i.imgur.com/s2042ut.png

### "/ae plinfo" link

https://paste.md-5.net/aquxofezer

### Server Log

https://bin.bloom.host/kidutavolu.yaml

**Comment by GC-spigot** [comment]
AAC seems to be abandoned by it's author and we can't really fix this without author's support unfortunately
