### ISSUE TITLE
%exp% placeholder in en.us.yml file

### ISSUE THREAD

**Issue by Jozo7** [GC-spigot/AdvancedEnchantments#2503]
### Describe the bug

%exp% placeholder, 

### How to reproduce

The %exp% placeholder is not working in the locale folder > en.us.yml, u have told me in the tickets that u will fix it in the next update u probably forgot it so this ticket is just a reminder.

### Screenshots / Videos

https://gyazo.com/2c402a0f8f065f3f711e0a2a475cfff1

Here my en.us.yml file >> https://mcpaste.io/c5b3fda1ae4c8ec8

### "/ae plinfo" link

https://paste.md-5.net/bisazutafo

### Server Log

https://mcpaste.io/6d3d0bb2f3e6f0ed

**Comment by GC-spigot** [comment]
My bad! Fixed
