### ISSUE TITLE
ADD_HARM no longer working with condition

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#2505]
### Describe the bug

ADD_HARM is not adding any damage with this condition.

---------
      condition:
        - "%mob type% = ZOMBIE : %allow%"
      effects:
        - "ADD_HARM:30 %victim%"

### How to reproduce

Tested with a sword, bow, and axe. Tested with different mob types. ADD_HARM only works without the condition. This was working in version on 8.7.11.

      condition:
        - "%mob type% = ZOMBIE : %allow%"
      effects:
        - "ADD_HARM:30 %victim%"

### "/ae plinfo" link

https://paste.md-5.net/qaqaqataqo

**Comment by GC-spigot** [comment]
Fixed, it defaults to PLAYER not MOB in this case, but will be resolved for next update, easiest way to use it would be `%victim mob type%`
