### ISSUE TITLE
enchantLimitation (still able to put enchant books on custom armor/weapons)

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2506]
### Describe the bug

The update of today was suppose to solve this, however it doesn't appear to be solved. We are still able to put enchantment books on items that contain the below lore using an anvil.

enchantLimitation:
enabled: true
lore: '&8v2.0'
message: '&cDit item kan niet worden aangepast!'
NBT-tag: unmodifiable

### How to reproduce

See the above

### "/ae plinfo" link

https://paste.md-5.net/sarelurowi

**Comment by GC-spigot** [comment]
From testing it works for me, but I reworked it, should work differently now

**Comment by Sikatsu** [comment]
@GC-spigot I have tested this again on todays update and it still doesn't work. 

Please let me know if I am doing it wrong, I will attach a video:

https://we.tl/t-ydyBollrp4
