### ISSUE TITLE
Smelt effect dupe blocks (furnace enchantment) | DUPE BUG

### ISSUE THREAD

**Issue by ArefyNetwork** [GC-spigot/AdvancedEnchantments#2507]
### Describe the bug

Smelt effect (furnace enchantment) dupes any type of block 

### How to reproduce

Breaking a block multiple times until the blocks get duped (with a pickaxe and furnace enchantment)

### Screenshots / Videos

https://www.youtube.com/watch?v=A9e48sq--JI

### "/ae plinfo" link

https://paste.md-5.net/weqotibosi

### Server Log

No need of logs for that bug, anyway if you need it tell me on discord xNekio#9001 please

**Comment by GC-spigot** [comment]
Can't recreate. It's likely to be another plugin conflicting, but just for the sake of it, would be good to know what combinations of enchants are on that item.
