### ISSUE TITLE
Gkits without custom enchantments no longer work

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2508]
### Describe the bug

GKits that have no advanced enchantments no longer work, they now cause a NPE when giving the kit.

### How to reproduce

Create a gkit with an item that does not have any advanced enchantments.
Give yourself that kit.
Internal error occurs, kit is not given.

### "/ae plinfo" link

https://paste.md-5.net/amuyoxirom

### Server Log

https://mcpaste.io/16308b908cbd982e

**Comment by GC-spigot** [comment]
Fixed
