### ISSUE TITLE
PARTICLE + <aoe> not working on more than 1 mob

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#2509]
### Describe the bug

Particles are only applying to 1 mob, the nearest to the player.

### How to reproduce

Using the following DOES NOT work:

 type: 'REPEATING'
```
        - 'PARTICLE:SNEEZE:8:0.5 <aoe> radius=9 target=mobs </aoe>'
```

### Screenshots / Videos

![Screenshot_10](https://user-images.githubusercontent.com/77632389/144143917-94f0161e-09f8-49ac-be4f-61646b64b64c.png)

### "/ae plinfo" link

https://paste.md-5.net/asoyaronez

**Comment by GC-spigot** [comment]
Fixed
