### ISSUE TITLE
AE disabled

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2510]
### Describe the bug

Suddenly, AE is disabled in every version I use, it worked earlier, but ever since i downloaded latest version, it just gives this weird error error whenever i run commands, the commands show up in tablist though.

### How to reproduce

newest version

### Screenshots / Videos

https://pastebin.com/QMs7bfPp

### "/ae plinfo" link

cannot execute command

### Server Log

https://mcpaste.io/38e99a14be79deac

**Comment by GC-spigot** [comment]
This is due to license issues, open a ticket on Discord and we'll help you.
