### ISSUE TITLE
Issue with reforged enchant adding NBT tags

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2513]
### Describe the bug

By using the Reforged enchant on a bow or a crossbow in the offhand, the item in your main hand will get an NBT tag. This causes certain items that will be affected by this, not to be able to stack anymore.

This is how the enchant is setup: https://pastebin.com/uRWdaG81

### How to reproduce

By using the Reforged enchant on a bow or a crossbow in the offhand, the item in your main hand will get an NBT tag. This causes certain items that will be affected by this, not to be able to stack anymore.

### "/ae plinfo" link

https://paste.md-5.net/uheqipiwol

**Comment by GC-spigot** [comment]
Fixed
