### ISSUE TITLE
Enchants won't apply to items

### ISSUE THREAD

**Issue by owensto** [GC-spigot/AdvancedEnchantments#2517]
### Describe the bug

Enchants just won't apply to items that they're set to apply to

### How to reproduce

Per usual, place the enchantment book on respective item

### Screenshots / Videos

https://paste.gg/p/anonymous/facaaf1c39af41a1b173e520bcd3eb95

### "/ae plinfo" link

https://paste.md-5.net/ogebivabuy

**Comment by GC-spigot** [comment]
Please post full server log, seems like you have a plugin called "BanItem" but it's one that's not supported

**Comment by owensto** [comment]
I disabled the plugin and it was fixed. Just replaced the plugin with something that doesn't interfere instead. Thank you for the help.
