### ISSUE TITLE
error upon fresh installation 

### ISSUE THREAD

**Issue by SZMYTT** [GC-spigot/AdvancedEnchantments#2518]
### Describe the bug

fresh install on paper 1.16.5 from spigot website
version : [AdvancedEnchantments] Disabling AdvancedEnchantments v8.7.18

error : https://mcpaste.io/80c57a56749559f2

### How to reproduce

i just fresh installed it. 

### "/ae plinfo" link

doesnt work "interal error"

### Server Log

https://mcpaste.io/993755eff8134073

**Comment by GC-spigot** [comment]
Are you reloading the server?
