### ISSUE TITLE
Enchanting books via the enchanting table

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#2519]
### Describe the bug

Unable to pull any custom enchants when enchanting with the normal vanilla enchanting table onto books.

### How to reproduce

Using the vanilla enchanting table, enchant books.

### "/ae plinfo" link

https://paste.md-5.net/najenavadi

**Comment by GC-spigot** [comment]
Not a feature yet! Only items get custom enchants.
