### ISSUE TITLE
Group Colour Placeholder

### ISSUE THREAD

**Issue by BirminghamBoy** [GC-spigot/AdvancedEnchantments#2523]
### Describe the bug

Issue with _customcommands.yml_ enchant info. The _%color_ placeholder works fine for the _group-enchantment-inventory_ item, but does not work for the message that is send when right-clicking a book. The _%group-color_ placeholder works for the message, but not the GUI item. Asked about this in a ticket, was referred to here. 

### How to reproduce

See description of bug.

### Screenshots / Videos

https://media.discordapp.net/attachments/917392755725058068/917393398342758410/unknown.png

### "/ae plinfo" link

https://paste.md-5.net/ruqopaxire

Side note - is it possible to set items such as Black Scroll, etc to glow? I was told not, but thought I'd ask here too.

**Comment by GC-spigot** [comment]
Fixed
