### ISSUE TITLE
Telepathy Enchant doesnt work on spawners

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2524]
### Describe the bug

Telepathy enchant does not work on spawners placed by the MineableSpawners plugin (https://www.spigotmc.org/resources/mineablespawners-1-8-1-18-silkspawners-alternative.59921/)

When you mine spawners, they just drop and do not go into your inventory (silk touch pick with telepathy enchant)

### How to reproduce

Place spawners from the mineable spawners plugin and mine them with a telepathy silk touch pick

### "/ae plinfo" link

https://paste.md-5.net/gihuvowuva

**Comment by GC-spigot** [comment]
It's not really supported and we do not have plans on supporting it - seems like it's not well supported by the developer
