### ISSUE TITLE
Spigot 1.18 is not working

### ISSUE THREAD

**Issue by YourKyckling** [GC-spigot/AdvancedEnchantments#2525]
### Describe the bug

As of December 8th, 2021 the spigot update 8.7.20 is not working, when downloaded the .jar file is just an exact copy of the previous version rendering the plugin unusable. Nothing works with the plugin.

### How to reproduce

Download it from spigot.

### Screenshots / Videos

none, no need.

### "/ae plinfo" link

Doesn't work.

**Comment by GC-spigot** [comment]
And that is why it's so important to include some information with reports. Plugin works fine on 1.18 - https://prnt.sc/22ai30k
Going to close this ticket, try next update. If still doesn't work open a ticket including startup logs.
