### ISSUE TITLE
''DISABLE_ACTIVATION:DIVINEIMMOLATION:5 %attacker% - Not working in Armorsets

### ISSUE THREAD

**Issue by Jozo7** [GC-spigot/AdvancedEnchantments#2526]
### Describe the bug

Hi, the disable_enchantment effect on armorsets ain't working.
Tested multiple times, with different enchantments but not working.
  DEFENSE:
    chance: 100
    effects:
      - 'DISABLE_ACTIVATION:DIVINEIMMOLATION:5 %attacker%

### How to reproduce

See description just copy & paste it in your config and didn't worked.

### Screenshots / Videos

Nothing

### "/ae plinfo" link

https://paste.md-5.net/aridoremuj

**Comment by GC-spigot** [comment]
Replied to your other issue
