### ISSUE TITLE
Item Dupe BUG

### ISSUE THREAD

**Issue by tanertekin0** [GC-spigot/AdvancedEnchantments#2527]
### Describe the bug

When I right-click on the item in his hand, it both wears it on me and stays in the inventory. It gets fixed when I delete the advancedenchaments plugin

### How to reproduce

when you right click on the item and wear it

### Screenshots / Videos

https://user-images.githubusercontent.com/66686400/145210000-0ffd73e4-2c09-48bf-b146-62e91477c77f.mp4

### "/ae plinfo" link

https://paste.md-5.net/wohebirosa

### Server Log

https://mcpaste.io/84ca5544f31e4810

**Comment by GC-spigot** [comment]
This happens when there's 2 plugins for switching armor, e.g. a factions plugin. Disable armor switching in other plugin.

**Comment by tanertekin0** [comment]
thank you ^^
