### ISSUE TITLE
ASets Armor Full set bonus bug

### ISSUE THREAD

**Issue by Amenosda** [GC-spigot/AdvancedEnchantments#2528]
### Describe the bug

**- you can cheat full set bonus

### How to reproduce

1. /asets give [Player] [Armor]
2. /gamemode survival
3. when switching armor in survival mode, the fullset bonus stays (no shift)

### Screenshots / Videos

![ffff](https://user-images.githubusercontent.com/95755991/145213341-91a1932d-c38f-4952-b039-171aa2c84f0d.PNG)

### "/ae plinfo" link

https://paste.md-5.net/ilatacunes

### Server Log

https://mcpaste.io/c02447514349be48

**Comment by GC-spigot** [comment]
Again, likely other plugin colliding/skript. Proof that it works: https://gyazo.com/29aed76b737fd290e09a2c14329cc0f3
