### ISSUE TITLE
Timber Enchant 

### ISSUE THREAD

**Issue by Amenosda** [GC-spigot/AdvancedEnchantments#2529]
### Describe the bug

- cooldown not working

### How to reproduce

/ae enchant Timber 1

### "/ae plinfo" link

https://paste.md-5.net/qayeyumoxi

### Server Log

https://mcpaste.io/c02447514349be48

**Comment by GC-spigot** [comment]
From my testing it does, might be other plugins colliding/skripts. Do any other enchants have this issue?

**Comment by Amenosda** [comment]
I noticed that all enchants have such a problem

**Comment by Amenosda** [comment]
"might be other plugins colliding/skripts" 
just a question what plugin can it be :((

**Comment by GC-spigot** [comment]
Try removing plugins by a few at a time until this is fixed, then you'll figure it out.
