### ISSUE TITLE
Default detonate enchantment issue

### ISSUE THREAD

**Issue by oyasumiiipunpun** [GC-spigot/AdvancedEnchantments#253]
when using Detonate and Atomic Detonate the amount of current amount of blocks is not dropping. It only drops the one block that you mined and not the full 3x3 and 7x7 area.

running paperspigot-475 1.13.2.

the enchantment: https://pastebin.com/SyLE0e9q

**Comment by oyasumiiipunpun** [comment]
atomic detonate enchantment: https://pastebin.com/uDj29dU1

**Comment by Blazingshadow17** [comment]
I think he means trench.

**Comment by GC-spigot** [comment]
It's an issue with worldguard.
