### ISSUE TITLE
Trench Broken(as in OP af)

### ISSUE THREAD

**Issue by Zoro-6191** [GC-spigot/AdvancedEnchantments#2530]
### Describe the bug

My friend showed this bug in our server, where he would place a 3x3 obsidian on ground which would take usual time to break but will still mine 3x3 area(first op thing as I assumed trench works only in stone or netherrack etc), but when placed any other block over center of that 3x3 area, it would mine whole thing instantly(that pick also has hasten 2, i cant tell if thats relevant but on testing i used only trench ix)

Till this is fixed, can you quickly tell me a way i can disable just Trench

### How to reproduce

Just use trench ix in any pick( i used netherite), place 3x3 obsidian, place netherrack or smth in center block and mine it.

### Screenshots / Videos

https://user-images.githubusercontent.com/52291201/145273726-4c347911-cbb7-4455-ad53-5d413e1c3394.mp4
![trench](https://user-images.githubusercontent.com/52291201/145274163-e0b9201d-0bfc-428d-a510-b9c5474eed0a.gif)

### "/ae plinfo" link

https://paste.md-5.net/uqupixubey

**Comment by Zoro-6191** [comment]
this one in survival,
![trench](https://user-images.githubusercontent.com/52291201/145274346-4b0cc060-a42f-4c16-88d7-17c895da887a.gif)

**Comment by GC-spigot** [comment]
If you want this changed, just add Obsidian to trench blacklist in bottom of config.yml, There's nothing else we can do.

**Comment by Zoro-6191** [comment]
um even if you can't help with the speed, it's clearly mining 10blocks when it shouldnt mine more than 9. Just saying.

**Comment by GC-spigot** [comment]
Mining speed is handled client sided. The pickaxe is meant to mine 3x3x3, which is 27, that means everything is behaving as supposed. Just saying.
