### ISSUE TITLE
VEIN_MINE is not give exp

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2532]
### Describe the bug

when player break ore block with VEIN_MINE, exp was not given.
Therefore, the effect of mending cannot be received.

### How to reproduce

When player break ore blocks with VEIN_MINE pickaxe, give exp to player.

### "/ae plinfo" link

https://paste.md-5.net/icexahuvuc

**Comment by GC-spigot** [comment]
Fixed
