### ISSUE TITLE
Issue with banner patterns

### ISSUE THREAD

**Issue by BirminghamBoy** [GC-spigot/AdvancedEnchantments#2533]
### Describe the bug

Hopefully last minor bug I report - I'm trying to use the banner pattern item for my scroll as I prefer the texture, however this seems to break the plugin. From the error message, the plugin thinks I'm wanting a "WHITE_SKULL_BANNER_PATTERN", despite me just putting in "SKULL_BANNER_PATTERN". I've tried removing the numerical item data, as well as using just "BANNER_PATTERN", neither of which fix the issue.

### How to reproduce

See above ^

### Screenshots / Videos

https://media.discordapp.net/attachments/801769353090433030/918849573764595762/unknown.png

### "/ae plinfo" link

https://paste.md-5.net/akakahopot

### Server Log

https://www.toptal.com/developers/hastebin/lifokebute.yaml

**Comment by GC-spigot** [comment]
Fixed
