### ISSUE TITLE
Upgrading a set to Heroic

### ISSUE THREAD

**Issue by Jozo7** [GC-spigot/AdvancedEnchantments#2535]
### Describe the bug

When i apply an heroic set upgrade, on a armor piece, it will show-up like this:
https://gyazo.com/9507922d91758ecc469410190556ae79

### How to reproduce

If i run this command /asets giveheroicupgrade playername setname 100 1,
and apply it on a set it will show-up like this; 
https://gyazo.com/9507922d91758ecc469410190556ae79

### Screenshots / Videos

https://gyazo.com/9507922d91758ecc469410190556ae79

### "/ae plinfo" link

https://paste.md-5.net/sefejeyido

### Server Log

https://mcpaste.io/e1703754bb2b2023

**Comment by Jozo7** [comment]
And if it works, just kill yourself on a alt on minecraft, and it will be shown like this
https://gyazo.com/9507922d91758ecc469410190556ae79

**Comment by GC-spigot** [comment]
This is caused by your texturepack
