### ISSUE TITLE
Auto smelt not working with Fortune

### ISSUE THREAD

**Issue by bipedd** [GC-spigot/AdvancedEnchantments#2536]
### Describe the bug

Auto smelt does not work with the vanilla enchant fortune but it should. Works as fortune is not applied.

### How to reproduce

Place 6 blocks of say gold ore, break them all with a pickaxe with auto smelt as well as fortune and you will get 6 gold ingots, tested multiple times and always got 6.

### "/ae plinfo" link

https://paste.md-5.net/igemayaqih

### Server Log

https://mcpaste.io/4960d2eea21e6481

**Comment by Blazaddo** [comment]
I am also having this bug.

**Comment by GC-spigot** [comment]
Fixed
