### ISSUE TITLE
EnchantLimitation showing 3 messages

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2538]
### Describe the bug

The EnchantLimitation feature shows 3 times the message ''You can not change this item!''

![image](https://user-images.githubusercontent.com/5664135/145712179-16a4b3ef-14a7-42ee-9c7b-1f2ad4e92e8d.png)

### How to reproduce

I think this one is clear haha

### "/ae plinfo" link

https://paste.md-5.net/rotecerizi

**Comment by GC-spigot** [comment]
Fixed
