### ISSUE TITLE
Set static effects disappearing

### ISSUE THREAD

**Issue by Stinlot** [GC-spigot/AdvancedEnchantments#2540]
### Describe the bug

Hi,

I have a set which give static regen 1 effect

When players eat a non enchant golden apple, it gives them regen 2 for few seconds (normal behaviour)

Then the static regen I effect doesn't come back after the golden apple one disappears

### How to reproduce

Put a set which give static regen effect

Eat a non enchant golden apple

Wait until the end of the golden apple effect (few seconds) static set effet doesn't come back

### "/ae plinfo" link

https://paste.md-5.net/yepimosodi

**Comment by GC-spigot** [comment]
I can't recreate this - permanent effect still stays
