### ISSUE TITLE
Effect (TELEPORT_BEHIND) on BOW type still triggers into a (STOP_ATTACK) on DEFENSE_BOW on armor 

### ISSUE THREAD

**Issue by Stinlot** [GC-spigot/AdvancedEnchantments#2541]
### Describe the bug

I have some boots with a 100% chance STOP_ATTACK effect with a DEFENSE_BOW type (arrowdeflect)
Whenever I equip thoses boots, I indeed don't take any damage from arrows (event seems cancelled) 

I also have a bow which teleports players when hitting them (TELEPORT_BEHIND effect) with the BOW type

The problem is, even when the event is cancelled and I don't get damage from arrows, the TELEPORT_BEHIND effect still triggers.
Note: TELEPORT_BEHIND effect works well when event is cancelled with worlguard rg, factions friendly fire... but seems like when it is cancelled with an other AE effets, it doesn't work anymore.

### How to reproduce

Put arrowdeflect on a piece of armor

Put teleport behind effect on a bow

Shoot with the bow, even though the damage is cancelled, teleport still happens

### "/ae plinfo" link

https://paste.md-5.net/yepimosodi

**Comment by GC-spigot** [comment]
Can you share the enchantment?

**Comment by Firosee** [comment]
@Stinlot
