### ISSUE TITLE
DOUBLE_DAMAGE doesn't work

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#2542]
### Describe the bug

ATTACK or ATTACK_MOB with DOUBLE_DAMAGE doesn't double or increase any damage.

### How to reproduce

criticalstrike:
  display: '&7Critical Strike%group-color% ■'
  description: "&e10% &8chance to deal twice the damage on melee attacks."
  applies-to: "Axe/Sword"
  type: 'ATTACK;ATTACK_MOB'
  group: 'SIMPLE'
  applies:
    - ALL_AXE
    - ALL_SWORD
    - TRIDENT
  levels:
    1:
      chance: 100
      effects:
        - 'DOUBLE_DAMAGE %attacker%'

### "/ae plinfo" link

https://paste.md-5.net/asoyaronez

**Comment by GC-spigot** [comment]
Fixed
