### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Thefluffypvper1** [GC-spigot/AdvancedEnchantments#2544]
### Describe the bug

I am not sure how it happen just saw it in console

### How to reproduce

Not sure

### Screenshots / Videos
https://mcpaste.io/8080b6169a8be858
https://paste.helpch.at/nasedocebe.js

### "/ae plinfo" link

https://paste.md-5.net/wexuqoxihe

### Server Log

No

**Comment by GC-spigot** [comment]
Fixed
