### ISSUE TITLE
Using /aegive to give an item with a custom enchant results in a warning and sometimes error

### ISSUE THREAD

**Issue by baailey** [GC-spigot/AdvancedEnchantments#2547]
### Describe the bug

When using /aegive to give an item that can have both a vanilla and a custom enchant, it gives the item with the enchant but prints `WARN [AdvancedEnchantments] Invalid vanilla enchantment: waterwalker. Enchantment names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html` in console. If you try using the item with the 'invalid' custom enchant, it then spams errors in console and does not resolve until a server restart.

### How to reproduce

1. Do /aegive baailey diamond_boots 1 name:&btest protection:6 unbreaking:5 depth_strider:4 mending:1 waterwalker:1
2. Look in console
3. If you wish to see the error, equip the boots and try walk on water.

### "/ae plinfo" link

https://paste.md-5.net/anarurocac

### Server Log

https://pastebin.com/3r7jbbjA

**Comment by GC-spigot** [comment]
Resolved
