### ISSUE TITLE
detonate will not drop all of the blocks

### ISSUE THREAD

**Issue by enkrona3052** [GC-spigot/AdvancedEnchantments#255]
The detonate enchantment will not drop any of the blocks only 1 that you break. my players are wondering if theres a way to fix this or make it so it will get all the blocks to break and be on the ground.

**Comment by Stager83** [comment]
Yep I found the same issue :)

**Comment by Blazingshadow17** [comment]
Yeah, I would love all the block dropped plz!

**Comment by Stager83** [comment]
My players have requested it as well.
