### ISSUE TITLE
repeat type bug 

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2550]
### Describe the bug

공복:
  display: "%group-color%공복"
  description: "일정 시간마다\n허기를 채울 확률이 생깁니다."
  applies-to: "투구"
  type: "SPRINT"
  time: 5
  group: "에픽"
  applies:
    - ALL_HELMET
  levels:
    1:
      chance: 25
      effects:
        - "ADD_FOOD:1"
    2:
      chance: 45
      effects:
        - "ADD_FOOD:1"
    3:
      chance: 65
      effects:
        - "ADD_FOOD:1"
    4:
      effects:
        - "ADD_FOOD:1"

this enchant is worked well, but when player combat against monster,
effect was not applied. what is the problems?
is 'repeat' type has bug?
(when player re-equiped armor or reconnect server, effect was worked again) 
this problems has occur with aoe. (repeat type - aoe)

### How to reproduce

can you check repeat type and aoe?

### "/ae plinfo" link

https://paste.md-5.net/ineteravip

**Comment by GC-spigot** [comment]
Change type to `REPEATING`
