### ISSUE TITLE
Your license exceeded maximum number of unique IPs

### ISSUE THREAD

**Issue by CubicCubeCubed** [GC-spigot/AdvancedEnchantments#2551]
### Describe the bug

My boyfriend and I have been attempted to rebuild our server and have been using AdvancedEnchantments, but suddenly we are getting this error code: " [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs." Not sure why, hopefully someone can help.

My boyfriend purchased AdvancedEnchantments on spigotMC.org under the name LividRedstone, if that info is needed.

### How to reproduce

Randomly began happening

### "/ae plinfo" link

N/A

**Comment by ProfessionalBoatDrifter** [comment]
If you haven't already, try opening a support ticket on their Discord: https://discord.gg/GzdQdMw
Considering the holidays it might take a bit longer to have your license IPs reset.
