### ISSUE TITLE
Hellfire enchant not following worldguard

### ISSUE THREAD

**Issue by bipedd** [GC-spigot/AdvancedEnchantments#2552]
### Describe the bug

The hellfire enchant is breaking blocks in an area protected by a worldguard. Not sure why, I tested this on my Skyblock server and the worldguard settings are exactly the same for the region.

### How to reproduce

Create a worldguard area, allow pvp, hit another player with a bow with the enchant hellfire.

### Screenshots / Videos

https://user-images.githubusercontent.com/77213949/147161560-73049f9a-b8cc-4c98-a5a1-aec2c7d3ace7.mp4

### "/ae plinfo" link

https://paste.md-5.net/olofeleyer

### Server Log

https://mcpaste.io/57df7b0dcadb0fda

**Comment by bipedd** [comment]
Sorry for the short video, wasn't able to post a longer one.

**Comment by GC-spigot** [comment]
Deny ghast fireballs with WG flags
