### ISSUE TITLE
Distance enchant causes false positives with Vulcan Anti-Cheat

### ISSUE THREAD

**Issue by bipedd** [GC-spigot/AdvancedEnchantments#2553]
### Describe the bug

The enchantment Distance causes my anti-cheat (Vulcan) to trigger the motion (TYPE: G) and jump (TYPE: B) checks. I was told to report this here by a support member who also said that the easiest way to fix this is to cancel flags for those checks right after the plugin uses an ability like that.

### How to reproduce

Install vulcan anti-cheat on your server.
Get an axe with the distance enchant applied to it.
Fight another player until distance throws one of you in the air.
False positives will appear.

### Screenshots / Videos

https://user-images.githubusercontent.com/77213949/147165660-313107ea-9034-4d54-b6b4-9814627dc1ee.mp4

### "/ae plinfo" link

https://paste.md-5.net/iqemepegab

### Server Log

https://mcpaste.io/b46fdd647e2ee5a4

**Comment by GC-spigot** [comment]
Fixed
