### ISSUE TITLE
'SHIFT' type bugs

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2554]
### Describe the bug

 ![2021-12-23_22 24 37](https://user-images.githubusercontent.com/25452835/147256129-2bbc556c-aec3-471b-915c-2eaf550ca3b0.png)

If player hold anti-gravity shoes in your hand, player will get a slow drop,
but if player change the inventory window to something other than your shoes while using a slow drop,
player get an infinite bug of slow drops.

안티그래비티:
 display: "%group-color%안티 그래비티"
  description: "낙하 중 웅크리기를 하면\n느린 낙하를 할 수 있게 됩니다."
  applies-to: "부츠"
  type: "SHIFT"
  group: "에픽"
  applies:
    - ALL_BOOTS
  levels:
    1:
      effects:
        - "POTION:SLOW_FALLING:0:20"

### How to reproduce

can you reproduce turn it off when player switching other tools?

### "/ae plinfo" link

https://paste.md-5.net/efuharumiw

**Comment by GC-spigot** [comment]
Fixed
