### ISSUE TITLE
Enchants Activate through Shield Block

### ISSUE THREAD

**Issue by Blazaddo** [GC-spigot/AdvancedEnchantments#2555]
### Describe the bug

When a player is blocking with a shied and successfully blocks the attack, the enchant still goes off. For example, if you had a poison enchant and someone block it with a shield, they would block the attack damage but still be poisoned.

### How to reproduce

Use a poison enchant and attack someone blocking with a shield, and they will be poisoned

### "/ae plinfo" link

https://paste.md-5.net/eqevisetem

**Comment by GC-spigot** [comment]
Fixed
