### ISSUE TITLE
INCREASE_DAMAGE and EXTRA_DAMAGE don't work properly

### ISSUE THREAD

**Issue by Blazaddo** [GC-spigot/AdvancedEnchantments#2556]
### Describe the bug

INCREASE_DAMAGE and EXTRA_DAMAGE do nothing unless their values are set extremely high (above 100% (1) for increase damage, I have tested for extra damage). Unless that condition is meant it seems to do no extra damage.

### How to reproduce

The enchants I'm using:
https://pastebin.com/Ap0Zare4

### "/ae plinfo" link

https://paste.md-5.net/eqevisetem

**Comment by GC-spigot** [comment]
Should be resolved
