### ISSUE TITLE
Unbreakable not working with dispensers

### ISSUE THREAD

**Issue by dro1d-89o** [GC-spigot/AdvancedEnchantments#2557]
### Describe the bug

Unbreakable enchant does not seem to work in items when they are used by dispensers.

### How to reproduce

Put the unbreakable enchant on shears, put the enchanted shears into a dispenser, durability will still go down on the shears

### "/ae plinfo" link

https://paste.md-5.net/moqicosune

**Comment by GC-spigot** [comment]
It won't work like that unfortunately, enchants only work if they are interacted by entities (players or mobs)
