### ISSUE TITLE
Some items / Scrolls not applying to items.

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#256]
Lately it seems that when I try to click some items (for example white and black scrolls) onto an item such as a diamond sword, the item does not apply and is simply switched around with the item in your inventory (like vanilla behaviour). It's kinda wierd I know.

I use the latest AdvancedEnchantments version with default config. Only the sounds in configs were edited to suit 1.13.

I use paperspigot 1.13.2

If you need a link ill happily give one to you.

Thanks in advance! You seem like a really nice dev.

**Comment by GC-spigot** [comment]
Go to survival mode rather than creative, will work then.

**Comment by Leomelonseeds** [comment]
Tried survival, doesn't work. Players have been complaining for days.
