### ISSUE TITLE
Veinminer does not work with fortune enchant

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2564]
### Describe the bug

It appears the veinminer enchant does not work with the vanilla fortune enchant. Is this intended?

### How to reproduce

Use both enchants together and you'll see it doesn't currently function.

### "/ae plinfo" link

https://paste.md-5.net/xayekuhuvi

**Comment by GC-spigot** [comment]
Seems to be fixed

**Comment by Sikatsu** [comment]
Not on my end, unless you meant the next update.
