### ISSUE TITLE
Bug with NachoSpogot

### ISSUE THREAD

**Issue by boristran03** [GC-spigot/AdvancedEnchantments#2567]
### Describe the bug

I got this error when i start my server

### How to reproduce

Can't preproduce

### "/ae plinfo" link

NachoSpigot 1.8.8

### Server Log

https://mcpaste.io/050a1695e0322fc0

**Comment by boristran03** [comment]
pls take a look at this issue, I've been waiting for an answer for days

**Comment by GC-spigot** [comment]
Fixed
