### ISSUE TITLE
Fortune with Enchant Telepathy and Smelting

### ISSUE THREAD

**Issue by Amenosda** [GC-spigot/AdvancedEnchantments#2568]
### Describe the bug

on the new version 1.17, 1.18 with a fortune drops a lot more raw gold and raw iron, and if you use these enchants fortune does not work on these ores

### How to reproduce

i take Pickaxe
/ae enchant Telepathy 4
/ae enchant Smelting 1
/enchantment fortune 10

digging gold and iron ore 

### Screenshots / Videos

(no need)

### "/ae plinfo" link

https://paste.md-5.net/qulofavunu

### Server Log

(no need)

**Comment by GC-spigot** [comment]
Fixed
