### ISSUE TITLE
Auto-Smelt dupes blocks

### ISSUE THREAD

**Issue by Jbacot** [GC-spigot/AdvancedEnchantments#2571]
### Describe the bug

When mining normal blocks with auto-smelt, it duplicates them (2x). I am not sure exactly which blocks it does and doesn't work on.
Ores seem to smelt fine but when mining non-ore blocks such as wood, it just doubles the drop.

### How to reproduce

Enchant a pickaxe to auto-smelt 3 and mine any non-ore block.

autosmelt:
  display: '%group-color%Auto Smelt'
  description: "&7Ores are automatically\n&7smelted when mined."
  applies-to: 'Pickaxes'
  type: 'MINING'
  group: 'UNCOMMON'
  applies:
    - ALL_PICKAXE
  levels:
    1:
      chance: 41
      effects:
        - 'SMELT'
    2:
      chance: 62
      effects:
        - 'SMELT'
    3:
      chance: 100
      effects:
        - 'SMELT'

### Screenshots / Videos

https://vimeo.com/manage/videos/662729218
https://ibb.co/LRJvbLH

### "/ae plinfo" link

https://paste.md-5.net/sareqogiko

**Comment by Folas1337** [comment]
Seems to not happen on a server without other plugins, I'm suspecting your stacking plugin to be having some compatibility issue. Might be useful to figure out what combination is causing it cause I doubt the devs are willing to get all the plugins you have just to narrow it down 😉 

Cheers

**Comment by GC-spigot** [comment]
^^^^ Please open a discord ticket if you figure it out
