### ISSUE TITLE
Perish enchantment is on attacker rather than victim

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#2573]
### Describe the bug

The default enchantments.yml has the perish enchantment defined to apply to the attacker which makes no sense.
Should be changed to "%victim%" instead.

### How to reproduce

Install AdvancedEnchantments
Put Perish on bow
Shoot entity

### "/ae plinfo" link

https://paste.md-5.net/vonicodona

**Comment by GC-spigot** [comment]
Default seems to be victim: https://gyazo.com/863938c5c004346bdcccc40a300ba83b 
Are you using an outdated enchantments.yml?
