### ISSUE TITLE
Reforged 5 and above = unbreakable

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#2574]
### Describe the bug

A pickaxe that is enchanted with Reforged 5 or anything above will basically be unbreakable as it "recovers" more health than it requires.

I am not sure if this is intentional or not but I didn't exactly expect that behavior.
If it's intended, it's all good and you can comment on this and close it, otherwise I'd like it to be investigated :)

### How to reproduce

- Put Reforged 5 or above on a pickaxe
- Break blocks and see how it will never go below roughly -10 durability

### "/ae plinfo" link

https://paste.md-5.net/qasofuxoci

**Comment by GC-spigot** [comment]
Fixed
