### ISSUE TITLE
Gkits

### ISSUE THREAD

**Issue by NoPantsCarl** [GC-spigot/AdvancedEnchantments#2575]
### Describe the bug

When you use Gkits such as Viking & Gladiator you get error right away in chat.
It will say things such as: Enchant blessed cannot be resolved. 
Then Axe of the Dwarvish Gods or simlar items with effects will:
Say Failed to pase effect 'ATTACK_MOB' for echant 'barbarian'
Using Papper 1.17.1

When i use item with attack mob Triger i get the console error 
https://mcpaste.io/3e4d49d9baf1627b

### How to reproduce

use /gkits
select anyone the kits and will get the error in chat for every gkit.
(Enchant 'Enchant name" cannot be resolved.)
Select any with attack trigger such as Viking and use the Axe on a mob

### Screenshots / Videos

https://gyazo.com/6f684557a4605501b0c6da39ae2697ae
https://gyazo.com/e799521f4931a74bb81c1b6cccc45e68

### "/ae plinfo" link

https://paste.md-5.net/dexikuruxa

### Server Log

https://mcpaste.io/b6d889b36ff39832

**Comment by NoPantsCarl** [comment]
If i removed Both of my AAC5 and ACC additions the error for parse effect 'ATTACK_MOB' for enchant 'barbarian' will go away.
But i still have the  ''Enchant name" cannot be resolved" every time I claim a gkit

**Comment by GC-spigot** [comment]
Error resolved
