### ISSUE TITLE
slot-increaser wrong message

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2579]
### Describe the bug

Item slot-increaser is showing a wrong message (without translation option) on applying (when max slot is reached).

### How to reproduce

1. Give slot increaser; /ae giveitem name slotincreaser 1 <any>
2. Increase the enchantments item slots up to the maximum allowed by the configuration using slot-increaser.
3. Try to apply again and see the message in chat.

![image](https://user-images.githubusercontent.com/66658478/149546330-73110fd8-b11e-450a-be60-1f21c239a20f.png)

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/66658478/149546506-5630e7df-5ec9-457c-a4c2-3141a8e4d35b.png)
There is no message option for "fail"

All my lang is translated
![image](https://user-images.githubusercontent.com/66658478/149546610-962c8c2b-98cd-4ffc-9d1f-e2aa1c60c931.png)

### "/ae plinfo" link

https://paste.md-5.net/oqumilitog.css

**Comment by GC-spigot** [comment]
Fixed
