### ISSUE TITLE
[Request] Players/Mobs/Entities in Radius

### ISSUE THREAD

**Issue by Blazingshadow17** [GC-spigot/AdvancedEnchantments#258]
Is it possible to add a condition that checks a radius around the victim/attacker, and affects mobs, players, or all entities in a radius?

Example, I want to ignite all players and mobs in a 5 block radius around me when I get hit.

Example, I want to ignite all players and mobs in a 5 block radius around me when I hit something.

Thanks! (If this can apply with potion effects etc that would be awesome).

**Comment by GC-spigot** [comment]
This is coming soon as an addon.
