### ISSUE TITLE
Plugin Crashing when server starter

### ISSUE THREAD

**Issue by pingwinek123** [GC-spigot/AdvancedEnchantments#2580]
### Describe the bug

hello i found a bug when i start my server the Advanced Enchantments plugin is not working and when i load backup from when he worked its still crashing

### How to reproduce

Starting Server

### "/ae plinfo" link

An internal error occured while attemping to perform this command

### Server Log

https://mcpaste.io/7492c24af14a42d9

**Comment by GC-spigot** [comment]
Fixed
