### ISSUE TITLE
Permenant potion effects when equipping and unequipping armor

### ISSUE THREAD

**Issue by Tejay17** [GC-spigot/AdvancedEnchantments#2581]
### Describe the bug

When the user equips and unequipped the armor fast enough the user will have the potion effect permanently. If the wearer dies the effects go away.

### How to reproduce

To reproduce the bug, the user goes into their inventory and equips and unequipped the armor as fast as they can click. After my third or fourth try I can gain a permanent regeneration effect on myself.

### Screenshots / Videos

https://youtu.be/HXjeaPlDK-U

### "/ae plinfo" link

https://paste.md-5.net/ezerayuvif

### Server Log

https://mcpaste.io/bc365a93d9c10c3f

**Comment by GC-spigot** [comment]
It may be purpur - likely is. Purpur breaks a toooooooon of plugins.
