### ISSUE TITLE
Telepathy Dupe Bug

### ISSUE THREAD

**Issue by Regerta** [GC-spigot/AdvancedEnchantments#2582]
### Describe the bug

Dupe bug when you destroy a chest with filled shuklerbox inside using a pickaxe that has telepathy enchant.

FYI, WildStacker is enabled on my server.

### How to reproduce

- Fill a shulkerbox with some items and keep that shulker in your inventory
- Place a chest and put that filled shulkerbox from your inventory into the chest
- Destroy the chest with pickaxe that has SilkTouch (Vanilla) & Telepathy (AE)
- It will drop x2 Sulker Box randomly

### "/ae plinfo" link

https://paste.md-5.net/mufehanuno

**Comment by Folas1337** [comment]
Not happening with no other plugins, I suggest narrowing down what plugin combination causes it unless you've been running with JUST AE and WildStacker but that hasn't been clarified here.

**Comment by GC-spigot** [comment]
^^^
