### ISSUE TITLE
HELD effect stops working after ~2 seconds in offhand.

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#2583]
### Describe the bug
I am on AdvancedEnchantments-8.8.1 and Spigot 1.16.5.
Currently HELD effects seem to turn off if in the off-hand after some small time. It refreshes when switching slots.
Here is one of my HELD enchants that turns off after some time:
amuletturtle:
  display: '&6Cursed Amulet: &fTurtle'
  description: "&fGain Resistance, Hunger and Slow"
  applies-to: 'Amulet'
  type: 'HELD'
  group: 'UNIQUE'
  applies:
    - RED_DYE
  levels:
    1:
      effects:
        - 'POTION:HUNGER:1'
        - 'POTION:DAMAGE_RESISTANCE:0'
        - 'POTION:SLOW:0'

### How to reproduce

Put a HELD enchant in the off-hand.(Even from inventory)
The enchant will work.
It will stop working after some time.(Usually ~2 seconds)

### Screenshots / Videos

Expected Result:
![Screenshot_2475](https://user-images.githubusercontent.com/23641964/149620515-8d821fe8-a343-4d10-8872-e4a101efaa58.png)
After some seconds:
![Screenshot_2474](https://user-images.githubusercontent.com/23641964/149620520-b7fc365f-96d2-4411-83b7-c426cc823b4d.png)

### "/ae plinfo" link

https://paste.md-5.net/iyuyegejoz

### Server Log

Is this necessary?

**Comment by GC-spigot** [comment]
Fixed
