### ISSUE TITLE
Smelting enchant issue

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2585]
### Describe the bug

There are some plugins which cancel the drops for certain blocks (creative restriction plugins cancel the drops if the block was placed in creative).

The issue here is that with the smelting enchant, the enchant doesn't listen to if the drops have been cancelled by another plugin so drop anyway. Could it be made so before the enchant does anything, it checks if the drop table is not empty before auto smelting the items

### How to reproduce

Download RestrictedCreative from spigot so blocks placed in creative mode don't drop when mined in survival. Mine with a smelting custom enchant and they still drop.

### "/ae plinfo" link

https://paste.md-5.net/ajiwepevuc

**Comment by JHarris12345** [comment]
Hello?

**Comment by JHarris12345** [comment]
This would also get fixed by dropping the items in the current drop table (and putting the listener to highest priority)

**Comment by Burchard36** [comment]
Hello there! I am one of the newer developers GC has added to the team, so i will be looking into this issue for you :) Apologies that this bug was left unattended for quite some time

I will look into this issue and test it locally on my machine right now, and see about working on a possible fix!

As for the latest comment you have made, RestrictedCreative has an API for checking if blocks were placed in creative, so I will likely add support directly for this plugin, no need to change any ListenerPriorities here

**Comment by Burchard36** [comment]
Apologies, upon further searching, I didn't see before that this plugin is a premium resource.

We will need to further look into this plugin and see whether the author will get us access to said plugin, or if we need to purchase said resource and then work upon it from there. We will keep you updated on this issue!

Please allow us 1-2 days for any type of resolution for your bug

**Comment by JHarris12345** [comment]
@Burchard36 Restricted Creative was an example plugin. There are numerous plugins without API (inlcuding my own private ones) that will cancel drops of blocks. The easiest fix would be to make the listener priority higher and then dropping the drops from that current loot table. No need to hook into anything and that makes a fix for pretty much every plugin

**Comment by Burchard36** [comment]
Closing as support for these are added

If you have issues with any of this, please feel free to contact me on discord or open a new issue referancing this one!
