### ISSUE TITLE
Nether Crash - World Populator

### ISSUE THREAD

**Issue by icenii** [GC-spigot/AdvancedEnchantments#2586]
### Describe the bug

Private Server I'm hosting for my friends crashed out of nowhere while 2 players with lava walker were exploring the nether while I was afk at the overworld.

Server is Using Paper version 1.18.1-152 and Advance Enchantment is running at version 8.8.1.
Memory Distribution: -Xmx8G -Xms6G (Out of 32 GB)
Server is running at local computer with my own Optifine Minecraft Client.

Other Plugins:
- Graves v4.6
- ItemsAdder v.2.5.4
- LibDisguises
- LightAPI-Bukkit v5.1.0
- LoneLibs
- LuckPerms-Bukkit v5.3.86
- mcMMO
- Model-Engine v2.3.1
- Mythicmobs Snapshot 5.0.0
- OTD
- Placeholder API v.2.11.1
- Protocollib
- sleep-most v.4.13.2
- StopnetherTrap
- WuufusWayGates v.1.3.3

Crashlog: [crash-2022-01-15_21.16.55-server.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/7876260/crash-2022-01-15_21.16.55-server.txt)

### How to reproduce

Unsure how to recreate but this enchantment was edited from the default bundled Lava Walker enchantment.
`lavawalker:
  display: "%group-color%Lava Walker"
  description: "Walk on Lava."
  applies-to: "Boots"
  type: "EFFECT_STATIC"
  group: "ETHER"
  applies:
    - ALL_BOOTS
  levels:
    1:
      effects:
        - "LAVA_WALKER"`

### "/ae plinfo" link

https://paste.md-5.net/yutotehujo

### Server Log

https://mcpaste.io/4b4e58f3a4aa05e5

**Comment by GC-spigot** [comment]
Fixed
