### ISSUE TITLE
Damage from Custom enchants

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#2587]
### Describe the bug

Issue is as followed, that with UltimateClans, if you have custom enchants. You can damage your teammates/allies if you have turned friendly fire off on UltimateClans.

### How to reproduce

Download UltimateClans

Use custom enchant on fellow clan member

he get damaged

### "/ae plinfo" link

https://paste.md-5.net/lezogabapa

**Comment by GC-spigot** [comment]
Ask UltimateClans to cancel player damage event
