### ISSUE TITLE
Incompatibilaty with saberfactions causing a dupe glitch with armour

### ISSUE THREAD

**Issue by LeitoCc187** [GC-spigot/AdvancedEnchantments#2588]
### Describe the bug

the bug is ocuring when Saber Factions and AE plugins are both installed on the same server

### How to reproduce

hold and item of armour in your hand look in the air and right-click the armour will be put onto the player and a copy will be left in your hand drop the item in your hand take the armour off and repeat 

### "/ae plinfo" link

https://paste.md-5.net/jomiciveke

### Server Log

https://mcpaste.io/6f5c0e767273f9f7

**Comment by LeitoCc187** [comment]
the factions pluign virsion is factions v1.6.9.5-3.0.0-RC-1.18pre

**Comment by GC-spigot** [comment]
Disable armor switching with your factions plugin - that's how to fix this.

**Comment by LeitoCc187** [comment]
sorry but in my factions configs there is not option for armor switching so what do you mean
