### ISSUE TITLE
Major memory leak

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2590]
### Describe the bug

In the MobDrops class you issue meta data "from_spawner" which does not get removed properly as I have a heap dump with over 11GB of that meta data. There is a paper event called EntityRemoveFromWorld. You could use that event to ensure it's removed properly or just find the leak and remove it

### How to reproduce

Load plugin -> memory leak

### "/ae plinfo" link

https://paste.md-5.net/hetodidaga

**Comment by JHarris12345** [comment]
I would like to point out that you do not need to have metadata to show the mob is from a spawner at all. You shouldn't really add meta data to show it's from a spawner. To check it's from a spawner, just get the entitie's spawn reason and if it = spawner, there ya go :D

**Comment by GC-spigot** [comment]
Fixed
