### ISSUE TITLE
AE Disables Itself

### ISSUE THREAD

**Issue by newbandpro** [GC-spigot/AdvancedEnchantments#2591]
### Describe the bug

The plugin activates at the beginning of the server startup but then gets disabled towards the end. I've tried updating the plugin and disabling firewall (It's locally hosted) but none of these helped.

### How to reproduce

Simply start up the server with the newest version of AE. It disables itself towards the end.

### "/ae plinfo" link

(Plugin doesn't work so I can't do this command)

### Server Log

https://pastebin.pl/view/9662c981

**Comment by GC-spigot** [comment]
Should be resolved
