### ISSUE TITLE
Tinkerer right confirm button doesn't work

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2593]
### Describe the bug

I can't confirm a trade using the right red/lime stained glass pane, but I can do with the left one.

Obs.: I would like if tinkerer was more configurable, like chest lines, choose pane slots, etc.

### How to reproduce

1. Open /tinkerer
2. Add any items
3. Try to confirm the trade using the RIGHT red/lime pane

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/66658478/150544577-440eaaf6-a962-4fd7-9bef-0950f507a51c.png)
![image](https://user-images.githubusercontent.com/66658478/150544611-b19ea095-4cad-4c68-9707-6dd5131217a7.png)

### "/ae plinfo" link

https://paste.md-5.net/oqumilitog.css

**Comment by GC-spigot** [comment]
That button is a "visual" part for tinkerer to accept it, not the user. User's side is on the left - this is intentional.
