### ISSUE TITLE
ADD:HARM broken

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2597]
### Describe the bug

ADD:HARM feature does not work, does not give damage at all.

### How to reproduce

With empty server, just AE, or even a server filled with plugins, ADD:HARM just doesnt work, I even tried ADD:HARM 100, 500, it just doesn't work, I even add message popups as a debug, the messages pop up and other effects work, its just the HARM.

### Screenshots / Videos

Just the code:
vengefuldiminish:
  display: '%group-color%Vengeful Diminish'
  description: "&fA chance to only get get half the damage your\n&fopponent deals and gain a chance to repel a burst of\n&fdamage.\n&6Requires:\n&eDiminish &eVI"
  applies-to: 'Chestplate'
  type: 'DEFENSE'
  group: 'TIER3'
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      chance: 6
      cooldown: 30
      effects:
        - 'MESSAGE:&d&l** VENGEFUL DIMINISH ** %victim%'
        - 'MESSAGE:&d&l** VENGEFUL DIMINISHED ** %attacker%'
        - 'HALF_DAMAGE'
        - 'ADD_HARM:15 %attacker%'
        - 'PLAY_SOUND:BLOCK_ANVIL_LAND %attacker%'
        - 'PLAY_SOUND:BLOCK_ANVIL_LAND'

### "/ae plinfo" link

https://paste.md-5.net/cuvifisavu

### Server Log

https://mcpaste.io/d590eea9c2582529

**Comment by illudota** [comment]
As an experiment, I tried reverting back to a random version, I reverted back to 8.7.25, harm works here, maybe later versions dont work.

**Comment by GC-spigot** [comment]
Fixed
