### ISSUE TITLE
Server crash with AdvancedEnchantments-8.8.4 Exception in server tick loop

### ISSUE THREAD

**Issue by Azakaturan** [GC-spigot/AdvancedEnchantments#2598]
### Describe the bug

After upgrading from AE version 8.8.0 to AE version 8.8.4, we had 2 server crashes within 30 minutes with the same error in both reports.  After the 2nd crash, I downgraded back to 8.8.0 and the server has been stable since.

### How to reproduce

Not sure.  All we did was update from 8.8,0 to 8.8.4.

### Screenshots / Videos

https://pastebin.com/HCMfVdQz
https://pastebin.com/ppMXLfx1

### "/ae plinfo" link

https://paste.md-5.net/fabetepoza

### Server Log

https://mcpaste.io/979380518fc8a129

**Comment by GC-spigot** [comment]
Fixed
