### ISSUE TITLE
TELEPATHY With crops

### ISSUE THREAD

**Issue by nivcoo** [GC-spigot/AdvancedEnchantments#2602]
### Describe the bug

Hello, telepathy doesn't work with crops, after break, no item is dropped

### How to reproduce

Break some crops with telepathy.

### "/ae plinfo" link

https://paste.md-5.net/uyiyizakan

**Comment by Firosee** [comment]
Hi could you record a video of this if possible? I have a suspicion that maybe a plugin could be conflicting? A list of your /pl would also be helpful.

Thanks!

**Comment by Burchard36** [comment]
https://user-images.githubusercontent.com/48583030/166220282-12ebbae9-99c4-4a31-84a6-10e19e704090.mp4

Closing this as there is no response on this, and it's not a bug on the most latest version, if you still experience issues with this, please open a new ticket and reference this one!

**Comment by Burchard36** [comment]
https://user-images.githubusercontent.com/48583030/166221265-b228d2e1-f180-4fcf-a277-69a24a06089e.mp4

Apologies for the first video was really laggy for some odd reason
