### ISSUE TITLE
Aura CE working in broken ways

### ISSUE THREAD

**Issue by Nextshot** [GC-spigot/AdvancedEnchantments#2605]
### Describe the bug

Equipping an enchantment that applies buffs or debuffs affects the target (damageable or undamageable) weirdly, sometimes when you equip the armor (in this case a chestplate) sometimes it doesnt even apply at all.
(When the effect is EFFECT_STATIC it gives the target a one-time permanent debuff and when it is REPEATING it acts weirdly sometimes working as intended (enter area of effect -> apply debuff for the time stated in ticks -> re-apply if inside the radius and when cooldown ends) and sometimes not working at all.
Also having multiple enchantments that apply a potion effect (Debuffs or buffs) cause only one of them to work (and what I stated above is still true, sometimes it doesn't even apply one at all)
Also it happens in offline or online mode.
Attached a video link so you guys can see I'm not going nuts.

### How to reproduce

I cant quite help with the part of reproducing it, mostly because it happens randomly but that's what I do:
1. Enchant your chestplate with X
2. Check if the debuff is applying
3. Re-equip the armor you are wearing (It will stop applying if it even applied at all)

1. Enchant your chestplate with X and Y
2. One debuff if not both are not applying

### Screenshots / Videos

https://www.youtube.com/watch?v=qEe9La2KCmg

### "/ae plinfo" link

https://paste.md-5.net/daqemibere

### Server Log

https://mcpaste.io/e6b21ec016ace477

**Comment by GC-spigot** [comment]
Sorry about delays, it's been fixed now
