### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by SliderKP** [GC-spigot/AdvancedEnchantments#2608]
### Describe the bug

If u can add posibilitie to activate enchantments when a user has been hit with shield equipped

something like this:

voodoo:
  display: "%group-color%Purificacion"
  description: "Da la oportunidad de\nlidiar con la debilidad."
  applies-to: "Armaduras"
  **type: "DEFENSE;DEFENSE_MOB;DEFENSE_SHIELD"**
  group: "POCOCOMUN"
  applies:
    - ALL_ARMOR

### How to reproduce

suggest

### "/ae plinfo" link

www.google.com

**Comment by Firosee** [comment]
Please do not use the bug report section for a feature request, wait until feature requests open up again please.
