### ISSUE TITLE
Your license exceeded maximum number of unique IPs

### ISSUE THREAD

**Issue by bydossch** [GC-spigot/AdvancedEnchantments#2609]
### Describe the bug

Name in spigot is BydossCH
[AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### How to reproduce

Your license exceeded maximum number of unique IPs

### Screenshots / Videos

![151503912-5911ff32-37c3-4e5a-8e54-aa51db72e1b6](https://user-images.githubusercontent.com/78153202/151645254-1d51bf76-f880-4f0d-a3c5-11e0586e41ce.jpg)

### "/ae plinfo" link

Paper 1.18.1

### Server Log

AdvancedEnchantments v.8.8.7

**Comment by RulerOfEternity** [comment]
that's not a bug, just contact the developer as instructed and the limit will be reset 🤦‍♂️

**Comment by Firosee** [comment]
Join our discord and open a ticket to have it be fixed. https://discord.gg/F9GUUVs6cJ
