### ISSUE TITLE
Feature - ITEMS IN HELMET SLOT

### ISSUE THREAD

**Issue by celciusjj** [GC-spigot/AdvancedEnchantments#2610]
### Describe the bug

Hi, this is not really a bug, is for request a feature. I have the permission of GC to open it.

the feature is to open the possibility to give the enchants effects to items that your put with /hat, MMOitems and Gunging Ootilities, or oraxen for example as many of us are bundling our RPG servers with the advanced enchantments, but we can't use custom textured helmets for this reason.

### How to reproduce

Enchant a item and put this with /hat or Gunging Ootilities in the head, and does nothing happend.

Thank you.

### Screenshots / Videos

Example image

![image](https://user-images.githubusercontent.com/37490999/151677557-fc77539b-1989-4905-a1f8-d22ab407a692.png)

### "/ae plinfo" link

https://paste.md-5.net/rivojiciko

**Comment by celciusjj** [comment]
will it ever be done? :(

**Comment by GC-spigot** [comment]
Added

**Comment by celciusjj** [comment]
> Added

I went back to my minecraft server, I wanted to try the feature and I find that it still doesn't work, and it hasn't been implemented :(

![image](https://user-images.githubusercontent.com/37490999/192912205-f0868b82-816a-4344-9504-5caa39d2a012.png)
Dont give me the night vision.
