### ISSUE TITLE
bug with enchantment furnace with protection stones plugin

### ISSUE THREAD

**Issue by Ronal1999** [GC-spigot/AdvancedEnchantments#2611]
### Describe the bug

as you can view in the video just put the protection in my case coal ore and then you mined

### How to reproduce

mined and put, and keep going, videos below

### Screenshots / Videos

https://www.youtube.com/watch?v=DCLs1tadZ5Q

### "/ae plinfo" link

https://paste.md-5.net/ixocoyociv

### Server Log

dont have one, no error so far

**Comment by Burchard36** [comment]
Hey there, the video is private can you re-upload as a unlisted video please?

**Comment by Burchard36** [comment]
Closing this as there is no response, if you still encounter this issue please do open another bug report referencing this issue! You can also comment on this and i can re-open it if you prefer, ill get email notifications :)
