### ISSUE TITLE
Repeating Enchantment Doesn't Work

### ISSUE THREAD

**Issue by newbandpro** [GC-spigot/AdvancedEnchantments#2612]
### Describe the bug

I've made an enchantment that restores durability over time to an item. However,it only works for a couple of ticks on my server even though it works fine on another server.

**Enchantment:**
reconstruct:
  display: "%group-color%Reconstruct"
  description: "Restores durability over time."
  applies-to: "All"
  type: "REPEATING"
  group: "LEGENDARY"
  time: 1
  applies:
    - ALL_ARMOR
    - ALL_AXE
    - ALL_SWORD
    - ALL_PICKAXE
    - ALL_HOE
    - ALL_SHOVEL
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
    1:
      chance: 10
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    2:
      chance: 20
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    3:
      chance: 30
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    4:
      chance: 40
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    5:
      chance: 50
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    6:
      chance: 60
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    7:
      chance: 70
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    8:
      chance: 80
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    9:
      chance: 90
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    10:
      chance: 100
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"

### How to reproduce

Simply add the enchantment to any damaged item. It doesn't restore any durability.

### Screenshots / Videos

https://gyazo.com/fee52c7de0a14b162d61e4a208b52a38

### "/ae plinfo" link

https://gyazo.com/fee52c7de0a14b162d61e4a208b52a38

### Server Log

https://mcpaste.io/84974698a6d2aa0c

**Comment by DawamRM** [comment]
Another Issue:
If you have multiple REPEATING enchantments under one item for some reason not all of them work. No errors in console, using latest version.

**Comment by Burchard36** [comment]
Hello this would be due to REPEATING and EFFECT_STATIC only being applicable for armor types, if you want you can open a new issue and mention that this should be a feature request,  and I will change its type for you

No current path is on track to add this feature, but we definitely can :)
