### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by iAmBenjamin11** [GC-spigot/AdvancedEnchantments#2614]
### Describe the bug

A option to toggle levels showing as numbers versus Roman Numerals.

For Example:

Rage 5     instead of      Rage V

Thanks!

### How to reproduce

A option to toggle levels showing as numbers versus Roman Numerals.

For Example:

Rage 5     instead of      Rage V

Thanks!

### "/ae plinfo" link

https://paste.md-5.net/sabigobixu

**Comment by Firosee** [comment]
Please do not use the bug report section for a feature request, wait until feature requests open up again please.
