### ISSUE TITLE
Encoding Issue in /enchanter preview

### ISSUE THREAD

**Issue by griffins07** [GC-spigot/AdvancedEnchantments#2615]
### Describe the bug

Right click on an enchantment in /enchanter and there's issues with the text and symbols and colors

### How to reproduce

Right click on an enchantment in /enchanter

### Screenshots / Videos

https://cdn.discordapp.com/attachments/377152090088275968/937943505555312680/unknown.png

### "/ae plinfo" link

https://paste.md-5.net/usuwexilit

### Server Log

https://mcpaste.io/d18994b2f73fc0b1

**Comment by GC-spigot** [comment]
Fixed

**Comment by griffins07** [comment]
I don't know how to reopen this, but it's not fixed
