### ISSUE TITLE
Cannot Merge Books in Anvil

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2616]
### Describe the bug

Expecting to be able to place 2 of the same custom enchantment book in an Anvil and get a higher level book of that same enchantment book. Same behavior as vanilla.

However, this does not work. Putting 2 Replenish II books in an Anvil does NOT produce a single Replenish III book. It does not do anything.

AE Anvil handling is enabled, and custom enchantment books can be applied to items.

### How to reproduce

Get 2 of same custom enchant book - NOT highest level for that enchant. Place into Anvil.

This has been tested with the plugins listed in plinfo, and without.

### Screenshots / Videos

https://ibb.co/ynmhFzz
https://ibb.co/PhjJPkX

### "/ae plinfo" link

https://paste.md-5.net/wudenogohe

**Comment by Burchard36** [comment]
Hello there, have you tried this on the latest version of AE by chance? Apologies for the late response on this!

**Comment by bdagenais2** [comment]
This issue still exists in 8.9.21

**Comment by bdagenais2** [comment]
Issue still exists in 8.12.5
