### ISSUE TITLE
INCREASE_DAMAGE Doesn't Work

### ISSUE THREAD

**Issue by newbandpro** [GC-spigot/AdvancedEnchantments#2618]
### Describe the bug

I've tried to use INCREASE_DAMAGE on armor to increase the damage of my attacks if the conditions are met. The condition *does* work,I just don't get a damage buff.

### How to reproduce

I've used this enchantment and set the time to night. Then I tried to hit someone and I do no extra damage.
nocturnal:
  display: "%group-color%Nocturnal"
  description: "Increases damage during night. (Conflicts with Diurnal)"
  applies-to: "Armor"
  type: "ATTACK;ATTACK_MOB"
  group: "ELITE"
  applies:
    - ALL_ARMOR
  levels:
    1:
      condition: "%time% > 12000: %allow%"
      effects:
        - "INCREASE_DAMAGE:5"
    2:
      condition: "%time% > 12000: %allow%"
      effects:
        - "INCREASE_DAMAGE:10"
    3:
      condition: "%time% > 12000: %allow%"
      effects:
        - "INCREASE_DAMAGE:15"
    4:
      condition: "%time% > 12000: %allow%"
      effects:
        - "MESSAGE:test %attacker%"
        - "INCREASE_DAMAGE:1000"

### "/ae plinfo" link

https://paste.md-5.net/amowewanow

**Comment by Burchard36** [comment]
When 8.9.15 is out, please update to that version as well as:

Your configuration is wrong:

INCREASE_DAMAGE needs %victim% at the end of it

**Comment by newbandpro** [comment]
That seems to have fixed it,thanks
