### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by ZeddyOG** [GC-spigot/AdvancedEnchantments#262]
With the plugin 'essentials' there is a command "/hat" and if a player uses the command it will replace their helmet with the item in hand, basically if the player has a 'static effect' enchantment on the helmet and does /hat the helmet will be removed but the effects will not be. (ONLY TESTED WITH STATIC EFFECTS)

If a player uses a transmog on an item then decides to either rename it or name it and attempts to re-transmog that item the [#] will not display next to the name.

**Comment by GC-spigot** [comment]
1st can't be fixed, 2nd will be fixed.
