### ISSUE TITLE
Overload effect breaks with AureliumSkills

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2622]
### Describe the bug

We have AureliumSkills, an mcMMO alternative, and as players level up their "health" stat, it gives them extra health. For example, at the time of testing, I had 24.8/20 health. With this plugin, the Overload enchant does not grant the user any additional health and actually causes the visual healthbar to go down (even though their actual health doesn't change).

### How to reproduce

Install AureliumSkills and AE. Level up your Defense ability in AureliumSkills to get more max health (viewable with /stat). Then, put on a piece of armor enchanted with Overload.

### Screenshots / Videos

https://i.ibb.co/ZMk799Z/image.png
https://i.ibb.co/j6WsXb7/image.png

### "/ae plinfo" link

https://paste.md-5.net/wudenogohe

**Comment by GC-spigot** [comment]
If they add the healthboost with potions it's not something we can track unfortunately with how enchants work right now, I'll try to contact their developer and work on it :)
