### ISSUE TITLE
Mobs not dropping ae items, including randomenchatedbook, works on old versions, not 8.8.8

### ISSUE THREAD

**Issue by Midge4261** [GC-spigot/AdvancedEnchantments#2624]
### Describe the bug

Vanilla mobs are not dropping randomenchantedbook when killed. Just their standard loot is dropped.

### How to reproduce

I've tried to change the item dropped and nothing but the normal vanilla drops occur when I kill a Zombie. here is my config for mobs.yml:

# You can give custom AE items when mobs are killed
# Item names must be same as from '/ae giveitem' command (for future references).

# Current items: whitescroll, renametag, blocktrak, stattrak, soultracker, mobtrak, transmog, randomenchantmentbook, secret:<amount>:<group>

# Format: "<item name>:<count>"

mobs:
  ZOMBIE:
    chance: 100
    items:
      - 'randomenchantedbook:1'

### "/ae plinfo" link

https://paste.md-5.net/uwuperokar

**Comment by Midge4261** [comment]
Did some troubleshooting on discord. This is a version issue. It isn't working on 8.8.8 but is working in previous versions.

**Comment by Midge4261** [comment]
Do I need to downgrade versions to get this to work? Not trying to pressure, but I really want this feature on my server.

**Comment by Burchard36** [comment]
fixed, when 8.9.15 is out update to that version :)
