### ISSUE TITLE
chace bug

### ISSUE THREAD

**Issue by rongda0201** [GC-spigot/AdvancedEnchantments#2625]
### Describe the bug

If I has a book 60%/40%, I use a 10% secret-dust it become 70%/40%, and I use 7%  secret-dust again it become 67%/40%

### How to reproduce

video

### Screenshots / Videos

https://www.dropbox.com/s/ozl0z91h6bzd3j7/%E9%8C%84%E8%A3%BD_2022_02_04_23_16_35_415.mp4?dl=0

### "/ae plinfo" link

https://paste.md-5.net/pakiwobixa

**Comment by rongda0201** [comment]
If I has a book 60%/40%, I use a 10% secret-dust it become 70%/40%, and I use 7%  secret-dust again it become 67%/40%

**Comment by GC-spigot** [comment]
Works fine from testing
