### ISSUE TITLE
Error on 1.8.9

### ISSUE THREAD

**Issue by boristran03** [GC-spigot/AdvancedEnchantments#2626]
### Describe the bug

Got this error when player use pickaxe, sword,....

### How to reproduce

idk

### "/ae plinfo" link

https://paste.md-5.net/kavihikazi

### Server Log

https://mcpaste.io/3051a1705e8c04f0

**Comment by boristran03** [comment]
pls fix this, it's been 2 day :"//

**Comment by GC-spigot** [comment]
Fixed, update is coming in ~10 minutes
