### ISSUE TITLE
[SUGGESTION] Spartan plugin support

### ISSUE THREAD

**Issue by CraftyKenny** [GC-spigot/AdvancedEnchantments#263]
**Issue**
Currently our anti cheat, Spartan, which is a well-known anti cheat is not compatible with this plugin. I've talked to the plugin developer of that plugin and he has said that the plugin developer(s) of this plugin has to add the support for Spartan. 

**Request**
I'd like to see the support added to Spartan I can continue using this enchantment plugin.

**Comment by GC-spigot** [comment]
Please tell me which exact issues are you having. As far as I'm aware, most if not all current effects/enchants should be compatible.
