### ISSUE TITLE
Advanced Enchantments not working with villagers or enchantment table

### ISSUE THREAD

**Issue by TheOsmanium** [GC-spigot/AdvancedEnchantments#2631]
### Describe the bug

I installed the plugin, and for some reason it wont allow me to trade with villagers or get enchantments through the enchantment table, also lapis is not being consumed either and only vanilla enchants work. 

### How to reproduce

I just installed the plugin and it never worked since then, I wish I could give more detail but there is nothing more to it.

### "/ae plinfo" link

https://paste.md-5.net/ofaveluvik

### Server Log

https://mcpaste.io/571c204df3c133c7

**Comment by Midge4261** [comment]
There is a .yml file for Enchantmenttable. Did you set the value from False to True in that file, save, then restart the server?

**Comment by TheOsmanium** [comment]
I did set it to true and I should have mentioned that I went through all of the simple steps of diagnosing it with Dunescifye on discord, even running it on a test server by itself and it still got us nowhere

**Comment by DarkPink69** [comment]
Hi , so im having kinda the same problem here , while my enchanting table works perfectly fine even with tweaked chances the villagers don't trade custom books i tried most of the jobs and none have any kind of custom trades or books , there is a config for the enchantmenttable but none for villagers so im kinda stuck.

**Comment by Burchard36** [comment]
> I did set it to true and I should have mentioned that I went through all of the simple steps of diagnosing it with Dunescifye on discord, even running it on a test server by itself and it still got us nowhere

In regards to your villagers, not trading, this worked fine for me, i just had to tweak the chances a bit to get them to show up

This is in lootConfiguration.yml

![image](https://user-images.githubusercontent.com/48583030/166226148-b336b6fb-e5d7-479c-8fd3-7271225cda44.png)


Can you send yours regarding villagers not trading? Ill post another comment update for the enchantment table

**Comment by Burchard36** [comment]
> Hi , so im having kinda the same problem here , while my enchanting table works perfectly fine even with tweaked chances the villagers don't trade custom books i tried most of the jobs and none have any kind of custom trades or books , there is a config for the enchantmenttable but none for villagers so im kinda stuck.

Hello please open another issue if you want support for this, and read my comment above this one :)

**Comment by Burchard36** [comment]
Closing due to no response, please open a new issue if this one still persists and reference it in your new ticket!
