### ISSUE TITLE
Attributes of Armor/Weapons show in gkit Menu

### ISSUE THREAD

**Issue by griffins07** [GC-spigot/AdvancedEnchantments#2632]
### Describe the bug

Attributes of Armor/Weapons show in gkit Menu

### How to reproduce

Just use a piece of armor or a weapon for a gkit item

### "/ae plinfo" link

https://paste.md-5.net/icapahotud

### Server Log

https://mcpaste.io/4c9d5ddb3d82b8a0

**Comment by Burchard36** [comment]
Hello, will be fixed in 8.9.23 :)

Apologies for the late response! These issues were open long before i started working here :)

**Comment by Burchard36** [comment]
Closing as this was fixed
