### ISSUE TITLE
Poison Enchantment not applying to Target

### ISSUE THREAD

**Issue by CombatMedic02** [GC-spigot/AdvancedEnchantments#2633]
### Describe the bug

When you apply the Poison enchantment to a Sword/Axe after hitting a mob/player the Poison effect isn't applied to them. Doesn't matter if the chance is even set to 100% it just doesn't effect any target.

DuneSciFye has tested this issue when I brought it up on Discord and has confirmed that the issue exists on their test server.

### How to reproduce

1) Apply the Poison enchantment to a Sword/Axe.
2) Hit a player/mob.
Result: Target will not be inflicted with the Poisoned Status Effect.

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by Burchard36** [comment]
Hello, are you able to send your enchantment for this? I don't see any enchantment named "Poison" in our default configuration(s) (Unless its an addon possibly)

Apologies for the late response, make sure to update as well and just double check if that enchantment is still bugged for you!

**Comment by CombatMedic02** [comment]
It should be one of the enchantments that comes with the mod? It was in AdvancedEnchantments-8.8.19 at least unless you have removed it since? DuneSciFye from your Support Discord tested in on a server with just the AdvancedEnchantments plugin and confirmed that is wasn't working. That was on the 6th of Feb though. I haven't tested it since because I didn't get any response to this ticket so I assumed it was still broken. I can test it again during the week if you like? 

The enchantment as it is in enchantment.yml can be found below.

poison:
  display: "%group-color%Poison"
  description: "A chance of giving poison effect."
  applies-to: "Swords, Axes"
  type: "ATTACK;ATTACK_MOB"
  group: "ELITE"
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    1:
      chance: 25
      cooldown: 2
      effects:
        - "POTION:POISON:0:80 %victim%"
    2:
      chance: 50
      cooldown: 2
      effects:
        - "POTION:POISON:1:30 %victim%"
    3:
      chance: 70
      cooldown: 4
      effects:
        - "POTION:POISON:1:80 %victim%"

**Comment by GC-spigot** [comment]
Seems to be working fine!
