### ISSUE TITLE
Duplicate description when applying book to existing enchanted item

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2634]
### Describe the bug

Trying to upgrade a custom enchant on an item with a book results in the enchant level staying the same, but the description being duplicated.

### How to reproduce

See screenshots.

### Screenshots / Videos

https://i.ibb.co/t4X22DY/image.png
https://i.ibb.co/CBbzBPH/image.png
https://i.ibb.co/gZ31mVv/image.png

### "/ae plinfo" link

https://paste.md-5.net/wudenogohe

**Comment by Burchard36** [comment]
Hello there can you upgrade AE and see if this bug still persists? When combining books on my end 

Screenshots arent available anymore as it took us a while to respond to the issue, sorry!

Also can you provide your config.yml as well too please and thank you!

**Comment by bdagenais2** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/issues/2960
