### ISSUE TITLE
%is on fire% and other conditions are bugged... AGAIN

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#2636]
### Describe the bug

%is on fire% is bugged again, not sure if you need me to explain again.

### How to reproduce

  type: 'ATTACK;ATTACK_MOB'
  group: 'UNIQUE'
  settings:
    disable-in-enchanter: true
  applies:
    - ALL_AXE
    - ALL_SWORD
    - TRIDENT
  levels:
    1:
      chance: 40
      condition: '%victim is on fire% = true : %allow%' 
      cooldown: 1
      effects:
        - 'ADD_DURABILITY_ITEM:-<random number>1-2</random number> %attacker%'

is triggers even when not on fire or if DEFENSE it never triggers.

### "/ae plinfo" link

https://paste.md-5.net/ugusitorol

**Comment by GC-spigot** [comment]
Works just fine from testing
