### ISSUE TITLE
Magic Dust destroys books in anvils.

### ISSUE THREAD

**Issue by MCTGE** [GC-spigot/AdvancedEnchantments#2637]
### Describe the bug

Magic Dust will destroy an AE Enchantment Book if placed in an anvil.

### How to reproduce

If you place Magic Dust in the first slot of an anvil and a book in the second slot, it will create magic dust with the same rates as before.  However, the book is consumed in the process. 

### Screenshots / Videos

![AEAnvilbug](https://user-images.githubusercontent.com/93126894/153275811-f748c1c7-f531-4bd3-b899-aae7ae0ff138.png)

### "/ae plinfo" link

https://paste.md-5.net/ricumuduqo

### Server Log

https://mcpaste.io/d309caf844abbd42

**Comment by GC-spigot** [comment]
Fixed
