### ISSUE TITLE
%prevlevel% Placeholder is not working correctly when upgrading an item.

### ISSUE THREAD

**Issue by MCTGE** [GC-spigot/AdvancedEnchantments#2638]
### Describe the bug

When upgrading an enchantment the %prevlevel% placeholder is showing instead of the intended integer. 

### How to reproduce

Upgrade any enchantment on any item from a lower level to a higher level.

### Screenshots / Videos

![ae bug](https://user-images.githubusercontent.com/93126894/153487308-3191dc3b-df9b-491a-8dfa-236018a0b01d.png)

### "/ae plinfo" link

https://paste.md-5.net/wodiduwiji

### Server Log

https://mcpaste.io/1c95434c565381a0

**Comment by GC-spigot** [comment]
Fixed
