### ISSUE TITLE
very serious duplication bug

### ISSUE THREAD

**Issue by haroldrc** [GC-spigot/AdvancedEnchantments#2642]
### Describe the bug

just place "oreblock" in the spot where you dug with trench and dig them with a pickaxe with "silktouch"

### How to reproduce

just place "oreblock" in the spot where you dug with trench and dig them with a pickaxe with "silktouch"

### "/ae plinfo" link

https://paste.md-5.net/omejuzuvev

**Comment by GC-spigot** [comment]
Can you provide a video or a gif?

**Comment by haroldrc** [comment]
https://vimeo.com/676965340

**Comment by haroldrc** [comment]
https://vimeo.com/676965340

**Comment by haroldrc** [comment]
-I dug with "trench"
-I placed 64 blocks
-I dug them with "silktouch" (and received 65 blocks, sometimes I get more)

**Comment by haroldrc** [comment]
what should I do

**Comment by Burchard36** [comment]
Hello, can you try this on the latest version of AE and let me know if this persists?

**Comment by Burchard36** [comment]
Closing due to a lack of response and inability to replicate, if you are still experiencing this issue please open a new issue referancing this one!
