### ISSUE TITLE
Non-Op players can still see /ae

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2645]
### Describe the bug

Without any permissions, regular players can see and execute /ae. There is no reason for them to see this, it only confuses them as they think it's something they can do/use.

As a workaround I've blocked the command with another plugin and staff now use /advancedenchantments:ae to run commands, but this is extremely annoying.

### How to reproduce

Use the plugin.

### "/ae plinfo" link

https://paste.md-5.net/wudenogohe

**Comment by GC-spigot** [comment]
It's meant to be this way.
