### ISSUE TITLE
BREAK_TREE cuts other trees and sometimes not the entire tree

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2646]
### Describe the bug

Using BREAK_TREE sometimes a different tree will be cut down in addition to the one you're cutting. Also, often will not cut down the entire tree (neither the one you cut nor the other one that happened to get hit).

### How to reproduce

Use BREAK_TREE.

### Screenshots / Videos

https://youtu.be/F0IjVKWc0qQ

### "/ae plinfo" link

https://paste.md-5.net/wudenogohe

**Comment by Burchard36** [comment]
Hello, sorry for the delay this issue was opened before i started working here

This will no longer happen, please update to the latest version :)
