### ISSUE TITLE
EFFECT_STATIC bug with regeneration effect when eating gapples

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#2648]
### Describe the bug

When you use EFFECT_STATIC with regeneration I effect, if you eat a gapple, the regeneration effect disappear.

### How to reproduce

1) Use an armor with effect_static & regen 1
2) eat a gapple
3) the permanent regeneration don't come back until you unequip / equip the armor.

### Screenshots / Videos

https://youtu.be/mSV3nRfuPXk

### "/ae plinfo" link

https://paste.md-5.net/dohojorulu

**Comment by GC-spigot** [comment]
Seems to be working fine on latest version, try updating
