### ISSUE TITLE
Warn when use PUMKIN effect

### ISSUE THREAD

**Issue by YKDZ** [GC-spigot/AdvancedEnchantments#2649]
### Describe the bug

When I use this Pumkin enchant:

https://mcpaste.io/39df8f0c8bf4906f

And attack a player, this WARN will appear:

https://mcpaste.io/659211c16758907e

### How to reproduce

1. Load my PUMKIN enchant
2. Enchant a sword
3. Using that sword to attack player
4. Find this WARN

### "/ae plinfo" link

https://paste.md-5.net/liqoyojidi

### Server Log

https://mcpaste.io/643dc9f05222557c

**Comment by YKDZ** [comment]
Then I use v8.8.15 to test but this warn will also appear.

**Comment by GC-spigot** [comment]
Resolved
