### ISSUE TITLE
Blesssed

### ISSUE THREAD

**Issue by hetjoshi** [GC-spigot/AdvancedEnchantments#265]
Blessed Enchantment doesn't work properly. Now if you get poison it removes it but when you have a drunk 4 helmet on it doesn't remove the slowness 3 and slow_dig 3 or 2. Using the latest version and

      - 'CURE:SLOW'
      - 'CURE:CONFUSION'
      - 'CURE:BLINDNESS'
      - 'CURE:POISON'
      - 'CURE:WITHER'
      - 'CURE:HUNGER'
      - 'CURE:WEAKNESS'
      - 'CURE:SLOW_DIGGING'
      - 'MESSAGE:&e&l** BLESSED ** %attacker%'

thats the config fyi.

**Comment by Frostyeiz** [comment]
blessed won't cure permanent effects (because if it do so, enchantments like drunk would be op asf)
