### ISSUE TITLE
Error Give GKIT

### ISSUE THREAD

**Issue by Verkros** [GC-spigot/AdvancedEnchantments#2656]
### Describe the bug

Hello, is there any way to give a gkit from the console to a player?

### How to reproduce

I try to use "gkit (kit) (nick)" but it doesn't work

### Screenshots / Videos

https://pastebin.com/Mn14QQtV

### "/ae plinfo" link

https://pastebin.com/Mn14QQtV

**Comment by Burchard36** [comment]
Hello please use this command instead, apologies for the late response 

`/ae givegkit (player) (gkit)`

If you still have issues with this please open a new issue referancing this one!
