### ISSUE TITLE
Equipping Haste II pickaxe when wearing takeoff boots sends flying toggle message

### ISSUE THREAD

**Issue by CapitalistCow** [GC-spigot/AdvancedEnchantments#2657]
### Describe the bug

When wearing boots with takeoff on them, holding a pickaxe enchanted with Haste II will send the message "youre flying has been toggled" to chat. Every time you scroll to the item it will send the message. Does not actually toggle flying, but still sends the message. 

### How to reproduce

Equip diamond boots with takeoff I enchant. Enchant a diamond pickaxe with Haste II and place it in your hotbar. Exit inventory and scroll to the pickaxe and the message "your flying has been toggled" will appear in chat. 

UPDATE: We have found that it occurs with any level haste, on any tool. 

### Screenshots / Videos

https://user-images.githubusercontent.com/100172484/155041274-24df3db9-63aa-4328-b7e5-47f0c530f3ae.mp4

### "/ae plinfo" link

https://paste.md-5.net/pegenakoji

**Comment by Burchard36** [comment]
Hello there im deeply apologies this issue went unresolved for so long

Can you please give me the configuration for `takeoff` as this is not a default enchantment of ours, please and thanks in advance!

**Comment by GC-spigot** [comment]
Fixed!
