### ISSUE TITLE
DUPE BLOCK PROTECTION

### ISSUE THREAD

**Issue by ProAlexYTB** [GC-spigot/AdvancedEnchantments#2658]
### Describe the bug

With these custom enchant can dupe protection blocks, the plugin named is ProtectionStones

### How to reproduce

He need to have these custom enchant

### Screenshots / Videos

https://prnt.sc/0d5G9kvOevqS

### "/ae plinfo" link

https://paste.md-5.net/avuqolojud

**Comment by GC-spigot** [comment]
This isn't a bug, it's a feature request. We don't support ProtectionStones - support has been added.
