### ISSUE TITLE
Enchant preview does not accurately reflect resulting enchant

### ISSUE THREAD

**Issue by dsevvv** [GC-spigot/AdvancedEnchantments#2660]
### Describe the bug

![2022-02-22_23 23 48](https://user-images.githubusercontent.com/76348815/155276457-b4ba8895-f44a-4add-9bb6-a120a070eaf3.png)

Here you can see the preview for the diamond sword, it appears to be "Unbreaking III"

![2022-02-22_23 23 52](https://user-images.githubusercontent.com/76348815/155276548-46a4d4a4-d92a-4796-8303-ee42eb96b747.png)

Here you can see the resulting sword, it does not have Unbreaking, but instead has "Smite V"

### How to reproduce

Enchant an item in the enchant table, view details above.

### Screenshots / Videos

![2022-02-22_23 23 48](https://user-images.githubusercontent.com/76348815/155276638-4c4d23e5-771f-47bb-8f56-60054725fbfd.png)
![2022-02-22_23 23 52](https://user-images.githubusercontent.com/76348815/155276644-d8b7b1fb-2260-401b-8881-a53cd92806a4.png)

### "/ae plinfo" link

https://paste.md-5.net/oguqaporow

### Server Log

https://mcpaste.io/268f644344fa2112

**Comment by GC-spigot** [comment]
Can't fix this unfortunately, for some reason server reports something different than it adds
