### ISSUE TITLE
Kill Aura not working

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#2661]
### Describe the bug

This part of the config seems to not work at all:
>        - "KILL_MOB:1 <aoe> radius=3 target=mobs </aoe>"

It's on the enchantment called Kill Aura and it's not killing any mobs in an area.
I tried with "ADD_HARM" instead and that seems to work fine.

### How to reproduce

Put Kill Aura on a sword, kill mobs in a large group, nothing except for the particles happens.

### "/ae plinfo" link

https://paste.md-5.net/ucuguricat

**Comment by GC-spigot** [comment]
Use ADD_HARM until this is fixed :)
