### ISSUE TITLE
Blocktrak + World based Enchants NBT Dupe

### ISSUE THREAD

**Issue by ryankayz7** [GC-spigot/AdvancedEnchantments#2663]
### Describe the bug

I have an enchant that activates when "MINING" in a world with a pickaxe however when the blocktrak is added to this item it duplicates the blocktrak nbt data causing essentially an NBT bomb meaning the item will crash anyone near it. This doesn't occur outside of the specified world and works as it normally should.

### How to reproduce

Put blocktrak on and also an enchant that specifies activating on break-block and also is only active in a certain world. An example of the enchant and the nbt it adds is linked in screenshots.

### Screenshots / Videos

https://gyazo.com/f623adb8bd4d005b17e66ab52a0458c8
https://gyazo.com/61d44f540ce64914ab580f17d99dd9c2

### "/ae plinfo" link

https://paste.md-5.net/ketogisiju

**Comment by GC-spigot** [comment]
Can you post the enchant here? Thanks

**Comment by ryankayz7** [comment]
Sorry about the delay but here is the enchant:
unbreakable:
  display: "%group-color%Unbreakable"
  description: 'Prevent your pickaxe from breaking in mines!'
  applies-to: 'Tools'
  group: 'COPPER'
  type: 'MINING'
  applies:
  - 'ALL_PICKAXE'
  levels:
    '1':
      chance: 100
      condition:
      - '%player world% = world_mines : %allow%'
      effects:
        - 'ADD_DURABILITY_CURRENT_ITEM:-1'

**Comment by GC-spigot** [comment]
Likely to be another plugin, not caused with latest version https://prnt.sc/SndL9aOh3wF-

**Comment by ryankayz7** [comment]
Hey, so I managed to re-replicate this without the unbreakable enchant but with trench. I wonder if this has to do with speed that blocks are broken at. I couldn't re-replicate my previous issue with the same conditions however I managed to cause the same bug to happen with only the trench enchantment and the blocktrak item. This has been pictured below. version used is 8.9.2.

https://gyazo.com/ff1fb5d6242f19794938ff40e6346b9a

Trench enchant is as followed:
trench:
  display: "%group-color%Trench"
  description: "Chance to break in 3x3 area."
  applies-to: "Pickaxes, Shovels"
  type: "MINING"
  group: "GOLD"
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 4
      effects:
        - "TRENCH:3"
        - "TP_DROPS" 
        - 'ADD_DURABILITY_CURRENT_ITEM:-15'              
    2:
      chance: 8
      effects:
        - "TRENCH:3"
        - "TP_DROPS"      
        - 'ADD_DURABILITY_CURRENT_ITEM:-15'              
    3:
      chance: 12
      effects:
        - "TRENCH:3"
        - "TP_DROPS"                
        - 'ADD_DURABILITY_CURRENT_ITEM:-15'              
    4:
      chance: 16
      effects:
        - "TRENCH:3"
        - "TP_DROPS"                
        - 'ADD_DURABILITY_CURRENT_ITEM:-15'              
    5:
      chance: 20
      effects:
        - "TRENCH:3"
        - "TP_DROPS"        
        - 'ADD_DURABILITY_CURRENT_ITEM:-15'

**Comment by ryankayz7** [comment]
Also an update. I change trench to this and I was not able to replicate it.

trench:
  display: "%group-color%Trench"
  description: "Chance to break in 3x3 area."
  applies-to: "Pickaxes, Shovels"
  type: "MINING"
  group: "GOLD"
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 4
      effects:
        - "TRENCH:3"   
        - "TP_DROPS"                        
    2:
      chance: 8
      effects:
        - "TRENCH:3"
        - "TP_DROPS"                        
    3:
      chance: 12
      effects:
        - "TRENCH:3"
        - "TP_DROPS"                
    4:
      chance: 16
      effects:
        - "TRENCH:3"
        - "TP_DROPS"                
    5:
      chance: 20
      effects:
        - "TRENCH:3"
        - "TP_DROPS"
