### ISSUE TITLE
No AdvancedEnchatments in /plugins

### ISSUE THREAD

**Issue by OhWelle122710** [GC-spigot/AdvancedEnchantments#2664]
### Describe the bug

If i install AE only the AdvancedEnchantment in /plugin is Color Red
so i receive an error everytime i enter commands

and if i Install AE + AE API in my server theres no AE in /plugins and i cant type any AE commands

### How to reproduce

a

### "/ae plinfo" link

cant type any /ae commands

### Server Log

https://mcpaste.io/4a84647d4b0c31fb

**Comment by GC-spigot** [comment]
Update the plugin
