### ISSUE TITLE
CE effect cooldown only working per PLAYER

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2665]
### Describe the bug

CE effect cooldown only working per PLAYER

basically, when u make a CE with a cooldown, when a player makes that CE proc, and its on cooldown, the cooldown doesnt exist for the other player, so when the other player hits you, the CE procs again, which wasnt like this before and it makes CE OP. 

A player discovered the bug when he was being jumped 1v5, and thus, the CE kept proccing. which was unusual, so I tested it with him and let 5 players hit me all at the same time, a CE with 60s cooldown,  procced 5 times in that 60s span. which means the CD works per PLAYER and not UNIVERSALLY.

### How to reproduce

Make a CE with a cooldown and 100% chance, test it with 2 players, make it a defense CE, see how the CD is client-sided.

-- HERE IS THE CODE OF THE CE I USED --
      chance: 100
      cooldown: 30
      effects:
        - 'MESSAGE:&d&l** VENGEFUL DIMINISH ** %victim%'
        - 'MESSAGE:&d&l** VENGEFUL DIMINISHED ** %attacker%'
        - 'HALF_DAMAGE'
        - 'ADD_HARM:30 %attacker%'
        - 'PLAY_SOUND:BLOCK_ANVIL_LAND %attacker%'
        - 'PLAY_SOUND:BLOCK_ANVIL_LAND'

This is just a test CE to see if the cooldown really exists universally, but no, it only exists per PLAYER.

### Screenshots / Videos

https://www.youtube.com/watch?v=rGsDgbvd1X0

### "/ae plinfo" link

https://paste.md-5.net/oyaqolicul

### Server Log

https://mcpaste.io/ee534e5acb5ba557

**Comment by illudota** [comment]
Server version paper 1.16 btw

**Comment by illudota** [comment]
https://discord.com/channels/376425582139015168/377152090088275968/948472447122956328 
other proof.

**Comment by GC-spigot** [comment]
Fixed
