### ISSUE TITLE
Telepathy/Smelting Dupe with other plugins

### ISSUE THREAD

**Issue by GroundedMC** [GC-spigot/AdvancedEnchantments#2666]
### Describe the bug

Item duplication bug when running Advanced Enchantments with RoseStacker or other plugins, when Smelting or Telepathy are applied to a tool.

I searched the Discord for dupe bugs and found that others are also having the same issue, but with other plugins, such as Factions.  I have spoken to the Dev of RoseStacker and she has tried a couple things but is unable to figure out a fix without having the code for AE.  She is willing to work with the AE Devs to hopefully find a fix.

### How to reproduce

Add telepathy/smelting to a tool of choice.  Break a chest with items/mine and all items dropped to the ground will be duplicated.

### Screenshots / Videos

Mining Ore with AE & RoseStacker - https://youtu.be/Uq31GUQtuYw
Full Inventory with AE & RoseStacker - https://youtu.be/0Dg95SPmXjk
AE & RoseStacker - https://youtu.be/tPnpUpw4GYA

AE without RoseStacker - https://youtu.be/5J8qCzOyeQc

### "/ae plinfo" link

https://paste.md-5.net/exotumaruy

**Comment by Esophose** [comment]
Hello, author of RoseStacker here. If you could possibly explain what events and actions you take with the smelting enchantment I might be able to get some insight on how we could fix this. I've noticed that even when the enchantment doesn't actually smelt anything it still dupes the items and were wondering why you still seem to be modifying the event even if nothing is happening. I think it might have to do with the event priorities but I'm not sure what events you're listening to for it either. If you want you could DM me on Discord (Nicole#0001) or we could chat here about it, just trying to get this fixed as I've had three separate people come to me about it now.

**Comment by MCTGE** [comment]
I am having this exact same issue with Smelting and the RoseStacker Combo.

**Comment by GC-spigot** [comment]
Contacted @Esophose, hopefully we can resolve this asap

**Comment by GroundedMC** [comment]
> Contacted @Esophose, hopefully we can resolve this asap

Hi there - checking to see if there is an update on this?  Thanks so much!

**Comment by Burchard36** [comment]
Oh wow I'm surprised this slipped through the cracks when I was implementing this

Support has been added for RoseStacker for a very long time now haha, almost a month now, please update and it will work! Open another issue referencing this issue if you still experience this bug for some odd reason :)

**Comment by gordoperoguapo** [comment]
Dupe issue still happening.
