### ISSUE TITLE
Obsidian destroyer not working 

### ISSUE THREAD

**Issue by NightLife-SG** [GC-spigot/AdvancedEnchantments#2668]
### Describe the bug

enchantment doesnt work as it stated
it suppose to have chance to break obsidian instantly but no matter how i try it does do what it stated

### How to reproduce

i have a netherite pickaxe with the eff 5 and obsidian destroyer on highest lv

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/84533050/156418140-d4a01651-d047-4c48-bb3e-ddee0a1e69e3.png)

### "/ae plinfo" link

https://paste.md-5.net/nujidexefo

**Comment by CrystallizedAtrophy** [comment]
I'm not a dev or anything but i had this same issue the other day. try  removing the '%can break% = true : %allow%' and it should work. You can also update it to allow crying obsidian by replacing the other line with '%block type% = OBSIDIAN OR %block type% = CRYING_OBSIDIAN : %allow%'

**Comment by ddman1211** [comment]
and upgrade plugin!!
