### ISSUE TITLE
/apply not working as expected

### ISSUE THREAD

**Issue by Hermelijn15** [GC-spigot/AdvancedEnchantments#2669]
### Describe the bug

/apply and /reapply do not "reaply" the armor set the player is wearing, meaning that if you equip armor to a player with a third party plugin and do /apply or /reapply it wont recognize the armor set (but only the enchants), was told to make a github issue after making a ticket.

### How to reproduce

use any third party plugin to equip armor.

### Screenshots / Videos

https://streamable.com/in9xmd

### "/ae plinfo" link

https://paste.md-5.net/omexapelid

### Server Log

feel free to contact me and i can dm it, wont be uploading the complete file here

**Comment by ddman1211** [comment]
upgrade plugin!

**Comment by GC-spigot** [comment]
Fixed
