### ISSUE TITLE
Huge problem crashing server

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2670]
### Describe the bug

In a 25/30 players combat, the server always crash for a reason. Got two reports from 2 differents days.

https://pastebin.com/qGBMHeEX

https://pastebin.com/wx9UdVtf

### How to reproduce

I don't know which event is breaking it, but after the lag, the players armors brokes.

### "/ae plinfo" link

https://paste.md-5.net/upibajopuq.css

**Comment by ddman1211** [comment]
bug cause for mcmmo.

**Comment by ddman1211** [comment]
upgrade plugin .... https://www.spigotmc.org/resources/1-8-1-18-2-%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90create-custom-enchantments-%E2%9C%85-50-sale.43058/

**Comment by GC-spigot** [comment]
Should be resolved
