### ISSUE TITLE
Issue with Bows/crossbows

### ISSUE THREAD

**Issue by CrystallizedAtrophy** [GC-spigot/AdvancedEnchantments#2672]
### Describe the bug

Can't get either of these enchants to proc particle effect with SHOOTING the bow, only when PUNCHING with the bow.
Have tried using message to make sure it procs but only shows up after punching player/mob.

version: 8.8.19

soulpiercer:
  display: "%group-color%Soul Piercer"
  description: "Your arrows pierce players souls and capture them for yourself upon death."
  applies-to: "Crossbows, Bows"
  type: "KILL_PLAYER"
  group: "MASTERY"
  applies:
    - CROSSBOW
    - BOW
  levels:
    1:
      chance: 45
      effects:
        - "ADD_SOULS:1"
        - "PARTICLE:FALLING_OBSIDIAN_TEAR:1:0 %victim%"
        - "WAIT:30" #1.5 seconds
        - "PARTICLE:SOUL:1:0 %victim%"
    2:
      chance: 65
      effects:
        - "ADD_SOULS:1"
        - "PARTICLE:FALLING_OBSIDIAN_TEAR:1:0 %victim%"
        - "WAIT:30" #1.5 seconds
        - "PARTICLE:SOUL:1:0 %victim%"
    3:
      chance: 75
      effects:
        - "ADD_SOULS:1"
        - "PARTICLE:FALLING_OBSIDIAN_TEAR:1:0 %victim%"
        - "WAIT:30" #1.5 seconds
        - "PARTICLE:SOUL:1:0 %victim%"
soulsiphon:
  display: '%group-color%Soul Siphon'
  description: 'Your arrows siphon the souls of lesser beings.'
  applies-to: 'Crossbows, Bows'
  type: 'KILL_MOB'
  group: 'MASTERY'
  applies:
    - CROSSBOW
    - BOW
  levels:
    '1':
      chance: 4
      cooldown: 80
      effects:
        - 'CONSOLE_COMMAND:ae giveitem %attacker name% soulgem 1 4'
        - "PARTICLE:FALLING_OBSIDIAN_TEAR:1:0 %victim%"
        - "WAIT:30" #1.5 seconds
        - "PARTICLE:WAX_OFF:1:0 %victim%"
    '2':
      chance: 6
      cooldown: 65
      effects:
        - 'CONSOLE_COMMAND:ae giveitem %attacker name% soulgem 1 4'
        - "PARTICLE:FALLING_OBSIDIAN_TEAR:1:0 %victim%"
        - "WAIT:30" #1.5 seconds
        - "PARTICLE:WAX_OFF:1:0 %victim%"
    '3':
      chance: 8
      cooldown: 55
      effects:
        - 'CONSOLE_COMMAND:ae giveitem %attacker name% soulgem 1 4'
        - "PARTICLE:FALLING_OBSIDIAN_TEAR:1:0 %victim%"
        - "WAIT:30" #1.5 seconds
        - "PARTICLE:WAX_OFF:1:0 %victim%"    

### How to reproduce

Make enchants above, try to kill mob/player with shooting of bow.

### "/ae plinfo" link

https://paste.md-5.net/yitediyote

### Server Log

https://mcpaste.io/237e221ba2021873

**Comment by Burchard36** [comment]
Hello Have you tried the `BOW` or `SHOOT_BOW`  type?

You have KILL_PLAYER which will only proc when you kill a player

**Comment by CrystallizedAtrophy** [comment]
Sorry been busy. Why would I want it to proc on bow or shoot bow when I want it only when it kills a player? It supposed to be a bow version of Axe of Spirits. Wouldn't bow/shoot bow work when it hits the player, or you shoot the bow? That seems like a incorrect way of doing the enchant.

axeofspirits:
  display: '%group-color%Axe of Spirits'
  description: "Chance to get more souls\nfrom killing players."
  applies-to: 'Axes'
  type: 'KILL_PLAYER'
  group: 'MASTERY'
  applies:
    - ALL_AXE
  levels:
    1:
      chance: 45
      effects:
        - 'ADD_SOULS:1'
        - 'PARTICLE:HEART:1:0'
    2:
      chance: 65
      effects:
        - 'ADD_SOULS:1'
        - 'PARTICLE:HEART:1:0'
    3:
      chance: 75
      effects:
        - 'ADD_SOULS:1'
        - 'PARTICLE:HEART:1:0'
        
        ^^^ example of what I want but with bows.

**Comment by GC-spigot** [comment]
Use BOW enchant type and condition to check if victim's health - damage is less than or equal to 0
