### ISSUE TITLE
Very critical dupe issue with MORE_DROPS

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2675]
### Describe the bug

ore block was duplicated with silktouch+MORE_DROPS pickaxe

### How to reproduce

enchant pickaxe with MORE_DROPS (AE), silktouch, durability, efficiency.

### Screenshots / Videos

https://www.youtube.com/watch?v=sJTn3lBj7jE

### "/ae plinfo" link

https://paste.md-5.net/gokucixojo

**Comment by NCSV** [comment]
maybe this problems was occured by TPS drop.

**Comment by GC-spigot** [comment]
Can you screenshot the item's lore? So we can see all the data

**Comment by NCSV** [comment]
![1](https://user-images.githubusercontent.com/25452835/157445719-1dd930d3-5cf9-41f8-aa26-69331c23d41d.png)

**Comment by NCSV** [comment]
> ![1](https://user-images.githubusercontent.com/25452835/157445719-1dd930d3-5cf9-41f8-aa26-69331c23d41d.png)
efficiency 5
silktouch
durability 3
MORE_DROPS

(UNBREAKING)

**Comment by GC-spigot** [comment]
MORE_DROPS no longer works with silktouch

**Comment by NCSV** [comment]
> MORE_DROPS no longer works with silktouch

then how to disable MORE_DROPS with SilkTouch?

증식: #영혼 매커니즘 제거하고 수치조정
  display: "%group-color%증식"
  description: "광물 블록 채광시에,\n확률적으로 광물획득량이 늘어납니다."
  applies-to: "곡괭이"
  type: "MINING"
  group: "레전더리"
  applies:
    - ALL_PICKAXE
  not-applyable-with:
    - "SILK_TOUCH"
    - "SILKTOUCH"
  levels:
    1:
      chance: 30
      cooldown: 1
      condition: "%block type% contains ORE : %allow%"
      effects:
        - "MORE_DROPS:2"
      condition:
        - "%has enchantment in hand of SILK_TOUCH% : %deny%"
        - "%has enchantment in hand of SILKTOUCH% : %deny%"
    2:
      chance: 40
      cooldown: 1
      condition: "%block type% contains ORE : %allow%"
      effects:
        - "MORE_DROPS:2"
      condition:
        - "%has enchantment in hand of SILK_TOUCH% : %deny%"
        - "%has enchantment in hand of SILKTOUCH% : %deny%"
    3:
      chance: 50
      cooldown: 1
      condition: "%block type% contains ORE : %allow%"
      effects:
        - "MORE_DROPS:3"
      condition:
        - "%has enchantment in hand of SILK_TOUCH% : %deny%"
        - "%has enchantment in hand of SILKTOUCH% : %deny%"
        
        
i also set like this, but still duplicated with silktouch.
@GC-spigot
