### ISSUE TITLE
/ae claim doesn't work 

### ISSUE THREAD

**Issue by Shad0c** [GC-spigot/AdvancedEnchantments#2676]
### Describe the bug

when creating a custom enchantment and when I try to use /ae claim random numbers it says a an internal error occurred while attempting to perform this command,
![image](https://user-images.githubusercontent.com/101286063/157508223-0fd2b158-07e4-4133-b5cd-f8df1d733542.png)

the console says this: 
![image](https://user-images.githubusercontent.com/101286063/157508289-d0c8f96a-29a9-4b4f-b637-0c7e2a31a28a.png)

my friend said this about it (he knows how to code)
![image](https://user-images.githubusercontent.com/101286063/157508396-4f167999-29dd-469e-aa93-3e6f10a35d4e.png)

### How to reproduce

you just make a custom enchantment and type /ae claim into the chat and it will tell the error

### "/ae plinfo" link

https://paste.md-5.net/wahosixuqe

**Comment by GC-spigot** [comment]
Fixed
