### ISSUE TITLE
silktouch with MORE_DROPS (2)

### ISSUE THREAD

**Issue by NCSV** [GC-spigot/AdvancedEnchantments#2683]
### Describe the bug
8.9.1
i saw your replies. so i disable AE enchantments with silktouch, but can not.
i set this in enchantments.yml, but still apllied with silktouch (  not-applyable-with: ), and worked with silktouch (condition:)

증식: #영혼 매커니즘 제거하고 수치조정
  display: "%group-color%증식"
  description: "광물 블록 채광시에,\n확률적으로 광물획득량이 늘어납니다."
  applies-to: "곡괭이"
  type: "MINING"
  group: "레전더리"
  applies:
    - ALL_PICKAXE
  not-applyable-with:
    - "SILK_TOUCH"
    - "SILKTOUCH"
  levels:
    1:
      chance: 30
      cooldown: 1
      condition:
        - "%has enchantment in hand of SILK_TOUCH% : %deny%"
        - "%has enchantment in hand of SILKTOUCH% : %deny%"
        - "%block type% contains ORE : %allow%"
      effects:
        - "MORE_DROPS:2"
    2:
      chance: 40
      cooldown: 1
      condition:
        - "%has enchantment in hand of SILK_TOUCH% : %deny%"
        - "%has enchantment in hand of SILKTOUCH% : %deny%"
        - "%block type% contains ORE : %allow%"
      effects:
        - "MORE_DROPS:2"
    3:
      chance: 50
      cooldown: 1
      condition:
        - "%has enchantment in hand of SILK_TOUCH% : %deny%"
        - "%has enchantment in hand of SILKTOUCH% : %deny%"
        - "%block type% contains ORE : %allow%"
      effects:
        - "MORE_DROPS:3"

### How to reproduce

can you disable enchantments with silktouch

### "/ae plinfo" link

https://paste.md-5.net/cehofagese

**Comment by NCSV** [comment]
+ version of AE is 8.9.1, but ae plinfo printed 8.9.0

**Comment by GC-spigot** [comment]
It will still apply with silktouch, but it won't waork. I added more checks but there's no way it works now if item has silktouch
