### ISSUE TITLE
Issue with Alchemist

### ISSUE THREAD

**Issue by YKDZ** [GC-spigot/AdvancedEnchantments#2684]
### Describe the bug

When I click the item in Alchemist GUI, for example, the black stained glass pane used as gui edge, or the white stained glass pane used as preview slot placeholder, message "Alchemist doesn't accept this item." will appear.
But this message should only appear when I click a wrong item in my own inventory.

### How to reproduce

1. Open the Alchemist GUI
2. Click the gui item
3. Find message appear

### "/ae plinfo" link

https://paste.md-5.net/ayerizefef

**Comment by GC-spigot** [comment]
Fixed
