### ISSUE TITLE
TP_DROPS doesn't work with mcMMO double drops

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2685]
### Describe the bug

If you have mine a ore with TP_DROPS, the double drops from mcMMO doens't work.

### How to reproduce

1. Create a enchantment with TP_DROPS effect;
2. Set your minig mcmmo level to max; (/mmoedit name minig 1000)
3. Mine a ore.

Result = You don't gain any extra ore (tested with all of them, iron, diamond, copper, gold..)

### "/ae plinfo" link

https://paste.md-5.net/hoseroquzo

**Comment by dinobossytnew** [comment]
Update the new version of the plugin and test if it works for you.

**Comment by austv** [comment]
> Update the new version of the plugin and test if it works for you.

Nop, tried the 8.9.2 and same problem. The problem is with mcMMO double drops.

**Comment by Burchard36** [comment]
TP_DROPS now works with McMMO's Double drop system for the MINING skill

**Comment by Burchard36** [comment]
Update is out and they now work
