### ISSUE TITLE
<aoe> effects were not applied players after hit by monster.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2687]
### Describe the bug

this enchant is  debuff enchantment.
It usually works well, but stops working when it is hit by a monster. (maybe monster's debuff)

수호자:
  display: '%group-color%수호자'
  description: "15초마다 범위 내 플레이어의 \n상태이상을 치료하고 소량 회복시킵니다."
  applies-to: '투구'
  type: 'REPEATING'
  time: 15
  group: '에픽'
  applies:
    - 'ALL_HELMET'
  levels:
    '1':
      effects:
        - 'ACTIONBAR:&a&l수호자&c&lI <aoe> radius=3 target=all </aoe>'
        - 'ACTIONBAR:&a&l수호자&c&lI'
        - 'ADD_HEALTH:4'
        - 'ADD_HEALTH:2 <aoe> radius=3 target=all </aoe>'
        - 'CURE:POISON <aoe> radius=3 target=all </aoe>'
        - 'CURE:NAUSEA <aoe> radius=3 target=all </aoe>'
        - 'CURE:WITHER <aoe> radius=3 target=all </aoe>'
        - 'CURE:SLOW <aoe> radius=3 target=all </aoe>'
    '2':
      effects:
        - 'ACTIONBAR:&7*&b수호자II&7* <aoe> radius=4 target=all </aoe>'
        - "ACTIONBAR:&7*&b수호자II&7*"
        - 'ADD_HEALTH:4'
        - 'ADD_HEALTH:2 <aoe> radius=4 target=all </aoe>'
        - 'CURE:POISON <aoe> radius=4 target=all </aoe>'
        - 'CURE:NAUSEA <aoe> radius=4 target=all </aoe>'
        - 'CURE:WITHER <aoe> radius=4 target=all </aoe>'
        - 'CURE:SLOW <aoe> radius=4 target=all </aoe>'
    '3':
      effects:
        - 'ACTIONBAR:&7*&b수호자III&7* <aoe> radius=4 target=all </aoe>'
        - "ACTIONBAR:&7*&b수호자III&7*"
        - 'ADD_HEALTH:6'
        - 'ADD_HEALTH:4 <aoe> radius=4 target=all </aoe>'
        - 'CURE:POISON <aoe> radius=4 target=all </aoe>'
        - 'CURE:NAUSEA <aoe> radius=4 target=all </aoe>'
        - 'CURE:WITHER <aoe> radius=4 target=all </aoe>'
        - 'CURE:SLOW <aoe> radius=4 target=all </aoe>'
    '4':
      effects:
        - 'ACTIONBAR:&7*&b수호자IV&7* <aoe> radius=5 target=all </aoe>'
        - "ACTIONBAR:&7*&b수호자IV&7*"
        - 'ADD_HEALTH:6'
        - 'ADD_HEALTH:4 <aoe> radius=5 target=all </aoe>'
        - 'CURE:POISON <aoe> radius=5 target=all </aoe>'
        - 'CURE:NAUSEA <aoe> radius=5 target=all </aoe>'
        - 'CURE:WITHER <aoe> radius=5 target=all </aoe>'
        - 'CURE:SLOW <aoe> radius=5 target=all </aoe>'
    '5':
      effects:
        - 'ACTIONBAR:&7*&b수호자V&7* <aoe> radius=5 target=all </aoe>'
        - "ACTIONBAR:&7*&b수호자V&7*"
        - 'ADD_HEALTH:8'
        - 'ADD_HEALTH:4 <aoe> radius=5 target=all </aoe>'
        - 'CURE:POISON <aoe> radius=5 target=all </aoe>'
        - 'CURE:NAUSEA <aoe> radius=5 target=all </aoe>'
        - 'CURE:WITHER <aoe> radius=5 target=all </aoe>'
        - 'CURE:SLOW <aoe> radius=5 target=all </aoe>'

### How to reproduce

make same enchantment and hit by monster

### "/ae plinfo" link

https://paste.md-5.net/kayaqeqepu

**Comment by CrystallizedAtrophy** [comment]
All = players that are able to be damaged and ones that aren't supposed to be damaged.. "friendlies" like in factions. If you want both players and mobs you need to add <aoe> target=mobs </aoe> with the same effects. 'CURE:SLOW <aoe> radius=5 target=mobs </aoe> ' as an example
