### ISSUE TITLE
Blocktrak NBT Dupe 2

### ISSUE THREAD

**Issue by ryankayz7** [GC-spigot/AdvancedEnchantments#2689]
### Describe the bug

Hey, so I managed to re-replicate #2663 without the unbreakable enchant but with trench. I wonder if this has to do with items repairing as that was what unbreakable had and trench's issue too. I couldn't re-replicate my previous issue with the same conditions however I managed to cause the same bug to happen with only the trench enchantment and the blocktrak item. This has been pictured below. version used is 8.9.2.

https://gyazo.com/ff1fb5d6242f19794938ff40e6346b9a

Trench enchant is as followed:
trench:
display: "%group-color%Trench"
description: "Chance to break in 3x3 area."
applies-to: "Pickaxes, Shovels"
type: "MINING"
group: "GOLD"
applies:
- ALL_PICKAXE
- ALL_SPADE
levels:
1:
chance: 4
effects:
- "TRENCH:3"
- "TP_DROPS"
- 'ADD_DURABILITY_CURRENT_ITEM:-15'
2:
chance: 8
effects:
- "TRENCH:3"
- "TP_DROPS"
- 'ADD_DURABILITY_CURRENT_ITEM:-15'
3:
chance: 12
effects:
- "TRENCH:3"
- "TP_DROPS"
- 'ADD_DURABILITY_CURRENT_ITEM:-15'
4:
chance: 16
effects:
- "TRENCH:3"
- "TP_DROPS"
- 'ADD_DURABILITY_CURRENT_ITEM:-15'
5:
chance: 20
effects:
- "TRENCH:3"
- "TP_DROPS"
- 'ADD_DURABILITY_CURRENT_ITEM:-15'

 I change trench to this and I was not able to replicate it.

trench:
display: "%group-color%Trench"
description: "Chance to break in 3x3 area."
applies-to: "Pickaxes, Shovels"
type: "MINING"
group: "GOLD"
applies:
- ALL_PICKAXE
- ALL_SPADE
levels:
1:
chance: 4
effects:
- "TRENCH:3"
- "TP_DROPS"
2:
chance: 8
effects:
- "TRENCH:3"
- "TP_DROPS"
3:
chance: 12
effects:
- "TRENCH:3"
- "TP_DROPS"
4:
chance: 16
effects:
- "TRENCH:3"
- "TP_DROPS"
5:
chance: 20
effects:
- "TRENCH:3"
- "TP_DROPS"

### How to reproduce

Add the trench enchantment on and after the trench block break there will be extra blocktrak lore.

### Screenshots / Videos

https://gyazo.com/ff1fb5d6242f19794938ff40e6346b9a

### "/ae plinfo" link

https://paste.md-5.net/vepateyuhi

**Comment by Burchard36** [comment]
Fixed! Will be added in 8.9.11

GC is currently away on vacation so this version may take a few days to get out, apologies for that

Also apologies for this issue going without response for so long, I am one of the newer devs for AdvancedEnchantments to im only just now getting around to this :)
