### ISSUE TITLE
Enchantment error, ore smelting

### ISSUE THREAD

**Issue by xmakdwerd** [GC-spigot/AdvancedEnchantments#2691]
### Describe the bug

levels:
    1:
      chance: 33
      effects:
        - "SMELT"
    2:
      chance: 66
      effects:
        - "SMELT"
    3:
      chance: 100
      effects:
        - "SMELT"
I have here this charm works not quite correctly. In new versions, luck affects iron ore, but for some reason it always turns out one ore ... although it should work like with diamonds
for example, it works well with copper ore, but it works badly with iron, there is always a chance even with luck 3, the chance is only to get 1 iron ore, same with gold ore
kernel version 1.17.1

### How to reproduce

I have here this charm works not quite correctly. In new versions, luck affects iron ore, but for some reason it always turns out one ore ... although it should work like with diamonds
for example, it works well with copper ore, but it works badly with iron, there is always a chance even with luck 3, the chance is only to get 1 iron ore, same with gold ore
kernel version 1.17.1

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by Burchard36** [comment]
Issue was resolved in discord, simply was missing the config setting: `settings.fortune-works-on-iron-gold` it was set to false instead of true

A fix will be implemented next bug patch, where the setting will default to true if the version of minecraft is 1.17 or higher

**Comment by Burchard36** [comment]
After further research, I was able to confirm this as a bug, it has been fixed and will be applied next bug patch.

Video: https://youtu.be/smzXnm9UlOY

**Comment by Burchard36** [comment]
This will be fixed when 8.9.9 has been released onto spigot/ae.net. Please allow a few hours for this to be uploaded, have a nice day!
