### ISSUE TITLE
Whitescroll not working properly (really harmful bug)

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2692]
### Describe the bug

Basically, if you will upgrade the book, whitescroll doesn't work properly. But if it is a new enchant, it does.
config to break item and removed the whitescroll = true

### How to reproduce

1. apply whitescroll on it a item without ae enchantments
2. add a enchant book with 0% sucess rate
3. whitescroll get remove properly

But, if you do 
1. add a enchant (level 1) to a item
2. apply whitescroll on it
3. add the same enchant using a book with 0% sucess rate
4. whitescroll is not being removed.

### "/ae plinfo" link

https://paste.md-5.net/ezadahekab

**Comment by Burchard36** [comment]
Confirmed this myself when i tried yet, couldn't find any immediate fixes for it but will update you accordingly
