### ISSUE TITLE
Villager trading orb higher than configured max

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2696]
### Describe the bug

We have the plugin configured to give items 3 enchantment slots by default, and allow a maximum of 7 enchantment slots with orbs applied. Today a player rolled a villager that is trading a +5 orb which sets the enchantment slots on an item to 8.

### How to reproduce

Continue to re-place a lectern near a villager until it trades an illegal orb. This will likely be extremely rare as we've only seen this happen once so far in the couple of months we've been running this plugin.

### Screenshots / Videos

https://i.ibb.co/3fpcP2Q/image.png
https://i.ibb.co/PG1cQLj/image.png

### "/ae plinfo" link

https://paste.md-5.net/pirugufedo

**Comment by GC-spigot** [comment]
Fixed
