### ISSUE TITLE
Error on enchantments

### ISSUE THREAD

**Issue by FrontierGamers** [GC-spigot/AdvancedEnchantments#270]
30.12 23:03:18 [Server] ERROR Could not pass event PlayerInteractEvent to AdvancedEnchantments v5.0.6
30.12 23:03:18 [Server] INFO org.bukkit.event.EventException
30.12 23:03:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:248) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:215) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:603) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
30.12 23:03:18 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
30.12 23:03:18 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:427) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
30.12 23:03:18 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/entity/BoardColl
30.12 23:03:18 [Server] INFO at n3kas.ae.hooks.a.a(a.java:31) ~[?:?]
30.12 23:03:18 [Server] INFO at n3kas.ae.enchanttypes.k.a(k.java:68) ~[?:?]
30.12 23:03:18 [Server] INFO at sun.reflect.GeneratedMethodAccessor389.invoke(Unknown Source) ~[?:?]
30.12 23:03:18 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
30.12 23:03:18 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
30.12 23:03:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[custom.jar:git-TacoSpigot-bf023c7d]
30.12 23:03:19 [Multicraft] Skipped 37 lines due to rate limit (30/s)

**Comment by GC-spigot** [comment]
Will be fixed now.
