### ISSUE TITLE
Ability to repair items with damaged items

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#2700]
### Describe the bug

I can for example repair a damaged diamond pickaxe with a damaged stone pickaxe.
It won't work with an undamaged stone pickaxe but as soon as it's taken damage, I can repair it.

### How to reproduce

Get diamond pickaxe, get stone pickaxe.
Break a block with diamond pickaxe, break a block with stone pickaxe (so both have at least 1 damage).

Put diamond pickaxe and stone pickaxe in anvil.
It even works with items which don't match such as a diamond sword and a stone pickaxe.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/39222968/159137212-b522a44c-8e0f-4f1e-8ca0-6c6ef767e804.png)

### "/ae plinfo" link

https://paste.md-5.net/axekucuyit

### Server Log

https://mcpaste.io/d6a646de81350df7

**Comment by Burchard36** [comment]
![image](https://user-images.githubusercontent.com/48583030/163701910-cce24586-3a0e-48c7-ba28-798d3439bd80.png)

Should be fixed! 8.9.14 when its out, apologies for the late response on this bug report!

**Comment by Burchard36** [comment]
Fix was added, if you have an issue please open a new issue request mentioning this one
