### ISSUE TITLE
Plant Seeds not working

### ISSUE THREAD

**Issue by DuneSciFye** [GC-spigot/AdvancedEnchantments#2702]
### Describe the bug

The effect "PLANT_SEEDS" isn't working. I've updated to latest version and tested with default carrotplanter enchant, still not working.

### How to reproduce

Test out carrot planter enchantment

### "/ae plinfo" link

https://paste.md-5.net/ujizosofed

**Comment by Burchard36** [comment]
Works good for me! Maybe you do not have a high enough light level? Maybe there is no water? PLANT_SEEDS only work if you are able to plant seeds manually (IE You need enough light level and a water source nearby). Also make sure your holding the hoe you enchant with the PLANT_SEEDS enchant with, as it wont work without it (Unless you make lets say and armor set with it)

Can you provide us with any more information? The information you posted is very vague, a video would be nice of you trying to use this enchantment and it not working

Heres a video if it working for me: https://youtu.be/wn1boLWJcFU

**Comment by DuneSciFye** [comment]
I tried this on Paper software, without any other plugins installed, fresh AE folder + jar, 8.9.10 version

https://user-images.githubusercontent.com/65089425/161167719-d3b6b3e4-7a1e-4879-b35a-21e26914e74a.mp4

**Comment by DuneSciFye** [comment]
This still isn’t working for me, but probably something on my end.
