### ISSUE TITLE
Armor Dupe Bug

### ISSUE THREAD

**Issue by zwrumpy** [GC-spigot/AdvancedEnchantments#2704]
### Describe the bug

armor dupe bug:

Tested server versions:
    - paper 1.18.2 java 
    - nachospigot paper 1.8.8
    - mcpe geyser spigot

AE versions: 
   - 8.9.5 and 8.9.6

### How to reproduce

Steps to reproduce bug:

1. no armor equiped
2. armor on hotbar then right click to equip
3. you can throw item on hotbar
4. result 1 armor on hotbar and 1 armor on equipped slot

### Screenshots / Videos

video link: 
www.youtube.com/watch?v=oN5mbKKTE7

### "/ae plinfo" link

https://paste.md-5.net/lesalehemo

**Comment by zwrumpy** [comment]
bug fixed:

quick fix 1 (non faction server): deleting old libraries folder, versions folder and updating to later papermc 1.18.2

quick fix 2: (faction server): disable armor switch on corex folder > config

thanks to DuneSciFye at AE discord support

**Comment by DuneSciFye** [comment]
@Firosee Close this
