### ISSUE TITLE
Advanced Enchantments and Custom Model Data not rendering Armor textures for Armor Sets.

### ISSUE THREAD

**Issue by Alphatoxic** [GC-spigot/AdvancedEnchantments#2705]
### Describe the bug

To begin, this issue involves the two following plugins: Itemsadder and Advancedenchantments. I have determined that the issue resides within Advanced Enchantments however I am unsure. I am seeking to create armor sets within the AdvancedEnchantments (AE from here on out) plugin. I want to pair these custom armor sets with custom armor textures from Itemsadder (IA from here on out). To begin the diagnosis, I investigated if the issue was with IA. To do this, I looked at the textures of the physical items of the armor. See Figures 1 and 2. Besides the obvious lack of vanilla enchantments on the set from IA in Figure 2, the textures of the items are identical. The issue does not reside within the Custom Model Data itself since the actual  textures of the items match from the two plugins. The armor texture is not rendered when they are worn on a player. Figure 3 and 4 is where I am wearing the AE armor with the IA textures (excuse my skin). To show that the armor textures do actually render with IA, see Figures 6 and 7. To identify how this is possible, an understanding on how IA's armor works, so I will provide the WIKI pages regarding armor rendering.

Here is a Link on how to add the armor from IA - 
https://itemsadder.devs.beer/plugin-usage/advanced/creating-a-custom-item/armor

Here is a Link on how to render the armor in-game from IA - 
https://itemsadder.devs.beer/plugin-usage/advanced/armors/texture

After understanding how the textures of the IA armor works (I honestly do not fully understand myself), Here is the configurations for both the IA armors, and the asets yml.

IA Druid Armor CONFIG - 

info:
  namespace: druidarmor
armors_rendering:
  druid_armor:
    color: "#84fc03"
    layer_1: druid/layer_1
    layer_2: druid/layer_2
    use_color: false
items:
  druidhelmet:
    display_name: Floral Wreathe
    permission: cosmetic_armors.druid_armor
    resource:
      generate: true
      model_id: 88601
      textures:
      - druid/helmet
    durability:
      max_custom_durability: 417
    specific_properties:
      armor:
        slot: head
        custom_armor: druid_armor
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
  druidchestplate:
    display_name: Druid Chestplate
    permission: cosmetic_armors.druid_armor
    resource:
      generate: true
      model_id: 88602
      textures:
      - druid/chestplate
    durability:
      max_custom_durability: 602
    specific_properties:
      armor:
        slot: chest
        custom_armor: druid_armor
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
  druidleggings:
    display_name: Druid Leggings
    permission: cosmetic_armors.druid_armor
    resource:
      generate: true
      model_id: 88603
      textures:
      - druid/leggings
    durability:
      max_custom_durability: 565
    specific_properties:
      armor:
        slot: legs
        custom_armor: druid_armor
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
  druidboots:
    display_name: Druid Boots
    permission: cosmetic_armors.druid_armor
    resource:
      generate: true
      model_id: 88604
      textures:
      - druid/boots
    durability:
      max_custom_durability: 491
    specific_properties:
      armor:
        slot: FEET
        custom_armor: druid_armor
    attribute_modifiers:
      feet:
        armor: 4
        armorToughness: 3

AE Armor set CONFIG - 

name: '&5&lDruid Armor'
material: LEATHER
settings:
  equipped:
    - '&a&l(!) &aYou have activated the Druid Armor Set!'
  unequipped:
    - '&c&l(!) &cYou have deactivated the Druid Armor Set!'
items:
  helmet:
    name: '&5&lFloral Wreathe'
    # If you want this item to be a player head, uncomment this line
    #owner: "name"
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 88601
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
    enchants: # Supports AdvancedEnchantments CE
      - "protection:4"
      - "unbreaking:3"
  chestplate:
    name: '&2&lDruid Chestplate'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 88602
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
    enchants: # Supports AdvancedEnchantments CE
      - "protection:4"
      - "unbreaking:3"
  leggings:
    name: '&2&lDruid Leggings'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 88603
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
    enchants: # Supports AdvancedEnchantments CE
      - "protection:4"
      - "unbreaking:3"
  boots:
    name: '&2&lDruid Boots'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 88604
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
    enchants: # Supports AdvancedEnchantments CE
      - "protection:4"
      - "unbreaking:3"
events:
  FALL_DAMAGE:
    chance: 100
    effects:
      - 'STOP_ATTACK'

The important places to look can be seen in Figures 7 - 14.

All of the custom model datas match, the armor, when attained via IA, renders when worn, the only issue is when the asets armor is worn.

### How to reproduce

1. Install the latest version of LoneLibs, Itemsadder, AE and its dependencies (if any).
2. Configure a set of custom armor using the armor renderer from IA.
3. Match the Custom Model Data into the Asets yml.
4. Wear the custom armor from AE

### Screenshots / Videos

Figure 1 - Items from AE with the IA textures - 
![image](https://user-images.githubusercontent.com/98225467/159598857-d257049d-5eb6-42d5-9318-372575075bec.png)
Figure 2 - Items from IA with the IA textures - 
![image](https://user-images.githubusercontent.com/98225467/159598915-77bc60f0-5816-4345-a752-855fcd7c8bbc.png)
Figure 3 - Front of worn Armor from AE with IA textures -
![image](https://user-images.githubusercontent.com/98225467/159599142-16b02215-0bbf-4f9f-a523-43186892e2a7.png)
Figure 4 - Rear of worn Armor from AE with IA textures - 
![image](https://user-images.githubusercontent.com/98225467/159599207-cca4166f-42e4-4376-9675-d6c78a30b10e.png)
Figure 5 - Front of worn Armor from IA with IA textures - 
![image](https://user-images.githubusercontent.com/98225467/159599319-cf163ee5-27ee-4cb1-a102-0aafa9ec4bec.png)
Figure 6 - Rear of worn Armor from IA with IA textures - 
![image](https://user-images.githubusercontent.com/98225467/159599410-e4b3307e-909c-4039-ad2a-46e8ec118ea2.png)
Figure 7 - Custom Model Data section from Druid Helmet IA CONFIG - 
![image](https://user-images.githubusercontent.com/98225467/159600889-60961d4a-9bf4-4087-929e-00966195e2bd.png)
Figure 8 - Custom Model Data section from Druid Chestplate IA CONFIG - 
![image](https://user-images.githubusercontent.com/98225467/159600835-838d6321-16b7-4e60-a484-e026cc79283e.png)
Figure 9 - Custom Model Data section from Druid Leggings IA CONFIG - 
![image](https://user-images.githubusercontent.com/98225467/159600778-1e5050d3-f259-4f17-951d-4f77132c2575.png)
Figure 10 - Custom Model Data section from Druid Boots IA CONFIG - 
![image](https://user-images.githubusercontent.com/98225467/159600810-2da8cc8b-ebb6-4f2c-ba91-0c1727dd0b8f.png)
Figure 11 - Custom Model Data section from Druid Helmet AE CONFIG - 
![image](https://user-images.githubusercontent.com/98225467/159600360-33b80368-d531-40f3-84af-c4297d68cd5e.png)
Figure 12 - Custom Model Data section from Druid Chestplate AE CONFIG - 
![image](https://user-images.githubusercontent.com/98225467/159600622-c9dcafcd-225a-4a72-982c-ff5156945337.png)
Figure 13 - Custom Model Data section from Druid Leggings AE CONFIG - 
![image](https://user-images.githubusercontent.com/98225467/159600444-8f75b74d-1b6b-4182-9a92-5a8ac13eb58b.png)
Figure 14 - Custom Model Data section from Druid Boots AE CONFIG - 
![image](https://user-images.githubusercontent.com/98225467/159600424-74b2b0bd-f91a-4004-94b3-4a8cb6cc08da.png)

### "/ae plinfo" link

https://paste.md-5.net/peramagehe

### Server Log

https://mcpaste.io/e75946dcfdf079bf

**Comment by DuneSciFye** [comment]
To sum it up, custom model textures made with Item Adder won't display when wearing the armor

**Comment by Burchard36** [comment]
Hello, in my past experiences with Armor Models, you need optifine installed on your end in order to render these. Have you tried installing optifine and doing them this way?

I have no experience in ItemsAdder, but I do with CustomItems, and with that plugin you need Optifine installed with armor sets installed to the server side texture pack (And i assume with any other plugin that add custom models to the game for armor)

Have you tried running only ItemsAdder on your server, and validating that they work this way?

Hope to see a response from you :)

**Comment by DuneSciFye** [comment]
@Burchard36 Close this one, Alpha isn't needing it anymore, I've talked with him
