### ISSUE TITLE
REMOVE_ENCHANT effect not working as intended

### ISSUE THREAD

**Issue by DuneSciFye** [GC-spigot/AdvancedEnchantments#2708]
### Describe the bug

When using the REMOVE_ENCHANT effect, it remove's the enchant of the held item rather than the item the enchant was activated upon

### How to reproduce

1. Have an enchantment that has the REMOVE_ENCHANT effect for an armor piece
2. Equip the armor piece
3. The enchant isn't removed, but it is activated (you can see it was activated via debug mode)
4. If you hold another item with the enchantment it's supposed to remove, it will remove it

### "/ae plinfo" link

 https://paste.md-5.net/fahogopuja

**Comment by GC-spigot** [comment]
Fixed
