### ISSUE TITLE
Errors after the update

### ISSUE THREAD

**Issue by Frostyeiz** [GC-spigot/AdvancedEnchantments#271]
> [15:59:19 INFO]: [AdvancedEnchantments ERROR] Could not pass IllegalArgumentException: No enum constant n3kas.ae.effectsreader.EffectType.LIGHTNING %ATTACKER%
> [15:59:19 INFO]:    Class: n3kas.ae.effectsreader.EffectType.valueOf(EffectType.java:1)
> [15:59:19 INFO]:    Extra info: Effect[DEFENSE_BOW], enchant[stormcaller]; mc[112]; ae[5.1.2]
>
> **This happened with all enchant that use LIGHTNING effect**
>
> stormcaller:
>   display: '%group-color%Stormcaller'
>   description: "A"
>   applies-to: 'Armor'
>   type: 'DEFENSE;DEFENSE_BOW'
>   group: 'ELITE'
>   applies:
>   - ALL_ARMOR
>   levels:
>     1:
>       chance: 17
>       cooldown: 4
>       effects:
>       - 'LIGHTNING %attacker%'
>       - 'EXTINGUISH %attacker%'
>     2:
>       chance: 23
>       cooldown: 5
>       effects:
>       - 'LIGHTNING %attacker%'
>       - 'EXTINGUISH %attacker%'
>     3:
>       chance: 31
>       cooldown: 5
>       effects:
>       - 'LIGHTNING %attacker%'
>       - 'EXTINGUISH %attacker%'
>     4:
>       chance: 41
>       cooldown: 5
>       effects:
>       - 'LIGHTNING %attacker%'
>       - 'EXTINGUISH %attacker%'

> [15:30:17] [Server thread/INFO]: [AdvancedEnchantments ERROR] Could not pass IllegalArgumentException: No enum constant n3kas.ae.effectsreader.EffectType.DROP_HEAD %VICTIM%
> [15:30:17] [Server thread/INFO]: [AdvancedEnchantments]    Class: n3kas.ae.effectsreader.EffectType.valueOf(EffectType.java:1)
> [15:30:17] [Server thread/INFO]: [AdvancedEnchantments]    Extra info: Effect[KILL_PLAYER], enchant[decapitation]; mc[112]; ae[5.1.2]
> [15:30:17] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
> 
> 
> decapitation:
>   display: '%group-color%Decapitation'
>   description: "a"
>   applies-to: 'Axe'
>   type: 'KILL_PLAYER'
>   group: 'SIMPLE'
>   applies:
>   - ALL_AXE
>   levels:
>     1:
>       chance: 20
>       effects:
>       - 'DROP_HEAD %victim%'
>     2:
>       chance: 40
>       effects:
>       - 'DROP_HEAD %victim%'
>     3:
>       chance: 60
>       effects:
>       - 'DROP_HEAD %victim%'

> [15:42:26] [Server thread/INFO]: [AdvancedEnchantments ERROR] Could not pass IllegalArgumentException: No enum constant n3kas.ae.effectsreader.EffectType.TELEPORT_BEHIND %VICTIM%
> [15:42:26] [Server thread/INFO]: [AdvancedEnchantments]    Class: n3kas.ae.effectsreader.EffectType.valueOf(EffectType.java:1)
> [15:42:26] [Server thread/INFO]: [AdvancedEnchantments]    Extra info: Effect[DEFENSE], enchant[trickster]; mc[112]; ae[5.1.2]
> [15:42:26] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
> 
> **I changed %VICTIM% to %ATTACKER%, but the error still appear.
> 
> trickster:
>   display: '%group-color%Trickster'
>   description: "D"
>   applies-to: 'Amor'
>   type: 'DEFENSE'
>   group: 'ELITE'
>   applies:
>   - ALL_ARMOR
>   levels:
>     1:
>       chance: 8
>       cooldown: 5
>       effects:
>       - 'TELEPORT_BEHIND %attacker%'
>       - 'MESSAGE:&e&l* WOSSH * %victim%'
>     2:
>       chance: 14
>       cooldown: 5
>       effects:
>       - 'TELEPORT_BEHIND %attacker%'
>     3:
>       chance: 17
>       cooldown: 5
>       effects:
>       - 'TELEPORT_BEHIND %attacker%'
>     4:
>       chance: 21
>       cooldown: 5
>       effects:
>       - 'TELEPORT_BEHIND %attacker%'
>     5:
>       chance: 29
>       cooldown: 5
>       effects:
>       - 'TELEPORT_BEHIND %attacker%'
>     6:
>       chance: 37
>       cooldown: 5
>       effects:
>       - 'TELEPORT_BEHIND %attacker%'
>     7:
>       chance: 46
>       cooldown: 5
>       effects:
>       - 'TELEPORT_BEHIND %attacker%'
>     8:
>       chance: 51
>       cooldown: 5
>       effects:
>       - 'TELEPORT_BEHIND %attacker%'
>       - 'MESSAGE:&e&l* WOSSH * %victim%'

> [15:57:04] [Server thread/INFO]: [AdvancedEnchantments ERROR] Could not pass IllegalArgumentException: Health must be between 0 and 48.5, but was 49.5. (attribute base value: 36.5, player: Pluto)
> [15:57:04] [Server thread/INFO]: [AdvancedEnchantments]    Class: n3kas.ae.effectsreader.RunnableEffect.b(RunnableEffect.java:1473)
> [15:57:04] [Server thread/INFO]: [AdvancedEnchantments]    Extra info: effect[INCREASE_DAMAGE:63]; enchant[bleed]; mc[112]; ae[5.1.2]
> [15:57:04] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
> 
> bleed:
>   display: '%group-color%Bleed'
>   description: "B"
>   applies-to: 'Axe'
>   type: 'ATTACK'
>   group: 'ULTIMATE'
>   applies:
>   - ALL_AXE
>   levels:
>     1:
>       chance: 8
>       cooldown: 10
>       effects:
>       - 'POTION:SLOW:0:25 %victim%'
>       - 'INCREASE_DAMAGE:<random number>25-50</random number> %victim%'
>       - 'MESSAGE:&4BLEED! %victim%'
>       - 'WAIT:20'
>       - 'ADD_HARM:1 %victim%'
>     2:
>       chance: 15
>       cooldown: 10
>       effects:
>       - 'POTION:SLOW:0:25 %victim%'
>       - 'INCREASE_DAMAGE:<random number>35-50</random number> %victim%'
>       - 'MESSAGE:&4BLEED! %victim%'
>       - 'WAIT:20'
>       - 'ADD_HARM:1 %victim%'
>     3:
>       chance: 23
>       cooldown: 10
>       effects:
>       - 'POTION:SLOW:0:50 %victim%'
>       - 'INCREASE_DAMAGE:<random number>45-50</random number> %victim%'
>       - 'MESSAGE:&4BLEED! %victim%'
>       - 'WAIT:20'
>       - 'ADD_HARM:1 %victim%'
>     4:
>       chance: 30
>       cooldown: 10
>       effects:
>       - 'POTION:SLOW:0:50 %victim%'
>       - 'INCREASE_DAMAGE:<random number>45-50</random number> %victim%'
>       - 'MESSAGE:&4BLEED! %victim%'
>       - 'WAIT:20'
>       - 'ADD_HARM:2 %victim%'
>     5:
>       chance: 44
>       cooldown: 10
>       effects:
>       - 'POTION:SLOW:1:25 %victim%'
>       - 'INCREASE_DAMAGE:<random number>50-55</random number> %victim%'
>       - 'MESSAGE:&4BLEED! %victim%'
>       - 'WAIT:20'
>       - 'ADD_HARM:2 %victim%'
>     6:
>       chance: 60
>       cooldown: 10
>       effects:
>       - 'POTION:SLOW:1:25 %victim%'
>       - 'INCREASE_DAMAGE:<random number>50-65</random number> %victim%'
>       - 'MESSAGE:&4BLEED! %victim%'
>       - 'WAIT:20'
>       - 'ADD_HARM:2 %victim%'

**Comment by GC-spigot** [comment]
Fixing right now.
