### ISSUE TITLE
REVIVE Effect not working 

### ISSUE THREAD

**Issue by DuneSciFye** [GC-spigot/AdvancedEnchantments#2711]
### Describe the bug

The REVIVE effect doesn't revive the player, simply does nothing

### How to reproduce

Have an armor piece with REVIVE effect, get killed, don't get revived

### "/ae plinfo" link

.

**Comment by Burchard36** [comment]
This has been fixed for 8.9.11

Currently GC is away so we are unable actually push this to spigotmc or ae.net

Should hopefully be uploaded within the week!

Have a nice day!

**Comment by Burchard36** [comment]
8.9.11 is out now! Please update to the latest version :)

If you have any new issues please open a new issue request!
