### ISSUE TITLE
SMELT effect duplicating blocks with AutoPickup plugin

### ISSUE THREAD

**Issue by DuneSciFye** [GC-spigot/AdvancedEnchantments#2712]
### Describe the bug

When you have another plugin that has AutoPickup, and it's enabled, when mining anything with Smelt it duplicated it. This is only when smelt gets activated and only when auto pickup is enabled. If AutoPickup is disabled nothing happens. The auto pickup plugin I used for this is https://www.spigotmc.org/resources/autopickup-1-18-support.70157/

Also I tried this with a condition to check if the block was a ore, and that then only duplicated ores. It gave me one iron ingots and 1 raw iron, farther confirming that this only happens when the smelt effect activates

### How to reproduce

Have AutoPickup plugin
Enable AutoPickup
Get a pickaxe with smelt enchant
For testing turn chance to 100 and cooldown to 0, with no condition
Mine any block in game

### "/ae plinfo" link

Unable to log into panel at this time, will send later

**Comment by Burchard36** [comment]
After various testing and talks with the developer of this plugin, we beileve this is an issue with his plugin.

I will update you accordingly for any fixes we or him implement, thank you for the bug report!

**Comment by Burchard36** [comment]
Hello, support for this plugin has been added: https://youtu.be/ckDmt75cCWs

Expect to see this fix in one of the future bug fix updates

Please note, support for other AutoPickup plugins are currently not added, we cannot add support for all of them directly as there is different ways each AutoPickup plugins functions, but the one listed in your issue has support added

**Comment by Burchard36** [comment]
Support for this plugin has been added to 8.9.9, please let this take a few hours for the verison to be available for download, have a nice day!
