### ISSUE TITLE
[Spigot 1.8.8] TRENCH do not work on shovels

### ISSUE THREAD

**Issue by guidonofrio** [GC-spigot/AdvancedEnchantments#2713]
### Describe the bug

TRENCH do not work on shovels in the update v8.9.6

### How to reproduce

Use an enchant using TRENCH effect with a shovel

### "/ae plinfo" link

https://paste.md-5.net/kananuvego

**Comment by Burchard36** [comment]
Hello, looked into this and can confirm that they do not work on 1.8.8 for some odd reason, the issue will be getting looked into soon

Cant guarantee we will have a fix in the next release, but after that we should hopefully have a fix :)

**Comment by Burchard36** [comment]
Hello, this bug will be fixed for 1.8.8, 1.9, 1.10, 1.11, and 1.12 in version 8.9.11

Please allow a few hours for this version to reach the website/spigot MC and update from there :)

**Comment by guidonofrio** [comment]
Thank You Burchard!! I am waiting

**Comment by Burchard36** [comment]
8.9.11 is out now! Please update to the latest version :)

If you have any new issues please open a new issue request!

Apologies for the wait GC had went on vacation on the same day i had fixed this :P
