### ISSUE TITLE
TRENCH let's you obtain infested silverfish blocks.

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2716]
### Describe the bug

players are able to obtain silverfish infested blocks by using the "trench" enchant on regular blocks near an infested block

### How to reproduce

using the "trench" enchant on regular blocks near an infested block

### "/ae plinfo" link

https://paste.md-5.net/pirugufedo

**Comment by Burchard36** [comment]
Hello there, have you tried adding these block(s) to the trench-blacklist, I can confirm when this is not added you do receive the infested block, but when added to the blacklist the block will not break and it wont be added to the players inventory

This config option can be found in `config.yml` and you can set it to something like this:

```yml
  trench-blacklist: 
    - INFESTED_STONE
```

**Comment by Burchard36** [comment]
Closing this as there has been no response, if you notice this issue on your end with the above configuration setting, please re-open this issue

**Comment by bdagenais2** [comment]
> Closing this as there has been no response, if you notice this issue on your end with the above configuration setting, please re-open this issue

The above configuration should be a temporary work around, not the permanent solution.

**Comment by Burchard36** [comment]
> The above configuration should be a temporary work around, not the permanent solution.

I do not see how this is a temporary work around, as this is the way you should be backlisting blocks you don't want players to obtain (For example end portal frames)

**Comment by bdagenais2** [comment]
> > The above configuration should be a temporary work around, not the permanent solution.
> 
> I do not see how this is a temporary work around, as this is the way you should be backlisting blocks you don't want players to obtain (For example end portal frames)

It fails to replicate vanilla behavior.

Vanilla:
- Can be broken
- Spawns silverfish
- Does not drop block

AE with blacklist:
- Cannot be broken
- Allows user to avoid vanilla trap
- Frustrates player as trench appears to not work correctly (some stone doesn't break)

**Comment by Burchard36** [comment]
Okay I see, if anything this is more or less a feature request, not exactly a bug

We will add support for spawning the silverfish with Trench in one of our future udpates :)
