### ISSUE TITLE
Disabled enchantment in a world but it still work

### ISSUE THREAD

**Issue by NightLife-SG** [GC-spigot/AdvancedEnchantments#2722]
### Describe the bug

So i have a few enchantment that are disabled in a world
but if a player would wear the armor before changing to the world,the enchantment would still work

### How to reproduce

wear a blacklisted enchantment in a normal world
then you change world wearing that armor

### "/ae plinfo" link

https://paste.md-5.net/icunazihur

**Comment by GC-spigot** [comment]
Can you give an example? From your configuration
