### ISSUE TITLE
'TREE_BREAK' Breaks player placed logs.

### ISSUE THREAD

**Issue by thats-bs** [GC-spigot/AdvancedEnchantments#2723]
### Describe the bug

Basically this has been a bug for as long as I can remember but when an axe has 'TREE_BREAK' it breaks the logs of trees completely fine however it also destroys player placed logs so lets say you're using logs on your house it will also break ALL of those logs not just the 1 you're trying to break.

### How to reproduce

Have an axe with 'TREE_BREAK' enchantment,
Break a tree, see that it works,
Make a small grouping of logs,
Break that small grouping with the same axe,
Watch them all get broken not just the 1 block you wanted to break.

### "/ae plinfo" link

https://paste.md-5.net/hukohaweme

**Comment by Burchard36** [comment]
Hey there, this bug is now fixed but to check your discord as there is a possible issue with blocks placed before this patch

Its fixed in 8.9.11 but do note GC is on vacation currently, so it may be a few more days until this is pushed to ae.net/spigot
