### ISSUE TITLE
AE Bedrock Anvil issue

### ISSUE THREAD

**Issue by AvatarMental** [GC-spigot/AdvancedEnchantments#2724]
### Describe the bug

Players that connect to Java server using Bedrock are unable to use an anvil to add ae books to an item. Using 1.18.2 with Geyser/Floodgate on paper.

### How to reproduce

Give player logged in via bedrock a book with 100% success 0% failure, and they cannot use an anvil to add the enchant to the item. Java players seem to have no issue doing this. Also, drag and drop seems to work fine for bedrock users.

### Screenshots / Videos

https://i.imgur.com/fn2cLd3h.jpg
https://i.imgur.com/fn2cLd3h.jpg

### "/ae plinfo" link

https://paste.md-5.net/osafewomib

### Server Log

https://mcpaste.io/709e5b8a22fd47ad

**Comment by Burchard36** [comment]
Issue was resolved via github, have a nice day!
