### ISSUE TITLE
Bug with command

### ISSUE THREAD

**Issue by Conor1201** [GC-spigot/AdvancedEnchantments#2725]
### Describe the bug

When using a command containing the world "clear", it damages the player for 0 hearts or something like that. For example, if i type /clearabcdefg (without args) it will do this.

I removed AE and tried it again and the issue was gone.

### How to reproduce

Type /clear(anything here)

### Screenshots / Videos

https://gyazo.com/d13f2ee8efd2849d5f31bbf8adbd6f3e

### "/ae plinfo" link

N/A

**Comment by DuneSciFye** [comment]
This is not happening for me, since you removed the plugin and it stopped, this may be an incompatibility between AE and another plugin. Remove all other plugins and try this with only AE installed and see if this still happens

**Comment by Burchard36** [comment]
Hello this bug will be fixed in 8.9.11

Not sure why this command existed in the first place, apologies for that

Currently GC is away on vacation so this update wont be pushed until hopefully later this week, apologies for the inconvenience

**Comment by Burchard36** [comment]
8.9.11 is out now! Please update to the latest version :)

If you have any new issues please open a new issue request!
