### ISSUE TITLE
Armor Sets Effects not working properly

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2727]
### Describe the bug

The %attacker% and AOE variables are not working on armor sets DEFENSE idk with ATTACK but yeah.

### How to reproduce

make a defense with %attacker% variable on armor sets, it'll still damage the victim.

### Screenshots / Videos

none

### "/ae plinfo" link

https://paste.md-5.net/isivoperin

### Server Log

https://mcpaste.io/f5e84af302588e1d

**Comment by illudota** [comment]
EDITED. effects work but variables dont.

**Comment by GC-spigot** [comment]
Resolved
