### ISSUE TITLE
Block Break error

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2728]
### Describe the bug

Spamming the console

### How to reproduce

I have no idea, but i see RAW_IRON somewhere on the error.

### Screenshots / Videos

https://pastebin.com/zvbpH8UJ

### "/ae plinfo" link

https://paste.md-5.net/amifudasur

### Server Log

https://mcpaste.io/cc113563cd12a83a

**Comment by Burchard36** [comment]
Fixed! Apologies for this, when 8.9.12 is pushed that will be the version that fixes it :)
