### ISSUE TITLE
Autosmelt + Telepathy 

### ISSUE THREAD

**Issue by flrping** [GC-spigot/AdvancedEnchantments#273]
It works fine, but some blocks are ignored such as gold ore, iron ore, or cobblestone. It smelts but doesn't transfer to your inventory.

Server version 1.8.8
Version: 5.1.2 (I didn't see on patch notes on recent update if this was fixed, so I assume it wasn't.)

**Comment by flrping** [comment]
Updated to recent version. Still occurs.

**Comment by GC-spigot** [comment]
Fixed in next update.
