### ISSUE TITLE
Could not pass NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getUniqueId()" because "<local1>" is null

### ISSUE THREAD

**Issue by DrakMC** [GC-spigot/AdvancedEnchantments#2730]
### Describe the bug

I got an error with the extinguish enchant in the console.

### How to reproduce

I don't know when this error will happen.

### "/ae plinfo" link

https://paste.md-5.net/halomofeni

### Server Log

https://mcpaste.io/c9259d93027bf2e8

**Comment by Burchard36** [comment]
Refer to #2719 as this is a duplicate
