### ISSUE TITLE
Infinite Obsidian bug trench?

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2731]
### Describe the bug

Use trench on enderchest

### How to reproduce

https://www.youtube.com/watch?v=1r9z8ZyfNVg

### Screenshots / Videos

https://www.youtube.com/watch?v=1r9z8ZyfNVg

### "/ae plinfo" link

https://paste.md-5.net/zomevogika

### Server Log

https://mcpaste.io/bca93070b0c4cea5

**Comment by Burchard36** [comment]
Hello, fixed with 8.9.11

GC is currently on vacation so it may be a bit until he uploads this to ae.net and or spigot's website apologies for this inconvenience

**Comment by Burchard36** [comment]
8.9.11 is out now! Please update to the latest version :)

If you have an new issues please open a new issue request!
