### ISSUE TITLE
WARN in console

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2732]
### Describe the bug

Hello this warn is spamming my console at some times, it's just a warn but idk if it's anything serious?
https://pastebin.com/Z6sGqQcY

### How to reproduce

No Idea, but here's the warn lines:
https://pastebin.com/Z6sGqQcY

### Screenshots / Videos

https://pastebin.com/Z6sGqQcY

### "/ae plinfo" link

https://paste.md-5.net/zomevogika

### Server Log

https://mcpaste.io/bca93070b0c4cea5

**Comment by Burchard36** [comment]
Refer to #2719 as this is a duplicate
