### ISSUE TITLE
The GUI opened by "/alchem" command cannot be customized

### ISSUE THREAD

**Issue by yebanme** [GC-spigot/AdvancedEnchantments#2735]
### Describe the bug

All contents displayed by the "/alchem" command can only be displayed in config I want to modify the GUI, just like the inventory configuration in the "customcommands. yml" file

### How to reproduce

Use the command "/alchem" to open the GUI in the game

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/20102749/162551667-83745153-538d-4149-9ac6-f32063bf6bf9.png)
This is a GUI that cannot be modified at present
![image](https://user-images.githubusercontent.com/20102749/162551826-a2dbd483-8b26-4db2-80bd-56c9ae3d2412.png)
This is the display configuration of alchemist currently provided by the plugin
![image](https://user-images.githubusercontent.com/20102749/162551714-ed94b6f2-58d6-4c99-890f-38fc1fdb8ee2.png)
I hope to add such a configuration to modify the GUI

### "/ae plinfo" link

https://paste.md-5.net/liqizitafe

**Comment by yebanme** [comment]
It has been a long time since a completely customized GUI has been used in other menus. Can you customize this GUI?

**Comment by GC-spigot** [comment]
We don't have a planned rework for Alchemist just yet, but in future we will rework it :)
