### ISSUE TITLE
All enchanted books are deleted when using a stack of enchanted books fails

### ISSUE THREAD

**Issue by yebanme** [GC-spigot/AdvancedEnchantments#2737]
### Describe the bug

Use the same enchanted books in stacks, when the triggering of the enchanting fails, all the enchanted books will be deleted

### How to reproduce

1. Changed the material of enchanted books to stackable items such as "paper"
2. Use the command "/ae givebook test armored 1 10 0 100" to get a stack of enchanted books
3. Use an enchanted book on an item
4. All enchanted books are deleted on failure

### "/ae plinfo" link

https://paste.md-5.net/yevayudiza

**Comment by GC-spigot** [comment]
Cannot recreate https://gyazo.com/c4fd9393e5d2f4b5c004e5d5434da1b8

**Comment by yebanme** [comment]
I'm sorry that I realized that I didn't provide a configuration information. I hope you can modify the configuration and retest
`chances:
  # Should book chances be random?
  random: true
  # If not random, what should be the simple values?
  # Can use `<min>-<max>` to define range between
  success: 92
  destroy: 8
  # If applying book fails, should plugin destroy item 100% of the time or use Destroy from book to give a chance to
  # neither apply enchant neither destroy. If set to "enabled: true', item will always be destroyed.
  destroy-if-fail:
    enabled: true`

**Comment by Burchard36** [comment]
Using above configuration, bug was confirmed

Will be fixed in the latest AE update 8.9.18
