### ISSUE TITLE
Issue with not-applyable-with setting

### ISSUE THREAD

**Issue by lordgecko27** [GC-spigot/AdvancedEnchantments#274]
Vanilla enchantments doesn't seem to work on the setting "not-applyable-with".
I already try to use both name formats (Example: LOOT_BONUS_BLOCKS and Fortune).

AE Version: 5.1.2
Server Spigot Version: 1.8.8

**Comment by GC-spigot** [comment]
This only works when an enchantment is already on item, and another is being applied to it, not the opposite way. Which means that Fortune cannot be used.
