### ISSUE TITLE
critical bugs with TRENCH

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2740]
### Describe the bug

when player break ore block with trench (without any enchantments, only trench)
ore item was drops x5 times than normal.
also duplicated with smelt.

i  repoted bugs about 10 times, but still many bugs.
why are this plugins has so many bugs? I'm tired of reporting.

### How to reproduce

굴삭기: 
  display: "%group-color%굴삭기"
  description: "1레벨당 20%의 확률로\n3x3 영역을 파괴합니다."
  applies-to: "곡괭이, 삽"
  type: "MINING"
  group: "신화" #에픽
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 20
      effects:
        - "TRENCH:3"
    2:
      chance: 40
      effects:
        - "TRENCH:3"
    3:
      chance: 60
      effects:
        - "TRENCH:3"
    4:
      chance: 80
      effects:
        - "TRENCH:3"
    5:
      chance: 100
      effects:
        - "TRENCH:3"

### "/ae plinfo" link

https://paste.md-5.net/opicorakop

**Comment by NCSV** [comment]
also when player break shulkerbox with trench, items are not appears. just disappeared.

**Comment by Burchard36** [comment]
Can you try this on the latest version now and see if it still persists?

**Comment by GC-spigot** [comment]
Fixed
