### ISSUE TITLE
Bug with Extinguish

### ISSUE THREAD

**Issue by Omarlatif** [GC-spigot/AdvancedEnchantments#2741]
### Describe the bug

I do not particularly know how it happens, although I see the spam in chat and console.

### How to reproduce

Unknown

### "/ae plinfo" link

https://paste.md-5.net/recureyuri

### Server Log

https://mcpaste.io/81d0420707206521

**Comment by Omarlatif** [comment]
The error that comes up is "Failed to parse effect 'EXTINGUISH' for enchant 'extinguish'
Arguments included with effect: '[]'"

**Comment by Burchard36** [comment]
Please update to 8.9.11 this should fix your issue :)
