### ISSUE TITLE
Carved pumpkin not 'Armor'

### ISSUE THREAD

**Issue by Indigo102** [GC-spigot/AdvancedEnchantments#2744]
### Describe the bug

My Friend and I are working on quite a big project, and to help us see our dream come to fruition we tried to put custom enchants on a carved pumpkin, as when using a resource pack, and chaging the name of the pumpkin allowed the changing of the texture of that specific named pumpkin, and without it being registered armor, whenever the pumpkin is worn, the enchants dont activate when hit with pumpkin on your head, but rather if you hold it in your haands                                     

### How to reproduce

As this is not really a bug, it should not be reproduced as such. How we showed the fact that the Carved pumpkin was not registered as armor was via the use of the enchantment Trickster, which we put onto the pumpkin. Then, after changing the config to guerentee the proc of the Trickster enchant, we tried to hit the person with the pumpkin on their head. This did not proc the enchant, HOWEVER, when the pumpkin was help in the hand of the user and the user was hit, it worked just fine.

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by Burchard36** [comment]
Do note I have yet to test this, but I will make sure that I test this feature, are you able to send the enchantment for the headpiece you are using as well?

**Comment by Burchard36** [comment]
8.9.11 is out now! Please update to the latest version :)

If you have an new issues please open a new issue request!
