### ISSUE TITLE
LAVA WALKER - OBSIDIAN GENERATOR

### ISSUE THREAD

**Issue by alexeses** [GC-spigot/AdvancedEnchantments#2746]
### Describe the bug

Hello!

Several users have reported to me that using the lava walker in the nether generates obsidian practically infinitely without the need of water or other things. 

Is it possible that you can block that users can't break this block or that we can detect that this block is set by the plugin with some kind of block metadata or similar.

Thanks.

### How to reproduce

By putting on your boots and walking on lava. This generates an infinite obsidian DUPE and you can then chop it.

### Screenshots / Videos

https://user-images.githubusercontent.com/46347629/163144768-8d9dabc9-cb74-4788-9163-354138b6c3f3.mp4

### "/ae plinfo" link

https://paste.md-5.net/fijizohage

### Server Log

https://mcpaste.io/6b74d84ce9d33e3c

**Comment by Burchard36** [comment]
To be honest there is not a great way to handle this, as block metadata is not persistent and won't stay throughout server restarts

If you are fine with this, we can implement a fix where they can immediately be broken when the enchantment is activated, but on a server restart they will be able to break these blocks again 

There is a way to fix this by storing every single block placed by the enchantment in a data file, but this comes with a risk as players could run through your servers storage limit and force stop your server on some hosts as they have a storage limit (This may not be an issue for you, but for others it may)

**Comment by alexeses** [comment]
Hello! 

It would be very nice the solution you propose me and there would be no problem. I hope you will be able to apply it soon.

Thank you very much!

**Comment by alexeses** [comment]
Any news on the correction?

**Comment by Burchard36** [comment]
Sorry for the delay didnt get an email, I will add this in an update here very soon :)

**Comment by alexeses** [comment]
Thank you, I will be waiting

**Comment by alexeses** [comment]
Will it ever be fixed?

**Comment by GC-spigot** [comment]
Fixed
