### ISSUE TITLE
Turtle helmet not detected as a helmet

### ISSUE THREAD

**Issue by samfces** [GC-spigot/AdvancedEnchantments#2747]
### Describe the bug

When configuring the "applies" section with "ALL_HELMET" setting, it appears that the turtle helmet is not a helmet.

### How to reproduce

To reproduce the bug, the following steps must be taken:
- Configure an enchantment so that it can only be applied to helmet.
- Try to add the enchantment to a turtle helmet.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/26687602/163154385-f56f50db-c927-4b75-942d-48b279e2884d.png)
![image](https://user-images.githubusercontent.com/26687602/163154671-4d864d03-0ebb-41a7-b504-9e129b9a1493.png)

### "/ae plinfo" link

https://paste.md-5.net/fiqehahene

**Comment by alexeses** [comment]
The same thing is happening to me, do you know anything?

**Comment by samfces** [comment]
I am still waiting for this bug to be fixed. It is not difficult to fix it

**Comment by samfces** [comment]
I do not see it as normal that this bug (which is easy to fix) is not being fixed and others that are complicated are being fixed. Three weeks waiting and counting
