### ISSUE TITLE
White scroll doesn't work on shovels

### ISSUE THREAD

**Issue by CryLegende** [GC-spigot/AdvancedEnchantments#2748]
### Describe the bug

Hello, White scrolls can't be appliqued on shovels. I don't know if there is an option to change that but I don't find it.
I have custom enchants for shovels, so I think white scrolls need to work on them too ^^

Thank you for your help ! :)

### How to reproduce

Try to apply a white scroll on a diamond shovel.

### "/ae plinfo" link

https://paste.md-5.net/okohehanen

**Comment by Burchard36** [comment]
![image](https://user-images.githubusercontent.com/48583030/163701593-cd9d9e21-56e7-4f09-b295-ec72682846b3.png)
Works for me? Even tested on 1.12.2 with just default configurations, can we get some more information like a video please?

**Comment by CryLegende** [comment]
Hello, sorry for the delay, here is a video of the problem: https://i.gyazo.com/a416e49e085ca6eab0981f34f0c05c01.mp4

**Comment by Burchard36** [comment]
Have you tried backing up your AdvancedEnchantments folder, deleting, then regenerating it, and from there trying to apply the white scroll? If so please try this and tell me your results

**Comment by CryLegende** [comment]
Same with the default AdvancedEnchantments folder
But I just see that I don't have the problem on my 1.16 server (default folder or not)
I only have it on my 1.12 servers
