### ISSUE TITLE
How can I register Carved Pumpkin as Armor?

### ISSUE THREAD

**Issue by Indigo102** [GC-spigot/AdvancedEnchantments#2749]
### Describe the bug

A friend and I are having problems with custom enchants, just to discover the reason It was not working was because the Carved Pumpkin was not considered a piece of armor. I'm wondering how to fix this issue?

### How to reproduce

We placed a AE enchant (Trickster) with 100% success rate onto a carved pumpkin, and the enchant did not work while the pumpkin was on the head of the player, but it worked when in the hand of a player. 

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by Burchard36** [comment]
Can you try this on the latest version?

**Comment by Burchard36** [comment]
Closing due to no response, if you still have this issue please open a new one referancing this one

Preferably, for questions like this you should ask a question on our discord :)
