### ISSUE TITLE
SERVER FAILS TO SHUT DOWN

### ISSUE THREAD

**Issue by alexeses** [GC-spigot/AdvancedEnchantments#2752]
### Describe the bug

Hello!

Since I put the AE plugin I have noticed that my servers often do not shut down and it is impossible for this to happen if I leave it hours to finish. I haven't really touched anything weird in the plugin for this to happen.

Server ver: PaperSpigot 1.17.1 (last possible version of Minecraft version) 
Plugin ver: Last version

Thank you very much

### How to reproduce

There is no exact confirmation of how to reproduce it, but the servers not shutting down really is a problem.

### Screenshots / Videos

Complete log: https://paste.minebox.es/kuninufori.yaml
Last log: https://paste.minebox.es/omojorezit.yaml

https://cdn.discordapp.com/attachments/328148475814346752/965275771553869915/unknown.png

### "/ae plinfo" link

https://paste.md-5.net/ozocudugeg

**Comment by Burchard36** [comment]
When you remove AE does the bug still persist? Cant replicate on my end

**Comment by alexeses** [comment]
Hello!

If I remove the plugin there is no inconvenience and everything shuts down correctly. As I tell you I have an average of 20 servers and at least 5-6 randoms servers are stopped in the same phase of deactivation of the plugin.

It is really a serious problem, since it does not finish saving my worlds. I attach the configuration for you to see the enchantments I have enabled:

> List of special enchantments: https://paste.minebox.es/gulehirixe.yaml

Very possibly it is some enchantment that gets stuck when deactivating.

**Comment by alexeses** [comment]
I don't like to be "critical", I understand that everyone has a life and must do other more important things. However in my opinion it is something quite serious and I have not been given any solution about it having paid a significant amount for the plugin. 

I don't ask for an instant response but at least give me some attention. It's kind of **It's annoying** to be on the lookout when my servers are not downloading because of the plugin. 

If you need more data to analyze the error don't hesitate to ask me, I'm really happy to help you.

**Comment by DuneSciFye** [comment]
@alexeses Can you send your plugin list? There may be some incompatibility between AE and another plugin causing this

**Comment by Burchard36** [comment]
The only reason we didn't give you a response so fast is that we cant replicate this on our end for some reason

In order for us to fix a bug we need to be able to replicate it locally and we just arent able to replicate it

Have you tried removing SlimeWorldManager, but keep AE and see if you get the same issue?

Also do please try this on the most latest version
