### ISSUE TITLE
Alchemist dupe

### ISSUE THREAD

**Issue by Pumkinhead** [GC-spigot/AdvancedEnchantments#2753]
### Describe the bug

when you open /alchemist and you put an item in there you can take it out and if you keep clicking the blank space you will keep getting more items than you put in

### How to reproduce

Not really sure about this one...

### "/ae plinfo" link

not sure what to put here

**Comment by Burchard36** [comment]
Can you get a video for this, please? And we need the output of /ae plinfo as well

**Comment by Burchard36** [comment]
Closing due to no recent response, please open a new issue referancing this one if the issue still persists for you!
