### ISSUE TITLE
ADD HARM Knockback

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2757]
### Describe the bug

Add harm gives knockback

### How to reproduce

Make an add harm CE, like repeating harm, You could try making a defense ADD_HARM CE too, it will knockback the attacker.

### Screenshots / Videos

https://streamable.com/gog15p

### "/ae plinfo" link

gives error idk why, wasnt like this before: https://pastebin.com/1hgfPg7S,  but im on latest version.

### Server Log

https://mcpaste.io/e8bb4d074b38df6f | Server is 1.16

**Comment by GC-spigot** [comment]
Not much we can do unfortunately, this is caused by Vanilla mechanics
