### ISSUE TITLE
Detonation break shulker

### ISSUE THREAD

**Issue by Igzak** [GC-spigot/AdvancedEnchantments#2758]
### Describe the bug

Hi, i reveal if someone broke shulker_box using detonation enchant with pickaxe that shulker_box just disappear 
Version of Plugin: 8.9.16
Server: git-Purpur-1566 (MC: 1.18.1)

### How to reproduce

Enchant pickaxe with detonation and break shulker

### Screenshots / Videos
checked plinfo on 8.9.16 also 500
![image](https://user-images.githubusercontent.com/22889464/164030659-cecdb6f1-24df-4eff-9436-fb34333ad2ba.png)
https://imgur.com/a/rxKxlJ5

### "/ae plinfo" link

return 500 code

### Server Log

https://mcpaste.io/90de2dc8966380d2

**Comment by Igzak** [comment]
Re-tested on new version with this plugin list
https://imgur.com/a/oQMDuFp

**Comment by Burchard36** [comment]
Can you send the enchantment you are using?

I do not see a default enchantment called "detonation" unless you are using an addon's enchantment? Do please send the configuration for this enchantment

Furthermore, I assume you mean this happens with the TRENCH effect as that sounds most fitting, if that's the case i couldn't replicate, here's a video 

https://user-images.githubusercontent.com/48583030/165003965-7d54fed2-674c-48e3-8ea5-587e9376cdfa.mp4

**Comment by Burchard36** [comment]
Closing due to no response, if this issue still persists please open a new ticket referancing this one

**Comment by GC-spigot** [comment]
Read latest update
