### ISSUE TITLE
The shulker box becomes empty due to the 'SMELT' effect

### ISSUE THREAD

**Issue by ERogovtsoff** [GC-spigot/AdvancedEnchantments#2759]
### Describe the bug

The bug relates to the 'SMELT' effect. When I mine the shulker box with some items inside, when I'm picking up such shulker box, it's empty. A visual description of the issue in the screenshots.  (Sorry for the Russian language on the screenshots)

Environment:
Paper 1.12.2 (build 1620)

### How to reproduce

Preconditions:
The pickaxe is enchanted by the 'SMELT' effect
There is any not empty shulker box

Steps to reproduce:
1. Put the shulkar box in any place
2. Mine it with a pickaxe with the 'SMELT' effect
3. Pay attention to the items in the shuker box

Actual Result:
The sulker box is empty

Expected Result:
The items remained in the shulker box

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/50799290/164030150-e30cd8a2-9931-4ef9-9132-b4ba73d78179.png)
![image](https://user-images.githubusercontent.com/50799290/164030206-510fd739-2c55-4415-b235-08e0087cdf70.png)
![image](https://user-images.githubusercontent.com/50799290/164030428-f16319b1-dd28-40b6-88ab-af3a4ec74bd6.png)
![image](https://user-images.githubusercontent.com/50799290/164030276-a951197f-0b8e-4c69-b0b8-a45335d213d7.png)
![image](https://user-images.githubusercontent.com/50799290/164030538-12bc836a-4222-4f3e-bd75-82d022963d63.png)
![image](https://user-images.githubusercontent.com/50799290/164030614-b36f4e0d-e0c4-4edb-af18-136a120a9ce4.png)

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ERogovtsoff** [comment]
AE Verison
![image](https://user-images.githubusercontent.com/50799290/164034293-3493f7d1-bd54-4f90-ba56-af9f116ce17a.png)

**Comment by ERogovtsoff** [comment]
Actually, I found the workaround:

> condition: "%block type% contains SHULKER : %stop%"

**Comment by Burchard36** [comment]
Hello this is now fixed when 8.9.19 is out, you wont have to use that condition once its pushed to spigot :)

**Comment by Burchard36** [comment]
Update has been out, please update and open a new issue if this still persists
