### ISSUE TITLE
Bow_Shoot no longer works with Particle.

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#2760]
### Describe the bug

Well, bow_shoot no longer works with Particle. Worked previously and only works with BOW / BOW_MOB now.
Tried variations with %player% %player_name% etc...

### How to reproduce

Try an enchant that uses Bow_Shoot and particle.
bowparticle:
  display: '&6&lSpecial'
  description: "&fApplies different particles based on Lv"
  applies-to: 'Bow'
  type: 'BOW_SHOOT'
  group: 'UNIQUE'
  applies:
    - BOW
  levels:
    1:
      effects:
        - 'PARTICLE:CRIMSON_SPORE:50:1'

### "/ae plinfo" link

I've gotten error 500 when trying this command.

### Server Log

necessary?

**Comment by Burchard36** [comment]
Hello, can you tell me the last version this enchantment worked on?

**Comment by Burchard36** [comment]
Resolved and will be available in 8.9.17, please check your discord DM's though
