### ISSUE TITLE
Heads issue

### ISSUE THREAD

**Issue by Omarlatif** [GC-spigot/AdvancedEnchantments#2761]
### Describe the bug

Placing a Minecraft head against a block (wall) turns the head to face north and sets it to steve. After disabling AdvancedEnchantments, it seems to fix the issue. Console reveals no issues when heads are placed.

(Server is up to date with AE 8.9.16)

### How to reproduce

Placing heads against blocks, (IT MUST BE FULL BLOCKS) seems to cause the issue.

### Screenshots / Videos

https://gyazo.com/502385f2c32f6e6ec9893973350e796b
https://gyazo.com/67a5f2e757e2fe968400aee4b7366e0b

### "/ae plinfo" link

Could not create debug link! Error: Server returned HTTP response code: 500 for URL: https://paste.md-5.net/documents

### Server Log

N/A (No errors)

**Comment by Burchard36** [comment]
Fixed when 8.9.18 is out, sorry about that its related to the new pump helmet fix, they will now work as intended
