### ISSUE TITLE
Adding custom drops to custom made named/boss mobs

### ISSUE THREAD

**Issue by UncleanCreams23** [GC-spigot/AdvancedEnchantments#2763]
### Describe the bug

Making a way so custom made mobs, such as the mythicmobs plugin mobs, drop items like random enchant books and scrolls and such
Let's say my mob boss was named ZombieKing would it work with this kind of format?
mobs:
#  ZOMBIEKING:
#    chance: 10
#    items:
#      - "randomenchantmentbook:1"

### How to reproduce

^

### Screenshots / Videos

^

### "/ae plinfo" link

^

### Server Log

^

**Comment by doitliketyler** [comment]
Any updates on this? I would love to be able to add AE items to the drop table in MythicMobs. Drops are much better because giving items via command breaks the immersion. I've searched and noticed countless folks on Discord asking for this feature as well. Any chance on making this happen?
