### ISSUE TITLE
Player Heads Conflict

### ISSUE THREAD

**Issue by BrandonT80** [GC-spigot/AdvancedEnchantments#2767]
### Describe the bug

When placing player heads, the orientation is set differently than wanted, and to all other players the head reverts to a steve head.

### How to reproduce

Place any head or hdb head. Look with another account.

### Screenshots / Videos

https://youtu.be/5FojP17fTB4

### "/ae plinfo" link

https://paste.md-5.net/ocamevugiv

**Comment by Burchard36** [comment]
Read #2761 :) will be fixed in the next update
