### ISSUE TITLE
can not combine custom enchanted book in anvil

### ISSUE THREAD

**Issue by Onlyroin** [GC-spigot/AdvancedEnchantments#2768]
### Describe the bug

can not combine custom enchanted book in anvil.

### How to reproduce

번개:
  display: "%group-color%번개"
  description: "일정 확률로 몹들 타격시 번개가 칩니다."
  applies-to: "검, 도끼"
  type: "ATTACK;ATTACK_MOB;BOW;BOW_MOB"
  group: "레전더리"
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    1:
      chance: 24
      cooldown: 3
      effects:
        - "LIGHTNING %victim%"
    2:
      chance: 32
      cooldown: 3
      effects:
        - "LIGHTNING %victim%"
    3:
      chance: 48
      effects:
        - "LIGHTNING %victim%"

### Screenshots / Videos

![2022-04-24_00 33 47](https://user-images.githubusercontent.com/89057657/164912817-8636f780-e55d-4c90-a103-db626f62fe9d.png)

### "/ae plinfo" link

https://paste.md-5.net/zofakuhepa

**Comment by austv** [comment]
go to anvil.yml and set
`allow-illegal-custom-enchant-combinations: true`

**Comment by Burchard36** [comment]
What @austv said, set that and it should work for you, let us know

**Comment by Burchard36** [comment]
Closing due to no response, please open a new issue mentioning this one if it still persists after using the configuration option above in the anvil.yml file
