### ISSUE TITLE
Smelting does not work with MORE_DROPS

### ISSUE THREAD

**Issue by Omarlatif** [GC-spigot/AdvancedEnchantments#2771]
### Describe the bug

`smelting:
  display: "%group-color%Smelting"
  description: "Chance to smelt mined blocks."
  applies-to: "Pickaxes"
  type: "MINING"
  group: "SIMPLE"
  applies:
    - ALL_PICKAXE
    - ALL_SHOVEL
  levels:
    1:
      chance: 25
      effects:
        - "SMELT"
    2:
      chance: 50
      effects:
        - "SMELT"
    3:
      chance: 75
      effects:
        - "SMELT"
    4:
      effects:
        - "SMELT"`
        
`
advancedfortune:
  display: "%group-color%Advanced Fortune"
  description: "Chance to receive more ore drops."
  applies-to: "Pickaxes"
  type: "MINING"
  group: "LEGENDARY"
  applies:
    - ALL_PICKAXE
  levels:
    1:
      chance: 25
      effects:
        - "MORE_DROPS:1"
    2:
      chance: 50
      effects:
        - "MORE_DROPS:1"
    3:
      chance: 75
      effects:
        - "MORE_DROPS:2"
    4:
      chance: 100
      effects:
        - "MORE_DROPS:2"`
    
Smelting works on its own, but does not work when presented with an enchant with more drops. (Both vanilla Fortune and MORE_DROPS:)

/ae about:
Version: 8.9.16
Universal Break Checks: True

Server Info:
Version: 1.18.2
Waterfall (Bungee) - Purpur (Server)

### How to reproduce

Tested both on Gold Ore and Iron Ore, it seems as if MORE_DROPS/Vanilla Fortune take priority rather than smelting then applying them. (More raw drops)

### Screenshots / Videos

https://gyazo.com/a8008a6e6f4e1cba247b76d6951fc1d3

### "/ae plinfo" link

https://paste.md-5.net/ugemulapog

### Server Log

No console information.

**Comment by Omarlatif** [comment]
I will test this on the latest update to make sure it is a bug.

**Comment by Omarlatif** [comment]
Tested on 8.9.18 - Same issue

**Comment by Burchard36** [comment]
Have you tried this with blocks that were not placed by a player? I believe we prevent these enchants on player placed blocks due to an issue this would obviously have with players duping items

**Comment by Omarlatif** [comment]
I apologise and did not think of that... Please disregard this bug report.
