### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by DrakMC** [GC-spigot/AdvancedEnchantments#2773]
### Describe the bug

I saw the error in the console.

### How to reproduce

I don't know when it will happen.

### "/ae plinfo" link

https://paste.md-5.net/tumilozapa

### Server Log

https://pastebin.com/raw/VSWrLwWm

**Comment by Burchard36** [comment]
#2772 read resolution there :)

Duplicate issue
