### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by BHGKing** [GC-spigot/AdvancedEnchantments#2776]
### Describe the bug

2 placeholders that i know of arent working at the moment and they are (%player_current_exp%)(%player_level%) both the plugin and the server have been reloaded and it doesnt seem to work.

### How to reproduce

N/A

### Screenshots / Videos

https://imgur.com/a/jSMmIKe

### "/ae plinfo" link

https://paste.md-5.net/rudiweqeto

**Comment by Burchard36** [comment]
Hello, placeholder API support was added now, update to 8.9.20
