### ISSUE TITLE
Re-add /asets reload or allow /ae reload to reload asets.

### ISSUE THREAD

**Issue by Omarlatif** [GC-spigot/AdvancedEnchantments#2777]
### Describe the bug

According to Spigot. March 28, 2021 - /asets was removed;
`Removed "/asets reload". Use "/ae reload" from now on.`

I can confirm, through thorough testing, that /ae reload does not reload asets.
- It does not apply changes to the current (tweaked) aset.
- It does not register new asets.
- It does not register new asets weapons.

Version it was removed: 8.0.0-Pre21.6

### How to reproduce

- Create a new aset
- Do /ae reload
- Nothing changed

### "/ae plinfo" link

https://paste.md-5.net/pirupumepu

**Comment by SirJben** [comment]
Spelling correction by Omarlatif.
![image](https://user-images.githubusercontent.com/63577950/165078834-ec9da181-99d5-4517-bba9-cdd666cc972d.png)

**Comment by GC-spigot** [comment]
Added
