### ISSUE TITLE
Clicking on the item to the right of the tinker triggered the action

### ISSUE THREAD

**Issue by yebanme** [GC-spigot/AdvancedEnchantments#2778]
### Describe the bug

After opening the tinkerer and placing the item, click on the item generated on the right side, the plugin mistakenly thinks it is an item that needs to be put into the tinkerer and outputs an error message

### How to reproduce

1. Use the command "ae givebook" to get an enchanted book
2. Open tinker with the command "tinkerer"
3. Click on the enchanted book to place it in the tinker
4. Click on the new item that appears on the right
5. An alert message appears in the chat bar

### Screenshots / Videos

https://user-images.githubusercontent.com/20102749/165106445-726efbc4-e68a-437f-bb55-081fb70fe86b.mp4

### "/ae plinfo" link

https://paste.md-5.net/yoziselevo

**Comment by austv** [comment]
Given that issue was opened, I would like to leave my other reports from tinkerer here:
https://github.com/GC-spigot/AdvancedEnchantments/issues/2678 (fixed issue number 1)

Also, I have the same bug in that video.

**Comment by Burchard36** [comment]
Hello i see, this is rather minor as it seems to be just a test issue, but it will be on our lists to fix it on a very future update :)
