### ISSUE TITLE
Recommendations and Issues

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#278]
First of all, I want to start by saying you shouldn't close issues that have not been resolved, like my last two issues.

First problem: magic dust, any scrolls (including white, black, transmog etc.) will NOT work. I am in SURVIVAL mode, as mentioned in my last issue.

Second problem: Add Kingdoms+ plugin support. The detonate enchantment can break blocks even when inside kingdom territory. When you mentioned that it should automatically have the support, apparently it doesn't.

Thanks for your help :D

**Comment by GC-spigot** [comment]
First of all, I'm not adding any plugins support as they should automatically properly handle block breaking, I've made trenching universal and if they weren't able to use Spigot's provided methods it's not my fault and therefore plugin support for it won't be added.

Secondly I'm testing on 1.8.9 (most commonly used version) and all items work.

**Comment by GC-spigot** [comment]
Only 22.7% of all servers are 1.13 or higher, Im pretty sure thats not "most people". 

1.13 was a big backend update and Im still focusing on versions that are used mostly - 77% of minecraft servers use.

That does not say that it wont be fixed on 1.13, it says that theres a priority for lower versions.

**Comment by Leomelonseeds** [comment]
Oh! I didn't know. Sorry about that then.

What I am saying is that you need to get it to 1.13 so the 22.7% of people like me can enjoy it :D

Hopefully you understand me. Have a nice day :)
