### ISSUE TITLE
Could not pass event PlayerInteractEvent to AdvancedEnchantments v8.9.18

### ISSUE THREAD

**Issue by Avynx** [GC-spigot/AdvancedEnchantments#2780]
### Describe the bug

https://pastebin.com/jAttXjWw Getting this spam error in console. How do i fix it? thanks.

### How to reproduce

NIL.

### Screenshots / Videos

NIL.

### "/ae plinfo" link

https://pastebin.com/jAttXjWw

**Comment by austv** [comment]
Did you tried 8.9.19? I guess that version added a fix for that issue
![image](https://user-images.githubusercontent.com/66658478/165356287-3a6668e4-ce00-47bc-beab-28a53a6aac36.png)

**Comment by Burchard36** [comment]
What @austv said but instead its this message instead :) 
![image](https://user-images.githubusercontent.com/48583030/165386891-6eeacda6-2343-48c1-a0fd-41cbc68ecf79.png)
