### ISSUE TITLE
Veinminer Mines extra Veins

### ISSUE THREAD

**Issue by BrandonT80** [GC-spigot/AdvancedEnchantments#2781]
### Describe the bug

The Veinminer enchantment does not only mine the vein attached to the ore, it mines all other veins of the same type in the area.

### How to reproduce

Mine with veinminer. Best to use X-Ray to see whats going on around. View the video below to see an example. 
https://youtu.be/kOYr0JEcEiI

### Screenshots / Videos

https://youtu.be/kOYr0JEcEiI

### "/ae plinfo" link

https://paste.md-5.net/hoyojurape

**Comment by Awpmeister2170** [comment]
Fixed in a recent update.
