### ISSUE TITLE
RESTORE enchantment doesn't work

### ISSUE THREAD

**Issue by SbirTeo** [GC-spigot/AdvancedEnchantments#2783]
### Describe the bug

I downloaded the latest version of Advanced Enchantmenst, but the enchant "Restore" (desc: Upon breaking, item has a chance\nto lose this enchantment and repair\nhalf of its durability) doesn't work. The item is not restored at breaking. 

restore:
  display: "%group-color%Restore"
  description: "In caso di rottura\nl'oggetto sarà riparato\nper metà della sua durata\nperdendo questo incantesimo."
  applies-to: "Pickaxes"
  type: "ITEM_BREAK"
  group: "MAGIC"
  applies:
    - ALL_PICKAXE
  levels:
    1:
      chance: 100
      effects:
        - "REMOVE_ENCHANT:restore"
        - "ADD_DURABILITY_ITEM:<round><math>-1 * (%maximum durability%/2)</math></round>"
        - "PLAY_SOUND:ITEM_TOTEM_USE"
     
     
      
DuneSciFye | Enchant Comissions — Oggi alle 22:27 
I feel like the issue here
is that current_item on the add durability enchant is gone and since its gone the plugin isnt able to repair that item
ill look into a fix for this today

### How to reproduce

I downloaded the latest version of Advanced Enchantmenst, but the enchant "Restore" (desc: Upon breaking, item has a chance\nto lose this enchantment and repair\nhalf of its durability) doesn't work. The item is not restored at breaking. 

restore:
  display: "%group-color%Restore"
  description: "In caso di rottura\nl'oggetto sarà riparato\nper metà della sua durata\nperdendo questo incantesimo."
  applies-to: "Pickaxes"
  type: "ITEM_BREAK"
  group: "MAGIC"
  applies:
    - ALL_PICKAXE
  levels:
    1:
      chance: 100
      effects:
        - "REMOVE_ENCHANT:restore"
        - "ADD_DURABILITY_ITEM:<round><math>-1 * (%maximum durability%/2)</math></round>"
        - "PLAY_SOUND:ITEM_TOTEM_USE"
     
     
      
DuneSciFye | Enchant Comissions — Oggi alle 22:27 
I feel like the issue here
is that current_item on the add durability enchant is gone and since its gone the plugin isnt able to repair that item
ill look into a fix for this today

### "/ae plinfo" link

https://paste.md-5.net/sidejujepe

**Comment by GC-spigot** [comment]
Fixed
