### ISSUE TITLE
The "TP_DROPS" effect doesn't work with sugar cane

### ISSUE THREAD

**Issue by ERogovtsoff** [GC-spigot/AdvancedEnchantments#2784]
### Describe the bug

When I mine a reed with a pickaxe enchanted on 'TP_DROPS', the reeds disappears, and I have the following message in the console:
https://pastebin.com/PbDB85CT

### How to reproduce

1. Enchant the pickaxe to the 'TP_DROPS' effect.
2. Mine  sugar cane.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/50799290/165397347-e3531e1b-560d-448f-8ea2-b817898dd120.png)
https://pastebin.com/PbDB85CT

### "/ae plinfo" link

/ae plinfo skipPlugins

### Server Log

https://mcpaste.io/a5020672e3a8a8f0

**Comment by Burchard36** [comment]
Hi yes Uhm, what's a reed? Do you mean lead? Or something else?

**Comment by austv** [comment]
> Hi yes Uhm, what's a reed? Do you mean lead? Or something else?

I don't know what is a reed, but TP_DROPS ignores lot of external events. Could you check this for me?
TP_DROPS do not give extra drops from mcMMO (mining and herbalism) and the normal drops from beetroot.
I have opened a issue once: https://github.com/GC-spigot/AdvancedEnchantments/issues/2685

With beetroot (didn't reported before):
TP_DROPS only give 1 beetroot and 1 beetroot seed, but even without fortune, mine beetroot conced lots of seeds

**Comment by ERogovtsoff** [comment]
I mean Sugar Canes😅

**Comment by Burchard36** [comment]
> > Hi yes Uhm, what's a reed? Do you mean lead? Or something else?
> 
> I don't know what is a reed, but TP_DROPS ignores lot of external events. Could you check this for me? TP_DROPS do not give extra drops from mcMMO (mining and herbalism) and the normal drops from beetroot. I have opened a issue once: #2685
> 
> With beetroot (didn't reported before): TP_DROPS only give 1 beetroot and 1 beetroot seed, but even without fortune, mine beetroot conced lots of seeds

I responded in that ticket ill look into the beetroot thing here soon

**Comment by Burchard36** [comment]
> I mean Sugar Cane😅

As in, the 2 blocks above the sugar_cane don't drop? That's the issue I'm currently having right now :)

**Comment by Burchard36** [comment]
If that's your issue above, it is now fixed along with cactus's being fixed as well as the same thing happened to them.

**Comment by Burchard36** [comment]
Update is out!
