### ISSUE TITLE
Shulkers disappearing when broken with Detonate, atomic detoante

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2785]
### Describe the bug

my previous issue was not fixed due to mcpaste link not working,  here is a reupload
https://paste.md-5.net/sexeyogoyo.bash

this is regarding to 
https://github.com/GC-spigot/AdvancedEnchantments/issues/2734

version AdvancedEnchantments-8.9.8.jar confirmed to not have this issue. whatever was changed after that is causing it.

### How to reproduce

Break any shulker with detonate or atomic detonate, and its gone forever.

### "/ae plinfo" link

https://paste.md-5.net/disiduyeya

**Comment by Burchard36** [comment]
Hello you are on a very outdated version of AE (8.1.10) please update to the latest and see if this is still an issue with you :)

**Comment by antibitcoin** [comment]
> Hello you are on a very outdated version of AE (8.8.10) please update to the latest and see if this is still an issue with you :)

On AdvancedEnchantments-8.9.22.jar on my test server I break the shulker and it will be treated as a regular chest, the shulker is gone forever, the content will drop to the ground as if I am breaking a wooden chest.

New PLINFO
https://paste.md-5.net/avajoyolez

my config
 https://paste.md-5.net/sexeyogoyo.bash

Enchants file
https://paste.md-5.net/abedifalod.bash

At this point if I am the only one with this bug, and if you cannot recreate it please take a look if its my config or enchants file if I might have something wrong.

**Comment by antibitcoin** [comment]
I have fixed the issue by removing the trench-blacklist section from the config file however breaking blocks near a shulker will now also drop the shulker, also breaking a shulker will break the whole person house with it because of trench.

any suggestions on how to fix this?

**Comment by GC-spigot** [comment]
Read latest update
