### ISSUE TITLE
Soulbound items disappear with totems

### ISSUE THREAD

**Issue by BirminghamBoy** [GC-spigot/AdvancedEnchantments#2787]
### Describe the bug

Items with the Soulbound enchant disappear out of the inventory when a player's totem pops, then reappear when the player respawns after their next death. 

### How to reproduce

See above ^

### "/ae plinfo" link

https://paste.md-5.net/vuniteheyu

### Server Log

https://www.toptal.com/developers/hastebin/vahafemati.yaml

**Comment by Awpmeister2170** [comment]
Fixed.
