### ISSUE TITLE
VEIN_MINE not compatible with fortune

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2788]
### Describe the bug

with veinmine whitelist
```
  veinmine-whitelist:
  - COAL_ORE
  - DEEPSLATE_COAL_ORE
  - IRON_ORE
  - DEEPSLATE_IRON_ORE
  - COPPER_ORE
  - DEEPSLATE_COPPER_ORE
  - GOLD_ORE
  - DEEPSLATE_GOLD_ORE
  - LAPIS_ORE
  - DEEPSLATE_LAPIS_ORE
  - REDSTONE_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DIAMOND_ORE
  - DEEPSLATE_DIAMOND_ORE
  - EMERALD_ORE
  - DEEPSLATE_EMERALD_ORE
  - NETHER_QUARTZ_ORE
  - NETHER_GOLD_ORE
  - ANCIENT_DEBRIS
```

and ``fortune-works-on-iron-gold: true``

mining nether_gold_ore with fortune + veinmine enchantment only drop items number like without fortune enchantment

### How to reproduce

1. enable that fortune-works-on-iron-gold: true 
2. add veinmine whitelist
3. restart server
4. get 2 fortune 30 something pickaxe, 1 with veinminer
5. mine 1 gold ore with fortune only, drop around 30 - 40 gold
6. mine 1 gold ore with fortune + veinminer, drop around 4 gold

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/61608872/165675690-7b3bf72e-7645-4d7a-8cda-1682459b4f4e.png)

![image](https://user-images.githubusercontent.com/61608872/165675701-c35d0755-43a7-4a85-98b5-93f907dfa47b.png)

With veinminer

![image](https://user-images.githubusercontent.com/61608872/165675741-02555f11-1ff8-46c5-a9a5-e627f8c53366.png)

![image](https://user-images.githubusercontent.com/61608872/165675757-69651ec7-96fd-4828-b93a-678a0d922c5a.png)

### "/ae plinfo" link

https://paste.md-5.net/weqoguxifu

### Server Log

https://paste.denizenscript.com/View/96061

**Comment by Ecilpse** [comment]
also i have simmilar problems. VEIN_MINE was not applied with fortune correctly
