### ISSUE TITLE
Error in console when right clicking a block with an empty hand. 

### ISSUE THREAD

**Issue by Apxthy** [GC-spigot/AdvancedEnchantments#2789]
### Describe the bug

I get a huge NPE when right clicking a block with anything in my hand besides blocks, in any world.

### How to reproduce

Right click a block with anything in your hand thats not placeable.

### "/ae plinfo" link

https://paste.md-5.net/afezujoval

### Server Log

https://mcpaste.io/453d84a9a088556d

**Comment by GC-spigot** [comment]
Already fixed, always update before reporting issues

**Comment by Apxthy** [comment]
Im experienced in plugin configuration. Im well aware that you should do whatever you can before you report a bug. However, with the latest version of AdvancedEnchantments thats released on Spigot, STILL has this issue.
