### ISSUE TITLE
No effects work

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#279]
From the recent update, almost everything is broken. Here is a list of the ones (that I know of) are broken from recent logs:

- ATTACK
- DEFENSE
- TRENCH

I will add more as they come. Thanks for helping.

**Comment by GC-spigot** [comment]
Issue with 1.13

**Comment by GC-spigot** [comment]
How can I fix something which isn't even an effect.
