### ISSUE TITLE
Can't combine/upgrade enchantments by left clicking on item

### ISSUE THREAD

**Issue by n0tlz** [GC-spigot/AdvancedEnchantments#2792]
### Describe the bug

So I have a problem, before when I put like a custom enchant on an item example its Bone Crusher 1, then I put another Bone Crusher 1 book it should turn into a bone crusher 2. but now it doesn't

### How to reproduce

Get any custom enchant thats level 1, apply it on an item, then get the same custom enchant level 2,3, or whatever and apply it on the same item and the custom enchant won't be upgraded.

### "/ae plinfo" link

https://paste.md-5.net/icibesumag

### Server Log

https://mcpaste.io/5939de48dc379523

**Comment by Burchard36** [comment]
Hello this works for me perfectly (I tried this with the multiplication enchant, check my video)

https://user-images.githubusercontent.com/48583030/166140532-0b69ffbb-8a27-490e-8bd8-52e7456106f5.mp4

This is likely a configuration issue, can you send your config.yml? You can open a ticket on our discord if you want faster support :)

**Comment by n0tlz** [comment]
> 

What version are you using? I dunno why mines not working

**Comment by n0tlz** [comment]
Uploading 2022-05-02 16-51-40.mp4…

Here's mine look

**Comment by austv** [comment]
Go to config.yml and change to this:
```
combining:
  enabled: true
  chances:
    use-chances: true
    break-item: true
    upgrade: true #here is need to be true
```

**Comment by Burchard36** [comment]
Yep try the config.yml settings austv sent, should work for you then
