### ISSUE TITLE
Heroic Upgrade Leather Armor Bug

### ISSUE THREAD

**Issue by DJDan21** [GC-spigot/AdvancedEnchantments#2793]
### Describe the bug

When a player upgrades a set to the heroic version, changing it into the "harder than diamond" leather set, it is in fact, not harder than diamond and as shown in the test laid out in the video provided ( https://paste.md-5.net/tewayiyano.bash.). You can clearly see the difference in armor sets and it is quite clear that this needs fixing.  I'm using the /ae premade #2 setup on my 1.8.8 server.

### How to reproduce

Give yourself any sets then upgrade to the heroic version

### Screenshots / Videos

[https://youtu.be/HZvILreUqZM](url)

### "/ae plinfo" link

https://paste.md-5.net/wovasuyiva

### Server Log

https://mcpaste.io/3fe5568f876b1d11

**Comment by illudota** [comment]
same issue

**Comment by GC-spigot** [comment]
It only supports 1.13+ unfortunately for now
