### ISSUE TITLE
Permanent Potion Effect when switching helmet for vanilla head (such as zombie head)

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#2794]
### Describe the bug

If you have a helmet with a permanent effect such as with the enchantment "Glowing" you can switch out the helmet with a vanilla head such as a Zombie Head and the effect won't be removed.

### How to reproduce

- Get a diamond helmet, enchant it with Glowing, put it on.
- Grab a Zombie Head from the creative menu
- Swap the two back and forth and see how the permanent night vision won't go away.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/970365413001146468/970365546572959814/2022-05-01_10-41-55_Trim.mp4

### "/ae plinfo" link

//paste.md-5.net/evifopitox

### Server Log

https://mcpaste.io/640881988136f19d

**Comment by GC-spigot** [comment]
Fixed
