### ISSUE TITLE
The error appears when someone dies on the server

### ISSUE THREAD

**Issue by ERogovtsoff** [GC-spigot/AdvancedEnchantments#2799]
### Describe the bug

The following error appears in the console when someone dies on the server: https://pastebin.com/JLw0KCpf

### How to reproduce

1. Die
2. Pay attention to the console

Actual result:
The error appears in the console

Expected result:
No error appears in the console

### "/ae plinfo" link

/ae plinfo skipPlugins

### Server Log

https://mcpaste.io/3216b43e5b07dfc4

**Comment by Burchard36** [comment]
Will be fixed next update 

What server version are you on by the way

**Comment by ERogovtsoff** [comment]
Paper(1620) 1.12.2-R0.1-SNAPSHOT
