### ISSUE TITLE
Scrolls, Dust, Detonate do not WORK

### ISSUE THREAD

**Issue by Serpentfan** [GC-spigot/AdvancedEnchantments#280]
Scrolls and dust do not work on books or items. When I drag a magic dust (+success rate) on to a book it just doesn't do anything. When I drag a scroll (example: white scroll) onto an item it also doesn't do anything. Detonate 9 and Atomic Detonate 9 pickaxe's do not react/work. When digging it digs like a normal pickaxe but never clears a 3x3 or a 7x7 area of blocks. The server has spigot 1.13.2 and I am hoping there is a possible fix for this (if so a possible date of when a fix might be available).

Thank you for your kind attention

**Comment by GC-spigot** [comment]
What version are you using? Also any errors in console?
