### ISSUE TITLE
Bow enchantments do not proc [again]

### ISSUE THREAD

**Issue by Fenor-NG** [GC-spigot/AdvancedEnchantments#2800]
### Describe the bug

My bows enchantments do not proc (debug mode enabled), i already reported the issues, you closed it and said it was fixed, i tested 3 times in the lastest version (8.9.23) and it does not work. It worked and it stopped worked at a moment that i do not remember (before the first report).
bow-full-power: false

### How to reproduce

punch yourself, with a bow that have hellfire or explosive enchantments with chance to 100

### "/ae plinfo" link

https://paste.md-5.net/kovoxucuja

**Comment by Burchard36** [comment]
Can you send the enchantment please? Because i indeed did fix enchantments related to BOW_SHOOT in #2760 even though it was a particle effect it will still work for most other effects so please do send me the enchantment

**Comment by Fenor-NG** [comment]
hellfire:
  display: '%group-color%Hellfire'
  description: "All arrows shot by you turn\ninto explosive fireballs when\n in contact with the enemy."
  applies-to: 'Bow'
  type: 'BOW'
  group: 'ULTIMATE'
  applies:
    - BOW
  levels:
    1:
      chance: 25
      cooldown: 3
      effects:
        - 'FIREBALL %victim%'
    2:
      chance: 30
      cooldown: 3
      effects:
        - 'FIREBALL %victim%'
    3:
      chance: 45
      cooldown: 3
      effects:
        - 'FIREBALL %victim%'
    4:
      chance: 55
      cooldown: 3
      effects:
        - 'FIREBALL %victim%'
    5:
      chance: 70
      cooldown: 3.2
      effects:
        - 'FIREBALL %victim%'
explosive:
  display: '%group-color%Explosive'
  description: 'Lance des flêches explosive.'
  applies-to: 'Arcs'
  type: 'BOW'
  group: 'UNIQUE'
  applies:
    - BOW
    - CROSSBOW
  levels:
    1:
      chance: 20
      cooldown: 7
      effects:
        - 'TNT %victim%'
    2:
      chance: 30
      cooldown: 8
      effects:
        - 'TNT %victim%'
    3:
      chance: 40
      cooldown: 8
      effects:
        - 'TNT %victim%'
    4:
      chance: 50
      cooldown: 8
      effects:
        - 'TNT %victim%'
    5:
      chance: 100
      cooldown: 0
      effects:
        - 'TNT %victim%'
explosuve:
  applies-to: "Arcs"
  display: '%group-color%Explosuve'
  description: 'Lance des flêches explosive.'
  type: "BOW;BOW_MOB"
  group: "UNIQUE"
  applies:
    - BOW
    - CROSSBOW
  levels:
    1:
      chance: 20
      cooldown: 7
      effects:
        - 'TNT %victim%'
    2:
      chance: 30
      cooldown: 8
      effects:
        - 'TNT %victim%'
    3:
      chance: 40
      cooldown: 8
      effects:
        - 'TNT %victim%'
    4:
      chance: 50
      cooldown: 8
      effects:
        - 'TNT %victim%'
    5:
      effects:
        - "TNT %victim%"
        - "MESSAGE:test"
   (explosuve is an enchantment that a moderator send to me for test)

**Comment by Fenor-NG** [comment]
i tested with BOW_SHOOT, it activate, but do not effect on players
