### ISSUE TITLE
REMOVE_ENCHANT doesn't work 

### ISSUE THREAD

**Issue by Neekokaiinn** [GC-spigot/AdvancedEnchantments#2803]
### Describe the bug

version: latest (8.9.23)
server version: 1.8.8

Enchantements : somes, it doesn't work on all my enchant who have this effect :

gift4u:
  display: '%group-color%Gift 4 U'
  description: 'give'
  applies-to: 'all'
  group: 'SIMPLE'
  type: 'HELD;DEFENSE;ATTACK;RIGHT_CLICK'
  applies:
    - 'ALL_SWORD'
  levels:
    '1':
      chance: 100
      cooldown: 1
      effects:
        - 'CONSOLE_COMMAND:aegive %attacker name% cookie 1 name:&aHibiscus %attacker%'
        - 'REMOVE_ENCHANT:gift4u'

cookie is gave but enchant not removed

contrepret:
  display: '%group-color%Contre prÃªt'
  description: 'big hit'
  applies-to: 'Sword'
  group: 'ONHIT'
  type: 'ATTACK'
  applies:
    - 'ALL_SWORD'
  levels:
    '1':
      chance: 100
      effects:
        - 'INCREASE_DAMAGE:100 %victim%'
        - 'ADD_HARM:17 %victim%'
        - 'REMOVE_ENCHANT:contrepret %attacker%'
        - 'PLAY_SOUND:SKELETON_DEATH:30:100 %attacker%'
    '2':
      chance: 100
      effects:
        - 'INCREASE_DAMAGE:100 %victim%'
        - 'ADD_HARM:25 %victim%'
        - 'REMOVE_ENCHANT:contrepret'
        - 'PLAY_SOUND:SKELETON_DEATH:30:100 %attacker%'
    '3':
      chance: 100
      effects:
        - 'INCREASE_DAMAGE:100 %victim%'
        - 'ADD_HARM:42 %victim%'
        - 'REMOVE_ENCHANT:contrepret %attacker%'
        - 'PLAY_SOUND:SKELETON_DEATH:30:100 %attacker%'

Dammage dealt but enchant not removed

commotionhit:
  display: '%group-color%Commotion hit'
  description: 'hit are more strong and last fear'
  applies-to: 'Sword'
  group: 'ONHIT'
  type: 'ATTACK'
  applies:
    - 'ALL_SWORD'
  levels:
    '1':
      chance: 100
      effects:
        - 'INCREASE_DAMAGE:100 %attacker%'
        - 'POTION:BLINDNESS:0:80 %victim%'
        - 'POTION:SLOW:150:80 %victim%'
        - 'POTION:JUMP:250:80 %victim%'
        - 'RESET_COMBO %attacker%'
        - 'REMOVE_ENCHANT:commotionhit %attacker%'
    '2':
      chance: 100
      effects:
        - 'INCREASE_DAMAGE:50 %attacker%'
        - 'ADD_ENCHANT:commotionhit:1 %attacker%'
        - 'RESET_COMBO %attacker%'
    '3':
      chance: 100
      effects:
        - 'INCREASE_DAMAGE:50 %attacker%'
        - 'ADD_ENCHANT:commotionhit:2 %attacker%'
        - 'RESET_COMBO %attacker%'
    '4':
      chance: 100
      effects:
        - 'INCREASE_DAMAGE:150 %attacker%'
        - 'ADD_ENCHANT:commotionhit:3 %attacker%'
        - 'RESET_COMBO %attacker%'

(this enchant is a 4hit enchant, first you have 3 hit who will decrease enchant lvl (for counting hits) and at last hit the enchant should be removed)
effect are gave but enchant not removed

### How to reproduce

use enchantemens on 1.8.8 server with same thing as me i guess 

### Screenshots / Videos

https://youtu.be/ZFNZLlydjiU
https://youtu.be/L8xv4WgpYDE

### "/ae plinfo" link

https://paste.md-5.net/omexijucip

### Server Log

this is what happen when i use gift4u : https://mcpaste.io/bbfce4ab9095e631

**Comment by Neekokaiinn** [comment]
Update : it doesn't work with the newest update too 8.10.4

**Comment by Neekokaiinn** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/issues/2844
its the same issue i put this here for the moment when my issue we'll be see.

**Comment by GC-spigot** [comment]
Should be resolved
