### ISSUE TITLE
AE armor Effect Issue

### ISSUE THREAD

**Issue by ghostplays00** [GC-spigot/AdvancedEnchantments#2804]
### Describe the bug

Custom Armorsets with EVENT Effect FLAME trigger by Defense 
i setup an ArmorSets with an effect / Event "FLAME" and my plan is Every time player hit you,Attaker will be Burn and its work from past version 1.17.1 and when my server update to 1.18.2 with a 8.9.x version of Advance Enchantemt
the armor set didnt work fine in latest version... the "FLAME %attacker%" didnt work instead of attacker burn , the player who equiped the armor that burn

### How to reproduce

# Advanced Sets
# These sets are fully creatable, to create your own simply copy this file, rename it and edit it however you want!

# ** Set Materials:
# * LEATHER (change-able color) https://github.com/GC-spigot/AdvancedEnchantments/wiki/�-Colored-Leather-Armor
# * IRON
# * GOLD
# * CHAIN
# * DIAMOND

# ** Enchantment effects are supported - view enchantments.yml to see all effects available for sets.

#  ** Set Events
#    Change upon what event should sets trigger
#    - EFFECT_STATIC : Gives permanent potion effect (as long as armor piece is worn)
#    - ATTACK : Set Event run only when attacking another player
#    - DEFENSE : Set Event run only when being attacked
#    - DEFENSE_BOW : Set Event run only when player gets shot by a bow
#    - MINING : Gives effects when block is mined
#    - ATTACK_MOB : Gives effects when player attacks mob
#    - KILL_MOB : Effects given when attacked mob is killed
#    - BOW : Effects given when player is shot by another player
#    - KILL_PLAYER : Effects given when attacker kills a player
#    - DEATH : Runs when player dies due to another player.
#    - RIGHT_CLICK : Runs when player right clicks held item
#    - BOW_MOB : Effects given when mob is shot by player
#    - FIRE : Effects given when player is on fire
#    - EXPLOSION : Effects given when player gets hit by explosion
#    - SWING : Enchant runs when player swings
#    - FALL_DAMAGE : Set Event runs when player takes fall damage
#    - DEFENSE_MOB : Set Event runs when mob attacks a player
#    - SHIFT : Set Event runs when player toggles crouching (shifts)
#    - ITEM_BREAK : Set Event runs when player toggles crouching (shifts)
#    - CATCH_FISH : Set Event runs when player catches a fish
# Set Events & Enchant types are intercompatible together

# ** Creating set effects, this explains the system
#events:
#  <any of the effects from the list>:
#    chance: <chance of effects activating, 1-100> (Optional)
#    cooldown: <cooldown period after effects activate, in seconds> (Optional)
#    effects: <effects are available in enchantments.yml>
#    # E.g.: - 'INCREASED_DAMAGE:10'

name: '&4&lDragonicflame Set'
material: DIAMOND
settings:
  equipped:
    - '&a&l(!) &aYou have now wear &c&lDRAGONIC SKINS!&A Dragon spirit is with you!'
  unequipped:
    - '&c&l(!) &cYou have now wear &c&lDRAGONIC SKINS!&A Dragon spirit departed your soul!'
items:
  helmet:
    name: '&f&l-=[&e&lઑ&f&l]=-  &c&lHelm &7&l&oof the &4&lFlame Dragons &f&l-=[&e&lઑ&f&l]=-'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 0
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
      - '&4&l ☬ &c&l&n&oDRAGON SLAYER LORE'     
      - '&c Made from the scales of a 1st Gen Dragon Slayer,'
      - '&chalf dragon half human. It is said that when '
      - '&cworn the full set you have the power of a Dragon.'
      - ''
      - '&4&l ☬ &c&l&n&oDRAGON SLAYER BONUS'
      - '&f&lEnemies deal 30% less damage to you.'
      - '&f&l* Permanent Fire resistance'
      - '&f&l* Chance to pullaway and get fire to the attacker'
      - '&7&o&l(Requires all 4 DRAGON SLAYER GEAR.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:9"
      - "unbreaking:9"
      - "projectile_protection:4"
      - "deathbringer:%1-3%"
      - "dodge:%1-5%"
      - "valor:%1-5%"
  chestplate:
    name: '&f&l-=[&e&lઑ&f&l]=- &c&lAegis &7&l&oof &4&lIGNEEL &f&l-=[&e&lઑ&f&l]=-'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 0
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
      - '&4&l ☬ &c&l&n&oDRAGON SLAYER LORE'    
      - '&cForged from the breath of Igneel, '
      - '&cthe king of Fire Dragons. Made from his scales, '
      - '&cmaking it really hard to pierce.'
      - ''
      - '&4&l ☬ &c&l&n&oDRAGON SLAYER BONUS'
      - '&f&lEnemies deal 30% less damage to you.'
      - '&f&l* Permanent Fire resistance'
      - '&f&l* Chance to pullaway and get fire to the attacker'
      - '&7&o&l(Requires all 4 DRAGON SLAYER GEAR.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:9"
      - "unbreaking:9"
      - "projectile_protection:4"
      - "enlighted:%1-3%"
      - "tank:%1-4%"
      - "disappear:%1-4%"
  leggings:
    name: '&f&l-=[&e&lઑ&f&l]=- &c&lChausses &7&o&lof the &4&lFlame Kingdom &f&l-=[&e&lઑ&f&l]=-'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 0
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
      - '&4&l ☬ &c&l&n&oDRAGON SLAYER LORE'     
      - '&cStolen from the Fire Dragon Kingdom,'
      - '&cscales of a dragon forged into Leggings,'
      - '&cprotecting the lower part of your body. Almost impenetrable'
      - ''
      - '&4&l ☬ &c&l&n&oDRAGON SLAYER BONUS'
      - '&f&lEnemies deal 30% less damage to you.'
      - '&f&l* Permanent Fire resistance'
      - '&f&l* Chance to pullaway and get fire to the attacker'
      - '&7&o&l(Requires all 4 DRAGON SLAYER GEAR.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:9"
      - "unbreaking:9"
      - "projectile_protection:4"
      - "arrowdeflect:%1-3%"
      - "demonic:%1-3%"
      - "valor:%1-5%"
      - "masterblacksmith:%1-4%"
  boots:
    name: '&f&l-=[&e&lઑ&f&l]=- &4&l&oDragonscale &c&lGreaves &f&l-=[&e&lઑ&f&l]=-'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 0
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
      - '&4&l ☬ &c&l&n&oDRAGON SLAYER LORE'   
      - '&cForged inside of a Dragons mouth, taken from a '
      - '&cdragons foot, took years to make. Said when worn,'
      - '&cyou can walk on lava with no problems.'
      - ''
      - '&4&l ☬ &c&l&n&oDRAGON SLAYER BONUS'
      - '&f&lEnemies deal 30% less damage to you.'
      - '&f&l* Permanent Fire resistance'
      - '&f&l* Chance to pullaway and set in fire to the attacker'
      - '&7&o&l(Requires all 4 DRAGON SLAYER GEAR.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:9"
      - "unbreaking:9"
      - "projectile_protection:4"
      - "angelic:1"
      - "marksman:%1-4%"
      - "ragdoll:%1-4%"
      - "disintegrate:%1-4%"

events:
  EFFECT_STATIC:
    effects:
      - 'POTION:FIRE_RESISTANCE:0'
      
  DEFENSE: 
    chance: 50
    effects:
      - 'PULL_AWAY:2 %attacker%'
      - 'FLAME:2 %attacker%'
      - 'NEGATE_DAMAGE:20'    
      
  DEFENSE_MOB:
    chance: 25
    effects:
      - 'PULL_AWAY:2 %attacker%'
      - 'FLAME:2 %attacker%'
      - 'NEGATE_DAMAGE:20'

### "/ae plinfo" link

https://paste.md-5.net/lipunasete

### Server Log

https://mcpaste.io/2a772892a222bbce

**Comment by illudota** [comment]
variables don't work in armorsets, I reported this several times already and it seems like they're busy fixing other stuff

**Comment by GC-spigot** [comment]
Fixed
