### ISSUE TITLE
Telepathy Causes Items attached to block to disappear

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2806]
### Describe the bug

Breaking a block with a torch, lever, etc, attached to that block, causes that item to disappear.

### How to reproduce

Place torch on stone block. Mine stone block with TELEPATHY enchanted tool.

### "/ae plinfo" link

https://paste.md-5.net/awafijumic

**Comment by GC-spigot** [comment]
Fixed
