### ISSUE TITLE
Players cannot fish

### ISSUE THREAD

**Issue by FrontierGamers** [GC-spigot/AdvancedEnchantments#281]
07.01 15:12:02 [Server] WARN java.io.FileNotFoundException: http://n3.fyi/ae/connections/connector.php?&s=a264a4a68ac0df343d1aa5c298a18683&p=38&h=play.armonicpvp.net&ae=5.1.3&buyer=%%__USER__%%
07.01 15:12:02 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
07.01 15:12:02 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
07.01 15:12:02 [Server] WARN at n3kas.ae.utils.TagUtils.a(TagUtils.java:102)
07.01 15:12:02 [Server] WARN at n3kas.ae.utils.TagUtils.access$0(TagUtils.java:87)
07.01 15:12:02 [Server] WARN at n3kas.ae.utils.TagUtils$1.run(TagUtils.java:45)
07.01 15:12:02 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
07.01 15:12:02 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
07.01 15:12:02 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
07.01 15:12:02 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
07.01 15:12:02 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by GC-spigot** [comment]
Not related to fishing in any way. Update for this to be fixed.
