### ISSUE TITLE
Enchant Smelting Bug

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#2811]
### Describe the bug

Use Enchant Smelting to mine the block with playerhead will drop x2 heads.

### How to reproduce

Use Enchant Smelting to mine the block with playerhead will drop x2 heads.

### Screenshots / Videos

https://youtu.be/4y9S6wkrAPM

### "/ae plinfo" link

https://paste.md-5.net/aciyutahij

**Comment by Burchard36** [comment]
Hello this is likely due to your stacking plugin, can you please update to the latest version and try again?

**Comment by uploadx10** [comment]
Enchant Smelting drop x2
Pickaxe Normal not bug
