### ISSUE TITLE
McMMO possibly conflicts with the replanter enchant(default enchant) - breaking it

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#2813]
### Describe the bug

Basically, from what I know, it makes the replanter enchant bi-polar. One minute it works, the next it doesn't. Finally after posting 10 times in the discord explaining that it kept shutting off and on, I realize that right after I used mcmmo herbalism skill "green thumb", it started to work right after that skill for mcmmo disabled.  https://mcmmo.fandom.com/wiki/Herbalism

### How to reproduce

Use McMMO - use the replanter for a bit, I have just under 100 herbalism level and it breaks the enchant - unbreaks it - breaks it - no config error, debug information is below.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/87890013/167229452-bead14e5-7e9d-4a74-a817-da50852c3826.png)
https://gyazo.com/a7473e7a02f2d38ecd11ef6ad3a9cfeb

### "/ae plinfo" link

https://paste.md-5.net/yawujeceyi

### Server Log

https://paste.helpch.at/feborelowo.md

**Comment by ClickErrorxD** [comment]
It appears that this is more of an issue that it stops working at night time. Please do test.

**Comment by BloodshotPico** [comment]
@ClickErrorxD do you happen to know if this is still caused with the newer versions?
