### ISSUE TITLE
veinminer + trench = dupe lazuli

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#2814]
### Describe the bug

This was reported by BeDePaY[Admin]#4680 | 563684198448234497
Here's the [transcript](https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/839378013346725888/972529055343714344/transcript-aenchantments-1996.html)

### How to reproduce

veinminer + trench enchantment.

### Screenshots / Videos

https://youtu.be/iTRvfQpsGKk

### "/ae plinfo" link

N/A

**Comment by GC-spigot** [comment]
Fixed
