### ISSUE TITLE
%victim% not working on armor sets

### ISSUE THREAD

**Issue by TheJoeEnder** [GC-spigot/AdvancedEnchantments#2815]
### Describe the bug

%victim% isn't working on custom armor sets. When inputting it as an effect, and loading the armor set, the plugin does not recognize it.

### How to reproduce

EXAMPLE:
events:
  ATTACK:
    chance: 50
    effects:
      - 'BLOOD %victim%'

Now a few things, obviously the event could be anything, but this must be done on a custom armor set.
The chance and effect does not matter, only the %victim% argument, which does not recognize.  

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/99829737/167281687-1e5994ce-a5a6-4993-812f-b7d742ed27e5.png)

### "/ae plinfo" link

https://paste.md-5.net/jazelayuna

### Server Log

![image](https://user-images.githubusercontent.com/99829737/167281794-2c63455c-0f53-4c9f-b30a-840614573c21.png)

**Comment by illudota** [comment]
still not fixed :/

**Comment by GC-spigot** [comment]
Fixed
