### ISSUE TITLE
REPEATING enchant for repairing armor doesn't work

### ISSUE THREAD

**Issue by newbandpro** [GC-spigot/AdvancedEnchantments#2816]
### Describe the bug

The item is meant to be repaired over time but it only repairs once or twice then stops. I've used ADD_DURABILITY and ADD_DURABILITY_ITEM,none of them work. ADD_DURABILITY_CURRENT_ITEM does work however but it only repairs the held item,not the armor.

### How to reproduce

Use this enchant on a piece of armor:

reconstruct:
  display: "%group-color%Reconstruct"
  description: "Restores durability over time."
  applies-to: "Armor"
  type: "REPEATING"
  group: "LEGENDARY"
  time: 5
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 10
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    2:
      chance: 20
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    3:
      chance: 30
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    4:
      chance: 40
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    5:
      chance: 50
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    6:
      chance: 60
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    7:
      chance: 70
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    8:
      chance: 80
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    9:
      chance: 90
      effects:
        - "ADD_DURABILITY_CURRENT_ITEM:-1"
    10:
      effects:
        - "ADD_DURABILITY:-1"

### "/ae plinfo" link

https://paste.md-5.net/sukagicego

**Comment by GC-spigot** [comment]
Fixed
