### ISSUE TITLE
VEIN_MINE

### ISSUE THREAD

**Issue by xmakdwerd** [GC-spigot/AdvancedEnchantments#2817]
### Describe the bug

levels:
1:
chance: 15
cooldown: 4
effects:
- "VEIN_MINE"
2:
chance: 35
cooldown: 3
effects:
- "VEIN_MINE"
3:
effects:
- "VEIN_MINE"

Tmistake is that he cuts blocks that do not touch, he cuts them at some distance, and the distance is quite large, it may be that, as for me, it’s not very correct, I see it, that there are ores that are in contact with each other and only they must be mined, and ores that remain untouched, they must not break
Attached is a video of the issue.

### How to reproduce

Break blocks with this spell

### Screenshots / Videos

https://youtu.be/0y3PJCMlLaw

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by xmakdwerd** [comment]
I broke 1 block of iron and I turned out to have 64 iron, although luck 3 was on the pick, but apparently it broke all the iron in that direction

**Comment by Awpmeister2170** [comment]
Fixed in recent update
