### ISSUE TITLE
Problem With Ores

### ISSUE THREAD

**Issue by Aquamonk** [GC-spigot/AdvancedEnchantments#2820]
### Describe the bug

Problem with ores spamming console and chat when using mine enchants.
Tested in Trench & Smelting.

### How to reproduce

Just install last version of the plugin on a 1.12.2 server

### Screenshots / Videos

https://i.imgur.com/XWVOHlV.png
https://i.imgur.com/ZoaGYtF.png
https://i.imgur.com/T2wI07O.png
https://i.imgur.com/fbaaAY3.png
https://i.imgur.com/2z3Kxgo.png

### "/ae plinfo" link

https://paste.md-5.net/apojozuqes

### Server Log

https://mcpaste.io/061b6d22c15eb095

**Comment by Burchard36** [comment]
Hello this bug will be fixed next update
