### ISSUE TITLE
Console Error Killing Player

### ISSUE THREAD

**Issue by Aquamonk** [GC-spigot/AdvancedEnchantments#2821]
### Describe the bug

Console error when killing a player

### How to reproduce

Killing a player with the last version of the plugin on a 1.12.2 server

### Screenshots / Videos

https://i.imgur.com/1lRKkDq.png
https://i.imgur.com/mo8EAOv.png

### "/ae plinfo" link

https://paste.md-5.net/ovaqorejiz

### Server Log

I just can't reproduce it now because I'm alone in the server, but you got Screenshots!

**Comment by GC-spigot** [comment]
Fixed
