### ISSUE TITLE
applying custommodel data with orb, whitescroll

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2824]
### Describe the bug

when i change orb and whitescroll's type in config, custommodeldata, it was not change properly.
(other items are changed, [magic dust, randombook, etc..)

1. orb was not change type.
2. white-scroll was not changed custommodeldata.

### How to reproduce

![22](https://user-images.githubusercontent.com/25452835/167627882-51aa3f86-d7e6-40e9-8a65-c8a724e14a41.PNG)
![1](https://user-images.githubusercontent.com/25452835/167627888-2254ee7c-b6f0-4847-ba60-074829cbbad8.PNG)

### "/ae plinfo" link

https://paste.md-5.net/ejoxolubob

**Comment by Ecilpse** [comment]
and is there other ways to change each's group enchant-book's custom model data?
(not randombook, enchantment-book in config.)

**Comment by DuneSciFye** [comment]
Pretty sure 8.10.3 fixed this. @Ecilpse

**Comment by Ecilpse** [comment]
> Pretty sure 8.10.3 fixed this. @Ecilpse

i updated lastest build. but still same issue. not fixed.
