### ISSUE TITLE
Translation break

### ISSUE THREAD

**Issue by norhu1130** [GC-spigot/AdvancedEnchantments#2825]
### Describe the bug

![image](https://user-images.githubusercontent.com/46096192/167836366-34a84820-05fc-445e-8c6e-e1618260bf8e.png)
When applying Korean translation, some letters break.

### How to reproduce

Just set lang "ko"

### "/ae plinfo" link

https://paste.md-5.net/bezeziposi

**Comment by GC-spigot** [comment]
Fixed
