### ISSUE TITLE
VEIN_MINE was not worked with MORE_DROPS

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2826]
### Describe the bug

literally. VEIN_MINE not worked with MORE_DROPS

### How to reproduce

증식: #영혼 매커니즘 제거하고 수치조정
  display: "%group-color%증식"
  description: "광물 블록 채광시에,\n확률적으로 광물획득량이 늘어납니다."
  applies-to: "곡괭이"
  type: "MINING"
  group: "레전더리"
  applies:
    - ALL_PICKAXE
  not-applyable-with:
    - "SILK_TOUCH"
    - "SILKTOUCH"
  levels:
    1:
      chance: 30
      cooldown: 1
      condition:
        - "%block type% contains ORE : %allow%"
        - "%has enchantment in hand of SILK_TOUCH% : %deny%"
        - "%has enchantment in hand of SILKTOUCH% : %deny%"
      effects:
        - "MORE_DROPS:5"
    2:
      chance: 40
      cooldown: 1
      condition:
        - "%block type% contains ORE : %allow%"
        - "%has enchantment in hand of SILK_TOUCH% : %deny%"
        - "%has enchantment in hand of SILKTOUCH% : %deny%"
      effects:
        - "MORE_DROPS:6"
    3:
      chance: 50
      cooldown: 1
      condition:
        - "%block type% contains ORE : %allow%"
        - "%has enchantment in hand of SILK_TOUCH% : %deny%"
        - "%has enchantment in hand of SILKTOUCH% : %deny%"
      effects:
        - "MORE_DROPS:7"

광맥: #3레벨 50퍼로 조정 추후 더 해방
  display: "%group-color%광맥"
  description: "확률적으로 광물이 이어진\n광맥을 한번에 채굴합니다.\n&7(효과 발동시 바닐라 경험치는 오르지 않습니다)"
  applies-to: "곡괭이"
  group: "에픽" #레어
  type: "MINING"
  applies:
    - "ALL_PICKAXE"
  levels:
    1:
      chance: 30
      cooldown: 1
      effects:
        - "VEIN_MINE"
    2:
      chance: 50
      cooldown: 1
      effects:
        - "VEIN_MINE"
    3:
      chance: 70
      cooldown: 1
      effects:
        - "VEIN_MINE"

### "/ae plinfo" link

https://paste.md-5.net/jehoveqevo

**Comment by Burchard36** [comment]
Hello there the version of your plugin is severely outdated, update to 8.10.4 and let me know if the issue still persists for your!

**Comment by Ecilpse** [comment]
> Hello there the version of your plugin is severely outdated, update to 8.10.4 and let me know if the issue still persists for your!

i tested lastest version of AE, but still not worked. 
plinfo : https://paste.md-5.net/nediyawoqi

**Comment by Burchard36** [comment]
Hey there, bug is fixed on my end and will be implemented next update!

**Comment by Burchard36** [comment]
Update is out, please add a comment to this issue if its still broken for you afterwards :)
