### ISSUE TITLE
%group-name% doesn't work in chat

### ISSUE THREAD

**Issue by Golicraft** [GC-spigot/AdvancedEnchantments#2828]
### Describe the bug

When I right click enchanted book in chat it displays %group-image% instead of the input. 

![image](https://user-images.githubusercontent.com/11066952/168139170-9948bfec-3706-4fa1-9073-bfc7ac710ac4.png)

This use the same lore as in the GUI, where it works just fine:
![image](https://user-images.githubusercontent.com/11066952/168139365-ae1c79ba-c417-47c6-a6a0-17856b52135d.png)

### How to reproduce

Add %group-name% to lore, then right-click item in-game. 

### "/ae plinfo" link

https://paste.md-5.net/uyoyekejip

**Comment by Burchard36** [comment]
Can you send the configuration you are using to make the book look like this when right-clicked? This doesn't look like the default configuration

**Comment by Golicraft** [comment]
It's this part in customcommands.yml `    item:
      type: EMERALD
      id: 0
      custom-model-data: 0
      force-glow: false
      # What command should be ran when player clicks on one of the enchantments?
      # %max-lvl% - Displays max. level in numbers, %max-lvl-roman% - displays max. level in roman numerals
      command: "/enchant %enchantment%"
      name: "%group-color%Rune of &l%enchant-no-color%"
      lore:
        - "&7%desc%"
        - ""
        - '&8▎ &7Rarity: %group-color%%group-name%'
        - '&8▎ &7Usage: &f%applies-to%'
        - "&8▎ &7Max Level: &f%max-lvl-roman%"
`

**Comment by Golicraft** [comment]
![image](https://user-images.githubusercontent.com/11066952/170844516-cd120588-3c39-4a4d-ae99-d9e40ea33158.png)

**Comment by GC-spigot** [comment]
Fixed
