### ISSUE TITLE
Armour effects not reapplying after death

### ISSUE THREAD

**Issue by cloverlucy** [GC-spigot/AdvancedEnchantments#2831]
### Describe the bug

Enchantments on armour currently don't reapply their effects after dying with keep inventory, and you have to remove the armour and reapply it after respawning for them to work. For example, the Overload enchant will not give you the extra hearts after respawning unless you take the armour piece off and apply it again. This only happens if you die in the same world as the respawn location.

### How to reproduce

1) Put armour piece on with a custom enchant applied to it
2) Die whilst wearing the armour piece (with keep inventory) in the same world as respawn location
3) Have to reapply the armour after respawning to get the effects of the custom enchant back

### "/ae plinfo" link

https://paste.md-5.net/urixagisum

**Comment by Burchard36** [comment]
Hello there, sorry for the delay this bug will be fixed next update

**Comment by Burchard36** [comment]
Update is out now, please update!
