### ISSUE TITLE
Custom items (like mmoitems) and items with custom enchants don't work on itemframes

### ISSUE THREAD

**Issue by Truongvv10** [GC-spigot/AdvancedEnchantments#2833]
### Describe the bug

After updating AE from 8.10.1 to 8.10.3, custom items like mmoitems, or just vanilla items with ae enchants can't interact with itemsframes or another example is custom shears (made with mmoitems or ae enchants) not working on sheeps

### How to reproduce

Enchant an item with an ae enchant (version 8.10.3) and put it in an itemframe
Enchant a shear with an ae enchant (version 8.10.3) and shear a sheep

### Screenshots / Videos

https://user-images.githubusercontent.com/67742370/168450804-5a634863-0c9d-416d-a0ac-9a059a9cbe1e.mp4

### "/ae plinfo" link

https://paste.md-5.net/quwotehoju

**Comment by Burchard36** [comment]
Fixed for next update!

**Comment by Burchard36** [comment]
Version is out now, update and it shall be fixed! :)
