### ISSUE TITLE
Bug: Shear/Nametag/ItemFrame

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#2834]
### Describe the bug

Can't right click guys Shear/Nametag/ItemFrame There may be more than that, I just found this problematic. because the latest version update

### How to reproduce

right click guys Shear/Nametag/ItemFrame

### Screenshots / Videos

-

### "/ae plinfo" link

https://paste.md-5.net/vapemozexu

### Server Log

-

**Comment by Regerta** [comment]
Same here, I can't give nametag to mobs after updating to AE 8.10.4 (latest version)
Nametag are working fine on AE 8.10.1

**Comment by Burchard36** [comment]
Will look into this ASAP

**Comment by Burchard36** [comment]
Fixed for next update!

**Comment by Burchard36** [comment]
Update is out now, please update !
