### ISSUE TITLE
Advanced Enchantments disables itself in startup

### ISSUE THREAD

**Issue by KochPatrick** [GC-spigot/AdvancedEnchantments#2835]
### Describe the bug

I have the latest version of Advanced Enchantments installed (v.8.10.3) the plugin won't start-up on my server my server version is 1.18 

### How to reproduce

I just start the server up and it does this I'll paste the startup log below

### "/ae plinfo" link

It won't work it just says /AdvancedEnchantments in a white text

### Server Log

https://mcpaste.io/1b6896e6ea735a5e

**Comment by Burchard36** [comment]
Hello, there can you contact us on discord regarding this issue? This isn't a bug with our plugin but likely something configured on your server

**Comment by KochPatrick** [comment]
I created a ticket on your server before but I was directed to go to github
