### ISSUE TITLE
interact citizens NPC by rightclick.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2837]
### Describe the bug

i updated version 8.10.4 to 8.9.20, player can't open gui with custommodel-sword. (citizens npc command)
when i disable AE by plugman, it worked properly.

### How to reproduce

1. create npc with citizens.
2. /npc command add "test command" -r -o --cooldown 3
3. hand custom model's tools and right click NPC

### "/ae plinfo" link

https://paste.md-5.net/ubunepiyaw

**Comment by Burchard36** [comment]
Hello, when 8.10.5 is out do try this again, this version (not released yet) should fix your issue!

**Comment by Burchard36** [comment]
version is out now, and i personally tested this and it worked with me, enjoy :)
