### ISSUE TITLE
Block Trak Orb lore infinitely duping

### ISSUE THREAD

**Issue by Vaspei** [GC-spigot/AdvancedEnchantments#2839]
### Describe the bug

When a player adds the block trak orb to their item (so far only happens with pickaxes with trench enchantment) every few seconds of mining blocks, an extra line of the block trak info gets added to the lore.

Plugin Version: 8.10.5
Server Version: Paper-134 (MC: 1.18.1)

### How to reproduce

Seems to only happen with pickaxes with trench

### Screenshots / Videos

https://vaspei.us/ss/qr4vs.png

### "/ae plinfo" link

https://paste.md-5.net/imaqabahok.css

**Comment by ClickErrorxD** [comment]
We're experiencing this too!
I am unable to get a video of it as player's are experiencing this.

Paper-Spigot 1.18.2

**Comment by ClickErrorxD** [comment]
> We're experiencing this too! I am unable to get a video of it as player's are experiencing this.
> 
> Paper-Spigot 1.18.2
![2022-06-29_07 51 33](https://user-images.githubusercontent.com/87890013/176430469-c90c51b0-0596-4d0b-a9ed-019f561ff6a3.png)

**Comment by ClickErrorxD** [comment]
> 

You might have to add it from a different version(s) and then update to current version(s)? Based on another report they kinda suggest it. https://github.com/GC-spigot/AdvancedEnchantments/issues/2887
