### ISSUE TITLE
Turtle helmets are not detected as helmet [BUMP]

### ISSUE THREAD

**Issue by samfces** [GC-spigot/AdvancedEnchantments#2840]
### Describe the bug

When configuring the "applies" section with "ALL_HELMET" setting, it appears that the turtle helmet is not a helmet.
NOTE: I've duplicated the issue because old issue was not attended. (I was waiting for a response more than 3 weeks)

### How to reproduce

To reproduce the bug, the following steps must be taken:
- Configure an enchantment so that it can only be applied to helmet.
- Try to add the enchantment to a turtle helmet.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/26687602/163154385-f56f50db-c927-4b75-942d-48b279e2884d.png)
![image](https://user-images.githubusercontent.com/26687602/163154671-4d864d03-0ebb-41a7-b504-9e129b9a1493.png)

### "/ae plinfo" link

https://paste.md-5.net/fiqehahene

**Comment by GC-spigot** [comment]
Fixed
