### ISSUE TITLE
EXP not converting to Levels in placeholders

### ISSUE THREAD

**Issue by TizoCraft** [GC-spigot/AdvancedEnchantments#2841]
### Describe the bug

in the config.yml the enchanter option if you switch to levels instead of exp the %price% and %left% placeholder still shows the number in exp and not in levels which is very confusing for players if they think they need to have 1500 levels.

### How to reproduce

use price: level:10 and see that the numbers from the placeholders still shows exp

### "/ae plinfo" link

https://paste.md-5.net/xogahiwuji

### Server Log

https://mcpaste.io/86ebaa81ac1767fa

**Comment by GC-spigot** [comment]
It's designed to be this way unfortunately, hopefully in future we rework how it functions
