### ISSUE TITLE
Conditions do not parse correctly with placeholder

### ISSUE THREAD

**Issue by TZ122** [GC-spigot/AdvancedEnchantments#2846]
### Describe the bug

Checkitem placeholders that need to match a specific string will not work because AE parses them as lower case. (This needs an exact match)

Example: 
        - '%player checkitem_amount_namecontains:&d&lName% > 1 : %allow%'
        - "%player checkitem_remove_namecontains:&d&lName,amt:1% = yes : %allow%"

### How to reproduce

Write a checkitem name contains placeholder using AE

Parse this with placeholder vs parse it with AE.

See image below for example

  levels:
    1:
      cooldown: .01
      condition:
        - '%player checkitem_amount_namecontains:&d&lNingen Effigy% > 1 : %allow%'
        - "%player checkitem_remove_namecontains:&d&lNingen Effigy,amt:1% = yes : %allow%"

### Screenshots / Videos

https://cdn.discordapp.com/attachments/976529871268380734/976530292074487889/unknown.png

### "/ae plinfo" link

https://paste.md-5.net/hifavexisa

**Comment by GC-spigot** [comment]
Unfortunately cannot do anything about this at the moment :(
