### ISSUE TITLE
When right clicking a block AE triggers enchant twice

### ISSUE THREAD

**Issue by TZ122** [GC-spigot/AdvancedEnchantments#2847]
### Describe the bug

When using trigger on RIGHT_CLICK function with AE the enchant will activate twice. This was used since there is no trigger for ON_PLACE for example.

### How to reproduce

Put an enchant on a placeable item that uses RIGHT_CLICK function. Place this item on the ground and it will register as a right click twice thus running the enchant twice. 

### Screenshots / Videos

https://www.youtube.com/watch?v=2uRxMeeivKI

### "/ae plinfo" link

https://paste.md-5.net/hifavexisa

**Comment by GC-spigot** [comment]
Fixed
