### ISSUE TITLE
AdvancedEnchantments trench bug

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#2848]
### Describe the bug

The trench does not work correctly with ores, it gives a lot more resources from ore than it should be, which breaks the economy of the server

### How to reproduce

On the video, I showed in detail how bad the trench works, and I also showed what ores it works badly with.
Plugins version: 8.10.5

### Screenshots / Videos

https://youtu.be/RJNVSS7fHrk

### "/ae plinfo" link

----

### Server Log

----

**Comment by GC-spigot** [comment]
Fixed
