### ISSUE TITLE
Detonate enchant does not work for anyone that is not OP-ed

### ISSUE THREAD

**Issue by Serpentfan** [GC-spigot/AdvancedEnchantments#285]
I would just like to say THANK YOU for the quick and amazing fix on the scrolls and magic dusts (for 1.13.2). The only thing for the server I play on that is still broken is "Detonate" and "Atomic Detonate" enchants. They do not work (do not destroy 7x7 or 3x3 area) for players that do not have operator (OP-ed). The servers spigot is: 1.13.2 and to recreate this scenario we used "Atomic Detonate IX" and "Detonate IX" both of which do not work for normal users that do not have perms. We would just like to know if this is a bug in the plugin or a server side issue with our* perms. 

THANK YOU For your insight and time.

**Comment by Leomelonseeds** [comment]
Some other enchants like Experience and Telepathy don't work unless opped as well.

**Comment by GC-spigot** [comment]
Try with newest updating (will be posted soon), if you keep experiencing same issues let me know.
