### ISSUE TITLE
critical dupe bugs with veinmine+moredrops+fortune

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2851]
### Describe the bug

video : https://www.youtube.com/watch?v=MPkMQLGZnts
### How to reproduce

enchant pickaxe VEIN_MINE/ Fortune / MORE_DROPS

### "/ae plinfo" link

https://paste.md-5.net/ofejisomug

**Comment by Ecilpse** [comment]
if it's not bugs, can you make upper limit?

**Comment by Burchard36** [comment]
Hello there, the video provided is private, you can simply drag and drop the video into the text bar on github to upload it here

Or you can unprivate the video on youtube :) Please response when you have done either or!

**Comment by Ecilpse** [comment]
https://user-images.githubusercontent.com/25452835/169770307-41b051b4-2dad-4104-a8b1-3994b4aab295.mp4



> Hello there, the video provided is private, you can simply drag and drop the video into the text bar on github to upload it here
> 
> Or you can unprivate the video on youtube :) Please response when you have done either or!

https://user-images.githubusercontent.com/25452835/169770328-3f3298d2-ef05-4f2b-9cb1-4d6379b505e9.mp4

**Comment by Ecilpse** [comment]
i tested a while, this problems is occured by more drops. can you check this issue?

**Comment by Ecilpse** [comment]
> Hello there, the video provided is private, you can simply drag and drop the video into the text bar on github to upload it here
> 
> 
> 
> Or you can unprivate the video on youtube :) Please response when you have done either or!

@Burchard36

**Comment by Ecilpse** [comment]
> Hello there, the video provided is private, you can simply drag and drop the video into the text bar on github to upload it here
> 
> Or you can unprivate the video on youtube :) Please response when you have done either or!
i changed link. i can't upload video file because of the file size.
link: https://www.youtube.com/watch?v=MPkMQLGZnts
