### ISSUE TITLE
Rename tag not working[1.8.8]

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2853]
### Describe the bug

Right clicking rename tag does nothing

### How to reproduce

Get a rename tag in 1.8.8 server and try, it doesnt work

### Screenshots / Videos

https://streamable.com/6pv087

### "/ae plinfo" link

https://paste.md-5.net/gulaqeyoye

### Server Log

https://mcpaste.io/7d75c99891f483a6

**Comment by Burchard36** [comment]
Hello there, apologies for that it will be fixed in the next release of AE
