### ISSUE TITLE
Console Error (INK_SAC)

### ISSUE THREAD

**Issue by Aquamonk** [GC-spigot/AdvancedEnchantments#2854]
### Describe the bug

I got this console error

### How to reproduce

Mining with a pickaxe with advanced enchantments

### Screenshots / Videos

https://i.imgur.com/sUMWoZ5.png

### "/ae plinfo" link

https://paste.md-5.net/mofakigoxi

### Server Log

https://pastebin.com/Qp8xAaGe

**Comment by Burchard36** [comment]
Hello there, bug will be fixed next version release

**Comment by Aquamonk** [comment]
Hello, thanks!
