### ISSUE TITLE
BlockTracker

### ISSUE THREAD

**Issue by 10BamberJ** [GC-spigot/AdvancedEnchantments#2856]
### Describe the bug

Block Tracker Stacking After adding Unbreakable

### How to reproduce

Netherite Pickaxe

Efficiency V
Silk Touch
Mending 
Unbreaking III
Experience V
Telepathy IV
Reforged IX
- Added Block Tracker
Trench IX
- Added White Scroll/Protection scroll
- Added Unbreakable (Fabled Enchant)

### Screenshots / Videos

https://i.imgur.com/dfPBbJY.png

### "/ae plinfo" link

https://paste.md-5.net/vawotetego

### Server Log

https://mcpaste.io/72ba5541e18b2a1b

**Comment by Burchard36** [comment]
Hello there, your version of AE is outdated, this was fixed in a later update

After updating to the latest version your bug will be fixed 👍
