### ISSUE TITLE
Detonate Deletes Shulkers

### ISSUE THREAD

**Issue by dsevvv** [GC-spigot/AdvancedEnchantments#2857]
### Describe the bug

When mining a shulker with a pickaxe that has the "Detonate" enchant, the shulker gets deleted. Other blocks are mined normally and as expected.

### How to reproduce

https://www.youtube.com/watch?v=AURgNY2axQ8

### Screenshots / Videos

https://www.youtube.com/watch?v=AURgNY2axQ8

### "/ae plinfo" link

https://paste.md-5.net/banoxuduvi

### Server Log

https://mcpaste.io/d8b388c4883581b0

**Comment by Burchard36** [comment]
Hello there can you please send me the enchantment you are using? I tried using our default `trench` enchantment but it does not have this effect, when breaking shulkers, they drop on my end

https://user-images.githubusercontent.com/48583030/169717819-1dcca923-5c8b-4741-b51e-51d710e123d3.mp4

**Comment by dsevvv** [comment]
### This enchant is a part of the "Cosmic Enchants" set

detonate:
  display: '%group-color%Detonate'
  description: "Chance to break in 3x3 area."
  applies-to: 'Pickaxes and shovels'
  type: 'MINING'
  group: 'ULTIMATE'
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 13
      effects:
        - 'TRENCH:3'
    2:
      chance: 26
      effects:
        - 'TRENCH:3'
    3:
      chance: 36
      effects:
        - 'TRENCH:3'
    4:
      chance: 49
      effects:
        - 'TRENCH:3'
    5:
      chance: 59
      effects:
        - 'TRENCH:3'
    6:
      chance: 72
      effects:
        - 'TRENCH:3'
    7:
      chance: 85
      effects:
        - 'TRENCH:3'
    8:
      chance: 90
      effects:
        - 'TRENCH:3'
    9:
      chance: 100
      effects:
        - 'TRENCH:3'

**Comment by dsevvv** [comment]
Any follow up?

**Comment by dsevvv** [comment]
This issue persists with the new version 8.11.0. Shulkers getting deleted is a very severe issue.

**Comment by dsevvv** [comment]
Shulkers being deleted is a huge issue. Please look into this. I have shared all the requested information. It has been nearly 30 days.

**Comment by GC-spigot** [comment]
Sorry about delays, we’re looking into this asap

**Comment by dsevvv** [comment]
Cheers

**Comment by GC-spigot** [comment]
Remove shulker box from trench blacklist in config.yml
