### ISSUE TITLE
SlotIncreaser not working in version 8.10.7

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2858]
### Describe the bug

The slot increaser stopped working in version 8.10.7, i tried regenerating the config and tried the default one, but still doesn't work.

### How to reproduce

Just try using the slot increaser, it doesn't work

### "/ae plinfo" link

https://paste.md-5.net/nakeyeseja

**Comment by GroundedMC** [comment]
You must have at least one custom enchant on the item before you are able to apply a slot increaser.

**Comment by xlsalvolx** [comment]
> You must have at least one custom enchant on the item before you are able to apply a slot increaser.

I am aware. It didn't work. It worked fine prior to release 8.10.7

**Comment by GC-spigot** [comment]
Fixed
