### ISSUE TITLE
Soulbound doesn't get removed if the enchant is applied on armor

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2859]
### Describe the bug

If you add the "REMOVE_ENCHANT:soulbound" effect to soulbound, it will work fine on weapons (you die, the item doesn't get dropped, the enchants gets removed) but if you try to apply it on armors the enchant won't get removed (you die, the item stays in your inventory but the enchant will still be there after death)

### How to reproduce

1. Apply soulbound to an armor piece (make sure it has the REMOVE_ENCHANT effect)
2. Die
3. You will still find soulbound on the item

### "/ae plinfo" link

https://paste.md-5.net/nakeyeseja

**Comment by GC-spigot** [comment]
`"REMOVE_ENCHANT:soulbound"` effect should be first, after that KEEP_ON_DEATH effect should be listed
