### ISSUE TITLE
Magic Dust not working for some people (weird ik)

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#286]
My enchanter shop gives players magic dust of the SIMPLE category (default config)

In my config, I have set it so that dusts of any category can be used for books in any categoroy (groups.yml)

What is really weird is that some players can use my magic dust sold from the enchanter shop for any group, while some people can only use those magic dust for SIMPLE category books.

OP-ing the players does nothing. They still cannot apply the dusts to books other than SIMPLE.

If you could get this fixed soon, that would be much appreciated. Thanks <3

**Comment by GC-spigot** [comment]
Should be fixed.
