### ISSUE TITLE
AdvancedEnchantments

### ISSUE THREAD

**Issue by srrawr11** [GC-spigot/AdvancedEnchantments#2860]
### Describe the bug

Minecraft: Java
Version: Paper 1.8.8

Hi, I would like to report that when you have the enchantment TRENCH in any pickaxe and try to mine it spam the console with this error: https://pastebin.com/V1jHu47d .. I am trying with the STAINED_CLAY:0

### How to reproduce

...

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/73607495/170131064-fe1db14b-ff54-4729-9e4a-2219079ec3e8.png)
![image](https://user-images.githubusercontent.com/73607495/170131097-b8823984-12bb-44d1-8b0f-62fbb435ea9e.png)

### "/ae plinfo" link

https://paste.md-5.net/ofufiwifad

**Comment by GC-spigot** [comment]
Try updating

**Comment by srrawr11** [comment]
Still same.
