### ISSUE TITLE
PlaceholderAPI Bug with AE

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#2861]
### Describe the bug

I updated version 8.10.8 causing the PlaceholderAPI to not work, so I reverted to version 8.10.6 and it works.

https://pastebin.com/UNr462ez

### How to reproduce

I updated version 8.10.8 
PlaceholderAPI to not work
I reverted to version 8.10.6 and it works .

### "/ae plinfo" link

https://paste.md-5.net/efajigocis

**Comment by GC-spigot** [comment]
This is a placeholderapi error, seems to be related with reloading the server
