### ISSUE TITLE
Holy White Scroll Dupe

### ISSUE THREAD

**Issue by GroundedMC** [GC-spigot/AdvancedEnchantments#2862]
### Describe the bug

When players die with keep inventory on, they keep all of the items and Holy's are still applied _and_ they get a new pair of items without Holy protection. 

So my guess is that Holy White Scrolls cant detect how we set up item dropping in Deluxe Combat, and its giving new items, no matter how they die, but Deluxe Combat prevents the original items from dropping - so players keep both.

### How to reproduce

Have Holy White Scrolls applied to your items.
Die when Keep Inventory is On.

### "/ae plinfo" link

/aw plinfo skipPlugins

**Comment by GC-spigot** [comment]
Fixed
