### ISSUE TITLE
[Velocity] when player rejoined server, potion effect are disappeared

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2863]
### Describe the bug

youtube : https://www.youtube.com/watch?v=Oviu7JTiMv4

### How to reproduce

1. link 2 server through velocity.
2. sync inventory plugin (InventorySaver)
   -> i tried disable sync potion effect, but still same problems.

### "/ae plinfo" link

https://paste.md-5.net/ijawacusev

**Comment by GC-spigot** [comment]
Should be resolved
