### ISSUE TITLE
[PERFORMANCE] net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak() Very resource intensve

### ISSUE THREAD

**Issue by matipoirierg** [GC-spigot/AdvancedEnchantments#2864]
### Describe the bug

General bad performance of the plugin vecause of net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak()

### How to reproduce

Using enchantments that triggers net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak()

### Screenshots / Videos

![AE](https://user-images.githubusercontent.com/97362850/170760766-00ebf79d-ae2c-4899-86e3-8cf28c162abb.JPG)

### "/ae plinfo" link

https://paste.md-5.net/togapabuya

**Comment by matipoirierg** [comment]
timing with 60 players. https://timings.aikar.co/?id=9d166eadee3f4f8e991d9a2b234fdd39#timings

**Comment by GC-spigot** [comment]
Most/all of that is coming from McMMO
