### ISSUE TITLE
Slot Increaser cannot apply 1.8.8

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2865]
### Describe the bug

Cannot apply slot increaser

### How to reproduce

Apply slot increaser

### Screenshots / Videos

https://streamable.com/vq5n6g

### "/ae plinfo" link

https://paste.md-5.net/gahaxojise

### Server Log

https://mcpaste.io/1e519c75aa162d56

**Comment by GC-spigot** [comment]
Fixed
