### ISSUE TITLE
A BIG BIG PROBLEM

### ISSUE THREAD

**Issue by None030** [GC-spigot/AdvancedEnchantments#2867]
### Describe the bug

hey I have a problem
when I try to apply a enchant which requires another enchantment to be applied on the item first 
It destroyes the item even with protection
and I want it not to destroy the item neither take protection from the item coz the enchant requires another enchantment to be applied on it first
so it shouldnt try to apply it on the item

### How to reproduce

Just try using Titan Trap on a protected item with no ces on it (Cosmic Enchantment)

### "/ae plinfo" link

https://paste.md-5.net/yejudufusu

**Comment by GC-spigot** [comment]
It doesn't destroy the item, only this message is shown in chat: https://prnt.sc/HmCB90L1QlLJ
Please record a gif or a video and open another issue after
