### ISSUE TITLE
Broken enchant - dupe bug?

### ISSUE THREAD

**Issue by DrakMC** [GC-spigot/AdvancedEnchantments#2870]
### Describe the bug

Because of this bug I can get more out of ore than I should.

### How to reproduce

If I mine a vein (multiple ores in the same place) with a pickaxe that has these enchants: https://i.imgur.com/INauRqh.png I get more ore than I should have - for example 3 stacks.

The problem occurs in version: 8.10.9 In older versions this bug does not occur.

### "/ae plinfo" link

https://paste.md-5.net/bamirovoxu

**Comment by GC-spigot** [comment]
Fixed
