### ISSUE TITLE
More Drops don't work

### ISSUE THREAD

**Issue by MrABCDevelopment** [GC-spigot/AdvancedEnchantments#2875]
### Describe the bug

when i use enchant with MORE_DROPS:(number) nothing happens.

### How to reproduce

Step 1: write enchant with more_Drops
Step 2: enchant your pickaxe with this enchant
Step 3: break any block

### Screenshots / Videos

https://imgur.com/a/cx4N1E0

### "/ae plinfo" link

https://paste.md-5.net/ubecoheluf

**Comment by GC-spigot** [comment]
Plugin ignores player-placed blocks, that is why this doesn't work in your way of testing. Place diamond ore, restart and then it will work - since cache is reset after restarts.
