### ISSUE TITLE
Rebreather is giving more bubbles than the max bubbles in vanilla minecraft

### ISSUE THREAD

**Issue by J14P** [GC-spigot/AdvancedEnchantments#2877]
### Describe the bug

When the rebreather enchant is on a pickaxe and you mine a block, the enchant gives giving more bubbles than the max amount of bubbles in vanilla minecraft.

### How to reproduce

Put rebreather on a pickaxe and go mine stone underwater. You should see that you have a ton more bubbles than you should.

### Screenshots / Videos

https://prnt.sc/m3oCC3jrfCMz
https://youtu.be/LRdJZk2TWzc

### "/ae plinfo" link

https://paste.md-5.net/xahiwukiva

### Server Log

https://mcpaste.io/a1a4d2c5f79d2f77

**Comment by GC-spigot** [comment]
Fixed
