### ISSUE TITLE
RESTORE and ADD_DURABILITY_CURRENT_ITEM do not work with TRENCH

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2878]
### Describe the bug

When a TRENCH item with RESTORE and/or ADD_DURABILITY_CURRENT_ITEM is broken, neither effect works. I'm assuming this is because the trench_do_all_durab config setting is set to true, and multiple durability is being done to the item at once.

### How to reproduce

Enchant a tool with a TRENCH and a RESTORE and/or ADD_DURABILITY_CURRENT_ITEM enchantment(s).
Use the item until it breaks.
The item will not restore properly, and the "Failed to parse effect" messages will show up for the two enchantments.

### "/ae plinfo" link

https://paste.md-5.net/ekinufefid

### Server Log

https://mcpaste.io/d02b66da5bf4c72d

**Comment by hkkongou** [comment]
still appear in AdvancedEnchantments-9.0.0b67
