### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ImYenil** [GC-spigot/AdvancedEnchantments#2879]
### Describe the bug

Clicking on any item in creative state causes this error

### How to reproduce

Clicking on any item in creative state causes this error

### Screenshots / Videos

https://pastebin.com/XAYDuv4z

### "/ae plinfo" link

https://pastebin.com/XAYDuv4z

### Server Log

https://pastebin.com/XAYDuv4z

**Comment by GC-spigot** [comment]
Fixed
