### ISSUE TITLE
EXPLOSIVE PICKAXES AND EXPERIENCE

### ISSUE THREAD

**Issue by Olavvvv** [GC-spigot/AdvancedEnchantments#2880]
### Describe the bug

When stabbing with a pickaxe with enchantments like: explosive, perforation (custom_trench:3:3 or custom_trench: 5:1:1)
This does not receive experience, nor the peak, nor the player, even if it has repair. It would be good if it was fixed since when breaking more blocks, the pickaxe breaks very easily and it would also be good if it was fixed because it does not give experience and that is wrong

### How to reproduce

explosivo:
  display: '%group-color%Explosivo'
  description: 'Rompe en un area de 3x3x3'
  applies-to: 'Tools'
  group: 'FABLED'
  type: 'MINING'
  applies:
    - 'ALL_AXE'
    - 'ALL_PICKAXE'
    - 'ALL_SPADE'
  levels:
    '1':
      chance: 100
      cooldown: 0.3
      effects:
        - 'CUSTOM_TRENCH:3:3:3'

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/94938785/171933491-9f5951ff-c95a-4100-84c1-be849a64fdf0.png)

### "/ae plinfo" link

latest version advancedenchantments - server 1.16.5

**Comment by GC-spigot** [comment]
To change durability change `trench-do-all-durab` setting in config to false, looking into everything else
