### ISSUE TITLE
PASSIVE_DEATH effect triggers on cancelled/resisted damage

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2883]
### Describe the bug

If a player has a high resistance potion effect and takes enough damage that would kill them without the resistance, it seems that the PASSIVE_DEATH effect is triggered. In my case the player had resistance five and the fall did no real damage to them, but caused their KEEP_ON_DEATH item to disappear from their inventory.

### How to reproduce

Enchant an item with an enchantment that triggers on PASSIVE_DEATH
Give yourself a high level resistance effect.
Fall/take enough damage to kill you if you didn't have the resistance.
The PASSIVE_DEATH enchantment effects will trigger.

### "/ae plinfo" link

https://paste.md-5.net/ububacikuy

**Comment by xlsalvolx** [comment]
Looks related to this other bug: https://github.com/GC-spigot/AdvancedEnchantments/issues/2882
