### ISSUE TITLE
BlockTrak Duplicating on Items Prior to the 8.11.1 Update

### ISSUE THREAD

**Issue by GroundedMC** [GC-spigot/AdvancedEnchantments#2887]
### Describe the bug

When using an item that already had a BlockTrak on it, prior to the 8.11.1 update, when using that same item after the update, it is duplicating the BlockTrak on the item and starting the count over.

### How to reproduce

Please see the video below.  Just had to have an item with a BlockTrak on it, prior to the 8.11.1 update.  When using after the update is installed, the BlockTrak duplicates on that item.

### Screenshots / Videos

https://youtu.be/Er_pPMolrZQ

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ryankayz7** [comment]
Was about to report this too. Can confirm it happened to my server too. I think it basically reset the blocktrak count and added the lore again as if the first one had never been there? Would be good if there was a way to keep counting from the original blocktrak number or players will lose the stats they had with blocktrak, which would suck a little

**Comment by ClickErrorxD** [comment]
Happened to our server as well. Sucks
![2022-06-29_07 51 33](https://user-images.githubusercontent.com/87890013/176430315-9e6a8c7b-f70e-4798-9dae-1a4a4d7c11bb.png)

!

**Comment by GroundedMC** [comment]
We are no longer having an issue with this - seems all old blocktrak creators needed to be replaced after the update that was duplicating them..

**Comment by GC-spigot** [comment]
Will be looking into this asap for next update!
