### ISSUE TITLE
when player rejoined server, HEALTH_BOOST was refreshed.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2888]
### Describe the bug

Literally, when player rejoined with HEALTH_BOOST enchantment,
The extra heath is disappeared.

### How to reproduce

과부하: # 3레벨까지 있던걸 1레벨만 남겨둠
  display: "%group-color%과부하"
  description: "최대 체력이 증가합니다.\n&7(여러부위 중첩되지 않습니다)"
  applies-to: "방어구"
  type: "EFFECT_STATIC"
  group: "레전더리" #레전더리
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - "POTION:HEALTH_BOOST:0"
    2:
      effects:
        - "POTION:HEALTH_BOOST:2"  
    3:
      effects:
        - "POTION:HEALTH_BOOST:4"    

### Screenshots / Videos

youtube: https://www.youtube.com/watch?v=hC8kpVOTNBI

### "/ae plinfo" link

https://paste.md-5.net/lohiyokuca

**Comment by GC-spigot** [comment]
Should be working fine
