### ISSUE TITLE
[FEATURE] Add multiples things. Read this when you can

### ISSUE THREAD

**Issue by maxlehot1234** [GC-spigot/AdvancedEnchantments#289]
Hey GC, I have multiple suggestion for your plugin:

1- Give items that have enchants on it using a console command like this:
    /ae giveenchantitem <playername> <item> <enchant1:LVL> <enchant2:LVL> <enchant3:LVL>
   EX: ./ae giveenchantitem maxlehot1234 diamond_pickaxe autosmelt:1 confusion:1 aquatic:1

2- Give gkits to a player

3- Make gkitz not listed in the gui so they can be give using console commands.

1 can be easily replaced by 2 and 3 since we can put enchanted items in gkitz.

These things could be really useful

**Comment by GC-spigot** [comment]
2nd & 3rd are already in the plugin - /ae givekit & there's a "hide" setting for each gkit, if you set it to true it's hidden from the GUI.
1st feature will be implemented in future.

**Comment by maxlehot1234** [comment]
Any update for 1 ? This could be a really muich better than giving a gkit during events and set a cooldown to 999999999
