### ISSUE TITLE
NametagItem placeholder parse error.

### ISSUE THREAD

**Issue by YKDZ** [GC-spigot/AdvancedEnchantments#2890]
### Describe the bug

![Snipaste_2022-06-11_14-02-34](https://user-images.githubusercontent.com/69898831/173184411-40bbbd81-0e51-4ca1-8b2d-bed6aa619ac4.png)
The success messge of the nametag is just like this. 

### How to reproduce

Use the name tag
Find the error

### Screenshots / Videos

![Snipaste_2022-06-11_14-02-34](https://user-images.githubusercontent.com/69898831/173184495-4c385757-06b7-4091-a46d-41e875584239.png)
Could not create debug link! Error: Connect timed out
The plinfo is time out. So my AdvancedEnchantments version is AdvancedEnchantments-8.11.4.

### "/ae plinfo" link

Connect timed out

**Comment by Awpmeister2170** [comment]
Fixed
