### ISSUE TITLE
Carved Pumpkin doesn't register as armor

### ISSUE THREAD

**Issue by Indigo102** [GC-spigot/AdvancedEnchantments#2893]
### Describe the bug

Essentially, AE doesnt check carved pumpkins as armor, so when it is placed on your head it doesn't function to give you buffs as if its armor, but when it is in your hand the effects work just fine

### How to reproduce

Bind pretty much any carved pumpkin with an enchant, and it will work while in your hand but not on your head

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by GC-spigot** [comment]
Fixed
