### ISSUE TITLE
player helmet was disappeared when place Carved pumkin

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2894]
### Describe the bug

https://user-images.githubusercontent.com/25452835/173252835-0fd8db7f-6a74-4dea-8da7-adf2ee4d2ff1.mp4

### How to reproduce

1. wear helmet
2. place carved pumkin

### "/ae plinfo" link

https://paste.md-5.net/paciminazo

**Comment by GC-spigot** [comment]
Fixed
