### ISSUE TITLE
Function "TRENCH" works incorrectly

### ISSUE THREAD

**Issue by Snele** [GC-spigot/AdvancedEnchantments#2896]
### Describe the bug

Enchantment detonation that uses the trench function does not work correctly. If you break an block (for example shulker) from the trench blacklist, then it does not fall out!

### How to reproduce

Break blocks from the trench blacklist by detonate enchantment.

### "/ae plinfo" link

https://paste.md-5.net/zigaqemiqo

**Comment by GC-spigot** [comment]
Read latest update
