### ISSUE TITLE
Error when shutting down the server

### ISSUE THREAD

**Issue by Treasure233** [GC-spigot/AdvancedEnchantments#2898]
### Describe the bug

When I shut down my server, there are some plugin errors that I'm having a hard time understanding.I can only present them in the form of a report!

### How to reproduce

Plugin crash when shutting down the server

### "/ae plinfo" link

https://paste.md-5.net/ganigizexu

### Server Log

https://mcpaste.io/4f8bdd9375aa1195

**Comment by GC-spigot** [comment]
Fixed
