### ISSUE TITLE
Enchant books not working. "Could not pass event InventoryClickEvent"

### ISSUE THREAD

**Issue by InfernoPandaGaming** [GC-spigot/AdvancedEnchantments#2899]
### Describe the bug

Whenever a player, whether they have permissions or is in any gamemode, they cannot drag and drop AE enchantment books over tools/weapons to combine them. Whenever the player does try to do this, a very lengthy error pops up in console. There was an issue that had the same problem as me but even after trying the solutions there, it was not solved. 

Other issue: https://github.com/GC-spigot/AdvancedEnchantments/issues/52
Error in console: https://pastebin.com/eV0jD1KJ

### How to reproduce

Its quite simple, although I'm not sure if you will be able to reproduce...

Attempt to combine any AE book with valid gear.

### Screenshots / Videos

Error in console (again): https://pastebin.com/eV0jD1KJ

Video of bug: https://user-images.githubusercontent.com/64215261/173631997-43a985e9-ae34-4d70-bd98-d51d84de5ca8.mp4

### "/ae plinfo" link

https://paste.md-5.net/zocohirevi

### Server Log

https://mcpaste.io/6f80deeca261a110

**Comment by Awpmeister2170** [comment]
Try placing the Book on the item instead of the Item on the Book 

( Grab the book first and click the Chestplate with the book )

**Comment by GC-spigot** [comment]
Fixed
