### ISSUE TITLE
Telepathy does not work on skulls

### ISSUE THREAD

**Issue by xDacon** [GC-spigot/AdvancedEnchantments#290]
Mining a head or skull with telepathy enhantment turns it into a default skeleton skull

feature request: blacklisted items that aren't affected by enchantments like telepathy, blast etc.

**Comment by GC-spigot** [comment]
Seems like this cannot be fixed, as it works with simple player heads but not for ones with custom skins.

**Comment by xDacon** [comment]
Blacklisted item list would fix it though, and future potential issues
