### ISSUE TITLE
Enchant not working on CARVED_PUMPKIN

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#2902]
### Describe the bug

CARVED_PUMPKIN enchant not working
There may be a problem with all CARVED_PUMPKIN helmets.

### How to reproduce

config enchant
https://i.imgur.com/qW9ozXe.png

### Screenshots / Videos

https://i.imgur.com/nFXo87C.png
video
https://youtu.be/EWIWeTXBztc

### "/ae plinfo" link

https://paste.md-5.net/yeravojufo

### Server Log

-

**Comment by GC-spigot** [comment]
Fixed
