### ISSUE TITLE
bug with infinite obsidian

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#2903]
### Describe the bug

Endless obsidian, which requires boots on a water walker 1, and a trench, you walk on water under your feet obsidian appears if you break the trench, it falls and this is endless obsidian

### How to reproduce

Endless obsidian, which requires boots on a water walker 1, and a trench, you walk on water under your feet obsidian appears if you break the trench, it falls and this is endless obsidian

### Screenshots / Videos

-

### "/ae plinfo" link

https://paste.md-5.net/iwuriledol

### Server Log

-

**Comment by GC-spigot** [comment]
Fixed
