### ISSUE TITLE
Trech does not give Xp to users when mining ores

### ISSUE THREAD

**Issue by TrevorTGKCR** [GC-spigot/AdvancedEnchantments#2904]
### Describe the bug

When you bite with the trech on the peak it does not give the xp and effects such as fortune and others are not applied

### How to reproduce

/ae enchant trench 9
/enchantment efficiency 5 
/enchantment fortune 3
with these commands it does not give the user the xp for minced ore

### Screenshots / Videos

![ScreenShot_20220616203239](https://user-images.githubusercontent.com/107661678/174213376-f0e33665-83d5-450d-8831-ba6e08b93c87.png)
Mining with trech 9
![ScreenShot_20220616203249](https://user-images.githubusercontent.com/107661678/174213379-0b5ed523-20c8-41ed-a940-7a52afbdaa23.png)
20lvls and no xp goes up
![ScreenShot_20220616203301](https://user-images.githubusercontent.com/107661678/174213381-3fe5184f-3d82-412c-9bce-73c4ebaa16bd.png)
If we remove the trech 9 it already gives us the xp that would give us an ore
![ScreenShot_20220616203311](https://user-images.githubusercontent.com/107661678/174213382-c13a4a7e-444a-4f4f-82c7-b73055e23a50.png)

### "/ae plinfo" link

https://paste.md-5.net/ihijubapoh

### Server Log

https://mcpaste.io/10302a34ac09e07a

**Comment by TrevorTGKCR** [comment]
I hope you have a solution I am in love with this plg since I bought it

**Comment by GC-spigot** [comment]
Fixed
