### ISSUE TITLE
Timber doesnt break whole trees

### ISSUE THREAD

**Issue by flaszuu** [GC-spigot/AdvancedEnchantments#2907]
### Describe the bug

Hello, it seems that Timber enchantment doesnt manage to cut down entire tree, and lives a floating 1x1 tower always when trying to cut large spruce.

### How to reproduce

Cut down large spruce with timber enchantment.

### "/ae plinfo" link

https://paste.md-5.net/ucacofaqad

**Comment by Awpmeister2170** [comment]
Hello, i dont seem to have this issue and i cant seem to recreate it, have you attempted this on Multiple Trees as it isnt 100% that it will cut the whole tree it gives you a chance to.

**Comment by flaszuu** [comment]
Hello, its sometimes hard to reproduce with spruce, but i get consistent results with jungle trees. I attach 2 screens showing how it looks after trees were cut 
![javaw_fdLWQjl4fY](https://user-images.githubusercontent.com/45732082/174912125-41245ae4-79a3-4770-b20f-99a992d15d93.png)
![javaw_X7GCpBZ9t4](https://user-images.githubusercontent.com/45732082/174912130-eca30ad3-af7a-4df2-9fb5-2c9cbf96c125.png)
Cheers
