### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Hyronymos1337** [GC-spigot/AdvancedEnchantments#2908]
### Describe the bug

Inventory Error

### How to reproduce

Open a AE Inventory

### "/ae plinfo" link

https://paste.md-5.net/sezuhuvuwu

### Server Log

https://paste.twerion.net/udofalafon.md

**Comment by GC-spigot** [comment]
Seems like config is broken, item types are missing e.g. blocktrak

**Comment by Hyronymos1337** [comment]
> Seems like config is broken, item types are missing e.g. blocktrak

i just used pre-made configuration, with no changes

**Comment by GC-spigot** [comment]
Which premade?
