### ISSUE TITLE
Telepathy - Reinforced Deepslate

### ISSUE THREAD

**Issue by SpookGezichtje** [GC-spigot/AdvancedEnchantments#2909]
### Describe the bug

Player can mine Reinforced Deepslate with their telepathy pickaxe and obtain the block.

### How to reproduce

Mine Reinforced Deepslate with telepathy.

### "/ae plinfo" link

https://paste.md-5.net/qupiyolitu

**Comment by Awpmeister2170** [comment]
I have Telepathy 4 on my Pickaxe and i am unable to obtain Reinforced Deepslate it just breaks, Can you possibly include your Server logs / a video of the Issue.

**Comment by SpookGezichtje** [comment]
> I have Telepathy 4 on my Pickaxe and I am unable to obtain Reinforced Deepslate it just breaks, Can you possibly include your Server logs / a video of the Issue.

Can you try to add Silk Touch to it? I've noticed that it won't go in your inventory. But with silk touch on the pickaxe, it does for me. Pickaxe contains: 
- Silk touch 1
- Telepathy 4
- Vein Miner 3

**Comment by Awpmeister2170** [comment]
Ok yes, with Silktouch and Telepathy this does happen we will look into this.
