### ISSUE TITLE
Bug enchant scare

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#2910]
### Describe the bug

When the enchant scare is activated, the **Carved Pumpkin** in the inventory are removed.

### How to reproduce

Use enchant **Scare** attack

### Screenshots / Videos

https://i.imgur.com/tO5XYlm.gif

### "/ae plinfo" link

https://paste.md-5.net/cujijuloro

**Comment by GC-spigot** [comment]
Fixed
