### ISSUE TITLE
Armorsets Variables

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2911]
### Describe the bug

Armor sets variables dont work: %victim% %attacker% or AOE, the effects only works for the wearer of the armor, like you cannot add something like : ADD_HARM %attacker% , it would return to the victim itself or if not, it won't even work.

Please make variables work like in enchantments.yml

**This has been around for ages already, when is this going to be fixed / reworked? Armor sets are a big thing and I hope this will get fixed, it's the only thing missing in this MASTERPIECE plugin, I've been using AE for almost a year, and it helped my server become better and more fun to play, I really hope you guys fix this! thank you! There's a plugin called EliteArmor, that has variables working on armorsets but it needs EliteEnchantments plugin for some armor sets to work, but I don't want that, I want to stick with AE because this plugin is actually better and has more features and EASIER to use, please be able to fix this soon.**

### How to reproduce

Create an armor set

try adding an event like:

DEFENSE:
ADD_HARM %attacker% , attack the wearer of the armor set, nothing will happen.

### Screenshots / Videos

none

### "/ae plinfo" link

https://paste.md-5.net/befehixiyi

### Server Log

https://mcpaste.io/ce681e4a0e480c1b

**Comment by illudota** [comment]
Same with customWeapons btw

**Comment by KazMNF** [comment]
Did u tested INCREASE_DAMAGE event ?

**Comment by illudota** [comment]
> Did u tested INCREASE_DAMAGE event ?

it will work, it just wont work with variables. like example: DEFENSE: ADD_HARM:50 %attacker% , this won't work, it will return to victim instead.

**Comment by illudota** [comment]
any update?

**Comment by GC-spigot** [comment]
Fixed
