### ISSUE TITLE
Enchantment Telepathy

### ISSUE THREAD

**Issue by SpookGezichtje** [GC-spigot/AdvancedEnchantments#2912]
### Describe the bug

Upon destroying a jukebox with telepathy the jukebox disc disappears.

This happens on a 1.19 server, but it also did it on 1.18.2. The server has no other plugins. No errors either in logs.

P.S loud music in the video, of the music disc.

### How to reproduce

Destroy a jukebox with a disc with telepathy and the disc disappears.

### Screenshots / Videos

https://youtu.be/dX67DX-ozZM

### "/ae plinfo" link

https://paste.md-5.net/emitusunux

**Edit**

The jukebox goes into your inventory, but without the content, you can't see that on the video.

**Comment by GC-spigot** [comment]
Fixed
