### ISSUE TITLE
TP_DROPS doesn't increase statistics

### ISSUE THREAD

**Issue by ryankayz7** [GC-spigot/AdvancedEnchantments#2913]
### Describe the bug

When you mine a block using an enchant with TP_BLOCKS it does not not increase the amount of blocks mined. For example I'm using the statistic placeholder which is %statistic_mine_block% and it won't increase. 

This issue has been a past one and reported in #2106 but it was fixed.

### How to reproduce

Mine a block with telepathy and then go to your statistics and it will not increase your blocks mined.

### "/ae plinfo" link

https://paste.md-5.net/cusegapexe

**Comment by GC-spigot** [comment]
Unfortunately cannot fix it right now with the way it's made :( We will try to figure it out in the future!
