### ISSUE TITLE
TRENCH IN SHOLVELS

### ISSUE THREAD

**Issue by Olavvvv** [GC-spigot/AdvancedEnchantments#2914]
### Describe the bug

the 3x3 explosion in shovels just doesn't work

### How to reproduce

explosivo2:
  display: '%group-color%explosivo2'
  description: 'explosivo2'
  applies-to: 'Tools'
  group: 'SIMPLE'
  type: 'MINING'
  applies:
    - 'ALL_SPADE'
  levels:
    '1':
      chance: 100
      cooldown: 1
      effects:
        - 'CUSTOM_TRENCH:3:3:3'

### Screenshots / Videos

i dont have, but i have the enchantment

### "/ae plinfo" link

latest spigot

**Comment by Awpmeister2170** [comment]
Hello Olav can you change CUSTOM_TRENCH to TRENCH and see if that resolves your issue
