### ISSUE TITLE
EXPLOSIVE AND SHULKERS

### ISSUE THREAD

**Issue by Olavvvv** [GC-spigot/AdvancedEnchantments#2916]
### Describe the bug

when chopping a shulker with something explosive, it does not receive it

### How to reproduce

explosivo:
  display: '%group-color%Explosivo'
  description: 'Rompe en un area de 3x3x3'
  applies-to: 'Tools'
  group: 'FABLED'
  type: 'MINING'
  applies:
    - 'ALL_AXE'
    - 'ALL_PICKAXE'
    - 'ALL_SPADE'
  levels:
    '1':
      chance: 100
      effects:
        - 'CUSTOM_TRENCH:3:3:3'

### "/ae plinfo" link

latest version

**Comment by AlfieOnGit** [comment]
Pretty sure we're experiencing the same thing. If shulker boxes are blacklisted from trench and you try to directly mine a shulker box with trench it destroys the item. Relevant ymls:

in config.yml:
`  trench-blacklist:
  - ANVIL
  - BARREL
  - BEACON
  - BEE_NEST
  - BEEHIVE
  - BLACK_SHULKER_BOX
  - BLAST_FURNACE
  - BLUE_SHULKER_BOX
  - BREWING_STAND
  - BROWN_SHULKER_BOX
  - CAMPFIRE
  - CARTOGRAPHY_TABLE
  - CHEST
  - HOPPER
  - CHIPPED_ANVIL
  - COMPOSTER
  - CYAN_SHULKER_BOX
  - DAMAGED_ANVIL
  - DISPENSER
  - DROPPER
  - ENCHANTING_TABLE
  - ENDER_CHEST
  - FLETCHING_TABLE
  - FURNACE
  - GRAY_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - GRINDSTONE
  - JUKEBOX
  - LECTERN
  - LIGHT_BLUE_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - LIME_SHULKER_BOX
  - LOOM
  - MAGENTA_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - PINK_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - RED_SHULKER_BOX
  - SHULKER_BOX
  - SMITHING_TABLE
  - SMOKER
  - SOUL_CAMPFIRE
  - STONECUTTER
  - TRAPPED_CHEST
  - WHITE_SHULKER_BOX
  - YELLOW_SHULKER_BOX`

in enchantments.yml:
`trench:
  display: "%group-color%Trench"
  description: "Chance to break in 3x3 area. Blocks will go into player's inventory."
  applies-to: "Pickaxes, Shovels"
  type: "MINING"
  group: "LEGENDARY"
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 100
      effects:
        - "TRENCH:3"`
