### ISSUE TITLE
Ces working on armor stand

### ISSUE THREAD

**Issue by None030** [GC-spigot/AdvancedEnchantments#2917]
### Describe the bug

I had a armor with ces and I used it on a armor stand and when I hit the armor stand It and it spawned iron golems as Guardian ce spawns iron golems

### How to reproduce

^^^

### Screenshots / Videos

https://streamable.com/qfgtou

### "/ae plinfo" link

https://paste.md-5.net/ofifekipun

**Comment by Awpmeister2170** [comment]
Fixed in latest update
