### ISSUE TITLE
Blocks that have been "water walked" or "lava walked" and then replaced come back on server restart

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#2918]
### Describe the bug

If I walk over any block of water with water walker or lava with lava walker, then place a block where the obsidian was and then restart the server, it will reset all the blocks I have manually placed to water again.

This has haunted my server for months now and I was never able to figure out why it happened, until now. Took me quite a while to find out the exact reason, also it happens even if you restart the server hours or even days later which makes it even more annoying.

### How to reproduce

Find water, apply water walker to your boots, put them on, walk over the surface, replace the blocks that were obsidian at some point, then restart the server and you'll see that all your manually placed blocks will be replaced with water.

### "/ae plinfo" link

https://paste.md-5.net/xovitabuvi

### Server Log

https://mcpaste.io/7f68986d722f0123

**Comment by GC-spigot** [comment]
Fixed
