### ISSUE TITLE
Mobs come Invincible with WS(maybe)

### ISSUE THREAD

**Issue by ClickyMCSMP** [GC-spigot/AdvancedEnchantments#2920]
### Describe the bug

Mobs killed with a sword with AE's seem to have a small chance to cause mobs to go invincible. (Possible Confliction with https://bg-software.com/wildstacker/)
I have removed countless enchants that "deal additional damage to X mob type", but it's still an issue. A rare-ish issue, but still one nonetheless
I have also tried using wildstacker on a server with no other plugins, and it seems to not be an issue

### How to reproduce

Use AE enchants while killing mobs stacked by WildStacker.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/issues/2813

https://gyazo.com/8d30da9bda7c66a4d1a9730617831e14

### "/ae plinfo" link

https://paste.md-5.net/hoqoloceja

### Server Log

https://mcpaste.io/b4306a7e65a11cc0

**Comment by xlsalvolx** [comment]
Having the same issue, expecially with mythicmobs

**Comment by ClickyMCSMP** [comment]
> 
 Thank you! I'm hoping this gets solved. We've removed so many AE default enchantments to try and find a work around, but no luck.

**Comment by DuneSciFye** [comment]
Can confirm with my server as well.
- DuneSciFye (Admin on the AdvancedPlugins Discord)

**Comment by ClickErrorxD** [comment]
Hoping to see this fixed soon. We've been experiencing it for a month+ now.
