### ISSUE TITLE
TP Drop destroy tile entity near by without drop

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2921]
### Describe the bug

When break the grass using TP_Drop, the lever will be gone

screenshot below
![image](https://user-images.githubusercontent.com/61608872/175555590-d6e24df2-05c7-4811-b787-1231c8964deb.png)

### How to reproduce

use a TP_drop enchant, break the grass

### Screenshots / Videos

https://www.youtube.com/watch?v=B59jfgOcS9E

### "/ae plinfo" link

https://paste.md-5.net/kateveyuzu

### Server Log

https://paste.denizenscript.com/View/97984

**Comment by ClickErrorxD** [comment]
+bump - Had a player report this as well on my server. Tested and confirmed it myself. https://youtu.be/glBzd-umXwM PaperSpigot 1.18.2

**Comment by GC-spigot** [comment]
This has been resolved since
