### ISSUE TITLE
ENCHANT CUSTOMS / PICKAXES MENDING

### ISSUE THREAD

**Issue by Olavvvv** [GC-spigot/AdvancedEnchantments#2922]
### Describe the bug

When a pickaxe has plugin enchantments, it is not repaired. Previously you didn't get experience, but they fixed it. Now receives experience, but the pickaxe does not receive even if it has MENDING

### How to reproduce

add enchantments like explosive, telephaty or any other that has to do with the plugin

### "/ae plinfo" link

latest

**Comment by GC-spigot** [comment]
Fixed
