### ISSUE TITLE
Duping with armor and souls

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#2925]
### Describe the bug

duping bug, i have lava walker on my boots and taking boots from inv slot just keep duping them 
1.19 latest version of AE... no error in console
using souls for enchant so every duped item has 1 less soul so maybe instead of reducing souls in lore its making new item??
https://gyazo.com/929b05f27f32d35b1d39ec0a49b31bcc

### How to reproduce

Just put add soul requirement on lava walker and walk on lava it will not update the lore and cause the duping when you try to take out boots from inv

### Screenshots / Videos

https://gyazo.com/929b05f27f32d35b1d39ec0a49b31bcc

### "/ae plinfo" link

https://paste.md-5.net/keliqiqixa

**Comment by Awpmeister2170** [comment]
Hello, Please update your Plugin to the Latest release and see if your issue is resolved
