### ISSUE TITLE
keep_on_death will remove items from your inventory if you are not fully dead

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2927]
### Describe the bug

If the keep_on_death effect thinks you are dead it will remove every item with soulbound from your inventory and they will come back only after you die for real. This can be tested using a totem of undying or by having yellow hearts while at 0 red health.

### How to reproduce

1. Get a totem of undying, put it in your offhand
2. Apply the soulbound enchant to any item
3. Use this command: /effect give yournicknamehere minecraft:instant_damage 10 5
4. You will not die but the keep_on_death effect will think you did, removing the items from your inventory
5. Die to get the items back

### Screenshots / Videos

https://www.youtube.com/watch?v=rDnTP7SDy4w&feature=youtu.be

### "/ae plinfo" link

https://paste.md-5.net/jugimorewo

**Comment by Awpmeister2170** [comment]
Fixed
