### ISSUE TITLE
Telepathy deletes items INDEFINITELY

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#2928]
### Describe the bug

When certain blocks are placed on a block that you mine with the Telepathy enchantment, the said item on that block is erased from existence.

### How to reproduce

Place a block on a block.
Delete the block located under block... lol? [The video makes since! BELOW]

We've tested blocks that were reported specifically by a player of our server. Which is as follows:
Redstone, Bell, Item Frame... However, the video shows that the item frame was good.

### Screenshots / Videos

https://youtu.be/glBzd-umXwM

### "/ae plinfo" link

https://paste.md-5.net/jozedezaca

### Server Log

https://mcpaste.io/ddd64ef7f1a8954e

**Comment by Sikatsu** [comment]
Can confirm.

**Comment by ClickErrorxD** [comment]
Can confirm. The video literally proves it.

**Comment by GC-spigot** [comment]
Fixed in next update

**Comment by ClickErrorxD** [comment]
> Fixed in next update

In [8.12.8 Changelog](https://www.spigotmc.org/resources/1-8-1-19-%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90create-custom-enchantments-%E2%9C%85-50-sale.43058/update?update=465566)? I'm not seeing anything in the change-log about it.
