### ISSUE TITLE
Duplication Bug: Player-placed blocks can get mcMMO double drops when mined with Telepathy after a server restart

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2931]
### Describe the bug

After a server restart, ores that players have placed can get mcMMO double drops when mined with Telepathy. Without Telepathy, they would not get Double Drops.

### How to reproduce

Prerequisites:
`/mmoedit <username> Mining 1000`
Hold a pickaxe and do `/ae enchant Telepathy 4`

Steps:
1.) Place an ore
2.) Restart your server
3.) Mine the ore with the Telepathy pickaxe

You will get 2 ores when you should of got 1

### "/ae plinfo" link

https://paste.md-5.net/ozoxizofed

**Comment by GC-spigot** [comment]
There’s nothing we can do, after server restart. Im fairly certain mcmmo gives double drops after a restart as well.

**Comment by WhatsTheBadNews** [comment]
> There’s nothing we can do, after server restart. Im fairly certain mcmmo gives double drops after a restart as well.
> […](#)
> On 2022-06-30, at 09:32 AM, WhatsTheBadNews ***@***.***> wrote: ﻿ Describe the bug After a server restart, ores that players have placed can get mcMMO double drops when mined with Telepathy. Without Telepathy, they would not get Double Drops. How to reproduce Prerequisites: /mmoedit <username> Mining 1000 Hold a pickaxe and do /ae enchant Telepathy 4 Steps: 1.) Place an ore 2.) Restart your server 3.) Mine the ore with the Telepathy pickaxe You will get 2 ores when you should of got 1 Screenshots / Videos No response "/ae plinfo" link https://paste.md-5.net/ozoxizofed Server Log No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

I tested it with a normal pickaxe as well. It did not give Double Drops for placed blocks. Only the pickaxe with Telepathy did.

If there is nothing you can change to prevent this dupe, can we have an option to disable mcMMO's Double Drops working with TP_DROPS?

**Comment by WhatsTheBadNews** [comment]
Also are you sure there is nothing you can do? Could you not use mcMMO's API to access their blockstore?

**Comment by WhatsTheBadNews** [comment]
mcMMO.p.getBlockStore()
