### ISSUE TITLE
Armor DUPE with Holy White Scroll

### ISSUE THREAD

**Issue by GroundedMC** [GC-spigot/AdvancedEnchantments#2936]
### Describe the bug

We previously reported this issue and were told it was fixed, however, the dupe bug is still happening.
https://github.com/GC-spigot/AdvancedEnchantments/issues/2862

When players die with keep inventory on, they keep all of the items and Holy's are still applied and they get a new pair of items without Holy protection.

So my guess is that Holy White Scrolls cant detect how we set up item dropping in Deluxe Combat, and its giving new items, no matter how they die, but Deluxe Combat prevents the original items from dropping - so players keep both.

### How to reproduce

Have Holy White Scrolls applied to your items.
Die when Keep Inventory is On.

### "/ae plinfo" link

/aw plinfo skipPlugins

**Comment by ClickErrorxD** [comment]
So is this issue only happening with AE + DeluxeCombat? Or doesn't it exist without any combat plugin too?

We use combatlogx and have considered adding the ability to obtain Holy White Scrolls here soon.

**Comment by GroundedMC** [comment]
> So is this issue only happening with AE + DeluxeCombat? Or does it exist without any combat plugin too?
> 
> We use combatlogx and have considered adding the ability to obtain Holy White Scrolls here soon.

My server Admin tested this with combatlogx and it doesn't seem to be a problem with them because they don't have the rule for keep inventory when you die when your pvp is off, which is what we feel the underlying issue seems to be.

**Comment by GroundedMC** [comment]
We have created a new issue report after additional testing, to provide additional details.  
https://github.com/GC-spigot/AdvancedEnchantments/issues/2938
