### ISSUE TITLE
ADD_DURABILITY_CURRENT_ITEM:(amount) IS NOT WORKING

### ISSUE THREAD

**Issue by endknife** [GC-spigot/AdvancedEnchantments#2937]
### Describe the bug

It will not give me unbraking to the armor when worn
I had a lot of problems to recreate the unbreaking enchant for armors with this custom plugin

There is a second thing that not works, and it makes me upset.
It is not possible to change the xp cost (default 2000) to upgrade the enchants in the alchemist....

And i have a request, to add the possibility to use hex colors in the gkits.yml config file, like in the names and lores of the peaces of the armor

### How to reproduce

1) Enchant that is not working :(

aearmorunbreaking:
  display: '%group-color%&cArmor unbreaking'
  description: 'Gli item dureranno di più'
  applies-to: 'Armor'
  group: 'ELITE'
  type: 'DEFENSE'
  applies:
    - 'ALL_ARMOR'
  levels:
    '1':
      chance: 100
      effects:
        - 'ADD_DURABILITY_CURRENT_ITEM:-1'

2) No xp cost change
![image](https://user-images.githubusercontent.com/64046612/177409868-0d095e08-fe3a-445b-a02e-1dc1c13b1f04.png)
![image](https://user-images.githubusercontent.com/64046612/177409938-1be114ab-2e32-419b-b245-b0f67db7db6b.png)

3) Pls add it :)

### "/ae plinfo" link

https://paste.md-5.net/ezebalades

**Comment by reussy** [comment]
Hello, for the second "problem" you must set the "**let-plugin-count**" option to false.
