### ISSUE TITLE
Armor, Weapon and Tools DUPE with a combination of Holy White Scroll and Deluxe Combat keepInventory option

### ISSUE THREAD

**Issue by GroundedJDU** [GC-spigot/AdvancedEnchantments#2938]
### Describe the bug

Fixed

_Originally posted by @GC-spigot in https://github.com/GC-spigot/AdvancedEnchantments/issues/2862#issuecomment-1144098927_

Hello,

We updated the plugin to the version that this should be fixed in, but it was still not fixed.

The problem we are having is when the Holy White Scrolls are applied to armor pieces and they are equipped they keep the Holy White Scrolls but they are still placed in your inventory even tho you would still have them equipped. Same happens with any Weapon or Tool with a Holy White Scroll applied, but it has to be in the offhand slot.

### How to reproduce

Have Holy White Scrolls applied to your items.
Have them equipped either as armor pieces or tools put in offhand, and just die with pvp being toggled off in any way thats not pvp related.
The items will still have Holy White Scrolls on them but you will get a extra pairs in your inventory.
If the items weren't equipped then the Holy White Scrolls would be gone even tho the deluxe combat keepInventory rule is on when pvp is toggled off and the Holy White Scroll effect shouldn't be activated.

### Screenshots / Videos

https://www.youtube.com/watch?v=nLkR3o0gyN0&ab_channel=JDU

### "/ae plinfo" link

https://paste.md-5.net/idigowawig

**Comment by kathfishing** [comment]
@GC-spigot are there any updates on this?
