### ISSUE TITLE
Enchant Water Walking works even after unequipping the item

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2940]
### Describe the bug

You are able to use water walking, even after unequipping the item that had the enchantment.

### How to reproduce

Steps to replicate:
1- Wear the item which contains the enchant
2- Go to spawn
3- Remove the item (In spawn)
4- Return to previous location
5- You're able to water walk without the item equipped

### "/ae plinfo" link

https://paste.md-5.net/apuxusaput

**Comment by Awpmeister2170** [comment]
Can you please send us a Video of this? i cant seem to reproduce the error.

**Comment by Awpmeister2170** [comment]
I still can’t seem to reproduce the issue, update to the latest version and see if this issue still happens for you.
