### ISSUE TITLE
Telepathy enchant issue with torches/redstone/entities

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2941]
### Describe the bug

Mining a block with the telepathy enchant, stuff like torches/redstone/entities will be deleted instead of dropped.

### How to reproduce

Mine a block using Telepathy enchant with a... Redstone on it or something.

### "/ae plinfo" link

https://paste.md-5.net/apuxusaput

**Comment by ClickErrorxD** [comment]
Can confirm. Reported it too and they confirmed it.

**Comment by Awpmeister2170** [comment]
Fixed
