### ISSUE TITLE
Set bonus stays active after unequipping

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2942]
### Describe the bug

The bug is about the set bonus. When a player equips this, the set bonus kicks in. If the set is unequipped using shift + click, the effect will wear off, as it should. When, however, the armour pieces are manually unequipped by simply clicking the armour piece with your mouse, picking the armour piece up and placing it somewhere else in your inventory, the effects will stay indefinitely.

### How to reproduce

As for how to reproduce, please see the explanation above.

### "/ae plinfo" link

https://paste.md-5.net/ruyifawece

**Comment by Awpmeister2170** [comment]
Could you possibly send a video? i cant seem to reproduce this issue.

**Comment by Sikatsu** [comment]
Of course @Awpmeister2170 
https://user-images.githubusercontent.com/5664135/178793535-e355c87c-9ae7-45f8-8c38-ad571fabbdf8.mp4
