### ISSUE TITLE
Trident Dupe Glitch

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#2943]
### Describe the bug

Basically, if you modify the default AE enchant "Abiding"(max level 1) to be applied to Tridents, as it is and can be a weapon, which is what Abiding is used for, "**Weapons** with this enchant become unbreakable", it has the ability to dupe its self.

### How to reproduce

1. Get a Trident.
2. Modify the Abiding enchantment to allow Tridents.
3. Throw it up in the air and damage yourself. This part is important, if you're in a region/have god mode on, it will not duplicate.

`abiding:
  display: "%group-color%Abiding"
  description: "Weapons with this enchant become unbreakable"
  applies-to: "Weapons"
  type: "ATTACK;ATTACK_MOB;BOW;BOW_MOB"
  group: "LEGENDARY"
  applies:
    **- TRIDENT**
    - ALL_SWORD
    - BOW
  levels:
    1:
      effects:
        - "REPAIR"`

### Screenshots / Videos

https://youtu.be/hrs-LqKiI1s - Video Evidence
Original Player Report by one of our players who discovered it:
![image](https://user-images.githubusercontent.com/87890013/178072924-9c04ba94-f886-4ff0-a2bb-d5996f5eb46d.png)
Note, we only tested Abiding 1, which clearly was the cause, not Poseidon.

### "/ae plinfo" link

https://paste.md-5.net/pawayosuha

### Server Log

https://mcpaste.io/101b771da11d88d9

**Comment by Awpmeister2170** [comment]
Fixed when next update is released.
