### ISSUE TITLE
Plugin disables when loading

### ISSUE THREAD

**Issue by Azakaturan** [GC-spigot/AdvancedEnchantments#2945]
### Describe the bug

When starting the server, the plugin can't connect to the server, and then disables itself.

![image](https://user-images.githubusercontent.com/79327162/178089185-8b02cecb-ecee-4434-a1b6-a636b9643db8.png)

### How to reproduce

Idk, start the server with the plugin?

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/79327162/178089188-165f29c9-340e-4c21-93f8-3da9990bd614.png)

### "/ae plinfo" link

Can't since the plugin disables..

### Server Log

https://mcpaste.io/7ff243952331e201

**Comment by Awpmeister2170** [comment]
Fixed, servers went down they are back up and running again.
