### ISSUE TITLE
Detonate on Shulker Box

### ISSUE THREAD

**Issue by spasboy1** [GC-spigot/AdvancedEnchantments#2947]
### Describe the bug

Detonate Makes the Shulker Box Disapear and erased. Please fix this bug

### How to reproduce

Use detonate on a shulker box and it will disapear

### "/ae plinfo" link

https://paste.md-5.net/ineroqimog

### Server Log

https://mclo.gs/G8C981k

**Comment by Awpmeister2170** [comment]
i cant seem to reproduce this issue, could you send us a Video of it happening for you please

**Comment by spartan090907** [comment]
https://drive.google.com/file/d/1A2IIKiAAJsRj-rJgfZ2G2vm5OCu6Bp6X/view?usp=sharing

**Comment by spartan090907** [comment]
it may be linked to telekinesis as well, I'm not sure

**Comment by Awpmeister2170** [comment]
Still can not reproduce this issue it works fine for me
