### ISSUE TITLE
BOW, BOW_MOB not working with Mythic Crucible plugin active

### ISSUE THREAD

**Issue by icenii** [GC-spigot/AdvancedEnchantments#2949]
### Describe the bug

Without using Mythic Crucible, my bow related enchantments used to work properly. Now that I added Mythic Crucible, it seems the BOW and BOW_MOB enchant no longer applies the effects listed in the enchantment. 

Server Client: paper-1.19-58
Mythicmob version: Mythicmob Premium Snapshot 5.1.0
Mythiccrucible version: Mythiccrucible Premium Snapshot 1.5.0
Advance Enchantment version: AdvancedEnchantments-8.12.4

Other Notes:
- ARROW_HIT seems to still work properly
- There seems to be no errors messages for both mods in the server log that I noticed.

### How to reproduce

Use Mythicmob, Mythic Crucible, and Advance Enchantments mod together and try use a BOW/BOW_MOB enchantment with the mentioned plugins.

Test weapon used is a Bow and a Crossbow. Both failed to apply BOW and BOW_MOB effects.

### "/ae plinfo" link

https://paste.md-5.net/ebazecixir

**Comment by cr0wstorm** [comment]
I'm having the same issue. Running on paper-1.18.2.
