### ISSUE TITLE
Souls not adding up with player kills

### ISSUE THREAD

**Issue by divingross** [GC-spigot/AdvancedEnchantments#2951]
### Describe the bug

Souls collected: (ammount) are not collecting with player kills, only mob kills

I have spoken with DuneSciFye | Enchant Comissions
DuneSciFye#0326

in your discord who told me to report the issue 

The 7 collected in https://prnt.sc/y-B3CFnekKPC are from mob kills, not player kills

### How to reproduce

Souls are enabled in config.yml along with mob kills

Server is on purpur 1.19
there's nothing else really to add

### Screenshots / Videos

https://prnt.sc/7hw9aTcO6KaC

https://prnt.sc/y-B3CFnekKPC

### "/ae plinfo" link

https://paste.md-5.net/ovohotoric

### Server Log

https://mcpaste.io/30f33b7195b4f2f3

**Comment by Awpmeister2170** [comment]
Fixed for next update
