### ISSUE TITLE
Changes in configuration not taking place.

### ISSUE THREAD

**Issue by Expelled1** [GC-spigot/AdvancedEnchantments#2953]
### Describe the bug

I recently made some changes in the config.yml, lootConfiguration.yml and mobs.yml.
Some of them seem to work whenever I change the desired categories, but others seem to stay the same no matter if I restart or reload the server I'm hosting. We have also tried to shut down the server, make the changes and then start it again, but to no avail.

Some of the main issues we have discovered thus far are the following:
- Changing the EXP needed to buy a random book from each enchantment-group, doesn't change it ingame.
- Adding potential mob-drops like whitescrolls or random enchantment books in mobs.yml, doesn't work.
- Enchantments such as "Trench", "Vein Miner" and maybe "Telepathy" doesn't cooperate with mcmmo multiplication and fortune, despite having changed those in the configuration.
- Blacklisting certain blocks for the "Trench" enchantment, doesn't work.

We did some testing with trench and veinminer on certain ores, to see if issues no. 3, was viable.

32 ores of iron, copper and coal was used to see if there was an issue.
A normal diamond pickaxe with fortune 3, +- level 1000 in mcmmo mining level and one with the same standard enchantments but also with trench and veinminer, +- 1000 mcmmo mining level, was used.

(N = Normal pickaxe, AE = Trench + Veinminer pickaxe)

"N" on coal-ore gave an average of 1 stack and 34 pieces.
"AE" on coal-ore gave an average of 32 pieces.

"N" on copper-ore gave an average of 4 stacks and 37 pieces.
"AE" on copper-ore gave an average of 1 stack and 32 pieces.

"N" on iron-ore gave an average of 1 stack and 31 pieces.
"AE" on iron-ore gave an average of 32 pieces.

### How to reproduce

Really hard to describe how to reproduce, since the plugin was downloaded less than 24 hours ago.
The current plugins on the server is:
McMMO
Xessentials
Simple TPA
Advanced Enchantments.

The first three has been there since the beginning roughly 2 weeks ago.
The last has been there for less than 24 hours.

### Screenshots / Videos

![Elite and Ultimate](https://user-images.githubusercontent.com/109297556/179019300-2694c9e0-4c4d-4f98-883f-2dc87b900e54.PNG)
![Simple and Unique](https://user-images.githubusercontent.com/109297556/179019306-9d3cce64-3ec0-4019-a492-61c46c704408.PNG)
![Fabled Enchantments](https://user-images.githubusercontent.com/109297556/179019307-bb6500d5-1979-4511-9454-74df1b3c6a1a.PNG)
![Legendary Enchantments](https://user-images.githubusercontent.com/109297556/179019311-224a1ff6-5f30-4832-b8c0-61fe64c0fd0e.PNG)
![Issue no  2 mobs,yml](https://user-images.githubusercontent.com/109297556/179019317-7fe98ecb-fbe2-4924-b76a-e7175b829904.PNG)
![Legendary and Fabled](https://user-images.githubusercontent.com/109297556/179019320-a4683739-bae5-45f5-be8d-f6989f965dc0.PNG)

### "/ae plinfo" link

https://paste.md-5.net/etunawicuv

### Server Log

https://mcpaste.io/b493793332d849a3

**Comment by GC-spigot** [comment]
Will be fixed, try restarting if this issue happens again
