### ISSUE TITLE
Telepathy does not work on Brewing stands

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#2957]
### Describe the bug

Hey, i discovered that Telepathy enchant does not work on Brewing stands. They drop on the ground normally.

### How to reproduce

Place/find brewing stand, use pickaxe whit telepathy enchant and mine it.

### Screenshots / Videos

![Screenshot_201](https://user-images.githubusercontent.com/26152540/179392620-2b66c361-a979-4859-9387-cc6b390d41ba.png)
![Screenshot_200](https://user-images.githubusercontent.com/26152540/179392623-2d59831c-0cf5-463d-b500-f0e68c8670fa.png)

### "/ae plinfo" link

https://paste.md-5.net/osivazekuz

**Comment by GC-spigot** [comment]
Fixed in next update
