### ISSUE TITLE
Could not pass BlockBreakEvent 

### ISSUE THREAD

**Issue by maximina16** [GC-spigot/AdvancedEnchantments#2959]
### Describe the bug

Spams error when i try to break any block with trench enchant. It's probably happens for every pickaxe enchant. I only tried the trench

### How to reproduce

Simply adding trench enchant to pickaxe. And you'll see

### "/ae plinfo" link

https://paste.md-5.net/itoromufom

### Server Log

https://mcpaste.io/e53b60940b2ad221

**Comment by reussy** [comment]
If you're using [AutoPickup](https://www.spigotmc.org/resources/autopickup-1-18-support.70157/) make sure you have the latest version.

**Comment by maximina16** [comment]
> If you're using [AutoPickup](https://www.spigotmc.org/resources/autopickup-1-18-support.70157/) make sure you have the latest version.

It's on latest version right now

**Comment by Awpmeister2170** [comment]
Can’t seem to reproduce this error, can you update to the latest version of the plugin and see if your issue is fixed?

**Comment by maximina16** [comment]
It’s fixed when i updated the AutoPicker pl. Thanks

Windows için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: ***@***.***>
Gönderilme: 22 Temmuz 2022 Cuma 06:18
Kime: ***@***.***>
Bilgi: ***@***.***>; ***@***.***>
Konu: Re: [GC-spigot/AdvancedEnchantments] Could not pass BlockBreakEvent (Issue #2959)


Can’t seem to reproduce this error, can you update to the latest version of the plugin and see if your issue is fixed?

**Comment by Awpmeister2170** [comment]
Brilliant :) I’ll close this issue now.
