### ISSUE TITLE
When you combine 2 items with the same enchant to upgrade that enchant level, the enchant takes 2 slots

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2960]
### Describe the bug

I.E.

Boots w/ springs 1 (2/3 slots left)
\+
Boots w/ springs 1 (2/3 slots left)
\=
Boots w/ springs 2 (1/3 slots left)

Then, if you apply another enchant to that item - the available slots goes down to 0.

### How to reproduce

Merge 2 items with same enchant in anvil, check available slots on item.

### "/ae plinfo" link

https://paste.md-5.net/ifosigarex

**Comment by Awpmeister2170** [comment]
Hello, Sorry im unsure what you mean could you possibly send a video of the issue?

**Comment by Awpmeister2170** [comment]
Sorry, i dont understand what you mean could you possibly send a video of the issue?

**Comment by bdagenais2** [comment]
I wasn't able to replicate the issue. It may be fixed and I was too slow to report it.
