### ISSUE TITLE
'STATIC_EFFECT' enchants delete armor on world change

### ISSUE THREAD

**Issue by EndergamerHUN** [GC-spigot/AdvancedEnchantments#2962]
### Describe the bug

When I change worlds with any armor having an enchantment of type 'STATIC_EFFECT', the item gets completely deleted and the effect stays on the player.

### How to reproduce

1. Enchant helmet with glowing
2. Go through a portal or use a teleport command to change worlds
3. Your helmet is gone, but you still have night vision.

### Screenshots / Videos

https://youtu.be/jkPPbbYNExM

### "/ae plinfo" link

https://paste.md-5.net/ofigacaqex

### Server Log

https://mcpaste.io/b687c2721395d03f

**Comment by Awpmeister2170** [comment]
Update to the latest version and see if it fixes your issue, your using a pretty outdated version
