### ISSUE TITLE
AOE effect enchants let players kill protected animals within GriefPrevention claims

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2965]
### Describe the bug

Players can use the enchant "Plummet" to kill villagers within someone else's griefprevention claim (which should be protected). The Plummet enchant uses the ADD_HARM effect as an AOE. It seems to ignore griefprevention protections.

### How to reproduce

See above.

### "/ae plinfo" link

https://paste.md-5.net/ifosigarex

**Comment by Awpmeister2170** [comment]
Fixed in next update.
