### ISSUE TITLE
"Smelting" breaks BentoBoxes's AOneblock add-on.

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#2966]
### Describe the bug

I am not sure how or why it works, but using the enchantment "[Smelting](https://paste.helpch.at/cesayiziba.pl)" literally breaks the Oneblock. It will not re-appear like it should. It just simply make's it an empty block which shouldn't be possible.

### How to reproduce

In order to test, you need to be using [Bentobox AOneblock](https://download.bentobox.world/custom). 

Get a pickaxe with just Smelting and one without, you'll notice that the oneblock act's completely as it should without the use of silktouch. If you use the smelting enchantanted pickaxe, you'll notice the one block completely get's removed and doesn't generate another block but simply breaks.

### Screenshots / Videos

1. https://gyazo.com/7a27d672c5d5399dc483f43bf8095728
2. gyazo.com/722461afd23d6c74a2d049342442515e
3. https://youtu.be/LonKhGOIhDw

### "/ae plinfo" link

https://paste.md-5.net/enesenuriv

### Server Log

https://mcpaste.io/40d939f1047c0d08

**Comment by Awpmeister2170** [comment]
Fixed next update
