### ISSUE TITLE
Magic Dust and InventoryClickEvent error

### ISSUE THREAD

**Issue by Gabris060** [GC-spigot/AdvancedEnchantments#2967]
### Describe the bug

Magic dust will not apply to any books of its own group (simple dust on simple book etc). When dragging and dropping it nothing happens. It also spams an error in the console (see separate issue: https://github.com/GC-spigot/AdvancedEnchantments/issues/2946). Could this please be prioritised as soon as possible, because I have seen other people also having this issue.

### How to reproduce

Drag and drop Magic Dust on a custom enchantment book.

### Screenshots / Videos

https://youtu.be/_naFnR18MXY

### "/ae plinfo" link

https://paste.md-5.net/zinipuloyi

### Server Log

https://mcpaste.io/423875eb6d00502c

**Comment by Awpmeister2170** [comment]
This is a configuration error and needs to be updated to the latest, Please update your Config and your issue should be resolved
