### ISSUE TITLE
Wrong indentation in lores and messages chat

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2968]
### Describe the bug

As my issue is doing 3 mounths birthday, I just guess would be better if I open another issue.

There is: https://github.com/GC-spigot/AdvancedEnchantments/issues/2779

I guess is really easy to fix that.

### How to reproduce

In that issue I was using 8.9.18, I tested the new version (also 8.13.0) and isn't working either.

### "/ae plinfo" link

https://paste.md-5.net/uhovitinis.css

**Comment by Awpmeister2170** [comment]
Fixed Next update
