### ISSUE TITLE
Special characters doesn't work on lang file (Still not fixed)

### ISSUE THREAD

**Issue by Golicraft** [GC-spigot/AdvancedEnchantments#2969]
### Describe the bug

The bug is that it appears "?" instead of the actual character I'm using. I have seen two exact same issues which I link below. It's exactly the same problem. And still not fixed, odd?

https://github.com/GC-spigot/AdvancedEnchantments/issues/2311
https://github.com/GC-spigot/AdvancedEnchantments/issues/2592

It's only in the lang.yml file. Special characters work in for example enchantments.yml.

### How to reproduce

Add for example this line in lang.yml

  wrong-material: "&cThis enchantment cannot &f[ 鏻 ] be applied on this item."

Then it appears in chat: 

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/11066952/181215841-c1d735a5-9193-4529-a2f6-ac8827b89d61.png)

### "/ae plinfo" link

https://paste.md-5.net/zifotekaxu

**Comment by Golicraft** [comment]
This is hopeless. This is just before I post a bad review. It's the second time I've reported it now, it's supposed to be so easy to fix and you've had the same problem presented several times, but it hasn't done anything about it! Incredibly bad.

@GC-spigot

**Comment by GC-spigot** [comment]
> This is hopeless. This is just before I post a bad review. It's the second time I've reported it now, it's supposed to be so easy to fix and you've had the same problem presented several times, but it hasn't done anything about it! Incredibly bad.
> 
> @GC-spigot

https://ae.advancedplugins.net/plugin-information/faq#non-english-languages-garbled-in-game

**Comment by GC-spigot** [comment]
I reworked the lang system just now, let me know if next update helps with it as well :)
