### ISSUE TITLE
[Feature Request] Enchantments fully work on mobs

### ISSUE THREAD

**Issue by ghosts1234** [GC-spigot/AdvancedEnchantments#297]
I mentioned this on the discord server, however, I think it would be great if all the attack based custom enchants (EG Life steal, rage, ect) would be fully compatible with mobs. This is mainly because it would allow the custom enchants to be used with custom server dungeons, and overall will enhance the users experience with the plugin.  Currently, it spews out in console errors like the ones below.

https://hastebin.com/ropadebicu.sql
https://hastebin.com/bepawaseje.css

**Comment by GC-spigot** [comment]
Sadly cannot be done with current enchants engine.
