### ISSUE TITLE
Speed II Custom Enchant

### ISSUE THREAD

**Issue by yeatt** [GC-spigot/AdvancedEnchantments#2971]
### Describe the bug

we have a custom enchant that gives permanent speed II on any pair of boots, but when players use a totem of undying, it removes the speed effect and doesn't return until the player re-equips their boots.

### How to reproduce

Any custom enchant that applies permanent speed II on armor equip

speed:
  display: "%group-color%Speed"
  description: "Added speed when equipped."
  applies-to: "Boots"
  type: "EFFECT_STATIC"
  group: "ULTIMATE"
  applies:
    - ALL_BOOTS
  levels:
    1:
      effects:
        - "POTION:SPEED:1"

### "/ae plinfo" link

https://paste.md-5.net/xuruquzawa

**Comment by Awpmeister2170** [comment]
Fixed for next update
