### ISSUE TITLE
AE doesnt work at all

### ISSUE THREAD

**Issue by BertieBots** [GC-spigot/AdvancedEnchantments#2974]
### Describe the bug

Every time I try to do a command for a book or the list is says "An internal error has occurred while attempting to perform this command." Im playing on 1.19 in a paper minehut server if thats info you need. I cant even do the /ae plinfko thing

### How to reproduce

just every time i try to use a command with /ae

### Screenshots / Videos

![2022-08-01_20 16 48](https://user-images.githubusercontent.com/110433741/182265875-4f8ac25f-4f13-46f6-a1bc-394a1ce5bc7d.png)

### "/ae plinfo" link

it doesnt work

**Comment by Awpmeister2170** [comment]
Hello @BertieBots can you please send over your Console logs and Open a ticket in our Discord, we need some more information from you ie the errors you receive in console etc.

**Comment by BertieBots** [comment]
Im sorry but i dont know how to do either of those things. Im logging into the AE discord right now tho

**Comment by BertieBots** [comment]
I believe I have opened a ticket but i do not know how to give you console commands sry :/

**Comment by Bunnky** [comment]
This is likely due to AP's authentication servers going down. When that happens, AE will disable itself, and will cease to function until that server is back up.

If you start your server and immediately see AE or any of AP's plugins disable, this may be the cause.

AP's authentication server is an anti-piracy measure, however, that measure is very unstable, as the authentication server is **REQUIRED** :/

**Comment by BertieBots** [comment]
Oh ok. That might be it because when i do /plugin to see my plugins AE is red. Do you have any idea how to fix it?

**Comment by Awpmeister2170** [comment]
I can’t seem to locate your ticket on our Discord can you open one and we can look into the issue there, I need to see your console logs.

To get them head to your server files and find the latest.log and send that over 👍

**Comment by BertieBots** [comment]
My ticket number is 2328

**Comment by BertieBots** [comment]
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/9254312/latest.log)

**Comment by BertieBots** [comment]
I believe those are my ticket and latest logs 👍

**Comment by Awpmeister2170** [comment]
Are you sure the ticket is still open? i am unable to locate it still, The reason the Plugin isnt working is you have reached the Max IPs and your license is full so i need more info from you but best done in a ticket on the Discord, Tag me in the ticket you have open on there or open a new one and i can assist you further
