### ISSUE TITLE
Disabling AdvancedEnchantments

### ISSUE THREAD

**Issue by haroldrc** [GC-spigot/AdvancedEnchantments#2975]
### Describe the bug

the error occurs randomly, after I start the server the error occurs

### How to reproduce

idk

### "/ae plinfo" link

the plugin gets disabled, so I can't do that

### Server Log

https://mcpaste.io/67d8f74ce1a24a35

**Comment by Awpmeister2170** [comment]
Issue is being dealt with, will be fixed asap

**Comment by haroldrc** [comment]
how do i know when you will fix it?

**Comment by Awpmeister2170** [comment]
It's already fixed 👍
