### ISSUE TITLE
ADD_FOOD are not applied when player hit by monster. 

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#2978]
### Describe the bug

ADD_FOOD are not applied when player hit by monster

### How to reproduce

공복:
  display: "%group-color%공복"
  description: "일정 시간마다\n허기를 채울 확률이 생깁니다."
  applies-to: "투구"
  type: "REPEATING"
  time: 5
  group: "에픽"
  applies:
    - ALL_HELMET
  levels:
    1:
      chance: 45
      effects:
        - "ADD_FOOD:1"
    2:
      chance: 65
      effects:
        - "ADD_FOOD:1"
    3:
      chance: 85
      effects:
        - "ADD_FOOD:1"
    4:
      effects:
        - "ADD_FOOD:1"

### Screenshots / Videos

videop : https://www.youtube.com/watch?v=lsxf0rK9fXQ&feature=youtu.be

### "/ae plinfo" link

https://paste.md-5.net/koxoxofubi

**Comment by Faln** [comment]
The type needs to be changed to `type: "DEFENSE_MOB"`. Confirmed this is not a bug, enchant worked successfully.

**Comment by Ecilpse** [comment]
> The type needs to be changed to `type: "DEFENSE_MOB"`. Confirmed this is not a bug, enchant worked successfully.

i don't want change DEFENSE_MOB. just REPEATING.
Due to the genre of the server, there are not many chances to be hit by monster.

**Comment by Faln** [comment]
Your description of the bug is `ADD_FOOD are not applied when player hit by monster` and the enchant you've pasted will never work with DEFENSE_MOB. 

I've also tested the enchant on `REPEATING` and it seems to work fine.
`food:
  display: "%group-color%Food"
  description: "일정 시간마다\n허기를 채울 확률이 생깁니다."
  applies-to: "투구"
  type: "REPEATING"
  time: 5
  group: "SIMPLE"
  applies:
    - ALL_HELMET
  levels:
    1:
      chance: 100
      cooldown: 3
      effects:
        - "MESSAGE:&aYou have been fed!"
        - "ADD_FOOD:10"`

**Comment by Ecilpse** [comment]
> 

it doesn't work if it's hit by a mob when it's REPEAT type.

https://studio.youtube.com/video/2pQyyMQInro/edit

> Your description of the bug is `ADD_FOOD are not applied when player hit by monster` and the enchant you've pasted will never work without DEFENSE_MOB.
> 
> I've also tested the enchant on `REPEATING` and it seems to work fine. food: display: "%group-color%Food" description: "일정 시간마다\n허기를 채울 확률이 생깁니다." applies-to: "투구" type: "REPEATING" time: 5 group: "SIMPLE" applies: - ALL_HELMET levels: 1: chance: 100 cooldown: 3 effects: - "MESSAGE:&aYou have been fed!" - "ADD_FOOD:10"

**Comment by Faln** [comment]
It will never work when hit by a mob. Its not DEFENSE_MOB type. You choose to NOT put the enchant on DEFENSE_MOB hence mob attacking you will do nothing.

If you have further issues with REPEATING enchant types. Update to the latest version and copy/paste the enchant example from https://ae.advancedplugins.net/enchantments/repeating-enchantments.
