### ISSUE TITLE
Plugin Disable

### ISSUE THREAD

**Issue by ImYenil** [GC-spigot/AdvancedEnchantments#2980]
### Describe the bug

I am not using CraftBukkit, but the plugin is disabled

### How to reproduce

https://pastebin.com/fr5V2wfH

### "/ae plinfo" link

X

**Comment by Awpmeister2170** [comment]
Hello, it seems the error states you are using CraftBukkit Still, make sure to delete it completely and install either Paper or Spigot as this is what we recommend

**Comment by GC-spigot** [comment]
Fixed next update
