### ISSUE TITLE
Veinminer enchant searches in arbitrary 4 block radius

### ISSUE THREAD

**Issue by Shawn11564** [GC-spigot/AdvancedEnchantments#2981]
### Describe the bug

When using the vein_miner enchant, it arbitrarily searches in a 4 block radius instead of a preconfigured radius. This can lead to the enchant chaining very far from the source block as long as it can find at least 1 block of the original broken type within 4 blocks. It goes through air and layers of stone and looks / feels unrealistic.

My suggestion is to make this search radius configurable.

### How to reproduce

- Enchant a pickaxe with vein_miner
- Place down breakable ores that are within 4 blocks of eachother but not directly connected
- Break one and watch the enchant magically break the others through 3 block gaps of air

### "/ae plinfo" link

https://paste.md-5.net/civuwisatu

**Comment by Awpmeister2170** [comment]
Fixed for next update
