### ISSUE TITLE
Soul dupe critical issue

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2983]
### Describe the bug

It's possible to add the soultracker in items that shouldn't be possible.
For example golden apples: 
![image](https://user-images.githubusercontent.com/66658478/183744355-b0ded359-33a4-4ae7-83d3-84b5a1879f53.png)
Foods: 
![image](https://user-images.githubusercontent.com/66658478/183744320-5c10d438-5fe8-4eca-b7b2-1efd209ac0b2.png)

For some reason, blocks and some items is not possible.
But, when the soul tacker is applied, the player is able to add soul gem to the stacked item, and after that is just unstacked them and you will have a lot of items with lots of souls.

Players can do /withdrawsouls on my server so they can dupe soul unlimited.

### How to reproduce

1. Take a soultracker with **/ae giveitem nickname soultracker 1**
2. Take any stacked item, eg 64 enchanted golden apple
3. Apply the soultracker in the stacked item, like the image below:
![image](https://user-images.githubusercontent.com/66658478/183744962-36dd9491-edb4-40e9-9b21-07a99306542b.png)
4. Give yourself soul gem, don't matter quantity, using **/ae giveitem nickname soulgem 1 300**
5. Apply the soulgem in the item with soultracker, like the image below:
![image](https://user-images.githubusercontent.com/66658478/183745099-055f7b87-ebb3-4822-b52d-63b022949d5f.png)
6. Split the items in your inventory, like the image below:
![image](https://user-images.githubusercontent.com/66658478/183745217-0862b20d-49a5-4db3-8a3d-4958e01e1450.png)
7. Done, now you have 300 souls in 64 items. You could withdraw this souls, gather the apples again and to the process many times you want.

### "/ae plinfo" link

https://paste.md-5.net/xakijoyato

**Comment by Awpmeister2170** [comment]
Hello, Remove ALL_EDIBLE in your Config and this should fix your issue.

**Comment by austv** [comment]
> 

Fixed, thanks.
