### ISSUE TITLE
ASETS - Have to reapply on rejoin in order for it to work

### ISSUE THREAD

**Issue by ConnorServers** [GC-spigot/AdvancedEnchantments#2986]
### Describe the bug

Hi.

I've created an armour set, however, if I re-login then the armour set will no longer work.
I have multiple players complaining every single day, please is there a way to fix this?

I'm using latest version of AE.
https://gyazo.com/74be770d964eabebf802471fca0b6216

Thank you.

### How to reproduce

I've created an armour set, however, if I re-login then the armour set will no longer work.
I have multiple players complaining every single day, please is there a way to fix this?

### Screenshots / Videos

https://gyazo.com/74be770d964eabebf802471fca0b6216

### "/ae plinfo" link

https://paste.md-5.net/segikexiyo

### Server Log

https://mcpaste.io/

**Comment by Awpmeister2170** [comment]
Fixed.
