### ISSUE TITLE
Sweeping Edge Not Working

### ISSUE THREAD

**Issue by BrandonT80** [GC-spigot/AdvancedEnchantments#2989]
### Describe the bug

Sweeping edge no longer work with AE. When using it, it will only ever hit one mob at a time. This is present even with AE as the only plugin as seen below.

This was tested in both 1.19 and 1.19.2.

### How to reproduce

Add sweeping edge to a sword. Attack a group of mobs close together. Will only ever hit one single mob at a time instead of area.

### "/ae plinfo" link

https://paste.md-5.net/zupesasoxu

**Comment by Awpmeister2170** [comment]
Latest Version will fix this issue
