### ISSUE TITLE
Incorrect damage to mobs

### ISSUE THREAD

**Issue by Cowio** [GC-spigot/AdvancedEnchantments#2990]
### Describe the bug

With the plugin enabled, swords and axes dont deal the right damage amounts.

Testing without the plugin: You can kill a pig with 2 swings of a netherite sword or 1 swing with a netherite axe
Testing with the plugin: You can kill a pig with 6 swings of a netherite sword or 5 swings with a netherite axe

This makes it so that netherite is basically just as strong as wooden swords or axes. It is not only netherite, all axes and swords deal so little damage and I dont know why. This is both with and without any custom enchantments on the weapons. And of what I can see there are no settings in the config to disable this, therefore this must be a bug.

### How to reproduce

1. Open up a singleplayer or server without advanced enchantments plugin
2. Take a netherite sword or axe
3. /summon minecraft:pig
4. Kill the piggy
5. Count the swings
6. Open a server with advanced enchantments plugin
7. Go to step 2.

### "/ae plinfo" link

https://paste.md-5.net/ojaxegixas

### Server Log

no errors or stacktrace to see

**Comment by BrandonT80** [comment]
Can confirm this is an issue on my side too.

**Comment by Awpmeister2170** [comment]
Update to latest version, this issue is resolved
