### ISSUE TITLE
Damage bug

### ISSUE THREAD

**Issue by SalvatoreZx** [GC-spigot/AdvancedEnchantments#2991]
### Describe the bug

Hello i got a problem i cant do more than 2-3 damage on all mobs.

No errors in console. 

### How to reproduce

Hitting the mobs and the damage is the same (2-3)

### "/ae plinfo" link

https://paste.md-5.net/eyunigejus

**Comment by BrandonT80** [comment]
Same issue as #2990

I can also confirm this is an issue as well.

**Comment by Awpmeister2170** [comment]
Update to latest version this should resolve your issue

**Comment by jimlin91** [comment]
I have updated to the newest version, but the issue remains

**Comment by BrandonT80** [comment]
Can confirm, issue still remains

**Comment by SalvatoreZx** [comment]
issue still remains

**Comment by Lemonray114** [comment]
issue still remains

**Comment by GC-spigot** [comment]
@Lemonray114 @SalvatoreZx @BrandonT80 @jimlin91 Post your "/ae plinfo" links, there must be a mutual external plugin causing such issues. Are you using any specific enchantments for this to happen?

**Comment by austv** [comment]
@SalvatoreZx this bug is only related to mobs?

**Comment by GC-spigot** [comment]
I can't recreate it on latest version of AdvancedEnchantments without any other plugins

**Comment by SalvatoreZx** [comment]
https://paste.md-5.net/oyezavokic @GC-spigot 
@austv I haven't tried on players but yes on all mobs, also bow damage I think its okay.
@GC-spigot I tried the plugin with out other plugins and it doesn't work in discord I sent some pictures when I was disabling and enabling the plugin.

**Comment by jimlin91** [comment]
I think the issue is relate to protocolLib. Once I updated new version, problem fixed.

**Comment by BrandonT80** [comment]
> I think the issue is relate to protocolLib. Once I updated new version, problem solved.

Can confirm, the latest protocollib dev build fixed the damage issue!
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by SalvatoreZx** [comment]
Bug has been fixed update the ProtocolLib,

**Comment by Awpmeister2170** [comment]
I will close this issue now :) any other issues let us know Thank you to everyone for reporting this and helping find the solution :)
