### ISSUE TITLE
Breaking blocks in creative creates errors

### ISSUE THREAD

**Issue by Peanutis1mo** [GC-spigot/AdvancedEnchantments#2992]
### Describe the bug

I have already made a ticket on discord, they told me to report it.

The issue is when I try to break a block with anything (even hand) it generates errors like this:

Could not pass event InventoryCreativeEvent to AdvancedEnchantments v8.13.9
Could not pass event PlayerInteractEvent to AdvancedEnchantments v8.13.9

### How to reproduce

I just broke a block in creative, idk about survival.

### "/ae plinfo" link

https://paste.md-5.net/esuyolifiw

### Server Log

https://mcpaste.io/db60a25c3df55c89

**Comment by Awpmeister2170** [comment]
Hello, can you provide us your Config File please, Thank you

**Comment by Peanutis1mo** [comment]
https://pastebin.com/H0J7VqK0

**Comment by GC-spigot** [comment]
Seems to be resolved
