### ISSUE TITLE
EFFECT_STATIC, TRIDENT_THROW, and HELD DUPLICATE BUG

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#2996]
### Describe the bug

 Issue is reported by OwO 2L#1997 | 254349985963835393
 Discord [Transcript](https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/841740907467636756/1010877110413434890/transcript-aenchantments-2585.html)
 
I am not sure if this is intended or a bug tho, it really feels like a bug.
I have this enchant which is mainly a copy of Abiding default enchant
```
undestructable:
  display: '%group-color%Undestructable'
  description: "Makes your enchanted tool Unbreakable\nhowever you first must have Unbreaking Level 10\n(Unbreaking X) on the item."
  applies-to: 'All Armour & Tools & Weapons'
  group: 'FABLED'
  type: 'EFFECT_STATIC;ATTACK;MINING;ATTACK_MOB;KILL_MOB;BOW;KILL_PLAYER;SWING;REPEATING;BOW_MOB;ELYTRA_FLY;ROD_CAST'
  time: 1
  applies:
    - 'ALL_ARMOR'
    - 'ALL_SWORD'
    - 'ALL_AXE'
    - 'BOW'
    - 'ALL_PICKAXE'
    - 'ALL_SPADE'
    - 'ELYTRA'
  settings:
    required-enchants:
      - 'unbreaking:10'
  levels:
    1:
      effects:
        - 'REPAIR'```
        

### How to reproduce

What happens is, when you try to unequip the armour it literally duplicates it
so it removes it but also re-creates the armour
I do want this to be applicable to all tools, weapons and armour if they have upgraded their unbreaking to level 10 on the specific item, Ideally using repeating is what I'm looking for but it doesn't seem to work as intended

I found out that the armour duplication is caused by "EFFECT_STATIC" and I discovered that "TRIDENT_THROW" (for trident) and "HELD" (for any item that has the enchantment, it can also void previously held items) cause also item duplications

### Screenshots / Videos

_No response_

### "/ae plinfo" link

https://paste.md-5.net/owakezurew

### Server Log

_No response_

**Comment by austv** [comment]
@SirJben This happens because EFFECT_STATIC apply when you click on the armor to remove/add...
Change all these "types" for REPEAT, and your enchantment will work the same way and no bugs.

**Comment by Kimochii-x3** [comment]
Hi, I'm OwO 2L, I have found a different way to work with this, I have removed EFFECT_STATIC and TRIDENT_THROW along with HELD as those cause the duplication with REPAIR effect. But it still shouldn't recreate the armour upon equip/unequip. Same for when a trident is thrown and held item is changed. I will try to edit this later on when I create a video to showcase it.
