### ISSUE TITLE
Enchantment Apply Errors

### ISSUE THREAD

**Issue by SirCraftypants** [GC-spigot/AdvancedEnchantments#2998]
### Describe the bug

When i updated to the latest AE, multiple errors were thrown because AE is refusing to allow for `- FEATHER or - STICK` in the enchantment apply list as show below. 

  applies:
    - ALL_HELMET
    - FEATHER  

I was the user who requested this feature in 1.17.2 and you implemented it, it was working perfectly fine in 1.18.2, soon as i updated to 1.19.2 and updated AE, errors were thrown.  I removed the FEATHER and STICK from the enchantments and the errors stopped. 

### How to reproduce

Add `- FEATHER or -STICK` to enchantments apply list.

### "/ae plinfo" link

https://paste.md-5.net/omokagenek

### Server Log

https://mcpaste.io/b7850d38179f9480

**Comment by austv** [comment]
same here

**Comment by UniqueUserName500** [comment]
This plugins spamming update but never fix the most simplest bug. What is wrong with the author

**Comment by Awpmeister2170** [comment]
Fixed next update.

**Comment by SirCraftypants** [comment]
thanks for the update
