### ISSUE TITLE
TP_DROPS issue with mcMMO

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2999]
### Describe the bug

When a item is enchanted with TP_DROPS effect, mcMMO doesn't work with it.

2 examples for it:

1. When mine a block with a pickaxe and TP_DROPS, the players doesn't gain mcmmo mining experience.
2. mcMMO has the skill to duplicate crops (like in herbalism, mining, woodcutting..). The extra drop doesn't work when the item is enchanted with TP_DROPS

### How to reproduce

Create a enchantment with TP_DROPS and 100% chance.
Have mcMMO installed on the server.
Try to mine something to see if you gain mcmmo XP.
Get max level of mining and mine some ore to see that double drops doesn't work.
Get max level of herabalism and extract some crops to see that double drops doesn't work.

### "/ae plinfo" link

https://paste.md-5.net/busereluno.sql

**Comment by Awpmeister2170** [comment]
Fixed for next update
