### ISSUE TITLE
Apply items doesn't work in new versions

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3002]
### Describe the bug

The version 8.14.1 and newer, ae items as whitescroll to work on items that doesn't have any enchantment before.
For example, if you want to add a whitescroll on a item before apply a enchantment, this doesn't work.

**The version 8.14.0 works fine. I tested every version above 8.14.0**

### How to reproduce

1. Take a fishing rod.
2. Give yourself any AE item, like whitescroll (/ae giveitem nick whitescroll 1)
3. Try to apply on item without any enchantments. Nothing happens and there is errors on console
4. Look the error: https://pastebin.com/mZ3MzURN

Also, the slotincreaser message is wrong, when you apply on a item withou enchantments
![image](https://user-images.githubusercontent.com/66658478/186955179-1c7429a4-33d9-4576-b9a8-5a803c2b0157.png)

### "/ae plinfo" link

https://paste.md-5.net/toresoxajo

**Comment by Awpmeister2170** [comment]
This is intentional for the WhiteScroll to not apply when an item does not have an enchant. 

You need to have an enchant on item already for these admin items to be applyable

**Comment by austv** [comment]
@Awpmeister2170 I have to move to a old version, that whitescroll is now work without enchantment.
I don't think this is intentional, did you saw the error log? I believe that if it was intentional, it would not have the error message.

Also, slotincreaser don't work on fishing rods sometimes, and I can't find a model for this situation.

**Comment by Awpmeister2170** [comment]
Ahh ok, it is intended to be how it is now but may have been changed in a recent update by one of our developers.

We will look into this

**Comment by Awpmeister2170** [comment]
Fixed in the Next Update
