### ISSUE TITLE
No special mob drops when using sweeping edge

### ISSUE THREAD

**Issue by Il-Palazzo** [GC-spigot/AdvancedEnchantments#3006]
### Describe the bug

The sweep attack damage of swords doesn't work with the mobs custom drops from the plugin
I gave a zombie 100 chance to drop something, works fine if I kill it with the sword attacking him directly
But if i use the sweeping edge part of the attack, it doesn't drop anything.
I also tested with a group of mobs with the same result, the ones killed by the sweeping edge do not drop special loot.

Tested in 1.18.2
Plugin Version: 8.13.5

### How to reproduce

You can use an armor stand to test it easily, attack the armor stand and kill the mobs with the sweeping edge part of the attack and they wont drop anything from the plugin. 

### "/ae plinfo" link

https://paste.md-5.net/ejimexapew

**Comment by Awpmeister2170** [comment]
Hello, i cant seem to reproduce this, can you please Update to the latest version of the Plugin and send us a video of this issue Thanks.
