### ISSUE TITLE
White Scroll not working

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#3007]
### Describe the bug

Error when use whitescroll drag and drop item

### Screenshots / Videos

https://pastebin.com/4rSBKTPg

### "/ae plinfo" link

https://pastebin.com/4rSBKTPg

**Comment by Awpmeister2170** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/issues/3002 

Same as reported here.
