### ISSUE TITLE
Telepathy + coreprotect issue

### ISSUE THREAD

**Issue by Il-Palazzo** [GC-spigot/AdvancedEnchantments#3008]
### Describe the bug

Blocks broken by telepathy enchantment are not logged in core protect

### How to reproduce

Use a pickaxe enchanted with telepathy, break a bloc, it leaves no logs in the core protect plugin

### "/ae plinfo" link

https://paste.md-5.net/ejimexapew

**Comment by Awpmeister2170** [comment]
Fixed for next update
