### ISSUE TITLE
Smelting enchant break-block event compatible bug (Battle pass plugin)

### ISSUE THREAD

**Issue by Sangnamja123** [GC-spigot/AdvancedEnchantments#3009]
### Describe the bug

When using Smelting Inchant, the block-break smelted block in the battle pass plugin are not counted.

### How to reproduce

Mining ore with a pickaxe with the Smelting custom enchantment applied. (Battle pass plugin quest applied)

  1:
    name: '1주 - 광부는 힘들구나... (1)'
    type: block-break
    variable: coal_ore:0 
    required-progress: 200
    points: 10
    item:
      material: diamond_pickaxe:0
      amount: 1
      name: '&e광부는 힘들구나... (1)'
      lore:
        - ''
        - '&6● &e200개&f의 &e석탄 광석&f을(를) 캐보자!'
        - ''
        - '&6● &f진행도: &e%total_progress%&7/&a%required_progress%'
        - ''

### "/ae plinfo" link

https://paste.md-5.net/ofilobicek

**Comment by Awpmeister2170** [comment]
Fixed next update
