### ISSUE TITLE
PULL_AWAY doesn't work on custom weapons

### ISSUE THREAD

**Issue by Gladnii** [GC-spigot/AdvancedEnchantments#3010]
### Describe the bug

when i create custom weapon (item) with PULL_AWAY effect it won't work, but when I make enchant with exact same effect it works without problem.

### How to reproduce

This is how my custom weapon config looks:
https://pastebin.com/J4gkXv50
But when I make custom enchant with exact same effect it works without any problems.

### "/ae plinfo" link

https://paste.md-5.net/ajujavisoq

**Comment by GC-spigot** [comment]
Fixed
