### ISSUE TITLE
Disappearing block on OneBlock

### ISSUE THREAD

**Issue by DrakMC** [GC-spigot/AdvancedEnchantments#3011]
### Describe the bug

If I dig the main block on OneBlock (BentoBox), the block disappears.

### How to reproduce

1. Have a pickaxe with the Smelting enchantment.
2. Dig the main block
3. The main block will disappear.

### "/ae plinfo" link

https://paste.md-5.net/hexajaviqo

**Comment by ClickErrorxD** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/issues/2966

**Comment by Awpmeister2170** [comment]
Fixed next update
