### ISSUE TITLE
TP_DROPS with MORE_DROPS are not worked with.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3012]
### Describe the bug

TP_DROPS with MORE_DROPS are not worked with.

### How to reproduce

reproduce video : https://youtu.be/3Bc_se8u2ek
first pickaxe is only MORE_DROPS
second pickaxe is MORE_DROPS + DP_DROPS

증식: #MORE_DROPS
display: "%group-color%증식"
description: "광물 블록 채광시, 확률적으로\n광물획득량이 늘어납니다.\n&8(섬세한 손길, 굴삭기, 광맥 적용 불가)"
applies-to: "곡괭이"
type: "MINING"
group: "레전더리"
applies:
- ALL_PICKAXE
settings:
not-applyable-with:
- "SILK_TOUCH"
- "광맥"
- "굴삭기"
levels:
1:
chance: 50
cooldown: 1
condition:
- "%block type% contains ORE : %allow%"
effects:
- "MORE_DROPS:3"
2:
chance: 60
cooldown: 1
condition:
- "%block type% contains ORE : %allow%"
effects:
- "MORE_DROPS:5"
3:
chance: 70
cooldown: 1
condition:
- "%block type% contains ORE : %allow%"
effects:
- "MORE_DROPS:7"

######################

수확: #TP_DROPS
  display: "%group-color%수확"
  description: "확률적으로 도구로 파괴한 블록이\n인벤토리에 자동으로 들어갑니다.\n&7(mcMMO [2배 드롭]은 적용되지 않습니다)"
  applies-to: "도구,괭이"
  type: "MINING"
  group: "레전더리" #언커먼
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
    - ALL_HOE
  levels:
    1:
      chance: 50
      effects:
        - "TP_DROPS"
    2:
      chance: 80
      effects:
        - "TP_DROPS"
    3:
      effects:
        - "TP_DROPS"

### "/ae plinfo" link

https://paste.md-5.net/idoyanewex

**Comment by Awpmeister2170** [comment]
Hello, are you using the Enchant MORE_DROPS on Naturally Spawned Blocks or are you placing them?

**Comment by Ecilpse** [comment]
> Hello, are you using the Enchant MORE_DROPS on Naturally Spawned Blocks or are you placing them?

yes. not placed block.

**Comment by Awpmeister2170** [comment]
What blocks are you breaking in the Video as they don’t look like Naturally Spawning Blocks 🤔

**Comment by Ecilpse** [comment]
> What blocks are you breaking in the Video as they don’t look like Naturally Spawning Blocks 🤔

this is not placedblock, by worldedit. It was reproduced separately for easy viewing. i also tested with nature block
