### ISSUE TITLE
TP_DROPS causes tools to take damage when breaking crops

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3013]
### Describe the bug

When using an enchantment with TP_DROPS effect, breaking crops damages the item. This does not happen with the same items without this enchantment.

### How to reproduce

Put a TP_DROPS enchantment on an item.
Break a crop.
The item will take damage when it should not.

### "/ae plinfo" link

https://paste.md-5.net/owaxobajec

**Comment by Awpmeister2170** [comment]
Fixed for next update
