### ISSUE TITLE
Vein Miner, Some time works and sometime doesn't

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#3014]
### Describe the bug

Vein Miner, Some time works and sometime doesn't... Sharing the config below... for players its random even tho they have more than 10K souls and was working fine before... After updating the server to 1.19.2 started happening this issue so idk..
And when reporting this bug already updated plugin jar to lstest to time reporting this bug...

Players reported it works 5-6 time out of 10 times and rest of time doesn't so hit and miss. and tested myself happens...

https://paste.md-5.net/iyojayoteh.pl

### How to reproduce

just mine with vein miner?

### "/ae plinfo" link

https://paste.md-5.net/uqecexanik

**Comment by reussy** [comment]
What exactly does "Some time works and sometime doesn't" mean?
Veinminer stops breaking a block if there is another block in between other than the one being broken, for example, a stone block between a diamond ore.

Previously this was different, all ores nearby were broken, it did not matter if there was another block in between and this shouldn't be the case.

**Comment by Rexmen1** [comment]
So it was changed in the recent version? 
And by sometime it works and sometime it doesn't it doesn't do vein mine...

Like if there are 3 iron ores right next to each other only mining 1, and for 2 ores not mining both only 1...

https://gyazo.com/7e651598424c085a4f961e014bf1140a
https://gyazo.com/1fd6d060494da8199b1cb2a2ed570f53
pickaxe has 66k souls and 80% of the time works and some time just doesn't vein mine for ores like that...

But before they worked 100% of the time no issues.. been using this for 3 months just after updating to 1.19.2 started happening these issue

**Comment by Awpmeister2170** [comment]
They all have to be touching ( ie behind the one you break another ore would need to be there for it to mine the rest. )

**Comment by Rexmen1** [comment]
It was working fine before tho why the change?

**Comment by Rexmen1** [comment]
So i guess need to time to downgrade the plugin...

**Comment by Rexmen1** [comment]
No reason for the change?

**Comment by reussy** [comment]
> What exactly does "Some time works and sometime doesn't" mean? Veinminer stops breaking a block if there is another block in between other than the one being broken, for example, a stone block between a diamond ore.
> 
> Previously this was different, all ores nearby were broken, it did not matter if there was another block in between and this shouldn't be the case.

It doesn't work like that, you only have to break the blocks that are fenced and are together, if left as before then people can break ores infinitely.

**Comment by Rexmen1** [comment]
I mean there are only 5-10 ores, Never in my life seen infinitely ores in a single row...

**Comment by Rexmen1** [comment]
So Idk why this was changed bcz as players point of view and server admin's point of view this is not making sense and is bad move and im sure you guys are making plugins for server admins and players... So please if possible revert back to old method...
