### ISSUE TITLE
combine-dust false was not worked.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3015]
### Describe the bug

![image](https://user-images.githubusercontent.com/25452835/188720437-63c8cf2f-80c9-45de-9e9c-4b47eff2df65.png)
![1](https://user-images.githubusercontent.com/25452835/188720468-8282c4f7-ca46-4314-a3d1-e115a67e6316.PNG)

### How to reproduce

set combine-dust: false, and open alchemist

### "/ae plinfo" link

https://paste.md-5.net/edejaqulip

**Comment by Awpmeister2170** [comment]
Fixed in next update
