### ISSUE TITLE
TP_DROPS drops only one beetroot seed

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3018]
### Describe the bug

When harvesting beetroot with a TP_DROPS enchantment, only one beetroot seed is put in the player's inventory. More should be dropped.

### How to reproduce

Enchant a tool with a TP_DROPS enchantment.
Harvest beetroot.
Only one seed will be "dropped" for each beetroot harvested.

### "/ae plinfo" link

https://paste.md-5.net/febayopona

**Comment by Awpmeister2170** [comment]
Try updating to the Latest Version, i cant reproduce this

**Comment by Dakotaa** [comment]
> Try updating to the Latest Version, i cant reproduce this

Yep, fixed now.
