### ISSUE TITLE
Bug/Error - Custom Made Enchants | Materials.txt Errors

### ISSUE THREAD

**Issue by ZEROOblivious** [GC-spigot/AdvancedEnchantments#3019]
### Describe the bug

When creating an Enchant or modifying one, If you attempt to make a specific item listed in the Materials.txt file, It shoots back this errors in console and those specific items/enchants do not work. Errors are added into the Server Log pastebin. 

Server: Paper(135) 1.19.2-R0.1-SNAPSHOT
Plugin: AdvancedEnchantments-8.14.6 

Plugin list is in the AE plinfo link. 

### How to reproduce

Create a Custom Enchantment
Put it on a Material not on the Material.txt File
Save/Reload 
Error for that Enchantment & Item in the Materials.txt

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/32251194/188875255-511ebd59-f67a-4ecf-8caf-2d006d4bdb2b.png)
After changing the applies section to "ALL_[chestplate,Leggings,boots,etc]" it works perfectly:
![image](https://user-images.githubusercontent.com/32251194/188875292-30220972-be8a-4c93-8a42-bd8387edaa7c.png)

### "/ae plinfo" link

https://paste.md-5.net/qoyitubuvi

### Server Log

https://mcpaste.io/d22262d55f98061e

**Comment by Awpmeister2170** [comment]
Fixed in the next update
