### ISSUE TITLE
[CRUCIAL] Telepathy, of all levels, breaks Bentoboxes AOneblock Addon.

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#3020]
### Describe the bug

When using telepathy, it breaks the Oneblock from BentoBox AOneblock, the addon. It completely gets rid of the block, and in order to fix it, you need to manually place a block in the original position. This happens 100% of the time when using any level of telepathy.

### How to reproduce

Add Telepathy to your pickaxe/tool.
Mine your Oneblock/Omni Block/Magic block from AOneblock.

### Screenshots / Videos

https://youtu.be/5R-2SSMEKqk

### "/ae plinfo" link

https://paste.md-5.net/uzesabaqom

### Server Log

https://mcpaste.io/91b26aa7cb064fd5

**Comment by ClickErrorxD** [comment]
Any update? Multiple of our users are experiencing this.

**Comment by Awpmeister2170** [comment]
Fixed next update
