### ISSUE TITLE
Applies to SHIELD is not worked.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3021]
### Describe the bug

Applies to SHIELD is not worked after update lastest of AE.
when i changed others, it worked.
![캡처](https://user-images.githubusercontent.com/25452835/189104878-d08de1f8-d063-43ab-a388-397e05060d46.PNG)

### How to reproduce

아이기스:
  display: "%group-color%아이기스"
  description: "방패를 오른손으로 방어시,\n일정확률로 내구도를\n큰 폭으로 회복합니다."
  applies-to: "방패"
  type: "SHIELD_BLOCK"
  group: "언커먼"
  applies:
    - SHIELD
  levels:
    1:
      chance: 30
      effects:
        - "ADD_DURABILITY_ITEM:-10"
    2:
      chance: 35
      effects:
        - "ADD_DURABILITY_ITEM:-20"
    3:
      chance: 40
      effects:
        - "ADD_DURABILITY_ITEM:-30"
    4:
      chance: 45
      effects:
        - "ADD_DURABILITY_ITEM:-40"
    5:
      chance: 50
      effects:
        - "ADD_DURABILITY_ITEM:-50"  

### "/ae plinfo" link

https://paste.md-5.net/levegexoqe

**Comment by Awpmeister2170** [comment]
Fixed in next update
