### ISSUE TITLE
Water and Lava Walker do not respect build permissions

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3022]
### Describe the bug

Both the enchantments lava walker and water walker do not respect build permissions from Towny, if I walk into someone's town with those enchantments on, I can simply turn people's water to ice and lava to obsidian.
One way of abusing this would be by walking over water near sugar cane which makes it drop.

### How to reproduce

Have Towny and AE installed, put water walker on your boots, walk over water that's inside another person's town.

### "/ae plinfo" link

https://paste.md-5.net/ofanafazit

### Server Log

https://mcpaste.io/b953ec9e47b3439d

**Comment by Awpmeister2170** [comment]
Fixed for the next update
