### ISSUE TITLE
TP_DROPS enchantments not giving mcMMO EXP

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3023]
### Describe the bug

When breaking blocks with a TP_DROPS enchantment tool, no mcMMO EXP is rewarded for the corresponding skill.

### How to reproduce

Have mcMMO installed.
Enchant a tool with a TP_DROPS enchantment.
Break a block that would normally give mcMMO EXP.
No EXP is earned.

### "/ae plinfo" link

https://paste.md-5.net/ovadakofev

**Comment by Awpmeister2170** [comment]
Fixed for next update
