### ISSUE TITLE
Problem with Telepathy / TP_DROPS effect

### ISSUE THREAD

**Issue by OGreenC** [GC-spigot/AdvancedEnchantments#3024]
### Describe the bug

I'm having problems with the telepathy enchant (puts broken blocks directly into the inventory) in combination with other plugins such as advancedAchievements & QuestCreator, as items broken with a tool with the telepathy enchant is not registered in these plugins. I'm thinking this could be related to #3017 with events not being registered by other plugins?

### How to reproduce

Download a plugin, such as advancedAchievements, which relies on the block break event, and break a block with a tool with a enchant with TP_DROPS effect on. 

The plugin will not register this block-break event, as I assume you´re cancelling the event.

### "/ae plinfo" link

https://paste.md-5.net/izotukozal

**Comment by reussy** [comment]
Hi, please update the plugin and try again.
I just fixed the related issues, but I'm not sure if this can be fixed with those changes.

If updating the plugin doesn't work, then wait for the next update.

**Comment by Awpmeister2170** [comment]
Any Update @OGreenC

**Comment by OGreenC** [comment]
Hi, 

Sorry for the late respons - I've had a busy week.

I've now had a chance to test the newest version of the plugin ( https://paste.md-5.net/zokeworufi ), but unfortunately the problem still persists.

More specifically, I tested by destroying a block with a tool with the telepathy enchant applied, without it being registered in AdvancedAchievements.

**Comment by austv** [comment]
@Awpmeister2170 @reussy Hello, any updates on this?

We are waiting this updates related to TP_DROPS, you can also look at this issues? 
https://github.com/GC-spigot/AdvancedEnchantments/issues/2999
https://github.com/GC-spigot/AdvancedEnchantments/issues/3023
https://github.com/GC-spigot/AdvancedEnchantments/issues/3025

They all talking about the same problem

**Comment by Awpmeister2170** [comment]
Hello @austv  Work is underway on all the issues MCMMO is pretty complex so it may take some time to come up with a solution on some of these issues

**Comment by OGreenC** [comment]
Hi, I´m sorry for being inpatient, but I'm now have multiple open tickets, with problems all boiling down to this particular problem in the end.

Are there any updates?

**Comment by reussy** [comment]
> Hi, I´m sorry for being inpatient, but I'm now having multiple open tickets, with problems all boiling down to this particular problem in the end.
> 
> Are there any updates?

Hey man, sorry for the wait! I'm looking into this topic (TP_DROPS issues).
I noticed that AdvancedAchievements can be compiled but it gives a lot of errors and I can't fix it, is it possible to share your .jar to my private to use it?

Regards

**Comment by reussy** [comment]
I have also noticed that with Quest Creator I haven't problems, the Block Break missions can be completed with the TP_DROPS effect. @OGreenC

**Comment by OGreenC** [comment]
Hi @reussy, I've contacted you via Discord, regarding the Jar you requested of AdvancedAchievements.

Regarding QuestCreator, I realized, that only a limited set of the quests where affected, all of which includes breaking some blocks with custom drop handling, handled by a custom plugin of ours. 

I´ll have one of my developers look into this particular problem.

Another problem we're experiencing, and which some malicious players are sadly beginning to pick up on, are a problem with island levels in SuperiorSkyblock and the telepathy command, more precisely levels are not removed from an island, when removed with a tool with Telepathy on it.

I took a small GIF of the issue: https://gyazo.com/471896ec4f917e792a5307053d9c1ef3
The diamond pickaxe has telepathy, the gold pickaxe does not. The island level can be seen in the scoreboard to the right.

**Comment by reussy** [comment]
Well, regarding the problem with AdvancedAchievements, it works perfect, the achievements of breaking blocks are being completed normally, I attach screenshots.

Regarding the SuperiorSkyblock problem, I will try to find a way to fix it!

![image](https://user-images.githubusercontent.com/63428864/194741380-da842f13-3472-4aac-bc77-f9abadcbc623.png)
![image](https://user-images.githubusercontent.com/63428864/194741384-be66ae61-3948-4936-8884-e9b14b6560bd.png)

**Comment by OGreenC** [comment]
Hi @reussy 

I tried to install AdvancedEnchantments & AdvancedAchievements on a seperate test server, with only these 2 plugins installed, and the problem is unfortunally still there on my end.

When advancedachievement is initially installed, it comes with a achievement where you have to break 1 stone block - This is the achievement you see me complete in the  GIF below.

The enchanted pickaxe only has telepathy 1 (which I configured to work 100% of the time) and the unenchanted does not.
I do not complete the achievement, when breaking the block with telepathy.
https://gyazo.com/f14f2cd2f77751e15831261690866600

![image](https://user-images.githubusercontent.com/46462998/194758126-071eca41-3fbe-4e3c-8b75-a55840a0db06.png)
![image](https://user-images.githubusercontent.com/46462998/194758130-5a2d6f31-a386-4649-9c2c-4b99bce6b14c.png)
![image](https://user-images.githubusercontent.com/46462998/194758150-b2d182d2-4ca0-4f70-9f38-d90d8b4e0616.png)

Plugin info for refference: https://paste.md-5.net/uwufewoxar

**Comment by OGreenC** [comment]
Looking back, I can now see, that it does indeed work for ice, as you tested it to.

When I have tested it, I must have mainly been testing it with blocks that didn´t drop as it self, but rather as some other items, when broken without silktouch, such as stone or glowstone.

Is there any way to fix this?

**Comment by Awpmeister2170** [comment]
Fixed for next update

**Comment by OGreenC** [comment]
2 blocks are removed from SuperiorSkyblock islands now, whenever a block is removed with a tool with telepathy.

This is obviously causing havoc, as players are able to circumvent limits.

You can see how many of each block are registered for a island, by using '/island counts' while on your island.

**Comment by reussy** [comment]
> 2 blocks are removed from SuperiorSkyblock islands now, whenever a block is removed with a tool with telepathy.
> 
> This is obviously causing havoc, as players are able to circumvent limits.
> 
> You can see how many of each block are registered for a island, by using '/island counts' while on your island.

You're right, I forgot this... Fixed next update
