### ISSUE TITLE
TP_DROPS doesen't work properly.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3025]
### Describe the bug

when player break block with fast speed (crops), TP DROPS not worked.
i posted serveral issue about TP_DOPRS, MORE_DROPS but why not check this issue? just unconfirmed.
i wasted about many time to report bug. this plugin is not beta right?

### How to reproduce

.

### Screenshots / Videos

https://youtu.be/yxmskLTL8vU

### "/ae plinfo" link

https://paste.md-5.net/kugemafuri

**Comment by Awpmeister2170** [comment]
Hello, We think you have posted the Wrong Video? could you explain more about the issue

**Comment by Freshtana** [comment]
Same issue here, I already reported too.
