### ISSUE TITLE
Restore enchantment (REMOVE_ENCHANT) printing an 

### ISSUE THREAD

**Issue by TonyMontero** [GC-spigot/AdvancedEnchantments#3026]
### Describe the bug

When triggering the Restore enchantment (default), it prints me an error and don't make his point.

### How to reproduce

Just use the enchantment on a pickaxe and let the fun begin

### Screenshots / Videos

https://i.imgur.com/qqnFVs0.png

### "/ae plinfo" link

https://paste.md-5.net/qilaqofesa

### Server Log

https://mcpaste.io/f7525f8f35c00696

**Comment by TonyMontero** [comment]
Adding information, REMOVE_ENCHANTMENT works well when used on "Soulbound", so it's merely on that enchantment.

Enchantment config:
https://mcpaste.io/4df74200f5027bd6

**Comment by reussy** [comment]
Hi @TonyMontero 👋

Please upgrade to the latest version and let us know if your issue is fixed, on my side your enchantment works perfectly.

**Comment by TonyMontero** [comment]
Gonna try the following days and telling you how it went :)

**Comment by reussy** [comment]
@TonyMontero how did everything go, has your problem been solved?

**Comment by reussy** [comment]
@Awpmeister2170 there seems to be no answer...

**Comment by Awpmeister2170** [comment]
Closing due to lack of response

**Comment by TonyMontero** [comment]
> @TonyMontero how did everything go, has your problem been solved?

Yeah, sorry, I got a lot of problems with my internet and today I got a chance to be back. Solved!
