### ISSUE TITLE
Poisonous potatoes no appear when harvesting potatoes with a pickaxe with the Smelting enchant applied

### ISSUE THREAD

**Issue by Sangnamja123** [GC-spigot/AdvancedEnchantments#3028]
### Describe the bug

Poisonous potatoes no appear when harvesting potatoes with a pickaxe with the Smelting enchant applied

### How to reproduce

when break potatoes crop with a pickaxe with the Smelting enchant applied

### "/ae plinfo" link

https://paste.md-5.net/yiximesuju

**Comment by GC-spigot** [comment]
Thanks will fix
