### ISSUE TITLE
Durability effects do not work

### ISSUE THREAD

**Issue by sudokou** [GC-spigot/AdvancedEnchantments#3031]
### Describe the bug

Using any of the durability effects (ADD_DURABILITY, ADD_DURABILITY_CURRENT_ITEM) doesn't seem to have any effect.
Tried on a sword enchant as well as a boots enchant - could not get durability to be affected in either instance.

### How to reproduce

Create enchant with effect: ADD_DURABILITY:-300
Use item
Neither armor, nor the item itself, have durability affected in any way.

### "/ae plinfo" link

https://paste.md-5.net/wamalerife

**Comment by SirJben** [comment]
Hello @bdagenais2 turn on your debug mode and check if the enchantment is activating and try this in the latest version of the PL.
