### ISSUE TITLE
Tools that apply smelting enchant do not drop experience

### ISSUE THREAD

**Issue by Sangnamja123** [GC-spigot/AdvancedEnchantments#3032]
### Describe the bug

Tools that apply smelting enchant do not drop experience

ex: If coal or diamond is mined with a pickaxe applied with smelting incentives, the experience is not dropped.

### How to reproduce

pickaxe applied with smelting

### "/ae plinfo" link

https://paste.md-5.net/oticehovuq

**Comment by Awpmeister2170** [comment]
Fixed in next update
