### ISSUE TITLE
Issue with <aoe> and add_harm

### ISSUE THREAD

**Issue by CrystallizedAtrophy** [GC-spigot/AdvancedEnchantments#3033]
### Describe the bug

<aoe> doesn't work with ADD_HARM effect.

rendingedge:
  display: '%group-color%Rending Edge'
  description: "Chance to deals up to 8 damage in up to a 4 block radius.\nRequires Sweeping Strike 4 to apply."
  applies-to: 'Swords, Axes, Tridents'
  type: 'ATTACK;ATTACK_MOB;TRIDENT_THROW'
  group: 'HEROIC'
  settings:
    required-enchants:
      - 'sweepingstrike:4'
    removed-enchants:
      - 'sweepingstrike'
    removeable: true
  applies:
    - ALL_AXE
    - ALL_SWORD
    - ALL_TRIDENT
  levels:
    1:
      chance: 4
      cooldown: 12
      effects:
        - 'ADD_HARM:<random number>1-8</random number> <aoe> radius=1 target=damageable </aoe>'
        - 'ADD_HARM:<random number>1-8</random number> <aoe> radius=1 target=mobs </aoe>'
        - 'MESSAGE:&d&l** RENDING EDGE &7(%attacker name%)&d&l ** <aoe> radius=1 target=damageable </aoe>'
    2:
      chance: 5
      cooldown: 13
      effects:
        - 'ADD_HARM:<random number>2-8</random number> <aoe> radius=2 target=damageable </aoe>'
        - 'ADD_HARM:<random number>2-8</random number> <aoe> radius=2 target=mobs </aoe>'
        - 'MESSAGE:&d&l** RENDING EDGE &7(%attacker name%)&d&l ** <aoe> radius=2 target=damageable </aoe>'
    3:
      chance: 7
      cooldown: 14
      effects:
        - 'ADD_HARM:<random number>3-8</random number> <aoe> radius=3 target=damageable </aoe>'
        - 'ADD_HARM:<random number>3-8</random number> <aoe> radius=3 target=mobs </aoe>'
        - 'MESSAGE:&d&l** RENDING EDGE &7(%attacker name%)&d&l ** <aoe> radius=3 target=damageable </aoe>'
    4:
      chance: 100
      cooldown: 0
      effects:
        - 'ADD_HARM:<random number>5-8</random number> <aoe> radius=4 target=damageable </aoe>'
        - 'ADD_HARM:<random number>5-8</random number> <aoe> radius=4 target=mobs </aoe>'
        - 'MESSAGE:&d&l** RENDING EDGE &7(%attacker name%)&d&l ** <aoe> radius=4 target=damageable </aoe>'  

### How to reproduce

Use ADD_HARM with <aoe>.

### Screenshots / Videos

https://www.youtube.com/watch?v=1kl2gOlhil8

### "/ae plinfo" link

https://paste.md-5.net/arugivohih

### Server Log

N/A

**Comment by reussy** [comment]
Hello @CrystallizedAtrophy 👋

You are missing to encapsulate the arguments with <aoe></aoe>.
**Example**: `ADD_HARM:<random number>1-3</random number> <aoe> radius=1 target=damageable </aoe>`.

See for reference: [Radius of Effect enchantments](https://ae.advancedplugins.net/enchantments/radius-of-effect-enchantments)

**Comment by CrystallizedAtrophy** [comment]
Ah looks like I posted from where I was messing with it trying to get it to work again. 
This should be the original that wasn't working 
![unknown-43](https://user-images.githubusercontent.com/64324575/191077166-b7ab1efd-08d4-4999-bd71-ca753c9a98bb.png)

**Comment by CrystallizedAtrophy** [comment]
> Hello @CrystallizedAtrophy 👋
> 
> You are missing to encapsulate the arguments with `<aoe></aoe>`. **Example**: `ADD_HARM:<random number>1-3</random number> <aoe> radius=1 target=damageable </aoe>`.
> 
> See for reference: [Radius of Effect enchantments](https://ae.advancedplugins.net/enchantments/radius-of-effect-enchantments)

https://gyazo.com/b67716092293efed22b8d12f25c23a08 looks like I did have it, it didn't seem to copy or post on github. Just got home to check ptero and it was showing <aoe>

**Comment by GC-spigot** [comment]
Can you post your enchant using code tags?

**Comment by reussy** [comment]
Heey @CrystallizedAtrophy 👋

We've recently updated and fixed many bugs, could you confirm if this still happens in the latest versions?

**Comment by CrystallizedAtrophy** [comment]
> Heey @CrystallizedAtrophy 👋
> 
> We've recently updated and fixed many bugs, could you confirm if this still happens in the latest versions?

It does seem to be working now with a extra bonus to it. For some reason its causing hostile mobs to attack one in the group.
