### ISSUE TITLE
Not getting paid from Jobs Reborn with effects SMELT and TP_DROPS

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#3035]
### Describe the bug

Mining with a tool (the kind of tool doesn't matter, applies to axe, pickaxe, etc.) that has Telepathy or Smelting doesn't pay in Jobs Reborn. This has been fixed in the past, but seems to have been broken again in a recent version of the plugin. See #1361 #1772 etc.

### How to reproduce

NOTE: This can be done with pickaxe for Miner job, shovel for Digger job, axe for Woodcutter job. The type of tool doesn't matter, the problem point seems to be Telepathy or Smelting.

1.) Install CMILib, Jobs Reborn, Vault, and EssentialsX
2.) Hold an axe
3.) /ae enchant telepathy 4
4.) /jobs join woodcutter
5.) Find a tree and chop some logs with the aforementioned axe
6.) Wait a few moments and see that your balance hasn't increased with /bal
7.) You can chop some logs with an unenchanted axe to see that you do get paid and that the issue lies with Telepathy

### "/ae plinfo" link

https://paste.md-5.net/esucuzaqof

**Comment by Mdsh9** [comment]
Same error.

**Comment by ItzKomplicated** [comment]
We're having the same issue on our server

**Comment by botboy0** [comment]
Same

**Comment by Gfieldd** [comment]
we are having the same error as well
