### ISSUE TITLE
Chestplate is being replaced with chest when placing a chest on the ground and the chestplate will get deleted

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#3037]
### Describe the bug

When you craft and place a chest on the ground using right click, the chest will be placed and a copy of it go to your chestplate slot, like you would wear a chest box, your original chestplate will be deleted "cause me lot of labor work restoring everyone inventories"

this happens on AE 8.15.3 and I have the cosmic pvp setup.

I think this is to some event of wearing a chest, but instead, you guys forgot to actually add PLATE at the end when coding.

I would never know.

But I really beg you to start a development channel where you release updates and only release stable versions in spigotmc when the plugin is stable enough.

### How to reproduce

Wear any diamond or netherite chestplate, craft a chet than place it on the ground, your chestplate will be replaced with a regular chest, and the chest you placed will have the name of your chestplate if it have a name.

You should not be OP and should not have * permission, this only happens to regular players.

### "/ae plinfo" link

https://paste.md-5.net/edefehokuy - PLEASE ignore AE version on the AE plinfo as I reverted back to the good version

### Server Log

not really needed you know whats wrong already

**Comment by Awpmeister2170** [comment]
Hello remove this from your files and it should work fine for you.
![FF805070-A51D-4B49-9A43-F220A74A75D3](https://user-images.githubusercontent.com/45782230/191581480-bde460a3-a3a7-4f52-8e23-4deac8ce9ccb.jpeg)

**Comment by Awpmeister2170** [comment]
Fixed for next update
