### ISSUE TITLE
Internal Error on /aegive with custom enchants

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3038]
### Describe the bug

When I use /aegive to give a player an item with a custom enchant specified, an error is thrown and the item is not given. The same command works fine when the custom enchant is not specified.

Log: https://pastebin.com/kdQuLk2M

### How to reproduce

/aegive yourself an item with a custom enchant
Error is thrown, item is not received

### "/ae plinfo" link

https://paste.md-5.net/suvuvuloqi

**Comment by GC-spigot** [comment]
Update your plugin and restart, seems like some things are missing internally
