### ISSUE TITLE
Repairing enchanted tools in anvil removes glow

### ISSUE THREAD

**Issue by TheRealPandaa** [GC-spigot/AdvancedEnchantments#3039]
### Describe the bug

I have enchanted a tool with, lets say, Inferno 3. When enchanted, there is the usual glow from enchanted tools.
When repairing that tool in an anvil, it removes the glow of the repaired tool.

Looked into the configs, haven't really found a setting there, so believe its a bug?

### How to reproduce

Enchant a tool, dmg it a bit, repair it in an anvil.

### Screenshots / Videos

https://prnt.sc/OX4FarhKvrrz
https://prnt.sc/c_9tl7cCXOiV
https://prnt.sc/WwF-WyKfEVtP
https://prnt.sc/rcFVrnxy4t-N

### "/ae plinfo" link

https://paste.md-5.net/tumoceyumu

**Comment by Awpmeister2170** [comment]
Fixed for next update
