### ISSUE TITLE
TP_DROPS effect door / Flower dupe

### ISSUE THREAD

**Issue by OGreenC** [GC-spigot/AdvancedEnchantments#3040]
### Describe the bug

Doors / 2 high flowers (and all other 2 high blocks, if any, I would imagine) are duping when the upper part of the block are broken with a tool with TP_DROPS effect on it.

Please see the video below.

https://medal.tv/games/minecraft/clips/AobcXcQT1Fv1l/d1337VkH90po?invite=cr-MSwzV0ksMjgxODQyODUs

### How to reproduce

https://medal.tv/games/minecraft/clips/AobcXcQT1Fv1l/d1337VkH90po?invite=cr-MSwzV0ksMjgxODQyODUs

### "/ae plinfo" link

https://paste.md-5.net/makigizaro

**Comment by Awpmeister2170** [comment]
Fixed for next update
