### ISSUE TITLE
/asets losing the itemsadder nbt on sets and loses armor textures

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#3041]
### Describe the bug

Itemsadder added AdvancedEnchantment compatibility, but AdvancedEnchantment needs to add compatibility for custom sets.

Agaloth — 01/06/2022
yo lone
I see that you released the full update for 2.5.2 on spigot.
was the AE bug I reported meant to be for 2.5.2 or another version
(the nbt bug on ae with /asets)

~LoneDev ⛔ NO PRIVATE MESSAGES — 01/06/2022
Do you mean a fix?
I don't have a fix for that bug
it must be fixed on AE code, not IA code
Apparently, the NBT tag bug has to be fixed by AE, he added support for AE on itemsadder but it doesn't fix the NBT tag issue with the armors with /asets

### How to reproduce

1)Make a custom armor with itemsadder
2) Use AdvancedEnchantment to create a set with the custom model data ;
3) Give yourself the armor and see error.

### Screenshots / Videos

https://imgur.com/a/vRRqdnj

As you can see the helmet was given with itemsadder (/iagive ...) and the other armor parts were with /asets and lost their textures.

### "/ae plinfo" link

https://paste.md-5.net/gunoquyaqo

**Comment by Agaloth** [comment]
This has been an issue since January 13th

**Comment by Agaloth** [comment]
0 = itemsadder's `/iagive` armor

1 = AdvancedEnchantment's `/asets give` armor

![image](https://user-images.githubusercontent.com/33335971/192127107-f2a55213-7f19-46c5-b62b-8d5d96b6f26d.png)

**Comment by reussy** [comment]
Hey @Agaloth 

I'm a bit confused. I have no way to test this since I'm not an ItemsAdder buyer.

In the screenshot you showed, you say they lose their textures, but I see the textures applied to each armor or what exactly are you referring to.  In addition to this, what does the ArmorSet configuration look like?

**Comment by Agaloth** [comment]
> Hey @Agaloth
> 
> I'm a bit confused. I have no way to test this since I'm not an ItemsAdder buyer.
> 
> In the screenshot you showed, you say they lose their textures, but I see the textures applied to each armor or what exactly are you referring to. In addition to this, what does the ArmorSet configuration look like?

![image](https://user-images.githubusercontent.com/33335971/196019189-51a200d6-fc78-467c-8167-1bf47cbe0f61.png)

As you can see, the helmet isn't given with /asets but with itemsadder's /iagive command and this one shows the custom texture on the player and the other armor parts with /asets shows as netherite armor

This is the ArmorSet config: https://pastebin.com/qA3FhaMC

**Comment by reussy** [comment]
> > Hey @Agaloth
> > I'm a bit confused. I have no way to test this since I'm not an ItemsAdder buyer.
> > In the screenshot you showed, you say they lose their textures, but I see the textures applied to each armor or what exactly are you referring to. In addition to this, what does the ArmorSet configuration look like?
> 
> ![image](https://user-images.githubusercontent.com/33335971/196019189-51a200d6-fc78-467c-8167-1bf47cbe0f61.png)
> 
> As you can see, the helmet isn't given with /asets but with itemsadder's /iagive command and this one shows the custom texture on the player and the other armor parts with /asets shows as netherite armor
> 
> This is the ArmorSet config: https://pastebin.com/qA3FhaMC

Wow, I hadn't noticed that.... Thanks for replying, will check it out!
