### ISSUE TITLE
duplicated enchantments and cant remove it | HEX COLOR PROBLEM ⚠

### ISSUE THREAD

**Issue by SNokerYT** [GC-spigot/AdvancedEnchantments#3042]
### Describe the bug

https://github.com/GC-spigot/AdvancedEnchantments/issues/2225

### How to reproduce

.

### Screenshots / Videos

.

### "/ae plinfo" link

.

### Server Log

.

**Comment by SirJben** [comment]
Hello please provide details of your issue such as informations and screenshots that will help our devs to reproduce your issue.

**Comment by Awpmeister2170** [comment]
Fixed for the next update
