### ISSUE TITLE
Block Duplication with BREAK_TREE and TP_DROPS

### ISSUE THREAD

**Issue by OrangeCat555** [GC-spigot/AdvancedEnchantments#3043]
### Describe the bug

When the two enchants are combined on the same tool there is a chance that any block mined other than wood gets duplicated.

### How to reproduce

Place both enchants on the same item and mine any block (duplicates shulkers, dirt, beacons, etc.) it will occasionally drop the block whilst also teleporting it to the player's inventory.

### "/ae plinfo" link

https://paste.md-5.net/wesidiwaci

**Comment by OrangeCat555** [comment]
Yeah that's the one, good to have a video showing it. We have a lot of stuff with TP_DROPS so we went the other way and disabled anything with BREAK_TREE temporarily.

*Didn't mean to close and reopen my bad*

**Comment by Awpmeister2170** [comment]
Fixed for next update
