### ISSUE TITLE
examine-book: in locale and applies-to: in enchantment.yml not displaying correctly 

### ISSUE THREAD

**Issue by clarkkentz** [GC-spigot/AdvancedEnchantments#3045]
### Describe the bug

%group-name% in examine-book: from locale not display the group name. 
applies-to: in enchantment.yml not display the value I set.

### How to reproduce

just change value in `applies-to:` to anything else and it will stay the same

### "/ae plinfo" link

https://paste.md-5.net/yexuyasiya

**Comment by GC-spigot** [comment]
Fixed
