### ISSUE TITLE
Golden boots do not apply enchant effects

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#3049]
### Describe the bug

You can apply an enchant (like springs or gears) to golden_boots, but when you equip the item on your character, no effects are applied. Applying the same enchant to another set of boots like diamond_boots, works with no issues.

### How to reproduce

Get GOLDEN_BOOTS
Apply springs enchant (/ae enchant springs 3)
Equip boots
Try to jump

### "/ae plinfo" link

https://paste.md-5.net/uteqoxuqop

**Comment by Awpmeister2170** [comment]
https://gyazo.com/c9e36e33e1d68d0cc435eb6605356794

Works fine for me i jump higher with them,  could you send your console logs please.

**Comment by bdagenais2** [comment]
Yes, here's a video - https://www.youtube.com/watch?v=Zw9_gkKCo_8

**Comment by reussy** [comment]
Hello @bdagenais2 
Please add "GOLDEN_BOOTS" to the list of boots. You can find it by searching for "armor-items".

Also, a patch for this will be added in future updates, thank you!

Example:
![image](https://user-images.githubusercontent.com/63428864/194776384-ead4c1b0-359c-466d-a59f-e7ba035a118c.png)
