### ISSUE TITLE
Unbreakable enchantment duplication bug

### ISSUE THREAD

**Issue by DrakMC** [GC-spigot/AdvancedEnchantments#3050]
### Describe the bug

Armor can be duplicated by the unbreakable enchantment

### How to reproduce

1. Put on a chestplate with unbreakable enchantment
2. Get hit by, for example, a zombie
3. A duplicate item appears in your leggings slot.

### "/ae plinfo" link

https://paste.md-5.net/efusapiniv

**Comment by Awpmeister2170** [comment]
Fixed next update
