### ISSUE TITLE
Dupe Glitch with Alchemist

### ISSUE THREAD

**Issue by Truongvv10** [GC-spigot/AdvancedEnchantments#3051]
### Describe the bug

Duping glitch after updating AE to version 9.0.0b1 where alchemist completely got reworked.

### How to reproduce

You can dupe when 2 or mulitple players are in alchemist at the same time. When person A is combining their books, the other person (b) can see the books that are being combined by person (A). Person (B) can just combine the books from person (A) and person (A) exits the gui and get their books refunded

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/67742370/193577347-c483a85c-cd57-4097-9368-608fe81b1fd7.png)

### "/ae plinfo" link

https://paste.md-5.net/aseberideg

### Server Log

https://mcpaste.io/a797039c3181c15d

**Comment by Awpmeister2170** [comment]
Fixed for next update
