### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by SirCraftypants** [GC-spigot/AdvancedEnchantments#3052]
### Describe the bug

I gave myself a diamond pickaxe and got a nullpointerexception error.

### How to reproduce

use the /give command to give yourself a tool.

### "/ae plinfo" link

https://paste.md-5.net/obalulayug

### Server Log

https://mcpaste.io/6c6fd509fb506cf8

**Comment by reussy** [comment]
Heey @SirCraftypants 👋

This is probably a configuration error or some missing path, please perform a backup, update the plugin, regenerate all files and see if the error persists. In case it is fixed, you can use your backup to replace everything.

**Comment by Awpmeister2170** [comment]
Closing due to no response, Please reopen a new report if doing what Reussy has stated above does not work for you

**Comment by SirCraftypants** [comment]
> Closing due to no response, Please reopen a new report if doing what Reussy has stated above does not work for you

No need, after updating a few time it seems to have fixed it.

**Comment by Awpmeister2170** [comment]
Brilliant news! Take care of yourself :)
