### ISSUE TITLE
There are problems with Enchant 'Flight'

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3053]
### Describe the bug

There is a rather old bug that we can’t get rid of for a long time, if a player playing with bedrock puts on boots with the enchant "flight" and teleports somewhere and then takes off his boots, and again does /rtp, then he can constantly fly without boots already!
(P.s Please don't ask me to upgrade!! Pre-builds are coming out now, and I'm afraid of bugs. But I downloaded and installed the latest version on the test server and this bug works great there!!)
21.10.2022: AdvancedEnchantments 9.0.0b19 (The bug is still working!!!)

### How to reproduce

1. Put on your flight boots.
2. Start flying.
3. Example: you are in the End, so you have to teleport to spawn or to hell or to a simple world or so on.
4. Start flying after the teleport from point 2.
5. Take off your shoes (in the same world) from point 2.
6. Example: you are in hell, so you need to teleport either to spawn or to a simple world. (p.s after completing the steps above)
7. can fly (without sneakers for flight)

### Screenshots / Videos

https://youtu.be/Q6bFK3ZOFw4
https://youtu.be/UE35pas5yYc

### "/ae plinfo" link

https://paste.md-5.net/ezonesovek

### Server Log

https://mcpaste.io/f5ae30e2b57ab575

**Comment by Awpmeister2170** [comment]
Duped report ( https://github.com/GC-spigot/AdvancedEnchantments/issues/3064 )
