### ISSUE TITLE
Telepathy enchantment does not seem to trigger the fact you mined a block, especially with McMMO!

### ISSUE THREAD

**Issue by RMF-AndyPlayz** [GC-spigot/AdvancedEnchantments#3054]
### Describe the bug

I'm not sure if this is a bug with Advanced Enchantments, or with [McMMO](https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/), so I'm going to put this here in case it is an issue with this plugin! So basically, the Telepathy command does not seem trigger other plugins' break reception. For example, I could mine a stone block with a pickaxe that has Telepathy IV enchanted on it, and it would grant me no Mining XP from McMMO. However, it would work fine if I were to put Trench on it, either have it be the only enchantment or even paired with Telepathy! So basically, telepathy does not work when it's on its own.

The problem I'm potentially seeing is that telepathy on its own does not tell the server that "Hey! This player mined this block!" which means, no other plugins can detect this modification, which means they cannot properly update the player's stats.

And again, this may be a McMMO problem and I might need to report to them instead. But just in case it is something with this plugin, please do take a look at it! (And potentially fix it! :D)

### How to reproduce

Quite simple!
- Install some sort of skills plugin like McMMO
- Put telepathy on any pickaxe or tool
- Mine a block appropriate to the tool you put telepathy on (i.e. telepathy pickaxe mining stone)
- You will notice that you will not gain Mining XP

### Screenshots / Videos

https://user-images.githubusercontent.com/58617083/194226860-858e4346-134f-41b3-9a2f-47fb6d09aba0.mp4

### "/ae plinfo" link

https://paste.md-5.net/ozezabozis

**Comment by Awpmeister2170** [comment]
Fixed for next update
