### ISSUE TITLE
Telepathy enchantment error (silk touch) (version: 1.12.2)

### ISSUE THREAD

**Issue by Sangnamja123** [GC-spigot/AdvancedEnchantments#3055]
### Describe the bug

Tools with silk touch enchant do disappear or doesn't drop all crop items except watermelons and pumpkins when harvesting crops through telepathy enchant.

### How to reproduce

An error occurs when crops are harvested using tools that apply both silk touch minecraft enchant and telepathy custom enchant.

### "/ae plinfo" link

https://paste.md-5.net/eluwirigeg

**Comment by Awpmeister2170** [comment]
Fixed for next update
