### ISSUE TITLE
Bug 2 or more players have the Alchemist window open

### ISSUE THREAD

**Issue by astridcloud** [GC-spigot/AdvancedEnchantments#3056]
### Describe the bug

When 2 or more players have the Alchemist window open and one of the players  input a CE book/dust, the CE book/dust will also pop up in other players Alchemist screen. And when the other players exit the Alchemist screen, the CE book/dust will get duplicated into their inventory. This bug happens when the players are anywhere, even when they are in different dimensions (overworld/nether).

### How to reproduce

-Have 2 or more players open the Alchemist screen
-Have one of the players put in a CE book or dust
-The CE book or dust will pop up in other player's Alchemist screen

### "/ae plinfo" link

https://paste.md-5.net/pewofikeco

**Comment by reussy** [comment]
Hey @astridcloud
From my side I can't reproduce this, you may be able to record a video to have more information. Additionally, it would be better if you run "/ae plinfo" without the **skipPlugins** argument.

![image](https://user-images.githubusercontent.com/63428864/194738383-6685cb69-f5b3-4922-b7e5-84fdb071d08d.png)

**Comment by Awpmeister2170** [comment]
Fixed for next update
