### ISSUE TITLE
Telepathy doesn't work on Quest.

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#3058]
### Describe the bug

The Telepathy enchantments refuse to add +1 to each block/crop harvested.

### How to reproduce

Add Telepathy, of any level, to an item and harvest crops with it / mine blocks with it for your quest.

Create applicable quest using [Quests](https://www.spigotmc.org/resources/quests-1-8-1-19-set-up-goals-for-players.23696/)!

### Screenshots / Videos

https://youtu.be/RdDh2lMRIhA

### "/ae plinfo" link

https://paste.md-5.net/ofipemupix

### Server Log

Ill add this in a few, need to wait for server restart, the mcpaste isn't generating me a link cause the log is too long.

**Comment by ClickErrorxD** [comment]
Here is my start up log. https://mcpaste.io/6488959f227d724b

**Comment by Awpmeister2170** [comment]
Fixed
