### ISSUE TITLE
Permission ae.help

### ISSUE THREAD

**Issue by Golicraft** [GC-spigot/AdvancedEnchantments#3059]
### Describe the bug

I negate the permission ae.help on a user / rank and when we still do /ae it shows the help commands and everything. 

### How to reproduce

Do /ae on an account with zero permissions. 
Add permission -ae.help or "ae.help false" with Luckperms 
Try again

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/11066952/195216373-b8e60c51-ef27-41f7-a3bf-b8bf84a4ff5a.png)

### "/ae plinfo" link

https://paste.md-5.net/vavuheveqa

### Server Log

Not necessary.

**Comment by Awpmeister2170** [comment]
Fixed for next update
