### ISSUE TITLE
RIGHT_CLICK_BLOCK HAND

### ISSUE THREAD

**Issue by Distoupia** [GC-spigot/AdvancedEnchantments#3061]
### Describe the bug

Today I update AE to the last version. but this bring too many problems, one of those, the title, this spam the chat when you right click in a block, chest, or right clicking things basically, planting and more stuffs, you can see the "RIGHT_CLICK_BLOCK HAND" yours and from anothers players in the same chat, until the console.

### How to reproduce

Just Right Click any block, chest, plant crops and will appear.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/106001914/195737556-7db9f019-60f0-4cc1-a255-19ff6e910d2f.png)

### "/ae plinfo" link

https://paste.md-5.net/mowaweyidi

### Server Log

https://mcpaste.io/bbbc6a4c04cbc94b

**Comment by PENKVIN** [comment]
Same problem

**Comment by MasonX3** [comment]
Exact same problem with 9.0.0b11. Had to roll back to prevent chat from being spammed.

**Comment by Awpmeister2170** [comment]
Fixed for next update

**Comment by BrandonT80** [comment]
Same problem
