### ISSUE TITLE
Error, wont startup on 1.8.8

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3063]
### Describe the bug

Plugin wont enable

### How to reproduce

Install on 1.8.8 server

### Screenshots / Videos

https://pastebin.com/bwa65kNT

### "/ae plinfo" link

Ae is disabled so no plinfo. but here's the server info: 1.8.8 Paper Fork ReliableSpigot, Plugins (10): FastAsyncWorldEdit, Essentials, EssentialsSpawn, EssentialsChat, ProtocolLib, AuthMe, WorldEdit, FastLogin, WildStacker, AdvancedEnchantments

### Server Log

https://mcpaste.io/7be7cd2e21384e05

**Comment by GC-spigot** [comment]
Downgrade until fixed, this is an issue with 1.8 version missing a featureOn 2022-10-14, at 12:54 PM, illudota ***@***.***> wrote:﻿
Describe the bug
Plugin wont enable
How to reproduce
Install on 1.8.8 server
Screenshots / Videos
https://pastebin.com/bwa65kNT
"/ae plinfo" link
Ae is disabled so no plinfo. but here's the server info: 1.8.8 Paper Fork ReliableSpigot, Plugins (10): FastAsyncWorldEdit, Essentials, EssentialsSpawn, EssentialsChat, ProtocolLib, AuthMe, WorldEdit, FastLogin, WildStacker, AdvancedEnchantments
Server Log
https://mcpaste.io/7be7cd2e21384e05

**Comment by Awpmeister2170** [comment]
Fixed for next update
