### ISSUE TITLE
The plugin loads the server

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3065]
### Describe the bug

I noticed that sometimes the plugin causes severe delays on my server

### How to reproduce

you will see it from the spark report

### Screenshots / Videos

https://spark.lucko.me/zysrTpHU80

### "/ae plinfo" link

https://paste.md-5.net/osiredavud

### Server Log

-

**Comment by Awpmeister2170** [comment]
Hello, we need some more information please send a timings report as no there are no other reports with this issue
