### ISSUE TITLE
Plugin overloads the server

### ISSUE THREAD

**Issue by cRestalious** [GC-spigot/AdvancedEnchantments#3066]
### Describe the bug

Sometimes the plugin just crash the server with the error listed bellow, I can get a full log due to the server rolling back aswell.

### How to reproduce

Randomly happens

### Screenshots / Videos

https://prnt.sc/xEWeNk71ttD3

### "/ae plinfo" link

https://paste.md-5.net/bawezacixe

### Server Log

it gets roll back can't get the file..

**Comment by Awpmeister2170** [comment]
update to latest version
