### ISSUE TITLE
Right-Click enchantment acting different in latest versions.

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3069]
### Describe the bug

Right-click type enchant used to be when you right-click, it activates enchant, now it doesn't, however you can still right-click activate the enchant, as long as your item is interacting with a block, before with just right-click, no matter if its in the air, it should still activate.

### How to reproduce

just make a right-click enchant and right-click on air / nothing, it will not work, but if you right click on a block, the enchant will work. videos shown below.

Try this enchant:
test:
  display: "%group-color%Test"
  description: 'Test'
  applies-to: 'Swords'
  type: 'RIGHT_CLICK'
  group: 'HEROIC'
  applies:
    - ALL_SWORD
  settings:
    removeable: false
  levels:
    '1':
      effects:
        - "PARTICLE:FLAME:50:1"
        - "MESSAGE:TEST"
        - 'PLAY_SOUND_OUTLOUD:ENDERDRAGON_GROWL'

### Screenshots / Videos

**NOTE: Videos are laggy due to bad OBS settings, was too lazy to record it again, but it's still clear to see what I mean in the video.**

Latest version(bug):
https://streamable.com/vrm2fk

Version(8.15.1)(normal, I was using this ver before I upgraded):
https://streamable.com/lcide2

### "/ae plinfo" link

https://paste.md-5.net/nuguxevoxa

### Server Log

https://mcpaste.io/be13c524f41fab83

**Comment by oORevanOo** [comment]
Can confirm this!

**Comment by Caprisito** [comment]
I can confirm that, Good Luck!

**Comment by Awpmeister2170** [comment]
Fixed for next update
