### ISSUE TITLE
[Bug] Issue with lore counter wiuth transmog

### ISSUE THREAD

**Issue by maxlehot1234** [GC-spigot/AdvancedEnchantments#307]
Hi, Is it normal to have thjis issue:

![image](https://user-images.githubusercontent.com/5159244/51794238-05f3f680-219c-11e9-88c8-4389104ac672.png)

I apply a transmog and it doesn't count vanilla enchants (fortune,  Efficiency, unbreaking, etc)

So it display 5 instead of 8.

Any way to fix this?

Thanks again

**Comment by GC-spigot** [comment]
It's not supposed to, it only counts custom enchantments.
