### ISSUE TITLE
Right tinkerer accept button not working

### ISSUE THREAD

**Issue by oORevanOo** [GC-spigot/AdvancedEnchantments#3073]
### Describe the bug

In latest versions, the right red glass pane in tinkerer does nothing. 
You can only accept the trade with the left pane

When left pane is clicked, the right pane also turns green, while still not doing anything if clicked.

### How to reproduce

Open tinkerer, input any book and click the right glass pane to accept the trade. Nothing will happen

### "/ae plinfo" link

https://paste.md-5.net/egawelitip

**Comment by reussy** [comment]
Hi @oORevanOo 

It's done on purpose, it's not a bug. The player shouldn't be able to accept from the Tinkerer's side (by default to the right), only from his side (by default to the left). Anyway, you can fully customize it in **tinkerer.yml**
