### ISSUE TITLE
Ability to duplicate items!!

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3074]
### Describe the bug

If you cast 4 enchant, "strike 2", "explosive 5", "piercing 4", "abiding 1" on the bow. Then if you shoot at a player or creature from it tightly and receive damage from the enchant "explosive 5", and die as a result of this action, then the bow falls out of you and also remains in your inventory and you can do this endlessly duplicating the bow !!

### How to reproduce

1) Apply the enchants described above to your bow.
2) Then put the mobs so that they do not beat you!
3) get close to the mobs and shoot them with a bow!
4) So that the enchant "explosive 5" damages you!
5) And do this until your life pool reaches 0.
6) As a result of which you die, this bow falls to you and also it remains with you!

### Screenshots / Videos

-

### "/ae plinfo" link

https://paste.md-5.net/fidojisege

### Server Log

-

**Comment by Awpmeister2170** [comment]
Fixed next update
