### ISSUE TITLE
Unable to configure different items for each tier of enchantment book

### ISSUE THREAD

**Issue by iLemon** [GC-spigot/AdvancedEnchantments#3075]
### Describe the bug

I hoped to configure a different item for each tier of enchantment-book. For example, a common enchantment book will have a white book texture, and a legendary enchantment book will have a red book texture.
 

### How to reproduce

n/a

### "/ae plinfo" link

n/a

**Comment by Awpmeister2170** [comment]
This should be possible in the latest updates
