### ISSUE TITLE
Tinkerer.yml not fully working

### ISSUE THREAD

**Issue by oORevanOo** [GC-spigot/AdvancedEnchantments#3077]
### Describe the bug

I've wrote an Issue earlier this week, about not being able to make both glass panes in tinkerer work as an accept button

however it seems like the tinkerer.yml does not even let me change the slot for the accept button
it also doesn't let me disable the confirmation screen, I have to click the accept button twice for it to progress the trade

here's my tinkerer.yml https://pastebin.com/w99Cq6ks
note: I've only set the slot to 8 and disabled the confirm screen

but it's ignoring both changes
Renaming works tho

### How to reproduce

set:

accept-trade-item:
   slot: "8" 
    
or try:
    
player-confirm-trade-item:
   enabled: false
    
    

### "/ae plinfo" link

AdvancedEnchantments-9.0.0b23

**Comment by reussy** [comment]
Hi @oORevanOo 

If you want to disable confirmation, set `enabled-confirm-items` to `false`.

On the other hand, my items are changing slots when modified. I recommend you to start carefully with the default tinkerer configuration and watch the modifications in the game using /ae reload.

**Comment by reussy** [comment]
By the way, I have made a fix for future changes to Tinkerer! 👌

**Comment by oORevanOo** [comment]
> Hi @oORevanOo
> 
> If you want to disable confirmation, set `enabled-confirm-items` to `false`.
> 
> On the other hand, my items are changing slots when modified. I recommend you to start carefully with the default tinkerer configuration and watch the modifications in the game using /ae reload.

enabled-confirm-items to false is working thanks!

**Comment by oORevanOo** [comment]
However it feels like the config is still a complete mess, I tried using a fresh generated one and it is still completely impossible to change items where they should be

I can move them by changing tinkerer-confirm-trade-item and player-confirm-trade-item
but for example tinkerer-confirm-trade-item can't be disabled, so theres 2 buttons everytime, both saying I hould click on them, while only one is working

tinkerer-confirm-trade-item and player-confirm-trade-item us the name of accept-trade-item and can't be individually translated, they both say the same everytime

neither can I just put them both on one slot and add slot 0 and 8 to player and tinkerers inventory, this just gives me an error
when both items are on one slot, I can accept the trade without offering anything and it gives me the glass pane


If you have time, try modifying the config, you can indeed change it, but it is not working at all if changed

**Comment by oORevanOo** [comment]
Just to reply

The new Version has the same issues
I can't add slot 0 to player's slot and 8 to tinkerer's, this just spams errors in console

I want 2 working buttons or just one in the middle
Both buttons say Accept and can't be individually translated

hope this gets a fix soon

**Comment by reussy** [comment]
> Just to reply
> 
> The new Version has the same issues I can't add slot 0 to player's slot and 8 to tinkerer's, this just spams errors in console
> 
> I want 2 working buttons or just one in the middle Both buttons say Accept and can't be individually translated
> 
> hope this gets a fix soon

Hello @oORevanOo 👋

The best thing is that you show the error, I can't understand what you mean that you can't add the slot 0 to the player slot, by default it comes like that and the same for the tinkerer.

On the other hand, the configuration is clear, you just have to know how to configure the file, I have no problem changing the slots. Please, if possible make a detailed report of the error or if possible, create a ticket in Discord to assist you in case it is not a plugin error but a configuration error.

Translated with www.DeepL.com/Translator (free version)

**Comment by oORevanOo** [comment]
I've created a config with notes, please thy accepting a trade with this.
Look for ##   those are my notes
https://pastebin.com/YxD33As3

it should error out in console but the config is correctly configured
https://pastebin.com/yBWBQsPU
change line 79: "slot: 13" to "slot: 0" then the config works, but this shouldn't even be needed as I added slot 0 to the
player-slots (line 14), so it should expect trade items in 0

**Comment by Awpmeister2170** [comment]
Fixed for next update :)
