### ISSUE TITLE
%applies% show does not match enchantments.yml

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#3078]
### Describe the bug

I set the value in enchantments.yml to unicode, but it doesn't change it as intended.

applies-to: "new word"

enchantment-book: %applies% in config.yml

### How to reproduce

-

### Screenshots / Videos

-

### "/ae plinfo" link

https://paste.md-5.net/owamecawun

### Server Log

-

**Comment by reussy** [comment]
Hello @uploadx10 

Use %applies-to% instead
