### ISSUE TITLE
Soulminer not working properly with Trench and Haste

### ISSUE THREAD

**Issue by redaroro31** [GC-spigot/AdvancedEnchantments#3079]
### Describe the bug

If you have Soulminer with Trench or Haste on a pickaxe sometimes its working and gave you the souls but sometimes not or its working for 10 min and after that stop working or I have seen pickaxe that can t take at all any souls. I have set the chance of  soulminer to 100 and enable debug mode and its says that the enchant is activated but don t add the souls. I don t get any errors in console when an enchant is activated.

### How to reproduce

Just enchant any pickaxe with soulminer trench or haste but this depends because i tested with 5 pickaxe with same enchants (soulminer and trench) and 3 of 5 pickaxe work properly but with a pickaxe at the start i mined 5-6 blocks and didnt work but after that no problem

### Screenshots / Videos

Here you can see that i mined some blocks and i get the souls from miningsoul setting in config, but the enchant is activating every time
https://prnt.sc/7dXDprSbpJsX

### "/ae plinfo" link

https://paste.md-5.net/yurixizuwi

**Comment by Awpmeister2170** [comment]
Fixed next update
