### ISSUE TITLE
Souls Enchants not working on weapons (Tested on  swords, axes and bows)

### ISSUE THREAD

**Issue by ZadeFear** [GC-spigot/AdvancedEnchantments#3080]
### Describe the bug

Using soul enchants on weapons causes console error. 

### How to reproduce

1. Get a soul enchant
2. Apply soul tracker to weapon
3. Apply soul gem to weapon
4. Use soul enchant

### Screenshots / Videos

https://pastebin.com/dJCu9tiz

### "/ae plinfo" link

https://paste.md-5.net/puzajaqoqi

**Comment by ZadeFear** [comment]
Forgot to mention that the enchants dont actually work. I just said they cause console error my bad.

**Comment by GBABHI** [comment]
I have a question for which version is this suitable ? Will this work in 1.19x

**Comment by Awpmeister2170** [comment]
Fixed for next update
