### ISSUE TITLE
Requested enchantments does give a diferent enchantment instead of the specified one.

### ISSUE THREAD

**Issue by Bop191** [GC-spigot/AdvancedEnchantments#3082]
### Describe the bug

Hey, when I execute the `/ae enchant blink 1` or the `/ae givebook blink 1 1 100 0` command, it does not enchant the item or book with *blink*, but it will enchant the item or book with *webster* instead.

### How to reproduce

Not sure exactly...
I think it could happen with any enchantment in the *enchantments.yml* file.

### Screenshots / Videos

https://prnt.sc/Vr_DrbM9BdMO

### "/ae plinfo" link

https://paste.md-5.net/aqamijerud

### Server Log

https://mcpaste.io/67a0b1f4f48e8d6f

**CONCLUSION**
Make sure the enchantment name is the same as the %group-color% name.

**Comment by reussy** [comment]
Hi @Bop191 

You could check if the enchantment is misconfigured in enchantments.yml, or if you prefer, attach enchantments.yml to help you.

**Comment by Bop191** [comment]
Here it is @reussy.
https://mcpaste.com/c8bc8465684afec5d77af9509202e028

**Comment by reussy** [comment]
> Here it is @reussy. https://mcpaste.com/c8bc8465684afec5d77af9509202e028

![image](https://user-images.githubusercontent.com/63428864/200721434-d0a3f938-f64d-42e4-a1b3-b4a16f9e20ba.png)
The name of the enchantment is Webster

**Comment by Bop191** [comment]
> > Here it is @reussy. https://mcpaste.com/c8bc8465684afec5d77af9509202e028
> 
> ![image](https://user-images.githubusercontent.com/63428864/200721434-d0a3f938-f64d-42e4-a1b3-b4a16f9e20ba.png) The name of the enchantment is Webster

But I specify it as Blink. How can I fix this problem?
