### ISSUE TITLE
The ability to duplicate tools was found!

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3084]
### Describe the bug

For this bug to work it is necessary to enchant "unbreakable"!
The bug only works thanks to Advanced Enchants, please fix it, it greatly spoils the economy of the server

### How to reproduce

To duplicate any items you need
1. AutoTool cheat.
2. Enchantment "unbreakable"
3. at least 7 efficiency
How to duplicate tools:
1. take any tool as in the video is a pickaxe
2. Put charms efficiency vanilla at least 7, and be sure!!! put unbreakable
After that turn on the cheat AutoTool, and start breaking 2 types of blocks, this type 1 where you need for rapid destruction hoe, and the type where you need a pickaxe, and break the rapid switching between them and volya time you have 2 identical subjects

### Screenshots / Videos

https://youtu.be/eIFt8IcxAvM
I also check on a clean assembly: https://youtu.be/Bdy5XtX1nts

### "/ae plinfo" link

https://paste.md-5.net/akekesujas

### Server Log

-

**Comment by Awpmeister2170** [comment]
Fixed for next update
