### ISSUE TITLE
Wearing armor with Static/repeating effect not working properly[1.8]]

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3086]
### Describe the bug

When u wear an armor with static / repeating effect, they will not work unless u apply another armorpiece after it.

### How to reproduce

EX:
Put speed in ur boots, wear it, it will not work, then create another armorpiece with enchants as well, wear it after the boots, the boots effect will work. 

### Screenshots / Videos

https://www.youtube.com/watch?v=IGRGp3WR9vs

### "/ae plinfo" link

https://paste.md-5.net/nonojazucu

### Server Log

https://mcpaste.io/665eed138927e4ac

**Comment by ItsNoWorry** [comment]
Bump! Having the same issue.

**Comment by GC-spigot** [comment]
Cannot recreate it https://gyazo.com/32757318b0692db5df9e373d2bc15702

**Comment by ItsNoWorry** [comment]
> Cannot recreate it https://gyazo.com/32757318b0692db5df9e373d2bc15702

You're not on 1.8

**Comment by illudota** [comment]
> Cannot recreate it https://gyazo.com/32757318b0692db5df9e373d2bc15702

try 1.8.8

**Comment by ItsNoWorry** [comment]
Bump, we have been waiting for this to be resolved for weeks now. Tried getting help in discord and was told it was going to be patched and still wasn't patched. Please look into this.

**Comment by Awpmeister2170** [comment]
Fixed for the next update, sorry for the inconvenience
