### ISSUE TITLE
BOW type applies effects to attacker instead of victim with weapons

### ISSUE THREAD

**Issue by ZadeFear** [GC-spigot/AdvancedEnchantments#3087]
### Describe the bug

Using the BOW type on a custom weapon applies the effects to the attacker rather than victim. Using variables in weapons dont work either. (%attacker%, %victim% etc)

EX:
events:
  BOW:
    chance: 100
    effects:
       - 'MESSAGE:&c&l* ARCHER ABILITY *'
       - 'ADD_HARM:3' # Harms the bow shooter instead of the victim

### How to reproduce

1. Make an armor set with a bow as weapon
2. Use BOW type and use any effect (ADD_HARM for example)
3. shoot a player and the effect runs on you instead

### Screenshots / Videos

https://gyazo.com/5f1e416a9c1c26b7736f146e84e104a4

### "/ae plinfo" link

https://paste.md-5.net/nahutewiso

**Comment by GC-spigot** [comment]
Do `- 'ADD_HARM:3 %victim%'`

**Comment by GC-spigot** [comment]
%victim% works fine with my testing, if you are having issue try restarting

**Comment by ZadeFear** [comment]
https://gyazo.com/3aa5039cbb3ad4e1dbf80b29fb20741e - This is for a bow custom weapon

https://gyazo.com/58e48040a16e52a96f876746bb8a3c4a - This shows the 'MESSAGE:&c&l* ARCHER ABILITY * %victim%' from above screenshot doesnt work. It only sends the message to the attacker and when using %victim% variable for any effect, it wont do anything
