### ISSUE TITLE
Enchant lore becoming unreadable

### ISSUE THREAD

**Issue by smuddgge** [GC-spigot/AdvancedEnchantments#3088]
### Describe the bug

When you have a long applies to list, the enchant lore becomes huge and most the time unreadable. Could there be line breaks added?

### How to reproduce

Create a enchant with
```yml
applies:
  - ALL_AXE
  - ALL_SWORD
  - ALL_PICKAXE
  - ALL_SPADE
  - ALL_HOE
  - BOW
  - CROSSBOW
  - TRIDENT
  - SHEARS
  - FISHING_ROD
  - SHIELD
```

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/68658429/200028031-2c7cf8e8-63ec-49e2-a9c9-c30e7935af0b.png)

### "/ae plinfo" link

https://paste.md-5.net/oxozukivin

**Comment by GC-spigot** [comment]
So you will need to change your enchantment book configurations for this to work better, change placeholder from `%applies%` to `%applies-to%`, that will use `applies-to` description for each enchantment.
```enchantment-book:
  # If true, books can be applied to items in anvils.
  anvil-application: false
  # If true, books can be applied to items by dragging and dropping them on the item in an inventory.
  drag-drop-application: true
  item:
    type: ENCHANTED_BOOK
    id: 0
    custom-model-data: 0
    force-glow: false
    # Variables: %enchant%, %enchant-no-color%, %description%, %applies%, %success%, %destroy%, %color%, %max-level%
  name: "%group-color%&l&n%enchant-no-color% %level%"
  lore:
    - "&a%success%% Success Rate"
    - "&c%destroy%% Destroy Rate"
    - "&e%description%"
    - "&7%applies-to% Enchantment"
    - "&7Drag n' drop onto item to enchant"```

**Comment by smuddgge** [comment]
Ahh thank you!
