### ISSUE TITLE
Armor swapping while placing down chest

### ISSUE THREAD

**Issue by NightLife-SG** [GC-spigot/AdvancedEnchantments#3089]
### Describe the bug

while placing down chest,my chestplate will be swapped out with the chest

### How to reproduce

shift + right click to place down chest,while you are wearing chestplate

i tried the bug without AE plugin,and there no issue

with AE however,the issue will come out.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/84533050/200129880-1ed8fc40-9150-4072-bc7c-d1bb2bd43158.png)

### "/ae plinfo" link

https://paste.md-5.net/cuvepeseti

**Comment by reussy** [comment]
Hi @NightLife-SG 

Please remove custom items that you don't want as armor items from the armor list in your config.yml
