### ISSUE TITLE
Could not pass event InventoryClickEvent to AdvancedEnchantments

### ISSUE THREAD

**Issue by dzakwaniqbal** [GC-spigot/AdvancedEnchantments#3090]
### Describe the bug

So suddenly my plugins ae spammed in the console with the words "[Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedEnchantments v9.0.0b29" I've updated version but still , and it makes my server lag and crash

### How to reproduce

Im not sure

### "/ae plinfo" link

https://paste.md-5.net/gociqunegu

### Server Log

https://mcpaste.io/494d2316b99fa7b6

**Comment by reussy** [comment]
Hello @dzakwaniqbal 

This is probably a configuration error or some missing path, please perform a backup, update the plugin, regenerate all files and see if the error persists. In case it is fixed, you can use your backup to replace everything.
