### ISSUE TITLE
You can wear chests eggs and paper?

### ISSUE THREAD

**Issue by cRestalious** [GC-spigot/AdvancedEnchantments#3092]
### Describe the bug

When you wear your armor and right click on any of those items you were them instead sometimes it bugs and the chestplate dissapears and the chests or any other item takes the name of the chest instead...

### How to reproduce

Just right click on any of the items I have in title while wearing your armor.

### Screenshots / Videos

https://prnt.sc/YP8TJHx8VNLC

### "/ae plinfo" link

https://paste.md-5.net/difawanafu

**Comment by reussy** [comment]
Hi @cRestalious 

Please remove custom items that you don't want as armor items from the armor list in your config.yml

**Comment by Awpmeister2170** [comment]
Will close this issue as its a easy fix by changing Wearable Armor in the Config
