### ISSUE TITLE
Enchants not work on Copper ore

### ISSUE THREAD

**Issue by DrakMC** [GC-spigot/AdvancedEnchantments#3093]
### Describe the bug

Enchants Smelter and maybe Lucky Miner as well don't work when mining copper ore.

### How to reproduce

1. Mine ore

### "/ae plinfo" link

https://paste.md-5.net/opiqatemod

**Comment by reussy** [comment]
Hello @DrakMC 

It works for me, can you add more info about this please

**Comment by DrakMC** [comment]
I mined it with pickaxe that had these enchantments from AE: Lucky Miner III, Haste I, Telekinesis II.

**Comment by reussy** [comment]
> I mined it with pickaxe that had these enchantments from AE: Lucky Miner III, Haste I, Telekinesis II.

Please, attach the "Lucky Miner" enchantment config here.
