### ISSUE TITLE
Latest plugin version removed enchant cooldowns

### ISSUE THREAD

**Issue by ZadeFear** [GC-spigot/AdvancedEnchantments#3096]
### Describe the bug

I updated to latest ver and noticed no enchant cooldowns. I then went back 1 version and enchant cooldown now works

### How to reproduce

- Make an enchant with 100% chance to proc
- set cooldown to a few seconds
- test the enchant to see if the cooldown doesnt work

### Screenshots / Videos

https://gyazo.com/8d44188a1965520b9591b1c231ebdbea

### "/ae plinfo" link

https://paste.md-5.net/ojadewesik

**Comment by GC-spigot** [comment]
Fixed
