### ISSUE TITLE
Dupe With Vouchers and Beastwithdraws ect.

### ISSUE THREAD

**Issue by Skilz-yt** [GC-spigot/AdvancedEnchantments#3098]
### Describe the bug

This bug is a dupe where a player is currently able to get more ecomoney ( economy money) in game in my case.

### How to reproduce

To reproduce this error you need leggings on and need a voucher or some sorts of right clickable item in your hand. you simply right click holding your item that you want to dupe with economy money and you will claim the money and be wearing it.
Weirdly enough you cant put it on through the inventory but can take it off.

### Screenshots / Videos

https://user-images.githubusercontent.com/87422879/201497942-810f612e-b148-4ed3-89a1-6559cf5d0ad0.mp4

### "/ae plinfo" link

https://paste.md-5.net/forixoxazi

**Comment by GC-spigot** [comment]
Can you include your config.yml for AdvancedEnchantments? Thanks

**Comment by Skilz-yt** [comment]
I will be able to at 4pm GMT, im currently at school.

**Comment by Skilz-yt** [comment]
this should work, [download the config](https://www.mediafire.com/file/p6tw1pdfiaviz57/config.yml/file)

**Comment by ZadeFear** [comment]
line 888 in ur config, remove paper. Also probably remove lines 897, 871, 869, 866

**Comment by Skilz-yt** [comment]
when you say remove paper, do you mean like paper what i am running on my server or something else as i am also running bukkit plugins at the same time

**Comment by Skilz-yt** [comment]
oh nevermind i see what you mean

**Comment by Awpmeister2170** [comment]
Yeah make sure in your Config.yml in the armor section you remove all materials you do not want players to be able to wear ( ie Paper for your case here )

**Comment by Skilz-yt** [comment]
This had worked amazingly for me, thank you all so much

**Comment by Awpmeister2170** [comment]
Brilliant news! and no problem at all! ill close the issue now :)
