### ISSUE TITLE
Something wierd with Armor stands

### ISSUE THREAD

**Issue by kiriles** [GC-spigot/AdvancedEnchantments#3099]
### Describe the bug

Console bug

### How to reproduce

Im not sure

### Screenshots / Videos

It just gives a random spam in the console

### "/ae plinfo" link

https://paste.md-5.net/sowunifuge

### Server Log

https://mcpaste.io/19f9ee68591eaeb3

**Comment by GC-spigot** [comment]
Should be resolved
