### ISSUE TITLE
Abiding Duplication Bug

### ISSUE THREAD

**Issue by UMXR6015** [GC-spigot/AdvancedEnchantments#3100]
### Describe the bug

a player on my server was using a netherite axe in pvp. it would duplicate on several occasions but stopped when we removed abiding from it.

### How to reproduce

use a axe with abiding in pvp

### "/ae plinfo" link

https://paste.md-5.net/kaqedoqaho

**Comment by GC-spigot** [comment]
Any other enchants on the item?

**Comment by UMXR6015** [comment]
the enchants on the axe were cleave bleed hex stun insanity devour barb corrupt blessed abiding

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
