### ISSUE TITLE
Duplicating Doors

### ISSUE THREAD

**Issue by DuneSciFye** [GC-spigot/AdvancedEnchantments#3102]
### Describe the bug

When breaking the upper half of a door using a tool enchanted with smelting, it drops twice.

### How to reproduce

1. Get a diamond pickaxe
2. Enchant it with smelting
3. Place a door
4. Break upper half of door

### "/ae plinfo" link

https://paste.md-5.net/ilevevokeh

**Comment by GC-spigot** [comment]
Fixed
