### ISSUE TITLE
Invincible Effect Broken

### ISSUE THREAD

**Issue by ItsNoWorry** [GC-spigot/AdvancedEnchantments#3103]
### Describe the bug

7:
      chance: 30
      cooldown: 15
      condition:
        
"%victim health% > 8 : %stop%"
    effects:
"POTION:INVISIBILITY:2:120 %victim%"
"INVINCIBLE:120 %victim%"

Invincible last until server restarts. Please need fix asap.

### How to reproduce

Use Invincible effect

### "/ae plinfo" link

https://paste.md-5.net/egeqepeyop

**Comment by GC-spigot** [comment]
It's not timed, it's either on or off. Using `INVINCIBLE` once will enable it, then `INVINCIBLE` another time will disable it. It's generally used with `EFFECT_STATIC`
