### ISSUE TITLE
Upgrading Enchantment reduces slots

### ISSUE THREAD

**Issue by BrightSteel** [GC-spigot/AdvancedEnchantments#3108]
### Describe the bug

Bug when an item already has an enchantment, say Bleed I, and is given a higher level, such as Bleed III, the enchantment is upgraded successfully (only Bleed III is present) but the number of available enchantment slots decreases by one. 

### How to reproduce

I used an anvil to apply any enchantment book to a possible item, and then used another book of a higher level to upgrade it. I also have the lore showing the available slots, so it is clear that a slot is lost. Additionally, I am unable to add more enchantments once all slots have been depleted, so it seemingly is not just lore showing incorrect info.

### "/ae plinfo" link

https://paste.md-5.net/heyikatufa

**Comment by GC-spigot** [comment]
Fixed
