### ISSUE TITLE
Some Error With Tinker!

### ISSUE THREAD

**Issue by MikuSnow** [GC-spigot/AdvancedEnchantments#3109]
### Describe the bug

Server Version: 1.12.2
Plugin Version: v9.0.0b34

### How to reproduce

1. get some weapons like IRON_SWORD
2. use command :/tinker
3. click the iron_sword in inventory gui.
4. see the console error.
5. click the iron_sword in tinker gui.
6. see the console error.

### "/ae plinfo" link

https://paste.md-5.net/mugedozudu

### Server Log

https://mcpaste.io/1ffd99fa142b3c60

**Comment by Awpmeister2170** [comment]
Fixed for next update
