### ISSUE TITLE
Chest Dupe Bug

### ISSUE THREAD

**Issue by Spaex** [GC-spigot/AdvancedEnchantments#3110]
### Describe the bug

When placing a chest while sneaking and placing an empty chest, I can dupe that chest at the cost of my Chestplate.
This makes the plugin super vulnerable for every server using crate plugins. 
As soon as I disable armor switiching it is "fixed".

### How to reproduce

Sneak and climb a ladder while wearing a chestplate. Place a chest while climbing and it will get placed, but it will also be put into your chestplate slot. ---> Duped the chest.
Also shown in the video. 

### Screenshots / Videos

https://www.youtube.com/watch?v=rf6suRwgOxQ

### "/ae plinfo" link

https://paste.md-5.net/xazepulidi

**Comment by reussy** [comment]
Hi @Spaex 

Please remove custom items that you don't want as armor items from the armor list in your config.yml

**Comment by Spaex** [comment]
Oh okay. Weird I never did put it there. But thanks then it was on my side. Sorry.
