### ISSUE TITLE
Spartan x AE | Error

### ISSUE THREAD

**Issue by 21MX** [GC-spigot/AdvancedEnchantments#3111]
### Describe the bug

hello I have noticed that trench and telepathy no longer work is it because of our anti cheat (spartan) ? we use both for a long time I have now but recently updated ae

### How to reproduce

Hello, I noticed that Spartan always deactivates on me since I loaded an update of Spartan and Advanced Enchantments

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/114404655/202859655-497135a6-5190-46d9-ae08-56a15fd9455b.png)

### "/ae plinfo" link

https://pastebin.com/WjVxMDvR

**Comment by reussy** [comment]
Hello @21MX 

Could you attach the link to the logs so I can solve the error, thanks!

**Comment by 21MX** [comment]
https://pastebin.com/WjVxMDvR
