### ISSUE TITLE
Aromor swapping 

### ISSUE THREAD

**Issue by tiarnia** [GC-spigot/AdvancedEnchantments#3122]
### Describe the bug

when you toss an egg it swaps to your boots  some times when your placing chests and have 2 it replaces your chest plate with a chest 

### How to reproduce

load the plugin  toss an egg while wearing armor

i am still testing to see if it is some sort of compatibility issue but it seems to not matter what other plugins i have installed so far 

### Screenshots / Videos

https://user-images.githubusercontent.com/16805000/205725699-7b438637-3fc2-4488-9a0a-e6753b2810e9.mp4

### "/ae plinfo" link

https://paste.md-5.net/udibehasun

**Comment by tiarnia** [comment]
i have verified it does this even with all other plugins removed

**Comment by Awpmeister2170** [comment]
Hello, in the Config File please remove all the items you don't want to be wearable from the Armor Section, this will resolve the issue with changing when right clicking
