### ISSUE TITLE
[Issue] InventoryCreateEvent console spam Issue

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#3124]
### Describe the bug

https://hastebin.com/poxufulube.apache

### How to reproduce

Just go for block interact.

### "/ae plinfo" link

9.0.0b38 - Paper 1.18

### Server Log

https://hastebin.com/poxufulube.apache

**Comment by GC-spigot** [comment]
Please use pastebin.com, hastebin deletes its pastes after a day or two
