### ISSUE TITLE
Lava Walker and Water Walker not being disabled

### ISSUE THREAD

**Issue by Joeychuwu** [GC-spigot/AdvancedEnchantments#3125]
### Describe the bug

i have one world where even if you take your boots off, the lava/water walker effect stays on, so i wanted to just outright disable them in that world with the config, but neither 
```
enchantment-world-blacklist:
  - world_parkour
```
in the config.yml nor
```
 disabled-worlds:
    - "world_parkour"
```
in the enchantments.yml on the 2 enchantments would disable them in that world.
(case sensitive etc. has already been checked, talked with discord support and they sent me here :3)

### How to reproduce

on this one world its basically impossible to turn off water/lava walker if you enter it with boots on that have those enchants

### Screenshots / Videos

https://user-images.githubusercontent.com/103876062/206230663-26962680-82c1-4b63-8fc4-7218f714c5a9.mp4

### "/ae plinfo" link

https://paste.md-5.net/aqifepobar

**Comment by GC-spigot** [comment]
Fixed
