### ISSUE TITLE
veinminer bug

### ISSUE THREAD

**Issue by rongda0201** [GC-spigot/AdvancedEnchantments#3126]
### Describe the bug

check video

### How to reproduce

check video

### Screenshots / Videos

https://www.dropbox.com/s/0zo5h251x2uxwyu/bandicam%202022-12-03%2015-08-20-056.mp4?dl=0

### "/ae plinfo" link

https://paste.md-5.net/avekabufif

**Comment by SpookGezichtje** [comment]
+1 Got the same issue on my server, I just wanted to make a report when I saw this :)

No plugins installed + latest version on Paper (1.19.2)
