### ISSUE TITLE
Weapon / Armor SLOT not going down!

### ISSUE THREAD

**Issue by RandomUser4510** [GC-spigot/AdvancedEnchantments#3129]
### Describe the bug

Let's assume your armor has 6 free slots and 3 extra slots for the increaser slot.
So, you have an armor with 6 slots, add an enchantment for example Drunk 1, you will lose a slot, that is, you will only have 5 slots free, BUTTTTTTTTT if you put a book of higher value, for example a Drunk 4 , he instead of keeping the 5 slots free, he will ADD another +1 slot for you, and you get 6 slots free...
WTF hahahaha, it doesn't even make sense to explain, it's so stupid how is that out there.

### How to reproduce

So, you have an armor with 6 slots, add an enchantment for example Drunk 1, you will lose a slot, that is, you will only have 5 slots free, BUTTTTTTTTT if you put a book of higher value, for example a Drunk 4 , he instead of keeping the 5 slots free, he will ADD another +1 slot for you, and you get 6 slots free...

### Screenshots / Videos

Anyone can do it without needing video or screenshots.

### "/ae plinfo" link

It is not necessary for this...

### Server Log

It is not necessary for this...

**Comment by antibitcoin** [comment]
I can confirm that slots are infinite, if you also use blackscroll it will reset item slots.

**Comment by GC-spigot** [comment]
Fixed
