### ISSUE TITLE
You can get soulgems by hitting armor stands

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#3131]
### Describe the bug

You are able to get soulgems without killing any players using only armor stands

### How to reproduce

Just keep hitting an armor stand it will be like killing a player.

### "/ae plinfo" link

https://paste.md-5.net/todekiradi

### Server Log

Not needed

**Comment by GC-spigot** [comment]
Show your config and record a gif or a video. I can't recreate it.
