### ISSUE TITLE
BlockBreakEvent 1.8.8 console spam error

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3136]
### Describe the bug

Spamming error in console called 'BlockBreakEvent'

### How to reproduce

Not sure yet, maybe some block-breaking enchants? I just see it spamming on console

### Screenshots / Videos

https://mcpaste.io/23d8bf5d93f373a3

### "/ae plinfo" link

https://paste.md-5.net/ucihamirum

### Server Log

Log file too big, I'll create ticket on discord and upload it there.

**Comment by Awpmeister2170** [comment]
Fixed in Next update
