### ISSUE TITLE
Trench and Veinminer STILL do not give mcMMO double drops

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#3137]
### Describe the bug

Trench and VeinMiner still do not give mcMMO double drops even though it was "fixed" apparently months ago

### How to reproduce

Trench or Veinminer any ore with mcMMO level 1000 for double drops, and you won't get them.

### "/ae plinfo" link

https://paste.md-5.net/dijoyafadi

**Comment by austv** [comment]
Also, TP_DROPS doesn't give the double drops as well

**Comment by ArmonicPvP** [comment]
Correct
