### ISSUE TITLE
DUPE GLITCH

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#3138]
### Describe the bug

When you right click whilst holding paper (and have leggings on), the paper switches with the leggings so you wear the paper as leggings

### How to reproduce

1. Wear leggings
2. Right click with paper in your hand
3. They swap

### "/ae plinfo" link

https://paste.md-5.net/ugefolakaq

**Comment by Awpmeister2170** [comment]
Open your Config File and look for the Armor Section, in Leggings remove Paper

Go through all the Armor settings in the Config and remove all material you don’t want wearable
