### ISSUE TITLE
Lots of enchantments not working when not opped

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#314]
Detonate, telepathy, experience among others all do not work unless the players is opped. The simple magic dust working on any category of book feature in the config also does not work unless opped.

Please fix this, I have been waiting a long time.

**Comment by GC-spigot** [comment]
This is caused by an external plugin, Im running this plugin on multiple 100+ player servers i work with and we do not have this issue.

**Comment by Leomelonseeds** [comment]
How about on 1.13.2? Ever tried that?
