### ISSUE TITLE
yet another abusable Grindstone issue (infinite exp)

### ISSUE THREAD

**Issue by Shurelia** [GC-spigot/AdvancedEnchantments#3140]
### Describe the bug

Grindstone mechanics broken, still be able to reproduce after setting grindstones-remove-custom-enchants to either true or false

### How to reproduce

put a enchanted item on grindstone to remove the enchants
press 2 (keyboard key) to grab it but 
ensure your slot 2 of your inventory is taken by another item
item wont be grindstoned but you still got the xp anyways

### Screenshots / Videos

https://streamable.com/smkbpw

### "/ae plinfo" link

https://paste.md-5.net/kogowohega

### Server Log

done on a live server if this is crucial i could get one later

**Comment by GC-spigot** [comment]
Fixed
