### ISSUE TITLE
Discription placeholder color doesn't work

### ISSUE THREAD

**Issue by Truongvv10** [GC-spigot/AdvancedEnchantments#3142]
### Describe the bug

Placeholders from AE won't parse correctly in description. This is in the enchants preview and when you right click a book in your hand. 

Description on lore of the physical book that I am holding works fine. 

### How to reproduce

Put %group-color% in description of an enchant

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/67742370/208971741-a435f839-5a77-4730-9cbe-4f037bd5e959.png)
![image](https://user-images.githubusercontent.com/67742370/208971796-4eab3da4-e134-4a3f-9422-0421651b4ff5.png)
![image](https://user-images.githubusercontent.com/67742370/208971866-ed8953b3-75e9-4049-885e-1f324fb20ba1.png)

### "/ae plinfo" link

https://paste.md-5.net/peneyuvuyu

**Comment by GC-spigot** [comment]
Seems to be working fine for me, can you send your customcommands.yml file?
