### ISSUE TITLE
Could not pass event ArmorEquipEvent

### ISSUE THREAD

**Issue by LoneDevilX** [GC-spigot/AdvancedEnchantments#3146]
### Describe the bug

I am not sure how does this error occur, but it seems like player can swap the inventory with chest, which make them have a lost of their chestplate or elytra.

### How to reproduce

not sure

### "/ae plinfo" link

https://paste.md-5.net/evefonayid

### Server Log

https://pastebin.com/Ae872fcR

**Comment by GC-spigot** [comment]
Should be fixed
