### ISSUE TITLE
Some enchantments only working when opped 1.13.2

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#315]
Same as the issue you just so quickly closed. How can this be a conflict with another plugin? What type of plugin would it conflict with and which events?

Also have you ever tested it on 1.13?

**Comment by GC-spigot** [comment]
Any that would block events. This plugin is dynamic and detects plugin responses, if it doesnt allow an action it won't allow enchantment to work.

**Comment by Leomelonseeds** [comment]
So would I check for plugins with the BlockBreakEvent?

Also I will try this plugin on a test server with only the ae plugin. If it still doesnt work then its probably an issue with 1.13.

Please leave this issue open until then, thanks.

**Comment by Leomelonseeds** [comment]
Alright Mr. GC, it seems like the problem is an incompatibilty with NoCheatPlus' checks. Could you please include support for that plugin?
