### ISSUE TITLE
BlockBreakEvent Error 

### ISSUE THREAD

**Issue by Rhys00** [GC-spigot/AdvancedEnchantments#3150]
### Describe the bug

AdvancedEnchants plugin BlockBreakEvent is causing an error with another plugin. I am not sure how to fix this. 

### How to reproduce

I am not sure, it just randomly seems to be happening when using custom tools on my server. 

### Screenshots / Videos

https://paste.helpch.at/etaxafawif.rb

### "/ae plinfo" link

https://paste.md-5.net/dexajakoro

### Server Log

https://mcpaste.io/a8dbd659aaa9ab24

**Comment by Awpmeister2170** [comment]
Should be fixed in next update
