### ISSUE TITLE
Alchemist 2nd transition Slot 22 Not changing item

### ISSUE THREAD

**Issue by Snicket66** [GC-spigot/AdvancedEnchantments#3154]
### Describe the bug

In slot 22 in the alchem, When 2 books or items or dust are place in, i have configured that the green glass to be a piece of paper, and it is not - this is a bug and has been tested in a ticket.

### How to reproduce

1 Go into config files for  alchemist
2 under 'inventory'
3 under 'confirm-item'
4 change GREEN_STAINED_GLASS_PANE to any item in minercraft
5 reload plugin
6 place 2 of the same books into alchem
see that it is still the green stained glass pane.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/120325902/212532167-6aacd839-3c72-4f82-b589-34fcb7bd3dab.png)
![image](https://user-images.githubusercontent.com/120325902/212532171-966311d3-245c-40a0-bcc7-d104b408c341.png)
![image](https://user-images.githubusercontent.com/120325902/212532176-c0d65fef-5854-4b68-a301-23fd232b8ca2.png)
![image](https://user-images.githubusercontent.com/120325902/212532195-13963591-93df-47cd-9b05-f22ac366fc26.png)

### "/ae plinfo" link

https://paste.md-5.net/wiyibifisu

**Comment by GC-spigot** [comment]
It needed a restart to update before, fixed for reloading
