### ISSUE TITLE
Fishing Event Error 

### ISSUE THREAD

**Issue by Rhys00** [GC-spigot/AdvancedEnchantments#3155]
### Describe the bug

https://paste.helpch.at/ujeredikof.scss I see this in the console, pretty sure its whenever someone throws, or catches a fish or something. 

### How to reproduce

Try fish and see if it reproduces.

### Screenshots / Videos

N/A

### "/ae plinfo" link

https://paste.md-5.net/menurikizo

**Comment by GC-spigot** [comment]
Fixed
