### ISSUE TITLE
EFFECT_STATIC Bug

### ISSUE THREAD

**Issue by VerfiyNull** [GC-spigot/AdvancedEnchantments#3157]
### Describe the bug

My custom enchantment does not work with golden armor ( and I am sure other types of materials ) but did with diamond armor

### How to reproduce

wear an enchantment with Static Effect type on a gold helmet 

### "/ae plinfo" link

https://paste.md-5.net/iqipuyokeh

### Server Log

https://hastebin.com/fagatikopu.sql

**Comment by Dakotaa** [comment]
I'm having the same problem. EFFECT_STATIC enchantments work with every armour type except gold.

**Comment by reussy** [comment]
Hey @Dakotaa and @VerfiyNull,

The solution is to modify the materials in config.yml file.
https://github.com/GC-spigot/AdvancedEnchantments/issues/3170

If the error persists please open a new issue report.
