### ISSUE TITLE
Alchemist closing the inventory after a trade

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3160]
### Describe the bug

After done a trade, the alchemist GUI is closed, and it's very bad because if the player wants to use several times, it keeping closing it.

Also, if you miss a click and added the wrong book/item, if you click in the book to remove it the GUI is also closed.

### How to reproduce

1. Open alchemist
3. Do a trade
4. GUI is closed
-------- another situation

1. Open alchemist
2. Add some book
3. Click on it to remove it
4. GUI is closed

### "/ae plinfo" link

https://paste.md-5.net/dawupahoce

**Comment by GC-spigot** [comment]
Reworked the alchemist inventory for this
