### ISSUE TITLE
ExcellentCrates error

### ISSUE THREAD

**Issue by tanertekin0** [GC-spigot/AdvancedEnchantments#3162]
### Describe the bug

https://hastebin.com/okirofitap.properties

### How to reproduce

I do not Know xD

### "/ae plinfo" link

https://paste.md-5.net/suxudabalu

### Server Log

https://mcpaste.io/5cda2196d4f88e26

**Comment by GC-spigot** [comment]
This is from battlepass :) It's fixed however
