### ISSUE TITLE
The /enchanter does not accept money to price

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3164]
### Describe the bug

Customer came on ticket aenchantments-3300 telling about bug that /enchanter does not accept money for price and it gives and %paymenttype% error. I went on my own server and tested it there too and i have same issue, we both have latest version of plugin, he has 1.19.3 spigot and i have 1.19.3 paper#384

### How to reproduce

Go to aenchantments config.yml and change the exp: to money: after reloading files it gives an error 

### Screenshots / Videos

Cant upload any screenshot here. "Something went really wrong, and we cant process that file" But they are found in ticket

### "/ae plinfo" link

https://paste.md-5.net/evoyilewiv

**Comment by reussy** [comment]
Hey @aXe18,

This is not a bug as such, unfortunately AdvancedEnchantment only supports economy plugins that use **[Vault](https://dev.bukkit.org/projects/vault)** as API (**[EssentialsX](https://essentialsx.net/)**, **[PlayerPoints](https://www.spigotmc.org/resources/playerpoints.80745/)**, etc). In the case of **EssentialsGems** (I assume you use that one), if it doesn't have **[Vault](https://dev.bukkit.org/projects/vault)** support then AdvancedEnchantments won't detect it as a money type economy. **Could you open a ticket in our Discord to sort this out better?**

**Comment by aXe18** [comment]
@reussy I dont open tickets  you can talk to me on staff chat, or DM. Well tee I use those but only after updating to latest version, this happens.
