### ISSUE TITLE
Enchant packs missing groups

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3166]
### Describe the bug

From /ae market cant be downloaded anything. Enchant packs missing are groups

### How to reproduce

Open /ae market, download anything and see console. At least from version [9.0.0b55] this is happening

### Screenshots / Videos

![Screenshot_733](https://user-images.githubusercontent.com/26152540/215338220-4716fd19-cff9-43f5-824a-92636c556b24.png)

### "/ae plinfo" link

https://paste.md-5.net/qahikariro

**Comment by BloodshotPico** [comment]
Tested this with Spigot 1.19.3
Spigot Version: (3654-Spigot-19641c7-7cd3244)

**Comment by Awpmeister2170** [comment]
Fixed via ticket, this isn’t a bug 👌
