### ISSUE TITLE
Fishing error (Again)

### ISSUE THREAD

**Issue by Rhys00** [GC-spigot/AdvancedEnchantments#3167]
### Describe the bug

When a player fishes/catches a fish this random error pops in console. 

https://paste.helpch.at/uhibarusov.php

### How to reproduce

Fish

### "/ae plinfo" link

https://paste.md-5.net/qiponofoxi

### Server Log

https://mcpaste.io/c9b6b645d6446be3

**Comment by reussy** [comment]
Hey  @Rhys00,

The bug has been fixed for the next update.
