### ISSUE TITLE
force-glow for enchantment book not working

### ISSUE THREAD

**Issue by lDOREMIl** [GC-spigot/AdvancedEnchantments#3168]
### Describe the bug

The enchantment book is not glowing even after set TRUE for force-glow in config.yml

### How to reproduce

Set
enchantment-book:
  item:
    type: BOOK
    force-glow: true

### Screenshots / Videos

![Snipaste_2023-01-31_16-27-12](https://user-images.githubusercontent.com/99507374/215707805-f02715e9-2c5b-4bcf-bae8-d98029ebeaa9.png)

### "/ae plinfo" link

https://paste.md-5.net/pupokiwomu

**Comment by Awpmeister2170** [comment]
Fixed for next update
