### ISSUE TITLE
SOULBOUND ENCHANTMENT does not work with end crystal,bed explosions!

### ISSUE THREAD

**Issue by Darkmager** [GC-spigot/AdvancedEnchantments#3169]
### Describe the bug

Plugin ver: AdvancedEnchantments-9.0.0b64
server ver: git-Purpur-1905 (MC: 1.19.3)

the enchantment "SOULBOUND" that keeps items on death does not work when player dies by end crystal or BED EXPLOSION , this gives others to abuse end crystal in a server

### How to reproduce

equip a soulbound and try exploding yrself with bed or end crystal

### "/ae plinfo" link

https://paste.md-5.net/ecefopomip

**Comment by reussy** [comment]
Hey @Darkmager,

This seems to be quite some time old, fortunately it has been fixed and will be available in the next update.
