### ISSUE TITLE
Golden Armor Bug

### ISSUE THREAD

**Issue by JericNisperos** [GC-spigot/AdvancedEnchantments#3170]
### Describe the bug

https://imgur.com/pwEQAaI

Context: If you wear a boots with AE in it, the AE will be activated. And removing it will also remove the AE effect. However, if you wear the boots with AE and then swap the boots to a golden boots using your hotbar keys, the AE Effect will retain. This bug can't be reproduced from other armors, just Golden Armors.

### How to reproduce

Wear the boots with AE and then swap the boots to a golden boots using your hotbar keys, the AE Effect will retain. This bug can't be reproduced from other armors, just Golden Armors.

### Screenshots / Videos

https://imgur.com/pwEQAaI

### "/ae plinfo" link

https://paste.md-5.net/ujolijapix

**Comment by reussy** [comment]
Hey @JericNisperos,

I am not able to replicate your problem, you could try this using the latest version and sharing the Gears III enchantment in case it is not the default.

**Comment by JericNisperos** [comment]
The Gears 3 is on default. I tried enchanting the Golden boots with Gears 3 but Gears 3 isn't working. And even Jelly Legs. I think this applies to all golden armors.

**Comment by JericNisperos** [comment]
Just for the record, here's the Gears enchant:

gears:
  display: '%group-color%Gears'
  description: 'Added speed when equipped.'
  applies-to: 'Boots'
  type: 'EFFECT_STATIC'
  group: 'LEGENDARY'
  applies:
    - ALL_BOOTS
  levels:
    1:
      effects:
        - 'POTION:SPEED:0'
    2:
      effects:
        - 'POTION:SPEED:1'
    3:
      effects:
        - 'POTION:SPEED:2'
        
 Additionally, all AE doesn't work on Golden armors. No nbttag linked on Golden Armors since I already checked it from /data get entity.

**Comment by JericNisperos** [comment]
![image](https://user-images.githubusercontent.com/29251574/218421600-f708f2b2-db94-40c9-9a22-4e13944c4579.png)

![image](https://user-images.githubusercontent.com/29251574/218421644-1b9ae4c3-6f60-4ccd-93f2-90b0fa101353.png)

These items doesn't have any tags on other plugins. meaning it's not being linked to any features of the server. Already removed some of the plugins to check the issue but still can't find it.

**Comment by JericNisperos** [comment]
Found the bug :3 . From the armor-items tab in config.yml, it says there GOLD_CHESTPLATE instead of GOLDEN_CHESTPLATE and some armors as well. Already updated it and now works. I think you may need to add a catch from that part of the code to check if it matches any item from Minecraft and returns an error from console. But already working.

**Comment by reussy** [comment]
@Awpmeister2170 hey man

You can close this issue 😄
