### ISSUE TITLE
Korean is broken.

### ISSUE THREAD

**Issue by WkaWkqhr** [GC-spigot/AdvancedEnchantments#3172]
### Describe the bug

I am contacting you after inquiring about the discord.
aenchantments-3339
I applied Unicode on the server bucket, but the Korean translation keeps breaking

### How to reproduce

config.yml
language: ko

### Screenshots / Videos

[ko.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/10577245/ko.zip)

### "/ae plinfo" link

https://paste.md-5.net/xibanogusa

**Comment by reussy** [comment]
Hola @WkaWkqhr,

Make sure your text editor is using the UTF-8 encoder, for example:

![image](https://user-images.githubusercontent.com/63428864/225210354-eb123460-1951-45f5-a513-7011772f72da.png)
