### ISSUE TITLE
Diploid enchantment not working properly

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3173]
### Describe the bug

I tried to reproduce diploid enchantment bug and not working for me either. Even setting change to 100 and all but not working. No errors or anything.

### How to reproduce

Use paper 1.19.2 or 1.19.3 and latest b65 version of the plugin and try to get more drops whit diploid enchant

### "/ae plinfo" link

https://paste.md-5.net/agaqobofep

**Comment by Folas1337** [comment]
I was able to confirm this one just now, it literally doesn't do anything on version 9.0.0b70

**Comment by reussy** [comment]
Hey guys,

@Folas1337 you are correct, the correct type to do would be KILL_MOB.
