### ISSUE TITLE
Drag and Drop upgrading for enchants doesnt work

### ISSUE THREAD

**Issue by Joeychuwu** [GC-spigot/AdvancedEnchantments#3176]
### Describe the bug

the 'combining' feature doesnt work on items

### How to reproduce

drag and drop to upgrade, although this seems to be working for most others

### Screenshots / Videos

https://youtu.be/KGYLhTfXybs

### "/ae plinfo" link

https://paste.md-5.net/upudupofus

### Server Log

https://mcpaste.io/5dcffc8dd9a5bdc1

**Comment by reussy** [comment]
Hey @Joeychuwu,

This seems to work perfectly for me, you could update the plugin and check if the problem persists.

**Comment by SirJben** [comment]
Try one of the following solutions:

1. Remove and place the Villager again: The first solution would be to remove and place the Villager again. This will reload their trade and items, and they will start selling the updated and working items.

2. Use the command: You can try the following command to reload the plugin: /ae reload. This will reload all the items and trades, and should fix any issues related to Villagers selling outdated items.
