### ISSUE TITLE
Thelepathy not working on quest plugin.

### ISSUE THREAD

**Issue by RWslayer** [GC-spigot/AdvancedEnchantments#3177]
### Describe the bug

Hi!
 My name is slayer and I have question for you. We are currently running the AdvancedEnchants plugin and as quest plugin: Quests. The problem is whenever you use thelepathy on for ex: a hoe and you farm for your quest yu get the item but the progress of the quests isn't progressing (look video for clearer info) [https://youtu.be/5xC3tFwkx9o](url). Is this something yu guys are able to take a look at and maybe even fix or is this a bug on the devs from Quests

### How to reproduce

Video explains itself.

### "/ae plinfo" link

https://paste.md-5.net/ikuhavumar

### Server Log

-

**Comment by reussy** [comment]
Hey @RWslayer,

Please try to update the plugin to the latest version, this bug was fixed some time ago.

**Comment by reussy** [comment]
@Awpmeister2170
