### ISSUE TITLE
[Feature Request] Blacksmith for combining various enchantments.

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#318]
This would use the /blacksmith command, and working like an anvil, this would combine the enchantments on any 2 same pieces of gear. For example, if you have a diamond pickaxe with Detonate and another dpick with Experience, you could combine these two tools to produce a Detonate, Experience diamond pickaxe.

**Comment by GC-spigot** [comment]
Not going to be added.
