### ISSUE TITLE
AE menus taking items.

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#3180]
### Describe the bug

AE inventories can take the items and disappear when closed.

### How to reproduce

https://user-images.githubusercontent.com/63577950/216892454-4bb5a4a3-67e1-4209-b0bb-1ccb1cbfbefb.mp4

### "/ae plinfo" link

https://paste.md-5.net/etisohurij

**Comment by SirJben** [comment]
in `/ae view <enchantment>` also take items.

**Comment by alimix3** [comment]
I have the same problem with `/alchem` when `filler-item` is disabled in alchemist.yml

**Comment by Awpmeister2170** [comment]
Fixed for next update
