### ISSUE TITLE
Armor Bug

### ISSUE THREAD

**Issue by Jozo7** [GC-spigot/AdvancedEnchantments#3181]
### Describe the bug

Gear is broken in inventory looking like black/purple blocks (the armor)
https://gyazo.com/0f1abf6c036cf7d6398b964e73de8093

i didn't add latest logs, cuz it isn't needed ths happened a while ago.

### How to reproduce

I have found the issue the issue is when I put an heroic upgrade of an armorset on an armor, and someone deals damage on me the gear will look like the screenshots I've sent u.

If im pvping with someone it will look like this:
https://gyazo.com/6eb644d80dc738cb40038a8553356950

### Screenshots / Videos

Check above in describe the bug and how to reproduce.

### "/ae plinfo" link

https://paste.md-5.net/ahesepiqam

**Comment by reussy** [comment]
Hi @Jozo7,

Are you using custom model data or any plugin to modify textures?
