### ISSUE TITLE
Broken GUI (alchemist.yml)

### ISSUE THREAD

**Issue by alimix3** [GC-spigot/AdvancedEnchantments#3182]
### Describe the bug

Changing the slot numbers of the `other-items-slot` is breaking the menu. Click on the enchanted books will not move them inside as it does when left by default.

### How to reproduce

https://paste.md-5.net/moyedefota.bash

### "/ae plinfo" link

https://paste.md-5.net/feveqefatu

**Comment by Awpmeister2170** [comment]
Fixed for next update
