### ISSUE TITLE
There is a problem with plugin enchantment

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3185]
### Describe the bug

On pickaxes with trench + silk touch enchantments, it gives back the block + gives additional loot, like vanilla xp, xp in skills and money in moneyhunters. This gives a lot of opportunities for abusing and duping xp, allowing to break and place blocks over and over again, getting lots of different loot and progress

### How to reproduce

1. place a diamond ore
2. mine the diamond ore with pickaxe that has trench + silk touch enchantments 
3. get the ore back + have xp and other stuff
4. go back to step 1 to have more loot

### "/ae plinfo" link

https://paste.md-5.net/uladiqamuv

### Server Log

-

**Comment by reussy** [comment]
Hey @DimaSergeew,

The problem has been fixed, it will not release any more experience while used with Silk Touch.
