### ISSUE TITLE
Dupe bug on /alchemist

### ISSUE THREAD

**Issue by KazMNF** [GC-spigot/AdvancedEnchantments#3189]
### Describe the bug

Found a player using /alchemist and duping Ce books and dusts.
We have a wildstacker and it removes all stacked mobs synced to clearlag and removes.
player waits to clear stacked mobs and when server clear mobs this wil makes lag spike 1 sec.
before clear player opens alchemist and put ce and after a server lag spike happen he takes dust and makes 2 same dust/ce books
Im not fluent in english so hope to understand.

### How to reproduce

Dm me Karloss#6065 i can tell this by private.

### "/ae plinfo" link

https://paste.md-5.net/utewexegom

**Comment by reussy** [comment]
Hi @KazMNF,

Could you open a ticket on our Discord for more information about this please.

**Comment by reussy** [comment]
Fixed in the latest versions
