### ISSUE TITLE
Eggs and chests replaces armor when right-clicking in air

### ISSUE THREAD

**Issue by MrFalconDK** [GC-spigot/AdvancedEnchantments#3192]
### Describe the bug

When loading the plugin at my server, this bugs happens.. When right clicking in air with an egg, it replaces boots armor and when right clicking air with chest, it replaces chestplate. The armor it replaces either disappear or take the item slot the egg or chest was in..

I tried disabling the plugin, and the bugs disappears

Im using the latest PaperMC version for 1.19.3

![image](https://user-images.githubusercontent.com/125840830/219988481-4c814b6c-83a5-4757-89bf-4f50db4fa1b9.png)

### How to reproduce

Right-click in air with and egg or chest, while using armor

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/125840830/219988691-b1f7cc61-6c31-41cd-ac1a-2daa16d02da8.png)

### "/ae plinfo" link

https://paste.md-5.net/azefawujas

**Comment by aXe18** [comment]
@MrFalconDK Fix this by taking out those items from config.yml armor items starting from row 477

**Comment by MrFalconDK** [comment]
> @MrFalconDK Fix this by taking out those items from config.yml armor items starting from row 477

THANK you so much!
