### ISSUE TITLE
Missile bow enchantment explodes blocks in protected WorldGuard regions where pvp is enabled

### ISSUE THREAD

**Issue by iLemon** [GC-spigot/AdvancedEnchantments#3194]
### Describe the bug

![CleanShot 2023-02-24 at 17 44 50](https://user-images.githubusercontent.com/18317307/221251137-052391da-9b29-49c8-964e-b7643aa6bc8a.gif)

### How to reproduce

Use the Missile explosive arrows enchantment on a bow

Setup a region where block breaking is denied and pvp is enabled

Shoot another player to activate the enchantment

Blocks will explode, even when the region is protected.

### "/ae plinfo" link

https://paste.md-5.net/evadefidov

**Comment by GC-spigot** [comment]
Should be fixed
