### ISSUE TITLE
fortune-works-on-iron-gold option not working

### ISSUE THREAD

**Issue by falistos** [GC-spigot/AdvancedEnchantments#3195]
### Describe the bug

Option `fortune-works-on-iron-gold: false` does not work with SMELT effect.
When breaking a gold ore for example, Fortune still works on it (multiple gold ingot drops).

### How to reproduce

Break an gold ore with a pickaxe enchanted with SMELT effect.

### "/ae plinfo" link

https://paste.md-5.net/unayugupix

**Comment by reussy** [comment]
Hey @falistos,

If I'm not mistaken this option is not being used for a long time, instead you could use the conditions offered by the plugin. 
https://ae.advancedplugins.net/enchantments/enchantment-conditions
