### ISSUE TITLE
Effects bugged

### ISSUE THREAD

**Issue by SalomonPicos** [GC-spigot/AdvancedEnchantments#3197]
### Describe the bug

Hello. Basically when players equip armor by shift clicking on it it works perfectly but as soon as they drag and drop it on the armor slots it gets bugged and give the effects just when player unequip it.

### How to reproduce

Wear a armor with enchant like "glowing" by drag and dropping it (not shift clicking it)

### Screenshots / Videos

https://www.mediafire.com/file/oze6ogx8z9wy6ob/2023-02-27_08-53-03.mp4/file

### "/ae plinfo" link

https://paste.md-5.net/vifaguhecu

### Server Log

https://mcpaste.io/fd961d0c7ce4ae2a

**Comment by reussy** [comment]
Hi @SalomonPicos,

As for the error, **you could try just with AdvancedEnchantments installed on a separate server** and check if the error is possible. From my side I am not able to replicate it, it works perfectly for me.

I'l merge your report with two other similar reports to avoid the accumulation of these reports. https://github.com/GC-spigot/AdvancedEnchantments/issues/3128 https://github.com/GC-spigot/AdvancedEnchantments/issues/3199

**Comment by SalomonPicos** [comment]
Hello @reussy,

Thanks for the help. It seems it's not just me having this problem and as you can see @Replaycchi installed it on a local server and was able to reproduce the bug anyway


Let me know, thanks!

**Comment by GC-spigot** [comment]
Should be resolved with latest rework

**Comment by SalomonPicos** [comment]
Hello. When i try to break the ancient debris with a pickaxe with Trench now i receive these message:

![immagine](https://user-images.githubusercontent.com/88857385/231743406-dce0f214-51a2-438d-a0a0-c87788742925.png)
