### ISSUE TITLE
Alchemist combining dust breaks the item placeholders in lore

### ISSUE THREAD

**Issue by iLemon** [GC-spigot/AdvancedEnchantments#3198]
### Describe the bug

https://media.discordapp.net/attachments/1079820052968247457/1079820239677685890/CleanShot_2023-02-27_at_17.39.41.gif

### How to reproduce

Combine 2 legendary dust in alchemist

### "/ae plinfo" link

-

**Comment by reussy** [comment]
Hey @iLemon,

The link is broken, could you update it please.

**Comment by kill23445** [comment]
![Capture](https://user-images.githubusercontent.com/11782290/222876214-d7014a6b-2e72-49d4-b89d-f822a4d49baa.PNG)
![Capture](https://user-images.githubusercontent.com/11782290/222876238-05c38caf-c53f-4f59-9e14-71d7db78be9d.PNG)
I can confirm this bug / possible placeholders. Any dusts combined do not work reguardless of tier. (paper, java/bedrock hybrid server)

**Comment by reussy** [comment]
> ![Capture](https://user-images.githubusercontent.com/11782290/222876214-d7014a6b-2e72-49d4-b89d-f822a4d49baa.PNG) ![Capture](https://user-images.githubusercontent.com/11782290/222876238-05c38caf-c53f-4f59-9e14-71d7db78be9d.PNG) I can confirm this bug / possible placeholders. Any dusts combined do not work reguardless of tier. (paper, java/bedrock hybrid server)

Thank you for your report, a solution for this will be sought!

**Comment by reussy** [comment]
Good news! Fixed next update
