### ISSUE TITLE
EFFECT_STATIC is not working like it should..

### ISSUE THREAD

**Issue by Kyjasport** [GC-spigot/AdvancedEnchantments#3199]
### Describe the bug

If I put on a kit that puts my boots on with speed 2 on them, the effect doesn't activate. See the video for a demonstration.

### How to reproduce

Maybe it would help if the plugin checked if the armor is worn

### Screenshots / Videos

https://user-images.githubusercontent.com/125750990/222113086-7aa3a0ab-7f52-4e26-94cf-c06d79288a77.mp4

https://user-images.githubusercontent.com/125750990/222113245-2dda4f15-5e6b-404d-bdfc-0a3d4c1d2882.png

### "/ae plinfo" link

https://paste.md-5.net/iyapodamor

### Server Log

https://mcpaste.io/50696b0bf1002dc4

**Comment by reussy** [comment]
Hey @Kyjasport,

I'll close your report and keep only https://github.com/GC-spigot/AdvancedEnchantments/issues/3197 to avoid report accumulation. If the bug persists after the above solution then it is pending to the other bug.
