### ISSUE TITLE
org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy

### ISSUE THREAD

**Issue by AurelienConte** [GC-spigot/AdvancedEnchantments#3201]
### Describe the bug

I am getting this error log :

[10:50:08 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug

When launching the server in (paper - 1.18.2)

### How to reproduce

Download the latest release of AE
Put the plugin in the paperMC plugins folder of a server at version 1.18.2 (latest build)

This error will appear on startup

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by GC-spigot** [comment]
You can ignore this, AE uses some legacy materials currently
