### ISSUE TITLE
slot-increaser, broken

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#3202]
### Describe the bug

slot-increaser , After the version 67 update, the original slotincreaser is broken?
also custom-model-data broken
Tested and confirmed 100%
slot-increaser
1. custom-model-data is broken
2. The old slot-increaser item, becomes unusable

![image](https://user-images.githubusercontent.com/5382252/222611672-3b01742d-7c14-43f2-8f39-91547bf067cd.png)

### How to reproduce

Summoning items will find this BUG

### "/ae plinfo" link

https://paste.md-5.net/ihanizocap

**Comment by reussy** [comment]
Hey @p82183645,

What do you mean when the item is broken? Could you add more details or images?

**Comment by p82183645** [comment]
> Hey @p82183645,
> 
> What do you mean when the item is broken? Could you add more details or images?

Means this item can't be used, looks like nbt changed
old version items

**Comment by p82183645** [comment]
> > > Hey @p82183645,
> > > What do you mean when the item is broken? Could you add more details or images?
> > 
> > 
> > Means this item can't be used, looks like nbt changed old version items
> 
> I've applied a small patch, please try this in the next update and report back to me here.

still no fix
old item , still can't use 
It means that after updating the version, the old items will lose their function
