### ISSUE TITLE
Custom model data bug

### ISSUE THREAD

**Issue by maximina16** [GC-spigot/AdvancedEnchantments#3203]
### Describe the bug

when i apply custom model data to a advanced set and wear it it looks the leather armor piece
![image](https://user-images.githubusercontent.com/65305406/222902189-67131eae-000b-4b8c-a04b-0a130536c48e.png)
![image](https://user-images.githubusercontent.com/65305406/222902193-336e2048-38d5-4043-9085-0d3d99d279f5.png)

and this is what happens when i get another custom modelled item using /aegive Maximina16 leather_chestplate 1 custommodeldata:10024
![image](https://user-images.githubusercontent.com/65305406/222902215-9d6ba90d-95b6-4632-a23a-7b509420dfb1.png)
still same.

### How to reproduce

writed above.

### "/ae plinfo" link

https://paste.md-5.net/ubocicufir

### Server Log

https://mcpaste.io/c25385754902fcd7

**Comment by maximina16** [comment]
bump

**Comment by GC-spigot** [comment]
Working on this!
