### ISSUE TITLE
%victim% does not work in customweapons

### ISSUE THREAD

**Issue by dtathu828** [GC-spigot/AdvancedEnchantments#3205]
### Describe the bug

I configured an event inside the customweapons folder and I found out that %victim% has no effect

### How to reproduce

I checked %victim% but it doesn't work at all in customweapons

### "/ae plinfo" link

https://paste.md-5.net/ipujecuwor

**Comment by reussy** [comment]
Hey @dtathu828,

Could you provide the configuration where you are trying to use %victim%.
