### ISSUE TITLE
Dupe bug on alchemist.

### ISSUE THREAD

**Issue by KazMNF** [GC-spigot/AdvancedEnchantments#3206]
### Describe the bug

This bug is fixed on 8.15.8.
But not for 9.0.0 above versions.

### How to reproduce

/alchemist and use number keys to fast place items on gui and gui is double back item.

### Screenshots / Videos

https://youtu.be/tjz4CFo87r4

### "/ae plinfo" link

https://paste.md-5.net/ulemoyulip

**Comment by iLemon** [comment]
Confirmed. You can dupe any item with this. It needs a fix urgently @GC-spigot

**Comment by reussy** [comment]
Hey @iLemon and @KazMNF,

**The bug was fixed**, thank you for reporting this problem, the whole development team apologizes for this big problem and what could affect your servers

**Comment by iLemon** [comment]
> Hey @iLemon and @KazMNF,
> 
> 
> 
> **The bug was fixed**, thank you for reporting this problem, the whole development team apologizes for this big problem and what could affect your servers

When is the jar being uploaded to spigot?

**Comment by GC-spigot** [comment]
> > Hey @iLemon and @KazMNF,
> > **The bug was fixed**, thank you for reporting this problem, the whole development team apologizes for this big problem and what could affect your servers
> 
> When is the jar being uploaded to spigot?

Today, have been in hospital past ~week, was not available.
