### ISSUE TITLE
Enchants stay after armor breaks

### ISSUE THREAD

**Issue by timjuic** [GC-spigot/AdvancedEnchantments#3207]
### Describe the bug

Effects from the enchants of type EFFECT_STATIC remain on the player after armor piece with the enchant breaks. It may also be a problem with other enchantment types. Im using the latest version of Advanced Enchantments plugin at the server version 1.8.8

### How to reproduce

To reproduce this problem, wear an armor peace with EFFECT_STATIC enchantment type on it. After that armor peace breaks enchantment will stay on the player

### Screenshots / Videos

https://user-images.githubusercontent.com/70685646/224018238-ed6e1172-4da7-4f44-b07d-91d74235cb30.mp4

### "/ae plinfo" link

https://paste.md-5.net/cujajizuro

**Comment by reussy** [comment]
The fix is available in the next update. 👌
