### ISSUE TITLE
Heads and Custom Enchant books

### ISSUE THREAD

**Issue by Reap09** [GC-spigot/AdvancedEnchantments#3208]
### Describe the bug

Not being able to add custom enchant books to heads with "PLAYER_HEAD" for applies:

### How to reproduce

Not being able to add custom enchant books to heads with "PLAYER_HEAD" for applies:

### "/ae plinfo" link

https://paste.md-5.net/upabiyowaq

**Comment by reussy** [comment]
Hey @Reap09,

Could you please elaborate a bit more about your problem, I don't quite understand what you mean.

**Comment by Reap09** [comment]
> Hey @Reap09,
> 
> Could you please elaborate a bit more about your problem, I don't quite understand what you mean.

basically i want to apply enchants to custom heads, but i've contacted support in the discord and tried everything they told me like applies-to: PLAYER_HEAD, SKULL
and such and non of them worked so they told me to open an issue report

**Comment by GC-spigot** [comment]
It does work! Here's an example with aquatic enchantment:
```yaml
aquatic:
  display: '%group-color%Aquatic'
  description: Breathe underwater.
  applies-to: Helmets
  type: EFFECT_STATIC
  group: SIMPLE
  applies:
    - 'PLAYER_HEAD'
    - ALL_HELMET
  levels:
    '1':
      effects:
        - POTION:WATER_BREATHING:0```
