### ISSUE TITLE
implants enchantment issue

### ISSUE THREAD

**Issue by Lilie-desuyo** [GC-spigot/AdvancedEnchantments#3212]
### Describe the bug

take off helmet with "implants" and wear it, "implants" is not working. then, if player warps to nother world like The End, it start working but 3~4times on each repeating.

### How to reproduce

1. take off helmet with 'implants' enchantment, and wear it.
2. wait a few seconds to check it isnt working
3. warp to nother world and wait again

### Screenshots / Videos

https://youtu.be/t1HYYK2bYO8

### "/ae plinfo" link

https://paste.md-5.net/gugugegusa

**Comment by reussy** [comment]
Hey @Lilie-desuyo,

Please provide the configuration of the "implants" enchantment.

**Comment by Lilie-desuyo** [comment]
> 여기요@Lilie-desuyo,
> 
> "임플란트" 인챈트의 구성을 제공하십시오.

implants:
  display: "%group-color%에너지드링크"
  description: "&f지속적으로 배고픔을 회복합니다."
  applies-to: "&f투구"
  type: "REPEATING"
  time: 10
  group: "ULTIMATE"
  applies:
    - ALL_HELMET
  levels:
    1:
      chance: 50
      effects:
        - "ADD_FOOD:1"
    2:
      chance: 65
      effects:
        - "ADD_FOOD:2"
    3:
      chance: 80
      effects:
        - "ADD_FOOD:3"
        - "MESSAGE:&fimplants activated"

**Comment by Lilie-desuyo** [comment]
> Hey @Lilie-desuyo,
> 
> Please provide the configuration of the "implants" enchantment.

implants:
  display: "%group-color%에너지드링크"
  description: "&f지속적으로 배고픔을 회복합니다."
  applies-to: "&f투구"
  type: "REPEATING"
  time: 10
  group: "ULTIMATE"
  applies:
    - ALL_HELMET
  levels:
    1:
      chance: 50
      effects:
        - "ADD_FOOD:1"
    2:
      chance: 65
      effects:
        - "ADD_FOOD:2"
    3:
      chance: 80
      effects:
        - "ADD_FOOD:3"
        - "MESSAGE:&fimplants activated"

**Comment by reussy** [comment]
> > Hey @Lilie-desuyo,
> > Please provide the configuration of the "implants" enchantment.
> 
> implants: display: "%group-color%에너지드링크" description: "&f지속적으로 배고픔을 회복합니다." applies-to: "&f투구" type: "REPEATING" time: 10 group: "ULTIMATE" applies: - ALL_HELMET levels: 1: chance: 50 effects: - "ADD_FOOD:1" 2: chance: 65 effects: - "ADD_FOOD:2" 3: chance: 80 effects: - "ADD_FOOD:3" - "MESSAGE:&fimplants activated"

There is no bug, your configuration has a delay of 10 seconds with a chance of 80%. **If you change these values the effect will always be activated.**

![image](https://user-images.githubusercontent.com/63428864/224896938-57132882-a7a8-47ca-a244-dd5f4375c42b.png)
