### ISSUE TITLE
TPS getting too low 10TPS because of ATTACK_MOB

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#3214]
### Describe the bug

TPS gets too low because of people attacking multiple mobs on a mob farm
https://timings.aikar.co/dev/?id=a454bde1d7374bb08fad8c4c00abd168

### How to reproduce

Have so many mobs about 30 40 near a spawner and spam attack all.
even when I disable all enchants with ATTACK_MOB type it still lags the server, if I disable advanced enchants everything is smooth again.

### "/ae plinfo" link

https://paste.md-5.net/tucosasuka

### Server Log

https://timings.aikar.co/dev/?id=a454bde1d7374bb08fad8c4c00abd168

**Comment by antibitcoin** [comment]
This is still lagging my server
AdvancedEnchantments::Event: net.advancedplugins.ae.enchanthandler.enchanttypes.ATTACK_MOB (EntityDamageByEntityEvent) (SELF)
Kindly help

**Comment by antibitcoin** [comment]
New timings still an issue on version AE: 9.0.0b81

https://timings.aikar.co/dev/?id=4a1dae188e06415290daf2a40f6cb949

**Comment by GC-spigot** [comment]
Try with newest version 9.0.0

**Comment by antibitcoin** [comment]
Its fixed now, thanks
