### ISSUE TITLE
- [Fri 08:49:08 ERROR Minecraft] Could not pass event EntityDamageEvent to AdvancedEnchantments v9.0.0b78

### ISSUE THREAD

**Issue by WolfLiSteel** [GC-spigot/AdvancedEnchantments#3215]
### Describe the bug

This error message spamming my console after restart last night

- [Fri 08:49:08 ERROR Minecraft] Could not pass event EntityDamageEvent to AdvancedEnchantments v9.0.0b78

and error when using /ae plinfo

### How to reproduce

the EntityDamageEvent just keeps spamming.

using  /ae plinfo gives an error message

### Screenshots / Videos

![2023-03-17_09 53 40](https://user-images.githubusercontent.com/121672422/225857875-d0b1467d-777e-4a78-8e64-8af4b2b9896a.png)

### "/ae plinfo" link

N/A

### Server Log

https://mcpaste.io/4fd7c08cf95f5604

**Comment by GC-spigot** [comment]
Resolved
