### ISSUE TITLE
Enchantments are not working with alchemist

### ISSUE THREAD

**Issue by Eqxinus** [GC-spigot/AdvancedEnchantments#3219]
### Describe the bug

When using the alchemist, when you put an enchantment in, it tells me the alchemist doesn't accept this item.

It says: "The Alchemist doesn't accept this item!"

(I set the enchantments to emeralds that may be causing the issue.)
enchanter-books:
  firework-on-open: true
  cosmetics:
    particle: HAPPY_VILLAGER
    sound: LEVEL_UP
  display-right-click-message: true
  type: EMERALD
  id: 0
  custom-model-data: 0
  force-glow: false
  name: '%group-color%&l%group-name%&l Enchantment Rune &7(Right Click)'
  lore:
  - '&7Right Click while holding to receive a random'
  - '%group-color%%group-name% &7enchantment book.'

### How to reproduce

Using 1.8.8

Just get an emerald based enchantment and try to put in the alchemist inventory and it should deny you accessibility to put it in the inventory.

### Screenshots / Videos

https://i.imgur.com/w0Y8Idu.png
https://i.imgur.com/FyOBUDO.png

### "/ae plinfo" link

https://paste.md-5.net/esezujewal

### Server Log

https://mcpaste.io/aec867fdeb99412c

**Comment by GC-spigot** [comment]
Resolved
