### ISSUE TITLE
Mob.yml

### ISSUE THREAD

**Issue by SKILLETTON2K** [GC-spigot/AdvancedEnchantments#3221]
### Describe the bug

I can't get Piglin brutes to drop enchantment books so I moved to Ravagers, which worked but only from the ones from spawn eggs. If they spawn by a spawner it will not work. Asked for assistance on the discord and was directed here. 

mobs:
  RAVAGER:
    chance: 25
    items:
      - "randomenchantmentbook:1"

### How to reproduce

After typing the code in the Mob.yml, give yourself the correct ravager spawner and once they are kill by a player they will not drop anything, but if you use a ravager spawn egg it will drop the random book. 

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by GC-spigot** [comment]
Set `settings.custom-drops-from-spawners` to true in config
