### ISSUE TITLE
Enchantment "Phoenix" Not working

### ISSUE THREAD

**Issue by GatoronronYT** [GC-spigot/AdvancedEnchantments#3222]
### Describe the bug

It says "Chance to revive yourself when killed" but we Never revive, just respawn like a normal Death and i changed "chance" to 75-100 and is still not working.

### How to reproduce

Let you kill by anything type and you will see it's not working at 100% chance

### Screenshots / Videos

https://user-images.githubusercontent.com/128557960/226775443-9e318656-c1f9-461c-a7cf-dc6a66342c1f.mp4

### "/ae plinfo" link

https://paste.md-5.net/furetopeqe

**Comment by GC-spigot** [comment]
Add `PASSIVE_DEATH` type to enchant, since you get killed by fire not player damage
