### ISSUE TITLE
AE GUI not working

### ISSUE THREAD

**Issue by Twistedr** [GC-spigot/AdvancedEnchantments#3224]
### Describe the bug

So as i said in a discord ticket, i buyed the GUI from the site, and when i use the RP with the RP config it shows bugged, like this 
![image](https://user-images.githubusercontent.com/129333765/228663988-e8de2a6e-2087-46cf-9cde-279b3d0b9d9b.png)
Any help please?

### How to reproduce

Just use the files from  the site

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/129333765/228664046-8055c21e-33f4-4bc2-9e31-da2010ab7eb9.png)

### "/ae plinfo" link

https://paste.md-5.net/coburekuvu

**Comment by reussy** [comment]
Hey @Twistedr,

Are you using Oraxen or ItemsAdder?
If yes, try updating the plugin files (alchemist.yml, tinkerer.yml, etc)

**Comment by Twistedr** [comment]
I use the version without Oraxen or ItemsAdder as i want just the custom GUI. And i updated alchemist.yml and tinkerer and the rest from the "AdvancedEnchantments Config (For Texture Pack)" folder.

**Comment by reussy** [comment]
> I use the version without Oraxen or ItemsAdder as i want just the custom GUI. And i updated alchemist.yml and tinkerer and the rest from the "AdvancedEnchantments Config (For Texture Pack)" folder.

Still not working?
You can get support in our [Discord](https://discord.gg/GzdQdMw)

**Comment by Twistedr** [comment]
I did a ticket on discord before coming here and it told me to report it on github

**Comment by GC-spigot** [comment]
https://wiki.advancedplugins.net/ui/install-custom-uis
