### ISSUE TITLE
BIG DUPE BUG, easy to reproduce

### ISSUE THREAD

**Issue by shika258** [GC-spigot/AdvancedEnchantments#3225]
### Describe the bug

Hello, as you can see on the video, I found a duplication bug very simple to reproduce.

I use the last version of your plugin on a version of spigot 1.8.8

https://user-images.githubusercontent.com/40808436/228742172-9d4e5af8-b121-4f60-a771-48194058206e.mp4

### How to reproduce

look the video

### Screenshots / Videos

https://user-images.githubusercontent.com/40808436/228742228-b5f33829-90ef-4030-9fdf-bb0ff1d24be4.mp4

### "/ae plinfo" link

https://paste.md-5.net/unecudewob

**Comment by GC-spigot** [comment]
Simply do not use creative mode - this is an issue with it and 1.8.8.
We are dropping support for 1.8.8 in a week, this issue will be gone by then.
