### ISSUE TITLE
plugin keeps breaking at every possible corner

### ISSUE THREAD

**Issue by Joeychuwu** [GC-spigot/AdvancedEnchantments#3226]
### Describe the bug

villager trades break so frequently now that my players stopped trying to get them because, which ae items are the most profible on the server, the items they trade stop functioning all the time.
i tried stopping to update the plugin, but when i do that i get ppl on my server who abuse all the glitches and bugs.
ennchanted equipment breaks all the time as well, had to take away 3 swords this month because they randomly broke and allowed for more enchantments than are supposed to be possible (17, 18 and 15, instead of the 13 the config is set to) and 2 of them broke so magnificently that they started dealing 5k+ dmg to dragon, oneshotting it... and you can imagine how happy players are when i have to take away their items and replace them with something that isnt so utterly broken.
im starting to hate this plugin, its so much trouble

### How to reproduce

have the plugin running on a server for more than 2 minutes

### "/ae plinfo" link

https://paste.md-5.net/adaduyuzad

**Comment by GC-spigot** [comment]
Try now :) We just had a huge overhaul!
