### ISSUE TITLE
Infinite Mining Xp with trench enchant

### ISSUE THREAD

**Issue by SalomonPicos** [GC-spigot/AdvancedEnchantments#3227]
### Describe the bug

Hello. 

When using a pickaxe with the Trench enchantments and breaking a ancient debris, if you place again the same ancient debris and break it with the trench enchant it will give you xp again.

So players can basically farm infinite xp just by placing and breaking ancient debris wich is the most valuable source of mining xp.

### How to reproduce

Enchant a pickaxe with trench
Break a ancient debris (or whatever blocks that give mining xp)
Replace the broken block
Break again the block

### Screenshots / Videos

In the first part as you can see i break a ancient debris that i placed with a normal pickaxe and it gives me no xp, wich is right.
As soon as i break it with the trench enchant it gives me xp as if it was naturally generated.

https://www.dropbox.com/s/hp84j8sdzao4zq1/2023-03-30%2019-50-55.mp4?dl=0

### "/ae plinfo" link

https://paste.md-5.net/icadukovib

**Comment by GC-spigot** [comment]
Resolved in recent versions

**Comment by SalomonPicos** [comment]
Hello. 

I tried with the latest version on spigot and it still bug when i don't shift click. If i drag and drop it won't apply it when i wear it but as soon as i unwear it it gives me the effect.
