### ISSUE TITLE
If you cannot identify cause of this, contact developer providing this report. 

### ISSUE THREAD

**Issue by WolfLiSteel** [GC-spigot/AdvancedEnchantments#3228]
### Describe the bug

! [Thu 19:31:08 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2520)
! [Thu 19:31:08 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1406)
! [Thu 19:31:08 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:240)
! [Thu 19:31:08 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:288)
! [Thu 19:31:08 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:111)
! [Thu 19:31:08 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:139)
! [Thu 19:31:08 WARN ]     at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor880.execute(Unknown Source)
 
! [Thu 19:31:08 WARN ]     at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
! [Thu 19:31:08 WARN ]     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
! [Thu 19:31:08 WARN ]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
! [Thu 19:31:08 WARN ]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:369)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:328)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:266)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1883)
! [Thu 19:31:08 WARN ]     at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
! [Thu 19:31:08 WARN ]     at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
! [Thu 19:31:08 WARN ]     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.TickTask.run(TickTask.java:18)
! [Thu 19:31:08 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
! [Thu 19:31:08 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
! [Thu 19:31:08 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
! [Thu 19:31:08 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandler.bq(IAsyncTaskHandler.java:114)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1445)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
! [Thu 19:31:08 WARN ]     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
! [Thu 19:31:08 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)
  [Thu 19:31:08 INFO  AdvancedEnchantments]    Class: AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2520)
  [Thu 19:31:08 INFO  AdvancedEnchantments]    Extra info: effect[SMELT:]; enchant [smelting]; mc[1191]; ae[9.0.0b80]
  [Thu 19:31:08 INFO  AdvancedEnchantments] If you cannot identify cause of this, contact developer providing this report. 
! [Thu 19:31:17 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2520)
! [Thu 19:31:17 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1406)
! [Thu 19:31:17 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:240)
! [Thu 19:31:17 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:288)
! [Thu 19:31:17 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:111)
! [Thu 19:31:17 WARN ]     at AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:139)
! [Thu 19:31:17 WARN ]     at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor880.execute(Unknown Source)
 
! [Thu 19:31:17 WARN ]     at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
! [Thu 19:31:17 WARN ]     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
! [Thu 19:31:17 WARN ]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
! [Thu 19:31:17 WARN ]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:369)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:328)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:266)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1883)
! [Thu 19:31:17 WARN ]     at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
! [Thu 19:31:17 WARN ]     at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
! [Thu 19:31:17 WARN ]     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.TickTask.run(TickTask.java:18)
! [Thu 19:31:17 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
! [Thu 19:31:17 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
! [Thu 19:31:17 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
! [Thu 19:31:17 WARN ]     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1289)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1177)
! [Thu 19:31:17 WARN ]     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
! [Thu 19:31:17 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)
  [Thu 19:31:17 INFO  AdvancedEnchantments]    Class: AdvancedEnchantments-9.0.0b80.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2520)
  [Thu 19:31:17 INFO  AdvancedEnchantments]    Extra info: effect[SMELT:]; enchant [smelting]; mc[1191]; ae[9.0.0b80]
  [Thu 19:31:17 INFO  AdvancedEnchantments] If you cannot identify cause of this, contact developer providing this report. 

### How to reproduce

Idk where this is from.

### "/ae plinfo" link

https://paste.md-5.net/eyewateyos

### Server Log

https://mcpaste.io/cf6c0f420fc7c791

**Comment by GC-spigot** [comment]
Resolved
