### ISSUE TITLE
BIG DUPE /ALCHM /ALCHEMIST

### ISSUE THREAD

**Issue by cynikhavoc** [GC-spigot/AdvancedEnchantments#3231]
### Describe the bug

You use the mod SimpleGUI and you delay packets(using the simplegui mod) while the /alchm and /alchemist window is open and you quick move in and out the item you want to dupe, when you close the GUI it dupes the items.
On latest version of AE, server version 1.19.3

### How to reproduce

You use the mod SimpleGUI and you delay packets(using the simplegui mod) while the /alchm and /alchemist window is open and you quick move in and out the item you want to dupe, when you close the GUI it dupes the items.
On latest version of AE, server version 1.19.3

### Screenshots / Videos

https://paste.md-5.net/ewudojayic

### "/ae plinfo" link

https://paste.md-5.net/ewudojayic

**Comment by cynikhavoc** [comment]
https://www.youtube.com/watch?v=1pFFtFZEHxg

Here is a video, time marker around 2:23

**Comment by GC-spigot** [comment]
Can you link me this SimpleGUI mod? I cannot find it anywhere

**Comment by cynikhavoc** [comment]
I don't have it, I was only watching someone who came to my server to dupe
use it.

**Comment by cynikhavoc** [comment]
This is still a problem, I have tens of people per day hop on my server and do the command /alchm trying to find a server to dupe on...

[Sun 09:47:47 INFO  Server/PlayerConnection] riggive0408 issued server command: /alchem
  [Sun 09:47:47 INFO ] riggive0408 doesn't have permission for: cmi.customalias.alchem
  [Sun 09:47:50 INFO  Server/PlayerConnection] riggive0408 issued server command: /alchemist:alchem
  [Sun 09:47:50 INFO ] riggive0408 doesn't have permission for: cmi.customalias.alchemist:alchem
  [Sun 09:47:53 INFO  Server/PlayerConnection] riggive0408 lost connection: Disconnected
  [Sun 09:47:53 INFO  Server] riggive0408 left the game

**Comment by GC-spigot** [comment]
> This is still a problem, I have tens of people per day hop on my server and do the command /alchm trying to find a server to dupe on...
> 
> [Sun 09:47:47 INFO Server/PlayerConnection] riggive0408 issued server command: /alchem [Sun 09:47:47 INFO ] riggive0408 doesn't have permission for: cmi.customalias.alchem [Sun 09:47:50 INFO Server/PlayerConnection] riggive0408 issued server command: /alchemist:alchem [Sun 09:47:50 INFO ] riggive0408 doesn't have permission for: cmi.customalias.alchemist:alchem [Sun 09:47:53 INFO Server/PlayerConnection] riggive0408 lost connection: Disconnected [Sun 09:47:53 INFO Server] riggive0408 left the game

Which version of the plugin are you using? 9.0.0b81 was supposed to fix that.

**Comment by cynikhavoc** [comment]
I was on a version before that, can't confirm if its fixed on the newer version though, ever since updating I've been getting this error spamming chat and console. I went back to my old version and now it still spams it. https://prnt.sc/1ZxA_Rzn9O6R

**Comment by GC-spigot** [comment]
Yeah in new versions TP_DROPS must specify to target the broken block, but we'll add a patch next version
