### ISSUE TITLE
OR function inside a condition not working

### ISSUE THREAD

**Issue by Il-Palazzo** [GC-spigot/AdvancedEnchantments#3232]
### Describe the bug

Having an OR function inside a condition wont work.
It will only work if the first condition is met and will ignore any other.
Taking an example from your webpage the enchantment will only work when attacking skeletons.

### How to reproduce

https://ae.advancedplugins.net/enchantments/enchantment-conditions/multiple-conditions

Just use this enchantment taken from your wiki with a skeleton and a zombie, it will work with the skeleton cause its the first one in the conditions list but all the others won't work.

holy:
  display: '%group-color%Holy'
  description: 'Deal more damage to undead mobs'
  applies-to: 'Swords'
  type: 'ATTACK_MOB'
  group: 'UNCOMMON'
  applies:
    - ALL_SWORD
  levels:
    1:
      condition:
        - '%mob type% = SKELETON : %allow% OR %mob type% = ZOMBIE : %allow% OR %mob type% = ZOMBIE_VILLAGER : %allow% OR %mob type% = WITHER : %allow% OR %mob type% = WITHER_SKELETON : %allow% OR %mob type% = ZOMBIFIED_PIGLIN : %allow% OR %mob type% = SKELETON_HORSE : %allow% OR %mob type% = ZOMBIE_HORSE : %allow% OR %mob type% = STRAY : %allow% OR %mob type% = HUSK : %allow% OR %mob type% = PHANTOM : %allow% OR %mob type% = DROWNED : %allow% OR %mob type% = ZOGLIN : %allow%
      effects:
        - 'ADD_HARM:<math>%level%*1.5</math> %victim%'

### Screenshots / Videos

Works fine when attacking a skeleton which is the first mobtype in the conditions
![image](https://user-images.githubusercontent.com/73161625/230049285-d79b1c35-1d1b-4980-be96-4f2336e886dc.png)

Simply not works when attacking a zombie which is inside the condition with an OR function
![image](https://user-images.githubusercontent.com/73161625/230049215-e43fd8be-c14e-4b99-a375-040768e3568d.png)

### "/ae plinfo" link

https://paste.md-5.net/qiyubiyeta

**Comment by GC-spigot** [comment]
Already fixed on 9.0.0+

**Comment by Il-Palazzo** [comment]
AE: 9.0.0b81 ?

**Comment by GC-spigot** [comment]
> AE: 9.0.0b81 ?

No, that's an old beta version, now latest version is 9.0.3
