### ISSUE TITLE
Geyser Duplication Bug

### ISSUE THREAD

**Issue by Dryixz** [GC-spigot/AdvancedEnchantments#3233]
### Describe the bug

Alchemist and possibly Tinkerer dupe bug with minecraft pe players (geyser)

### How to reproduce

In bedrock (PE) you type /alchemist and lets say you have a book instead of placing it on the free space you place it in the glasspane and it will of course instantly go to the free space after doing that you swap it again with the glasspane inside alchemist and it goes back to your inventory 2x

### Screenshots / Videos

https://user-images.githubusercontent.com/119065128/230462101-f92cb9be-2271-4e9a-967b-fd7bdd56e44b.mp4

![336658030_1259654027974780_6288159827714957104_n](https://user-images.githubusercontent.com/119065128/230462133-0e7b292e-3a49-4a98-9bcf-aa9e194dee18.jpg)

### "/ae plinfo" link

https://paste.md-5.net/uquxaholic

**Comment by nicogb2007** [comment]
I can confirm that that dupe works and it is really easy to do

**Comment by cynikhavoc** [comment]
This is essentially the same dupe I posted a week ago, except you have to use packet delay and it works on java...
