### ISSUE TITLE
Free Lava using Water Walker and BentoBox Skyblock/Oneblock.

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#3234]
### Describe the bug

Player's can turn what's supposed to be fake obsidian into an actual usable item (lava).

### How to reproduce

Get Water Walker on your boots
Walk on water, wait until there's a SINGLE (no more than one) obsidian block left
quickly scoop it up with a bucket.

This obsidian to bucket of lava feature is provided by BentoBox. This is for players who mess up their cobblestone generators.
However, either plugin should detect that that's not a legit obsidian block being generated by that enchantment.

### Screenshots / Videos

https://youtu.be/bUktOUarmUo

### "/ae plinfo" link

https://paste.md-5.net/lojoqawuli

### Server Log
https://mclo.gs/fTihVeg

**Comment by GC-spigot** [comment]
Unfortunately can't find a way to fix this, can you toggle this feature? That's the only way :(
