### ISSUE TITLE
netherite item in error

### ISSUE THREAD

**Issue by LeePC** [GC-spigot/AdvancedEnchantments#3235]
### Describe the bug

An error occurs when you hold an netherite sword and pickaxe tools

tested version 
This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)\nYou are running the latest version\nPrevious version: git-Purpur-1919 (MC: 1.19.3)

### How to reproduce

An error occurs when you hold an netherite sword and pickaxe tools

### "/ae plinfo" link

https://paste.md-5.net/abakijozes

### Server Log

https://mcpaste.io/8127d76d1f7bbf70

**Comment by GC-spigot** [comment]
Fixed!
