### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by norhu1130** [GC-spigot/AdvancedEnchantments#3236]
### Describe the bug

PaperMC 1.19.4 After installing the latest Advanced Entities 9.0.0 preview build from the latest build, an error occurs if you kill the entity.

### How to reproduce

1. Ensure 9.0.0 AdvancedEnchantments Preview Build
2. Kill Entity

### "/ae plinfo" link

https://paste.md-5.net/acafesuyey

### Server Log

https://mcpaste.io/6f9e7c287db25ad3

**Comment by YKDZ** [comment]
Found the same issue in my server.
https://mcpaste.com/387a3cf067fdfba6e7224060cb5d1f07

**Comment by GC-spigot** [comment]
Fixed!
