### ISSUE TITLE
Reforged Dupe Glitch

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#3238]
### Describe the bug
UPDATE: it have nothing to do with reforged, even after disabling reforged stuff still dupes, only downgrading the plugin to [9.0.0b81] fixed the dupe, it could be detonate or anything, please fix whatever changed on the new version.

Reporting a dupe glitch for some reason it makes use of reforged enchant, once you break a shulker you get 2 of them.

### How to reproduce

Place a shulker and break it with a pick that has reforged on it, make sure you are not opped.

### "/ae plinfo" link

https://paste.md-5.net/sajatijequ

**Comment by GC-spigot** [comment]
Looking into it

**Comment by Zekernn** [comment]
I can vouch for this as well. Huge problem, and the only thing that fixed it was downgrading.

**Comment by antibitcoin** [comment]
> I can vouch for this as well. Huge problem, and the only thing that fixed it was downgrading.

Yes but downgrading is throwing errors as I think the new version changed configs or something or just no good with 1.19.4, all my enchants are broke so I am waiting for them to patch this.

**Comment by GC-spigot** [comment]
We’re looking into it, will be fixed next update. This was a preview version and still in testing

**Comment by Mithranduil** [comment]
when will the update be released?

**Comment by GC-spigot** [comment]
> when will the update be released?

Later today

**Comment by Mithranduil** [comment]
> 

its not fixed, in the newest version its getting the same duplication bugs, new is the message that appears: https://prnt.sc/p2zhpkxbw-JJ

**Comment by GC-spigot** [comment]
Please record and show what dupes are you talking about, with latest version of plugin. Thank you!On 2023-04-14, at 06:20 PM, Mithranduil ***@***.***> wrote:﻿


its not fixed, in the newest version its getting the same duplication bugs, new is the message that appears: https://prnt.sc/p2zhpkxbw-JJ

**Comment by antibitcoin** [comment]
dupe still on 9.0.2 shulkers are getting duped, I proposed a fix in the past to blacklist all shulkers from trench and all kind of enchants if possible, it was implemented for trench but no idea it doesn't work now, it rather be blackslited on all enchants.

**Comment by GC-spigot** [comment]
> dupe still on 9.0.2 shulkers are getting duped, I proposed a fix in the past to blacklist all shulkers from trench and all kind of enchants if possible, it was implemented for trench but no idea it doesn't work now, it rather be blackslited on all enchants.

I am still unable to recreate it. Record a video.
