### ISSUE TITLE
armor bug

### ISSUE THREAD

**Issue by Tymiy** [GC-spigot/AdvancedEnchantments#3239]
### Describe the bug

The custom enchantments dont work on armor, they barrely let you wear the armor. 
on any armor piece now i cant put it on or take it off. the springs, gears, glowing anything that's supposed to admit a potion effect doesnt work. 

### How to reproduce

im not sure i just bought it and installed it and didnt have isseus till i found this. 

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/149BwjsEI14onX/d1337N2c3Bl9?invite=cr-MSxEMUgsNzMxMjQ4OTQs

### "/ae plinfo" link

https://medal.tv/games/minecraft/clips/149BwjsEI14onX/d1337N2c3Bl9?invite=cr-MSxEMUgsNzMxMjQ4OTQs

**Comment by GC-spigot** [comment]
I cannot reproduce this, you need to provide server version and plugin version with `/ae plinfo` link.

**Comment by Tymiy** [comment]
i reinstalled the plugin fully and i dont have the issue anymore, i think it may have been something to do with me editings things
