### ISSUE TITLE
EFFECT_STATIC works backwards when drag+dropping armour to equip

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3241]
### Describe the bug

When equipping via drag+dropping (rather than shift-clicking) a piece of armour with an EFFECT_STATIC enchantment, the effect is granted when the piece of armour is unequipped, and removed when it is equipped.

### How to reproduce

Enchant a piece of armour with an EFFECT_STATIC enchantment.
Drag+drop into into your armour slot.

### Screenshots / Videos

https://i.imgur.com/iMWhEZp.mp4

### "/ae plinfo" link

https://paste.md-5.net/otamizufij

**Comment by GC-spigot** [comment]
I cannot recreate it, it's working as expected. We'll be releasing an update today, let me know if that possibly fixes it for you.

**Comment by Dakotaa** [comment]
Went through my plugins to find if one was conflicting, and it seems that [WolfyUtilities](https://www.spigotmc.org/resources/wolfyutilities-core-plugin-api-1-16-1-19.64124/) is what's causing the issue. For what it's worth, it seems to only happen in survival mode; drag + drop equipping in creative doesn't cause the issue. I'll contact the developer and see if they can do anything about it.
