### ISSUE TITLE
aegive <nick> diamond_sword 1 allure:2 - error

### ISSUE THREAD

**Issue by KalviPL** [GC-spigot/AdvancedEnchantments#3242]
### Describe the bug

 aegive <nick> diamond_sword 1 allure:2
 
 command doesn't work
Command displays error in console

### How to reproduce

 aegive <nick> diamond_sword 1 allure:2

### Screenshots / Videos

https://mclo.gs/LxglnBh

### "/ae plinfo" link

https://paste.md-5.net/ajayaneyuq

### Server Log

https://mclo.gs/LxglnBh

**Comment by GC-spigot** [comment]
According to that error, there was no level input 
````
[21:28:36] [Server thread/INFO]: _Kalvi_ issued server command: /aegive _Kalvi_ diamond_sword 1 allure;
--
5 | [21:28:38] [Server thread/INFO]: _Kalvi_ issued server command: /aegive _Kalvi_ diamond_sword 1 allure

**Comment by KalviPL** [comment]
> According to that error, there was no level input
> 
> ```
> [21:28:36] [Server thread/INFO]: _Kalvi_ issued server command: /aegive _Kalvi_ diamond_sword 1 allure;
> --
> 5 | [21:28:38] [Server thread/INFO]: _Kalvi_ issued server command: /aegive _Kalvi_ diamond_sword 1 allure
> ```

https://mclo.gs/5x7SBdn

If I enter /aegive _Kalvi_ diamond_sword 1 allure;1 gives me an item without enchantment

/aegive _Kalvi_ diamond_sword 1 allure I got this command from your support on discord, when I said it was displaying an error I received a reply to report here
