### ISSUE TITLE
enchants-debug-mode and dupe of shulkers

### ISSUE THREAD

**Issue by jackeroficial** [GC-spigot/AdvancedEnchantments#3243]
### Describe the bug

the debug being in phase does not work the enchantments veins and telepathy duplicate items, for the moment we know that sun shulkers also the shovels and picks with trench break all kinds of blocks

### How to reproduce

the debug being false does not work and the enchantments telepathy and veins cause duping of shulkers

### Screenshots / Videos

https://cdn.discordapp.com/attachments/861299738690453525/1095813477857230958/WhatsApp_Image_2023-04-12_at_2.42.54_PM.jpeg

### "/ae plinfo" link

ae plinfo skipPlugin

**Comment by GC-spigot** [comment]
Should be resolved in next update
