### ISSUE TITLE
Dupe bugs AE 9,0,1 version

### ISSUE THREAD

**Issue by GatoronronYT** [GC-spigot/AdvancedEnchantments#3244]
### Describe the bug

I discovered 2 types of dupes, the dupe by enchantment to pickaxe and the dupe for enchantment to weapons/tools
I found like 4 enchantment for pickaxe that has dupe (moneygiving, trench, multiplication and soulminer) all of them dupes shulkers and as i've read "reforged" has dupe too

The second method is with the enchantment "permanency", it makes skeletons and zombies copy your weapons and drop a copy when are death, and for some reason if you kill a spider it do not copy the weapon but it drops a copy of your weapon when gets killed

I did not try all enchantments for pickaxe but i'm sure there are more enchantments with dupe for pickaxe...

### How to reproduce

1.- Use the enchantment with a pickaxe and break a shulker.
2.- Use the enchantment with a sword/pickaxe and attack a skeleton, zombie or spider.

### "/ae plinfo" link

https://paste.md-5.net/evuxapavuw

### Server Log

https://mcpaste.io/ff016205bcc345b8

**Comment by antibitcoin** [comment]
dupe still on version 9.0.2 confirmed with testing

**Comment by GC-spigot** [comment]
> dupe still on version 9.0.2 confirmed with testing

Still no proof of this dupe, record a video.

**Comment by cynikhavoc** [comment]
Shulker dupe still works on 9.0.5 with unbreakable, and trench.
