### ISSUE TITLE
Condition debug spam %attacker combo%

### ISSUE THREAD

**Issue by xcalma1** [GC-spigot/AdvancedEnchantments#3245]
### Describe the bug

![image](https://user-images.githubusercontent.com/35653864/232032713-e428909f-995e-4285-8ee8-e6731205d690.png)

It seems that this bug lags my server and I couldn't find it on any of the plugin's .yml files. Could someone explain this matter and help me towards this issue? 

### How to reproduce

![image](https://user-images.githubusercontent.com/35653864/232032813-2de6a6e9-74b9-4967-9be1-2800d25b72de.png)

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/35653864/232032813-2de6a6e9-74b9-4967-9be1-2800d25b72de.png)

### "/ae plinfo" link

https://paste.md-5.net/juyelikohi

**Comment by GC-spigot** [comment]
Hey! Sorry about this, we left debug enabled for Operators on the server - this is now resolved for next update!
