### ISSUE TITLE
aegive don't give ae enchantments

### ISSUE THREAD

**Issue by KalviPL** [GC-spigot/AdvancedEnchantments#3246]
### Describe the bug

aegive diamond_sword 1 allure:2 - command doesn't work
Command displays error in console

The command does not work, it does not give enchants on the item and the item itself appears. In addition, if I use it with enchantments from minecraft vanilla it works.

It was confirmed on discord together with Senior Moderator | Jben

### How to reproduce

aegive diamond_sword 1 allure:2

### "/ae plinfo" link

https://paste.md-5.net/pagavofexa

### Server Log

https://mclo.gs/nj5fVTz

**Comment by GC-spigot** [comment]
Fixed!
