### ISSUE TITLE
armor-items in config.yml not working

### ISSUE THREAD

**Issue by jaymesss** [GC-spigot/AdvancedEnchantments#3248]
### Describe the bug

Whenever adding "LEATHER-HORSE-ARMOR" to "armor-items.helmet" (I presume it doesn't work for any other armor types), nothing happens and it gives the "applying.wrong-material" error message.

![image](https://user-images.githubusercontent.com/52758545/232246747-8921204a-efe7-46f2-9e4a-b1a00ac86e97.png)
![image](https://user-images.githubusercontent.com/52758545/232246763-d0244ecf-9400-4a13-af86-4ff1e5c7d6b2.png)
![image](https://user-images.githubusercontent.com/52758545/232246771-ab92a8a9-8048-470f-b318-d37893a26a04.png)

### How to reproduce

Add LEATHER_HORSE_ARMOR to "armor-items.helmet" and run /ae enchant <helmetEnchant> <level> to get the "applying.wrong-material" message.

### "/ae plinfo" link

https://paste.md-5.net/zejevafilo

**Comment by GC-spigot** [comment]
Add leather_horse_armor for that specific enchantment applies-to item as well

**Comment by jaymesss** [comment]
I have tried that as well, still doesn't work.

![image](https://user-images.githubusercontent.com/52758545/232326028-16737530-02c5-4ebd-b85f-ec884fd071dc.png)

**Comment by jaymesss** [comment]
I added an egg there, and that seems to work, but leather horse armor does not.
![image](https://user-images.githubusercontent.com/52758545/232326201-a687536d-f168-4c1e-8e10-1fd11851cd82.png)
![image](https://user-images.githubusercontent.com/52758545/232326207-3cc5e345-7e38-4590-bb9c-6d8b439c2a41.png)

**Comment by GC-spigot** [comment]
Resolved!
