### ISSUE TITLE
Blackscroll bug

### ISSUE THREAD

**Issue by Anco0329** [GC-spigot/AdvancedEnchantments#3249]
### Describe the bug

If you use the black scroll, the enchantment will remain on the item and an enchantment book will be added to your inventory. Plugin version is latest.

### How to reproduce

If you use the black scroll, the enchantment will remain on the item and an enchantment book will be added to your inventory. Plugin version is latest.

### "/ae plinfo" link

https://paste.md-5.net/apuqosopol

**Comment by GC-spigot** [comment]
Resolved!
