### ISSUE TITLE
Issues we've found

### ISSUE THREAD

**Issue by Daphsquid** [GC-spigot/AdvancedEnchantments#325]
Hi there, 

We just got done testing out this plugin and configuring it for our server. We found a few issues with it and we wanted to report them here. Please tell me if these can be fixed via the config, I'd appreciate it! 

•    Detonate doesn’t apply any fortune effects
•    Telepathy always gives the maximum amount of items (e.g. always 3 coal instead of 1-3 coal)
•    Contrary to their description, the heroic enchantments work with ANY level of the previous ones (e.g. Inquisitive 1 is enough to add Master Inquisitive)
•    DOUBLE_DAMAGE effect doesn’t work properly (chance to deal less/no damage)
•    Effect EXP doesn’t spawn experience balls (e.g. Inquisitive)
•    Unfocus enchantment: messages of effect start and end appear at the same time
•    Plague Carrier enchantment: Creeper doesn’t deal damage, gives unlimited strength II effect
•    DISTANCE_DAMAGE (Assassin & Shadow Assassin): damage doesn’t change with distance
•    Detection of held items always gives a positive result (even if both players don’t even have such an item in their inventory) for Insanity, Farcast, Greatsword, Valor, Longbow, Armored, Paladinarmored, Heavy, Tank (it works for Farcast only,we are not sure why)

AdvancedEnchantments version: v5.2.0
PaperSpigot: 1.13.2

Thank you!

**Comment by GC-spigot** [comment]
Not all descriptions are accurate, they're done using CosmicPvP's enchantments idea but as close as it's possible with the plugin. 

I'll fix as many fixes as I can recreate, thanks for reporting!
