### ISSUE TITLE
Water Walker and Lava Walker trigger block breaks in AureliumSkills

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3250]
### Describe the bug

If I put lava walker or water walker on boots, put them on and walk across blocks, AureliumSkills thinks I'm breaking compatible blocks, leading to me gaining experience in skills such as excavation and mining even though I'm clearly not breaking blocks.

### How to reproduce

- Get boots of any kind
- /ae enchant lavawalker 1 OR /ae enchant waterwalker 1
- Walk on grass or stone
- Gain excavation or mining skill in AureliumSkills

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/39222968/232256815-488d48b8-717d-4fa3-8116-ae413d78bb92.png)
(As you can see, I haven't broken any blocks, I'm merely walking around and I'm gaining Excavation skill)

### "/ae plinfo" link

https://paste.md-5.net/sujirubegu

### Server Log

https://mcpaste.io/02a199dac7e3954e

**Comment by GC-spigot** [comment]
Resolved!
