### ISSUE TITLE
ArmorEquipEvent Error

### ISSUE THREAD

**Issue by Ogstel** [GC-spigot/AdvancedEnchantments#3252]
### Describe the bug

There's an issue where players can't remove or equip their armor because of the error below. 

### How to reproduce

I'm not sure how to reproduce this, but it happened after I released my server for the first time and players were able to use some AE enchants on armors which worked fine but they can't take it off as well as armors and elytras that have no AE enchants.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/130917794/232323534-af2922f1-97e2-4671-a739-46c83a357c10.png)

### "/ae plinfo" link

https://paste.md-5.net/ciyudoqaqu

### Server Log

https://mcpaste.io/0bdde29d63a06abe

**Comment by GC-spigot** [comment]
Fixed
