### ISSUE TITLE
Trench breaks everything in 3x3x3, not just compatible blocks

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3253]
### Describe the bug

Trench currently seems to break any block in a 3x3x3 area, not just compatible blocks.
So I can break dirt with my pickaxe that has trench and it breaks anything that's within 3x3x3.

### How to reproduce

- Get pickaxe
- '/ae enchant trench 9'
- Break any block

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/39222968/232337945-613f7316-3b6d-4604-b797-65e1053cf473.png)

### "/ae plinfo" link

https://paste.md-5.net/obovuyemek

### Server Log

https://mcpaste.io/2da9fcc14377cca0

**Comment by ArmonicPvP** [comment]
Can confirm this also happens to me

**Comment by GC-spigot** [comment]
Resolved
