### ISSUE TITLE
Trench and VeinMiner do not work with mcMMO

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#3257]
### Describe the bug

Trench and VeinMiner do not produce mcMMO double drops

### How to reproduce

Give mcMMO max level to always get double drops and use Veinminer or Trench to break blocks

### "/ae plinfo" link

https://paste.md-5.net/ixululenel

**Comment by GC-spigot** [comment]
Looking into this!

**Comment by cynikhavoc** [comment]
Trench also dupes full ore blocks, ex netherite blocks, emerald blocks etc, try only trench and fortune 3 and it will dupe 50% of the time, place and rebreak and repeat.

**Comment by GC-spigot** [comment]
Should be resolved!
