### ISSUE TITLE
Chest drops

### ISSUE THREAD

**Issue by Minerpro205** [GC-spigot/AdvancedEnchantments#3259]
### Describe the bug

Items inside of chests will not drop when broken by a custom enchanted item.

### How to reproduce

Very simply break any chest with items in it with a custom enchanted item. I don't know how many work, but I know reforged and timber cause this. It reminds me of the duplication bug in a previous version as it seems to be the same enchantments causing it.

### Screenshots / Videos

I don't have any screenshots, but it's pretty easy to test.

### "/ae plinfo" link

https://paste.md-5.net/wamuduzogu

### Server Log

https://mcpaste.io/d0769e70fa69dbac

**Comment by GC-spigot** [comment]
Fixed!
