### ISSUE TITLE
BREAK_BLOCK effect Error

### ISSUE THREAD

**Issue by SemenovEgo** [GC-spigot/AdvancedEnchantments#3261]
### Describe the bug

I made an enchantment that is supposed to instantly break a melon or pumpkin when I swing on it with an axe, it does not work

### How to reproduce

This is the enchantment I used
superharvester_enchantment:
  display: "%group-color%SuperHarvester"
  description: ""
  applies-to: "Axes"
  type: "SWING"
  group: "SIMPLE"
  applies:
    - ALL_AXE
  levels:
    1:
      condition: "%block type% = PUMPKIN or %block type% = MELON  : %allow%"
      effects:
        - "BREAK_BLOCK"

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/91209696/232559214-404e0df3-dc16-46f0-ab96-5d98918599a2.png)
![image](https://user-images.githubusercontent.com/91209696/232559276-58920049-1e59-407c-9039-bfb4c2525949.png)
![image](https://user-images.githubusercontent.com/91209696/232559319-fc097316-72cc-4597-8f5e-32bf058990ac.png)

### "/ae plinfo" link

https://paste.md-5.net/vehizokune

**Comment by GC-spigot** [comment]
We don't provide support for older versions, update
