### ISSUE TITLE
Mining with AE enchanted pickaxe duplicates spawners

### ISSUE THREAD

**Issue by kletico** [GC-spigot/AdvancedEnchantments#3262]
### Describe the bug

When mining spawners in combination with SilkSpawners_v2 Version 2.2.0, the spawner is duplicated. This does not occur with a non-AE enchanted pickaxe, and I am on AdvancedEnchantments version 9.0.4.
I have tested several enchants and have isolated which ones duplicate and which ones do not:

Enchantments that duplicate:
Experience 
Hasten
Smelting
Telepathy
Soul Miner
Rebreather
Reforged
Multiplication
Vein Miner
Replenish
Unbreakable 
Trench

Enchantments that do not duplicate:
Haste
Restore
SoulBound

### How to reproduce

-Needs SilkSpawners_v2 plugin 
On game mode survival, (creative conflicts with silk_spawners), 
With a silk-touch enchanted pickaxe that also has any of the conflicting enchants, such as reforged X, or Vein Miner III, mine any mob spawner.

### "/ae plinfo" link

https://paste.md-5.net/xegumuvefi

**Comment by HarisAli3** [comment]
Same goes for breaking spawners from rosestacker plugin.

**Comment by GC-spigot** [comment]
Should be fixed
