### ISSUE TITLE
inventory click event 

### ISSUE THREAD

**Issue by BLACKGAMER1221** [GC-spigot/AdvancedEnchantments#3266]
### Describe the bug

hi when i click on my inventory or any ae menu get this error https://mclo.gs/CShHBwh.
cant get enchants from enchanter menu and can steal items from premade menu.

### How to reproduce

click on your inventory or any ae menus with paper 1.13.2

### "/ae plinfo" link

https://paste.md-5.net/iqocufiruv

### Server Log

https://mclo.gs/CShHBwh

**Comment by reussy** [comment]
Heyo @BLACKGAMER1221,

Attach the link that **/ae plinfo** gives you. This happens because you are using CraftBukkit or a fork other than Spigot / Paper.

**Comment by BLACKGAMER1221** [comment]
plinfo link added and i use paper

**Comment by GC-spigot** [comment]
Fixed!
