### ISSUE TITLE
Veinminer issue

### ISSUE THREAD

**Issue by CrystallizedAtrophy** [GC-spigot/AdvancedEnchantments#3267]
### Describe the bug

Veinminer not working on [9.0.5]
Only enchant on pickaxe is Veinminer.

### How to reproduce

Update to latest version

### Screenshots / Videos

https://gyazo.com/88ad766858f892b8cd2c06891d7ee839

### "/ae plinfo" link

https://paste.md-5.net/ivilidibeg

### Server Log

https://mcpaste.io/6854851a4664d3a4

**Comment by Truongvv10** [comment]
Can confirm, using 9.0.5 vienminer isn't working

**Comment by murut87** [comment]
can confirmed also, and also make server lagged by using it.
https://pastebin.pl/view/aac48cf5

**Comment by GC-spigot** [comment]
Fixed
