### ISSUE TITLE
Chest breaking

### ISSUE THREAD

**Issue by Minerpro205** [GC-spigot/AdvancedEnchantments#3268]
### Describe the bug

I made an issue request about this a day or so ago, it was marked as fixed but the issue is still here. Breaking chests with a custom enchanted tool won't drop items from it on plugin version 9.0.5

### How to reproduce

Same as before, break a chest with a custom enchanted tool. Reforged and timber do this for me, more may do it though.

### Screenshots / Videos

~~Still no screenshots, easy to reproduce though.~~ Actually no screw that, [here](https://www.youtube.com/watch?v=7v0m0U4PBf4).

### "/ae plinfo" link

https://paste.md-5.net/axubuxaqaq

### Server Log

https://mcpaste.io/c073b34a4e64b75b

**Comment by Truongvv10** [comment]
I have this issue too, this appears when I have experience enchant.

![image](https://user-images.githubusercontent.com/67742370/232872699-4051587e-25d5-4eec-b041-dc9c38ca8767.png)

**Comment by Truongvv10** [comment]
It also dupes custom blocks from itemsadder

**Comment by reussy** [comment]
Hey, patched for the next update.


> It also dupes custom blocks from itemsadder
Please make a separate issue report detailing the dupes with a video demonstration.
