### ISSUE TITLE
Duping Issue with combination enchantments

### ISSUE THREAD

**Issue by Zoneman1972** [GC-spigot/AdvancedEnchantments#327]
There is an issue with Telepathy and Fortune on a pick.
 Using this combination on ores, doubles/triples the amount of ore you get. eg, place 1 iron ore block, mine it and get 3 back, place the 3, mine them and get 10 back, place the 10, mine them and get 31 back. As you can guess, this is a huge duping issue.
And yes, this is the latest version  5.2.2, just installed and tested.

**Comment by newbie029** [comment]
I got same problem, can you @gc fix it asap? Many player know the bug

**Comment by GC-spigot** [comment]
Will be fixed in ~3 minutes.

**Comment by newbie029** [comment]
It's not only happen with ore btw
It happen with any block,
but I'll try the new update to see if it fixed

**Comment by xDacon** [comment]
^ just tested with diamond blocks and still works

**Comment by newbie029** [comment]
Yes, I go back using v5.2.0.
Fortune support for trench is not a good idea, Willa just cause dupe
