### ISSUE TITLE
Telepathy and reforged not giving back blocks

### ISSUE THREAD

**Issue by Arcadegtech** [GC-spigot/AdvancedEnchantments#3270]
### Describe the bug

Telepathy and reforged not giving back blocks when they are on a item.
blocks wont come in inventory or on ground

### How to reproduce

try enchanting Telepathy and reforged

### "/ae plinfo" link

https://paste.md-5.net/yemogedama

**Comment by reussy** [comment]
Hi @Arcadegtech,

Could you add more information or a demo video, I fail to replicate your problem.
You can try using the option **enchants-debug-mode** in config.yml:
```yaml
enchants-debug-mode: true
```

**Comment by GC-spigot** [comment]
Working fine, still try updating to the new update we're posting soon. 
https://gyazo.com/093e9a81d4942903fd73a0380a84c7ff

**Comment by LeePC** [comment]
https://user-images.githubusercontent.com/8704225/233292398-5cc2de3c-97a5-470b-86b6-0533ba03caf5.mp4

enchant debug mode on....not message
telepathy 4 enchant not ..... fix please

**Comment by GC-spigot** [comment]
Debug mode is disabled right nowOn 2023-04-20, at 10:30 AM, LeePC ***@***.***> wrote:﻿
https://user-images.githubusercontent.com/8704225/233292398-5cc2de3c-97a5-470b-86b6-0533ba03caf5.mp4
enchant debug mode on....not message
telepathy 4 enchant not ..... fix please

**Comment by Arcadegtech** [comment]
i guess leepc has showed the problem in video.
