### ISSUE TITLE
Enchantments get removed after world change

### ISSUE THREAD

**Issue by Disorbs** [GC-spigot/AdvancedEnchantments#3271]
### Describe the bug

On the new version and the one before i think its was caused it not sure. But when players switch worlds like TP to spawn and nether or end they enchantments stop working and the player has to take off the armor and put it back on every time they switch worlds.

### How to reproduce

Get new update add jump and speed and vision/glow on your helmet and when its activated teleport to another world and now the effects are gone until you remove the armor and put them back on there for activating them again.

### Screenshots / Videos

https://i.gyazo.com/c14e57efaa4c11fe17c609e2400b1e8e.gif

### "/ae plinfo" link

https://paste.md-5.net/omotumucup

**Comment by reussy** [comment]
Hey, patched for the next update.
