### ISSUE TITLE
Error [17:04:37 ERROR]: Could not pass event I

### ISSUE THREAD

**Issue by dei15** [GC-spigot/AdvancedEnchantments#3272]
### Describe the bug

![im32age](https://user-images.githubusercontent.com/99554686/233032501-5aa48670-43ca-4fe7-b0ca-20ef1199916f.png)
![ima32ge](https://user-images.githubusercontent.com/99554686/233032531-913e5f9b-07cd-4c36-bc98-01a0af7db89a.png)

### How to reproduce

not sure

### Screenshots / Videos

![im32age](https://user-images.githubusercontent.com/99554686/233032648-616d118c-2bc8-4300-b86e-760b4223e731.png)
![ima32ge](https://user-images.githubusercontent.com/99554686/233032751-0938aa41-2804-47b4-a22a-efb346354151.png)

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by GC-spigot** [comment]
Enchantment group issues, invalid group is set for an enchant somewhere
