### ISSUE TITLE
Duping using Silk Touch

### ISSUE THREAD

**Issue by murut87** [GC-spigot/AdvancedEnchantments#3273]
### Describe the bug

You can dupe by using Silk Touch.

### How to reproduce

Enchant any Tools with Silk Touch > Break Enchanted Bookshelves > You get Double

Tools I used : Netherite Pickaxe
Enchant : Efficiency 5, Mending, Silk Touch, Unbreaking 3, Experience IV, Telepathy 4, Reforged X, Replenish 2, Vein Miner 3.

### "/ae plinfo" link

https://paste.md-5.net/oyelefecoj

**Comment by GC-spigot** [comment]
Fixed
