### ISSUE TITLE
Anvils take book away when renaming

### ISSUE THREAD

**Issue by Disorbs** [GC-spigot/AdvancedEnchantments#3274]
### Describe the bug

A player tries to combine silktouch to something that has fortune while RENAMING the item as well and it goes through but its not suppose to and results in the player loosing a book because vanilla doesn't do silktouch + fortune. Its a small issue but some people keep doing it by accident and would be nice to get it fixed.

### How to reproduce

Get a tool that has fortune and a enchanted book with silktouch

Go on the anvil and add both and it wont work but if the player also happens to switch the name now the item goes through
resulting in loosing the item.

### Screenshots / Videos

Vanillia no AE: https://i.gyazo.com/e075e0fcfbdb5bdcb3906a9053a265f6.png

With AE: https://i.gyazo.com/1d585dbca30bda517891907d4dcd6cfa.png

### "/ae plinfo" link

https://paste.md-5.net/apakicovut

**Comment by Disorbs** [comment]
bump

**Comment by GC-spigot** [comment]
Looking into it!

**Comment by GC-spigot** [comment]
Fixed
