### ISSUE TITLE
Permanent effects get removed when switching worlds

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3275]
### Describe the bug

By going from the overworld to the nether while wearing any enchantment that gives you a permanent effect (such as glowing) it will no longer be applied when entering the other world.

### How to reproduce

- Get helmet
- Enchant helmet with glowing 1
- Wear helmet
- Go from overworld to nether (through portal)
- See how there is no permanent effect anymore

### Screenshots / Videos

(Hopefully not required)

### "/ae plinfo" link

https://paste.md-5.net/efemexebal

### Server Log

https://mcpaste.io/7a92114566cde119

**Comment by GC-spigot** [comment]
Fixed!
