### ISSUE TITLE
Trench Dupe

### ISSUE THREAD

**Issue by newbie029** [GC-spigot/AdvancedEnchantments#328]
https://streamable.com/wzlfc

Trench dupe 
edit
Detonate + Fortune cause dupe

AdvancedEnchantments v5.2.3

**Comment by newbie029** [comment]
I downgrade to v5.2.0 and it now working correctly
Please fix it, I prefer to use latest version

**Comment by newbie029** [comment]
Can you just make option in the config to enable or disable fortune support for trench? It only cause dupe

**Comment by Kbryst** [comment]
-I placed 9 stone, broke with silk touch and detonate pickaxe
-Received 9 stone and 8 cobble. 

Same plugin version.

**Comment by Krosta8** [comment]
I can confirm that too.
If you have only detonate with fortune, it will dupe everything. 
In addition.
With only detonate: Sometimes, if you destroy 9x Stone (example), you will get 8x Cobble

**Comment by newbie029** [comment]
Right, I have tested it. Detonate and Fortune is the problem

**Comment by GC-spigot** [comment]
Fixed.
