### ISSUE TITLE
Enchantments don't work on golden armour or tools

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3282]
### Describe the bug

Enchants do not seem to trigger when on golden tools/armour. Work fine on all other types of tools/armour. Not sure if this is once again an issue with how they're defined in armor-items in config.yml (in the past I've had to change the material there), but I've tried both GOLD_ and GOLDEN_ prefixes and neither work.

### How to reproduce

Enchant a golden tool/armour with an Advanced Enchantment
Try to trigger the enchantment
Nothing happens

### "/ae plinfo" link

https://paste.md-5.net/xekamiqive

**Comment by Truongvv10** [comment]
Can confirm this happening!

**Comment by GC-spigot** [comment]
Fixed!
