### ISSUE TITLE
TRENCH effect is inconsistent when CompatNoCheatPlus is installed

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3283]
### Describe the bug

When using a pickaxe with the Trench effect, the correct area is not always broken. It seems to only happen when blocks are mined too quickly. If the player waits a moment before mining another block, it works fine. Happens with both the TRENCH:3 and CUSTOM_TRENCH:3:3:3 effects.

This seems to be the same issue as #1938, where it turned out to be a NoCheatPlus/CompatNoCheatPlus issue, but was eventually fixed.

### How to reproduce

Enchant a tool with a TRENCH enchantment.
Break blocks without letting go of left-click.
Trench breaks after the first will not break all the blocks it should.

### "/ae plinfo" link

https://paste.md-5.net/xekamiqive

**Comment by Dakotaa** [comment]
Confirmed this issue only happens when CompatNoCheatPlus is installed.

**Comment by reussy** [comment]
Hey, patched!
