### ISSUE TITLE
TRENCH effect does not consider unbreaking

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3284]
### Describe the bug

When a tool with a TRENCH effect is used, it does not consider the unbreaking level of the tool when changing the durability. e.g. using a TRENCH effect with a tool with Unbreaking X will still remove 18 durability when breaking 18 blocks.

### How to reproduce

Enchant a tool with a TRENCH effect enchantment and unbreaking
Break blocks
The tool will take full durability dmaage as if it didn't have unbreaking

### "/ae plinfo" link

https://paste.md-5.net/xekamiqive

**Comment by GC-spigot** [comment]
Resolved
