### ISSUE TITLE
MINING enchantments trigger two block break events

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3285]
### Describe the bug

When breaking a block with a MINING type enchantment, it appears that two block break events are triggered, both with the event block being the block being broken (the second event isn't being triggered with air as the event block).

This is causing issues with other plugins that listen for block breaking, e.g. giving additional crop drops.

### How to reproduce

Enchant a tool with a MINING type enchantment
Break a block
Two block break events will be triggered

### "/ae plinfo" link

https://paste.md-5.net/xekamiqive

**Comment by GC-spigot** [comment]
Resolved
