### ISSUE TITLE
PLANT_SEEDS Effect does not remove seeds from armour slots, but still plants 

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3286]
### Describe the bug

When using a PLANT_SEEDS enchant, if the player has the seed items in their armour slot(s) (through /hat or similar commands), the seeds will be counted and the plant will happen, but the seeds are not removed from their inventory.

### How to reproduce

Put seeds in your armour slot.
Use a PLANT_SEEDS tool
The seeds will be planted, but not taken from the inventory.

### "/ae plinfo" link

https://paste.md-5.net/xekamiqive

**Comment by GC-spigot** [comment]
Fixed
