### ISSUE TITLE
EFFECT_STATIC potion effects lost when losing same effect after unequipping HELD enchantment item 

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3287]
### Describe the bug

If you're wearing a piece of armour with an EFFECT_STATIC enchantment giving a potion effect (e.g. a helmet giving night vision), unequipping a tool with a HELD enchantment giving the same effect (e.g. a pickaxe giving night vision) will remove the effect entirely, when you should still have it since you're still wearing the armour that gives it.

Same issue as #2046 

### How to reproduce

Wear a piece of armour giving an EFFECT_STATIC potion effect
Equip a tool with a HELD enchant giving the same effect
Unequip the tool
The potion effect will be lost, even though you're still wearing the EFFECT_STATIC armour

### "/ae plinfo" link

https://paste.md-5.net/xekamiqive

**Comment by reussy** [comment]
Hey, patched!
