### ISSUE TITLE
telepathy enchant bug....

### ISSUE THREAD

**Issue by LeePC** [GC-spigot/AdvancedEnchantments#3289]
### Describe the bug

debug mode on......
but message not print

### How to reproduce

tested version : purpur 1.19.4 latest version

### Screenshots / Videos

https://user-images.githubusercontent.com/8704225/233293215-492a5548-45ca-4cf7-b0a1-10ff024085dc.mp4

### "/ae plinfo" link

https://paste.md-5.net/eweligisas

**Comment by GC-spigot** [comment]
Resolved!
