### ISSUE TITLE
Telepathy Dupe

### ISSUE THREAD

**Issue by CrystallizedAtrophy** [GC-spigot/AdvancedEnchantments#3291]
### Describe the bug

Telepathy dupes containers on latest version.

### How to reproduce

Use AdvancedEnchantments-9.0.6.jar and then use telepathy on containers.

### Screenshots / Videos

https://youtu.be/oISEM1_1I-4

### "/ae plinfo" link

https://paste.md-5.net/lihadejesu

### Server Log

https://mcpaste.io/7bb92b2ca287ba7c

**Comment by Truongvv10** [comment]
I have this issue too..........

**Comment by cynikhavoc** [comment]
Shocked this has been unconfirmed for 4 days when hundreds or thousands of servers have paid for this plugin and there is this absolutely server destroying, game breaking bug.

Happens on my server, and my test server.

**Comment by GC-spigot** [comment]
> Shocked this has been unconfirmed for 4 days when hundreds or thousands of servers have paid for this plugin and there is this absolutely server destroying, game breaking bug.
> 
> Happens on my server, and my test server.

Hey! We're working on improving the system a lot, this issue has been confirmed internally just we haven't had a chance to mark it - it's going to be resolved in an update today

**Comment by GC-spigot** [comment]
Fixed!
