### ISSUE TITLE
Enchanted Pick doesnt work

### ISSUE THREAD

**Issue by TheSquidHQ** [GC-spigot/AdvancedEnchantments#3292]
### Describe the bug

Whenever I enchant a pickaxe with a AE enchant, it stops picking up items

### How to reproduce

Enchant any pickaxe with any enchant.

### Screenshots / Videos

https://www.youtube.com/watch?v=MUMuKCK1ug8

### "/ae plinfo" link

https://paste.md-5.net/riwibofidu

### Server Log

https://mcpaste.io/b6f518fb68154aba

**Comment by GC-spigot** [comment]
Fixed

**Comment by TheSquidHQ** [comment]
I updated the plugin and it still doesnt work. Armor enchants now work though
