### ISSUE TITLE
error plugins!!!AdvancedEnchantments 9.0.6

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3293]
### Describe the bug

spam error plugins
Enchant: inquisitive:
      This charm!!! broken!!! why does it change the experience even from other plugins!!! it causes a bunch of dupes!! dup experience for example

### How to reproduce

-

### "/ae plinfo" link

https://paste.md-5.net/fuliconire

### Server Log

https://mcpaste.io/8d7a85df7a8a6f66

**Comment by GC-spigot** [comment]
Fixed
