### ISSUE TITLE
[23:44:34 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v9.0.6

### ISSUE THREAD

**Issue by dei15** [GC-spigot/AdvancedEnchantments#3295]
### Describe the bug

Spam error in console

### How to reproduce

Not sure

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/99554686/233679379-6865a131-2f3b-4c8a-969f-405c038ca914.png)
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/11297352/latest.log)

### "/ae plinfo" link

https://paste.md-5.net/igowobubed

### Server Log

cant paste server logs here pasted up there

**Comment by GC-spigot** [comment]
This is related with your AOE configuration, next update will now have a warning to inform you what the issue is
