### ISSUE TITLE
Blocks being deleted when mined or dug with tools that have AE enchants

### ISSUE THREAD

**Issue by kletico** [GC-spigot/AdvancedEnchantments#3296]
### Describe the bug

Advanced enchantments version 9.0.6 is in conflict with the SlimeFun plugin (Version RC - 33 (git 0830fc6d) ), and blocks are being deleted when mined with an AE enchanted tool. This does not occur with normally enchanted tools and does not occur with the Haste enchantment. I have tested the following enchants on pickaxes and shovels (when applicable) here are the conflicting enchants:

Conflicting:
Unbreakable 
replenish
experience
telepathy
trench
vein miner
Hasten
Soul Miner
Multiplication
reforged
rebreather
smelting

Non-Conflicting:
Haste

### How to reproduce

-Requires SlimeFun Version RC - 33 (git 0830fc6d) to test

In survival mode, holding a pickaxe or shovel enchanted with any of the conflicting AE enchants such as unbreakable, break any block such as dirt or stone.

### "/ae plinfo" link

https://paste.md-5.net/xofihujalo

**Comment by GC-spigot** [comment]
Seems to be resolved in latest versions, we did a lot of reworks so that *may* be the reason. If this happens after 9.0.7 tag me @GC-spigot and I'll reopen this issue https://gyazo.com/411ff96e43cb8903f0b1d0bace517525
