### ISSUE TITLE
Other issues with BREAK_BLOCK and @Block as target

### ISSUE THREAD

**Issue by CrystallizedAtrophy** [GC-spigot/AdvancedEnchantments#3297]
### Describe the bug

Have enchant Obsidian Destroyer and it gives a error in console and does not break the block.

[obsidian destroyer.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/11299763/obsidian.destroyer.txt)
[error log.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/11299764/error.log.txt)

### How to reproduce

Have enchant Obsidian Destroyer and try to mine with it.

### "/ae plinfo" link

https://paste.md-5.net/ocexezugon

### Server Log

https://mcpaste.io/b66f8e18b108a9d3

**Comment by Truongvv10** [comment]
I have this issue too

**Comment by GC-spigot** [comment]
Fixed
