### ISSUE TITLE
Pickaxe dupes

### ISSUE THREAD

**Issue by GatoronronYT** [GC-spigot/AdvancedEnchantments#3298]
### Describe the bug

1.- When you pickaxe a bookshelf with trench/moneygiver enchant + silktouch it gives you 3 bookshelfs and not books, so you can triplicate bookshelfs.
2.- When you pickaxe spawners with trench/silktouch it will give you the spawner triplicated even if you DON'T have permission to break spawners...

### How to reproduce

Enchant a pickaxe with trench/moneygiver + silktouch or trench + silktouch and break bookshelfs and spawners.

### Screenshots / Videos

https://user-images.githubusercontent.com/128557960/233764436-12d4694f-1c6c-417d-af81-b6967ba7a20e.mp4

https://user-images.githubusercontent.com/128557960/233764438-44c0bab0-23b9-443b-bce5-de473fe9b2ba.mp4

### "/ae plinfo" link

https://paste.md-5.net/ejehulufoc

**Comment by GC-spigot** [comment]
Already fixed.. update.
