### ISSUE TITLE
Armor throwing NPE

### ISSUE THREAD

**Issue by Ogstel** [GC-spigot/AdvancedEnchantments#3299]
### Describe the bug

Gives a long list of warning in console when switching a player head to off hand

### How to reproduce

Equip a player head or skull in your off hand then it will pop warnings

### Screenshots / Videos

![Screenshot 2023-04-23 000250](https://user-images.githubusercontent.com/130917794/233794771-1828ff5d-3b54-4f9c-a36f-a65da441bfce.png)

### "/ae plinfo" link

https://paste.md-5.net/etumecedij

**Comment by GC-spigot** [comment]
Resolved
