### ISSUE TITLE
[FEATURE] Soulbound/holywhitescroll related stuff

### ISSUE THREAD

**Issue by PengBread** [GC-spigot/AdvancedEnchantments#330]
Hello GC, i have suggestions here.

- Add the "holy white scroll lore" to custom items ourself and make the item soul bounded instead of using a holywhitescroll on it.

- Able make the holywhitescroll effect protected forever even after death the effect will still be on the item.

**Comment by GC-spigot** [comment]
First is already editable, 2nd will be next update (http://prntscr.com/mo4smd)
