### ISSUE TITLE
TP_DROPS damages axes, pickaxes, shovels when breaking crops

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3303]
### Describe the bug

TP_DROPS enchantments still damage axes, pickaxes, and shovels when breaking crops (these tools are not damaged without the enchantment).

### How to reproduce

Enchant an axe with a TP_DROPS enchantment
Break fully grown wheat.
Tool will take durability damage when it shouldn't

### "/ae plinfo" link

https://paste.md-5.net/zowewogudi

**Comment by GC-spigot** [comment]
Fixed
