### ISSUE TITLE
Implants give food too fast

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3305]
### Describe the bug

When I'm wearing a helmet with implants on them, I'm gaining food/hunger bars way faster than it was before 9.0.0

Also basically making it useless to get anything higher than level 1 of the enchantment.

### How to reproduce

- Get some hunger
- Get a helmet
- Enchant with Implants 1
- Observe how it rapidly fills up your hunger bar

### Screenshots / Videos

Hopefully not required as this is something easy to explain even with just words :)

### "/ae plinfo" link

https://paste.md-5.net/ibubibokev

### Server Log

https://mcpaste.io/56c12d87049d2710

**Comment by GC-spigot** [comment]
Have you configured new REPEATING trigger properly? You need to set time per-level now instead of for whole enchant, E.g.:
```yaml
implants:
  display: '%group-color%Implants'
  description: Chance to restore food every few seconds.
  applies-to: Helmets
  type: REPEATING
  group: ULTIMATE
  applies:
    - ALL_HELMET
  levels:
    '1':
      chance: 30
      time: 5
      effects:
        - ADD_FOOD:1
