### ISSUE TITLE
Renaming chest to alchemist and spam openning it will cause a dupe

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#3307]
### Describe the bug

if any chest get renamed to alchemist and you place stuff on slot 4 and 6 than open it you dupe any items inside of it.

Please fix asap

### How to reproduce

if any chest get renamed to alchemist and you place stuff on slot 4 and 6 than open it you dupe any items inside of it.

### Screenshots / Videos

https://prnt.sc/GQHVAgeOrRLR
https://prnt.sc/_WkcTY2SZ6MR

### "/ae plinfo" link

https://paste.md-5.net/eholigoxos.css

**Comment by antibitcoin** [comment]
update:
putting item on slot 4 or 6 with number key and spam open chest cancceled trade and alchem doesnt clear item

also it works for dispenser, hopper, shulker, chest, trapped chest and basically any item with inventory, barrels included.

**Comment by antibitcoin** [comment]
I have created my own patch for plugin for this, when people open any inventory named Alchemist and its not actually the alchemist they get an error saying "&cSorry but I am not an alchemist". 

but I hope it get fixed on the main plugin soon.

regards

**Comment by GC-spigot** [comment]
Patched! Thank you for reporting
