### ISSUE TITLE
AE not using ItemsAdder custom durability

### ISSUE THREAD

**Issue by OrdenDesLOGO** [GC-spigot/AdvancedEnchantments#3309]
### Describe the bug

Advanced Enchantments is not using the durability from itemsadder items.
ItemsAdder works like this: They create an alternate texture for an item and then add their custom durability, 
but AE uses the durability of the item that is being replaced with an alternate texture. Which means custom durability cant be used which is very bad.

### How to reproduce

Uses ItemsAdder and AE and use a custom durability for an IA item then enchant it with an ae enchantment

### "/ae plinfo" link

https://paste.md-5.net/ahiridopop

**Comment by matipoirierg** [comment]
can confirm this is very sad ae is considering all armor like leather durability

**Comment by OrdenDesLOGO** [comment]
Please its very important since its not possible to use the plugin on servers that use items adder

**Comment by GC-spigot** [comment]
Added!
