### ISSUE TITLE
Griefing another player's island

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3311]
### Describe the bug

By firing a bow or crossbow you can kill mobs on the player's foreign island (AOneBlock, BentoBox). Maybe you can also destroy blocks.

### How to reproduce

Have a crossbow with Missile I or Hellfire II enchantment and shoot the mob and the mob will take damage (die).

### "/ae plinfo" link

https://paste.md-5.net/eterexegiq

**Comment by GC-spigot** [comment]
Looking into this!
