### ISSUE TITLE
Effect water walker does not disappear

### ISSUE THREAD

**Issue by rinasuzuki** [GC-spigot/AdvancedEnchantments#3312]
### Describe the bug

Player not wear any armor but still have effect and not disappear

### How to reproduce

After update to latest Minecraft version 1.19.4 and latest plugin version then this happen for few player

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1101479584513396766/1101479783126282271/Base_Profile_2023.04.28_-_20.02.55.01.mp4

### "/ae plinfo" link

https://paste.md-5.net/umiyoleyis

**Comment by Truongvv10** [comment]
I have this issue occurring on my server with my players too, please check this video out https://streamable.com/qr3y0s

**Comment by GC-spigot** [comment]
Fixed!
