### ISSUE TITLE
Different chance for multiple item drops 

### ISSUE THREAD

**Issue by BadLemon96** [GC-spigot/AdvancedEnchantments#3315]
### Describe the bug

I can not create a mob to drop multiple different items, with a specific chance for each said items. I created a ticket on the Discord serve but was advised this is not currently implemented with the plugin. For example, 

mobs:
#  ZOMBIE:
#    chance: 75
#    items:
#      - "randomenchantmentbook:1"

Works just fine of course, but if I wanted to add say "transmog:1" I can not set the chance for just that item, it is going to be stuck at 75%. 

### How to reproduce

I tried,

mobs:
  ZOMBIE:
    items:
      - item: "randomenchantmentbook:1"
        chance: 50
      - item: "transmog:1"
        chance: 25

but it does not work. 

### "/ae plinfo" link

Server currently offline

**Comment by GC-spigot** [comment]
Looking into this, should be reworked soon!
