### ISSUE TITLE
AE doesn't recognize PAPI placeholders.

### ISSUE THREAD

**Issue by ehfowefasfjtut** [GC-spigot/AdvancedEnchantments#3317]
### Describe the bug

AE doesn't recognize PAPI placeholders.
the new version give errors with placeholders and don't work for examples with aureliumskills api like in the past it did
also with custom plugins api 

### How to reproduce

those are some enchant showing the issue, as example:

bloodmoons:
  display: '&4Durante la Luna Insanguinata:'
  description: 'aad'
  applies-to: 'piccone'
  group: 'FABLED' 
  type: 'ATTACK_MOB;ATTACK'
  applies:
    - 'ALL_SWORD'
  levels:
    '1':
      chance: 100
      conditions:
        - "%player bloodmoonapi_status% = false : %allow%"
      effects:
        - ACTION_BAR:&fHai attivato l'abilità {#19171a}&lAvvizzimento @Attacker
        - NEGATE_DAMAGE _HARM:10 @Victim

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by GC-spigot** [comment]
Fixed!

**Comment by ehfowefasfjtut** [comment]
> Fixed!
tried, not working:
blazelord:
  display: '&6Palla di fuoco'
  description: 'aad'
  applies-to: 'piccone'
  group: 'FABLED'
  type: 'RIGHT_CLICK'
  applies:
    - 'ALL_SWORD'
  levels:
    '1':
      chance: 100
      cooldown: 10
      conditions:
        - "%player aureliumskills_mana% >= 14 : %allow%"
      effects:
        - ACTION_BAR:&fHai attivato l'abilità &6Palla di fuoco @Attacker
        - PLAY_SOUND:ENTITY_BLAZE_SHOOT @Attacker
        - PLAY_SOUND:ENTITY_BLAZE_SHOOT @Aoe{radius=5,target=all}
        - CONSOLE_COMMAND:mana remove %attacker name% 20 true 
        - PROJECTILE:FIREBALL:3 @Attacker
        - WAIT:10
        - PLAY_SOUND:ENTITY_BLAZE_SHOOT @Attacker
        - PLAY_SOUND:ENTITY_BLAZE_SHOOT @Aoe{radius=5,target=all}
        - PROJECTILE:FIREBALL:3 @Attacker
        - WAIT:390
        - ACTION_BAR:&2Abilità &6Palla di fuoco &2pronta @Attacker

**Comment by GC-spigot** [comment]
Finally resolved! Sorry about the wait
