### ISSUE TITLE
Error Effect of "CANCEL_USE" and "TAKE_AWAY" 

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3318]
### Describe the bug

I tried using teleblock with my bow but it seems like if the arrow hit to the player, it doesn't do the effect as it throws the error in the console as you can see in the server log that i sent.

### How to reproduce

Just put the teleblock ce in to your bow, then use it against to someone. (You may put the chances to 100, so it will be faster to see the effect itself) after that, it should replicate the error from what i have sent to the server log.

### "/ae plinfo" link

https://paste.md-5.net/ukocudubuk

### Server Log

https://mcpaste.io/1afcb4a447d45d24

**Comment by GC-spigot** [comment]
CANCEL_USE was removed with v9, now being readded - will be back next update!
