### ISSUE TITLE
Dupe Bug in Effect of "REMOVE_SOUL @Attacker/Victim and ADD_SOUL @Attacker/Victim"

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3322]
### Describe the bug

So when i tried on using CosmicPvP Enchantment.yml, and tested out the soul siphone CE. I noticed that if the attacker didn't have any armor and the attacker attack the victim (who have soul siphone CE on his/her armor), The boots just dupe itself. I believe it's something to do with "REMOVE_SOUL" and i suppose it has the same function as "ADD_SOUL" 

### How to reproduce

soulsiphone:
  display: '%group-color%Soul Siphone'
  description: |-
    Proc'ing on outgoing damage events this enchant siphons souls
    and durability from enemies in large quantities!.
  applies-to: Boots
  type: DEFENSE
  group: MASTERY
  applies:
  - ALL_BOOTS
  levels:
    '1':
      chance: 6.1
      cooldown: 60
      effects:
      - DAMAGE_ARMOR:10 @Attacker
      - REMOVE_SOULS:200 @Attacker
      - MESSAGE:§4§l** SOUL SIPHONE ** §7(%victim name%)
    '2':
      chance: 8.1
      cooldown: 60
      effects:
      - DAMAGE_ARMOR:15 @Attacker
      - REMOVE_SOULS:200 @Attacker
      - MESSAGE:§4§l** SOUL SIPHONE ** §7(%victim name%)
    '3':
      chance: 10.4
      cooldown: 60
      effects:
      - DAMAGE_ARMOR:20 @Attacker
      - REMOVE_SOULS:200 @Attacker
      - MESSAGE:§4§l** SOUL SIPHONE ** §7(%victim name%)
    '4':
      chance: 13.5
      cooldown: 60
      effects:
      - DAMAGE_ARMOR:30 @Attacker
      - REMOVE_SOULS:200 @Attacker
      - MESSAGE:§4§l** SOUL SIPHONE ** §7(%victim name%)
      
      and then use this CE, Let the Victim get this CE.
      after that, Let the Attacker don't have any armor or weapon just hands. And attack the victim. It will somehow dupe the item 
      as the plugin things that it needs to have the item so it will replicate the boots.

### "/ae plinfo" link

https://paste.md-5.net/cicojokucu

**Comment by GC-spigot** [comment]
We'll have to rework this effect in future versions, as right now it makes no sense how this would work and what item to target for other player, so this should be only used on the person who's enchant it is, e.g. in this case only targeted towards the victim (who owns item with current enchant)
