### ISSUE TITLE
After updating the new version, the backend has been constantly dealing with this issue

### ISSUE THREAD

**Issue by Naohuah** [GC-spigot/AdvancedEnchantments#3323]
### Describe the bug

![67867856](https://user-images.githubusercontent.com/131630941/235916345-83a370cc-7007-4f6f-9141-6693ba43963c.png)
After updating the plugin, it will cause the backend to refresh this information, but it will not affect the use of some functions. It seems that the enchantment of bows and arrows will cause this, as well as the enchantment of the manuscript.

### How to reproduce

After updating the plugin, it will cause the backend to refresh this information, but it will not affect the use of some functions. It seems that the enchantment of bows and arrows will cause this, as well as the enchantment of the manuscript.
![67867856](https://user-images.githubusercontent.com/131630941/235916810-6b3fa543-e508-4ebd-91cd-b3e72f1fb6a8.png)

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by GC-spigot** [comment]
This is a problem with one of the pull_closer effect enchants, but we've now resolved it, thanks for reporting!
