### ISSUE TITLE
Telepathy does not work for all items/blocks like it used to be

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3327]
### Describe the bug

So i went to my vine farm first time after updating to 9.+ and noticed that telepathy enchant does not work on vines, tested on multiple tools and ended up removing telepathy and testing it, Then i went to test on snow and grass too, and same problem, like all normal "blocks" works just fine

### How to reproduce

Enchant telepathy on version 9.1.0 and try mine like vine or snow, does not come inventory, just vanished 

### "/ae plinfo" link

https://paste.md-5.net/akagivafiy

**Comment by GC-spigot** [comment]
Fixed drops for snow!
