### ISSUE TITLE
AdvancedHeads don't work with AdvancedEnchantments

### ISSUE THREAD

**Issue by Neeekss** [GC-spigot/AdvancedEnchantments#3328]
### Describe the bug

I tried many different ways to make it work but it seems that plugin is not support it. 

      2:
      item:
        advanced-heads: 18854
      enchant-group: SIMPLE
      price: exp:400
      sound: ANVIL_LAND
      name: "&f&lSimple Enchantment &7(Right Click)"
      lore:
        - "&7Examine to receive a random"
        - "&fsimple &7enchantment book."
        - ""
        - "&b&lCOST &f%price% EXP &7(You need %left% more EXP)"

### How to reproduce

Try to add advanced-heads in item: line.

### "/ae plinfo" link

https://paste.md-5.net/esaxosewer

**Comment by GC-spigot** [comment]
Working on this!

**Comment by NekroCraft** [comment]
I have this error too creating kits , i tried differents configs and nothing. Will the update be advanced heads or advanced enchants? If it is the last one, I use the latest version available for 1.8.8, will I be able to use it?

![IMG_3526](https://github.com/GC-spigot/AdvancedEnchantments/assets/135345807/0ecd470c-a2f7-4243-b942-5d441f244777)

![2](https://github.com/GC-
![n1](https://github.com/GC-spigot/AdvancedEnchantments/assets/135345807/66259c7d-f55a-44a5-80af-e0c574351aa9)
![n2](https://github.com/GC-spigot/AdvancedEnchantments/assets/135345807/0bcf0ec5-83a3-4eea-97b1-140685970b0d)
spigot/AdvancedEnchantments/assets/135345807/2a25fda8-5524-4c62-bdfd-13c6cbb1bd9c)
![1](https://github.com/GC-spigot/AdvancedEnchantments/assets/135345807/cd0ef0b7-245c-468a-a023-55438eb8b0e7)

**Comment by GC-spigot** [comment]
Work in progress
