### ISSUE TITLE
DEFENSE_MOB_PROJECTILE functionality issue

### ISSUE THREAD

**Issue by FighterPilot50** [GC-spigot/AdvancedEnchantments#3329]
### Describe the bug

The trigger "DEFENSE_MOB_PROJECTILE" doesn't seem to work. Having a player shot by skeletons does not activate an enchant with this trigger.

### How to reproduce

![image](https://user-images.githubusercontent.com/77595823/236222919-5045a676-fdc5-4354-98a7-411906aa55c6.png)
I've tried formatting different sections with '' and "" but to no avail. All my other enchants are also formatted the same and work fine. I've also changed @Victim to @Attacker with no difference. Lastly I've also tried different effects such as potions. No matter what, mobs like zombies and vindicators can always activate the enchant (so long as I include DEFENSE_MOB as well), but skeletons can't. I have yet to try other ranged mobs.

### "/ae plinfo" link

https://paste.md-5.net/coluwiriwo

### Server Log

https://mcpaste.io/9baa00bdb0e646dd

**Comment by GC-spigot** [comment]
Fixed!
