### ISSUE TITLE
ADD_EXP_MCMMO doesn't exist anymore.

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#3330]
### Describe the bug

After the major recode update, my mcmmo related enchants stopped working

### How to reproduce

Update to latest

### "/ae plinfo" link

https://paste.md-5.net/ezinakucid

**Comment by 10lulu** [comment]
I have the same issue on my server, id be really glad if this got looked at because its really annoying :/

**Comment by GC-spigot** [comment]
Added back!
