### ISSUE TITLE
Advanced enchantments failed to load, disabling plugin.

### ISSUE THREAD

**Issue by ELIAS7281** [GC-spigot/AdvancedEnchantments#3332]
### Describe the bug

Hi, we have updated purpur to the latest build and advanced enchantments is the only plugin in my skyblock server that does not work. AE support staff have told me that it has nothing to do with AE plugin but everything to do with (cmi does not support purpur). We have been using cmi with purpur for a year with no problem and advanced enchantments worked perfectly. Purpur has responded with.

"no, it tries to register an itemstack that is null
it's 100% on the plugin itself
something with alchemist inventory
would be best to go to the author of the plugin for support"

i will drop my start up logs and plugins installed.

### How to reproduce

issue is in logs

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/111949540/236421804-7b120404-b345-4599-8c36-de986d6f3018.png)

### "/ae plinfo" link

https://pastes.dev/FLx858Iq8r

### Server Log

https://mclo.gs/sZrTckf

**Comment by ELIAS7281** [comment]
To add on to this , alchemist.yml was empty and i have created a new file and pasted the config for it in that file. I know there is an issue with alchemist but plugin is still being disabled.

**Comment by ELIAS7281** [comment]
Support staff had told me to delete and reload. the file never returned. they gave me the download to put in for alchemist but apon reload it did not regenerate. thats why i manually created that file to see if it worked and it does show in the file but im not sure if it works for the plugin.

**Comment by GC-spigot** [comment]
Do you have your own custom configuration? If you don't, try deleting whole AdvancedEnchantments folder, still seems to have an issue. Try deleting either whole folder or `menus` folder - if you are upgrading from previous versions to the new rework. Let me know how it goes.

**Comment by ELIAS7281** [comment]
I have deleted the jar and the folder and re-downloaded advanced enchantments and it is now working in the server.
Thank you.
