### ISSUE TITLE
mcMMO EXP not given when using AdvancedEnchantments

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3334]
### Describe the bug

Tools with AdvancedEnchantments enchantments don't give mcMMO EXP

### How to reproduce

Enchant a tool with an AE enchant
break a block
no mcMMO EXP is given

### "/ae plinfo" link

https://paste.md-5.net/gisiyiwigi

**Comment by GC-spigot** [comment]
Fixed!
