### ISSUE TITLE
MINING Enchants not giving JobsReborn rewards

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3336]
### Describe the bug

Certain MINING effects (SMELT, TP_DROPS, etc.) are not triggering JobsReborn block breaks properly (no jobs money/exp given).

### How to reproduce

Enchant a tool with a SMELT enchantment.
Join a JobsReborn job that rewards breaking stone.
Break stone with the tool.
No jobs rewards are given.

### "/ae plinfo" link

https://paste.md-5.net/ayiteyices

**Comment by Dakotaa** [comment]
Likewise, these enchantments seem to not be giving progression towards [AdvancedAchievements](https://www.spigotmc.org/resources/advanced-achievements.83466/) plugin.

**Comment by GC-spigot** [comment]
Should be fixed along with #3334 issue.
