### ISSUE TITLE
TP_DROPS does not drop/give Chorus Flowers

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3337]
### Describe the bug

When breaking chorus flowers with a TP_DROPS enchanted tool, the block is not dropped or put in the inventory.

### How to reproduce

Enchant a tool with a TP_DROPS enchant
break a chorus flower
no chorus flower is dropped/given

### "/ae plinfo" link

https://paste.md-5.net/ibicepiyiq

**Comment by GC-spigot** [comment]
Fixed!
