### ISSUE TITLE
%souls on item% > 3 : %allow% not working if the player is @Victim

### ISSUE THREAD

**Issue by R411gun** [GC-spigot/AdvancedEnchantments#3338]
### Describe the bug

So I wanted to make an Enchant that blocks explosions while also consuming souls
without the condition - '%souls on item% > 3 : %allow%' the enchant works fine
with the condition it fails and spammes the console https://pastebin.com/C4VATYQt

I think whats happening is, that it checks the creeper for souls, which obviously does not have souls
I also tried %victim souls on item% %attacker souls on item% and %player souls on item%
made an ticket aenchantments-3890 and Jben suggested me to open an issue here

### How to reproduce

You can test this issue by using my enchantments.yml file
there are 3 enchantments: 

explosive_error              <- the important one that leads to console spam
explosive_kinda_works  <- this one does not have the souls on item condition and works - but everytime
wings_working_fine       <- has the souls condition but works fine, I think thats because the player is the attacker
[enchantments.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/11414984/enchantments.zip)

### "/ae plinfo" link

https://paste.md-5.net/adenugejah

**Comment by R411gun** [comment]
Just noticed that this enchant suffers from the same problem

phoenix:
  display: "%group-color%Phönix"
  description: "Revives you when you die"
  applies-to: Brustplatten
  type: DEATH
  group: FABLED
  applies:
  - ALL_CHESTPLATE
  levels:
    "1":
      chance: 100
      cooldown: 20
      conditions:
      - '%souls on item% > 199 : %allow%'   #Only works WITHOUT this condition
      effects:
      - 'REMOVE_SOULS: 200 @Victim'
      - 'REVIVE @Victim'

**Comment by reussy** [comment]
Hello,

Tested and working, if the error persists open a new report.
