### ISSUE TITLE
Compatibility issues with aurellium skills

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3339]
### Describe the bug

after change mcmmo to aurelium skills,
sometimes advanced enchant's effect doesn't work. This bug occurs in all enchant related break event.
(smelt, TP_DROPS, etc..)

### How to reproduce

1. install aurellium skills, AE
2. make smelt or TP_DROPS pickaxe
3. break block. (It seems to happen once every 30~40 times)

### Screenshots / Videos

https://user-images.githubusercontent.com/25452835/236698933-14fb1bdf-f578-4fa9-b942-f5e9fcc1d2ad.mp4

### "/ae plinfo" link

https://paste.md-5.net/iyasepebiy

**Comment by GC-spigot** [comment]
Fixed
