### ISSUE TITLE
Experience buff issue

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#334]
Is there a way we can get it to read when its breaking the same block? (Like jobs/mcmmo has).

Players are able to place and break cobblestone and get exp from it.

Confirmed with Experience X enchant.

**Comment by Kbryst** [comment]
Players are also saying they are able to place and break shulker boxes and get exp.

**Comment by GC-spigot** [comment]
This cannot be fixed due to how McMMO handles broken blocks tracking.
