### ISSUE TITLE
Trench/Telepathy doesn't respect other Unbreakable

### ISSUE THREAD

**Issue by lajnicek** [GC-spigot/AdvancedEnchantments#3341]
### Describe the bug

Hello there :) 
Two days ago I updated AdvancedEnchantments-9.0.0b78 to AdvancedEnchantments-9.1.1 
Players reported to me that their pickaxes with Trench lost their 3x3 after some time.
Then I tested pickaxe with Trench and Telepathy, same Axe with Telepathy.
I've found that AE enchants ends respecting Unbreakable from other plugins (ExecutableItems, ItemEdit)
 
So the tools are damaged(You can see it in MC Clients) and when they are on the end of their durability, it ends their enchants(loose trench, telepathy) but the base item stays in inventory.

this issue started after this update 🙂 

In pictures, you will understand it better :)

(with enchant Unbreakable from your plugin all is ok, but i have to rework all items a change items for all players on my server)

### How to reproduce

for exaple
1. Create any pickaxe
2. In ExecutableItems click Unbreakable or in ItemEdit /ie unbreakable true on pickaxe
3. Enchant with AE Trench and Telepathy
4. Mine, mine, mine 
5. After few moments(depends on durability) tool is broken(0% on photo) with lost 3x3 and telepathy effect

### Screenshots / Videos

![2023-05-07_02 23 59](https://user-images.githubusercontent.com/117314475/236703933-f5557a9c-7b26-4f50-b1ad-468d34e62724.png)
![2023-05-07_02 24 49](https://user-images.githubusercontent.com/117314475/236703935-3ae04560-b49b-4be2-a975-ab42d1856aac.png)
![2023-05-07_02 25 46](https://user-images.githubusercontent.com/117314475/236703936-3a0538cf-b8a8-4562-9426-ea7d454225a9.png)

### "/ae plinfo" link

https://paste.md-5.net/mepoheneyo

**Comment by aXe18** [comment]
I did some testing while he opened ticket. Got same results

**Comment by GC-spigot** [comment]
Resolved!
