### ISSUE TITLE
Souls and more_drops

### ISSUE THREAD

**Issue by CrystallizedAtrophy** [GC-spigot/AdvancedEnchantments#3342]
### Describe the bug

multiplication:
  display: '%group-color%Multiplication'
  description: |-
    Chance to multiply ore drops.

     {#57595D}+ {#D9CAC3}ᴘʀᴏᴄ ᴄʜᴀɴᴄᴇ ● &f15&8/&f20&8/&f25&8/&f28&8/&f30
     {#57595D}+ {#D9CAC3}ᴄᴏᴏʟᴅᴏᴡɴ     ● &f5&8/&f5&8/&f6&8/&f7&8/&f8
     {#57595D}+ {#D9CAC3}ꜱᴏᴜʟ ᴄᴏꜱᴛ    ● &f5 ꜱᴏᴜʟꜱ
  applies-to: Pickaxe
  type: MINING
  group: SOUL
  applies:
  - ALL_PICKAXE
  levels:
    '1':
      chance: 15
      cooldown: 5
      conditions: '%block type% contains ORE : %allow%'
      souls: 5
      effects:
      - MORE_DROPS:1
      - MESSAGE:§2§l* * * Multiplication * * *
    '2':
      chance: 20
      cooldown: 5
      conditions: '%block type% contains ORE : %allow%'
      souls: 5
      effects:
      - MORE_DROPS:1
      - MESSAGE:§2§l* * * Multiplication * * *
    '3':
      chance: 25
      cooldown: 6
      conditions: '%block type% contains ORE : %allow%'
      souls: 5
      effects:
      - MORE_DROPS:1
      - MESSAGE:§2§l* * * Multiplication * * *
    '4':
      chance: 28
      cooldown: 7
      conditions: '%block type% contains ORE : %allow%'
      souls: 5
      effects:
      - MORE_DROPS:1
      - MESSAGE:§2§l* * * Multiplication * * *
    '5':
      chance: 100
      cooldown: 0
      conditions: '%block type% contains ORE : %allow%'
      souls: 5
      effects:
      - MESSAGE:§2§l* * * Multiplication * * *      
      - MORE_DROPS:2
      
      This enchant will constantly proc even without mining ore blocks and then will not take souls as currency.

### How to reproduce

Use enchant and mine anything. Still procs the mutliply drops when not mining ore blocks, also doesn't take souls as currency.

### Screenshots / Videos

https://youtu.be/9KKtTwbseoA

### "/ae plinfo" link

https://paste.md-5.net/ekazivutoc

### Server Log

https://mcpaste.io/3d86ec73869cbf87

**Comment by CrystallizedAtrophy** [comment]
[9.1.10] still having issues with this. Still proccing message even though it is NOT a ore block, duplicating blocks that are NOT a ore block, and still not taking souls as currency.

**Comment by GC-spigot** [comment]
Hey! So for conditions, it's now supposed to be a list, e.g.: 
```yaml
conditions:
- '%block type% contains ORE : %allow%'`
```

Soul support hasn't been added yet, will be added next update
