### ISSUE TITLE
FALL_DAMAGE doesn't work with any conditions

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#3343]
### Describe the bug

Seems that no matter what the condition is, it'll always pop up an error, so either a fix to this, or possibly re-adding SHIFT may also be a fix to the issue, as there aren't any workarounds to adding the feature which is ignoring fall damage when you are crouching. Error and the enchant are provided below

[enchant.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/11427250/enchant.txt)
[error.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/11427267/error.txt)

### How to reproduce

Try to put any condition while you have FALL_DAMAGE as the type

### "/ae plinfo" link

https://paste.md-5.net/ixucadadix (have tested with all other plugins disabled)

**Comment by GC-spigot** [comment]
Fixed!
