### ISSUE TITLE
Off-Hand Functionality With Items (such as totems) [REQUEST]

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#3344]
### Describe the bug

Right before I bought the plugin over a year ago, I remember making a ticket (which I also have a transcript of) of me asking if the feature was a thing, and asked for confirmation, as a friend who also owned the plugin, said it didn't, to which I was told by GC that it wasn't implemented but could be added. So I was wondering if it finally could be added as a feature sometime in the future, as it was one of the main reasons I bought the plugin for, as well as I was told that the plugin updates and patches often (which it still does). I of course know that things like that can take time to set up, as well as the fact that the person developing the plugin has other things to do than to just develop a Minecraft plugin, I just hope this feature could be added as soon as the next month, or at least be confirmed to be added when time is available, even if it's a few months from now.

### How to reproduce

Feature Request

### "/ae plinfo" link

Feature Request

**Comment by GC-spigot** [comment]
Can you give us the transcript so we can progress with this request?

**Comment by DuplexLake** [comment]
Hopefully this is correct, kinda sick currently so not at computer.
https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/909181233110601798/956923641986183188/transcript-prepurchase-0383.html

**Comment by reussy** [comment]
Hey,

It's been a long time, we apologize for this! 🙏

I've added the functionality you requested, you still need to enable it from the configuration (config.yml)

Add the following value to your configuration, just below **settings**.

```yaml
right-click-triggers-on-off-hand: true
```

It should look something like this:
```yaml
settings:
  # If true, right-click triggers will work on off-hand.
  right-click-triggers-on-off-hand: true
```
