### ISSUE TITLE
A 2nd Message In Chat Appears That Shouldn't Be There To When Attempting To Apply An Enchant

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#3345]
### Describe the bug

The enchant file below appears a text error that is never mentioned in the enchant config, while the Mechanical book states that it cannot be applied if the Mechanical+ book is already on the item, it never mentions needing the Mechanical+ enchant to be applied. (As the Mechanical+ enchant does mention that it needs the Mechanical enchant to be applied beforehand but the Mechanical enchant doesn't)

![image](https://user-images.githubusercontent.com/35179393/236997083-295fc751-7589-40c5-8dc1-52fbec48f3dd.png)
[mechanical.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/11427379/mechanical.txt)

### How to reproduce

Get 2 books of Mechanical IV, and 1 book of Mechanical+, apply 1 book of Mechanical IV, then 1 of Mechanical+, then try to apply Mechanical IV when Mechanical+ is already on the tool.

### "/ae plinfo" link

https://paste.md-5.net/ixucadadix

**Comment by GC-spigot** [comment]
Fixed!
