### ISSUE TITLE
Glowing enchant not working with Gold helmet

### ISSUE THREAD

**Issue by GatoronronYT** [GC-spigot/AdvancedEnchantments#3346]
### Describe the bug

The enchantment glowing is not working with "gold helmet" but it works with all the other helmets.

### How to reproduce

enchant a gold helmet with glowing

### Screenshots / Videos

![gold](https://user-images.githubusercontent.com/128557960/237005841-fb1b485a-546f-4c82-99bc-158b9cc3e5e5.PNG)
![netherite](https://user-images.githubusercontent.com/128557960/237005847-aae18b5b-6a59-4615-9a74-b54b20f09b54.PNG)

### "/ae plinfo" link

https://paste.md-5.net/adosilawir

**Comment by DuplexLake** [comment]
had the same issue, was fixed when i updated the plugin to the latest version
