### ISSUE TITLE
The plugin keeps spamming this error in the console after updating its version

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3347]
### Describe the bug

It's hard for me to say what's causing it, it keeps spamming this error in the console. As a developer, I think you'll quickly understand and fix it

### How to reproduce

error: https://mclo.gs/GCWzzu9

### Screenshots / Videos

-

### "/ae plinfo" link

https://paste.md-5.net/ifoboyados

### Server Log

-

**Comment by CrystallizedAtrophy** [comment]
idk man but it kinda looks like you didn't edit your aoe enchants. "0<aoe>radius=3target=mobs</aoe>" they don't use <aoe></aoe> anymore. Probably should look at changelog/wiki more often.

**Comment by GC-spigot** [comment]
^^^
