### ISSUE TITLE
REACH pops up an error with SWING, ATTACK, Etc. when it comes to a target

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#3348]
### Describe the bug

Enchants seem to have issues when it comes to a target, whether @Victim @
[spear.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/11437001/spear.txt)

### How to reproduce

Copy what is written in the file, and error will pop up in-game

### "/ae plinfo" link

https://paste.md-5.net/ixucadadix

**Comment by FighterPilot50** [comment]
I also can't seem to get REACH to stop sending errors.

**Comment by GC-spigot** [comment]
Should be resolved!
