### ISSUE TITLE
Placeholder condition and disable-enchants: setting in config.yml bugged

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#3349]
### Describe the bug

I'm trying to disable detonate in my nether world but neither conditions or disable-enchants: are working, we discussed that in my ticket.

### How to reproduce

Use these files: https://paste.gg/p/anonymous/2c9838d019fd4753aebae2e3a04889b6

### "/ae plinfo" link

https://paste.md-5.net/ogedenedag

**Comment by GC-spigot** [comment]
Fixed!
