### ISSUE TITLE
/n is a bit buggy

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#335]
Heya! I've noticed when it comes to enchants (in the config /n is used as a line breaker), sometimes when players create new books it will show the /n instead of it being a line breaker. 

I've seen one person create the same book 3 times, and 1 of the 3 had the /n, while the other just had the rest of the sentence correctly on the next line.

**Comment by ZeddyOG** [comment]
First the breaker is (\n) not (/n) also when using the breaker be sure that the description is in "desc" and not 'desc'

**Comment by Kbryst** [comment]
It's the default config. And im able to get the same book twice, where the
first time it will show up correctly and the second time it will show the
'/n' in a run on sentence.

**Comment by GC-spigot** [comment]
Do you have some visual information or certain enchant which does it?

**Comment by Kbryst** [comment]
I was able to recreate it normally but after a server restart it looks like
it went away. Unable to recreate now
