### ISSUE TITLE
Error when player holds enchanted item (TOTEM_OF_UNDYING, PASSIVE_DEATH) KEEP_ON_DEATH inactive

### ISSUE THREAD

**Issue by TunanaX** [GC-spigot/AdvancedEnchantments#3351]
### Describe the bug

When holding any item in hand and die
on the console will show an error
Paper 1.12.2 - 1620
AdvancedEnchantments-9.0.0b81

I tested on default configuration
and only one plugin AdvancedEnchantments-9.0.0b81

### How to reproduce

run paper server 1.12.2 1620 with plugin AdvancedEnchantments-9.0.0b81
take the item in hand and die
see what happens on console

### "/ae plinfo" link

https://paste.md-5.net/aqezapobay.cs

### Server Log

https://mcpaste.com/c64244cb1f490d84f42bb237255dc79b

**Comment by GC-spigot** [comment]
Sorry we don't support that version anymore, no updates for it anymore are available :(
