### ISSUE TITLE
Thorns enchant activating all ATTACK & ATTACK_MOB custom enchants

### ISSUE THREAD

**Issue by FighterPilot50** [GC-spigot/AdvancedEnchantments#3353]
### Describe the bug

Upon activation of thorns, it appears to activate enchants worn or held with the ATTACK or ATTACK_MOB trigger, including potion and damage increasing effects. This is very game-breaking and I may have to ban thorns from my server for the time being.

### How to reproduce

Wear armor with max thorns enchantments, then hold any item with an enchantment with a 100% chance triggered by ATTACK or ATTACK_MOB and proceed to let yourself be attacked to activate the thorns and thus the custom enchantment.

### "/ae plinfo" link

https://paste.md-5.net/koxixucuno

### Server Log

https://mcpaste.io/0204624011ab4a4f

**Comment by GC-spigot** [comment]
This actually isn't intended, fixed!
