### ISSUE TITLE
enchantment-world-blacklist does not work

### ISSUE THREAD

**Issue by nasiridrishi** [GC-spigot/AdvancedEnchantments#3354]
### Describe the bug

I want to disable all custom enchants in certain worlds and tried using "enchantment-world-blacklist" to disable it but it does not effect and custom enchants work on disabled worlds.  

### How to reproduce

1. add a world in enchantment-world-blacklist 
2. reload/restart server
3. get a custom enchant: example gears 
4. teleport to blacklisted world 

### "/ae plinfo" link

https://paste.md-5.net/fewukefixi

**Comment by aXe18** [comment]
Got same results while testing this out

**Comment by aXe18** [comment]
And holy white scrolls have same issue

**Comment by GC-spigot** [comment]
Fixed
