### ISSUE TITLE
Unbreakable and Soulminer don't give souls

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3355]
### Describe the bug

If my pickaxe has a soul tracker and only soulminer on it, it can collect souls just fine.
As soon as I also add the unbreakable enchantment on top if it, it seems to cancel the collection of souls.

I am using AE 9.1.3 which is the latest as of writing this and I removed all plugin that could have interfered, only leaving Vault, LuckPerms, ViaVersion and ViaBackwards (aside from AE of course).

### How to reproduce

- Get pickaxe of any kind
- Get soul tracker
- Put soul tracker on pickaxe
- Enchant pickaxe with soulminer
See how your souls get collected fine

- Put unbreakable on pickaxe
See how your souls no longer get collected :(

### Screenshots / Videos

This is the pickaxe that's been stuck on 8 souls even after having several hearts show up that should indicate having generated souls:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/39222968/bc7e7980-0f97-4df1-8176-d78bda36abaf)

### "/ae plinfo" link

https://paste.md-5.net/anapayocus

### Server Log

https://mcpaste.io/294307b61d3f3e39

**Comment by lukebradaric** [comment]
Same exact issue here. 
Tested with multiple other enchants. 
Using the same AE version.

**Comment by jnadlesh** [comment]
> Same exact issue here. Tested with multiple other enchants. Using the same AE version.

yeah I've been having the same issue.

**Comment by reussy** [comment]
Hey guys,

I have fixed this problem. If it still persists comment in this same report with more details.
