### ISSUE TITLE
Trench - Piston Dupe bug

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3356]
### Describe the bug

Pistons can be duplicated due to this bug

### How to reproduce

![Screenshot 2023-05-13 at 1 51 04](https://github.com/GC-spigot/AdvancedEnchantments/assets/117641078/8392eaed-c2f7-4bf7-991d-4c87c799045c)

1. Place the pistons side by side
2. Activate them
3. Break the upper (extended) part of the piston with piackaxe that has the enchant Trench III (3x3 mining)
4. You have 3 pistols instead of two

### "/ae plinfo" link

https://paste.md-5.net/sohojusexa

**Comment by GC-spigot** [comment]
I can't recreate this, this may have been already fixed. I attach a gif of me doing it, if this is still an issue let me know by tagging me @GC-spigot https://gyazo.com/662a825030bbb1fb35f42114bfe1e572
