### ISSUE TITLE
Ineffective Functioning of holy-whitescrolls-world-blacklist

### ISSUE THREAD

**Issue by Naokogit** [GC-spigot/AdvancedEnchantments#3357]
### Describe the bug

I am writing to report a bug regarding the functionality of the "holy-whitescrolls-world-blacklist" feature in the enchant plugin. It appears that the feature is not working as intended when adding worlds to the specified field using the provided YAML code. The worlds added in the following format do not get properly blacklisted:

### How to reproduce

Add the following lines to the "holy-whitescrolls-world-blacklist" section:

holy-whitescrolls-world-blacklist:
- world1
- world2

restart the server

### "/ae plinfo" link

https://paste.md-5.net/ramurohana

**Comment by GC-spigot** [comment]
Fixed!
