### ISSUE TITLE
AdvancedEnchantments Error?

### ISSUE THREAD

**Issue by HanMi00** [GC-spigot/AdvancedEnchantments#3358]
### Describe the bug

Hello, producer
AdvancedEnchantments I'm using the plug-in
I am inquiring because I think there is a problem.
There may be something wrong because I inquired with the translator.
The trench and reforged incant are not compatible,
There are some minerals that do not have a lucky effect when applying the veinminer incant.
I don't think luck is applicable to smelting incandescent.
Please check it out.
Thank you for reading the long article.

### How to reproduce

,

### "/ae plinfo" link

https://paste.md-5.net/inusajefas

**Comment by SirJben** [comment]
Hello what's the console error?
