### ISSUE TITLE
Smelt/More drops & Pyromining 

### ISSUE THREAD

**Issue by CrystallizedAtrophy** [GC-spigot/AdvancedEnchantments#3359]
### Describe the bug

Using this enchant causes pyromining to NOT give experience when mining.
autosmelt:
  display: '%group-color%Auto Smelt'
  description: |-
    Ores are automatically smelted
    when mined. Gives extra drops
    upon mining an ore.

     {#FFFFFD}+ {#D9CAC3}ᴘʀᴏᴄ ᴄʜᴀɴᴄᴇ ● &f41&8/&f62&8/&f100
  applies-to: Pickaxes
  type: MINING
  group: SIMPLE
  settings:
    not-applyable-with:
    - furnace
  applies:
  - ALL_PICKAXE
  levels:
    '1':
      chance: 41
      conditions:
      - '%block type% contains ORE : %allow%'
      effects:
      - SMELT
      - MORE_DROPS:2
    '2':
      chance: 62
      conditions:
      - '%block type% contains ORE : %allow%'
      effects:
      - SMELT
      - MORE_DROPS:3
    '3':
      chance: 100
      conditions:
      - '%block type% contains ORE : %allow%'
      effects:
      - SMELT
      - MORE_DROPS:4

### How to reproduce

Use smelt on a enchant and have pyromining and it won't give pyromining exp.

### Screenshots / Videos

https://youtu.be/CyQzGZnn3Zk

### "/ae plinfo" link

https://paste.md-5.net/jozadapize

### Server Log

https://mcpaste.io/ec09f5e6ec3b83a6

**Comment by Truongvv10** [comment]
I have this problem too....

**Comment by GC-spigot** [comment]
Fixed!
