### ISSUE TITLE
Tinkerer eats books

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#336]
If a player puts a book in the tinker but then closes out the gui instead of accepting or taking the book, it just eats the book.

**Comment by newbie029** [comment]
Same issue here

**Comment by GC-spigot** [comment]
What plugin version / minecraft version is this happening?

**Comment by newbie029** [comment]
MC1.12.2 / v5.2.3

It will eat book if we close the inventory with book still in the tinkerer, this not always happen

**Comment by GC-spigot** [comment]
Thanks for the info, will be fixed.

**Comment by Kbryst** [comment]
Mine is same ae version, paper spigot 1.13.2

**Comment by Kbryst** [comment]
I know this was added to the milestone, just wanted to point out its still an issue.

Paper spigot 1.13.2
AdvancedEnchantments 5.2.8
