### ISSUE TITLE
telepathy and smelting enchantments doesn't work properly with protectionstones

### ISSUE THREAD

**Issue by Suzuuki** [GC-spigot/AdvancedEnchantments#3361]
### Describe the bug

When breaking private blocks with enchantments "telepathy", "smelting", the block is broken, and the private is not removed

### How to reproduce

a

### Screenshots / Videos

https://www.youtube.com/watch?v=rMW1UX3J77s

### "/ae plinfo" link

https://paste.md-5.net/olosevapeg

### Server Log

https://mcpaste.io/d74ac240df88e932

**Comment by reussy** [comment]
Hello,

Tested and working, if the error persists open a new report.
