### ISSUE TITLE
SHOOT and SHOOT_MOB doesn't activate while in armor slots but ATTACK and ATTACK_MOB does

### ISSUE THREAD

**Issue by NeuTraLZero** [GC-spigot/AdvancedEnchantments#3362]
### Describe the bug

Having an armor with SHOOT or SHOOT_MOB as the trigger doesn't activate the effects while shooting targets with any ranged weapons

### How to reproduce

example enchantment for reference:

> duelist:
>   display: '&7Duelist'
>   description: Dealing damage with ranged weapon gives you strength for 3 seconds
>   applies-to: Chestplate
>   type: SHOOT;SHOOT_MOB
>   group: RARE
>   applies:
>     - ALL_CHESTPLATE
>   levels:
>     '1':
>       effects:
>         - 'POTION:INCREASE_DAMAGE:0:60 @Attacker'

### "/ae plinfo" link

https://paste.md-5.net/uwejikelep

### Server Log

https://mcpaste.io/a022232ed70cfc87

**Comment by GC-spigot** [comment]
SHOOT and SHOOT_MOB only activates for items in hand, by design.
