### ISSUE TITLE
Effects not working unless you SHIFT-CLICK armor on

### ISSUE THREAD

**Issue by CletusShufell** [GC-spigot/AdvancedEnchantments#3363]
### Describe the bug

On the newest version when players have armor pieces with effects (ie. extra hearts, speed etc..) the effects do NOT get added to the player if the player drag and drops the armor piece onto the slot. The effects ONLY get added to the player if the player SHIFT-CLICKS the armor into the slot.

### How to reproduce

Get a piece of armor with custom enchants that give effects such as speed or extra hearts and attempt to drag the armor onto your player and then try to shift click it on and see the difference.

### "/ae plinfo" link

https://paste.md-5.net/orunuzovaz

### Server Log

https://mcpaste.io/097a24badaabc843

**Comment by CletusShufell** [comment]
** DISCLAIMER ** 

This ONLY happens in survival. DO NOT test in creative.

**Comment by GC-spigot** [comment]
Is this still an issue? I haven't noticed any other reports, might be something with your server / client. https://gyazo.com/91cd16daf2689dad96afe82f04e676ce
