### ISSUE TITLE
MORE_DROPS doesn't work with <chance> in effect line

### ISSUE THREAD

**Issue by FighterPilot50** [GC-spigot/AdvancedEnchantments#3365]
### Describe the bug

Adding MORE_DROPS to an enchantment activated with MINING works like normal, unless <chance> is introduced in the specific effect line.

### How to reproduce

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/77595823/81a46b36-2b53-40d0-9706-b4d45dd1b57e)
If you remove the last line in effects, it functions normally, but given how it is now, MORE_DROPS doesn't function at all.

### "/ae plinfo" link

https://paste.md-5.net/yahuhekiqe

### Server Log

https://mcpaste.io/be1bf45854f3c21e

**Comment by GC-spigot** [comment]
Add `@Block` target to MORE_DROPS effect, it's required.
