### ISSUE TITLE
Error with FactionsUUID

### ISSUE THREAD

**Issue by Phanthropogenic** [GC-spigot/AdvancedEnchantments#3366]
### Describe the bug

No idea why, usually happens when someone with LavaWalker boots enchant walks around.

### How to reproduce

I have the Factions fork called SaberFactions installed. It happens with certain enchantments aswell.
Happens when someone with LavaWalker enchantment walks around(?)

### Screenshots / Videos

https://prnt.sc/ZE6EiPI4rkhk

### "/ae plinfo" link

https://paste.md-5.net/ayexuromeg

**Comment by reussy** [comment]
Hello,

Tested and working, if the error persists open a new report.
