### ISSUE TITLE
Water Walker working when boots are off

### ISSUE THREAD

**Issue by Roky67** [GC-spigot/AdvancedEnchantments#3367]
### Describe the bug

One player had his boots with Water Walker on and them put them off. But he still walks on water (replaces nearby water with obdsidian). Now the enchant on his boots doesn’t work.

### How to reproduce

I don’t know exactly, he just had them on for a while. He says it might be since he enchanted them with feather falling. 

### Screenshots / Videos

https://streamable.com/2w968b

### "/ae plinfo" link

https://paste.md-5.net/oyufuvixif

### Server Log

I don’t know when exactly that happened + don’t think it is going to be necessary

**Comment by GC-spigot** [comment]
Update, already fixed!
