### ISSUE TITLE
Bug - Smelting enchant

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3369]
### Describe the bug

Smelting enchant don't drop blocks that aren't ore

### How to reproduce

1. Break block that is not ore (for example grass) with pickaxe with smelting enchantment.
2. No item is dropped.

### "/ae plinfo" link

https://paste.md-5.net/nubeturovu

**Comment by GC-spigot** [comment]
Already resolved :)
