### ISSUE TITLE
lava-worker was not loaded with specific world.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3370]
### Describe the bug

not blacklisted world. when player generate dungeon world, (named pve0_1, pve0_2 ,,,)
lavaworker was not worked.

### How to reproduce

you can see with video link below i uploaded

### Screenshots / Videos

https://youtu.be/m9N1ynHi-EY

### "/ae plinfo" link

https://paste.md-5.net/ojabaqaboz

**Comment by GC-spigot** [comment]
Hey, video is private, please make it unlisted. Also, try re-applying the armor and seeing if it works then.
