### ISSUE TITLE
player can break block in claimed region (towny, griefprevention)

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3371]
### Describe the bug

I understand that AE softends Towny, GriefPrevention.
but player can break block other region after update lastest version of AE.

글래스해머:
  display: '%group-color%글래스해머'
  description: |-
    유리를 즉시 파괴할 수 있게 됩니다.
    &7(수확은 적용되지 않습니다)
  applies-to: 
  type: SWING
  group: 레어
  applies:
  - ALL_AXE
  - ALL_PICKAXE
  - ALL_SPADE
  levels:
    '1':
      conditions:
      - '%block type% contains GLASS : %allow%'
      effects:
      - BREAK_BLOCK @Block

### How to reproduce

1. make protected area by griefprevention or LWC or towny
2. break block by BREAK_BLOCK effect.
3. can break block although protected area.

### Screenshots / Videos

https://youtu.be/vRrkXWGGw3o

### "/ae plinfo" link

https://paste.md-5.net/ojabaqaboz

**Comment by GC-spigot** [comment]
Added Towny, GriefPrevention, LWC support
