### ISSUE TITLE
smelt dosen't give mcmmo xp

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3372]
### Describe the bug

when player break ore block with 'smelt', it doesen't give mmo xp.

### How to reproduce

1. break block with doesen't enchant 'smelt'
2. break block with enchanted 'smelt'

### Screenshots / Videos

https://youtu.be/NMkATLoX-F0

### "/ae plinfo" link

https://paste.md-5.net/ojabaqaboz

**Comment by GC-spigot** [comment]
Hey! Is this with mcmmo or what plugin? Also video is private, make it unlisted

**Comment by reussy** [comment]
Hello,

Tested and working, if the error persists open a new report.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63428864/ee09b43d-b80b-4188-9245-5fb3f1e4e94c)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63428864/21eb5d68-7d35-4663-acef-26fc477fc87a)
