### ISSUE TITLE
VEIN_MINE was not worked sometimes.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3376]
### Describe the bug

vein mine was not worked sometimes after update.
Before the update, all the connected minerals were broken, but after the update, they often don't dig properly like the video.

### How to reproduce

1. make VEIN_MINE pickaxe.
2. break ore
    '4':
      settings:
        whitelist:
          - "COAL_ORE"
          - "COPPER_ORE"
          - "IRON_ORE"
          - "GOLD_ORE"
          - "LAPIS_ORE"
          - "REDSTONE_ORE"
          - "DIAMOND_ORE"
          - "EMERALD_ORE"
          - "NETHER_QUARTZ_ORE"
          - "NETHER_GOLD_ORE"
          - "ANCIENT_DEBRIS"
          - "DEEPSLATE_COAL_ORE"
          - "DEEPSLATE_COPPER_ORE"
          - "DEEPSLATE_IRON_ORE"
          - "DEEPSLATE_GOLD_ORE"
          - "DEEPSLATE_LAPIS_ORE"
          - "DEEPSLATE_REDSTONE_ORE"
          - "DEEPSLATE_DIAMOND_ORE"
          - "DEEPSLATE_EMERALD_ORE"
      effects:
      - BREAK_BLOCK @Veinmine

### Screenshots / Videos

https://youtu.be/ja1gFQlVT8A

### "/ae plinfo" link

https://paste.md-5.net/ojabaqaboz

**Comment by GC-spigot** [comment]
Fixed!
