### ISSUE TITLE
Pickaxe issues 

### ISSUE THREAD

**Issue by Daphsquid** [GC-spigot/AdvancedEnchantments#338]
Hi there, 

Thanks for the quick bug fixes you've done for us so far. I have a few other issues regarding pickaxes. Looking forward to a fix! 

- The initial block broken with a Detonate pickaxe (in the middle of the 3x3x3 cube) doesn't drop anything.
- Pickaxes with Telepathy on them do not lose durability when breaking blocks.

Thanks again,

**Comment by GC-spigot** [comment]
Fixed the #-1 problem, what version are you using to achieve #-2 issue? Testing on 1.8.8:

**Comment by Daphsquid** [comment]
Sorry, I should've included that information. 

Server version: [16:44:23 INFO]: This server is running Paper version git-Paper-525 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
AE version: [16:44:48 INFO]: AdvancedEnchantments version 5.2.3

**Comment by Kbryst** [comment]
I am also able to recreate this, 

paper spigot a few versions behind theirs, 516
Same ae version, 5.2.3

**Comment by GC-spigot** [comment]
Fixed.
