### ISSUE TITLE
SET_BLOCK keeps asking for a target but even with a target still does not work

### ISSUE THREAD

**Issue by Zorrkez** [GC-spigot/AdvancedEnchantments#3380]
### Describe the bug

SET_BLOCK Does not work

Here is the enchant info
coalconversion:
  display: '%group-color%Coal Conversion'
  description: |-
    &7Has a chance to turn
    &7coal ore into a coal block.
    &7
  applies:
  - ALL_PICKAXE
  group: CT
  type: MINING
  applies:
   - ALL_PICKAXE
  levels:
    '1':
      chance: 100
      conditions: 
        - '%block type% = MINECRAFT:COAL_ORE'
      effects:
      - SET_BLOCK:COAL_BLOCK @Block
      
      It will give an error "activating entity-based effect without a valid target (e.g. @Attacker), Coal Conversion, Level 1"

### How to reproduce

Paste the exact enchant into the enchantments.yml and test it

### Screenshots / Videos

![pre](https://github.com/GC-spigot/AdvancedEnchantments/assets/134566460/e7cbf72c-fb3b-4300-bf35-7b38f722ab48)

### "/ae plinfo" link

https://paste.md-5.net/yopedehiyu

### Server Log

https://mcpaste.io/dfafbe9082f14a62

**Comment by GC-spigot** [comment]
Target format is `@Block`, capitalised.

**Comment by Zorrkez** [comment]
Hey GC I changed it too @Block but it still does not work...

> Target format is `@Block`, capitalised.

**Comment by SirJben** [comment]
I can confirm this. It also happens on my end. 

Also tried with other materials.
`SET_BLOCK:COBBLESTONE @Block`

**Comment by GC-spigot** [comment]
Thanks for your patience! Fixed for next update
