### ISSUE TITLE
issue parse placeholders inside of <condition></condition> tags

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#3381]
### Describe the bug

after defining a variable using
- "SET_VARIABLE:random:<random number>1-100</random number>"
"and then we try to read the variable inside of <condition>"
- "DO_HARM:2 @Attacker <condition>%random% >= 50 : %allow%</condition>"
we get the following error:
"Condition (93>=50) contains letters, but must be numeric only."

### How to reproduce

copy this enchantment and paste it in the config:

gamble:
  display: '%group-color%Gamble'
  description: |-
    Deal true damage like a gambler.
    Power and odds increase with level.
  applies-to: Weapons
  type: ATTACK;ATTACK_MOB
  group: RESPLENDENT
  applies:
  - ALL_SWORD
  - ALL_AXE
  levels:
    '1':
      chance: 100
      effects:
      - "SET_VARIABLE:random:<random number>1-100</random number>"
      - "DO_HARM:2 @Attacker <condition>%random% >= 50 : %allow%</condition>"
      - "PLAY_SOUND:BLOCK_AMETHYST_BLOCK_CHIME:2:10 @Attacker <condition>%random% >= 50 : %allow%</condition>"
      - "DO_HARM:2 @Victim <condition>%random% <= 50 : %allow%</condition>"
      - "PLAY_SOUND:BLOCK_AMETHYST_BLOCK_CHIME:5:10 @Attacker <condition>%random% <= 50 : %allow%</condition>"

### "/ae plinfo" link

https://paste.md-5.net/rewarenige

**Comment by GC-spigot** [comment]
Added <= and >= support!
