### ISSUE TITLE
Health Damage

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#3382]
### Describe the bug

this is more of a feature request but at the same time its kind of a bug because other plugins have a way to remove health from an entity.

As of now, AE has several ways of removing health or doing true damage but it doesn't always work as intended.
You may use "DO_HARM:2" which does regular damage to an entity. You would think that adding IGNORE_ARMOR_PROTECTION would increase the amount of damage to one full heart while wearing full diamond armor with these two effects paired together, but it still does less than half a heart. If I take my diamond armor off, DO_HARM:2 does one and a half hearts of damage to me instead of 1 heart like it should.

Another approach to fixing this issue involves using spigot attribute placeholders, in order to scale the weapon damage based on armor. This doesn't work on mobs so it is a no go for my server.

A different approach to solving this issue involves using the %changeoutput% placeholder to deal an increased amount of damage based on the armor. This works, however it takes up a lot of space and could all be moved into the skills part of the plugin whenever that comes out.

I think you see what I am getting at. It would be much easier if AE had a way to take away a certain amount of health from an entity whether mob or player it should work on both.

change the "ADD_HEALTH" effect to "SET_HEALTH" and let it take in a positive number or negative number like so:

```java
    public void customDamage(Entity e, Double health, String type) {
        Bukkit.getScheduler().runTaskLater(new Runtime(), () -> {
            if (e instanceof Player player) {
                double maxHP = player.getAttribute(Attribute.GENERIC_MAX_HEALTH).getValue();
                double newHealth = player.getHealth() + health;
                if (newHealth < 0) {
                    // you may need to change this out with runTaskLater because there is potential for the player to die twice.
                    player.setHealth(0);
                } else if (newHealth > maxHP) {
                    player.setHealth(maxHP);
                } else {
                    player.setHealth(newHealth);
                }
            }
            else if (e instanceof LivingEntity entity) {
                double newHealth = entity.getHealth() + health;
                double maxHealth = entity.getAttribute(Attribute.GENERIC_MAX_HEALTH).getValue();
                if (newHealth < 0) {
                    entity.setHealth(0);
                } else if (newHealth > maxHealth) {
                    entity.setHealth(maxHealth);
                } else {
                    entity.setHealth(newHealth);
                }
            }
        }, 1L);
    }
}
//Edited the code to run one tick later and checked for livingentity instead of player
```
I used chat gpt to code this so you might need more error checking.

### How to reproduce

In order to reproduce the IGNORE_ARMOR_PROTECTION bug, you may try this enchantment I have created.
selfdmg:
  display: '%group-color%Damage Test'
  description: |-
    Deal 1 <3 to yourself.
  applies-to: Weapons
  type: ATTACK;ATTACK_MOB
  group: RESPLENDENT
  applies:
  - ALL_SWORD
  - ALL_AXE
  levels:
    '1':
      chance: 100
      effects:
      - "IGNORE_ARMOR_PROTECTION @Attacker"
      - "DO_HARM:2 @Attacker"
      - "PLAY_SOUND:BLOCK_AMETHYST_BLOCK_BREAK:1:10 @Attacker"

### "/ae plinfo" link

https://paste.md-5.net/sedejinedo

**Comment by Skullslice** [comment]
I edited the code to use the new attributes instead of @deprecated getMaxHealth

**Comment by ThomasWega** [comment]
Should be fixed in the next update.

I've actually added two different effects. Both of them are independent of armor

REMOVE_HEALTH: removes the specified health from the entity. Doesn't play any damage effect.
REMOVE_HEALTH_DAMAGE: does the exactly same but will play a damage effect
