### ISSUE TITLE
Trench, Vein Mining, and Smelt not giving McMMO EXP

### ISSUE THREAD

**Issue by MasonX3** [GC-spigot/AdvancedEnchantments#3384]
### Describe the bug

When an enchant with the Vein Mining, Trench, or Smelt effects is applied to a pickaxe and a naturally generated block is mined, the proper McMMO EXP is not given to the player.

### How to reproduce

Apply an enchant with the Trench, Vein Mining, or Smelt effects and mine a naturally generated stone block or an ore with McMMO installed. 

### "/ae plinfo" link

https://paste.md-5.net/ubobihivew

**Comment by reussy** [comment]
Hello,

You mean it doesn't give experience at all or it doesn't give the experience it should give?

**Comment by ThomasWega** [comment]
It works just fine for me. This is a pretty old issue, so feel free to test with the latest version and in case the issue is still present, you can open a new github issue

**Comment by JericNisperos** [comment]
Been having the same issue for the past few months already, or maybe a year already. We just decided to accept the fact that TP_DROP, SMELT, and TRENCH doesn't provide McMMO, Statistic data, Aurelium Skill and Jobs. It seems like it doesn't count as breaking the blocks. But similar plugin works fine.

**Comment by ThomasWega** [comment]
Feel free to open a new issue and we will look at it
