### ISSUE TITLE
ItemsAdder bug

### ISSUE THREAD

**Issue by Lerphie** [GC-spigot/AdvancedEnchantments#3385]
### Describe the bug

Breaking custom blocks from ItemsAdder using the enchantment pickaxe with 3x3 block breakage does not work. Also does not work auto-melting from custom ores of the ItemsAdder plugin

### How to reproduce

1) Install the custom ore from the ItemsAdder
2) Break it with any enchantment (3x3 or auto-melting)

### "/ae plinfo" link

ItemsAdder + AE

**Comment by GC-spigot** [comment]
Fixed

**Comment by Lerphie** [comment]
> Fixed
Don't work
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66962762/66b6e273-6b8c-4745-84c8-b2836008dcef)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66962762/d750b869-bb4a-4422-964c-b26cbe9d064f)
