### ISSUE TITLE
Abiding duplicating Trident

### ISSUE THREAD

**Issue by naikyys** [GC-spigot/AdvancedEnchantments#3386]
### Describe the bug

Hello, when abiding is active on trident this happens. Simply you throw trident to mob and it duplicates the trident.

### How to reproduce

Just enchant trident by abiding enchant and throw it to mob.

### Screenshots / Videos

https://youtu.be/xRT_3s8hVWs

### "/ae plinfo" link

https://paste.md-5.net/iniculuhan

**Comment by aXe18** [comment]
I tested this too, with that version of AE and all to newest. Cant reproduce either by any means

**Comment by reussy** [comment]
Hey,

On my side I was able to replicate the problem, fortunately it's fixed now.

**P.S: It is still not possible to use repair effect on the tridents, we are looking for a solution for this...**
