### ISSUE TITLE
BREAK_BLOCK and/or TRENCH effect don't give mcMMO Double Drops

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3387]
### Describe the bug

Breaking blocks with the BREAK_BLOCK effect using TRENCH target does not trigger mcMMO double drops.

### How to reproduce

Enchant a tool with a Trench enchantment.
Break blocks that should have mcMMO double drops.
Double drops are never triggered.

### "/ae plinfo" link

https://paste.md-5.net/afamoviduf

**Comment by ThomasWega** [comment]
This is a pretty old issue, so feel free to test with the latest version and in case the issue is still present, you can open a new github issue. If so, please provide a video showcase
