### ISSUE TITLE
Compatibility with AureliumSkills.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3388]
### Describe the bug

i know AdvancedEnchantments has softdepend for AureliumSkills,
so i switched mcmmo to AureliumSkills. but some bugs are happend.
bountiful_harvest, lumberjack, lucky_miner, lucky_catch are not worked with AE.
this skills are x2 drop item. when player break crops, wood, ore or fishing.

 As you can see from the video, items created by the double drop are not affected by the effect of SMELT or TP_DROPS.

### How to reproduce

i reproduce instructions to video

### Screenshots / Videos

https://youtu.be/NhabNF3yZ50

### "/ae plinfo" link

https://paste.md-5.net/usosasowus

**Comment by aXe18** [comment]
I can confirm this too, "extra blocks" do not teleport into inventory. Using latest on both plugins

**Comment by GC-spigot** [comment]
Fixed!
