### ISSUE TITLE
server crashed due to Compatibility with AureliumSkills (trench)

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3390]
### Describe the bug

when player run skill 'terraform' with trench spade, server crashed.

### How to reproduce

1. make trench spade.
2. run skill 'Terraform'.
3. server crashed. (Could not pass event TerraformBlockBreakEvent to AdvancedEnchantments v9.1.9
java.lang.StackOverflowError: null)

### "/ae plinfo" link

https://paste.md-5.net/usosasowus

### Server Log

https://mcpaste.io/37187915c0c63140

**Comment by Folas1337** [comment]
If the server does not crash, it'll end up looking like this from breaking one block:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/39222968/1439353f-3a83-43e9-9e37-500232d305e3)

Using nothing on the server but AE, AureliumSkills, LuckPerms, Vault, ViaBackwards and ViaVersion, also on the latest version of paper 1.19.4 (build 538)

The same comment happened back in April when I reported it here: https://github.com/GC-spigot/AdvancedEnchantments/issues/3276

**Comment by GC-spigot** [comment]
Should be now resolved again, sorry about that!

**Comment by Ecilpse** [comment]
> Should be now resolved again, sorry about that!

thanks. can you check this issues? #3388 
I think this is also a pretty big problem.
