### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3393]
### Describe the bug

[19:34:15] [Server thread/ERROR]: Could not pass event ProjectileHitEvent to AdvancedEnchantments v9.1.10
java.lang.NullPointerException: null

### How to reproduce

Hit vehicle with projectile

### "/ae plinfo" link

https://paste.md-5.net/pivulelase

**Comment by GC-spigot** [comment]
Please share the whole error or logs file

**Comment by GC-spigot** [comment]
Fixed!
