### ISSUE TITLE
Custom Commands Bug

### ISSUE THREAD

**Issue by Royul2k** [GC-spigot/AdvancedEnchantments#3394]
### Describe the bug

The inventory menu in customcommands.yml wont toggle off even when "enabled is set to false"

### How to reproduce

![a1ed0975e54226bd072f54f7d5a35bc0](https://github.com/GC-spigot/AdvancedEnchantments/assets/51523997/bc843903-fc17-4e82-9345-55465ccabde9)

### "/ae plinfo" link

https://gyazo.com/a1ed0975e54226bd072f54f7d5a35bc0

**Comment by Royul2k** [comment]
plinfo https://paste.md-5.net/idajuqokul

**Comment by GC-spigot** [comment]
that setting was not supposed to be there! Sorry about that one, it's now removed. We've updated the default files. Thanks for letting us know!
