### ISSUE TITLE
I encountered errors and server crashes on update 9.1.10

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3395]
### Describe the bug

After updating to version 9.1.10, I encountered errors in the console and server crashes due to issues with this plugin. I don't understand why this is happening, but it is likely a bug in the plugin's code. I request you to investigate and address this as soon as possible.
!!!!I cannot upload the entire log as it is too large. However, I can share the relevant plugin errors with you.!!!!

### How to reproduce

-

### "/ae plinfo" link

https://paste.md-5.net/gerohubahe

### Server Log

https://mcpaste.io/7722cf2e15478e52
https://mcpaste.io/f47703a067513faf
https://mcpaste.io/19841aaad69b9c43
https://mcpaste.io/f1a2440365a88570
https://mcpaste.io/177db6e2a8ac298b

**Comment by GC-spigot** [comment]
Should now be resolved!
