### ISSUE TITLE
shulker_box was disappeared with TP_DROPS pickaxe.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3398]
### Describe the bug

literally. shulker_box was disappeared with TP_DROPS pickaxe.

### How to reproduce

i attacted youtube video.

### Screenshots / Videos

https://youtu.be/M35UFTBIU3o

### "/ae plinfo" link

https://paste.md-5.net/vuhugufani

**Comment by GC-spigot** [comment]
Do you have any other enchants on this item? We've tested this: https://gyazo.com/fb7fe6c5ac043bb611371d372e95b57d and made sure it is working well.

**Comment by Ecilpse** [comment]
> Do you have any other enchants on this item? We've tested this: https://gyazo.com/fb7fe6c5ac043bb611371d372e95b57d and made sure it is working well.

글래스해머:
  display: '%group-color%글래스해머'
  description: |-
    유리를 즉시 파괴할 수 있게 됩니다.
    &7(수확은 적용되지 않습니다)
  applies-to: 
  type: SWING
  group: 레어
  applies:
  - ALL_AXE
  - ALL_PICKAXE
  - ALL_SPADE
  levels:
    '1':
      conditions:
      - '%block type% contains GLASS : %allow%'
      effects:
      - BREAK_BLOCK @Block

with this enchant. no vanilla enchant.

And when will there be a revised build for this issue #3388 ?
Currently, there are more than 300 players playing on our server, and there are a lot of problems due to the bug.
