### ISSUE TITLE
Trench doesn't work with CustomModelData tools

### ISSUE THREAD

**Issue by Agaloth** [GC-spigot/AdvancedEnchantments#3399]
### Describe the bug

When using a tool with Custom Model Data, trench doesn't work.

### How to reproduce

Use a custom pickaxe with custommodeldata

### Screenshots / Videos

https://youtu.be/woHl3hHmnAo

### "/ae plinfo" link

https://paste.md-5.net/mixecejezi

**Comment by Agaloth** [comment]
Any news on this?

**Comment by GC-spigot** [comment]
Is this tool added to enchantment? And config.yml pickaxes?

**Comment by Agaloth** [comment]
what do you mean?

**Comment by SirJben** [comment]
I think it's bugged @GC-spigot 

Not custom model data
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63577950/ed4119b8-7e42-4715-a742-08ece3fbbfe9)

Custom model data
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63577950/3fc3fac1-5307-43d1-ab76-874b6a50fde7)

**Comment by Agaloth** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/issues/3414

Someone is having another issue related to CustomModelData tools

**Comment by Agaloth** [comment]
Any updates? My donators keeps asking for refunds because of trench not working because of this issue

**Comment by GC-spigot** [comment]
Looking into this

**Comment by GC-spigot** [comment]
Fixed!
