### ISSUE TITLE
EFFECT_STATIC effects can be kept by swapping items in hand

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3401]
### Describe the bug

If you put an item with an EFFECT_STATIC enchantment in your hand, and any item in your off-hand, then press the button to swap main hand/off hand items, you can unequip both items and keep the static effects.

### How to reproduce

Put an EFFECT_STATIC enchanted item in your main hand
Put any other item in your off-hand
Swap your main hand and offhand items with the keybind.
You can now unequip both items while keeping the effects.

### "/ae plinfo" link

https://paste.md-5.net/ebiguyecod

**Comment by GC-spigot** [comment]
I can't recreate this, please record a gif / video. Thanks!
https://gyazo.com/5e2b1610cadd60039df88e209ee17dd8

**Comment by Gilthunderx** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/issues/3425

Same bug, I have a video

**Comment by Gilthunderx** [comment]
Bump

**Comment by GC-spigot** [comment]
Fixed!
