### ISSUE TITLE
INVINCIBLE EFFECT BUG

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3402]
### Describe the bug

I can't toggle my Invincibility, that it overrides the /gmc and /godmode of Essentials.

Also is it possible to make it that it have "ticks" so if ever that the you can be invincible for 3 secs etc etc.

### How to reproduce

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/87959487/073bbb01-8b55-49a6-8c3d-b7d3f6caee13)

### "/ae plinfo" link

https://paste.md-5.net/adojitefef

**Comment by GC-spigot** [comment]
I can't really do anything about essential overriding it, the goal of it is to be as performance efficient as possible so it does not have any time feature whatsoever.
