### ISSUE TITLE
MORE_DROPS applies to player-placed blocks

### ISSUE THREAD

**Issue by jYearyBoy** [GC-spigot/AdvancedEnchantments#3405]
### Describe the bug

MORE_DROPS enchantment works on player-placed blocks. Players can very easily duplicate ores right now because of this.

### How to reproduce

Create a custom weapon with an enchantment that applies "MORE_DROPS" and break blocks you placed. Break the blocks, then replace them for infinite profit. 

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/45554415/a7abb62e-6524-4d9b-b6bb-98417c006b34

### "/ae plinfo" link

Unable to send this, the plugin is down right now.

**Comment by ThomasWega** [comment]
Should be fixed in the next update
