### ISSUE TITLE
Plugin doesn't work for some reason

### ISSUE THREAD

**Issue by staypleur** [GC-spigot/AdvancedEnchantments#3408]
### Describe the bug

First of all, I am Korean. Sorry in advance for my poor English. I bought it and applied it to the game, and when I use most commands like /ae, only the words you see in the picture below appear in the chat window. Is there a solution to this?

### How to reproduce

I just opened the server with spigot and put the plugin jar in the plugin file.

### Screenshots / Videos

![2023-06-02_02 08 11](https://github.com/GC-spigot/AdvancedEnchantments/assets/133564503/33dfbcf0-c41e-4f65-ac32-095c276b3024)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/133564503/6ebe3cce-6574-4f6f-a4de-d75186f212d4)
![image2](https://github.com/GC-spigot/AdvancedEnchantments/assets/133564503/b5c3f5a7-0172-4edd-b0e7-112d229d1eef)
![image3](https://github.com/GC-spigot/AdvancedEnchantments/assets/133564503/bd0d039f-ada0-4693-9580-f4ce098059ab)

### "/ae plinfo" link

/ae pinfo skipPlugins

**Comment by Herieman2** [comment]
I seem to have run into this same issue, when on a Spigot version the plugin refuses to fully load, though on Paper it does seem to work strangely.

**Comment by GC-spigot** [comment]
Fixed next update! Sorry about delays, been moving to USA
