### ISSUE TITLE
[Feature Request] Matrix AntiCheat Support

### ISSUE THREAD

**Issue by newbie029** [GC-spigot/AdvancedEnchantments#341]
Can you please add support for this plugin?
https://www.spigotmc.org/resources/matrix-anti-cheat-advanced-anti-cheat-solution-hack-blocker-1-8-1-12-1-13.64635/

The problem is with the speed check.
Like Shockwave enchantments will make player kicked

**Comment by GC-spigot** [comment]
Tell the author to add support to velocity modifications.

**Comment by newbie029** [comment]
http://prntscr.com/mpash5
done sir
