### ISSUE TITLE
Enchants doesn't work

### ISSUE THREAD

**Issue by GinoCarino** [GC-spigot/AdvancedEnchantments#3410]
### Describe the bug

Some enchant doesn't works

### How to reproduce

I don't know, I downloaded new version and some enchants doesn't works

### Screenshots / Videos

![Immagine 2023-06-02 185425](https://github.com/GC-spigot/AdvancedEnchantments/assets/132331890/2d8dd51a-f01f-4c9c-ad5b-2df53e3e6de5)

### "/ae plinfo" link

https://paste.md-5.net/soqajemaji

### Server Log

https://mcpaste.io/d19579fa8800618f

**Comment by SirJben** [comment]
Hello @GinoCarino can you specify what enchantments are not working?

**Comment by GinoCarino** [comment]
Strike, Impact, Explosive, Frenzy, Hunter, Soulless, Virus, Poisoned, Snare, Perish, Bowmaster, Arrowdeflect, Arrowbreak, Fumble, Reinforced, Piercing, Archer, Marksman, Poseidon, Heavy, Hellfire, Missile, Longbow, Chaos, Abiding, Striker, Sniper, Deadshot, Neutralize, Spark

**Comment by SirJben** [comment]
@GinoCarino open a ticket in Discord and send your enchantments.yml

**Comment by GC-spigot** [comment]
These are working completely fine
