### ISSUE TITLE
rates not working

### ISSUE THREAD

**Issue by ttt0** [GC-spigot/AdvancedEnchantments#3411]
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66686400/293723ba-8c7a-489e-910d-23473f0a7b5a)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66686400/19f51ac8-1554-4415-998d-f9235ae02ab4)
Even though the settings are like this, the book with a lower rate is still coming

### How to reproduce

I don't know

### "/ae plinfo" link

https://paste.md-5.net/kakixaqero

### Server Log

https://mcpaste.io/e06f0c017ef20d41

**Comment by GC-spigot** [comment]
Set `random` to false above that screenshot that you sent, then those rates are enabled
