### ISSUE TITLE
Telepathy not working with Jobs.

### ISSUE THREAD

**Issue by AEItsJonay** [GC-spigot/AdvancedEnchantments#3412]
### Describe the bug

When I use telepathy on any tool (hoe, pickaxe, digger) while using that item, the player will not get paid. We are updated to the latest version of AdvancedEnchants and Jobs Reborn. Ive tested this with multiple jobs, items and actions (breaking stone, farming etc). Any way to fix this?

### How to reproduce

Have jobs reborn, use an item with telepathy and you will not get paid by jobs while using that item.

### "/ae plinfo" link

https://paste.md-5.net/wazusaqozo

**Comment by ThomasWega** [comment]
We were not able to replicate this issue. This is a pretty old issue and AE had many updates since then. If you still have this issue even on the latest issue, feel free to create a new github issue and please provide a video
