### ISSUE TITLE
Smelting Enchantment is not working with Custom Item(Pickaxe) [ItemsAdder]

### ISSUE THREAD

**Issue by DarrienZ** [GC-spigot/AdvancedEnchantments#3414]
### Describe the bug

https://youtu.be/ZllA8g_IhaQ

Custom Pickaxe ItemsAdder
https://youtu.be/mxfbuWwGC6c

### How to reproduce

The enchantment will only smelt the ore 100% when I use normal pickaxe 

And I found out that this enchantment will also stop dropping other's block eg: concrete/log

Custom item pickaxe is using netherite
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/108975040/8b90b45e-ac63-4baf-b4e3-2ea5fa1b4ab6)

### Screenshots / Videos

https://youtu.be/ZllA8g_IhaQ

Custom Pickaxe ItemsAdder
https://youtu.be/mxfbuWwGC6c

### "/ae plinfo" link

https://paste.md-5.net/eganivinuw

### Server Log

https://mcpaste.io/398d3e2ed1a9863a

**Comment by DarrienZ** [comment]
Damn paid plugin but support is slow?...

**Comment by DarrienZ** [comment]
After removing CosmeticCore and InteractiveChatDiscordSRVAddons it temp-fixed the problem

**Comment by DarrienZ** [comment]
Update: After installing lastest battlepass plugin the smelting enchantment started bugging again

**Comment by GC-spigot** [comment]
Fixed!
