### ISSUE TITLE
Dupe and enchant bug on anvil 

### ISSUE THREAD

**Issue by BLACKGAMER1221** [GC-spigot/AdvancedEnchantments#3418]
### Describe the bug

when you put enchanted item on anvil with enchant level 8 and higher you cant convert your item and can dupe it.
anvil controll : true 
use repair cost: true 
illegal vanilla/custom enchant : false
backward enchant: false 
max enchantment level : 10

### How to reproduce

put ypur items with enchant level 8 and higher (example: 2 sword with  sharpness 8) on anvil and shift_rightclick on output sword
now you have duped item with sharpness V.

### Screenshots / Videos

https://mega.nz/file/UxpB2JyZ#ADykWeYDW9dwLrlKQPg0y91twYpueYMFyeozSvJeljk

**Comment by DarrienZ** [comment]
I got the same problem too but only when I use creative.

**Comment by GC-spigot** [comment]
This is definitely creative mode issue, we can't do much about it since creative mode inventories are mostly bugged
