### ISSUE TITLE
MORE_DROPS dupes

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#3419]
### Describe the bug

default enchantment diploid and multiplication have dupe  problem because of MORE_DROPS

all enchantment using MORE_DROPS can be dupe

### How to reproduce

1.dig shulker box/any block
condition can prevent direct dig shulker box dupe but there is a special case

special case:  trench + more_drops
trench dig a block next to the dupe target box(e.g. shulker box, video below)
cannot be prevented using condition

2. kill mob holding shulker box
wait mob pick up dupe item, kill mob with more_drops enchantments

### Screenshots / Videos

https://youtu.be/7TVkG1zgdX4
https://youtu.be/AuxsGjb4W2E

### "/ae plinfo" link

https://paste.md-5.net/fuwujonaco

### Server Log

https://paste.denizenscript.com/View/110676

**Comment by ThomasWega** [comment]
Hello, do you mind trying out if using a condition works for you?

"%block type% = SHULKER_BOX : %stop%"

**Comment by ThomasWega** [comment]
Fixed!
