### ISSUE TITLE
[Feature Request] AE working with key crates

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#342]
So I'm trying to get crates reloaded to give items with advanced enchants. The way we've done it in the past is configure it in the crates reloaded to give the lore text that matches the enchants. This has worked for other plugins but does not work for AdvancedEnchantments. 

I was able to recreate the White Scroll, and get it to work fine with crates reloaded. I cannot get any enchants on gear to work.

Is there a way to get this to work, or a way that can be added?

**Comment by GC-spigot** [comment]
Not possible cause AE utilizes NBT tags rather than lores for more customisability.
