### ISSUE TITLE
 Could not pass event PlayerFishEvent 

### ISSUE THREAD

**Issue by Thangsss** [GC-spigot/AdvancedEnchantments#3420]
### Describe the bug

When fishing with a rod with Bait and Hook, neither do anything and this error message is in console
[message.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/11671446/message.txt)

### How to reproduce

No idea

### "/ae plinfo" link

https://paste.md-5.net/qitocurine

**Comment by GC-spigot** [comment]
Does this still happen on recent version?
