### ISSUE TITLE
Telepaty duping [ItemsAdder]

### ISSUE THREAD

**Issue by DarrienZ** [GC-spigot/AdvancedEnchantments#3422]
### Describe the bug

I think this only happens to custom items pl

When the tools have Efficiency 4-5 it will start able to dupe.

### How to reproduce

- 

### Screenshots / Videos

With AE: https://youtu.be/ezO74OgEyOQ
Without AE: https://youtu.be/V_14PPVsof0
Without Efficiency but with AE: https://youtu.be/o9g0_paZCyc

### "/ae plinfo" link

https://paste.md-5.net/ajuzolecow

### Server Log

https://mcpaste.io/512f3cbc4bb12e2e

**Comment by GC-spigot** [comment]
I can't see the videos unfortunately, so can't verify this issue. Can you reupload or unprivate videos?

**Comment by DarrienZ** [comment]
Without Efficiency but with AE: https://youtu.be/o9g0_paZCyc
Without AE: https://youtu.be/0Motnx2FGW8
With AE: https://youtu.be/ezO74OgEyOQ

Now?

**Comment by ThomasWega** [comment]
We were unable to replicate this issue. If anyone still has this issue even on the latest version, please make sure to reopen a new issue.
