### ISSUE TITLE
TP_DROPS drops only 1 slab from double-slab blocks

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3424]
### Describe the bug

When breaking a double-slab block (two slabs placed in one block) with a TP_DROPS tool, only one slab is dropped.

### How to reproduce

Enchant a tool with a TP_DROPS enchantment.
Break a double-slab block
Only one slab drops

### "/ae plinfo" link

https://paste.md-5.net/umefuqurus

**Comment by GC-spigot** [comment]
Fixed!
