### ISSUE TITLE
Off-hand Bug with CE

### ISSUE THREAD

**Issue by Gilthunderx** [GC-spigot/AdvancedEnchantments#3425]
### Describe the bug

The bug is quite simple, the enchant of an item like Haste or Sharpness will not go away when is equipped using OFF-Hand, even tho the item is unequipped.

### How to reproduce

Place an custom enchanted on your off hand  and **unequip using Shift button**  and the CE will remain.

### Screenshots / Videos

https://www.mediafire.com/file/a96btqioyalgm1h/Minecraft_1.16.5_LabyMod_3.9.58_2023-06-10_15-42-00.mp4/file

### "/ae plinfo" link

https://paste.md-5.net/punuyofico

**Comment by GC-spigot** [comment]
Fixed!
