### ISSUE TITLE
AE Ignores Response From Checkitem Placeholder

### ISSUE THREAD

**Issue by scottyboii** [GC-spigot/AdvancedEnchantments#3428]
### Describe the bug

So when creating an enchantment that uses the result of the checkitem placeholder as a condition, it is seemingly ignored.

An example of my enchant can be seen as follows:

```saturation:
  display: '%group-color%Saturation'
  description: 'Gives saturation in offhand'
  applies-to: 'Tools'
  group: 'SIMPLE'
  type: 'HELD'
  applies:
    - 'ALL_HOE'
  levels:
    '1':
      condition:
        - "%checkitem_inhand:off,lorecontains:&7Saturation,mat:DIAMOND_HOE% = yes : %allow%"
      effects:
        - 'POTION:speed:3'
 
 ```
 
At the suggestion of one of your Admins, I attempted to try the reverse of what I want 

`"%attacker checkitem_inhand:main,lorecontains:&7Saturation,mat:DIAMOND_HOE% = yes : %stop%"`

However, this also didn't work.

When the placeholder %checkitem_inhand:off,lorecontains:&7Saturation,mat:DIAMOND_HOE% is parsed ingame, it correctly returns "yes" if in offhand, and "no", if in mainhand. However, AE activates the enchant when the item is in either hand.

### How to reproduce

Create an enchant with the above syntax
Reload
Put item in your main hand - Observe the enchant activates, it should not.

### "/ae plinfo" link

https://paste.md-5.net/omenuqubaj

**Comment by Skullslice** [comment]
Its a shot in the dark but ae might parse strings weirdly compared to booleans. Normally I would assume it translates this internally but you could try putting yes or no in quotes.

**Comment by scottyboii** [comment]
> Its a shot in the dark but ae might parse strings weirdly compared to booleans. Normally I would assume it translates this internally but you could try putting yes or no in quotes.

I tried the following with no success:

`        - '%checkitem_inhand:off,lorecontains:&7Saturation,mat:DIAMOND_HOE% = "yes" : %allow%'`

**Comment by Truongvv10** [comment]
I have the same similar issue, I can confirm that it doesn't work. 
https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/841740907467636756/1132828360670720021/transcript-aenchantments-4343.html

**Comment by Truongvv10** [comment]
Is there no updates on this? It's been more than a month?

**Comment by Awpmeister2170** [comment]
Hello, i apologise for the delay i have mentioned this to our main developers and they will look into this asap for you!

we have been very busy getting as many fixes out as possible.

**Comment by Awpmeister2170** [comment]
Hello, could you also try conditions not condition

**Comment by Truongvv10** [comment]
Doesnt work

**Comment by GC-spigot** [comment]
Looking into this.

**Comment by GC-spigot** [comment]
First problem - it's `conditions:` not `condition:`. Secondly - conditions are lower-case only, meaning this will break with `Saturation` check. 

To check for custom enchantments you can use different condition: `%has enchantment in hand of saturation%`.

This completely worked, except the Saturation check
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/13188801/3289518e-f98c-4cb7-a853-3a27d3f53d30)
