### ISSUE TITLE
Aurelium Skills and McMMO Combined

### ISSUE THREAD

**Issue by JericNisperos** [GC-spigot/AdvancedEnchantments#3430]
### Describe the bug

Hi, I have TP_DROPS enchant called Magnetic. If I don't have that enchant on my tool, I gain XP from Aurelium Skill and McMMO at the same time. But when I add a TP_DROPS on the tool, I no longer gain McMMO Exp but still be able to earn Exp from Aurelium Skills. Additionally, McMMO Skills no longer work like auto replant.

### How to reproduce

1. Add Aurelium Skills, McMMO and AE on the server
2. Create and apply an enchant with TP_DROPS and put it on a HOE
3. Harvest wheats using the HOE with TP_DROPS

### "/ae plinfo" link

https://paste.md-5.net/opawavasec

### Server Log

N/A

**Comment by ThomasWega** [comment]
Hey! This is a pretty old issue, sorry for not handling this sooner. I've tried with the latest version of all plugins, and it seems to work fine for me. Please create a new github issue, if you still have these issues on the latest version
