### ISSUE TITLE
System.out/err.print (JavaPlugin#getLogger)

### ISSUE THREAD

**Issue by BLACKGAMER1221** [GC-spigot/AdvancedEnchantments#3431]
### Describe the bug

hi i update my server from 1.13 to 1.18.2 but when i run the server get the warn  like this on loot of plugin 
[00:20:39 WARN]: Nag author(s): '[AdvancedPlugins]' of 'AdvancedEnchantments' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).

server: Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

i know its not a plugin bug but i dont know how to fix it pls help me 

### How to reproduce

i dontknow

### "/ae plinfo" link

dont need

**Comment by GC-spigot** [comment]
Version of AdvancedEnchantments?

**Comment by BLACKGAMER1221** [comment]
> Version of AdvancedEnchantments?

i update AdvancedEnchantments from 9.2.1 to 9.2.4 and it fixed but i still have this issues on some of my other plugins 

one of this my plugins return this error ((Your server version is not handled with NMS.))

java version : OpenJDK 64-Bit Server VM 17.0.2+8-86 (windows 10)

if you can pls help me

**Comment by GC-spigot** [comment]
Should be resolved next update. Try updating paper to most recent version if you can, might be a problem with that.
