### ISSUE TITLE
Pickaxes with the Trench enchantment don't drop shulker boxes [ItemsAdder]

### ISSUE THREAD

**Issue by DarrienZ** [GC-spigot/AdvancedEnchantments#3433]
### Describe the bug

Pickaxes with the Trench enchantment don't drop shulker boxes

### How to reproduce

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/108975040/4862aa40-ba94-4d77-8b78-de59c093d62e)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/108975040/ba0f5295-5bdb-4012-a79c-bc2c9f9b5f76)

### Screenshots / Videos

https://youtu.be/HJETrdUufL4

### "/ae plinfo" link

https://paste.md-5.net/ihonejeduq

### Server Log

.

**Comment by GC-spigot** [comment]
Fixed!
