### ISSUE TITLE
AdvancedPlugins UI and ItemsAdder

### ISSUE THREAD

**Issue by JorgeEspadas** [GC-spigot/AdvancedEnchantments#3434]
### Describe the bug

Hi, this is not a bug but a warning that i'm getting with the latest version of both plugins.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/45724402/24bfa7b8-bdaa-4bd2-877e-ca236629d98a)

This is on Spigot 1.20.1 with the latest AE and IA (that released today), it has to be migrated to the new folder structure to avoid having issues

### How to reproduce

- Install AdvancedEnchantments
- Install ItemsAdder
- Install AdvancedEnchantments UI

### "/ae plinfo" link

https://paste.md-5.net/kecocuhene

**Comment by GC-spigot** [comment]
We're working on updating them!
