### ISSUE TITLE
AdvancedEnchantments and ReviveMe

### ISSUE THREAD

**Issue by JorgeEspadas** [GC-spigot/AdvancedEnchantments#3435]
### Describe the bug

This is a bug happening at the time of death when **ReviveMe** is installed
Nothing breaks or any major issue is detected so far but the stacktrace gets printed each time the player dies.

### How to reproduce

- Install ReviveMe
- Install AdvancedEnchantments
- Be Killed in the server and either wait for the timer to expire or kys by pressing shift.
- Log will printed in the console.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/45724402/4ba6d373-dfaf-4098-a7a1-e2d1f24b5a31)

### "/ae plinfo" link

https://paste.md-5.net/kecocuhene

**Comment by GC-spigot** [comment]
Resolved!
