### ISSUE TITLE
Major bug involving the @Victim target

### ISSUE THREAD

**Issue by SpacePjoes** [GC-spigot/AdvancedEnchantments#3437]
### Describe the bug

The bug is fairly simple to reproduce and leaves many advanced/complex enchantments unusable and broken, as it replaces all @Victim targets with @Self (I think), after any WAIT effect.

### How to reproduce

When an enchantment has 'WAIT' as an effect, it appears to "forget" the @Victim target, and apply to @Self instead. This means that in an enchantment with the effects:

effects:
  - 'LIGHTNING @Victim'
  - 'WAIT:10'
  - 'LIGHTNING @Victim'

the first 'LIGHTNING' will apply to @Victim, as specified. However, the second 'LIGHTING' will apply to @Self, since there is a 'WAIT' before it.

### Screenshots / Videos

The videos included are only of one of the many examples in the enchantments I used to use. The correct version shows a Piglin Brute flying away, the incorrect one me flying away from a Zombified Piglin, as the enchant "forgot" it was the target.

https://github.com/GC-spigot/AdvancedEnchantments/assets/60235552/9267b524-e4fd-4ed5-82c0-d30332815e63

https://github.com/GC-spigot/AdvancedEnchantments/assets/60235552/5369be5d-9efc-440b-a296-c59d9ba8ebd7

### "/ae plinfo" link

https://paste.md-5.net/zidoyalise

**Comment by SpacePjoes** [comment]
Update: The same occurs with an @Aoe target, which will also default back to @Self

**Comment by ThomasWega** [comment]
I've just tried it myself. Setting the effect exactly the same way.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/764bf677-6aa6-47ff-a2e4-1b3b152e0c35)

However, it seems to work just fine for me. Could you try if this issue is still present in the latest version (9.3.0) ?
![ezgif com-optimize](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/bebc6df0-3d96-49e5-94dc-bd003de5f9d2)

**Comment by SpacePjoes** [comment]
Interestingly it does look like the lightning effect does work now. Here's a couple of examples of enchantments that do not work:

All @Victim instead applies to @Self here:
`3:
      cooldown: 12
      conditions:
        - "%damage cause% = THORNS : %stop%"
        - '%damage% > %victim health% : %stop%'
      effects:
        - "CONSOLE_COMMAND:minecraft:execute at %attacker name% run playsound minecraft:celestium.enchantments.trickster ambient @a[distance=..10] ~ ~ ~ 0.7 1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window ||||||||||||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c|&7|||||||||||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c||&7||||||||||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c|||&7|||||||||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c||||&7||||||||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c|||||&7|||||||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c||||||&7||||||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c|||||||&7|||||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c||||||||&7||||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c|||||||||&7|||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c||||||||||&7||||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c|||||||||||&7|||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c||||||||||||&7||||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c|||||||||||||&7|||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c||||||||||||||&7||||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c|||||||||||||||&7|||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c||||||||||||||||&7||"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &c|||||||||||||||||&7|"
        - "POTION:WEAKNESS:5:3 @Victim"
        - 'POTION:LEVITATION:9:5 @Victim'
        - "TELEPORT_BEHIND @Attacker"
        - "PULL_AWAY:2 @Victim"
        - "WAIT:1"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &a||||||||||||||||||"
        - "POTION:STRENGTH:5:4 @Attacker"
        - "CONSOLE_COMMAND:minecraft:execute at %attacker name% run particle minecraft:sweep_attack ^ ^1.2 ^1.5 0 0 0 1 1 normal"
        - "WAIT:4"
        - "ACTION_BAR:&8☽ &3Trickster: &7critical window &8||||||||||||||||||"
        - "WAIT:220"
        - "ACTION_BAR:&8☽ &3Trickster: &7available"`


Another example is this, @Aoe applies to @Self here:
`
4:
      cooldown: 6
      conditions: 
        - "%damage cause% = THORNS : %stop%"
        - "%attacker is critical% = FALSE : %stop%"
        - "%attacker is sneaking% = FALSE : %stop%"
      effects:
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'ACTION_BAR:&c🔥 &aInferno: &7||||||||||||||||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'ACTION_BAR:&c🔥 &aInferno: &c|&7|||||||||||||||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'ACTION_BAR:&c🔥 &aInferno: &c||&7||||||||||||||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 1'
        - 'ACTION_BAR:&c🔥 &aInferno: &c|||&7|||||||||||||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 1'
        - 'ACTION_BAR:&c🔥 &aInferno: &c|||||&7|||||||||||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 1'
        - 'ACTION_BAR:&c🔥 &aInferno: &c||||||&7||||||||||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 1'
        - 'ACTION_BAR:&c🔥 &aInferno: &c|||||||&7|||||||||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 1'
        - 'ACTION_BAR:&c🔥 &aInferno: &c|||||||||&7|||||||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~-3 0.2 0.5 0.2 0.01 2'
        - 'ACTION_BAR:&c🔥 &aInferno: &c||||||||||&7||||||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~-3 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'ACTION_BAR:&c🔥 &aInferno: &c|||||||||||&7|||||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~-3 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 2'
        - 'ACTION_BAR:&c🔥 &aInferno: &c|||||||||||||&7|||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~-3 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 2'
        - 'ACTION_BAR:&c🔥 &aInferno: &c||||||||||||||&7||||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~-3 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-3 ~ ~ 0.2 0.5 0.2 0.01 3'
        - 'ACTION_BAR:&c🔥 &aInferno: &c|||||||||||||||&7|||||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~-3 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 3'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-3 ~ ~ 0.2 0.5 0.2 0.01 3'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.8 ~ ~1.1 0.2 0.5 0.2 0.01 3'
        - 'ACTION_BAR:&c🔥 &aInferno: &c|||||||||||||||||&7|||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~-3 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 3'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 3'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-3 ~ ~ 0.2 0.5 0.2 0.01 3'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.8 ~ ~1.1 0.2 0.5 0.2 0.01 3'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.1 ~ ~2.1 0.2 0.5 0.2 0.01 5'
        - 'ACTION_BAR:&c🔥 &aInferno: &c||||||||||||||||||&7||'
        - 'WAIT:2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~3 0.2 0.5 0.2 0.01 1'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~1.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~3 ~ ~ 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~ ~ ~-3 0.2 0.5 0.2 0.01 2'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-1.1 ~ ~-2.8 0.2 0.5 0.2 0.01 3'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.1 ~ ~-2.1 0.2 0.5 0.2 0.01 3'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.8 ~ ~-1.1 0.2 0.5 0.2 0.01 3'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-3 ~ ~ 0.2 0.5 0.2 0.01 3'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.8 ~ ~1.1 0.2 0.5 0.2 0.01 4'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-2.1 ~ ~2.1 0.2 0.5 0.2 0.01 5'
        - 'CONSOLE_COMMAND:execute at %attacker name% run particle minecraft:flame ~-1.1 ~ ~2.8 0.2 0.5 0.2 0.01 10'
        - 'ACTION_BAR:&c🔥 &aInferno: &7Enflame! @Attacker'
        - 'PLAY_SOUND_OUTLOUD:ENTITY_ZOMBIE_INFECT:0.6:1'
        - 'PLAY_SOUND_OUTLOUD:BLOCK_FIRE_AMBIENT:1:1'
        - 'PLAY_SOUND_OUTLOUD:ENTITY_GHAST_SHOOT:0.3:0.3'
        - 'BURN:12 @Aoe{radius=3,target=damageable}'
        - 'BURN:12 @Aoe{radius=3,target=mobs}'
        - 'WAIT:90'
        - 'ACTION_BAR:&c🔥 &aInferno: &7available @Attacker'
`

**Comment by SpacePjoes** [comment]
[simplified.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/12204439/simplified.txt)
Interestingly in this simplified version, the second enchantment DOES work correctly (just barebones compared to the original), however the first enchantment does NOT work, and functions as shown in the original video.

**Comment by LambChomps** [comment]
+1. This recently started breaking many of my enchants.
Did some testing, and the following works:
```yaml
test:
  display: '%group-color%Test'
  description: |-
    test
  applies-to: Items
  type: ATTACK;ATTACK_MOB
  group: BASIC
  applies:
    - ALL_SWORD
    - ALL_TOOLS
  levels:
    '1':
      effects:
        - "MESSAGE:hi"
        - "WAIT:20"
        - "MESSAGE:hi"
```
However, adding seemingly any effects after the wait (have tested DO_HARM, PARTICLE, and PLAY_SOUND_OUTLOUD) targeted at something will instead redirect everything after the wait towards whatever is being targeted by that effect. So,
```yaml
      effects:
        - "MESSAGE:hi"
        - "WAIT:20"
        - "MESSAGE:hi"
        - "PARTICLE:HEART:5:1 @Victim"
```
Will incorrectly redirect the message to the victim. Or,
```yaml
      effects:
        - "MESSAGE:hi"
        - "WAIT:20"
        - "DO_HARM:1 @Victim"
        - "PARTICLE:HEART:5:1 @Attacker"
```
Will incorrectly redirect the damage at the attacker.

**Comment by Truongvv10** [comment]
I'm having some of these issues too

**Comment by GC-spigot** [comment]
Fixed!
