### ISSUE TITLE
Trench does not apply with more drop

### ISSUE THREAD

**Issue by cada3141** [GC-spigot/AdvancedEnchantments#3438]
### Describe the bug

If ores destroyed by a trench, the more drop effect doesn't work.
Mining ores directly works fine, but more drop doesn't work if trench is triggered by breaking blocks around the ores.

### How to reproduce

mining blocks around ores with trench and more drop.

### "/ae plinfo" link

https://paste.md-5.net/jemicuridu

**Comment by GC-spigot** [comment]
Seems to be working fine for me now on latest version, try updating
