### ISSUE TITLE
Custom Enchant breaking on world change

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#344]
AdvancedEnchantments: 5.2.5 - was a bug on previous versions
Paper spigot 1.13.2
Using multiverse core for extra worlds.

We have a custom enchant that grants the fly effect. On world change it turns it off. However if you are in a world where it turns it off, and you take off the boots, it turns it back on. So you can have flight without wearing the gear. The flight does turn off again when they change worlds.

`
wings:
  display: '%group-color%Wings'
  description: "Heroic Enchantment.\nGives creative flight."
  applies-to: 'Boots'
  type: 'EFFECT_STATIC'
  group: 'HEROIC'
  applies:
  - ALL_BOOTS
  levels:
    1:
      effects:
      - FLY

`

**Comment by GC-spigot** [comment]
Sounds like a Multiverse issue. I do not recommend having Flight enchants as they could be very much abused in many ways, intentionally or not. 

Multiverse enables/disables fly, you should look into that.

**Comment by Kbryst** [comment]
Got some time to test it,

It's conflicting with EssentialsX. I have the flight command disabled in EssentialsX. Still can't fix it.


I do understand the recommending of not using flight as an enchant, its been apart of our server for a long time with a different enchant plugin, players are just too used to it now to remove it as an enchant. 

I think the issue is the enchant "toggles" flight, so when they take it off after it gets auto-toggled off, it reenables it for them.
