### ISSUE TITLE
"SMELT" effect does not work on certain blocks

### ISSUE THREAD

**Issue by SpacePjoes** [GC-spigot/AdvancedEnchantments#3440]
### Describe the bug

I'm pretty sure this used to work on old versions. The blocks include: Netherrack, Clay, Red Sand, Logs, Cactus, Stone (to Smooth Stone), possibly others. Sand and Cobblestone are examples of blocks that do work. These may be hardcoded, but probably shouldn't be.

### How to reproduce

Use the "SMELT" effect on any block in the previous list (possibly more)

### "/ae plinfo" link

https://paste.md-5.net/wazanatimu

**Comment by GC-spigot** [comment]
Added some of the mentioned materials. They didn't work in previous versions ever.
