### ISSUE TITLE
"CATCH_FISH" effect no longer supports MORE_DROPS

### ISSUE THREAD

**Issue by SpacePjoes** [GC-spigot/AdvancedEnchantments#3441]
### Describe the bug

This used to work in previous versions, however MORE_DROPS no longer activates when a Fishing Rod is enchanted with a CATCH_FISH enchantment.

### How to reproduce

Get a catch with a Fishing Rod enchanted with a CATCH_FISH enchantment. You will receive no extra drops.

### "/ae plinfo" link

https://paste.md-5.net/wazanatimu

**Comment by GC-spigot** [comment]
It's definitely working on latest version, tested it.
