### ISSUE TITLE
"BOOST" effect gives hardly any momentum

### ISSUE THREAD

**Issue by SpacePjoes** [GC-spigot/AdvancedEnchantments#3442]
### Describe the bug

This effect used to give significantly more on previous versions, now it is practically useless, at it gives about 3-5 blocks max (BOOST level 1000 or so).

### How to reproduce

Use any BOOST enchantment, however I only tested a **forward** BOOST.

### "/ae plinfo" link

https://paste.md-5.net/wazanatimu

**Comment by GC-spigot** [comment]
I've increased the "safe" limits, but there's a huge limitation now with "sudden" boosts for Spigot. The limit is now doubled, should be better but cannot increase any more.

**Comment by SpacePjoes** [comment]
There's a Spigot plugin called "Parkour", which is updated for 1.20. You could try to take a look at this plugin, as it does have blocks which give you a very large sudden boost (over 10 blocks), which may be useful to look into, perhaps ask the author how they did it. That's of course your call though.
