### ISSUE TITLE
"BREAK_BLOCK" effect no longer breaks blocks that are unbreakable

### ISSUE THREAD

**Issue by SpacePjoes** [GC-spigot/AdvancedEnchantments#3443]
### Describe the bug

Using the BREAK_BLOCK effect no longer breaks Bedrock. This worked in previous versions. I think this should be possible, as you can simply exclude it with a condition.

### How to reproduce

Use any BREAK_BLOCK enchantment on Bedrock. It will not break.

### "/ae plinfo" link

https://paste.md-5.net/wazanatimu

**Comment by GC-spigot** [comment]
This is for safety purposes, will add a blacklist list in configs in future.

**Comment by SpacePjoes** [comment]
Awesome
