### ISSUE TITLE
"BREAK_TREE" effect is inconsistent on trees that do not go straight up

### ISSUE THREAD

**Issue by SpacePjoes** [GC-spigot/AdvancedEnchantments#3444]
### Describe the bug

Using the BREAK_TREE effect often doesn't break attached log blocks of larger trees/trees with branches. I understand this may be hard to fix.

### How to reproduce

Use an enchantment with the BREAK_TREE effect to break a cherry / mangrove / acacia / dark oak / large oak / large jungle tree. Some logs will not break.

### "/ae plinfo" link

https://paste.md-5.net/wazanatimu

**Comment by GC-spigot** [comment]
"Fixing" this will cause a lot of side effects, e.g. touching trees will be broken together. Unfortunately it has to stay this way.
