### ISSUE TITLE
"combo-limit" setting from config.yml does not work

### ISSUE THREAD

**Issue by SpacePjoes** [GC-spigot/AdvancedEnchantments#3445]
### Describe the bug

The combo will have no limit no matter the number provided in this setting.

### How to reproduce

Use an enchantment with a combo. This combo will go up indefinitely.

### "/ae plinfo" link

https://paste.md-5.net/wazanatimu

**Comment by GC-spigot** [comment]
This is being removed completely by a new combo system, will be out soon
