### ISSUE TITLE
%player name% returns an uncapitalized version of the player name, instead of a capitalized one

### ISSUE THREAD

**Issue by SpacePjoes** [GC-spigot/AdvancedEnchantments#3446]
### Describe the bug

Same goes for %victim name% and %attacker name%. This is often not an issue, however in 1.19.4+ (I think) using for example: @p[name=!%player name%] no longer works for a player with capital letters in their name.

Example:
If your name in Minecraft is "Notch", and you execute an enchantment that will apply wither to anything, except yourself in 10 blocks, you will get this effect:

effects:
   - CONSOLE_COMMAND:minecraft:effect give @e[distance=..10,name=!%attacker name%] minecraft:wither 40 0
   
This will execute the command:
/minecraft:effect give @e[distance=..10,name=!notch] minecraft:wither 40 0

This command WILL damage the caster, since the casters name is "Notch" and not "notch". This is a very frustrating problem for complex enchantments and gives unintentional advantages/disadvantages to some players.

### How to reproduce

Use an enchantment with a %player name% variable in the effect. It's easily visible with for example "ACTION_BAR:%player name%". It will return the player name without capital letters.

### "/ae plinfo" link

https://paste.md-5.net/otigicavit

**Comment by GC-spigot** [comment]
You can do all of this with effects, without the need of minecraft commands.
Unfortunately we can't change this now, it's actually an important part of conditions, and those must be in lowercase, so this happens to be one of the side effects.

**Comment by SpacePjoes** [comment]
I can do this yes, but I have a special warden sonic boom enchantment that uses a couple commands like this:
execute at %player name% positioned ^ ^1.8 ^10 run effect give @e[distance=..2,name=!%player name%] minecraft:instant_damage 1 2 true
This does not work on any player with a capitalized name, as they will instantly die and be locked out of the world, every time they join they will instantly die again.

**Comment by SpacePjoes** [comment]
I think I can make a fix for it though, I'll also use /damage now
