### ISSUE TITLE
Enchantment table not working with books

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#3447]
### Describe the bug

All items under this list work, however books just won't get enchanted no matter how many times etc. All items armors etc work, just not books so you are unable to get books to add onto the items.

### How to reproduce

Enchant book in enchanting table.

### Screenshots / Videos

https://prnt.sc/RwbSJwAZqe8G

### "/ae plinfo" link

https://paste.md-5.net/miyuxoyopo

**Comment by GC-spigot** [comment]
This is by design, it doesn't work with books just yet! :) Will be added very soon.
