### ISSUE TITLE
Cant add more enchant via anvil (too expensive)

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#3448]
### Describe the bug

Can't add more custom enchants via anvil when having a lot of enchants already but didn't reach the limit.

In anvil.yml  settings are:
enabled: true

use-repair-cost: false

### How to reproduce

Have sword with a lot enchants (example in the  photo) and try add one more enchant.

### Screenshots / Videos

https://prnt.sc/Dd7eczaFAci3
https://prnt.sc/m302WyzHAePX

### "/ae plinfo" link

https://paste.md-5.net/onomineyir

**Comment by GC-spigot** [comment]
Seems like that is a lot of enchants already, it hit minecraft's anvil limit.

**Comment by SirvydasS** [comment]
Can you expand that limit when enchanting custom enchatments? Because now anvil feauture is not fully functional.
