### ISSUE TITLE
%block x% Placeholder not Functioning

### ISSUE THREAD

**Issue by RAYCAL2000** [GC-spigot/AdvancedEnchantments#3452]
### Describe the bug

When using the MINING enchantment type I'm unable to use the %block x%, %block y% or %block z% placeholder inside of the effects. Things such as %block location% work fine, but I need the individual coordinates for what I'm trying to get working. Below are a screenshot of both the enchantment I have and the in game chat message it sends.

### How to reproduce

- Create any enchantment that uses the MINING effect.
- Send a message trying to use the %block x%, %block y% or %block z% placeholders.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/64821088/b16493d7-9963-42c3-ad9f-3e4c04363e24)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/64821088/dc1a2288-e456-40b5-a659-f6305d02c4ce)

### "/ae plinfo" link

https://paste.md-5.net/karederobe

**Comment by GC-spigot** [comment]
Fixed!
