### ISSUE TITLE
Souls on player heads

### ISSUE THREAD

**Issue by Texbio** [GC-spigot/AdvancedEnchantments#3453]
### Describe the bug

I was mining some blocks using a some player heads and noticed they did not stack with the same variants; I realized it was because I enabled souls on mining.

This is not really ideal and I think this should not apply to random items like player heads that do not belong here. Also there might be an issue with being able to unstack these and withdraw souls?

-------------------------------------------------------
AdvancedEnchantments/config.yml
  # Collecting souls from mining
  # This can be used as a "tokens" currency for prison servers
  miningSouls:
    enabled: false
    # Chance to gain a soul from mining
    chance: 20
-------------------------------------------------------
 ^ Enabling this lets player heads somehow accumulate souls?

### How to reproduce

mine something using player heads and accumulate souls.

### Screenshots / Videos

n/a

### "/ae plinfo" link

https://paste.md-5.net/acakuzareg

### Server Log

n/a

**Comment by GC-spigot** [comment]
Fixed next update
