### ISSUE TITLE
Issues with 'force-glow' and shown attributes/effects

### ISSUE THREAD

**Issue by BirminghamBoy** [GC-spigot/AdvancedEnchantments#3454]
### Describe the bug

1. Setting `force-glow` to `true` for the following items does not give the item glint. 
- stattrak
- black-scroll
- randomization-scroll

2. When setting item type to banner pattern will cause banner pattern type to show in the lore for some items.
- slot-increaser
- white-scroll 

### How to reproduce

Set `force-glow` to `true` for the items listed above (stattrak, black-scroll, randomization-scroll).

Set item type to `minecraft:mojang_banner_pattern` for the items listed above (slot-increaser, white-scroll).

### Screenshots / Videos

https://prnt.sc/Yd-tYpDsIBrs

### "/ae plinfo" link

https://paste.md-5.net/nekatuguju

### Server Log

https://mcpaste.io/c527724bff42b370

**Comment by GC-spigot** [comment]
Glowing works, unfortunately you will need to reload the server for now for it to activate. Fixed everything else.
