### ISSUE TITLE
obtain obsidian block using trench&lava walker

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3458]
### Describe the bug

player can obtain obsidian block by trench&lava walker

### How to reproduce

1.make obsidian by lava walker
2.break blocks with trench.

### Screenshots / Videos

https://youtu.be/EpD7SyYQ87A

### "/ae plinfo" link

https://paste.md-5.net/zokohinexi

**Comment by GC-spigot** [comment]
Fixed
