### ISSUE TITLE
Dupe Bug of Trident Throw

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3459]
### Describe the bug

Whenever you try to throw a trident with a CE on it. and you throw it at your enemy. It dupes suddenly. 

### How to reproduce

virus:
  display: '%group-color%Virus'
  description: 'A chance of giving poison effect.'
  applies-to: 'Bow, Crossbow, TRIDENT'
  type: 'SHOOT_MOB;SHOOT'
  group: 'UNIQUE'
  applies:
    - TRIDENT
    - BOW
    - CROSSBOW
  levels:
    1:
      souls: 5
      chance: 6
      cooldown: 2
      effects:
        - 'POTION:POISON:0:80 @Victim'
    2:
      souls: 10
      chance: 22
      cooldown: 2
      effects:
        - 'POTION:POISON:0:120 @Victim'
    3:
      souls: 15
      chance: 35
      cooldown: 2
      effects:
        - 'POTION:POISON:1:80 @Victim'

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/87959487/de5a561b-3881-4dd9-95c3-7e4c061a92a5

### "/ae plinfo" link

https://paste.md-5.net/zetohihipu

**Comment by SirJben** [comment]
Any CE or just this one? @KingCueio

**Comment by KingCueio** [comment]
I do think it's any CE to be put in Trident. @SirJben

**Comment by ThomasWega** [comment]
We were not able to reproduce this issue. Does it still happen in the latest version? @KingCueio
