### ISSUE TITLE
Bug on sacred white parchment

### ISSUE THREAD

**Issue by Rcorcho6** [GC-spigot/AdvancedEnchantments#3460]
### Describe the bug

The keep after death is in  'true', the scroll is removed and the item remains. The test I did resulted in the scroll still remaining on the item even after death.

### How to reproduce

Tests were carried out through death by drowning, still the item was not dropped but the holy white scroll was not removed from the item 

### Screenshots / Videos

Test keep after death: false

https://drive.google.com/file/d/1-BOYeVFQepheGxEKvt7lakjlR-LsWG7G/view?usp=drivesdk

Test keep after death: true

https://drive.google.com/file/d/1-YYD5GXm23wlTf24NI-yqid_tKE_-On7/view?usp=drivesdk

### "/ae plinfo" link

https://paste.md-5.net/joharazodo

### Server Log

https://mcpaste.io/2015c6aaba30d058

**Comment by SirJben** [comment]
+1 also happens on my end.

**Comment by Rcorcho6** [comment]
hello, good morning, what I told you via tickets only happens in the world, something accidentally happened yesterday in the end and it was deleted
