### ISSUE TITLE
Broken Fortune enchant

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3461]
### Describe the bug

When mining Nether Gold Ore, the player doesn't get the correct number of Gold Nuggers (Fortune doesn't work).

Enchants on the pickaxe are in the screenshot.

### How to reproduce

Mine Nether Gold Ore

### Screenshots / Videos

https://i.imgur.com/Y9R3znP.png

### "/ae plinfo" link

https://paste.md-5.net/qokirunigo

**Comment by GC-spigot** [comment]
Fixed
