### ISSUE TITLE
Holy White Scroll - Doesn't Work

### ISSUE THREAD

**Issue by srrawr11** [GC-spigot/AdvancedEnchantments#3464]
### Describe the bug

Hi, as I talked in the ticket..
Minecraft: Paper 1.19.4
Versions: Java edition
Plugin version: 9.2.10

As you see in the GIF, that the HOLY PROTECTED still remains in the item after death.
https://i.imgur.com/6R6KoDp.mp4

### How to reproduce

https://i.imgur.com/6R6KoDp.mp4

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/73607495/88013c51-7859-4512-80c8-c4036d43f76e)

### "/ae plinfo" link

https://i.imgur.com/6R6KoDp.mp4

**Comment by reussy** [comment]
Please attach the link that shows you the command /ae plinfo @srrawr11

**Comment by srrawr11** [comment]
> Please attach the link that shows you the command /ae plinfo @srrawr11

https://paste.md-5.net/rayoboxoco

**Comment by srrawr11** [comment]
Hello?

**Comment by reussy** [comment]
> Hello?

Hey,

I'll work on a fix these days, sorry for the delay.

**Comment by srrawr11** [comment]
Thanks, I appreciate it!

**Comment by srrawr11** [comment]
When do you think is gonna be fixed this issue?

**Comment by srrawr11** [comment]
> > Hello?
> 
> Hey,
> 
> I'll work on a fix these days, sorry for the delay.

Hello?

**Comment by reussy** [comment]
> > > Hello?
> > 
> > 
> > Hey,
> > I'll work on a fix these days, sorry for the delay.
> 
> Hello?

Sorry, I've been busy... I'll make time for this on Friday.

**Comment by srrawr11** [comment]
> > > > Hello?
> > > 
> > > 
> > > Hey,
> > > I'll work on a fix these days, sorry for the delay.
> > 
> > 
> > Hello?
> 
> Sorry, I've been busy... I'll make time for this on Friday.

Okey, please!

**Comment by srrawr11** [comment]
> > > > Hello?
> > > 
> > > 
> > > Hey,
> > > I'll work on a fix these days, sorry for the delay.
> > 
> > 
> > Hello?
> 
> Sorry, I've been busy... I'll make time for this on Friday.

Hi, when will you able to fix this?..
You fixing other stuffs.. but this still remains.. It's been 3 weeks.. but nothing..
Am pretty sure is not that difficult to have a look and fix it in one go..

**Comment by GC-spigot** [comment]
Sorry about delays, we've switched to a whole new system for effects, and fixing holy whitescrolls will require a bit of a rework, This will be fixed asap - priority # 1 now.
