### ISSUE TITLE
Placeholder api support

### ISSUE THREAD

**Issue by mattuz00** [GC-spigot/AdvancedEnchantments#3465]
### Describe the bug

After the ability update I had a problem with the external placeholders used as conditions for my custom enchant, the problem had been solved, but now we are in the same situation as a few months ago, most of my custom enchants do not work because they use PAPI placeholders and I have to put the server in maintenance for this problem,  How we can solve definitively? I have the latest version of AE and the latest version of PAPI. 

### How to reproduce

When I use any external placeholder as a condition following this format"%player " <placeholder>=(or<>) : %allow%" the enchant doesn't work 

### "/ae plinfo" link

https://paste.md-5.net/dasopudori

**Comment by GC-spigot** [comment]
Can you give an example condition which we could test?

**Comment by mattuz00** [comment]
You can test with every papi placeholders

**Comment by ThomasWega** [comment]
We use PAPI placeholders ourself and they work absolutely fine. If you have issues, please provide a specific examples...

**Comment by mattuz00** [comment]
Probably it is a problem that gives with some incompatible plugin
