### ISSUE TITLE
RGB colors support

### ISSUE THREAD

**Issue by VISION6969** [GC-spigot/AdvancedEnchantments#3467]
### Describe the bug

Add RGB Support in Item Rename Tags

### How to reproduce

/ae giveitem ___VISION renametag 1

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/99619455/2617a9f1-d0d3-47ef-8204-6420aba67e92)

### "/ae plinfo" link

https://paste.md-5.net/yucuceyepa

**Comment by ThomasWega** [comment]
We already do support this. Just put the HEX color in brackets like so

{#a18c3a}Test

There are few places where this is not supported yet, but I issued a fix for it just now, so it will be available in the upcoming versions.
