### ISSUE TITLE
INVINCIBLE EFFECT_STATIC BUG

### ISSUE THREAD

**Issue by Zelenik** [GC-spigot/AdvancedEnchantments#3468]
### Describe the bug

Hello. I wanted to make a god enchantment. It would make you invincible.
I used EFFECT_STATIC, which would mean the INVINCIBLE effect would have to toggle when I'm equipping and unequipping the item. It doesn't seem to work, as it makes you invincible when equipping, and it doesn't toggle it off after unequipping.

Please fix this in the next update.
This was discussed in a Discord ticket #aenchantments-4236

Thank you

### How to reproduce

god:
  display: '%group-color%God'
  description: 'This makes you invincible.'
  applies-to: 'Armor'
  group: 'LEGENDARY'
  type: 'EFFECT_STATIC'
  applies:
    - 'ALL_ARMOR'
  levels:
    '1':
      chance: 100
      effects:
        - 'INVINCIBLE @Self'
        
        
Equip this enchant and put on the armor. You are now immortal.
Unequip it, but you will stay immortal.

This should probably work like a POTION effect.

### Screenshots / Videos

/

### "/ae plinfo" link

https://paste.md-5.net/utogadahaw

### Server Log

/

**Comment by GC-spigot** [comment]
Seems to be working for me, can you do `/ae debug enable`, try applying then unapplying armor and send server latest.log file here?

**Comment by ThomasWega** [comment]
Try the latest version. Works fine for multiple other people. In case of need, feel free to create a new github issue :)
