### ISSUE TITLE
player can break block in claimed region (lands)

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3470]
### Describe the bug

player can break block other region (protected by lands) after update lastest version of AE.

### How to reproduce

same as #3371. can you support lands plugins?

### "/ae plinfo" link

https://paste.md-5.net/cufuwogulu

**Comment by reussy** [comment]
Added [Lands](https://www.spigotmc.org/resources/lands-⭕-land-claim-plugin-✅-grief-prevention-protection-gui-management-nations-wars-1-20-support.53313/) support for break checks.
