### ISSUE TITLE
VEIN_MINE was not worked sometimes. (2)

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3474]
### Describe the bug

i reported this issue at #3376 , i replied it fixed, There are some improvements,
but there are still times when the entire mineral is not dug up.

And i reported issue about aurelium skills at #3339 , Can I know when the bug can be fixed?

### How to reproduce

1. make VEIN_MINE pickaxe.
2.
break ore
'4':
settings:
whitelist:
- "COAL_ORE"
- "COPPER_ORE"
- "IRON_ORE"
- "GOLD_ORE"
- "LAPIS_ORE"
- "REDSTONE_ORE"
- "DIAMOND_ORE"
- "EMERALD_ORE"
- "NETHER_QUARTZ_ORE"
- "NETHER_GOLD_ORE"
- "ANCIENT_DEBRIS"
- "DEEPSLATE_COAL_ORE"
- "DEEPSLATE_COPPER_ORE"
- "DEEPSLATE_IRON_ORE"
- "DEEPSLATE_GOLD_ORE"
- "DEEPSLATE_LAPIS_ORE"
- "DEEPSLATE_REDSTONE_ORE"
- "DEEPSLATE_DIAMOND_ORE"
- "DEEPSLATE_EMERALD_ORE"
effects:
BREAK_BLOCK @Veinmine

### Screenshots / Videos

https://youtu.be/3CXPefUAwrE

### "/ae plinfo" link

https://paste.md-5.net/seluzefera

**Comment by GC-spigot** [comment]
Fixed, this is probably related to aureliumskills
