### ISSUE TITLE
trench-blacklist not working as intended

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3475]
### Describe the bug

Adding a block such as budding_amethyst to the trench-blacklist in the config.yml has no effect.

### How to reproduce

- Add BUDDING_AMETHYST to trench-blacklist in config.yml
- Get a pickaxe
- '/ae enchant trench 9'
- Place stone next to budding amethyst
- Break stone
- Notice the budding amethyst breaks as well even though it shouldn't

### Screenshots / Videos

Hopefully not required, this is really easy to reproduce

### "/ae plinfo" link

https://paste.md-5.net/omebuserur

### Server Log

https://mcpaste.io/cb4f7f534b40d84f

**Comment by GC-spigot** [comment]
Fixed
