### ISSUE TITLE
Spamming error in the console

### ISSUE THREAD

**Issue by carechoripan** [GC-spigot/AdvancedEnchantments#3476]
### Describe the bug

Hi, recently I've been configuring this plugin and I noticed something, apparently everything works correctly inside the game, but every time I do something related to the plugin, I get this error, what can I do? Could it be a plugin bug?

### How to reproduce

I was just configuring and this error started

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138632168/631fb760-3f7e-42c4-8239-8c3dd32b7bd4)

### "/ae plinfo" link

/ae plinfo skipPlugins

### Server Log

https://mcpaste.io/96f95deded8ecbb1

**Comment by GC-spigot** [comment]
Seems like this is an error with your config.yml , stattrack configuration is missing. Make sure nothing is deleted there.
