### ISSUE TITLE
Effect "ACTION_BAR" Broken after upgrade to 9.2.9 on MC 1.20.1

### ISSUE THREAD

**Issue by sudokou** [GC-spigot/AdvancedEnchantments#3478]
### Describe the bug

Started getting an error in console when any "ACTION_BAR" effect would attempt to trigger after upgrading to version 9.2.9 on Paper 1.20.1.

Effect worked with no errors on previous version: 9.0.0b81 on Paper 1.19.3

Error from console included below as server log.

enchantments.yml: https://mcpaste.io/da8121b167e210dd

### How to reproduce

Copy enchantments.yml and install on 9.2.9 w/ Paper 1.20.1. Other versions untested.

### "/ae plinfo" link

https://paste.md-5.net/lajusadumo

### Server Log

https://mcpaste.io/dde93b4cf4973c6c

**Comment by GC-spigot** [comment]
Effect was trying to activate on non player entities (in this case Zombie), fixed for next version.
