### ISSUE TITLE
GKits compatibility with Armor Trims

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#3481]
### Describe the bug

I have set up a gkit where my armor has an armor trim and it does not apply when giving the kit

### How to reproduce

Set up an armor trim kit:

  spacesuit:
    hide: TRUE
    slot: 2
    delay: 0
    content:
      '1':
        material: NETHERITE_HELMET
        armor-trim: 'IRON;SILENCE'
        data: 0
        amount: 1
        name: '{#dfdfea}&lS{#e5e5ee}&lp{#ececf2}&la{#f2f2f7}&lc{#f9f9fb}&le {#ffffff}&lH{#f9f9fb}&le{#f2f2f7}&ll{#ececf2}&lm{#e5e5ee}&le{#dfdfea}&lt'
        lore:
        - '&eUnbreakable'
        - ''
        - '&3Official Space Suit'
        - '&3Galactic Crate 2023'
        advanced-enchantments:
        - "subzero:1"
        enchants:
        - protection_explosions:50
        - protection_fire:50
        - protection_projectile:50
        - protection_environmental:50
        - water_worker:1 # Aqua affinity - helmet
        - respiration:30 # helmet

### "/ae plinfo" link

https://paste.md-5.net/unasunalaz

**Comment by GC-spigot** [comment]
GKits aren't yet compatible with them, will be added shortly

**Comment by GC-spigot** [comment]
Ready for next update
