### ISSUE TITLE
other plugins can't recognize break-event by TP_DROPS, SMELT.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3484]
### Describe the bug

1. Jobs plugin (it give money when player break block)
 when player break block by TP_DROPS, SMELT enchanted tool, jobs plugin doesen't give money to player.

2.  Also i have skyblock plugin. it has hopper limit features. (superiorskyblock)
when player break hopper with TP_DROPS or SMELT enchanted tools, plugin can't recognize break-event.
so after break hopper, player can't replace hopper. 
-> https://youtu.be/vq5pMkl9Mqc

This problem occurs in all third-party plugs that recognize break-event, not just in the above two plugins.

### How to reproduce

화로2:
  display: '%group-color%화로'
  description: |-
    광물, 모래 파괴시 일정확률로
    해당 아이템을 즉시 가공합니다.
    &8스탯 시스템 스킬과
    &8별개로 발동됩니다.
  applies-to: 
  type: MINING
  group: 레어
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  levels:
    '1':
      chance: 25
      effects:
      - SMELT
    '2':
      chance: 50
      effects:
      - SMELT
    '3':
      chance: 75
      effects:
      - SMELT
    '4':
      chance: 100
      effects:
      - SMELT

수확:
  display: '%group-color%수확'
  description: |-
    확률적으로 도구로 파괴한
    블록이 인벤토리에
    자동으로 들어갑니다.
    &8스탯 시스템 스킬과
    &8별개로 발동됩니다.
  applies-to: 
  type: MINING
  group: 레전더리
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  - ALL_AXE
  - ALL_HOE
  levels:
    '1':
      chance: 25
      effects:
      - TP_DROPS
    '2':
      chance: 50
      effects:
      - TP_DROPS
    '3':
      chance: 75
      effects:
      - TP_DROPS
    '4':
      effects:
      - TP_DROPS

### "/ae plinfo" link

https://paste.md-5.net/ihixavujav

**Comment by ThomasWega** [comment]
Hello. We made some event handling changes in code some time ago, and this shouldn't happen anymore. Please create a new github issue if this happens in the latest version as well.
