### ISSUE TITLE
Bug on  9.2.13 of advanced enchantment

### ISSUE THREAD

**Issue by ColdDragons81** [GC-spigot/AdvancedEnchantments#3485]
### Describe the bug

when i use trench, replanter, potato or replant carrot the enchant don't work

### How to reproduce

i just use the tool and an error is produce and the enchant don't work

### Screenshots / Videos

https://mcpaste.com/8f8a5c527840cdd2f67daa22c9c71d51
https://mcpaste.com/29a39ea33950bbff643c00a267a3fb9b

### "/ae plinfo" link

https://paste.md-5.net/lurefogobu

**Comment by reussy** [comment]
Hello,

I fail to replicate the same error, could you show the configuration of the enchantments?

**Comment by ColdDragons81** [comment]
For the use of the enchant I use mmo items with enchant trench or
replanter, I send you my config this day

**Comment by ColdDragons81** [comment]
The bug is with lands
lands and advanced enchantment bug when i use item

**Comment by GC-spigot** [comment]
Could you post these errors with pastebin? mcpaste.com doesn't work

**Comment by ColdDragons81** [comment]
https://pastebin.com/56ehr5hC
https://pastebin.com/6H5Y7t8Y

**Comment by GC-spigot** [comment]
Fixed! This was an issue with Lands
