### ISSUE TITLE
Many triggers do not work with the particle effect.

### ISSUE THREAD

**Issue by ChineseLegolas** [GC-spigot/AdvancedEnchantments#3488]
### Describe the bug

Only a few triggers (attack/attack_mob, jump, kill/kill_mob) work with creating particles. Some, such as  effect_static, will give a large console error, other, such as repeating, have no error. The error code for effect_static is below.

`09.07 17:05:23 [Server] [WARN] java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getLocation()" because "<parameter2>" is null
09.07 17:05:23 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.ParticleEffect.executeEffect(ParticleEffect.java:22)
09.07 17:05:23 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:176)
09.07 17:05:23 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:111)
09.07 17:05:23 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54)
09.07 17:05:23 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68)
09.07 17:05:23 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ArmorWearTrigger.runCheck(ArmorWearTrigger.java:204)
09.07 17:05:23 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ArmorWearTrigger.updateWornArmor(ArmorWearTrigger.java:171)
09.07 17:05:23 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ArmorWearTrigger.updateWornArmor(ArmorWearTrigger.java:132)
09.07 17:05:23 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ArmorWearTrigger.onArmor(ArmorWearTrigger.java:70)
09.07 17:05:23 [Server] [WARN] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor389.execute(Unknown Source)
09.07 17:05:23 [Server] [WARN] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
09.07 17:05:23 [Server] [WARN] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
09.07 17:05:23 [Server] [WARN] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
09.07 17:05:23 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
09.07 17:05:23 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
09.07 17:05:23 [Server] [WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
09.07 17:05:23 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.armorutils.ArmorListener.onInventoryClick(ArmorListener.java:182)
09.07 17:05:23 [Server] [WARN] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor420.execute(Unknown Source)
09.07 17:05:23 [Server] [WARN] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
09.07 17:05:23 [Server] [WARN] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
09.07 17:05:23 [Server] [WARN] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
09.07 17:05:23 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
09.07 17:05:23 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
09.07 17:05:23 [Server] [WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
09.07 17:05:23 [Server] [WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3383)
09.07 17:05:23 [Server] [WARN] at net.minecraft.network.protocol.game.PacketPlayInSetCreativeSlot.a(PacketPlayInSetCreativeSlot.java:18)
09.07 17:05:23 [Server] [WARN] at net.minecraft.network.protocol.game.PacketPlayInSetCreativeSlot.a(PacketPlayInSetCreativeSlot.java:12)
09.07 17:05:23 [Server] [WARN] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
09.07 17:05:23 [Server] [WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
09.07 17:05:23 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
09.07 17:05:23 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
09.07 17:05:23 [Server] [WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
09.07 17:05:23 [Server] [WARN] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
09.07 17:05:23 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
09.07 17:05:23 [Server] [WARN] at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
09.07 17:05:23 [Server] [WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
09.07 17:05:23 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
09.07 17:05:23 [Server] [WARN] at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
09.07 17:05:23 [Server] [WARN] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
09.07 17:05:23 [Server] [WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
09.07 17:05:23 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
09.07 17:05:23 [Server] [WARN] [AdvancedEnchantments] §4Failed to activate effect '§fPARTICLE:SMOKE_LARGE:15:1 '
09.07 17:05:23 [Server] [WARN] [AdvancedEnchantments] §cAdditional information: §7Error while activating effect
09.07 17:05:25 [Server] [WARN] java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getLocation()" because "<parameter2>" is null
09.07 17:05:25 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.ParticleEffect.executeEffect(ParticleEffect.java:22)
09.07 17:05:25 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:176)
09.07 17:05:25 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:111)
09.07 17:05:25 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54)
09.07 17:05:25 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68)
09.07 17:05:25 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ArmorWearTrigger.runCheck(ArmorWearTrigger.java:204)
09.07 17:05:25 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ArmorWearTrigger.updateWornArmor(ArmorWearTrigger.java:172)
09.07 17:05:25 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ArmorWearTrigger.updateWornArmor(ArmorWearTrigger.java:132)
09.07 17:05:25 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ArmorWearTrigger.onArmor(ArmorWearTrigger.java:70)
09.07 17:05:25 [Server] [WARN] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor389.execute(Unknown Source)
09.07 17:05:25 [Server] [WARN] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
09.07 17:05:25 [Server] [WARN] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
09.07 17:05:25 [Server] [WARN] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
09.07 17:05:25 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
09.07 17:05:25 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
09.07 17:05:25 [Server] [WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
09.07 17:05:25 [Server] [WARN] at AdvancedEnchantments-9.2.11.jar//net.advancedplugins.ae.impl.effects.armorutils.ArmorListener.onInventoryClick(ArmorListener.java:182)
09.07 17:05:25 [Server] [WARN] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor420.execute(Unknown Source)
09.07 17:05:25 [Server] [WARN] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
09.07 17:05:25 [Server] [WARN] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
09.07 17:05:25 [Server] [WARN] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
09.07 17:05:25 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
09.07 17:05:25 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
09.07 17:05:25 [Server] [WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
09.07 17:05:25 [Server] [WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3383)
09.07 17:05:25 [Server] [WARN] at net.minecraft.network.protocol.game.PacketPlayInSetCreativeSlot.a(PacketPlayInSetCreativeSlot.java:18)
09.07 17:05:25 [Server] [WARN] at net.minecraft.network.protocol.game.PacketPlayInSetCreativeSlot.a(PacketPlayInSetCreativeSlot.java:12)
09.07 17:05:25 [Server] [WARN] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
09.07 17:05:25 [Server] [WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
09.07 17:05:25 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
09.07 17:05:25 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
09.07 17:05:25 [Server] [WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
09.07 17:05:25 [Server] [WARN] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
09.07 17:05:25 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
09.07 17:05:25 [Server] [WARN] at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
09.07 17:05:25 [Server] [WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
09.07 17:05:25 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
09.07 17:05:25 [Server] [WARN] at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
09.07 17:05:25 [Server] [WARN] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
09.07 17:05:25 [Server] [WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
09.07 17:05:25 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
09.07 17:05:25 [Server] [WARN] [AdvancedEnchantments] §4Failed to activate effect '§fPARTICLE:SMOKE_LARGE:15:1 '
09.07 17:05:25 [Server] [WARN] [AdvancedEnchantments] §cAdditional information: §7Error while activating effect`

### How to reproduce

`cosmetic_blossoms:

  display: '§aCosmetic Blossoms'

  description: Attacking with this item emits sakura leaves.

  applies-to: Swords, Axes

  type: REPEATING

  group: Cosmetic

  applies:

    - ALL_SWORD

    - ALL_AXE

  levels:

    '1':

      time: 5

      effects:

      - PARTICLE:CHERRY_LEAVES:15:1 @Victim
`

### "/ae plinfo" link

https://paste.md-5.net/nujuculudi

**Comment by GC-spigot** [comment]
With REPEATING it would not work like that, REPEATING has no victim it only has the main Player which is usually @Attacker unless there's 2 players in the trigger. Use @Attacker
