### ISSUE TITLE
Latest update not working with Lands

### ISSUE THREAD

**Issue by FourNineRugz** [GC-spigot/AdvancedEnchantments#3489]
### Describe the bug

https://mcpaste.io/75d6fda55cffe7b1

Looks like it only has issues with enchants like Trench and Multiplication that have block breaking events

### How to reproduce

https://mcpaste.io/75d6fda55cffe7b1

Looks like it only has issues with enchants like Trench and Multiplication that have block breaking events

### "/ae plinfo" link

https://paste.md-5.net/mukizozaye

### Server Log

https://mcpaste.io/75d6fda55cffe7b1

**Comment by ColdDragons81** [comment]
I have the same problem and i have lands

**Comment by GC-spigot** [comment]
Fixed next update!
