### ISSUE TITLE
Issue with TRENCH + Fortune

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#349]
Hey,

upon closer inspection it seems that the bug where TRENCH doesn't drop any iron/gold ore only occurs when the pickaxe has Fortune of any level on it. It doesn't affect the initially broken block (in the middle of the 3x3x3 cube.
Here is a short video of the bug (Detonate III on our server is the same as Detonate IX of the default config):
https://youtu.be/MEPXrZi45_c

AdvancedEnchantments version: v5.2.8
PaperSpigot: 1.13.2

Thank you!

**Comment by newbie029** [comment]
https://streamable.com/e0ltz
Trench + Fortune is still duping
Place 27 diamond block then mine that with trench + fortune 
to get extra blocks

Tested with AdvancedEnchantments version: v5.2.8 & v5.2.5

**Comment by GC-spigot** [comment]
Fixed.
