### ISSUE TITLE
Candle_cake

### ISSUE THREAD

**Issue by RWslayer** [GC-spigot/AdvancedEnchantments#3490]
### Describe the bug

I've found another potentional bug. when using block-break as the type and candle_cake:0 as the variable The quests seems to not be working for somereason. I've been testing out and came to some conclusions:
When in CREATIVE abd you destroy the candled cake. It destroys the cake aswel as the candle in 1 click no itemdroppings. -> sometimes counts.
When in SURVIVAL it seems not to be working bcs of the nbt metatags change when destroying the object. You get the candle in return, therefore possibly not cound ascandled_cake
When WE is used (World Edit) the quests seems to be working consistently. (Maybe has something to do with the metatags, idk). (Ofcourse we don't prefere this method cuz players need to grind for the progress, instead of giving them free points.

### How to reproduce

.

### Screenshots / Videos

.

### "/ae plinfo" link

https://paste.md-5.net/ejaraxodan

**Comment by GC-spigot** [comment]
Is this battlepass report? Please post it there
