### ISSUE TITLE
Telepathy don't work with Fortune (Vanilla) enchantment.

### ISSUE THREAD

**Issue by SaltyPotata** [GC-spigot/AdvancedEnchantments#3491]
### Describe the bug

You can see everything in the video. The title basically says it all.

### How to reproduce

Put Fortune and Telepathy enchantment together.

### Screenshots / Videos

https://www.mediafire.com/file/ih27oqfe8kz3jnd/test.mp4/file

### "/ae plinfo" link

https://paste.md-5.net/dumaqisixe

**Comment by SirvydasS** [comment]
Having same problem.
1.20.1

**Comment by SaltyPotata** [comment]
Bump

**Comment by GC-spigot** [comment]
Seems to be working just fine now

**Comment by SirvydasS** [comment]
Having agian same problem. Version: 9.3.17
