### ISSUE TITLE
Wardens cannot be used as a GUARD

### ISSUE THREAD

**Issue by SpacePjoes** [GC-spigot/AdvancedEnchantments#3493]
### Describe the bug

A Warden that is a GUARD will still attack the player.

### How to reproduce

Summon a Warden as a GUARD as an enchantment effect.

### "/ae plinfo" link

https://paste.md-5.net/heveroxifo

**Comment by austv** [comment]
Same here, warden is attacking the owner.
I tested in a old version, the 9.0.0b81 and this wasn't a problem.

Another problem is that the owner gets darkness.

**Comment by GC-spigot** [comment]
> Same here, warden is attacking the owner. I tested in a old version, the 9.0.0b81 and this wasn't a problem.
> 
> Another problem is that the owner gets darkness.

It's using the same exact code, I'm not sure why it would be different. Warden casts darkness to everyone around, including owner. That's a vanilla mechanic.

**Comment by austv** [comment]
> > Same here, warden is attacking the owner. I tested in a old version, the 9.0.0b81 and this wasn't a problem.
> > Another problem is that the owner gets darkness.
> 
> It's using the same exact code, I'm not sure why it would be different. Warden casts darkness to everyone around, including owner. That's a vanilla mechanic.

This is issue is marked as closed but was fixed? Not the darkness but the fact the guardians are attacking the owner
