### ISSUE TITLE
DECREASE_DAMAGE does not work on Wardens melee attacks

### ISSUE THREAD

**Issue by SpacePjoes** [GC-spigot/AdvancedEnchantments#3494]
### Describe the bug

A player will still take full damage from a Warden MELEE attack. Sonic Booms DO get negated by DECREASE_DAMAGE.

### How to reproduce

Have an enchantment that decreases damage by 100%, using DECREASE_DAMAGE:100. Any mob attack will not deal any damage to the player, but a Wardens melee attack will still deal damage.

### "/ae plinfo" link

https://paste.md-5.net/heveroxifo

**Comment by ThomasWega** [comment]
Hello. I was not able to replicate this issue. Make sure this wasn't causes by cooldown on the enchantment, as well make sure to update your server jar and the plugin jar.

https://i.imgur.com/ZCRWKsc.mp4

If this issue still persists for you, feel free to open new issue.
