### ISSUE TITLE
CATCH_FISH Still triggering on entities and players

### ISSUE THREAD

**Issue by SawJin22** [GC-spigot/AdvancedEnchantments#3495]
### Describe the bug

CATCH_FISH Trigger that was fixed in one of the recent updates is still triggering on entities and players

currently running version 9.2.16 on minecraft 1.19.4

### How to reproduce

snag-hook-test:
  display: "%group-color%Snag Hook Test"
  description: "Has an increased chance to receive uncommon items from fishing."
  applies-to: "Fishing Rod"
  type: "CATCH_FISH"
  group: "SIMPLISTIC"
  applies:
    - FISHING_ROD
  levels:
    1:
      chance: 100
      effects:
        - "MESSAGE:&e**Your snag hook caught you something!**"

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/25687937/07d27a79-8d4f-406d-9783-62a36b5b0f58

### "/ae plinfo" link

https://paste.md-5.net/nonatabupe

**Comment by Nashlord** [comment]
Same problem here with itemadder's invisible armorstand. I'm using version 9.2.18.
Video : [https://gyazo.com/97b83fabe8b5e5e96ac93a963d880e49](https://gyazo.com/97b83fabe8b5e5e96ac93a963d880e49)

**Comment by GC-spigot** [comment]
Fixed!
