### ISSUE TITLE
Custom Enchant Conflict 

### ISSUE THREAD

**Issue by Nathan1463** [GC-spigot/AdvancedEnchantments#3496]
### Describe the bug

https://pastebin.com/yfthM7S5 -- Console error

When I have the following enchants on a sword I get that error - when killing mobs:

Enchants are:
Slayer
Critical
Beastslayer
Double Strike
Grindstone
Inquisitive
Soulgrind

### How to reproduce

Put the same enchants on a weapon and it will do it when killing mobs

### "/ae plinfo" link

https://paste.md-5.net/anefelisos

### Server Log

https://pastebin.com/yfthM7S5

**Comment by GC-spigot** [comment]
Seems like your configuration hasn't been updated to the newest format, you still have `%victim%` your enchantments.yml, make sure that it's replaced with @Victim, also `%attacker%` with @Attacker as well.

**Comment by Nathan1463** [comment]
Hi,

I have changed everything to @victim and @attacker but I am still getting
the same error


21.07 18:52:42 [Server] [WARN] at
AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.KillMobTrigger.onMobDeath(KillMobTrigger.java:57)
21.07 18:52:42 [Server] [WARN] at
com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor519.execute(Unknown
Source)
21.07 18:52:42 [Server] [WARN] at
org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
21.07 18:52:42 [Server] [WARN] at
co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
21.07 18:52:42 [Server] [WARN] at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
21.07 18:52:42 [Server] [WARN] at
io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
21.07 18:52:42 [Server] [WARN] at
io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
21.07 18:52:42 [Server] [WARN] at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
21.07 18:52:42 [Server] [WARN] at
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
21.07 18:52:42 [Server] [WARN] at
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
21.07 18:52:42 [Server] [WARN] at
net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
21.07 18:52:42 [Server] [WARN] at
net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
21.07 18:52:42 [Server] [WARN] at
net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
21.07 18:52:42 [Server] [WARN] at
net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
21.07 18:52:42 [Server] [WARN] at
net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
21.07 18:52:42 [Server] [WARN] at
java.base/java.lang.Thread.run(Thread.java:833)
21.07 18:52:42 [Server] [WARN] [AdvancedEnchantments] Failed to parse
***@***.*** from String to Integer.
21.07 18:52:42 [Server] [WARN] java.lang.NumberFormatException: For input
string: ***@***.***"
21.07 18:52:42 [Server] [WARN] at
java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
21.07 18:52:42 [Server] [WARN] at
java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
21.07 18:52:42 [Server] [WARN] at
java.base/java.lang.Double.parseDouble(Double.java:651)
21.07 18:52:42 [Server] [WARN] at
AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.utils.ASManager.parseInt(ASManager.java:541)
21.07 18:52:42 [Server] [WARN] at
AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.utils.ASManager.parseInt(ASManager.java:531)
21.07 18:52:42 [Server] [WARN] at
AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.MoreDropsEffect.executeEffect(MoreDropsEffect.java:41)
21.07 18:52:42 [Server] [WARN] at
AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:181)
21.07 18:52:42 [Server] [WARN] at
AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:111)
21.07 18:52:42 [Server] [WARN] at
AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54)
21.07 18:52:42 [Server] [WARN] at
AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68)
21.07 18:52:42 [Server] [WARN] at
AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.KillMobTrigger.onMobDeath(KillMobTrigger.java:57)
21.07 18:52:42 [Server] [WARN] at
com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor519.execute(Unknown
Source)
21.07 18:52:42 [Server] [WARN] at
org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
21.07 18:52:42 [Server] [WARN] at
co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
21.07 18:52:42 [Server] [WARN] at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
21.07 18:52:42 [Server] [WARN] at
io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
21.07 18:52:42 [Server] [WARN] at
io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
21.07 18:52:42 [Server] [WARN] at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
21.07 18:52:42 [Server] [WARN] at
WildStacker-2023.2.jar//com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:156)
21.07 18:52:42 [Server] [WARN] at
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
21.07 18:52:43 [Server] [WARN] at
org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
21.07 18:52:43 [Server] [WARN] at
net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
21.07 18:52:43 [Server] [WARN] at
net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
21.07 18:52:43 [Server] [WARN] at
net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
21.07 18:52:43 [Server] [WARN] at
net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
21.07 18:52:43 [Server] [WARN] at
net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
21.07 18:52:43 [Server] [WARN] at
java.base/java.lang.Thread.run(Thread.java:833)
