### ISSUE TITLE
Reach Seems To Be Bugged

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#3497]
### Describe the bug

Any kind of reach doesn't seem to work, no matter what target

### How to reproduce

swing:
  display: '%group-color%Swing'
  description: 'Swing'
  applies-to: 'Shovels'
  group: 'CUSTOM'
  type: 'SWING'
  applies:
    - 'ALL_SHOVEL'
  settings:
    removeable: false
  levels:
    '1':
      chance: 100
      cooldown: 0
      effects:
        - 'REACH:5'

### "/ae plinfo" link

https://paste.md-5.net/raqocabive

**Comment by GC-spigot** [comment]
It's for attacking entities with weapons

**Comment by DuplexLake** [comment]
> It's for attacking entities with weapons
the shovel is planned to be used as a weapon, hence why it's as type: SWING

**Comment by DuplexLake** [comment]
Any update on this? has been "in testing for 2 weeks"

**Comment by GC-spigot** [comment]
Yes! It's resolved now, sorry about delays!

**Comment by DuplexLake** [comment]
Glad ya got to it, all good,  thank you
