### ISSUE TITLE
[FEATURE] - Allow inclusion/restriction of certain enchanted books/ enchantment groups from random loot

### ISSUE THREAD

**Issue by z1haze** [GC-spigot/AdvancedEnchantments#3498]
I was instructed to report the issue this way by the support team in the discord.

### Describe the bug

Hi I just encountered a crippling issue in my server using your plugin. My impression was that if enchantments are disabled in the enchanting table, making them only available via the ae give commands, that when enabled in random loot, they would not show up. However this is not the case, your plugin will put any and all enchanted books into the random loot, and completely ignore the books that were restricted in the enchanting table. Please make it an option to be able to include certain enchanted books, either by group or by the name specifically in the random loot, so not all books are included

### How to reproduce

1. disable certain enchantment groups in the enchanting table
2. enable random loot with a random enchanted book

Expect to not see the restricted books in loot

Actual: see all books in loot, including restricted ones.

### "/ae plinfo" link

https://paste.md-5.net/izuquyitil

**Comment by ThomasWega** [comment]
Should be added in the next update! :)

**Comment by z1haze** [comment]
Leave it open until you can reference a commit or release?

**Comment by aXe18** [comment]
> Leave it open until you can reference a commit or release?

There is no need to keep issues open if dev has answered for you :)
