### ISSUE TITLE
DO_HARM not working at all

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#3499]
### Describe the bug

DO_HARM not working at all

### How to reproduce

Enchant with Do_Harm:2000. Doesn't do anything to @Victim or any other target.

### "/ae plinfo" link

https://paste.md-5.net/idanewaheg

**Comment by GC-spigot** [comment]
Tested, it's definitely working. Reporting issues include examples of how you've done this. Check everything else related with enchantment, and don't do that much damage - it might be limited by minecraft itself.

**Comment by SoraShiunin** [comment]
I figured it out? Apparently it only works if theres no targets. So here is a video.
Enchant used: 
`teststick:
  display: '%group-color%Do Harm'
  description: |-
    &fDamages extra 
  applies-to: Axes
  type: ATTACK_MOB
  group: UNIQUE
  applies:
  - STICK
  - BOW
  levels:
    '1':
      effects:
      - DO_HARM:6
teststick2:
  display: '%group-color%Do Harm 2'
  description: |-
    &fDamages extra 
  applies-to: Axes
  type: ATTACK_MOB
  group: UNIQUE
  applies:
  - STICK
  - BOW
  levels:
    '1':
      effects:
      - DO_HARM:6 @VICTIM`
Video: https://youtu.be/PPuW1xqIhnk
Honestly no idea why. Am I doing something wrong? I even tried putting it between ''.

**Comment by GC-spigot** [comment]
It's case sensitive, try using `@Victim` instead

**Comment by SoraShiunin** [comment]
I figured it out. The MythicLib plugin doesn't let ANY type of damage enchant work. I have created an issue with them hoping they make a way to disable their damage calculation, but if anything can be done on your side, it'd also help alot.
