### ISSUE TITLE
Trench + VeinMiners = Duplicate items

### ISSUE THREAD

**Issue by Annnekkk** [GC-spigot/AdvancedEnchantments#3500]
### Describe the bug

My players report me trench have a bug when use trench enchanted item with veinminers will duplicate item drops 

### How to reproduce

Use an pickaxe have Trench enchanted, turn on Veinminer plugins, and hold sneak button to active Veinminer, and items dropped will be duplicated.

### Screenshots / Videos

https://drive.google.com/file/d/1TofLZ3boyc8jDBa5I7gdq4fEJCxmD9hp/view?usp=sharing, https://drive.google.com/file/d/1YREL_uOyOp8OBTJL-48AaLHNB_OXJfbS/view?usp=sharing

### "/ae plinfo" link

https://paste.md-5.net/ejekitimiq

### Server Log

https://mcpaste.io/b0eac40b56cfaee2

**Comment by GC-spigot** [comment]
Any outside veinminer plugins are not supported, use built-in veinminer for this.
