### ISSUE TITLE
AE API not working

### ISSUE THREAD

**Issue by Johanmans10** [GC-spigot/AdvancedEnchantments#3502]
### Describe the bug

When attempting to use the AE API I first noticed that the version of the plugin my client is using does not exist on the API.
I attempted using the latest version available but when the code to remove an enchantment is executed nothing happens.
By nothing I mean nothing, the enchants remain on the item and there is no mention in chat or in the logs of any warnings or errors occuring within the AE plugin or my own. Using the AE commands the enchants are still there and can be removed but through the API it's like nothing happens.

Also it might be useful to make a method to clear all AE enchantments instead of having other devs manually loop over the enchantments hashmap and removing the enchantments one by one using their key strings.

### How to reproduce

- Create a plugin
- Add AdvancedEnchantments' API as a library (I used maven to do this import, and added it to my pom as such)
- Add AE as a soft-depend in your plugin.yml
- On any trigger that can hand you an item (in my case an InventoryClickEvent) run the following code:
```java
if (stack != null && !stack.getType().equals(Material.AIR)) {
    stack.getEnchantments().keySet().forEach(stack::removeEnchantment);
    if (Bukkit.getPluginManager().isPluginEnabled("AdvancedEnchantments")) {
        AEAPI.getEnchantmentsOnItem(stack).keySet().forEach(name -> AEAPI.removeEnchantment(stack, name));
        Bukkit.broadcast(Component.text(AEAPI.getEnchantmentsOnItem(stack).toString()).asComponent()); // DEBUG
    }
}
```

You will notice all advanced enchantments will get placed in chat by the debug broadcast (meaning that AEAPI#getEnchantmentsOnItem can find the enchants) but none of them are removed from the item.

I have tried rearranging the code many other ways but none seem to work.

### Screenshots / Videos

Nothing happens, so no video or screenshots could be made.

### "/ae plinfo" link

https://paste.md-5.net/ritovopuzo

### Server Log

As said before nothing is mentioned in the logs about either plugin.

**Comment by GC-spigot** [comment]
Those API methods return itemstacks. Enchants are applied with NBT, so removing NBT means rebuilding the itemstack. Right now you don't use the returned itemstacks, here's an example of how you should do it
```java
item = AEAPI.removeEnchantment(item, enchant);
