### ISSUE TITLE
Lands don't work with advanced enchantment in 9.2.18 

### ISSUE THREAD

**Issue by ColdDragons81** [GC-spigot/AdvancedEnchantments#3503]
### Describe the bug

With the last version of advanced enchantment trench, potatos , carrot replanter and replanter doesn't work, 
i have this log 

### How to reproduce

Take item with trench and try to break block with lands install with the version 9.2.18 of advanced enchant and lands in 6.32.5

### Screenshots / Videos

For trench https://pastebin.com/RdyLVW13
For replanter, carrot and potatos https://pastebin.com/d2M7vnBj

### "/ae plinfo" link

https://paste.md-5.net/ipubacalej

**Comment by Nashlord** [comment]
I have the same error, with the latest version of plugin lands and advancedenchant. The trench enchantment no longer works.

**Comment by GC-spigot** [comment]
Resolved
