### ISSUE TITLE
Haste - left hand

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3504]
### Describe the bug

When a player puts a pickaxe that has a Haste enchant in his left hand, the player receives Haste even if he cannot dig with the pickaxe.

### How to reproduce

https://www.youtube.com/watch?v=vvq9z9kVPtY

### "/ae plinfo" link

https://paste.md-5.net/utoqewovan

**Comment by GC-spigot** [comment]
That is designed to be this way, he's holding that item. If it was something else, e.g. regen or more health item, it would need to work - same for this one.
