### ISSUE TITLE
Please add permissions to plugin.yml for accessibility

### ISSUE THREAD

**Issue by z1haze** [GC-spigot/AdvancedEnchantments#3505]
### Describe the bug

Hi, please add all of the permission nodes for commands and such to your plugin.yml for accessibility so that other plugins can read them and know how to properly hide/display access to things. For example, PL-Hide/PL-Hide-Pro is for managing command access and tab complete, however because your plugin does not include the commands and permissions in the plugin.yml, things do not function properly.

### How to reproduce

1. use a plugin that expects permissions and commands to exist in plugin.yml like normal. (PL Hide is my example)
2. see that when you add certain permissions for a user/group in lperms, PL Hide is unable to display proper comamnds and tab complete.
<img width="528" alt="image" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/6024725/1cb0dc0d-cacf-4ccb-a258-b178ced549bf">

additionally, the permissions shown here in your documentation do not allow the user to run these commands:
<img width="381" alt="image" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/6024725/34a969ad-f95c-483f-8bbd-b524970f9c8c">

### "/ae plinfo" link

https://paste.md-5.net/vatatopivi

**Comment by GC-spigot** [comment]
Added
