### ISSUE TITLE
Torchlights and Pitcher seeds don't replant with the Replanter enchantment

### ISSUE THREAD

**Issue by FourNineRugz** [GC-spigot/AdvancedEnchantments#3506]
### Describe the bug

Torchlights and Pitcher seeds don't replant with the Replanter enchantment. When breaking them they dont replant

### How to reproduce

Torchlights and Pitcher seeds don't replant with the Replanter enchantment. When breaking them they dont replant

### "/ae plinfo" link

https://paste.md-5.net/loqoxexexi

**Comment by ThomasWega** [comment]
Should be fixed in the next update :)
