### ISSUE TITLE
Having a trench item in the offhand and trying to silk touch leaves with a hoe won't drop the leaves

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3507]
### Describe the bug

Leaves aren't dropped when placed near stone or similar blocks when the leaves are broken with a hoe that has silk touch and you're holding the item with trench in the off hand.

I see this as two issues in one:
- Trench shouldn't apply here at all / it shouldn't break any stone
- The leaves should be dropped

### How to reproduce

- Get a diamond pickaxe
- Enchant it with Trench 9
- Put the diamond pickaxe in your off hand
- Get a diamond hoe
- Enchant the diamond hoe with the vanilla silk touch 1
- Place any leaves near stone
- Break the leaves with your hoe
- See how the stone is removed while it shouldn't be and the leaves do not drop at all.

### Screenshots / Videos

https://youtu.be/m0sc_3bqWIU

### "/ae plinfo" link

https://paste.md-5.net/okacayipal

### Server Log

https://mcpaste.io/e81c3e59ca469a69

**Comment by MrAxeTv** [comment]
Bug confirmed  will look at it today

**Comment by Folas1337** [comment]
> Bug confirmed will look at it today

Have you been able to do anything about this yet?

**Comment by Folas1337** [comment]
It seems it's been fixed in one of the current versions. Thanks for fixing it!
