### ISSUE TITLE
ARROW_HIT doesn't work

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#3508]
### Describe the bug

Arrow Hit Doesn't Work No Matter What, Below works with SHOOT, but not ARROW_HIT

### How to reproduce

test:
  display: '%group-color%Test'
  description: 'Test'
  applies-to: 'Bows'
  group: 'CUSTOM'
  type: 'ARROW_HIT;SHOOT'
  applies:
  
'BOW'
settings:
  removeable: false
levels:'1':
    chance: 100
    cooldown: 0
    effects:
"MESSAGE:I shot an arrow @Attacker"
"MESSAGE:%block x% @Attacker"
"MESSAGE:%victim block x% @Attacker"
"MESSAGE:this number should be different or null from the above number %attacker block x% @Attacker"

### "/ae plinfo" link

https://paste.md-5.net/ekuhubesid

**Comment by GC-spigot** [comment]
Fixed
