### ISSUE TITLE
God mode issue

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#3509]
### Describe the bug

If an effect fails, the player will become invincible. Attacking them will appear to do damage but they will not lose any health. It will also not print to the console that the effect failed like it used to

### How to reproduce

1. Use an item with an effect that is not configured correctly. Here is an example of my broken one (because I did not put the "time: " for the repeating effect 

fairydust:
  display: '%group-color%Fairydust'
  description: "Restore food and health every few seconds."
  applies-to: 'Armor'
  type: 'REPEATING'
  group: 'ULTIMATE'
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 30
      effects:
        - 'ADD_FOOD:20'
        - 'ADD_HEALTH:20'

2. When wearing an item with this enchant, I now cannot be killed
3. When I add "time: ", it works fine. 

This issue occurs for every failed effect in some way and doesn't output ANYTHING to the console

### Screenshots / Videos

I posted a video in my active discord ticket "aenchantments-4364"

### "/ae plinfo" link

https://paste.md-5.net/vedipirepi

**Comment by GC-spigot** [comment]
This is definitely an issue with REPEATING, resolved now
