### ISSUE TITLE
Issue with static effect enchantments on SkullItems (v5.2.8)

### ISSUE THREAD

**Issue by Splurgies** [GC-spigot/AdvancedEnchantments#351]
So i am having issues with static effect enchantments on player skulls. I am having more than 1 issue and I will list all that I know of.

Left click skull onto helmet slot. (Right clicking the skull onto the helmet slot works fine.)
https://imgflip.com/gif/2uhx90
As you might be able to tell the first time I put the skull on the player I put it on by left clicking, the second time I put the skull on the player I right clicked.

Right clicking the skull in hot bar. When a player right clicks the skull (doing the function of right clicking an armor piece to equip it) it gives the static potion effects on the item. I am not requesting a feature to put the skull on the head but rather a fix so it will no longer give the static effects.

Shift clicking the skull in your inventory. In vanilla minecraft when a player shift clicks an helmet piece and they have nothing on on their head the armor piece will be applied to their head. Since it is a player skull, and in vanilla minecraft you can not shift click a player skull to put it on your head, the skull just goes to the top of your inventory and the player gets the effects of the skull without wearing it.
https://imgflip.com/gif/2uhxwd

These are all of the issues that I have found with enchantments working with player skulls.

**Comment by GC-spigot** [comment]
Can't fix any issues with skulls - the utility I use for detecting armor equipping / unequipping is often updated and if I modify it then I won't be able to update it, and will have to implement the changes every time it's updated.
