### ISSUE TITLE
Bug with Lands with 9.3.1

### ISSUE THREAD

**Issue by Darkmager** [GC-spigot/AdvancedEnchantments#3510]
### Describe the bug

whenever u use veinminer,trench it dont work and there is a error in console
https://pastebin.com/Esy1P19d

### How to reproduce

install lands latest version and adv ench 9.3.1 and use mining custom enchants

### "/ae plinfo" link

https://paste.md-5.net/yipewabige

**Comment by Nashlord** [comment]
same problem here

**Comment by ColdDragons81** [comment]
Same for me

**Comment by Darkmager** [comment]
any update on this?

**Comment by ColdDragons81** [comment]
It's in progress i think

**Comment by Nashlord** [comment]
it's starting to get urgent...

**Comment by Darkmager** [comment]
yes kinda urgent when 15+ players in my server are complaining everyday

**Comment by Darkmager** [comment]
issue is resolved
