### ISSUE TITLE
Two hands

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3511]
### Describe the bug

AdvancedEnchantments does not support two hands: if I put a pick with special enchantments in my left hand and a regular pick (without any enchantments)  in my right hand, I can still dig with a regular pick, e.g. 3x3, I have a haste effect. In addition, the pickaxe in the left hand gets damaged.

### How to reproduce

1. Put pickaxe with special enchantments in the left hand
2. Put regular pickaxe (without any enchantments) in the right hand
3. Mine
4. Enchantments work altough you have special pickaxe in the left hand. Also the pickaxe in the left hand is getting damage.

### "/ae plinfo" link

https://paste.md-5.net/jisoluripa

**Comment by plumpkiwi** [comment]
have also had this issue, have trench being able to be triggered while in the offhand slot.

**Comment by ThomasWega** [comment]
For now we decided to disable enchantments working in offhand if the trigger is MINING or ATTACK/ATTACK_MOB. The changes will be in the next update

**Comment by ThomasWega** [comment]
We fixed that in 9.3.19

**Comment by ThomasWega** [comment]
My bad. I've actually issued a fix for this yesterday, but it wasn't merged yet. In for sure will be in one of upcoming updates. Most likely today :)
