### ISSUE TITLE
custommodeldata not working

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#3512]
### Describe the bug

slot-increaser and holywhitescroll custommodeldata not working

### How to reproduce

slot-increaser:
type: paper
id: 0
custom-model-data: 2103
holywhitescroll:
type: PAPER
id: 0
custom-model-data: 2100

### Screenshots / Videos

https://i.imgur.com/bl7arcR.png

### "/ae plinfo" link

https://paste.md-5.net/upikebalid

**Comment by GC-spigot** [comment]
Restart your server instead of `/ae reload`, it will work then
