### ISSUE TITLE
%players% and %nearby mobs% output nothing

### ISSUE THREAD

**Issue by LambChomps** [GC-spigot/AdvancedEnchantments#3514]
### Describe the bug

%players% and %nearby mobs% should output the number of their respective entities within a 10-block radius but don't return any number no matter the number of mobs or players nearby. Using either in a condition as well will return "(condition) should be numeric only".

Confirmed by aXe on Discord in ticket aeenchanments-4374.

### How to reproduce

test:
  display: '%group-color%Test'
  description: |-
    test
  applies-to: Axes
  type: ATTACK;ATTACK_MOB
  group: BASIC
  applies:
    - ALL_SWORD
    - ALL_TOOLS
  levels:
    '1':
      cooldown: 1
      effects:
        - 'MESSAGE:mobs-%nearby mobs%, players-%players%, victim mobs-%victim nearby mobs%, attacker mobs-%attacker nearby mobs%.'

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/84216914/846bc37e-8719-4085-88e6-27cbb04cf1e2)

### "/ae plinfo" link

https://paste.md-5.net/obawulejat

**Comment by ThomasWega** [comment]
Will be fixed in the next update :)
