### ISSUE TITLE
Telepathy issue

### ISSUE THREAD

**Issue by Tek78** [GC-spigot/AdvancedEnchantments#3515]
### Describe the bug

The Telepathy enchant does not give the correct amount of clay balls when a clay block is mined.
By default a clay block drops 4 clay balls, telepathy gives only 1.

### How to reproduce

Pretty self explanatory, Enchant a shovel with Telepathy and mine a clay block.

### "/ae plinfo" link

https://paste.md-5.net/aliqateyun

**Comment by GC-spigot** [comment]
Resolved!
