### ISSUE TITLE
Breaking the enchantment of trench blocks that appear due to the enchantment of Water_Walker

### ISSUE THREAD

**Issue by FunSkelet** [GC-spigot/AdvancedEnchantments#3516]
### Describe the bug

Enchantment Water_walker creates obsidian under the player. If you break any block next to the obsidian with a pickaxe, with the enchantment of Trench, then the obsidian will also break

### How to reproduce

on the video

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/68019106/23030ce4-9c2c-4ba5-ada6-b3cb523e8fc1

### "/ae plinfo" link

https://paste.md-5.net/xikidafute

**Comment by MrAxeTv** [comment]
Fixed!
