### ISSUE TITLE
[BUG] When quickly swapping armor/tools you keep effects

### ISSUE THREAD

**Issue by Texbio** [GC-spigot/AdvancedEnchantments#3517]
### Describe the bug

When quickly swapping armor/tools you keep effects

get a pickaxe with haste and click it a couple times in your slot that you are selecting and you can keep the effects.
works for armor too.

this has been a bug for a couple years no idea why its not fixed

### How to reproduce

-

### "/ae plinfo" link

n/a

**Comment by GC-spigot** [comment]
We can’t recreate this, provide /ae plinfo paste and record a video

**Comment by ThomasWega** [comment]
I am sorry, we were not able to replicate this issue and also haven't heard back from you in a while. If you still have this issue, feel free to create a new github issue and please provide a video showcasing the issue.
