### ISSUE TITLE
REPAIR effect not working on DEFENSE type

### ISSUE THREAD

**Issue by danekoenders** [GC-spigot/AdvancedEnchantments#3518]
### Describe the bug

I'm trying to create an enchantment that will make armor unbreakable. So what i did is run a REPAIR effect on a DEFENSE type. But this will not work. When I put another type like ATTACK or something else, it will work. So it has to do with the DEFENSE type. I've tried to set targets to the effect too, like @Self but this will not work either.

This is the config of the enchantment:
`kowarenai:
  display: '%group-color%Kowarenai'
  description: Armor with this enchant become unbreakable.
  applies-to: Armor
  type: ATTACK
  group: HEROIC
  settings:
    removeable: false
    disable-in-enchanter: true
  applies:
  - ALL_ARMOR
  levels:
    '1':
      effects:
      - REPAIR`

### How to reproduce

Just put the config posted above in the enchantments.yml file. Then you will see that when hit by a mob or player it won't repair itself.

### "/ae plinfo" link

 https://paste.md-5.net/oxidiwinib

**Comment by MrAxeTv** [comment]
Started looking in to it 
I can confirm DEFENSE trigger not working

**Comment by MrAxeTv** [comment]
> ### Describe the bug
> 
> I'm trying to create an enchantment that will make armor unbreakable. So what i did is run a REPAIR effect on a DEFENSE type. But this will not work. When I put another type like ATTACK or something else, it will work. So it has to do with the DEFENSE type. I've tried to set targets to the effect too, like @self but this will not work either.
> 
> This is the config of the enchantment: `kowarenai: display: '%group-color%Kowarenai' description: Armor with this enchant become unbreakable. applies-to: Armor type: ATTACK group: HEROIC settings: removeable: false disable-in-enchanter: true applies:
> 
>     * ALL_ARMOR
>       levels:
>       '1':
>       effects:
>       
>       * REPAIR`
> 
> 
> ### How to reproduce
> 
> Just put the config posted above in the enchantments.yml file. Then you will see that when hit by a mob or player it won't repair itself.
> ### Screenshots / Videos
> 
> _No response_
> ### "/ae plinfo" link
> 
> https://paste.md-5.net/oxidiwinib
> ### Server Log
> 
> _No response_

I made some testing and made it work 
please can you try this settings 
https://pastebin.com/vvkE5hUC

**Comment by ThomasWega** [comment]
Can confirm this works

**Comment by danekoenders** [comment]
I have tried this exact setup but it doesn't work on my end. Are u sure it works? @ThomasWega
