### ISSUE TITLE
InventoryClickEvent

### ISSUE THREAD

**Issue by JIMIN0402** [GC-spigot/AdvancedEnchantments#3519]
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/114882365/91accb75-6fba-47a4-980d-5f18b3aab965)

### How to reproduce

I'm not sure what to write.

If you don't know how to use Github, please leave it on Discord so we can know exactly.
Discord: jimin_0402

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/114882365/67eaa755-ab3e-4aea-a9ca-12054221593d)

### "/ae plinfo" link

https://paste.md-5.net/zanepizufa

**Comment by GC-spigot** [comment]
Seems like this is a configuration issue - stattrack material is invalid. I've added more warnings when this happens to console.
