### ISSUE TITLE
Alchemist issue/bug

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#352]
So the alchemist exchanges 2x of the same book for 1 of a level higher. That works fine.

But it also exchanges 2x magic dust of the same rarity into 1 of higher chances. I am unable to get that to work. I tried  3%+10% and it turned into a 6%. I'm having players report this to me as well.

Would there also be a way to add if you put two dusts at max %, they could = a low % of the next tier?

**Comment by GC-spigot** [comment]
This isn't an issue - (3+10) / 2 = 6 (if not rounded). There's a setting in config.yml to change how this works, by default it adds up chances and splits them in half, you're able to change it so it just adds up.
