### ISSUE TITLE
Dupe Bug with soulbound

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#3520]
### Describe the bug

just hold the item in offhand with soulbound and die in keeping enabled world. it will dupe it... well at least on my server does it..

### How to reproduce

just hold the item in offhand with soulbound and die in keeping enabled world. it will dupe it... well at least on my server does it..

### "/ae plinfo" link

https://paste.md-5.net/ehaholagiz

**Comment by Rexmen1** [comment]
https://gyazo.com/9a2796bb4cf724e3b79efe15998bd338

**Comment by Rexmen1** [comment]
soulbound:
  display: '%group-color%Soulbound'
  description: Keeps item on death.
  applies-to: Weapons + Tools + Bows + Armor
  type: DEATH;PASSIVE_DEATH
  group: LEGENDARY
  applies:
    - ALL_TOOLS
    - ALL_SWORD
    - BOW
    - CROSSBOW
    - ALL_ARMOR
    - FISHING_ROD
    - TRIDENT
    - SHIELD
    - SHEARS
  levels:
    '1':
      effects:
        - KEEP_ON_DEATH

**Comment by Rexmen1** [comment]
keep inv enabled world*

**Comment by Darkmager** [comment]
why would you want to use soulbound in keep inv world?

**Comment by ThomasWega** [comment]
Should be fixed in newer versions, as I can't reproduce the issue and can see that we check for keepInventory. If this issue still persists, please make sure to create a new Issue. Thanks! :)

**Comment by Rexmen1** [comment]
Its not fixed still, Still happening in latest version of advanced enchantment 9.3.17
