### ISSUE TITLE
Strike enchantment

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3522]
### Describe the bug

When I hit with a bow that has Enchant Strike, like a mob, it gets hit by lightning. Properly, lightning should only be sent if I hit it with a shot arrow.

### How to reproduce

1. Hit mob with Strike bow (without shooting arrows) 

### "/ae plinfo" link

https://paste.md-5.net/azewocazus

**Comment by MrAxeTv** [comment]
> ### Describe the bug
> 
> When I hit with a bow that has Enchant Strike, like a mob, it gets hit by lightning. Properly, lightning should only be sent if I hit it with a shot arrow.
> ### How to reproduce
> 
>     1. Hit mob with Strike bow (without shooting arrows)
> 
> 
> ### Screenshots / Videos
> 
> _No response_
> ### "/ae plinfo" link
> 
> https://paste.md-5.net/azewocazus
> ### Server Log
> 
> _No response_

Can you provide us with configuration of you enchant?
