### ISSUE TITLE
Fortune doesn't work 

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3523]
### Describe the bug

Fortune VII does not work correctly (does not drop the correct number of ore) when the enchants Experience III, Smelting III, Trench III, Haste III are present

### How to reproduce

1. Mine ore with specific pickaxe

### "/ae plinfo" link

https://paste.md-5.net/umunicosel

**Comment by ThomasWega** [comment]
Can you please provide a video and explain in more detail what is wrong?

**Comment by ThomasWega** [comment]
Can you provide some numbers from your testing? What should it drop with fortune and what it drops to you?

**Comment by ThomasWega** [comment]
does this happen only with nether gold ore, or with other ores as well?

**Comment by ThomasWega** [comment]
Confirmed. I will handle this issue more on https://github.com/GC-spigot/AdvancedEnchantments/issues/3523

**Comment by ThomasWega** [comment]
will handle it further on https://github.com/GC-spigot/AdvancedEnchantments/issues/3615
