### ISSUE TITLE
[FEATURE/IMPROVEMENT] Change Or Replace %hit location%

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#3524]
### Describe the bug

%hit location% in-game shows x|y|z as the arrow coordinates when the arrow lands, and doesn't do much seemingly outside of a message, a change that'd be small but effective would change it do x y z, by simply replacing | with a space, as it'd be usable in commands such as teleport as well as execute positioned, another, more technical option would be to splice it into %hit location x% for example, but the current hit location isn't as useful as it is now, and just removing the seperators and setting a space would give it a lot more uses, especially for a wanted feature such as a teleport bow for example, would let people do things such as

CONSOLE_COMMAND:teleport %player name% %hit location%

as of now, it doesn't work since it puts for example -51|0|-4 even in the command, which is kind of terrible

### How to reproduce

Change %hit location% display from -51|0|-4 to -51 0 -4
Or Add/Splice the placeholder to get %hit location (x/y/z)% to just get 1 variable alone for same result for if people want something more specific

### "/ae plinfo" link

https://paste.md-5.net/egugibocoj

**Comment by SkiiTahoe** [comment]
This is needed as a feature 👍

**Comment by Skullslice** [comment]
instead of seperating it out manually like others have stated can we just get a thing like %block x% or %hit location x% to get where the arrow landed?

**Comment by DuplexLake** [comment]
> 

that's basically been suggested above, yeah

**Comment by ThomasWega** [comment]
Just finished coding this. In the next update, there will be new variables:

%hit location x%
%hit location y%
%hit location z%
