### ISSUE TITLE
Mineral Duplication BUG

### ISSUE THREAD

**Issue by PhantomXjack** [GC-spigot/AdvancedEnchantments#3525]
### Describe the bug

I discovered that if two enchantments are simultaneously applied to a pickaxe, there will be a case of mineral duplication.
And attach the original version of Silk Touch 

### How to reproduce

巨錘:
  display: '%group-color%巨錘'
  description: "有機會在3x3區域內一次性破壞"
  applies-to: "鎬子、鏟子"
  type: MINING
  group: ULTIMATE
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    '1':
      chance: 13
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '2':
      chance: 26
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '3':
      chance: 36
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '4':
      chance: 49
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '5':
      chance: 59
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '6':
      chance: 72
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '7':
      chance: 85
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '8':
      chance: 90
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '9':
      chance: 100
      effects:
        - BREAK_BLOCK @Trench{r=3}
----------------------------------------------------
連鎖挖礦:
  display: '%group-color%連鎖挖礦'
  description: "挖掘整個礦脈"
  applies-to: "鎬子"
  group: ELITE
  type: MINING
  applies:
    - ALL_PICKAXE
  levels:
    '1':
      chance: 15
      cooldown: 4
      settings:
        whitelist:
          - "COAL_ORE"
          - "COPPER_ORE"
          - "IRON_ORE"
          - "GOLD_ORE"
          - "LAPIS_ORE"
          - "REDSTONE_ORE"
          - "DIAMOND_ORE"
          - "EMERALD_ORE"
          - "NETHER_QUARTZ_ORE"
          - "NETHER_GOLD_ORE"
          - "ANCIENT_DEBRIS"
          - "DEEPSLATE_COAL_ORE"
          - "DEEPSLATE_COPPER_ORE"
          - "DEEPSLATE_IRON_ORE"
          - "DEEPSLATE_GOLD_ORE"
          - "DEEPSLATE_LAPIS_ORE"
          - "DEEPSLATE_REDSTONE_ORE"
          - "DEEPSLATE_DIAMOND_ORE"
          - "DEEPSLATE_EMERALD_ORE"
      effects:
        - BREAK_BLOCK @Veinmine
    '2':
      chance: 35
      cooldown: 3
      settings:
        whitelist:
          - "COAL_ORE"
          - "COPPER_ORE"
          - "IRON_ORE"
          - "GOLD_ORE"
          - "LAPIS_ORE"
          - "REDSTONE_ORE"
          - "DIAMOND_ORE"
          - "EMERALD_ORE"
          - "NETHER_QUARTZ_ORE"
          - "NETHER_GOLD_ORE"
          - "ANCIENT_DEBRIS"
          - "DEEPSLATE_COAL_ORE"
          - "DEEPSLATE_COPPER_ORE"
          - "DEEPSLATE_IRON_ORE"
          - "DEEPSLATE_GOLD_ORE"
          - "DEEPSLATE_LAPIS_ORE"
          - "DEEPSLATE_REDSTONE_ORE"
          - "DEEPSLATE_DIAMOND_ORE"
          - "DEEPSLATE_EMERALD_ORE"
      effects:
        - BREAK_BLOCK @Veinmine
    '3':
      settings:
        whitelist:
          - "COAL_ORE"
          - "COPPER_ORE"
          - "IRON_ORE"
          - "GOLD_ORE"
          - "LAPIS_ORE"
          - "REDSTONE_ORE"
          - "DIAMOND_ORE"
          - "EMERALD_ORE"
          - "NETHER_QUARTZ_ORE"
          - "NETHER_GOLD_ORE"
          - "ANCIENT_DEBRIS"
          - "DEEPSLATE_COAL_ORE"
          - "DEEPSLATE_COPPER_ORE"
          - "DEEPSLATE_IRON_ORE"
          - "DEEPSLATE_GOLD_ORE"
          - "DEEPSLATE_LAPIS_ORE"
          - "DEEPSLATE_REDSTONE_ORE"
          - "DEEPSLATE_DIAMOND_ORE"
          - "DEEPSLATE_EMERALD_ORE"
      effects:
        - BREAK_BLOCK @Veinmine
        
      Using these two enchantments along with Silk Touch will cause a bug.

### "/ae plinfo" link

https://paste.md-5.net/jonakidase

**Comment by GC-spigot** [comment]
Fixed
