### ISSUE TITLE
BREAK_BLOCK / TP_DROPS to mining activities bug?

### ISSUE THREAD

**Issue by PhantomXjack** [GC-spigot/AdvancedEnchantments#3526]
### Describe the bug

The enchantments like BREAK_BLOCK / TP_DROPS, etc., which are related to mining activities, will not apply the Fortune effect to ores such as lapis lazuli/redstone, etc., that usually yield multiple drops in vanilla Minecraft.

### How to reproduce

Enchantments using BREAK_BLOCK / TP_DROPS commands mining activities to ores such as lapis lazuli/redstone,

### "/ae plinfo" link

https://paste.md-5.net/jonakidase

**Comment by GC-spigot** [comment]
Fortune is applied, we've tested. Try breaking multiple blocks - just like in vanilla, not all blocks will drop it.
