### ISSUE TITLE
Wings I problem

### ISSUE THREAD

**Issue by reaLIupy** [GC-spigot/AdvancedEnchantments#3531]
### Describe the bug

when a user exchanges the Wings I enchanted boots into another non-flyable boots by right-clicking, the fly effect remains, making the user eventually flyable without wearing Wings I boots.

### How to reproduce

 I tried %item slot% and many other things to make it flyable when only Wings I enchanted boots are equipped, but they all failed. in order to find out if the bug was also existed in the 1.17, I ran 1.17 server pack(the one of 2 years before) again, and I found it working only when equipped with feets, making the fly effect to be disabled immediately when I perform a right clicking exchange with other boots. I want the new version to be executed normally again.

### Screenshots / Videos

https://youtu.be/lZQRZKih4LU

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ThomasWega** [comment]
Hey! I was not able to replicate this issue. Try with the latest version of the plugin please, and record a video if possible
https://i.imgur.com/a0pyHrT.mp4
