### ISSUE TITLE
Enchanted book duping bug

### ISSUE THREAD

**Issue by R3verseV** [GC-spigot/AdvancedEnchantments#3532]
### Describe the bug

Making an enchantable book from the configs causes the book to dupe for free.

### How to reproduce

- Add "BOOK" to the enchantable category of an enchantment
- Enchant a stack of books in the enchanting table
- You'll now have 64 enchanted books

### Screenshots / Videos

https://youtu.be/d9WpY3mC02Q

### "/ae plinfo" link

https://paste.md-5.net/qowubaxexe

### Server Log

https://mcpaste.io/50b6db9177574dd7

**Comment by GC-spigot** [comment]
You shouldn't really apply custom enchants onto books, that's now how it's designed to be done. Are you sure this is not an issue because you are in creative mode? Creative mode is super buggy and a lot of things aren't designed to be done in it.

I can't reproduce it.
