### ISSUE TITLE
MMOItems support

### ISSUE THREAD

**Issue by KNzE07** [GC-spigot/AdvancedEnchantments#3534]
### Describe the bug

If an upgrade from MMOitems is used and it succeeds, the effect from AE cannot be applied.

### How to reproduce

Fixed an issue where Custom Enchanted effects could not be used if upgrading from the MMOitems plugin was successful.

### Screenshots / Videos

https://youtu.be/oR9YiVAbKBY

### "/ae plinfo" link

https://paste.md-5.net/jesizogeye

**Comment by ThomasWega** [comment]
Hey! Could you please explain a bit better what exactly is wrong? How exactly to reproduce your issue, your configs, expected result. Thanks :)

**Comment by ThomasWega** [comment]
We will be looking into MMOItems integration in the future

**Comment by ThomasWega** [comment]
Hey! Please explain what exactly is the conflict here so I can take a look at it
