### ISSUE TITLE
Blocktrak + Telephaty dont work

### ISSUE THREAD

**Issue by sachiko8787** [GC-spigot/AdvancedEnchantments#3537]
### Describe the bug

If you use Telephaty + Blocktrak then Blocktrak stop count

### How to reproduce

If you use Telephaty + Blocktrak then Blocktrak stop count

### "/ae plinfo" link

https://paste.md-5.net/begihizigu

**Comment by aXe18** [comment]
@sachiko8787 Update to latest version and it works ! Tested on latest
