### ISSUE TITLE
Pumpkin effect losing items

### ISSUE THREAD

**Issue by anhcraft** [GC-spigot/AdvancedEnchantments#3538]
### Describe the bug

The scare enchantment, using Pumpkin effect, sometimes cause item loss. This has existed on my server and caused a lot of trouble.

### How to reproduce

1. The attacker equips a weapon with Scare enchantment
2. Attack someone who also has a helmet equipped
3. This bug currently occurs if: The victim got the effect at the last hit. He dies while the effect is still going on.
4. The helmet is dropped, and the pumpkin remains forever even after respawn
Sometimes, the helmet will be lost forever.

To quickly reproduce this issue:
1. Set Scare chance to 100%
2. Using a powerful weapon that can kill target in 1-2 hits

### "/ae plinfo" link

https://paste.md-5.net/oxufiqiwor

**Comment by ThomasWega** [comment]
Should be fixed in next updates! :)
