### ISSUE TITLE
Plugin does not respect BlockBreakEvent#isDropItems

### ISSUE THREAD

**Issue by masmc05** [GC-spigot/AdvancedEnchantments#3540]
### Describe the bug

My plugin is incompatible with the enchantment's effect "SMELT" because my plugin does not cancel the event but instead use BlockBreakEvent#setDropItems to false for a proper work of my features, but your plugin still make the items drop

Maybe you could ignore the event if this is set to false?

### How to reproduce

Make a plugin which sets BlockBreakEvent#setDropItems to false and expects it to work

### "/ae plinfo" link

https://paste.md-5.net/uzawifaleq

**Comment by GC-spigot** [comment]
Change your listener priorities, we support it https://i.gyazo.com/f145b789d50ae353774ee7230fd901cd.png

**Comment by masmc05** [comment]
> Change your listener priorities, we support it https://i.gyazo.com/f145b789d50ae353774ee7230fd901cd.png

oh, ok
