### ISSUE TITLE
Alchemist wont accept any books or dust

### ISSUE THREAD

**Issue by Chiefink5** [GC-spigot/AdvancedEnchantments#3543]
### Describe the bug

When trying to complete the trade in the Alchemist, regardless of the enchantment group used, it wont accept any books/dust inserted into the GUI.

### How to reproduce

Get some enchantment books that would match and upgrade when put in the alchemist. Try to complete the trade for the upgraded enchantment book/dust and see that the alchemist does not want those items.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1136472905383944232/1136485764864168156/IMG_4918.mov

### "/ae plinfo" link

https://paste.md-5.net/hobusujuba

### Server Log

https://paste.md-5.net/powomofoco.md

**Comment by ThomasWega** [comment]
Hey! It works just fine for us. Make sure to use the latest version. If this issue still persists, feel free to create a new github issue.

**Comment by ThomasWega** [comment]
it's most likely old AI and AE plugins... so updating both plugin and generating fresh files should solve it
