### ISSUE TITLE
No permission for commands inputted in console/OPs

### ISSUE THREAD

**Issue by anhcraft** [GC-spigot/AdvancedEnchantments#3544]
### Describe the bug

Using the latest version, commands such as /ae giveitem, givebook and give cannot be used in the console or by OPs. The error returned is no permission.

### How to reproduce

1. Use command /ae giveitem in the console
2. No permission

After downgrading to 9.3.5, the problem was solved.

### "/ae plinfo" link

https://paste.md-5.net/icogumiguq

**Comment by ThomasWega** [comment]
Hey! Does this issue still happen in 9.3.7? @GC-spigot added a fix for that in that version. Please let me know

**Comment by anhcraft** [comment]
yep this was fixed

**Comment by ThomasWega** [comment]
Glad to hear that! Thanks for letting us know :)
