### ISSUE TITLE
Trench, Waterwalker, Lavawalker BUG

### ISSUE THREAD

**Issue by LavosKore** [GC-spigot/AdvancedEnchantments#3546]
### Describe the bug

This enchants don't work, and when they used appear this message in console https://pastebin.com/uaqQFDFK

### How to reproduce

When i mine with a pickaxe with trench up, appear this message, and block mined drop nothing, same for lavawalker and waterwalker, i think is an issue with Factions, i use SaberFactions.

### Screenshots / Videos

https://pastebin.com/uaqQFDFK

### "/ae plinfo" link

https://paste.md-5.net/pitibijube

**Comment by GC-spigot** [comment]
duplicate of #3486
