### ISSUE TITLE
Feature request - regarding BREAK_TREE

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3548]
### Describe the bug

Ok, so BREAK_TREE effect should be done way it respects player placed blocks, only working to naturally grown trees :) 
Its just annoying to have that enchant and then trying to remove few blocks from your build and then it can destroy alot of work.
Or making everyone having option to use it way they want, there could be then meaby setting like "respect-player-placed-blocks: true" and that could be located even under the "stems-count-as-trees: true"

### How to reproduce

Same as above :) 

### "/ae plinfo" link

No need

**Comment by ThomasWega** [comment]
Should hopefully be added in the next update! :)
