### ISSUE TITLE
MobTrak stops tracking whenever item is dropped

### ISSUE THREAD

**Issue by Toshiii35** [GC-spigot/AdvancedEnchantments#3549]
### Describe the bug

Whenever you add **MobTrak** on an item, it records the mobs killed but stops doing so whenever you drop & pick it again.  

### How to reproduce

Put a mobtrak on a sword, start killing mobs. It will record it at first, then drop the item on the ground and pick it back up, it won't continue the count anymore

### "/ae plinfo" link

https://paste.md-5.net/utetosobob

**Comment by ThomasWega** [comment]
Hey! I was unfortunately not able to replicate this issue. If this issue is still present even in the latest version, please let me know and best supply a video showcase

**Comment by Toshiii35** [comment]
Sorry! I forgot to mention this issue is still active and only exists on items with CustomModelData here's a video https://www.xbox.com/play/media/D4567WQDJM

**Comment by ThomasWega** [comment]
Hey! Still works just fine for me.

https://i.imgur.com/TwgvzKz.mp4
