### ISSUE TITLE
PERMANENT EFFECTS BUG WHEN SWITCH ARMOR

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3550]
### Describe the bug

Is possible to switch armors with right click. But, if you wearing a armor with EFFECT_STATIC and switch using right click, you will have permanent effects.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66658478/68127962-aaef-4c30-87f0-d0c0b6f77525)
****

### How to reproduce

Use any default enchantment of the plugin that use **EFFECT_STATIC**.

1. Enchant a armor with it
2. Equip the armor, let's suppose is a helmet
3. Take any other helmet, with no enchantments
4. Right click to switch the helmet
5. Done, you have a permanent effect

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66658478/0e3a5866-4657-4f65-a597-700fc8d85917)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66658478/e0d90b9e-1910-4eb4-bad6-2bea5d2e94ec)

### "/ae plinfo" link

https://paste.md-5.net/feterihava

**Comment by GC-spigot** [comment]
Fixed!
