### ISSUE TITLE
Telepathy bypasses Towny protection

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3551]
### Describe the bug

If you have a pickaxe with telepathy you can bypass the protection of Towny claims. You'll break the block, it'll say "Outsiders aren't allowed to Destroy." but it'll still teleport the block into your inventory.

### How to reproduce

- Install AdvancedEnchantments
- Install Towny
- Have a pickaxe with the telepathy enchantment
- Break a block inside a town where you shouldn't be able to break it

### Screenshots / Videos

(Hopefully not required as this is really straight forward and easy to explain in text)

### "/ae plinfo" link

https://paste.md-5.net/upaxidewup

### Server Log

https://mcpaste.io/ca2b4e58af5428dc

**Comment by Folas1337** [comment]
It is not only Telepathy bypassing Towny, it also seems to be Trench and Smelting and probably pretty much any enchantment that somehow breaks or modifies the drop of blocks, quite urgent imho!

**Comment by Folas1337** [comment]
Last version where this was NOT an issue is 9.3.1, so it seems to have been introduced in 9.3.2.

**Comment by GC-spigot** [comment]
Fixed
