### ISSUE TITLE
BREAK_BLOCK to Fortune abnormal quantity

### ISSUE THREAD

**Issue by PhantomXjack** [GC-spigot/AdvancedEnchantments#3553]
### Describe the bug

The issue originally reported in #3526 has been re-uploaded, but it has not been resolved. When testing on version 9.3.5, the quantity issue persists, mainly due to the inability of Chain Mining and TP_DROPS to apply Fortune, resulting in a significant reduction in the quantity of lapis lazuli and redstone.

I tested it and found that there is a significant difference in the quantity of Lapis Lazuli and redstone. 
With just Fortune III, mining three blocks may yield around 36 items, 
but when using Veinminer combined with Fortune III, it only yields around 12 items instead.
And often it is like this.
I know Fortune will have randomness, but this is a noticeable difference. Both are Fortune III, but I can feel the abnormality in the quantity after adding additional enchantments. 

The main issue lies with redstone/lapis lazuli; other resources like diamonds and coal are not affected.

### How to reproduce

Using a Fortune III pickaxe and a Fortune III pickaxe with BREAK_BLOCK @Veinmine attached, 
there is a significant difference in the number of lapis lazuli obtained when mining two lapis lazuli ores.

### "/ae plinfo" link

https://paste.md-5.net/jociwewili

**Comment by Dakotaa** [comment]
It also appears that poisonous potatoes are dropping an insanely high amount

**Comment by ThomasWega** [comment]
I will continue to handle the fortune issue here: https://github.com/GC-spigot/AdvancedEnchantments/issues/3615
