### ISSUE TITLE
TP_DROPS dropping far more carrots and potatoes than it should

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3559]
### Describe the bug

Farming carrots or potatoes with a TP_DROPS enchanted tool drops far too many (double?) items.

### How to reproduce

Enchant a tool with a TP_DROPS enchant.
Farm carrots or potatoes.

### "/ae plinfo" link

https://paste.md-5.net/deyasihehi

**Comment by ThomasWega** [comment]
Should be fixed in the next update :)

**Comment by Dakotaa** [comment]
@ThomasWega it appears that on the latest update, TP_DROPS no longer works at all on carrots/potatoes (items drop normally).

**Comment by ThomasWega** [comment]
@Dakotaa not an issue for me. What server version do you run on? Is it paper/spigot? Can you provide a video please?

**Comment by Dakotaa** [comment]
Paper 1.18.2. Can't get a video at the moment but I will when I can.
