### ISSUE TITLE
Stems count as trees not working.

### ISSUE THREAD

**Issue by ELIAS7281** [GC-spigot/AdvancedEnchantments#3560]
### Describe the bug

I have enabled Stems count as trees in the config and reloaded, restarted, fresh tool and fresh enchantment on the timber enchantment. This has not worked for the effect BREAK_TREE. For crimson and warped.

Advanced Enchantments Version 9.3.4
Server Version 1.20.1

timber:
  display: '%group-color%Timber'
  description: Chance to break a tree in one hit
  applies-to: Axes
  group: UNIQUE
  type: MINING
  applies:
  - ALL_AXE
  levels:
    '1':
      chance: 15
      cooldown: 5
      effects:
      - BREAK_TREE
    '2':
      chance: 35
      cooldown: 5
      effects:
      - BREAK_TREE
    '3':
      chance: 99
      cooldown: 6
      effects:
      - BREAK_TREE

### How to reproduce

Information in Describe the bug:

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ThomasWega** [comment]
Should be fixed in the next update! :)
