### ISSUE TITLE
custommodeldata not working

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#3563]
### Describe the bug

slot-increaser custommodeldata not working

https://github.com/GC-spigot/AdvancedEnchantments/issues/3512 not working

### How to reproduce

slot-increaser:
type: paper
id: 0
custom-model-data: 2103

### Screenshots / Videos

https://i.imgur.com/bl7arcR.png

### "/ae plinfo" link

https://paste.md-5.net/zesutijule

### Server Log

-

**Comment by 21MX** [comment]
I have exactly the same problem

**Comment by austv** [comment]
same problem, **not working for slot increaser and whitescroll**. The rest of the items is working normally

**Comment by GC-spigot** [comment]
All of our current items are being reworked to use the new system we've implemented, items using previous system do not have support for custom model data - that's why there are issues with some of the items. This is being fixed step by step.

**Comment by austv** [comment]
> All of our current items are being reworked to use the new system we've implemented, items using previous system do not have support for custom model data - that's why there are issues with some of the items. This is being fixed step by step.

@GC-spigot I saw that slot increaser got fixed. I just want to you know that whitescroll have the same problem.
