### ISSUE TITLE
Custom success rate desync(?) with random toggled off.

### ISSUE THREAD

**Issue by LambChomps** [GC-spigot/AdvancedEnchantments#3565]
### Describe the bug

Setting enchant chances off true and using a range for success chances causes the custom enchanter to give bugged books. 
In the screenshot below, the success chance is set between 20%-90%, but random enchantment books will give books that visually show from under 20% to above 100% success chance. However, books do not actually inherit the shown success chance. Books with above 100% have still failed or destroyed the item, and using magic dust on these books will seemingly reset the shown success back to what the actual success chance. Causing it to no longer show over 100% if it does. 

Destroy rate has worked as intended though with no similar issues.

From ticket#4454 on Discord.

### How to reproduce

- Set random: false
- Set success: (x)-(y)
- Get book using /ce or /ae giverandombook {name} {rarity}
_(book showing above 100% success chance may vary on the max range set, haven't tested enough)_
- Apply magic dust of any chance to the book

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/84216914/1c15c033-de64-47e4-bb47-1fd7d8857de5)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/84216914/ef819d9d-70d0-424c-8102-c9996b1ddf6c)

### "/ae plinfo" link

https://paste.md-5.net/ezewetesaf

**Comment by GC-spigot** [comment]
Fixed!
