### ISSUE TITLE
player can keep use whitescrolls

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3566]
### Describe the bug

player can keep use whitescrolls (not holy-whitescroll)
video show player keep apply 0% success rate enchant book on tool applied with white-scroll.
i also set "delete: true" in white-scroll.

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/c53fc2f6-9530-4ad1-9dfb-002639121b07

### How to reproduce

1. apply white-scroll
2. give 0% success rate enchanted book.
3. apply on tool.

### "/ae plinfo" link

https://paste.md-5.net/ajujehucer

**Comment by ThomasWega** [comment]
Hey! For this to work, you need to set 

destroy-if-fail:
    enabled: true

in config.yml
