### ISSUE TITLE
Veinminer gives exp for jobs/mcmmo/pyromining

### ISSUE THREAD

**Issue by Truongvv10** [GC-spigot/AdvancedEnchantments#3567]
### Describe the bug

Theres no cooldown after placing an ore, mining and placing the same block will give mcmmo, jobs exp, pyro exp.

This only happens when you have veinminer.

### How to reproduce

Put veinminer on your pickaxe and placing an ore, mining and placing the same block

### "/ae plinfo" link

https://paste.md-5.net/edohucimur

**Comment by ThomasWega** [comment]
should be fixed in the next update
