### ISSUE TITLE
MAJOR ISSUE WITH TELEPATHY ENCHANT

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#3568]
### Describe the bug

Pickaxes with the telepathy enchant can mine ANYWHERE despite the block break event being cancelled

### How to reproduce

Mine with a telepathy enchant pick

EXTRA INFO: This bug came in 9.3.2. In 9.3.1 it is fine

My telepathy enchant:

telepathy:
  display: '&aTelepathy'
  description: "Automatically places blocks broken\nby tools in your inventory."
  applies-to: 'Tools'
  type: 'MINING'
  group: 'UNIQUE'
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
  levels:
    1:
      effects:
        - 'TP_DROPS @Block'

When mining, it seems to call the block break event TWICE because I get the "You can't build here message twice" and then it breaks the block anyway

### "/ae plinfo" link

https://paste.md-5.net/soluxeruhe

**Comment by Dakotaa** [comment]
I too am experiencing this issue. DM'd GC on Discord a few days ago but haven't heard back.

This affects both Towny and Factions, to my knowledge.

**Comment by OrangeCat555** [comment]
This also occurs with the SMELT effect. 

If you have access to a developer it can be cancelled with EffectsActivateEvent, checking the block location from the executiontask's builder. _Meaning this as a temporary measure while it gets fixed._

**Comment by GC-spigot** [comment]
I've tested this with SaberFactions, WorldGuard - can't recreate this. Give an exact plugin and exact version of it so we can test it.

**Comment by JHarris12345** [comment]
I use my own factions plugin. Not sure what plugin the person above me uses. But is there anything in the code for that enchant that would look like it can cause this? As clearly it is being experienced by multiple people

**Comment by GC-spigot** [comment]
We changed event priority for MINING trigger, that is the cause for sure - but it was required for us to be changed to add AureliumSkills support.

**Comment by JHarris12345** [comment]
Realistically, your block break event cant be force breaking blocks on a low priority because of how many protection plugins it will bypass

**Comment by OrangeCat555** [comment]
Also meant specifically for the Towny plugin, we use griefprevention too but there doesn’t seem to be an issue with that.

**Comment by GC-spigot** [comment]
Fixed
