### ISSUE TITLE
Grindstone Bug w/ vanilla enchants

### ISSUE THREAD

**Issue by KokuouGobi** [GC-spigot/AdvancedEnchantments#3569]
### Describe the bug

Grindstone only transfers AE Enchants and NOT Vanilla Enchants.

### How to reproduce

As an Example, I have an enchanted pick with 3 Vanilla enchants (Efficiency IV, Fortune III, and Unbreaking III) and 2 AE's (Telepathy 1, Vein Miner 3). When I try to remove them and put them on a book, it only takes the AE Enchantments and puts them on the book. 

### Screenshots / Videos

![1](https://github.com/GC-spigot/AdvancedEnchantments/assets/88715056/b4e45704-1e58-4533-94b2-a0f6af0c1917)
![2](https://github.com/GC-spigot/AdvancedEnchantments/assets/88715056/967ac04f-2e59-4f31-9577-b4819aab0be1)
![3](https://github.com/GC-spigot/AdvancedEnchantments/assets/88715056/ee0322ca-2bfa-40f9-89aa-ec8bacca292d)

### "/ae plinfo" link

https://paste.md-5.net/mihulonuci

### Server Log

https://mcpaste.io/e68a3ec6a1a8d47e

**Comment by ThomasWega** [comment]
Hey! This issue seems to be caused by a different plugin, as AdvancedEnchantments don't have this feature. Are you sure you are not using any other plugin which allows this behaviour?
