### ISSUE TITLE
Permanent buff/elytra glitch

### ISSUE THREAD

**Issue by ydu80** [GC-spigot/AdvancedEnchantments#357]
It is possible to keep the permanent effect after removing the armor piece by replacing it with elytra. 

![image](https://user-images.githubusercontent.com/47582656/53655493-6bd31280-3c61-11e9-834b-745a4e564af3.png)

1. Equip armor chestplate with a permanent effect boost (health/speed/whatever)
2. Click on elytra in your inventory
3. While elytra is picked, you can click on chestplate & it will be replaced with it while saving the effect

1.12.2, 5.2.8

**Comment by GC-spigot** [comment]
Fixed!
