### ISSUE TITLE
The effect never ends

### ISSUE THREAD

**Issue by studysnack** [GC-spigot/AdvancedEnchantments#3570]
### Describe the bug

The translation might be weird because it's a translator.
Please refer to the video below

### How to reproduce

Please refer to the video below

### Screenshots / Videos

https://cdn.discordapp.com/attachments/832987591795408897/1139535963303968838/2023-08-11_21-28-10.mkv

### "/ae plinfo" link

https://paste.md-5.net/fiqasileke

**Comment by austv** [comment]
This should be fixed in next updated, was I reported in #3550

**Comment by CheeseSand** [comment]
Resolved
