### ISSUE TITLE
VEINMINER breaks with LANDS plugin 

### ISSUE THREAD

**Issue by aaa8881** [GC-spigot/AdvancedEnchantments#3572]
### Describe the bug

veinminer doesn't work when lands plugin exists. 

### How to reproduce

same as above. 

### "/ae plinfo" link

https://paste.md-5.net/qinequtawe

**Comment by aaa8881** [comment]
confiremd it broke after adding LANDS hook , which is 9.2.12

**Comment by GC-spigot** [comment]
Reported in another ticket already
