### ISSUE TITLE
[Supposed bug] Should Trench + BlockTrac result in the trenched blocks being counted into BlockTrac?

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3573]
### Describe the bug

I have come to realize that if you have Trench and BlockTrak on your pickaxe, it won't take the extra blocks that were broken due to Trench into consideration for the BlockTrac.

Now I'm not entirely sure if this is really a bug or if it isn't intended behavior but it would certainly be good to know which one (I tried searching for "Trench BlockTrak" on the GitHub issues to no avail).

### How to reproduce

1. Get a pickaxe
2. Enchant the pickaxe with Trench 9
3. Get a BlockTrak item
4. Put it on the pickaxe
5. Now mine something that breaks extra blocks thanks to trench
6. See how your BlockTrak only goes up by 1 each time

### Screenshots / Videos

(Hopefully not required as it's really easy to reproduce and describe)

### "/ae plinfo" link

https://paste.md-5.net/cutocanepa

### Server Log

https://mcpaste.io/3beb28b4527ab89b

**Comment by ThomasWega** [comment]
Recently the BlockTrak didn't even work with Trench. I remember that I was the one who fixed this issue, and was asking myself the exact same thing 😄. Whether to count only the one block or the extra blocks as well.

Let's get some community feedback on this and see what people prefer. For everyone who wants BlockTrak to track the extra blocks broken with Trench, please leave a comment here :)

**Comment by aXe18** [comment]
Yes absolutely this needs to be a thing !

**Comment by ThomasWega** [comment]
Should be added in the next update! :)
