### ISSUE TITLE
permanent effects bug when clear command is used

### ISSUE THREAD

**Issue by CheeseSand** [GC-spigot/AdvancedEnchantments#3574]
### Describe the bug

The translation might be weird because it's a translator.
Please refer to the video below

### How to reproduce

This happens when you use the clear command to empty the inventory.
Please refer to the video below

### Screenshots / Videos

https://cdn.discordapp.com/attachments/832987591795408897/1140573009577525310/2023-08-14_18-08-46.mkv

### "/ae plinfo" link

https://paste.md-5.net/homarepone

**Comment by GC-spigot** [comment]
Resolved!
