### ISSUE TITLE
AureliumSkills hook conflicts

### ISSUE THREAD

**Issue by anhcraft** [GC-spigot/AdvancedEnchantments#3575]
### Describe the bug

So the issue occurred in my server, where AE, AureliumSkills and our custom plugin (called X) are installed:
(X and AE both hook into AureliumSkills)
Previously, this combination worked well: Our plugin + AureliumSkills + AE v9.3.6
But when testing with AE v9.3.10, I noticed the behaviour was broken.

The issue occurs if the player triggers the bonus effect from the mining skill. X tries to cancel the event but somehow the item still drops. This affects both AE-enchanted items and non-AE-enchanted items.
I believe this issue does not come from X (our plugin) because I have tested several cases so far:

X + AureliumSkills - works as intended
X + AE v9.3.6 - works as intended
X + AE v9.3.10 - works as intended
X + AureliumSkills + AE v9.3.6 - works as intended
X+ AureliumSkills + AE v9.3.10 - broken

### How to reproduce

The issue can reproduce by making a simple plugin that hooks into AureliumSkills and use PlayerLootDropEvent. In the event, tries to cancel it.
- Use `skills skill setlevel <player> mining 100` to maximize mining skill
- Use any pickaxe to break blocks
- Broken behaviour: the item drops

What if in the event, tries to set item stack to air? Exception will occur from AE `java.lang.IllegalArgumentException: Cannot drop air` from `net.advancedplugins.ae.impl.utils.hooks.plugins.AureliumSkillsHook`

Test plugin: https://paste.md-5.net/egebovovat.java

### "/ae plinfo" link

https://paste.md-5.net/ebefokidow

**Comment by anhcraft** [comment]
@GC-spigot How about AE ignore PlayerLootDropEvent if it was cancelled by another plugin?

**Comment by GC-spigot** [comment]
> @GC-spigot How about AE ignore PlayerLootDropEvent if it was cancelled by another plugin? So that works if other plugin uses lower priority to handle before AE

Sure we can add that
