### ISSUE TITLE
Dupe Bug Regarding about "ADD_SOULS"

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3577]
### Describe the bug

Trying to press 1-2 number in the keyboard continuously, while trying to mine a block with Soulminer (with 100% Chance) 

### How to reproduce

soulminer:
  display: '%group-color%Soulminer'
  description: Chance to get souls by mining.
  applies-to: Pickaxe
  type: MINING
  group: FABLED
  applies:
    - ALL_PICKAXE
  levels:
    '1':
      chance: 100
      effects:
        - ADD_SOULS:1
        - PARTICLE:HEART:1:0

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/87959487/661775d2-7657-4f64-89ec-ff9df6643ece

### "/ae plinfo" link

https://paste.md-5.net/uqonizukun

**Comment by NIKIBG12** [comment]
Same here, please fix it or at least answer because this is a serious dupe glitch.

**Comment by GC-spigot** [comment]
Fixed!
