### ISSUE TITLE
Disabled worlds not working

### ISSUE THREAD

**Issue by ctrl-cheeb-del** [GC-spigot/AdvancedEnchantments#3582]
### Describe the bug

When trying to set up an enchantments disabled worlds they never seem to take effect. For example I have my disabled worlds listed keeping case sensitivity in mind for the take off enchantment. However the enchantment seems to still be working regardless.

### How to reproduce

Disabling enchantment particularly take off in a multiverse world

### "/ae plinfo" link

https://paste.md-5.net/kozuqaliqe

**Comment by NIKIBG12** [comment]
Same here with newer versions of the plugin, I see that you are with older version, try updating to 9.3.5 at least.

**Comment by ThomasWega** [comment]
Does this happen in the latest version as well? @ctrl-cheeb-del @NIKIBG12

**Comment by ctrl-cheeb-del** [comment]
sorry for delayed response but yes this bug is still occuring even on the latest version

**Comment by ThomasWega** [comment]
Would you be so kind and send me your config with a video if possible? I've just tried it and it seems to work fine for me. Installed multiverse, and disabled the enchantment in the config for the world.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/8658ca48-dd82-464d-8303-02efc61427a2)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/87251c4c-1f02-439e-ab97-ccccf06a3d47)
https://i.imgur.com/dB6goir.mp4

**Comment by ctrl-cheeb-del** [comment]
ah I think I found my issue, I was attempting to disable the enchant straight from the enchantment.yml file.  For example
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/56118342/1a697fe4-051d-4df5-b31a-a48c836cfb25)

However this would not disable the enchant, and doing it how you did straight from config.yml seemed to work perfectly!

**Comment by ThomasWega** [comment]
Glad to hear that! :)
