### ISSUE TITLE
Slot Increaser NBT Tags

### ISSUE THREAD

**Issue by NIKIBG12** [GC-spigot/AdvancedEnchantments#3583]
### Describe the bug

After updating from 9.3.5 to the latest version Slot Increasers are broken. Until now they were with 5 NBT tags, now they are with 6 and all the old ones are unusable. Also they glow by default even if it's disabled in the config. I tried with default configuration and it's the same. Please fix it because I can't update to the latest version.

### How to reproduce

Updating to the latest version and every version after 9.3.5

### "/ae plinfo" link

https://paste.md-5.net/udorimagoh

**Comment by anhcraft** [comment]
+1 confirm

**Comment by mishonenchev** [comment]
+1 facing the same issue

**Comment by Notobia** [comment]
+1

**Comment by ThomasWega** [comment]
Yep, I fixed it :). Closing the issue now
