### ISSUE TITLE
reapply command doesn't seem to work with non-helmet items on head with effect static & maybe more

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#3584]
### Describe the bug

When using /reapply, nothing is done if something is on your head (items, mob heads, etc.) even if it has nothing to do with that slot. I use reapply a lot since with kitPVP map I'm working on, putting armor on someone via command won't auto apply effects without it.

### How to reproduce

1. use below command
  saturation:
  display: '%group-color%Saturation'
  description: 'Generic-Saturation'
  applies-to: 'Bows'
  group: 'CUSTOM'
  type: 'EFFECT_STATIC'
  applies:
    - 'ALL_ARMOR'
  settings:
    removeable: false
  levels:
    '1':
      chance: 100
      cooldown: 0
      effects:
        - 'POTION:SATURATION:0:200'
2. Put the enchantment on a chestplate
3. Equip something on your head that isn't a piece of armor (such as wither skull for example)
4. Clear all effects to make sure you don't have any
5. Run /reapply on yourself and it won't work

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/1pDOdHxoDBdJpe/d133797APbSZ?invite=cr-MSx0TkMsMTc4MDQ0NTYyLA

### "/ae plinfo" link

https://paste.md-5.net/imodonepag

**Comment by GC-spigot** [comment]
Fixed!
