### ISSUE TITLE
Effect and MMOItems durability issue

### ISSUE THREAD

**Issue by YKDZ** [GC-spigot/AdvancedEnchantments#3585]
### Describe the bug

There are some effects that break the durability from MMOItems, deducting only the vanilla, such as SMELT and BREAK_BLOCK @Trench{r=3}:
![Snipaste_2023-08-19_13-05-34](https://github.com/GC-spigot/AdvancedEnchantments/assets/69898831/9c538ce2-5e6d-4cde-a015-fd2856bd0841)
Removing the corresponding enchantment solves the problem.

### How to reproduce

Make an enchantment with these effect.
Make an MMOItems item with custom durability and durability bar.
Apply the enchantment and use the item. 

### "/ae plinfo" link

https://paste.md-5.net/olitiyoxus

**Comment by ThomasWega** [comment]
could you please provide us with your configuration, or at least a video please?

**Comment by ThomasWega** [comment]
also make sure to update your plugin before that please

**Comment by ThomasWega** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/issues/3534
