### ISSUE TITLE
Bait enchantment

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3586]
### Describe the bug

Bait enchantment doesn't work. I've got same amount of loot as without enchant.

### How to reproduce

1. Catch fish with fishing rod that has bait enchantment

### "/ae plinfo" link

https://paste.md-5.net/buyugozone

**Comment by ThomasWega** [comment]
Already issued a fix for this. It should be fixed in the next version :)
