### ISSUE TITLE
Many enchantment effects have failed

### ISSUE THREAD

**Issue by ALMikey** [GC-spigot/AdvancedEnchantments#3587]
### Describe the bug

I don't know what I'm doing. My server's AdvancedEnchantments plugin has many enchanting effects that have failed. The version is AdvancedEnchantments 9.3.11.
There is no error prompt output in the background.

### How to reproduce

null

### Screenshots / Videos

null

### "/ae plinfo" link

https://paste.md-5.net/beyekufozi

### Server Log

https://mclo.gs/i4zSAlv

**Comment by GC-spigot** [comment]
You are using old enchantment format with new reworked abilities. Regenerate your enchantments.yml or visit wiki to see how new enchantments are formated.

Biggest issues will be AOE enchantments for you, since everything else is automatically converted
