### ISSUE TITLE
CustomCrafting Support

### ISSUE THREAD

**Issue by AppeazeTheCheese** [GC-spigot/AdvancedEnchantments#3588]
### Describe the bug

When putting on/removing armor with enchantments that apply effects, in certain situations, the effects are not applied/removed respectively.

### How to reproduce

I am running on the latest version of AE at the time of writing this (9.3.12) and the latest Paper server (1.20.1 build 133). The specific enchantment I used to test this was Glowing.

When taking an item on/off, if you:

- Shift-click the item to put it on: The status effect will be applied normally
- Shift-click the item to take it off: The status effect will be removed normally
- Click the item to put it on: The status effect will be removed
- Click the item to take it off: The status effect will be applied

It also acts strangely if you use the number keys to try and take off the armor. The effect will be removed if, and only if, there is an item in the slot associated with the key pressed. If the slot is empty and the armor piece does get removed, the effect is not removed.

After the effects are applied, they persist after the player leaves and re-joins, regardless of whether or not the armor piece is being worn.

### Screenshots / Videos

https://streamable.com/sevo87

### "/ae plinfo" link

https://paste.md-5.net/bigilipopa

### Server Log

N/A

**Comment by ItsTrixinity** [comment]
I had the same issues as well, I believe WolfyUtilities/Custom Crafting is conflicting with AE, hopefully they will be able to fix the interaction :(

**Comment by Yukylyu** [comment]
same :( CustomCrafting ...

**Comment by ThomasWega** [comment]
can you please provide a video? I will try to see if I can fix it by hooking to the plugin's API

**Comment by AppeazeTheCheese** [comment]
There is a video in the issue already.

**Comment by ThomasWega** [comment]
> There is a video in the issue already @ThomasWega. I fail to see what critical info is lacking.

My bad, didn't see it. Will see what I can do

**Comment by ThomasWega** [comment]
Can you try asking the author if he cannot fix this issue on his side?

**Comment by AppeazeTheCheese** [comment]
I could probably do that. Any insight as to what might be going on that I can pass on to them?

**Comment by ThomasWega** [comment]
<img width="761" alt="image" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/50d765f7-2916-40b0-bf8a-4a44f2ab58b2">
Doesn't seem like our issue after all
