### ISSUE TITLE
Duplication of Mob Heads Using "Smelting" Enchantment

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#3590]
### Describe the bug

The "smelting" enchantment on a pickaxe allows players to duplicate mob heads by breaking them. This process works only with mob heads that have been obtained in survival mode, not those taken from creative mode.

I am attaching a video showing this duplication process. This can cause unwanted behavior in the game and disrupt the balance.

### How to reproduce

1. Obtain a mob head in survival mode (not in creative).
2. Enchant a pickaxe with the "smelting" enchantment.
3. Break the obtained mob head using the enchanted pickaxe.
4. Notice that the mob head is duplicated instead of being normally destroyed.

### Screenshots / Videos

https://www.youtube.com/watch?v=59KoG6Ociho

### "/ae plinfo" link

https://paste.md-5.net/ugupufewel

**Comment by ThomasWega** [comment]
Make sure you are using the latest version. We have tried this ourself and were not able to replicate this issue with smelting enchantment. It might be caused by a different plugin. Feel free to open a new issue if this persists
