### ISSUE TITLE
Reach Not Working Properly

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#3591]
### Describe the bug

Reach Now Works Partially, But Is Too Buggy To Use Properly, Since For Example, It Doesn't Work Half The Time (At Least When Testing Against Another Player) Will Provide Video Proof If Needed, But Seems Even After The Fix, It's Still Too Buggy

### How to reproduce

swing:
  display: '%group-color%Swing'
  description: 'Swing'
  applies-to: 'Shovels'
  group: 'CUSTOM'
  type: 'SWING'
  applies:
    - 'ALL_SHOVEL'
  settings:
    removeable: false
  levels:
    '1':
      chance: 100
      cooldown: 0
      effects:
        - 'REACH:6'

### "/ae plinfo" link

https://paste.md-5.net/avibuwaxaz

**Comment by GC-spigot** [comment]
With the previous report I was debating on removing this effect completely. There’s no good way to add this for entities, the current method it uses is basically the only method. I’ll see what we can do but it’s likely that it the way it is now
