### ISSUE TITLE
Fish cannot be obtained by fishing in AdvancedEnchantments v9.3.12.

### ISSUE THREAD

**Issue by KNzE07** [GC-spigot/AdvancedEnchantments#3592]
### Describe the bug

I tested fishing in AE version 9.2.7 and found that it can get fish by fishing.
But when I update Advanced Enchantments It is the latest version or it is 9.3.12.
Found that it was impossible to get fish by fishing.
And I think it has to do with the Aurelium Skills plugin.
Because I tried fishing at level 1 and level 97 was the max level.
Found that level 1 fish can be obtained by fishing.
And found that level 97 did not get any fish from fishing. and it looks like it's colliding with the air.
Finally, I have posted 2 videos for you to understand and visualize.

### How to reproduce

Fixed it to be able to fish and get fish.

### Screenshots / Videos

first video
https://youtu.be/mx0yKoqmhmw

second video
https://youtu.be/UM3uZUlfZnU

### "/ae plinfo" link

https://paste.md-5.net/qesikovabi

**Comment by KNzE07** [comment]
Please reply to let us know that you are aware of this issue.

**Comment by aXe18** [comment]
@KNzE07 Yes devs are aware of the issue :)

**Comment by KNzE07** [comment]
9.3.15 Changelog
Changes:

- Fixed CATCH_FISH trigger with MORE_DROPS

Did you fix it?
I tested it and still can't get fish from fishing like before update 9.3.15

**Comment by ThomasWega** [comment]
No, that fix was issued for MORE_DROPS not working with the specific trigger. We will get to your issue asap. We have lot of other issues as you might be able see :)

**Comment by ThomasWega** [comment]
Should be fixed in the next version. Actually, the item doesn't collide with AIR, but it was rather spawned there by us.
