### ISSUE TITLE
Slot increaser can be incorrectly used using offhand

### ISSUE THREAD

**Issue by anhcraft** [GC-spigot/AdvancedEnchantments#3593]
### Describe the bug

If the slot increaser is set to eye of ender (by default), the player can switch the item to their offhand, and right-click to use the item to find a stronghold. This causes confusion to the player.
I have not tested other items yet, but AE is missing a check for off-hand.

### How to reproduce

1. Get the slot increaser
2. Swap the item to offhand
3. Right click to throw it

### "/ae plinfo" link

https://paste.md-5.net/osodejeruq

**Comment by ThomasWega** [comment]
Will be fixed in the next update :)
