### ISSUE TITLE
Wrong format of Nullify enchantment.

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#3594]
### Describe the bug

`REMOVE_SOULS` of Nully enchantment in default enchantments.yml is invalid. The effect of REMOVE_SOULS will not work properly and it doesn't say anything in the console or error message.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63577950/8b544de1-c6f5-493c-8a4c-aa698af6b7d1)

It should be like this like other enchantments that has `REMOVE_SOULS`
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63577950/902c23e1-f9a0-48aa-92bc-244cfc3fd690)

### How to reproduce

Install latest version of the plugin.

### "/ae plinfo" link

N/A

**Comment by ThomasWega** [comment]
Thanks. Will be fixed in the next update :)
