### ISSUE TITLE
Conflict with Oraxen items

### ISSUE THREAD

**Issue by Toshiii35** [GC-spigot/AdvancedEnchantments#3595]
### Describe the bug

From the title itself, custom enchants on items from oraxen oesnt get detected when dropped and then picked up, I tried removing the enchants on the custom item  using blackscroll but it says that there are no enchants in it when the enchant name shows. 

### How to reproduce

Have an item with Oraxen, enchant with it any custom enchant and drop it on the ground and then pick it up. Try removing the enchant with a blackscroll and it wont get detected.  

### Screenshots / Videos

https://www.xbox.com/en-US/play/media/9JLT76568N

### "/ae plinfo" link

https://paste.md-5.net/wixacasabu

**Comment by Toshiii35** [comment]
https://github.com/oraxen/oraxen/issues/1034 here's an issue another person with the same problem opened on Oraxen github

**Comment by ThomasWega** [comment]
Seems like oraxen fixed it. Check last comments on the https://github.com/oraxen/oraxen/issues/1034
