### ISSUE TITLE
Crossbows Ignore Defensive Triggers From Players

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#3596]
### Describe the bug

Seems that using a crossbow ignores any kind of defense, and doesn't trigger it, but bows & tridents do which is quite a big deal, I know it's DEFENSE_PROJECTILE, but just used all of them for fun, and it seems everything else works except for crossbow shots. Use the below enchant to test it, I've tested this with mobs such as a pillager, and it seems to work, so it's only a bug with players.

### How to reproduce

madman:
  display: '%group-color%MadMan'
  description: 'Mad-Man'
  applies-to: 'Armor'
  group: 'CUSTOM'
  type: 'DEFENSE;DEFENSE_MOB;DEFENSE_PROJECTILE;DEFENSE_MOB_PROJECTILE;FIRE;FALL_DAMAGE'
  applies:
    - 'ALL_ARMOR'
  settings:
    removeable: false
  levels:
    '1':
      chance: 100
      cooldown: 0
      effects:
        - 'DOUBLE_DAMAGE @Victim'

### "/ae plinfo" link

https://paste.md-5.net/kuleyufufo

**Comment by ThomasWega** [comment]
Should be fixed in the next update :)
