### ISSUE TITLE
TP_DROPS @Block does not work with beds

### ISSUE THREAD

**Issue by alechretien16** [GC-spigot/AdvancedEnchantments#3598]
### Describe the bug

I have an enchantment called telekinesis, when breaking the items they go directly to the inventory, however when breaking a bed it doesn't go to the inventory nor does it fall to the ground, it just disappears.

### How to reproduce

With the following incantation break a bed.

telequinesis:
  display: '%group-color%Telequinesis'
  description: Al romper ítems van directo al inventario.
  applies-to: Herramientas
  type: MINING
  group: LEGENDARIO
  applies:
    - ALL_TOOLS
  levels:
    '1':
      effects:
        - TP_DROPS @Block 

### "/ae plinfo" link

https://paste.md-5.net/gogekavola

**Comment by ThomasWega** [comment]
Should be fixed in the next update
