### ISSUE TITLE
grindstones-remove-custom-enchants does not give experience

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#3601]
### Describe the bug

As described in the title, when you remove custom enchantments with a grindstone, you will receive no experience points.

Additionally, the result slot of the grindstone still has the item with the enchantment name in the lore, which is quite unintuitive especially for newer players coming from vanilla. 
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/17891302/3db891a7-15a0-403f-a38c-f205ff1dd803)

### How to reproduce

1. Enchant any item with any custom enchantment
2. Place the item in a grindstone. You will observe that the enchantment is still in the lore of the item in the output slot.
3. Take the item from the output slot. The enchantment will be removed correctly, but no experience is given.

### "/ae plinfo" link

https://paste.md-5.net/janivatoja

**Comment by ThomasWega** [comment]
Hello. We tested this and receive XP from custom enchants. Make sure you have the latest version, and if the issue still persists, please send a video proof
