### ISSUE TITLE
Advice on NBTTag

### ISSUE THREAD

**Issue by DawnXinyu** [GC-spigot/AdvancedEnchantments#3602]
### Describe the bug

Hello, Excuse me, I would like to know if there is any plan to update NBTTag in the future?
Now all NBT entries are separate, which is very unfriendly to some item library plugins that refresh item NBT, such as mmoitems and NeigeItems (this is a plugin from China, the author is named Neige).
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/28a70863-dcab-49ee-ad84-89e35abfdc1d)
I wonder if it would be possible to add this format to enchanted NBT entries? It can be used as an additional option, so that other plugins only need to detect and keep "ae_enchantment" when they want to keep the enchanted NBT, and then they can keep all the NBTTags below
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/f6d20de1-e31f-4f83-9bcc-b3527860e811)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/c8a382d9-3a84-434a-be45-edc55e50e59f)
If you update this format of NBTTag (you can let users choose which format of NBT to use in the configuration), it will greatly facilitate the compatibility of other plug-ins with AE, thank you
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/cfc578cb-270a-4dd7-80d4-b3118c727a1c)

### How to reproduce

content above

### "/ae plinfo" link

content above

**Comment by GC-spigot** [comment]
We can’t change the format, thousands of servers are using this format for custom enchants with AE. We’d have to redo the entire plugin for this unfortunately
