### ISSUE TITLE
Feature Request - Add formatting numbers

### ISSUE THREAD

**Issue by srrawr11** [GC-spigot/AdvancedEnchantments#3603]
### Describe the bug

**Feature Request**

Convert > Sharpness 30 instead of Sharpness enchantment.level.30
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/73607495/c65c7dad-e161-4c6a-b369-d6edb506b9db)

### How to reproduce

N/A

### "/ae plinfo" link

N/A

### Server Log

N/A

**Comment by GC-spigot** [comment]
We wont be able to add this, this requires protocollib which we do not use for our plugin and dont want to require a dependency.
