### ISSUE TITLE
Throwing An Egg Removes the Effects from boots

### ISSUE THREAD

**Issue by evnrca** [GC-spigot/AdvancedEnchantments#3606]
### Describe the bug

When throwing an egg. the effects on the boots are being removed.

### How to reproduce

Equip a boot with ae enchants. Especially Gears Then Throw an egg. it would remove the Gears Effect. IDK if it removes other effects other than gears

Please see video below

### Screenshots / Videos

https://drive.google.com/file/d/1bH7ChOhoY2PZl8-E-hlt5b3YkCVxXx8r/view?usp=drive_link

### "/ae plinfo" link

https://paste.md-5.net/gihajojixo

**Comment by GC-spigot** [comment]
I can't reproduce this on same version of Minecraft and AdvancedEnchantments - https://gyazo.com/eff61bc3a724e059e77a8027aee477e8

Would it be possible any of your other plugins causing this?

**Comment by evnrca** [comment]
> I can't reproduce this on same version of Minecraft and AdvancedEnchantments - https://gyazo.com/eff61bc3a724e059e77a8027aee477e8
> 
> Would it be possible any of your other plugins causing this?

Okay thanks. will try to figure this out.
