### ISSUE TITLE
Telepathy enchant with Towny

### ISSUE THREAD

**Issue by RageOfFire** [GC-spigot/AdvancedEnchantments#3607]
### Describe the bug

Telepathy enchant can break block from another towny

### How to reproduce

My player from server report about new dupe glitch when they have Telepathy enchant they can block [Towny](https://www.spigotmc.org/resources/towny-advanced.72694/) block (from another town)

### Screenshots / Videos

https://vimeo.com/857520662?share=copy

### "/ae plinfo" link

https://paste.md-5.net/wofuhasagu

### Server Log

https://mcpaste.io/f7ae4629393fe359

**Comment by ThomasWega** [comment]
It does seem like your server is pretty laggy. I tried this myself and was not able to replicate this issue. If it still persists, please try with only Towny and AE on a fresh server with latest plugin version. Also make sure your tps is good. Feel free to create a new github issue in case this still persists
