### ISSUE TITLE
You cannot apply a randomizer to this! (bug?)

### ISSUE THREAD

**Issue by moonies44** [GC-spigot/AdvancedEnchantments#3609]
### Describe the bug

Hello.
So on nearly all my books (some work, some dont randomly) i get the error "You cannot apply a randomizer to this!"

I have both these options set to false
limit-applying-per-group: false
limit-applying-per-group: false

but even after, i get you cannot apply.

### How to reproduce

apply a randomizer to any book  

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/66435479/ce673bc7-53a8-4ce9-a225-fab0188d85da

https://github.com/GC-spigot/AdvancedEnchantments/assets/66435479/bf7c6cd9-c89d-456b-9ac0-d6a0e13c1087

### "/ae plinfo" link

https://paste.md-5.net/omezipaxom

### Server Log

https://mclo.gs/BBWyKm3

**Comment by ThomasWega** [comment]
Hey! Make sure to update your plugin. It works just fine for us, and we tried on multiple servers. If the issues still persists, try to test it on a fresh server with only latest AE and no other plugins. If it still persists even after that, please record a video and create a new github issue. However I doubt that will be needed
