### ISSUE TITLE
[Feature Request] Speed_Percentage effect

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#3611]
### Describe the bug

I want a feature to modify the player speed without giving them a speed effect.
SPEED_PERCENT
or better yet
MULTIPLY_SPEED
or something like that which would be an effect static so they put it on to get increased speed.

### How to reproduce

feature request

### "/ae plinfo" link

feature request

**Comment by aXe18** [comment]
+1

**Comment by ThomasWega** [comment]
I've added few effects for you.

WALK_SPEED:<SPEED>:[TICKS]
ADD_WALK_SPEED:<SPEED>:[TICKS]
FLY_SPEED:<SPEED>:[TICKS]
ADD_FLY_SPEED:<SPEED>:[TICKS]

should be available next update
