### ISSUE TITLE
Nether gold ore drops nuggets instead of an ingot with autosmelt

### ISSUE THREAD

**Issue by Jordyn114** [GC-spigot/AdvancedEnchantments#3613]
### Describe the bug

When you smelt nether gold ore in a furnace, it smelts 1 gold ingot. When you use autosmelt, it instead drops gold nuggets. (On a side note, these nuggets seem to be unaffected by fortune. I think this should stay, as smelting nether gold ore in a furnace only gives 1 ingot regardless). It should be noted that my server has McMMO, and although I don't think this issue stems from their interaction, it's worth paying attention to.

### How to reproduce

Mine nether gold ore with an autosmelt pickaxe and it drops gold nuggets. Smelt it in a furnace and it gives 1 gold ingot.

### Screenshots / Videos

https://imgur.com/a/oAJXhAT

### "/ae plinfo" link

https://paste.md-5.net/arucutadaq

### Server Log

https://mcpaste.io/3214191a67c5e95a

**Comment by ThomasWega** [comment]
Should be fixed in the next update! :)
