### ISSUE TITLE
Holy White Scroll randomly activates, although it's disabled on the world

### ISSUE THREAD

**Issue by AlexanderOFGR** [GC-spigot/AdvancedEnchantments#3614]
### Describe the bug

I am having issues, where the Holy White Scroll is randomly activated, although I have disabled it in all worlds via the plugin's config.

### How to reproduce

Disable the Holy White Scroll via the config

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/1qzUdiCGSg0W-2/d13378ebaPUw?invite=cr-MSxKemMsNzA1MTM3NjQs
https://medal.tv/games/minecraft/clips/1qzP3nNjsc5-hq/d1337Y8c4IWU?invite=cr-MSxMVzEsNzA1MTM3NjQs

### "/ae plinfo" link

https://paste.md-5.net/ayahikuwew

**Comment by ThomasWega** [comment]
I was not able to replicate this at all. Maybe a different plugin causes it? Make sure to try with fresh server with only latest AE.

**Comment by ThomasWega** [comment]
Truly wasn't able to replicate this. Tried multiple times. If this issues still persists, make sure to create a new fresh server with only latest AE as a plugin and test it there. Then create a new github issue with these details.
