### ISSUE TITLE
break cooper_ore with VEIN_MINE applied, fortune enchant is not applied.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3615]
### Describe the bug

copper ore
fortune3 = 45
fortune3+VEIN_MINE = 23

gold ore
fortune3 = 15
fortune3+VEIN_MINE = 13

### How to reproduce

1. make 2 pickaxe ( fortune / fortune + VEIN_MINE)
2. picking copper ore

### "/ae plinfo" link

https://paste.md-5.net/ovatehugaj

**Comment by Ecilpse** [comment]
> ### Describe the bug
> copper ore fortune3 = 45 fortune3+VEIN_MINE = 23
> 
> gold ore fortune3 = 15 fortune3+VEIN_MINE = 13
> 
> ### How to reproduce
> 1. make 2 pickaxe ( fortune / fortune + VEIN_MINE)
> 2. picking copper ore
> 
> ### Screenshots / Videos
> _No response_
> 
> ### "/ae plinfo" link
> https://paste.md-5.net/ovatehugaj
> 
> ### Server Log
> _No response_

also redstone, lapis ore does.
There seems to be this problems with ore blocks that drops several items at once.

**Comment by ThomasWega** [comment]
Indeed, there is an issue. I will try taking a look at it :)

**Comment by ThomasWega** [comment]
Should be fixed in the next update
