### ISSUE TITLE
Broken Equipped with CustomArmor and CustomWeapon Sets

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3616]
### Describe the bug

The advanced sets only works if there's an custom enchantment in the set. In the old versions of the AE, this does not happen as it should be.

It works with/without the custom enchantment.

### How to reproduce

1.) remove custom enchantment in the specific file on the asets.
2.) Leave at least one enchantment in specific armor on the file.
3.) then try to wear the armor from have enchantment to no enchantment armor (as it will not work)
4.) try wearing the armor from no enchantment armor to have an enchantment armor (It will work)

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/87959487/2a8a90d1-d982-4764-9e74-410dc1d42f11

### "/ae plinfo" link

https://paste.md-5.net/jumiqofayo

**Comment by GC-spigot** [comment]
Resolved
