### ISSUE TITLE
Enchanting an  textured oraxen leather armor resets and remove old enchantes

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#3617]
### Describe the bug

When you enchant an armor that is textured with oraxen it loses its old enchants, and it may be conflicting with oraxen as oraxen uses this code to update items

``// Add all enchantments from oldItem and add all from newItem aslong as it is not the same Enchantments
for (Map.Entry<Enchantment, Integer> entry : oldMeta.getEnchants().entrySet())
    itemMeta.addEnchant(entry.getKey(), entry.getValue(), true);
for (Map.Entry<Enchantment, Integer> entry : newMeta.getEnchants().entrySet().stream().filter(e -> !oldMeta.getEnchants().containsKey(e.getKey())).toList())
    itemMeta.addEnchant(entry.getKey(), entry.getValue(), true);``

### How to reproduce

enchant an already enchanted oraxen leather armor with new enchants and it will remove old enchants.

### "/ae plinfo" link

https://paste.md-5.net/ilopiduqaj

**Comment by Toshiii35** [comment]
bump, it happens to every oraxen item, not just leather armor

**Comment by Toshiii35** [comment]
https://github.com/oraxen/oraxen/issues/1034#issuecomment-1708252145 more details here
