### ISSUE TITLE
BREAK_TREE does not break entire tree (jungle, acacia, dark forest_

### ISSUE THREAD

**Issue by mybvbbles** [GC-spigot/AdvancedEnchantments#3618]
### Describe the bug

Trees that branch out/does not grow in a straight-line upwards won't get fully destroyed.

### How to reproduce

enchant:
timber:
  display: "&7Timber"
  description: "Chance to break a tree in one hit"
  applies-to: "Axes"
  group: "ULTIMATE"
  type: "MINING"
  applies:
    - "ALL_AXE"
  levels:
    1:
      chance: 15
      cooldown: 5
      effects:
        - "BREAK_TREE @Block"
        
        With enchantment equipped, break either a Spruce tree, Acacia tree, or Dark Oak Tree

### "/ae plinfo" link

https://paste.md-5.net/ihizinaboc

**Comment by aXe18** [comment]
@mybvbbles Thats how it is, its really hard to make it break trees with many branches etc
This has been on discussion before and there is not really much what can be done
