### ISSUE TITLE
The "trench enchant" will trigger the "customdrop" twice

### ISSUE THREAD

**Issue by HOWTOCHICKEN** [GC-spigot/AdvancedEnchantments#3619]
### Describe the bug

I've set up the "CustomDrop" plugin to have a 100% chance of dropping a treasure chest when digging stone. However, when I use a pickaxe with the "Trench" enchantment and break 18 stone blocks at once, it drops 34 treasure chests instead of the expected 18. I've noticed that the number 34 represents the additional drops from 17 stone blocks, which were destroyed due to the "Trench" enchantment. Therefore, I believe this extra triggering is caused by the "Trench" enchantment. Please fix this issue.

The CustomDrop plugin I'm using can be found here: https://www.spigotmc.org/resources/%E2%AD%90-custom-drops-editor-1-16-1-20-easy-to-use-hard-not-to-want-%E2%AD%90.100748/

### How to reproduce

1. Using a pickaxe with the Trench enchantment to mine 18 stone blocks at once.
2. Dropped 34 treasure chests from the plugin "customdrop," but it should drop 18 instead.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/69415795/315eaff7-5586-46b6-951a-5756b8d76785

### "/ae plinfo" link

https://paste.md-5.net/ulihusekog

### Server Log

https://mcpaste.io/512bc561f8a65132

**Comment by GC-spigot** [comment]
Hi! That plugin needs to ignore cancelled block breaks, since that's what happens with TRENCH - it calls it's own block break events to add support for other plugins, but they need to be able to handle cancelled block breaks.
