### ISSUE TITLE
Problem with stacked blocks from SuperiorSkyblock 2

### ISSUE THREAD

**Issue by LO383krystianch** [GC-spigot/AdvancedEnchantments#3620]
### Describe the bug

if you have a pickaxe with custom enchant and you will destroy stacked blocks you will get random 
quantity of blocks, no errors in console

### How to reproduce

https://github.com/GC-spigot/AdvancedEnchantments/assets/82154782/c5620f1b-8e0f-47ec-a66f-fe8053732994

### "/ae plinfo" link

https://paste.md-5.net/piyabenira

**Comment by ThomasWega** [comment]
The video you provided is corrupt. Please reupload it

**Comment by LO383krystianch** [comment]
https://www.youtube.com/watch?v=6EuccvZnR0w

**Comment by ThomasWega** [comment]
will be fixed in the next update :)
