### ISSUE TITLE
Dropping an item from a grindstone keeps the custom enchant

### ISSUE THREAD

**Issue by renndrew** [GC-spigot/AdvancedEnchantments#3621]
### Describe the bug

When you're disenchanting an item in a grindstone and you drop the item output out of the grindstone GUI it will keep the custom enchants, but remove vanilla enchants.

### How to reproduce

Put an enchanted item in a grindstone.
Left click the item output slot.
Click off the GUI to drop it out.
Pick it back up and it's got all vanilla enchants removed, but not custom ones.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/883816441323864134/1146560767072665691/Untitled_video_-_Made_with_Clipchamp.mp4

### "/ae plinfo" link

https://paste.md-5.net/wugopituce

**Comment by ThomasWega** [comment]
Should be fixed in the next update
