### ISSUE TITLE
Trench and vulcan anticheat kicks you at max level.

### ISSUE THREAD

**Issue by sennby** [GC-spigot/AdvancedEnchantments#3622]
### Describe the bug

When mining with max lvl trench, vulcan will kick a player for hacks.

### How to reproduce

Mine amethyst for example with trench and vulcan will kick a player for cheats.

### "/ae plinfo" link

https://paste.md-5.net/secuyuzoza

**Comment by ThomasWega** [comment]
Hey! I've just tried with default Vulcan config and was not able to replicate this. Did you modify the Vulcan config by any chance? Do you also mind sending a video?
