### ISSUE TITLE
BlockTrack issue

### ISSUE THREAD

**Issue by plumpkiwi** [GC-spigot/AdvancedEnchantments#3623]
### Describe the bug

blocktrack no longer tracks blocks broken while mob trackers still works, config files haven't been changed

### How to reproduce

not sure how to reproduce as I don't know what triggered it.

### "/ae plinfo" link

/ae plinfo skipplugins

**Comment by ThomasWega** [comment]
Hey. You will need to figure out how to reproduce this issue before we are actually able to investigate it
