### ISSUE TITLE
[Feature Request] Each level different description

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#3624]
### Describe the bug

per level descriptions

### How to reproduce

the players on my server want the enchants to have per level descriptions so they can know the difference between each one. On hypixel it has per level desc and this has been a requested feature before. Another enchantment plugin on spigot has per level descriptions with placeholders only and i think the development team could annihilate the competition if they implemented this feature in a meaningful way imho. It shouldn't be too difficult.

### "/ae plinfo" link

feature request

### Server Log

feature request

**Comment by ThomasWega** [comment]
Working on it! Should be out soon :)
