### ISSUE TITLE
API integration - entity metadata

### ISSUE THREAD

**Issue by kangarko** [GC-spigot/AdvancedEnchantments#3626]
### Describe the bug

Hey,

One of our customers need integrating with our Boss plugin. Do entities spawned under your plugin (such as Guardian-spawned Golemns) have a custom metadata so I can ignore them? 

Thx.

### How to reproduce

N/A

### "/ae plinfo" link

N/A

**Comment by ThomasWega** [comment]
Hey! In the next update, we will mark the mobs spawned by us with fixed metadata value "ae-entity"

**Comment by kangarko** [comment]
Love it, thanks so much!
