### ISSUE TITLE
Holy White Scroll deletes items

### ISSUE THREAD

**Issue by Xyaafol** [GC-spigot/AdvancedEnchantments#3628]
### Describe the bug

When the Holy White Scroll is applied to any item, it is deleted upon death and not given to the player when they respawn. Testing older versions shows that this was fine in 9.3.14 but has been an issue in 9.3.15 and 9.3.16

### How to reproduce

In version 9.3.15 or 9.3.16 apply an item with the Holy White Scroll, then die - the item will be deleted not in your inventory and not dropped on the floor. Test in version 9.3.14 to see the intended effect of respawning with the item in your inventory.

### "/ae plinfo" link

https://paste.md-5.net/udequduyom

**Comment by ThomasWega** [comment]
Hey! I was not able to replicate this issue. You most likely have conflict with other plugin. If you try it with AE as the only plugin on the server, does that same happen for you? Are you please able to provide video?

**Comment by Xyaafol** [comment]
Please see video: https://youtu.be/s1WWoR09tOM

Tested on a completely fresh server, no other plugins, new install folder of AE, latest AE and Paper version

**Comment by Xyaafol** [comment]
Not sure how I didn't notice before, but there is an error showing in console whenever this happens
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/64779104/387435fa-3d48-40b8-932a-e8dcab9a9981)

Just that one line repeating more than 100 times, only when a player is killed with a holy white scroll applied to an item.

**Comment by ThomasWega** [comment]
Will be fixed in the next update
