### ISSUE TITLE
Mining Enchant Duplicate Bug

### ISSUE THREAD

**Issue by madebygood** [GC-spigot/AdvancedEnchantments#3633]
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/43653581/0d2a8071-55de-48f9-a7eb-98a6dbedc578)

### How to reproduce

1) Mining Enchant with 1.19.2

2) Skript coding:
on break:
 cancel event

3) duplicate item

### Screenshots / Videos

https://youtu.be/a2W9XCir3mM?si=F_xKt8f3TKE99q4j

### "/ae plinfo" link

https://paste.md-5.net/epokihatob

**Comment by ThomasWega** [comment]
Change your priority level :)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/d7f335dc-62be-4bb2-ba34-2ce5d9d217bb)

**Comment by madebygood** [comment]
This bug didn't exist before updating advancedenchantments .

This bug occurred after upgrading to the latest version.

Then, it's your plugin's problem, not the other plugin's problem, and you need to fix it.

Don't force discomfort on your users.

There are too many bugs and inconveniences in this plugin these days.

Rather than focusing on adding new features, please do your best to resolve these inconveniences.

**Comment by madebygood** [comment]
> Change your priority level :)
> 
> ![image](https://user-images.githubusercontent.com/82312488/266714347-d7f335dc-62be-4bb2-ba34-2ce5d9d217bb.png)

This bug didn't exist before updating advancedenchantments .

This bug occurred after upgrading to the latest version.

Then, it's your plugin's problem, not the other plugin's problem, and you need to fix it.

Don't force discomfort on your users.

There are too many bugs and inconveniences in this plugin these days.

Rather than focusing on adding new features, please do your best to resolve these inconveniences.
