### ISSUE TITLE
Armorset Bonuses aren't working

### ISSUE THREAD

**Issue by ShikuretSensei** [GC-spigot/AdvancedEnchantments#3634]
### Describe the bug

All armorsets aren't working and I have a video proof. Let's take KOTH Bonus is not working that negates supposedly 100% of the fall damage.  

Listed Armorsets that aren't working:
DimensionalTraveller
KOTH
Phantom
Ranger
Supreme
Yeti
Yijki

I have tested it but it doesn't work. I don't know why or how but the config files are as is. I didn't reconfigure anything.

### How to reproduce

I do not know how to reproduce it, It is as is in the config files of the plugin.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/39545120/aa5198e3-0b5c-4b7c-b7fb-86d20001bb2c

### "/ae plinfo" link

https://paste.md-5.net/omoniwiwez

**Comment by KingCueio** [comment]
@ShikuretSensei, You should try to update your AdvancedEnchantment to the latest update. It seems you're using 9.3.12, as the ArmorSet's Ability got fix around 9.3.13

**Comment by GC-spigot** [comment]
That's just an old format, will be updated next update!
