### ISSUE TITLE
Mining Duplication Bug *URGENT*

### ISSUE THREAD

**Issue by sennby** [GC-spigot/AdvancedEnchantments#3635]
### Describe the bug

https://discord.com/channels/376425582139015168/1148682408296730724

Place ancient debris
mine it
Seems it is able to dupe under certain conditions
Trying to figure out exactly how
But i know its possible,

Player placed 14 ancient debris, mined it and the pickaxe had telepathy, ended up with more than 14 ancient debris.
Used a normal pickaxe, none duped.
Trying to figure out why,. I have aureliumskills, and jobsreborn, but it seems to only happen with telepathy in my testing so far.
okay maybe its with trench as well
I just placed 5, and mined them, i have 6 now.
these are the enchants.
Image
yes trench for sure
Its not jobs, disabled teh job miner, and still happening.
100% theres a dupe with reforged,telepathy, and trench. In one of those enchants. ill test further
senby8 [aristant] — Today at 2:21 PM
telepathy, trench. narrowed down to
trench alone its not happening
yes, trench alone doesnt do it, and telepathy alone doesnt do it
pair the two together, it does it.
Image
Image
Image

### How to reproduce

GET TELEPATHY + TRENCH AND PLACE DEBRIS THEN MINE IT

Has also been repeated on JUST telepathy.

### "/ae plinfo" link

https://paste.md-5.net/ekisodebej

**Comment by ThomasWega** [comment]
Hey! Can you try with just AE on your server? I've tried this and am not able to replicate this. If you could send a video, that would be helpful as well.

**Comment by sennby** [comment]
I just did it again on my test server with pretty bare bones .( no jobs, no skills, nothing)
Pickaxe: eff v, telepathy IV, Trench XIX
Didnt happen
Put in aureliumskills (a plugin you have listed as supported on the plugin page)
and it dupes.


So aureliumskills + these combination.

**Comment by ThomasWega** [comment]
There's always issues with AureliumSkills... I can now confirm this bug.

**Comment by GC-spigot** [comment]
This is not a dupe, aureliumskills drops extra ancient debries by itself.

**Comment by sennby** [comment]
But it doesnt happen if i dont have custom enchantments on...

**Comment by GC-spigot** [comment]
It's on aureliumskills, it has a very poorly made API. We have debug here enabled while breaking this block: https://prnt.sc/_Bq9AiX6VQdE

It decides that it's dropping ancient debris block, but that's coming from it - we can't really control that part of it.

**Comment by sennby** [comment]
https://gyazo.com/4e02e405025feb503e34a43c662a9e07
lovely. you say its not you and they say it not them.
So any server running these two plugins know has a giant dupe, which is alot of them.
