### ISSUE TITLE
The effect of aurelium skills is not triggered when a particular enchantment is applied.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3637]
### Describe the bug

this problems are occured after update 9.3.11 to 9.3.18.
The effect of aurelium skills is not triggered when a particular enchantment is applied.
(bountiful_harvest, triple_harvest,  lucky_miner, etc)

### How to reproduce

재련:
  display: '%group-color%재련'
  description: |-
    사용시 일정확률로 도구의
    내구도를 회복합니다.
  applies-to: 
  type: ATTACK_MOB;MINING;SHOOT;SHOOT_MOB
  group: 커먼
  applies:
  - ALL_AXE
  - ALL_SWORD
  - NETHERITE_PICKAXE
  - DIAMOND_PICKAXE
  - IRON_PICKAXE
  - STONE_PICKAXE
  - WOOD_PICKAXE
  - ALL_SPADE
  - ALL_HOE
  - BOW
  - CROSSBOW
  levels:
    '1':
      chance: 20
      effects:
      - ADD_DURABILITY_ITEM:-1
    '2':
      chance: 25
      effects:
      - ADD_DURABILITY_ITEM:-2
    '3':
      effects:
      - ADD_DURABILITY_ITEM:-9

### "/ae plinfo" link

https://paste.md-5.net/xuzeloqida

**Comment by ThomasWega** [comment]
Hey! Could you provide a video comparison please?

**Comment by Ecilpse** [comment]
> Hey! Could you provide a video comparison with the latest version please?

9.3.11 https://youtu.be/9WlDhvYam6M

9.3.18 https://youtu.be/4EudwjRZN9c

**Comment by ThomasWega** [comment]
Would you be that kind and identify which exact version causes this issue please? Try every version after 9.3.11 until you come across one where this issue occurs

**Comment by Ecilpse** [comment]
> Would you be that kind and identify which exact version causes this issue please? Try every version after 9.3.11 until you come across one where this issue occurs

9.3.14 -> 9.3.15

**Comment by ThomasWega** [comment]
Should be fixed in the next update! :)
