### ISSUE TITLE
book success/destroy rate

### ISSUE THREAD

**Issue by newbie029** [GC-spigot/AdvancedEnchantments#364]
I use '/ae givebook' in my crates plugin to give player books
The success + destroy rate can be more than 100% because I make the success rate is 1-97 and destroy rate 1-100, when player apply a dust to a book where success + destroy rate is more than 100%, it decrease both success and destroy rate of the book.
Can you fix it please.

If I use '/ae give' the book is always have success + destory rate = 100%, and i dont want this.

Thanks before

**Comment by GC-spigot** [comment]
You can change these settings in config.yml

**Comment by newbie029** [comment]
Which one?
