### ISSUE TITLE
Failed effect activation 

### ISSUE THREAD

**Issue by Toshiii35** [GC-spigot/AdvancedEnchantments#3641]
### Describe the bug

Whenever the ANGELIC enchant gets activated, a message gets sent saying it failed to activate

### How to reproduce

Enchant an armor with Angelic CE, have someone or a mob trigger it, it will show the failed message

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/109869577/15498720-5145-4b6c-ad40-455caf7367e5)

### "/ae plinfo" link

https://paste.md-5.net/riwojijebe

**Comment by ThomasWega** [comment]
My bad. Should be fixed in the new update
