### ISSUE TITLE
Enchant buffs stay when unequipping armor.

### ISSUE THREAD

**Issue by GilsJunior** [GC-spigot/AdvancedEnchantments#3646]
### Describe the bug

Whenever you unequip armor which has custom enchants on it, the buffs stay till you reload while not having the armor equiped.
The buffs go away after a relog.

### How to reproduce

Just put any enchantment on your armor which gives you a buff (movement speed, extra hearts etc) and just unequip armor.

### Screenshots / Videos

not needed.

### "/ae plinfo" link

https://paste.md-5.net/begulonute

### Server Log

not needed.

**Comment by aXe18** [comment]
@GilsJunior Update your plugin first

**Comment by ThomasWega** [comment]
Yes please.. update first as you are multiple versions behind. Let us know if the issue persists on the latest version
