### ISSUE TITLE
DUPE BUG

### ISSUE THREAD

**Issue by NightLife-SG** [GC-spigot/AdvancedEnchantments#3647]
### Describe the bug

with enchantment working in offhand it create alot of problem

one of them being dupe
if you have autosmelt in offhand and main hand silk touch + experience
you create infinite loop of block

### How to reproduce

autosmelt in offhand and main hand silk touch + experience and mine block

### "/ae plinfo" link

https://paste.md-5.net/tiwusanumu

**Comment by ThomasWega** [comment]
Hey. Update your plugin, few days later we fixed this issue by disabling OFFHAND for triggers MINING, ATTACK and ATTACK_MOB

**Comment by NightLife-SG** [comment]
which version that fixed this?

**Comment by ThomasWega** [comment]
Just use the latest version. Or do you need to know the precise version where this was introduced?
