### ISSUE TITLE
Holy white scrolls is DELETING the items after death

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3649]
### Describe the bug

when the player dye with a item with the holy white scroll, the items just **disappears**!

### How to reproduce

1. Use the latest version
2. Apply a holy white scroll in a item (/ae giveitem WaKaliTe holywhitescroll 1)
3. Die

### "/ae plinfo" link

https://paste.md-5.net/esasevococ

**Comment by austv** [comment]
This error happens when the problem is reproduced: https://mclo.gs/zaCImTs

**Comment by austv** [comment]
Tried with the basic config as well, the problem persist

**Comment by ThomasWega** [comment]
Will be fixed in the next update
