### ISSUE TITLE
force-glow: false was not worked.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3650]
### Describe the bug

ae item (mystery dust, magic dust, etc..) was not applied force-glow: false.

### How to reproduce

  mystery-dust:
    type: SULPHUR
    id: 0
    custom-model-data: 0
    force-glow: false
    name: '&fMystery Dust'
    lore:
    - '&7A failed bi-product'
    - '&7of Magic dust.'

### "/ae plinfo" link

https://paste.md-5.net/ulohebaqez

**Comment by ThomasWega** [comment]
Should be fixed in the next update! :)
