### ISSUE TITLE
Break SlimeFun head with tools that have enchantment will drop normal(bug) head

### ISSUE THREAD

**Issue by DarrienZ** [GC-spigot/AdvancedEnchantments#3653]
### Describe the bug

Breaking SF Items with tools that have custom enchantment will not drop SF Original Head. Was reported but looks like GC team ignored the message.

### How to reproduce

Using ItemsAdder as SlimeFun resourcepack
Using SF Resourcespack [Download](https://github.com/xMikux/Slimefun-Resourcepack)

[17:02:56 INFO]: This server is running Pufferfish version git-Pufferfish-25 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e32a780 on HEAD)
[17:03:19 INFO]: AdvancedEnchantments version 9.4.0
[17:03:26 INFO]: Slimefun version DEV - 1100 (git d683a633)

### Screenshots / Videos

https://youtu.be/klHVNz91YMs

### "/ae plinfo" link

https://paste.md-5.net/ehagayosur

### Server Log

https://pastebin.com/txFpibsa

**Comment by ThomasWega** [comment]
Hey! Does this issue occur only with the resource pack? Because it works fine for me
https://i.imgur.com/Ywtjtgc.mp4

**Comment by DarrienZ** [comment]
Without resourcespack also got same problem

**Comment by DarrienZ** [comment]
Updates:
After using v9.4.1, everything looking good now. Tried with resourcespack and without resourcespack. Thanks you
