### ISSUE TITLE
Armor Sets Bonuses don't apply (events not working)

### ISSUE THREAD

**Issue by TreemanKing** [GC-spigot/AdvancedEnchantments#3655]
### Describe the bug

Bonuses should apply to armour sets. Currently the bonuses do not work (haven't tested all of the bonuses but I'm assuming all).

### How to reproduce

1. Open Fresh Instance of AE (Default Configs and Armor Sets)
2. Equip KOTH armour
3. Take Fall Damage/(Give effect and Swing)
4. Nothing Occurs

### Screenshots / Videos

![2023-09-11_20 33 07](https://github.com/GC-spigot/AdvancedEnchantments/assets/67459602/7be85be2-a21e-43fa-8e23-7f158bdd9a56)
![2023-09-11_20 33 14](https://github.com/GC-spigot/AdvancedEnchantments/assets/67459602/19376240-cbd4-46be-b5ac-7e9f5d3b722c)
![2023-09-11_20 33 18](https://github.com/GC-spigot/AdvancedEnchantments/assets/67459602/15f63109-ed56-46f7-ab12-7d08f9b6b1c8)

### "/ae plinfo" link

https://paste.md-5.net/zoyasalabo

### Server Log

https://mcpaste.io/11d557f3c6c1ea39

**Comment by ThomasWega** [comment]
Hey! Did this happen in a previous version as well? Or just in 9.4.0?

**Comment by TreemanKing** [comment]
> Hey! Did this happen in a previous version as well? Or just in 9.4.0?

Unsure, as we haven't been able to use Armor Sets due to previous bugs.

**Comment by ToucanFacilities** [comment]
I can confirm we have encountered this issue too.

**Comment by ThomasWega** [comment]
it just seems like we didnt include an enchant that cancels the fall damage in the default configuration. I've tried including one myself and it works just fine

![obrazek](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/7bec6a36-759d-4300-bd28-96d869799387)
![obrazek](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/76299bf7-880e-478b-9325-46923637df15)

**Comment by GC-spigot** [comment]
Fixed next update
