### ISSUE TITLE
Telepahty dont work with mcMMO herbalism 

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#3657]
### Describe the bug

When chopping carrots with telepathy enchant and 1000 level of Herbalism (mcMMO) you getting less carrots and if you chop without telepathy you getting a lot more carrots.

### How to reproduce

Set 1000 levels of herbalism and chop carrots with HOE who have telepathy and compare results when chopping with HOE who don't have telepathy.

### Screenshots / Videos

https://www.youtube.com/watch?v=RPBZufHq1_g turetu buti aisku

### "/ae plinfo" link

https://paste.md-5.net/merogawego

**Comment by ThomasWega** [comment]
Hey! Do you mind trying this in the latest version and on fresh server with only mcMMO and AE? Thanks

**Comment by SirvydasS** [comment]
Still same problem

**Comment by ThomasWega** [comment]
Will be fixed in the next update! :)
