### ISSUE TITLE
sacred white scroll bug, when they die it does not disappear and eliminates the item it protected

### ISSUE THREAD

**Issue by Rcorcho6** [GC-spigot/AdvancedEnchantments#3658]
### Describe the bug

In this bug not only what happened previously happens that the players died but they were still in the item, now the same thing happens but the protected items disappear

### How to reproduce

the player applies the sacred white scroll to the item, it enters pvp, the items protected upon death remain protected, but one of all the items disappears.

As you can see in the video, first the helmet disappears, then the boots and so on.

### Screenshots / Videos

https://youtu.be/7i3cXu2-7j0

### "/ae plinfo" link

https://paste.md-5.net/ucikoquvuj

**Comment by ThomasWega** [comment]
can you try on a server with only AE please? This shouldn't happen and I cannot reproduce it

**Comment by WAFFUGOD** [comment]
Still I tried It every Way but These bug Uh

**Comment by ThomasWega** [comment]
Have you updated the plugin?

**Comment by WAFFUGOD** [comment]
Im Currently Using 9.3.19
Which Version Shall I use

**Comment by ThomasWega** [comment]
Either you have a bad configuration or needs to be a plugin conflict. I truly don't see any other way. I am sending video as a proof that everything works fine for us. 

https://i.imgur.com/yMAA8ek.mp4

If you can record a video, where you show a completely fresh server with latest AE version and this issue still happens, I will be happy to investigate further
