### ISSUE TITLE
Conditions don't work

### ISSUE THREAD

**Issue by ToucanFacilities** [GC-spigot/AdvancedEnchantments#3659]
### Describe the bug

I try to use conditions, but they just don't work. For example, I used "_%player world% = my_world : %allow%_" as found on the wiki, which in theory would make it so the enchant only activates when the user is in the correct world, well it works but completely ignores the condition meaning it activates regardless of if I'm in the right world or not. 

This is just one of the many times they don't work, I am convinced that they are just broke since every enchantment I try to create with a condition, it just ends up getting ignored. I am running on version 9.4.0.

### How to reproduce

This is an enchant I try and use to make the item do more damage to mobs found in the nether, however it ignores the conditions and works on any mob. There isn't really more I can say other than the conditions just get ignored.

blessed:
  display: '%group-color%⚡ Blessed'
  description: Deal 10% more damage against Nether mobs.
  applies-to: All melee weapons.
  type: ATTACK_MOB
  group: UNCOMMON
  applies:
  - ALL_SWORD
  - ALL_AXE
  - TRIDENT
  levels:
    '1':
      cooldown: 1
      condition:
      - '%mob type% = WITHERSKELETON or %mob type% = ZOGLIN or %mob type% = MAGMACUBE
        or %mob type% = PIGLIN or %mob type% = PIGLINBRUTE or %mob type% = PIGZOMBIE
        or %mob type% = BLAZE or %mob type% = HOGLIN : %allow%'
      effects:
      - INCREASE_DAMAGE:10
      
      

### Screenshots / Videos

https://youtu.be/jaLhQtLP5oI?feature=shared
video showcasing the issue

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/144877470/f6b059ba-b9c1-4b55-80fc-d29637a79061)
this is the fury enchant as shown in the video

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/144877470/81cd0133-d3b7-4e64-b500-8f48acc09a4f)
this is the blessed enchant as shown in the video

[AdvancedEnchantments.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/12593839/AdvancedEnchantments.zip)
my AE folder

### "/ae plinfo" link

https://paste.md-5.net/ejepiyipud

**Comment by ThomasWega** [comment]
can you try 9.4.1 please? We've fixed some placeholders in that version

**Comment by ToucanFacilities** [comment]
I just updated to 9.4.1 and there was no change, both enchants still ignored the condition.

**Comment by ThomasWega** [comment]
that's because it's not "condition" but rather "conditions"

**Comment by ToucanFacilities** [comment]
Yes this worked, thank you!
