### ISSUE TITLE
Issue with detonate

### ISSUE THREAD

**Issue by AzoteBottle** [GC-spigot/AdvancedEnchantments#366]
Hey,

I've got an issue with detonate pickaxe.

I can break some blocks endlessly and if we add experience on this pickaxe we can earn experience by endlessly breack technic ...

List of block which I can do this (incomplete maybe)

prismarine_brick_slab
prismarine_slab
dark_prismarine_slab
prismarine_brick_stairs
prismarine_stairs
dark_prismarine_stairs
blue_ice
stripped_oak_log ( ... birch, dark_oak ... all stripped)
stripped_oak_wood  ( ... birch, dark_oak ... all stripped)
oak_wood ( ... birch, dark_oak ... all wood)
kelp
![2019-03-05_18 52 36](https://user-images.githubusercontent.com/29676092/53826588-37b96380-3f79-11e9-85e1-45e796349040.png)
![2019-03-05_18 52 39](https://user-images.githubusercontent.com/29676092/53826614-4738ac80-3f79-11e9-80b3-d60ed719fb0c.png)
![2019-03-05_18 52 44](https://user-images.githubusercontent.com/29676092/53826637-56b7f580-3f79-11e9-8943-79efea1d2ad2.png)
![2019-03-05_18 52 47](https://user-images.githubusercontent.com/29676092/53826649-633c4e00-3f79-11e9-8f79-cb93393d47d8.png)

Sorry for my bad english ...

**Comment by AzoteBottle** [comment]
EDIT : All stairs

**Comment by GC-spigot** [comment]
Confirmed to be an issue and might not be fixable until plugin is switched to 1.13-only.
