### ISSUE TITLE
Add timer to FLY effect

### ISSUE THREAD

**Issue by wlm1455925277** [GC-spigot/AdvancedEnchantments#3664]
### Describe the bug

Can he make the fly effect a limited time effect? For example, FLY:100 means flying for 10 seconds, and the flight will be turned off after 10 seconds. I checked the wiki and he said that the time can be set like this. When I set it, he couldn't specify how long it can fly! Hope this feature can be added or fixed.

### How to reproduce

翅膀:
  display: '%group-color%翅膀'
  description: 穿戴后可以飞行.
  applies-to: "靴子"
  type: EFFECT_STATIC
  group: LEGENDARY
  applies:
    - ALL_BOOTS
  levels:
    '1':
      cooldown: 30
      effects:
        - FLY:40

### "/ae plinfo" link

https://paste.md-5.net/ecaqawiwid

### Server Log

https://mcpaste.io/50a8222baa0ba999

**Comment by ThomasWega** [comment]
Will be added in the next update! :)
