### ISSUE TITLE
ArmorSets independent of enchantments.yml

### ISSUE THREAD

**Issue by TreemanKing** [GC-spigot/AdvancedEnchantments#3665]
### Describe the bug

BUG:
Currently, the enchantments.yml is NOT customisable at all. 

We cannot remove redundant enchants to make a clean file with the CUSTOM enchants that we want as a result. 

One the default enchantments are removed, this causes most features with ARMORSETS to break (effects included).

From trial and error, OVERLOAD is used as a fake ENCHANTMENT to make the custom ARMORSET work. 

Quite honestly, it's disappointing how you can call this a fix for #3616 and #3655. We could've just applied a fake enchantment if we truely wanted to achieve the result.

What should be the case:
ArmorSets and effects to these armorsets should be INDEPENDENT of the enchantments. 

### How to reproduce

1. Load Fresh Server
2. Replace current `enchantment.yml` file with the file provided
3. Try Equipping any Armor Set with any custom effects (example also given)
4. Doesn't Work

Included is the ArmorSets and `enchantments.yml` (renamed to `enchantmentsTest.yml`)
[AdvancedEnchantments.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/12617909/AdvancedEnchantments.zip)

### "/ae plinfo" link

https://paste.md-5.net/jabuhoqawa

### Server Log

N/A - No errors present.

**Comment by GC-spigot** [comment]
Fixed!
