### ISSUE TITLE
enchantment-world-blacklist

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3666]
### Describe the bug

Enchantment world blacklist can be bypassed (also probably other blacklists).

### How to reproduce

1. Go to world where enchantment is not disabled (blacklisted)
2. Take item with enchantment in main or off hand
3. You got potion effect
4. Go to blacklisted world
5. You still have potion effect

### "/ae plinfo" link

https://paste.md-5.net/exuliyijoy

**Comment by ThomasWega** [comment]
Will be fixed in the next update
