### ISSUE TITLE
REMOVE_HEALTH and REMOVE_HEALTH_DAMAGE ignores totem of undying.

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#3668]
### Describe the bug

If this effect kills somebody it completely ignores totems.

### How to reproduce

Hold a totem with either one of these effects on a sword and damage yourself and then you die without the totem activating.

### "/ae plinfo" link

https://paste.md-5.net/oheyakebaj

**Comment by ThomasWega** [comment]
Will be added in the next update! I've added two new effects.

REMOVE_HEALTH_TOTEM
REMOVE_HEALTH_DAMAGE_TOTEM

both of them will allow the usage of totem
