### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3669]
### Describe the bug

[00:39:26 ERROR]: Could not pass event PlayerFishEvent to AdvancedEnchantments v9.3.17
java.lang.NullPointerException: null

### How to reproduce

Fish (probably with special enchantment?)

### "/ae plinfo" link

https://paste.md-5.net/mugivuwexo

**Comment by ThomasWega** [comment]
Please send the full error

**Comment by ThomasWega** [comment]
does this happen in the latest version as well?

**Comment by ThomasWega** [comment]
So? Also, what's the enchant you use?

**Comment by ThomasWega** [comment]
Hey! All these enchantments have actually been removed few versions ago by us, as they have causes some issues. Also I am not able to work with the info you have provided me with, so I will need to close it. If you have more info some time later, feel free to open a new issue and I'd happily investigate the issue for you
