### ISSUE TITLE
Issue with <math> and combo

### ISSUE THREAD

**Issue by Frostyeiz** [GC-spigot/AdvancedEnchantments#367]
1. So I tried <math> like what you said in #361  but it doesn't seem to work, here are the enchantment and the error:
```
rage:
  display: '%group-color%Rage'
  description: "a"
  applies-to: 'Weapon'
  type: 'ATTACK'
  group: 'HEROIC'
  applies:
  - ALL_AXE
  - ALL_SWORD
  levels:
     1:
      effects:
      - 'EXTRA_DAMAGE:<math>%combo%/10</math> %attacker%'
```
^ what i wanted is for every hit i land, my damage will increase 10% (which is 1.1x), not so sure if I done it right, if i did it wrong, can you fix it for me? Thanks.
```
[20:06:57 INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException:
[20:06:57 INFO]:    Class:
[20:06:57 INFO]:    Extra info: Effect[ATTACK], enchant[rage]; mc[112]; ae[5.3.5]
[20:06:57 INFO]: If you cannot indentify cause of this, contact developer providing this report.
```
2. How long does it take for combo to reset? If possible, can you make it configurable?

**Comment by GC-spigot** [comment]
You're able to configure how many hits player can stack up till it doesn't increase any more in config.yml under settings.

**Comment by GC-spigot** [comment]
Your issue might be fixed next update - not having this error after I redid a few effects.
