### ISSUE TITLE
archer enchant didn't work

### ISSUE THREAD

**Issue by RabiRadish** [GC-spigot/AdvancedEnchantments#3670]
### Describe the bug

when i use archer enchant's bow shooting this not work and console appear error

### How to reproduce

enchant archer 1 and shooting

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/145276328/1994da62-ea1f-4c34-9558-213010eb158f)

### "/ae plinfo" link

https://paste.md-5.net/osusojisix

### Server Log

https://mcpaste.io/119aab9a9cbc238c

**Comment by ThomasWega** [comment]
Will be fixed in the next update
