### ISSUE TITLE
TP_DROPS don't work with AureliumSkills

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3671]
### Describe the bug

aureliumskill's xp was not gained when apply ae enchantments.

### How to reproduce

i tested by TP_DROPS

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/00db5e18-5e90-4ab4-843c-b1d85358e4cf

### "/ae plinfo" link

https://paste.md-5.net/axezabuhaw

**Comment by ThomasWega** [comment]
Will be fixed in the next update
