### ISSUE TITLE
Item Dupe Glitch With ItemsAdder Plugin

### ISSUE THREAD

**Issue by MoGGaming** [GC-spigot/AdvancedEnchantments#3673]
### Describe the bug

apply soulbound enchant any armor set of IA and just kill the player item will be dupe.

### How to reproduce

1.get any armor from IA 
2. apply soulbound enchant to armor
3. wear the armor
4. kill the player
result will be 2 armors

### "/ae plinfo" link

https://paste.md-5.net/toxahizowa

**Comment by aXe18** [comment]
Send that soulbound enchant

**Comment by Ramgaming** [comment]
https://paste.md-5.net/xavehufiqi.shell

**Comment by MoGGaming** [comment]
do you have itemsadder armor in your hand ?
Then just apply soulbound to it and kill the player ?

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
