### ISSUE TITLE
AureliumSkills - dirt copies itself during destruction

### ISSUE THREAD

**Issue by Gacekkk** [GC-spigot/AdvancedEnchantments#3674]
### Describe the bug

dirt copies itself during destruction

### How to reproduce

visible on film

### Screenshots / Videos

https://youtu.be/l0rm-FeW2Gk

### "/ae plinfo" link

https://paste.md-5.net/avoximasur

**Comment by aXe18** [comment]
Same issue for me, provided video about this for @ThomasWega in discord

**Comment by ThomasWega** [comment]
Will be fixed in the next update
