### ISSUE TITLE
AE Permissions and Essentials integration

### ISSUE THREAD

**Issue by UnoriginalName** [GC-spigot/AdvancedEnchantments#368]
How would you go about integrating AE on items within kits on essentials. Also, why are there no perms set for /ae, /ae about. I'd like to be able to deny access to specific players for those commands.

**Comment by GC-spigot** [comment]
Those commands are open to public due to piracy reasons. What goes for Essentials kits - it's not supported as of right now, AE utilizes NBT and it's not available for Essentials
