### ISSUE TITLE
When world change, Effect is reset.

### ISSUE THREAD

**Issue by madebygood** [GC-spigot/AdvancedEnchantments#3680]
### Describe the bug

If you change worlds, the potion effect will be applied again.

Therefore, there is a problem with additional heatlh being initialized due to health boost.

### How to reproduce

world change

### "/ae plinfo" link

https://paste.md-5.net/oqavopeqiz

**Comment by ThomasWega** [comment]
Ugh... I did this because we had an issue that the effect didn't get removed at all when you switched world and the enchantment was blocked there. Guess I will to handle it differently. Will see what I can do.

**Comment by ThomasWega** [comment]
what's your enchant please?

**Comment by ThomasWega** [comment]
will be fixed in the next update!

**Comment by madebygood** [comment]
> will be fixed in the next update!

The issue has not been fixed yet.
Please check again.

**Comment by ThomasWega** [comment]
Correct. Sorry, my bad. https://github.com/GC-spigot/AdvancedEnchantments/issues/3791
