### ISSUE TITLE
Fire can be trenched

### ISSUE THREAD

**Issue by MinecraftAdmin** [GC-spigot/AdvancedEnchantments#3681]
### Describe the bug

When you trench a fire-block, it trenches all the blocks around it. 
Its instant, all you have to do is click the fire block and it trenches it and everything around it

Would appreciate the fix

### How to reproduce

Get trench pickaxe, click fire. 

### "/ae plinfo" link

https://paste.md-5.net/ocalenarog

**Comment by ThomasWega** [comment]
Will be fixed in the next update
