### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3682]
### Describe the bug

some error spamming in console.

### How to reproduce

Not sure, but I think its by an enchant.

### Screenshots / Videos

https://pastebin.com/FvSFyG5E

### "/ae plinfo" link

https://paste.md-5.net/ikinogihuy

### Server Log

Log too big, i will send it tickets.

**Comment by SirJben** [comment]
https://paste.md-5.net/qiqoyemula.cs

**Comment by GC-spigot** [comment]
This is happening when a book is opened has an invalid enchant, I've fixed the errors from showing up but there may be an underlying issue with your enchantment configuration itself.

**Comment by illudota** [comment]
ohh thats why, yeah i had removed some enchants and people still had some books of it.
