### ISSUE TITLE
mining delay bug

### ISSUE THREAD

**Issue by Rcorcho6** [GC-spigot/AdvancedEnchantments#3683]
### Describe the bug

The reason for this reportis because the Trench that thinks it mines 5x5 has a delay of 1 or more seconds but when creating it it sets a cooldown of 0
Here I send you my enchants file and if the last thing goes, find the trench created to see if I have something wrong since it has a delay that makes my users impatient, I have configured it from scratch to see if a file had been corrupted but it continues equal

### How to reproduce

It turns out that as we are mining this time there is a delay when creating the 5x5 mining animation with a delay of 1 second or more, therefore we have installed the previous version on the recommendation of the admin through a ticket and this version works correctly

### Screenshots / Videos

https://youtu.be/dSdqqiGU1jQ

### "/ae plinfo" link

https://paste.md-5.net/lejidomujo

**Comment by ThomasWega** [comment]
Hello. We are not able to reproduce it. Please try on a fresh server with AE only. And make sure to send us timings reports as well
