### ISSUE TITLE
Telephaty converts slimefun blocks in vanilla blocks

### ISSUE THREAD

**Issue by kingakis2** [GC-spigot/AdvancedEnchantments#3684]
### Describe the bug

When you have telephaty enchant on a pickaxe and mine a block of slimefun likely a infinity expansion block it converts in vanilla and, some blocks will even dupe dropping the vanilla block and slimefun block with some enchants.

### How to reproduce

Enchant a pickaxe with telephaty and break a slimefun or a slimefun expansion block it will give you the vanilla block or with other enchants it will drop the slimefun one and vanilla block.

### "/ae plinfo" link

https://paste.md-5.net/bucevigoto

**Comment by kingakis2** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/assets/109235946/6551443c-2d6e-439b-b208-90e34be4de84
telephaty enchant

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Although please note that trench won't work on slime fun items for now (is disabled), as we need to handle some issues with that first
