### ISSUE TITLE
Could not pass event BlockDropItemEvent to libreforge v4.34.0

### ISSUE THREAD

**Issue by tntromania** [GC-spigot/AdvancedEnchantments#3685]
### Describe the bug

everytime i broke something to recive an item(dirt/stone/diamond...) i recive console error

### How to reproduce

help me please

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/143605457/bbe71637-0b7b-4ed4-8b05-a706ee8434b9)

### "/ae plinfo" link

https://paste.md-5.net/wafacupilu

### Server Log

https://mcpaste.io/1255f95dc7656d29

**Comment by ThomasWega** [comment]
seems like libreforge issue

**Comment by tntromania** [comment]
And how i can fix it man?

**Comment by ThomasWega** [comment]
I don't know. I am not a developer for libreforge
