### ISSUE TITLE
SMELT was not applied properly with fortune.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3686]
### Describe the bug

literally. SMELT was not applied properly with fortune
breaking 10 diamond ore:
pickaxe + SMELT + fortune 3 = 27 diamonds
pickaxe + fortune 3 = 18 diamonds

### How to reproduce

1. make 2 pickaxe (SMELT + fortune 3 / fortune 3)
2. break 5 diamond ore with pickaxe.

### Screenshots / Videos

https://youtu.be/wioVKLKKlBg

### "/ae plinfo" link

https://paste.md-5.net/agozatatof

**Comment by Ecilpse** [comment]
> Have you concluded more tests? Is it always more? Fortune does not always drop the same amounts...

my server has over 300+ player.
many users report this issue.
Certainly, pickaxe with smelt has a low rate of drops.

**Comment by ThomasWega** [comment]
Update to the latest. We've already some fortune issues and it seems to work just fine for me now. Next time before creating github issue, please make sure you are on the latest version.
