### ISSUE TITLE
DROP_HEAD  not working propertly

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#3689]
### Describe the bug

In mobHeads.yml for example are a few ZOMBIE skins, but you only getting always the same skin.
CAT heads not dropping. (same bug with trader lama and maybe a more mobs don't drop head (they are written in config))
And when try to change FOX head texture I still getting same FOX head.

### How to reproduce

Have an enchanted sword with enchant who will drop on kill heads and try killing mobs.
1. Try to kill a lot of zombies and watch how you get only 1 type of skin.
2. Try kill CAT and will not get a head.
3. Try change FOX head skin to zombie and after restart you still get FOX skin.

### "/ae plinfo" link

https://paste.md-5.net/icetototet

**Comment by ThomasWega** [comment]
Hello. Send you enchant config please

**Comment by ThomasWega** [comment]
my bad :D

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
