### ISSUE TITLE
SHIFT event for armor sets not working

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#3690]
### Describe the bug

Tried most of the events to activate a simple potion effect and everything worked except the SHIFT one. 

### How to reproduce

events:
  SHIFT:
    chance: 100
    effects:
    - POTION:INVISIBILITY:5:100
    - POTION:SPEED:3
    cooldown: 0    

Does not work, but EFFECT_STATIC for example, does

### "/ae plinfo" link

https://paste.md-5.net/kifimezuro

**Comment by aXe18** [comment]
@detoxv Reason is bc there is no shift trigger, all triggers are listed here ->
https://wiki.advancedplugins.net/abilities/triggers
