### ISSUE TITLE
Hook Enchantment giving always x2 drop

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#3695]
### Describe the bug

When fishing with rod and with HOOK 3 enchantment you always will get x2 drops. Example 2 fish and etc.
And thinking you not getting more xp.

### How to reproduce

Put hook 3 enchant on the fishing rod and go fish then catch the fish.

### "/ae plinfo" link

https://paste.md-5.net/cibiwufoto

**Comment by ThomasWega** [comment]
the hook enchantment was removed few versions ago
