### ISSUE TITLE
Oraxen custom blocks support (trench / vein miner / smelter)

### ISSUE THREAD

**Issue by FrederikSchmidtDv** [GC-spigot/AdvancedEnchantments#3696]
### Describe the bug

When proccing trench enchant, vein miner enchant or smelter enchant with a custom ore (oraxen block) it breaks. 

### How to reproduce

Have any custom ore (that is disguised like a noteblock or mushroom stem) and use vein miner / smelter / trench enchant and it will instead drop the noteblock (instead of the actual drop that was supposed to happen). 

Ore generated: custom-ore-generator

Oraxen version: 1.162.0

AE: 9.4.3

### "/ae plinfo" link

https://paste.md-5.net/asabafinox

**Comment by ThomasWega** [comment]
Should be fixed in the next update!
