### ISSUE TITLE
Condition %offhand item% Not Working

### ISSUE THREAD

**Issue by MrSal202** [GC-spigot/AdvancedEnchantments#3697]
### Describe the bug

conditions:
    - '%offhand item% = true : %stop%'

Does not prevent the enchant from proccing in the offhand.

### How to reproduce

Put the enchanted item in your offhand then activate the effect with your main hand.
Here is an example config:

ragetest:
  display: '%group-color%Rage Test'
  description: |-
    Gain Strength after a kill.
  applies-to: Swords, Axes
  type: KILL_MOB;KILL_PLAYER
  group: RARE
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    '1':
      conditions:
        - '%offhand item% = true : %stop%'
      effects:
        - POTION:STRENGTH:0:200 @Self

Put the ragetest enchanted item in your offhand, then kill a mob with your main hand. The effect will activate when it shouldn't.

### "/ae plinfo" link

https://paste.md-5.net/miyepupili

**Comment by ThomasWega** [comment]
You are using the wrong placeholder
<img width="733" alt="image" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/1c36dc00-4448-4486-8028-d4dc09830b56">

try using %item slot% = OFFHAND
