### ISSUE TITLE
applies-to does not work when translated

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#3698]
### Describe the bug

When you translate the applies-to does not take the translation and remains the default

### How to reproduce

Translate within the enchantments.yaml file the applies-to and when you are inside the translation does not work

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138524212/6c2c7dfb-9387-481b-9416-414acf840e5e)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138524212/fade9239-4ca8-47f3-8a02-629b6b6385ca)

### "/ae plinfo" link

https://paste.md-5.net/jopiyayapa

### Server Log

https://pastebin.com/D50tjZyj

**Comment by ThomasWega** [comment]
Hello. Either recreate your config or change the config value to %applies-to% instead of %applies%
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/60dfb827-c8af-481e-b1f6-7b466a82b928)
