### ISSUE TITLE
vein_mine was not worked.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3700]
### Describe the bug

literally. break-event was cancelled when effect VEIN_MINE

### How to reproduce

1.enchant veinmine
2. break ore block
3

### "/ae plinfo" link

https://paste.md-5.net/ocexibejek

**Comment by ThomasWega** [comment]
Sorry, what do you mean exactly? Do you work with API, or does the veinmine doesn't work in the game? If so, can you record a video please?

**Comment by Ecilpse** [comment]
> Sorry, what do you mean exactly? Do you work with API, or does the veinmine doesn't work in the game? If so, can you record a video please?

This problems has been occured by restart only plguin by plugman.
It fixed when it restart sever. Sorry for my mistake
