### ISSUE TITLE
INCREASE_DAMAGE for bow was not worked

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3701]
### Describe the bug

INCREASE_DAMGED for BOW was not worked. still same damage after enchant
### How to reproduce

apply this enchantments that i wrote below and shoot arrow to monster.
명궁:
  display: '%group-color%명궁'
  description: 활로 가하는 데미지가 증가합니다.
  applies-to: 
  type: SHOOT;SHOOT_MOB
  group: 에픽
  applies:
  - BOW
  levels:
    '1':
      effects:
      - INCREASE_DAMAGE:<random number>1500-1600</random number> @Victim

### "/ae plinfo" link

https://paste.md-5.net/efeyefekun

**Comment by ThomasWega** [comment]
You have improper formatting. You are only using the close tag (</>) but you never open the tag

1500-1600</random number>

change to:

<random number>1500-1600</random number>.

Also make sure to write the target in uppercase (@Victim)

**Comment by Ecilpse** [comment]
> You have improper formatting. You are only using the close tag (</>) but you never open the tag
> 
> 1500-1600</random number>
> 
> change to:
> 
> 1500-1600</random number>.
> 
> Also make sure to write the target in uppercase (@victim)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/c76c32a8-6905-4fba-a5d6-724b206efb9a)

i set like this, still now worked.
and what is defference "1500-1600</random number>" and "1500-1600</random number>" that you said?

**Comment by ThomasWega** [comment]
My bad. I pasted the wrong message 

<random number>1500-1600</random number>.

**Comment by ThomasWega** [comment]
```
<random number>1500-1600</random number>
```

Sorry I pasted the wrong thing

**Comment by ThomasWega** [comment]
```
<random number>1500-1600</random number>
```

Sorry I pasted the wrong thing

**Comment by ThomasWega** [comment]
```
<random number>1500-1600</random number>
```

Sorry I pasted the wrong thing

**Comment by ThomasWega** [comment]
Can you please try in 9.4.8? There was a fix for bows, so it might have fixed this

**Comment by Ecilpse** [comment]
> Can you please try in 9.4.8? There was a fix for bows, so it might have fixed this
It seems that not only the bow but also the sword has this problem.
I've done dozens of bug reports for months, but why are bugs constantly occurring

**Comment by ThomasWega** [comment]
Hey! We've just tested this and were not able to replicate it. If you are able to pinpoint when this issue exactly happens, please let us know in a new github issue
