### ISSUE TITLE
EXP:%exp% effect double drops

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3702]
### Describe the bug

hook:
  display: '%group-color%Hook'
  description: Get more exp from fishing.
  applies-to: Fishing Rod
  type: CATCH_FISH
  group: ELITE
  applies:
    - FISHING_ROD
  levels:
    '1':
      chance: 15
      cooldown: 12
      effects:
        - EXP:%exp%
    '2':
      chance: 25
      cooldown: 12
      effects:
        - EXP:%exp%
    '3':
      chance: 100
      cooldown: 0
      effects:
        - EXP:%exp%

### How to reproduce

Its giving double drops even tho it should not

### "/ae plinfo" link

-

**Comment by ThomasWega** [comment]
the enchantment was removed previously
