### ISSUE TITLE
KILL_MOB;KILL Do not work when you kill using a Bow Projectile

### ISSUE THREAD

**Issue by MrSal202** [GC-spigot/AdvancedEnchantments#3705]
### Describe the bug

Here is an example config:

bountifulhunt:
  display: '%group-color%Bountiful Hunt'
  description: |-
    Hostile mobs drop bonus XP when killed.
  applies-to: Bows
  type: KILL_MOB;KILL
  group: UNCOMMON
  applies:
    - BOW
  levels:
    '1':
      conditions:
        - '%is hostile% = true : %allow%'
        - '%item slot% = OFFHAND : %stop%'
      effects:
        - MESSAGE:Bountiful! @Attacker
        - EXP:<random number>10-30</random number> @Victim

It seems bows are not affected by the KILL or KILL_MOB triggers when they kill using a projectile. The trigger only works if you melee kill while holding the bow.

### How to reproduce

Enchant a bow with an enchant using KILL_MOB;KILL trigger. Then kill using arrows. The trigger will not go off. Try killing with melee, the trigger will go off.

### "/ae plinfo" link

https://paste.md-5.net/lafoyuduta

**Comment by ThomasWega** [comment]
Should be added in the next version!
