### ISSUE TITLE
/tinkerer GUI "Accepting Trade" right button not working as it should.

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#3706]
### Describe the bug

As described by the title.

Plugin version: AE 9.4.6
Server: Paper 1.19.4 and 1.20.1

### How to reproduce

Put CE Books into /tinkerer GUI, then click on the Accept trade button to the right.

### Screenshots / Videos

https://drive.google.com/file/d/1I_BmGL-jb20GU4qONYa886bOcLvcklrf/view?usp=sharing

### "/ae plinfo" link

Don't think this is needed

### Server Log

Don't think this is needed

**Comment by GC-spigot** [comment]
It is not supposed to work, it's a "visual" button for tinkerer to accept, not player.
