### ISSUE TITLE
Shield Effects in the Offhand Affect Shield in the Main Hand

### ISSUE THREAD

**Issue by MrSal202** [GC-spigot/AdvancedEnchantments#3708]
### Describe the bug

If I enchant a shield to take less durability damage, and I have it in my offhand, and I also have a regular unenchanted shield in my main hand, then proceed to block, my right hand shield is affected by the enchantment. Shields with conflicting enchantments can proc all of the enchantments if you dual-wield shields with the enchants.

### How to reproduce

Enchant a shield and place it in your offhand, then place an unenchanted shield in your main hand. Proceed to activate the SHIELD_BLOCK trigger and you'll see that your main hand, unenchanted shield, is being affected as if it was enchanted.

### "/ae plinfo" link

https://paste.md-5.net/jujiyexipu

**Comment by ThomasWega** [comment]
Send your enchant please

**Comment by ThomasWega** [comment]
Should be fixed in the next update!
