### ISSUE TITLE
Mob Drop_head name after place changes to randoms numbers

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#3709]
### Describe the bug

When you place mob head which you got from Enchant with DROP_HEAD and then you break and take head it becomes some seems randoms numbers.

### How to reproduce

1. Kill mob
2. Get head from that mob (see it will be normal name example: Zombie Head)
3. Place that head
4. Break that head and pickup
5. See head random name. (0.2654654533525 Head)

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/8950371/25565bd1-53e5-4a94-93ff-237095816199)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/8950371/9461364b-0fe9-4cd5-82ee-b099c8f8d8ea)

### "/ae plinfo" link

https://paste.md-5.net/viyilulaxe

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
