### ISSUE TITLE
Extreme Lag

### ISSUE THREAD

**Issue by Real6dq** [GC-spigot/AdvancedEnchantments#3711]
### Describe the bug

If there are ~5 players mining with some enchantments, it'd start lagging, but it gets worse when there are like 30, like 25ms.

### How to reproduce

Simply mine blocks with bunch of your friends.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/104909470/d4456152-74be-4aae-aff7-a338e6e2fc9c)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/104909470/4f30e251-1c9f-4684-b4f0-6a57d9b7de58)

### "/ae plinfo" link

Latest version

**Comment by ThomasWega** [comment]
Hey! We did have some performance issues with combination with other plugins. One example would be: https://github.com/GC-spigot/AdvancedEnchantments/issues/3423. If you want us to address this, you'd need to identify the issue more specifically
