### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by QuitoYT** [GC-spigot/AdvancedEnchantments#3713]
### Describe the bug

I just created an enchantment but there is a problem. The incantation is as follows:

ligado:
  display: '%group-color%Ligado a tu alma'
  description: |-
    Conservarás el objeto, jamás lo perderás
    &c(Ultra exclusivo)
  applies-to: Tools, Armors, Weapons, Swords
  type: DEATH;PASSIVE_DEATH
  group: EXCLUSIVO
  applies:
    - ALL_TOOLS
    - BLAZE_ROD
    - ALL_ARMOR
    - WEAPONS
    - ALL_SWORD
  levels:
    '1':
      chance: 100
      effects:
        - KEEP_ON_DEATH

The problem is the following:

When the player dies from a warden attack, the item with the enchantment is doubled.

### How to reproduce

You can try the enchantment to see, just look for a warden and wait for him to attack you like in the video.

### Screenshots / Videos

https://youtu.be/lNo2RD1q_NQ

### "/ae plinfo" link

https://paste.md-5.net/nuqamiruka

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
