### ISSUE TITLE
player gain infinite potion effect via 'HELD' type

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3715]
### Describe the bug

1. HELD tool with 'HELD' type enchant
2. switch hand by F key
3. put out the item in the shield slot.

### How to reproduce

헤이스트:
  display: '%group-color%헤이스트'
  description: |-
    도구 사용시 영구적으로
    성급함 효과를 얻습니다.
  applies-to: 
  type: HELD
  group: 레전더리
  applies:
  - ALL_SWORD
  - ALL_PICKAXE
  - ALL_SPADE
  - ALL_AXE
  levels:
    '1':
      conditions:
      - '%is offhand% = true : %stop%'
      effects:
      - POTION:FAST_DIGGING:0
    '2':
      conditions:
      - '%is offhand% = true : %stop%'
      effects:
      - POTION:FAST_DIGGING:1
    '3':
      conditions:
      - '%is offhand% = true : %stop%'
      effects:
      - POTION:FAST_DIGGING:2

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/0f8e1482-b9d1-406a-8715-91093f8cd44b

### "/ae plinfo" link

https://paste.md-5.net/nagonifoyu

**Comment by Ecilpse** [comment]
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/522109af-bd94-457d-b453-bdc376dd7cd2)
+ Potion effect was keep persist after Armor break with effect_static potion enchantements.

**Comment by GC-spigot** [comment]
I cannot recreate either of these issues:
https://gyazo.com/85477a8cdc30d4cc90d37358bb693dfb
https://gyazo.com/713755af2f81d7db75df89e7d1f4c6eb

I am willing to bet that it's a purpur issue, it's always a purpur issue. They "optimize" by removing Spigot features, that's not optimization, that always causes issues.

**Comment by Ecilpse** [comment]
> I cannot recreate either of these issues: https://gyazo.com/85477a8cdc30d4cc90d37358bb693dfb https://gyazo.com/713755af2f81d7db75df89e7d1f4c6eb
> 
> I am willing to bet that it's a purpur issue, it's always a purpur issue. They "optimize" by removing Spigot features, that's not optimization, that always causes issues.

https://paste.md-5.net/ebetawuxav

it's not purpur issue. this problems has occured after update.
i reuploaded video. i tested with paper and only 2 plugins (AE, CMI)

1. held item.
2. swap item to offhand
3. put out item from inventory

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/dfe1218b-36b0-46de-95cd-60c7af6fa985

**Comment by Ecilpse** [comment]
> I cannot recreate either of these issues: https://gyazo.com/85477a8cdc30d4cc90d37358bb693dfb https://gyazo.com/713755af2f81d7db75df89e7d1f4c6eb
> 
> I am willing to bet that it's a purpur issue, it's always a purpur issue. They "optimize" by removing Spigot features, that's not optimization, that always causes issues.

can you check this issue?
