### ISSUE TITLE
Сant use AE on my server

### ISSUE THREAD

**Issue by Nimesyss** [GC-spigot/AdvancedEnchantments#3716]
### Describe the bug

Console write this message on load Advanced Enchantments v8.8.9

> [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

I have buy a licence on spigotmc.org in 2020 on same account name . But i cant use this on new hosting.

### How to reproduce

Change IP or Hoster

### Screenshots / Videos

https://screenshare.ru/s/P3oRyooeYX2DfKbHmDoe75

### "/ae plinfo" link

Its not work because - server not load plugin

### Server Log

https://mcpaste.io/b14fa0fff7932d71

**Comment by aXe18** [comment]
@Nimesyss Open ticket on our discord server
