### ISSUE TITLE
premade cosmic sets bugged?

### ISSUE THREAD

**Issue by report101** [GC-spigot/AdvancedEnchantments#3717]
### Describe the bug

The premade cosmicpvp enchants comes with amour so when Im using it and getting attacked by players it sends an error to me and the console. 

### How to reproduce

1.download premade cosmicpvp enchants- (everything was premade i did not touch much only tried to fix )
2.put on the premade traveler set
3.get a player to attack you
4.you should get the error

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/50795064/e4014d3e-dcb5-49f0-a7e4-2874f70134de)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/50795064/9eed1d25-b269-4f66-888f-90f9228c965a)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/50795064/ee7e11e5-b728-4ba4-a755-e97ded51da14)

### "/ae plinfo" link

https://paste.md-5.net/kowobujoke

### Server Log

https://mcpaste.io/60cbf64a30fcae29

**Comment by ThomasWega** [comment]
Hey! Please recreate your files, as DIMENSIONAL_SHIFT effect was removed. Also, if you update your version to newer, be sure to rename all your ADD_DURABILITY: effects to ADD_DURABILITY_ARMOR:
