### ISSUE TITLE
TP_DROPS beak age 1 seeds when cast 'replenish' skill in AureliumSkills.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3718]
### Describe the bug

TP_DROPS beak age 1 seeds when cast 'replenish' skill in AureliumSkills.
replenish is autoplant seeds skill in AureliumSkills.
It doesen't destroy it unless it's a fully grown seed, but it breaks with a tool with TP_DROPS.

### How to reproduce

수확:
  display: '%group-color%수확'
  description: |-
    확률적으로 도구로 파괴한
    블록이 인벤토리에
    자동으로 들어갑니다.
  applies-to: 
  type: MINING
  group: 레전더리
  applies:
  - ALL_HOE
  levels:
    '1':
      effects:
      - TP_DROPS

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/64a76f9b-95e8-490b-93e3-8ce412b051ab

1. first hoe was not applied TP_DROPS
2. second hoe was applied TP_DROPS

### "/ae plinfo" link

https://paste.md-5.net/afamuwunif

**Comment by ThomasWega** [comment]
AureliumSkills dev first needs to learn how to code properly. This is their mess and we won't fix it. They are trying to disallow the breakage of the crop with HIGHEST priority. That's just non sense. Feel free to forward this to them.
https://github.com/Archy-X/AureliumSkills/blob/6d61d59fb49cd5ab4f22f2e3c775899d4ea3bbd3/bukkit/src/main/java/com/archyx/aureliumskills/mana/Replenish.java#L37
