### ISSUE TITLE
Replanter not replanting

### ISSUE THREAD

**Issue by ItsOn3x** [GC-spigot/AdvancedEnchantments#3719]
### Describe the bug

The replanter enchantment is not working. I am using the most recent version on a 1.19.4 server. Me and Jben have looked at it to no succsess. I will link a wetransfer video so you have look at it.

### How to reproduce

I am trying to remove the conditions so that it replants every time. The video shows how it is not possible to remove the conditions. 

### Screenshots / Videos

https://wetransfer.com/downloads/76e7be43854ab1ef98bdaa12d7ea011720231009151737/452b16

### "/ae plinfo" link

https://paste.md-5.net/focucugapa

### Server Log

https://mcpaste.io/77c2050aa351e275

**Comment by ThomasWega** [comment]
The reason would be this. And it should be fixed in the next update
https://github.com/GC-spigot/AdvancedEnchantments/issues/3714
