### ISSUE TITLE
Separate the nbt from the books

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#3720]
### Describe the bug

When creating a shop where you can sell books, you cannot sell books that have a different nbt in relation to the success/destruction rate.

I think that separating the nbt will give more play when it comes to generating stores and so on, since with certain plugins you can ignore the nbt for this to work.

It could be separated into nbt of names, lore, rate, enchantment.

If you do it, I am willing to test everything that is needed in a trial version.

### How to reproduce

grab a book and put it up for sale, in my case with the economyshopgui premium plugin. You will see that you can buy and sell if they have the same nbt success/destruction rate. But if you try to sell a book with a different price, you won't be able to because it detects that it is not the same book.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138524212/89501bce-526c-44b4-a35a-ae72fc488123)

### "/ae plinfo" link

https://paste.md-5.net/toxesijazu

**Comment by ThomasWega** [comment]
Working on this! Should be out soon
