### ISSUE TITLE
Mobs not dropping ae loot

### ISSUE THREAD

**Issue by GrxyGrxy** [GC-spigot/AdvancedEnchantments#3721]
### Describe the bug

I changed the config and the mobs loot to drop ae items but both of them are not working.

### How to reproduce

Just changed the config/mobs.yml restarted the server multiple times no luck

### Screenshots / Videos

  # If set to false, mobs that spawn from spawners won't
  # drop custom drops defined in the mobs.yml file.
  custom-drops-from-spawners: true
mobs:
#  ZOMBIE:
#    chance: 75
#    items:
#      - "randomenchantmentbook:1"
#      - "whitescroll:1"
#  BLAZE:
#    chance: 100
#    items:
#      - "whitescroll:1"
#  SKELETON:
#    chance: 50
#    items:
#      - "randomenchantmentbook:1"
#  WARDEN:
#    chance:100
#    items:
#      - "whitescroll:1"

### "/ae plinfo" link

https://paste.md-5.net/facegemugi

**Comment by GrxyGrxy** [comment]
sorry not used to github first time using it

**Comment by ThomasWega** [comment]
Hey! You probably have some setting incorrect or it might be a plugin conflict. It works fine for us. It will probably be faster if you open a ticket on discord where we can try to assist you with this :)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/6c8c7e5e-7aec-4581-ae3d-033429f7b91d)
