### ISSUE TITLE
Unable to make enchants work on different items.

### ISSUE THREAD

**Issue by TheTheovaniac** [GC-spigot/AdvancedEnchantments#3723]
### Describe the bug

I can't change the items that an enchant can be applied to, I'm trying to make a poison spear, which is meant to be an iron shovel that has the Poison III enchantment. But I am unable to apply the enchant to the item, even when changing the config.

### How to reproduce

It isn't allowing me to change applicable items in config.

### "/ae plinfo" link

https://paste.md-5.net/ijiwihobak

**Comment by Epszeta** [comment]
It seems like it's with anvils. Everything was working before and I updated then it stopped working properly. Drag n drop works still from my end.

**Comment by TheTheovaniac** [comment]
I'm trying to do it with /ae enchant, but neither drag n' drop nor anvils work.

**Comment by GC-spigot** [comment]
Show your configuration, enchantment and what you are changing.

**Comment by TheTheovaniac** [comment]
I was trying to make all enchants work with everything, we had all the obtaining ways disabled because we were just going to make custom items. We did added these to every command: 

poison:
  display: '%group-color%Poison'
  description: A chance of giving poison effect.
  applies-to: Swords, Axes
  type: ATTACK;ATTACK_MOB
  group: ELITE
  applies:
    
BOW
TRIDENT
CROSSBOW
ALL_SWORD
ALL_ARMOR
ALL_PICKAXE
ALL_SPADE
ALL_AXE
ALL_EDIBLE
FISHING_ROD
levels:'1':
    chance: 6
    cooldown: 2
    effects:
POTION:POISON:0:80 @Victim'2':
  chance: 22
  cooldown: 2
  effects:
POTION:POISON:0:120 @Victim
'3':
  chance: 35
  cooldown: 2
  effects:
POTION:POISON:1:80 @Victim

**Comment by ThomasWega** [comment]
Hey! Please send the enchantment formatted https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by ThomasWega** [comment]
@TheTheovaniac
