### ISSUE TITLE
Failed to activate effect

### ISSUE THREAD

**Issue by GrxyGrxy** [GC-spigot/AdvancedEnchantments#3724]
### Describe the bug

It's an issue with a different effect. grindstone effect and explosive immunity cause errors in the server. grindstone says error while activating EXP:1000 %victim%. Whereas Explosive Immunity says cannot activate effect STOP_ATTACK
file:///C:/Users/grxyg/Desktop/Minecraft%20Server/plugins/AdvancedEnchantments/enchantments.yml

### How to reproduce

put explosive immunity on your armor preferably maxed, then get hit by mobs
put any level grindstone and try to clear some mobs preferably maxed.

### Screenshots / Videos

![Screenshot 2023-10-11 184411](https://github.com/GC-spigot/AdvancedEnchantments/assets/147569816/aabe0c63-f34c-4e83-b9d1-4a0cda40f9ff)

### "/ae plinfo" link

https://paste.md-5.net/oxavuguwat

**Comment by GrxyGrxy** [comment]
i was able to fix grindstone by changing it to attack, but explosive immunity does not work

**Comment by GrxyGrxy** [comment]
dualwield also not procing like it should

**Comment by aXe18** [comment]
@GrxyGrxy You should open ticket on our discord for these, not github report.
You have misscongigured stuff, not bugs

**Comment by GC-spigot** [comment]
Update your configuration, it's using %victim% when it's been removed for a long time - now use @Victim etc.
