### ISSUE TITLE
Effect is removed

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3725]
### Describe the bug

When I throw chicken egg, the speed effect from Gears enchantment will be removed.

### How to reproduce

1. Put on you armor with the Gears enchantment
2. Throw chicken egg
3. Speed effect has been removed

### "/ae plinfo" link

https://paste.md-5.net/uxiloyofum

**Comment by GC-spigot** [comment]
I cannot recreate this: https://gyazo.com/819227d345d3676c596dd1010e5d64fa

**Comment by ThomasWega** [comment]
Video has been archived. We can't watch it

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
