### ISSUE TITLE
Feature Request - Eat Trigger Black/Whitelist

### ISSUE THREAD

**Issue by Alphatoxic** [GC-spigot/AdvancedEnchantments#3726]
### Describe the bug

In the config.yml section, have something similar to the veinmine whitelist that uses Minecraft IDs to only allow or not allow the listed items to trigger the EAT feature. If I want my enchant to only work if they eat a steak, that is how I would do it.

It would also be reasonable to add a %food type% condition/placeholder that returns whatever the person consumed.

### How to reproduce

N/A

### Screenshots / Videos

N/A

### "/ae plinfo" link

N/A

**Comment by ThomasWega** [comment]
Hey. I've added %food type% placeholder for you. This should solve your struggle
