### ISSUE TITLE
ItemsAdder support

### ISSUE THREAD

**Issue by SeptyIsHere** [GC-spigot/AdvancedEnchantments#3727]
### Describe the bug

ItemsAdder blocks are not affected by Trench whatsoever

### How to reproduce

Get ItemsAdder and mine with any pickaxe any ItemsAdder blocks

### Screenshots / Videos

[](url)

### "/ae plinfo" link

https://paste.md-5.net/ugudadofif

**Comment by SeptyIsHere** [comment]
https://www.veed.io/view/ff7dc369-e020-4b5d-9044-d90b4d8004b0?sharingWidget=true&panel=

**Comment by ThomasWega** [comment]
I've created a feature request on IA, as we first need an API method to be implemented on their side for us to make this work.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3113

**Comment by ThomasWega** [comment]
Should be added in the next update!

**Comment by ThomasWega** [comment]
Actually, ItemsAdder has another issue. First need to handle that. https://github.com/PluginBugs/Issues-ItemsAdder/issues/3159

**Comment by ThomasWega** [comment]
Should be added in the next update!
