### ISSUE TITLE
Issues with Inqusitive

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#373]
- 'EXP:<random number>4-8</random number> %victim%'

AE- 5.3.7
Paper- 1.13.2

Players are reporting that Inquisitive doesn't work with mob spawners. No bonus exp is given.

**Comment by GC-spigot** [comment]
They might not notice that EXP spawns right under them rather than when they pick up the mob experience orbs. I tested it and it works.
