### ISSUE TITLE
Dupe Bug Helmet enchant

### ISSUE THREAD

**Issue by 69Slowpoke** [GC-spigot/AdvancedEnchantments#3730]
### Describe the bug

When wearing Replenish I(Elite Enchantment, only for Helmet) all shulkers,chests and heads duplicate while mining with pickaxe. 
Also when items are in it, head, and some other stuff is all duplicated by it. 

I tried a combination or on other armor, its just replenish I as far I could see. We have the latest version. I didn't notice before because I rarely wear armor (OP Staff on server) so normally I run around without. I just kept it on from fighting bosses earlier when I noticed. 

I tested on > Netherite helmet with enchants
Diamond Helmet without enchants

Both start duping when wearing the helmet with Replenish I. 

### How to reproduce

When replenish is given as admin command they are not > When withdrawn out of /ce with XP it is. 

### Screenshots / Videos

https://youtu.be/YEAUNqGBHEI

### "/ae plinfo" link

x

**Comment by ThomasWega** [comment]
Hey! We are not able to replicate this. I'd also like to point out that we've changed the replenish enchantment to be for pickaxes rather then helmets a while ago. You'd need to recreate your config for this to take affect though.
