### ISSUE TITLE
Soulbound item dupe if we die by warden SonicBoom

### ISSUE THREAD

**Issue by MoGGaming** [GC-spigot/AdvancedEnchantments#3732]
### Describe the bug

die by warden SonicBoom while holding soulbound item

### How to reproduce

die by warden SonicBoom while holding soulbound item

### "/ae plinfo" link

https://paste.md-5.net/uceduzofoy

**Comment by ThomasWega** [comment]
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3713
