### ISSUE TITLE
DO_HARM: <HEALTH>The effect is the same as DOUBLE_DAMAGE

### ISSUE THREAD

**Issue by NEIKI19914** [GC-spigot/AdvancedEnchantments#3733]
### Describe the bug

When I use the enchantment effect like this, the actual effect is DOUBLE_DAMAGE.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/206cf008-a37d-44ae-9d90-61afae41cc47)
When WAIT:20 is added, DO_HARM will work as expected.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/e4426685-5dfb-4a70-91fc-1aebb2a99b32)
I updated the plugin but still have this issue.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/b69baec0-6c34-4c57-9376-03bd38251380)

### How to reproduce

Without using WAIT:20, the DO_HARM effect becomes DOUBLE_DAMAGE effect.

### "/ae plinfo" link

https://paste.md-5.net/kapewekoka

**Comment by ThomasWega** [comment]
Hey! I've tried doing damage 100 and it worked just fine
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/00f6d265-4469-481f-a294-f692f1c0e91f)

**Comment by NEIKI19914** [comment]
....The DO_HARM effect is the DOUBLE_DAMAGE effect for players..
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/8b40f67d-0fb5-40ed-9874-dd47366d0c48)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/d13dd480-b8e5-48ff-bb69-4fd23e9e9ca3)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/30205f8f-4519-4332-8b5e-d0ca4a5d4504)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/df611169-6b9a-4968-bdda-a698e5f65f97)

**Comment by NEIKI19914** [comment]
Only using DO_HARM on the player is double damage, it is normal for other entities....

**Comment by ThomasWega** [comment]
Hey! It works just fine. Please note that the 3 you use means 1.5 hearts.

https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/4ea54b0b-dcb8-4b2e-bad0-69fc8a7365e6

**Comment by NEIKI19914** [comment]
> Hey! It works just fine. Please note that the 3 you use means 1.5 hearts.
> 
>  2023-10-21.13-00-00.mp4

1.20.1 seems to be fine... I am purpur 1.20.2...

**Comment by NEIKI19914** [comment]
> > Hey! It works just fine. Please note that the 3 you use means 1.5 hearts.
> > 2023-10-21.13-00-00.mp4
> 
> 1.20.1 seems to be fine... I am purpur 1.20.2...

I did not change the effect, it is just an enchanting effect in the default configuration.An enchantment called permafrost.

**Comment by NEIKI19914** [comment]
> 嘿！它工作得很好。请注意，您使用的 3 表示 1.5 颗心。
> 
>  2023-10-21.13-00-00.mp4

I asked the owner of the service on this side of my area.... It seems that only 1.20.2 has such a problem...
He's on a 1.20.1 server, no problems...

**Comment by ThomasWega** [comment]
Nope, still works just fine for me even on 1.20.2 with permafrost

**Comment by NEIKI19914** [comment]
> Nope, still works just fine for me even on 1.20.2 with permafrost

Purpur-1.20.2-2076 version DO_HARM:3 @Victim still appear... But I suspect it's an issue with the core version... Quite a few other plugins of mine are not working properly on purpur-1.20.2-2084 version, or even paper-1.20.2-249...
