### ISSUE TITLE
Feature Request - Black Scroll 2.0

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3735]
### Describe the bug

Ok so, i want **Black Scroll** having more options for enchant removing. 
Like upon drag&drop it should open GUI where is all enchant listed "as books" what that item has, and you could choose the enchant you want to remove, instead of it being random, but config options should stil lhave the random option if people want that and if random is enabled, GUI wont open, it just gives the book for you.

And for more config options, keeping succes/destroy rate and random, but adding price option for setting it taking levels/exp/money when enchant is removed. 

Also enchant removing should be 2 step option, so it gives confirmation option, to prevent accidental enchant removes and this could be done just GUI where is red/green option to pressing.

And then GUI modification options, like green/red glass item change and filler item choosing, like red glass pane etc

### How to reproduce

same as above

### "/ae plinfo" link

-

**Comment by ELIAS7281** [comment]
ok so its a great idea, and i would so use it with added features like this, i have spoken to axe and just throwing ideas out there to maximize this plugins potential. And GC if your listening in on this, every mf out there loves a good auction plugin. here is what i come up with.
So there is a cost to obtaining a black scroll to be able the option to remove an enchantment on your item. So first order is to be able to afford the black scroll in the first place. Second step is applying the black scroll to the item which opens up the GUI of the item and its enchantments. Only option is (choose which enchantment you wish to remove). Once chosen another GUI pops up with options. #1 (remove this enchantment with random success/destroy rate for the full cost of the groups enchantment rate. #2 ( remove this enchantment with 100% success rate for double the original cost of the enchantment rate). #3 (cancel this transaction)

Options and features on an auction plugin is just gonna make it that much more popular and me and so much others want to utilize a auction plugin to its full potential. We already integrating our auction plugins we have with discord for max exposure. 

This project is worth it and i hope you guys look into it..

**Comment by SrMonsterYT** [comment]
this suggestion is very good I would love to see this, only I would not use the success rate and destruction of the item but it is a great suggestion and very cool

**Comment by SrMonsterYT** [comment]
has something like this been implemented?
