### ISSUE TITLE
EXP effect duping drops

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3736]
### Describe the bug

Long story short, EXP: effect will dupe items (mobs) when killed,having exp:100 effect drops about 1000 golden swords from piglins

### How to reproduce

same as above 

### "/ae plinfo" link

-

**Comment by GC-spigot** [comment]
This was a bug 30+ versions ago, however I can't recreate this now. You can DM me on discord with more info if this is happening on a recent version.

https://gyazo.com/5fe7ec0e539a04c41fd9a36230b48c27
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/13188801/e1b14eff-7205-498e-8deb-e41b20a30bc5)
