### ISSUE TITLE
Could not pass event PlayerFishEvent

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3737]
### Describe the bug

https://pastebin.com/raw/51z6CyhF

### How to reproduce

I think it happens when fishing with fishing rod with special enchantments: https://i.imgur.com/0Bl6FTZ.png

### "/ae plinfo" link

https://paste.md-5.net/ehenebihuw

**Comment by GC-spigot** [comment]
You may need to update your default enchantments.yml with new snap enchantment:
```yaml
snap:
  display: '%group-color%Snap'
  description: Pull hit entity towards you.
  applies-to: Fishing Rod
  type: CATCH_FISH
  group: ELITE
  applies:
    - FISHING_ROD
  levels:
    '1':
      chance: 15
      cooldown: 4
      conditions:
        - '%caught% = PLAYER : %allow%'
      effects:
        - PULL_CLOSER:1 @Victim
    '2':
      chance: 25
      cooldown: 6
      conditions:
        - '%caught% = PLAYER : %allow%'
      effects:
        - PULL_CLOSER:1.5 @Victim
    '3':
      conditions:
        - '%caught% = PLAYER : %allow%'
      effects:
        - PULL_CLOSER:2 @Victim


We now have a condition for it by default.

**Comment by GC-spigot** [comment]
> I already had a snap enchantment in enchantments.yml.
> 
> My enchantments.yml file: https://pastebin.com/raw/nGsusLyq

Okay then try updating :) We may have fixed issues you are having in versions between. I can't recreate this issue on latest unless the condition is removed.
