### ISSUE TITLE
Aoe targeter does not work

### ISSUE THREAD

**Issue by detoxv** [GC-spigot/AdvancedEnchantments#3738]
### Describe the bug

Created a ticket and spoke to a staff member that told me it was a bug and to submit an issue report here

It seems aoe does not work in any context, armor set events, enchantments, etc

I have tried the old formatting of <aoe> </aoe> and the new one as mentioned below and confirmed it works if i change the targeter to @Victim but @Aoe does not work

BURN:7 @Aoe{radius=7,target=all}

LIGHTNING @Aoe{radius=7,target=damageable}

Wanted this effect to work as an armor set event but had no luck

Thanks

### How to reproduce

BURN:7 @Aoe{radius=7,target=all}

LIGHTNING @Aoe{radius=7,target=damageable}

### "/ae plinfo" link

https://paste.md-5.net/lixubosedu

**Comment by GC-spigot** [comment]
Can you screenshot the enchantments or use code tags when posting them? Github by default messes with formatting when pasting and it may be something related to that - AOE is supposed to be formatted `@Aoe`. 

Also try updating as well. I've tested this just today and it was working fine.
