### ISSUE TITLE
Veinminer can dupe player head

### ISSUE THREAD

**Issue by RainfallHaruno** [GC-spigot/AdvancedEnchantments#3739]
### Describe the bug

When I use a pickaxe with veinminer (translated to Chinese in the video) to break a player head, it will dupe the head.

### How to reproduce

Try to enchant a pickaxe with veinminer and break a player head.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/143864118/509cda4c-5697-4d5c-b0c8-b2ea2e416662

### "/ae plinfo" link

https://paste.md-5.net/ilavepegah

**Comment by aXe18** [comment]
@RainfallHaruno Well first you should update your plugin and see if issue still exists :)

**Comment by GC-spigot** [comment]
Not able to reproduce on latest
