### ISSUE TITLE
trench-do-all-durab setting broken

### ISSUE THREAD

**Issue by sudokou** [GC-spigot/AdvancedEnchantments#3740]
### Describe the bug

Trench is expected to do 9 durability damage (if using a 3x3 trench) to the tool if the setting `trench-do-all-durab` is set to true. Instead, trench only does 1 damage. Changing this setting to false has no effect.

Seems this setting is broken.

### How to reproduce

Enchant a pickaxe with Trench, break stone, check item durability (use F3+H to see advanced tooltips).

### "/ae plinfo" link

https://paste.md-5.net/ewaciwited

**Comment by GC-spigot** [comment]
Fixed!
