### ISSUE TITLE
Trench problem

### ISSUE THREAD

**Issue by vladyaso** [GC-spigot/AdvancedEnchantments#3741]
### Describe the bug

In the video you can see that your trench takes away the item's durability for 1 broken block, and not for all that I broke with a pickaxe.

Some blocks, such as basalt, etc., cannot be broken by the pickaxe.

### How to reproduce

Need to get a pickaxe for the trench
and start breaking any block.
Basalt does not count as a block that can be broken with a pickaxe.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/110984772/a4b5fa2d-c2a7-4453-97cf-ceccd8a15f09)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/110984772/d14f5df0-4c90-4b2b-a464-d4dcd95657f3)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/110984772/021b9cdf-c17a-4a1c-a92e-a07262bb4368)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/110984772/8ed5ae8e-5330-4c40-9336-b02d5ca64423)
https://www.youtube.com/watch?v=rFHPMhEEr20

### "/ae plinfo" link

https://paste.md-5.net/qoquxecudo

### Server Log

There are no errors in the console

**Comment by GC-spigot** [comment]
Should be resolved now! Update :)

**Comment by vladyaso** [comment]
> Should be resolved now! Update :)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/110984772/b6be3fe8-1de2-491a-96bb-da88bb97f72a)
