### ISSUE TITLE
Remove Durability

### ISSUE THREAD

**Issue by ELIAS7281** [GC-spigot/AdvancedEnchantments#3743]
### Describe the bug

Hey guys i just want to know if it is possible to have an enchant that removes items durability From the enemys weapon So say im wearing armor that has an enchant to remove extra durability from the enemys weapon when being attacked. So say

Applies: armor
Type: Defence
Effects: Remove_Durability:2 @Attacker

if not is it possible to add. cheers 

### How to reproduce

as above

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by aXe18** [comment]
@ELIAS7281 Yes you can have this by any current dura effect, making number positive and target to Victim like ->
```
effects:
      - ADD_DURABILITY_CURRENT_ITEM:10 @Victim
```

**Comment by ThomasWega** [comment]
This effect should be updated next update so you can either use the old way

ADD_DURABILITY_ITEM:<AMOUNT>

or the new way

ADD_DURABILITY_ITEM:<SLOT>:<AMOUNT> @Target

Slot meaning like HAND, OFFHAND, CHESTPLATE etc..

**Comment by ThomasWega** [comment]
Need to reopen this lol. Somehow the code just went missing, so need to do it again. Leaving this as a reminder for me :D

**Comment by ThomasWega** [comment]
Okay, re-added it :D sorry haha
