### ISSUE TITLE
Feature Request | Making The Slot Increasers Not Limited per Group 

### ISSUE THREAD

**Issue by malusic23354** [GC-spigot/AdvancedEnchantments#3748]
### Describe the bug

Hello, I'm interested in making Slot Increasers a global feature, similar to how you can use Magic Dusts and Randomization Scrolls universally. Is there a method to enable this functionality for Slot Increasers as well? Much like how we can apply Magic Dusts to any custom enchantment by group, there's an option to disable the group-specific limit for Magic Dusts, allowing them to be applied across all groups. I'd like to achieve a similar capability with Slot Increasers, allowing any custom enchantment to be added to any Slot Increaser without being dependent on the group.

### How to reproduce

This is a Feature not a Bug

### "/ae plinfo" link

https://paste.md-5.net/ezuwosicux

**Comment by GC-spigot** [comment]
It is right now global, you can safely remove group mention in the name of it without a problem. Only difference between groups for slot increasers is the number of slots they add, but they can applied however you want.
