### ISSUE TITLE
Gkits CustomModelData

### ISSUE THREAD

**Issue by gagybrateu** [GC-spigot/AdvancedEnchantments#3749]
### Describe the bug

Hello, i have issue with CustomModelData only in Gkits menu i server is on latest version, tryed one before and still the same. Everything works on all other menus expect Gkits

### How to reproduce

CustomModelData Not working on Gkits

### "/ae plinfo" link

https://paste.md-5.net/raguvezama

**Comment by SirJben** [comment]
Hello @gagybrateu are you using this format? `customModelData: 0`. Make sure the model is working on your texture hosting.

**Comment by ThomasWega** [comment]
please send your config
