### ISSUE TITLE
REACH effect causes excessive durability loss

### ISSUE THREAD

**Issue by sudokou** [GC-spigot/AdvancedEnchantments#3750]
### Describe the bug

Created an enchant that has the REACH:5 effect. After applying this enchant to a trident, the trident will often take excessive durability loss while hitting mobs - sometimes to the extent of instantly breaking the items.

### How to reproduce

Create enchant with REACH:5 effect, apply to trident, hit zombie.

### "/ae plinfo" link

https://paste.md-5.net/asefokipip

**Comment by ThomasWega** [comment]
can you please send your enchantment?

**Comment by sudokou** [comment]
`reach:
  display: '%group-color%Reach'
  description: Increase range underwater
  applies-to: Tridents
  type: ATTACK;ATTACK_MOB
  group: EXOTIC
  applies:
  - TRIDENT
  levels:
    '1':
      condition:
      - '%damage cause% != THORNS : %allow%'
      effects:
      - REACH:5`
