### ISSUE TITLE
Anvil doesn't support applying book AND renaming item simultaneously

### ISSUE THREAD

**Issue by sudokou** [GC-spigot/AdvancedEnchantments#3751]
### Describe the bug

AE managed anvil is enabled. When applying an enchanted book to an item, user cannot simultaneously rename item. You can see the output in the anvil before completing the action - the resulting item shows no name change, even if user types in custom name in anvil GUI.

### How to reproduce

Enable AE managed anvils. Put sword in anvil along with any valid sword enchant book (tested with bane of arthropods). Type in custom name. You will see the output box flicker, showing the custom name for a second, before reverting back to the default item name.

### "/ae plinfo" link

https://paste.md-5.net/asefokipip

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
