### ISSUE TITLE
Enchant is taking up most resources from all other plugins

### ISSUE THREAD

**Issue by Tizooo** [GC-spigot/AdvancedEnchantments#3752]
### Describe the bug

this enchant is taking up way more resources then anything else i have on my server:
graben:
  display: '%group-color%Graben'
  description: "Zerstört Blöcke in einem 3x3-Bereich."
  applies-to: Pickaxes, Shovels
  type: MINING
  group: EPISCH
  applies:
    - ALL_PICKAXE
  levels:
    '1':
      effects:
        - BREAK_BLOCK @Trench{r=3}

spark report: https://spark.lucko.me/69BJ1Tn1VX

- also updated to the newest version but this issue is still there.

### How to reproduce

use the enchant very much 

### "/ae plinfo" link

https://paste.md-5.net/acociyoniw

**Comment by GC-spigot** [comment]
So it seems like other plugins are taking up high percentages, but your TPS solid 20/20. Our "high usage" is not causing any lag, it's just that part of what makes your server run, that's how much it takes up.

We actually found some improvements we can do with this immediately. Try next update, it will be better :) But I can promise you this is not lag. What causes the biggest % of this performance is actually us telling other plugins that blocks were broken with trench, and them processing those block breaks is included in overall total percentage - we can't do anything about that.

Anyway, we have found an improvement we can do, it will be available next update. Thanks for the report!
