### ISSUE TITLE
Feature Request to block/stattarck

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3753]
### Describe the bug

Add new features to block and stattarck. So basically option to give preset trackers.
like /ae  giveitem <player> blocktrack 1 32400 <- here last number will be the blocks "mined" already or 
add command like /ae set blocktrack <amount> while holding item in hand where is tracker to set count for it 

### How to reproduce

same as above 

### "/ae plinfo" link

-

**Comment by ThomasWega** [comment]
/ae giveitem blocktrack 1 N
/ae giveitem stattrak 1 N

Will be added in the next update!
