### ISSUE TITLE
Feature Request - New effect

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3754]
### Describe the bug

New effect what is similiar to SPAWN_ARROWS but you could choose the item spawned from above. 
Like SPAWN_ITEM:DRIPSTONE:10 or SPAWN_ITEM:ANVIL:, here the last number will be the amount, so full effect will be 
SPAWN_ITEM:<MATERIAL>:<AMOUNT>
This could be usefull pvp enchant 

### How to reproduce

same as above 

### "/ae plinfo" link

-

**Comment by ThomasWega** [comment]
Added SPAWN_BLOCKS:<MATERIAL>:<DAMAGE> effect!
