### ISSUE TITLE
Incompatibility with Protectionstones plugin

### ISSUE THREAD

**Issue by EntonLCZ** [GC-spigot/AdvancedEnchantments#3756]
### Describe the bug

Hello, I have a dupe compatibility problem with the Protectionstones plugin, breaking protection blocks with a 3x3 mining pickaxe gives me the protection but also duplicates the mineral with which the protection is made.

### How to reproduce

place a protection (gold or any mineral) and chop with the pickaxe with the 3x3 mining enchantment, at this moment it will give you the protection in the inventory and in the world it will drop a block of the chopped object

### Screenshots / Videos

[ASD](https://drive.google.com/file/d/1YBR-hPeV_CRDdZ1ugxjp0x7CHu273pLQ/view?usp=sharing)

### "/ae plinfo" link

https://paste.md-5.net/esajizebeg

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
