### ISSUE TITLE
The Standard Enchantment Replanter doesn't work on a Plot from Plotsquared Plugin

### ISSUE THREAD

**Issue by Schauniix** [GC-spigot/AdvancedEnchantments#3757]
### Describe the bug

Hey I bought the Plugin and we are currently using the enchantment replanter on our server, which automatically plants crops when u break them, but it doesn't work on a Plot created with the Plugin Plotsquared. It's a standard Enchantment.

Version AE Plugin: AdvancedEnchantments-9.5.5
Version Plotsquared Plugin: PlotSquared v7 7.1.0

Enchantment:

replanter:
  display: '%group-color%Nachpflanzer'
  description: Pflanzt Pflanzen nach beim Ernten.
  applies-to: Hacke
  type: MINING
  group: EINZIGARTIGE
  applies:

ALL_HOE
levels:'1':
    conditions:
'%is crop% = false : %stop%'
'%is fully grown% = false : %stop%'
effects:
PLANT_SEEDS:0:%block drop type%

### How to reproduce

Step by Step:

1. Create Plotworld with Plotsquared
2. Take the Enchantment but in on a Hoe
3. Make a Wheat or Carrot or other Crops field and use the hoe.
Doesn't work or it works just a few instead of anytime.

If you want you can put exactly my enchantments on the hoe.

### Screenshots / Videos

<img width="382" alt="image" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/149617525/23401dd1-6a44-4a7e-91db-849bcac80f31">

### "/ae plinfo" link

https://paste.md-5.net/erutuyonur

**Comment by Schauniix** [comment]
> Collaborator

Of course just a sec :)

**Comment by Schauniix** [comment]
I uploadet it here

> Hey! If you could send a video, that'd be great

I uploadet it here: it's active for 12 hours:  https://workupload.com/file/spb9rX8jbeu

**Comment by Schauniix** [comment]
> Hey! If you could send a video, that'd be great

Hey I uploadet it here: https://workupload.com/file/2fVZ339NBGa

I think its not working because of Aureliumskills or Plotsquared Plugin not sure.

**Comment by Schauniix** [comment]
I think it's not because of the AureliumskillsPlugin. Because now it magically works and sometimes it just stops working :(

Link: https://workupload.com/file/2n4qw83wnns

The Videos are available for 12h only

**Comment by ThomasWega** [comment]
AureliumSkills are causing issues everytime. I doubt this is issue with us but rather AureliumSkills issue. It is like this everytime
