### ISSUE TITLE
Enchanting Table Completely Broken

### ISSUE THREAD

**Issue by sudokou** [GC-spigot/AdvancedEnchantments#3759]
### Describe the bug

User reported today - and verified by multiple other users including myself - the enchantment table is broken. (Putting an item in the enchantment table does not do anything, no enchantments appear).

Disabling AE's enchantment table support fixes the issue. So, issue is caused by enchantment table support in AE.

### How to reproduce

Make sure Enchantment Table Support is enabled (enchantmentTable.yml). Place enchantment table in-game and put any item into the table. Nothing happens.

### "/ae plinfo" link

https://paste.md-5.net/rodavocona

**Comment by ThomasWega** [comment]
Will be fixed in the next update
