### ISSUE TITLE
Obtaining items illegally

### ISSUE THREAD

**Issue by jhqwqmc** [GC-spigot/AdvancedEnchantments#3760]
### Describe the bug

Using telepathy enchantment will Obtaining items illegally
TP_DROPS @Block this effect

### How to reproduce

![](https://www.dropbox.com/scl/fi/vnfk5t0nfoy2uak0e57eq/QQ2023112-153555-HD.mp4?rlkey=lea4in7u3u6rwqcqdzaisnl29&dl=1)

If this block can be destroyed instantly, it can be Obtaining illegally

### Screenshots / Videos

https://www.dropbox.com/scl/fi/vnfk5t0nfoy2uak0e57eq/QQ2023112-153555-HD.mp4?rlkey=lea4in7u3u6rwqcqdzaisnl29&dl=1

### "/ae plinfo" link

https://paste.md-5.net/equdutuxic

**Comment by ThomasWega** [comment]
Should be fixed in the next update!
