### ISSUE TITLE
AE keeps starting then stopping for no reason idk how to fix it 

### ISSUE THREAD

**Issue by uhm1** [GC-spigot/AdvancedEnchantments#3762]
### Describe the bug

its just starting and stopping idk how to fix it at all 

### How to reproduce

idk

### "/ae plinfo" link

wont let me it will say An internal error occurred to preform this command

### Server Log

https://mcpaste.io/ef7b0161f55c1542

**Comment by uhm1** [comment]
Ive tried to use this plugin on multiple servers all its saying is the same thing
its on 1.20.1 paperMC

**Comment by uhm1** [comment]
my friend who also owns advanced enchants just said he put it on his server and it just worked his version is also 1.20.1 but its on spigot

**Comment by aXe18** [comment]
@uhm1 Open ticket on our discord, reading the log tells what to do :D This is not bug

**Comment by uhm1** [comment]
i dont have discord sorry

**Comment by uhm1** [comment]
can u tell me what to do here?

**Comment by uhm1** [comment]
pls?

**Comment by aXe18** [comment]
@uhm1 I cant, opening ticket on our discord is only way i can handle this

**Comment by uhm1** [comment]
Oh okay 
why is it ur only way tho?
