### ISSUE TITLE
Timber hasn't work on nether trees

### ISSUE THREAD

**Issue by Oraniacz** [GC-spigot/AdvancedEnchantments#3763]
### Describe the bug

The timber enchant does not work on netherite trees

### How to reproduce

1. Break Fungus or Crimson tree with a Timber Axe

### Screenshots / Videos

https://drive.google.com/file/d/1ljc_C752oARwCZGd-rF5A196pRjJvFR5/view?usp=sharing

### "/ae plinfo" link

newest version of the plugin (v9.5.5)

**Comment by aXe18** [comment]
@Oraniacz Make `stems-count-as-trees: true` in `config.yml` and it will work just fine ;)
