### ISSUE TITLE
Dupe of gold ingot

### ISSUE THREAD

**Issue by vladyaso** [GC-spigot/AdvancedEnchantments#3767]
### Describe the bug

AE 9.4.16
Paper 1.16.5

### How to reproduce

You need to enchant the pickaxe to automatically smelt ore

MATERIAL BLOCK NETHER_GOLD_ORE

### Screenshots / Videos

https://imgur.com/a/iiJvooR

### "/ae plinfo" link

https://paste.md-5.net/iyuwoceyol

### Server Log

no logs

**Comment by vladyaso** [comment]
> What's the issue exactly?

From the NETHER_GOLD_ORE block when enchanting a smelting I get GOLD_INGOT, more than I get GOLD_NUGGETS

**Comment by ThomasWega** [comment]
What values have you encountered while testing? Can you send a video comparison please?

**Comment by vladyaso** [comment]
https://youtu.be/il2rq3wguwQ

> What values have you encountered while testing? Can you send a video comparison please?

**Comment by vladyaso** [comment]
Is this some kind of joke?
