### ISSUE TITLE
Send an announcement to everyone in the game when you open a spell book

### ISSUE THREAD

**Issue by ttt0** [GC-spigot/AdvancedEnchantments#3771]
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66686400/ee7c6d79-fb2e-4eee-a299-d0531cb2a9e2)
An announcement that when a spellbook is opened, everyone in the game can see what comes out.
It would be great if it was added to the location in the photo ^^

### How to reproduce

suggestion

### Screenshots / Videos

suggestion

### "/ae plinfo" link

suggestion

**Comment by ThomasWega** [comment]
in API there is a BookOpenEvent. You can do this yourself if you know how to code.
