### ISSUE TITLE
Quickly break custom blocks in the Itemsadder, TP_DROPS effect will spawn a large number of note boxes.

### ISSUE THREAD

**Issue by NEIKI19914** [GC-spigot/AdvancedEnchantments#3772]
### Describe the bug

Breaking the Itemsadder's custom blocks with an enchantment of 5 will spawn a large number of note boxes TP_DROPS the effect.

### How to reproduce

If the destruction rate is fast enough, TP_DROPS will spawn a large number of note blocks in the inventory.
My plugin version AdvancedEnchantments-9.5.7 ItemsAdder_3.6.2-beta-r2

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/65b92a87-f245-49a8-a6d1-09eedd86343a

### "/ae plinfo" link

https://paste.md-5.net/orimokogog

**Comment by ThomasWega** [comment]
Should be fixed in the next version!
