### ISSUE TITLE
Dupe Bug! Urgent Attention needed!

### ISSUE THREAD

**Issue by ChefJisoo** [GC-spigot/AdvancedEnchantments#3773]
### Describe the bug

When using the healers hatchet command - will add the config for this dont worry, you can break the right side of a double chest and the items come out, then break the last single chest and the same items come out

healershatchet:
  display: "%group-color%♦ &fHealers Hatchet"
  description: "Chance to break an entire tree."
  applies-to: "Axes"
  type: "MINING"
  group: "MAGNIFICENT"
  applies:
    - ALL_AXE
  levels:
    1:
      chance: 4
      cooldown: 45
      effects:
        - "BREAK_TREE"
    2:
      chance: 5
      cooldown: 40
      effects:
        - "BREAK_TREE"
    3:
      chance: 5
      cooldown: 35
      effects:
        - "BREAK_TREE"
    4:
      chance: 6
      cooldown: 30
      effects:
        - "BREAK_TREE"
    5:
      chance: 8
      cooldown: 35
      effects:
        - "BREAK_TREE"

### How to reproduce

Use my enchant i attached and create a double chest. put an item in the chest and mine the right side of the chest. The item should come out, and then if you break the left side (now a single chest) the same item will come out again.

### Screenshots / Videos

https://youtu.be/xYC5pRcSwlY 
 A player made this video ^

### "/ae plinfo" link

https://paste.md-5.net/depicagene

### Server Log

https://mclo.gs/kBWuReQ#L1465

**Comment by aXe18** [comment]
@ChefJisoo Update your plugin

**Comment by ThomasWega** [comment]
Yes, please do so

**Comment by ChefJisoo** [comment]
> Yes, please do so first. Then let us know if the issue still persists :)


issue still exsists. please reopen this.

**Comment by ChefJisoo** [comment]
> Yes, please do so first. Then let us know if the issue still persists :)

thanks a lot, is there any more info from me you would need?

**Comment by ThomasWega** [comment]
No. It's not still present. I've just tested exactly the same and all works good. I know we've had this issue but it was fixed some time ago

**Comment by ChefJisoo** [comment]
> No. It's not still present. I've just tested exactly the same and all works good. I know we've had this issue but it was fixed some time ago

No.... it definitely is still there....

**Comment by aXe18** [comment]
@ChefJisoo update your plugin....

**Comment by ChefJisoo** [comment]
I literally said I did so don't keep saying that. it is the most updated version. it is bugged.
