### ISSUE TITLE
Armor trims dont work

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#3776]
### Describe the bug

If you have a gkit with an armor trim set (e.g armor-trim: 'IRON;SILENCE'), when you give yourself the gkit, it does not spawn with the trim

### How to reproduce

1) Make gkit with armor trim
2) Give yourself gkit

### "/ae plinfo" link

https://paste.md-5.net/rahekupofe

**Comment by ThomasWega** [comment]
duplicae of #3691
