### ISSUE TITLE
ITEM_BREAK will not be activated

### ISSUE THREAD

**Issue by axeldupuy** [GC-spigot/AdvancedEnchantments#3777]
### Describe the bug

If an enchantment has the activator type: ITEM BREAK and is destroyed by the effect ADD_DURABILITY_ARMOR:-15 @Victim the effect of the enchantment with the activator type: ITEM_BREAK will not be activated

### How to reproduce

If an enchantment has the activator type: ITEM BREAK and is destroyed by the effect ADD_DURABILITY_ARMOR:-15 @Victim the effect of the enchantment with the activator type: ITEM_BREAK will not be activated

### Screenshots / Videos

a

### "/ae plinfo" link

a

**Comment by ThomasWega** [comment]
Should be fixed in update!
