### ISSUE TITLE
KILL effect

### ISSUE THREAD

**Issue by ELIAS7281** [GC-spigot/AdvancedEnchantments#3779]
### Describe the bug

Hey guys, a ticket came across about the KILL effect destroying armor as well. Is it possible to have the kill effect @victim to kill the player but not destroy the armor in the process. There was a work around with %victim name% but I believe the kill effect should be default kill player only. Correct me if I’m wrong. Cheers guys.

### How to reproduce

Add enchantment on a sword with the kill effect, kill a player with armour on.

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ThomasWega** [comment]
REMOVE_HEALTH_DAMAGE:100000
