### ISSUE TITLE
enchant that will use all available soul

### ISSUE THREAD

**Issue by RageOfFire** [GC-spigot/AdvancedEnchantments#3780]
### Describe the bug

Hope AE make it possible to create a enchant that will use all available soul to transfer to some effect for example:
```yml
ADD_HEALTH:<All Soul Available>
```

### How to reproduce

N/A

### "/ae plinfo" link

N/A

**Comment by ThomasWega** [comment]
Hey! Just use %souls on item% placeholder

**Comment by RageOfFire** [comment]
> Hey! Just use %souls on item% placeholder with REMOVE_SOULS effect

Didn't know this exist XD where can I find all available placeholder like this ? All I found is here https://wiki.advancedplugins.net/abilities/variables
