### ISSUE TITLE
Bait enchantment doesn't work

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3783]
### Describe the bug

Bait enchantment on fishing rod doesn't work

### How to reproduce

1. Try to catch a fish using fishing rod that have bait enchantment
2. Only one item will drop instead two (tried 9 times)

### "/ae plinfo" link

https://paste.md-5.net/uveranebev

**Comment by ThomasWega** [comment]
Hey! Works just fine for us. Just tested
