### ISSUE TITLE
Some enchantments doesn't work

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3784]
### Describe the bug

Some enchantments are broken in the latest versions.

For example: Chunky or Frozen enchantment

### How to reproduce

1. Put armor on yourself with Chunky or Frozen enchantment
2. The enchantment will not work

### "/ae plinfo" link

https://paste.md-5.net/vubaxuqeja

**Comment by ThomasWega** [comment]
They work just fine
