### ISSUE TITLE
Effect EXP Error

### ISSUE THREAD

**Issue by mk9395** [GC-spigot/AdvancedEnchantments#3785]
### Describe the bug

I have an enhancement that increases EXP when killing monsters, and currently it is reporting an error on the console

### How to reproduce

I'm using inquisitive: inquisitive
When destroying monsters, there will be a chance to receive more EXP, but currently when the player destroys monsters, the system reports the following error:

> [AdvancedEnchantments] §4Failed to activate effect '§fEXP:9'
> [AdvancedEnchantments] §cAdditional information: §7Error while activating effect

Here my config enchantment:

> inquisitive:
>   display: '%group-color%Lão Luyện'
>   description: Tăng EXP khi giết mob.
>   applies-to: Kiếm
>   type: KILL_MOB
>   group: ELITE
>   applies:
>   - ALL_SWORD
>   levels:
>     '1':
>       chance: 13
>       cooldown: 12
>       effects:
>         - EXP:<random number>3-5</random number>
>     '2':
>       chance: 26
>       cooldown: 14
>       effects:
>         - EXP:<random number>5-7</random number>
>     '3':
>       chance: 39
>       cooldown: 16
>       effects:
>         - EXP:<random number>7-9</random number>
>     '4':
>       chance: 52
>       cooldown: 18
>       effects:
>         - EXP:<random number>9-11</random number>

### "/ae plinfo" link

https://paste.md-5.net/adiwoyedoy

### Server Log

https://mclo.gs/4H7AOTB

**Comment by ThomasWega** [comment]
Will be fixed in the next version!
