### ISSUE TITLE
alchemist suggestion

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3788]
### Describe the bug

add the option in the alchemist to be able to use customized level EXP, there is only the option of EXP points and money, please add the option of level EXP in the alchemist.yml

### How to reproduce

alchemist.yml

general:
  settings:
    # The alchemist should accept books.
    # If false, the alchemist will not accept books.
    combine-books: true
    # The alchemist should accept dust.
    # If false, the alchemist will not accept dusts.
    combine-dust: false
    books:
      # This method adds chances together and splits by 2 (x+y/2)
      add-up-chances: false
      pre-set-chances:
        enabled: false
        success: 50
        destroy: 50
    dusts:
      # This method just adds up chances together
      add-up: false
    price:
      # Set false to use money economy instead of XP.
      experience: true
      # If true the plugin will calculate the price.
      let-plugin-count: true
      # Your custom price here.
      # Only works if let-plugin-count is true
      custom-price: 250
    other-items-slot:
      first-item-slot: 3
      second-item-slot: 5
      
    add a customized XP level option, e.g. charge 10 exp level to perform a combination of enchantments

### "/ae plinfo" link

no error

**Comment by ThomasWega** [comment]
new LEVEL economy has been added and the alchemist config will be updated to support all economies in the next update

**Comment by SrMonsterYT** [comment]
> new LEVEL economy has been added and the alchemist config will be updated to support all economies in the next update

Is it already available in this version? 9.5.10

**Comment by ThomasWega** [comment]
No
