### ISSUE TITLE
Chat Spam & Console Spam Error

### ISSUE THREAD

**Issue by TylorTurner** [GC-spigot/AdvancedEnchantments#3789]
### Describe the bug

Loading in new chunks I get this error consistently. 
I reset my loot config and loaded up my settings and still got the same error/spam.
"Failed to generate Advanced Enchantments Random Loot for item RANDOM_ENCHANT_BOOK: error is located in console."

PaperMc 1.19.4 - Latest
AE 9.5.9.Jar - Latest

### How to reproduce

Use my loot configuration settings and start flying.

Loot Config > https://mcpaste.io/7713ec072dfb8524

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/133236597/4ead31bb-f6d4-4c71-82c1-3bb8e8f1395d)

### "/ae plinfo" link

https://paste.md-5.net/wagezudixu

### Server Log

https://mcpaste.io/79f9df94a0377f8a

**Comment by ThomasWega** [comment]
Not able to replicate this. The issue might lie somewhere else then with lootConfiguration. Try recreating all your files and then you should be good

**Comment by TylorTurner** [comment]
Can you try my enchantments.yml, I allowed all enchantments and had 0 spam. When I # Some enchantments it spams.

https://mcpaste.io/3811b5340f4a8ac3
