### ISSUE TITLE
Bug with Shift file of oraxen in AE Gui

### ISSUE THREAD

**Issue by lythongpy** [GC-spigot/AdvancedEnchantments#3790]
### Describe the bug

The shift file is not match with the default rank of oraxen plugin. When i add in the shift file of AE Gui it remove the texture of the default rank system. 

### How to reproduce

i found out that it had something to do with the code: of the shift file. The new update of oraxen replaced the code: with char: and now it mess up with lots of default stuff of oraxen. 

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1172758795492003860/1172760720593662012/image.png?ex=65617d88&is=654f0888&hm=dea2da9bb727c8a3ccfa0881c603fdb887c57b6db7d1ba1f3fd59c604601f9b2&

https://media.discordapp.net/attachments/1172758795492003860/1172758862479249488/image.png?ex=65617bcd&is=654f06cd&hm=575ccd9546d68ca98da0eaa9e0e2f0c2b8617dcba81c4b93ac8ac5cd723d3540&=&width=567&height=468

### "/ae plinfo" link

https://paste.md-5.net/ibovofibaj

**Comment by ELIAS7281** [comment]
just to comment that it was the second ticket about the same thing when this was reported, i wasnt sure of the issue so i requested a github report.

**Comment by Denis485** [comment]
Happening on Advanced Pets aswell. 
https://imgur.com/a/G7bgX5A
