### ISSUE TITLE
Overload Extra Hearts Drain & Have To Refill Upon Switching Worlds

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#3791]
### Describe the bug

In previous versions of the plugin, you would keep your Overload health when switching between worlds. Your extra hearts would not drain and have to refill when you move to another world. Now, whenever you switch worlds, your extra hearts completely drain and have to refill. In addition to being inconvenient, this is extra problematic as it causes players to need to eat more often than they otherwise would.

### How to reproduce

1.) Apply Overload enchant to a piece of armor
2.) Wear the armor
3.) Switch worlds

### Screenshots / Videos

Video Demonstration:
https://youtu.be/a4wvsvUrwf0

### "/ae plinfo" link

https://paste.md-5.net/lamuvezepe

**Comment by ThomasWega** [comment]
Will be fixed in one of the next updates!
