### ISSUE TITLE
Cannot invoke "org.bukkit.block.Block.getType()

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3793]
### Describe the bug

using the inquisitive enchantment that gives more experience when killing mobs gives this error on the console and in the game chat

error: https://prnt.sc/cB6fH-M8zcK-
error chat: https://prnt.sc/YdarYd0v3BAh

### How to reproduce

use the inquisitive enchantment on 1 sword and kill 1 mob

### "/ae plinfo" link

https://paste.md-5.net/kivufayocu

**Comment by ThomasWega** [comment]
Please wait for the next update. It will be fixed there
