### ISSUE TITLE
SlimeFun and AdvancedEnchantments conflict

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3794]
### Describe the bug

when I put this slimefun enchantment on 1 item, and then try to put the same AdvancedEnchantments enchantment on it, it deletes the slimefun enchantment, but if I do the opposite, both items remain.

### How to reproduce

video bug: https://youtu.be/h-LAxYq7T-U

### "/ae plinfo" link

https://paste.md-5.net/lowoxuzedi

**Comment by ThomasWega** [comment]
What if you try only with AE soulbound?

**Comment by SrMonsterYT** [comment]
> Yeah, this makes sense. We both give the item back. I don't see why you would use two soulbounds at once

people who don't remove this could be the server duped by adding these 2 enchantments together

**Comment by ThomasWega** [comment]
Correct
