### ISSUE TITLE
Add region blocking

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#3796]
### Describe the bug

Some enchantments can have effects even in areas protected with worldguard and I would also like to make it so that some regions cannot use certain enchantments.

An option in the enchantment file itself would be nice:

region-deny:
  - world
  - survival

and mark the regions of the wordguard where we do not want that enchantment.

But they can be put in the same yml of enchantments, so we can block the ones we want

### How to reproduce

It is a suggestion, since we need it.

### "/ae plinfo" link

https://paste.md-5.net/tikepaqeco

**Comment by ThomasWega** [comment]
Hey! Just use conditions with WorldGuard placeholders and don't allow the enchantment if in some region

**Comment by Z3r0xh** [comment]
It works but halfway, if you come with the enchanted item from outside the region and you enter it it still works, you have to unequip it and equip it again so it doesn't work

> Hey! Just use conditions with WorldGuard placeholders and don't allow the enchantment if in some region

**Comment by ThomasWega** [comment]
What's the whole enchantment you use?

**Comment by SirJben** [comment]
\\

> What's the whole enchantment you use?

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63577950/cb254d0e-cf17-425f-90d9-45e637ad83ae)

**Comment by SirJben** [comment]
`%worldguard_region_name% = spawn : %stop%`
from his ticket.

**Comment by ELIAS7281** [comment]
yes i can confirm when i tested that an item enchanted before entering the region still has the effect when entering

**Comment by ThomasWega** [comment]
Well the effect is obviously not going to stop when it's EFFECT_STATIC. We check for the placeholders only on equip/unequip. You can try with REPEATING trigger. That might work

**Comment by Z3r0xh** [comment]
Ok, I'm going to try what you told me, the only thing is that I have to find a way to apply it to everyone, since I want to remove the customs for events by region. That's why I asked if some type of denial could be created by region.****

**Comment by Z3r0xh** [comment]
> Well the effect is obviously not going to stop when it's EFFECT_STATIC. We check for the placeholders only on equip/unequip. You can try with REPEATING trigger. That might work
In type do I then have to put REPEATING in all the enchantments that I want to block?

**Comment by ThomasWega** [comment]
All I am saying is that EFFECT_STATIC parses the placeholders only when you equip/unequip the armor off. So obviously the effect won't be deactivated when you enter a region. You may try REPEATING enchantment instead of EFFECT_STATIC. Other triggers like MINING etc.. should work just fine

**Comment by Z3r0xh** [comment]
Perfect!
