### ISSUE TITLE
Translate enchantment level

### ISSUE THREAD

**Issue by BrayaanPS** [GC-spigot/AdvancedEnchantments#3797]
### Describe the bug

You could add an option to translate the enchantment levels. Since it only allows to use in number or roman numeral.

### How to reproduce

suggestion.

### Screenshots / Videos

https://i.imgur.com/Dm2MuLI.png

### "/ae plinfo" link

https://i.imgur.com/Dm2MuLI.png

**Comment by GC-spigot** [comment]
We'll look into this
