### ISSUE TITLE
[Feature Request] Stacked items in Essentials Kits Addon

### ISSUE THREAD

**Issue by mclegendary1** [GC-spigot/AdvancedEnchantments#380]
Bug in EssentialsXKitAddon
*Screenshot*
![2019-03-14_19 26 20](https://user-images.githubusercontent.com/32602514/54382780-f61f6b80-4690-11e9-8e8f-89f562051f3a.png)

*Description*
Can't get in stack potions and another items, what can't be stacked. EssentialsX have that functiont(on screenshot) for this, but it doesn't work with new kit addon.
![ffffff](https://user-images.githubusercontent.com/32602514/54383010-704ff000-4691-11e9-8d14-b6a469537c28.png)

**Comment by GC-spigot** [comment]
It's not a bug/issue, it's a feature request.

**Comment by mclegendary1** [comment]
I'm sorry
