### ISSUE TITLE
Armor durability depletion

### ISSUE THREAD

**Issue by Gilthunderx** [GC-spigot/AdvancedEnchantments#3800]
### Describe the bug

Whenever im using a pickaxe with CE, it slowly damages my armors durability even the armor has no CE in it.

### How to reproduce

Reforged CE on the pickaxe.
and mine continuously and you will notice your armor slowly breaking

### "/ae plinfo" link

https://paste.md-5.net/oqazarejom

**Comment by SirJben** [comment]
Hello @Gilthunderx open a ticket and send your enchantments.yml

**Comment by ThomasWega** [comment]
Will handle the issue at https://github.com/GC-spigot/AdvancedEnchantments/issues/3804
