### ISSUE TITLE
bug enchantments

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3801]
### Describe the bug

this enchantment does not respect griefPrevention protection

Immolation
Set all mobs in radius on fire.
Swords
Ultimate

plummet
Deal damage to nearby mobs when taking fall damage.
Boots
Ultimate

for example the kill-aura enchantment that damages the mobs around it respects the protection while these 2 do not

image Immolation: https://prnt.sc/6MB2qdkjX7Cu
image plummet: https://prnt.sc/Wos9IAwBK6U9

The killaura enchantment is not working properly.
only particles come out of the ground and kill only 1 mob

image killaura: https://prnt.sc/Cwma_8Jaih5-

enchantment is not defending against the wither effect, the level is at 100%
enchant: unholy

image unholy: https://prnt.sc/KdL9qAkMvC5E

### How to reproduce

all enchantments have been tested and these bugs happen some don't work and others don't respect the protection

### "/ae plinfo" link

AE: 9.5.10
Git Revision: 79ddde03
Server: git-Pufferfish-27 (MC: 1.20.1)
API: 1.20.1-R0.1-SNAPSHOT
Java: 21.0.1

**Comment by SrMonsterYT** [comment]
unholy:
  display: '%group-color%Unholy'
  description: |-
    Defend with weakness and wither effects.
  applies-to: Armor
  type: DEFENSE
  group: LEGENDARY
  applies:
    - ALL_ARMOR
  levels:
    '1':
      chance: 10
      effects:
        - POTION:WITHER:0:60 @Attacker
        - POTION:WEAKNESS:0:100 @Attacker
    '2':
      chance: 20
      effects:
        - POTION:WITHER:1:60 @Attacker
        - POTION:WEAKNESS:0:5 @Attacker
    '3':
      chance: 30
      effects:
        - POTION:WITHER:1:60 @Attacker
        - POTION:WEAKNESS:0:100 @Attacker
    '4':
      chance: 50
      effects:
        - POTION:WITHER:1:60 @Attacker
        - POTION:WEAKNESS:0:100 @Attacker
    '5':
      effects:
        - POTION:WITHER:1:60 @Attacker
        - POTION:WEAKNESS:0:100 @Attacker

**Comment by ThomasWega** [comment]
The first issue should be fixed. If you have a different issue, please create a new github issue
