### ISSUE TITLE
Night vision enchantment bugs when you wear and unwear helmet

### ISSUE THREAD

**Issue by SMARTSZK** [GC-spigot/AdvancedEnchantments#3803]
### Describe the bug

enchantment  with potion effects bugs when you wear and unwear armor

### How to reproduce

I inserted youtube links with detailed info

### Screenshots / Videos

https://www.youtube.com/watch?v=yFGs7dpPM2M&feature=youtu.be
https://www.youtube.com/watch?v=_HbRprec-sg

### "/ae plinfo" link

https://paste.md-5.net/ehujoxijag

**Comment by ThomasWega** [comment]
Hey! I've just tried it exactly the same way and I am unfortunately not able to replicate it
