### ISSUE TITLE
Items loosing durability

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3804]
### Describe the bug

For some reason, items just start to drop durability until they broke and there is nothing I can do to stop it.

The bug starts suddenly. Once it started, it don't stop anymore, the player have to unequip the armor or items. The odd thing is the player can use a not enchanted item, like a iron armor with no enchants on it and the durability will drop until broke all the pieces.

### How to reproduce

I can't tell exaclty how to start the bug, either my players. But it started to happen when I update my jar version from **9.4.13** to **9.5.7**. After that I tried the 9.5.10 but didn't fixed.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/66658478/7d136197-5807-4dad-a026-ff67f052a29b

https://github.com/GC-spigot/AdvancedEnchantments/assets/66658478/343a2bdb-42c2-4275-90bc-ca8397905082

So here is possible to see that the set is breaking. In this video is a normal netherite armor with a resource pack, but it happens with all kind of items.

### "/ae plinfo" link

https://paste.md-5.net/ropatiseri.css

**Comment by austv** [comment]
Notice that #3800 has a similar issue, but with a enchantment. This issue brings some videos

**Comment by ThomasWega** [comment]
Hey! This most likely needs to be a plugin conflict, as I don't see any way how this could happen from only AE. Do you mind trying with only latest AE on a clean server?

**Comment by austv** [comment]
> Hey! This most likely needs to be a plugin conflict, as I don't see any way how this could happen from only AE. Do you mind trying with only latest AE on a clean server?

@ThomasWega Sure, I will provide a test tomorrow.

**Comment by austv** [comment]
I still didn't have time to test, but, I compared the same plugins from my issue and #3800

    **CoreProtect:
    CraftingStore:
    Essentials:
    GSit:
    GriefPrevention:
    LuckPerms:
    Multiverse-Core:
    PlaceholderAPI:
    PlayerWarps:
    ProtocolLib:
    TAB:
    Vault:
    ViaBackwards:
    ViaVersion:
    Votifier:
    VotingPlugin:
    Vulcan:
    WorldEdit:
    WorldGuard:
    WorldGuardExtraFlags:
    antiRedstoneClock:
    mcMMO:**

maybe this information can help, but I don't think is a incompability since the bug start to happen when I updated AE

**Comment by austv** [comment]
# UPDATE!
A player help me to simulate a pvp and we reproduced the bug.
https://github.com/GC-spigot/AdvancedEnchantments/assets/66658478/ab666aec-32df-4d0d-a994-e78938417055

We tried without plugins and with plugins and in the end, I think there is some incompatibility.

# Testing pluins:

No bug with these plugins: https://paste.md-5.net/orocabixum

Bug active with these plugins: https://paste.md-5.net/canetulipo.css

Comparing the plugins above with the other issue, the similar plugins is:
Essentials
LuckPerms
Multiverse-Core
PlaceholderAPI
ProtocolLib
Vault
ViaBackwards (can't be)
ViaVersion (can't be)
WorldEdit
WorldGuard

**Comment by ThomasWega** [comment]
Hey! It's good that you were able to replicate the issue. I'd ask you to please find the exact plugin which causes the issue now

**Comment by austv** [comment]
@ThomasWega After a hard work, we find out that is a incompatibily with PlaceholderAPI. I dropped everyplugin until it's only placeholder, tried different versions and that's it, that's the plugin.

I was previous using AE 9.5.10 and PlaceholderAPI 2.11.3, but I also tried with latest AE (9.5.15) and PlaceholderAPI (2.11.5).
I forced a combat with another player to reproduce the bug

**Comment by ThomasWega** [comment]
This seems super weird. If you try latest versions of both plugins, does this still happen? PAPI conflict doesn't really make sense
