### ISSUE TITLE
TRENCH DUPE BUG

### ISSUE THREAD

**Issue by Bunnky** [GC-spigot/AdvancedEnchantments#3806]
### Describe the bug

Items dupe when using the Trench enchant

### How to reproduce

Add Trench to a pickaxe, try and break a Slimefun machine that is effected by the Trench 3x3 breaking.

### Screenshots / Videos

https://streamable.com/x68cgn

### "/ae plinfo" link

https://paste.md-5.net/tikoqecubu

### Server Log

N/A

**Comment by GC-spigot** [comment]
Fixed!
