### ISSUE TITLE
Turn off invincible not working

### ISSUE THREAD

**Issue by Xeroclon** [GC-spigot/AdvancedEnchantments#3807]
### Describe the bug

Creating an enchantment and using the invincible effect activates the invincible but does not turn it off

### How to reproduce

prueba123:
  display: '%group-color%Piromanía'
  description: 'prueba123'
  applies-to: 'Espadas'
  group: 'ULTIMATE'
  type: 'RIGHT_CLICK;RIGHT_CLICK_ENTITY'
  applies:
    - 'ALL_SWORD'
  settings:
    removeable: false
  levels:
    '1':
      chance: 100
      cooldown: 1
      effects:
        - 'INVINCIBLE @Self' 
        - 'WAIT:20'  
        - 'PLAYER_COMMAND:mm mobs spawn blackskill ' 
        - 'WAIT:20'  
        - 'INVINCIBLE @Self'   
        
        
        
       Invincible mode is activated, but the problem is that it remains active and deactivates itself until the server is restarted 
        
        
        
        
        

### "/ae plinfo" link

https://paste.md-5.net/ilogaxigep

### Server Log

https://mcpaste.io/b313a030f23fa902

**Comment by ELIAS7281** [comment]
hi ive tested this enchantment and it doesnt turn off. not sure what the intention of the enchantment is for. cheers

**Comment by ThomasWega** [comment]
Should be fixed in the next update! It would turn off only when you used EFFECT_STATIC
