### ISSUE TITLE
Two targets support

### ISSUE THREAD

**Issue by kothackerr** [GC-spigot/AdvancedEnchantments#3808]
### Describe the bug

Mistake "Failed to activate effect 'PARTICLE:SOUL:50:1 @Victim" "Additional information: Error while activating effect"
I use two targets in one particle effect. The documentation says that you can use two purposes of a separating comma. I work exclusively with the plugin documentation.

configuration:

doublestrike:
  display: '%group-color%doublestrike'
  description: A chance to strike a double blow.
  applies-to: Swords
  type: ATTACK;ATTACK_MOB
  group: LEGENDARY
  applies:
    - ALL_SWORD
  levels:
    '1':
      chance: 60
      cooldown: 0
      effects:
        - DO_HARM:%damage% @Victim
        - PARTICLE:SOUL:50:1 @Victim, @EyeHeight
        - PLAY_SOUND:ITEM_TRIDENT_THUNDER 
    '2':
      chance: 60
      cooldown: 0
      effects:
        - DO_HARM:%damage% @Victim
        - PARTICLE:SOUL:50:1 @Victim, @EyeHeight
        - PLAY_SOUND:ITEM_TRIDENT_THUNDER 
    '3':
      chance: 60
      cooldown: 0
      effects:
        - DO_HARM:%damage% @Victim
        - PARTICLE:SOUL:50:1 @Victim, @EyeHeight
        - PLAY_SOUND:ITEM_TRIDENT_THUNDER
        
        
       I have tried many times to change this separating comma with other characters, but still nothing helped

### How to reproduce

there is nothing

### Screenshots / Videos

there is nothing

### "/ae plinfo" link

there is nothing

### Server Log

there is nothing

**Comment by ThomasWega** [comment]
Not possible now, but a good idea. Leaving it as a feauture request

**Comment by ThomasWega** [comment]
Will be added in the next update! :)
