### ISSUE TITLE
new enchantments

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3809]
### Describe the bug

add enchantments that allow you to cancel events, for example, armor that removes insomnia from players so that phantoms never appear.

add an enchantment that allows you to cancel the events that cause damage from the wither boss when you pass over the wither flower and receive decomposition.

In short, enchantments that cancel events.

### How to reproduce

cancel events

### "/ae plinfo" link

AE: 9.5.11 Git Revision: 75fa32d5 Server: git-Pufferfish-27 (MC: 1.20.1) API: 1.20.1-R0.1-SNAPSHOT Java: 21.0.1

**Comment by SrMonsterYT** [comment]
@ThomasWega how do i make 1 chest take away my insomnia? so the phantom never shows up?

**Comment by ThomasWega** [comment]
you don't. Not a thing. I've closed this because I don't see anyone using this apart from you, so unfortunately not something worth our time right now. Hopefully in the near future
