### ISSUE TITLE
ADD_DURABILITY_CURRENT_ITEM does not work with tools that have a modeldata

### ISSUE THREAD

**Issue by Nashlord** [GC-spigot/AdvancedEnchantments#3810]
### Describe the bug

The hoe is supposed to lose 3 durability each time the effect is used, this works with a vanilla hoe but not with a hoe with a custom model. (The custom model is added using itemadder)

### How to reproduce

rare_ble:
  display: '&ctest'
  description: |-
    Plant seeds in a 3x3 area
    by shift+right-clicking.
  applies-to: Hoes
  type: RIGHT_CLICK
  settings:
    showActionBar: false
  group: RARE
  applies:
    - ALL_HOE
  levels:
    '1':
      conditions:
        - '%player has enchantment in hand of rare_ble% = true : %allow%'
      effects:
        - PLANT_SEEDS:1
        - ADD_DURABILITY_CURRENT_ITEM:-3

### Screenshots / Videos

https://gyazo.com/aeb2daeaea65be86b57a3ecfe07ac36d

### "/ae plinfo" link

https://paste.md-5.net/mafopebaxo

**Comment by Nashlord** [comment]
Same problem with version 9.5.12 and the "ADD_DURABILITY_ITEM" effect

**Comment by ThomasWega** [comment]
Are you using Oraxen or ItemsAdder?

**Comment by Nashlord** [comment]
itemsadder

**Comment by ThomasWega** [comment]
Will be fixed in the next update! Thanks for reporting.
