### ISSUE TITLE
SMELTING DUPE BUG [Using ItemsAdder]

### ISSUE THREAD

**Issue by DarrienZ** [GC-spigot/AdvancedEnchantments#3811]
### Describe the bug

After removing SMELTING (1, 2, 3) from the ItemsAdder custom pickaxe it solved the problem. 

### How to reproduce

https://youtu.be/BQCHKDQs2WA

### Screenshots / Videos

https://youtu.be/BQCHKDQs2WA

### "/ae plinfo" link

https://paste.md-5.net/oqaqujamiy

### Server Log

-

**Comment by ThomasWega** [comment]
Should be fixed in the next update!
