### ISSUE TITLE
Error with slot-increaser

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#3812]
### Describe the bug

We understand that the slot increaser works by enchantment ranges, meaning that if a simple type increaser applies, we can only add simple type enchantments.

The problem comes when I add the simple type incrementer and I can add higher type enchantments (I leave a video of the test in both java and bedrock)

https://www.youtube.com/watch?v=6fywuyWikY8&ab_channel=Neah

### How to reproduce

In the video you can see that I have:

https://www.youtube.com/watch?v=6fywuyWikY8&ab_channel=Neah

- A simple type slot increaser.
- A "Unique" type enchantment
- A helmet with 3 custom enchantments.

As seen at the beginning (sorry for being in Spanish) I cannot add the enchantment because I have blocked that normally the maximum in custom enchantments is 3.

Then I add the simple type slot increaser and take a "unique" type enchantment and can add it, when this should not be the case and I should only be able to add enchantments in this simple type case.

### Screenshots / Videos

https://www.youtube.com/watch?v=6fywuyWikY8&ab_channel=Neah

### "/ae plinfo" link

https://paste.md-5.net/coqixupire

**Comment by ThomasWega** [comment]
This is actually incorrectly flagged as a Bug. It's not a bug as slot increasers do not depend on the enchantment book group applied. Theirs groups basically let you set different numbers of slots they increase the tool with. As in ```groups.yml```

```yaml
slot-increaser:
      # How many slots should slot increaser add when using this type increaser
      slots: 1
      custom-model-data: 0
```

We have however noted the possibility of the feature your described and it might be coming in the future if community welcomes it.

**Comment by ThomasWega** [comment]
More info https://ae.advancedplugins.net/general-information/giving-plugin-items/slot-increasers
