### ISSUE TITLE
suggestion playerlist enchantments

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3813]
### Describe the bug

add a /ae playerlist, where it shows all the enchantments at the maximum level, and shows information such as, the name of the enchantment the description of what it does and where it is applied such as swords, axes..., this would be nice for players to know what enchantments they have on the server and what their function is.

remembering they can't get books or anything just see what's on the server and what enchantments it has and what it's for

### How to reproduce

/ae playerlist

### "/ae plinfo" link

AE: 9.5.12 Git Revision: 7b4476a2 Server: git-Pufferfish-27 (MC: 1.20.1) API: 1.20.1-R0.1-SNAPSHOT Java: 21.0.1

**Comment by GC-spigot** [comment]
Have you checked out `/enchants` ?

**Comment by SrMonsterYT** [comment]
> Have you checked out `/enchants` ?

is it for players? to see the enchantments?

**Comment by GC-spigot** [comment]
Yes, precisely that!

**Comment by SrMonsterYT** [comment]
> Yes, precisely that!

thank you very much and sorry for opening a suggestion
