### ISSUE TITLE
suggested enchantments level

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3814]
### Describe the bug

when i put an enchantment for example bait 1 on a fishing rod and then try to put bait 3 the fishing rod doesn't allow it, would it be ok if i put 1 low level enchantment on 1 item and then try to put the same enchantment on a higher level it should replace that would be nice

### How to reproduce

allow me to upgrade when I put on a low level enchantment and want to put on the same enchantment at a higher level let me put on and replace the small level one

### "/ae plinfo" link

AE: 9.5.12 Git Revision: 7b4476a2 Server: git-Pufferfish-27 (MC: 1.20.1) API: 1.20.1-R0.1-SNAPSHOT Java: 21.0.1

**Comment by ThomasWega** [comment]
This already works...

**Comment by SrMonsterYT** [comment]
> This already works...

https://youtu.be/AjPEEVzRCvI

I'm on version 9.5.13
