### ISSUE TITLE
BREAK_BLOCK bug

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3815]
### Describe the bug

this enchantment that breaks blocks in an instant is not respecting the protection of griefPrevention

stay_glassy:
  display: "%group-color%Stay Glassy"
  description: "Break glass and other glass-type blocks instantly."
  applies-to: Espadas
  type: SWING
  group: ELITE
  applies:
    - ALL_PICKAXE
  levels:
    '1':
      chance: 100
      conditions:
        - '%block type% = GLASS : %allow%'
      effects:
        - BREAK_BLOCK @Block
        

### How to reproduce

use this enchantment

### Screenshots / Videos

video: https://youtu.be/mGT5tg4vOpU

### "/ae plinfo" link

AE: 9.5.12 Git Revision: 7b4476a2 Server: git-Pufferfish-27 (MC: 1.20.1) API: 1.20.1-R0.1-SNAPSHOT Java: 21.0.1

**Comment by Bunnky** [comment]
I can confirm the same happens on Paper-196 (MC: 1.20.1)

**Comment by ThomasWega** [comment]
Fixed!
