### ISSUE TITLE
Add Compatibility with Oraxen (read desc)

### ISSUE THREAD

**Issue by malusic23354** [GC-spigot/AdvancedEnchantments#3816]
### Describe the bug

So i have a CE called Telepathy that adds items directly into your inventory, that works fine with everything except that i have a plugin called Oraxen that adds custom texturepacks to server, i made a Custom Ore called Ruby_ore that drops Ruby when broken, issue comes to that there's no such thing as ruby_ore in minecraft, it's a textured Noteblock that looks like a ruby, so when i break that block with telepathy it doesn't put the custom item it drops in my inventory but rather it puts the Noteblock inside my inventory, so i kindly ask to add support to oraxen custom blocks and items so that they could be compatible :)

### How to reproduce

Have CE on a Pickaxe, Break the Custom textured block, get a Noteblock instead (noteblock = textured custom block)

### Screenshots / Videos

https://imgur.com/a/CFxfETz

### "/ae plinfo" link

https://paste.md-5.net/ipoxujihiv

**Comment by ThomasWega** [comment]
We do have a pretty good support for ItemsAdder, however not so much for Oraxen. I will leave this as a feature request

**Comment by ThomasWega** [comment]
Done with it, but Oraxen needs to sort these issues out first

https://github.com/oraxen/oraxen/issues/1134
https://github.com/oraxen/oraxen/issues/1135

**Comment by ThomasWega** [comment]
Should be added in the next update!
