### ISSUE TITLE
unbreakable new version

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3817]
### Describe the bug

I see that when you add the unbreakable enchantment it keeps wearing off and coming back, why don't you do it like slimefun that when you add the enchantment it doesn't show the durability of the item, look at the video the supreme sword has unbreakable from slimefun vs the one from AdvancedEnchantments

video: https://youtu.be/VgMvAel3944

by adding the enchantment you could make the item not durable, that would be much nicer than regenerating the item

### How to reproduce

unbreakable

### "/ae plinfo" link

AE: 9.5.13 Git Revision: 7b4476a2 Server: git-Pufferfish-27 (MC: 1.20.1) API: 1.20.1-R0.1-SNAPSHOT Java: 21.0.1

**Comment by ThomasWega** [comment]
We'd need to have a separate effect for that, which does seem kind of useless. I feel like this is really a small quality of life improvement, which is not really worth our time now.
