### ISSUE TITLE
Admin Ignore Cooldown

### ISSUE THREAD

**Issue by NoahJosephFox** [GC-spigot/AdvancedEnchantments#3818]
### Describe the bug

A new admin command to ignore enchant cooldowns, for debugging and testing.
Possibly event a setting/condition to work on individual enchants in the configs?

### How to reproduce

.

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ThomasWega** [comment]
if you want to test enchantments, why not to just put the cooldown to 0?

**Comment by NoahJosephFox** [comment]
because i didnt think of that
