### ISSUE TITLE
DUPE BUG: Trench

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3819]
### Describe the bug

In the latest version of AE (9.5.14) is it possible to dupe items using Trench enchantment (again).

### How to reproduce

1. Place Shulker Box with items inside it
2. Mine near the Shulker Box with pickaxe with Trench enchantment
3. You will have two same Shulker Boxes

### "/ae plinfo" link

AE 9.5.14

**Comment by plumpkiwi** [comment]
I also have this issue. though it only dupes the shulker itself, not the contents

**Comment by ThomasWega** [comment]
I am not able to replicate this. Can you provide a video please? Also make sure to try on latest AE with only plugin being AE

**Comment by ThomasWega** [comment]
Aha. So it's more random. I will investigate. Thank you

**Comment by ThomasWega** [comment]
Yep, got it!
