### ISSUE TITLE
Issue with ADD_HARM and lightning

### ISSUE THREAD

**Issue by Frostyeiz** [GC-spigot/AdvancedEnchantments#382]
So after I update to the latest version, the bug about ADD_HARM is fixed, which is good. But then I saw my players something die instantly, after checking, they seem to died when a lightning strike them. (not all the time tho)
I tried to manually lightning them but they don't die instantly or receive huge damage, so it is not about the server's lightning.
After testing for a while, I think that there is something wrong about the new ADD_HARM when it comes to activating before/together/after lightning strikes.
I'm using 5.3.7 AdvancedEnchantments with PaperSpigot build 1604

**Comment by GC-spigot** [comment]
Reworked the effect, might fix this now (not confirmed to be an issue, but check if it's good after this update).
