### ISSUE TITLE
The admin of ae-tickets says that allow-backwards-enchant-books: false is no longer valid.

### ISSUE THREAD

**Issue by NEIKI19914** [GC-spigot/AdvancedEnchantments#3821]
### Describe the bug

https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/81f7c265-7ed8-4b44-8196-63b4cf610d16

Around the 22nd second. The administrator said that the function is that the ae enchanted book is merged with the original enchanted book through the anvil.

### How to reproduce

The administrator said that this feature is rarely used... So now I found out that it failed.

### "/ae plinfo" link

https://paste.md-5.net/tidiboqaji

**Comment by ThomasWega** [comment]
This feature has indeed been removed. Sorry for the inconvinience
