### ISSUE TITLE
Problems with enchantment conflicts in anvils

### ISSUE THREAD

**Issue by jhqwqmc** [GC-spigot/AdvancedEnchantments#3822]
### Describe the bug

https://github.com/GC-spigot/AdvancedEnchantments/assets/113768629/25ecfc56-7179-445b-b3e5-e24d48aca3d7

Enchanted books disappear instead of preventing enchantment

### How to reproduce

1. Enable anvil enchantment in config.yml and anvil.yml and set enchantment conflict to use anvil enchantment
2. according to the operation in the video

### "/ae plinfo" link

https://paste.md-5.net/opogisegoc

**Comment by ThomasWega** [comment]
Hey! The video is corrupted. Can you please re-send it?

**Comment by jhqwqmc** [comment]
> Hey! The video is corrupted. Can you please re-send it?

https://www.dropbox.com/scl/fi/t53lrrntemz6omej8g2mc/285590594-25ecfc56-7179-445b-b3e5-e24d48aca3d7.mp4?rlkey=9i2hfdhxvt4hr3n303eeolaoe&dl=1

**Comment by ThomasWega** [comment]
Just tried it and works completely fine
