### ISSUE TITLE
Enchant Vein Miner XP

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#3824]
### Describe the bug

Mining a block that earns xp will only give you one block, such as a quart block.

### How to reproduce

Mining blocks earns minecraft xp.

### Screenshots / Videos

-

### "/ae plinfo" link

https://paste.md-5.net/ukewanenak

### Server Log

-

**Comment by ThomasWega** [comment]
We need more info and explanation then this...

**Comment by ThomasWega** [comment]
it might give only one xp orb but the value it gives seems to be all the blocks xp combined

**Comment by ThomasWega** [comment]
Should be fixed in the next update!

**Comment by ThomasWega** [comment]
It won't produce more XP orbs but the XP orb will give correct experience
