### ISSUE TITLE
HARVESTER DUPE BU

### ISSUE THREAD

**Issue by ChefJisoo** [GC-spigot/AdvancedEnchantments#3826]
### Describe the bug

Using this enchant on non-crop blocks causes them to dupe.

harvester:
  display: '%group-color%♦ &fHarvester'
  description: Replants crops when you break them.
  applies-to: Hoes
  type: MINING
  group: ADVANCED
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
  - ALL_HOE
  levels:
    '1':
      condition:
      - '%is crop% = false : %stop%'
      - '%is fully grown% = false : %stop%'
      - '%offhand item% = %block drop type% : %allow%'
      effects:
      - TAKE_AWAY:%block drop type%
      - SET_BLOCK:%block type%

### How to reproduce

Use my enchant on a hoe and try break something that isnt a crop i.e beacon, dirt anything. The block will dupe. 

harvester:
  display: '%group-color%♦ &fHarvester'
  description: Replants crops when you break them.
  applies-to: Hoes
  type: MINING
  group: ADVANCED
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
  - ALL_HOE
  levels:
    '1':
      condition:
      - '%is crop% = false : %stop%'
      - '%is fully grown% = false : %stop%'
      - '%offhand item% = %block drop type% : %allow%'
      effects:
      - TAKE_AWAY:%block drop type%
      - SET_BLOCK:%block type%

### Screenshots / Videos

https://www.youtube.com/watch?v=SfNGELUPmVY 

### "/ae plinfo" link

https://paste.md-5.net/imitejobot

### Server Log

https://mclo.gs/XRqIZ3z

**Comment by ThomasWega** [comment]
The correct format would be conditions, not condition
