### ISSUE TITLE
SlimeFun Dupe

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3827]
### Describe the bug

you can multiply blocks when you break slimefun machines with the telepathy enchantment, watch the video: https://youtu.be/Xa33eB23jvg

my suggestion would be for the plugin to ignore any modified blocks this would solve a bug in several other plugins as well
### How to reproduce

 break slimefun machines

### "/ae plinfo" link

AE: 9.5.15 Git Revision: 7b4476a2 Server: git-Pufferfish-27 (MC: 1.20.1) API: 1.20.1-R0.1-SNAPSHOT Java: 21.0.1

**Comment by GC-spigot** [comment]
@SrMonsterYT How do you get that "surpreme generator" item? Is that a default slimefun item? I cannot find it in slimefun. This was a problem and we've fixed it: https://gyazo.com/c03db466e89b7dd6be05ff68ef20ed72

If that's not a native slimefun item we'd have to hook into other plugins to add support for this as well

**Comment by GC-spigot** [comment]
So that's why there's this issue. You should mention it's an addon. It's clearly not properly supported by SlimeFun, as SlimeFun's API does not say that it's their custom item. I'll see what we can do.

**Comment by SrMonsterYT** [comment]
@GC-spigot https://youtu.be/4qyfrV625sA
