### ISSUE TITLE
Godly overload fake death

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#383]
paper 1.13.2
ae- 5.3.7

Godly overload is doing this weird fake death to people. The player loses the 10 hearts from godly overload, and then get a death screen. When they hit respawn they don't actually respawn, they go back to where they were, with everything in their inventory. Their character is then sideways, red, and spazzing out. 

-One player was able to recreate it by drinking milk.
-Another player was just placing blocks when it happened to him.
-The third player was AFK just standing there when it happened.

*The only enchant these players had in common is Godly Overload. This enchant is using the default settings from the plugin.

Spazz video:
https://www.youtube.com/watch?v=fnBnSw_cVfM&feature=youtu.be

Milk bucket recreating:
https://www.youtube.com/watch?v=L8T4fui7gQ4&feature=youtu.be

Super creepy right?

**Comment by GC-spigot** [comment]
As you see he gets damaged as soon as he drinks the milk, therefore it's player's client thinking that they died when in fact they didn't. It's not creepy, it's death animation activating over and over again.
This is a bug with 1.13 at the moment.

**Comment by Kbryst** [comment]
Well that's just what one player did to recreate it.

My main point is it's happening to players when they are standing still and
doing nothing.

**Comment by GC-spigot** [comment]
Update your server .jar, could be a bug with that since this hasn't been reported yet. Could be another plugin causing this as well.
