### ISSUE TITLE
AdvancedChests Dupe | Almost as with the Slimefun dupe

### ISSUE THREAD

**Issue by SeptyIsHere** [GC-spigot/AdvancedEnchantments#3830]
### Describe the bug

Telepathy & Blast have issues sometimes, AdvancedChests requires a GUI to actually break the chest, because AdvancedChests modifies a chest NBT (probably or so I've been told) telepathy gives it back and in some scenarions AdvancedChests keeps the chest there and you can have two by placing another chest there and the one you get with telepathy. Same with Trench and with slimefun machines

### How to reproduce

Just break with telepathy advancedchests chests until you get it, or add a blacklist for Telepathy. But the slimefun bug is also important!

### "/ae plinfo" link

https://paste.md-5.net/oqekunoziv

**Comment by ThomasWega** [comment]
Contacted the author. If he doesn't want the block to be broken normally he should be cancelling the ```BlockBreakEvent``` and then we'd be able to handle it accordingly, but if I were to guess he doesn't. Will hopefully figure this out if the author replies

**Comment by ThomasWega** [comment]
Author doesn't respond and seems not to be active a lot. I doubt this is our issue. Regarding to this

> Contacted the author. If he doesn't want the block to be broken normally he should be cancelling the `BlockBreakEvent` and then we'd be able to handle it accordingly, but if I were to guess he doesn't. Will hopefully figure this out if the author replies

he might be cancelling it but with a too high of a priority. If you want this fixed, it'd go ask the AdvancedChests author.

**Comment by ThomasWega** [comment]
Author contacted me on discord. Reopening this

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
