### ISSUE TITLE
Aoe effects interacting with Armor Stand

### ISSUE THREAD

**Issue by TheBadshah** [GC-spigot/AdvancedEnchantments#3831]
### Describe the bug

It seems like Aoe is counting Armor Stand in its target types 

>  test:
>   display: '%group-color%test'
>   description: test.
>   applies-to: test
>   type: RIGHT_CLICK
>   group: test
>   applies:
>   - ALL_SWORD
>   levels:
>     '1':
>       effects:
>       - PARTICLE:GLOW:30:0.5 @Aoe{r=10,t=damageable}

### How to reproduce

use the aoe effect 

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/116473315/efb85582-226b-4a66-b685-0105a2b976bd

### "/ae plinfo" link

https://paste.md-5.net/owoducicum

**Comment by GC-spigot** [comment]
Fixed!
