### ISSUE TITLE
Plugin Disabling Itself Once New Update Added.

### ISSUE THREAD

**Issue by DontMessWithDis** [GC-spigot/AdvancedEnchantments#3836]
### Describe the bug

When I add the new version to my test server the plugin gives "Internal error has occurred." And this is with no other plugins and we tried deleting folders, completely re-installing it and even going back versions. Nothing is working.

### How to reproduce

Simply install it and it won't work.

### "/ae plinfo" link

/ae plinfo skipPlugins

### Server Log

https://mcpaste.io/4296a15c354077bd

**Comment by GC-spigot** [comment]
Hey, there is a problem with your license, contact our discord support server https://discord.gg/advancedplugins open a pre-purchase ticket if you're not verified, general ticket if you are. You have hit a security limit for licenses.
