### ISSUE TITLE
lucky_miner in aurelium skills (2x drops) was not applied with ANCIENT_DEBRIS 

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3837]
### Describe the bug

If ANCIENT_DEBRIS is breaked with SMELT applied pickaxes, LUCKY_MINER of Aurelium Skills will not be activated.

### How to reproduce

1. set aurelium skill's level 97 by "/skill skill setall player 97" command
2. apply SMELT on PICKAXE
3. Break ANCIENT_DEBRIS

### Screenshots / Videos

https://youtu.be/tYlUZ5jn3aM

### "/ae plinfo" link

https://paste.md-5.net/zobafowiji

**Comment by ThomasWega** [comment]
Issue on AureliumSkills again. Hate them, their code is really bad and causes issues all the time. Sometimes even event cancellation doesn't work. Talk with them
