### ISSUE TITLE
TRENCH DUPLICATION GLITCH

### ISSUE THREAD

**Issue by ShikuretSensei** [GC-spigot/AdvancedEnchantments#3838]
### Describe the bug

Our players just abused this bug but good thing we have caught them as soon as possible. All you need to do is just have the custom enchantment **TRENCH** on any pickaxe and mine a shulker box and it will duplicate the shulker box. That's all!

### How to reproduce

All you need to do is just have the custom enchantment **TRENCH** on any pickaxe and mine a shulker box and it will duplicate the shulker box. That's all! The uploaded video says it all and no further explanation needed. 

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/39545120/6b0ed9a4-73d5-40b5-ada4-60fd1934d6b3

### "/ae plinfo" link

https://paste.md-5.net/jovesiboxo

**Comment by GC-spigot** [comment]
Fixed!
