### ISSUE TITLE
SUGGESTION: REMOVE_HEALTH effect should remove absorption health/hearts first

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3839]
### Describe the bug

Hello, can remove_health option not bypass absorption effect? because if you have absorption and you use remove_health, it won't affect the absorption hearts, can we make it remove absorption hearts first before removing the actual health?(since absorption counts as HEALTH as well)

### How to reproduce

Suggestion

### Screenshots / Videos

Suggestion

### "/ae plinfo" link

Suggestion

### Server Log

Suggestion

**Comment by ThomasWega** [comment]
Will be added in the next update
