### ISSUE TITLE
[Feature-Request] Unbreakable, effects on block, AOE

### ISSUE THREAD

**Issue by mclegendary1** [GC-spigot/AdvancedEnchantments#384]
Hello, i have three feature request.
**Description**
1. Enchant with what some item could be unbreakable(mb some like that already exists in plugin).
2. Will be fine, if STATIC_EFFECTS type can be used on block like on an armour.
3. New enchant type = AOE, what run some static effects ONLY if players are in radius.

**Example(3)**
rad:
  display: 'Radiation'
  description: 'Gives static effects only if players staying in radius.'
  applies-to: 'Armor'
  type: 'AOE'
  group: 'Epic'
  applies:
  - ALL_ARMOR
  levels:
    1:
      effects:
      - 'POTION:POISON:0 <aoe> radius=7 target=all </aoe>'

Thanks for your time.

**Comment by GC-spigot** [comment]
Use REPEATING enchant type to affect players in radius.
