### ISSUE TITLE
[Suggestion] per custommodeldata

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3842]
### Describe the bug

can you add individual custommodel data for each group of customenchant book & magic dust?

### How to reproduce

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/fb33dd69-8545-4282-8465-d755b1592597)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/d21e51b4-768c-41f9-bd92-6fdd0af07e88)

Regardless of the group, only one custommodel must be used unconditionally,
so it is difficult to distinguish which group the item belongs to.
So that we can distinguish this, can you make custommodel data to each group's magic dust and enchantments book?
(I'm not talking about rcbook, I'm talking about enchantment book)

### "/ae plinfo" link

https://paste.md-5.net/xoriraraza

**Comment by ThomasWega** [comment]
We would need to restructure the code. Haven't really even looked how big/small the restructure would be. I will eventually get to this once bugs are fixed

**Comment by GC-spigot** [comment]
We don't really plan on making magic dust per group configurable, but you can actually customise enchantment books:
groups.yml
```yaml
groups:
  SIMPLE:
    global-color: "&7"
    group-name: "Simple"
    enchant-book-item:
      item:
        type: BOOK
        id: 0
        custom-model-data: 0
        force-glow: false
      # Variables: %enchant%, %enchant-no-color%, %description%, %level-description%, %applies%, %success%, %destroy%, %color%, %max-level%
      name: '%group-color%&l&n%enchant-no-color% %level%'
      lore:
      - '&a%success%% Success Rate'
      - '&c%destroy%% Destroy Rate'
      - '&e%description%'
      - '&7%applies-to% Enchantment'
      - '&7Drag n'' drop onto item to enchant'
    # Use this to change the type of item per group
    item:
      type: FIREWORK_CHARGE
      id: 0
      custom-model-data: 0
      # Use this to set firework charge's color only! Uses RGB
      # Find colors here: https://htmlcolorcodes.com/color-picker/
      rgb-color: 200;200;200
    slot-increaser:
      # How many slots should slot increaser add when using this type increaser
      slots: 1
      custom-model-data: 0
    magic-dust:
      # when right-clicked, it gives magic with success chance
      # How much success should the dust have? (e.g.: 5 would mean always 5, 5-10 would mean random number from 5 to 10)
      success: 1-15
      # Chance to give Magic dust instead of Mystery dust
      chance: 22

**Comment by Ecilpse** [comment]
> We don't really plan on making magic dust per group configurable, but you can actually customise enchantment books. Just add `enchant-book-item` for each GROUP, like this: groups.yml
> 
> ```yaml
> groups:
>   SIMPLE:
>     global-color: "&7"
>     group-name: "Simple"
>     enchant-book-item:
>       item:
>         type: BOOK
>         id: 0
>         custom-model-data: 0
>         force-glow: false
>       # Variables: %enchant%, %enchant-no-color%, %description%, %level-description%, %applies%, %success%, %destroy%, %color%, %max-level%
>       name: '%group-color%&l&n%enchant-no-color% %level%'
>       lore:
>       - '&a%success%% Success Rate'
>       - '&c%destroy%% Destroy Rate'
>       - '&e%description%'
>       - '&7%applies-to% Enchantment'
>       - '&7Drag n'' drop onto item to enchant'
>     # Use this to change the type of item per group
>     item:
>       type: FIREWORK_CHARGE
>       id: 0
>       custom-model-data: 0
>       # Use this to set firework charge's color only! Uses RGB
>       # Find colors here: https://htmlcolorcodes.com/color-picker/
>       rgb-color: 200;200;200
>     slot-increaser:
>       # How many slots should slot increaser add when using this type increaser
>       slots: 1
>       custom-model-data: 0
>     magic-dust:
>       # when right-clicked, it gives magic with success chance
>       # How much success should the dust have? (e.g.: 5 would mean always 5, 5-10 would mean random number from 5 to 10)
>       success: 1-15
>       # Chance to give Magic dust instead of Mystery dust
>       chance: 22
> ```
I think there will be a lot of improvements in convenience'
if set up custom model data like an enchantments book.
I would appreciate it if you could reflect it later.
