### ISSUE TITLE
FactionsKore Support

### ISSUE THREAD

**Issue by YT-Duckyyy** [GC-spigot/AdvancedEnchantments#3844]
### Describe the bug

Currently, there is no support for Kore's mob stacking for enchants such as Kill Aura. This enchant is where more than one mob in a stack dies upon killing the mob. For example, if I kill 1 blaze in a stack of 30, it could kill (x) in that stack rather than just one.

### How to reproduce

Have Kore Mob Stacker

### "/ae plinfo" link

https://paste.md-5.net/bojecahufi

**Comment by GC-spigot** [comment]
How widely is this plugin used? Where can we find an API for this plugin?

**Comment by ThomasWega** [comment]
Oh, you only wanted this support for killaura. I thought that enchantments killed all the stacked mobs or something like that, which as I've tested now doesn't happen. I will be closing this as it doesn't seem to be worth our time just because of killaura at the moment
