### ISSUE TITLE
Spam with Water & Lava Walker with FactionsUUID

### ISSUE THREAD

**Issue by YT-Duckyyy** [GC-spigot/AdvancedEnchantments#3845]
### Describe the bug

Currently, your chat is spammed if entering other's claims on FactionsUUID with either Water Walker or lava Walker effects, this needs to be prevented. Maybe a config that allows it within claims? 

### How to reproduce

Have either of the enchants on boots
Walk into an enemy claim with the source below.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1180556354994315294/1180881866488819732/dfc185b811248577d321389337b42728.mp4?ex=657f08f0&is=656c93f0&hm=babbb84c6da9175a83b0f52511b02034c1d0d59f83014aca83f2032fd87ae692&

### "/ae plinfo" link

https://paste.md-5.net/bojecahufi

**Comment by ThomasWega** [comment]
Can you please send the attachment differently? I cannot download it. The discord one
