### ISSUE TITLE
FLY_SPEED / WALK_SPEED

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#3846]
### Describe the bug

These two new effects are not working in 9.5.20.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63577950/16cee339-4238-46c0-ab3f-f9cbd534bd75)

### How to reproduce

```
  type: 'RIGHT_CLICK'
  group: 'SIMPLE'
  applies:
    - ALL_BOOTS
  levels:
    1:
      effects:
        - 'WALK_SPEED:10:100'
        - 'MESSAGE:speed'```

### Screenshots / Videos

_No response_

### "/ae plinfo" link

https://paste.md-5.net/icanakowix

### Server Log

_No response_

**Comment by ThomasWega** [comment]
Speed value need to be between -1 and 1. Default is 0.2 if I remember correctly
