### ISSUE TITLE
Book apply when the item reach max enchant limit

### ISSUE THREAD

**Issue by newbie029** [GC-spigot/AdvancedEnchantments#385]
Please make book cannot be applied to item if the player reached the maximum enchant limit permission rather than make the book gone or destroy items

**Comment by GC-spigot** [comment]
It must be a visual glitch if they disappear.

**Comment by newbie029** [comment]
Dont close the issue too fast
https://streamable.com/ebozp
I can apply a book with high destroy rate to the item and destroy the item
