### ISSUE TITLE
[FEATURE REQUEST] add pointers for EFFECT_STATIC_ON, EFFECT_STATIC_OFF EFFECT_STATIC

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#3851]
### Describe the bug

if you want to do this with the current system in place you have to check their gear slot to see if they have a certain item in that slot and then set the effects accordingly. with on and off you wouldn't need an extra condition to check their gear, you could just point to which one you wanted with ~EFFECT_STATIC_ON, I am not sure if this is feasible with the current code of effect_static but I think it would give this more uses and or make it easier to work with.

contact me on discord: VoidArc

### How to reproduce

[feature request]

### Screenshots / Videos

[feature request]

### "/ae plinfo" link

[feature request]

### Server Log

[feature request]

**Comment by GC-spigot** [comment]
You can already do this this way 
```
effects:
  - 'MESSAGE:Armor removed <condition>%is removal% = true : %allow%</condition>'```
