### ISSUE TITLE
[Suggestion] Sneak-right click options to items.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3852]
### Describe the bug

can you add sneak + right click option to open randombook & secret items?
The player accidentally opens the item while holding the item and opening the box or right-clicking the NPC.

And drag-drop items (magic dust, white-scroll, etc..) are often accidentally applied by the player while organizing items from the inventory, which also seems to need improvement.

### How to reproduce

i reproduce issue on video link.

### Screenshots / Videos

https://youtu.be/9emZU2ZEEhk

### "/ae plinfo" link

https://paste.md-5.net/zizugedeji

**Comment by ThomasWega** [comment]
Hey! I've added an shift-click option to config items settings. You will be able to use it like so:

´´´yaml
    settings:
      shift-click: true
´´´

Hopefully in the next update :)

**Comment by Ecilpse** [comment]
> Hey! I've added an shift-click option to config items settings. You will be able to use it like so:
> 
> ```yaml
>   secret-dust:
>     type: FIREBALL
>     id: 0
>     custom-model-data: 0
>     force-glow: false
>     settings:
>       shift-click: true
>     shift-click: true
>     name: '%group-color%%group-name%%group-color% Secret Dust &7(Right Click)'
>     lore:
>     - '&7Contains: &bMagic, &fMystery &7dust.'
>     - '&7An unidentified satchel of dust.'
> ```
> 
> Hopefully in the next update :)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/32bfd0cb-39ef-4136-a844-75dbbd5435bc)

not worked with enchanter-books. is it only worked with secret-dust?
