### ISSUE TITLE
Asets custommodeldata

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3854]
### Describe the bug

Asets custom model data not working properly, the Icon works but not the set, its not the same issue when i get the custom model on /ia, check video below.

### How to reproduce

Create an armorset with custom model data, and see video below.

### Screenshots / Videos

https://streamable.com/kkhs4q

My ninja.yml in armorsets
https://pastebin.com/LCutqh0H

### "/ae plinfo" link

https://paste.md-5.net/obuhinusuy

### Server Log

https://mcpaste.io/eedbecc4b0e1bf6f

**Comment by illudota** [comment]
can someone check on this?

**Comment by ThomasWega** [comment]
https://wiki.advancedplugins.net/configuration/config-items you need to put itemsadder value instead
