### ISSUE TITLE
ROD_CAST not working

### ISSUE THREAD

**Issue by ryankayz7** [GC-spigot/AdvancedEnchantments#3857]
### Describe the bug

While using 9.5.23 the ROD_CAST type does not activate any effect at all.

### How to reproduce

Using an enchant such as the following the MESSAGE effect works if you change the "type" to RIGHT_CLICK but ROD_CAST does not showing anything. RIGHT_CLICK also has an error (as will be reported in another issue) whereas ROD_CAST does not display anything at all. Changing or removing the max/min catch time did not change the result at all.

fishing:
  display: '%group-color%Fishing'
  description: Testing.
  applies-to: Fishing Rod
  type: ROD_CAST
  group: FISHING
  applies:
  - FISHING_ROD  
  levels:
    '1':
      chance: 100  
      effects:
      - MESSAGE:Works
      - SET_MIN_CATCH_TIME:100 
      - SET_MAX_CATCH_TIME:120

### "/ae plinfo" link

https://paste.md-5.net/limuferipu

**Comment by ThomasWega** [comment]
Works completely fine

**Comment by ryankayz7** [comment]
I did some more testing with debug. Wouldn't this suggest it is activating as "SWING" instead of "ROD_CAST"?
https://gyazo.com/e2abd55a8c6f9d15197850be44bfda93
