### ISSUE TITLE
SET_MAX_CATCH_TIME and SET_MIN_CATCH_TIME not working

### ISSUE THREAD

**Issue by ryankayz7** [GC-spigot/AdvancedEnchantments#3858]
### Describe the bug

On 9.5.23 if you use this effect it will give an error in chat and not work. 

### How to reproduce

I tested changing the ticks around to SET_MIN_CATCH_TIME:120 SET_MAX_CATCH_TIME:140 and also SET_MIN_CATCH_TIME:20 SET_MAX_CATCH_TIME:120 however neither worked and displayed errors. I used the enchantments as follows. Note I used RIGHT_CLICK instead of ROD_CAST as it is broken at the moment. 

fishing:
  display: '%group-color%Fishing'
  description: Testing.
  applies-to: Fishing Rod
  type: RIGHT_CLICK
  group: FISHING
  applies:
  - FISHING_ROD  
  levels:
    '1':
      chance: 100  
      effects:
      - MESSAGE:Works
      - SET_MIN_CATCH_TIME:20 
      - SET_MAX_CATCH_TIME:120
      
fishing:
  display: '%group-color%Fishing'
  description: Testing.
  applies-to: Fishing Rod
  type: RIGHT_CLICK
  group: FISHING
  applies:
  - FISHING_ROD  
  levels:
    '1':
      chance: 100  
      effects:
      - MESSAGE:Works
      - SET_MIN_CATCH_TIME:120 
      - SET_MAX_CATCH_TIME:140

### Screenshots / Videos

Chat error
https://gyazo.com/311c30e65f6a67b3006083ed94705e3f

### "/ae plinfo" link

https://paste.md-5.net/uwabakusiz

**Comment by ThomasWega** [comment]
SET_MIN_CATCH_TIME and SET_MAX_CATCH_TIME work only with ROD_CAST trigger
