### ISSUE TITLE
Soultrak's lore disappear after custom enchantments.

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#3860]
### Describe the bug

Soul tracker lore in the item disappears after applying AE enchantments. If you have a number of souls in the item and the enchantments require souls to activate, it will still work, even if soul tracker lore vanished. However, putting the AE enchantment first before the soul tracker works perfectly fine.

### How to reproduce

^

### "/ae plinfo" link

.23

**Comment by ThomasWega** [comment]
Works just fine on the latest

**Comment by ThomasWega** [comment]
When exactly does the lore disappear? Do you mind sending a video?
