### ISSUE TITLE
Telepathy and Smelting

### ISSUE THREAD

**Issue by ray28alyan** [GC-spigot/AdvancedEnchantments#3862]
### Describe the bug

duplicate bug using custom enchant telepathy and smelting, the way it works is put a string then put a block next to the string then destroy it using a pickaxe with custom enchant telepathy or smelting, and a duplicate occurs

### How to reproduce

telepathy is a custom enchant so that destroyed blocks go directly into the player's inventory, and smelting is a custom enchant that when destroying ores, the ores don't need to be burned and immediately become ingots

### "/ae plinfo" link

/ae plinfo skipPlugins

### Server Log

there's no logs error

**Comment by ThomasWega** [comment]
Please send a video example and your plugin + server version
