### ISSUE TITLE
Armor Crystals [REQUEST]

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3863]
### Describe the bug

Hello! please bring back armor crystals, they are very useful for people who want to upgrade their set instead and not make a whole new one, this will be a good addition again, please! <3 I have no idea why it was removed

### How to reproduce

none

### Screenshots / Videos

none

### "/ae plinfo" link

none

### Server Log

none

**Comment by illudota** [comment]
Please add them back :<

**Comment by GC-spigot** [comment]
Unfortunately minecraft servers are moving away from factions, armor sets and such features like this. We're focusing on features that suit the new minecraft trends, right now smp and survival servers are most popular.

**Comment by illudota** [comment]
> Unfortunately minecraft servers are moving away from factions, armor sets and such features like this. We're focusing on features that suit the new minecraft trends, right now smp and survival servers are most popular.

That's unfortunate, Its not really related to Factions but yeah kind of, it just makes it easier for people to have an armorset without having to rebuild their enchants no? anyway yeah, just saying, HOPEFULLY.

**Comment by illudota** [comment]
or if you ever could not bring back armor crystals, can you atleast allow customWeapons to be used by multiple armorsets?
like:

requireSet:
- Armorset1
- Armorset2

**Comment by GC-spigot** [comment]
We'll look into this
