### ISSUE TITLE
Fish Caught Stat Tracker

### ISSUE THREAD

**Issue by HalfloveJAR** [GC-spigot/AdvancedEnchantments#3864]
### Describe the bug

I posted this suggestion on Discord recently, and was recommended to repost it here as a bug, and an admin would tag it as a feature request manually:

A very popular suggestion on my server right now is to add an item similar to the block stat tracker and the mob stat tracker that will track how many fish you've caught with a fishing rod.

If this is a possible feature that could be added, I would greatly appreciate it! Thanks in advance for your consideration 👍

### How to reproduce

Place a fish tracker onto a fishing rod, track every time a successful cast was performed

### "/ae plinfo" link

https://paste.md-5.net/holuwiwava

**Comment by ThomasWega** [comment]
Will be added in the next update!
