### ISSUE TITLE
DEFENSE_MOB_PROJECTILE Doesn't work in version 9.5.23+

### ISSUE THREAD

**Issue by zylstra1313** [GC-spigot/AdvancedEnchantments#3865]
### Describe the bug

The trigger "DEFENSE_MOB_PROJECTILE" stops working after updating to version 9.5.23 or 9.5.24.

### How to reproduce

Use the enchant:
test:
  display: "%group-color%Test"
  description: "Triggers on ranged damage."
  applies-to: Armor
  type: DEFENSE_PROJECTILE;DEFENSE_MOB_PROJECTILE
  group: FABLED
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - 'CONSOLE_COMMAND:say test'
in version 9.5.22 then update to version 9.5.23 and test the enchant again.

### "/ae plinfo" link

https://paste.md-5.net/rilosasipi

**Comment by ThomasWega** [comment]
Works fine
