### ISSUE TITLE
Minor issue (Rightclicking heads toggles armorsets)

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3866]
### Describe the bug

interacting with playerheads toggles armorsets

### How to reproduce

Right click a player head while you have an armorset

### Screenshots / Videos

https://streamable.com/djkldn

### "/ae plinfo" link

https://paste.md-5.net/katihajeto

### Server Log

https://drive.google.com/file/d/1fy-iHxBqKWE30ZW_Fhm2YCHKFpkROglS/view?usp=drive_link

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
