### ISSUE TITLE
Trench cancel action

### ISSUE THREAD

**Issue by hiiamken** [GC-spigot/AdvancedEnchantments#3867]
### Describe the bug

I am experiencing an issue with the Trench enchantment, where if a player mines continuously on the same block, they will be unable to continue mining, and an animation error occurs

### How to reproduce

You can enchant a trench pickaxe with a high efficiency enchantment. When mining continuously, the action gets canceled. This applies to cobblestone farm machines (Lava + Water).

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/9ba8df5a-1f6c-4ecb-a56c-05f0ea2c555b

### "/ae plinfo" link

https://paste.md-5.net/erixireyij

### Server Log

https://mclo.gs/Vc7s7bw (Cant use https://mcpaste.io/)

**Comment by hiiamken** [comment]
Someone reply please

**Comment by ThomasWega** [comment]
Was not able to replicate this. Seems like an edge scenario anyway
