### ISSUE TITLE
Armor Effects apply incorrectly when pieces of armor are directly put into armor slot

### ISSUE THREAD

**Issue by EvansSC1** [GC-spigot/AdvancedEnchantments#3868]
### Describe the bug

If you have an armor item with an enchantment that applies a potion effect to the wearer, putting on the piece of armor via directly clicking on the armor slot in the inventory results in incorrect effect application. The effects will reverse and be applied when the armor is not equipped.

### How to reproduce

- Create an armor item with enchant (ie. boots with "Gears")
- Open inventory
- Click on boots
- Place boots in boots slot
- Notice that boots are not giving effect as intended
- Take boots out of slot via same method
- Notice that effect is applied to the player, with the item no longer being worn

Shift clicking boots out of the slot will maintain whatever effect is present while boots are worn.

### Screenshots / Videos

https://youtu.be/WbMBQE1Uiuo

### "/ae plinfo" link

https://paste.md-5.net/oqeduweqet

**Comment by EvansSC1** [comment]
I realize that the plinfo contains a version 2 versions out of date but I have tested this bug on the most recent 3 versions, 9.5.24 being the one where it was discovered

**Comment by ThomasWega** [comment]
Works absolutely fine for me. What if you try on a clean server with AE as the only plugin? Does this still happen? Make sure to try with latest as well

**Comment by MylaChuu** [comment]
I can confirm that this bug happens to me aswell but in my case this is being caused by CMI because it allows people putting on any item as a hat by just clicking it in your headslot, you can work around this by denying the permission "cmi.inventoryhat" if your an operator or take it away if this is given to your players.

Im guessing any other plugin that allows you to wear any item on your head like this will cause the same issue

**Comment by ThomasWega** [comment]
Yeah these are probably plugin incompatibilities. Thanks for bringing this up.

@EvansSC1 can you send me your plugin list?

**Comment by EvansSC1** [comment]
Custom Crafting, EssentialsX, EssentialsXChat, LuckPerms, MythicMobs, Quests, Shopkeepers, Vault, VoiceChat(bukkit plugin to use SimpleVoice) WolfyUtils (dependency of CC), WorldGuard, ZNpcs+

**Comment by ThomasWega** [comment]
My guess is WolfyUtils (Custom Crafting with it). Essentials is also possible. Can you try without these 3 plugins and see if the issue remains please?
