### ISSUE TITLE
Possibility to translate Alchemist transaction message for vault/xp

### ISSUE THREAD

**Issue by TheLaoming** [GC-spigot/AdvancedEnchantments#3869]
### Describe the bug

Hey, so basically there's no way how to translate message you receive once trade with alchemist is done.
```
price:
      experience: true
      let-plugin-count: true
      custom-price: 250
```
Both experience and money can't be translated, so the message looks like "- 250$" or "-250XP". Since my server is highly customized using resource pack, I wanna translate both messaages with an new option, something like `alchemist_moneytaken: "%price%$"` etc. I'm not sure if this message is shown anywhere else, I know only about alchemist.

Will be very useful not only for me, thanks!

### How to reproduce

Make a trade with the alchemist, you receive this message then.

### "/ae plinfo" link

https://paste.md-5.net/ojiqoxuwur

**Comment by ThomasWega** [comment]
Done. Will be added in the next update
