### ISSUE TITLE
[suggestion] prevent applying higher enchantment on tools

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3870]
### Describe the bug

If player apply a level 3 enchant book to tool that applied  level 1 enchant,
disappears and it changes to level 3.
This is likely to cause problems by accidentally applying it if it is expensive.

### How to reproduce

i described in bugs.
can you add config options to prevent applying enchant except when it's not the same level of enchant ?

### "/ae plinfo" link

https://paste.md-5.net/alecinuruk

**Comment by ThomasWega** [comment]
is ```combining.enabled``` what you mean?

**Comment by GC-spigot** [comment]
`combining.chances.upgrade` is what you are looking for
