### ISSUE TITLE
enchantment effect failure

### ISSUE THREAD

**Issue by Rcorcho6** [GC-spigot/AdvancedEnchantments#3871]
### Describe the bug

Apparently when they are doing pvp and the programmed effects of the enchantment fail even if they are in a correct configuration, causing multiple errors in the console and game chat

### How to reproduce

He is damaged when using the inflame and immolation enchantments causing the falling_lava particles to fail.

### Screenshots / Videos

inflame:
  display: '%group-color%Inflame'
  description: ᴘᴏɴ ᴀ ᴛᴏᴅᴏѕ ʟᴏѕ ᴊᴜɢᴀᴅᴏʀᴇѕ ᴇɴ ᴜɴ ʀᴀᴅɪᴏ ᴅᴇ ꜰᴜᴇɢᴏ.
  applies-to: Axes
  group: LEGENDARIO
  type: ATTACK
  applies:
    - ALL_AXE
  levels:
    '1':
      chance: 10
      cooldown: 4
      effects:
        - PARTICLE:FALLING_LAVA:5:0 @Victim
        - BURN:40 @Victim
    '2':
      chance: 12
      cooldown: 5
      effects:
        - PARTICLE:FALLING_LAVA:5:0 @Victim
        - BURN:50 @Victim
    '3':
      chance: 16
      cooldown: 5
      effects:
        - PARTICLE:FALLING_LAVA:5:0 @Victim
        - BURN:60 @Victim
        
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/86140264/e1463c92-7e77-42bb-946c-a815f87f59b6)

### "/ae plinfo" link

https://paste.md-5.net/ubomuyutij

### Server Log

https://pastes.dev/dnGXtbwvVi

**Comment by ThomasWega** [comment]
Can you send a video please?

**Comment by ThomasWega** [comment]
Should be fixed in the next version
