### ISSUE TITLE
Enchantment Glow Failure

### ISSUE THREAD

**Issue by 3Dins** [GC-spigot/AdvancedEnchantments#3873]
### Describe the bug

Currently on version 9.5.25.
If you go into the config and set items to glow from custom enchantments, they do not.

### How to reproduce

Set 
custom-enchants-cause-glow: true
they will not work

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1187866401348780176/1188170079997808691/image.png?ex=65998c9e&is=6587179e&hm=da87bb1129cf6f5684013206189975a6677be92fff7cb7b1c7efbad038c4f517&

### "/ae plinfo" link

https://paste.md-5.net/qogoveyuro

**Comment by ThomasWega** [comment]
Should be fixed in the next version
