### ISSUE TITLE
some books was not applied magic dust.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3876]
### Describe the bug

some books can't applied mysterybooks.

nbt tags of nomally enchant bock : ae_book_failure:1 / ae_book_success:99
nbt tags of enchant bock that can not apply magic dust : ae_book_failure:0 / ae_book_success:99

### How to reproduce

I haven't been able to reproduce it myself.
However, these problems often lead to bug reports.
Because succes rate of books is marked as 99%, player could think  destroy the equipment.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/a13f12a1-8517-4e0e-80f0-0594ff000fb6

### "/ae plinfo" link

https://paste.md-5.net/aniwegawez

**Comment by ThomasWega** [comment]
how were you able to get a book that has ae_book_failure:0 / ae_book_success:99
?

**Comment by Ecilpse** [comment]
> how were you able to get a book that has ae_book_failure:0 / ae_book_success:99 ?

i don't know how can make that book.
However, this issue is often reported.

**Comment by ThomasWega** [comment]
Will be fixed in the next update

**Comment by Ecilpse** [comment]
> Will be fixed in the next update

it seemd fixed in lastest build but player can apply maigc dust apply it infinitely.
I think it should not be applied when the success rate is 100%.
