### ISSUE TITLE
Add the option to define model data per book or per rarity (enchantments)

### ISSUE THREAD

**Issue by TheLaoming** [GC-spigot/AdvancedEnchantments#3877]
### Describe the bug

Hey there, so I use AE for server where **resource pack** is really important part of the server, so I just created 5 textures for dusts and books, but noticed it's not possible to define more than one model for **books** (there's an option for dusts tho). Unfortunately you can setup only 1 texture for enchants and that's the one in the config.

I'll be glad if you can add something like an optional
`custom-model-data: value` value in the enchantments.yml file (under every enchantment) or just in the groups.yml. This value should overwrite config's model data value, used for books and allows you to customize 1. specific enchant itself / or / 2. the whole rarity.

I would like to make all of the books different by their appearance, without having to hover over them with the mouse cursor. I think it's really useful suggestion.

### How to reproduce

-

### "/ae plinfo" link

https://paste.md-5.net/egiqikatut

**Comment by ThomasWega** [comment]
Similar to https://github.com/GC-spigot/AdvancedEnchantments/issues/3842. Will handle the feature request there
