### ISSUE TITLE
%left% placeholder

### ISSUE THREAD

**Issue by cesardeltoroc** [GC-spigot/AdvancedEnchantments#3879]
### Describe the bug

The left placeholder is not showing the correct ammount of money needed if a player doesnt have the full balance its translating to XP instead of money.

### How to reproduce

Change price to money:10000 instead of exp:100

### "/ae plinfo" link

https://paste.md-5.net/julinapavi

### Server Log

https://mcpaste.io/f2cb9abea87462c5

**Comment by MylaChuu** [comment]
I can confirm this bug aswell

### Screenshot

![xp](https://github.com/GC-spigot/AdvancedEnchantments/assets/35538738/b2647334-445d-4350-9e12-720c350a3eba)
![money left missmatch](https://github.com/GC-spigot/AdvancedEnchantments/assets/35538738/a7372070-a2de-4f63-8d2b-61df9b0295fe)

### /ae plinfo link

https://paste.md-5.net/qamiviraki

### Server Log

https://mcpaste.io/471797078f9bab8f

**Comment by ThomasWega** [comment]
Should be fixed in the next update!
