### ISSUE TITLE
%has enchantment in hand of <enchant>% Condition not working with vanilla enchants in version 9.5.27

### ISSUE THREAD

**Issue by zylstra1313** [GC-spigot/AdvancedEnchantments#3881]
### Describe the bug

Title

### How to reproduce

Add the condition:
%has enchantment in hand of knockback% = true : %allow%
to an enchant and use the enchant.

### "/ae plinfo" link

https://paste.md-5.net/obubulalik

**Comment by ThomasWega** [comment]
What enchantment are you trying? Send me your whole enchantment please

**Comment by zylstra1313** [comment]
Here's an example of an enchant that doesn't work:
experience:
  display: '%group-color%Experience'
  description: Chance to get more experience from ores.
  applies-to: Pickaxes
  type: MINING
  group: MINING
  applies:
    - ALL_PICKAXE
  levels:
    '1':
      cooldown: 1
      conditions:
        - '%has enchantment in hand of knockback% = true : %allow%'
      effects:
        - EXP:<random number>1-5</random number> @Block
        - CONSOLE_COMMAND:say Test complete!

If you switch "knockback" to any AE enchantment then it works as expected.
(I'm now testing in version 9.5.28)

**Comment by ThomasWega** [comment]
just make the enchantment in UPPERCASE and it works fine. Lowercase will be supported in the next version as well though
