### ISSUE TITLE
custom-enchants-cause-glow is broken

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#3883]
### Describe the bug

As described in the title, setting `custom-enchants-cause-glow` to `true` and trying to enchant an item through any means does not cause a previously unenchanted item to glow. The following related bug is reported in the console when trying to enchant items: https://pastebin.com/y91KWjzx

### How to reproduce

Try to enchant any item with any compatible enchant using `/ae enchant`.

### "/ae plinfo" link

https://paste.md-5.net/upubanevoh

**Comment by ThomasWega** [comment]
Will be fixed in the next version
