### ISSUE TITLE
Enchantment settings are broken with anvils

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#3884]
### Describe the bug

Hello, this is a follow up to #3600, which I apologize for not replying to earlier. I'm on the latest AE version now, and it still seems like anvils will let you combine enchantments (vanilla + custom or custom + custom), even if they are listed in the `not-applyable-with` section in the enchantment.

The same behavior is also present with `required-enchants` and `removed-enchants` - anvils will allow you to add an enchantment regardless if you meet a required enchantment, without removing that enchantment if its listed in `removed-enchants`.

Thanks in advance for your time!

### How to reproduce

 Here's a video of it: 

https://github.com/GC-spigot/AdvancedEnchantments/assets/17891302/941924ab-571e-4b8d-86dd-d085f8508103

The relevant enchantment:
```iceaspect:
  display: '%group-color%Ice Aspect'
  description: |-
    Freeze enemies as if they were in
    powdered snow. Incompatible with
    Fire Aspect.
  applies-to: Swords
  type: ATTACK;ATTACK_MOB
  group: UNCOMMON
  applies:
  - ALL_SWORD
  settings:
    not-applyable-with:
    - FIRE_ASPECT
  levels:
    '1':
      effects:
      - CONSOLE_COMMAND:freeze %attacker name% 300
    '2':
      effects:
      - CONSOLE_COMMAND:freeze %attacker name% 420
```

### "/ae plinfo" link

https://paste.md-5.net/tonipifetu

**Comment by ThomasWega** [comment]
> Hello, this is a follow up to #3600, which I apologize for not replying to earlier. I'm on the latest AE version now, and it still seems like anvils will let you combine enchantments (vanilla + custom or custom + custom), even if they are listed in the `not-applyable-with` section in the enchantment.

about this. Just use the same format but in lowercase. So 
```yaml
  settings:
    not-applyable-with:
    - fire_aspect
```
And because I know this is dumb, In the next update it will be case insensitive, so even your formatting will work

The other things I am still testing but can confirm some functionality is missing for sure. That will be worked on

**Comment by ThomasWega** [comment]
> The same behavior is also present with `required-enchants` and `removed-enchants` - anvils will allow you to add an enchantment regardless if you meet a required enchantment, without removing that enchantment if its listed in `removed-enchants`.

Should be fixed in the next version!
