### ISSUE TITLE
%damage% placeholder doesnt work

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#3885]
### Describe the bug

The %damage% placeholder is not working for the DO_HARM effect

### How to reproduce

Make a DEFENSE armor enchant that does DO_HARM:%damage% @Attacker and it doesnt work. Here is an example:

takedown:
  display: '&bTakedown'
  description: "Absorb enemy damage and\nreflect it back."
  applies-to: 'Armor'
  type: 'DEFENSE;DEFENSE_MOB'
  group: 'UNIQUE'
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 5
      cooldown: 15
      effects:
        - 'CANCEL_EVENT'
        - 'DO_HARM:%damage% @Attacker'
        - 'CACTUS @Victim'

### "/ae plinfo" link

https://paste.md-5.net/wozisoqahi

**Comment by ThomasWega** [comment]
Works fine for me. And the placeholder also parses correctly

**Comment by JHarris12345** [comment]
> Works fine for me. And the placeholder also parses correctly

Can you please test on the exact enchant I made as this doesnt work for me at all

**Comment by ThomasWega** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/08c4efe6-dbc8-41d9-bf1d-38e200a643e3

**Comment by JHarris12345** [comment]
> 2024-01-05.16-05-51.mp4

That is on mobs. It works fine for mobs. It is players it doesnt work on

**Comment by ThomasWega** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/5292f02f-02c2-4e84-a040-f7a3bcdd2274

**Comment by JHarris12345** [comment]
> 2024-01-06.17-59-15.mp4

Are you saying this already works or that it is now fixed

**Comment by ThomasWega** [comment]
Already works

**Comment by JHarris12345** [comment]
I cannot get this to work at all for players

**Comment by JHarris12345** [comment]
> Already works

Are you able to help me out by showing the code for how damage is applied to the player?

**Comment by JHarris12345** [comment]
I see the issue. If the attack damage on the player is 1, it cancels

**Comment by ThomasWega** [comment]
We use Damageable#damage method. Nothing really specific that should cause this
