### ISSUE TITLE
Slot limiter by Group

### ISSUE THREAD

**Issue by JeffersonSerrano** [GC-spigot/AdvancedEnchantments#3887]
### Describe the bug

Hello everyone, it would be great if you could limit the number of enchantments that an item in each group can have.

example:

Slot limit: 
Ulti: 1 
Epic: 2 
Legendary: 3

Thank you so much! ^^

### How to reproduce

Adding enchats to an item

### "/ae plinfo" link

https://pastebin.com/2pXRh4Sg

**Comment by GC-spigot** [comment]
We're already working on this! Thanks for the idea:)
