### ISSUE TITLE
Bug i think

### ISSUE THREAD

**Issue by mclegendary1** [GC-spigot/AdvancedEnchantments#389]
Hello.
I try this, like you sayed
radiation:
  display: '&2Test'
  description: 'Test'
  applies-to: 'Armor'
  type: 'REPEATING'
  time: 5
  group: 'ADM'
  applies:
  - ALL_HELMET
  levels:
    1:
      effects:
      - 'POTION:POISON:1:100 <aoe> radius=7 target=damageable </aoe>'

And:
![Screenshot](https://user-images.githubusercontent.com/32602514/54781096-ae15c100-4c1b-11e9-9462-06e4ba1095bc.png)

**Comment by GC-spigot** [comment]
You need to use `POTION:POISON:1:100 <aoe> radius=7 target=damageable </aoe>` as shown in examples of enchantments.yml
