### ISSUE TITLE
[Feature] Remove lore from SMITHING TEMPLATES when they are used like enchanting book

### ISSUE THREAD

**Issue by iVillager** [GC-spigot/AdvancedEnchantments#3890]
### Describe the bug

I'm currently working on setting up upgrade templates for items, such as an Enchanting Book. I would like to remove the default lore of upgrade templates, which currently looks like this: ![Image](https://i.imgur.com/bDCl4HO.png).
Deleting this lore would make the upgrade template cleaner and more similar to an enchanting book.

### How to reproduce

In order to address this, it would be nice to let people configure this "flag" under the enchanting-book section in the config.yml like the screenshot 
![Screenshot 2024-01-02 170423](https://github.com/GC-spigot/AdvancedEnchantments/assets/7922770/a21e256c-7070-496a-8c8f-b3cb819f68f4)
here

### Screenshots / Videos

https://i.imgur.com/bDCl4HO.png

### "/ae plinfo" link

https://paste.md-5.net/ixusupupap

**Comment by NaTorOG** [comment]
UP, would be a very white cool feature

**Comment by ThomasWega** [comment]
If I understand it right, you want to be able to set ItemFlags (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html)?

**Comment by iVillager** [comment]
Yeah, that would be the solution @ThomasWega

**Comment by ThomasWega** [comment]
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/c1687deb-ba4d-45c6-90cd-cb191202b4df)
just put the flags outside of the ```item```
