### ISSUE TITLE
Cancelling the keep on death effect

### ISSUE THREAD

**Issue by Ayouubyy** [GC-spigot/AdvancedEnchantments#3891]
### Describe the bug

I'm trying to to make a specific weapon that negates the holywhitescroll effect, but the issue is that the KeepOnDeath effect does not trigger any of the api events including the EffectsActivateEvent, and in the api there is not method to remove the holywhitescroll from an item.

### How to reproduce

N/A

### "/ae plinfo" link

N/A

**Comment by ThomasWega** [comment]
this method will be added to the API 
![obrazek](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/2c202c87-b19e-4c52-b991-81c5b5697d28)

Just wait for an update

**Comment by Ayouubyy** [comment]
It does not work, the item will still have the tag "holywhitescrolled" even after removing it with the method above.

**Comment by ThomasWega** [comment]
It should work just fine
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/1a6e5274-4505-4764-ba8f-24f63a7e2ed9)
Note that you need to get the returned value of the method

**Comment by Ayouubyy** [comment]
Okay the tag removing and stuff works all good. But for my case it's still not working. I'm listening to entityDamageByEntity event and removing the effect, it does get removed for the item but the player still keeps the item on respawning. Is there a way I can go around this issue?

**Comment by ThomasWega** [comment]
Please create a new issue on this and show the full code if possible
