### ISSUE TITLE
Gkits pvp

### ISSUE THREAD

**Issue by dinobossytnew** [GC-spigot/AdvancedEnchantments#3893]
### Describe the bug

I was testing the gkits since I tried the cosmic pvp that came with 1 pack that you make and in 1 kit I got that error.
https://bin.bloom.host/fuxuhaquxa.csharp

### How to reproduce

Install the default pvp cosmic pack and try the GrimReaper gkits.

### Screenshots / Videos

![2024-01-03_11 22 13](https://github.com/GC-spigot/AdvancedEnchantments/assets/58078116/7ad3abc0-df96-456e-8aa7-6866b72731e2)

### "/ae plinfo" link

https://paste.md-5.net/amudopovam

### Server Log

https://mclo.gs/YiXRHN1

**Comment by ThomasWega** [comment]
Fixed. Just re-download it
