### ISSUE TITLE
arclight-forge-1.19.2-1.0.2 Please make it compatible

### ISSUE THREAD

**Issue by ii109** [GC-spigot/AdvancedEnchantments#3894]
### Describe the bug

[latest.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/13825456/latest.zip)

### How to reproduce

arclight-forge-1.19.2-1.0.2 Please make it compatible

### "/ae plinfo" link

/ae plinfo skiplugins

**Comment by GC-spigot** [comment]
Looking into this!
