### ISSUE TITLE
ClassNotFoundException when using /ae enchant

### ISSUE THREAD

**Issue by Nanpure** [GC-spigot/AdvancedEnchantments#3895]
### Describe the bug

Trying to enchant using /ae enchant works but dumps an error in the log.

### How to reproduce

Creative mode. Give self sword. Use `/ae enchant decapitation 1`. See log.

### "/ae plinfo" link

https://paste.md-5.net/ayuralezaj

### Server Log

https://mcpaste.io/4e98ae2d9a91cc7d

**Comment by ThomasWega** [comment]
We know about this issue. If you set ```custom-enchants-cause-glow``` to ```false``` the error will go away for the time being

**Comment by GC-spigot** [comment]
Fixed next version
