### ISSUE TITLE
Lore Customization

### ISSUE THREAD

**Issue by Rectos28** [GC-spigot/AdvancedEnchantments#3899]
### Describe the bug

The lore of the items when enchanted need to allow more customization asit lacks alot.
When using the **slots placeholder** it always displayed at the bottom of the **enchantments**. Also, adding more placeholder for like how many slots used and the total slots available, so we can have somthing like:

- For an Item with 2 enchants and total 6 slots:

` (%slots_used%/%slots_total%) = (2/6)`

And for lore customization, add the abbilty to rearrange everything and placeholder text for available slots:
- For an Item with 2 enchants and total 6 slots the lore will be:
```
%item_name%
Enchant Slots: (%slots_used%/%slots_total%)
%enchantments%
```
While `%enchantments%` placeholder display the enchants and the free slots
That will be like:
```
Iron Sword
Enchant Slots: (2/6)
- Mending
- Sweeping Edge I
- Free Slot
- Free Slot
- Free Slot
- Free Slot
```

Example image represent my request:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/39403034/d0af533e-6729-45fb-a03a-7fef45a53365)

There is other plugins do that but don't support AdvancedEnchantments as it's not a real enchant plugin. [Link to the Plugin](https://www.spigotmc.org/resources/enchantmentslots-add-enchantment-slot-feature-to-your-server-1-17-1-20.113048/).

### How to reproduce

idk

### "/ae plinfo" link

idk

**Comment by GC-spigot** [comment]
This isn't planned yet but we will add this in the future. I will archive this for us to come back later.

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
