### ISSUE TITLE
Issue with blocks 20x + amount of blocks broken with 9.5.28 update

### ISSUE THREAD

**Issue by Kaludii** [GC-spigot/AdvancedEnchantments#3900]
### Describe the bug

Hello, something with the newest update makes blocks broken like 25x for %statistic_mine_block%. I broke like 6 blocks and it went from 400 to 10k. Many players in our server now have millions of blocks broken in the leaderboard even though they only broke a few thousand. It started on from 9.5.28, the previous versions look fine. It may be due to the following:
```
If this option can be changed in the config that would be helpful:
9.5.27 Changelog
Changes:
Blocks broken by effects are now added to Player's Minecraft Stats
```
An option to disable blocks broken by effects not being counted in the minecraft stats would be useful as well.

### How to reproduce

Download 9.5.28 and eqip any enchant from AE and start breaking blocks. Check `%statistic_mine_block%` before and after and see the huge increase from the actual amount of blocks broken.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63890666/3f36ef24-e4b0-412d-910e-668179a0fe9a)

### "/ae plinfo" link

https://paste.md-5.net/buzagaguxu

**Comment by ThomasWega** [comment]
added option ```minecraft-stats-blocks-broken-count``` to config.yml in the next update
