### ISSUE TITLE
Tinkerer customization

### ISSUE THREAD

**Issue by Bounty38** [GC-spigot/AdvancedEnchantments#3903]
### Describe the bug

Would be great if you could disable dusts and make tinker trade only in exp bottles. My goal is to remove dusts, stattracks etc. and leave only enchantments and custom exp bottles. I dont want to disable tinkerer cause it gives players ability to trade their enchanted items for exp bottles. I just dont want them to get any dusts from him

### How to reproduce

-

### "/ae plinfo" link

-

**Comment by ThomasWega** [comment]
Will be in the next update!
