### ISSUE TITLE
gkits still dont work as expected

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#3904]
### Describe the bug

In the latest spigot update it says that armor trims are now applied in gkits but they still dont

### How to reproduce

I have this gkit:

  spacesuit:
    hide: TRUE
    slot: 2
    delay: 0
    content:
      '1':
        material: NETHERITE_HELMET
        data: 0
        amount: 1
        name: '{#dfdfea}&lS{#e5e5ee}&lp{#ececf2}&la{#f2f2f7}&lc{#f9f9fb}&le {#ffffff}&lH{#f9f9fb}&le{#f2f2f7}&ll{#ececf2}&lm{#e5e5ee}&le{#dfdfea}&lt'
        lore:
        - '&eUnbreakable'
        - ''
        - '&3Official Space Suit'
        - '&3Galactic Crate 2023'
        advanced-enchantments:
        - "subzero:1"
        enchants:
        - protection_explosions:30
        - protection_fire:30
        - protection_projectile:30
        - protection_environmental:30
        - water_worker:1 # Aqua affinity - helmet
        - respiration:30 # helmet
        armor-trim: 'IRON;SILENCE'

It doesnt give it with the trim

### "/ae plinfo" link

https://paste.md-5.net/yafageyame

**Comment by GC-spigot** [comment]
Example format:
```yaml
  Cosmonaut:
    content:
      '1':
        advanced-enchantments:
        - guardians:%1-10%
        - immortal:%1-4%
        amount: 1
        data: 0
        enchants:
        - protection:5
        - unbreaking:3
        lore:
        - '&6&oForged of the finest materials in all'
        - '&6&othe galaxy. A timeless, unique piece.'
        material: DIAMOND_CHESTPLATE
        armor-trim: IRON;SILENCE
        name: '&6&lCosmonaut Spacesuit'```
        
       Outcome:  
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/13188801/712f56a4-67d3-49c3-ad29-6911a73d985f)
