### ISSUE TITLE
%group% placeholder not working for ae info

### ISSUE THREAD

**Issue by Kaludii** [GC-spigot/AdvancedEnchantments#3905]
### Describe the bug

Hello, when using `/ae info (enchant)`, I added the %group% placeholder which was already present in the en-us.yml file, but when the command is run the group shows up as something else, not the actual group of the enchant

```
    info:
      - "&eInformation about &6%enchant% &eenchantment&7:"
      - "&6Description&7: &e%description%"
      - "&6Group&7: &e%group%"
      - "&6Max level&7: &e%max-level%"
      - "&6Applies to&7: &e%applies%"
```

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63890666/6ef28565-c265-4275-9e31-3fb5deef9381)

### How to reproduce

Download latest version of AE and add the following line to the AE info section in en-us.yml:
```
      - "&6Group&7: &e%group%"
```

### "/ae plinfo" link

https://paste.md-5.net/vatorudapa

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thanks!
