### ISSUE TITLE
Duplicating items when using Detonate

### ISSUE THREAD

**Issue by Edsher08** [GC-spigot/AdvancedEnchantments#3906]
### Describe the bug

when I try to mine using the Detonate + Silktouch some of the items will or ores will be duplicated

### How to reproduce

Get ores/items like ender chest then mine it using Detonate + Silktouch combined in a pickaxe. when the Detonate is used the item will be duplicated

### "/ae plinfo" link

https://paste.md-5.net/yuwamoqowi

**Comment by ThomasWega** [comment]
please send a video

**Comment by ThomasWega** [comment]
Also update your plugin please
