### ISSUE TITLE
MORE_DROPS dupe items with trench

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#3907]
### Describe the bug

if trench enchantment is installed with more_drops, more drops will drop multiple blocks that is placed by player.

### How to reproduce

1. place a block that want to dupe
2. use trench enchantment with more_Drops
3. break  the near by block (instead of the targeted dupe block)

### Screenshots / Videos

https://youtu.be/f8tvdDNHDt8

### "/ae plinfo" link

https://paste.md-5.net/unodicaduk

**Comment by ThomasWega** [comment]
send your enchantments

**Comment by hkkongou** [comment]
5 enchantments on the pickaxe are
https://paste.denizenscript.com/View/119496

**Comment by ThomasWega** [comment]
Not able to reproduce it. Tried with all the enchantments and works completely fine without any dupes
