### ISSUE TITLE
Potion effect remains active when removing item from offhand

### ISSUE THREAD

**Issue by markusew** [GC-spigot/AdvancedEnchantments#391]
If you have an item with a static potion effect and put it in your off-hand you can then remove the item from your off-hand using your mouse (not with the hotkey) and that effect will stay active without you having to hold the item. 

This image is an example of me having the static potion effect without having the item equipped.
https://i.imgur.com/PRQQ7wN.png

EDIT: I would also like to add that the static potion effect of the item is not applied when you drop the item off in your off-hand slot. You have to use the hotkey to get it to apply the effect.

**Comment by GC-spigot** [comment]
Fixed!
