### ISSUE TITLE
Holy White Scroll Configuration 

### ISSUE THREAD

**Issue by YT-Duckyyy** [GC-spigot/AdvancedEnchantments#3910]
### Describe the bug

I believe that Holy White Scrolls should have a configuration option to change the percentage rather than 100% all the time. For example players could set it to 50/50 chances instead.

On top of this, an effect to counter Holy Whitescrolls would be awesome 👌 

Like "HOLY:[PERCENTAGE]", percentage being how much to negate by, for example "HOLY:10" would make it a 90% chance of working.

Both of these additions would be lovely especially for factions servers!

### How to reproduce

.

### "/ae plinfo" link

.

**Comment by GC-spigot** [comment]
We'll look into this
