### ISSUE TITLE
Version 9.5.29 breaks color formating

### ISSUE THREAD

**Issue by TheLaoming** [GC-spigot/AdvancedEnchantments#3911]
### Describe the bug

Hey, with version 9.5.29 or newer are broken colors in lore formating. So here's the deal:

```
description: |-
    Line 1 something something
    Line 2 something something
    Line 3 something something
    Line 4 something something
```
Description section works just fine if you have one or two lines of lore, once you add third line (or more), colors are broken like this.
![broken_lore](https://github.com/GC-spigot/AdvancedEnchantments/assets/75527300/53e162bf-8e9e-4fa2-abf8-e044ffeeddf7)
I've tried multiple formating styles but it doesn't work, don't know how about regular colors, I use only hexes.

Second bug and just a small detail, you probably forgot but in update [9.5.27](https://www.spigotmc.org/resources/25-sale-%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90-create-custom-enchantments-%E2%9C%85-1-13-1-20-4.43058/update?update=527458) you added "Tinkerer's take-currency message is translateable" but this one actually doesn't work, it's not even autoadded into the file and when you add it manually, it's the same result.

### How to reproduce

Create an enchant with more than 2 lore lines.

### "/ae plinfo" link

https://paste.md-5.net/fuwoteyelo

**Comment by GC-spigot** [comment]
Just assign colors to each line, that seems like it could be a default minecraft behavior. The italic purple style is default minecraft behavior when there's no color assigned, it's probably reset after a new line or two.

**Comment by TheLaoming** [comment]
I know it's a default mc behavior, I wanted to avoid editation of almost 200 enchantments tho. I just created this beacuse it was fine before this version. Anyway, Tinkerer's **take-currency message** is not translantable since version [9.5.27 Changelog](https://www.spigotmc.org/resources/25-sale-%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90-create-custom-enchantments-%E2%9C%85.43058/update?update=527458), even when it's manually added. You probably missed it cuz it still doesn't work with latest AE.

**Comment by ThomasWega** [comment]
> I know it's a default mc behavior, I wanted to avoid editation of almost 200 enchantments tho. I just created this beacuse it was fine before this version. Anyway, Tinkerer's **take-currency message** is not translantable since version [9.5.27 Changelog](https://www.spigotmc.org/resources/25-sale-%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90-create-custom-enchantments-%E2%9C%85.43058/update?update=527458), even when it's manually added. You probably missed it cuz it still doesn't work with latest AE.

please create a new issue on it and I will fix it right away. Just so I don't forget
