### ISSUE TITLE
Grindstone Lore Bug

### ISSUE THREAD

**Issue by kcw0205** [GC-spigot/AdvancedEnchantments#3913]
### Describe the bug

So currently, when I put in an item with customenchantments on it into a grindstone, the result display(like the result slot) still has all the lores from the enchantments but when i actually take it out, it will remove both the enchantment and the lore.

### How to reproduce

The grindstone should do its job, get rid of ALL the vanilla enchantments and ALL the custom enchantments, and as well as display the result item WITHOUT the lores from custom enchantments like it does with vanilla.

### Screenshots / Videos

<img width="729" alt="Screenshot 2024-01-09 at 10 34 52 PM" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/50742278/57c2c8b5-0544-45b7-9725-7afcafd9258d">

### "/ae plinfo" link

https://paste.md-5.net/goqagugidi

**Comment by ThomasWega** [comment]
The issue with this is that the events which allow us to do this properly are present only in the latest versions, which we don't currently have our dev environment prepared for. We first need to update some stuff and then I will quickly fix this up. Might take some time though.

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Sorry for the long wait
