### ISSUE TITLE
KILL effect doesn't work, DEATH doesn't work either

### ISSUE THREAD

**Issue by Olavvvv** [GC-spigot/AdvancedEnchantments#3914]
### Describe the bug

The effect kill dont work

### How to reproduce

The effect kill dont work

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/94938785/2cde1e73-63e6-4260-a9e4-667f1b6dc471)

### "/ae plinfo" link

latest version

**Comment by ThomasWega** [comment]
It works completely fine
