### ISSUE TITLE
Miner enchantment not working

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3915]
### Describe the bug

Miner III enchantment is not working

enchantments.yml: https://pastebin.com/raw/zWEF0Nie

### How to reproduce

1. Break blocks with pickaxe that has Miner III enchantment

### "/ae plinfo" link

https://paste.md-5.net/qijujekiya

**Comment by ThomasWega** [comment]
Actually. Not a bug. Only odd numbers are allowed
