### ISSUE TITLE
TP_DROPS crop drops are too high

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3916]
### Describe the bug

It appears that breaking certain crops with a TP_DROPS enchantment drops more crops than it should. Tested and confirmed with wheat (drops 2) and carrots (drops like 8-11). Tried with beetroot and it only dropped one as it should, so doesn't seem to be all crops.

### How to reproduce

Break wheat/carrot/(other crops?) with a TP_DROPS enchanted tool.

### "/ae plinfo" link

https://paste.md-5.net/joyepufaha

**Comment by ThomasWega** [comment]
doesn't McMMO skill cause this? I know I was adding this compatibility a while ago. Might be activated even without any skill though. Please test it

**Comment by Dakotaa** [comment]
Doesn't seem to be mcMMO related, my mcMMO Herbalism level wasn't high enough to be triggering consistent double drops

**Comment by Dakotaa** [comment]
Nevermind, it does seem to be something with mcMMO, as it's only happening with mcMMO loaded. Not sure why, because my double drops should not be triggering, so might be a bug with mcMMO. My bad, apologies for any confusion

**Comment by ThomasWega** [comment]
I think it was possible that we handled double drops even if the user didn't have herbalism skill. Did take some precautions for this, so that might help.
