### ISSUE TITLE
Feature request. Advanced Enchantments Guards

### ISSUE THREAD

**Issue by Celipa** [GC-spigot/AdvancedEnchantments#3917]
### Describe the bug

Ive seen that several other players have asked for this feature as well in the discord, That we should be able to use baby mobs as Guard when it comes to enchantments and other features. For example being able to have Baby Zombies as a Guard in the enchantments. I would assume to either have them as BABY_(MOB) OR (MOB_(BABY).

### How to reproduce

Example

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/143783754/de6250e7-588f-415e-bd2e-34bfeddbf763)

### "/ae plinfo" link

ee

**Comment by ThomasWega** [comment]
Will be added in the next update!
