### ISSUE TITLE
Request for enchbook plugin compatibility

### ISSUE THREAD

**Issue by kingakis2** [GC-spigot/AdvancedEnchantments#3918]
### Describe the bug

is related to anvils i use enchbook for op enchantments likely power 6 or sharpness 6 and the plugin have and option in her config to don't allow this books be able to combine on anvils and gain +1 level their levels

like power 6 + power 6 = power 7

but with advancedenchantments anvils enabled it ignores i really appreciate if this can be fixed or added

### How to reproduce

for example, with anvils= true and enchbook plugin use ''/be newbook power 6'' two times

on anvil: power 6 + power 6 = power 7

even with the Safe Books: true on the enchbook config

### "/ae plinfo" link

https://paste.md-5.net/esaqikomaz

**Comment by kingakis2** [comment]
https://www.spigotmc.org/resources/enchbook.62545/ heres plugin link

**Comment by ThomasWega** [comment]
Works fine for me. Make sure this is changed in anvil.yml
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/70e23225-457f-4a03-8bb4-3e32e1c34fc9)

**Comment by kingakis2** [comment]
the plugin have and option to don't allow books gets their level upgrade on the anvil for example using power 6 + power 6 = power 7 but with the safebook option on true it will be power 6 + power 6 = power 6

i want compatibility with that, i already know about those options on anvils
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/109235946/b6dd97ef-26fb-4db3-9cad-dbf7741dcd6a)


> Works fine for me. Make sure this is changed in anvil.yml ![image](https://private-user-images.githubusercontent.com/82312488/298047902-70e23225-457f-4a03-8bb4-3e32e1c34fc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzA2MzYsIm5iZiI6MTcwNTY3MDMzNiwicGF0aCI6Ii84MjMxMjQ4OC8yOTgwNDc5MDItNzBlMjMyMjUtNDU3Zi00YTAzLThiYjQtM2UzMmUxYzM0ZmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEzMTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MDRmNzhjMmExM2M3YzNiNmZlNTY4NTE1NWI2MTNjMTVlY2JlN2Q0NzJlOGFjNzk3MjgyY2UyNzYxMWRhZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lt4fWB1huIUcu0PChEPpqAPoDulYCMUv816PGgFURI0)
