### ISSUE TITLE
Enhancement: Player-look direction to Boost effect + Left/Right

### ISSUE THREAD

**Issue by xenxero1** [GC-spigot/AdvancedEnchantments#3919]
### Describe the bug

Currently the Boost effect can only operate on Up/Down/Forward/Backwards. I would like to have the ability for Boosting in strafe directions (Left/Right), and more importantly, the ability to boost in the direction the player is looking. Currently there is no way for my players to boost on an angle to traverse terrain, only a straight boost upwards, or a boost forwards which only really works if the player is in the air. I'd like the option to use Pitch/Yaw to set the boost direction for more dynamic movement.

### How to reproduce

Feature Request

### "/ae plinfo" link

https://paste.md-5.net/omecosexey

**Comment by xenxero1** [comment]
It's worth noting that currently EpicEnchants has this capability, where their version of BOOST (They call throw) has similar formatting to AE's Boost, but their Forward parameter functions on pitch/yaw instead of using the flat XZ-plane.

**Comment by Skullslice** [comment]
also it would be cool if you could pass 2 velocities and 2 directions into the effect and have it normalize the vector for you.
for example:
BOOST:FORWARD:5
BOOST:UP:2
as it is right now, the second boost completely cancels the velocity of the first one and I want to make an effect that rockets you forward and up.

**Comment by ThomasWega** [comment]
Would it be enough for you to allow look direction boost? Like so:
```yaml
- BOOST:LOOK:25 @Self
```

https://i.imgur.com/OyxZ2dO.mp4

**Comment by xenxero1** [comment]
For my uses that would be exactly what im looking for!

May be worth still having the discussion about normalized vectors still though, for things like curved knockback systems etc.

**Comment by ThomasWega** [comment]
That is something we'll think about and might be added in the future. For now I will just add the LOOK direction
