### ISSUE TITLE
xp was not given When using AureliumSKills ability with smelt

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3921]
### Describe the bug

When using AureliumSKills terraform with smelt applied pickaxe, xp is not obtained.

### How to reproduce

1. enchant smelt on tools
2. execute ability from AureliumSkills

### Screenshots / Videos

https://youtu.be/YHNHYy9R4Ko

### "/ae plinfo" link

https://paste.md-5.net/sujoduzomu

**Comment by ThomasWega** [comment]
If I was to guess AureliumSkills handles events some stupid was as they usually do. We don't cancel any events nor do we change the contents of the events as far as my knowledge goes. So I'd try going to AureliumSkills devs about this
