### ISSUE TITLE
Enchants group list page button bug

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#3923]
### Describe the bug

When the enchants group list has more than 1 page then showing "Next page", but no more pages are.

### How to reproduce

Go to Elite (same with Ultimate and Legendary ) enchants list GUI and go to laste page and see "Next page" button.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/8950371/8dd92484-c8fa-47e4-a5d9-a0062274f62a)

### "/ae plinfo" link

https://paste.md-5.net/aheyeyoyis

**Comment by ThomasWega** [comment]
Will be fixed in the next update
