### ISSUE TITLE
New Feature: Slot Increasers Change

### ISSUE THREAD

**Issue by YT-Duckyyy** [GC-spigot/AdvancedEnchantments#3926]
### Describe the bug

Also, slot increasers, the rarity ones, is there a way to have a placeholder on item to say "Empty Elite Enchantment Slot" or something? to allow players to see theres one added?

Cause currently there's no way to tell at all.... 

### How to reproduce

.

### "/ae plinfo" link

.

**Comment by GC-spigot** [comment]
We'll look into it for the future.
