### ISSUE TITLE
Slot-increaser force-glow not working

### ISSUE THREAD

**Issue by uploadx10** [GC-spigot/AdvancedEnchantments#3927]
### Describe the bug

After I updated the new version Slot-increaser The old one cannot be used because force-glow doesn't work causing the nbt item to not match.

### How to reproduce

Cannot be used with items.

### Screenshots / Videos

-

### "/ae plinfo" link

https://paste.md-5.net/idagusayap

**Comment by ThomasWega** [comment]
You need to add force-glow: true in groups.yml
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/b7094dbc-dccf-4e19-bdf1-d999a5ec6f2c)
We will however fix it that if don't have this section present in groups.yml a main one from the config.yml will be taken
