### ISSUE TITLE
plugins can't work 

### ISSUE THREAD

**Issue by ximuya2** [GC-spigot/AdvancedEnchantments#3928]
### Describe the bug

plugins can't work 

### How to reproduce

not

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/113600917/64949428-8080-4061-b838-7cfd7ec9dfc0)

### "/ae plinfo" link

not

### Server Log

not

**Comment by GC-spigot** [comment]
This means nothing, post full server log.

**Comment by ximuya2** [comment]
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/13937409/latest.log)

**Comment by ThomasWega** [comment]
[AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

Join our discord https://discord.com/invite/tm9QzqvmQA
