### ISSUE TITLE
holywhitescroll causes exception and item isn't kept

### ISSUE THREAD

**Issue by mfnalex** [GC-spigot/AdvancedEnchantments#3929]
### Describe the bug

EDIT: Also happens without any other plugins, see reply below

Whenever a player dies with a holywhitescroll-enchanted item in their inventory and having EssentialsX enabled, the following stacktrace is printed and the item isn't kept on death: https://paste.jeff-media.com/?b67bbfba6495a765#7v9u9V9oucpqEMP6FLxEVY4HvCZaAHh44Vo3DDjn9Yoe

Plugins: AdvancedEnchantments 9.6.3, EssentialsX 2.21.0-dev+25-fbfd7e9
Server: git-Paper-388 (MC: 1.20.4)

### How to reproduce

1. /ae giveitem holywhitescroll <name> 1
2. /give diamond_axe  1
3. apply holy white scroll to axe
4. die -> stacktrace, item isn't kept

### "/ae plinfo" link

https://paste.md-5.net/ezojinafek

**Comment by mfnalex** [comment]
I have noticed that this also happens when having only AE installed, and no other plugins: https://paste.jeff-media.com/?b591f5d9503b31c8#35qFXhsx8Ke61aB6FBXUMAwg9BfxrYELU9jrq3eVMLK1

**Comment by ThomasWega** [comment]
Will be fixed in the next update
