### ISSUE TITLE
Failed to activate effect ´break_block_block´

### ISSUE THREAD

**Issue by HectorMech** [GC-spigot/AdvancedEnchantments#3931]
### Describe the bug

I have a pickaxe with the following enchantments:
- Experience 4.
- Detonate 7.
- Telepathy 4. 
- Abiding 1.
When I want to mine, I get the following error on the console and in the game:
[08:03:02 WARN]: [AdvancedEnchantments] Failed to activate effect 'BREAK_BLOCK_BLOCK '
[08:03:02 WARN]: [AdvancedEnchantments] Additional information: Failed to activate effects as advancedEffect is null or invalid: 'BREAK_BLOCK_BLOCK', BREAK_BLOCK_BLOCK , trigger:MINING, entity:HectorMechanix

PD: Sorry for my English, I'm Argentine.

### How to reproduce

It occurs when I want to mine with detonate

### Screenshots / Videos

![Error](https://github.com/GC-spigot/AdvancedEnchantments/assets/156667278/7271ad24-ab3b-49ea-8e75-f2a3ae6674dc)

### "/ae plinfo" link

https://paste.md-5.net/disacaqoze

### Server Log

https://mcpaste.io/58458accae52171e

**Comment by ThomasWega** [comment]
You have incorrect formatting. Use BREAK_BLOCK @Block

**Comment by HectorMech** [comment]
I changed it and I get a new error.
![New error](https://github.com/GC-spigot/AdvancedEnchantments/assets/156667278/3b31a300-bf86-4446-8688-278d826ea80d)
![Notes](https://github.com/GC-spigot/AdvancedEnchantments/assets/156667278/551b0a04-3287-4957-a318-fd903c3675fd)
