### ISSUE TITLE
RegEx example on website incorrect

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3932]
### Describe the bug

You state on this website: https://wiki.advancedplugins.net/abilities/conditions/condition-comparison

That the following expression is meant to check if a username starts with a dot:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/39222968/be519da3-6b49-4ce3-8a5e-14524f5c32ae)

That's simply not true, the dot at the start matches any character and is simply a wrong example.

Instead of `.\w+` it should be `\.\w+` where the `\.` escapes the dot, making it a literal dot, see also https://regex101.com/ for reference.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/39222968/a31d8ece-f81a-437b-beeb-46594f7072b4)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/39222968/5545ba43-9e36-41e2-8582-58036fa29768)

### How to reproduce

See above

### Screenshots / Videos

Not required

### "/ae plinfo" link

Not required

### Server Log

Definitely also not required

**Comment by Folas1337** [comment]
I've also just come to realize that perhaps it'd even be more accurate to use `^\.\w+` in the example as `^` in RegEx stands for the start of a line, so your wording of "starts with" would be even more accurate.
I'll leave the decision up to you which one you want to choose but definitely don't use the one that's currently on the website as it's factually wrong.

**Comment by ThomasWega** [comment]
Will be updated soon. Thank you
