### ISSUE TITLE
Failed to activate effect ´break_block @block´

### ISSUE THREAD

**Issue by HectorMech** [GC-spigot/AdvancedEnchantments#3933]
### Describe the bug

I have a pickaxe with the following enchantments:

Experience 4.
Detonate 7.
Telepathy 4.
Abiding 1.
When I want to mine, I get the following error on the console and in the game.

### How to reproduce

It occurs when I want to mine with detonate.

### Screenshots / Videos

![New error](https://github.com/GC-spigot/AdvancedEnchantments/assets/156667278/a8301095-7f84-4bc2-811b-db8c89b7ca29)
![Notes](https://github.com/GC-spigot/AdvancedEnchantments/assets/156667278/25308fb0-f5ff-43d7-8747-22014cf0a502)
1

### "/ae plinfo" link

https://paste.md-5.net/obikevezos

### Server Log

https://mcpaste.io/b15333c552031541

**Comment by ThomasWega** [comment]
you are using radius on @Block, which is not correct. Radius is on @Trench. Also, you have need to have the first letter in uppercase, so @Block not @block
