### ISSUE TITLE
Telepathy causing placed ores to dupe

### ISSUE THREAD

**Issue by plumpkiwi** [GC-spigot/AdvancedEnchantments#3934]
### Describe the bug

when using a pickaxe with telepathy, placing down ores and mining them again causes it to dupe

### How to reproduce

enchant a pickaxe with telepathy, place down ore then mine to pick back up, repeat 

### Screenshots / Videos

https://youtu.be/YPxIevA2rbM

### "/ae plinfo" link

https://paste.md-5.net/ilonufetuj

**Comment by ThomasWega** [comment]
Will most likely be another plugin causing this. Not our fault if I had to guess though. If you try with only AE it works fine
