### ISSUE TITLE
Levels still display on item name even if %level% not present

### ISSUE THREAD

**Issue by YT-Duckyyy** [GC-spigot/AdvancedEnchantments#3935]
### Describe the bug

Levels still display in the enchantment item name, even when %level% is not present within the config file.

### How to reproduce

Remove %level% from enchantment-item config option name, and it'll still be there

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/97541939/62d106e6-439b-4681-add5-cc0bfc3b8862)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/97541939/96a88b84-019e-403f-ad5b-94401a99e848)

### "/ae plinfo" link

https://paste.md-5.net/navedayapi

**Comment by ThomasWega** [comment]
It won't update old books, but for new ones it works completely fine
<img width="506" alt="image" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/6b9ed249-ffeb-414b-9dbf-ae06c7174fc7">
<img width="331" alt="image" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/d76f6eaf-a6be-4e36-ba8d-cc33fcdc7933">

**Comment by YT-Duckyyy** [comment]
That's not the case my end, even after restarting, reloading and getting new books, it still states the level. What placeholder are you using? Maybe I've done it wrong

**Comment by ThomasWega** [comment]
Figured out it's because of the %enchant% placeholder. It displays the level as well. Is it possible for you to use %enchant-no-color%?

**Comment by YT-Duckyyy** [comment]
Yeah that's fine, I'll have a little play around and figure it out. Thank you
