### ISSUE TITLE
Disable Armorsets Feature - Request

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3939]
### Describe the bug

Just like this feature, please also add Disable armorsets in specific world <3
```
disable-enchants:
  # Disable enchants in specific world
  raidworld: # world name
    - gears
```

let's say
```
disable-armorsets:
  # Disable armorsets in specific world
  raidworld: # world name
    - koth
    - timetraveler
```

### How to reproduce

N/A

### Screenshots / Videos

N/A

### "/ae plinfo" link

N/A

### Server Log

N/A

**Comment by ThomasWega** [comment]
Will be added in the next update
