### ISSUE TITLE
Smelting dupe bug with mcmmo

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#3942]
### Describe the bug

When having silk touch and smelting you get double drops when mining your own buildet ores.

### How to reproduce

Build ore and break it. Have mining 1000lvl. and pickaxe:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/8950371/c351e8cd-a950-4777-887b-0ed51a3a106d)

Video:
https://youtu.be/dI1dLEyssEopickaxe

### "/ae plinfo" link

https://paste.md-5.net/uqebufolis

**Comment by ThomasWega** [comment]
Just tried it and all works fine, no dupe
