### ISSUE TITLE
DISARM effect drops weapon

### ISSUE THREAD

**Issue by menkisa** [GC-spigot/AdvancedEnchantments#3945]
### Describe the bug

DISARM effect is dropping the weapon from the inventory, if you have your inventory filled while being disarmed, instead of returning it back. I think it should go back to its place and drop the last added item in the inventory 

### How to reproduce

1. Take a sword with disarm and disarm the target which stays on top of items
2. When the target is disarmed, the items below will fill the whole inventory of the target and the disarmed target will be forced to drop the weapon.

### "/ae plinfo" link

Keeping private, has nothing to do with the issue

### Server Log

No errors

**Comment by ThomasWega** [comment]
We'll think about this feature
