### ISSUE TITLE
Failed to activate effect problem

### ISSUE THREAD

**Issue by Captain7604** [GC-spigot/AdvancedEnchantments#3946]
### Describe the bug

When I hit someone with an axe a chat message appears that says 

![2024-01-19_23 09 59](https://github.com/GC-spigot/AdvancedEnchantments/assets/128932062/74194630-2e0e-4661-9395-0cce9b9b5984)

### How to reproduce

I simply hit another player with my axe and I get the error in chat.
![2024-01-19_23 14 48](https://github.com/GC-spigot/AdvancedEnchantments/assets/128932062/f7e6ffb4-c1c2-4e88-bce9-552a97c59ba7)

### "/ae plinfo" link

https://paste.md-5.net/feyocibaba

**Comment by SirJben** [comment]
EXTRA_DAMAGE doesn't exist anymore. Use `INCREASE_DAMAGE`
Kindly refer to this page: https://wiki.advancedplugins.net/abilities/effects
