### ISSUE TITLE
enchbook safe books option compatibility or a new option on anvil.yml

### ISSUE THREAD

**Issue by kingakis2** [GC-spigot/AdvancedEnchantments#3948]
### Describe the bug

the plugin enchbook (https://www.spigotmc.org/resources/enchbook.62545/) have and option on their config.yml to don't allow books gets their level upgrade combining them on the anvil and is called ''Safe Books=''

when you put this option on true it must be power 6 + power 6 = power 6 don't allowing to upgrade the level and it works but with advancedenchantments anvil enabled it doesn't

for example it will be power 6 + power 6 = power 7 even if the option ''Safe Books='' on enchbook plugin is on true

i was wanting if is possible compatibility with that or some new option included on anvil.yml to not allowing books be upgraded it will be great and i already know about the maximum levels vanilla config but that is not related and works fine

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/109235946/0d91ab54-3b3e-4d04-9a45-ee377d3822da)

### How to reproduce

put ''Safe Books= true'' on enchbook config.yml
on anvil (with enaled= true on anvil.yml advancedenchantments) put any enchantment for example sharpness 6 + sharpness 6 it will convert to sharpness 7

as i explain and the option safe books on true himself explain it should not be like that

### "/ae plinfo" link

https://paste.md-5.net/ipiwiqikug

**Comment by kingakis2** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/issues/3918 same issue closed because of misunderstanding

**Comment by ThomasWega** [comment]
We'll look into this

**Comment by kingakis2** [comment]
if you guys ain't going to help with this just tell it and don't make others lose the time
