### ISSUE TITLE
Bug with CMI heads and Smelt enchantment

### ISSUE THREAD

**Issue by Joaofixe** [GC-spigot/AdvancedEnchantments#3949]
### Describe the bug

When I use the smelt enchantment from Advanced Enchantments on CMI heads, they duplicate; however, if it's heads from other plugins, this doesn't happen. Is this an issue with the enchantment or with CMI? (no erros on console)

### How to reproduce

/cmi mobhead zombie (or other mob)
Enchant a tool with the Smelt enchantment, regardless of the level.
Place the CMI head on the ground.
Break the head you just placed with the tool you just enchanted.

### Screenshots / Videos

https://prnt.sc/Nq_C4L9wPhfy

### "/ae plinfo" link

https://paste.md-5.net/hihanulura

**Comment by ThomasWega** [comment]
If I had to guess I'd say that CMI handles head drops differently. We might be able to check if it's CMI head and don't drop the item. Can you send the NBT data of the head please?

**Comment by ThomasWega** [comment]
Aha. All blocks you break in creative get duped this way. Will be fixed in the next update!

**Comment by lajnicek** [comment]
> If I had to guess I'd say that CMI handles head drops differently. We might be able to check if it's CMI head and don't drop the item. Can you send the NBT data of the head please?

Hello,
AE Version 9.6.11 (latest) and bug is still here.
CMI Version 9.6.10.1 (latest)
Survival gamemode
/ae plinfo: https://paste.md-5.net/exisaqefib

Adding more info:

Head from CMI → picture 1 with 3 NBT tags

Head mined with enchant Smelting (III) → always drops two heads → picture 1 (3NBT Tags) and picture 2 (2NBT Tags)

Head mined with enchant Telepathy (IV) → sometimes drops two heads → picture 1 (3NBT Tags) and picture 1 (1NBT Tag) 

![1_base_3NBT](https://github.com/GC-spigot/AdvancedEnchantments/assets/117314475/365b8829-1e93-4a2e-a06a-93f003520e1b)
![2_smelting_2NBT](https://github.com/GC-spigot/AdvancedEnchantments/assets/117314475/a8ab33cb-70b9-4629-a705-a312d92edd67)
![3_telepathy_1NBT](https://github.com/GC-spigot/AdvancedEnchantments/assets/117314475/5aa2043e-c187-4482-bcf3-4db392ca79e5)
