### ISSUE TITLE
KEEP_ON_DEATH is broke

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedEnchantments#395]
souvenir:
  display: '%group-color%Souvenir'
  description: 'Slim chance to keep item on death.'
  applies-to: 'Armor'
  type: 'DEATH'
  group: 'IMMORTAL'
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 8
      effects:
        - 'KEEP_ON_DEATH %victim%'

that my enchantment and when someone die with that enchantment he get back the item but the item drop on the floor aswell..

**Comment by GC-spigot** [comment]
I'll have this fixed for an update after this one.
