### ISSUE TITLE
broken holywhitescroll

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#3951]
### Describe the bug

Things don't save with a holywhitescroll 

### How to reproduce

`/ae giveitem nick holywhitescroll 1`

### Screenshots / Videos

https://www.youtube.com/watch?v=XB_PuZj2oxU

https://youtu.be/V4m7g1zQeYk

### "/ae plinfo" link

https://paste.md-5.net/refehitulu

**Comment by ThomasWega** [comment]
Works fine for me, but my guess is that this happens because you switch world on death. Can you try without switching the player to a different world please?

**Comment by ThomasWega** [comment]
also, any errors in console?

**Comment by ThomasWega** [comment]
Fixed in 9.6.6. Duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/3925
