### ISSUE TITLE
BUG ON ENCHANTS COOLDOWN 0

### ISSUE THREAD

**Issue by Olavvvv** [GC-spigot/AdvancedEnchantments#3952]
### Describe the bug

Some enchantments with 0 cooldown sometimes don't work. How is this case of the peaks. Previously I used a very old version (a year and a half without updating) and this error did not happen... it turns out that now I updated and it does happen, and very often.

The explosive should explode, the telekinesis should go to your inventory, the infernal touch should give you the cooked minerals.

There are times when none of this happens, I have many more videos and at least 50 reports about this on my server...

### How to reproduce

ENCHANTS:
explosivo:
  display: '%group-color%Explosivo'
  description: 'Rompe en un area de 3x3x3'
  applies-to: 'Tools'
  group: 'FABLED'
  type: 'MINING'
  applies:
    - 'ALL_PICKAXE'
  levels:
    '1':
      chance: 100
      cooldown: 0
      effects:
        - BREAK_BLOCK @Trench{r=3}

telekinesis:
  display: '%group-color%Telekinesis'
  description: 'Recibe automaticamente lo que rompas en tu inventario'
  applies-to: 'Tools'
  group: 'FABLED'
  type: 'MINING'
  applies:
    - 'ALL_PICKAXE'
  levels:
    '1':
      chance: 100
      cooldown: 0
      effects:
        - 'TP_DROPS'

toqueinfernal:
  display: '%group-color%Toque Infernal'
  description: 'Obtienes lo que mines cocinado'
  applies-to: 'Tools'
  group: 'FABLED'
  type: 'MINING'
  applies:
    - 'ALL_PICKAXE'
  settings:
    removeable: false
    disable-in-enchanter: true
  levels:
    '1':
      chance: 100
      effects:
        - 'SMELT'

### Screenshots / Videos

https://youtu.be/uJpnmGwe3PU?si=ctof_bxKkYZRkPLa

### "/ae plinfo" link

LATEST VERSION

### Server Log

no errors in start..

**Comment by ThomasWega** [comment]
Works completely fine. My guess would be you have some plugin which interferes with our enchants
