### ISSUE TITLE
smelt with silktouch not worked.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3953]
### Describe the bug

smelt + silktouch was not worked.

### How to reproduce

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/355be676-821a-4664-89dd-b6de2d119c19

### "/ae plinfo" link

https://paste.md-5.net/saliqixeha

**Comment by GC-spigot** [comment]
It's intentional, we had complaints before about smelt working with silk touch. We'll add make it so smelt enchant doesnt apply with silk touch enchant from enchantments.yml config.
