### ISSUE TITLE
lootConfiguration.villagerTrades.blacklisted-groups.

### ISSUE THREAD

**Issue by NEIKI19914** [GC-spigot/AdvancedEnchantments#3958]
### Describe the bug

The lootConfiguration configuration of villagerTrades.blacklisted-groups causes added enchantment book groups to not be available via randombook...

### How to reproduce

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/6f665bbb-eef3-4e54-891f-caef74098907)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/59737752/63c0afc5-3020-454f-8bb8-897552b4c00d)

### "/ae plinfo" link

https://paste.md-5.net/gokediwika

**Comment by ThomasWega** [comment]
Not true. This option doesn't even touch random books. It will be something different misconfigured on your side

**Comment by NEIKI19914** [comment]
> Not true. This option doesn't even touch random books. It will be something different misconfigured on your side

I've tried to enter this blacklist without adding enchantment groups without any problems, enchantment groups added to the blacklist can't even be previewed...

**Comment by NEIKI19914** [comment]
> Not true. This option doesn't even touch random books. It will be something different misconfigured on your side

villagerTrades.blacklisted-groups prohibits villagers from trading specific enchantment groups, but also prohibits other ways of obtaining and viewing enchantment groups...

**Comment by NEIKI19914** [comment]
> Not true. This option doesn't even touch random books. It will be something different misconfigured on your side

I reproduced the issue .... Using ae reload the enchantment groups in blacklisted-groups become globally blacklisted after loading on the server...

**Comment by NEIKI19914** [comment]
> 不对。此选项甚至不会触及随机书籍。这将是你这边配置错误的不同的东西



> Not true. This option doesn't even touch random books. It will be something different misconfigured on your side

It took me some more events... Thoroughly found the process that triggers this issue .... This happens when players trade out plugin enchantment books with villagers... The blacklist becomes comprehensive, even using ae giverandombook name LEGENDARY can not be obtained by the LEGENDARY group enchantment that I added to the blacklist.

**Comment by NEIKI19914** [comment]
The blacklist will only become comprehensive and mandatory if the player refreshes the ae plugin's enchantment from the villager trade...

**Comment by ThomasWega** [comment]
If you could send a video of this whole process with only AE on the server it would be very helpful
