### ISSUE TITLE
[Feature Request] Add support for Paper's AsyncChat

### ISSUE THREAD

**Issue by NoltoxGit** [GC-spigot/AdvancedEnchantments#3959]
### Describe the bug

Hello,
Can you add the support for the Paper `AsyncChatEvent` and/or `AsyncChatDecorateEvent` in the configuration of your plugin please?
Because you're currently using an old listener: `org.bukkit.event.player.AsyncPlayerChatEvent`. 

Example for a new configuration:
```yml
# Use Paper's async Chat Event
use-async-chat: true/false
```

Thank you so much if you add this! :)

**Comment by ThomasWega** [comment]
Do you suffer from performance with that old event or what's really the issue with it? We use it because we also support spigot and older versions

**Comment by NoltoxGit** [comment]
> Do you suffer from performance with that old event or what's really the issue with it? We use it because we also support spigot and older versions

Hello, thanks for the answer.
Yes, but one of my plugins strongly recommends using this event.

**Comment by ThomasWega** [comment]
Ofc it's better, but I don't see this causing any performance issues from us. We don't use it that much
