### ISSUE TITLE
can't use per-level descriptions

### ISSUE THREAD

**Issue by NahidaS2** [GC-spigot/AdvancedEnchantments#3960]
### Describe the bug

Before explaining, I would like to apologize for my poor English skills.

I wanted to use per-level descriptions, so i read wiki and setup config.yml.
I copied example from https://ae.advancedplugins.net/configuration/per-level-descriptions and when i reload ae, console printed this message.
[21:45:13 ERROR]: [AdvancedEnchantments] Failed to load the "hasten" enchantment! Reason: enchantment does not have a description!

### How to reproduce

just paste example enchant to enchantments.yml

### "/ae plinfo" link

https://paste.md-5.net/osuvahoquh

**Comment by SirJben** [comment]
Hello, you simply misconfigured your files. Kindly open a ticket in Discord support and send your enchantments.yml.

**Comment by ThomasWega** [comment]
It works fine, but you have improper formatting. And on the wiki it is improper too haha. The default description needs to stay. Next version we will fix it so that you can have only level descriptions without issues. Same as on the wiki. Thanks for reporting
