### ISSUE TITLE
Feature Request: Allow/support REPEATING trigger for held items

### ISSUE THREAD

**Issue by xenxero1** [GC-spigot/AdvancedEnchantments#3962]
### Describe the bug

Currently the Repeating trigger is only supported for armor, despite it having tremendous potential for being used with held items. I would like to see support for this so held items can trigger passive effects. In my case I'm trying to have it generate souls passively at intervals on weapons.

### How to reproduce

Feature Request

### "/ae plinfo" link

https://paste.md-5.net/anadaropex

**Comment by ThomasWega** [comment]
Will be added in the next update!
