### ISSUE TITLE
ENCHANTS NOT WORKING IN PICKAXES

### ISSUE THREAD

**Issue by Olavvvv** [GC-spigot/AdvancedEnchantments#3965]
### Describe the bug

Again I... report the same errors for the third time. It's not a question of a plugin interfering, since this time I tried it without plugins. In a discord ticket they told me to create the report here.

Spike enchantments, such as explosive, smelt, telekinesis, sometimes do not work when they have 0 cooldown.

### How to reproduce

explosivo:
  display: '%group-color%Explosivo'
  description: 'Rompe en un area de 3x3x3'
  applies-to: 'Tools'
  group: 'FABLED'
  type: 'MINING'
  applies:
    - 'ALL_PICKAXE'
  levels:
    '1':
      chance: 100
      effects:
        - BREAK_BLOCK @Trench{r=3}
telekinesis:
  display: '%group-color%Telekinesis'
  description: 'Recibe automaticamente lo que rompas en tu inventario'
  applies-to: 'Tools'
  group: 'FABLED'
  type: 'MINING'
  applies:
    - 'ALL_PICKAXE'
  levels:
    '1':
      chance: 100
      cooldown: 0
      effects:
        - 'TP_DROPS'
toqueinfernal:
  display: '%group-color%Toque Infernal'
  description: 'Obtienes lo que mines cocinado'
  applies-to: 'Tools'
  group: 'FABLED'
  type: 'MINING'
  applies:
    - 'ALL_PICKAXE'
  settings:
    removeable: false
    disable-in-enchanter: true
  levels:
    '1':
      chance: 100
      effects:
        - 'SMELT'

### Screenshots / Videos

LATEST VERSION - 0 PLUGINS (ONLY AE)
As you can see, it fails several times:

https://github.com/GC-spigot/AdvancedEnchantments/assets/94938785/186e0352-8dee-4db4-8481-8268d7c57c54

VERSION 8.11.7 - 0 PLUGINS (ONLY AE)
As you can see, it doesn't fail even once:

https://github.com/GC-spigot/AdvancedEnchantments/assets/94938785/02ed96d8-2e29-46c7-a7e6-67e248ef9b90

### "/ae plinfo" link

latest version

**Comment by ThomasWega** [comment]
can you send your spark report?

**Comment by Olavvvv** [comment]
No errors in the console

Spark:
https://spark.lucko.me/27Osw0w63n

**Comment by ThomasWega** [comment]
Works fine on my end as well

**Comment by Olavvvv** [comment]
I was testing version by version, in the
AdvancedEnchantments-9.1.5.jar works fine for me, after that the enchantment starts to fail

It doesn't make sense but that's how it is...

Could you see what will happen?

I had my server paused 1 month ago because of this... the spikes are not the same and precisely these enchantments are super important

**Comment by Olavvvv** [comment]
@SirJben @ThomasWega ^^ sorry tag

**Comment by Olavvvv** [comment]
I would have no problem downgrading the version, but the problem is that when I updated I added enchantments of that version and now I cannot delete them since they have been on my server for 1 month.

Could you find out more about this?

It's really worrying, I know a friend's server that has exactly the same thing happening

**Comment by Olavvvv** [comment]
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/94938785/bfdc3d16-8cff-46f3-bac6-5d13150cbf1d)

In other server

**Comment by Olavvvv** [comment]
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/94938785/35e2374e-9c9d-4fa3-973d-bf1483f7eaf1)

**Comment by ThomasWega** [comment]
We'd like to do something about it but we need to be able to reproduce the issue which we currently are not
