### ISSUE TITLE
If detonate is used, mcmmo blocks cannot be doubled.

### ISSUE THREAD

**Issue by ii109** [GC-spigot/AdvancedEnchantments#3967]
### Describe the bug

If detonate is used, mcmmo blocks cannot be doubled. /
mcmmo's drops 2x and 3x skill do not apply if minerals are picked up by detonate.

### How to reproduce

Please apply 2x and 3x drops.

### "/ae plinfo" link

/ae plinfo skiplugins

**Comment by ThomasWega** [comment]
What version are you on + plugin ver, what other plugins do you use? We do run the events, so McMMO should listen to those

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
