### ISSUE TITLE
[SUGGEST] Please add a trigger when right-click the GRASS/DIRT BLOCK with a HOE

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3969]
### Describe the bug

 i tried to find triggers but that triggers was not found.
this triggers would be help to make enchantments related farming.

### How to reproduce

1. make hoe
2. right click grass / dirt block

### "/ae plinfo" link

suggestions.

**Comment by ThomasWega** [comment]
can't you use RIGHT_CLICK trigger and check with conditions for `%block type%`?

**Comment by Ecilpse** [comment]
> can't you use RIGHT_CLICK trigger and check with conditions for `%block type%`?
enchant type is "type: ATTACK_MOB;MINING;SHOOT;SHOOT_MOB".
if i add check with conditions for %block type%, can't trigger with "ATTACK_MOB;MINING;SHOOT;SHOOT_MOB" type.

**Comment by ThomasWega** [comment]
Then it doesn't make sense to check for hoe clicking grass does it?

**Comment by Ecilpse** [comment]
> Then it doesn't make sense to check for hoe clicking grass with these triggers does it?

so i suggest make "plow" triggers instead adding conditions

**Comment by ThomasWega** [comment]
This can be done with conditions. You can even check for the other triggers and filter them out. I don't see the usage of this, nor it doesn't make sense to me.
