### ISSUE TITLE
Tinkerer eating items

### ISSUE THREAD

**Issue by newbie029** [GC-spigot/AdvancedEnchantments#397]
Hi,
Tinkerer is eating item, its randomly eat items when the player close the thinkerer with esc button, the item not go back to the player inventory.

**Comment by GC-spigot** [comment]
What Minecraft version / Plugin version is this occurring with?

**Comment by GC-spigot** [comment]
@newbie029

**Comment by newbie029** [comment]
Paperspigot 1.12.2
AdvancedEnchantments 5.5.3

**Comment by GC-spigot** [comment]
Cannot reproduce this on paper 1.12.2
