### ISSUE TITLE
[FEATURE REQUEST] Veinminer/Trench

### ISSUE THREAD

**Issue by SkeletonAce** [GC-spigot/AdvancedEnchantments#3970]
### Describe the bug

Hello I have a few suggestions I would like to make for some additional parameters:

Add limit for vein miner:
@veinminer:{n=10}
Break 10 blocks in a vein, so you can use veinminer on more common block types

Remove restrictions for specific tool requirements:
@veinminer:{n=10,allblocks=true}
@trench:{r=3,allblocks=true}
Lets any tool break any block types with the enchantments

Add option for flat trench mining
@trench:{r=3,flat=true}
Would mine blocks in a 3x3x1 area

I want to create an enchantment with trench to be used to break glass blocks which is not currently possible:
firefighter:
  display: '%group-color%Firefighter'
  description: Break glass in a 3x3 area.
  applies-to: Axes
  group: ELITE
  type: MINING
  applies:
    - ALL_AXE
  levels:
    '1':
      settings:
        whitelist:
          - "GLASS"
      effects:
        - BREAK_BLOCK @Trench{r=3}

### How to reproduce

None

### "/ae plinfo" link

https://paste.md-5.net/gapuritaba

**Comment by ThomasWega** [comment]
Will be added in the next update

**Comment by ThomasWega** [comment]
Will be added in the next update
