### ISSUE TITLE
Timer enchantment breaks wooden floor

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3971]
### Describe the bug

When using Timber enchantment on axe, it breaks sometimes wooden floor

### How to reproduce

https://streamable.com/g5v1zs

### "/ae plinfo" link

https://paste.md-5.net/ewozehatip

**Comment by GC-spigot** [comment]
It does what it says it does. Nothing we can do about this unfortunately. No way to detect player placed blocks that will not cause lag in the long run :/
