### ISSUE TITLE
MMOItems support

### ISSUE THREAD

**Issue by JasperRuiz96** [GC-spigot/AdvancedEnchantments#3972]
### Describe the bug

Hello, I am experiencing a problem, and this was not an issue before. I am using MMOItems and AdvancedEnchantments, which are excellent plugins. However, I am facing a problem related to Durability.

As you can see in the images I've marked, MMOItems has a custom durability system. Strangely, some enchantments are causing this durability to break...

To give an example:
When I apply an enchantment like Smelt, this custom durability starts to deteriorate.
I did not have such an issue in previous versions. It seems that when both plugins were updated, this issue occurred.
![Screenshot_1](https://github.com/GC-spigot/AdvancedEnchantments/assets/126576073/552af3ec-8b1f-4a2b-9b78-4a2cec8ba12c)
![Screenshot_2](https://github.com/GC-spigot/AdvancedEnchantments/assets/126576073/9a7bd5f4-a5d0-42f0-83f3-f9d4395ec42d)

### How to reproduce

I believe you can resolve this through an update or perhaps introduce something like MMOItems support. After all, these two plugins complement each other very well.

### Screenshots / Videos

![Screenshot_1](https://github.com/GC-spigot/AdvancedEnchantments/assets/126576073/f322afb9-1bca-40e4-8192-e389589d1f6d)
![Screenshot_2](https://github.com/GC-spigot/AdvancedEnchantments/assets/126576073/3dce1609-14b5-4dd4-9e73-69f0d19de8e4)

### "/ae plinfo" link

https://paste.md5.net/honutezosu

**Comment by SamGamerYT** [comment]
Hoii

**Comment by JasperRuiz96** [comment]
Additional info:
When editing items in mmoitems premium plugin
hide real durability bar: true false

And

custom durability amount:

custom durability is 0 then broken: true false

There is a setting like .

**Comment by byKurtu** [comment]
I have that same problem. I hope the error will be resolved as soon as possible.

**Comment by JasperRuiz96** [comment]
When can it be added?
It's annoying that many items get damaged due to enchant.

**Comment by ThomasWega** [comment]
We'll for sure be taking a look at this! Highly requested feature. Just hang on for a bit please, there's bugs with priority

**Comment by JericNisperos** [comment]
Hello, Just coming from Issue: [#4074](https://github.com/GC-spigot/AdvancedEnchantments/issues/4074)

May I also know if it's confirmed to add the support for EliteMobs?

**Comment by ThomasWega** [comment]
Hey everyone! I've just tested this with the latest dev build of MMOItems and MythicLib and it seems to all work fine! Please let me know if you still have any issues whatsoever with MMOItems and AE combo and I'll see what I can do! :)
