### ISSUE TITLE
Enchantment Trench conflicts with the BeaconPlus plugin

### ISSUE THREAD

**Issue by hiiamken** [GC-spigot/AdvancedEnchantments#3973]
### Describe the bug

I'm having a bug with enchant smelting. When using a pickaxe with the smelting enchant to break a beacon (here the beacon of the Beaconplus plugin), it will x2 items. 

### How to reproduce

1. Enchant smelting in a pickaxe
2. Place a regular beacon block (Make sure applying beaconplus with vanilla beacons is enabled in the beaconplus plugin)
3. Break that beacon with the enchanted smelting pickaxe
4. Will receive 2 beacons instead of 1

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/e2514821-9d67-46e8-af9f-0d0f82c4ba7b

### "/ae plinfo" link

https://paste.md-5.net/boxaqiguje

### Server Log

https://mclo.gs/2e2MoZf

**Comment by hiiamken** [comment]
I've had this problem for quite a while, about 2-3 months. I think it's not because I'm not using the latest version of AE.

**Comment by ThomasWega** [comment]
Will be fixed in the next version. Added hook for BeaconPlus3

**Comment by hiiamken** [comment]
tks, beaconplus 3 has fixed it in the latest version btw

**Comment by ThomasWega** [comment]
You could've let me know...

**Comment by hiiamken** [comment]
Sorry, I thought you contacted them and they fixed it lol
