### ISSUE TITLE
Randomizer is not setting random chances based on config

### ISSUE THREAD

**Issue by leogianfagna** [GC-spigot/AdvancedEnchantments#3975]
### Describe the bug

The randomizer item works for setting a random chances on the book. In my server, I use this config:
```yml
chances:
  random: false
  success: 10
  destroy: 90
  destroy-if-fail:
    enabled: true
```

This way, every new book collected is given with 10/90 chances. This is better to stack the books.
However, if you use a randomizer in any book, the item will set the chances in 10/90 as well, and not randomize it.

If I have a book with 40/60% chances and apply the item, it will be 10/90.

### How to reproduce

1. Setup the config as I used above, with FALSE random chances
2. Restart the server
3. Get a randomizer **/ae giveitem nickname randomizer 1 SIMPLE**
4. Get a enchantment book, eg: **/ae giverandombook nickname SIMPLE 1**
5. Apply the randomizer
6. See your enchant setting up to 10/90 and not randomizing it

### Screenshots / Videos

before applying:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142264317/cc5c2de7-06f8-4ef8-819d-56de835afad7)

after:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142264317/ce871da5-1c3e-4ecd-af45-1e5b5d43fab5)

### "/ae plinfo" link

https://paste.md-5.net/tinayocute

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
