### ISSUE TITLE
BlockBreakEvent error when breaking blocks while McMMO is installed

### ISSUE THREAD

**Issue by oliviathevampire** [GC-spigot/AdvancedEnchantments#3976]
### Describe the bug

When trying to break blocks while in survival and you have McMMO installed the blocks does not actually break, but rather turns into ghost blocks, and when right-clicked turns into the normal block again.

### How to reproduce

Try to break blocks in survival when McMMO is installed

### Screenshots / Videos

https://paste.learnspigot.com/ponumotupo.rb

### "/ae plinfo" link

https://paste.md-5.net/bebalicedi

### Server Log

https://mcpaste.io/99cca2f271a4dd6d

**Comment by ThomasWega** [comment]
Can you try latest AE with latest McMMO please?

**Comment by colue** [comment]
i was using the latest of both and still had the issue

**Comment by colue** [comment]
https://paste.md-5.net/xumuruxugu

https://mcpaste.io/e62c5ceb53c1446d

**Comment by ThomasWega** [comment]
Will be fixed next update!
