### ISSUE TITLE
Anvil Application Bug

### ISSUE THREAD

**Issue by Bugheadben** [GC-spigot/AdvancedEnchantments#3977]
### Describe the bug

When combining items with a custom enchantment book via anvil application, you are not able to take the item out of the anvil 
(only applies to spigot servers)

### How to reproduce

Put a item that a custom enchant applies to, then book a custom enchantment book into a anvil, try taking the final product version of the item out 

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/118641320/0bf44472-b444-4b51-a802-5ee679dc54a5

### "/ae plinfo" link

https://paste.md-5.net/wigawehatu

**Comment by SirJben** [comment]
Works with Paper, not sure with Spigot jar only.

**Comment by ThomasWega** [comment]
are you on bedrock by any chance?
