### ISSUE TITLE
Mobtrak not correcty applies on item

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#3978]
### Describe the bug

When trying to put on item mobtrak, but it gets startrak. But if item aready have startrak and you puting mobtrak everything works fine.

### How to reproduce

Have clean sword and try put mobtrak on it.

### Screenshots / Videos

https://youtu.be/SPsBbi2mg1U

### "/ae plinfo" link

https://paste.md-5.net/ufigekoyik

**Comment by ThomasWega** [comment]
update
