### ISSUE TITLE
This condition no longer works on newer updates, what changed?

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3979]
### Describe the bug

```
conditions:
        - '%victim is holding% contains SWORD : %allow%'
```
does not work anymore, last time It worked for me was on v. 9.6.0

### How to reproduce

```
conditions:
        - '%victim is holding% contains SWORD : %allow%'
```

this does not work anymore on newer versions, it still worked on 9.6.0

### Screenshots / Videos

none

### "/ae plinfo" link

https://paste.md-5.net/nacumumife

### Server Log

https://mcpaste.io/a3349bddb68972bd

**Comment by leogianfagna** [comment]
@illudota I tested using v9.6.9 and it's working fine

**Comment by illudota** [comment]
> @illudota I tested using v9.6.9 and it's working fine
try mixing with
- '%attacker is holding% contains SWORD : %allow%'
then
INCREASE_DAMAGE, cuz that was the enchant that wasnt working for me. pretty w eird.

**Comment by leogianfagna** [comment]
> > @illudota I tested using v9.6.9 and it's working fine
> > try mixing with
> 
> * '%attacker is holding% contains SWORD : %allow%'
>   then
>   INCREASE_DAMAGE, cuz that was the enchant that wasnt working for me. pretty w eird.

Actually I tested a way different:
```yml
      conditions:
        - '%victim is holding% = BOW : %allow%'
```

now I tested with CONTAINS and **it's a bug**. this doesn't work
```yml
      conditions:
        - '%victim is holding% contains BOW : %allow%'
```

**Comment by illudota** [comment]
might be they just updated the placeholder.

**Comment by GC-spigot** [comment]
Fixed
