### ISSUE TITLE
Permission effect issue. Doesn't work at all

### ISSUE THREAD

**Issue by maxlehot1234** [GC-spigot/AdvancedEnchantments#398]
Is it me or the permission thing doesnt seems to work correctly?

I add a different permission per level and players doesn't get the permission.

Config example:
https://gist.github.com/maxlehot1234/c0b97d5ebbe584e36ce1ca7eac9a42c3

The permission wasnt apply to the player when he hold the pickaxe for example.

Anything else I am supposed to do?

PaperSpigot V1.13.2 B597 (latest one)
Java 8 (of course)
AdvancedEnchantments 5.5.3

Thanks again GC

**Comment by maxlehot1234** [comment]
Anything @GC-spigot It prevent me to use this feature and develop my own enchants XD :P

**Comment by GC-spigot** [comment]
'Pending' - not home at the moment.

**Comment by GC-spigot** [comment]
@maxlehot1234 are you using a permissions plugin? It's working fine for me at the moment, I'll switch it up a bit but not a whole lot I can do.

**Comment by maxlehot1234** [comment]
@GC-spigot Yes of course, which server owner doesn't use a permission plugin seriously on a pûblic server that have plugins on it?!

I have latest version of vault of course and LuckPerms

**Comment by maxlehot1234** [comment]
Anything for this ? What I amn doing wrong with the actual setup?

**Comment by maxlehot1234** [comment]
Anything on this? Any help? Instead of: "It's working fine for me"?
@GC-spigot Thank you
