### ISSUE TITLE
Lore duplicating bug

### ISSUE THREAD

**Issue by ozanusug** [GC-spigot/AdvancedEnchantments#3980]
### Describe the bug

when i apply custom enchantment on an item then when its done, lore duplicating the texts. 

### How to reproduce

I just changed almost all whole the configuration files, there is no errors while plugin starting status or no errors while using the plugin but when i apply enchantments if i applied another enchantments before or i am applying the enchant for the first time the enchantment lore & other enchantment lores are duplicating the lore texts.

### Screenshots / Videos

https://prnt.sc/peyWwxNOSEcy

### "/ae plinfo" link

https://paste.md-5.net/cejamadewa

### Server Log

https://mcpaste.io/2ba2deb9561d8236

**Comment by ThomasWega** [comment]
Saw this before and was caused by misconfiguration. Not sure what was it, but I'd suggest making a backup and recreating the files and changing them in parts and always test before changing the next part.
