### ISSUE TITLE
EffectActivationEvent not working when used correctly 

### ISSUE THREAD

**Issue by Abeoji** [GC-spigot/AdvancedEnchantments#3981]
### Describe the bug

EffectActivationEvent does not fire at all and yes I have already used AEAPI.forceEnchantToTriggerEvent(enchantment) in my onEnable method to force this for all enchantments and nothing works it seems to be a persistent issue for others 

### How to reproduce

Use the EffectActivationEvent event and fire it correctly using the forceEnchantToTriggerEvent and it does not fire

### "/ae plinfo" link

https://paste.md-5.net/abixevatic

**Comment by ThomasWega** [comment]
This is old way and deprecated way. Checkout the wiki
https://ae.advancedplugins.net/for-developers/create-custom-effects

**Comment by Abeoji** [comment]
Sorry I meant for the EnchantActivateEvent It does not fire regardless of what I do

**Comment by ThomasWega** [comment]
It won't. It's not used anymore
