### ISSUE TITLE
Durability effects remove glow on tools

### ISSUE THREAD

**Issue by Alien0-7** [GC-spigot/AdvancedEnchantments#3982]
### Describe the bug

I found two bugs:
1) if i hit any entity with abiding it will disable all enchants form the sword
2) if it's night carrot planter doesn't works

### How to reproduce

create a normal server and put the plugin with viaversion and viabackwards

### Screenshots / Videos

I don’t have sites to host videos of more than 20 seconds for free so if you need them I’ll send them to discord
al3n. _

### "/ae plinfo" link

https://paste.md-5.net/usudoyapoc

### Server Log

https://mclo.gs/iYqSx45

**Comment by ThomasWega** [comment]
Feel free to use imgur, youtube or vimeo to upload these videos. We do need them

**Comment by Alien0-7** [comment]
I didn't know vimeo, i uploaded my videos and these are the links:
- [first bug](https://vimeo.com/manage/videos/911569504) (abiding remove glow effect + didn't restore all durability but full durability - 1)
- [second bug](https://vimeo.com/911562938) (carrot planter doesn't work at night)

**Comment by ThomasWega** [comment]
We know about the durability being (max dur - 1) everytime. The second bug I've already fixed but the first bug we need to investigate. Can confirm this happens but we need to find another way to do the glowing

**Comment by ThomasWega** [comment]
Should be fixed in the next update!
