### ISSUE TITLE
Support CustomFishing plugin

### ISSUE THREAD

**Issue by NoltoxGit** [GC-spigot/AdvancedEnchantments#3983]
### Describe the bug
Hello,
For the new enchant added today: `autoreel`, can you add the compatibility with [CustomFishing plugin](https://polymart.org/resource/customfishing.2723) rods please? 

### "/ae plinfo" link
https://paste.md-5.net/pozineqole

**Comment by ThomasWega** [comment]
Same answer as I gave on https://github.com/GC-spigot/AdvancedEnchantments/issues/3985

> We listen to PlayerFishEvent, if they don't call this, they should
