### ISSUE TITLE
Autoreel does not work when combined with PyroFishing

### ISSUE THREAD

**Issue by FourNineRugz** [GC-spigot/AdvancedEnchantments#3985]
### Describe the bug

Autoreel does not work when combined with PyroFishing

### How to reproduce

Put autoreel on fishing rod, wait for bite. Does not auto reel. Tested on server with only AdvancedEnchantments and it works. 

### "/ae plinfo" link

https://paste.md-5.net/migamegipe

**Comment by ThomasWega** [comment]
We listen to PlayerFishEvent, if they don't call this, they should

<img width="618" alt="image" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/435d5df1-b2d9-4a43-8f8f-75604b1feea4">
