### ISSUE TITLE
Timber Enchant Bugged

### ISSUE THREAD

**Issue by Meiyueh** [GC-spigot/AdvancedEnchantments#3986]
### Describe the bug

Hi i have problem with "Timber" Enchant.
When i try chop a tree. i got this message.
![obrázek_2024-02-03_112526894](https://github.com/GC-spigot/AdvancedEnchantments/assets/158362614/dc4e15f0-6b0c-4be9-a519-1c7ed9a0f932)

### How to reproduce

i just added enchants an try it.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/158362614/dc4e15f0-6b0c-4be9-a519-1c7ed9a0f932

### "/ae plinfo" link

https://paste.md-5.net/lubeduwivi

### Server Log

https://mcpaste.io/5e6ffafd585af59c

**Comment by SirJben** [comment]
Use this enchantment. Next time open a Discord Ticket first.

```
timber:
  display: '%group-color%Timber'
  description: Chance to break a tree in one hit
  applies-to: Axes
  group: ULTIMATE
  type: MINING
  settings:
    showActionBar: true
  applies:
    - ALL_AXE
  levels:
    '1':
      chance: 15
      cooldown: 5
      effects:
        - BREAK_TREE @Block
    '2':
      chance: 35
      cooldown: 5
      effects:
        - BREAK_TREE @Block
    '3':
      chance: 55
      cooldown: 6
      effects:
        - BREAK_TREE @Block
