### ISSUE TITLE
FishTrak item can't be applied.

### ISSUE THREAD

**Issue by pykew** [GC-spigot/AdvancedEnchantments#3989]
### Describe the bug

You can't apply the fishtrak item on any fishingrod.

### How to reproduce

1.Give yourself a fishtrak item using /ae giveitem {username} fishtrak 1
2.Try to apply it on a fishing rod.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/140652366/4cfe98c8-93d4-45d4-97ee-3ffe2e0e03b2

### "/ae plinfo" link

https://paste.md-5.net/ivaruvuvip

**Comment by SirCraftypants** [comment]
Confirmed, using latest AdvancedEnchantments-9.6.8  on paper 1.20.2 and you can not attach a fishtrak to a fishing rod.

**Comment by TheLaoming** [comment]
Can confirm too, but for me even **stattrak** doesn't work with AE 9.6.13 and version 1.20.2. Other stuff like mobtrak, blocktrak works just fine but can't attach a stattrak to any item in the game.

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Very sorry
