### ISSUE TITLE
Enchanting Slot Bug

### ISSUE THREAD

**Issue by MartiThaWizz** [GC-spigot/AdvancedEnchantments#3990]
### Describe the bug

If you have 0 CE's slots on an item, and you try for example to apply a higher enchant then you currently have (Example BeastSlayer 2 on Sword and you wish to apply BeastSlayer 4 it won't let you until you apply an extra slot.) I am on the latest version. 

### How to reproduce

(Example BeastSlayer 2 on Sword and you wish to apply BeastSlayer 4 it won't let you until you apply an extra slot.)

### "/ae plinfo" link

https://paste.md-5.net/bohurivabe.css

**Comment by MartiThaWizz** [comment]
Forgot to mention this issue is related to CE's and Anvils. It would probably work if you had the other setting turned on for application.

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
