### ISSUE TITLE
' EFFECT_STATIC' potion effect was removed after changed world & death

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3991]
### Describe the bug

' EFFECT_STATIC' potion effect was removed after changed world & death
so i made execute console command '/apply player' when player world changed.

this world is not nomral world. generate temporarily by mythicdungeons.

### How to reproduce

1. made dungeon world through mythicdungeons
2. equip armor to given potion effect
3. enter the dungeon

### Screenshots / Videos

https://youtu.be/XyXpH2wdeqI

### "/ae plinfo" link

https://paste.md-5.net/ruhazedilu

**Comment by ThomasWega** [comment]
I don't know how Mythic Dungeons work, but if I switch world normally with multiverse it works fine. Do you always die and then get moved onto a new world? Or how does that work? If you could get the author on this discussion, that might clear some things up

**Comment by ThomasWega** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/fe60f01d-5659-4d39-a108-16b655e5b19d

**Comment by Ecilpse** [comment]
So i said "this world is not nomral world. generate temporarily by mythicdungeons."

**Comment by ThomasWega** [comment]
> If you could get the author on this discussion, that might clear some things up
