### ISSUE TITLE
Slotincreaser issue

### ISSUE THREAD

**Issue by Bowieee69** [GC-spigot/AdvancedEnchantments#3993]
### Describe the bug

When I get myself any type of slot increaser and try to apply it to any item it says "You cannot apply that enchantment! No free slots left."

### How to reproduce

I just added a video about it.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/85521828/8f76a7ed-9e48-47bb-b5bb-2f24dd06527c

### "/ae plinfo" link

https://paste.md-5.net/obejagavip

**Comment by TheLaoming** [comment]
You have to use at least one AE enchant then you can use slot increaser (tested). But for sure, it's still a bug.

**Comment by ThomasWega** [comment]
Will be fixed in the next update
