### ISSUE TITLE
Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### ISSUE THREAD

**Issue by colinpapa** [GC-spigot/AdvancedEnchantments#3994]
### Describe the bug

Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### How to reproduce

Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### "/ae plinfo" link

can

**Comment by SirJben** [comment]
Hello @colinpapa please open a ticket in our Discord. https://discord.gg/advancedplugins

**Comment by zelathad** [comment]
Have the SAME issue cant bypass it at all! Im HEAVILY annoyed! What do i do as this error is preventing my players from playing. Was working fine till a server reboot
