### ISSUE TITLE
Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### ISSUE THREAD

**Issue by colinpapa** [GC-spigot/AdvancedEnchantments#3995]
### Describe the bug

Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### How to reproduce

Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### "/ae plinfo" link

can't

**Comment by SirJben** [comment]
Duplicate of #3994.
