### ISSUE TITLE
Chat is being spammed

### ISSUE THREAD

**Issue by tjfrom** [GC-spigot/AdvancedEnchantments#3998]
### Describe the bug

Everytime an action occurs that has a possibility of activating a custom enchantment it will send a notification in the chat.
Everyone sees this notification, not just ops.

### How to reproduce

In update 9.6.12 get a pickaxe with souls, multiplication 5 and start breaking stuff.

### Screenshots / Videos

https://imgur.com/a/3zmSLFe

### "/ae plinfo" link

https://paste.md-5.net/ajesijuman

### Server Log

https://mcpaste.io/e5479901514b6f8a

**Comment by GC-spigot** [comment]
Hey its already fixed on new update, please update now :)

**Comment by tjfrom** [comment]
Hello, i just double checked and i noticed that the plugin is indeed updated to update 13 but on the advancedplugins website it is still at update 12, can this be fixed so I can indeed update my server?
