### ISSUE TITLE
After version 9.6.6, the white scroll does not take effect

### ISSUE THREAD

**Issue by DawnXinyu** [GC-spigot/AdvancedEnchantments#3999]
### Describe the bug

The server I use is purpur1.20.2
I tested AE's 9.3.12, 9.6.9, 9.6.13, and 9.6.6 (because I saw that the next version in the update record modified the WhiteScroll check).
————
In versions 9.3.12 and 9.6.6, WhiteScroll takes effect normally and can only be used once on an item. In versions 9.6.9 and 9.6.13, the function of WhiteScroll is completely disabled and cannot protect the item from breaking when the enchantment fails, and WhiteScroll can be used multiple times on an item, adding lore.
![)O5~`HI{YL)5__8HBOK}H{K](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/f446b83f-ee97-432c-846d-f98e51189ff6)

(This is my modified enchantment protection lore)
————
In version 9.3.12, all functions of WhiteScroll take effect normally.
In version 9.6.6, WhiteScroll, I enabled the function that the equipment has a probability of breaking when the enchantment fails, and when the enchantment fails, the protection entry will be removed. In my actual measurement process, when the enchantment fails, the probability of the equipment being broken is very low, and it will only be triggered once a dozen or even dozens of times.
![@RXB7(~Q0XBGK`ENDO O ZC](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/9b28484c-b2c5-46c7-9cff-d49a6a5d4b74)
![UYD3SQZD{0OKL)HGJ9Y0@TC](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/fc350ea9-4b36-474f-b222-ba31772ab61d)
![38@~NDXN22FEY{7M_FU32 I](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/56e65a4e-c82c-4234-8fc5-f741c869be8c)

The enchanted book I used for testing has a breakage probability of 99% and a success rate of 1% when the enchantment fails.
![9%@N H4A_Y3H_T }L0~B7$2](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/49cf8ec2-3fa4-43ad-9b7a-b78aaa02cd03)

### How to reproduce

The server I use is purpur1.20.2
I tested AE's 9.3.12, 9.6.9, 9.6.13, and 9.6.6 (because I saw that the next version in the update record modified the WhiteScroll check).
————
In versions 9.3.12 and 9.6.6, WhiteScroll takes effect normally and can only be used once on an item. In versions 9.6.9 and 9.6.13, the function of WhiteScroll is completely disabled and cannot protect the item from breaking when the enchantment fails, and WhiteScroll can be used multiple times on an item, adding lore.
![)O5~`HI{YL)5__8HBOK}H{K](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/f446b83f-ee97-432c-846d-f98e51189ff6)

(This is my modified enchantment protection lore)
————
In version 9.3.12, all functions of WhiteScroll take effect normally.
In version 9.6.6, WhiteScroll, I enabled the function that the equipment has a probability of breaking when the enchantment fails, and when the enchantment fails, the protection entry will be removed. In my actual measurement process, when the enchantment fails, the probability of the equipment being broken is very low, and it will only be triggered once a dozen or even dozens of times.
![@RXB7(~Q0XBGK`ENDO O ZC](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/9b28484c-b2c5-46c7-9cff-d49a6a5d4b74)
![UYD3SQZD{0OKL)HGJ9Y0@TC](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/fc350ea9-4b36-474f-b222-ba31772ab61d)
![38@~NDXN22FEY{7M_FU32 I](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/56e65a4e-c82c-4234-8fc5-f741c869be8c)

The enchanted book I used for testing has a breakage probability of 99% and a success rate of 1% when the enchantment fails.
![9%@N H4A_Y3H_T }L0~B7$2](https://github.com/GC-spigot/AdvancedEnchantments/assets/96636368/49cf8ec2-3fa4-43ad-9b7a-b78aaa02cd03)

### "/ae plinfo" link

https://paste.md-5.net/ahoguhasef

### Server Log

none

**Comment by DawnXinyu** [comment]
In versions after 9.6.6, the white scroll will not take effect at all. It can be placed on an item repeatedly and will not protect the item from damage.

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
