### ISSUE TITLE
CMI or HeadsPlus duplicating with Smeling and telepathy 

### ISSUE THREAD

**Issue by lajnicek** [GC-spigot/AdvancedEnchantments#4000]
### Describe the bug

Hello
enchantment Smelting and Telepathy (other I haven't found yet) is duplicating heads from plugin CMI and from HeadsPlus too. It does't take NBT tags

More info with NBT Tags in my comment here:
https://github.com/GC-spigot/AdvancedEnchantments/issues/3949#issuecomment-1925218570

I'm sorry for creating new issue, but i don't know if you are reading closed issues  :)

### How to reproduce

/cmi mobhead cow (or other mob)
Enchant tool with Smelting 
Place CMI head on ground
Break the head with enchanted tool 

### Screenshots / Videos

![2024-02-09_21 35 34](https://github.com/GC-spigot/AdvancedEnchantments/assets/117314475/e7da0bfb-6e07-45bb-8e43-b302aaf28302)

### "/ae plinfo" link

https://paste.md-5.net/sonaxojawu

**Comment by ThomasWega** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/5f87ba92-1139-4dd9-adf2-35d6d28dd1be

Doesn't dupe for me

**Comment by lajnicek** [comment]
Try only with Smelting.
My head from CMI has 3 NBT tags. ( screens in comment in other issue)
It's only for heads stored in customheads.yml in CMI and turned on dropping heads from mobs.
When i will be on computer, I can  send video and more info too :))

**Comment by lajnicek** [comment]
CMI/config.yml
    Mob:
      # Enables custom mob heads dropping from mobs with particular chance
      # Check CustomHeads.yml for customization by entityType
      Drop: **true**

Video link (it's too big)
https://files.fm/u/fjpjsxv8ef

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thank you.
