### ISSUE TITLE
AdvancedPlugins site is update behind

### ISSUE THREAD

**Issue by tjfrom** [GC-spigot/AdvancedEnchantments#4001]
### Describe the bug

Sorry for writing this here but I didn't know where else to put this.
The AdvancedPlugins site is an update behind, this sucks because the new update has quite a big bugfix.
Is this an accident and if so can this be fixed?

### How to reproduce

https://advancedplugins.net/item/1/updates
Its still on .12

### "/ae plinfo" link

x

**Comment by GC-spigot** [comment]
Hey sorry about that one, it's now resolved!
