### ISSUE TITLE
Except for the exp purchase method, the purchase sound will not be heard after other conditions are set.

### ISSUE THREAD

**Issue by CCjun6** [GC-spigot/AdvancedEnchantments#4004]
### Describe the bug

AdvancedEnchantments / menus / enchanter
in this folder
Set the purchase condition to exp, then there will be a purchase sound effect
price:exp:1000
sound: ANVIL_LAND
If you set the purchase condition to money, there will be no purchase sound effect.
price: money:1000
sound: ANVIL_LAND

For all conditions except exp, there will be no purchase execution sound.

### How to reproduce

You can change exp to money or other conditions.

### "/ae plinfo" link

https://paste.md-5.net/rulovasemi

**Comment by ThomasWega** [comment]
Super weird, but will investigate haha

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
