### ISSUE TITLE
java.lang.Exception

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#4007]
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/118831819/2e18adef-afb7-4b28-8245-fed2e97404b6)

### How to reproduce

It is simple to run a PurPur server with this plugin

### "/ae plinfo" link

https://paste.md-5.net/oqiwezowos

### Server Log

https://mcpaste.io/be4d06fda9d4e282

**Comment by GC-spigot** [comment]
First load? This might be an issue with config
