### ISSUE TITLE
LOWER TPS WHEN MINING

### ISSUE THREAD

**Issue by Rcorcho6** [GC-spigot/AdvancedEnchantments#4008]
### Describe the bug

When carrying out constant activities such as mining, the server suffers from low tps due to blockbreak but this apparently causes conflict with the ConditionalEvents plugins, but the strangest thing is that when deactivating all CE activities it still continues to report effects Block Break and this continues to cause lag on the server

### How to reproduce

When carrying out frequent mining activities, we have already deactivated the trench to check but nothing... https://spark.lucko.me/PrOXrL8dzB

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/86140264/0fade9c7-f27e-4a84-b7ef-0566e9576aca)

### "/ae plinfo" link

https://paste.md-5.net/acegojutac

### Server Log

https://spark.lucko.me/PrOXrL8dzB

**Comment by ThomasWega** [comment]
Try with removing all plugins except AE and see if this issue still happens. It will most likely be an incompatibility with other plugin. ConditionalEvents is my guess as well
