### ISSUE TITLE
Internal Error occured after using /ae editor

### ISSUE THREAD

**Issue by RochyJiang** [GC-spigot/AdvancedEnchantments#4009]
### Describe the bug

Use the command /ae editor will cause an Internal Error. Console error from row 1304 to 1340.
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/14239286/latest.log)

### How to reproduce

Run a server and issue the command /ae editor

### "/ae plinfo" link

https://paste.md-5.net/dibusudaco

### Server Log

https://mcpaste.io/7105c0d2f0753405

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
