### ISSUE TITLE
Factions hook broken

### ISSUE THREAD

**Issue by iLemon** [GC-spigot/AdvancedEnchantments#4011]
### Describe the bug

https://pastes.dev/UDLvxKw8O6

### How to reproduce

- Run AdvancedEnchantments
- Run FactionsUUID
- Try mine with Trench or VeinMiner

### "/ae plinfo" link

https://paste.md-5.net/ekaxivacon

**Comment by ThomasWega** [comment]
Are you on latest FactionsUUID? Do you really use FactionsUUID or just one of it's forks? The method works completely fine for me and produces no errors

**Comment by iLemon** [comment]
We're running our own fork of it. Will get it updated.
