### ISSUE TITLE
Infinite enchants bug

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4013]
### Describe the bug

The plugin doesn't seem to check if the user has a custom enchant currently equipped on them. This can cause glitches with plugins that alter items in people's inventories (like per-world inventories).

- You can equip an armor piece in 1 world 
- Teleport to a separate world that has a separate inventory (so it loads different items on the player)
- That player will still get the advantages of the custom enchants equipped in the 1st world despite not having it equipped anymore
- This also works with plugins like duels where it replaces your inventory with a set kit
- It doesn't work for EVERY item (for some reason) but it does work 100% of the time for armor sets that give a special effect when fully equipped

The plugin needs to check that the armor is still equipped before allowing it to activate. 

### How to reproduce

All the info is above

### "/ae plinfo" link

https://paste.md-5.net/awukefaguj

**Comment by ThomasWega** [comment]
We run armor checks on every world change. Maybe the other plugin removes it after we check for it and that causes this issue

**Comment by JHarris12345** [comment]
Its not just world change. It can be the same world if a plugin loads a new inventory (like duelling)

**Comment by ThomasWega** [comment]
Hmm.. Only solution I can currently think of is running the check few seconds after world change. We will experiment and see what works

**Comment by JHarris12345** [comment]
Again, you dont need to change worlds for this glitch to occur. You can STILL have it occur via a plugin that switches out a players inventory. Like a duels plugin. None of that involves switching worlds.

**Comment by ThomasWega** [comment]
Got it. However I am not sure how we can really fix this, as the plugin just removes the items and we don't run the checks. We have basically no good way to know inventory was cleared. If the plugin wants to support AE he can run ArmorEquipEvent and we'll listen to it accordingly

**Comment by ThomasWega** [comment]
Or you can create your own plugin and use both of the plugins APIs
