### ISSUE TITLE
Cant add Orbs onto items with NBT Tags

### ISSUE THREAD

**Issue by tjfrom** [GC-spigot/AdvancedEnchantments#4015]
### Describe the bug

Its not possible to add a Weapon Enchantment Orb for example to a netherite sword with an NBT Tag

### How to reproduce

Get a sword with an NBT Tag and try to add a Weapon Enchantment Orb to it.

### "/ae plinfo" link

https://paste.md-5.net/ihenufaxav

**Comment by ThomasWega** [comment]
Orbs cannot be applied without having any enchantment on the item. If there is an additional nbt tag or not that makes no difference. If you need to apply orbs without any enchantment on the item first, create a new feature request
