### ISSUE TITLE
High Latency and Performance Degradation with >130 Players Online

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#4016]
### Describe the bug

I've observed significant performance issues with the plugin when the server's player count exceeds 130. The plugin starts to lag noticeably, affecting the gameplay experience for all connected players. This issue seems to be more pronounced during peak times when the server experiences high traffic. I request the development team to review the attached Spark report to identify the root cause of these delays and to implement necessary optimizations to improve the plugin's performance under high player loads.

### How to reproduce

Ensure the server is running with the plugin installed.
Increase the player count on the server to more than 130 players. This scenario can be simulated during peak hours or through a controlled test environment designed to mimic high traffic conditions.
Observe the plugin's performance and responsiveness during this time. Key metrics to monitor include command response times, player interaction delays, and any server-side errors or warnings.
Generate a Spark report (or similar performance analysis tool) to capture detailed performance metrics during the period of high player activity.

### Screenshots / Videos

https://spark.lucko.me/B5BTwKlqML

### "/ae plinfo" link

https://paste.md-5.net/pibigivine

### Server Log

-

**Comment by ThomasWega** [comment]
If you remove AureliumSkills, will the performance get any better?
