### ISSUE TITLE
Effect_Static Disabling/Enabling wrong when on multiple pieces of gear

### ISSUE THREAD

**Issue by Gfieldd** [GC-spigot/AdvancedEnchantments#4017]
### Describe the bug

This is an issue we found with the Overload enchant, which is part of the premade "Cosmic Enchants" set, but seems to be a bigger issue with the "Effect_Static" setting type in general

If you have the Overload enchant on multiple pieces of armor which you are wearing, unequipping one of them will remove the bonus hearts, and require you to un- and reequip the other piece of armor for it to work again.

On top of this, if these enchants are of a different level, equipping a lower level Overload enchant overwrites the effect that the higher level Overload enchant has given, so you end up with less hearts, until you un- and reequip the higher level overload enchant piece.

### How to reproduce

1. Create 2 different pieces of armor with different levels of the same enchant, preferrably one with a very noticable effect, possibly Overload.
3. Equip both of these pieces of armor.
4. Unequip the armor with the lowest level
5. Observe the effect being completely gone, even though you still have the enchant on the other piece of armor.
6. Equip the armor with the lowest level again.
7. Observer the higher level effect being replaced by the lower level effect.
8. Wait to confirm that this will not be fixed by simply waiting a few seconds

### "/ae plinfo" link

https://paste.md-5.net/bakapopeba

**Comment by ThomasWega** [comment]
Should be fixed in the next update!
