### ISSUE TITLE
Soulminer enchantment removes Enchant Glow on Pickaxe once soul is given.

### ISSUE THREAD

**Issue by Denial234** [GC-spigot/AdvancedEnchantments#4023]
### Describe the bug

Applying the Soulminer enchantment on a Pickaxe and mine until you recieve a Heart Particle will remove the enchantment glow right after.

### How to reproduce

1. Apply Soulminer enchantment to Pickaxe
2. Mine blocks until a heart particle appear
3. Enchantment Glow will be automatically removed from the Pickaxe

(Only works if no vanilla enchantments are applied to Pickaxe)

### "/ae plinfo" link

https://paste.md-5.net/ogobipuniq

**Comment by ThomasWega** [comment]
Similar to https://github.com/GC-spigot/AdvancedEnchantments/issues/3982
