### ISSUE TITLE
Gkit prints error in console

### ISSUE THREAD

**Issue by GamefactsIG** [GC-spigot/AdvancedEnchantments#4024]
### Describe the bug

Console is spammed with errors when doing /gkit and selecting a kit

### How to reproduce

Select a Gkit in /gkit, error occurs

### Screenshots / Videos

Gkit config:
https://mclo.gs/pS82Ic8

### "/ae plinfo" link

https://paste.md-5.net/detedutote

### Server Log

https://mclo.gs/WHDKC2R

**Comment by KingCueio** [comment]
@GamefactsIG I think you need to change 
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/87959487/432b0c14-ebeb-443f-963a-4f45a4e12f91)
this to `- magnet:1`

**Comment by ThomasWega** [comment]
You have incorrect configuration. Not sure if it's exactly as @KingCueio but there for sure is an error in your config file
