### ISSUE TITLE
Itemsadder lore bugged (only custom Items)

### ISSUE THREAD

**Issue by mekotori** [GC-spigot/AdvancedEnchantments#4026]
### Describe the bug

Every time you enchant Custom Enchants, your lore is doubled. This only happens with custom items like swords from Itemsadder. With Grindstone it is also doubled every time.

In addition, the Attack Speed and Attack Damage display changes from green to purple

My players have such a big lore and can't see enchants anymore

### How to reproduce

I'm not sure how to fix this but maybe you could give some support for itemsadder lore or custom items in general

### Screenshots / Videos

https://prnt.sc/yKZZPYWxC96S
https://prnt.sc/buHiAjnx7Jfs
https://prnt.sc/1-ydW4VJXdS3

### "/ae plinfo" link

https://paste.md-5.net/nuhecasobe

**Comment by ThomasWega** [comment]
Have you tried recreating your config for AE and ItemsAdder? What have you changed in both of these configs? Also make sure to try on a server with only AE and IA please. If the issue still persists, please do send a video showcase as well.
