### ISSUE TITLE
SUGGESTION: another trigger in levels or in the future feature: "Skills"

### ISSUE THREAD

**Issue by GJ-Euphory** [GC-spigot/AdvancedEnchantments#4028]
### Describe the bug

I wanted to create a skill that does not interrupt the main function of a tool or weapon (mining, digging, felling, killing, protecting, etc...) but that you can use the skill by right clicking and using the function. Mentioned above.

The main idea I wanted to create was that players could use their pickaxe to get materials, but then they could activate with a skill the option to be able to execute commands WHILE picking.

That is, if the player activates a skill, there must be a "MINING" type trigger that executes a command (/sellall) and gives permission for it.

Unfortunately, I contacted support and they told me that I cannot do that within "levels", so I would like them to be able to add that possibility or else they could do it in the future "skills" feature that I noticed they were going to add to their wiki.

### How to reproduce

-

### Screenshots / Videos

-

### "/ae plinfo" link

-

### Server Log

-

**Comment by ThomasWega** [comment]
We'll look into this
