### ISSUE TITLE
[URGENT] DRM call halts server startup

### ISSUE THREAD

**Issue by iLemon** [GC-spigot/AdvancedEnchantments#4029]
### Describe the bug

We've noticed a few times where our server will halt at startup and need manual intervention to kill it. Here's a jstack: https://pastes.dev/ac72cdCNjJ

It shows the DRM call is being cringe (potentially your api endpoint is sometimes down?).

This should never happen.

### How to reproduce

n/a

### "/ae plinfo" link

https://paste.md-5.net/ekaxivacon

**Comment by GC-spigot** [comment]
Ill get back to you via discord
