### ISSUE TITLE
Unable to find AdvancedEffects and AdvancedUtils

### ISSUE THREAD

**Issue by iLemon** [GC-spigot/AdvancedEnchantments#4030]
### Describe the bug

I paid $500 for the source, and we can't compile without AdvancedUtils and AdvancedEffects. Please advise where to find this as my discord ticket question was closed, so now I have to report this on github.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/18317307/29b16547-8f6a-41aa-91c1-444d57adb916)

### How to reproduce

n/a

### "/ae plinfo" link

https://paste.md-5.net/ekaxivacon

**Comment by GC-spigot** [comment]
Ill get back to you via discord
