### ISSUE TITLE
BlockStak not working

### ISSUE THREAD

**Issue by mcwal18** [GC-spigot/AdvancedEnchantments#4031]
### Describe the bug

When you time the following command: /ae giveitem MYNICK blocktrak 1 ELITE
It does not work and it send a error message in the console and chat.

### How to reproduce

Minecraft version: 1.20.1
Paper Spigot | Edition Java
Plugin version: 9.6.18

### Screenshots / Videos

https://pastebin.com/tHQmN1MK

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
