### ISSUE TITLE
BUG: The "PERMISSION" effect does not work.

### ISSUE THREAD

**Issue by GJ-Euphory** [GC-spigot/AdvancedEnchantments#4032]
### Describe the bug

I tried toggling a player's permission so that they could use a command when performing "X" action, but it doesn't work.

### How to reproduce

In my case, what I wanted to achieve was that the player could compact items every time he clicked, but when placing the effect: "PERMISSION:essentials.condense" or "PERMISSION:essentials.condense @Self" it did not work and did not allow the player run the command that requires this permission.

For some strange reason, Discord support asked me to use the command to assign permissions in effect "PERMISSION:" so at the time I used debug and recorded this during the execution of the skill.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/122542736/6b75d958-c4a1-4982-b940-0f7ce1429c1d)

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/122542736/f2a4874f-da11-4134-8d44-4270d25b5382)

### "/ae plinfo" link

https://paste.md-5.net/ataceloveb

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Do note that PERMISSION effect toggles it on/off everytime. Always the opposite of what it is now. It won't just set it to true and keep it there.

**Comment by GJ-Euphory** [comment]
Ok, that helps me prevent players from using that permission to command at other times when they don't have the enchantment.
