### ISSUE TITLE
Enchant Orbs don't work

### ISSUE THREAD

**Issue by YT-Duckyyy** [GC-spigot/AdvancedEnchantments#4035]
### Describe the bug

When applying the slot orbs to an item (not increasers, the orbs) they don't apply, they just swap.  I'm not on the most recent, but after reviewing the changes, noticed it wasn't even fixed since the version I'm on (i dont mind updating quickly to test it also, ill add a note once updated also to confirm)

### How to reproduce

Apply an enchantment orb to an item on latest version (1.20.4 too)

### "/ae plinfo" link

https://paste.md-5.net/puruxiviwu

**Comment by YT-Duckyyy** [comment]
I can confirm, latest version does not fix this issue either.

**Comment by SirJben** [comment]
Hello @YT-Duckyyy make sure the item has already custom enchantments. Can you provide a video of you doing this? Thank you.
