### ISSUE TITLE
[BUG] Glow effect on custom enchant with anvil

### ISSUE THREAD

**Issue by NoltoxGit** [GC-spigot/AdvancedEnchantments#4037]
### Describe the bug

When I try to enchant an object with a custom enchantment in an anvil, it loses the "glowing" effect.

### How to reproduce

1. Get a custom enchantement 
2. Get a tools
3. Get an anvil
4. Set the tool and the custom enchantement in the anvil
5.  See the custom enchantement disapear after some clicks on this

### Screenshots / Videos

Soon (my OBS is broke :c)

### "/ae plinfo" link

https://paste.md-5.net/fihasoqiqe

### Server Log

https://mclo.gs/UzuLpvO

**Comment by ThomasWega** [comment]
Will be the same reason as this: https://github.com/GC-spigot/AdvancedEnchantments/issues/4037. Will handle the issue there
