### ISSUE TITLE
cant stop flying in certain world

### ISSUE THREAD

**Issue by Stoniasawsome** [GC-spigot/AdvancedEnchantments#4038]
### Describe the bug

im trying to disable flight with wings enchant in certain worlds like spawn. players can fly no matter what.

### How to reproduce

im trying to disable enchants or at least flying with wings enchant at my spawn world. i put my spawn world in the blacklist 
disable-enchants:
  # Disable enchants in specific world
  test_world: # world name
    - spawn
 but this didnt work. so i disabled flight in that world via multiverse worldguard and cmi.
when players tp to the spawn world their fly is removed, but
all players have to do is reequip the pair of boots in the spawn world and it lets them fly.

### "/ae plinfo" link

https://paste.md-5.net/ucamopidid

**Comment by ThomasWega** [comment]
Your config needs to be incorrect. This works completely fine.

**Comment by Stoniasawsome** [comment]
what do you mean it needs to be incorrect? what do i need to fix?

**Comment by Stoniasawsome** [comment]
When a player wears wings in one world and teleports to the world with disabled enchants he can still fly. this IS a bug, not a config error.
