### ISSUE TITLE
Soulbound

### ISSUE THREAD

**Issue by universemcnetwork** [GC-spigot/AdvancedEnchantments#4039]
### Describe the bug

when a player dies and has soulbound on an item, I would like to remove the item with soulbound and put the same one without soulbound, because with REMOVE_ENCHANT:soulbound it duplicates the item in the inventory.
because if I now put soulbound on an item and the player dies it duplicates the item and gives him one with soulbound and the other without soulbound

### How to reproduce

When I put soulbound on an item and add the condition REMOVE_ENCHANT:soulbound I would like that when the player dies soulbound is removed and the item with soulbound is also removed and only the one without soulbound remains

### "/ae plinfo" link

https://paste.md-5.net/xezijeqici

**Comment by xenxero1** [comment]
Is there any reason to use this method instead of the already-provided Holy White Scroll?

**Comment by universemcnetwork** [comment]
> Is there any reason to use this method instead of the already-provided Holy White Scroll?

explain better please

**Comment by xenxero1** [comment]
There is an item in the plugin already called the Holy White Scroll which can be given with the command `/ae giveitem {playername} holywhitescroll`

This can be dropped onto an item in your inventory (doesn't work in creative), and prevents the item from being lost on death, but the effect is removed when it happens. It's effectively single-use soulbound, and can be reapplied each time as needed.

**Comment by universemcnetwork** [comment]
> There is an item in the plugin already called the Holy White Scroll which can be given with the command `/ae giveitem {playername} holywhitescroll`
> 
> This can be dropped onto an item in your inventory (doesn't work in creative), and prevents the item from being lost on death, but the effect is removed when it happens. It's effectively single-use soulbound, and can be reapplied each time as needed.

ok thanks, I'll try it and if it goes well I'll close the ticket.
