### ISSUE TITLE
Console error message

### ISSUE THREAD

**Issue by Zoneman1972** [GC-spigot/AdvancedEnchantments#404]
Getting this error message in console every so often.

https://pastebin.com/3beurY89

**Comment by GC-spigot** [comment]
What operating system is your server running on?

**Comment by Zoneman1972** [comment]
Platform: amd64 (Linux) Running threads: 58

[Server] INFO Java version: 1.8.0(191-8u191) Build: 12-2ubuntu0

**Comment by GC-spigot** [comment]
Fixed.
