### ISSUE TITLE
Could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by BronzWarq** [GC-spigot/AdvancedEnchantments#4040]
### Describe the bug

Installed the plugin, logged into the server and errors appeared

### How to reproduce

just install the plugin, go to the server and everything will appear

Also, when players move around the world, the following appears in the console: 
https://paste.helpch.at/mefucereyi.csharp
https://paste.helpch.at/inogorobij.css
fulllog https://paste.helpch.at/ehemazukem.makefile

### "/ae plinfo" link

https://paste.md-5.net/donucoxuko

### Server Log

https://paste.helpch.at/oduzemeviy.makefile

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
