### ISSUE TITLE
EFFECT BUG: EXALTED

### ISSUE THREAD

**Issue by GJ-Euphory** [GC-spigot/AdvancedEnchantments#4042]
### Describe the bug

The Exalted enchantment doesn't work, it just doesn't want to remove the negative effects.

### How to reproduce

I have tried to set the chance to be 100% and with a 1s cooldown, and while testing with a user, none of the negative effects it had disappeared, it is the default enchantment that the target had in "@attacker" and it did not in "@self" to heal you -.-

There are many effects that this has and it even makes things duplicate!! (as in abiding, if you add the "attack" trigger the item in hand is duped, I reported this on discord a few days ago)

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/122542736/2bf797ac-596b-4d2f-aec0-51f0813bbfb3)

### "/ae plinfo" link

https://paste.md-5.net/quzakekava

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
