### ISSUE TITLE
player can keep apply magic dust although book success rate is 100%

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4043]
### Describe the bug

player can keep apply magic dust although book success rate is 100%

### How to reproduce

1. make custom enchantment book's success rate to 100%
2. apply magic dust

### "/ae plinfo" link

https://paste.md-5.net/jufuqozozo

**Comment by ThomasWega** [comment]
Will be fixed in the next update!

**Comment by Ecilpse** [comment]
> Will be fixed in the next update!

not fixed at lastest build (9.7.0)

**Comment by GC-spigot** [comment]
@Ecilpse there was an issue with update, we'll post the update again in a few minutes - should be fixed then properly.
