### ISSUE TITLE
conflicts with the BeaconPlus plugin

### ISSUE THREAD

**Issue by hiiamken** [GC-spigot/AdvancedEnchantments#4044]
### Describe the bug

I installed the latest version of advacedenchantment and beaconplus 3 but the console still spams error messages

### How to reproduce

Install the latest versions of the 2 plugins

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/90444f6e-8a23-4d89-802d-cd39ce8e717c)

### "/ae plinfo" link

https://paste.md-5.net/manusiyohu

### Server Log

https://mclo.gs/QinbUA9

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
