### ISSUE TITLE
BlockBreakEvent Error

### ISSUE THREAD

**Issue by mattisadev** [GC-spigot/AdvancedEnchantments#4045]
### Describe the bug

When I break any block I am presented with a [block break event error](https://mcpaste.io/d05b78a9ae8e8dc1). 

### How to reproduce

Break any block

### "/ae plinfo" link

https://paste.md-5.net/ipinexizev

### Server Log

https://mcpaste.io/f450333e4aae2455

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
