### ISSUE TITLE
Getting mcmmo xp with telepathy enchant

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#4047]
### Describe the bug

When I put the custom enchanta "telepathy IV" on the spade. Then I went to gather the soil that I had built before, then I started to dig the soil
and I noticed that it gives mcmmo xp, and as we know that mcmmo only gives from generated land, then custom enchant got confused with mcmmo

### How to reproduce

Put telepathy enchant on spade and put dirt and mine that.

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/1Wr8jVIfcBqOi_/d13371Tu4Pd0?invite=cr-MSxmWXksNDkzMjA5MjEs

### "/ae plinfo" link

https://paste.md-5.net/tufanohiyu

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
