### ISSUE TITLE
Feature Request: @EntityInVision tag of some sort

### ISSUE THREAD

**Issue by xenxero1** [GC-spigot/AdvancedEnchantments#4049]
### Describe the bug

Currently there doesn't seem to be a way to select entities other than right clicking them, selecting all in an AOE, or hitting them and marking them as a victim. I'm trying to make something like a long-range spell or weapon that can place an effect like DO_HARM to a player or mob in the distance. There exists a method like this for blocks with @BlockInDistance, but not for entity selection.

### How to reproduce

n/a

### "/ae plinfo" link

x

**Comment by ThomasWega** [comment]
Target @EntityInSight will be added in next update. It'll allow to select an entity you are aiming on with a certain angle and distance threshold
