### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedEnchantments#405]
Add on groups config GUI color placeholder so I can change the color that on the placeholder like I want so if I want to get the color of the enchantment on lore to &e&l so the enchantment on item will be with bold and on the gui that will be &e. So that wont be bold on the Gui or the lore on the book. I could customize that like I want

**Comment by GC-spigot** [comment]
There's already a placeholder to get group color, put &l after to make it bold.
