### ISSUE TITLE
SUGGESTION: Improvements to EFFECT_STATIC

### ISSUE THREAD

**Issue by gamerdorks** [GC-spigot/AdvancedEnchantments#4051]
### Describe the bug

Allow EFFECT_STATIC work on mainhand and offhand items, and allow the use of pointers to specify the effect triggered on equip and on un-equip.
1. When you hold an item in your maindhand, or switch off of that item in your mainhand.
2. When you equip or unequip an item from your offhand, it will trigger the effect.
3. Use the `~equip` pointer to only trigger an effect when the item is equipped.
4. Use the `~unequip` pointer to only tigger an effect when the item is unequipped.

### How to reproduce

N/A

### "/ae plinfo" link

N/A

**Comment by GC-spigot** [comment]
Why not use `HELD` trigger? This sounds exactly like our HELD trigger. If you want to combine it with EFFECT_STATIC, you can use https://wiki.advancedplugins.net/abilities/pointers pointers already
