### ISSUE TITLE
Suggestion: ATTRIBUTE Effect

### ISSUE THREAD

**Issue by gamerdorks** [GC-spigot/AdvancedEnchantments#4054]
### Describe the bug

Add an effect called ATTRIBUTE, which allows you to set attribute modifiers for a certain amount of time, or unset them.

Proposed Syntax:
- `ATTRIBUTE:<TYPE>:<OPERATION>:<VALUE>:[TIME]`
- Types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/Attribute.html
- Operations: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/AttributeModifier.Operation.html
- Values: Any floating-point number within the attribute's value limits.  Setting this to 0 removes modifiers of that type.
- Time: (Optional) time in ticks set by the effect.  Leave blank for no time limit.

Examples:
- `ATTRIBUTE:generic_attack_speed:add_scalar:1:20` - Applies a +100% attack speed modifier for 20 ticks.
- `ATTRIBUTE:generic_armor:add_number:4` - Applies a +4 armor modifier until removed.
- `ATTRIBUTE:generic_knockback_resistance:add_number:0` - Removes any current Knockback Resistance buff by setting it to 0.

See the following links for reference:
- https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/Attribute.html
- https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/AttributeModifier.Operation.html
- https://minecraft.wiki/w/Attribute
- https://minecraft.wiki/w/Commands/attribute

### How to reproduce

N/A

### "/ae plinfo" link

N/A

**Comment by xenxero1** [comment]
+1

**Comment by ThomasWega** [comment]
I wonder how many people would actually use this. If you work with something like this, why don't just create a custom effect yourself?

**Comment by ThomasWega** [comment]
If you already have some, I'd be more than happy to implement it as native
