### ISSUE TITLE
Effect error spamming

### ISSUE THREAD

**Issue by vxkShelby** [GC-spigot/AdvancedEnchantments#4055]
### Describe the bug

Randomly starts spaming chat / console with this error

28.02 19:52:10 [Server] WARN [AdvancedEnchantments] Failed to activate effect 'PARTICLE:FALLING_LAVA:5:0@Aoe{radius=4,target=mobs}'
28.02 19:52:10 [Server] WARN [AdvancedEnchantments] Additional information: invalid targets

### How to reproduce

Totaly random .... sometimes often... sometimes not.....

### "/ae plinfo" link

 https://paste.md-5.net/oduhucuwug

**Comment by SirJben** [comment]
Open a AE ticket on our Discord https://discord.gg/advancedplugins
