### ISSUE TITLE
Suggestion: New version of AE support older versions of MC

### ISSUE THREAD

**Issue by LoxPlayz** [GC-spigot/AdvancedEnchantments#4056]
### Describe the bug

Hello! Could be cool if you could make the newer versions of AE support the older versions of Minecraft (like 1.8 example) since there’s still a lot of servers that uses 1.8. Also kinda sucks you can’t get any features added for the 1.8 version anymore. If this is possible, it could be really helpful :)!

### How to reproduce

what I said in the top. Could make people with 1.8 servers able to use the newer versions of AE, so they get the newer features + can get things added.

### "/ae plinfo" link

N/A

**Comment by ThomasWega** [comment]
It's really hard to keep support and all features working with all of these versions. We did support 1.8 previously and it caused so many issues. Developing a new version only for 1.8 is also not worth it.
