### ISSUE TITLE
 Could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by hiiamken** [GC-spigot/AdvancedEnchantments#4059]
### Describe the bug

I'm getting console spam when updating to the latest version

The server with beaconplus is fine, but my other 2 servers both have this error (they dont have beaconplus)

### How to reproduce

Turn on the server and you'll get the problem

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/b8791264-65a0-4832-b7d4-ffd6d82143c3)

### "/ae plinfo" link

https://paste.md-5.net/qodusupuqu

### Server Log

https://mclo.gs/eskIJpe

**Comment by hiiamken** [comment]
<img width="798" alt="Ảnh màn hình 2024-03-01 lúc 10 40 26" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/aaf7a27c-9191-4d63-b77f-9db7f540cb06">

server with beaconplus still issue

**Comment by GC-spigot** [comment]
Fixed next update
