### ISSUE TITLE
WAIT effect issue

### ISSUE THREAD

**Issue by IamWTbro** [GC-spigot/AdvancedEnchantments#406]
I have been having WAIT effect issues for a while now so basically here is my config:
      - SPAWN_ARROWS %victim%
      - PLAY_SOUND:GHAST_SCREAM2
      - ADD_HARM:1 %victim%
      - MESSAGE:&d&l*&5&l* &d&lGod's Rain &5&l*&d&l* %victim%
      - MESSAGE:&d&l*&5&l* &d&lGod's Rain &5&l*&d&l* %attacker%
      - WAIT:60
      - SPAWN_ARROWS %victim%
      - PLAY_SOUND:GHAST_SCREAM2
      - ADD_HARM:1 %victim%
      - MESSAGE:&d&l*&5&l* &d&lGod's Rain &5&l*&d&l* %victim%
      - MESSAGE:&d&l*&5&l* &d&lGod's Rain &5&l*&d&l* %attacker%
      - WAIT:60
      - SPAWN_ARROWS %victim%
      - PLAY_SOUND:GHAST_SCREAM2
      - ADD_HARM:1 %victim%
      - MESSAGE:&d&l*&5&l* &d&lGod's Rain &5&l*&d&l* %victim%
      - MESSAGE:&d&l*&5&l* &d&lGod's Rain &5&l*&d&l* %attacker%
      - WAIT:60
      - SPAWN_ARROWS %victim%
      - PLAY_SOUND:GHAST_SCREAM2
      - ADD_HARM:1 %victim%
      - MESSAGE:&d&l*&5&l* &d&lGod's Rain &5&l*&d&l* %victim%
      - MESSAGE:&d&l*&5&l* &d&lGod's Rain &5&l*&d&l* %attacker%

So what happens is that the enchant skips 1 WAIT effect and causes it to rain arrows and deal damage twice then the next WAIT effect works. That is my problem

**Comment by GC-spigot** [comment]
What minecraft / plugin version are you using?

**Comment by IamWTbro** [comment]
I am using the latest version and the version 1.8 I believe

**Comment by IamWTbro** [comment]
By latest version I mean the latest version of AE and Minecraft 1.8
