### ISSUE TITLE
Placeholder don't work

### ISSUE THREAD

**Issue by leogianfagna** [GC-spigot/AdvancedEnchantments#4061]
### Describe the bug

the placeholder %advancedenchantments_item_enchants_total_GROUP% doesn't work. It always return 0 (zero).

### How to reproduce

1. Enchant a item
2. Use /papi parse me %advancedenchantments_item_enchants_total_simples% (replace "simples" with the group name

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142264317/3b2c6c0b-cea0-43ca-a976-583a18c39b73)

### "/ae plinfo" link

https://paste.md-5.net/orawuyoyaw

**Comment by ThomasWega** [comment]
Will be fixed in the next update!

**Comment by ThomasWega** [comment]
Wiki will be updated with some more placeholders soon as well
