### ISSUE TITLE
Cannot invoke "org.bukkit.entity.LivingEntity.hasPotionEffect(org.bukkit.potion.PotionEffectType)" because "<parameter2>" is null

### ISSUE THREAD

**Issue by BronzWarq** [GC-spigot/AdvancedEnchantments#4067]
### Describe the bug

My players just use enchantments and an error pops up in the console every time

### How to reproduce

My players just use enchantments and an error pops up in the console every time
https://paste.helpch.at/qanasomede.csharp

### "/ae plinfo" link

https://paste.md-5.net/yupuyihena

### Server Log

https://paste.helpch.at/wejawobure.makefile

**Comment by GC-spigot** [comment]
You need to fix your enchantment which has effect `FIRE_RESISTANCE:1:20000`, this has time length - but it's not allowed when using with EFFECT_STATIC trigger
