### ISSUE TITLE
/enchants - Right click on /ce page not showing list of enchants

### ISSUE THREAD

**Issue by Ollie7821** [GC-spigot/AdvancedEnchantments#4069]
### Describe the bug

When I perform the /enchants command it states an internal error has occurred and for some reason when I open the enchanter, I cannot right click to view the enchants even though it's enabled in the menus config 

### How to reproduce

PLease help

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by SirJben** [comment]
Hello @Ollie7821 open an AE Ticket and your AE folder on our Discord server https://discord.gg/advancedplugins

**Comment by Ollie7821** [comment]
I've been trying to verify my acount all morning, I bought the plugin on spigot and i've added my discord username but cannot seem to verify

**Comment by SirJben** [comment]
Open a prepurchase ticket and staff members will manually verify you.
