### ISSUE TITLE
Telepathy cancels out other enchants.

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#407]
AE- 5.5.3
paper spigot 1.13.2

Telepathy is canceling out other advanced enchants

So far we have found:

-Confirmed: telepathy cancels out reforged.
-Confirmed: telepathy cancels out auto smelt.
-Confirmed: telepathy cancels out experience.

**Comment by GC-spigot** [comment]
Do you have a video showing this? I'm not able to reproduce it.

**Comment by Kbryst** [comment]
No. I'll see if I can make one.

**Comment by Kbryst** [comment]
Video wouldn't record right.

I was able to recreate this on a test server with just vault and essentials.

And now older issues are showing up. Like telepathy emptying out shulker boxes on break

**Comment by Kbryst** [comment]
Update:

Fully tested on:
Paper spigot 1.13.2
#621 (Updated 4/16/2019)

AdvancedEnchantments 5.5.5

Tested on a test server which only had: EssentialsX, Multiverse Core, Vault.


I was able to recreate all of this including telepathy emptying out shulker boxes, which I know was fixed in an older version of AdvancedEnchantments.


Video won't record correctly, what else would you like me to do instead.
