### ISSUE TITLE
Telepathy enchant doesn't collect everything in the inventory

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#4072]
### Describe the bug

The telepathy enchant doesn't fulfill its purpose, it doesn't collect everything in the inventory

### How to reproduce

Have telepathy enchant on hoe and try harvest farm.

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/1ZL4hyV42JtUr_/d1337XBc7uAw?invite=cr-MSxIQmssNDkzMjA5MjEs

### "/ae plinfo" link

https://paste.md-5.net/limatewidi

**Comment by ThomasWega** [comment]
Are you sure these are not some sort of bonus drops from a different plugin?
