### ISSUE TITLE
Console spam parsing

### ISSUE THREAD

**Issue by vxkShelby** [GC-spigot/AdvancedEnchantments#4073]
### Describe the bug

09.03 10:23:10 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:10 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:10 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:10 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:10 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:10 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:11 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:11 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:11 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:11 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:14 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:14 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:14 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:14 [Server] WARN Invalid condition: 0 > 4: %allow%, enchant was stopped from parsing
09.03 10:23:14 [Server] WARN Invalid condition: air contains redstone_ore: %allow%, enchant was stopped from parsing
09.03 10:23:14 [Server] WARN Invalid condition: air contains diamond_ore: %allow%, enchant was stopped from parsing 

### How to reproduce

i do not exactly know

### "/ae plinfo" link

https://paste.md-5.net/regubuhiki

**Comment by ThomasWega** [comment]
This is a misconfiguration for sure. Maybe you dont have a space in front of the `:`. Maybe it's something else. You can send the enchantment that doesn't work and I'll tell you what's wrong. Please send it formatted please.

**Comment by vxkShelby** [comment]
thats the thing .... enchantments seems to work .... this is just random errror in console ... idk when idk why ... i did not get report from any player that some enchtanment dont work ... but i would like to have a console without errors

**Comment by ThomasWega** [comment]
It's your misconfiguration. Cannot help if you don't show me anything
