### ISSUE TITLE
ADD_DURABILITY_ITEM:-5 breaks unbreakable armors

### ISSUE THREAD

**Issue by JericNisperos** [GC-spigot/AdvancedEnchantments#4074]
### Describe the bug

any ADD_DURABILITY effects that has a negative value, which is to lessen or deduct durability of an item / weapon / armor permanently destroys unbreakable items from other plugins (such as EliteMobs, MMOItems). These plugins prevents custom items from being destroyed by keeping the durability never drop to 1, which is a good feature to retain items but unusable until fixed.

However, if an elitemob item for example has a durability of 3 and an ADD_DURABILITY_ITEM:-5 has been applied, it permanently destroys the item.

### How to reproduce

Have atleast an elitemob armor or an MMOItem with custom durability and apply any AE enchant to a sword that has ADD_DURABILITY_ITEM:-5 in it, instead of reducing and keeping the durability to 1 to avoid the item being destroyed, it lowers the durability till 0 which makes the item break.

### Screenshots / Videos

N/A

### "/ae plinfo" link

https://paste.md-5.net/yirehejamo

### Server Log

N/A

### Additional information
This can be fix by adding an option to check first for the durability of an item/weapon/armor and if it's lower than the intended durability damage, it fixes the value into 1 making it unbreakable which should not bypass other plugin items from breaking.

**Comment by ThomasWega** [comment]
You can probably do this yourself with conditions and checking nbt of the item. If it's unbreakable. This can really only be fixed from us by hooking into the plugins, which is not the best solution.

**Comment by ThomasWega** [comment]
This is similar as well. We'll add the hooks soon. https://github.com/GC-spigot/AdvancedEnchantments/issues/3972

**Comment by ThomasWega** [comment]
Just tried on latest version and it works fine. If the item is unbreakable, we will not damage it. If It's breakable and you don't want it to go under some limit, you can check yourself with conditions and nbt.
