### ISSUE TITLE
1.20.4 Paper #450 Give blackscroll over 100%

### ISSUE THREAD

**Issue by Denial234** [GC-spigot/AdvancedEnchantments#4075]
### Describe the bug

You can go over 100 when typing in /ae giveitem **player** blackscroll 1 1000

### How to reproduce

Type in /ae giveitem **player** blackscroll 1 1000

### Screenshots / Videos

https://img001.prntscr.com/file/img001/K1SWVKMiT468_uzG76Y8aA.png

### "/ae plinfo" link

https://paste.md-5.net/mixepafece

**Comment by GC-spigot** [comment]
Thanks fixed
