### ISSUE TITLE
Guards attack player

### ISSUE THREAD

**Issue by abhisantos** [GC-spigot/AdvancedEnchantments#4078]
### Describe the bug

The GUARD feature is not working properly.
The guards attack the player and not the mobs/enemy

### How to reproduce

Spawn some zombies, wear armor enchanted with guards, may be iron golem or warden.
When the guards spawn to protect you, you instantly hit them, because you are fighting the zombies, and the guards try to attack you. and they forget the zombies.
They cant hit you, but they keep trying

### "/ae plinfo" link

https://paste.md-5.net/colovomeqi

**Comment by ThomasWega** [comment]
What guards have you tried? Wardens are a known issue, but everything else should work just fine

**Comment by abhisantos** [comment]
First i tried with iron golems. Same issue happened

Em seg., 18 de mar. de 2024 às 12:57, ThomasWega ***@***.***>
escreveu:

**Comment by ThomasWega** [comment]
I cannot replicate this. Can you please send a video showcase?
