### ISSUE TITLE
Telepathy (TP_DROPS) Dupe

### ISSUE THREAD

**Issue by ElysiumSMP** [GC-spigot/AdvancedEnchantments#4079]
### Describe the bug

The `TP_DROPS` effect has a very slight chance to **duplicate** the item mined. During testing, it can occur as frequently as every 20 items mined, up to every 50 items mined.

The duplication occurs by both teleporting the drop into your inventory, while the mined item also drops on the ground.

To illustrate:
> When mining `diamond_ore` with a `TP_DROPS` pickaxe, one diamond is teleported into your inventory, but another diamond is also **`duplicated`** on the ground.

### How to reproduce

(1) Enchant an item with `Telepathy`, or any enchantment with `TP_DROPS` effect.
(2) Mine up to `100` blocks.
(3) Mined item is both dropped onto the ground, and also teleported into inventory, effectively duplicating the item.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/163357569/95e7dd36-da4b-473b-8998-1b0b73645ccc)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/163357569/5053c2ff-8210-4b4c-821f-43280bd696b0)

### "/ae plinfo" link

https://paste.md-5.net/iziwajoxow

**Comment by MasonX3** [comment]
Can confirm, having the same issue.

Here's my "/ae plinfo" link: 
https://paste.md-5.net/itoqusocov

**Comment by ElysiumSMP** [comment]
> Can confirm, having the same issue.
> 
> It will also duplicate Shulker Boxes with their contents as soon as they are placed.
> 
> Here's my "/ae plinfo" link: https://paste.md-5.net/itoqusocov

Yep same here sadly. We've had to temporarily disable `TP_DROPS` from activating with all shulker boxes because of this

**Comment by MasonX3** [comment]
> > Can confirm, having the same issue.
> > It will also duplicate Shulker Boxes with their contents as soon as they are placed.
> > Here's my "/ae plinfo" link: https://paste.md-5.net/itoqusocov
> 
> Yep same here sadly. We've had to temporarily disable `TP_DROPS` from activating with all shulker boxes because of this

Odd, I had tried that and it still activated, had to disable the enchantment entirely to prevent the dupe.

**Comment by audeze** [comment]
Something similar also happens with Silk Touch & Veinminer(@Veinmine). Ex: I'll silk touch 36 emerald ores, 36 emerald ores will drop on the ground including ~25 raw emeralds. I'm an Admin on ElysiumSMP so "/ae plinfo" will be: https://paste.md-5.net/iziwajoxow

**Comment by ThomasWega** [comment]
I wonder if this could be a plugin incompatibility. This never happened to me while testing other stuff and mining. What if you guys try only with AE on the server?

**Comment by audeze** [comment]
What we have found out so far is: 
`Telepathy` doesn't teleport `mcmmo double drops` into your inventory and leaves it on the ground. Started happening after AE updated to `9.7.0`.

If you mine ore with `Telepathy` + `Silk touch` and it's a double drop from `mcmmo`, it will ignore `Silk touch` and just drop the raw material on the ground while teleporting the ore in your inventory. Started happening after AE updated to `9.7.0`.

**Comment by ThomasWega** [comment]
All should hopefully be fixed in the next update!
