### ISSUE TITLE
MCMMO + Smelt Effect not completely compatible

### ISSUE THREAD

**Issue by markusew** [GC-spigot/AdvancedEnchantments#408]
Hey, when having MCMMO double drops enabled and using a tool with Smelt Effect you get both the ingots from Smelt and the extra ore from MCMMO. Would it be possible so it does not give the extra ore from MCMMO?

**Comment by GC-spigot** [comment]
It's supposed to work like that. If you want something different with mcmmo, go to its config and change it.
