### ISSUE TITLE
TPS drop due to lore items

### ISSUE THREAD

**Issue by hiiamken** [GC-spigot/AdvancedEnchantments#4080]
### Describe the bug

I submitted spark in ticket and GC said "getting lore from item is causing lag"
This is my spark
https://spark.lucko.me/9zjnJdKqOF

### How to reproduce

I don't know why and can't describe specifically

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/7656de5b-46c4-4ee3-9634-3e748f3f4472)

### "/ae plinfo" link

https://paste.md-5.net/geyemipora

**Comment by ThomasWega** [comment]
I have implemented some more optimizations. Hope it helps. Will be available next update
