### ISSUE TITLE
Event to call block drops (Trench Enchantment)

### ISSUE THREAD

**Issue by hiiamken** [GC-spigot/AdvancedEnchantments#4081]
### Describe the bug

For example, when you mine a block stone, the block stone will automatically go into virtual storage instead of inventory.
1. Stone blocks will not fall on the ground after breaking
2. My storage will be +1 stone

In theory, when I use a pickaxe with the Trench enchantment, it will drop 8-9 blocks.
My problem now:
1. Storage has +9 blocks when breaking
2. 9 blocks still fall on the ground
So it will be duplicated into 18 blocks instead of 9 blocks
I want to fix the Item falling off the ground error

I want an event actuaclly a get for the drops and a cancel for the drops is enough

### How to reproduce

I want to have an event like GC said below. Thanks

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/ed000d28-883a-46dc-b837-0b550b0e9dc2)

### "/ae plinfo" link

https://paste.md-5.net/geyemipora

**Comment by ThomasWega** [comment]
What's your code? We run normal BlockBreakEvents 
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/ba544c5d-ca47-40ce-8be5-2f4957a4fbc1)

**Comment by hiiamken** [comment]
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/92e3c255-4f4f-4854-a193-8a58b1ccc143)

**Comment by hiiamken** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/8eda4d84-0aec-4867-a24f-7a4eb3914e52

**Comment by ThomasWega** [comment]
Your code is fine, but you need to use lower priority to run the code before we do. We run on HIGH, so you need to run on at least NORMAL
