### ISSUE TITLE
Nulify/souls issue

### ISSUE THREAD

**Issue by sennby** [GC-spigot/AdvancedEnchantments#4082]
### Describe the bug

Describe the bug
Date and Time of Occurrence: Consistently

Description of the Bug: . Basically, I have an Onyxian Shadowflame Axe that I've put Nullify IV on. I also put 10000 souls onto the ax because nullify is a pretty costly enchantment at 40 souls per use. I killed hundreds of blazes and creepers but not once did the ability activate, and I'm basing that on the fact that I didn't expend any souls. I don't know if maybe it's glitched or something, please help.

Steps to Reproduce: Put Nullify on a Onyxian Axe and some souls, and kill a bunch of stuff to see if it activates.

Location/Server: SMP

Screenshots or Video (if applicable): N/A

Impact on Gameplay: I used a lot of resources getting Nullify on my axe and it isn't working, I feel like I wasted all that time.

Frequency of Occurrence: It is consistent, Nullify hasn't worked for me once

Device and Minecraft Version: Java

How to reproduce
Date and Time of Occurrence: Consistently

Description of the Bug: Please don't remove this enchantment it's really cool I'm sure it's just a simple issue with how the custom items are tagged or something. Basically, I have an Onyxian Shadowflame Axe that I've put Nullify IV on. I also put 10000 souls onto the ax because nullify is a pretty costly enchantment at 40 souls per use. I killed hundreds of blazes and creepers but not once did the ability activate, and I'm basing that on the fact that I didn't expend any souls. I saw on the wiki page for custom enchantments that Nullify was originally a leggings enchantment but in-game it's a weapons enchantment, which I think makes more sense. I don't know if maybe it's glitched or something, please help.

Steps to Reproduce: Put Nullify on a Onyxian Axe and some souls, and kill a bunch of stuff to see if it activates.

Location/Server: SMP

Screenshots or Video (if applicable): N/A

Impact on Gameplay: I used a lot of resources getting Nullify on my axe and it isn't working, I feel like I wasted all that time.

Frequency of Occurrence: It is consistent, Nullify hasn't worked for me once

Device and Minecraft Version: Java

Screenshots / Videos
No response

Server Log
No response

### How to reproduce

Describe the bug
Date and Time of Occurrence: Consistently

Description of the Bug: . Basically, I have an Onyxian Shadowflame Axe that I've put Nullify IV on. I also put 10000 souls onto the ax because nullify is a pretty costly enchantment at 40 souls per use. I killed hundreds of blazes and creepers but not once did the ability activate, and I'm basing that on the fact that I didn't expend any souls. I don't know if maybe it's glitched or something, please help.

Steps to Reproduce: Put Nullify on a Onyxian Axe and some souls, and kill a bunch of stuff to see if it activates.

Location/Server: SMP

Screenshots or Video (if applicable): N/A

Impact on Gameplay: I used a lot of resources getting Nullify on my axe and it isn't working, I feel like I wasted all that time.

Frequency of Occurrence: It is consistent, Nullify hasn't worked for me once

Device and Minecraft Version: Java

How to reproduce
Date and Time of Occurrence: Consistently

Description of the Bug: Please don't remove this enchantment it's really cool I'm sure it's just a simple issue with how the custom items are tagged or something. Basically, I have an Onyxian Shadowflame Axe that I've put Nullify IV on. I also put 10000 souls onto the ax because nullify is a pretty costly enchantment at 40 souls per use. I killed hundreds of blazes and creepers but not once did the ability activate, and I'm basing that on the fact that I didn't expend any souls. I saw on the wiki page for custom enchantments that Nullify was originally a leggings enchantment but in-game it's a weapons enchantment, which I think makes more sense. I don't know if maybe it's glitched or something, please help.

Steps to Reproduce: Put Nullify on a Onyxian Axe and some souls, and kill a bunch of stuff to see if it activates.

Location/Server: SMP

Screenshots or Video (if applicable): N/A

Impact on Gameplay: I used a lot of resources getting Nullify on my axe and it isn't working, I feel like I wasted all that time.

Frequency of Occurrence: It is consistent, Nullify hasn't worked for me once

Device and Minecraft Version: Java

Screenshots / Videos
No response

Server Log
No response

### "/ae plinfo" link

https://paste.md-5.net/ifejusavif

**Comment by ThomasWega** [comment]
is it possible you've used the 3rd level? We forgot to add the effect there, as you can see. 
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/4f80bb7e-70d4-4d10-bf66-b80f9c5f5f0b)

**Comment by ThomasWega** [comment]
It works completely fine, but by default nulify enchantment works only on players. If you want it to work for mobs as well, you need to add another ATTACK_MOB trigger
