### ISSUE TITLE
"anvil-application" was not worked.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4085]
### Describe the bug

"anvil-application" was not worked if i set "enchant-book-item" in group.

### How to reproduce

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/3dc04b93-596f-4375-8d80-4146a088fde7)

this is grous.yml. when i remove "enchant-book-item" sections, anvil-application was worked.

### "/ae plinfo" link

https://paste.md-5.net/hesivawite

**Comment by Ecilpse** [comment]
cannot fixed?

**Comment by ThomasWega** [comment]
We'll look at it soon. Sorry for waiting so long

**Comment by ThomasWega** [comment]
Will be fixed in the next version
