### ISSUE TITLE
Add vulcan support for Timber enchantment 

### ISSUE THREAD

**Issue by MoGGaming** [GC-spigot/AdvancedEnchantments#4086]
### Describe the bug

Currently, players are getting banned by Vulcan because they are using the Timber enchantment, which breaks trees too fast. I tried to contact Vulcan Support, and they said I have to contact the AdvancedEnchantment plugin to add support for the Vulcan API.

### How to reproduce

add vulcan in your server
get timber enchantment 
try to cut tree 
And you will get ban

### "/ae plinfo" link

https://paste.md-5.net/hosedudoju

**Comment by ThomasWega** [comment]
Should be added in the next update.
