### ISSUE TITLE
Reforged triggers twice with Timber

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#4088]
### Describe the bug

Imagine you have Timber and Reforged on a diamond axe. The Reforged and Timber enchantment is set to a 100% chance of triggering.

Your diamond pickaxe is at 1300 durability and after you break a tree, it is now 1301 and after the next one it is 1302 and so on... This is certainly **not** the outcome I would have expected.

While I agree that this isn't game breaking, it becomes game breaking if the chances are not 100% and you rely on those numbers to be accurate.

### How to reproduce

Change Reforged and Timber to have a 100% chance of triggering for easier reproducability.

1. Get a diamond pickaxe and take some of its durability
2. Enchant the diamond pickaxe with Timber and Reforged
3. Break a tree
4. See the durability increase by 1 with every tree you break

### "/ae plinfo" link

https://paste.md-5.net/megixihoce

### Server Log

https://mclo.gs/IgRH3ff

**Comment by ThomasWega** [comment]
Will be fixed in the next update!

**Comment by ThomasWega** [comment]
Actually not. We first need to do some huge internal changes. This will take some time...

**Comment by ThomasWega** [comment]
Will be fixed next update
