### ISSUE TITLE
Timber incompatible with Unbreaking

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#4089]
### Describe the bug

If you break the same amount of blocks with Unbreaking 3 and then again with an axe that has Unbreaking 3 and Timber, you'll notice that the one with Timber takes more damage than the one with just Unbreaking 3, hinting towards the fact that Timber seems somewhat incompatible with Unbreaking.

### How to reproduce

Get 2 diamond axes.

1. Enchant diamond axe 1 with Unbreaking 3
2. Enchant diamond axe 2 with Unbreaking 3 and Timber (ideally give Timber no cooldown and a 100% chance to trigger)
3. Create an area with the same amount of logs with a '/fill' command, ideally somewhat big
4. Break the entire thing with the first axe
5. Replace the log area (with a '/fill' command again)
6. Break the entire thing with the second axe
7. Notice how the first axe has taken significantly less damage than the second one which has Timber on it.

### "/ae plinfo" link

https://paste.md-5.net/esicoxadog

### Server Log

https://mclo.gs/p1LHvnH

**Comment by ThomasWega** [comment]
I actually don't see much of a difference. Can you share your test numbers and possibly a video showcase? We handle unbreaking chances ourselves, but with the exact same logic as default

**Comment by Folas1337** [comment]
Video: https://www.youtube.com/watch?v=LW8CWRZwVMc

I tested both on exactly 2484 oak log blocks that I created with a '/fill' command as I said.
The one with only Unbreaking ends up with 956 durability and the one with Timber ends up with 698. That is a difference of 258 durability which is like 25% more damage than it should have taken and that is not insignificant.

I'd really appreciate if you could investigate this. Thanks :)

**Comment by ThomasWega** [comment]
You are on Bedrock. What if you try on Java?

**Comment by Folas1337** [comment]
> You are on Bedrock. What if you try on Java?

I am not on Bedrock, just using mods that make it look somewhat similar. I am using Java.

**Comment by ThomasWega** [comment]
Not able to replicate this at all. You are breaking the blocks in some weird way. Maybe it's caused by that. However, on our end it all works fine and unbreaking is calculated correctly

**Comment by Folas1337** [comment]
> Not able to replicate this at all. You are breaking the blocks in some weird way. Maybe it's caused by that. However, on our end it all works fine and unbreaking is calculated correctly

How could I possibly break them in "some weird way"?? I've shown you a video where I'm breaking them just normally and the numbers of 956 durability add up to what Unbreaking 3 is supposed to do! Unbreaking 3 prevents damage in 75% of all cases, basically cutting the damage the item takes in a fourth. A diamond axe has 1561 durability, ending with 956 means it has taken 605 durability damage. Multiply that by 4 and you get 2420 which is almost exactly how many log blocks (2484) I have spawned so this aligns with Minecraft and its expected behavior!

I've also now just gone ahead again and broken another 2484 oak logs just to verify again with no other plugins other than AE that it does indeed change how much damage the axe actually takes!

I have completely reset my entire AE folder and only changed in enchantments.yml that timber has a 100% chance and no cooldown. I have also removed any effects I had in the video and I have also removed any other enchantments and plugins, so it is literally ONLY AE installed with default config apart from timber being modified to be easier to troubleshoot for me.
<https://paste.md-5.net/murobanaro>

After this second test my axe with Timber is at 698 durability instead of anything near 956. How is that impossible for you to verify if I am literally doing it with nothing but AE installed, no effects and only Unbreaking 3 and Timber 3 on the axe??

Please consider reopening this case and reinvestigating, this is game breaking for me in its current state and I'm really disappointed in the current development of this issue.

**Comment by SirJben** [comment]
Hii @Folas1337 can you send your timber enchantment?

**Comment by Folas1337** [comment]
> Hii @Folas1337 can you send your timber enchantment?

```yaml
timber:
  display: '%group-color%Timber'
  description: Chance to break a tree in one hit
  applies-to: Axes
  group: ULTIMATE
  type: MINING
  settings:
    showActionBar: true
  applies:
    - ALL_AXE
  levels:
    '1':
      chance: 15
      cooldown: 5
      effects:
        - BREAK_TREE @Block
    '2':
      chance: 35
      cooldown: 5
      effects:
        - BREAK_TREE @Block
    '3':
      chance: 100
      #cooldown: 6
      effects:
        - BREAK_TREE @Block
```

And then using Timber 3 as I said. That's all I've done, that is literally the default config with just the chance changed to 100 and cooldown removed so there is none.

**Comment by ThomasWega** [comment]
Honestly. We are out of ideas. I agree it an issue, but there is not much we can do about it. We calculate the chances exactly the same as vanilla. There are no extra events block break events called at all. My only guess is something internal in spigot or issues with tick limits. I've also tried calculating the chances for all blocks at once, but that produced inaccurate results. I am sorrry
