### ISSUE TITLE
AdvancedEnchantments, do not work enchant Trench.

### ISSUE THREAD

**Issue by Nightmare1377** [GC-spigot/AdvancedEnchantments#4091]
### Describe the bug

Hi, can you help? All enchants work for me except for trench. They don't work at all.

### How to reproduce

I don't know

### "/ae plinfo" link

https://paste.md-5.net/loyesoxofi

**Comment by Nightmare1377** [comment]
`ava.lang.NullPointerException: Cannot invoke "String.split(String)" because "targetString" is null
	at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.TargetType.classifyTarget(TargetType.java:58) ~[AdvancedEnchantments-9.7.5.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.internal.TrenchTarget.getTargets(TrenchTarget.java:32) ~[AdvancedEnchantments-9.7.5.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.Targets.handleTargets(Targets.java:47) ~[AdvancedEnchantments-9.7.5.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.updateMain(ExecutionTask.java:226) ~[AdvancedEnchantments-9.7.5.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:93) ~[AdvancedEnchantments-9.7.5.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:57) ~[AdvancedEnchantments-9.7.5.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[AdvancedEnchantments-9.7.5.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.7.5.jar:?]
`

in log server when i break block with enchant

**Comment by Nightmare1377** [comment]
its enchant in enchantments.yml

``trench:
  display: '%group-color%Trench'
  description: Можливість прориву в зоні 3x3.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: ULTIMATE
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    '1':
      chance: 13
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '2':
      chance: 26
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '3':
      chance: 36
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '4':
      chance: 49
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '5':
      chance: 59
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '6':
      chance: 72
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '7':
      chance: 85
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '8':
      chance: 90
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '9':
      chance: 100
      effects:
        - BREAK_BLOCK @Trench{r=3}``

**Comment by Nightmare1377** [comment]
> ```ava.lang.NullPointerException: Cannot invoke "String.split(String)" because "targetString" is null at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.TargetType.classifyTarget(TargetType.java:58) ~[AdvancedEnchantments-9.7.5.jar:?] at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.internal.TrenchTarget.getTargets(TrenchTarget.java:32) ~[AdvancedEnchantments-9.7.5.jar:?] at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.Targets.handleTargets(Targets.java:47) ~[AdvancedEnchantments-9.7.5.jar:?] at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.updateMain(ExecutionTask.java:226) ~[AdvancedEnchantments-9.7.5.jar:?] at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:93) ~[AdvancedEnchantments-9.7.5.jar:?] at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:57) ~[AdvancedEnchantments-9.7.5.jar:?] at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[AdvancedEnchantments-9.7.5.jar:?] at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.7.5.jar:?] ```
> 
> in log server when i break block with enchant

**Comment by ThomasWega** [comment]
> ```
> 	at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.TargetType.classifyTarget(TargetType.java:58) ~[AdvancedEnchantments-9.7.5.jar:?]
> 	at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.internal.TrenchTarget.getTargets(TrenchTarget.java:32) ~[AdvancedEnchantments-9.7.5.jar:?]
> 	at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.Targets.handleTargets(Targets.java:47) ~[AdvancedEnchantments-9.7.5.jar:?]
> 	at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.updateMain(ExecutionTask.java:226) ~[AdvancedEnchantments-9.7.5.jar:?]
> 	at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:93) ~[AdvancedEnchantments-9.7.5.jar:?]
> 	at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:57) ~[AdvancedEnchantments-9.7.5.jar:?]
> 	at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[AdvancedEnchantments-9.7.5.jar:?]
> 	at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.7.5.jar:?]
> ```
> 
> in log server when i break block with enchant

please send the full error. This is only a part of it
