### ISSUE TITLE
Placeholders in messages from custom items

### ISSUE THREAD

**Issue by beachvisitor** [GC-spigot/AdvancedEnchantments#4093]
### Describe the bug

All placeholders are displayed correctly, but they do not work in messages from custom items. If I enter placeholders here, they will appear in plain text, not what they return. Example of an item with a message:

magic-dust:
    type: SUGAR
    id: 0
    custom-model-data: 0
    force-glow: false
    ...
    **messages:
      cannotApplyToStacked: '&c&l(!) &cCannot be applied to stacked books'**

### How to reproduce

.

### "/ae plinfo" link

https://paste.md-5.net/iwisatewak

**Comment by ThomasWega** [comment]
What placeholders would you like to use there?
