### ISSUE TITLE
BUG: PreciousStones 

### ISSUE THREAD

**Issue by SmartNamee** [GC-spigot/AdvancedEnchantments#4094]
### Describe the bug

CustomEnchantments that are block breaking or something related keeps bugging out with PreciousStones, Enchanments such as Trench, VeinMiner etc. 

### How to reproduce

Break the PreciousStones block using any of the block break enchantments

### "/ae plinfo" link

not required for this bug

**Comment by ThomasWega** [comment]
Duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4094
