### ISSUE TITLE
DUPE with mcmmo + trench enchant

### ISSUE THREAD

**Issue by axeldupuy** [GC-spigot/AdvancedEnchantments#4095]
### Describe the bug

in version 9.7.0

https://github.com/GC-spigot/AdvancedEnchantments/assets/72584413/eab0be39-bb94-49fd-9dd3-b6b0c3027b4c

### How to reproduce

break shulker with stone behind

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/72584413/01c7c50f-26a6-4f28-864e-47f80e77beef

### "/ae plinfo" link

https://paste.md-5.net/cixutoqega

**Comment by ThomasWega** [comment]
Will be fixed in the next update! :)
