### ISSUE TITLE
trench with fortune enchantment bug

### ISSUE THREAD

**Issue by eyedchalice2148** [GC-spigot/AdvancedEnchantments#4097]
### Describe the bug

this is a bug for bedrock players if their pickaxe has a trench with fortune enchantment and they have a shulker they can dupe everything inside of the shulker by duping the shulker itself tried it in java but not working only in bedrock and I tried it with bedrock with only trench enchantment it does not work but adding fortune the duping worked

### How to reproduce

I just remove the trench enchantment temporarily until the issue is resolved

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/159223486/c1cd77b8-de57-4ffb-abc5-11c064dea216)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/159223486/2c5bc396-cab4-4ed9-9e35-ba70bd6e0be7)

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ThomasWega** [comment]
Please send a video showing the exact dupe
