### ISSUE TITLE
Finds vault then disables since it cant find vault.

### ISSUE THREAD

**Issue by OneRogue** [GC-spigot/AdvancedEnchantments#4098]
### Describe the bug

[AdvancedEnchantments] Enabling AdvancedEnchantments v9.7.5
[17:21:46 INFO]: [AdvancedEnchantments] Loaded 7 armor sets.
[17:21:46 INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[17:21:46 INFO]: [AdvancedEnchantments] Successfully hooked into economy plugin (Vault)

It shows on server startup that it finds vault and successfully hooks into it. 
For tests sake i have made it so that the server only has AE, Vault and Essentials/Novaconomy for a basic economy.
No matter what i try though, i keep getting the same message afterwards:
[17:46:43 INFO]: [AdvancedEnchantments] Could not initialise plugin, are you using Vault?
[17:46:43 INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v9.7.5

### How to reproduce

Starting up a server with the plugins in the image causes the issue to come up for me on start-up

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/49925479/368788f7-721f-4932-8a79-0e436e0229ce)

### "/ae plinfo" link

Cant do this since the plugin is disabled.

**Comment by OneRogue** [comment]
I tried going to the discord server first but the verification with spigotmc (where i purchased the plugin) failed multiple times to the point where i gave up with it and then came here to report it.

**Comment by ThomasWega** [comment]
We've had issues with our bot. Feel free to open prepurchase ticket and verify manually with our staff, although the bot should work now. My guess is it's license issues, but I cannot check it from my end. Support team needs to.

**Comment by GC-spigot** [comment]
This is definitely an issue with we can only fix on discord, it's a license problem.
