### ISSUE TITLE
BREAK_BLOCK_TREE not working | Showing error 

### ISSUE THREAD

**Issue by n0tlz** [GC-spigot/AdvancedEnchantments#4100]
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/104715109/e9ada73e-a12f-4876-b5e4-b7c8dcc85c45)

This is the bug. I don't know how to fix it 

### How to reproduce

Just by using the effect of BREAK_BLOCK_TREE it happens when the player breaks a tree.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/104715109/5cc29ea6-9374-481e-8e6a-e97cc8719c96)

### "/ae plinfo" link

https://paste.md-5.net/bejelopoda

### Server Log

https://mcpaste.io/c80777509200b801

**Comment by ThomasWega** [comment]
The valid effect is `BREAK_TREE`. Where have you found this one?
