### ISSUE TITLE
Whitelist not working with MULTIPLE DROPS

### ISSUE THREAD

**Issue by fortcraftch** [GC-spigot/AdvancedEnchantments#4104]
### Describe the bug

Hi after makeing a simple enchantmen with the effect multiple drops I have found that the withelist is not working (I have used the veinminer example for makeing this one).

### How to reproduce

fortunacristalizada:
  display: '§x§A§B§0§0§0§0F§x§A§F§0§2§0§0o§x§B§3§0§4§0§0r§x§B§6§0§7§0§0t§x§B§A§0§9§0§0u§x§B§E§0§B§0§0n§x§C§2§0§D§0§0a §x§C§5§0§F§0§0c§x§C§9§1§1§0§0r§x§C§D§1§4§0§0i§x§D§1§1§6§0§0s§x§D§5§1§8§0§0t§x§D§8§1§A§0§0a§x§D§C§1§C§0§0l§x§E§0§1§E§0§0i§x§E§4§2§1§0§0z§x§E§7§2§3§0§0a§x§E§B§2§5§0§0d§x§E§F§2§7§0§0a'
  description: Como la fortuna normal pero mejor.
  applies-to: Pico
  type: MINING
  group: PRIMORDIAL
  applies:
    - ALL_PICKAXE
  levels:
    '1':
      settings:
        whitelist:
          - "COAL_ORE"
          - "COPPER_ORE"
          - "IRON_ORE"
          - "GOLD_ORE"
          - "LAPIS_ORE"
          - "REDSTONE_ORE"
          - "DIAMOND_ORE"
          - "EMERALD_ORE"
          - "NETHER_QUARTZ_ORE"
          - "NETHER_GOLD_ORE"
          - "DEEPSLATE_COAL_ORE"
          - "DEEPSLATE_COPPER_ORE"
          - "DEEPSLATE_IRON_ORE"
          - "DEEPSLATE_GOLD_ORE"
          - "DEEPSLATE_LAPIS_ORE"
          - "DEEPSLATE_REDSTONE_ORE"
          - "DEEPSLATE_DIAMOND_ORE"
          - "DEEPSLATE_EMERALD_ORE"
      effects:
        - 'MORE_DROPS:2'

### Screenshots / Videos

https://photos.app.goo.gl/1A6tKhZmsHpCYqNs8
![2024-03-22_20 24 42](https://github.com/GC-spigot/AdvancedEnchantments/assets/164557068/8062722e-0d72-463f-af37-c0903fb943b7)
![2024-03-22_20 24 35](https://github.com/GC-spigot/AdvancedEnchantments/assets/164557068/a9c4d489-f3f8-4c15-a4c0-59fa8ae0984a)

![2024-03-22_20 24 28](https://github.com/GC-spigot/AdvancedEnchantments/assets/164557068/0db3a22d-c19c-4b94-9c76-7637514c0c06)

### "/ae plinfo" link

https://paste.md-5.net/xesekocoqi

**Comment by fortcraftch** [comment]
level 1 and 2 on the enchantment do the same thing and I have tried with the two of them

**Comment by ThomasWega** [comment]
Will be fixed in the next update
