### ISSUE TITLE
problem enchant

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#4105]
### Describe the bug

the problem with the gears enchantment
I, have a problem with this enchantment, the player can apply speed 1, and 2 on 1 item
and the strange thing is that /ae admin shows only 2 levels and not 3.

### How to reproduce

you can put books gears 1, 2, 3 on 1 item, for example on 1 item I will have 2 charms, speed 1 and 2

### "/ae plinfo" link

https://paste.md-5.net/zofepafunu

**Comment by SirJben** [comment]
Provide a video if you can please.

**Comment by ThomasWega** [comment]
I don't understand what the issue even is. Please do provide a video or at least screenshots and explain better what's wrong

**Comment by ThomasWega** [comment]
Videoooo
