### ISSUE TITLE
Obsidian stays when using Waterwalker Enchant

### ISSUE THREAD

**Issue by Lacsapd1** [GC-spigot/AdvancedEnchantments#4106]
### Describe the bug

The Obsidian created from the Waterwalker Enchant stays when the chunk it is in is unloaded

### How to reproduce

use waterwalker enchant and unload the chunk by for example teleporting to a home or something like that

### "/ae plinfo" link

https://paste.md-5.net/kicizoteqo

**Comment by GC-spigot** [comment]
Should be solved
