### ISSUE TITLE
Error between the item string and tripwire_hook. (TP_DROPS)

### ISSUE THREAD

**Issue by TopicflyOffi** [GC-spigot/AdvancedEnchantments#4107]
### Describe the bug

I am currently using the TP_DROPS effect along with the Silktouch enchantment on an axe, and as soon as one breaks a string with it, a tripwire hook is obtained directly in the inventory, and the string disappears.

### How to reproduce

Having the TP_DROPS effect and the Silktouch enchantment on an axe, breaking a string will result in obtaining a tripwire hook.

### Screenshots / Videos

Debug mode enabled : https://i.goopics.net/fytqyd.png
Video of the bug in question : https://youtu.be/rlCQASqNsQ8
Configuration : https://i.goopics.net/v4nic7.png

### "/ae plinfo" link

https://paste.md-5.net/ejoluwopaf

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
