### ISSUE TITLE
CMI or HeadsPlus duplicating with Smeling and telepathy #2

### ISSUE THREAD

**Issue by lajnicek** [GC-spigot/AdvancedEnchantments#4109]
### Describe the bug

Helloo
I have same problem like last time:
https://github.com/GC-spigot/AdvancedEnchantments/issues/4000
But there is one change, Its duplicating on walls(vertically). On the ground(horizontally) its ok :) 

Look at video. 

Thank you

### How to reproduce

/cmi mobhead cow (or other mob)
Enchant tool with Smelting
Place CMI head on **wall**
Break the head with enchanted tool

### Screenshots / Videos

Video link:
https://files.fm/u/9ndbw68fnj

### "/ae plinfo" link

https://paste.md-5.net/akosovayul

**Comment by ThomasWega** [comment]
Will be fixed in the next update
