### ISSUE TITLE
Updated to v9.7.8 and got this error...

### ISSUE THREAD

**Issue by Hellscaped** [GC-spigot/AdvancedEnchantments#4111]
### Describe the bug

9.7.8 ver error

### How to reproduce

Use 9.7.8?

### "/ae plinfo" link

I can't, the plugin disables itself.

### Server Log

https://mcpaste.io/fc029bbc2164a4db

**Comment by GC-spigot** [comment]
Hi it'll be fixed in ~5 minutes
