### ISSUE TITLE
Suggestion: REMOVE_FOOD

### ISSUE THREAD

**Issue by soapchan** [GC-spigot/AdvancedEnchantments#4112]
### Describe the bug

Same as the ADD_FOD but in reverse

### How to reproduce

N/A

### "/ae plinfo" link

e

**Comment by ThomasWega** [comment]
cannot you just use ADD_FOOD in negative? For example `ADD_FOOD:-10`?

**Comment by soapchan** [comment]
> cannot you just use ADD_FOOD in negative? For example `ADD_FOOD:-10`?

no it didnt work and jben told me to make this suggestion, as using negatives didnt work for what i was tying to do, so idk why you closed this suggestion.

**Comment by ThomasWega** [comment]
It works just fine. If you have an issue for some enchantment, feel free to create a new issue and describe the bug there

**Comment by soapchan** [comment]
> It works just fine. If you have an issue for some enchantment, feel free to create a new issue and describe the bug there
it doesnt work for my circumstance, which is why jben told me to make a suggestion for it....
![image_2024-03-25_102641790](https://github.com/GC-spigot/AdvancedEnchantments/assets/105493276/6d910588-eed7-41bd-a233-0cb666450191)
