### ISSUE TITLE
Error when /ae enchant

### ISSUE THREAD

**Issue by NoltoxGit** [GC-spigot/AdvancedEnchantments#4114]
### Describe the bug

Hello,
When I enchant an item with the `/ae enchant` command, it make a big error in console and the item isn't enchanted.

### How to reproduce

1. Execute `/ae enchant` command,
2. See the error

### "/ae plinfo" link

https://paste.md-5.net/amovequxaq

### Server Log

https://mclo.gs/ng98VTG#L1139

**Comment by TH3N3WN00B** [comment]
Same happens to me:

Purpur 1.20.4
''/ae plinfo'': https://paste.md-5.net/gojunutero

Server Log: https://mclo.gs/L5O8Uff#L648

**Comment by ThomasWega** [comment]
This is caused by the glow. We needed to temporarily remove it and didn't catch this issue. Just set custom-enchants-cause-glow to false in config.yml

**Comment by TH3N3WN00B** [comment]
Will try and see if that fixes it for me, thanks!
