### ISSUE TITLE
Failed to activate effect 'BREAK_BLOCK_BLOCK'

### ISSUE THREAD

**Issue by Chaekars** [GC-spigot/AdvancedEnchantments#4115]
### Describe the bug

I have a person on my server who made a pickaxe with the atomic detonate enchantment and anytime they use it, this spams the in game chat for everyone, I don't this it's a bug but I was hoping to fix it so we don't have the message popping up for everyone

### How to reproduce

Add atomic detonate to a pickaxe and use it. It might have something to do with it not having detonate but wouldnt the plugin come with a prevention measure to stop that from happening?

### Screenshots / Videos

![2024-03-24_11 26 24](https://github.com/GC-spigot/AdvancedEnchantments/assets/24541689/c8572b5f-8b6a-4ea8-a08f-c7792b41ea39)
![2024-03-24_11 26 31](https://github.com/GC-spigot/AdvancedEnchantments/assets/24541689/184ba05c-3b56-4846-be03-0a9480a31208)

### "/ae plinfo" link

https://paste.md-5.net/exixemalec

### Server Log

https://mcpaste.io/3eb7c8e1b3570872

**Comment by Chaekars** [comment]
Adding Detonate 9 did not resolve issue

**Comment by ThomasWega** [comment]
This is incorrect formatting. Use BREAK_BLOCK
