### ISSUE TITLE
Getting error when i trying to apply enchantement on items

### ISSUE THREAD

**Issue by Sobertimed** [GC-spigot/AdvancedEnchantments#4118]
### Describe the bug

when i type /ae enchant abiding 1 (on sword) , and it generate an error

### How to reproduce

/ae enchant abiding 1 (on sword)

### Screenshots / Videos

https://snipboard.io/mONC81.jpg

### "/ae plinfo" link

https://paste.md-5.net/emekowariw

**Comment by GC-spigot** [comment]
Fixed
