### ISSUE TITLE
Issue with /ae give command 

### ISSUE THREAD

**Issue by lDoomerl** [GC-spigot/AdvancedEnchantments#4121]
### Describe the bug

Getting an error with the command `ae give`, probably due to cyrillyc symbols in the item name and itemlore
Or maybe HEX

### How to reproduce

Any command `/ae give` with enchantment argument
Example
 `/aegive Lisatot netherite_sword 1 name:{#e63c17}Меч_Охотника lore:&f15%_шанс_удвоить_лут_с_моба|&e&oСочетается_с_добычей diploid:5`

### "/ae plinfo" link

https://paste.md-5.net/uxoquyeraz

### Server Log

https://mcpaste.io/bc5ef4efaa888934

**Comment by GC-spigot** [comment]
Fixed
