### ISSUE TITLE
Random loot not generating

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#4122]
### Describe the bug

As described in the title, it does not seem like random loot is being generated on my server. It should be noted that I'm using multiple world generation datapacks, including Terralith and Continents. No other plugins affect loot chest generation in any way (including UltimaAddons, which is my own plugin).

### How to reproduce

Use the following `lootConfiguration.yml`: https://pastebin.com/pt6Hdcff

As can be seen, there is a 100% chance of items being generated, and a 100% chance of that item being a random enchant book. However, I have not yet found any random chests that have an enchantment book in them. Commenting out `blacklisted-groups` does not fix it. My method was using `/locate` to find structures like villages and dungeons, and opening their loot chests.

### "/ae plinfo" link

https://paste.md-5.net/diwefoyesi

**Comment by ThomasWega** [comment]
Try without any interfering plugins and let us know
