### ISSUE TITLE
1.20.4: MAJOR BUG - Books won't apply on item due to new glow effect update

### ISSUE THREAD

**Issue by Denial234** [GC-spigot/AdvancedEnchantments#4123]
### Describe the bug

When the book is supposed to be applied as successful onto the item it throws an error and nothing happens.

### How to reproduce

Drag n drop book onto item to apply.

### "/ae plinfo" link

https://paste.md-5.net/awagaxumar

### Server Log

https://mcpaste.io/fd60f14d7ec170f4

**Comment by GC-spigot** [comment]
Fixed!
