### ISSUE TITLE
Condition chance: 0 is evaluated at 100%

### ISSUE THREAD

**Issue by Nanpure** [GC-spigot/AdvancedEnchantments#4124]
### Describe the bug

Enchantment has a `chance: 0` but goes off at 100%. Setting it to 1% lowers it tremendously, but it still goes off.

### How to reproduce

Set chance: 0 for an enchantment (such as Trench).

### "/ae plinfo" link

https://paste.md-5.net/motosacise

**Comment by ThomasWega** [comment]
Not sure why you would want chance 0 though

**Comment by GC-spigot** [comment]
Solved
