### ISSUE TITLE
Condition matchesregex does not work

### ISSUE THREAD

**Issue by Nanpure** [GC-spigot/AdvancedEnchantments#4125]
### Describe the bug

The condition to match via regex always fails.

### How to reproduce

```trench:
  display: '%group-color%Trench'
  description: Chance to break in 3x3 area.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: ULTIMATE
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    '1':
      conditions:
        - '%player is holding% matchesregex ^.\w+_PICKAXE : %allow%'
      effects:
        - BREAK_BLOCK @Trench{r=3}
```

This should match only with pickaxes, but it fails for all held items. It won't even match with `.+`.

### "/ae plinfo" link

https://paste.md-5.net/xoyagamiya

**Comment by ThomasWega** [comment]
Indeed. There was a space added at the start of the regex. so this actually worked `%player is holding% matchesregex^\w+_pickaxe : %stop%`. Will be fixed next update and will work as expected. Sorry for the delay and thanks for reporting
