### ISSUE TITLE
Console Spamming "Could not pass event InventoryClickEvent"

### ISSUE THREAD

**Issue by hiiamken** [GC-spigot/AdvancedEnchantments#4126]
### Describe the bug

I have had this error since updating to the latest version of AE

### How to reproduce

1. Install plugins
2. Console spamming

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/44fe49b3-de7c-4d3b-98fb-e3507de3fa60)

### "/ae plinfo" link

https://paste.md-5.net/uqokufozuj

### Server Log

https://mclo.gs/PBpUuyv

**Comment by hiiamken** [comment]
The error was discovered when a member pressed a CE book onto a SlimeFun item

**Comment by GC-spigot** [comment]
Fixed!
