### ISSUE TITLE
[AE] Smelting enchantment causing a dupe

### ISSUE THREAD

**Issue by Disorbs** [GC-spigot/AdvancedEnchantments#4128]
### Describe the bug

When a player has the AE enchantment Smelting and they place a solid block in this case a shulker box with a dispenser/piston and then using the pickaxe with smelting on it 1/10 itll drop a dupe idk why all the pickaxe has is effeciency 5 and Smelting 1.

### How to reproduce

1. Get a pickaxe and add smelting 1 on it.
2. put a dispenser down with a lever and add a shulkerbox with items in it.
3. move the lever and itll place the shulker box and simply mine it.
4. do step 2 and 3 over and over and 1/10 times itll drop a dupe and do it over and over.

### Screenshots / Videos

N/A

### "/ae plinfo" link

https://paste.md-5.net/egijubuzob

**Comment by ThomasWega** [comment]
Should be fixed on latest version
