### ISSUE TITLE
Enchants Stay on without the armor piece

### ISSUE THREAD

**Issue by Ollie7821** [GC-spigot/AdvancedEnchantments#4129]
### Describe the bug

I'm having an issue where players can spam equip armor with enchants on and off until the armor is off but they still have the effects from the custom enchant, is there any fix for this?

### How to reproduce

Make a 1 second cooldown before the effects become active?

### Screenshots / Videos

https://jmp.sh/YgpASK2D

### "/ae plinfo" link

Not sure

**Comment by SirJben** [comment]
@Ollie7821 /ae plinfo

**Comment by ThomasWega** [comment]
> Make a 1 second cooldown before the effects become active?
Try removing the cooldown and seeing if this still happens

**Comment by ThomasWega** [comment]
> Make a 1 second cooldown before the effects become active?

 Try removing the cooldown and seeing if this still happens
