### ISSUE TITLE
1.20.4: Item does not glow upon applying without vanilla enchantments.

### ISSUE THREAD

**Issue by Denial234** [GC-spigot/AdvancedEnchantments#4132]
### Describe the bug

When the item does not have any vanilla enchantments, it doesn't apply a glow to the item once a custom enchantment is applied.

### How to reproduce

Apply custom enchantment book to an item that does not have a vanilla enchantment

### "/ae plinfo" link

https://paste.md-5.net/morazamuqa

**Comment by GC-spigot** [comment]
Hi! We're fully aware of this and are working on a fix, should roll out soon :)

**Comment by PROBKA123** [comment]
Привет! Использую версию плагина 9.7.2. Аналогичная проблема, есть альтернативные варианты решения проблемы, кро обновления до новой версии?

> Привет! Мы полностью осознаем это и работаем над исправлением, оно должно появиться в ближайшее время :)
