### ISSUE TITLE
i cant open the /ae editor

### ISSUE THREAD

**Issue by Stoniasawsome** [GC-spigot/AdvancedEnchantments#4138]
### Describe the bug

i cant open the /ae editor

### How to reproduce

try to open the /ae editor

### "/ae plinfo" link

https://paste.md-5.net/omuqiduxif

**Comment by Stoniasawsome** [comment]
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/14824672/latest.log)

**Comment by ThomasWega** [comment]
I don't see any errors there
