### ISSUE TITLE
Feature Request: Ability to make certain levels not obtainable for server enchanter

### ISSUE THREAD

**Issue by MylaChuu** [GC-spigot/AdvancedEnchantments#4139]
### Describe the bug

Like in vanilla minecraft where you cannot obtain Sharpness V from the enchantment table, but only by combining it, have an option to make certain levels of your custom enchants not obtainable through the server enchanter but needed to be combined.

### How to reproduce

Feature Request (After asking about this in a ticket i was asked to put it in the github as a request!)

### "/ae plinfo" link

https://paste.md-5.net/jaruwoboco

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
