### ISSUE TITLE
Adding mobs to the target list?

### ISSUE THREAD

**Issue by Laurus69** [GC-spigot/AdvancedEnchantments#4140]
### Describe the bug

does anyone know how to make it so that like strike 3 also works on mobs bc for me @Victim or @Attacker only works for players

### How to reproduce

does anyone know how to make it so that like strike 3 also works on mobs bc for me @Victim or @Attacker only works for players

### "/ae plinfo" link

https://paste.md-5.net/evujumoyom

**Comment by SirJben** [comment]
Make sure your trigger are `ATTACK_MOB` or `DEFENSE_MOB`
