### ISSUE TITLE
Continuing issues with McMMO

### ISSUE THREAD

**Issue by MasonX3** [GC-spigot/AdvancedEnchantments#4141]
### Describe the bug

After the hotfix for McMMO Double Drops, a new issue has reared its ugly head...

"TP_DROPS" works for items that do not give McMMO Exp, such as Shulker Boxes, Grass, etc. 

When you try to mine something that has possible McMMO Exp given, or even double drops, TP_DROPS will stop working altogether. This could be "intended behavior" to prevent the drops from duplicating; however, I have a console error that says otherwise. 

The attached log demonstrates the error shown in console, and it continues to repeat. No matter what McMMO level in Mining a player is, this bug will happen. 

### How to reproduce

Install McMMO, as well as AdvancedEnchantments + Dependencies.

Create an enchantment with "TP_DROPS", and apply it to a Pickaxe. 

Mine Stone, you will notice that the stone drops rather than moving into your inventory. 

### "/ae plinfo" link

https://paste.md-5.net/gixamudoyi

### Server Log

https://mcpaste.io/b251a0c678255079

**Comment by Etanarvazac** [comment]
In reference to issues #4070 & #4102 which were considered "resolved" by [ThomasWega](https://github.com/GC-spigot/AdvancedEnchantments/issues/4102#issuecomment-2016949646)

**Comment by ThomasWega** [comment]
McMMO just randomly removed a class from their code, which we used, that's the reason

**Comment by ThomasWega** [comment]
Should be fixed next update
