### ISSUE TITLE
Since 9.7.9 - Enchanting an item does not replace old "custom slots left" tag

### ISSUE THREAD

**Issue by Nanpure** [GC-spigot/AdvancedEnchantments#4142]
### Describe the bug

Since the latest 9.7.9 update, each time I add a new enchantment to an item on the anvil it adds another "custom slots left" tag. The problem is that this tag gets repeated without the old one being removed.

### How to reproduce

Apply multiple enchantment books onto an item.

### Screenshots / Videos

![ae_slots](https://github.com/GC-spigot/AdvancedEnchantments/assets/155417978/48d40047-9632-4b51-8d14-e86f7cc7085d)

https://github.com/GC-spigot/AdvancedEnchantments/assets/155417978/2bcef52f-a09e-4e47-88dc-40e075d2ea0a

### "/ae plinfo" link

https://paste.md-5.net/urodolubih

**Comment by GC-spigot** [comment]
Fixed!
