### ISSUE TITLE
1.20.4: ae.limit.<number> permission applies globally for all groups if group is inherited by a lower limit value.

### ISSUE THREAD

**Issue by Denial234** [GC-spigot/AdvancedEnchantments#4143]
### Describe the bug

I don't really know if my permissions plugin might be the issue but i have 2 ranks on the server.
Member & VIP. Member has the permission ae.limit.5 and VIP inherits all the Member permissions so that also includes ae.limit.5
But i've put a limit ae.limit.10 on the VIP group and it still only restrict it to 5 enchantments.

This issue however does not happen when i'm using an auction house plugin where i limit how much a player can sell at the same time. For Member i have 4 and for VIP i have 8. And that works totally fine even if VIP inherits the Member permissions.
This is why i thought there might be a problem with the plugin.

If a group has a higher ae.limit.<number> it should overwrite the lower value.

I would also like to say that i set the priority higher for VIP so that is not the issue since the auction house works just fine using limit permission.

### How to reproduce

Set ae.limit.5 on a group and ae.limit.10 on another group, In herit the group permissions from the ae.limit.5 group to the ae.limit.10 group and the ae.limit.10 permission won't apply to the ae.limit.10 group but instead only use ae.limit.5

### "/ae plinfo" link

https://paste.md-5.net/rojavesopo

**Comment by GC-spigot** [comment]
Fixed!
