### ISSUE TITLE
Error when using /ae unenchant command

### ISSUE THREAD

**Issue by hiiamken** [GC-spigot/AdvancedEnchantments#4144]
### Describe the bug

I'm getting an error when I can't use the /ae unenchant command. It says on the message that the item doesn't have that enchantment even though it does

### How to reproduce

1. Use 1 sword or random tool
2. /ae enchant <enchantment>
3. /ae unenchantment <enchantment>

### Screenshots / Videos

https://youtu.be/7A_UqvB-kmI

### "/ae plinfo" link

https://paste.md-5.net/rocefopohi

**Comment by SirJben** [comment]
Hello @hiiamken, send your console logs doing this. We can't identify the issue because of translated messages.

**Comment by GC-spigot** [comment]
Fixed!
