### ISSUE TITLE
Error when trading with Shopkeeper plugin

### ISSUE THREAD

**Issue by hiiamken** [GC-spigot/AdvancedEnchantments#4145]
### Describe the bug

Hello, I'm using a plugin called Shopkeeper to exchange items, but currently, for example, I have a sword with an enchantment attached to it, and then I remove it and I can't exchange it in Shopkeeper

### How to reproduce

1. Add enchant on item
2. Remove the item's enchantment
3. Cannot trade

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/76dc90dc-7af9-407a-8932-df2f43cff574

### "/ae plinfo" link

https://paste.md-5.net/oxijemefis

**Comment by GJ-Euphory** [comment]
That will always happen, shopkeeper makes exchanges with items that are 100% identical. If the lore of the object is altered, it changes value and is no longer identical to what you intended to make. It's impossible unless you want to have a vulnerability and make exchanges less secure.

**Comment by hiiamken** [comment]
What should I do to fix it?

**Comment by GJ-Euphory** [comment]
You can't, the AE plugin itself adds the enchant texts yes or yes

**Comment by GC-spigot** [comment]
Yeah unfortunately we cannot solve this now, we don't use NBT anymore and switched to PDC.
