### ISSUE TITLE
[AdvancedEnchantments] Disabling AdvancedEnchantments v9.7.9

### ISSUE THREAD

**Issue by thuanvo123** [GC-spigot/AdvancedEnchantments#4147]
### Describe the bug

The plugin still works fine when I add just one enchantment enhancement plugin
Plugins are not working when I have added some plugins to support my skyblock server

I tried deleting each plugin to see if advanced enchantments were incompatible with the plugin but still got no response
In versions 1.20.1 and 1.20.1 paper, purpur

### How to reproduce

At the bottom is latest.log
[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/14817252/latest.log)

### "/ae plinfo" link

https://paste.md-5.net/rorocasozu

### Server Log

https://github.com/GC-spigot/AdvancedEnchantments/files/14817252/latest.log

**Comment by SirJben** [comment]
@thuanvo123 send your /ae plifno with visible plugins.

**Comment by GC-spigot** [comment]
Where did you purchase the plugin from? We need your account, e.g. if from Spigot, give a link to your spigot account here please.

**Comment by thuanvo123** [comment]
> Where did you purchase the plugin from? We need your account, e.g. if from Spigot, give a link to your spigot account here please.

I bought them at advancedplugins.net

**Comment by thuanvo123** [comment]
> send your /ae plifno with visible plugins.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/93034076/68d14d37-955c-4588-8f40-5a03b3797059)

**Comment by KryptoKnight71** [comment]
I am having the same issue. I run a 1.20.4 Paper server and when i updated the plugin to AdvancedEnchantments-9.7.10 The plugin refuses to Enable and the console says Disabling plugin is it up to date?? When i type ./pl on my server its in Red. 
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/165975390/35dcc1c7-896f-4bb7-838a-77138da425e1)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/165975390/abd5d662-eef8-4c6a-a101-8aed57ad4304)

**Comment by SirJben** [comment]
@KryptoKnight71 open a ticket in our Discord server and send your startup log.
