### ISSUE TITLE
itemnametag can't use ( bug)

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#415]
1.
some bug itemnametag can't rename any item
I want to use this item to use in all item
can you check?

![image](https://user-images.githubusercontent.com/5382252/55895106-1427af80-5bee-11e9-89b6-0cdf5a6785c9.png)

2.
white-scroll
force-glow: true (no work) i test

spigot 1.13.2
AE 5.5.5

**Comment by GC-spigot** [comment]
I'll fix the encoding issue which causes that weird character in front of message. You must have no custom enchantments on items, which is required for it to be renameable.
