### ISSUE TITLE
/alchemist not working

### ISSUE THREAD

**Issue by xMarnel** [GC-spigot/AdvancedEnchantments#4150]
### Describe the bug

When I try to combine books the menu just closes and nothing happens.
![ae error](https://github.com/GC-spigot/AdvancedEnchantments/assets/80050200/081366f3-e9a3-441c-919d-c3f7602bf1bd)

### How to reproduce

Open /alchemist try to combine books.

### Screenshots / Videos

![ae error](https://github.com/GC-spigot/AdvancedEnchantments/assets/80050200/e4a4f09f-d7fc-4030-8f5f-e6f050ed5f16)

### "/ae plinfo" link

https://paste.md-5.net/wirifetemo

**Comment by GC-spigot** [comment]
Fixed!
