### ISSUE TITLE
GUI's not working for AE

### ISSUE THREAD

**Issue by TheRealBlitz** [GC-spigot/AdvancedEnchantments#4151]
### Describe the bug

When running on our main server using other plugins, the GUIs are not working.

When running on an emtpy server with less plugins, it is working fine. Would appreciate some assistance to identify the root cause and to fix it.

### How to reproduce

Perhaps a screen share session would make it easier to show what we have and what is happening.

### "/ae plinfo" link

No errors in plugin, best reach out and I show you as it works on a fresh spigot installed server

**Comment by GC-spigot** [comment]
You've given no details or information. Include a server log at least. We haven't had anyone report this.

**Comment by TheRealBlitz** [comment]
Hey of course. Please find it attached.
- Latest Server Log
- /ae plinfo" link - https://paste.md-5.net/mufefogujo
[Uploading latest.log…]()

One example:
GUI opens
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/140232769/78a742f8-53ef-4390-8522-4a435ed619a5)
But clicking on the items does nothing
