### ISSUE TITLE
Good dupe

### ISSUE THREAD

**Issue by EcopiaMC** [GC-spigot/AdvancedEnchantments#4152]
### Describe the bug

When mining the nether gold ore with the smelting enchant you don’t get nuggets you get loads of ingots wich is kinda op.

### How to reproduce

Enchant the pick and mine the nether gold ore

### Screenshots / Videos

https://www.mediafire.com/file/wgzk9xpv4bc2iyh/Screen_Recording_2024-04-01_at_10.00.09_AM.mov/file

### "/ae plinfo" link

https://paste.md-5.net/osulesaral

### Server Log

I cannot give you the server logs as that would leak player data wich I’m not comfortable doing

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
