### ISSUE TITLE
Could not pass event BlockBreakEvent to AdvancedEnchantments v9.7.9

### ISSUE THREAD

**Issue by jdjfj91929** [GC-spigot/AdvancedEnchantments#4153]
### Describe the bug

I'm not an expert I can't give details, but in the photo you can see it, and that error is appearing every 5 seconds, a lot of spam on the console

### How to reproduce

I'm not an expert, in the image you can see

### Screenshots / Videos

![IMG_5096](https://github.com/GC-spigot/AdvancedEnchantments/assets/66286286/7aa4dc7a-4e29-4848-86a5-5ec5ce11dd27)

### "/ae plinfo" link

https://paste.md-5.net/vexihocica

**Comment by GC-spigot** [comment]
Hii! We already fixed this for next update :) will be out in an ~hour
