### ISSUE TITLE
Could not pass event InventoryClickEvent to AdvancedEnchantments

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#4155]
### Describe the bug

I don't know how this happened, but it started when I updated to version v9.7.9

error console: https://mclo.gs/ZNYAM3s

server version: git-Pufferfish-47 (MC: 1.20.4)

### How to reproduce

update for v9.7.9

### "/ae plinfo" link

git-Pufferfish-47 (MC: 1.20.4)

**Comment by Yurkhun** [comment]
I also have the same issue:
https://mclo.gs/uRleLox

**Comment by GC-spigot** [comment]
Looking into this.
