### ISSUE TITLE
REPEATING type enchantments get perpetualy activated when traveling to other worlds

### ISSUE THREAD

**Issue by fortcraftch** [GC-spigot/AdvancedEnchantments#4156]
### Describe the bug

Hi, I have discovered that enchantments that have the triger REPEATING get perpetually activated (even when the item is not equiped) when you go to another world while having the item with the enchantment equiped, it will only deactivate when a reload is used, on the video you will see me using a menu but it only does "/warp" commands.

### How to reproduce

using any repeating enchantment (easier to spot if it uses particles), the one I showed on the video is this one.
Changeing the time to any other number does not solve the issue (I have tried it before).

lluvia:
  display: '§x§F§F§0§0§C§4P§x§F§8§0§0§C§6a§x§F§1§0§0§C§7r§x§E§A§0§0§C§9a §x§E§3§0§0§C§Bq§x§D§D§0§0§C§Cu§x§D§6§0§0§C§Ee §x§C§F§0§0§D§0n§x§C§8§0§0§D§1o §x§C§1§0§0§D§3p§x§B§A§0§0§D§5a§x§B§3§0§0§D§6s§x§A§C§0§0§D§8e§x§A§5§0§0§D§As §x§9§F§0§0§D§Bc§x§9§8§0§0§D§Da§x§9§1§0§0§D§Fl§x§8§A§0§0§E§0o§x§8§3§0§0§E§2r'
  description: Crea particulas que te siguen al llevar un casco equipado.
  applies-to: Casco
  type: REPEATING
  group: COSMETICO
  settings:
    not-applyable-with:
      - 'enfado'
      - 'cabezaardiendo'
      - 'corazones'
  applies:
    - ALL_HELMET
  levels:
    '1':
      time: 0.1
      effects:
        - PARTICLE:FALLING_WATER:3:0.3 @Add{x=0.0,y=2.5,z=0.0}
        - PARTICLE:CLOUD:3:0.3 @Add{x=0.0,y=3.5,z=0.0} 

### Screenshots / Videos

https://photos.app.goo.gl/1A6tKhZmsHpCYqNs8

### "/ae plinfo" link

https://paste.md-5.net/sowogipawi

**Comment by Stoniasawsome** [comment]
i have the same problem unfortunatly this issue will be closed and they will likely tell you "Your config needs to be incorrect. This works completely fine." like they have told me on more than one occassion. dont ask me why your config needs to be incorrect... this is what i was told by [ThomasWega](https://github.com/ThomasWega). I see many people have brought this up, it must be an issue they cannot fix or dont want to deal with.

**Comment by SirJben** [comment]
Try using EFFECT_STATIC instead.

**Comment by fortcraftch** [comment]
It is a good idea but the problem is that EFECT_STATIC only spawns 1 time the particle (or at least is what I have found after trying it out) and to create the effect/cosmetic it needs to be spawning constantly.

**Comment by ThomasWega** [comment]
Yeah this'll be issue with your config

**Comment by ThomasWega** [comment]
Just kiding, it's a bug

**Comment by ThomasWega** [comment]
Should be fixed in the next update

**Comment by fortcraftch** [comment]
thanks ;3
