### ISSUE TITLE
Effects An error occurred

### ISSUE THREAD

**Issue by LinAk900127** [GC-spigot/AdvancedEnchantments#4157]
### Describe the bug

I designed an enchantment
TP_DROPS is used, but it seems that there is an error in the drops of killing creatures and it has no effect, so the mining and collection performance is normal.

### How to reproduce

Enchantment name:TPITEM
Allowed: Swords Axes Pickaxes

My definition of enchantment is that it will be obtained directly whether it is collected or killed.

It seems to be killing creatures, but it has no effect. Instead, there are error reports.

### Screenshots / Videos

![2024-04-02_23 37 03](https://github.com/GC-spigot/AdvancedEnchantments/assets/125806086/c372b03a-3093-4d96-a197-95335717075d)
![2024-04-02_23 37 07](https://github.com/GC-spigot/AdvancedEnchantments/assets/125806086/ade47a15-f60c-49d9-b5f3-e9f0942e7283)
![2024-04-02_23 39 33](https://github.com/GC-spigot/AdvancedEnchantments/assets/125806086/42e4967d-4a1f-4ec7-88c6-7355864c6a24)
![2024-04-02_23 39 35](https://github.com/GC-spigot/AdvancedEnchantments/assets/125806086/0547bf7a-74a0-4c74-805e-2459a6570806)

### "/ae plinfo" link

https://paste.md-5.net/lokatasuxa

### Server Log

https://mcpaste.io/e6e462b663215535

**Comment by GC-spigot** [comment]
Hey, can you show your enchantment? It might be that there's no target set to it , e.g. `- 'TP_DROPS @Block'`

**Comment by ThomasWega** [comment]
Confirmed. Missing target
