### ISSUE TITLE
Duplicating Fish Tracker lore

### ISSUE THREAD

**Issue by Mirayii** [GC-spigot/AdvancedEnchantments#4159]
### Describe the bug

Whenever player catches a fish, the Fish Tracker lore creates another one instead of overwriting previous.

### How to reproduce

Adding Fish Tracker to item and fishing will create multiple lore lines

### Screenshots / Videos

https://prnt.sc/m0yItZLFF9XR

### "/ae plinfo" link

https://paste.md-5.net/xiquxihape

**Comment by ThomasWega** [comment]
That's interesting. First I though this issue was caused by us moving from NBT to PDC in 9.7.9, but this works absolutely fine for me. Does this happen only with old items or newly create as well? Are you able to send a video showcase please?

**Comment by Mirayii** [comment]
It creates new lore every time even on new items with Fishtrak. In offscreen i even tried with the Vanilla fishing mechanics to be sure that it's not caused by my plugin. Also tried it on new update 9.7.12
Video: https://www.youtube.com/watch?v=hF2PA1uOeUI

**Comment by Mirayii** [comment]
And with config reset, it still does create the same issue.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/45139953/5468fc94-01b3-4281-8b04-74de3266cb63)

**Comment by Folas1337** [comment]
Having the same issue, can confirm

**Comment by TheLaoming** [comment]
I can reproduce it too, but differently. For me it works fine all the time, until I use bait from plugin [EvenMoreFish](https://github.com/Oheers/EvenMoreFish). Once the bait is applied to the rod, anyitime a fish is caught, you get duplicated lore like this (probably bcs EMF adds it's own part of the lore, but still sounds more like a AE's issue).

**Comment by GC-spigot** [comment]
Solved! Sorry about the wait.
