### ISSUE TITLE
AE transmog issue

### ISSUE THREAD

**Issue by wheredabanat** [GC-spigot/AdvancedEnchantments#416]
When I apply a transmog with the same enchants that I am wearing. So you have a set with drunk 4, and a set with drunk 4 on a piece in your inventory. Apply a transmog on the drunk 4, and your potion effect will go away for strength III. 

I am using 1.8.8 Paper Spigot
5.55 AE (Latest Version)

**Comment by GC-spigot** [comment]
Fixed!
