### ISSUE TITLE
Due to version 9.7.9 the items are not interchangeable!!

### ISSUE THREAD

**Issue by GJ-Euphory** [GC-spigot/AdvancedEnchantments#4160]
### Describe the bug

Because of version 9.7.9, items cannot be exchanged no matter how many times I update the item, it keeps changing value at all times and does not allow my players to exchange with the Shopkeeper plugin. It's really annoying that they made this change without considering the consequences!! It is greatly affecting the activity of my users and forces me to update their items all the time, when I should be doing other things!!

### How to reproduce

Its value simply changes and is untradeable with Shopkeeper.

### Screenshots / Videos

I want to emphasize, I'm not stupid, I have copied this item to the requirement item to test, but not even that, the value of the id changes instantly.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/122542736/32a13e12-6fd6-4540-9dac-25607c4d6e45)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/122542736/f5a42bbb-c898-430c-be1c-19b1a504eb6d)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/122542736/9d59f67d-07a7-46e7-8dc6-ee0cc9e8c937)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/122542736/e9f0ae11-ad99-433a-8f0b-f5721a627d8c)

As an example, this item has "Gears", showing that it has an enchantment of this same plugin.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/122542736/0d536adb-d74e-47b8-87b2-6cbd04ab3a75)

### "/ae plinfo" link

https://paste.md-5.net/zilevonoji

**Comment by ThomasWega** [comment]
If you get new items does it work fine?

**Comment by ThomasWega** [comment]
We did not wanted to make this change, but we were kind of forced to do that. Many things will change in 1.20.5 and also NBT has many downsides. So we needed to move to PDC. Believe me, if it was not necessary, we'd not make this move

**Comment by GJ-Euphory** [comment]
Even though they are new items, they change and it is a headache, I had to switch to the version where they still use NBT, that does work for me but it will surely stop working when I improve the base version of my server.

**Comment by ThomasWega** [comment]
Can you check the PDC and NBT data and find what exactly changes value and doesn't match?

**Comment by ThomasWega** [comment]
this would show the NBT of item in your hand

/data get entity @s SelectedItem

**Comment by GJ-Euphory** [comment]
https://pastebin.com/9MvXh38U

This is the ID that appears when you already have the latest version. Taken from the ItemEdit plugin (it has a kind of item store to save the items that I have been creating).

--------------------------------------------------------
https://pastebin.com/cc2c3Tqz

And this one now with the old version of Ae, when the nbt was still used.

**Comment by GJ-Euphory** [comment]
I am now using the latest versions, this is the new data:

https://pastebin.com/jfDxsXNV

This seems to be the same, just in case I leave it.
https://pastebin.com/FrZbKS28

**Comment by GJ-Euphory** [comment]
Now this is the item that cannot be used for trading.

https://pastebin.com/D37Pd2US

**Comment by GC-spigot** [comment]
> Now this is the item that cannot be used for trading.
> 
> https://pastebin.com/D37Pd2US

There's nothing in this item from us, this is from ecoitems adding their data.
