### ISSUE TITLE
Wings enchant dont work

### ISSUE THREAD

**Issue by Stoniasawsome** [GC-spigot/AdvancedEnchantments#4161]
### Describe the bug

wings enchant dont work as of update 9.7.10. ive removed ALL the plugins except AE and wings still dont work. If i go back to v 9.7.9 wings works fine..

### How to reproduce

remove all plugins except AE try wings... it dont work. This started happeneing when you added "FLY effect will not attempt to enable flight for players that aren't allowed". Players shouldnt have to have a fly perm to use the wings enchant or its a useless enchant.

### "/ae plinfo" link

https://paste.md-5.net/yadarukiwa

### Server Log

https://mcpaste.io/ae1e4b2b302db43f

**Comment by Stoniasawsome** [comment]
i even removed cmi and luckperms to rule those out and its the same thing.
[05.04 10:18:14] [Server] [INFO] Bukkit Plugins:
[05.04 10:18:14] [Server] [INFO]  - AdvancedEnchantments, Vault

**Comment by GC-spigot** [comment]
Solved
