### ISSUE TITLE
POTION effect reset when scrolling, even when in offhand

### ISSUE THREAD

**Issue by ElysiumSMP** [GC-spigot/AdvancedEnchantments#4162]
### Describe the bug

When holding an item with the `POTION` effect in your offhand, such as `POTION:HEALTH_BOOST:0`, the effect gets continuously reset when scrolling in your offhand (the maximum health stays, but the total health gets reset to 0).

### How to reproduce

- Enchant an item with the effect `POTION:HEALTH_BOOST:0`
- Place the item in your offhand
- Scroll in your hotbar

### "/ae plinfo" link

https://paste.md-5.net/gikocefehu

**Comment by ThomasWega** [comment]
Should be fixed in the next update!
