### ISSUE TITLE
[bug] Regex restriction of [a-z0-9/._-] for enchantment key cause chinese/japanese server configration fail entirely

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#4163]
### Describe the bug

Regex restriction of [a-z0-9/._-] for enchantment key in enchantments.yml should be removed, chinese, japanese, russian or any server in location that does not use english as their mother language, will change the enchantment key so that the enchantment displayed in lore is their mother language. Setting this regex restirction will affect all customized settings for non-english server

### How to reproduce

load enchantments.yml with key in any non [a-z0-9/._-] character

### Recommendation
add a regex restriction configuration in config.yml which all users to manually configure the regex restriction,  with default value of [a-z0-9/._-] , use comment to warn users use at your own risk.

In fact, the plugin run without error when the regex does not exist, if you insist to keep it, please allow users to have a choice by themselves.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/61608872/a8ce8790-db6e-4d55-b812-1846077b7e3e)

### "/ae plinfo" link

https://paste.md-5.net/fahijogono

### Server Log

https://paste.denizenscript.com/View/121691

**Comment by GC-spigot** [comment]
This is unfortunately a limitation of Spigot. You would need downgrade the server version or change enchantment keys to use latin alphabet - https://ae.advancedplugins.net/enchantments/creating-enchantments#starting-out

**Comment by hkkongou** [comment]
> This is unfortunately a limitation of Spigot. You would need downgrade the server version or change enchantment keys to use latin alphabet - https://ae.advancedplugins.net/enchantments/creating-enchantments#starting-out

can you explain it more detail? What l imitation of Spigot is causing this and why the previous version of AE allow non latin alphabets?

I am already  using paper 1.20.1 which is actually old, i don't think there is any limitation for paper or spigot 1.20.1 regarding regex

**Comment by hkkongou** [comment]
> This is unfortunately a limitation of Spigot. You would need downgrade the server version or change enchantment keys to use latin alphabet - https://ae.advancedplugins.net/enchantments/creating-enchantments#starting-out

hello are you here?
