### ISSUE TITLE
9.7.11 - Disenchanting item creates duplicate "custom slots left" tags

### ISSUE THREAD

**Issue by Nanpure** [GC-spigot/AdvancedEnchantments#4164]
### Describe the bug

This is probably due to the 9.7.9 update and is related to this bug:

https://github.com/GC-spigot/AdvancedEnchantments/issues/4142

Players have found that they can still get duplicate "custom slots left" tags if they use the grindstone.

### How to reproduce

Apply one or multiple AdvancedEnchantment books to an item PLUS a vanilla Minecraft enchantment. It is not possible to remove custom enchantments without adding a vanilla enchantment. Use this item on the grindstone and all enchantments are moved but multiple "custom slots left" tags exist.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/155417978/9db37e47-2e19-46f2-a91f-cf5d9c28b546)

https://github.com/GC-spigot/AdvancedEnchantments/assets/155417978/f9e216be-9726-46a1-910c-a12db58a7dd2

### "/ae plinfo" link

https://paste.md-5.net/larufiyuco

**Comment by GC-spigot** [comment]
Fixed
