### ISSUE TITLE
Grindstone not able to remove custom enchantments

### ISSUE THREAD

**Issue by Nanpure** [GC-spigot/AdvancedEnchantments#4165]
### Describe the bug

Cannot remove custom enchantments on the grindstone, even when this feature is enabled in config.yml.

```settings:
  # If true, grindstones will remove custom enchants from items and return a small amount of XP.
  grindstones-remove-custom-enchants: true
```

It is however, possible to disenchant if a vanilla enchant is also on the item. But this causes another bug:

https://github.com/GC-spigot/AdvancedEnchantments/issues/4164

### How to reproduce

Apply custom enchant to sword. Drop in grindstone. No item is available on the disenchant side.

### "/ae plinfo" link

https://paste.md-5.net/larufiyuco

**Comment by ThomasWega** [comment]
Will finally be fixed soon, because minecraft and spigot added a proper functioning way to do this.

**Comment by ThomasWega** [comment]
Will be fixed next update. Sorry for the wait
