### ISSUE TITLE
Could not pass event BlockBreakEvent to AdvancedEnchantments v9.7.11

### ISSUE THREAD

**Issue by DraGoNixS** [GC-spigot/AdvancedEnchantments#4167]
### Describe the bug

When i use certain enchant this message appear and the enchant doesn't work

### How to reproduce

Fresh installed on my server. Just restart and enchant  

### Screenshots / Videos

https://pastebin.com/B2uMC4L5

### "/ae plinfo" link

https://paste.md-5.net/ufuwanoqig

### Server Log

https://pastebin.com/B2uMC4L5

**Comment by GC-spigot** [comment]
Fixed
