### ISSUE TITLE
[dupe] with the black scrolls

### ISSUE THREAD

**Issue by Rcorcho6** [GC-spigot/AdvancedEnchantments#4168]
### Describe the bug

When using the black scrolls on the items it infinitely removes the enchantments or sometimes you remove them but somehow they remain in hidden lore but the tool still has them and in this way it does not allow you to place the book that I removed because it still detects it as position

### How to reproduce

when you try to remove enchant with the black scroll

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/86140264/a06c5060-c106-4b85-8b7b-ee14829e1802

### "/ae plinfo" link

https://paste.md-5.net/eciwuzipuh

**Comment by rayhandestian** [comment]
I've also got multiple reports from my players that this can happens while using AE version 9.7.10 & 9.7.11.
But weirdly I cannot reproduce the dupe bug.

**Comment by Rcorcho6** [comment]
> Hey! Can you try the latest version? We can't reproduce this unfortunately. Would you be able to show an item with custom enchants, then disenchanting it until it get to this state? Any errors in console?

I don't get an error in the console, it just takes out books infinitely

**Comment by Rcorcho6** [comment]
> Hey! Can you try the latest version? We can't reproduce this unfortunately. Would you be able to show an item with custom enchants, then disenchanting it until it get to this state? Any errors in console?

I don't get an error in the console, it just takes out books infinitely

**Comment by Rcorcho6** [comment]
> I've also got multiple reports from my players that this can happens while using AE version 9.7.10 & 9.7.11.
> But weirdly I cannot reproduce the dupe bug.

Well, I did everything with the video evidence if I remember correctly.

**Comment by Rcorcho6** [comment]
> I've also got multiple reports from my players that this can happens while using AE version 9.7.10 & 9.7.11.
> But weirdly I cannot reproduce the dupe bug.

Well, I did everything with the video evidence if I remember correctly.

**Comment by Rcorcho6** [comment]
Furthermore, this is an error that I have been experiencing since before yesterday's update, when I recorded I had the latest update, even the scrolls were useful, right now I must publish another report that when they die Sacred scrolls items are duped
