### ISSUE TITLE
low tps due to MiningTrigger.onBlockBreak [possible incompatibility with conditionalevents]

### ISSUE THREAD

**Issue by Rcorcho6** [GC-spigot/AdvancedEnchantments#4169]
### Describe the bug

The use of trench and some use of enchantments causes the server to lose its tps causing lag and crashes on the server, AE consumption has reached up to 40% which causes delay on the server

### How to reproduce

our users mine and when they mine followed by 2 or 3 players with a 3x3 or 5x5 trench it causes this terrible lag effect, reaching the tps to 6 or server crash causing progress losses on the server

### "/ae plinfo" link

https://paste.md-5.net/hupubukoli

### Server Log

https://spark.lucko.me/R7Jpb21sgr

**Comment by ThomasWega** [comment]
It is an incompatibility with ConditionalEvents. Create an issue on their github and tell them to ignore BlockBreakEvents with metadata `blockbreakevent-ignore`. That should fix this issue
