### ISSUE TITLE
Force Glow not working

### ISSUE THREAD

**Issue by SolaceGlowhead** [GC-spigot/AdvancedEnchantments#4170]
### Describe the bug

Force-glow: true

Doesn't appear to be working and making the custom items (blackscroll, removal scroll etc..) glow.

Running most recent version of AE, and no errors on console.

Server version 1.20.4

### How to reproduce

N/A

### Screenshots / Videos

![Screenshot 2024-04-06 143751](https://github.com/GC-spigot/AdvancedEnchantments/assets/166248288/1802e344-510a-4692-8112-8303374a5ab4)

### "/ae plinfo" link

https://paste.md-5.net/udijocovuh

**Comment by GC-spigot** [comment]
Hi! We're aware of this problem and we are working on a fix. There's no proper way to make items glow right now without weird hacks that could glitch the gameplay. Thanks for the report, we'll make sure to hurry up!
