### ISSUE TITLE
Trench Enchantment Error

### ISSUE THREAD

**Issue by xMarnel** [GC-spigot/AdvancedEnchantments#4171]
### Describe the bug

Trench was working before the latest update 9.7.12 but after the update it somehow stopped working.

### How to reproduce

Enchant trench on pickaxe and try to mine stone

### "/ae plinfo" link

https://paste.md-5.net/iwobocifod

### Server Log

https://mcpaste.io/a19d37aabed2cd35

**Comment by ThomasWega** [comment]
It's the McMMO changing their classes. Not our fault, but will be fixed in the next version!
