### ISSUE TITLE
NoClassDefFoundError (API)

### ISSUE THREAD

**Issue by AKcel222** [GC-spigot/AdvancedEnchantments#4173]
### Describe the bug

I tried to implement the api via compileOnly and dependend source plugin from advancedenchantments in the plugin.yml
But somehow it says the error from the Title, I also tried to use in my build.gradle "implementation".

### How to reproduce

Update API ?

### Screenshots / Videos

![grafik](https://github.com/GC-spigot/AdvancedEnchantments/assets/73002105/c8ba4f5a-42e3-40b2-95ea-c0f4a5487133)

### "/ae plinfo" link

https://paste.md-5.net/kumiyuweve

### Server Log

https://mcpaste.io/4e8caf67f0e314d9

**Comment by ThomasWega** [comment]
Just use the main plugin and use the api package there

**Comment by AKcel222** [comment]
okk thanks
