### ISSUE TITLE
Multiplication Enchantment Bug

### ISSUE THREAD

**Issue by xMarnel** [GC-spigot/AdvancedEnchantments#4174]
### Describe the bug

Multiplication enchantment doesn't work.

### How to reproduce

Enchant Multiplication on pickaxe and try to mine ores.

### Screenshots / Videos

![multi bug](https://github.com/GC-spigot/AdvancedEnchantments/assets/80050200/f6a49efd-5ca3-40eb-8fc2-5eb2d9d14cdf)

### "/ae plinfo" link

https://paste.md-5.net/jasaboqoje

### Server Log

https://mcpaste.io/1a0a033c3706eab4

**Comment by Skullslice** [comment]
you need to add a space after the 4 and before the : so it appears like this:
```
0 > 4 : %allow%
```

**Comment by xMarnel** [comment]
> you need to add a space after the 4 and before the : so it appears like this:
> 
> ```
> 0 > 4 : %allow%
> ```

Thank you! Some of them didn't had space from the original config.

**Comment by GC-spigot** [comment]
Sorry about that one! Fixed for conditions as well in default files
