### ISSUE TITLE
Trench mine 3x3x2 and not 3x3x1 

### ISSUE THREAD

**Issue by DraGoNixS** [GC-spigot/AdvancedEnchantments#4177]
### Describe the bug

The custom enchantement "Trench" mine a 3x3x2 area and not a 3x3x1 area. It's problematic for my tools in game

### How to reproduce

Just mine with trench

### "/ae plinfo" link

https://paste.md-5.net/epuvevicec

**Comment by DraGoNixS** [comment]
And the config   
# false = does 1 durability damage on item
  trench-do-all-durab: false

Don't work...

**Comment by GC-spigot** [comment]
Trench actually mines 3x3x3, since you break the middle block of the cube it breaks a block to every side. It's not supposed to break 3x3x1.

For the setting, some of them require a restart - have you tried that?
