### ISSUE TITLE
Soulbound doesn't work when /suicide

### ISSUE THREAD

**Issue by DraGoNixS** [GC-spigot/AdvancedEnchantments#4178]
### Describe the bug

The soulbound enchantement doesn't work when player do /suicide

### How to reproduce

Enchant soulbound

### "/ae plinfo" link

https://paste.md-5.net/esiwarosaw

**Comment by ThomasWega** [comment]
Works completely fine. Most likely an incompatibility with some other plugin. Try on clean server with only AE. When you do find which plugin causes this, feel free to create a new issue with more info
