### ISSUE TITLE
Blackscroll Dupe

### ISSUE THREAD

**Issue by xMarnel** [GC-spigot/AdvancedEnchantments#4179]
### Describe the bug

Enchantments can be blackscrolled infinitely it will show that the enchantment has been removed but if you keep on clicking the blackscroll on the item it will keep on giving you the same enchantments that it has.

### How to reproduce

The dupe only works if you previously had AdvancedEnchantments 9.7.3 and applied enchantments on any items. When we updated to AdvancedEnchantments 9.7.12 the items that had 9.7.3 enchantments can be blackscrolled infinitely it will show that the enchantment has been removed but if you keep on clicking the blackscroll on the item it will keep on giving you the same enchantments that it has.

### Screenshots / Videos

https://www.youtube.com/watch?v=-zP6FBMrSmU

### "/ae plinfo" link

https://paste.md-5.net/zetuvuvela

### Server Log

No errors on console

**Comment by leogianfagna** [comment]
I can confirm that bug. Running purpur 1.20.4

**Comment by SrMonsterYT** [comment]
(https://github.com/GC-spigot/AdvancedEnchantments/issues/4199)](https://github.com/GC-spigot/AdvancedEnchantments/issues/4199)

version: 9.7.14
server: Pufferfish version git-Pufferfish-47 (MC: 1.20.4)

**Comment by TheLaoming** [comment]
Hey, I can confirm this issue and it works pretty easily.

Normally it doesn't work for me, when it's enchanted by a book. But when I use custom_nbt from Mmoitems lets say, like this:
```
custom-nbt:
    - ae_enchantment;soulbound 1
```
 it does not recognize it and scroll is used, but enchant is still there, so you can dupe it infinitely until you have enough blackscrolls. @GC-spigot

**Comment by GC-spigot** [comment]
We've moved on from NBT, and that's the reason for this bug being here. We now use a different system, but still as a backup check for NBT but never update it - so enchants aren't removed properly. Thanks, we'll figure out a solution for next update.

**Comment by GC-spigot** [comment]
Fixed!
