### ISSUE TITLE
dupe glitch with GUI of Gkits duplicating player's inventory 

### ISSUE THREAD

**Issue by iSkyify** [GC-spigot/AdvancedEnchantments#418]
Hey GC, player reported dupe glitch with GUI of Gkits duplicating player's inventory https://www.youtube.com/watch?v=iD1BwUhdhTQ&feature=youtu.be

**Comment by GC-spigot** [comment]
will fix whenever i have access back to spigot.

**Comment by GC-spigot** [comment]
Fixed.
