### ISSUE TITLE
/enchants

### ISSUE THREAD

**Issue by Latenciiii** [GC-spigot/AdvancedEnchantments#4180]
### Describe the bug

When typing /enchants it runs the following internal error in the console.

https://mcpaste.io/f4158afd122520c0

Im running the latest version of AE and am using a paper server.jar for 1.20.4. Also using the cosmicpvp premade setup.

### How to reproduce

typing /enchants 

### "/ae plinfo" link

https://paste.md-5.net/ditufozopo

### Server Log

https://mcpaste.io/8b1c67d814c20893

**Comment by GC-spigot** [comment]
Thank you, fixed for next update!

**Comment by Latenciiii** [comment]
Thank you, apprecaite it :)
