### ISSUE TITLE
Hex/RGB Compatibility Issue

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#4182]
### Describe the bug

Was told to report an issue I am having.
When I apply a CE in anyway (book or command), the enchant appears in the lore twice. If I apply an enchant while an enchant is added, the previous lore is duplicated.

- It doesn't happen on fresh files, using AdvancedEnchantments-9.7.13.jar and paper 1.20.4

### How to reproduce

> This is the thing, I do not know what I did to cause this issue, all I know Is that I am experiencing this bug, and my ticket on discord got closed before I could log back into my account at the end of my busy daily life.

Never mind, I have found the issue. In my groups.yml file, I wanted to use hex/rgb for the colors. However, &#CB2D3E or #CB2D3E, for example, didn't return a color. So I tried a different format, `&x&r&r&g&g&b&b`, which it works in-game to display that hex/rgb color, but for some reason it forces duplicate displays of enchantment names on items. 

**So, to reproduce this duplication of the lore bug, set up a group like this:** https://mcpaste.io/00c7ae0b106f7dc5

For now, I found that the `§x§F§2§A§1§F§F` format worked for me to display a HEX/RGB code + display the enchant name only once in lore. However, this format doesn't work in the display names in /enchanter --- but the above format does???? This is just a mess overall oh my god.

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/26gaTIujRksf8t/d1337fHwY1es?invite=cr-MSxkakcsMjY3NzA3OTcs - Video of enchant's being applied - And the enchant lore's being duplicated.

https://imgur.com/a/f32qUKY - Was told to report it here.

### "/ae plinfo" link

https://paste.md-5.net/zivipaxezo

### Server Log

https://mcpaste.io/7cd70d6861d28d3d

**Comment by ThomasWega** [comment]
Totally agreed. This is a total mess. I'll try to do something about it. The only issue is that we don't want to break people's configs

**Comment by ThomasWega** [comment]
I've found a solution which should work for all cases. Use `global-color: "{#CB2D3E}"`
