### ISSUE TITLE
[API] Deprecated EnchantActivateEvent

### ISSUE THREAD

**Issue by timderspieler** [GC-spigot/AdvancedEnchantments#4184]
### Describe the bug

Hello, 

I’ve already reached out to you guys on discord, but I have been told that I should open an issue on GitHub for this.

Since the latest versions of AdvancedEnchantments, this warning appears when I start my plugin registers the Eventlistener for AdvancedEnchantments. 
`
[23:35:53] [Server thread/WARN]: [DeluxeCombat] "DeluxeCombat v1.60.4" has registered a listener for net.advancedplugins.ae.api.EnchantActivateEvent on method "public void nl.marido.deluxecombat.hooks.plugins.itemplugins.AEHook.onEnchantActivateEvent(net.advancedplugins.ae.api.EnchantActivateEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Marido, timderspieler].
`
Sadly, I haven’t found a reference to this in the wiki and on the discord nobody could tell me which event I should use instead.

This is the code I use the event for:

`

	@EventHandler(priority = EventPriority.HIGHEST)
	public void onEnchantActivateEvent(EnchantActivateEvent e) {

		if (!(e.getFirstEntity() instanceof Player)) {
			return;
		}
		
		if (!(e.getSecondEntity() instanceof Player)) {
			return;
		}
		
		Player attacker = (Player) e.getFirstEntity();
		
		String wrld = attacker.getWorld().getName();
		
		if (ListSetting.DISABLED_WORLDS.getValue().contains(wrld)) {
			return;
		}
		
		Player victim = (Player) e.getSecondEntity();
		
		if (getPlugin().getCombatUtils().canCombat(victim, attacker, DamageCause.ENTITY_ATTACK)) {
			return;
		}
		
		e.setCancelled(true);
		
	}

`

It simply intervenes activating an enchantment on another player when combat is not allowed. 

Also, what I would like to mention is that the APi which is publicly available hasn’t been updated since 2021 (https://www.spigotmc.org/resources/advancedenchantments-api.76819/)

Thank you very much for your help in advance!

### How to reproduce

Start your server with the latest version of AdvancedEnchantments and register a listener with the EnchantActivateEvent.

### "/ae plinfo" link

Not needed.

**Comment by ThomasWega** [comment]
I don't think there is even an event called now. I'll implement some events and get back to you

**Comment by ThomasWega** [comment]
Actually, you can use EffectsActivateEvent in net.advancedplugins.ae.impl.effects.api

**Comment by ThomasWega** [comment]
I've also updated the wiki a bit
