### ISSUE TITLE
[AdvancedEnchantments] [STDOUT]

### ISSUE THREAD

**Issue by n0tlz** [GC-spigot/AdvancedEnchantments#4185]
### Describe the bug

[AdvancedEnchantments] [STDOUT]
This appears on my console 
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/104715109/b8981a04-77b2-41fc-ae36-a9c31f0888dc)

### How to reproduce

I have no idea it just appears on the console

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/104715109/901844fd-257b-4de8-8aa8-c4a9c9c50246)

### "/ae plinfo" link

https://paste.md-5.net/ayugigifox

### Server Log

https://mcpaste.io/91cf25ab486c6c59

**Comment by zhro** [comment]
This is filling up my log as well. It may be related to Trench.

**Comment by n0tlz** [comment]
> This is filling up my log as well. It may be related to Trench.

Have you found a fix yet on this or nah?
and yes its related to Trench

**Comment by GC-spigot** [comment]
Sorry about this, it will be fixed for next update and we'll implement changes for this to never happen again.
