### ISSUE TITLE
 old version to the new version copy error

### ISSUE THREAD

**Issue by yellrim** [GC-spigot/AdvancedEnchantments#4186]
### Describe the bug

After updating the plugin from the old version to the new version, enchantments applied to tools in the old version cause a copy error when using a blackscroll in the new version.
version 9.7.0 -> version 9.7.13

https://github.com/GC-spigot/AdvancedEnchantments/assets/93649193/f2c923b8-d990-4c89-bab6-40ffe572b917

### How to reproduce

After updating the plugin from the old version to the new version, enchantments applied to tools in the old version cause a copy error when using a blackscroll in the new version.
version 9.7.0 -> version 9.7.13

### "/ae plinfo" link

/ae plinfo skiPlugins

**Comment by GC-spigot** [comment]
Fixed!
