### ISSUE TITLE
Bug report EFFECT_STATIC

### ISSUE THREAD

**Issue by Angelsmate** [GC-spigot/AdvancedEnchantments#4187]
### Describe the bug

There is a bug that when you put on armor that requires having the same enchantment on all 4 pieces of armor (HELMET, CHEST, LEGGINGS, BOOTS), it doesn't give you the effect correctly unless you do it by putting on the armor with Shift + Click left.

### How to reproduce

The issue works with the following example configuration:

vitalidad:
  display: 'Vitalidad'
  description: Obtienes el efecto de vida extra | You get healt boost effect
  applies-to: Armor
  type: EFFECT_STATIC
  group: ULTIMATE
  applies:
    - ALL_ARMOR
  levels:
    '1':
      conditions:
        - '%has enchantment in HELMET of vitalidad% = true : %allow%'
        - '%has enchantment in CHESTPLATE of vitalidad% = true : %allow%'
        - '%has enchantment in LEGGINGS of vitalidad% = true : %allow%'
        - '%has enchantment in BOOTS of vitalidad% = true : %allow%'
      effects:
        - POTION:HEALTH_BOOST:3

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/163351996/d4d949e2-84ee-429b-a812-64ddbd9d4b11

### "/ae plinfo" link

https://paste.md-5.net/owifagiyim

**Comment by GC-spigot** [comment]
So the problem is with this setup - condition checks if **current** item in e.g. helmet has enchant, while the helmet hasn't been applied yet theoretically in inventory, just being clicked on that slot. This might not be possible to set up right now with how it all works :/
