### ISSUE TITLE
(API) Cencel event not working on EnchantApplyEvent

### ISSUE THREAD

**Issue by Pingu-Io** [GC-spigot/AdvancedEnchantments#4188]
### Describe the bug

If I try to setCancelled(true) the event EnchantApplyEvent it works (it will be cancelled) only if it is the first time an enchant is applied to an item. If the item already has an enchantment on it the event won't be cancelled. Considering applying it with a book.

### How to reproduce

For example if the item has no enchantment on it and I apply "ExampleEnchantment" with a book and I listen to EnchantApplyEvent I can set the event cancelled with no problem and the enchant won't be applied but if the same item already has "ExampleEnchantment" and I apply it with a book and listen to the event the event won't be cancelled and the item will receive "ExampleEnchantment II".

### "/ae plinfo" link

Not needed.

**Comment by ThomasWega** [comment]
Will be fixed in the upcoming updates!
