### ISSUE TITLE
Tools take damage with TP_DROPS @Block action, even when another plugin cancels all item durability loss events at priority = highest.

### ISSUE THREAD

**Issue by BigScary** [GC-spigot/AdvancedEnchantments#4189]
### Describe the bug

my players aren't supposed to take tool durability damage in their home areas, i do this with a custom plugin. it has been working perfectly for months. yesterday i installed AE, and two players are now reporting that their items are taking durability damage with use when they have an advanced enchantment on them. whether it's specific to mining enchantments or not i am unsure.

### How to reproduce

in another plugin:

@EventHandler(ignoreCancelled = true, priority = EventPriority.HIGHEST)
	public void onPlayerItemDamgae(PlayerItemDamageEvent event) {
event.setCancelled(true);}

apply TP_DROPS mining enchantment to a tool (there's one example in the default pack)
break a bunch of blocks with the tool, note they go into your inventory, indicates enchantment is working

expected: no durability loss to item.
actual: item loses durability.

my wild guess is you guys are not firing a PlayerItemDamage event and checking its cancellation status before modifying item durability? or maybe you have your handlers set at "highest" or "monitor" and are un-cancelling the event? the latter seems very unlikely.

### "/ae plinfo" link

https://paste.md-5.net/wiyebociki

**Comment by ThomasWega** [comment]
From now on we call PlayerItemDamageEvent. Should work fine now. Just wait for the update!
