### ISSUE TITLE
2 small issues

### ISSUE THREAD

**Issue by So1ene** [GC-spigot/AdvancedEnchantments#419]
- Telepathy is once again removing all the items in a shulker box
- Enchant slot adding scrolls aren't exclusive to their tier (ie: Simple enchant slot scroll still allows a Heroic enchant to be added)

**Comment by GC-spigot** [comment]
2nd - not supposed to be.
1st - will look into it whenever I have access back to spigot.

**Comment by GC-spigot** [comment]
@So1ene for 1st - does the shulker box break or just get it's items removed? This used to be an issue previously but from my testing right now it still cannot be broken.

**Comment by So1ene** [comment]
Seems like it's just the items
