### ISSUE TITLE
Custom enchantments (like Trench) do not work with McMMO

### ISSUE THREAD

**Issue by GJ-Euphory** [GC-spigot/AdvancedEnchantments#4190]
### Describe the bug

Custom enchantments (like Trench) do not work with McMMO

It only works if they are blocks placed by me, but it doesn't work if they are made by the world or by an external plugin (RealMines, nothing out of this world, they are vanilla minerals).

### How to reproduce

It happens when I try to mine the minerals. The plugin blocks the enchantment and stops working and co-existing with McMMO

### Screenshots / Videos

https://mcpaste.io/7bb9849b0e07f12b

### "/ae plinfo" link

https://paste.md-5.net/amasewukut

**Comment by ThomasWega** [comment]
Should be fixed in newer versions

**Comment by GJ-Euphory** [comment]
You're right, if it works, it looks like I'll be forced to update
