### ISSUE TITLE
Issue with the use of 40% and 35% black-scroll to any enchantment book.

### ISSUE THREAD

**Issue by Drock09** [GC-spigot/AdvancedEnchantments#4191]
### Describe the bug

This issue is happening with black scroll (particularly if we use 40% black scroll) on every enchantment book 
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/105316777/71988cc4-3343-4a7f-8f56-1bbc6e20268a)

### How to reproduce

I have provided the video 
just look how Sprits VIII gets converted to IX

### Screenshots / Videos

[Video.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/14959542/Video.zip)

### "/ae plinfo" link

https://paste.md-5.net/zagofaboru.css

**Comment by GC-spigot** [comment]
Should be solved on new update in an hour :)
