### ISSUE TITLE
This plugins GUI is being impacted by Head Database plugin.

### ISSUE THREAD

**Issue by TheRealBlitz** [GC-spigot/AdvancedEnchantments#4192]
### Describe the bug

AdvancedEnchantments GUIs are being impacted by 'Head Database' Plugin: https://www.spigotmc.org/resources/head-database.14280/

From my troubleshooting and testing, it seems the Head Database plugin is cancelling GUI click events.

These events it is cancelling are the actions:
- Confirm enchanter purchase
- Use a gkit
- Download a premade config
- etc

I have a ticket with the head database developer. I am reaching out to see if we can have some collaboration to assist the other developer to troubleshoot as they do not have access to this plugin to test.

Please let me know how you would like to proceed.

### How to reproduce

Latest Version of Head Database and AdvancedEnchantments.

Interact with the GUI's in the advancedEnchantments.
GUI Clicks to change pages work fine, it is just the final clicks that action other items.

### Screenshots / Videos

![gkit](https://github.com/GC-spigot/AdvancedEnchantments/assets/140232769/184dc4a3-8e56-4fad-a1a6-35fe9184f4c8)
![EnchanterGUI](https://github.com/GC-spigot/AdvancedEnchantments/assets/140232769/27872e5e-5e0a-466e-8cc4-87f5a6af1fa2)

### "/ae plinfo" link

https://paste.md-5.net/tezavudecu

### Server Log

https://mcpaste.io/813886faf71dc343

**Comment by GC-spigot** [comment]
Hey! It sounds like it's an issue on their end not correctly detecting their clicks and cancelling interaction of our inventory, they must solve it for our menus to work. If they don't fix it please reach out to us and we'll then contact them ourselves. Thanks!

**Comment by TheRealBlitz** [comment]
Hi, yes I am aware of this.
My request is if it is okay to provide the plugin to the other developer so they can test and fix the issue.

**Comment by GC-spigot** [comment]
Yes that's alright :)
