### ISSUE TITLE
 Slot Increaser Plugin Issue

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#4193]
### Describe the bug

The slot increaser item within the plugin appears to be malfunctioning. Despite applying it to an item, it fails to increase the enchantment limit as expected. Even after attaching the slot increaser item to an item, the enchantment limit remains unchanged, preventing players from adding additional enchantments.
This issue significantly hampers gameplay, as players are unable to benefit from the intended functionality of the slot increaser item. Immediate attention to rectify this bug is necessary.

### How to reproduce

Obtain the slot increaser item within the plugin.
Select any item to which you intend to apply the slot increaser.
Apply the slot increaser item to the selected item.
Attempt to add extra enchantments to the item.
Notice that the enchantment limit remains unaffected, and additional enchantments cannot be applied.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/75163645/4e5d0a4a-f21e-4f4f-a1e8-f8caac81ea9e

### "/ae plinfo" link

https://paste.md-5.net/bododuqijo

**Comment by ThomasWega** [comment]
Are you sure you are not on the maximum of increased slots?
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/17bd6bbb-eb1f-41fb-a2b2-91d51a5d4d6e)

It works completely fine for me. What if you create new items and enchant again? Does that happen only with old items you've had before you've updated AE?
