### ISSUE TITLE
Error description of enchantments

### ISSUE THREAD

**Issue by TopicflyOffi** [GC-spigot/AdvancedEnchantments#4194]
### Describe the bug

Hello, I'm reaching out to you regarding issue #4092 which was closed after a fix, but it's still not working. The problem persists with the latest version of the plugin.

**Summary:** Place the placeholder %desc% at the top in the enchantments description, while keeping the description at the bottom. (File: customcommands.yml)

### How to reproduce

Place the placeholder %desc% at the top in the 'customcommands.yml' configuration file, and the description will remain at the bottom of the displayed item.

### Screenshots / Videos

Current screen of the issue: https://i.goopics.net/5nq1ga.png
Configuration : https://i.goopics.net/1na8d9.png

### "/ae plinfo" link

https://paste.md-5.net/iyecepedoy

**Comment by ThomasWega** [comment]
Hey! It's fixed, but the update hasn't been released yet. I'll make sure to get this released soon. I'll leave this ticket open for now and let you know

**Comment by TopicflyOffi** [comment]
The problem is partly solved, the placeholder %desc% is correctly used in the 'enchantment-info' category. However, it still bugs on the page where all the enchantments of a category are displayed (https://i.goopics.net/bgdh7q.png). 

It is located in the customcommands.yml file under the 'enchantments:' category (https://i.goopics.net/b3i82a.png).

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Sorry for the inconvinience
