### ISSUE TITLE
Enchantment group names are not displayed in the certain menus

### ISSUE THREAD

**Issue by beachvisitor** [GC-spigot/AdvancedEnchantments#4195]
### Describe the bug

Enchantment group names are not displayed in the "Enchant" and "Enchantments" menus (AdvancedEnchantments/menus/customcommands.yml). When I use %group%, %group-name% or any other PAPI placeholder in that menus, they are not parsed. It's really terrible, I can't show players what type of enchantment they're looking at.

### How to reproduce

.

### "/ae plinfo" link

https://paste.md-5.net/ejoxovexaw

**Comment by ThomasWega** [comment]
Should be fixed in next update!
