### ISSUE TITLE
AE soulbound interferes with soulbound slimefun 

### ISSUE THREAD

**Issue by AlexLG2908** [GC-spigot/AdvancedEnchantments#4196]
### Describe the bug

AE soulbound interferes with SlimeFun soulbound, causing the slimefun soulbound rune not to be applied to an item. Even if the AE soulbound is not used, it still causes the slimefun soulbound to not work.

### How to reproduce

.

### Screenshots / Videos

![WhatsApp Image 2024-04-14 at 10 28 39 (1)](https://github.com/GC-spigot/AdvancedEnchantments/assets/167010522/7dfa82d9-b2ce-4f37-97f0-053792936536)
![WhatsApp Image 2024-04-14 at 10 28 39](https://github.com/GC-spigot/AdvancedEnchantments/assets/167010522/f73c7d3d-1ba7-45a2-a9a8-581b84dea28e)
https://www.youtube.com/watch?v=Fi467M1q_NY
### "/ae plinfo" link

https://paste.md-5.net/usuyitowah

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
