### ISSUE TITLE
Potion Effect stays active when switching items out

### ISSUE THREAD

**Issue by ElysiumSMP** [GC-spigot/AdvancedEnchantments#4197]
### Describe the bug

If you have a two different items enchanted with the `POTION` effect (especially when infinite, say one armour piece with `RESISTANCE` and one with `GLOWING`) and the `EFFECT_STATIC` trigger, you can stack those effects by hotswapping between the two armour pieces by `right-clicking` an armour piece in your main hand.

### How to reproduce

1. Have two armour pieces, each enchanted with a `POTION` effect using an `EFFECT_STATIC` trigger. Two different potion effects must be enchanted.
2. Wear one, and right-click the other to hotswap the armour piece.
3. The effects are now stacked permanently.

### "/ae plinfo" link

https://paste.md-5.net/hiwuteziwu

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
