### ISSUE TITLE
dupe books

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#4199]
### Describe the bug

when I updated the plugin to version 9.7.14, it seems that the enchantments continue after removal and if I use blackscroll, it keeps removing the enchantment infinitely.

### How to reproduce

update to version 9.7.14 and use the scroll

### Screenshots / Videos

Bug: https://www.youtube.com/watch?v=Gu1UPzA0nxA

### "/ae plinfo" link

https://paste.md-5.net/bobodejune.css

**Comment by GC-spigot** [comment]
Fixed!
