### ISSUE TITLE
REPEATING type enchants get permanently activated with Armor sets 

### ISSUE THREAD

**Issue by fortcraftch** [GC-spigot/AdvancedEnchantments#4200]
### Describe the bug

I have the same problem as in the issue #4156, but this time it seems to be caused by armor sets activateing effects and it also seems to happen in normal armor pieces as it is shown with the iron armor on the video

### How to reproduce

This is the armor set I have used

name: '&4&lArmadura Encuartizada'
material: NETHERITE
settings:
  equipped:
  - '&a&l(!) &aHas activado el set Encuartizado!'
  unequipped:
  - '&c&l(!) &cHas desactivado el set Encuartizado!'
items:
  helmet:
    name: '&7• &f&lCASCO &7| §x§5§0§F§F§F§1&lE§x§4§9§F§0§F§2&lN§x§4§1§E§1§F§4&lC§x§3§A§D§2§F§5&lU§x§3§3§C§3§F§6&lA§x§2§C§B§4§F§7&lR§x§2§4§A§5§F§9&lT§x§1§D§9§6§F§A&lI§x§1§6§8§7§F§B&lZ§x§0§F§7§8§F§C&lA§x§0§7§6§9§F§E&lD§x§0§0§5§A§F§F&lO
      &7•'
    lore:
    - ''
    - '&7Set Encuartizado'
    - ''
    - '&7• Velocidad II'
    - ''
    enchants: # Supports AdvancedEnchantments CE
      - protection:6
      - unbreaking:5
      - aquatic:1
  chestplate:
    name: '&7• &f&lPECHERA &7| §x§5§0§F§F§F§1&lE§x§4§9§F§0§F§2&lN§x§4§1§E§1§F§4&lC§x§3§A§D§2§F§5&lU§x§3§3§C§3§F§6&lA§x§2§C§B§4§F§7&lR§x§2§4§A§5§F§9&lT§x§1§D§9§6§F§A&lI§x§1§6§8§7§F§B&lZ§x§0§F§7§8§F§C&lA§x§0§7§6§9§F§E&lD§x§0§0§5§A§F§F&lA
      &7•'
    lore:
    - ''
    - '&7Set Encuartizado'
    - ''
    - '&7• Velocidad II'
    - ''
    enchants: # Supports AdvancedEnchantments CE
      - protection:6
      - unbreaking:5
  leggings:
    name: '&7• &f&lLEGGINS &7| §x§5§0§F§F§F§1&lE§x§4§9§F§1§F§2&lN§x§4§3§E§4§F§3&lC§x§3§C§D§6§F§5&lU§x§3§5§C§8§F§6&lA§x§2§F§B§A§F§7&lR§x§2§8§A§D§F§8&lT§x§2§1§9§F§F§9&lI§x§1§B§9§1§F§A&lZ§x§1§4§8§3§F§C&lA§x§0§D§7§6§F§D&lD§x§0§7§6§8§F§E&lO§x§0§0§5§A§F§F&lS
      &7•'
    lore:
    - ''
    - '&7Set Encuartizado'
    - ''
    - '&7• Velocidad II'
    - ''
    enchants: # Supports AdvancedEnchantments CE
      - protection:6
      - unbreaking:5
      - devolveralremitente:1
  boots:
    name: '&7• &f&lBOTAS &7| §x§5§0§F§F§F§1&lE§x§4§9§F§1§F§2&lN§x§4§3§E§4§F§3&lC§x§3§C§D§6§F§5&lU§x§3§5§C§8§F§6&lA§x§2§F§B§A§F§7&lR§x§2§8§A§D§F§8&lT§x§2§1§9§F§F§9&lI§x§1§B§9§1§F§A&lZ§x§1§4§8§3§F§C&lA§x§0§D§7§6§F§D&lD§x§0§7§6§8§F§E&lA§x§0§0§5§A§F§F&lS
      &7•'
    lore:
    - ''
    - '&7Set Encuartizado'
    - ''
    - '&7• Velocidad II'
    - ''
    enchants: # Supports AdvancedEnchantments CE
      - protection:6
      - unbreaking:5
      - fortuito:1
events:
  EFFECT_STATIC:
    chance: 100
    effects:
    - POTION:SPEED:1
    cooldown: 0

And this is one of the enchantments

caminoglow:
  display: '§x§F§F§0§0§C§4L§x§F§9§0§0§C§6u§x§F§3§0§0§C§7c§x§E§C§0§0§C§9e§x§E§6§0§0§C§Ac§x§E§0§0§0§C§Ci§x§D§A§0§0§C§Dt§x§D§4§0§0§C§Fa§x§C§D§0§0§D§0s §x§C§7§0§0§D§2p§x§C§1§0§0§D§3o§x§B§B§0§0§D§5r §x§B§5§0§0§D§6l§x§A§E§0§0§D§8o§x§A§8§0§0§D§9s §x§A§2§0§0§D§Bs§x§9§C§0§0§D§Cu§x§9§6§0§0§D§Ee§x§8§F§0§0§D§Fl§x§8§9§0§0§E§1o§x§8§3§0§0§E§2s'
  description: Crea un camino de particulas al llevar unas botas equipadas.
  applies-to: Botas
  type: REPEATING
  group: COSMETICO
  settings:
    not-applyable-with:
      - 'caminollamas'
  applies:
    - ALL_BOOTS
  levels:
    '1':
      time: 0.1
      effects:
        - PARTICLE:GLOW:1:0.2 @Add{x=0.0,y=0.3,z=0.0}

### Screenshots / Videos

https://photos.app.goo.gl/1A6tKhZmsHpCYqNs8

### "/ae plinfo" link

https://paste.md-5.net/filosagita

**Comment by ThomasWega** [comment]
Update your plugin...

**Comment by ThomasWega** [comment]
Sorry for the late response, but please send the enchantment formatted. This is unreadable https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by fortcraftch** [comment]
Hi sorry for the format (I didn't know how to fix it XD) here you have it a little more readable.

caminoglow:
  display: 'caminoglow'
  description: Crea un camino de particulas al llevar unas botas equipadas.
  applies-to: Botas
  type: REPEATING
  group: COSMETICO
  settings:
     not-applyable-with:
       - 'caminollamas'
  applies:
       - ALL_BOOTS
  levels:
    '1':
       time: 0.1
       effects:
         - PARTICLE:GLOW:1:0.2 @add{x=0.0,y=0.3,z=0.0}

**Comment by ThomasWega** [comment]
Hey! We did some adjustments to improve your armor events logic. Can you test again with the latest AE please?
