### ISSUE TITLE
FALL_DAMAGE

### ISSUE THREAD

**Issue by GoneWhiteBunny** [GC-spigot/AdvancedEnchantments#4201]
### Describe the bug

trigger "FALL_DAMAGE" does not work when crashing into a wall on elytra

### How to reproduce

display: '%group-color%dsadqwd'
  description: ''
  applies-to: ''
  type: FALL_DAMAGE
  group: DEFAULT
  applies:
    - ELYTRA
  levels:
    '1':
      effects:
        - 'CANCEL_EVENT'

### "/ae plinfo" link

https://paste.md-5.net/apeyacoceb

**Comment by ThomasWega** [comment]
Not really a fall damage. I've added ELYTRA_FLY_DAMAGE trigger for you
