### ISSUE TITLE
Custom items cant be enchanted doesnt work.

### ISSUE THREAD

**Issue by sennby** [GC-spigot/AdvancedEnchantments#4203]
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138246331/6d95edb7-eccd-4050-94d7-d5855ea167ec)
I had a custom helmet that is paper.
I add paper to the list
reboot reload whatever, doesnt work, cant enchant it with custom enchants, normal enchants no problem.
I also tried kelp with another helmet.

### How to reproduce

Get a piece of paper and add it to the list for helmet and try to enchant it with custom enchants. You cant.

### "/ae plinfo" link

https://paste.md-5.net/mecaqoniqa

**Comment by ThomasWega** [comment]
This is not the correct list. If you want this to work you'll need to apply the PAPER to specific items like so:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/b873107e-8d75-47b6-96ba-761c03f9a438)
