### ISSUE TITLE
Telepathy Enchantment Feature Request.

### ISSUE THREAD

**Issue by AidenJules** [GC-spigot/AdvancedEnchantments#4207]
### Describe the bug

![image_2024-04-19_224110189](https://github.com/GC-spigot/AdvancedEnchantments/assets/126147686/ae913e3e-4fd4-416e-b2df-d527ac78c56e)

I asked the Developer of the Extra Storage plugin if he could make it so that the advanced enchantments telepathy ability could put items into your storage, and he said to make that possible your plugin would need some sort of catch even to get the items and cancel it from going to their inventory. I was wondering if this is something you guys can make.

### How to reproduce

Null

### Screenshots / Videos

![image_2024-04-19_224226128](https://github.com/GC-spigot/AdvancedEnchantments/assets/126147686/170ada0f-d32f-4053-a2e7-ad5a824c2be2)

### "/ae plinfo" link

null

**Comment by ThomasWega** [comment]
Hey! I think you might be able to use `EffectsActivateEvent` and get the items by `task.getBuilder().getDrops()`. You can check if TP_DROPS was used with `task.getBuilder().getDrops().getSettings().isAddToInventory()`
