### ISSUE TITLE
DOUBLE_JUMP EFFECT

### ISSUE THREAD

**Issue by lDoomerl** [GC-spigot/AdvancedEnchantments#4209]
### Describe the bug

Double jump, that's all. Just an enchat for the boots. 

### How to reproduce

Double space

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/136274899/0b6a5a55-0e61-4038-a315-fe0f4123376f)

### "/ae plinfo" link

-

**Comment by GC-spigot** [comment]
Hi, this is planned at some point but not any time soon, we will get to this idea in the future :)
