### ISSUE TITLE
Enchant errors

### ISSUE THREAD

**Issue by IamWTbro** [GC-spigot/AdvancedEnchantments#421]
My enchant
violentoutrage:
  display: '%group-color%Violent Outrage'
  description: |-
    Drastically slow down players nearby
    you while dealing insane damage to them.
  applies-to: Swords
  type: ATTACK
  group: MASTERY
  applies:
  - ALL_SWORD
  settings:
    required-enchants:
    - 'outrage'
    removed-enchants:
    - 'outrage'
    removeable: false
  levels:
    '1':
      chance: 30
      cooldown: 105
      effects:
      - 'PARTICLE:FLAME:20:2 <aoe> radius=5 target=damageable </aoe>'
      - 'FLAME:2 <aoe> radius=5 target=damageable </aoe>'      
      - 'POTION:SLOW:3:100 <aoe> radius=5 target=damageable </aoe>'
      - 'ADD_HARM:3 <aoe> radius=5 target=damageable </aoe>'
      - 'PLAY_SOUND:WITHER_DEATH'
      - 'BLOOD <aoe> radius=5 target=damageable </aoe>'
      - 'MESSAGE:&c&l** VIOLENT OUTRAGE ** <aoe> radius=5 target=damageable </aoe>'
      - 'WAIT:40'
      - 'PARTICLE:FLAME:20:2 <aoe> radius=5 target=damageable </aoe>'
      - 'FLAME:2 <aoe> radius=5 target=damageable </aoe>'      
      - 'POTION:SLOW:3:100 <aoe> radius=5 target=damageable </aoe>'
      - 'ADD_HARM:3 <aoe> radius=5 target=damageable </aoe>'
      - 'PLAY_SOUND:ZOMBIE_PIG_ANGRY'
      - 'BLOOD <aoe> radius=5 target=damageable </aoe>'
      - 'MESSAGE:&c&l** VIOLENT OUTRAGE ** <aoe> radius=5 target=damageable </aoe>'
      - 'WAIT:40'
      - 'PARTICLE:FLAME:20:2 <aoe> radius=5 target=damageable </aoe>'
      - 'FLAME:2 <aoe> radius=5 target=damageable </aoe>'      
      - 'POTION:SLOW:3:100 <aoe> radius=5 target=damageable </aoe>'
      - 'ADD_HARM:3 <aoe> radius=5 target=damageable </aoe>'
      - 'PLAY_SOUND:ZOMBIE_PIG_ANGRY'
      - 'BLOOD <aoe> radius=5 target=damageable </aoe>'
      - 'MESSAGE:&c&l** VIOLENT OUTRAGE ** <aoe> radius=5 target=damageable </aoe>'
      - 'WAIT:40'
      - 'PARTICLE:FLAME:20:2 <aoe> radius=5 target=damageable </aoe>'
      - 'FLAME:2 <aoe> radius=5 target=damageable </aoe>'      
      - 'POTION:SLOW:3:100 <aoe> radius=5 target=damageable </aoe>'
      - 'ADD_HARM:3 <aoe> radius=5 target=damageable </aoe>'
      - 'PLAY_SOUND:ZOMBIE_PIG_ANGRY'
      - 'BLOOD <aoe> radius=5 target=damageable </aoe>'
      - 'MESSAGE:&c&l** VIOLENT OUTRAGE ** <aoe> radius=5 target=damageable </aoe>'
      - 'WAIT:20'
 
 The error:
 
 
 
 
 
> [00:58:00 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "2 "
> [00:58:00 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:348)
> [00:58:00 INFO]: [AdvancedEnchantments] Extra info: effect[PARTICLE:FLAME, 20, 2 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:00 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:00 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "2 "
> [00:58:00 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:549)
> [00:58:00 INFO]: [AdvancedEnchantments] Extra info: effect[FLAME:2 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:00 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:00 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "120 "
> [00:58:00 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:249)
> [00:58:00 INFO]: [AdvancedEnchantments] Extra info: effect[POTION:SLOW, 3, 120 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:00 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:00 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "3 "
> [00:58:00 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:466)
> [00:58:00 INFO]: [AdvancedEnchantments] Extra info: effect[ADD_HARM:3 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:00 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "2 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:549)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[FLAME:2 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "2 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:348)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[PARTICLE:FLAME, 20, 2 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "120 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:249)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[POTION:SLOW, 3, 120 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "3 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:466)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[ADD_HARM:3 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "2 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:348)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[PARTICLE:FLAME, 20, 2 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "2 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:549)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[FLAME:2 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "120 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:249)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[POTION:SLOW, 3, 120 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "3 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:466)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[ADD_HARM:3 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "2 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:348)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[PARTICLE:FLAME, 20, 2 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "2 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:549)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[FLAME:2 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "120 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:249)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[POTION:SLOW, 3, 120 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
> [00:58:01 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "3 "
> [00:58:01 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:466)
> [00:58:01 INFO]: [AdvancedEnchantments] Extra info: effect[ADD_HARM:3 ]; enchant[violentoutrage]; mc[188]; ae[5.5.5]
> [00:58:01 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report

**Comment by GC-spigot** [comment]
http://prntscr.com/ndb6dh
