### ISSUE TITLE
MAJOR BEDROCK SUPPORT

### ISSUE THREAD

**Issue by gamingjovi** [GC-spigot/AdvancedEnchantments#4210]
### Describe the bug

You will go to enchanter menu on a Bedrock Account/geyser

### How to reproduce

1. do /ce
2. press on fabled enchants (ON BEDROCK/GEYSER)
3. you get it for half the price if you click on a barrier block

### "/ae plinfo" link

https://paste.md-5.net/uyobafuhag

**Comment by ThomasWega** [comment]
Interesting. This is mainly java plugin and we cannot guarantee bedrock support out of the box. Especially when it's an issue like this, which is a pretty weird one. If we could get some input from Geyser team on why this could be happening, that'd be great
