### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by hiiamken** [GC-spigot/AdvancedEnchantments#4211]
### Describe the bug

My server is lagging due to advancedenchantment. I don't use enchantments like telepathy or trench
I tried deleting the plugin and the tps returned to normal 20

https://spark.lucko.me/75Kag5vw4I

### How to reproduce

I dont know

### "/ae plinfo" link

https://paste.md-5.net/hesepuqene

**Comment by hiiamken** [comment]
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142149960/d795f48d-dc1f-48df-8ac8-364dee101501)
https://spark.lucko.me/x3qG6TOPo6
can someone take a look, thanks

**Comment by ThomasWega** [comment]
My guess is it's actually a combination of AE and some different plugins and we force eachother to run events multiple times over and over. If you could please go one by one through your plugins and see if the AE performance improves with the specific plugin removed, that'd be great. I doubt AE will have this performance issue on it's own.

**Comment by hiiamken** [comment]
https://spark.lucko.me/HCeyNIXkXY

> My guess is it's actually a combination of AE and some different plugins and we force eachother to run events multiple times over and over. If you could please go one by one through your plugins and see if the AE performance improves with the specific plugin removed, that'd be great. I doubt AE will have this performance issue on it's own.


I have partially fixed it (removed some related plugins), can you take a look at this spark?
https://spark.lucko.me/HCeyNIXkXY

**Comment by ThomasWega** [comment]
Looks okay now! There still is a bit of a performance that we think we can improve, but it shouldn't cause any issues at all
