### ISSUE TITLE
black scrolls do not take out all the books

### ISSUE THREAD

**Issue by Rcorcho6** [GC-spigot/AdvancedEnchantments#4213]
### Describe the bug

It turns out that when trying to remove the enchantments with the black scrolls, they remove most of the book but another one does not detect them and leaves them there, it is necessary to remove them with the command /ae unenchat

### How to reproduce

When you try to remove the enchantments, I have version 9.7.15 because the next version crashed the entire modality. Maybe the report was from when the version came out, except that I had an emergency and I couldn't report in time.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/86140264/2f079878-ecfa-40a3-b51e-dc81aa04822e

### "/ae plinfo" link

https://paste.md-5.net/edolemamih

**Comment by GC-spigot** [comment]
We're looking into this and will continue to improve this, but this is happening because we switched from NBT to PDC. We'll figure out a solution with upcoming updates.
