### ISSUE TITLE
GRIEF DEFENDER COMPATIBLITY

### ISSUE THREAD

**Issue by ianflig** [GC-spigot/AdvancedEnchantments#4214]
### Describe the bug

players with enchantment like "poison" or "thor"can damage the grief defender owner standing in claim with "pvp" flag denied, i would like if you can add support for that plugin, there are more enchantments than can damage the player in safe zone (claim protection) but i don't remember which ones right now

### How to reproduce

hit a player with poison or other damage enchantment like these in a grief defender claim protection with pvp flag denied, and they can still damage them

### "/ae plinfo" link

https://paste.md-5.net/umalikejin

**Comment by ThomasWega** [comment]
Next update you will have %is damageable% placeholder, which should fix your trouble
