### ISSUE TITLE
The "rage" enchantment does not work

### ISSUE THREAD

**Issue by emiliogvt** [GC-spigot/AdvancedEnchantments#4215]
### Describe the bug

I was trying the ienchantment and it just doesn't work, so, in support told me to try changing the code

 

### How to reproduce

Original code 
    '6':
      chance: 100
      conditions:
      - '%attacker combo% > 3 : %stop%'
      cooldown: 5
      effects:
      - DO_HARM:%combo% @Victim
      - BLOOD @Victim
      
I elimineted the part combo 
Original code 
    '6':
      chance: 100
      conditions:
      - '%attacker % > 3 : %stop%'
      cooldown: 5
      effects:
      - DO_HARM:%combo% @Victim
      - BLOOD @Victim   
      
  The problem is that the original code doesn't work, and if I remove the "combo" part it does a lot of life damage. 

### "/ae plinfo" link

https://paste.md-5.net/gelapohipo

### Server Log

https://mcpaste.io/2687f5650ad5bc61

**Comment by ThomasWega** [comment]
please send the enchantments formatted
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code
