### ISSUE TITLE
Items no longer achieve a 100% success rate

### ISSUE THREAD

**Issue by Mithranduil** [GC-spigot/AdvancedEnchantments#4216]
### Describe the bug

If I drag the magic dust with a 10% success rate onto a book, for example, the success rate of the book also increases by 10%.

However, the destruction rate remains the same, which is why I end up with a total value of over 100%.

Example:

Book with 35% chance of success and 65% destruction rate.
Now I add a dust with a 10% chance of success.
The new values should be: 45% success rate, 55% destruction rate.

However, the values are now 45% success rate and 65% destruction rate.

### How to reproduce

use it like described in the last section

### "/ae plinfo" link

https://paste.md-5.net/fabuwayase

**Comment by ThomasWega** [comment]
Hey! Are you trying this out with newly created book or some old one back from older AE versions? Do you also mind sharing a video showcase? Just tested it out and seems to work fine
