### ISSUE TITLE
Burn Doesn't Work With Crossbows Suddenly?

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#4217]
### Describe the bug

Makes no sense, previous update it worked fine, but now it doesn't? I feel like updates need more testing, not trying to be rude ofc, since a lot of old things keep breaking, such as arrow hit for a teleport bow, and now something simple as this. Not complaining since I know bugs normally get fixed decently fast, but it's a little irritating to update and have old issues reappear. Below doesn't work

### How to reproduce

fireshot:
  display: '%group-color%CustomEnchant'
  description: "CustomEnchant"
  applies-to: 'Crossbows'
  type: 'ATTACK;ATTACK_MOB;SHOOT;SHOOT_MOB'
  group: 'DEV'
  applies:
    - CROSSBOW
  levels:
    '1':
      effects:
        - 'BURN:5 @Victim'

### "/ae plinfo" link

https://paste.md-5.net/opatuvuqoj

**Comment by DuplexLake** [comment]
Just looked into it, seems damage_increase doesn't work either. seems like crossbows entirely don't work :/

**Comment by ThomasWega** [comment]
Hey! I've tried the burn on mobs with using crossbow and it worked fine. Does it not work only for players or for everything for you? We haven't made any changes for these effects, so I am uncertain why this might be happening
