### ISSUE TITLE
EAT trigger doesn't work

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#4218]
### Describe the bug

Eating doesn't do anything when trigger is eat

### How to reproduce

saturating:
  display: '%group-color%CustomEnchant'
  description: "CustomEnchant"
  applies-to: 'Helmets'
  type: 'EAT'
  group: 'DEV'
  applies:
    - ALL_HELMET
  levels:
    '1':
      chance: 100
      effects:
        - 'CONSOLE_COMMAND:say test'

### "/ae plinfo" link

https://paste.md-5.net/alasodobev

**Comment by ThomasWega** [comment]
Seems to work completely fine.

**Comment by ThomasWega** [comment]
I'll keep this open for now. Feel free to send a video showcase or send more info about your testings

**Comment by DuplexLake** [comment]
> I'll keep this open for now. Feel free to send a video showcase or send more info about your testings

seems they are all working suddenly, maybe server when testing everything had an improper startup or something, my apologies, there was an issue with ARROW_HIT not working which I did do a lot more testing on, so I'll make a report in the near future on that after some more testing.

**Comment by ThomasWega** [comment]
Glad to hear that! Closing this now
