### ISSUE TITLE
Fishing Rods Don't Work As Well As No Example For Min Or Max Catch Time

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#4219]
### Describe the bug

Catching A Fish Doesn't Work At All Which Just Doesn't Make Sense

### How to reproduce

autorepair:
  display: '%group-color%CustomEnchant'
  description: "CustomEnchant"
  applies-to: 'Fishing Rods'
  type: 'CATCH_FISH'
  group: 'DEV'
  applies:
    - FISHING_ROD
  levels:
    '1':
      chance: 100
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:5

### "/ae plinfo" link

https://paste.md-5.net/alasodobev

**Comment by ThomasWega** [comment]
Works completely fine
