### ISSUE TITLE
Axe Enchant Doesn't Work In Latest Update, But Was Perfectly Fine 2 Updates Prior?

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#4221]
### Describe the bug

Below lines work perfectly in AE ver 9.6.15, but doesn't work at all in 9.6.17?

### How to reproduce

treecap:
  display: '%group-color%CustomEnchant'
  description: "CustomEnchant"
  applies-to: 'Pickaxes'
  type: 'MINING'
  group: 'DEV'
  applies:
    - ALL_AXE
  levels:
    '1':
      effects:
        - BREAK_TREE @Block

### "/ae plinfo" link

https://paste.md-5.net/alasodobev

**Comment by ThomasWega** [comment]
Works absolutely fine
