### ISSUE TITLE
plugin is killing my server performance

### ISSUE THREAD

**Issue by matipoirierg** [GC-spigot/AdvancedEnchantments#4223]
### Describe the bug

https://spark.lucko.me/NJD5PRW7KK

### How to reproduce

I'm just using the plugin with the default enchantments.

### "/ae plinfo" link

https://paste.md-5.net/eviqireruv

**Comment by ThomasWega** [comment]
Can you try removing HuskTowns plugin and retest?

**Comment by matipoirierg** [comment]
I can't since it´s the land protection plugin, and I won't be able to do it whitout whitelisting the server. If there are no players playing then it's impossible to reproduce the lag. I'm getting the HuskTowns lag fixed tho.

**Comment by ThomasWega** [comment]
The only performance hit from us is calling new events for blocks broken with trench, veinminer etc.., which we need to do. It can cycle with other plugins and that sometimes causes performance hit. So we cannot do anything with this unless you are able to figure out which plugin it cycles with
