### ISSUE TITLE
Bug with vanilla & custom enchant in anvil

### ISSUE THREAD

**Issue by NoltoxGit** [GC-spigot/AdvancedEnchantments#4225]
### Describe the bug

In an anvil, it's possible to combine any vanilla enchantment without adding the enchantment to the item.

Instead, the anvil should be marked with a cross indicating that it is impossible to combine the two together.

### How to reproduce

1. Take any enchantable item (e.g. : Bow)
2. Put a compatible enchantment on it in an anvil (e.g. :  Power 5)
3. Add a normally incompatible enchantment (e.g. : Protection 4)

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/75265787/32b7a367-2f0d-4976-88c1-948fe5a1d846

### "/ae plinfo" link

https://paste.md-5.net/afeqapudih

### Server Log

https://mclo.gs/lZsZkYf

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
