### ISSUE TITLE
holywhitescroll is broken

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#4226]
### Describe the bug

The white scroll either does not work at all or will save the item. A black scroll cannot remove enchantments if they have a white scroll on them.

### How to reproduce

Just put a white scroll on the item and die NOT FROM COMMANDS. This is not a problem with other plugins, namely yours. Version 9.6.16 - WORKS FINE.

### Screenshots / Videos

1) https://youtu.be/W6k6Wgi7sIw
2) https://youtu.be/dbjgd7Ia5yY
3) https://youtu.be/iK4IJXKi-eU

### "/ae plinfo" link

https://paste.md-5.net/ifugeqarox

**Comment by wundertraume** [comment]
?

**Comment by ThomasWega** [comment]
The blackscroll will be fixed next update! Sorry for the inconvinience

**Comment by ThomasWega** [comment]
If you still have issues with the white scroll please create a new issue with a video (the ones you've sent are private) and provide more info. I'll fix it very swiftly
