### ISSUE TITLE
The slotincreaser does not allow you to remove the enchantment

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#4227]
### Describe the bug

The slotincreaser does not allow you to remove the enchantment

### How to reproduce

check video

1) 2 AE Enchant book
2) 1 blackscroll
3) 3 slotincreaser 

### Screenshots / Videos

https://youtu.be/xzJ2Wsunx68

### "/ae plinfo" link

https://paste.md-5.net/pijesasise

**Comment by wundertraume** [comment]
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/118831819/eebe499a-6132-4c0c-8792-6b53b2bc2c81)

**Comment by ThomasWega** [comment]
Will be fixed in the next update
