### ISSUE TITLE
pickaxe breaking with trench

### ISSUE THREAD

**Issue by Paceski** [GC-spigot/AdvancedEnchantments#4228]
### Describe the bug

pickaxe breaks when trying to mine with trench

### How to reproduce

mine with trench, pickaxe goes boom and error in console

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/82279522/e0482df0-b8fe-41a9-99c3-92e94bb25a70

### "/ae plinfo" link

https://paste.md-5.net/unalawafap

### Server Log

https://paste.md-5.net/etacedaxoh.cs

**Comment by Paceski** [comment]
seems like going back to 9.7.15 fixes this issue. please start being more consistent, this made a lot of issues on our server.

**Comment by SliderKP** [comment]
same error.

**Comment by Paceski** [comment]
> same error.

It seems to be related to itemsadder together with AE, but it's mostly AE's fault here I believe.

**Comment by Paceski** [comment]
I haven't updated itemsadder in a while, only have updated ae.

**Comment by sennby** [comment]
same issue
also seems if you have unbreakable enchant it still breaks.

**Comment by Paceski** [comment]
> same issue also seems if you have unbreakable enchant it still breaks.

It's unreal how this isn't fixed yet.

**Comment by sennby** [comment]
Yeah i have been having fun with stuff breaking as well.

Are shulkers disappearing for you by chance as well?

**Comment by SliderKP** [comment]
all the enchantments for pickaxe with itemsadder skin has the same problem with durability

**Comment by GC-spigot** [comment]
Seems like this is an itemsadder bug, I'll talk with IA developer

**Comment by Paceski** [comment]
> Seems like this is an itemsadder bug, I'll talk with IA developer

I haven't updated IA at all it's a bit out of date due to issues, I don't think it's that, you most likely did code changes within this in your end

**Comment by sennby** [comment]
If it was an IA issue then downgrading your plugin wouldnt of fixed it.......

**Comment by GC-spigot** [comment]
It's a specific reason, we do durability damage for each block instead of stacking it and doing it at once, and after a couple of blocks IA returns wrong item's custom durability values and plugin thinks item doesn't have durability anymore.

**Comment by sennby** [comment]
is this fixed yet, still waiting for this to fix before updating.

**Comment by SliderKP** [comment]
> is this fixed yet, still waiting for this to fix before updating.

I'm also waiting, but it doesn't seem like it's going to be resolved anytime soon, let's hope so.

**Comment by ThomasWega** [comment]
We are actively working at it. Fix will come soon

**Comment by ThomasWega** [comment]
Would also like to point out that it's not issue on our part but on itemsAdder, so we are doing our best to find a workaround

**Comment by mastachef** [comment]
So has this been fixed?

**Comment by sennby** [comment]
One day ill be able to update again.. one day

**Comment by Paceski** [comment]
> One day ill be able to update again.. one day :D

Would attempt to fix it, but since the source isn't public, I can't make a pull request. You know how it is...

**Comment by sennby** [comment]
ONE DAY ILL BE ABLE TO UPDATE AGAIN.. ONE DAY :D

**Comment by Paceski** [comment]
they said soon bro

**Comment by SliderKP** [comment]
Any can say if solved ?

**Comment by sennby** [comment]
> Any can say if solved ?

nothings been said or done to my knowledge

**Comment by ThomasWega** [comment]
Hey guys! I have actually tried it on latest AE and ItemsAdder 3.6.4-release-2 and it seems to be working fine. Can you try updating everything and retesting?

**Comment by ThomasWega** [comment]
Thank you

**Comment by SliderKP** [comment]
Similar bug in armors in 1.21 @ThomasWega
