### ISSUE TITLE
detonate (trench) issues

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#423]
The following has been tested and recreated on the following:
Paper spigot 1.13.2
#621 (Updated 4/16/2019)

AdvanceEnchantments 5.5.5

Tested on a test server which only had: EssentialsX, Multiverse Core, Vault.

-Detonate cancels reforged.
-Detonate cancels silk touch.
-Detonate breaks blocks that the tool shouldn't be able to break.
-Detonate and autosmelt don't work together (just none of it dropped)
-Detonate doesn't work with experience

*Config is on default settings, so these are all the enchants that loaded in on default.

**Comment by GC-spigot** [comment]
will look into whenever i have access back to my spigot.
