### ISSUE TITLE
FishTrak Duplicating Fish Count Bug

### ISSUE THREAD

**Issue by Xidle** [GC-spigot/AdvancedEnchantments#4230]
### Describe the bug

When using a FishTraker on a fishing pole, they tracker duplicates into multiple counters like so.

Fishtrak Bug Example:
- Fishtrak Fish Caught: 1
- Fishtrak Fish Caught: 1
- Fishtrak Fish Caught: 1

That is what the lore ends up looking like on the fishing pole every fish caught.

### How to reproduce

Fishtrak Bug Example:
- Fishtrak Fish Caught: 1 < 1st fish caught
- Fishtrak Fish Caught: 1 < 2nd fish caught           < Lore on fishing pole with 1 fishtraker applied
- Fishtrak Fish Caught: 1 < 3rd fish caught

### Screenshots / Videos

![Fishtrak DUPE bug](https://github.com/GC-spigot/AdvancedEnchantments/assets/71620837/f7157a79-ca94-4669-b338-20e7190de512)

### "/ae plinfo" link

https://paste.md-5.net/ecipufixip

### Server Log

https://mcpaste.io/ac69109a9c10844c

**Comment by GC-spigot** [comment]
Update, already fixed
