### ISSUE TITLE
Server crashes when generating loot

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4233]
### Describe the bug

Server crashes when generating random loot

### How to reproduce

Generate random loot

### "/ae plinfo" link

https://paste.md-5.net/dexupedafu

### Server Log

https://mcpaste.io/e4ef3857f00c069e

**Comment by GC-spigot** [comment]
Should be solved

**Comment by ArmonicPvP** [comment]
not solved
