### ISSUE TITLE
EXP is completely broken with Sweeping Edge kills

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4235]
### Describe the bug

EXP does not work properly at all when mobs are killed with sweeping edge and the orb combines. The below formula was activated 10 times after killing 24 skeletons. %level% = 4. I received 18 EXP. Skeletons at minimum drop 5 EXP. 5 * (1.0 + 0.4 * 4) * 18 = 234. I should be receiving 234 EXP at minimum, but I am receiving 18. This is consistent after testing it 30 times. If I instead spam click the sword, I will receive the expected amount almost every time.

- EXP:<math>%exp% * (1.0 + 0.4 * %level%)</math> @Victim

I believe I reported this issue years ago, so I am surprised this still exists. Maybe it just reappeared, and it needs to be fixed again.

### How to reproduce

1. Use this enchantment on Paper 1.20.4:

inquisitive:
  display: '%group-color%Inquisitive'
  description: Chance to increase EXP drops from mobs
  applies-to: Swords
  type: KILL_MOB
  group: RARE
  applies:
    - ALL_SWORD
  levels:
    '1':
      chance: 12
      effects:
        - EXP:<math>%exp% * (1.0 + 0.25 * %level%)</math> @Victim
    '2':
      chance: 24
      effects:
        - EXP:<math>%exp% * (1.0 + 0.3 * %level%)</math> @Victim
    '3':
      chance: 36
      effects:
        - EXP:<math>%exp% * (1.0 + 0.35 * %level%)</math> @Victim
    '4':
      chance: 48
      effects:
        - EXP:<math>%exp% * (1.0 + 0.4 * %level%)</math> @Victim
        - MESSAGE:Activated inquisitive
        
2. Kill mobs with sweeping edge 

3. Collect EXP orb

### "/ae plinfo" link

https://paste.md-5.net/safuyipuze

**Comment by ArmonicPvP** [comment]
Btw: 

https://github.com/GC-spigot/AdvancedEnchantments/issues/3190
https://github.com/GC-spigot/AdvancedEnchantments/issues/1435
https://github.com/GC-spigot/AdvancedEnchantments/issues/1325

**Comment by ThomasWega** [comment]
> its true, everything was ok but now it drops a small amount really

Which version did it work in and on what exact version it broke please?

**Comment by ArmonicPvP** [comment]
> > its true, everything was ok but now it drops a small amount really
> 
> Which version did it work in and on what exact version it broke please?

i don't know which version it last worked in. for me it has never worked since I've used the plugin

**Comment by ThomasWega** [comment]
We didn't have the best math for exps, and it was sometimes off by a bit. Should be fixed in the next updated. I know why this issue actually happens. It's because we spawn many exp orbs and Spigot merges them together incorrectly and they lose value. I cannot do anything about this unfortunately. You can set merge-radius of exp to -1 in spigot.yml and that will fix it, but it might hurt performance
