### ISSUE TITLE
custom-enchants-cause-glow，There is an issue with this configuration

### ISSUE THREAD

**Issue by jackchen0318** [GC-spigot/AdvancedEnchantments#4237]
### Describe the bug

When the item does not have any vanilla enchantments, it doesn't apply a glow to the item once a custom enchantment is applied.

### How to reproduce

When applying a custom enchanted book to an item that is not enchanted with vanilla, the item does not glow

### "/ae plinfo" link

https://paste.md-5.net/yenavilowi

**Comment by GC-spigot** [comment]
Hey, we are aware of this. There is no proper way to make items glow now and this will be solved 1.20.6+ versions only.
