### ISSUE TITLE
Guardians still activating despite removing from chestplate

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4239]
### Describe the bug

Removed Guardians from chestplate (applied with /ae enchant guardians 10, removed with /ae enchant guardians 10) and it still activates, despite being removed from the chestplate

### How to reproduce

I have a soul tracker on the chestplate and below is the enchantment that is currently on it (Soulforged) and the enchantment that was on it (Guardians)

guardians:
  display: '%group-color%Guardians'
  description: Chance to summon Iron Golems
  applies-to: Chestplates
  type: DEFENSE;DEFENSE_MOB;DEFENSE_MOB_PROJECTILE;DEFENSE_PROJECTILE
  settings:
    showActionBar: true
  group: RARE
  applies:
    - ALL_CHESTPLATE
  levels:
    '1':
      chance: 6
      cooldown: 8
      effects:
        - GUARD:IRON_GOLEM:8:1 @Victim
    '2':
      chance: 9
      cooldown: 8
      effects:
        - GUARD:IRON_GOLEM:8:1 @Victim
    '3':
      chance: 13
      cooldown: 8
      effects:
        - GUARD:IRON_GOLEM:8:1 @Victim
    '4':
      chance: 14
      cooldown: 8
      effects:
        - GUARD:IRON_GOLEM:8:1 @Victim
    '5':
      chance: 16
      cooldown: 9
      effects:
        - GUARD:IRON_GOLEM:8:1 @Victim
    '6':
      chance: 17
      cooldown: 10
      effects:
        - GUARD:IRON_GOLEM:8:2 @Victim
    '7':
      chance: 18
      cooldown: 12
      effects:
        - GUARD:IRON_GOLEM:8:2 @Victim
    '8':
      chance: 20
      cooldown: 12
      effects:
        - GUARD:IRON_GOLEM:8:3 @Victim
    '9':
      chance: 22
      cooldown: 15
      effects:
        - GUARD:IRON_GOLEM:8:3 @Victim
    '10':
      chance: 24
      cooldown: 15
      effects:
        - GUARD:IRON_GOLEM:8:4 @Victim

soulforged:
  display: '%group-color%Soulforged'
  description: Chance to collect souls when attacked
  applies-to: Armor
  type: DEFENSE;DEFENSE_MOB;DEFENSE_MOB_PROJECTILE;DEFENSE_PROJECTILE
  group: SOUL
  applies:
    - ALL_ARMOR
  levels:
    '1':
      chance: 15
      cooldown: 3
      effects:
        - ADD_SOULS:1 @Victim
    '2':
      chance: 30
      cooldown: 2
      effects:
        - ADD_SOULS:<random number>1-2</random number> @Victim
    '3':
      chance: 45
      cooldown: 1
      effects:
        - ADD_SOULS:<random number>1-3</random number> @Victim
        
        
        

### "/ae plinfo" link

https://paste.md-5.net/imetozurel

**Comment by ArmonicPvP** [comment]
Checking NBT data shows it still exists, re-running the command just says it was removed again. The lore is gone, NBT data is not.

**Comment by ArmonicPvP** [comment]
Also appears that it activates with it being in my inv, not even wearing. It's in a shulker box and activates.

**Comment by GC-spigot** [comment]
> Also appears that it activates with it being in my inv, not even wearing. It's in a shulker box and activates.

We don't check inside shulker boxes, so that cannot be the case. We switched from NBT to PDC so NBT may still be there, even though the enchant is not on item. We'll look into this.

**Comment by ThomasWega** [comment]
Try the latest. Works fine for me and the NBT and PDC is removed

**Comment by ArmonicPvP** [comment]
The initial bug I reported is fixed. I will open up tickets for the other issues I now notice.

**Comment by ArmonicPvP** [comment]
After further testing, this is still a problem on items which the enchants were removed from before the update. 
![2024-05-14_16 46 09](https://github.com/GC-spigot/AdvancedEnchantments/assets/24983808/156c4932-20c8-4a2f-b042-8999743988ba)

**Comment by ThomasWega** [comment]
Can you please provide the exact way to reproduce this? With the older version - new version. When to remove the item etc.

**Comment by ArmonicPvP** [comment]
> Can you please provide the exact way to reproduce this? With the older version - new version. When to remove the item etc.

this isn't happening anymore after upgrading to 1.20.6 it seems
