### ISSUE TITLE
Error with some effects

### ISSUE THREAD

**Issue by SliderKP** [GC-spigot/AdvancedEnchantments#4240]
### Describe the bug

in the img you can see the error i get when i try to use a item with this enchant, i tried with @Victim and without and not working, i tried with Decrease and Negate and not work

enchant Tank works fine with:
      effects:
      - DECREASE_DAMAGE:2 @Victim
      
      and i tried to remove the condition in my enchant and not work too

### How to reproduce

enchant to reproduce:

dragonskin:
  display: '%group-color%Dragonskin'
  description: |-
    &f&oTu armadura obtiene propiedades de la piel de dragon
    &f&oObtienes Resistencia y Resist al fuego al agacharte
    &f&oRequiere el encantamiento Obsidianshield.
  applies-to: Armadura
  group: ARCANOS
  type: EFFECT_STATIC
  applies:
  - ALL_ARMOR
  settings:
    require-enchants:
    - obsidianshield:1
    removed-enchants:
    - obsidianshield
    removeable: false
  levels:
    '1':
      chance: 100
      cooldown: 0
      effects:
      - DECREASE_DAMAGE:2 @Victim
      - POTION:FIRE_RESISTANCE:20000:1 @Victim

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/6493041/74f38cfb-f499-450a-b783-7b9e26727532)

### "/ae plinfo" link

https://paste.md-5.net/awevuqoqoz

### Server Log

https://mcpaste.io/87f517f5fe47cdbf

**Comment by GC-spigot** [comment]
DECREASE_DAMAGE does not work with EFFECT_STATIC, this works with PVP triggers only (e.g. ATTACK, DEFENSE). Same with potions that have length, EFFECT_STATIC is only for permanent potion effects
