### ISSUE TITLE
Error Entity Damage Event

### ISSUE THREAD

**Issue by TylorTurner** [GC-spigot/AdvancedEnchantments#4241]
### Describe the bug

Console error
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/133236597/a8c31a96-b0e8-4ef2-8f38-2e67529a4b63)

### How to reproduce

Console Error

### "/ae plinfo" link

https://paste.md-5.net/iqelepefaw

**Comment by GC-spigot** [comment]
Solved
