### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by Muzammil201** [GC-spigot/AdvancedEnchantments#4244]
### Describe the bug

Hello Please tell me how to make slot increaser same for all ces , i dont want diffrent slot increasers for all type of groups , can u tell in whcih file and which line of code (number) is it so i can edit it , i cant find it

### How to reproduce

e

### Screenshots / Videos

e

### "/ae plinfo" link

hpp

### Server Log

e

**Comment by GC-spigot** [comment]
It's the same for all groups, just names are different in case you want different group to give a different number of new enchantment slots. Slots are global, not per-group.
