### ISSUE TITLE
Mass error log

### ISSUE THREAD

**Issue by kingevolved** [GC-spigot/AdvancedEnchantments#4245]
### Describe the bug

Currently, none of the enchants work and cause a mass error log. I've a mcpaste

### How to reproduce

Im not sure what's causing the error to produce. But anytime I use a tool or armor that has a enchant on it, the error occurs. It is also not letting me take off any gear with effect enchants. EX: i can't remove my boots with Gears I on them, or my Helmet with Aquatic I on it

### Screenshots / Videos

https://pastebin.com/kM0L8X1j

### "/ae plinfo" link

https://paste.md-5.net/xanunekiji

### Server Log

https://mcpaste.io/6979699911c1b982

**Comment by GC-spigot** [comment]
Solved
