### ISSUE TITLE
DEFENSE abilities activate as long as item is in inventory

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4246]
### Describe the bug

Defense abilities will activate as long as the item is in the inventory. This makes no sense, since you can just put a bunch of defensive abilities in a shulker box and it counts as an activation.

### How to reproduce

Put a defense ability in your inventory and watch it activate

### "/ae plinfo" link

https://paste.md-5.net/dinakazepa

**Comment by ThomasWega** [comment]
Hey! If you could please provide a video and config you use, that'd be great. I am not able to replicate this

**Comment by ArmonicPvP** [comment]
This issue is happening because of a different bug. I couldn't reproduce either.

**Comment by ArmonicPvP** [comment]
https://paste.md-5.net/pikaneveha
![2024-05-14_16 46 09](https://github.com/GC-spigot/AdvancedEnchantments/assets/24983808/66aa46a1-2a3d-40f1-896f-b52b3b582e8e)
