### ISSUE TITLE
BUG ADD_DURABILITY_ARMOR:-10

### ISSUE THREAD

**Issue by KingFouXx** [GC-spigot/AdvancedEnchantments#4247]
### Describe the bug

Hello, I'm reporting a bug with the AdvancedEnchantments plugin. Plugin info: https://paste.md-5.net/siticawele. The event ADD_DURABILITY_ARMOR:-10 @Victim doesn't seem to work and appears to repair the opponent's armor.

### How to reproduce

demonforged:
  display: '%group-color%Demonforged'
  description: |-
    Augmente la perte de durabilité sur
    l'armure de votre ennemi.
  applies-to: Swords
  type: ATTACK
  group: ELITE
  applies:
  - ALL_SWORD
  levels:
    '1':
      cooldown: 6
      chance: 8
      effects:
      - ADD_DURABILITY_ARMOR:-2 @Victim
    '2':
      cooldown: 6
      chance: 12
      effects:
      - ADD_DURABILITY_ARMOR:-2 @Victim
    '3':
      cooldown: 6
      chance: 15
      effects:
      - ADD_DURABILITY_ARMOR:-2 @Victim
    '4':
      cooldown: 1 #6
      chance: 100 #17
      effects:
      - ADD_DURABILITY_ARMOR:-10 @Victim
      - MESSAGE:&a** Démonforged IV **

### Screenshots / Videos

https://www.mediafire.com/file/ucnvbh89wupnxdr/Minecraft__1.20.1_-_Multijoueur_serveur_tiers_2024-05-03_17-40-45.mp4/file

### "/ae plinfo" link

https://paste.md-5.net/siticawele

**Comment by GC-spigot** [comment]
This works as intended, @Victim in this case is the player who got damaged, @Attacker is the player which attacked (using the enchant). Using negative values will repair the armor, using positive (above 0) will damage the armor.
