### ISSUE TITLE
HolyWhiteScroll BUG

### ISSUE THREAD

**Issue by KingFouXx** [GC-spigot/AdvancedEnchantments#4248]
### Describe the bug

Hello, I'm here to report a bug with the AdvancedEnchantments plugin. Plugin info: https://paste.md-5.net/siticawele. The HOLYWHITESCROLL doesn't seem to work. It can be applied and given via the command /ae giveitem holywhintescroll player 1, but upon death, the item is not retained, and the parchment is not removed from the item.

Note: Please send me a direct message on Discord for the video. I apologize, I couldn't upload it otherwise. "kingfoux"

### How to reproduce

   holywhitescroll:
    type: PAPER
    id: 0
    custom-model-data: 0
    force-glow: false
    name: '&6&lParchemin blanc sacré'
    lore:
    - '&7Une récompense légendaire qui peut'
    - '&7une fois appliqué aux armures/armes'
    - '&6donné 100% de chances de ne pas perdre'
    - '&7cette objet béni à la mort.'
    messages:
      applied:
      - '&7Vous avez appliqué avec succès &6&lParchemin Blanc Saint'
    settings:
      lore-display: '&e&l*&f&lHOLY&e&l* &f&lPROTECTED'
      # Keep holywhitescroll equipped to item even after death
      keep-after-death: false

 holy-whitescrolls-world-blacklist:
  - exemple_world

### Screenshots / Videos

https://www.mediafire.com/file/b0c1upy5i8smee7/Minecraft__1.20.1_-_Multijoueur_serveur_tiers_2024-05-03_17-39-08.mp4/file

### "/ae plinfo" link

https://paste.md-5.net/siticawele

**Comment by GC-spigot** [comment]
From the video it's not clear how you die, are you killing the player with commands? Killing with commands item is not retained, only with PVP/PVE. I've tested and it works now.

**Comment by KingFouXx** [comment]
@GC-spigot With each death, even in PvP, the blessed item falls to the ground and does not get removed from the inventory.
