### ISSUE TITLE
HolyWhiteScroll needs to be extended...

### ISSUE THREAD

**Issue by digital-r** [GC-spigot/AdvancedEnchantments#425]
Feature suggestion for HolyWhiteScroll:
- Add to compatible items shields, tridents, fishing rods, flint-and-steels and shears. Many servers use custom-modelled items and weapons based on last two items, so, it will be great option, if we can protect this items too.
- Add levels, which can acts as "use counts" or (better) "percent chance" for Holy White Scroll. I mean "Holy white scroll V" will save protected item five times, before burns-out, or can keep itself on item with chance 100%, while "Holy white scroll I" will keep itself on item with chance 10% only.

**Comment by GC-spigot** [comment]
Currently it's designed with CosmicPvP's style. You can add compatible items by editing http://prntscr.com/nnlr7o list, but the second suggestion will not be added, sorry!
