### ISSUE TITLE
Detonate enchant not counting into minecraft statistics

### ISSUE THREAD

**Issue by Gfieldd** [GC-spigot/AdvancedEnchantments#4250]
### Describe the bug

When mining with a pickaxe that has the detonate enchant, the "Times Mined" statistic in the statistics tab does not increase. This is an issue as this is an incompatibility between Minecraft and AdvancedEnchants, and we use these statistics as upgrade requirements on our server.

I see two possible ways to i would consider this "fixed", one where only the manually broken block is counted into statistics, the other where all of the broken blocks are counted into statistics. I see no reason to prefer one over the other, so i will be happy with either one.

### How to reproduce

1. Take any pickaxe
2. Apply the detonate anchant on said pickaxe. Efficiency and any other vanilla or advanced enchant can be added as well for easier testing.
3. Open the statistics tab on the pause menu, and in "Items" look for the "Times Mined" statistic for a pickaxe minable block like stone
4. Mine a noticable amount of the picked material using the previously enchanted pickaxe
5. Open the statistics tab again, and notice that the "Times Mined" statistics has not increased at all for said material

### "/ae plinfo" link

https://paste.md-5.net/afaqoyohay

**Comment by ThomasWega** [comment]
There is an option minecraft-stats-blocks-broken-count in config.yml. But you're on older version...
