### ISSUE TITLE
1.20.6 paper/pupur isn´t ready yet

### ISSUE THREAD

**Issue by Reiamsei** [GC-spigot/AdvancedEnchantments#4251]
### Describe the bug

[AdvancedEnchantments-9.8.1.jar:?] at AdvancedEnchantments-9.8.1.jar/net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.hasKey(NBTCompound.java:64 
I´m using 1.20.6 purpur 

logs are to long but I loaded up a cutout.

### How to reproduce

It happens when I try open a /enchanter item in my inventory and you can´t unequip your armor

### "/ae plinfo" link

I uninstalled it to prevent my players... so I´m sorry

### Server Log

https://mcpaste.io/e49e12ff733be4fe

**Comment by GC-spigot** [comment]
Solved for next update

**Comment by Reiamsei** [comment]
still not working.
https://mcpaste.io/c703f6e3052e4adb

**Comment by GC-spigot** [comment]
> still not working. https://mcpaste.io/c703f6e3052e4adb

It is working. 1 out of those 5 errors is related to AdvancedEnchantments, we'll fix that error for next update.

**Comment by Reiamsei** [comment]
Hey any news regarding this update?
