### ISSUE TITLE
can't unequip armor

### ISSUE THREAD

**Issue by LilBloodStayn** [GC-spigot/AdvancedEnchantments#4254]
### Describe the bug

can't unequip armor when the plugin is installed. no matter if I do a fresh install.

### How to reproduce

all I do is equip armor a few times then it's not possible to take off.

### Screenshots / Videos

https://youtu.be/1mhKuISaf0E

### "/ae plinfo" link

https://paste.md-5.net/ijiwuwiluw

### Server Log

https://mcpaste.io/3fa628dd5c7d2ce8

**Comment by GC-spigot** [comment]
Will be solved in an update today, bug with 1.20.6
