### ISSUE TITLE
1.20.6 / enchanter items wont work

### ISSUE THREAD

**Issue by Reiamsei** [GC-spigot/AdvancedEnchantments#4255]
### Describe the bug

the /enchanter items wont work.

### How to reproduce

try to use the /enchanter items

### "/ae plinfo" link

https://paste.md-5.net/ogujacawoz

### Server Log

https://mcpaste.io/c703f6e3052e4adb

**Comment by Reiamsei** [comment]
it´s the newest version from yesterday.

**Comment by GC-spigot** [comment]
Hey! I replied to you in the previous issue, I've fixed it since the reply in last 1-2 minutes :) It'll be available in an update later today, sorry about the inconvenience.
