### ISSUE TITLE
Spawner Drop Enchant

### ISSUE THREAD

**Issue by bogdanW11** [GC-spigot/AdvancedEnchantments#4258]
### Describe the bug

Can you add an enchantment that drops the spawner when it is broken? If I break a skeleton spawner to drop it on the ground with a chance.

I've used a custom enchant plugin before that had this enchant, and the players really liked it and it's even desirable. 

### How to reproduce

-

### Screenshots / Videos

-

### "/ae plinfo" link

-

### Server Log

-

**Comment by GC-spigot** [comment]
Hi! We cannot unfortunately add this without having a whole spawner system made - vanilla spawner items just do not "keep data" of spawners and most of the time placing it will result in a wrong mob.
