### ISSUE TITLE
@Aoe targeters can damage/kill mobs in claimed regions (Griefprevention)

### ISSUE THREAD

**Issue by Nightcraftop** [GC-spigot/AdvancedEnchantments#4259]
### Describe the bug

Good afternoon,
Players are able to damage/kill animals in other players protected claims using the Plummet enchant.
More specifically the @Aoe targeter can damage/kill protected animals.
These protected regions are achieved with GriefPrevention.

Example of one of the enchants that's able to achieve this:

plummet:
  display: '%group-color%Plummet'
  description: |-
    Deal damage to nearby mobs
    when taking fall damage.
  applies-to: Boots
  type: FALL_DAMAGE
  settings:
    showActionBar: true
  group: ULTIMATE
  applies:
    - ALL_BOOTS
  levels:
    '1':
      chance: 40
      effects:
        - 'ACTION_BAR:Plummet used'      
        - 'DO_HARM:3 @Aoe{radius=3,target=damageable}'
        - 'PARTICLE:FLAME:12:1 @Aoe{radius=3,target=damageable}'
        - 'PLAY_SOUND_OUTLOUD:BLOCK_ANVIL_LAND:.50:.75'
    '2':
      chance: 80
      effects:
        - 'ACTION_BAR:Plummet used'      
        - 'DO_HARM:5 @Aoe{radius=5,target=damageable}'
        - 'PARTICLE:FLAME:12:1 @Aoe{radius=5,target=damageable}'
        - 'PLAY_SOUND_OUTLOUD:BLOCK_ANVIL_LAND:.50:.75'
    '3':
      effects:
        - 'ACTION_BAR:Plummet used'      
        - 'DO_HARM:7 @Aoe{radius=8,target=damageable}'
        - 'PARTICLE:FLAME:12:1 @Aoe{radius=8,target=damageable}'
        - 'PLAY_SOUND_OUTLOUD:BLOCK_ANVIL_LAND:.50:.75'

### How to reproduce

Using the Plummet enchant, players can take fall damage in a farm to damage/kill protected animals.

### "/ae plinfo" link

https://paste.md-5.net/axutotuhih

**Comment by ThomasWega** [comment]
Any errors? We now have issues like these with Aoe https://github.com/GC-spigot/AdvancedEnchantments/issues/4260

**Comment by ThomasWega** [comment]
Should be fixed in the last update
