### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TylorTurner** [GC-spigot/AdvancedEnchantments#4260]
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/133236597/4bc6344d-e796-43d4-b411-f26baf2ff379)

### How to reproduce

Console error

### "/ae plinfo" link

https://paste.md-5.net/ifeloweqox

**Comment by ThomasWega** [comment]
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4256
