### ISSUE TITLE
Auto Reel doesn't give correct mcMMO XP

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4262]
### Describe the bug

Auto Reel doesn't give correct mcMMO XP. When auto reel activates, XP is extremely low. When reeling manually when it doesn't, XP is normal.

### How to reproduce

experience.yml from mcMMO:

https://hastebin.com/share/omamesebar.yaml

enchant:

autoreel:
  display: '%group-color%Auto Reel'
  description: Chance to automatically reel in when getting a bite
  applies-to: Fishing Rod
  type: BITE_HOOK
  group: UNCOMMON
  settings:
    showActionBar: true
  applies:
    - FISHING_ROD
  levels:
    '1':
      chance: 25
      effects:
        - AUTO_REEL
    '2':
      chance: 50
      effects:
        - AUTO_REEL
    '3':
      chance: 75
      effects:
        - AUTO_REEL
    '4':
      effects:
        - AUTO_REEL

### "/ae plinfo" link

https://paste.md-5.net/ezexorusip

**Comment by ThomasWega** [comment]
Should be fixed in the next update!
