### ISSUE TITLE
Failed to activate effects as advancedEffect is null or invalid

### ISSUE THREAD

**Issue by Reiamsei** [GC-spigot/AdvancedEnchantments#4266]
### Describe the bug

If try to break blocks with my enchantet pickaxe this happens:
[16:58:15 WARN]: [AdvancedEnchantments] ?cAdditional information: ?7Failed to activate effects as advancedEffect is null or invalid: 'BREAK',

### How to reproduce

It happens when I use this pickaxe:

### Screenshots / Videos

[
![2](https://github.com/GC-spigot/AdvancedEnchantments/assets/77484898/11ab129a-e237-4d3e-8112-d4ab76a8898b)
](url)

### "/ae plinfo" link

https://paste.md-5.net/tijirefuha

**Comment by SirJben** [comment]
Replace the effect of Obsidian Destroyer into `BREAK_BLOCK @Block`
