### ISSUE TITLE
spam error in console

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#4267]
### Describe the bug

check error

### How to reproduce

check error
[message.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/15264896/message.txt)

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/118831819/ecfc3d3a-172e-4954-a7f7-ae9a9d9e190b)

### "/ae plinfo" link

https://paste.md-5.net/qeyatulenu

**Comment by GC-spigot** [comment]
Solved next update
