### ISSUE TITLE
Compatibility with advancedclans

### ISSUE THREAD

**Issue by Olavvvv** [GC-spigot/AdvancedEnchantments#4268]
### Describe the bug

I am wanting to create an enchantment with the undamageable aoe but it has no effect, since it is not supported by the plugin in question

only works when user has /god or /vanish enabled

https://www.spigotmc.org/resources/%E2%AD%90-advanced-clans-1-8-1-20-4-%E2%AD%90-gui-based-levels-individual-statistics-banks-and-much-more.72061/

### How to reproduce

sage:
  display: '&b❤ Sage'
  description: 'Curate a vos y a tus aliados'
  applies-to: 'Weapons'
  type: RIGHT_CLICK
  group: 'ELITE'
  applies:
    - ALL_SWORD
  levels:
    '1':
      chance: 100
      cooldown: 1
      effects:
        - POTION_OVERRIDE:REGENERATION:4:50 @Self
        - POTION_OVERRIDE:REGENERATION:3:90 @Aoe{radius=10,target=undamageable}
        - PARTICLE:HEART:1:0 @Aoe{radius=10,target=undamageable}
        - MESSAGE:&9&lENCHANTS&8 » &d%attacker name%&f activó el poder de &b&lSage&f. @Aoe{radius=10,target=damageable}
        - MESSAGE:&9&lENCHANTS&8 »&f Activaste el poder de &b&lSage&f y te estás &acurando&f. @Self
        - MESSAGE:&9&lENCHANTS&8 » &fEstás siendo curado por &d%attacker name%&f. @Aoe{radius=10,target=undamageable}

### "/ae plinfo" link

latest version

**Comment by ThomasWega** [comment]
I don't understand. What are you trying to do?

**Comment by ThomasWega** [comment]
You are using undamageable. You should use damageable

**Comment by Olavvvv** [comment]
If I do that I heal the enemies, the idea is to heal my allies and members
of my clan

**Comment by ThomasWega** [comment]
I see now. Advancedclans is not handling the damage events correctly then. So not our issue, but advanced clans one
