### ISSUE TITLE
Failed to activate effect 'PARTICLE:FALLING_LAVA:5:0 <aoe> radius =4 target=damageable </aoe>'

### ISSUE THREAD

**Issue by AdwinL** [GC-spigot/AdvancedEnchantments#4269]
### Describe the bug

I got inflame on my axe, when i tried to hit someone with the axe it show that error

### How to reproduce

hitting a player with an axe with inflame

### Screenshots / Videos

![2024-05-10_15 42 07](https://github.com/GC-spigot/AdvancedEnchantments/assets/47217803/76333639-a2b9-418c-bd5c-bca0466cb706)

### "/ae plinfo" link

https://paste.md-5.net/amegowuruj

### Server Log

https://mcpaste.io/030afb03ccdbde22

**Comment by GC-spigot** [comment]
Hey, the AOE format has been changed for over a year now, you can find updated format here: https://wiki.advancedplugins.net/abilities/targets

**Comment by AdwinL** [comment]
ok thanks
