### ISSUE TITLE
Bypass of effect commands on armour

### ISSUE THREAD

**Issue by Vasito1** [GC-spigot/AdvancedEnchantments#4272]
### Describe the bug

We have an enchant that when activated gives the user a skill boost through our skills plugin. It is supposed to last for a few mins then deactivate and remove the skill boost. However when the user removes the armor that has the enchant applied after the enchant activates they will keep the boosts infinitely.

Here is the effects of the enchant:

effects:
        - 'POTION:GLOWING:1:20000 @Victim'
        - 'POTION:STRENGTH:7:20000 @Victim'
        - 'POTION:REGENERATION:7:20000 @Victim'
        - 'POTION:SATURATION:7:20000 @Victim'
        - 'POTION:RESISTANCE:3:20000 @Victim'
        - 'POTION:HEALTH_BOOST:750:20000 @Victim'
        - 'EXPLODE:10:true:false @Victim'
        - 'EXPLODE:15:true:false @Victim'
        - 'POTION:SPEED:3:20000 @Victim'
        - 'POTION:NIGHT_VISION:3:20000 @Victim'
        - 'POTION:WATER_BREATHING:3:20000 @Victim'
        - 'PLAYER_COMMAND:pp group load SuperSaiyan @Victim'
        - 'POTION:ABSORPTION:5:20000 @Victim'
        - 'ADD_HEALTH:1500 @Victim'
        - 'ADD_FOOD:100 @Victim'
        - 'NEGATE_DAMAGE:100 @Victim'
        - 'CONSOLE_COMMAND:sk modifier add %victim name% strength SuperSaiyanStrength 1750 @Victim'
        - 'CONSOLE_COMMAND:sk modifier add %victim name% health SuperSaiyanHealth 1750 @Victim'
        - 'CONSOLE_COMMAND:sk modifier add %victim name% regeneration SuperSaiyanRegeneration 1750 @Victim'
        - 'CONSOLE_COMMAND:sk modifier add %victim name% wisdom SuperSaiyanWisdom 1750 @Victim'
        - 'REPAIR @Self'
        - 'PULL_AWAY:15.0 @Attacker'
        - 'CONSOLE_COMMAND:playsound tavern:music.theme.robin master @a ~ ~ ~ 200 1 @Victim'
        - 'WAIT:18000'
        - 'PLAYER_COMMAND:pp reset %victim name% @Victim'
        - 'CONSOLE_COMMAND:sk modifier removeall %victim name% @Victim'

### How to reproduce

Create an enchant for amor using the effects above. After the enchant activates remove the armor and you will keep the skill boosts

### "/ae plinfo" link

https://paste.md-5.net/avunasibak

**Comment by ThomasWega** [comment]
What's the code for you plugin? Also send the whole enchantment please.
