### ISSUE TITLE
Grindstone Bug

### ISSUE THREAD

**Issue by WardenW7** [GC-spigot/AdvancedEnchantments#4276]
### Describe the bug

When items with custom enchantments are hotkeyd into the grindstone they do not lose their custom enchantments, yet still give the xp for the player for disenchanting.

### How to reproduce

Take an item with custome AE enchantment, use hotkey for putting it into the grindstone, disenchant, enjoy the free xp and keeping the enchantment.

### "/ae plinfo" link

https://paste.md-5.net/wexiwitagi

**Comment by ThomasWega** [comment]
Will be fixed in the next update
