### ISSUE TITLE
Wrong enchantment books are accepted by anvil if item is already enchanted

### ISSUE THREAD

**Issue by zhro** [GC-spigot/AdvancedEnchantments#4277]
### Describe the bug

Apply any enchantment to an item (vanilla or AE). It is now possible to use the wrong book on an item in the anvil.

To clarify, the enchantment does not appear on the item. But the anvil allows you to get an item on the other side, and deduct exp from you. This is wrong. The anvil should not allow this at all.

The book used in the process is destroyed, and this is not intuitive and can be confusing, if an item already has a lot of enchantments. The enchantment not being applied is not obvious.

### How to reproduce

Apply any enchantment to an item (vanilla or AE). It is now possible to use the wrong book on an item in the anvil.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/4738876/eb4ad312-fdb8-4297-bd2a-8ac5e8fbc8d6

### "/ae plinfo" link

https://paste.md-5.net/fekopuhipo

**Comment by ThomasWega** [comment]
For some reason I am not able to reproduce this. What I can see happening is that renaming the items allows you to enchant it (which I will fix), but not your exact issue.

https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/0a3c5303-c5e3-4ffd-89b1-f145022b212f

**Comment by zhro** [comment]
I still have this same problem even on the latest 9.8.8 update, exactly as demonstrated in the video.

https://paste.md-5.net/toriruwubi

I tried using a diamond sword with fire aspect and a trench book, exactly as you demonstrated, and I have the same issue as in my video. The problem exists, but I'm not certain why it's not reproducing for you.

**Comment by ThomasWega** [comment]
Can you try on completely fresh server with only latest AE?

**Comment by ThomasWega** [comment]
If you are able to find additional info, for sure create a new issue. I am however unable to do anything with it now
