### ISSUE TITLE
Improve BREAK_TREE

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4278]
### Describe the bug

BREAK_TREE has atrocious detection. It cannot reliably break down a 2x2 tree and will usually miss one of those. It also does not work half the time on 2x2 trees. Even on regular trees, it will just fail.

### How to reproduce

Use BREAK_TREE

### "/ae plinfo" link

https://paste.md-5.net/ixululenel

**Comment by ThomasWega** [comment]
Completely reworked it! Works really good now. Should not be very performance intensive as well

**Comment by ArmonicPvP** [comment]
@ThomasWega will this be live next update or is it already?

**Comment by ThomasWega** [comment]
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/7e021639-a40f-4ffc-9c6a-361c6b54fc73)
