### ISSUE TITLE
GKit GUI and Magic Dust

### ISSUE THREAD

**Issue by newbie029** [GC-spigot/AdvancedEnchantments#428]
Upgrading from ver 5.5.5 to 5.5.6
https://streamable.com/hv7vu
Player can take GKit gui to their inventory,

also I got many report after upgrading to 5.5.6 about magic dust eat book.
I have tried it but still cannot produce it. Im sure there is a bug because my staff also reporting

Server version : Paper 1.12.2 Latest Build

**Comment by GC-spigot** [comment]
Fixed both!

**Comment by newbie029** [comment]
You cool man

**Comment by ZoneRaids** [comment]
it is still doing the same thing?
