### ISSUE TITLE
Using AEAPI to detect what type of Unopened book is held

### ISSUE THREAD

**Issue by TheRealBlitz** [GC-spigot/AdvancedEnchantments#4281]
### Describe the bug

Is there an API method to check what tier a unopened enchanter book is?

### How to reproduce

N/A

### "/ae plinfo" link

N/A

**Comment by ThomasWega** [comment]
There's not, but you can check the PDC of the item
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/cc305b7c-d08c-42ae-a346-f75b60dd2c44)
