### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by HogwartsNet** [GC-spigot/AdvancedEnchantments#4283]
### Describe the bug

When the plugin is placed alone without any other plugin it works, but not always. And when I place another plugin (even just 1 more) AE stops working. I also tried placing all my other plugins first and AE last but that doesn't work either. I have the latest version and deleting the folder generated by the plugin does not work either.
I use Paper 1.20.4 and java 17

### How to reproduce

I attach two types of logs, one in which server.properties has DEBUG=true and the other error when DEBUG is false

### Screenshots / Videos

debug=true https://mcpaste.io/6785ac29e8324640
debug=false https://mcpaste.io/63fe1ae26c2699bc

### "/ae plinfo" link

error in console

**Comment by ThomasWega** [comment]
Will be fixed in the next version. Thanks for reporting
