### ISSUE TITLE
Vulcan sometimes kicks when using Trench when getting mining fatigue right before

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4284]
### Describe the bug

When getting mining fatigue 4, mining a block, and then having mining fatigue 4 wear off, trench will sometimes trigger the fast break type a cheat detection

### How to reproduce

See above

### "/ae plinfo" link

https://paste.md-5.net/imetozurel

**Comment by ThomasWega** [comment]
We already add exception for Anticheats. 
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/3ed23f69-76a5-4e45-8352-c5c2ea789022)
Not sure if there's something more we can do. This is probably more on Vulcan
