### ISSUE TITLE
Anvils do not support horse armor

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#4285]
### Describe the bug

In vanilla, anvils are able to enchant horse armor in creative mode (see https://minecraft.wiki/w/Horse_Armor#Enchanting). This is no longer possible with AdvancedEnchantments installed. It would also be great if custom enchantments had horse armor support!

### How to reproduce

Attempt to enchant horse armor with any compatible enchant (e.g. Thorns) in creative mode using an anvil. It will not be allowed.

### "/ae plinfo" link

https://paste.md-5.net/uwoletesux

**Comment by ThomasWega** [comment]
Should be fixed in the next update!
