### ISSUE TITLE
[Feature Request] Adding a %on block broken% Condition

### ISSUE THREAD

**Issue by MasonX3** [GC-spigot/AdvancedEnchantments#4286]
### Describe the bug

Coming from a Discord ticket, specifically one-time-effec-6434.

Wanted to see about the possibility of adding a %on block broken% condition for HELD enchants, rather than just relying on the MINING trigger.

The main point I have with it is to have items where you can have a potion effect when the item is held, but then have something like durability being taken away or even repairing like sharpening a sword. 

### How to reproduce

Wanted to get this out there to see what you guys think, fingers crossed! 

### "/ae plinfo" link

https://paste.md-5.net/usatepasar

**Comment by GC-spigot** [comment]
HELD only activates when item is equipped and unequipped from hand, it does not keep activating itself. This is impossible at the time being.
