### ISSUE TITLE
[Feature Request] Defining Enchant Slots in Groups

### ISSUE THREAD

**Issue by MasonX3** [GC-spigot/AdvancedEnchantments#4287]
### Describe the bug

Hi again!

Wanted to run this idea by as a possible new feature for tiered items.

Yes, we have the enchant slot increaser field, but what if we were able to define the amount of enchant slots a specific item type has, e.g:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/9630249/07772c31-617e-4049-bece-14846bcef616)

This gives something similar to Apotheosis tier items, providing an incentive for players to upgrade their gear to have more enchantment slots. Slot increaser then acts as the limit overall for the group, meaning you could have 6 netherite enchantments, 5 diamond enchants, etc. if you were to use the item on it. 

### How to reproduce

Please let me know your thoughts, would love to see this :) 

### "/ae plinfo" link

https://paste.md-5.net/usatepasar

**Comment by GC-spigot** [comment]
Hi, this is planned at some point but not any time soon, we will get to this idea in the future :)
