### ISSUE TITLE
AE bug: black scroll and block track dont work

### ISSUE THREAD

**Issue by UnderQuestion** [GC-spigot/AdvancedEnchantments#4289]
### Describe the bug

so, iv got black scroll and block track on my server when plugin was old. after update when im trying to apply them onto my items plguin says that there s no enchantments on my item. the reason is that items were made with old ae version, bc b scroll and track work perfectly with new items. 

### How to reproduce

.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63191496/6702c4d2-416f-4daf-93e1-a565d6a767f2)

### "/ae plinfo" link

im a player

### Server Log

im a player

**Comment by ThomasWega** [comment]
It should convert them automatically to the new PDC format. Make sure the plugin is updated on latest

**Comment by UnderQuestion** [comment]
so now u can fix this (maybe)

**Comment by UnderQuestion** [comment]
also block track still doesnt work for some reasons

**Comment by ThomasWega** [comment]
Hey! Thanks for the video. Are these old items converted to new items with update (NBT to PDC) or just freshly enchanted items? I've just tried with new items applying enchantment and orb and blackscroll works as expected

**Comment by ThomasWega** [comment]
Make sure the server has the latest version of the plugin as well please

**Comment by UnderQuestion** [comment]
server has the lastest version, so the main problem is old enchantment orb, i got it when plugin had older version

**Comment by UnderQuestion** [comment]
also this old enchantment orb was aplied on new item

**Comment by ThomasWega** [comment]
I have just now tested it exactly as you did in the video. Worked completely fine

**Comment by UnderQuestion** [comment]
idk but this problem appeared only after update. also i noticed that almost every plugin item (old, i got them on server when plugin was old) doesnt work anymore. for example name tag. i just rightclick and nothing happens. i dont know what will be if i use current plugin items, but im just a player and cannot get them anymore.
