### ISSUE TITLE
no commands working

### ISSUE THREAD

**Issue by InboundHound** [GC-spigot/AdvancedEnchantments#4293]
### Describe the bug

after adding the most updated Advanced Enchantments plugin and entering the server, whenever i type out the normal commands such as /ae list, or /enchanter, or /tinkerer, the server always responds with /AdvancedEnchantments, not this is not a valid command or anything. then i went into the config and enabled everything, but same issue

idk was /ae plinfo means or the description is describing, but I might just be too tired to understand, but when i type it in the server the same thing comes up if that helps any.

### How to reproduce

there is no way to reproduce that i can find, since it wasnt working in the first place for me

### Screenshots / Videos

![2024-05-15_02 19 31](https://github.com/GC-spigot/AdvancedEnchantments/assets/169891733/2ed0e8ed-eac0-437b-abf0-075c44cf5743)

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ArmonicPvP** [comment]
"/ae plinfo" is the command you run in console to get your plugin information

**Comment by SirJben** [comment]
Provide your startup log.

**Comment by ThomasWega** [comment]
You'll have some error in console for sure
