### ISSUE TITLE
AdvancedEnchantments not working with mcMMO

### ISSUE THREAD

**Issue by Nosleepjusttired** [GC-spigot/AdvancedEnchantments#4294]
### Describe the bug

A lot of our plugins to do with mining such as Smelting and VeinMiner won't work because of the plugin mcmmo. I have gone to support and they have done all they can and I was redirected here to inform you :)
A lot of other things such as enderslayer and netherslayer also are not working and I would assume that is also from the mcmmo.
Upon disabling mcmmo the issue was resolved but ideally I would like both to be on the server and was just wondering if there was anything that could be done.
Natrually generated ores and blocks do not get smelted or veinmined and in the end mobs like endermen and the enderdragon do not take extra damage using the enderslayer enchantment.

### How to reproduce

When we use the mcmmo plugin with your advancedenchantments plugin you cannot use enchants like smelting and veinminer, there might be a few other enchantments that do not work but the smelting and veinminer and 2 of the ones ive noticed. 
but mining any naturally generated ore with both plugins downloaded seems to cause the enchantments to stop working for whatever reason.

### "/ae plinfo" link

https://paste.md-5.net/xepowukuro

**Comment by serpentoi2** [comment]
update mcmmo version

**Comment by ArmonicPvP** [comment]
Your mcMMO is 3 months out of date. Update it.

**Comment by ThomasWega** [comment]
Thank you guys <3
