### ISSUE TITLE
[FQ] Method to differentiate natural vs placed blocks

### ISSUE THREAD

**Issue by StarFluxGames** [GC-spigot/AdvancedEnchantments#4295]
### Describe the bug

Suggesting an additional condition to block-related enchantments called `%is natural%`, when `TRUE` the target block(s) have been naturally generated, and aren't placed by the player.

Reasoning behind this is an issue I encountered with the `Multiplication` default enchantment not working against ore blocks which have been placed by the player. Informed this is in an attempt to avoid duplication issues where players can buy/sell ore blocks. With my particular case (I'm assuming others may have a similar case) I don't have this concern as my server is a small and privately hosted, and we don't have any form of buy/sell(ing) ore blocks completely disregarding the original issue.

### How to reproduce

N/A

### "/ae plinfo" link

https://paste.md-5.net/rimiqayaqe

**Comment by ThomasWega** [comment]
I could add this very simply, but it would work only until restart. Would that be enough for you? Otherwise persistent data about placed blocks is something we plan on doing for many things, but that'll take some time

**Comment by StarFluxGames** [comment]
> I could add this very simply, but it would work only until restart. Would that be enough for you? Otherwise persistent data about placed blocks is something we plan on doing for many things, but that'll take some time

In my particular case, I've built a sub-plugin for a workaround, although persistent data would be the ideal solution.

My temporary fix for this is disabling the event AE registers which is actually adding the natural tags

**Comment by ThomasWega** [comment]
I am glad you've found a workaround. We'll be adding this at some point in future for sure, although might take a bit
