### ISSUE TITLE
Anvil destroys books instead of denying illegal book + item combinations.

### ISSUE THREAD

**Issue by BigScary** [GC-spigot/AdvancedEnchantments#4296]
### Describe the bug

I have made a few enchantments which apply narrowly to very specific items, like "golden chestplate" or "shield". When players try to apply enchantment books to the wrong items, the anvil allows them to finish the transaction (bad) and neither applies the enchantment (good) nor returns the book (bad).

For what it's worth, the preview of the finished item in the anvil UI does NOT show the enchantment added. But nonetheless my players are overlooking that detail surprised/sad about losing their books this way.

### How to reproduce

ward:
  display: '%group-color%Ward'
  description: A chance to absorb enemy damage
  applies-to: Armor
  type: DEFENSE;DEFENSE_MOB
  group: UNIQUE
  applies:
    - GOLDEN_CHESTPLATE
  levels:
    '1':
      chance: 3
      cooldown: 5
      effects:
        - CANCEL_EVENT
    '2':
      chance: 7
      cooldown: 5
      effects:
        - CANCEL_EVENT
    '3':
      chance: 11
      cooldown: 5
      effects:
        - CANCEL_EVENT
    '4':
      chance: 15
      cooldown: 5
      effects:
        - CANCEL_EVENT

1. Define above enchantment.
2. Give yourself a book with this enchantment and a netherite breastplate.
3. Place both in anvil UI.
4. Complete anvil transaction.

Expected: Can't complete transaction because you have a netherite breastplate, while the enchantment is defined as applying to only golden chestplates.

Actual: Transaction completes, book is destroyed, item seems unchanged.

### "/ae plinfo" link

https://paste.md-5.net/ucuzisijar

**Comment by ArmonicPvP** [comment]
Your paper version is 34 versions out of date and your AdvancedEnchantments is 7 versions out of date. Update your paper jar and the plugin jar.

**Comment by ThomasWega** [comment]
Thank you <3
