### ISSUE TITLE
Pumpkin Effect BUG! Since Version 8.X.X

### ISSUE THREAD

**Issue by serpentoi2** [GC-spigot/AdvancedEnchantments#4297]
### Describe the bug

No console error given. but when player got effected by PUMPKIN effect the player helmet suddenly disappeared without touching it

### How to reproduce

it looks like the pumpkin devour the helmet like a nightmare and it can cause players progress like have a perfect ce then the helmet will be eaten using pumpkin effect easily 

### Screenshots / Videos

No console error given.

### "/ae plinfo" link

https://paste.md-5.net/gezufuzuda

### Server Log

No console error given

**Comment by ThomasWega** [comment]
Hey! Do you mind providing video showcase?

**Comment by serpentoi2** [comment]
I think when player got pumpkin on his helmet the helmet drain durability while hitting it.. players reporting it but i tested on my selft it didn't work

**Comment by ThomasWega** [comment]
I'd need a video showcase of the bug if possible please. If you are barely able to reproduce it, I don't know how I am supposed to be able to

**Comment by ThomasWega** [comment]
Thank you as well! :)
