### ISSUE TITLE
place can insert item in gui

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4301]
### Describe the bug

place can insert item in gui with hotkey. 
Reproduction occurs when player press the hotkey at high speed.

### How to reproduce

i reproduced in video: https://youtu.be/W4kPtj58q0A

### "/ae plinfo" link

https://paste.md-5.net/vixogiwawo

**Comment by ThomasWega** [comment]
Video is unavailable. Also, I wonder whether the item is actually usable after or if it's just a visual glitch?

**Comment by Ecilpse** [comment]
> Video is unavailable. Also, I wonder whether the item is actually usable after or if it's just a visual glitch?

player can insert actual items, not packet items. and close inventory, items was disappeared.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/95d1e036-8e77-412b-aa81-48d3f0d43258)

**Comment by ThomasWega** [comment]
Does it happen with every gui or only some specific ones?

**Comment by Ecilpse** [comment]
> Does it happen with every gui or only some specific ones?

only enchant book info gui.

**Comment by ThomasWega** [comment]
Hopefully fixed in the next update
