### ISSUE TITLE
Itemsadder With MMOItems + Smelt enchant has bug occur

### ISSUE THREAD

**Issue by hyein6790** [GC-spigot/AdvancedEnchantments#4302]
### Describe the bug

Only itemsadder has problem.
enchanting with smelt effect => extreamly low durability.
it doesn't look lower durability but break a few blocks, it going to broken. (2~30 blocks)

### How to reproduce

Only itemsadder has problem.
enchanting with smelt effect => extreamly low durability.
it doesn't look lower durability but break a few blocks, it going to broken. (2~30 blocks)

### "/ae plinfo" link

https://paste.md-5.net/apifucapuy

**Comment by ThomasWega** [comment]
Duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4228
