### ISSUE TITLE
vanilla enchants adding incorrectly to items

### ISSUE THREAD

**Issue by UMXR6015** [GC-spigot/AdvancedEnchantments#4304]
### Describe the bug

if you have a efficiency IV pickaxe for example, and want to use an enchantment book which has Efficiency IV and punch 1, both these enchants are added making the pickaxe Efficiency V and punch 1, however punch is only a bow enchant and shouldnt be added. i have anvil.yml disabled [](https://mclo.gs/AH95ncK)

### How to reproduce

use an enchantment book that has more then 1 enchant on it and then use an anvil to add it to item
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/118130748/8b1979d2-36d6-4567-b0c2-d0e9ccbe7e21)

### "/ae plinfo" link

https://paste.md-5.net/togaduwuqi

**Comment by ThomasWega** [comment]
Hey! You have anvil.yml disabled, meaning that something else is handling the anvil, not us
