### ISSUE TITLE
ae bug: telepathy with full cauldron dont drop the cauldron

### ISSUE THREAD

**Issue by UnderQuestion** [GC-spigot/AdvancedEnchantments#4305]
### Describe the bug

cauldron just dont drop the item after breaking it with pickaxe enchanted with telepathy
https://www.youtube.com/watch?v=hEAoh4qBOsQ

### How to reproduce

cauldron with water

### Screenshots / Videos

https://www.youtube.com/watch?v=hEAoh4qBOsQ

### "/ae plinfo" link

im a player

### Server Log

im a player

**Comment by ThomasWega** [comment]
Works completely fine for me. Maybe some other plugin is interfering
