### ISSUE TITLE
Combos are not handled properly

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4308]
### Describe the bug

Combos appear to currently be tracked by the last time you were hit by a melee attack and how many times you've melee attacked since then.

Combos should be tracked by the last time you were hit by any type of attack and should not persist after a certain amount of time.

A combo in any game is a chain of multiple hits without getting hit. I should not be able to take a projectile shot and still have a combo. Likewise, I should not be able to still have a combo after multiple minutes of not attacking.

### How to reproduce

Hit a mob and wait a few minutes and you will still have a combo. Let a skeleton shoot you.

### "/ae plinfo" link

https://paste.md-5.net/epovezuvoq

**Comment by ThomasWega** [comment]
Will be added in the next update
