### ISSUE TITLE
Guard CE not working as expected

### ISSUE THREAD

**Issue by SamGamerYT** [GC-spigot/AdvancedEnchantments#4309]
### Describe the bug

None of my Guard CE's are working on 1.20.4 Latest Purpur, Any known bug fixes for this?

### How to reproduce

  levels:
    '1':
      chance: 3
      cooldown: 6
      effects:
      - GUARD:ZOMBIE:8:1 @Victim
    '2':
      chance: 4
      cooldown: 6
      effects:
      - GUARD:ZOMBIE:8:1 @Victim
    '3':
      chance: 5
      cooldown: 6
      effects:
      - GUARD:ZOMBIE:8:1 @Victim
    '4':
      chance: 6
      cooldown: 6
      effects:
      - GUARD:ZOMBIE:8:2 @Victim
    '5':
      chance: 7
      cooldown: 6
      effects:
      - GUARD:ZOMBIE:8:2 @Victim
    '6':
      chance: 8
      cooldown: 6
      effects:
      - GUARD:ZOMBIE:8:2 @Victim
    '7':
      chance: 10
      cooldown: 6
      effects:
      - GUARD:ZOMBIE:8:3 @Victim
    '8':
      chance: 14
      cooldown: 6
      effects:
      - GUARD:ZOMBIE:8:3 @Victim
    '9':
      chance: 18
      cooldown: 6
      effects:
      - GUARD:ZOMBIE:8:3 @Victim
    '10':
      chance: 22
      cooldown: 6
      effects:
      - GUARD:ZOMBIE:8:4 @Victim

### "/ae plinfo" link

https://paste.md-5.net/zubejomale

**Comment by ArmonicPvP** [comment]
Change to `GUARD:ZOMBIE:8:1:@Victim` instead. Change the second number to the same as the ones you have.

**Comment by ThomasWega** [comment]
The suggestion by @ArmonicPvP would work. Or you can update to 9.8.6, where this was fixed. Always update to latest before saying something doesn't work please

**Comment by ThomasWega** [comment]
Thank you @ArmonicPvP
