### ISSUE TITLE
Enchants making items disappear

### ISSUE THREAD

**Issue by OGLuxey** [GC-spigot/AdvancedEnchantments#431]
Enchants with 100% success are sometimes deleting the item even though the enchant was "successful"

Also the enchant "Inquisitive" is doing the same, when successful it still happens (especially Inquis 3)
http://prntscr.com/nfwo6j

**Comment by MinecraftAdmin** [comment]
Can confirm, experiencing this issue as well.

**Comment by newbie029** [comment]
+1 I also faced this issue on 5.5.6
im using 5.5.5 for now

**Comment by newbie029** [comment]
Update : other AdvancedEnchantments items also make item disappear

**Comment by GC-spigot** [comment]
@OGLuxey @MinecraftAdmin @newbie029 Can you three PM me a list of your plugins on Discord? GC#0830

**Comment by newbie029** [comment]
@GC-spigot Sure
