### ISSUE TITLE
auto-reel is not working

### ISSUE THREAD

**Issue by bebeczka2** [GC-spigot/AdvancedEnchantments#4311]
### Describe the bug

the auto-reel enchant doesn't work, you can apply it, but when you cast the rod, nothing happens

### How to reproduce

this is my config:

autoreel:
  display: '%group-color%Automatyczna Wędka'
  description: Automatycznie wyciągnie wędkę gdy coś złapie!
  applies-to: Wędka
  type: BITE_HOOK
  group: b
  settings:
    showActionBar: true
  applies:
  - FISHING_ROD
  levels:
    '1':
      chance: 25
      effects:
      - AUTO_REEL
    '2':
      chance: 50
      effects:
      - AUTO_REEL
    '3':
      chance: 75
      effects:
      - AUTO_REEL
    '4':
      effects:
      - AUTO_REEL

### "/ae plinfo" link

https://paste.md-5.net/telulugeli

**Comment by TheCashFire** [comment]
Auto reel only activates when your bobber gets a bite, not when you cast it.
