### ISSUE TITLE
Anvil destroys books instead of denying illegal book + item combinations.

### ISSUE THREAD

**Issue by BigScary** [GC-spigot/AdvancedEnchantments#4313]
### Describe the bug

Note this is a resubmit after updating Paper/AE, so maybe it looks familiar.

I have made a few enchantments which apply narrowly to very specific items, like "golden chestplate" or "shield". When players try to apply enchantment books to the wrong items, the anvil allows them to finish the transaction (bad) and neither applies the enchantment (good) nor returns the book (bad).

For what it's worth, the preview of the finished item in the anvil UI does NOT show the enchantment added. But nonetheless my players are overlooking that detail surprised/sad about losing their books this way.

### How to reproduce

ward:
display: '%group-color%Ward'
description: A chance to absorb enemy damage
applies-to: Armor
type: DEFENSE;DEFENSE_MOB
group: UNIQUE
applies:
- GOLDEN_CHESTPLATE
levels:
'1':
chance: 3
cooldown: 5
effects:
- CANCEL_EVENT
'2':
chance: 7
cooldown: 5
effects:
- CANCEL_EVENT
'3':
chance: 11
cooldown: 5
effects:
- CANCEL_EVENT
'4':
chance: 15
cooldown: 5
effects:
- CANCEL_EVENT

Define above enchantment.
Give yourself a book with this enchantment and a netherite breastplate.
Place both in anvil UI.
Complete anvil transaction.
Expected: Can't complete transaction because you have a netherite breastplate, while the enchantment is defined as applying to only golden chestplates.

Actual: Transaction completes, book is destroyed, item seems unchanged.

### "/ae plinfo" link

https://paste.md-5.net/ijaruyajab

**Comment by ArmonicPvP** [comment]
This happens for me as well on latest version

**Comment by ThomasWega** [comment]
Could one of you please provide a video showcase?

**Comment by ArmonicPvP** [comment]
This isn't an issue anymore for me with the latest version it seems
