### ISSUE TITLE
replant enchant deducts from my inventory when I harvest, but doesn’t replant.

### ISSUE THREAD

**Issue by sennby** [GC-spigot/AdvancedEnchantments#4314]
### Describe the bug

My hoe with replant deducts carrots from my inventory when I harvest, but doesn’t replant.

### How to reproduce

My hoe with replant deducts carrots from my inventory when I harvest, but doesn’t replant.

### "/ae plinfo" link

https://paste.md-5.net/atotafitin

**Comment by sennby** [comment]
https://paste.md-5.net/ciqucinaga.coffeescript

**Comment by ThomasWega** [comment]
Very possibly could be AureliumSkills. I've just tried and worked completely fine

**Comment by sennby** [comment]
Well its not or wasnt.

Unless for whatever reason me updating Advancedenchantments broke the things and when i downgraded it it all stopped?

and this is across 2 servers with aurelium and aura, 2 different plugins now.

I havent updated or attempted to since this but I will now, but if its fixed, more than likely it got fixed randomly from something else like normal with AE, and something else will break because no ones aware.
