### ISSUE TITLE
MythicMobs conflicts

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#4315]
### Describe the bug

the mobs are using AdvancedEnchantments enchantments, see this is all the mob has:

skills and mob: https://mclo.gs/1jNtoYH

error: https://prnt.sc/sXmjUySXeUdZ 
I don't know if this error is related but this appeared on the console, after a player had his bow removed from the inventory

they're stealing players' bows, I already have 5 people who had their bows stolen by the mob, and I also have other mobs that are shuffling players' inventories.

plugin version: AdvancedEnchantments-9.7.15.jar

server version: git-Pufferfish-49 (MC: 1.20.4

MythicMobs version: MythicMobs-5.6.1-SNAPSHOT.jar

### How to reproduce

add MythicMobs with skills and place them at THE END

### "/ae plinfo" link

AdvancedEnchantments-9.7.15.jar

**Comment by ThomasWega** [comment]
The error is pretty clear. It's missing a target
