### ISSUE TITLE
Support for pvptoggle plugins.

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#4317]
### Describe the bug

PVP Enchantments work on player's when they have pvp toggled off, ultimately, allowing players to kill afk players outside of claims/protection regions, despite the afk player having pvp toggled off from the plugin.

PVP Toggle: https://www.spigotmc.org/resources/togglepvp.44918/

### How to reproduce

Use: https://www.spigotmc.org/resources/togglepvp.44918/
Stand outside a claim/protection region, we use griefprevention, so stand outside of it.
Activate a pvp-like enchantment, such as Striker on a bow, it'll deal damage.

### "/ae plinfo" link

https://paste.md-5.net/gebowadole

### Server Log

https://mcpaste.io/8453916f2194b19a

**Comment by ThomasWega** [comment]
If the other event correctly cancels damage events it should work fine
