### ISSUE TITLE
[Suggest] Add messages when apply blackscroll to non enchantments tools & make possbile to apply orb for non enchantments tools

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4320]
### Describe the bug

There are quite many cases of misunderstanding and reporting that orb/blackscoll was broken. 
becasuse orb, blackscroll can't apply with non-enchantments items.
can Add messages when apply blackscroll to non enchantments tools & make possbile to apply orb for non enchantments tools?

### How to reproduce

1. give non-enchantments tools
2. apply orb, blackscroll

### "/ae plinfo" link

https://paste.md-5.net/zisaqohemu

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
