### ISSUE TITLE
Feature to BlackScroll

### ISSUE THREAD

**Issue by SliderKP** [GC-spigot/AdvancedEnchantments#4322]
### Describe the bug

i want to add send a feature request, i think be nice, to prevent black scroll to be used in some enchantment groups defined maybe in groups.yml

thank you have nice day.

### How to reproduce

https://paste.md-5.net/naneceqiha

### Screenshots / Videos

https://paste.md-5.net/naneceqiha

### "/ae plinfo" link

https://paste.md-5.net/awevuqoqoz

### Server Log

https://paste.md-5.net/naneceqiha

**Comment by GC-spigot** [comment]
You can already achieve this per-enchant by adding `.settings.removeable` false value, e.g.
```yaml
glowing:
  name: Glowing
  settings:
    removeable: false
```

**Comment by SliderKP** [comment]
thank you.
