### ISSUE TITLE
Auto smelt enchant issue

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4323]
### Describe the bug

When mining red sandstone with an auto smelt tool, it SHOULD give smooth red sandstone but it gives the red sandstone back. Normal sandstone gives smooth sandstone

### How to reproduce

Mine red sandstone with auto smelt

### "/ae plinfo" link

https://paste.md-5.net/wujaxedivi

**Comment by ThomasWega** [comment]
Will be fixed in the next update
