### ISSUE TITLE
%statistic_mine_block% increases by too much

### ISSUE THREAD

**Issue by ClickErrorxD** [GC-spigot/AdvancedEnchantments#4325]
### Describe the bug

Using timber 3, when it cuts down a tree, even a small ass oak tree, you get like 1,000+ blocks broken added to your statistics.

### How to reproduce

Use timber 3 on an axe
Use https://www.spigotmc.org/resources/ajleaderboards.85548/ for leaderboards, such as blocks broken.
Use &a%player_name%: &7#%ajlb_position_statistic_mine_block_alltime% &8- &2**%statistic_mine_block%** in a custom command using https://www.spigotmc.org/resources/mycommand.22272/ or https://www.spigotmc.org/resources/decentholograms-1-8-1-20-6-papi-support-no-dependencies.96927/.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/87890013/c3fdd192-5880-4abd-925b-b4665303fd76

### "/ae plinfo" link

https://paste.md-5.net/olituxosay

### Server Log

https://mcpaste.io/afc25631f668f766

**Comment by ClickErrorxD** [comment]
Vien miner does this too. This plugin's enchants are so flawed and barely customizable. Never using this on a live server again lmao.

**Comment by ThomasWega** [comment]
It's a known issue that this extension reports incorrect amounts. However, it was an issue partly on our side, and next update it will be fixed. However the placeholder will still report duplicate numbers (e.g. 10 blocks broken = 20 on placeholder)
https://www.spigotmc.org/threads/duplicated-data-when-using-statistic_mine_block.532697/
https://www.spigotmc.org/threads/placeholderapi-statistic-placeholder-dont-work.418605/
https://github.com/PlaceholderAPI/Statistics-Expansion/issues/5
https://github.com/PlaceholderAPI/Statistics-Expansion/issues/13
