### ISSUE TITLE
Is there an inbuilt method to check if an item already has an enchant of the same level or below? and to not apply if so.

### ISSUE THREAD

**Issue by TheRealBlitz** [GC-spigot/AdvancedEnchantments#4327]
### Describe the bug

Is there an inbuilt method to check if an item already has an enchant of the same level or below? and to not apply if so.

### How to reproduce

Question

### "/ae plinfo" link

N/A

**Comment by ThomasWega** [comment]
getEnchantmentsOnItem in AEAPI class and check yourself
