### ISSUE TITLE
Effect Bug

### ISSUE THREAD

**Issue by ZYMEEEE** [GC-spigot/AdvancedEnchantments#4328]
### Describe the bug

If you have an effect lower, with a lower amplifier. Any enchant that would give you the same effect with a higher amplifier does not give you said effect.  

### How to reproduce

Give yourself speed 2 then use an enchant that would give you speed 3+

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/170836060/1e45eb22-03d9-4fb0-be64-b28d208a8286

### "/ae plinfo" link

https://paste.md-5.net/hosivofuzi

**Comment by ThomasWega** [comment]
Will be fixed in the update!
