### ISSUE TITLE
SPAM ERROR

### ISSUE THREAD

**Issue by Astralymc** [GC-spigot/AdvancedEnchantments#4331]
### Describe the bug

https://mclo.gs/tzr0IqO

Blockbreakevent

### How to reproduce

When mining

### "/ae plinfo" link

https://paste.md-5.net/azibatoyob

### Server Log

https://mclo.gs/KrUyDAg

**Comment by GC-spigot** [comment]
This looks more like an error with configuration, I cannot recreate it. Can you share your `trench` enchantment?

**Comment by Astralymc** [comment]
https://mclo.gs/fII3lNh

**Comment by Astralymc** [comment]
I sent you the complete file of enchantments

**Comment by Astralymc** [comment]
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/146713470/0e6a1cc1-cf00-4c66-8961-f0d2ac7d956a)

I really think I'm having a bad time xd

**Comment by ThomasWega** [comment]
Your issue is most likely here
```
@Trench{r=3 @Attacker}
``˙
in dinamitaseven enchantment

**Comment by Astralymc** [comment]
hey I corrected that after sending them the enchantments, and the problem still persists
