### ISSUE TITLE
Stat Trackers and AEnchantments Conflict

### ISSUE THREAD

**Issue by Insidi0usAngel** [GC-spigot/AdvancedEnchantments#4333]
### Describe the bug

When adding the enchant Mining boost 4 to a pickaxe it removes block tracker.
Excavation boost 4 also conflicts removes stat trackers.
Veinminer enchant when added also removes stat trackers.
Other boosts such as woodcutter 4 do not break start trackers on axes.

After using scrolls on items to take off problem enchants, it was still not possible then to add back a stat tracker. It is as if the stat trackers is on there but the lore line is removed making it permanently hidden.

What I noted was if you fully enchant the pickaxe etc then you can add stat trackers and it does not break.  However this is a problem as players will want to add stat trackers before enchants in most cases.  The pictures below show that the stat tracker works if you add all enchants first, second picture is after the stat tracker was removed by an enchant.  See also video of stat tracker being wiped/hidden.

### How to reproduce

Add a stat tracker to pick or shovel, then add mining boost 4 or excavation boost 4, or veinminer to pick
On adding those 3 enchants the stat tracker is permanently hidden

### Screenshots / Videos

![powers1](https://github.com/GC-spigot/AdvancedEnchantments/assets/99332317/99cf6f21-183f-49ee-8d7f-e296d8e44ff7)
![powers2](https://github.com/GC-spigot/AdvancedEnchantments/assets/99332317/cbdfae93-d49d-4a10-8ba5-ae6bc9b9dd30)

https://youtu.be/LdkeIu41xS0

### "/ae plinfo" link

https://paste.md-5.net/iroqisegob

### Server Log

https://mcpaste.io/39daca3cd09796bf

**Comment by Insidi0usAngel** [comment]
Also tested this on a fresh test server using paper 1.20.4 and no plugins except for essentialsx. Ran a clean install of advance enchantments.  Issue still occurs if veinminer 3 is applied to a pickaxe it hides stat tracker. https://youtu.be/3UUENbVj-IE

**Comment by ThomasWega** [comment]
Should hopefully be fixed in the next update
