### ISSUE TITLE
Koth set not working properly

### ISSUE THREAD

**Issue by BroGoDx** [GC-spigot/AdvancedEnchantments#4335]
### Describe the bug

I equip '/asets givepiece name Koth <piece>' armor and '/asets weapon name KothSword' sword and when I swing, it spams the chat and console with errors

### How to reproduce

paper 1.20.4-497
ae premade 2th (pvp action custom enchants)

### Screenshots / Videos

https://prnt.sc/GB7LEx9Z7ASE
https://prnt.sc/ns75oT0vq_Q5

### "/ae plinfo" link

https://paste.md-5.net/iwakacixod

### Server Log

https://mcpaste.io/b455764a2f07e94e

**Comment by SirJben** [comment]
You are using outdated targets. https://wiki.advancedplugins.net/abilities/targets
