### ISSUE TITLE
Mcmmo Support

### ISSUE THREAD

**Issue by Nch0001** [GC-spigot/AdvancedEnchantments#4337]
### Describe the bug

My post was cleared prior for the reason "Your mcmmo plugin is 5 years old" which is false as my mcmmo version is 
2.1.231 which was released Mar 10, 2024, which is obviously not 5 years old and unless they are a time traveler there's an issue.
[Previous Report Here](https://github.com/GC-spigot/AdvancedEnchantments/issues/4306)

### How to reproduce

all info is in the prior ticket

### "/ae plinfo" link

all info is in the prior ticket

**Comment by ThomasWega** [comment]
You need to update to latest though. That's 2.2

**Comment by Nch0001** [comment]
Yes but at the time it was very recent

**Comment by ThomasWega** [comment]
That's possible, however we've provided fixes for that already. The issues you've reported were already fixed, but you need to update
