### ISSUE TITLE
Could not pass event BlockBreakEvent 

### ISSUE THREAD

**Issue by Astralymc** [GC-spigot/AdvancedEnchantments#4338]
### Describe the bug

https://mclo.gs/tzr0IqO

Blockbreakevent

### How to reproduce

When mining

### Screenshots / Videos

ENCHANTMENTS.YML:
https://mclo.gs/lT7yPQL

### "/ae plinfo" link

https://paste.md-5.net/azibatoyob

### Server Log

https://mclo.gs/KrUyDAg

**Comment by ThomasWega** [comment]
If you try with fresh files, does this also happen?
