### ISSUE TITLE
AEAPI | Remove Enchantment is not working

### ISSUE THREAD

**Issue by TheRealBlitz** [GC-spigot/AdvancedEnchantments#4339]
### Describe the bug

ItemStack tmpItem = AEAPI.removeEnchantment(topInventorySlot13Item, HelperUtils.capitalizeFirstLetter(enchant.getKey()));

player.getInventory().addItem(tmpItem);

Enchants not being removed

### How to reproduce

As per the above.

### "/ae plinfo" link

N/A

**Comment by GC-spigot** [comment]
Enchant names everywhere use lowercase format, including enchantments.yml and api. Try without capitalizing. The method also returns a new itemstack, which will be different to the one inputted. Use the returned one.
