### ISSUE TITLE
Error with Effect

### ISSUE THREAD

**Issue by SliderKP** [GC-spigot/AdvancedEnchantments#4340]
### Describe the bug

dont shot any particle with the enchant i have created

### How to reproduce

create this enchantment:
disparo:
  display: '%group-color%Disparo'
  description: |-
    &f&oDispara un poder
    &f&oa quienes esten cerca. &4PRUEBA NO AGREGAR
  applies-to: Espadas
  type: RIGHT_CLICK
  group: ARCANOS
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
ALL_SWORD
levels:'1':
    chance: 100
    cooldown: 0
    effects:
PARTICLE_LINE:SMOKE:100:100 @Block

i want to shot a particle and take damage to objetive when the user press right click (the function of right click works fine but the particle_line dont work, i tried with lightning and works fine)
(no errors in console)

### "/ae plinfo" link

https://paste.md-5.net/ajuvukiled

### Server Log

https://paste.md-5.net/ajuvukiled

**Comment by ThomasWega** [comment]
What you are trying to achieve is probably not possible. The @Block is not always present on RIGHT_CLICK. Only if you actually click on a solid block

**Comment by SliderKP** [comment]
> What you are trying to achieve is probably not possible. The @block is not always present on RIGHT_CLICK. Only if you actually click on a solid block

and how i can create an enchantment for "shoot" a particle ?

**Comment by SliderKP** [comment]
@ThomasWega 
and how i can create an enchantment for "shoot" a particle ?

**Comment by ThomasWega** [comment]
You currently cannot. You can create a feature request for it
