### ISSUE TITLE
DO_HARM still triggers after the Victim is dead causing duplicate death message.

### ISSUE THREAD

**Issue by kolderz** [GC-spigot/AdvancedEnchantments#4341]
### Describe the bug

DO_HARM still triggers after the Victim is dead causing duplicate death message.

### How to reproduce

Use DO_HARM effect and one shot kill Victim.
effect: 
DO_HARM:100 @Victim

### "/ae plinfo" link

https://paste.md-5.net/mejayupufi

**Comment by ThomasWega** [comment]
Please provide more details and a video showcase if possible
