### ISSUE TITLE
@Aoe not working

### ISSUE THREAD

**Issue by BroGoDx** [GC-spigot/AdvancedEnchantments#4342]
### Describe the bug

Errors in console, enchants that uses @Aoe not working

### How to reproduce

Use an enchant like lifebloom, commander that has has @Aoe{r=5,t=damageable or undamageable} and hit the player that has armor with that enchant (just any enchant that uses @Aoe)
faction plugin: SaberFactions 1.6.9.5-4.1.4-STABLE (latest)

### "/ae plinfo" link

https://paste.md-5.net/kudifiguxi

### Server Log

https://mcpaste.io/a97a537a804b2014

**Comment by ThomasWega** [comment]
Will be fixed in the next update
