### ISSUE TITLE
Armorsets xp multiplyer doesnt work

### ISSUE THREAD

**Issue by RattenPlaagv2** [GC-spigot/AdvancedEnchantments#4343]
### Describe the bug

  ATTACK_MOB:
    Effects:
    
EXP: <EXP:<math>%exp% * (25.0 + 0.25 * %level%)</math> @Victim
  cooldown: 0
  chance: 100
That is probably because the effect isnt updated for armor set. This might be a bug. The developer will fix this. Please report this at github and it should be fixed with the next update. Works on this is the inquisitive enchant ment but placed in armoresets. with normal enchants it works but with armorsets it doesnt.

### How to reproduce

n.v.t

### Screenshots / Videos

n.v.t

### "/ae plinfo" link

n.v.t

**Comment by ThomasWega** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/c22f5766-6f15-4780-b8cd-e71e324334fb

Most likely incorrect formatting
