### ISSUE TITLE
Placeholder is not working on names of the item

### ISSUE THREAD

**Issue by AlFr3on111** [GC-spigot/AdvancedEnchantments#4347]
### Describe the bug

im trying to add placeholder on item name but its not working in enchanter.yml (AdvancedEnchantment > menu > enchanter.yml)
its seems like it works on lores only but i want it for names too

extra info:
i use last plugin update
minecraft server version is 1.20

here some pics
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/91131286/bc18085c-7c4f-4493-84fd-68de4b057a55)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/91131286/ece1877d-25ee-4ba4-8b9d-d0dc6e3c38b6)

### How to reproduce

add placeholder support on item names

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/91131286/bc18085c-7c4f-4493-84fd-68de4b057a55)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/91131286/ece1877d-25ee-4ba4-8b9d-d0dc6e3c38b6)

### "/ae plinfo" link

https://paste.md-5.net/puvugonuke

**Comment by ThomasWega** [comment]
Will be fixed in the next update
