### ISSUE TITLE
Bug Report: Duplicate and Overlapping 'gears' Enchantments on Items

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#4352]
### Describe the bug

There is an issue with the "gears" enchantment in our game where it is possible to apply the same enchantment multiple times on a single item. For example, a single item can have both Speed 1 and Speed 2 enchantments simultaneously, or even two instances of Speed 2 on the same item. This issue seems to be specific to the "gears" enchantment and breaks the intended functionality.

### How to reproduce

Obtain an item that can be enchanted with "gears."
Apply the "gears" Speed 1 enchantment to the item.
Apply the "gears" Speed 2 enchantment to the same item.
Observe that both Speed 1 and Speed 2 enchantments are present on the item.

### "/ae plinfo" link

https://paste.md-5.net/pecoyidazo

**Comment by ThomasWega** [comment]
I would appreciate a video. Not sure what exactly you mean
