### ISSUE TITLE
Error occurred when using AE

### ISSUE THREAD

**Issue by ZoruaFox** [GC-spigot/AdvancedEnchantments#4354]
### Describe the bug

Some error occurred when running server

### How to reproduce

1. Use latest verion of AE
2. Error occurred

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/96456728/9f946cd7-cdc9-494c-a8c6-b6abc0bfc417)

### "/ae plinfo" link

https://paste.md-5.net/modakakide

### Server Log

https://mclo.gs/6vAo7Tf

**Comment by ThomasWega** [comment]
You cannot use chinese characters in enchantments file config. You need to use alphanumerical values

**Comment by ZoruaFox** [comment]
> You cannot use chinese characters in enchantments file config. You need to use alphanumerical values

@ThomasWega But in earlier versions of AE I can use Chinese characters as enchanments' name, and I even opend a Crowdin project to translate the names.

**Comment by GC-spigot** [comment]
This was changed 3 months ago and unfortunately it's a limitation of Spigot, not ours. There's not much we can do :/

**Comment by ZoruaFox** [comment]
> This was changed 3 months ago and unfortunately it's a limitation of Spigot, not ours. There's not much we can do :/

I see, and thank you for your continued efforts to maintain the plugin.
