### ISSUE TITLE
NullPointerException in InventoryClickEvent in AdvancedEnchantments v9.8.9

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#4355]
### Describe the bug

A NullPointerException occurs when handling the InventoryClickEvent in the AdvancedEnchantments plugin. The error is triggered because getCurrentItem() returns null, and the code does not handle this case before attempting to call the clone() method on the returned value.
Error Stack Trace:
https://mclo.gs/ZMPm8ET
FullLogs:
https://mclo.gs/LpSGJy0

### How to reproduce

Install the AdvancedEnchantments plugin v9.8.9 on a Purpur 1.20.4 server.
Trigger an InventoryClickEvent by interacting with an inventory in the game.
Observe the server console for the NullPointerException error.
My server version: purpur 1.20.4 lastet builds

### "/ae plinfo" link

https://paste.md-5.net/jucuyatofa

**Comment by ThomasWega** [comment]
Will be fixed in the next update
