### ISSUE TITLE
Cosmic Enchants - Killaura bug

### ISSUE THREAD

**Issue by Veyjinn** [GC-spigot/AdvancedEnchantments#4356]
### Describe the bug

Hii!

I noticed that the Killaura enchantment can 1shot a mob with 1000 HP 
and I think it isn't supposed to do that.

I'm using AE 9.8.9

### How to reproduce

apply the enchantment on a sword and spawn a mob with a high amount of HP

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/59097595/f314b089-a502-4471-973d-74f026604d46

### "/ae plinfo" link

https://paste.md-5.net/zenusarome

### Server Log

https://mcpaste.io/e90cd4f13a1fddc5

**Comment by slyleight** [comment]
If you didn't change the default values of the enchantment, thats what killaura does.
**-KILL** means it will instantly kill the target entity no matter what.

The default level 5 enchantment does;
- KILL:1 @Aoe{radius=4,target=mobs}

This means it will one shot any mob with in 4 radius.

**_Please check the enchantments.yml before calling it a bug._**

**Comment by Veyjinn** [comment]
Allright, thank you for explaining. My bad ^^

**Comment by Veyjinn** [comment]
Yea youre probably right. Sorry for taking your time, my bad. And thank you for explaining!

**Comment by ThomasWega** [comment]
Thanks @slyleight
