### ISSUE TITLE
Anvil Mechanics Issue in Latest Plugin Version

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#4358]
### Describe the bug

In the latest versions of the plugin, there is an issue with the anvil mechanics. The plugin breaks the vanilla mechanics of how the anvil works. Previously, when enchanting books at the enchanting table, books with two or more enchantments would combine compatible enchantments onto an item, while incompatible ones would not. However, now the plugin doesn't allow these enchanted books to be applied to items at all. Please fix this issue.

### How to reproduce

1. Enchant books at the enchanting table.
2. Obtain books with two or more enchantments.
3. Attempt to apply these books to items using an anvil.
4. Notice that the plugin prevents any books from being applied to items.

### "/ae plinfo" link

https://paste.md-5.net/wamasesati

**Comment by DimaSergeew** [comment]
Perhaps the breakdown occurred in 9.8.2 since everything works well in 9.8.0

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thanks for reporting
