### ISSUE TITLE
Tinker item disappearing bug

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#436]
Tinker item disappearing bug

If you close the inventory quickly with the Accept button (red stained glass), the item disappears.

https://www.youtube.com/watch?v=UQ1hxG9hJeA&feature=youtu.be

**Comment by newbie029** [comment]
+1

**Comment by GC-spigot** [comment]
@geumu What minecraft version is this occurring on?

**Comment by geumu** [comment]
> @geumu What minecraft version is this occurring on?

1.13.2

**Comment by GC-spigot** [comment]
Please PM GC#0830 on spigot with your configuration, this seems to be related to it as I cannot reproduce this error.
