### ISSUE TITLE
Custom model data

### ISSUE THREAD

**Issue by Bradster176** [GC-spigot/AdvancedEnchantments#4361]
### Describe the bug

Make custom enchants work with items with custom models, such as helmets that are actually a piece of paper.
Helmets cannot have custom models on their own, so another item is used instead to allow for the custom model. Have the plugin allow these items to have CEs work with them.

### How to reproduce

Add a custom model data helmet with Itemsadder and add the enchants to it

### Screenshots / Videos

No need for screenshots

### "/ae plinfo" link

https://paste.md-5.net/ohoviludeh

**Comment by ThomasWega** [comment]
It's already very possible. You can make the paper an armor-item it will just work
