### ISSUE TITLE
Warning In Console When Player Leaves

### ISSUE THREAD

**Issue by DemarcoFC** [GC-spigot/AdvancedEnchantments#4362]
### Describe the bug

When a player leaves the game or does /apply, there are console warnings.

### How to reproduce

A player with custom enchants leaving the game or doing /apply.

### Screenshots / Videos

https://mcpaste.io/ceac7a7aa13e6c52

### "/ae plinfo" link

https://paste.md-5.net/uninuyegoq

### Server Log

https://mcpaste.io/ceac7a7aa13e6c52

**Comment by GC-spigot** [comment]
Solved
