### ISSUE TITLE
Right clicking a custom enchant doesnt work, PlayerInteractEvent issue

### ISSUE THREAD

**Issue by WayzJustme** [GC-spigot/AdvancedEnchantments#4364]
### Describe the bug

When a player right clicks on the custom enchant, nothing happens. They are able to buy etc

### How to reproduce

Not sure. I updated to 1.20.6 last month, hoping for a solution asap.

### Screenshots / Videos

none

### "/ae plinfo" link

https://paste.md-5.net/ibuvexoziy

### Server Log

https://mcpaste.io/24061946f6416f5e

**Comment by ThomasWega** [comment]
duplicate of https://github.com/GC-spigot/AdvancedEnchantments/issues/4351
