### ISSUE TITLE
Korean language texture is broken

### ISSUE THREAD

**Issue by jongmin58** [GC-spigot/AdvancedEnchantments#4365]
### Describe the bug

![캡232처](https://github.com/GC-spigot/AdvancedEnchantments/assets/173085452/84e52649-3c07-4bc4-a436-e2cfb157ae19)

Please fix it quickly ㅠㅠ

Korean language texture is broken

### How to reproduce

[Please fix it quickly ㅠㅠ](https://github.com/GC-spigot/AdvancedEnchantments/assets/173085452/84e52649-3c07-4bc4-a436-e2cfb157ae19)

Korean language texture is broken

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/173085452/84e52649-3c07-4bc4-a436-e2cfb157ae19

Korean language texture is broken

### "/ae plinfo" link

https://paste.md-5.net/qizacibigo

**Comment by SirJben** [comment]
Try adding `-Dfile.encoding=UTF-8` in your server's startup flags.

**Comment by jongmin58** [comment]
It doesn't work

2024년 6월 20일 (목) 오후 3:50, SirJben ***@***.***>님이 작성:
