### ISSUE TITLE
SHIELD_BLOCK does not work at times

### ISSUE THREAD

**Issue by ClimbersGroove** [GC-spigot/AdvancedEnchantments#4366]
### Describe the bug

The item Material.SHIELD and triggers for BLOCK_SHIELD do not work. They chat says that are enchanted, but they do not trigger or update correctly. See video for demonstration

[a885d7f7-2138-4341-9cda-f2518ac04a78.webm](https://github.com/GC-spigot/AdvancedEnchantments/assets/171830003/68cc7f2d-4695-481c-98c5-653ce3bbdd46)

### How to reproduce

Add this to enchantments.yml. Then try using it.

```
survivalinstinct:
  applies:
  - SHIELD
  applies-to: Shields
  description: 20-50% chance to gain 120-160s Speed I on block, 30s cooldown
  display: '%group-color%Survival Instinct'
  type: SHIELD_BLOCK
  group: LEGENDARY
  levels:
    '1':
      chance: 20
      cooldown: 30
      effects:
      - POTION:SPEED:1:120 @Victim
    '2':
      chance: 40
      cooldown: 30
      effects:
      - POTION:SPEED:1:120 @Victim
    '3':
      chance: 100
      cooldown: 0
      effects:
      - POTION:SPEED:1:160 @Self
  settings:
    showActionBar: true


### Screenshots / Videos

[a885d7f7-2138-4341-9cda-f2518ac04a78.webm](https://github.com/GC-spigot/AdvancedEnchantments/assets/171830003/6fc70508-df7f-4536-83f4-2e30448b28e3)



### "/ae plinfo" link

https://paste.md-5.net/idiyufadod

### Server Log

Attatched 

Log here: https://github.com/user-attachments/files/15876299/latest.log

_No response_

**Comment by ClimbersGroove** [comment]
Bumping this

**Comment by jnadlesh** [comment]
Having same problem 
`overflow:
  display: '%group-color%Overflow'
  description: Explode with particles.
  applies-to: 
  type: SHIELD_BLOCK
  group: ASPECT
  applies:
    - SHIELD
  levels:
    '1':
      chance: 100
      cooldown: 0
      effects:
        - PARTICLE:CLOUD:20:2`
     
Any enchant that has to do with the trigger SHIELD_BLOCK do not work.

**Comment by ThomasWega** [comment]
the SHIELD_BLOCK has been causing issues for some time. For some reason on one server restart it just works, on a different one it doesn't. We'll investigate

**Comment by ThomasWega** [comment]
Will handle it here https://github.com/GC-spigot/AdvancedEnchantments/issues/4478
