### ISSUE TITLE
Plugin commands do not work

### ISSUE THREAD

**Issue by OCNW101** [GC-spigot/AdvancedEnchantments#4367]
### Describe the bug

Only 4 commands show up when I try to search for commands. Manually typing the commands also does not work. When trying to use any of the commands that do show up the error "An unexpected error occurred while trying to execute that command" and when hovering over the error it states "Cannot execute command 'ae' in plugin  AdvancedEnchantmeants v9.9.2 - plugin is disabled. I have tried deleting and downloading the plugin several times to no avail. I was asked to post this here by one of the helpers from Discord after submitting a ticket. I am using the latest version of the plugin as well as the latest version of Paper which the server is running on.

### How to reproduce

I don't know it isn't really a bug more just the plugin not working to begin with

### Screenshots / Videos

![image_2024-06-18_162804929](https://github.com/GC-spigot/AdvancedEnchantments/assets/173133829/086e2475-43d8-42ac-a6b2-017dbd3ed6cb)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/173133829/2d3a9dc2-d92f-4846-919b-8a53f914a1b1)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/173133829/d0a50f80-c91f-45ea-b644-f3e293865687)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/173133829/12248c97-f476-4c31-b534-b31e41f41277)

### "/ae plinfo" link

Plugins on surver: AdvancedEnchantmeants v 9.9.2 TeePeeRequests-1.0, mcMMO

### Server Log

https://mcpaste.io/2f33019bf2f3acce

**Comment by GC-spigot** [comment]
Do you have a modified configuration for AdvancedEnchantmens? Seems like soulgem material is broken for you, try regenerating config

**Comment by CabenInTheWoods** [comment]
I am having the same issue! any help would be greatly appreciated.

**Comment by OCNW101** [comment]
No I haven't edited any of the configuration files. I have tried deleting a redownloading and uploading it multiple times to no avail.

> Do you have a modified configuration for AdvancedEnchantmens? Seems like soulgem material is broken for you, try regenerating config

**Comment by ThomasWega** [comment]
Works fine on latest
