### ISSUE TITLE
Paper 1.21 Plugin Error

### ISSUE THREAD

**Issue by XenoshiYT** [GC-spigot/AdvancedEnchantments#4368]
### Describe the bug

Plugin disable when i start the 1.21 Paper server.

### How to reproduce

Use the newest Paper 1.21 Version and put the plugin in the plugin folder. After this start the server and u will see the error.

### Screenshots / Videos

https://prnt.sc/xU1z5SBT73g6
https://prnt.sc/vUh4JqAOmmni

### "/ae plinfo" link

Not Working bc plugin autodisabled

### Server Log

https://mcpaste.io/691afa27d570d330

**Comment by ThomasWega** [comment]
Same issue as https://github.com/GC-spigot/AdvancedEnchantments/issues/4367
