### ISSUE TITLE
Jobs Reborn and Trench AE are incompatible.

### ISSUE THREAD

**Issue by Saros-6585** [GC-spigot/AdvancedEnchantments#4369]
### Describe the bug

if player mining with Trench AE pickaxe, the points in Jobs Reborn go to the user, but they are not properly counted in the limit.
The user actually earns 1000 points, but only 100 points are recorded in the limit, so the income limit of jobs reborn doesn't work properly.

### How to reproduce

Just mining with trench pickaxe, in server with jobs reborn (and join miner job).

### "/ae plinfo" link

https://paste.md-5.net/oyusagodig

**Comment by Lia-LV** [comment]
Money is recorded well in jobs limit, but there is only a problem in the jobs point.

**Comment by ThomasWega** [comment]
sooo. Is there too much or too little points being given?

**Comment by Lia-LV** [comment]
> sooo. Is there too much or too little points being given?

It's not a matter of giving more or less points. the user's point income record(/jobs limit) is not working properly.

so, Iet me explain. 

I can earn 1.12 points to break stone block, and I have trench pickaxe.
If I break stone with my trench pickaxe, Jobs Reborn give `1.12 points * amount of broken stones by trench` to me.
but, If I type the command '/jobs limit' and look at my point income limit, it says that only 1.12 points have been given.

So, It's not a matter of much or little points being given, but it can't detect on just jobs limits feature.

**Comment by ThomasWega** [comment]
Sorry for the delay. I would need to know how Jobs handle this internally to do anything about this. Can you link this issue to the author please?

**Comment by ThomasWega** [comment]
Will reopen if any new info is provided
