### ISSUE TITLE
THROW effect

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedEnchantments#437]
A effect that can throw stuff like enderpearl/snowball/eggs and more 
for example -

example:
  display: '%group-color%Exmaple'
  description: "Right-Click to shoot a snowball"
  applies-to: 'Weapon'
  type: 'RIGHT_CLICK'
  group: 'IMMORTAL'
  applies:
    - ALL_AXE
    - ALL_SWORD
  levels:
    1:
      cooldown: 10
      effects:
        - 'THROW:SNOW_BALL'

**Comment by GC-spigot** [comment]
Apparently this isn't possible with Spigot unless it's very unsafe methods which wouldn't support worldguard, so due to this it will not be implemented.
