### ISSUE TITLE
Conditions not Working

### ISSUE THREAD

**Issue by ZYMEEEE** [GC-spigot/AdvancedEnchantments#4371]
### Describe the bug

Conditions are not working. This has been an issue for over half a year now. 

### How to reproduce

Use "%victim health% > 3 : %stop%" condition, now hit the enemy player, the enchant will now activate. 

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/170836060/33ca3b97-d725-4cc3-bfff-48269b658551)

### "/ae plinfo" link

https://paste.md-5.net/sebecatehi

**Comment by ThomasWega** [comment]
You have incorrect formatting. This is an example of how you format conditions

```yaml
      conditions:
        - '%is headshot% = true : %allow%'
```

**Comment by ZYMEEEE** [comment]
> You have incorrect formatting. This is an example of how you format conditions
> 
> ```yaml
>       conditions:
>         - '%is headshot% = true : %allow%'
> ```
So what did I do wrong here? 

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/170836060/d999372b-f736-4c90-a41d-d09a040b9f8c)

**Comment by ThomasWega** [comment]
it's conditions not condition

**Comment by ZYMEEEE** [comment]
> it's conditions not condition

I'M ACTUALLY SO STUPID LMFAOOOOO THANK YOU SO MUCH
