### ISSUE TITLE
startup message after reboot

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4372]
### Describe the bug

I get this message that should only appear once the plugin is installed.

Yes, it is true that during this morning I deleted everything and only left the plugins and worlds folder to make a new installation.

The problem is that this message is always shown

### How to reproduce

Leave the plugins folder and your world again and reinstall paper

### Screenshots / Videos

https://media.discordapp.net/attachments/601814185776775168/1252939541602373735/image.png?ex=66740a61&is=6672b8e1&hm=1ffafacd04ea74faf4511d3fe96c20ee766a5cbf79ce9d48d74c5629b6644f1b&=&format=webp&quality=lossless

### "/ae plinfo" link

https://paste.md-5.net/xazaqadugo

### Server Log

https://mclo.gs/Ju4ifmV

**Comment by GC-spigot** [comment]
Hi! Already solved for next update :)
