### ISSUE TITLE
Plugin lag

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4373]
### Describe the bug

I am seeing a lot of AE being top of a spark and this is the tree 
![29b5abef945e4ea67beaa7c3aef60039](https://github.com/GC-spigot/AdvancedEnchantments/assets/46936647/93938e90-52dd-42fd-abe7-06951e0c4f59)

Is it possible to optimise this?

### How to reproduce

Run the plugin with loads of players

### "/ae plinfo" link

https://paste.md-5.net/ejawinotiw

**Comment by JHarris12345** [comment]
![372ee04be22f246688401b93892f6903](https://github.com/GC-spigot/AdvancedEnchantments/assets/46936647/7e145554-63bb-47e4-8ae8-9db428d78c8d)
Again showing but this time worse

**Comment by ThomasWega** [comment]
This is NBT, we've moved over to PDC, which might be better. Update... You are on a pretty old version

**Comment by JHarris12345** [comment]
> This is NBT, we've moved over to PDC, which might be better. Update... You are on a pretty old version

I can't update yet because the later versions have an McMMO issue with telepathy that I made a github issue for
