### ISSUE TITLE
ae: trickster enchantment problem

### ISSUE THREAD

**Issue by UnderQuestion** [GC-spigot/AdvancedEnchantments#4374]
### Describe the bug

trickster enchantment on armor teleports you behind when MOBS attack u. i think it should work only vs players because this enchantment ruins some mob farms. also trickster very useless vs mobs that have auto aim.

### How to reproduce

just make this enchantment only work on players

### Screenshots / Videos

not necessary

### "/ae plinfo" link

im a player

### Server Log

im a player

**Comment by ThomasWega** [comment]
then remove type DEFENSE_MOB and it will work only for players :)
