### ISSUE TITLE
error with descriptions

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4376]
### Describe the bug

In the /enchants menu the descriptions appear followed by description, without preserving how they should look, which is below description.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138524212/93f0f427-44a4-43c7-a051-d3056c32771f)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138524212/789590b6-2f94-495e-bd88-3d5b38d22eef)

### How to reproduce

It only modifies the descriptions and this happens

### "/ae plinfo" link

https://paste.md-5.net/yabukeyaro

**Comment by ThomasWega** [comment]
I don't understand

**Comment by Z3r0xh** [comment]
> I don't understand

nothing, I found that my files were outdated even though I had the plugin updated, this happened to me and depending on what I modified, the server did not start
