### ISSUE TITLE
Display Issue with Custom Enchantments v9.9.3

### ISSUE THREAD

**Issue by Xlikes** [GC-spigot/AdvancedEnchantments#4377]
### Describe the bug

When I add enchantments, everything is displayed correctly.
As soon as I strike a mob and the durability is added, the enchantments appear below.
At the top, it says "Enchantments," then there is a blank line. Then comes the durability and then the actual enchantment.

When I add a vanilla enchantment, it is correctly listed under the enchantments. Then comes the blank line again -> durability -> the custom enchantment.

The result is an unsightly image, which gives a somewhat buggy impression of the enchantments.

>>The latest version of the plugin 9.9.3 is being used together with Purpur 1.20.6. There are no other relevant plugins on the server.<<

### How to reproduce

Here in the example, you can see how a sword was first enchanted with the custom enchantment:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/92388937/9a45e8f3-62bf-438d-8a82-893da0bdb74c)

Now at least 1 durability is consumed:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/92388937/d05cd249-0ac7-46c5-8eba-a81be342c75b)

And now I add a vanilla enchantment:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/92388937/af7d16f3-90c3-4e54-b43a-f6447a642e65)

### "/ae plinfo" link

https://paste.md-5.net/ubuliyiceb

**Comment by ThomasWega** [comment]
Send your config please

**Comment by Xlikes** [comment]
I have now tried a few things. The same error keeps repeating itself. Blank Paper 1.20.6 Server only with the plug-in in the latest version. The config is 100% default.
The bug occurs with the Feather client. Is there any way around it or is there nothing I can do? Almost all players play with a client.
