### ISSUE TITLE
ERROR using /gkit

### ISSUE THREAD

**Issue by iftesum** [GC-spigot/AdvancedEnchantments#4380]
### Describe the bug

https://mcpaste.io/0ce97ed1fc7b4b91
this is the log and im getting error whenever i try to use this command /gkit and the menu opens but it doesnt give me any kits

### How to reproduce

idk what to put here

### "/ae plinfo" link

https://paste.md-5.net/hamedipocu

### Server Log

https://mcpaste.io/2d0f8c933601d0c6

**Comment by iftesum** [comment]
how do i fix it??

**Comment by iftesum** [comment]
@ThomasWega

**Comment by ThomasWega** [comment]
Works fine now! Update to latest
