### ISSUE TITLE
AE not supporting MCMMO 

### ISSUE THREAD

**Issue by Dexter113-Endpixel** [GC-spigot/AdvancedEnchantments#4381]
### Describe the bug

[10:22:54 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.9.1
java.lang.NoClassDefFoundError: com/gmail/nossr50/util/random/ProbabilityUtil

### How to reproduce

use telepathy with mcmmo installed

### "/ae plinfo" link

https://paste.md-5.net/kotukogiko

**Comment by ThomasWega** [comment]
Are you on latest mcmmo?

**Comment by Dexter113-Endpixel** [comment]
> Are you on latest mcmmo?

Yes i am on the latest Mcmmo.

**Comment by Dexter113-Endpixel** [comment]
> Are you on latest mcmmo?

It seems to work fine as OP.

**Comment by ThomasWega** [comment]
Just tried and works fine. Please make sure you really are on latest. There was one minor update to McMMO which broke this, but we've fixed it for latest
