### ISSUE TITLE
Slots limiter not working

### ISSUE THREAD

**Issue by Joaofixe** [GC-spigot/AdvancedEnchantments#4382]
### Describe the bug

The slot limiter is not working for some reason. Below, I am sending what I have, but even so, I can exceed the enchantment limit as if it were disabled.

In the first link, you can see my sword with more than 13 custom enchantments (13 is the limit on my server using the slot increaser).

In the second link, you can see the part of the configuration that sets the limit to 13.

### How to reproduce

To reproduce, simply set an enchantment limit and try to exceed that limit by enchanting book by book.

### Screenshots / Videos

1- https://prnt.sc/Bbn7WD1z812Y

2- https://prnt.sc/ALT4CtRU6G3D

### "/ae plinfo" link

https://paste.md-5.net/fututuzeyo

### Server Log

https://mcpaste.io/335de2f87b4a3a74

**Comment by ThomasWega** [comment]
Seems to work fine for me?

https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/f3e76c87-7444-420d-a0f0-36539c54d1cb

Not saying it doesn't happen, but it might not be so straight forward. Are you able to do some more testing and provide more info if possible?

**Comment by Joaofixe** [comment]
Apparently, it has already been fixed. I was making a video to show you how to do it, and it worked fine. Sorry for the inconvenience.

**Comment by ThomasWega** [comment]
No worries at all! Feel free to report anything else :)
