### ISSUE TITLE
Detonate not working at all

### ISSUE THREAD

**Issue by Shling1** [GC-spigot/AdvancedEnchantments#4383]
### Describe the bug

Keep getting the same issue while trying to mine, OP or not.

### How to reproduce

Mine with a pickaxe/

### Screenshots / Videos

https://prnt.sc/qv-VgZoYqOdg

### "/ae plinfo" link

https://paste.md-5.net/ugopihepac

**Comment by ThomasWega** [comment]
You've updated from a very old config. The formatting is different now. It's BREAK_BLOCK @Block
