### ISSUE TITLE
[Serious] Anvils are broken again

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#4385]
### Describe the bug

Anvils no longer allow items with the same vanilla enchant to be combined together, in order to upgrade the vanilla enchant. Not sure how this bug made it past testing, but it's there.

### How to reproduce

Attempt to combine 2 Prot I enchanted books together, or 1 armor item enchanted with Prot I and a book with Prot I.

### "/ae plinfo" link

https://paste.md-5.net/janosoteca

**Comment by ThomasWega** [comment]
That would be my fault. I've completely forgot about this interaction. Thank you for reporting and apologies. Fixed next ver
