### ISSUE TITLE
TP_DROPS doesen't works with auraskill's luck

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4390]
### Describe the bug

TP_DROPS doesen't works with auraskills luck
When the additional drops by "luck  (farming_luck/foraging_luck/mining_luck)" by auraskills,
it does not enter the inventory and falls to the floor.

### How to reproduce

1.make hoes with 100% TP_DROPS
2.set auraskill's level to 100
3.break crops

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/fb88fa02-8dc6-4a05-b769-e4bc889c368a

### "/ae plinfo" link

https://paste.md-5.net/petetubare

**Comment by ThomasWega** [comment]
is your AuraSkills on latest?

**Comment by Ecilpse** [comment]
> is your AuraSkills on latest?

yep i updated yesterday. not aurelium skills

**Comment by ThomasWega** [comment]
I swear a god few weeks ago I've created a new hook and it all worked. Tested TP_DROPS specifically... AuraSkills changes their code so often it's getting really hard to maintain support

**Comment by ThomasWega** [comment]
I will take a look at it

**Comment by Ecilpse** [comment]
> I will take a look at it

when it will be fixed?

**Comment by ThomasWega** [comment]
It will. Just not a huge priority right now. Once some more important or older issues are fixed, I'll get to this. Sorry for the wait

**Comment by Ecilpse** [comment]
> It will. Just not a huge priority right now. Once some more important or older issues are fixed, I'll get to this. Sorry for the wait

sorry to rush.
I'm checking every day to see if this issue has been resolved.
This is because a lot of users are complaining about it. Could you tell me when the fix build will be released?

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Just fixed it.
