### ISSUE TITLE
White Scroll Not working unless item is already enchanted

### ISSUE THREAD

**Issue by Insidi0usAngel** [GC-spigot/AdvancedEnchantments#4393]
### Describe the bug

White scroll will not apply to the following items:
- fishing rod
- trident
- shield
- crossbow
Tested on test server with just AE and necessary plugins - for the fishing rod it cannot have the white scroll 
Once a CE is applied to rod eg Hook 3 etc the whitescroll will then adhere to the item, a problem because the player needs the whitescroll to prevent item from being destroyed by a failed ce application.
On the test server I was able to put a whitescroll on a plain new trident but on the main server this is not the case until a trident ce had been applied (although this could indicate a conflict with other plugin because on test server the white scroll did not work on plain fishing rod)
I tested all other item types and the white scroll worked on armour and other weapons and tools.

### How to reproduce

Try to add a whitescroll to a fishing rod with no enchants on it
Then add whitescroll to fishing rod with a ce present
(AE version 9.8.7)

### "/ae plinfo" link

https://paste.md-5.net/novipewebi

**Comment by ThomasWega** [comment]
Update to latest

**Comment by ThomasWega** [comment]
Will be fixed in the next update
