### ISSUE TITLE
Failed combination enchantments do not trigger the EnchantDestroyItemEvent event

### ISSUE THREAD

**Issue by YunerNotFound** [GC-spigot/AdvancedEnchantments#4394]
### Describe the bug

When there are already advancedEnchantments on the weapon, I use a higher level enchantment to enchant, and the EnchantDestroyItemEvent  event cannot be triggered after the enchantment fails.

My plugin can't listen to this event to proceed to the next step

### How to reproduce

plugin version is lastest and there are my config.yml:

combining:
  enabled: true
  chances:
    # If true, Success and Destroy chances will effect combining
    use-chances: true
    # If true, item will break (if Protection is added, protection will be removed).
    break-item: true   <-----I set this as true
    # If higher level of enchantment already on item is applied, should the enchantment upgrade?
    upgrade: true

### "/ae plinfo" link

https://paste.md-5.net/abcdefghij

**Comment by ThomasWega** [comment]
Will be fixed in the next update
