### ISSUE TITLE
"REPEATING" trigger has not worked properly after update

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4395]
### Describe the bug

repeating trigger "TIME" was not applied properly. i set 7 but it repeat every seconds.
and i ADD_FOOD is "1" but player gain full hunger at moments

### How to reproduce

rhdqhr: #공복
  display: '%group-color%공복'
  description: |-
    일정 시간마다 확률적으로
    허기가 회복됩니다.
  applies-to: 
  type: REPEATING
  group: RARE
  applies:
  - ALL_HELMET
  - ALL_CHESTPLATE
  levels:
    '1':
      TIME: 7
      effects:
      - ADD_FOOD:1

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/c8aceba0-f962-465b-bd5e-94e774e3e7c3)

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/50dbaaa6-008e-4945-a22c-07d97009651c

### "/ae plinfo" link

https://paste.md-5.net/tagurayaze

**Comment by ThomasWega** [comment]
Try setting the "TIME" to lowercase "time"

**Comment by ThomasWega** [comment]
also. Update to latest. On 9.9.5 we've added fix for REPEATING chances

**Comment by ThomasWega** [comment]
Use the lowercase TIME -> time. Not the first time I am writing you about that

**Comment by Ecilpse** [comment]
> Use the lowercase TIME -> time. Not the first time I am writing you about that

I've been watching for a few days to make sure I check the issue. Sorry for the late response.
