### ISSUE TITLE
[New Feature] Disable StatTrack on certain items

### ISSUE THREAD

**Issue by iTzJefeH** [GC-spigot/AdvancedEnchantments#4396]
### Describe the bug

So I think it should be a must have feature.
I don't want players to use some of our custom items made by our plugin, because of our anti-dupe system it disables the StatTtrak and makes the console go wrumm... Also I suggest to add groups, like disable by names/lores/nbts and etc. but also disable on item groups like: "Axes, Pickaxes, Hoes, Armours, Miscs. and etc.

I really hope you guys can make this!

Amazing plugin still, I already love it!
Have an amazing work in the future!

### How to reproduce

(Not a bug, feature request.)
(GC said that I can do it like that.)

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ThomasWega** [comment]
I am not sure I understand. What exactly are you looking for to be added? Can you provide examples?

**Comment by iTzJefeH** [comment]
I want a setting option for the StatTrak items, like:
- disabled items:
 - ALL_AXES
 - netherite_pickaxe
 - wooden_sword

- disabled custom-items: (This thing should check for any item, not only AE made ones..)
 - something:
  - display_name: Good Sword
  - lore: []
  - nbt_tags: x
  
  Thats all. So you cannot apply StatTrak on thoose...

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
