### ISSUE TITLE
Adding enchants clears item lore.

### ISSUE THREAD

**Issue by DivineSanta** [GC-spigot/AdvancedEnchantments#4397]
### Describe the bug

If you have any item lore, or things like soultrackers on an item, the lore gets cleared when adding an enchant. This makes it impossible for players to see how many souls are collected on an item.

### How to reproduce

Add an enchantment to any item with lore/ae items added.

### "/ae plinfo" link

https://paste.md-5.net/notinecewi

**Comment by ThomasWega** [comment]
Used to be an issue, but was fixed few version back. Just tested it and works completely fine!

**Comment by SirJben** [comment]
@DivineSanta upload the videos you sent in DC.

**Comment by ThomasWega** [comment]
Already here probably? https://github.com/GC-spigot/AdvancedEnchantments/issues/4445
