### ISSUE TITLE
An unexpected error has occur 

### ISSUE THREAD

**Issue by clidedis** [GC-spigot/AdvancedEnchantments#4398]
### Describe the bug

if i use a command such as
/advancedenchantments enchant veinminer 3 
its will say an unexpected error has occur 
this happens with everything

### How to reproduce

Im on paper 1.20.6
running the plugins in screenshots

### Screenshots / Videos

![Screenshot 2024-06-27 082145](https://github.com/GC-spigot/AdvancedEnchantments/assets/173908415/a22a8eb6-63de-48af-924f-8ddb368a84ea)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/173908415/1cf89eb2-ecc7-45e3-9c44-9a9d71954ee9)

### "/ae plinfo" link

https://paste.md-5.net/ejuviredis

### Server Log

https://mcpaste.io/b8c731f34557d7d3

**Comment by ItzSimplyJoe** [comment]
https://pastebin.com/mf6bMhDq Startup logs for the same issue

**Comment by ThomasWega** [comment]
Try on latest version. Seems to work fine now
