### ISSUE TITLE
Unknown error? Console.

### ISSUE THREAD

**Issue by iTzJefeH** [GC-spigot/AdvancedEnchantments#4399]
### Describe the bug

It just appears in my console every few minutes for no reason.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/90069925/4a4f25fe-3482-4129-92e0-e2603509e360)

### How to reproduce

I don't know, I've just checked my console. Currently I'm using 4 enchants with players.
Fire Hook, Trickster, Telepathy and Timber

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by GC-spigot** [comment]
Solved!
