### ISSUE TITLE
Items adder and custom enchants don't work

### ISSUE THREAD

**Issue by Bradster176** [GC-spigot/AdvancedEnchantments#4400]
### Describe the bug

I've changed in the config on armor-items to look for 'paper' because that's what the item has to be for 3d model. The enchant that i'm trying to use is called 'Health Boost' and it works on normal helmets. When I enchant it on the 'paper' and then put it on my head, no effects what so ever. I've changed the config to look for this, i've made it so paper can be enchanted for this enchant. 

### How to reproduce

Items adder, change config and still doesn't work

### Screenshots / Videos

https://gyazo.com/1735f02469ec23a281e89d5ab664dc38
https://alpn.cloud/172664478255681536/2024-06-27_17.20.13.png
https://alpn.cloud/172664539777732608/2024-06-27_17.24.01.png

### "/ae plinfo" link

https://paste.md-5.net/icaxoyuxam

**Comment by Bradster176** [comment]
bump

**Comment by ThomasWega** [comment]
Will be fixed in the next update
