### ISSUE TITLE
The "/apply" command superimposes the trigger of repeat entrenchment

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4401]
### Describe the bug

literally. when i command "/apply [playername]", that player's repeat enchantments trigger superimposes.

### How to reproduce

1. equip repeat enchant
2. command "/apply player"

### Screenshots / Videos

https://youtu.be/S2o8hh-l0yw

### "/ae plinfo" link

https://paste.md-5.net/enibezifuv

**Comment by ThomasWega** [comment]
Will be fixed in the next update
