### ISSUE TITLE
when use 'terraform' manaability, it doesen't given auraskill's experice with 'SMELT' tools

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4402]
### Describe the bug

when use 'terraform' manaability, it doesen't given auraskill's experice with 'SMELT' tools
is problems persist before auraskills (aureliumskills)

### How to reproduce

ghkfh: #화로
  display: '%group-color%화로'
  description: |-
    광물, 모래 파괴시 일정확률로
    해당 아이템을 즉시 가공합니다.
  applies-to: 
  type: MINING
  group: RARE
  applies:
  - ALL_PICKAXE
  - ALL_SHOVEL
  levels:
    '1':
      chance: 100
      effects:
      - SMELT

### Screenshots / Videos

https://youtu.be/QHBa3MYfqh4

### "/ae plinfo" link

https://paste.md-5.net/sonigefeli

**Comment by ThomasWega** [comment]
I have two theories. I don't know AuraSkills much, so cannot know when it should and when it should not work.

1. The block auraskills gets from the break block event is already the smelted one, thus why it doesn't work
2. Is an issue on AuraSkills side.

I'd guess more it's the number 2, but really hard to say. Would need to know more info from their code

**Comment by ThomasWega** [comment]
I will try to speak with the author

**Comment by Ecilpse** [comment]
> I will try to speak with the author

How did the talk go with author?

**Comment by Ecilpse** [comment]
why still not fixed yet? i uploaded this issues 4 month ago

> I will try to speak with the author

why still not fixed yet? i uploaded this issues 4 month ago

**Comment by ThomasWega** [comment]
Should be fixed in the next update
