### ISSUE TITLE
[Suggest] send messages to player when tried to apply orb, blackscolls to non-customenchantments 

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4403]
### Describe the bug

when player tried to apply orb, blackscolls to non-customenchantments tools, It doesn't apply.
Please allow this to be applied, or add a message that says it's available after applying a custom enchant.
Quite many players are confused about this.

### How to reproduce

just apply orb, scoll to non-customenchant toolgs

### "/ae plinfo" link

https://paste.md-5.net/ajubeheyag

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
