### ISSUE TITLE
REPATING does not work with ADD_DURABILITY_CURRENT_ITEM

### ISSUE THREAD

**Issue by fytyrama666** [GC-spigot/AdvancedEnchantments#4404]
### Describe the bug

REPATING does not work with ADD_DURABILITY_CURRENT_ITEM. The effect is performed 1 time and does not change the durability. With ADD_FOOD everything works

server version: 1.20.1
Plugin version: 9.9.7

### How to reproduce

repairing_hish:
  display: '%group-color%repairing'
  applies-to: Tools
  type: REPEATING
  group: SIMPLE 
  applies to:
    - ALL_TOOLS
levels:
    '1':
      chance: 100
      description: Passively restores the item's durability.
      time: 5
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:1

### "/ae plinfo" link

https://paste.md-5.net/awiwuyogub

**Comment by ThomasWega** [comment]
Will be fixed in the next update!
