### ISSUE TITLE
[Feature Request] Add enchantment book's custom model data per each group

### ISSUE THREAD

**Issue by Lia-LV** [GC-spigot/AdvancedEnchantments#4405]
### Describe the bug

Currently, enchantment book can only have 1 custom model data.
so please add feature that enchantment book can have custom model data per each group(grade?).

sorry for using bug report, but moderator in discord said 'write feature request on bug report'.

**Comment by ThomasWega** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/issues/3842
