### ISSUE TITLE
Anvil Bug - When combining 2 items

### ISSUE THREAD

**Issue by iTzJefeH** [GC-spigot/AdvancedEnchantments#4406]
### Describe the bug

Hey!
So I've found a bug. 
If you combine 2 items for example:
- Prot 4 Diamond Chestplate
[+]
- Unbreaking 2, Any Custom Enchant Chestplate

You will get Unbreaking 2, Prot 4 Chestplate but without the Custom Enchant.
This also happens with stattrak tools too!

### How to reproduce

Medal video link: https://medal.tv/games/minecraft/clips/ia4X3099Wt8Y7ykSY/d1337J5VedjX?invite=cr-MSxyTzQsMTg5OTM2ODM1LA

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ThomasWega** [comment]
Will be fixed next update hopefully. Will come out soon. Do let me know back if the issue was fixed or there are still issues please
