### ISSUE TITLE
anvil-application was not worked

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4409]
### Describe the bug

although i set "true" anvil-application in config.yml / set "true" encabled, but not worked.
i delete whole AE folder and reinstalled. but still same problems.

### How to reproduce

i just put on server viaversion, protocollib, advancedenchantments.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/036e7e7f-23ea-4194-aef2-ba91046d1b16)

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/e47fd34b-7023-428a-9c90-4ded485a682a)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/9b786038-8356-42f1-a287-d1e43bdc6320)

### "/ae plinfo" link

https://paste.md-5.net/remaqosulo

**Comment by Leomelonseeds** [comment]
Can confirm that anvil application of enchants has been broken since 9.9.5. Please, test your plugin before you push to production.

**Comment by ThomasWega** [comment]
Will be fixed next update hopefully. Will come out soon. Do let me know back if the issue was fixed or there are still issues please

**Comment by Ecilpse** [comment]
> Will be fixed next update hopefully. Will come out soon. Do let me know back if the issue was fixed or there are still issues please

i will update version after fix #4390 .
