### ISSUE TITLE
'repeating' trigger usages extremely high.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4415]
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/c9afa46f-4a80-46c9-acbd-a3f83e6615df)
i use only 2 repeating enchantments.

### How to reproduce

rhdqhr: #공복
  display: '%group-color%공복'
  description: |-
    일정 시간마다 확률적으로
    허기가 회복됩니다.
  applies-to: 
  type: REPEATING
  group: RARE
  applies:
  - ALL_HELMET
  - ALL_CHESTPLATE
  levels:
    '1':
      time: 7
      effects:
      - ADD_FOOD:1
      #- MESSAGE:&f {#cad1e0}발동함
    '2':
      time: 5
      effects:
      - ADD_FOOD:1
    '3':
      time: 3
      effects:
      - ADD_FOOD:1
    '4':
      time: 1
      effects:
      - ADD_FOOD:1
      
      
rudghk: #경화
  display: '%group-color%경화'
  description: |-
    일정 주기마다 흡수효과를 제공합니다.
  applies-to: 
  type: REPEATING
  group: RARE
  applies:
  - ALL_CHESTPLATE
  levels:
    '1':
      time: 100
      effects:
      - POTION_OVERRIDE:ABSORPTION:0:600
    '2':
      time: 80
      effects:
      - POTION_OVERRIDE:ABSORPTION:0:600
    '3':
      time: 60
      effects:
      - POTION_OVERRIDE:ABSORPTION:0:600
    '4':
      time: 40
      effects:
      - POTION_OVERRIDE:ABSORPTION:0:600

### "/ae plinfo" link

https://paste.md-5.net/xememokecu

**Comment by ThomasWega** [comment]
Please send the spark report

**Comment by Ecilpse** [comment]
> Please send the spark report

Now when I look at timings, I'm not experiencing that problems,
but I'm sure it's happening under certain conditions. Let me check more.

**Comment by Ecilpse** [comment]
> Please send the spark report

https://spark.lucko.me/vTWvp5wSNr
