### ISSUE TITLE
Does not disable additional effects when a part of the armor set is broken

### ISSUE THREAD

**Issue by PalhareJoe** [GC-spigot/AdvancedEnchantments#4416]
### Describe the bug

Does not disable additional effects when a part of the armor set is broken

### How to reproduce

I created this armor set (attachment tbcguerreiro.pdf), so when the set is complete and equipped, the effects of the last lines will work, however when a part of the set is destroyed, these additional effects are not deactivated, but when you remove one part the effect is deactivated only occurs when it is destroyed.
[tbcguerreiro.pdf](https://github.com/user-attachments/files/16072397/tbcguerreiro.pdf)

### Screenshots / Videos

https://drive.google.com/file/d/17WvwJvu5xfSK86e0LO7UiT8V7iWIQr05/view?usp=sharing

### "/ae plinfo" link

.

**Comment by ThomasWega** [comment]
PlayerItemBreakEvent is not called in 1.21 for some reason. It's still experimental, so let's just wait for it to be stable first. Will continue handling this issue here
https://github.com/GC-spigot/AdvancedEnchantments/issues/4437
