### ISSUE TITLE
conditions are not worked properly

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4419]
### Describe the bug

player can get gaim potion effect infinitely.
It is triggered even though conditions are "is offhand = false".

### How to reproduce

gpdltmxm: #헤이스트
  display: '%group-color%헤이스트'
  description: |-
    도구 사용시 영구적으로
    성급함 효과를 얻습니다.
  applies-to: 
  type: HELD
  group: LEGENDARY
  applies:
  - ALL_SWORD
  - NETHERITE_PICKAXE
  - DIAMOND_PICKAXE
  - NETHERITE_SHOVEL
  - DIAMOND_SHOVEL
  - NETHERITE_AXE
  - DIAMOND_AXE
  levels:
    '1':
      conditions:
      - '%is offhand% = false : %allow%'
      effects:
      - POTION:FAST_DIGGING:0
    '2':
      conditions:
      - '%is offhand% = false : %allow%'
      effects:
      - POTION:FAST_DIGGING:1
    '3':
      conditions:
      - '%is offhand% = false : %allow%'
      effects:
      - POTION:FAST_DIGGING:2

### Screenshots / Videos

youtube : https://youtu.be/jVbciUIfeIE

### "/ae plinfo" link

https://paste.md-5.net/azokigokop

**Comment by ThomasWega** [comment]
This is not really how the HELD was supposed to be used, but I did the fix anyway. However, now you will need to also check for new variable %is removed%, because for example when switching hands, the HELD is called twice. Once for offhand and once for main hand. Will be present next update
