### ISSUE TITLE
AdvancedEffect Activate Event?

### ISSUE THREAD

**Issue by Latestion** [GC-spigot/AdvancedEnchantments#4421]
### Describe the bug

I have an config issue
"- '%attacker potion effect level SLOW 1%: %allow% OR %attacker potion effect level SLOW 2%: %allow%' "
We are using this condition for one our enchatns but it fails to parse it!

Also, This is not really a bug, but I was directed from discord to ask the question over here.

Is there an event to see when an AEItem was used 
I want to minuplate HolyWhiteScrolls usage (cancel them and stuff)

### How to reproduce

`metaphysical:
  display: '%group-color%Metaphysical'
  description: |-
    A chance to be cured of
    Slowness when attacked.
    At max level, you will only be
    affected approx. 10% of the time.
  applies-to: Boots
  type: DEFENSE
  group: ULTIMATE
  applies:
  - ALL_BOOTS
  levels:
    '1':
      chance: 30
      conditions:
        - '%attacker potion effect level SLOW 1%: %allow% OR %attacker potion effect level SLOW 2%: %allow%'
      effects:
      - CURE:SLOW @Victim
    '2':
      conditions:
        - '%attacker potion effect level SLOW 1%: %allow% OR %attacker potion effect level SLOW 2%: %allow%'
      chance: 60
      effects:
      - CURE:SLOW @Victim
    '3':
      conditions:
        - '%attacker potion effect level SLOW 1%: %allow% OR %attacker potion effect level SLOW 2%: %allow%'
      chance: 75
      effects:
      - CURE:SLOW @Victim
    '4':
      conditions:
        - '%attacker potion effect level SLOW 1%: %allow% OR %attacker potion effect level SLOW 2%: %allow%'
      chance: 90
      effects:
      - CURE:SLOW @Victim`

### "/ae plinfo" link

https://paste.md-5.net/udayeyetuv

**Comment by ThomasWega** [comment]
The conditions allow only one %allow% block if I remember correctly.

Other than that, there is already event ItemApplyEvent, which has AEItem inside

**Comment by Latestion** [comment]
> The conditions allow only one %allow% block if I remember correctly.
The wiki says otherwise and i have tried both!

> Other than that, there is already event ItemApplyEvent, which has AEItem inside
That was not even my question?

**Comment by ThomasWega** [comment]
> Is there an event to see when an AEItem was used
> I want to minuplate HolyWhiteScrolls usage (cancel them and stuff)

It was
