### ISSUE TITLE
Gemify doesnt work!

### ISSUE THREAD

**Issue by LepidusCraft** [GC-spigot/AdvancedEnchantments#4422]
### Describe the bug

I dont really know what to say other than mutiple people have the gemify enchant and it doesnt work itll pop up saying its been used but it hasnt this may also be due to trench also be on the pick? but not 100% sure! thanks!

### How to reproduce

mine with gemify on ores

### Screenshots / Videos

N/A

### "/ae plinfo" link

(https://paste.md-5.net/hexolujufi)

**Comment by GC-spigot** [comment]
It has a really low chance, and with TRENCH it does not work because of how easily abusable it would be.

**Comment by LepidusCraft** [comment]
i know it has a low chance but it pops up when it works and why cant you add a setting to make it usable with trench?
