### ISSUE TITLE
Slot Increaser not having a limit applying per group!

### ISSUE THREAD

**Issue by LepidusCraft** [GC-spigot/AdvancedEnchantments#4423]
### Describe the bug

the slot increaser do not have the setting limit applying per group? i was told by a moderator in the advanced plugins discord server to let you guys know here and you guys would do it

### How to reproduce

check the groups yml

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/174708309/eebde2ab-7258-456f-be7b-25ba9a3cf83f)

### "/ae plinfo" link

https://paste.md-5.net/hexolujufi

**Comment by GC-spigot** [comment]
Currently slots are not limited per group and they are global, therefore logically this is impossible to do without having everyone's slots messed up. We cannot add this, sorry!

**Comment by LepidusCraft** [comment]
well what are unique slot increasers then?

**Comment by LepidusCraft** [comment]
they are all different groups such as unique slot increaser and simple slot increaser i would love for them to be global but they arnt even your moderators agreed?
