### ISSUE TITLE
Fishtrack bug

### ISSUE THREAD

**Issue by pjindras** [GC-spigot/AdvancedEnchantments#4426]
### Describe the bug

Hello, I applyed fishtrack only once, but this it caused:

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/45400186/4c2d72a8-a49a-4367-9bdf-9b0c40b45585)

I am using Pyrofihing (where each wish has custom nbt data) + minecraft Purpur 1.20.4

### How to reproduce

I really dont know, it just happens always.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/45400186/d7b6b6c3-be70-4a2a-94d3-f6ea3b1324aa)

### "/ae plinfo" link

https://paste.md-5.net/xuqowakowo

**Comment by ThomasWega** [comment]
Try with latest on fresh config. Someting with your configuration needs to be causing this. If you are able to find out what, please let us know back
