### ISSUE TITLE
holywhitescroll bug, items are still droped (it doesnt work)

### ISSUE THREAD

**Issue by pjindras** [GC-spigot/AdvancedEnchantments#4427]
### Describe the bug

It should make keepinv, but it doesnt.

### How to reproduce

Easily, I applied it to weapon or armor, i got killed and the keepinv wasnt working. I lost the items. 

### "/ae plinfo" link

https://paste.md-5.net/xuqowakowo

**Comment by ThomasWega** [comment]
Update
