### ISSUE TITLE
Broken translation RU

### ISSUE THREAD

**Issue by a3pokic** [GC-spigot/AdvancedEnchantments#4428]
### Describe the bug

Broken translation in plugin jar file

### How to reproduce

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/174798314/cdabf4b9-a657-496a-a72d-64a039db40dc)

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/174798314/63e2032e-bf28-4195-b2ad-1deb2e2d4d25)

### "/ae plinfo" link

1

**Comment by ThomasWega** [comment]
same issue as https://github.com/GC-spigot/AdvancedEnchantments/issues/4365
