### ISSUE TITLE
Problem mcperks & AdvancedEnchantments

### ISSUE THREAD

**Issue by Yukylyu** [GC-spigot/AdvancedEnchantments#4429]
### Describe the bug

Hi I have a problem with "IncreaseMiningArea" from mcperk. I have a pickaxe with the smelting enchantment from the AdvancedEnchantments plugin. The server freezes, the tool's durability decreases, and it mines all the way to the bottom of the map by itself, then it crashes. I'm not sure if I should contact you or the developer of mcperks.

![e](https://github.com/GC-spigot/AdvancedEnchantments/assets/35634584/8f3c5469-bc7f-44ea-a7ee-6ddfb05f0f27)
![e2](https://github.com/GC-spigot/AdvancedEnchantments/assets/35634584/b8ec6714-f083-44d5-a95f-eef0e409bd61)

### How to reproduce

- Use the perk "IncreaseMiningArea"
- Take a pickaxe
- Apply the smelting enchantment (level 1)
- Start mining
- The server freezes or crashes
- When the server restarts, a very long mine has formed.

### Screenshots / Videos

https://www.youtube.com/watch?v=OuxyF9PoRxI

### pastebin

https://pastebin.com/Yhv8bTC2

**Comment by ThomasWega** [comment]
tell the author that the blocks which he breaks should be marked with `blockbreakevent-ignore` metadata. That should fix the lag and blocks being broken. Maybe the durability issue will be kept. In that case we will need to look at it. Contact the author, try the changes and then let us know :)
