### ISSUE TITLE
Able to get infinity haste whilst not holding a tool with haste.

### ISSUE THREAD

**Issue by GoiseKiller** [GC-spigot/AdvancedEnchantments#4430]
### Describe the bug

You can get infinity haste without holding the item with haste.

### How to reproduce

By repeatedly taking and putting your tool with haste in the hotbar slot you're holding, or offhand.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/174836826/4968867c-c326-4931-8c2d-1619f7b9b523

### "/ae plinfo" link

https://paste.md-5.net/kupikiqogu

**Comment by ThomasWega** [comment]
Fixed next update!
