### ISSUE TITLE
Repeating trigger is canceled in several ways

### ISSUE THREAD

**Issue by TheLaoming** [GC-spigot/AdvancedEnchantments#4431]
### Describe the bug

Hey, so I just started using REPEATING trigger since yesterday for the first time. I noticed it doesn't work properly and it's kinda useless at all, at this point (because of bugs I've found).

Your REPEATING trigger is canceled by several ways, more info below

### How to reproduce

Create an enchant that triggers along with the REPEATING trigger.
- When you create this enchant for a sword, axe or tool etc., it's cancelled when you hit a mob.
- When you create this enchant for an armor, first time you get hit it's cancelled. 

Unforutnately both are cancelled "permanently", until you switch your item in hotbar, or if it's an armor, when you reapply it in armor slot. This means, enchants with REPEATING trigger are useless and being constantly stopped, it's so bad especially for armor items.

Interesting fact is that in **creative mode** this doesn't happen. It works fine with gmc.

With `/ae debug enable` you can clearly see it's stopped with above reasons. As example you can use default enchant "Implants", it has this issue too.

### "/ae plinfo" link

https://paste.md-5.net/wafoxefoje

**Comment by ThomasWega** [comment]
Well that is above weird. Any idea of which update this started happening? @TheLaoming @slyleight

**Comment by slyleight** [comment]
For my case;
We were using version 9.9.2 on the server before, and everything was fine. Then we updated it to version 9.9.7, and that's when we encountered the issue. I assume the problem started with either version 9.9.5 or 9.9.7, which was the last time you updated the REPEATING condition.

@ThomasWega

**Comment by TheLaoming** [comment]
Looks like versions 9.9.8 and 9.9.9 doesn't work, version 9.9.0 which is my production version works fine. @ThomasWega

**Comment by ThomasWega** [comment]
Will be fixed in the next version. Apologies for the inconvenience.
