### ISSUE TITLE
Power 5 enchant book enchants to Power 2

### ISSUE THREAD

**Issue by Tizooo** [GC-spigot/AdvancedEnchantments#4432]
### Describe the bug

cant enchant custom enchants in a nvil on paper 1.21

### How to reproduce

use paper 1.21 and try to enchant trough anvil

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/icRIbQ06DA7UtTAgi/d1337re8TjJe?invite=cr-MSxMbDcsMTI4NzE2OTcs

### "/ae plinfo" link

https://paste.md-5.net/umeliruvox

**Comment by Tizooo** [comment]
and vanilla enchants are broken too. try to put a vanilla power 5 book on a bow
name gets removed and it becomes power 2

**Comment by ThomasWega** [comment]
Will be fixed next update hopefully. Will come out soon. Do let me know back if the issue was fixed or there are still issues please. The power won't be fixed yet though

**Comment by Tizooo** [comment]
still there

**Comment by NEIKI19914** [comment]
Same situation...

**Comment by ThomasWega** [comment]
Yes, working on it

**Comment by ThomasWega** [comment]
Will be fixed in the next update
