### ISSUE TITLE
Issue with Wings enchantment

### ISSUE THREAD

**Issue by lvdat** [GC-spigot/AdvancedEnchantments#4433]
### Describe the bug

Hi dev, i see a bug today with enchant Wings.

Player can fly after unequip Wings boots

### How to reproduce

- Equip a Wings boots.
- Open inventory and quick double click to Boosts, Boosts now unequipped.
- Player still can fly!

### Screenshots / Videos

https://youtu.be/S6JHV5b6w1k

### "/ae plinfo" link

https://paste.md-5.net/wituxipavo

**Comment by ThomasWega** [comment]
Should be fixed in the next update
