### ISSUE TITLE
Dupe with TP_DROPS

### ISSUE THREAD

**Issue by Lia-LV** [GC-spigot/AdvancedEnchantments#4434]
### Describe the bug

When I drop an item through the dropItemNaturally method in my custom plugin, TP_DROPS drop it to doubles.

### How to reproduce

make some plugin with BlockBreakEvent, and set dropItemNaturally(loc, itemStack) method in event.
-> dupe itemStack when I break with TP_DROPS custom enchantment tool.

### "/ae plinfo" link

https://paste.md-5.net/evumedaxos

**Comment by ThomasWega** [comment]
Obviously this will happen. Next update there will be an API method `addIgnoreDropWithNBT`. You will add NBT or PDC data to the item drops on the block and then register it with this method. That will make us ignore drops with this data. You can then handle that stuff yourself

**Comment by Lia-LV** [comment]
> Obviously this will happen. Next update there will be an API method `addIgnoreDropWithNBT`. You will add NBT or PDC data to the item drops on the block and then register it with this method. That will make us ignore drops with this data. You can then handle that stuff yourself

yep thanks, and may I know when it will be released?
