### ISSUE TITLE
Anvil Merging Issue with Custom Enchantments

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#4435]
### Describe the bug

I encountered a bug in the plugin where the anvil merging functionality does not work properly. When attempting to merge two items, each with custom enchantments and Unbreaking III, the items do not combine as expected.

### How to reproduce

Obtain two items with custom enchantments and Unbreaking III.
Attempt to merge these two items in an anvil.
Notice that the items do not merge.

### Screenshots / Videos

https://youtu.be/4byDzfKNIb8

### "/ae plinfo" link

https://paste.md-5.net/rokuwabaza

**Comment by ThomasWega** [comment]
Will be fixed next update hopefully. Will come out soon. Do let me know back if the issue was fixed or there are still issues please
