### ISSUE TITLE
editing a yml file in files, but always empty?

### ISSUE THREAD

**Issue by Paceski** [GC-spigot/AdvancedEnchantments#4439]
### Describe the bug

pdata.yml is always being edited but it never has anything in it, and also uses 1% of the servers thread

### How to reproduce

use spark profilers, and console

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1198009833316692119/1260121297854402721/image.png?ex=668e2ae9&is=668cd969&hm=def7d4b0f0459a31a3973c703117d30a4f9275ebb5dd292e8c139b82cef1af7c&

https://cdn.discordapp.com/attachments/1198009833316692119/1260121171698122832/image.png?ex=668e2acb&is=668cd94b&hm=eb0c6ee6364056257b6b089f7a782d6dc789e87257b4cdc2c1a42c4db59e0068&

https://cdn.discordapp.com/attachments/1198009833316692119/1260121255978205265/image.png?ex=668e2adf&is=668cd95f&hm=1dc3627fd81d6b233179394565cbb4c7afbd75fcf343ae7f2db1aa9de604f56b&

### "/ae plinfo" link

https://paste.md-5.net/uzuzibamaw

**Comment by ThomasWega** [comment]
Gkit cooldowns are saved there

**Comment by Paceski** [comment]
Can you disable that? we don't even have gkits enabled to begin with
