### ISSUE TITLE
[URGENT] Apply advanced enchant with anvil doesn't work

### ISSUE THREAD

**Issue by NoltoxGit** [GC-spigot/AdvancedEnchantments#4441]
### Describe the bug

Hello,
I've just noticed that it's no longer possible to apply a plugin enchantment in an anvil.

## My configs:
config.yml: https://api.mclo.gs/1/raw/Srr9CO5
enchantments.yml: https://api.mclo.gs/1/raw/NTDdr89
anvil.yml: https://api.mclo.gs/1/raw/VNncwOR

### How to reproduce

1. Give a custom enchant
2. Give a item to enchant
3. Put this in anvil
4. See the cross in the anvil gui 

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/75265787/48660673-8941-4258-b608-8007a9611bf7

### "/ae plinfo" link

https://paste.md-5.net/xabosisapa

**Comment by NoltoxGit** [comment]
@ThomasWega

**Comment by Mercurick** [comment]
I have a same problem at AE 9.9.12 and 1.20.4 pufferfish.

**Comment by ThomasWega** [comment]
Will look at it asap guys

**Comment by ThomasWega** [comment]
Will be fixed next update hopefully. Will come out soon. Do let me know back if the issue was fixed or there are still issues please
