### ISSUE TITLE
EXP effect doesn't work with Spigot experience merging

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#4443]
### Describe the bug

The EXP effect used in the Inquisitive enchant does not work with the `merge-radius.experience` setting in spigot. When you kill many mobs at once with sweeping edge, only the equivalent experience for killing 1 mob is given, if the exp is all merged beforehand.

### How to reproduce

- Leave `merge-radius.exp` at its default value of 3.0
- Set your experience level and bar to 0.
- Kill 1 singular mob with a sword enchanted with Sharpness 255, Sweeping Edge 3, and Inquisitive 5. Note the amount of experience you are given.
- Reset your experience again. 
- Spawn many of the same mob in an enclosed space.
- Kill all these mobs at once with the same sword. The dropped experience will be the same. 
- Repeat the last step with `merge-radius.exp` set to 0
- The issue is fixed

### "/ae plinfo" link

https://paste.md-5.net/ejajaciral

**Comment by ThomasWega** [comment]
This is true and we know about this, however this feels more like a spigot bug. I've had this issue with other plugins as well. I'll leave it here as Confirmed Bug, and will try to find a workaround

**Comment by GC-spigot** [comment]
This is definitely a Spigot bug, I'll forward it to them, nothing we can do as we do not handle exp merging in any way.
