### ISSUE TITLE
Telepathy and Extra Storage dupe

### ISSUE THREAD

**Issue by SemperAmici** [GC-spigot/AdvancedEnchantments#4444]
### Describe the bug

If you have items in storage setup to autopickup while also having a tool with the telepathy enchant you will receive the item in both the storage inventory and your own inventory.

### How to reproduce

Have any breakable item setup to auto collect in your storage and an item with telepathy

### Screenshots / Videos

![IMG_3687](https://github.com/GC-spigot/AdvancedEnchantments/assets/114605517/0c368d13-8bd4-40ff-8f5c-c9f68545cd32)

### "/ae plinfo" link

https://paste.md-5.net/xoqedefafe

**Comment by ThomasWega** [comment]
The other plugin needs to use this. https://ae.advancedplugins.net/for-developers/plugin-compatiblity-issues#tp_drops-duplicating-drops-to-multiple-inventories

**Comment by ThomasWega** [comment]
Wait for the next update though. It will change a bit. The wiki will update as well
