### ISSUE TITLE
Adding enchants clears item lore.

### ISSUE THREAD

**Issue by DivineSanta** [GC-spigot/AdvancedEnchantments#4445]
### Describe the bug

If you have any item lore, or things like soultrackers on an item, the lore gets cleared when adding an enchant. This makes it impossible for players to see how many souls are collected on an item. Was told this is fixed and reports keep getting closed. It is still happening on the latest version. Ticket opened on DC and Jben advised to open new report. 

### How to reproduce

Add an enchantment to any item with lore/ae items added.

### "/ae plinfo" link

https://paste.md-5.net/notinecewi

**Comment by DivineSanta** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/assets/151980648/3fea3f9a-914e-41f5-a1ff-e8d88d14eb62

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/151980648/d99de0f4-effa-45e5-802b-9d486647e2ad)

**Comment by ThomasWega** [comment]
![image](https://github.com/user-attachments/assets/8d9c7e71-2883-44ed-82a0-870402a3ab43)
If you manage to find out the reason, please create a new issue. Thank you <3
