### ISSUE TITLE
smelt enchantment not working

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4448]
### Describe the bug

Natural and non-natural minerals are not dropped when minced with this enchantment.

I know that if hand-laid ores are mined, self-smelting does not work, but the ore would have to be dropped at least.

The same thing also happens with naturally formed minerals.

### How to reproduce

use this enchantment in the following way and mine any ore, you will see that there is no drop

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138524212/0416ed28-9442-487e-83c7-2f5507d31475)

### "/ae plinfo" link

https://paste.md-5.net/ibuzaqevup

**Comment by Z3r0xh** [comment]
https://www.youtube.com/watch?v=NpIZkkPhhU0&ab_channel=Neah

**Comment by ThomasWega** [comment]
Also applies for telepathy. Agh.. 1.20.5 really broke everything

**Comment by ThomasWega** [comment]
Will be fixed in the next version
