### ISSUE TITLE
AE items data broken in 1.20.6

### ISSUE THREAD

**Issue by Lia-LV** [GC-spigot/AdvancedEnchantments#4449]
### Describe the bug

AE custom items aren't hide attributes.

### How to reproduce

Use 9.9.11+ AE version on 1.20.5+ server.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/036b18fa-aa4d-46fa-8d35-c8301df0ada3) ![image](https://github.com/user-attachments/assets/2deae90a-9fd1-431a-83bd-fed2b97bd35b)

### "/ae plinfo" link

https://paste.md-5.net/eqesexolig

**Comment by Lia-LV** [comment]
and i don't really remember if the original secret dust can stacked, but it doesn't either.

**Comment by ThomasWega** [comment]
Will be fixed in the update. Thanks for reporting
