### ISSUE TITLE
Enderwalker and Defense_Mob Do Not Work.

### ISSUE THREAD

**Issue by gsun101** [GC-spigot/AdvancedEnchantments#445]
Hey GC, I know your pretty busy, but it'd be appreciated if you could resolve two issues that made me pretty confused; firstly, Defense_Mob has been pretty odd recently especially when it always produces internal errors if ever used. I'm not sure why and I scrolled through the chat's old history to find a solution, but I wasn't able to find one; secondly, Enderwalker is also been buggy. I mean, it doesn't work at all and Poison/Withering do not trigger it's cures and effects. I'm using the latest version. Thanks.

**Comment by GC-spigot** [comment]
@gsun101 Do you have the errors from DEFENSE_MOB?
