### ISSUE TITLE
AEAPI outdated

### ISSUE THREAD

**Issue by Sniperkaos** [GC-spigot/AdvancedEnchantments#4450]
### Describe the bug

The AEAPI is outdated, and I cannot compile using it without runtime errors.

### How to reproduce

Use the method 

`AEAPI.createEnchantmentBook(enchantmentID, enchantmentLevel, success, failure)`

build, and call it. There will be an error. Also, the developer wiki shows something completely different than on the stripped jar. AdvancedEffect is instead CustomEffect, and etc. etc. Is there an updated version of AEAPI I can build off of? Or am I missing something? I tried asking on discord but they just told me they had no idea.

### "/ae plinfo" link

not a server problem

**Comment by ThomasWega** [comment]
Yeah, the stripped jar is very outdated. Just use the plugin jar instead. I'll ask for it to be removed
