### ISSUE TITLE
Authentication server going down disables plugin #2976

### ISSUE THREAD

**Issue by Bunnky** [GC-spigot/AdvancedEnchantments#4451]
### Describe the bug

If the authentication server goes down, AE disables itself. This doesn't make sense for a version that is 100% legal and paid for.

### How to reproduce

Wait for AP's auth server to go down, then try to start a server with AE on it. Or, while the server is up, wait for the auth servers to go down and watch AE disable itself.

### "/ae plinfo" link

There is no /ae plinfo, because it's impossible to run this command when the issue arises, simply because the plugin gets disabled entirely

**Comment by GC-spigot** [comment]
It is checked upon startup and after if server is running and check fails, it will still keep running for 12 hours before disabling.

We have not had any problems or downtime for months now, as we now have an automated switch between our servers and cloudflare.
