### ISSUE TITLE
If the item contains vanilla enchantments, the EnchantDestroyItemEvent won’t be triggered. However, if the item contains both advancedenchantments and vanilla enchantments, the EnchantDestroyItemEvent will trigger normally.

### ISSUE THREAD

**Issue by YunerNotFound** [GC-spigot/AdvancedEnchantments#4452]
### Describe the bug

    @EventHandler
    public void onEnchantFailed(EnchantDestroyItemEvent e) {
        /*
         If the item contains vanilla enchantments, the EnchantDestroyItemEvent won’t be triggered.
         However, if the item contains both custom enchantments and vanilla enchantments,
         the EnchantDestroyItemEvent will trigger normally.
         I'M QUITE SURE THIS IS A BUG!  I'M USING THE LATEST VERSION(9.9.12)!
         */
        ItemStack item = e.getItem();
        Player p = e.getPlayer();
        p.sendMessage("Starting to handle this item. Item type：" + item.getType());
}

### How to reproduce

I have a Sharpness V diamond sword. I tried to add advancedenchantments to it with additional advancedenchantment books, but the event doesn’t trigger when the enchantment fails. 

However, when I use another Sharpness V diamond sword that already has advancedenchantments, the event triggers if the enchantment fails.

### "/ae plinfo" link

https://paste.md-5.net/abcdefghij

### Server Log

NULL ERROR LOG

**Comment by ThomasWega** [comment]
Will be fixed in the next update
