### ISSUE TITLE
Trench not respecting Unbreakable items...

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#4456]
### Describe the bug

Trench not respecting Unbreakable items... Item is set to unbreakable from cmi but its still reducing the durability of item and once all durability is used item just stops working with trench etc..

### How to reproduce

Trench not respecting Unbreakable items... Item is set to unbreakable from cmi but its still reducing the durability of item and once all durability is used item just stops working with trench etc..

### "/ae plinfo" link

https://paste.md-5.net/uvawukubol

**Comment by Rexmen1** [comment]
same for vein miner

**Comment by Rexmen1** [comment]
bump

**Comment by ThomasWega** [comment]
Should hopefully be fixed next update
