### ISSUE TITLE
Unique Rarity Bug

### ISSUE THREAD

**Issue by Skaian** [GC-spigot/AdvancedEnchantments#4457]
### Describe the bug

I am currently facing some issues with groups:

Opening any book that is fabled/above rarities will turn that book into a unique book.
/enchants, /enchantments will show fabled category as unique, making sense for the point up.

Will send videos to show my issue, cannot solve it somehow.

### How to reproduce

Use /enchantments or /enchants to check the group. Use a book that says fabled/higher rarity which leads to a unique enchantment than the fabled/higher.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1262050700200906815/1262051619374239835/2024-07-14_17-21-35.mp4?
https://cdn.discordapp.com/attachments/1262050700200906815/1262051818779705416/2024-07-14_17-22-40.mp4?
![image](https://github.com/user-attachments/assets/4b038755-c943-4a8e-a2f7-508880e041ad)
![image](https://github.com/user-attachments/assets/b9391d5c-a595-47a4-80e5-a928a18c04f9)
![image](https://github.com/user-attachments/assets/70daa346-25d5-48da-a531-eccb1b67ac4d)

This is after reloading, shows from unique to fabled
https://cdn.discordapp.com/attachments/1262050700200906815/1262053269635862609/2024-07-14_17-28-05.mp4?

### "/ae plinfo" link

https://paste.md-5.net/racobapaga

### Server Log

https://mcpaste.io/c4fb54a57c9d0b2f

**Comment by ThomasWega** [comment]
Hey! Needs to be some kind of misconfiguration for sure. Try with fresh files and change that config in parts with your old backed up one. If you are able to figure out the exact reason, please create a new issue with more info and provide your full configs

**Comment by Skaian** [comment]
Would understand such a thing would be caused by misconfig, but what files do i have to redo just to make sure that it is a misconfig? no way i can recreate my whole plugin folder from scratch, i have over 240 enchants and custom setup for all texts, if you would suggest or be more specific i would be extremely thankful for your time much!

**Comment by Skaian** [comment]
I have been using text compare to accomplish what you have suggested in your comment, it seems like the only big difference that can be mentioned really is this from lootconfiguration.
![image](https://github.com/user-attachments/assets/b78a6da7-36d4-4721-bd28-482d759beb6e)
