### ISSUE TITLE
Soulbound does not work for multiple items

### ISSUE THREAD

**Issue by TheLaoming** [GC-spigot/AdvancedEnchantments#4458]
### Describe the bug

Soulbound enchant does not save all of the items with soulbound in the inventory, but just one. Also for some reason it unequip your items like helmet, chestplate etc. All other items drops.

### How to reproduce

Die with multiple soulbound items

### Screenshots / Videos

Posted in ticket already (id 6839)

### "/ae plinfo" link

https://paste.md-5.net/udokaxewab

**Comment by ThomasWega** [comment]
Should be fixed in the next update
