### ISSUE TITLE
Can't apply enchantment books on anvil with Bedrock clients

### ISSUE THREAD

**Issue by Nanpure** [GC-spigot/AdvancedEnchantments#4459]
### Describe the bug

Trying to apply enchantment book on sword with an anvil. Works fine on Java client 1.21 but not Bedrock client 1.21.2. When on Bedrock, items are placed in the anvil, but no item appears in the results side.

This used to work just fine. We are running server version 1.20.6. I believe it broke from a Bedrock client update. We use Geyser and Floodgate to accept Bedrock clients.

### How to reproduce

Place items in anvil using the Bedrock client.

### "/ae plinfo" link

https://paste.md-5.net/wufohepiji

**Comment by ThomasWega** [comment]
Not much we can do about this really. We don't officially support Bedrock and 1.21 is still broken as hell

**Comment by Folas1337** [comment]
No need to reopen but I still wanted to let @Nanpure know that this is a fix that actually works (requires PacketEvents however): https://modrinth.com/plugin/geyser-recipe-fix

**Comment by ThomasWega** [comment]
Awesome. I'll add it to the wiki, thank you <3
