### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#446]
bukkit: Paperspigot 1.13.2
Plugin Version: 5.5.8

1. implants
If you wear a helmet at night, the implants will not work even in the daytime.
Conversely, if you wear a helmet during the day, the implants work at night.

2. obsidiandestroyer
obsidiandestroyer enchant does not work. Check it out.

3. spirits
Blazed summoned by spirits enchant attacks the user without healing.

4. spirits & guardians
When spirits and guardians are worn and both effects are activated
Blaze and iron golem fight each other.

5. guardians
The effect is not active when hit on the bow.

6. trickster
The effect is not active when hit on the bow.

**Comment by GC-spigot** [comment]
1st - doesn't matter what time it's put on, it does not influence it's functions. You might be running into cooldown which is extremely long.
2nd - does work! just requires a compatible factions plugin. If you do not want factions / dont have one then simply remove it's condition and it will work.
3rd - it adds regeneration.
4th - not a whole lot I can do.
5th & 6th - you can change this behaviour yourself by adding DEFENSE_BOW to the enchant type.
