### ISSUE TITLE
Claiming enchants from /enchanter

### ISSUE THREAD

**Issue by VicelikeTuna630** [GC-spigot/AdvancedEnchantments#4460]
### Describe the bug

Hello! 

I would like to suggest your team a new feature and i've been recommended to do it here, on bug reports.
As we know, at the moment players will get random level books from /enchanter.

Idea is following :
I would love to see a feature, where players can only get / buy only level 1 enchant books from /enchanter and after that combine those level 1's to higher level enchants.
For example, let's name enchant "Bait". 
I will buy an enchant from /enchanter and will get Bait I book. Now, when i want it to be higher level ( or 3 for example ) , i should try buy it again from /enchanter and if i got it, i just combine Bait I book with another Bait I book and get Bait II as result. 
Level 2 and higher enchantss data can be changed on enchantments.yml even now, so this is not a problem.

But a new feature i would like to see is that players can obtain only level 1 enchant books and just combine them to get higher levels.
Combining is easy = 
Level 2 = level 1 + level 1
Level 3 = level 1 + level 1 will do level 2, and then another level 2 (1+1) together and will get level 3.

Also, this new feature should perhaps be optional to use for server owners

Thank you for attention and i would love to hear feedback or any additional questions about suggestions, as my english is not perhaps the best XD :) 

### How to reproduce

Make new feature as described on the issue main text

### "/ae plinfo" link

-

**Comment by ThomasWega** [comment]
We'll look into this
