### ISSUE TITLE
error in console and cant do /ce and /tinkerer and /alchemist 

### ISSUE THREAD

**Issue by MillsUnited** [GC-spigot/AdvancedEnchantments#4462]
### Describe the bug

error in console

### How to reproduce

i see this error in console

### Screenshots / Videos

.

### "/ae plinfo" link

.

### Server Log

https://mcpaste.io/91b82611f0c508fd

**Comment by ThomasWega** [comment]
Try downloading the jar again, it might be corrupted or something. In case that doesn't help, also try on 1.20.4 please
