### ISSUE TITLE
error with /enchanter and /enchants

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4463]
### Describe the bug

When you enter the /enchanter and click on the heroic type, it opens as if it were a single type and with the /enchants the same.

If you reload these they work again

### How to reproduce

enter the /enchanter and enter the heroic type, you will see that they appear as unique, if you do a reload they return to normal

### "/ae plinfo" link

https://paste.md-5.net/ifocahosej

**Comment by Z3r0xh** [comment]
I upload a video so you can better appreciate the problem.
As you can see, before the reloads, the unique category always appears if I click on heroic and after the reload they appear fine

https://youtu.be/OwCv68Y5ysU

**Comment by ThomasWega** [comment]
Try on 1.20.4 with fresh files please. This is super weird

**Comment by Z3r0xh** [comment]
> Try on 1.20.4 with fresh files please. This is super weird

I tried again installing and configuring the files, after a while it stops working and only shows unique ones.
I'm on 1.20.6

If you want I can open a ticket with all the AE files.

I have also downloaded the version and this only happens with the last 2 published in spigot

**Comment by Z3r0xh** [comment]
[AdvancedEnchantments.zip](https://github.com/user-attachments/files/16317629/AdvancedEnchantments.zip)

**Comment by Z3r0xh** [comment]
> Try on 1.20.4 with fresh files please. This is super weird

Any solution to this problem? since until now I have created a reload rule for the plugin every 2 min

**Comment by ThomasWega** [comment]
> I'm on 1.20.6

That's why I asked for you to try on 1.20.4. Version above that are broken sometimes

**Comment by ThomasWega** [comment]
Just tried it out an no issues at all. Possibly some kind of misconfiguration

**Comment by Z3r0xh** [comment]
> > I'm on 1.20.6
> 
> That's why I asked for you to try on 1.20.4. Version above that are broken sometimes

Sorry for the delay in responding, I was on vacation. The problem is that my server is on 1.21 and this only happens when there are many players accessing that menu.
