### ISSUE TITLE
[SUGGESTION] configure loot by villagers

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4464]
### Describe the bug

Minecraft now interacts with enchantments and villages so that certain enchantments only appear in certain biomes on those villagers.

It would be nice in the loot file to have a category to define which enchantments appear per loot and in what type of villagers.

This does not need to be in the loot file, it could be in the enchantments file itself, creating a setting like: 
villager: biome

Thus, we separately declare which enchantments have the possibility of appearing on villagers.

Groups would not be a good idea, since people would only look for 1 type of villager.

### How to reproduce

SUGGESTION

### "/ae plinfo" link

SUGGESTION

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
