### ISSUE TITLE
KEEP_ON_DEATH not working

### ISSUE THREAD

**Issue by BeilorDA** [GC-spigot/AdvancedEnchantments#4465]
### Describe the bug

I have a custom enchantment called "Conserve" that enchantment means that when you die you don't lose things (It can be applied to all items) and by having it put in a paid kit (Full armor, sword and bow) the players Dying does not keep items that have the enchantment on.

Plugin Version: 9.9.14
Server Version: 1.20.4

Enchant:

conservar:
  display: '%group-color%⎋ Conservar'
  description: Una posibilidad de conservar el objeto al morir.
  applies-to: Weapons + Tools + Bows + Armor
  type: DEATH;PASSIVE_DEATH
  group: FABLED
  applies:
    - ALL_ARMOR
    - ALL_TOOLS
    - ALL_SWORD
    - BOW
    - CROSSBOW
  levels:
    '1':
      chance: 4
      cooldown: 300
      effects:
        - KEEP_ON_DEATH
    '2':
      chance: 6
      cooldown: 300
      effects:
        - KEEP_ON_DEATH
    '3':
      chance: 8
      cooldown: 300
      effects:
        - KEEP_ON_DEATH
    '4':
      chance: 8
      cooldown: 300
      effects:
        - KEEP_ON_DEATH
    '5':
      chance: 16
      cooldown: 280
      effects:
        - KEEP_ON_DEATH
    '6':
      chance: 29
      cooldown: 250
      effects:
        - KEEP_ON_DEATH
    '7':
      chance: 50
      cooldown: 200
      effects:
        - KEEP_ON_DEATH
    '8':
      chance: 67
      cooldown: 170
      effects:
        - KEEP_ON_DEATH
    '9':
      chance: 79
      cooldown: 10
      effects:
        - KEEP_ON_DEATH
    '10':
      chance: 100
      effects:
        - KEEP_ON_DEATH

### How to reproduce

Occurs upon death

### Screenshots / Videos

https://youtu.be/4jBIDN2qu30

### "/ae plinfo" link

https://paste.md-5.net/ijimufajuh

**Comment by ThomasWega** [comment]
Was fixed in 9.9.15, just forgot to put it in the change log. Just tried it and works fine!

**Comment by BeilorDA** [comment]
Perfect
