### ISSUE TITLE
AE item's hide attributes is broken in 1.20.5+

### ISSUE THREAD

**Issue by Lia-LV** [GC-spigot/AdvancedEnchantments#4469]
### Describe the bug

#4449 
development team said it will be solved with an update, but it still hasn't been solved in the latest version(9.9.16).
Is there anything else I need to set up? If not, I think update is missing. please check.

### How to reproduce

none

### "/ae plinfo" link

https://paste.md-5.net/kihajupine

**Comment by GC-spigot** [comment]
Solved for next update

**Comment by ThePM2** [comment]
gg
