### ISSUE TITLE
Bug with enchants

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4470]
### Describe the bug

I found 2 enchants that dont work as supposed.

arrowdeflectb:
  display: '%group-color%Arrow Deflect (TRIAL)'
  description: Chance to prevent enemy arrow from dealing damage.
  applies-to: Armor
  type: DEFENSE_PROJECTILE;DEFENSE_MOB_PROJECTILE
  group: ADMIN
  applies:
    - ALL_HELMET
  levels:
    '1':
      chance: 15
      cooldown: 15
      effects:
        - CANCEL_EVENT
    '2':
      chance: 25
      cooldown: 15
      effects:
        - CANCEL_EVENT
    '3':
      chance: 35
      cooldown: 15
      effects:
        - CANCEL_EVENT
    '4':
      chance: 40
      cooldown: 15
      effects:
        - CANCEL_EVENT

Event is not called on this

tricksterb:
  display: '%group-color%Trickster (TRIAL)'
  description: |-
    When hit you have a
    chance to teleport directly
    behind you opponent.
  applies-to: Helmet
  type: DEFENSE;DEFENSE_MOB
  settings:
    showActionBar: true
  group: ADMIN
  applies:
  - ALL_HELMET
  levels:
    '1':
      chance: 8
      cooldown: 5
      effects:
      - TELEPORT_BEHIND @Victim
      - POTION:NAUSEA:9:5 @Attacker
    '2':
      chance: 14
      cooldown: 5
      effects:
      - TELEPORT_BEHIND @Victim
      - POTION:NAUSEA:9:5 @Attacker
    '3':
      chance: 17
      cooldown: 5
      effects:
      - TELEPORT_BEHIND @Victim
      - POTION:NAUSEA:9:5 @Attacker

Player is not teleported behind the other player.

Server version 1.21 Purpur

### How to reproduce

Use the enchants I posted and try and see if it works as supposed

### "/ae plinfo" link

https://paste.md-5.net/umebebuwuc

**Comment by ThomasWega** [comment]
Hey! I have just tested it out and all seem to work great! Make sure you are on latest AE and latest paper server jar!

**Comment by Cryptics1999** [comment]
Did you check on purpur, I use purpur so
Sendt fra min iPhone

4. aug. 2024 kl. 16:29 skrev ThomasWega ***@***.***>:

﻿

Hey! I have just tested it out and all seem to work great! Make sure you are on latest AE and latest paper server jar :)

**Comment by ThomasWega** [comment]
Purpur might not be updated to latest yet. 1.21 is still super buggy and has many issues. Not our fault. The server jars need to be fixed
