### ISSUE TITLE
Trench/Vein miner/Telepathy incompatible with Silk Touch

### ISSUE THREAD

**Issue by linaTetris** [GC-spigot/AdvancedEnchantments#4471]
### Describe the bug

I applied both Trench 9, Vein Miner 3, and Telepathy 4 to a Silk Touch pickaxe and tried to go mining, but neither enchant was working correctly. Silk Touch was working properly, but nothing else.

### How to reproduce

Apply Trench 9, Vein Miner 3, Telepathy 4 to a Silk Touch pickaxe, then mine some stone/deepslate and ore veins. None of the effects are triggered.

### "/ae plinfo" link

N/A

**Comment by ThomasWega** [comment]
What server version are you on? Update AE to latest. We need more info. Send /ae plinfo, and try on fresh files with only AE on the server
