### ISSUE TITLE
Enchantments with Chinese names can no longer be used, please support them in the regular expression

### ISSUE THREAD

**Issue by DawnXinyu** [GC-spigot/AdvancedEnchantments#4473]
### Describe the bug

![image](https://github.com/user-attachments/assets/277c52a8-9ecd-4397-9392-483d72d92807)

### How to reproduce

IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: ae_enchantment-雷击

雷击:
  display: '%group-color%雷击'
  description: |-
    攻击生物时
    有几率召唤雷电
  applies-to: "剑, 弓, 弩, 三叉戟"
  type: ATTACK;ATTACK_MOB;SHOOT;SHOOT_MOB
  group: 优良
  applies:
    - TRIDENT
    - BOW
    - CROSSBOW
    - ALL_SWORD
  levels:
    '1':
      chance: 10
      cooldown: 2
      settings:
        worldBlacklist:
          - "Fuben"
          - "spawnA"
      effects:
        - 'MESSAGE:&f갈 &f激活附魔 &f- &a雷击I'
        - LIGHTNING @Victim
    '2':
      chance: 15
      cooldown: 2
      settings:
        worldBlacklist:
          - "Fuben"
          - "spawnA"
      effects:
        - 'MESSAGE:&f갈 &f激活附魔 &f- &a雷击II'
        - LIGHTNING @Victim
    '3':
      chance: 20
      cooldown: 2
      settings:
        worldBlacklist:
          - "Fuben"
          - "spawnA"
      effects:
        - 'MESSAGE:&f갈 &f激活附魔 &f- &a雷击III'
        - LIGHTNING @Victim
    '4':
      chance: 30
      cooldown: 2
      settings:
        worldBlacklist:
          - "Fuben"
          - "spawnA"
      effects:
        - 'MESSAGE:&f갈 &f激活附魔 &f- &a雷击IV'
        - LIGHTNING @Victim
    '5':
      chance: 35
      cooldown: 2
      settings:
        worldBlacklist:
          - "Fuben"
          - "spawnA"
      effects:
        - 'MESSAGE:&f갈 &f激活附魔 &f- &a雷击V'
        - LIGHTNING @Victim

### "/ae plinfo" link

 https://paste.md-5.net/efequkeyac

**Comment by ThomasWega** [comment]
The cannot be used as enchantment names. You need to rename 雷击: to alphanumerical. Nothing we can do about this. It's a limitation of PDC, we were forced to update to

**Comment by DawnXinyu** [comment]
Please tell me in which version to change to use PDC, I will use the previous version of it

> 不能用作附魔名称。您需要将雷击：重命名为字母数字。我们对此无能为力。这是 PDC 的限制，我们被迫更新到不能用作附魔名称。您需要将雷击：重命名为字母数字。我们对此无能为力。这是 PDC 的限制，我们被迫更新到

**Comment by DawnXinyu** [comment]
> The cannot be used as enchantment names. You need to rename 雷击: to alphanumerical. Nothing we can do about this. It's a limitation of PDC, we were forced to update to

Please tell me in which version to change to use PDC, I will use the previous version of it

**Comment by ThomasWega** [comment]
9.7.8 if I remember correctly. It's in the change logs

**Comment by DawnXinyu** [comment]
> 9.7.8 if I remember correctly. It's in the change logs

okay, thank you
