### ISSUE TITLE
Black scrolls, Stat trackers and few other items not working as intended

### ISSUE THREAD

**Issue by martyr420** [GC-spigot/AdvancedEnchantments#4474]
### Describe the bug

Some items aren’t working on my server after updating from **1.20.4** to **1.21** - for instance with black scrolls when i try to apply them onto my items plugin says there’s no enchantments on it

This is the case for nearly all items made before the version change.

### How to reproduce

N/A

### "/ae plinfo" link

https://paste.md-5.net/elogipeqog

**Comment by GC-spigot** [comment]
Which version did you upgrade the plugin from? We had a lot of changes between versions and have dropped nbt support as it was supported last ~5 months between when NBT was stopped being used (early spring) and just recently NBT was removed by Mojang in 1.21
