### ISSUE TITLE
A bunch of my enchantments are not working + errors in logs 1.20.4 

### ISSUE THREAD

**Issue by Rashdonkey** [GC-spigot/AdvancedEnchantments#4476]
### Describe the bug

Bunch of my enchantments not working, fireballs not fireballing, explosive arrows AOE not doing damage, etc... I made a list of all the things that are not working (see attachment) until it was too many and decided to come here and make a post about it.

### How to reproduce

^^

### Screenshots / Videos

[
![image1](https://github.com/user-attachments/assets/1dde8a62-f912-46aa-9e19-169993c87175)
](url)

### "/ae plinfo" link

https://paste.md-5.net/aletuhulab

### Server Log

https://mclo.gs/dD38RZd

**Comment by SirJben** [comment]
Upload your enchantments.yml

**Comment by Rashdonkey** [comment]
Here is my enchantments.yml file: https://pastebin.com/AiGDiAX1

**Comment by Rashdonkey** [comment]
Any clue on what the cause would be?

**Comment by GC-spigot** [comment]
Explosive, Missile and Infernal are meant to be this way - they are not designed to destroy land. You can change that in enchantments.yml.

Others I tested and are working, ones that are not are being mitigated with an update later today.

**Comment by Rashdonkey** [comment]
The issue with the explosives is them not doing any damage to the players or mobs around them. I don't think it's a flag issue either.

Does this mean the oncoming updates will fix the broken enchantments, not a problem on my side?
