### ISSUE TITLE
Tinkerer not working Paper 1.20.4

### ISSUE THREAD

**Issue by HighPriestKing** [GC-spigot/AdvancedEnchantments#4477]
### Describe the bug

/tinkerer only works for OP

Permissions are okay using luckperms

For players that are not OP, accessing /tinkerer through command not working, Does not work via /enchanter either

Players can use /tinkerer:tinkerer to get gui to open

test version 9.9.12 up to 9.9.16 same issue no matter what

### How to reproduce

paper 1.20.4

Luckperms with permissions for enchanter and tinkerer

try to use tinkerer.. it wont work

**Comment by ThomasWega** [comment]
Works fine for me. Try on latest AE with only AE on the server
