### ISSUE TITLE
No lowercase option for %mob type%

### ISSUE THREAD

**Issue by someoldman** [GC-spigot/AdvancedEnchantments#4479]
### Describe the bug

If you write a custom enchantment and use %mob type% the value is returned in uppercase.   There is no option to set this or convert this to lowercase for use with console command.  Other options like %victim name% is returned in lowercase however where the mob has more than one word in it's name, doesn't include the underscore used by Minecraft.

example: 
%mob type% = TROPICAL_FISH
%victim name% = tropical fish
Required for Minecraft's console = tropical_fish

Possiable solution:  A version of %mob type% that has toLowerCase() applied to the value.

### How to reproduce

Kill any mob with more than two words in the name and check the %mob type% vs %victim name% values.

Examples: 
skeleton_horse
snow_golem
tropical_fish
wandering_trader
iron_golem

-- This isn't a comprehensive list as the issue is the same for all mobs that meet the criteria.

### "/ae plinfo" link

https://paste.md-5.net/bejiceburi

**Comment by ThomasWega** [comment]
Just use PlaceholderAPI String expansion and use placeholder `%string_lowercase_<string>%`?
