### ISSUE TITLE
No blacklist option for mob types

### ISSUE THREAD

**Issue by someoldman** [GC-spigot/AdvancedEnchantments#4480]
### Describe the bug

There is no option to blacklist mob types from receiving the effects of an enchant.  

Example: I want withers, sheep and ender dragons to be immune to the enchantment effects but everything else work fine.

### How to reproduce

Confirmed by your discord support team and told to put this here.

### "/ae plinfo" link

https://paste.md-5.net/bejiceburi

**Comment by ThomasWega** [comment]
You cannot just use conditions?
