### ISSUE TITLE
Mystery Dust NBT change on Server Restart

### ISSUE THREAD

**Issue by Nightcraftop** [GC-spigot/AdvancedEnchantments#4481]
### Describe the bug

Good morning,
Been having an issue with Mystery Dust chaning NBT data on server restarts.
For instance, I have a Shopkeeper that uses Mystery Dust as a currency, everything works fine for that day, but when the server restarts, the NBT data of the Mystery Dust changes, not allowing anyone to buy until I change the old Mystery Dust for the normal one.
A normal Mystery Dust NBT Data:
{} PublicBukkit Values
{"advancedenchantments:shift-click":"false"}
After restart in a shopkeeper:
{} PublicBukkit Values
{"advancedenchantments:shift-click":0b}

(Sometimes the Int HideFlags changes from 3 to 35 also)
Any help would be greatly appreciated, thank you for your time and amazing work! 

(This happened on Paper & Purpur)

### How to reproduce

Have Mystery Dust in a shopkeeper and restart the server, upon restart, the NBT of the shopkeeper will be different than ones you grab with /ae giveitem mystery
(This happened on Paper & Purpur)

### "/ae plinfo" link

https://paste.md-5.net/uxoyedosuh

**Comment by GC-spigot** [comment]
Does the dust stop working? false and 0b is the same, it's definitely not caused by us though, but it should not matter.

**Comment by Nightcraftop** [comment]
> Does the dust stop working? false and 0b is the same, it's definitely not caused by us though, but it should not matter.

The dust just no longer stacks which isn't a big deal.
Also you're unable to buy it from the shopkeeper as its technically a different NBT, it doesn't see it as the same item.

If this is a Shopkeeper issue, I will reach out to them.
Thank you for replying, appreciate the work you do!

**Comment by ThomasWega** [comment]
Try reaching out to Shopkeeper issue. As far as I remember, we do not modify NBT tags this randomly

**Comment by ThomasWega** [comment]
If you are unable to figure it out, feel free to get back to us
