### ISSUE TITLE
Unable to trigger the AdvancedEnchantItemEvent when enchanting a book.

### ISSUE THREAD

**Issue by YunerNotFound** [GC-spigot/AdvancedEnchantments#4482]
### Describe the bug

    @EventHandler
    public void onEnchantAE(AdvancedEnchantItemEvent event) {
        Player player = event.getPlayer();

        player.sendMessage("event trigger ");
    }

### How to reproduce

enchantmentTable.yml

# Custom enchants from enchantment table
enchantmentBooks:
  enabled: true  <------ I enable this to true
  # Chance of getting custom enchantments when enchanting with enchantment table.
  # This will give custom enchantment book instead of vanilla books, and can be
  #  applied either with anvil or drag & drop onto item.
  chance: 30 # Value: 1 to 100 %

### "/ae plinfo" link

#

### Server Log

#

**Comment by ThomasWega** [comment]
Fixed in next update
