### ISSUE TITLE
GKITS

### ISSUE THREAD

**Issue by Jrdelt** [GC-spigot/AdvancedEnchantments#4483]
### Describe the bug

When using customModelData in the gkits the preview shows the armor but when you equip the armor it doesnt have the custom textures.  USING ORAXEN.

### How to reproduce

Change the gkit to match a custom armor texture using CustomModelData and the armor when equiped wont have the custom textures.

### "/ae plinfo" link

https://paste.md-5.net/pumazecoba

**Comment by ThomasWega** [comment]
Will handle it further here https://github.com/GC-spigot/AdvancedEnchantments/issues/4491
