### ISSUE TITLE
Grindstones are not removing enchants

### ISSUE THREAD

**Issue by WaterArchery** [GC-spigot/AdvancedEnchantments#4485]
### Describe the bug

Players can bypass the grindstone enchant removal by trying couple of times.

### How to reproduce

1 - Place a grindstone
2 - Place your sword on top
3 - Check the right side if the custom enchants are still in the output. If it is, click the output. If it is not, pickup the sword on the top and place it again.

### Screenshots / Videos

Video: https://streamable.com/b1azp4

### "/ae plinfo" link

https://paste.md-5.net/debuferigu

**Comment by ThomasWega** [comment]
Video is not available. Also update to latest first

**Comment by WaterArchery** [comment]
I updated the latest but it is still happening.

Info: https://paste.md-5.net/quseregowi
Video: https://www.youtube.com/watch?v=QGDJSwFpss4

**Comment by ThomasWega** [comment]
Should be fixed in the next update
