### ISSUE TITLE
Enchantment Conditions

### ISSUE THREAD

**Issue by slyleight** [GC-spigot/AdvancedEnchantments#4486]
### Describe the bug

**Issue Description:**
My custom "Slayers Edge" enchantment is intended to increase damage by 25% against specific bosses and certain conditions. However, the conditions appear to be evaluated using an AND operator instead of an OR operator. As a result, even if one condition is met, the enchantment fails if subsequent conditions are not met.

**Expected Behavior:**
The enchantment should activate if any one of the specified conditions is met, using an OR operator logic.

**Current Behavior:**
The enchantment only activates if all conditions are met.

**Question:**
Is there a way to change the evaluation of these conditions to use an OR operator instead of an AND operator, or is there a workaround to achieve this functionality?

**Possible Solutions:**

**Configuration Change:** If there's a configuration setting that allows changing the condition evaluation from AND to OR, please provide guidance on how to apply it.
**Workaround:** If no configuration change is possible, suggest any potential workaround to achieve the desired behavior.

> slayersedge:
>   display: '%group-color%Slayers Edge'
>   description: |-
>     {#900C3F}&oʙᴏss Etkinliğinden Elde Edildi
>     {#FFC300}BOSS{#770ef8}'lara verilen hasarı kalıcı {#FFC300}25% {#770ef8}arttırın.
>   applies-to: Yay, Arbalet
>   type: SHOOT_MOB
>   group: ETKINLIK
>   settings:
>     removeable: false
>     showActionBar: true
>   applies:
>   - BOW
>   - CROSSBOW
>   levels:
>     '1':
>       conditions:
>       - '%victim name% contains ᴋɪɴɢ and %player world% contains dungeon : %allow%'
>       - '%victim max health% >= 1000 and %player world% contains dungeon = false : %allow%'
>       - '%mob type% = WARDEN or %mob type% = ENDER_DRAGON or %mob type% = WITHER : %allow%'
>       effects:
>       - 'INCREASE_DAMAGE:100'

### How to reproduce

1. Apply the Slayers Edge enchantment to a bow or crossbow.
2. Engage with a mob meeting one of the specified conditions.
3. Observe that the enchantment does not activate unless all conditions are met.

### Screenshots / Videos

![2024-07-24_18-01-28](https://github.com/user-attachments/assets/5d085077-ce6a-48da-a598-717ae98b61dd)

### "/ae plinfo" link

https://paste.md-5.net/amilizemiy

**Comment by ThomasWega** [comment]
Try negating the conditions and see if that's a possible workaround

so
`%victim max health% >= 1000 and %player world% contains dungeon = false : %allow%`
would become:
`%victim max health% < 1000 and %player world% != dungeon = true : %stop%`

**Comment by slyleight** [comment]
That's what I've been doing with my other enchants. %stop% makes sense because of the AND condition, and it checks each one of them. When I checked the document and saw you using multiple %allow% conditions, I thought it would work too.

**Comment by ThomasWega** [comment]
So does that workaround work or not?

**Comment by slyleight** [comment]
**Not really I'm afraid...**

We have different kinds of BOSS mobs, like spiders, skeletons, wither skeletons, and much more. Most of them have higher HP than 1000, so that condition is fine. However, we also want this to work against the Wither, Warden, and Ender Dragon too, as they are vanilla bosses.

But with health < 1000, it forces it to stop, even if it's a Warden (150 HP).

How am I going to work around that?

It would be nice to have multiple bracelet conditions:
((%victim max health% < 1000 and %player world% != dungeon) and %mob type% != WARDEN)

Because sometimes it is really hard to get around that problem.

If it is a vanilla mob (Wither, Warden, Ender Dragon), it should work no matter what.
If it is a custom boss (our custom bosses in the dungeon which have multiple mob types, but their names contain "KING"), it should work too.
Sometimes we spawn powerful mobs for our players, and they have more than 1000 health; it should work on them too.
It might be possible with more than 10 different conditions, but it turns into spaghetti coding, and if we add another boss, we have to change the enchantment again to completely recheck the conditions.

I believe it is not possible in a feasible way; but I believe multiple bracelets in conditions should do the trick.

**Comment by ThomasWega** [comment]
``%player world% contains dungeon = false`` is not possible btw. You can only do ``%player world% contains dungeon``

I am however working on the bracelet conditions you've suggested, while also improving the logic. This still won't work though ``%player world% contains dungeon = false``
