### ISSUE TITLE
Unbreakable Bugged Again

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#4487]
### Describe the bug

Unbreakable tools are not respected again and trench/vein miner causes durablity loss for unbreakble tools too...

AGAIN...
And latest version just doesnt work at all causing errors in console 9.9.17 atleast with 9.9.16 other enchants works but durablity issue is still there.. So i guess fix both issues?

log for 9.9.17 version is given below and with 9.9.16 unbreakable bug is still there... so i can't test if its fixed with 9.9.17 and for 100% sure its bugged in 9.9.16

### How to reproduce

Unbreakable tools are not respected again and trench/vein miner causes durablity loss for unbreakble tools too...

AGAIN...

### "/ae plinfo" link

https://paste.md-5.net/hecipuwuba

### Server Log

https://ptero.co/rapaxukiva.properties

**Comment by Rexmen1** [comment]
I think either you forgot to merge the changes you did or something else... can this be fixed? unbreaakble tools breaks everytime bcz of this...

**Comment by GC-spigot** [comment]
Try on 9.9.18 - coming in a few hours. I'm not experiencing the same problem.
