### ISSUE TITLE
Permanent buff bug

### ISSUE THREAD

**Issue by newbie029** [GC-spigot/AdvancedEnchantments#449]
Permanent buff when in hand item removed by /sell hand or /ah sell

https://streamable.com/essdx

**Comment by GC-spigot** [comment]
Not able to fix this. Only way would be to set up so that item cannot be sold.

**Comment by newbie029** [comment]
is it possible to do check for permanent buff on InventoryDragEvent or PlayerItemHeldEvent?
so when they change the hotbarslot we remove the buff
