### ISSUE TITLE
Oraxen Compatibility

### ISSUE THREAD

**Issue by CuprizeDev** [GC-spigot/AdvancedEnchantments#4491]
### Describe the bug

When using AdvancedEnchantments sets option, I set the custom model data, it shows the armor in the inventory as custom armor, but when I put it on it just shows as netherite armor. I have also checked if it is oraxen itself causing this issue and it is not, it only happens with the advanced sets. Example Config:

  helmet:
    name: '&4&lSupreme Headgear'
    customModelData: 1003
    itemFlags: []
    lore:
    - '&4&oA lightweight headpiece'
    - '&4&ofit for take off.'
    - ''
    - '&4&lSUPREME SET BONUS'
    - '&4&l* &4Gears IV'
    - '&4&l* &4No Fall Damage / Food Loss'
    - '&4&l* &4Deal +15% damage to all enemies'
    - '&4&l* &4Enemy arrows deal 10% more damage to you.'
    - '&4&l* &4+200% Clout'
    - '&7&o(Requires all 4 supreme items.)'
    enchants
      - protection:4
      - unbreaking:3
 
Video:
https://github.com/user-attachments/assets/194a4823-63ee-4dde-9a38-71a9f9cc0f8b

### How to reproduce

Use Oraxen, create a config in oraxen/items/armors, then change the default armor type to netherite, and add something similar to config. This should work, then you add the custom model data to advanced armor sets.
ruby_helmet:
  displayname: <gradient:#FA7CBB:#F14658>Ruby Leggings
  material: NETHERITE_HELMET
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - default/armors/ruby_helmet
    - default/armors/ruby_helmet
    custom_model_data: 1003
  color: 0,0,3

### Screenshots / Videos

https://github.com/user-attachments/assets/194a4823-63ee-4dde-9a38-71a9f9cc0f8b

### "/ae plinfo" link

https://paste.md-5.net/daleyeziju

### Server Log

no error log

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
