### ISSUE TITLE
[ERROR] Could not pass event PlayerInteractEvent to AdvancedEnchantments v9.9.17

### ISSUE THREAD

**Issue by WayzJust** [GC-spigot/AdvancedEnchantments#4494]
### Describe the bug

Opening the CE menu is ok and even the buy option works but when I try to right click it doesnt work. The custom enchant itself doesnt work. I have heard multiple other people also face issues with Event and Interaction.

Please help me out, I need this to work. Feel free to contact me on discord at wayz_me or join my server at mcmaniac.net
Looking forward to a favourable response

### How to reproduce

Not sure, we do not have any specific config

### "/ae plinfo" link

https://paste.md-5.net/uviyaricah

### Server Log

https://mcpaste.io/665148dd8c3fc713

**Comment by GC-spigot** [comment]
Please record a video and post it here :) https://gyazo.com/b9049b365993abed92f9726f6fd3bd89

**Comment by WayzJust** [comment]
Right clicking does nothing, I have uploaded console
https://gemoo.com/tools/upload-video/share/675470455264219136?codeId=DGY64L9qdxZQA&card=675470450960863232&origin=videolinkgenerator

**Comment by WayzJust** [comment]
Hey GC, any update?

**Comment by WayzJust** [comment]
hey?

**Comment by WayzJust** [comment]
How can you take over a week to respond to a bug, especially in a paid plugin. Are you trying to sell a real plugin or just acting like my developer who only solves easy bugs and not hard ones.

Please respond ASAP, feel free to send me a message on discord: wayz_me

**Comment by WayzJust** [comment]
02.08 16:32:37 [Server] INFO [AdvancedEnchantments] Loading server plugin AdvancedEnchantments v9.9.19
https://mcpaste.io/27b4a84b581a2e67
Some additional info while startup

**Comment by WayzJust** [comment]
This only happens in the 9.9.19 version! Console log given below

02.08 16:37:34 [Server] [INFO] Wayz_Playz issued server command: /ce
02.08 16:37:34 [Server] [ERROR] null
02.08 16:37:34 [Server] [INFO] org.bukkit.command.CommandException: Unhandled exception executing 'ce' in net.advancedplugins.ae.handlers.commands.EnchanterCommand(enchanter)
02.08 16:37:34 [Server] [INFO] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
02.08 16:37:34 [Server] [INFO] at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:999) ~[?:?]
02.08 16:37:34 [Server] [INFO] at org.bukkit.craftbukkit.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[?:?]
02.08 16:37:34 [Server] [INFO] at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
02.08 16:37:34 [Server] [INFO] at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.commands.execution.CommandQueueEntry.action(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:429) ~[?:?]
02.08 16:37:34 [Server] [INFO] at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[?:?]
02.08 16:37:34 [Server] [INFO] at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
02.08 16:37:34 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2200) ~[?:?]
02.08 16:37:34 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[?:?]
02.08 16:37:34 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[?:?]
02.08 16:37:34 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
02.08 16:37:34 [Server] [INFO] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1515) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:198) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[?:?]
02.08 16:37:34 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1492) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1415) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[?:?]
02.08 16:37:34 [Server] [INFO] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1381) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1242) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
02.08 16:37:34 [Server] [INFO] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
02.08 16:37:34 [Server] [INFO] Caused by: java.lang.IllegalStateException: zip file closed
02.08 16:37:34 [Server] [INFO] at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
02.08 16:37:34 [Server] [INFO] at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
02.08 16:37:34 [Server] [INFO] at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
02.08 16:37:34 [Server] [INFO] at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
02.08 16:37:34 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
02.08 16:37:34 [Server] [INFO] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
02.08 16:37:34 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
02.08 16:37:34 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
02.08 16:37:34 [Server] [INFO] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
02.08 16:37:34 [Server] [INFO] at AdvancedEnchantments-9.9.19 (2).jar/net.advancedplugins.ae.handlers.commands.EnchanterCommand.execute(EnchanterCommand.java:43) ~[AdvancedEnchantments-9.9.19 (2).jar:?]
02.08 16:37:34 [Server] [INFO] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
02.08 16:37:34 [Server] [INFO] ... 26 more

**Comment by ThomasWega** [comment]
Hey! I've just tried on latest 1.21 paper and AE, and all seems to work great! Make sure to use latest paper jar and AE, and you should be good to go. If you still have issues, just delete the AE folder and let the files recreate themselves

**Comment by WayzJust** [comment]
Did that, same error continues

**Comment by WayzJust** [comment]
Please open this ticket again\

**Comment by WayzJust** [comment]
https://mcpaste.io/df5722dc9f1a0768
LINE 483 onwards, please check it out!!!
