### ISSUE TITLE
Add support for Purpur Unsafe Enchants

### ISSUE THREAD

**Issue by MegaTKC** [GC-spigot/AdvancedEnchantments#4495]
### Describe the bug

Using AE 9.9.17.

I would like to Purpur's unsafe enchants config options to work with AdvancedEnchantments. Similarly to how it works with essentials. This option doesn't work because I've overrided the Anvil for Custom Enchants support. Some people might not choose to use Essentials.

### How to reproduce

Feature Request

### "/ae plinfo" link

https://purpurmc.org/docs/purpur/configuration/#allow-unsafe-enchants

**Comment by ThomasWega** [comment]
We'll be looking into this
