### ISSUE TITLE
Detonate enchant error

### ISSUE THREAD

**Issue by twist3d99** [GC-spigot/AdvancedEnchantments#4496]
### Describe the bug

When using the enchantment in game we are getting this error below

Failed to active effect 'BREAK_BLOCK_BLOCK'
Additional Informaiton: Failed to active effects as advancedEffect is null or invalid: 'BREAK_BLOCK_BLOCK, trigger: MINING, entity

### How to reproduce

enchant pickaxe with detonate and error occurs.

### Screenshots / Videos

https://imgur.com/GyuPezE 

### "/ae plinfo" link

https://paste.md-5.net/faxuxelozu

### Server Log

https://mcpaste.io/2166332d31f970c5

**Comment by ThomasWega** [comment]
This is an old format. Use `BREAK_BLOCK @Block`
