### ISSUE TITLE
Feature Request: Armor enchants can trigger weapons

### ISSUE THREAD

**Issue by DuplexLake** [GC-spigot/AdvancedEnchantments#4497]
### Describe the bug

so, to simply put it im using AE to make a kitPVP server, it's worked great so far but an issue I've noticed is enchants on weapons, I try to balance weapons, mainly bows to do more or less damage, issue is players can evade the penalties by swapping off the bow before the arrow hits. which us why I'm asking for there to be a feature/optional setting to let armor work with those enchant types. since I can then just put curse of binding on it and have no issues at all with how that's executed, will give an example issue in the future to show what I specifically mean

### How to reproduce

feature request ^

### "/ae plinfo" link

feature request for 1.21

**Comment by ThomasWega** [comment]
We'll be looking into this
