### ISSUE TITLE
Vein miner + Silktouch sometime gives raw material + ore version both

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#4499]
### Describe the bug

Vein miner + Silktouch sometime gives raw material + ore version both

### How to reproduce

Vein miner + Silktouch sometime gives raw material + ore version both

it just gives both rarely when mining with silktouch + vein miner pickaxe

### Screenshots / Videos

https://gyazo.com/5f60956a0731147d89dcec6fcf9a1015

gave raw redstone and raw copper + blocks when i mined using silktouch vein miner

### "/ae plinfo" link

https://paste.md-5.net/kaqazekeje

**Comment by ThomasWega** [comment]
Could be mcmmo incompatibility with their bonus drops. Update to latest, few versions back I've improved that. If it still happens, try without any other plugins.
