### ISSUE TITLE
Fireballs

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4501]
### Describe the bug

Fireballs Effect is not working

### How to reproduce

inferno:
  display: '%group-color%Inferno'
  description: Arrows turn into fireballs.
  applies-to: Bow
  type: BOW_FIRE
  settings:
    worldBlacklist:
      - "world"
      - "world_the_end"
    showActionBar: false
    not-applyable-with:
      - "infinity"
  group: EVENT
  applies:
    - BOW
  levels:
    '1':
      chance: 100
      cooldown: 10
      effects:
        - FIREBALL

Fireball is not sent

### "/ae plinfo" link

https://paste.md-5.net/badenuxetu

**Comment by GC-spigot** [comment]
Working on 1.21 as tested. You do not see the fireball, a fireball shoots at the mob/player once arrow hits.
