### ISSUE TITLE
Banner pattern type showing with some items

### ISSUE THREAD

**Issue by BirminghamBoy** [GC-spigot/AdvancedEnchantments#4505]
### Describe the bug

For Black Scroll and Randomisation Scroll items, when item type is set to banner pattern, the banner pattern type shows in lore.

Not the case for other item types as far as I can see.

### How to reproduce

Use configuration file below and give yourself relevant item(s).

https://mcpaste.io/355e51fabd078f47

### "/ae plinfo" link

https://paste.md-5.net/qiyobaboke

**Comment by ThomasWega** [comment]
We are missing an option to set itemflag on the items right now. Working on a fix. After it's done, you will need to add itemflag to the item in config. Specifically `HIDE_POTION_EFFECTS` one. Right here
<img width="677" alt="image" src="https://github.com/user-attachments/assets/f532c8a4-006a-4908-b933-37a5f34db1ba">

**Comment by ThomasWega** [comment]
Should be fixed in 9.9.19
