### ISSUE TITLE
I don't know they can create new enchantments 

### ISSUE THREAD

**Issue by StroidMods** [GC-spigot/AdvancedEnchantments#4506]
### Describe the bug

When a new enchantment is created in the enchants.yml, it cannot be reviewed in the game, create a 1x3 mining one and with reloads and restarts it throws errors, I already talked about it in the AdvancendEnchants discord and they asked me to speak on github

### How to reproduce

Create a new enchant for mining pickaxes or any enchant apparently and it doesn't work by typing /ae enchant name

### "/ae plinfo" link

/ae

**Comment by ThomasWega** [comment]
There needs to be an error. Something wrong with the new enchantment you've added. Send the full log please
