### ISSUE TITLE
Suggestion, re, applying dust 

### ISSUE THREAD

**Issue by BirminghamBoy** [GC-spigot/AdvancedEnchantments#4507]
### Describe the bug

Was told by support team in Discord that I could make this suggestion as a bug report.

Currently, if `mystery dust % + book success chance = >100%`, the dust will not apply. This has confused some players - I suggest implementing an error message AND/OR allow this to be disabled in config (i.e. dust can be applied in this situation as I don't see an issue with this).

### How to reproduce

N/A

### "/ae plinfo" link

N/A

**Comment by ThomasWega** [comment]
We'll be looking into this
