### ISSUE TITLE
Allow modification of GUI back button, etc.

### ISSUE THREAD

**Issue by BirminghamBoy** [GC-spigot/AdvancedEnchantments#4508]
### Describe the bug

Was told by support team in Discord that I could make this suggestion as a bug report.

GUI back button item type, name, lore etc. cannot be modified at present. It would be good to allow this. Same for any other GUI buttons/items that aren't currently modifiable.

### How to reproduce

N/A

### "/ae plinfo" link

N/A

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
