### ISSUE TITLE
FREEZE doesn't work

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4509]
### Describe the bug

iceaspect:
  display: '%group-color%Ice Aspect'
  description: |-
    Freezes enemies
  applies-to: Swords
  type: ATTACK;ATTACK_MOB
  group: ADMIN
  applies:
    - ALL_SWORD
  levels:
    '1':
      effects:
        - FREEZE:80 @Victim
    '2':
      effects:
        - FREEZE:160 @Victim

I used this, and when I hit the victim nothing happends, no freeze or anything. 

### How to reproduce

Use Purpur 1.21, and AE
Use this enchant
Hit Victim
Nothing Happends

### "/ae plinfo" link

https://paste.md-5.net/xovirupima

**Comment by ThomasWega** [comment]
Will be fixed in the next version
