### ISSUE TITLE
Permission slot not working

### ISSUE THREAD

**Issue by CryLegende** [GC-spigot/AdvancedEnchantments#451]
Hello ^^
I would like to add a slot for VIPs with permission "ae.limit.(count)" but permission does not seem to work

Config part:
https://pastebin.com/raw/pDSpm6NN

Permission: ae.limit.6
Server: (Paper)Spigot 1.12.2
Plugin: 5.6.0 (latest)

**Comment by GC-spigot** [comment]
Fixed!
