### ISSUE TITLE
Console multiple errors 

### ISSUE THREAD

**Issue by SpeedCrazy** [GC-spigot/AdvancedEnchantments#4510]
### Describe the bug

This error is causing my server to crash constantly.
Since my ram usage goes up and my server crashes.

### How to reproduce

"I don't know if it’s a bug with the AE that affects MCMMO or if it’s basically a bug with AE that constantly crashes my server."

### "/ae plinfo" link

https://paste.md-5.net/vecazipida

### Server Log

https://mcpaste.io/051b39f51abfa316

**Comment by GC-spigot** [comment]
Should be solved :)
