### ISSUE TITLE
Slot limiter by Group#2

### ISSUE THREAD

**Issue by JeffersonSerrano** [GC-spigot/AdvancedEnchantments#4511]
### Describe the bug

Hi^^ Good mornig.

6 moths ago i create a sugget called "Slot limiter by Group".
In discord an admin say to me that recreate the suggest on GitHub.
Thank you so  much! 

**SUGGEST**
Hello everyone, it would be great if you could limit the number of enchantments that an item in each group can have.

example:

Slot limit:
Ulti: 1
Epic: 2
Legendary: 3

Thank you so much! ^^

### How to reproduce

Adding enchants to an armor

### "/ae plinfo" link

https://pastebin.com/2pXRh4Sg

**Comment by GC-spigot** [comment]
We plan on having this added, but it requires a huge rework on slots which is not a priority right now, but there has been start on it :)
