### ISSUE TITLE
USE ENCHANTED TOOLS AND CONSOLE ERROR REPORT

### ISSUE THREAD

**Issue by iv3rins** [GC-spigot/AdvancedEnchantments#4512]
### Describe the bug

Console Error Reporting

### How to reproduce

This problem occurs when the player mines, and the player will also get a corresponding error when using slayer

### "/ae plinfo" link

https://paste.md-5.net/adokobikum

### Server Log

https://mclo.gs/NEJjxJt

**Comment by GC-spigot** [comment]
Fixed
