### ISSUE TITLE
Cannot invoke "org.bukkit.entity.LivingEntity.setFireTicks(int)" because "<parameter2>" is null

### ISSUE THREAD

**Issue by cloakfox** [GC-spigot/AdvancedEnchantments#4513]
### Describe the bug

https://gist.github.com/cloakfox/7cbf0ee90b6242d946725b0525d56b82

Using paper 1.20.4 with default AdvancedEnchantments config

### How to reproduce

No idea how to reproduce this, I assume this happens when a player uses some enchantment that has the burn effect

### Screenshots / Videos

https://gist.github.com/cloakfox/7cbf0ee90b6242d946725b0525d56b82

### "/ae plinfo" link

https://paste.md-5.net/fanerawiru

**Comment by ThomasWega** [comment]
is probably the inflame enchant. WIll be fixed next update. It's using an outdated formatting
