### ISSUE TITLE
[AdvancedEnchantments ERROR] Could not pass ClassCastException

### ISSUE THREAD

**Issue by ArdayraL** [GC-spigot/AdvancedEnchantments#4514]
### Describe the bug

I get this error when using enchants on my server and the condition "%is critical% = true : %allow%" gives an invalid error.

What is this error and how can I solve it?

### How to reproduce

1. Start Server
2. A player uses enchants
3. plugin gives error

### "/ae plinfo" link

https://paste.md-5.net/uvucehugih

### Server Log

https://mcpaste.io/4cc6a0382d53145a

**Comment by ThomasWega** [comment]
Try 9.10.0 please

**Comment by ArdayraL** [comment]
my problem is solved thank you <3

**Comment by ThomasWega** [comment]
Np. Thanks for reporting :)
