### ISSUE TITLE
Error using /tinker menu

### ISSUE THREAD

**Issue by TopicflyOffi** [GC-spigot/AdvancedEnchantments#4515]
### Describe the bug

Hello, when we set the category "tinkerer-confirm-trade-item:" to false to deactivate the item and we restart, the menu becomes buggy, we can no longer accept/confirm the change of the enchantment in powder.

### How to reproduce

Change the category "tinkerer-confirm-trade-item:" to false to bug the menu.

### Screenshots / Videos

Video of the menu without the bug: https://youtube.com/shorts/xCHP470XOeY?feature=share:

Video of the menu with the bug: https://youtube.com/shorts/3c-REjMVeQI

### "/ae plinfo" link

https://paste.md-5.net/dipoferula

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Or if you need it to work now, you can also disable `enabled-confirm-items` and you should be good to go
