### ISSUE TITLE
On 1.19.3 MC version: ERROR Could not pass event BlockBreakEvent to AdvancedEnchantments v9.10.0

### ISSUE THREAD

**Issue by Risingem** [GC-spigot/AdvancedEnchantments#4516]
### Describe the bug

Updated the plugin version and now i get ERROR messages. Few of the enchants not working.
[message.txt](https://github.com/user-attachments/files/16480600/message.txt)

### How to reproduce

Have MC version 1.19.3
Update the plugin
For example try to use trench

### "/ae plinfo" link

https://paste.md-5.net/nemipuhidu

**Comment by ThomasWega** [comment]
update your mcmmo to latest
