### ISSUE TITLE
DISARM effect giving error.

### ISSUE THREAD

**Issue by LioneLONeiL** [GC-spigot/AdvancedEnchantments#4518]
### Describe the bug

When DISARM effected Enchant triggers it gives error.

### How to reproduce

Add DISARM enchant to sword and trigger it.

### Screenshots / Videos

https://imgur.com/undefined

### "/ae plinfo" link

https://paste.md-5.net/lovutiquma

### Server Log

https://mcpaste.io/cb27d64c6288aed3

**Comment by ThomasWega** [comment]
You are using the DISARM effect without providing a valid target. Like @Attacker or something. Also need to be on a valid trigger

**Comment by LioneLONeiL** [comment]
Fixed on Discord ticket.

Neutralize was causing it. With air shot and effect activated.
