### ISSUE TITLE
Console spam | How to fix it

### ISSUE THREAD

**Issue by dzakwaniqbal** [GC-spigot/AdvancedEnchantments#4519]
### Describe the bug

the error is spam brutally
make my server ram full continuously

### How to reproduce

How to fix it

### Screenshots / Videos

![Screenshot_600](https://github.com/user-attachments/assets/1dd54024-5963-4ff5-b7db-b569eddd6a17)

### "/ae plinfo" link

https://paste.md-5.net/xayaselica

**Comment by SirJben** [comment]
Update your plugin.
