### ISSUE TITLE
model data

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#4520]
### Describe the bug

that it is possible to put skins on the books when we receive them, for example, the SIMPLE group, is a skin of 1 pink book, allow that when I open an orb, it comes with the pink skin

video: https://youtu.be/qBCux-fmgQw

allow me to define a model per group, like in the video when I take an orb of the simple book and open it, the pink book comes too, if it's single it comes with the green book with model...

### How to reproduce

no

### "/ae plinfo" link

no

**Comment by leogianfagna** [comment]
As far I know, this is already possible #3877

**Comment by SrMonsterYT** [comment]
> As far I know, this is already possible #3877

I tried and it didn't work, the ticket told me it's not possible, the idea is to get the book and come up with a skin, like the ones in the GUI, the only one who can help us is @GC-spigot

**Comment by ThomasWega** [comment]
You can just reuse the textures and their custom model datas on the books. Exactly as @leogianfagna linked
