### ISSUE TITLE
MiningTrigger performance issue

### ISSUE THREAD

**Issue by LPPRR123** [GC-spigot/AdvancedEnchantments#4521]
### Describe the bug

I don have any of Mining enchantments.B
But the MiningTrigger still taking up a lot of resources in my prison server. and cause lag.
Is it possible to disable AE's mining events without any mining enchantments to improve performance?

### How to reproduce

I don have any of Mining enchantments.B
But the MiningTrigger still taking up a lot of resources in my prison server. and cause lag.
Is it possible to disable AE's mining events without any mining enchantments to improve performance?

### Screenshots / Videos

![feca09b9b28c101fdeea273ef25f7b2f](https://github.com/user-attachments/assets/d34d946d-fd58-4ff7-8a1c-a4d10cdaca7b)

### "/ae plinfo" link

https://paste.md-5.net/igodadomup

**Comment by LPPRR123** [comment]
![image](https://github.com/user-attachments/assets/10767b9e-416c-4f06-b846-709d2f093bbb)
newest version same

**Comment by GC-spigot** [comment]
Please post the full spark report so we can investigate, run it for at least 30 minutes.
