### ISSUE TITLE
There was a problem with the original Luck of the Sea III enchantment.

### ISSUE THREAD

**Issue by NEIKI19914** [GC-spigot/AdvancedEnchantments#4523]
### Describe the bug

![image](https://github.com/user-attachments/assets/b6fa2b92-c169-43ef-b5e5-1e591d403194)
![image](https://github.com/user-attachments/assets/6df4fad7-f534-419b-9621-e8b78367592e)

### How to reproduce

Same problem as Bow Power 2.

### "/ae plinfo" link

https://paste.md-5.net/uwomavorus

**Comment by ThomasWega** [comment]
Hey! I have just tried it out and works absolutely fine for me. Latest AE, latest 1.21 Paper

**Comment by ThomasWega** [comment]
check your anvil.yml. Maybe it's just actually set to 2 there

**Comment by NEIKI19914** [comment]
> check your anvil.yml. Maybe it's just actually set to 2 there

![image](https://github.com/user-attachments/assets/4e7f0b3b-4686-4a55-81bd-9fa3e1a4e029)
![image](https://github.com/user-attachments/assets/ba444b72-66c2-4a02-945a-2468b28d601b)
I checked and it was indeed set to 3, but in the server it was only 2. It was the same problem as the previous bow power of 5.

**Comment by ThomasWega** [comment]
Weird I cannot replicate it. Try looking for other enchantments that are set at 2 in the anvil.yml and change them to for example 1. Do this one by one, and let me know which one affects the luck

**Comment by NEIKI19914** [comment]
I can't understand it. It's obvious that there is a problem but I closed my question.
