### ISSUE TITLE
[AdvancedEnchantments] Task #5146834 for AdvancedEnchantments v9.10.0 generated an exception

### ISSUE THREAD

**Issue by Jameskarl28** [GC-spigot/AdvancedEnchantments#4526]
### Describe the bug

it keeps popping up idk how to fix please help

### How to reproduce

this issue causes cpu usage rise up like hell

### "/ae plinfo" link

https://paste.md-5.net/inijojijon

### Server Log

https://mclo.gs/TuvtP06

**Comment by Jameskarl28** [comment]
![image](https://github.com/user-attachments/assets/60cf043d-e44d-4ce2-8266-5f8d3a4c6161)

**Comment by ThomasWega** [comment]
We need the full log, so we can see where this happens. This is not enough info

**Comment by GC-spigot** [comment]
Should be solved
