### ISSUE TITLE
Items adder custom armor doesnt work with durability effects

### ISSUE THREAD

**Issue by CuprizeDev** [GC-spigot/AdvancedEnchantments#4527]
### Describe the bug

Items adder armor is not compatible with add durability! This enchant works on regular netherite armor, but not items adder armor!

hellforge:
  display: '%group-color%Hellforge'
  description: Armor takes less durability damage.
  applies-to: Armor
  type: DEFENSE
  group: RARE
  applies:
  - ALL_ARMOR
  levels:
    '1':
      chance: 25
      cooldown: 7
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:1 @Victim
    '2':
      chance: 35
      cooldown: 7
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:1 @Victim
    '3':
      chance: 50
      cooldown: 7
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:5 @Victim

### How to reproduce

Create custom armor with items adder, add this enchantment to it:

hellforge:
  display: '%group-color%Hellforge'
  description: Armor takes less durability damage.
  applies-to: Armor
  type: DEFENSE
  group: RARE
  applies:
  - ALL_ARMOR
  levels:
    '1':
      chance: 25
      cooldown: 7
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:1 @Victim
    '2':
      chance: 35
      cooldown: 7
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:1 @Victim
    '3':
      chance: 50
      cooldown: 7
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:5 @Victim
        
   instead of adding durability, it removes durability.
   
  eceventhelmet:
    display_name: Event Helmet # Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol6/eceventhelmet.png
    durability:
      max_custom_durability: 407
    specific_properties:
      armor:
        slot: head
        custom_armor: eceventarmor
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
        knockback_resistance: 0.1

### "/ae plinfo" link

https://paste.md-5.net/etizamuxiv

### Server Log

no logs

**Comment by ThomasWega** [comment]
Should be fixed in the next update
