### ISSUE TITLE
Item NameTag Length request

### ISSUE THREAD

**Issue by SliderKP** [GC-spigot/AdvancedEnchantments#4528]
### Describe the bug

Can add a possibilitie to edit the amount of max characters to use on NameTag? i want to set more.

Thank you.

### How to reproduce

Use nametag, put more thank 26 char and get messaging, saying the name is too long.

add an option like:
max-character: 64

### "/ae plinfo" link

notNeccesary

### Server Log

notNeccesary

**Comment by GC-spigot** [comment]
Search for `itemnametag-max-name-length` in config.yml, it will be under `settings` at the bottom of file :)
