### ISSUE TITLE
Allow setting so you limit vanilla and custom enchants

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4529]
### Describe the bug

Add in so we can add restrictions between custom enchants and vanilla enchants

### How to reproduce

Was told to go here

### "/ae plinfo" link

ddffe

**Comment by ThomasWega** [comment]
What exactly are you looking for? You need to explain in more detail

**Comment by Cryptics1999** [comment]
Lets say I have a enchant called Ice Aspect, there is already a feature to make it not applyable with other custom enchants. Coud you add in so you can restrict this enchant the same way with Vanilla enchants also.

For Example I dont want Ice Aspect and Fire Aspect to be mixed in enchantmenttables, anvils or villager trades
________________________________
Fra: ThomasWega ***@***.***>
Sendt: torsdag 8. august 2024 11:47
Til: GC-spigot/AdvancedEnchantments ***@***.***>
Kopi: Cryptics1999 ***@***.***>; Author ***@***.***>
Emne: Re: [GC-spigot/AdvancedEnchantments] Allow setting so you limit vanilla and custom enchants (Issue #4529)


What exactly are you looking for? You need to explain in more detail

**Comment by ThomasWega** [comment]
it should already work with vanilla enchantments as well. Also in anvil etc.
https://ae.advancedplugins.net/enchantments/creating-enchantments/settings#required-enchants
