### ISSUE TITLE
BlockTrak tracks blocks "broken" in WorldGuard regions

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#453]
When a player tries to break a block in a WorldGuard protected region where they cannot build, it still adds one to their BlockTrak count. Since Worldguard stops them from breaking the block, it also does not remove item durability, so they can AFK and hold left click to get infinite BlockTrak counts.

**Comment by GC-spigot** [comment]
Do enchantments process as well?

**Comment by GC-spigot** [comment]
Patched!
