### ISSUE TITLE
Tinker secret dust cannot be stacked

### ISSUE THREAD

**Issue by ceze88** [GC-spigot/AdvancedEnchantments#4530]
### Describe the bug

Hi! Found an issue in 1.21. Plugin version 9.10.0. Issue is with thinker. When it gives the secret dusts back for the enchanted books they cannot be stacked as it was the case before we updated to 1.21.

The issue is with "addribute_modifiers" component, they have a "add_value" component which has a random UUID causing the items cannot be stacked.

### How to reproduce

Put enchanted books from the same rarity to the tinker and exchange them. 

### Screenshots / Videos

![kép_2024-08-07_121256966](https://github.com/user-attachments/assets/dfbd14dd-e0e0-463f-b9b7-63b0cc5aebe0)

### "/ae plinfo" link

https://paste.md-5.net/feyugegale

**Comment by ThomasWega** [comment]
Should be fixed in the next update
