### ISSUE TITLE
An internal erorr

### ISSUE THREAD

**Issue by kingjackk01** [GC-spigot/AdvancedEnchantments#4531]
### Describe the bug

![2024-08-07_08 19 11](https://github.com/user-attachments/assets/a40d7107-983b-4b95-a21b-a0360e4787ac)

### How to reproduce

eror i dont know why , and disable 

### "/ae plinfo" link

conot

### Server Log

https://mcpaste.io/835c94c43c93309c

**Comment by SirJben** [comment]
Open a Discord Ticket. https://discord.gg/advancedplugins

**Comment by kingjackk01** [comment]
i aready 5 time open support cnot help me
