### ISSUE TITLE
players can apply same enchant more than once by 

### ISSUE THREAD

**Issue by AlFr3on111** [GC-spigot/AdvancedEnchantments#4533]
### Describe the bug

i found player have pickaxe with same enchant twice and sword with same enchants 5 times and all what happened is he drag and onto the item

the enchants are from /enchanter 
enchantment-table is disabled
anvil is disabled too
![image](https://github.com/user-attachments/assets/b72a41a7-06c8-4cf3-88c0-3c0b6a9a0351)

### How to reproduce

do /enchanter and get two enchants same name same numbers and drag and drop onto the item as u can see in this pic
![image](https://github.com/user-attachments/assets/a1becc7b-5ebf-44e7-ad07-c033370229f4)

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/cdad7f73-c259-42b1-b5a7-c9a31b1e72f0)

### "/ae plinfo" link

https://paste.md-5.net/sicoricixa

### Server Log

https://mcpaste.io/0256ebccbd954538

**Comment by ArdayraL** [comment]
You can try updating the plugin

**Comment by ThomasWega** [comment]
I have just tried it out and works completely fine. Try on latest, with latest server jar and fresh AE files

**Comment by AlFr3on111** [comment]
> I have just tried it out and works completely fine. Try on latest, with latest server jar and fresh AE files

i did and works fine but when u add one enchant it gives u the enchant twice 

in this pic i just added one enchant book and i got two enchants 
![image](https://github.com/user-attachments/assets/cdf0a819-11c9-4f08-94e4-881a7b7076ca)
