### ISSUE TITLE
Bug with crossing enchantments

### ISSUE THREAD

**Issue by op-lum1x** [GC-spigot/AdvancedEnchantments#4534]
### Describe the bug

When crossing two identical custom enchantments at level 5, everything works and everything is crossed. but when I tried to combine enchantments for the eighth and ninth level in the anvil, it didn’t work out for me

### How to reproduce

Crossing items that have enchantments of the same level 

### "/ae plinfo" link

https://paste.md-5.net/ogezexokab

**Comment by op-lum1x** [comment]
Video bug: https://streamable.com/wxdi3k
![image](https://github.com/user-attachments/assets/764032fa-dd50-4ccb-a02e-e7a37b7d52e9)
![image](https://github.com/user-attachments/assets/621e1dc7-4980-41df-b3eb-91f34b38b11f)

**Comment by ThomasWega** [comment]
update to latest
