### ISSUE TITLE
Lava walker radius

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4535]
### Describe the bug

![image](https://github.com/user-attachments/assets/84c82e29-fa9a-4c1d-bf49-70fdeb8e46f0)
Set this to 5 and its still the default size

### How to reproduce

set to 5
walk
still small

### "/ae plinfo" link

https://paste.md-5.net/iredexidan

**Comment by ThomasWega** [comment]
confirmed. In the next update, it will work, but not with this config section, but rather like this `LAVA_WALKER:4`. Just use it directly in the effect
