### ISSUE TITLE
internal eror , plugin disable

### ISSUE THREAD

**Issue by kingjackk01** [GC-spigot/AdvancedEnchantments#4537]
### Describe the bug

[latest.log](https://github.com/user-attachments/files/16537221/latest.log) wfwfg
 

### How to reproduce

please help me i know why plugin disable

### Screenshots / Videos

![2024-08-07_08 19 11](https://github.com/user-attachments/assets/27a2057a-356c-490c-ab3b-15f9d35ebc47)

### "/ae plinfo" link

internal erorr

### Server Log

file:///C:/Users/USER/Downloads/latest%20(2).log

**Comment by ThomasWega** [comment]
There is no error about AE in the config. It might not be the full log

**Comment by GC-spigot** [comment]
Try running /advancedenchantments, remove ExcellentEnchants. AdvancedEnchantments is not disabled on the server, this may be related to something else.
