### ISSUE TITLE
 force-glow: true , no work

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#454]
white-scroll

force-glow: true , no work
check

![image](https://user-images.githubusercontent.com/5382252/57577625-d3051280-74ad-11e9-97d4-c3b846d2250c.png)

and
![image](https://user-images.githubusercontent.com/5382252/57577646-57579580-74ae-11e9-8f86-2ee241a6f296.png)

^A , This strange symbol will appear
Please fix

**Comment by GC-spigot** [comment]
Fixed!
