### ISSUE TITLE
'ITEMSTACK_SET_TAG'

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4541]
### Describe the bug

It is not a bug or I do not know how to reproduce it, I only have this error in the console from time to time

### How to reproduce

I can't find a way to reproduce this

### Screenshots / Videos

https://mclo.gs/sx75iX9

### "/ae plinfo" link

https://paste.md-5.net/wiroraquna

**Comment by GC-spigot** [comment]
Fixed!
