### ISSUE TITLE
Merging items in anvil

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4543]
### Describe the bug

![image](https://github.com/user-attachments/assets/c3c35170-36c0-40ce-a2d7-a8460b21ce10)
![image](https://github.com/user-attachments/assets/2ae73e11-aa3f-4db3-946b-c09b304f4fd0)
Gets merged when the first item has no enchant, but if swapped around dont work
![image](https://github.com/user-attachments/assets/661aa14a-ff9f-4311-b3c0-5748aec40e86)

### How to reproduce

^^^

### "/ae plinfo" link

https://paste.md-5.net/cimuhucozo

**Comment by ThomasWega** [comment]
Will be fixed in the next update
