### ISSUE TITLE
Telepathy

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4546]
### Describe the bug

When using Telepathy on Netherrite it gives you Nether Brick

### How to reproduce

1.21 Java
AE
TP Drop

### "/ae plinfo" link

https://paste.md-5.net/ituraxisuq

**Comment by GC-spigot** [comment]
Cannot recreate, check your other plugins: https://gyazo.com/db9bea8bec2a28a47f463ce7edc1b90b
