### ISSUE TITLE
Veinminer and TP Drops

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4547]
### Describe the bug

When using Veinminer with TP Drops it dont sends the blocks you get from veinminer to inventory

### How to reproduce

1.21 purpur
ae

### "/ae plinfo" link

https://paste.md-5.net/ituraxisuq

**Comment by GC-spigot** [comment]
I cannot recreate it, try updating later today when 9.10.4 is posted.
