### ISSUE TITLE
There's so much information showing up in my console and in-game!

### ISSUE THREAD

**Issue by jmox000** [GC-spigot/AdvancedEnchantments#4548]
### Describe the bug

Hello, can you help me with this? My console is getting spammed with information like this.

"[06:52:43 WARN]: java.lang.ClassCastException
[06:52:43 INFO]: [AdvancedEnchantments ERROR] Could not pass ClassCastException: 
[06:52:43 INFO]:    Class: 
[06:52:43 INFO]:    Extra info: Invalid condition: %mob type% = skeleton : %allow%; mc[1204];
[06:52:43 INFO]: If you cannot indentify cause of this, contact developer providing this report. "

This started when I updated to the latest version of the plugins. Even in-game, there's a lot of information being spammed, and I don't know how to remove it because it's really disrupting the game, especially in the console. Please help me fix this issue.

My server version is 1.20.4.
ae plugins: latest version

### How to reproduce

This started when I updated to the latest version of the plugins. Even in-game, there's a lot of information being spammed, and I don't know how to remove it because it's really disrupting the game, especially in the console. Please help me fix this issue.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/302d34e5-8142-40e9-a87c-46f98aa93e04)
![image](https://github.com/user-attachments/assets/6d451c63-fd41-4a00-a99f-fc7cf6e59755)

https://github.com/user-attachments/assets/de07a4d8-3d64-47b7-bca6-46b07262bcec

### "/ae plinfo" link

https://paste.md-5.net/gabevitoki

### Server Log

https://mcpaste.io/bbf2cc32581dcc0c

**Comment by GC-spigot** [comment]
Solved latest update!
