### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by En0tS** [GC-spigot/AdvancedEnchantments#455]
Hi! I urgently need feature to edit enchantments look in item lore. I need something like this:

```
Addons:
- Enchantment 1 (with level and name placeholders)
- Enchantment 2 (with level and name placeholders)
%item-lore%
```

**Comment by GC-spigot** [comment]
This is extremely complicated since you can just switch up lores with other plugins. Ill leave this open but I don't think this will be implemented soon.

**Comment by En0tS** [comment]
Can you tell me what plugin I can use to make split vanilla enchantments and AE enchantments in this way?

**Comment by En0tS** [comment]
Auto split when player adding new AE enchantment, not predefined items.

**Comment by GC-spigot** [comment]
Vanilla enchants are not lore text, it's a render of client. Lore is not, it's change-able text which shows my enchants. Splitting is "pointless" since it's already done by your minecraft client.

**Comment by En0tS** [comment]
No, I mean add some lore lines between vanilla enchantments and AE lore. Cause by default AE lore goes after vanilla enchantments.
