### ISSUE TITLE
Soulbound/keepinventory claimflag 

### ISSUE THREAD

**Issue by blakehamiltons** [GC-spigot/AdvancedEnchantments#4550]
### Describe the bug

When soulbound is active and keep inventory is also active it dupes items i don’t know if there is a method to call out “if keepinventory active disable soulbound on death” keepinventory is a griefprevention claimflag 

### How to reproduce

Install grief prevention set claimflag as keepinventory then die with soulbound items with 0 delay since people could have multiple items 

### "/ae plinfo" link

https://paste.md-5.net/xibinexuve

**Comment by ThomasWega** [comment]
update to latest and you should be good. If GriefDefender sets keep inventory on death event, which it should.
