### ISSUE TITLE
Errors then plugin in Red

### ISSUE THREAD

**Issue by Acetaminofenuwu** [GC-spigot/AdvancedEnchantments#4551]
### Describe the bug

I used the command: /ae premade and downloaded all the enchantments from the 3 sections. the plugin turned red and an error came up.

### How to reproduce

I used the command: /ae premade and downloaded all the enchantments from the 3 sections one by one. When I downloaded the last one from SkyBlock I shut down the server and when I opened it the plugin turned red and an error came up

### Screenshots / Videos

I have the log below.

### "/ae plinfo" link

I can’t the plugin is in red. My server is 1.20.4 and plugin ver is 9.10.3

### Server Log

https://mclo.gs/6WBn12M

**Comment by GC-spigot** [comment]
Delete your customcommands.yml file from advancedenchantments folder, this should solve it temporarily!
