### ISSUE TITLE
[AdvancedEnchantments] Task #6506 for AdvancedEnchantments v9.10.3 generated an exception

### ISSUE THREAD

**Issue by FourNineRugz** [GC-spigot/AdvancedEnchantments#4552]
### Describe the bug

![image](https://github.com/user-attachments/assets/4c78f911-e5e7-4b07-9b36-c451269c60b8)

https://mclo.gs/ceJgKSZ

### How to reproduce

All I do is right click with an empty hand into air and I get this error.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/4c78f911-e5e7-4b07-9b36-c451269c60b8)

### "/ae plinfo" link

https://paste.md-5.net/yulanusisa

**Comment by GC-spigot** [comment]
Solved next update!
