### ISSUE TITLE
/enchanter menu linking makes strange behaviour and change the clicks to some other enchant tiers (video provided)

### ISSUE THREAD

**Issue by pjindras** [GC-spigot/AdvancedEnchantments#4553]
### Describe the bug

Plugin version: 9.10.0
Server version: 1.20.4

Hello, we have a problem that we have a menu enchanter.yml in the game and there we have defined:

https://paste.gg/p/anonymous/c74d1d59d9e7417db57021006513be63

and from time to time it does this thing that it overwrites the place of the "ultimate" and "legendary" enchanter, that there is a unique one everywhere and we don't know why and what it is, after /ae reload it gets fixed again for a while and then it happens again

we also tested it with default (itemsadder) menu from advanced enchants (without our edits) and it has the same issue.

It does not show any error -> the plugin AE
I am sending the menu file; there is no error or any mistake, or I cannot see anything, what could cause the issue
this is plugin behavior, that it changes menus and the clicks without any rationality, so its strange :D

### How to reproduce

I really dont know, on our testing server, there is no issue, on live (survival) server, this issue occures.

### Screenshots / Videos

https://github.com/user-attachments/assets/eddfc6f5-4d89-4414-ba67-847e9cfe5892

### "/ae plinfo" link

https://paste.md-5.net/oninaxiyif

**Comment by pjindras** [comment]
video was made by our moderators with our menu on live server (with transations and edits, but after talk with moderator, we also tested default menu without edits and it is the same)

**Comment by GC-spigot** [comment]
As discussed on discord, may be fixed but keep us informed with next update.

**Comment by ThomasWega** [comment]
any update @pjindras ?

**Comment by pjindras** [comment]
> any update @pjindras ?

Unfortunately, the issue still exists, we contacted your discord support.

**Comment by Z3r0xh** [comment]
I have the same problem, from certain connected users the problem occurs

**Comment by Z3r0xh** [comment]
It seems that if you change the group type it stops having persistence and is removed.

https://pastebin.com/ckZPbGwX

**Comment by ThomasWega** [comment]
> It seems that if you change the group type it stops having persistence and is removed.
> 
> https://pastebin.com/ckZPbGwX

I have afked for like 30 mins with this config, and no change. Needs to be caused by some player interaction. Can all of you please do some more testing? It's impossible for me to figure it out this way

**Comment by ThomasWega** [comment]
More people have this issue. So the bug is there for sure. Just need someone to find out when exactly is happens

**Comment by Z3r0xh** [comment]
What I have found is that we all have the groups file modified, changing the fable or mysteri for another group.

Then the problem is when there are many users interacting at the same time then the plugin breaks

**Comment by Z3r0xh** [comment]
#4463 
@GC-spigot 
This error has been occurring since July, in the contribution some more information regarding the failures

**Comment by ThomasWega** [comment]
We are trying our best to reproduce it, but we don't have servers with many active players and so far we have not been able to reproduce it

**Comment by Z3r0xh** [comment]
> We are trying our best to reproduce it, but we don't have servers with many active players and so far we have not been able to reproduce it

It has been causing problems since versions 9.9.13-9.9.14-9.9.15, and the error started in one of these versions. I remember that in one of these versions I regenerated the file and the mastery file appeared, I think the error comes from that version.

Anyway, if you don't have a way to reproduce the error, I can lend my server or use versions with debugs so you can find the error. But it's been 3 months with this problem, this means errors when buying with exp and makes the administration have to be giving orbs manually without being able to check if the error is true or not (this means abuse by some players because there is no way to check it).

Those of us who are affected by the issue of modifying groups, can surely start using versions with debugs until we find the problem.

**Comment by ThomasWega** [comment]
Issue was figured out. Will be fixed in the next update
