### ISSUE TITLE
Advanced enchant on wiki dont work

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4554]
### Describe the bug

teleport:
  display: '%group-color%Teleport'
  description: 'Teleport 8 blocks into the direction you''re facing'
  applies-to: 'Swords'
  group: 'ULTRA'
  type: 'RIGHT_CLICK'
  applies:
    - ALL_SWORD
  levels:
    1:
      chance: 100
      cooldown: 0
      effects:
        - '%changeoutput_equals_{player_direction}_N_TELEPORT location=~0|0|-8_WAIT:0%'
        - '%changeoutput_equals_{player_direction}_NE_TELEPORT location=~6|0|-6_WAIT:0%'
        - '%changeoutput_equals_{player_direction}_E_TELEPORT location=~8|0|0_WAIT:0%'
        - '%changeoutput_equals_{player_direction}_SE_TELEPORT location=~6|0|6_WAIT:0%'
        - '%changeoutput_equals_{player_direction}_S_TELEPORT location=~0|0|8_WAIT:0%'
        - '%changeoutput_equals_{player_direction}_SW_TELEPORT location=~-6|0|6_WAIT:0%'
        - '%changeoutput_equals_{player_direction}_W_TELEPORT location=~-8|0|0_WAIT:0%'
        - '%changeoutput_equals_{player_direction}_NW_TELEPORT location=~-6|0|-6_WAIT:0%'

This enchant on the wiki dont work in 1.21

### How to reproduce

Use this enchant, try to right click dont work

### "/ae plinfo" link

https://paste.md-5.net/ucajamazek

**Comment by GC-spigot** [comment]
This requires more from you - installing the correct PlaceholderAPI extensions. It's an example in the wiki but you do need to figure out those extensions as well.
