### ISSUE TITLE
ArmorEquipEvent

### ISSUE THREAD

**Issue by Latestion** [GC-spigot/AdvancedEnchantments#4555]
### Describe the bug

1. Cancelling ArmorEquipEvent does not work
2. AE should not be handling the sub events ( InventoryClickEvent, PlayerInteractEvent ) -> if they are already cancelled, this removes the scope of other plugins work together.

The reason:
Cancelling the ArmorEquip still gives players BUFFS/DE-BUFFS.

### How to reproduce

Wear any armor which gives you an potion effect
cancel the event
and it will still give you the buffs

### "/ae plinfo" link

https://paste.md-5.net/vameneruva

**Comment by GC-spigot** [comment]
What ArmorEquipEvent are you cancelling? We have our own internal one, not any paper one etc.

**Comment by Latestion** [comment]
> What ArmorEquipEvent are you cancelling? We have our own internal one, not any paper one etc.

The one provided by AE

**Comment by ThomasWega** [comment]
Should be fixed in the next update
