### ISSUE TITLE
High efficiency value is not instabreaking ItemsAdder Custom Blocks.

### ISSUE THREAD

**Issue by lodylu** [GC-spigot/AdvancedEnchantments#4556]
### Describe the bug

As described in the title, i'm having this issue:
I can't instamine custom blocks added from ItemsAdder, that's a big issue because it's stopping me from giving that "full custom touch" to my Box server.

I need to be able to instabreak blocks AND i don't know if this is an issue given by ItemsAdder or by AdvancedEnchantments.

### How to reproduce

Use a only 1.20.4 paper.jar server
Install EssentialsX
Install ItemsAdder 3.6.4-release-3.jar
Install AdvancedEnchantments-9.10.3.jar
Provide your /plugins/ItemsAdder/contents/ with the default_pack and OtherPacks given as ItemsAdder resources on their GitHub ( https://github.com/ItemsAdder/DefaultPack/releases AND https://github.com/ItemsAdder/OtherPacks/releases )
Make sure to use Custom Blocks from ItemsAdder (Ores and Blocks with REAL_NOTE and NOTE are the targeted blocks)
Give yourself a Stone, Iron, Diamond or Netherite Pickaxe with efficiency 25, efficiency 50, efficiency 75, efficiency 100, efficiency 200
Try mining custom ores such as iasurvival ores (command: /ia -> iasurvival OR /iaget iasurvival: then press TAB to autofill)

### "/ae plinfo" link

https://paste.md-5.net/ojoqoxisiq

### Server Log

https://mcpaste.io/a815e59148ca9993

**Comment by GC-spigot** [comment]
This does sound like an itemsadder issue, efficiency enchantment is in no way related to us and is never handled by us. It may be likely that it's impossible for itemsadder to handle the speed of breaking the same way as normal blocks would with high efficiency.

**Comment by lodylu** [comment]
So you think that it's a limitation of ItemsAdder?

**Comment by GC-spigot** [comment]
Yes definitely
