### ISSUE TITLE
Plug-in causes Luck of the Sea and Density enchantment exceptions.

### ISSUE THREAD

**Issue by NEIKI19914** [GC-spigot/AdvancedEnchantments#4557]
### Describe the bug

![image](https://github.com/user-attachments/assets/5ba6daed-0306-4acf-93c1-6c871b2de5fb)
![image](https://github.com/user-attachments/assets/bd439faa-f0dd-4089-838d-25428e568215)
![image](https://github.com/user-attachments/assets/6951904e-5350-4d98-a016-8d36daecf0c4)
Will Level 5 Density become Level 3 after being enchanted with a weapon?
Luck of the Sea is still having issues, along with the bow's strength enchantment. When the bow's strength enchantment issue was fixed and it's still having issues, the developers closed my issue without changing any of my configurations. The default configuration of the plugin, don't try to close my issue to solve the problem.
https://github.com/GC-spigot/AdvancedEnchantments/issues/4523

### How to reproduce

There is a level issue when Density enchantment is synthesized and enchanted on items. Don't forget Luck of the Sea.

### "/ae plinfo" link

https://paste.md-5.net/uwomavorus

**Comment by GC-spigot** [comment]
Looking into this!

**Comment by NEIKI19914** [comment]
AdvancedEnchantments-9.10.6

> Looking into this!

AdvancedEnchantments-9.10.6 still does not solve this problem.

**Comment by GC-spigot** [comment]
We're aware, this is still being investigated, We may have found the problem, now testing internally.

**Comment by NEIKI19914** [comment]
AdvancedEnchantments-9.10.8 still has this problem.

**Comment by NEIKI19914** [comment]
Hasn't the problem been solved yet?

**Comment by ThomasWega** [comment]
https://github.com/user-attachments/assets/ee2ce312-6330-4cf8-984c-a78a9d30ebcb

**Comment by ThomasWega** [comment]
I've tested multiple times and worked okay every time. I've even debugged the code and everything is okay there. The power ench issue was a typo in the code. This is not

**Comment by NEIKI19914** [comment]
In a certain update, the enchantment limit in the anvil.yml file was increased. After comparing the file contents with the recent updates, there is no problem.

> I've tested multiple times and worked okay every time. I've even debugged the code and everything is okay there. The power ench issue was a typo in the code. This is not
