### ISSUE TITLE
[Suggestion] Limit item enchant

### ISSUE THREAD

**Issue by RageOfFire** [GC-spigot/AdvancedEnchantments#4560]
### Describe the bug

no bug

### How to reproduce

Hope can it possible to limit per item per group enchant ?
For example one item can have:
allow 3 enchant simple but only 1 enchant legendary

### "/ae plinfo" link

NaN

**Comment by GC-spigot** [comment]
Hi! This has been requested many times and we have it in our to-do list, it's not yet possible
