### ISSUE TITLE
Soulbound Dupe when using AE in combination withAuraSkills

### ISSUE THREAD

**Issue by Tizooo** [GC-spigot/AdvancedEnchantments#4563]
### Describe the bug

If using AE and AuraSkills its possible to dupe Soulbound items.

Tested on paper/pufferfish 1.21/1

### How to reproduce

have AE and AuraSkills installed
get yourself a item with soulbound
go in the nehter
die to a zombie pigmen
open your inventory after respawn and see your soulbound items duped

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/itmkHrZ5DLgn3s9mq/d1337ITIAFqE?invite=cr-MSxMSDcsMTI4NzE2OTcs

### "/ae plinfo" link

https://paste.md-5.net/uhusizekow

**Comment by Archy-X** [comment]
Was able to reproduce the dupe even without AuraSkills, so it is not a plugin conflict.

(Tested on Paper 1.21.1 using same method as video)

**Comment by ThomasWega** [comment]
Possibly was in older version of the plugin? I have no such issue now

https://github.com/user-attachments/assets/a5cc7dbd-6e90-4256-b346-bdd2a0ddcb6e

**Comment by ThomasWega** [comment]
Although, I can confirm it does happen with AuraSkills on

**Comment by ThomasWega** [comment]
Should be fixed in the update
