### ISSUE TITLE
random loot

### ISSUE THREAD

**Issue by NGzSideWayz** [GC-spigot/AdvancedEnchantments#4564]
### Describe the bug

'STAFF' works with generation but when you enter a blacklisted group it throws errors

### How to reproduce

set blacklisted groups to your groups instead of 'STAFF'

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/214b8521-5b7e-4c60-a863-4fb254decb08)
![image](https://github.com/user-attachments/assets/de78576a-6f89-439a-a61a-f8d126747ef8)
![image](https://github.com/user-attachments/assets/12d91603-050e-4615-b990-4f3499f0ab82)

### "/ae plinfo" link

https://paste.md-5.net/zadihasazo

### Server Log

https://mcpaste.io/0926d7359cab1db3

**Comment by ThomasWega** [comment]
In the log there is AE version 9.9.14. Can you try on latest?
