### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4566]
### Describe the bug

pick_pocket:
  display: '%group-color%Pick Pocket'
  description: |-
    A chance to steal coins
    when attacking.
  applies-to: Swords
  type: ATTACK
  group: ADMIN
  applies:
    - ALL_SWORD
  levels:
    '1':
      chance: 100
      conditions:
        - '%victim royaleeconomy_balance_bank% >= 1 : %allow%'
    #  cooldown: 120
      effects:
        - CONSOLE_COMMAND:rec purse add %Attacker name% 0.02
        - CONSOLE_COMMAND:rec purse remove %Victim name% 0.02

### How to reproduce

1.21 and newest AE

### "/ae plinfo" link

https://paste.md-5.net/vugifahora

**Comment by ThomasWega** [comment]
try with /ae debug enable and send the output please

**Comment by ThomasWega** [comment]
Should be fixed in latest

**Comment by ThomasWega** [comment]
https://wiki.advancedplugins.net/abilities/conditions/conditions-variables#placeholderapi-support
