### ISSUE TITLE
Custom Enchants Clear Lores

### ISSUE THREAD

**Issue by DontMessWithDis** [GC-spigot/AdvancedEnchantments#4567]
### Describe the bug

When adding a custom enchant to an item it clears the lore and all other enchants.

### How to reproduce

Add an enchant to an item and it clears the lore.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/3966a9c2-91cc-437c-acbf-5f035fb6afca)
![image](https://github.com/user-attachments/assets/9f4733b7-b98d-48a7-a3eb-a63423e67a7a)

### "/ae plinfo" link

https://paste.md-5.net/ehugafutop

**Comment by ThomasWega** [comment]
Hey! Are you running default config? Try with fresh files on latest AE please
