### ISSUE TITLE
Levitation effect doesn't work on 1.8 players

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4568]
### Describe the bug

If you try to give a 1.8 player the LEVITATION effect, you can't because it doesn't exist in <1.9.

I think there needs to be a workaround where if the player is on <1.9 it enacts different code that raises the player. Perhaps throw them up?

### How to reproduce

Make an enchant give LEVITATION and watch it not work on <1.9 players

### "/ae plinfo" link

https://paste.md-5.net/vudeticoye

**Comment by GC-spigot** [comment]
We don't support any versions below 1.17, this case is included. What we've done is added %player client version% placeholder you could use with inline condition to run different effects based on player's protocol version, e.g.
```yaml
- 'POTION:JUMP:5:20 <condition>%client version% < 48 : %allow%</condition>'
```

Protocol versions: https://wiki.vg/Protocol_version_numbers

**Comment by JHarris12345** [comment]
Is it %player client version% or %client version%? You put both there

**Comment by JHarris12345** [comment]
It also says "Condition (%client version% >- 48) contains letters but must be numeric only
