### ISSUE TITLE
Infinite Experience Bug When Using Grindstone with Full Inventory and Custom Enchantments

### ISSUE THREAD

**Issue by DimaSergeew** [GC-spigot/AdvancedEnchantments#4569]
### Describe the bug

When a player attempts to use a grindstone to remove both vanilla and custom enchantments from an item while their inventory is full, and the player uses the Shift + Left Click (LMB) combination, the player receives experience as if the enchantments were removed. However, the item remains enchanted, allowing the player to repeat this action infinitely and gain unlimited experience.

### How to reproduce

Ensure that your inventory is completely full.
Obtain an item with both vanilla and custom enchantments.
Place the item on a grindstone.
Use the Shift + Left Click (LMB) combination to attempt to disenchant the item.
Observe that experience is granted, but the item retains its enchantments.
Repeat the action to gain infinite experience.

### "/ae plinfo" link

https://paste.md-5.net/bociroqana

**Comment by GC-spigot** [comment]
Solved
