### ISSUE TITLE
Health Boost dont work

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4570]
### Describe the bug

When using health boost, it only works with 1 item it does not stack

### How to reproduce

Use health boost
works only 1 one item

refer to ticket https://discord.com/channels/376425582139015168/1273284651213127793

### "/ae plinfo" link

https://paste.md-5.net/pozayuvari

**Comment by ThomasWega** [comment]
I might be blind, but I don't see anything about health boost in the ticket. Send all the info here please

**Comment by Cryptics1999** [comment]
Askills-the_gc-0011

I put the video in there as I coudnt put it here as it told me size to big
Sendt fra min iPhone

25. aug. 2024 kl. 15:49 skrev ThomasWega ***@***.***>:

﻿

I might be blind, but I don't see anything about health boost in the ticket. Send all the info here please

**Comment by ThomasWega** [comment]
That ticket is about the gui groups being replaced. Nothing about health boost. Upload the video somewhere else and send the link here

**Comment by Cryptics1999** [comment]
[https://res.public.onecdn.static.microsoft/assets/mail/file-icon/png/video_16x16.png]Lunar_Client_1.21_v2.16.9-2434_2024-08-20_10-11-34.mp4<https://1drv.ms/v/c/81ae8f8d00649e38/EfP90ZGMSpBBvgAZNdfVk4wBozpreL7z_kMC-ggUuMD_qA>
________________________________
Fra: ThomasWega ***@***.***>
Sendt: søndag 25. august 2024 19:06
Til: GC-spigot/AdvancedEnchantments ***@***.***>
Kopi: Cryptics1999 ***@***.***>; Author ***@***.***>
Emne: Re: [GC-spigot/AdvancedEnchantments] Health Boost dont work (Issue #4570)


That ticket is about the gui groups being replaced. Nothing about health boost. Upload the video somewhere else and send the link here

**Comment by Cryptics1999** [comment]
Il just send it here ^
________________________________
Fra: Alexander Fiveland ***@***.***>
Sendt: søndag 25. august 2024 19:08
Til: GC-spigot/AdvancedEnchantments ***@***.***>
Emne: Sv: [GC-spigot/AdvancedEnchantments] Health Boost dont work (Issue #4570)

[https://res.public.onecdn.static.microsoft/assets/mail/file-icon/png/video_16x16.png]Lunar_Client_1.21_v2.16.9-2434_2024-08-20_10-11-34.mp4<https://1drv.ms/v/c/81ae8f8d00649e38/EfP90ZGMSpBBvgAZNdfVk4wBozpreL7z_kMC-ggUuMD_qA>
________________________________
Fra: ThomasWega ***@***.***>
Sendt: søndag 25. august 2024 19:06
Til: GC-spigot/AdvancedEnchantments ***@***.***>
Kopi: Cryptics1999 ***@***.***>; Author ***@***.***>
Emne: Re: [GC-spigot/AdvancedEnchantments] Health Boost dont work (Issue #4570)


That ticket is about the gui groups being replaced. Nothing about health boost. Upload the video somewhere else and send the link here

**Comment by Cryptics1999** [comment]
It is a Enchant issue tho

**Comment by Cryptics1999** [comment]
This is a Ae issue, if you make a health boost enchant. They dont stack between multiple armors.
________________________________
Fra: ThomasWega ***@***.***>
Sendt: onsdag 4. september 2024 11:58
Til: GC-spigot/AdvancedEnchantments ***@***.***>
Kopi: Cryptics1999 ***@***.***>; Author ***@***.***>
Emne: Re: [GC-spigot/AdvancedEnchantments] Health Boost dont work (Issue #4570)


Closed #4570<https://github.com/GC-spigot/AdvancedEnchantments/issues/4570> as completed.
