### ISSUE TITLE
Latest version dosen;'t work in paaer 1.20.1-196 bukkit

### ISSUE THREAD

**Issue by rhythembear** [GC-spigot/AdvancedEnchantments#4572]
### Describe the bug

latest version is don;t works on paper 1.20.1

### How to reproduce

just put in other plugins with this plugin.

### Screenshots / Videos

![스크린샷 2024-08-17 162607](https://github.com/user-attachments/assets/01fab5d1-f2fc-4c0f-a288-01a142758f6b)

### "/ae plinfo" link

![스크린샷 2024-08-17 162607](https://github.com/user-attachments/assets/01fab5d1-f2fc-4c0f-a288-01a142758f6b)

**Comment by GC-spigot** [comment]
Please post the server log or an error you're having, this is not an issue we can recreate nor other users are experiencing it
