### ISSUE TITLE
telepathy + fortune doesnt work with amethyst crystals

### ISSUE THREAD

**Issue by UnderQuestion** [GC-spigot/AdvancedEnchantments#4573]
### Describe the bug

i with my friend found the bug. when u get the amethyst crystals with fortune 6 and telepathy they drop max 4. but when i removed telepathy, the crystals began to drop in amount up to 64

### How to reproduce

make the amethyst crystals work with enchantments

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/a31abdf0-ca3e-45bc-9a90-db152b56a2b4)

### "/ae plinfo" link

im a player

### Server Log

im a player

**Comment by GC-spigot** [comment]
Fixed!
