### ISSUE TITLE
Required enchant not added

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4576]
### Describe the bug

![image](https://github.com/user-attachments/assets/1bead89c-e133-4b5e-996d-4d0acc1de2d0)
I have set knockback as a required enchant to this item

This player got this enchant thrue enchanting with enchantment table and it did not have the required enchant on it

### How to reproduce

Newest AE version
Purpur 1.21
Add a enchant with a requirement of a vanilla enchant
enchant is possible to be enchanted without the requried vanilla enchant

### Screenshots / Videos

https://paste.md-5.net/tagemotibi

### "/ae plinfo" link

https://paste.md-5.net/tagemotibi

**Comment by ThomasWega** [comment]
Try again on latest please
