### ISSUE TITLE
SET_BLOCK Effect Compatibility and Location Setting for ATTACK Triggers

### ISSUE THREAD

**Issue by slyleight** [GC-spigot/AdvancedEnchantments#4578]
### Describe the bug

I've tried every possible combination, but I'm unsure if it's possible to make the SET_BLOCK effect work with other triggers, such as ATTACK or SHOOT.

I know that MINING works because it can take a block position with `@Block`, but is there a way to manually set a location for it?

For example, I'm trying to add an enchantment that spawns a COBWEB on top of the player for 3 seconds. Since this enchantment works with the ATTACK trigger, how can I use the %victim x% location in my SET_BLOCK effect?

### How to reproduce

Is there a detailed information about SET_BLOCK effect?

### "/ae plinfo" link

https://paste.md-5.net/yelogacama

**Comment by ThomasWega** [comment]
Currently SET_BLOCK only works with Interact events where you click on a block and block break events, where you obviously also target blocks :D .

> For example, I'm trying to add an enchantment that spawns a COBWEB on top of the player for 3 seconds. Since this enchantment works with the ATTACK trigger, how can I use the %victim x% location in my SET_BLOCK effect?

What you are trying to achieve does sound cool, but probably wouldn't be as easy to manage. Removing the block after cooldown and everything. You could for sure do this pretty easily with a custom coded effect though. Would probably cost only few bucks to get some dev to do this.
