### ISSUE TITLE
ArmorSets Increase_Damage not working,

### ISSUE THREAD

**Issue by LioneLONeiL** [GC-spigot/AdvancedEnchantments#4579]
### Describe the bug

/ae sets 
Armors Deal Damage to 10% 15% all damage increase effects are not working.

### How to reproduce

Equip any armor set and try to hit something.
With Healthbar plugin will more easy to find this bug.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1275057347911487590/1275057505705267313/2024-08-19_15-17-40_online-video-cutter.com.mp4?ex=66c48156&is=66c32fd6&hm=67a8feb0a751c8b76d601e59c23c683af3482e09d170ebbbb33d0dd0d7acc433&

### "/ae plinfo" link

https://paste.md-5.net/ligalovoja

### Server Log

no logs for this bug.

**Comment by LioneLONeiL** [comment]
Still waiting to fix this issue.

**Comment by ThomasWega** [comment]
Don't send discord links...
```This content is no longer available.```

**Comment by LioneLONeiL** [comment]
https://youtu.be/dbRHQg5HMPY

**Comment by LioneLONeiL** [comment]
After activating armorset still hitting with 0.9 dmg. 
Its in video.

**Comment by ThomasWega** [comment]
Can you try with only AE as a plugin on the server? Might be some other plugin messing this up
