### ISSUE TITLE
Placeholders in AdvancedEnchants do not work

### ISSUE THREAD

**Issue by TheCashFire** [GC-spigot/AdvancedEnchantments#4581]
### Describe the bug

Placeholders do not work. Tested on 1.21.1 paper. Jr. Helper soapchan can back me up, as they tested too and found the same problem.

### How to reproduce

Turn server on. Attempt to use %advancedenchantments_item_enchants_total% in any instance. I was using it in DeluxeMenus, but it doesn't work anywhere else either.

### "/ae plinfo" link

https://paste.md-5.net/hacenofagi

**Comment by ThomasWega** [comment]
%advancedenchantments_item_enchants_total% works by getting the item in players hand. So this won't work in menus

**Comment by ThomasWega** [comment]
![image](https://github.com/user-attachments/assets/43dc0e8e-7e40-42eb-9f28-88496ff08ba7)

**Comment by TheCashFire** [comment]
Well thanks a bunch for double checking, but DeluxeMenus doesn't put the item in the menu, only reads a placeholder out based on what is in your hand. I even checked it using PAPI parse, _they do not work_.
