### ISSUE TITLE
Tools with "Silk Touch" makes "Experience" enchantment not work.

### ISSUE THREAD

**Issue by kcw0205** [GC-spigot/AdvancedEnchantments#4582]
### Describe the bug

Tools with silk touch enchantment makes experience(custom) enchantment's exp drop effect to not work.

It does trigger, (I know this as Im using showAcitonbar setting) but it seems like the exp orb is not dropping at all.

### How to reproduce

As written above, silk touch enchantment + Experience

### Screenshots / Videos

experience:
  display: '%group-color%경험치 획득'
  description: 블럭을 캘 때 경험치를 추가로 획득 할 확률이 증가합니다.
  settings:
    showActionBar: true
  applies-to:   
  type: MINING
  group: ULTIMATE
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
  levels:
    '1':
      chance: 15
      cooldown: 1
      effects:
        - EXP:<random number>2-5</random number> @Block
    '2':
      chance: 30
      cooldown: 2
      effects:
        - EXP:<random number>2-5</random number> @Block
    '3':
      chance: 45
      cooldown: 3
      effects:
        - EXP:<random number>2-5</random number> @Block
    '4':
      chance: 60
      cooldown: 4
      effects:
        - EXP:<random number>2-5</random number> @Block
    '5':
      chance: 75
      cooldown: 5
      effects:
        - EXP:<random number>2-5</random number> @Block

### "/ae plinfo" link

https://paste.md-5.net/roqemumeso

**Comment by GC-spigot** [comment]
Yes because silk touch does not drop experience, therefore this would never work together.
