### ISSUE TITLE
 AdvancedEnchantments & MCmmo 

### ISSUE THREAD

**Issue by enci4167** [GC-spigot/AdvancedEnchantments#4583]
### Describe the bug

 AdvancedEnchantments & MCmmo Contact questions

### How to reproduce

no

### Screenshots / Videos

no

### "/ae plinfo" link

https://mcpaste.io/bccd49b678e6eca1

### Server Log

https://mcpaste.io/bccd49b678e6eca1

**Comment by ThomasWega** [comment]
what version of McMMO are you on? Update all to latest
