### ISSUE TITLE
Bug with anvil

### ISSUE THREAD

**Issue by NoltoxGit** [GC-spigot/AdvancedEnchantments#4584]
### Describe the bug

Hello,

I've just updated the plugin, and I've noticed a bug when merging enchantments into anvils.
The enchantment doesn't apply on the hoe.

I don't know how to explain the bug, so here's a video 

### How to reproduce

1. See the video.
2. Try and see.

### Screenshots / Videos

Video: https://www.youtube.com/watch?v=Kr49dH9msEA
Config.yml: https://gist.github.com/NoltoxGit/27994a1cd7257086fe77dd9e68e831b3#file-config-yml
Anvil.yml: https://gist.github.com/NoltoxGit/27994a1cd7257086fe77dd9e68e831b3#file-anvil-yml

### "/ae plinfo" link

https://paste.md-5.net/ozadaqivos

### Server Log

https://mclo.gs/FciEqWN

**Comment by ThomasWega** [comment]
What is the enchantment? Send config for it
