### ISSUE TITLE
Method not loaded! 'ITEMSTACK_SET_TAG'

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4587]
### Describe the bug

spam in console

https://mclo.gs/qn8q6bS

### How to reproduce

I don't 

### "/ae plinfo" link

https://paste.md-5.net/utaliwoway

### Server Log

https://mclo.gs/qn8q6bS

**Comment by ThomasWega** [comment]
try updating to latest server jar first please

**Comment by Z3r0xh** [comment]
> try updating to latest server jar first please

I'm on the latest version and the problem persists

![image](https://github.com/user-attachments/assets/9632d8f7-5a4f-4ddc-b200-d5aa8d85cb68)

**Comment by Z3r0xh** [comment]
log from yesterday

https://mclo.gs/qrp6fS1

**Comment by ThomasWega** [comment]
SERVER jar. You are on 1.21-DEV

**Comment by Z3r0xh** [comment]
> SERVER jar. You are on 1.21-DEV

Do you mean 1.21.1 or the latest version of paper 1.21? I'm using a fork of paper, but it's updated with the latest version of paper.

**Comment by Z3r0xh** [comment]
> SERVER jar. You are on 1.21-DEV

Same error on 1.21.1

https://mclo.gs/H7PFaPK
![image](https://github.com/user-attachments/assets/dfea262b-d303-407c-88fa-ff3f33db4307)

**Comment by Z3r0xh** [comment]
> SERVER jar. You are on 1.21-DEV

Could you tell me why this error occurs? I use a fork and if you say it is a problem with the fork, even though it comes from papaer. I would like to know what it is about so I can report the error to the uSpigot developers.

**Comment by Z3r0xh** [comment]
> SERVER jar. You are on 1.21-DEV

Using papaer 1.21.1
![image](https://github.com/user-attachments/assets/44767bae-66a3-4075-8529-018e152df96e)

This problem occurs when disenchanting in vanilla mode, items that have custom enchantments and these items are older than the current version that the server is using, that is, before 1.20

https://mclo.gs/J8dEu1T

**Comment by ThomasWega** [comment]
We'll try it out. Probably an issue with converting nbt to the new components system on 1.20.5

**Comment by Z3r0xh** [comment]
> We'll try it out. Probably an issue with converting nbt to the new components system on 1.20.5

Yes, it only happens with items that have been created before 1.20.5 and the server is currently on 1.21.1

https://mclo.gs/cVZ4KmL

**Comment by ThomasWega** [comment]
What plugin version were you using before updating to 1.20.5+?

**Comment by Z3r0xh** [comment]
I don't remember the exact version. But I've always been using the latest version.

> ¿Qué versión del complemento estabas usando antes de actualizar a 1.20.5+?

**Comment by Z3r0xh** [comment]
> What plugin version were you using before updating to 1.20.5+?

Has the cause of this problem been found? There is too much spam in the console with this problem and it causes lag

**Comment by ThomasWega** [comment]
It hasn't, that's what I am confused about. I've tried reproducing the issue multiple times the exact way you described and it all seems to work fine. 
> > SERVER jar. You are on 1.21-DEV
> 
> Using papaer 1.21.1 ![image](https://private-user-images.githubusercontent.com/138524212/364148624-44767bae-66a3-4075-8529-018e152df96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTkxOTUsIm5iZiI6MTcyODkxODg5NSwicGF0aCI6Ii8xMzg1MjQyMTIvMzY0MTQ4NjI0LTQ0NzY3YmFlLTY2YTMtNDA3NS04NTI5LTAxOGUxNTJkZjk2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNTE0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTMyMmU2YjNlZDM0YjRiNmFlYmNjMmU0NjQxYzhlYmRmN2E3MTQ4MzRmMGQ3ZDBmN2ExODczNWYzMDA4ODI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HpvETs_FyXsVqH8rVzfJmgEQN99F8Yf4nEaSoIE6hE0)
> 
> This problem occurs when disenchanting in vanilla mode, items that have custom enchantments and these items are older than the current version that the server is using, that is, before 1.20
> 
> https://mclo.gs/HAKyKPS
> 
> Put an item with custom enchantments in a chest in version 1.20.4 or 1.20.6 and then update the server to a version higher than 1.21 and this problem occurs
> 
> ![image](https://private-user-images.githubusercontent.com/138524212/364149527-ac0be249-7c27-49f3-8449-ae12822931b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTkxOTUsIm5iZiI6MTcyODkxODg5NSwicGF0aCI6Ii8xMzg1MjQyMTIvMzY0MTQ5NTI3LWFjMGJlMjQ5LTdjMjctNDlmMy04NDQ5LWFlMTI4MjI5MzFiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNTE0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmNkODM5MTU1NGZlODk1NGU1ODliM2Q5YWNhZDVlNmQxNzk4MDcxZDgyYzlkNGMwMTllOTY0MzYyMThhOTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JPQLh2AjWgwuvXz16tMyMaD-XROeducDofkJ3DMbQj8)
> 
> Reviewing this error, I noticed that it said GrindstoneEvent, I searched the kit room for all of them and started testing them one by one until I realized that the oldest ones (created during 1.20.4) were the ones that were giving errors.
> 
> ![image](https://private-user-images.githubusercontent.com/138524212/364151853-74982ebd-4a7a-4e48-bb2c-d282f8ea54d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTkxOTUsIm5iZiI6MTcyODkxODg5NSwicGF0aCI6Ii8xMzg1MjQyMTIvMzY0MTUxODUzLTc0OTgyZWJkLTRhN2EtNGU0OC1iYjJjLWQyODJmOGVhNTRkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNTE0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDU3OGIzYTczMzYxMDAzNDQyMDQ0YWQwYTkxMTk5MjIzMjcwOWZjMTIwM2Q0YzQwOTEyMGRmNzFlOGQ3MWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BgJ_SOhWwpx_-g3h3ts_F1KMe8pugxv6pmcIxzO0ksY)

Can you please try this approach of yours on a fresh server? Not your production one

**Comment by ThomasWega** [comment]
I've meant the whole process of using old version, creating the items and then updating it

**Comment by GC-spigot** [comment]
Solved
