### ISSUE TITLE
Invincible Mobs with a few enchantments 

### ISSUE THREAD

**Issue by Lovekillin** [GC-spigot/AdvancedEnchantments#4588]
### Describe the bug

WIth a few enchantments it seems the zombies get bugged 
it doesnt have to be a bunch in an area i did this to speed up the process 
people can attack one mob and it will randomly happen

### How to reproduce

Simply put those enchants on and attack some mobs
id recommend spawning a ton in a small box like i did 

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/irbXaKFIF2pW5MbJC/d1337llv5TYJ?invite=cr-MSw4ODQsMTU5MzQyNjY4LA

https://media.discordapp.net/attachments/1275197756360757451/1276058352182497280/image.png?ex=66c82573&is=66c6d3f3&hm=cbd176166190e4886e6e0ddc4766d287a7517cffa32c9478280a861052b3feef&=&format=webp&quality=lossless&width=270&height=211

### "/ae plinfo" link

https://paste.md-5.net/hikigokequ

**Comment by ThomasWega** [comment]
Truly interesting, but I cannot think of a reason why AE should cause something like this. Does it not happen without AE?

**Comment by Lovekillin** [comment]
If i remove the plugin, test it , then add back will enchantment data come
back?

**Comment by ThomasWega** [comment]
yes. It's saved in the item NBT
