### ISSUE TITLE
Cannot issue /enchanter

### ISSUE THREAD

**Issue by jeffry1829** [GC-spigot/AdvancedEnchantments#4589]
### Describe the bug

Cannot issue /enchanter

### How to reproduce

Issue /enchanter

### "/ae plinfo" link

https://paste.md-5.net/zalizucoxu

### Server Log

https://mcpaste.io/7a5f6778bd81a376

**Comment by ThomasWega** [comment]
A message is probably missing in your lang file. Compare yours with en-us.yml and see if it's missing any
