### ISSUE TITLE
UNBREAKABLE Effect

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedEnchantments#459]
Hey! can you please add UNBREAKABLE effect as STATIC_EFFECT?
so we don't need to try make something with the repairing effect just add a effect that disable breaking option ^ (make it STATIC_EFFECT so we can set 1 enchantment on armor and tools [so we don't need to make few enchantments that are the same..] )

**Comment by GC-spigot** [comment]
Problem is that EFFECT_STATIC activates only when player equips / de-equips the armor, it's not constantly activating so UNBREAKABLE is impossible to do mid-wear. Your option is to use REPEATING enchant type.
