### ISSUE TITLE
Replanter enchant kicking players

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#4595]
### Describe the bug

player is getting kicked when using replanter enchant on hoe on crops.. no error in console just player getting kicked

### How to reproduce

player is getting kicked when using replanter enchant on hoe on crops

### Screenshots / Videos

https://gyazo.com/3178f0e446b0c36046c6511013cf4149

### "/ae plinfo" link

https://paste.md-5.net/olekenunoy

**Comment by ThomasWega** [comment]
Most likely some other plugin. Try removing plugins in groups and figuring out which one causes this

**Comment by Rexmen1** [comment]
Gonna check and reply back...

**Comment by ThomasWega** [comment]
Any updates?
