### ISSUE TITLE
Enchants are offline

### ISSUE THREAD

**Issue by selektivv** [GC-spigot/AdvancedEnchantments#4597]
### Describe the bug

I don't even know if its AdvancedEnchants related but as soon as i do /enchant (any enchantment) (amount), there will be a message in the chat saying (any enchantment) is not online! Idk how to solve that. Help!

### How to reproduce

I installed the plugin and after that the issue was coming up.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/323bc1d4-10ec-4bc8-9b56-73e9a1b0a8b1)
![image](https://github.com/user-attachments/assets/cf2175ae-ac98-460a-9680-a4eb4018d94d)

### "/ae plinfo" link

https://paste.md-5.net/apijuvohod

**Comment by SirJben** [comment]
This is not AE, use `/ae enchant` for custom enchantments. 

Remove other plugins to find which one interferes with your `/enchant` command.
