### ISSUE TITLE
Soul Dupe

### ISSUE THREAD

**Issue by LioneLONeiL** [GC-spigot/AdvancedEnchantments#4598]
### Describe the bug

Put soul tracker on any stacked item. 
I used apple and putting soul tracker into it.
After add some gem to stacked apple and unstack it. All apples are seperated and same amount of souls in it.

### How to reproduce

Put soul tracker on any stacked item. 
I used apple and putting soul tracker into it.
After add some gem to stacked apple and unstack it. All apples are seperated and same amount of souls in it.

### Screenshots / Videos

No need

### "/ae plinfo" link

No need

### Server Log

No need

**Comment by ThomasWega** [comment]
It should not have been put on stackable items in the first place. There is not much we can do about this, but I will put some preventive measures in next update. But do use this only on non-stackable items.
