### ISSUE TITLE
TELEPORT @BlockInDistance{distance=30}' NOT WORKING (AI)

### ISSUE THREAD

**Issue by Skryl5620** [GC-spigot/AdvancedEnchantments#4599]
### Describe the bug

if you try to use any item with that effect its only gona work when you have the reach and if you use it with teleport its gona telepot you in the groud for exaple if you use the teleport wand its only gona tp you in the ground and it your reach and ignores what is set in the confic that means the op dragon head also not works and prob many other items (this is all in 1.21) and this is also not working for other players.

### How to reproduce

Its just not working

### "/ae plinfo" link

https://paste.md-5.net/ojuyutenoz

**Comment by ThomasWega** [comment]
Will be fixed in the next update. The @BlockInDistance and @Block targets were both being matched, because their names start the same. So you would basically TP in the distance, and then straight back :D. Fixed!
