### ISSUE TITLE
Item Rename Tag Issues

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#460]
When a player uses an item rename tag, they are not able to use colours. It works normally for admins, but when a normal player tries, it just renames the item with the italicized &b blue default rename format. Blocked words for renaming are also case sensitize, so it's very difficult to actually block an item from being named with a certain word.

Also, a minor issue, when a player right clicks an item rename tag in their main hand with an item in their off-hand, they get the message "You can only do this with main hand!". The rename tag still works, it's just this message can be a bit confusing on the player's end.

**Comment by GC-spigot** [comment]
""You can only do this with main hand!". The rename tag still works" - it doesn't go through if it's in off-hand.
Colors aren't working due to your chat plugin filtering out them.

Fixed the case-sensitive issue with filtered words.

**Comment by Dakotaa** [comment]
Could there be some kind of work-around for the chat filtering the colours out? Such as a command rather than typing the name in chat after the nametag is clicked.
