### ISSUE TITLE
Add a way to create curses

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4600]
### Describe the bug

I want to be able to create curses that are on the same are as curses

![image](https://github.com/user-attachments/assets/e331df82-9fff-49d9-8722-5ea8ca705635)

They are above vanilla enchants so not possible to make atm

### How to reproduce

Idea

### "/ae plinfo" link

d

**Comment by SirJben** [comment]
Hii @Cryptics1999 you can try to use `DELETE_ITEM:[amount]` effect

**Comment by Cryptics1999** [comment]
I ment as in make a enchant group that is placed above the vanilla enchants next to the curses so they match
Sendt fra min iPhone

31. aug. 2024 kl. 04:18 skrev SirJben ***@***.***>:

﻿

Hii @Cryptics1999<https://github.com/Cryptics1999> you can try to use DELETE_ITEM:[amount] effect

**Comment by ThomasWega** [comment]
We'll be looking into this
