### ISSUE TITLE
Incompatibility of the 'disabled-worlds' & 'REPEATING' parameter.

### ISSUE THREAD

**Issue by TopicflyOffi** [GC-spigot/AdvancedEnchantments#4601]
### Describe the bug

Hello, I have an issue with the 'disabled-worlds' parameter and the 'REPEATING' enchantment type. When I go to a world where the enchantment is disabled and then switch to another world, the enchantment no longer works. I have to unequip and re-equip my armor to fix the problem.

### How to reproduce

• Apply a 'REPEATING' type enchantment and blacklist a world
• Go to the blacklisted world
• Return to another world
• Enchantment no longer works

### Screenshots / Videos

Enchantment configuration : https://i.goopics.net/2dzjyf.png

### "/ae plinfo" link

https://paste.md-5.net/amepafuteh

**Comment by ThomasWega** [comment]
Will be fixed in the next update

**Comment by TopicflyOffi** [comment]
Hello,
The bug is still present. As soon as I go into a blacklisted world, for example the world 'world', and then return to another world named 'test', the enchantment will no longer work. @ThomasWega

**Comment by TopicflyOffi** [comment]
Hello, Any news @ThomasWega ? 😊

**Comment by ThomasWega** [comment]
Hey! Try using this option in config.yml instead please
![obrazek](https://github.com/user-attachments/assets/9612fccb-d3b6-4857-bc17-f897b6dff61f)

**Comment by ThomasWega** [comment]
Actually, you are right

**Comment by ThomasWega** [comment]
Uploading 2024-10-02 12-29-56.mp4…

idk. It works completely fine for me?

**Comment by TopicflyOffi** [comment]
By using 'time:' instead of 'cooldown:', it works. Thank you for your responses and for the fix.

**Comment by ThomasWega** [comment]
No worries! Glad you've fixed it!
