### ISSUE TITLE
Souls Dont Get Removed on proc

### ISSUE THREAD

**Issue by KDKyleDoes** [GC-spigot/AdvancedEnchantments#4603]
### Describe the bug

When using the pheonix enchant (and I assume others) when it procs the souls are not removed from the player.

**Im using the 2nd prebuilt config (not the one pre installed)

### How to reproduce

Using an enchant that requires souls, the enchant still works even if no souls are in the players inventory, and if souls are in their inventory it doesnt take any souls

### "/ae plinfo" link

https://paste.md-5.net/efazidoxuy

### Server Log

https://mcpaste.io/3edc028884e30785

**Comment by ThomasWega** [comment]
Send the enchantment you are using
