### ISSUE TITLE
Anvil issue

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4604]
### Describe the bug

When trying to apply enchant on an item with required enchant added it wont let you add the item, but this works with drop an drag

### How to reproduce

Adding munk to a item and then trying to add a fuddle book thrue the anvil wont work, but if you use the drag an drop feature it works smooth as butter

munk:
  display: '%group-color%Munk'
  description: Disarm opponent.
  applies-to: Swords
  type: ATTACK
  group: NORMAL
  applies:
    - ALL_SWORD
  settings:
    showActionBar: false
    not-applyable-with:
      - "fuddle"
  levels:
    '1':
      chance: 2
      cooldown: 15
      effects:
        - DISARM @Victim
    '2':
      chance: 3
      cooldown: 15
      effects:
        - DISARM @Victim
    '3':
      chance: 4
      cooldown: 15
      effects:
        - DISARM @Victim
fuddle:
  display: '%group-color%Fuddle'
  description: Disorganize opponent's hotbar.
  applies-to: Swords
  type: ATTACK
  group: HARD
  applies:
    - ALL_SWORD
  settings:
    showActionBar: false
    required-enchants:
      - 'munk'
    removed-enchants:
      - 'munk'
  levels:
    '1':
      chance: 2
      cooldown: 15
      effects:
        - SHUFFLE_HOTBAR @Victim
    '2':
      chance: 3
      cooldown: 15
      effects:
        - SHUFFLE_HOTBAR @Victim
    '3':
      chance: 4
      cooldown: 15
      effects:
        - SHUFFLE_HOTBAR @Victim

### "/ae plinfo" link

https://paste.md-5.net/yugiwepore

**Comment by ThomasWega** [comment]
You use not-applyable-with and required-enchants between those two. That doesn't make any sense, thus why it doesn't work. One required it, the second one requires not having it

**Comment by Cryptics1999** [comment]
It does cause one of them remove the otjer one
Sendt fra min iPhone

17. sep. 2024 kl. 12:55 skrev ThomasWega ***@***.***>:

﻿

You use not-applyable-with and required-enchants between those two. That doesn't make any sense, thus why it doesn't work. One required it, the second one requires not having it
