### ISSUE TITLE
Items Adder and Advanced Enchants issue

### ISSUE THREAD

**Issue by Domm1** [GC-spigot/AdvancedEnchantments#4605]
### Describe the bug

Basically ever since the update to 1.21 something broke, I opened support ticket at AP and after Jben checking it I was told to report the issue here. The issue is open at Items Adder github as well (https://github.com/PluginBugs/Issues-ItemsAdder/issues/3921).

### How to reproduce

Paper version 1.21-124-master
AdvancedEnchantments 9.10.9
ItemsAdder 4.0.2-alpha-test-7

Have a configuration of items adder with enchant from AE added, start the server. AE will disable and IA will be broken.

### Screenshots / Videos

I can provide more information upon request/privately.

### "/ae plinfo" link

I cannot provide this as the server doesn't start with AE

### Server Log

https://pastebin.com/63j4rYUR (For full log I can share privately)

**Comment by ThomasWega** [comment]
Issue was marked as solved on IA's end
