### ISSUE TITLE
AdvancedEnchantments error

### ISSUE THREAD

**Issue by DarrienZ** [GC-spigot/AdvancedEnchantments#4608]
### Describe the bug

Not sure...

### How to reproduce

Error randomly appeared.

### "/ae plinfo" link

https://paste.md-5.net/efimirepej

### Server Log

https://mcpaste.io/ade84a476b40ec6c

**Comment by ThomasWega** [comment]
We need more information then this. We cannot do anything with this little info. Please do proper testing and then create new issue with all the info you were able to gather
