### ISSUE TITLE
Pickpocket steals from yourself instead of the victim

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4609]
### Describe the bug

When pickpocketing a player it removes your money and give it to them except of you pickpocketing them as it shoud

### How to reproduce

pick_pocket:
  display: '%group-color%Pick Pocket'
  description: |-
    A chance to steal coins
    when attacking.
  applies-to: Swords
  type: ATTACK
  group: NORMAL
  applies:
    - ALL_SWORD
  levels:
    '1':
      chance: 3
      cooldown: 80
      effects:
      - STEAL_MONEY:<random number>0-2</random number> @Victim
      - PLAY_SOUND_OUTLOUD:NOTE_STICKS:10
      - MESSAGE:§9§l** PICKPOCKET ** §7(-§6%random% Coins§7) @Victim
    '2':
      chance: 5
      cooldown: 80
      effects:
      - STEAL_MONEY:<random number>0-2</random number> @Victim
      - PLAY_SOUND_OUTLOUD:NOTE_STICKS:10
      - MESSAGE:§9§l** PICKPOCKET ** §7(-§6%random% Coins§7) @Victim
    '3':
      chance: 6
      cooldown: 80
      effects:
      - STEAL_MONEY:<random number>0-2</random number> @Victim
      - PLAY_SOUND_OUTLOUD:NOTE_STICKS:10
      - MESSAGE:§9§l** PICKPOCKET ** §7(-§6%random% Coins§7) @Victim

### "/ae plinfo" link

https://paste.md-5.net/xetinubika

**Comment by ThomasWega** [comment]
Just change the targets

**Comment by Cryptics1999** [comment]
Dont work, then you get error
