### ISSUE TITLE
Groups stop working

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4610]
### Describe the bug

After a while on the server, the groups stop working properly and the unique type is displayed instead of the heroic one. After the reload it works well but after a few minutes it fails again.

### How to reproduce

Just wait and it deconfigures itself

### Screenshots / Videos

https://youtu.be/OwCv68Y5ysU

### "/ae plinfo" link

https://paste.md-5.net/resedomiye

### Server Log

no errors in console

**Comment by ThomasWega** [comment]
will be the same issue as https://github.com/GC-spigot/AdvancedEnchantments/issues/4553
