### ISSUE TITLE
Error with HALF_DAMAGE effect

### ISSUE THREAD

**Issue by SpeedCrazy** [GC-spigot/AdvancedEnchantments#4611]
### Describe the bug

We currently have the fo
![HALF](https://github.com/user-attachments/assets/70621e19-08e7-455d-b90c-456e92790b34)
llowing bug within the server that causes too many threads to be generated and crashes the server 

### How to reproduce

This error, because the HALF_DAMAGE effect cannot be activated, causes the server to start throwing errors inside the console and inside the game, which causes too many trheads to be generated that the server is unable to process and crashes automatically.

### "/ae plinfo" link

https://paste.md-5.net/muyujimamu

### Server Log

https://mcpaste.io/e7918671b9306776

**Comment by ThomasWega** [comment]
It seems like you are using this effect with JUMP trigger? I need to see the enchantment.

**Comment by ThomasWega** [comment]
Then you need to figure out which enchantment was used and which causes the error

**Comment by ThomasWega** [comment]
reponse is on github ticket
