### ISSUE TITLE
removed-enchants fails to override when enchant slots are full

### ISSUE THREAD

**Issue by hvtess** [GC-spigot/AdvancedEnchantments#4612]
### Describe the bug

Enchantments set to remove an old enchantment require an extra slot to apply, even if it will override the deleted enchantment.

### How to reproduce

Set up an enchantment that requires another enchant and removes it when applied.
Add the max amount of enchants to an item, including the required enchantment.
Apply the book for the enchantment to the item while not OP.
The enchant set to be removed will remain on the item and the new enchantment will not be applied.
Should receive an error message requiring more slots for the enchantment to be added.

### "/ae plinfo" link

https://paste.md-5.net/kopejoneco

**Comment by ThomasWega** [comment]
I don't get it. Requires another enchant and removes it when applied doesn't make any sense and I doubt it's possible. Seems like a same issue as https://github.com/GC-spigot/AdvancedEnchantments/issues/4604
