### ISSUE TITLE
 Sneak-right click options to items for enchanter-books.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4613]
### Describe the bug

Player often accidentally open the enchanter-book.
Can you add an option to open only with sneak - right click?

### How to reproduce

just right click with held enchanter-book.

### "/ae plinfo" link

https://paste.md-5.net/beqifocepe

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
