### ISSUE TITLE
Gkit give event

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4614]
### Describe the bug

Hey, I would like to request a new event that is sent when someone is given a gkit that allows the items in the gkit to be modified before sending to the player. For example:

A method in the event like event.getItem(); that allows me to modify the item BEFORE the plugin then sends it to the player

### How to reproduce

N/A

### "/ae plinfo" link

N/A

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
