### ISSUE TITLE
Not updating placeholder %player_EXP%

### ISSUE THREAD

**Issue by MemTar** [GC-spigot/AdvancedEnchantments#4615]
### Describe the bug

When I buy an enchant with xp it takes the xp but it doesnt change/update the placeholder %player_total_exp%  It does change when I use commands such as /xp give or /xp set but not when buying something with xp using /enchanter 

### How to reproduce

Buy an enchant with xp it takes the xp but it doesnt change/update the placeholder %player_total_exp%

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/528f6bcc-562e-43a3-8e9b-5598a2e67126)

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by ThomasWega** [comment]
![image](https://github.com/user-attachments/assets/1bad52d7-4337-492c-be9b-f20fadc71a78)

Use %player_exp%
