### ISSUE TITLE
Errors with the menus and chests

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4616]
### Describe the bug

By renaming chests you can access some inventories
https://youtu.be/SEV2L5PbtaI

For example, the market one is blocked but spam appears in the console

### How to reproduce

Then, for example, if you try to enter the market menu from a chest, the following is spammed in the console:

https://mclo.gs/654wxPI

### Screenshots / Videos

Other inventories:

https://youtu.be/SEV2L5PbtaI

/ea market:

https://mclo.gs/654wxPI

### "/ae plinfo" link

https://paste.md-5.net/voqexuhefu

**Comment by ThomasWega** [comment]
Will be fixed in the next update

**Comment by Z3r0xh** [comment]
> Will be fixed in the next update

Thanks you very much!!
