### ISSUE TITLE
Vein Miner

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4617]
### Describe the bug

Vein Miner Vein mines playerplaced blocks

### How to reproduce

I use Vein Miner as my timber enchant as the plugin made one dont count some specific logs I need, but issue arrises that if people break logs in their house it breaks them all

### "/ae plinfo" link

dd

**Comment by SirJben** [comment]
Send the enchantment example.

**Comment by Cryptics1999** [comment]
timber:
  display: '%group-color%Timber'
  description: Cut down whole trees in 1 swing
  applies-to: Axes
  group: PEACEFUL
  type: MINING
  settings:
    showActionBar: false
  applies:
    - ALL_AXE
  levels:
    '1':
      chance: 60
      cooldown: 20
  #    conditions:
  #      - '%advancedskills_mana% > 7 : %continue%'
  #      - '%block type% contains LOG : %allow%'
  #      - '%block type% contains STEM : %allow%'
  #      - '%block type% contains WOOD : %allow%'
  #      - '%block type% contains HYPHAE : %allow%'
      settings:
        whitelist:
        - OAK_LOG
        - OAK_WOOD
        - SPRUCE_LOG
        - SPRUCE_WOOD
        - BIRCH_LOG
        - BIRCH_WOOD
        - JUNGLE_LOG
        - JUNGLE_WOOD
        - ACACIA_LOG
        - ACACIA_WOOD
        - DARK_OAK_LOG
        - DARK_OAK_WOOD
        - CHERRY_LOG
        - MANGROVE_LOG
        - MANGROVE_WOOD
        - WARPED_STEM
        - CRIMSON_STEM
        - CRIMSON_HYPHAE
        - WARPED_HYPHAE
      effects:
      - BREAK_BLOCK @Veinmine
    '2':
      chance: 60
      cooldown: 15
      settings:
        whitelist:
        - OAK_LOG
        - OAK_WOOD
        - SPRUCE_LOG
        - SPRUCE_WOOD
        - BIRCH_LOG
        - BIRCH_WOOD
        - JUNGLE_LOG
        - JUNGLE_WOOD
        - ACACIA_LOG
        - ACACIA_WOOD
        - DARK_OAK_LOG
        - DARK_OAK_WOOD
        - CHERRY_LOG
        - MANGROVE_LOG
        - MANGROVE_WOOD
        - WARPED_STEM
        - CRIMSON_STEM
        - CRIMSON_HYPHAE
        - WARPED_HYPHAE
      effects:
      - BREAK_BLOCK @Veinmine
    '3':
      chance: 60
      cooldown: 12
      settings:
        whitelist:
        - OAK_LOG
        - OAK_WOOD
        - SPRUCE_LOG
        - SPRUCE_WOOD
        - BIRCH_LOG
        - BIRCH_WOOD
        - JUNGLE_LOG
        - JUNGLE_WOOD
        - ACACIA_LOG
        - ACACIA_WOOD
        - DARK_OAK_LOG
        - DARK_OAK_WOOD
        - CHERRY_LOG
        - MANGROVE_LOG
        - MANGROVE_WOOD
        - WARPED_STEM
        - CRIMSON_STEM
        - CRIMSON_HYPHAE
        - WARPED_HYPHAE
      effects:
      - BREAK_BLOCK @Veinmine
    '4':
      chance: 60
      cooldown: 8
      settings:
        whitelist:
        - OAK_LOG
        - OAK_WOOD
        - SPRUCE_LOG
        - SPRUCE_WOOD
        - BIRCH_LOG
        - BIRCH_WOOD
        - JUNGLE_LOG
        - JUNGLE_WOOD
        - ACACIA_LOG
        - ACACIA_WOOD
        - DARK_OAK_LOG
        - DARK_OAK_WOOD
        - CHERRY_LOG
        - MANGROVE_LOG
        - MANGROVE_WOOD
        - WARPED_STEM
        - CRIMSON_STEM
        - CRIMSON_HYPHAE
        - WARPED_HYPHAE
      effects:
      - BREAK_BLOCK @Veinmine
    '5':
      chance: 60
      cooldown: 5
      settings:
        whitelist:
        - OAK_LOG
        - OAK_WOOD
        - SPRUCE_LOG
        - SPRUCE_WOOD
        - BIRCH_LOG
        - BIRCH_WOOD
        - JUNGLE_LOG
        - JUNGLE_WOOD
        - ACACIA_LOG
        - ACACIA_WOOD
        - DARK_OAK_LOG
        - DARK_OAK_WOOD
        - CHERRY_LOG
        - MANGROVE_LOG
        - MANGROVE_WOOD
        - WARPED_STEM
        - CRIMSON_STEM
        - CRIMSON_HYPHAE
        - WARPED_HYPHAE
      effects:
      - BREAK_BLOCK @Veinmine

**Comment by ThomasWega** [comment]
make sure this is ``true`` in ``config.yml`` 
<img width="746" alt="image" src="https://github.com/user-attachments/assets/95e30de0-8bd7-4058-ab91-b0edb5fbe254">
