### ISSUE TITLE
Vanilla & Custom Enchants Not Combining

### ISSUE THREAD

**Issue by ElBalthus** [GC-spigot/AdvancedEnchantments#4618]
### Describe the bug

So, every time I add an custom enchant to a vanilla-enchanted tool, it’s perfect, but if I wanna add another vanilla enchant in the tool with the anvil, it doesn’t let me add it

### How to reproduce

Idk if it’s an config.yml option, but I probably have it in false. If you can tell me the option, I can solve it

### "/ae plinfo" link

https://paste.md-5.net/erepoguguj

**Comment by ThomasWega** [comment]
in anvil.yml:
![image](https://github.com/user-attachments/assets/d721f6ff-ccb9-4d27-ac83-0f0948c550d4)


in config.yml:
![image](https://github.com/user-attachments/assets/442814aa-99b5-4b00-8a99-fdd90b1a0a1a)

have these both on, and you should be good to go
