### ISSUE TITLE
might not be a bug but hear me out...

### ISSUE THREAD

**Issue by RobertGaminPlayz** [GC-spigot/AdvancedEnchantments#4620]
### Describe the bug

You cannot have the same triggers like the trigger EFFECT_STATIC which is bad in my opinion due to a good missing feature where it will use an effect if the player wears an armor. My idea was to make it play a sound with the equipping and unequipping of the armor... (its also that if you want it to do a diff thing with the same trigger)

### How to reproduce

Simply just add multiple EFFECT_STATIC trigger and it will only run the last EFFECT_STATIC in the file.

### "/ae plinfo" link

https://paste.md-5.net/ibosikifid

**Comment by SirJben** [comment]
Hii, can you share this enchantment of yours.

**Comment by RobertGaminPlayz** [comment]
not really an enchantment but its built within the armor. Like I said I wanted it to use multiple triggers. I undid my original work and lost it so it might do the opposite. Basically since you cannot add like equip sounds and unequip sounds I was planning to instead use EFFECT_STATIC with the proper condition to make it work. But the issue is that you can only use 1 trigger each for an armor or weapon. Basically beacon activate sound should play only when you equip the armor and deactivate when you unequip the armor. While the others will do its thing normally. I am figuring things out with the AdvancedEnchantments so I made this..

[infinity-armor.txt](https://github.com/user-attachments/files/16922451/infinity-armor.txt)

**Comment by RobertGaminPlayz** [comment]
I do not know if you based the armor idea from ArmorPlus or wat but that plugin had equip and unequip sounds which are even toggleable so yeah... It looks somewhat similar. I wasn't the one who configurated the armors on the ArmorPlus but I was able to understand the concept of how it works and checked its config.

**Comment by ThomasWega** [comment]
I'll be looking into this

**Comment by RobertGaminPlayz** [comment]
I can try explaining the bug if you do not understand what I am trying to say...
