### ISSUE TITLE
Limit types of enchants on items

### ISSUE THREAD

**Issue by HaleFam23** [GC-spigot/AdvancedEnchantments#4623]
### Describe the bug

I am trying to add a limit for types of enchants on items and it is not in the config/files. I asked in discord they told me to make this.

### How to reproduce

No limit for enchant types.

### Screenshots / Videos

none

### "/ae plinfo" link

0

### Server Log

0

**Comment by HaleFam23** [comment]
any update on this?

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
