### ISSUE TITLE
slots enchantments

### ISSUE THREAD

**Issue by bladeRR** [GC-spigot/AdvancedEnchantments#4624]
### Describe the bug

Hello, I am having a visual bug, in which I limit the enchantments to 3, but the counter does not go down and keeps adding and going up, this makes the image dirty and looks ugly, as we can see in the video: 

https://youtu.be/6BA2PjW7P-g

<img width="251" alt="a" src="https://github.com/user-attachments/assets/d8420db1-4ad9-4b68-857f-44b9b096c67d">

### How to reproduce

You have to put the books one by one, the text of the slots will increase and the placeholder will not go down, it will only go up and mess up the image.

### Screenshots / Videos

https://youtu.be/6BA2PjW7P-g

### "/ae plinfo" link

https://paste.md-5.net/coyomuqusi

**Comment by ThomasWega** [comment]
Can you provide the config? Does the same happen when using the default config?
