### ISSUE TITLE
Fixing Lag Issues with Trench with Large Radius

### ISSUE THREAD

**Issue by MirMiksan** [GC-spigot/AdvancedEnchantments#4626]
### Describe the bug

When I use Trench with a large radius, as in the example, significant lag occurs on the server. Because of this, I can't create the enchantments I need.

applies-to: "Tools"
type: "MINING"
group: "LEGENDARY"
applies:
  - NETHERITE_PICKAXE 
levels:
  1:
    cooldown: 5
    chance: 100
    effects:
      - "REMOVE_ENCHANT:Mending <condition>%victim player_world% = lobby : %stop%</condition>"
      - "BREAK_BLOCK @Trench{radiuscustom=9x9x9} <condition>%victim player_world% = lobby : %stop%</condition>"
      
![image](https://github.com/user-attachments/assets/456f09a3-0547-48e8-8af1-f95dee446804)

### How to reproduce

The solution to this problem is simple: break the blocks step by step, rather than all at once in a 9x9x9 area. For example, break an area of 1x9x1 first, then 3x9x3, and so on. Unfortunately, the WAIT:<ticks> delay doesn't work with the MINING effect, so I can't manually achieve the desired result.

### "/ae plinfo" link

.

**Comment by ThomasWega** [comment]
Hey! We'll look into this, seems interesting. I'll do some internal testing
