### ISSUE TITLE
Trigger: PROJECTILE_BLOCK, Effects: RETURN, FERTILIZER

### ISSUE THREAD

**Issue by MirMiksan** [GC-spigot/AdvancedEnchantments#4627]
### Describe the bug

Please don't scold me for posting in the wrong section, as the thread for adding features is closed. I consulted with support in your Discord, and they told me that it's okay to create a topic for adding features in the "Bugs" section.

### How to reproduce

1) I would like to propose adding the PROJECTILE_BLOCK trigger, which will activate when a projectile, such as a trident, touches a block after being thrown. This trigger should work correctly with the PULL_CLOSER, PULL_AWAY, and TELEPORT effects. Here’s an example:

applies-to: "Trident"
type: "PROJECTILE_BLOCK"
group: "LEGENDARY"
applies:
  - TRIDENT
levels:
  1:
    chance: 100
    cooldown: 1
    effects:
      - "PULL_CLOSER:10 @Self"

2) I would like to suggest a new effect for quickly returning the trident — RETURN, which would work perfectly with the PROJECTILE_BLOCK trigger (described above) and SHOOT;SHOOT_MOB. Here’s an example:

applies-to: "Trident"
type: "PROJECTILE_BLOCK;SHOOT;SHOOT_MOB"
group: "LEGENDARY"
applies:
  - TRIDENT
levels:
  1:
    chance: 100
    cooldown: 1
    effects:
      - "RETURN @Self"

3) The addition of a new effect called FERTILIZER, which would work on crops such as sugar cane, nether wart, carrots, potatoes, etc. It would act like bone meal, growing crops by a specified number of stages, indicated by FERTILIZER:<how many stages to grow>. This effect should be correctly processed by the RIGHT_CLICK and SWING triggers, allowing it to work without breaking the crops. Here’s an example:

applies-to: "Hoe"
type: "SWING"
group: "LEGENDARY"
applies:
  - ALL_HOE
levels:
  1:
    chance: 100
    cooldown: 0
    effects:
      - 'FERTILIZER:1 <condition>%block type% = SUGAR_CANE : %allow%</condition>'
      - 'FERTILIZER:1 <condition>%block type% = POTATOES : %allow%</condition>'
      - 'FERTILIZER:1 <condition>%block type% = WHEAT : %allow%</condition>'
      - 'FERTILIZER:1 <condition>%block type% = CARROTS : %allow%</condition>'
      - 'FERTILIZER:1 <condition>%block type% = BEETROOTS : %allow%</condition>'
      - 'FERTILIZER:1 <condition>%block type% = NETHER_WART : %allow%</condition>'

### "/ae plinfo" link

1

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
