### ISSUE TITLE
Durability continues broken on 1.21.1

### ISSUE THREAD

**Issue by SliderKP** [GC-spigot/AdvancedEnchantments#4628]
### Describe the bug

Items Adder +`Advanced Enchantments gets durability dosnt work correctly, i reported to itemsadder too.
im not using the latestversion of AE because brokes some enchants on my server. im using 9.11.0

### How to reproduce

Enchant an armor of itemsadders with any ae

### Screenshots / Videos

https://i.imgur.com/3dXnJpd.png

### "/ae plinfo" link

https://paste.md-5.net/enifimimeg

### Server Log

https://mcpaste.io/e189487ca8fae20e

**Comment by ThomasWega** [comment]
Seems like it's not an issue with AE, but rather IA or ViaVersion
