### ISSUE TITLE
hide_flags bugg

### ISSUE THREAD

**Issue by lukrr** [GC-spigot/AdvancedEnchantments#4629]
### Describe the bug

hide_enchants does not work in the latest version of the plugin with version 1.21.1 (It worked on my old server with the same configuration using 1.16.5), I need it to hide the enchantment that is applied to the book so that it looks enchanted

![imagen](https://github.com/user-attachments/assets/87916f51-a381-4c8e-9898-70388a7466d8)

### How to reproduce

.

### "/ae plinfo" link

https://paste.md-5.net/qizitayaha

**Comment by GC-spigot** [comment]
Definitely works, this has been tested. Make sure this format is the same that you have:
```yaml
enchantment-book:
  # If true, books can be applied to items in anvils.
  anvil-application: false
  # If true, books can be applied to items by dragging and dropping them on the item in an inventory.
  drag-drop-application: true
  item:
    type: BOOK
    id: 0
    custom-model-data: 0
    force-glow: false
  # Variables: %enchant%, %enchant-no-color%, %description%, %level-description%, %applies%, %success%, %destroy%, %color%, %max-level%
  name: '%group-color%&l&n%enchant-no-color% %level%'
  lore:
  - '&a%success%% Success Rate'
  - '&c%destroy%% Destroy Rate'
  - '&e%description%'
  - '&7%applies-to% Enchantment'
  - '&7Drag n'' drop onto item to enchant'
  item-flags:
  - 'HIDE_ENCHANTS'
  enchantments:
  - 'SHARPNESS:5'```
