### ISSUE TITLE
Player is kicked when using seeds in offhand with replanter

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#4632]
### Describe the bug

Player is kicked when using seeds in offhand with replanter

### How to reproduce

Player is kicked when using seeds in offhand with replanter

### Screenshots / Videos

https://gyazo.com/9145f1542994484e1f702420154305e9

### "/ae plinfo" link

https://paste.md-5.net/cahicubora

**Comment by SirJben** [comment]
Update your plugin and provide any errors from console.

**Comment by Rexmen1** [comment]
There are no errors in console thats the thing

**Comment by GC-spigot** [comment]
Solved
