### ISSUE TITLE
Givercbook command gives wrong tier until /ae reload. And then resets after a few minutes.

### ISSUE THREAD

**Issue by ValhallaCraft** [GC-spigot/AdvancedEnchantments#4633]
### Describe the bug

Title

### How to reproduce

have custom tiers, run /ae givercbook <custom tier> player 1
run /ae reload
run give command again

### Screenshots / Videos

https://github.com/user-attachments/assets/2c1638c2-f7aa-47a8-a1e1-59985a065b09

### "/ae plinfo" link

https://paste.md-5.net/atihihebub

**Comment by ValhallaCraft** [comment]
This happens on all custom tiers, they resort to fabled for some reason

**Comment by GC-spigot** [comment]
We'll need your configuration, you can either share it here or drop it off on a discord ticket (let them know to tag me, @GC). Working okay on our end:
![image](https://github.com/user-attachments/assets/f65cf2b0-66e1-4f4d-84be-83daf7acea38)

**Comment by ThomasWega** [comment]
It will be the same issue as this https://github.com/GC-spigot/AdvancedEnchantments/issues/4553
