### ISSUE TITLE
Tons of triggers do not work in AE

### ISSUE THREAD

**Issue by ValhallaCraft** [GC-spigot/AdvancedEnchantments#4634]
### Describe the bug

HELD
ARROW_HIT
BOW_FIRE
BITE_HOOK
BREW_POTION
EAT
ELYTRA_FLY
JUMP

### How to reproduce

None of these triggers are functional, and i didnt test all of them, I know there are more. But it seems like false advertising that all these triggers are advertised but only a handful work.

### "/ae plinfo" link

https://paste.md-5.net/ajagociqas

**Comment by GC-spigot** [comment]
These are tested and used often not only by our community but by us as well. Show your testing methods - Ive personally used most of these within last 2 weeks.

**Comment by ValhallaCraft** [comment]
Im not gonna go through all of them and record but here are a few
https://drive.google.com/drive/folders/1npCbbpqzCiZoJ19OR0TIMfhH1Gb_3aIQ?usp=drive_link

**Comment by GC-spigot** [comment]
HELD:
![image](https://github.com/user-attachments/assets/bc6f355e-43c2-4201-a8ec-e91e2b56a7ff)
JUMP only works on Paper servers
Etc, I've tested now all and they are all working.
