### ISSUE TITLE
Firework does not shoot in air when enchant book opened

### ISSUE THREAD

**Issue by moonies44** [GC-spigot/AdvancedEnchantments#4635]
### Describe the bug

firework does not shoot in the air when opening enchantment book

### How to reproduce

open an enchantment book

### "/ae plinfo" link

https://paste.md-5.net/eqejicuxev

**Comment by GC-spigot** [comment]
Do you have this disabled in configuration? Definitely not a bug
https://gyazo.com/e31cd3e758110c1a8f4c0c116cbf21af
Check `enchanter-books.firework-on-open` value in config.yml and restart

**Comment by moonies44** [comment]
i assumed this was a bug, as this option is already enabled.

enchanter-books:
  firework-on-open: true
