### ISSUE TITLE
AE Commands not registering through console

### ISSUE THREAD

**Issue by TheCashFire** [GC-spigot/AdvancedEnchantments#4637]
### Describe the bug

Expecting /ae enchant to function using targeters through the console. Targeting seems to work when issued through a command in game, but it is hard to test with one person. Tried to issue the command through the console with no response, not even a error message. If this is not broken, can both console allowance and player targeters be added to the ae enchant command?

### How to reproduce

Issue an AE command through the console with a targeter.

### "/ae plinfo" link

https://paste.md-5.net/jowafaguxi

**Comment by SirJben** [comment]
Provide any error from console.

**Comment by TheCashFire** [comment]
There are no errors in the console. There is not so much as a message even in the console. Issuing the command results in nothing, not even a "This command can't be executed from the console" or anything. No result.

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
