### ISSUE TITLE
@Block doesnt seem to be working on latest AE

### ISSUE THREAD

**Issue by ValhallaCraft** [GC-spigot/AdvancedEnchantments#4639]
### Describe the bug

The @Block target doesnt work on latest version of AE

### How to reproduce

Use any enchant with @Block.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/c19f0264-0d3d-4c7a-9aed-e9245240d3db)

### "/ae plinfo" link

https://paste.md-5.net/aqegubahiw

**Comment by ThomasWega** [comment]
Will be fixed in the next update
