### ISSUE TITLE
add a code to gkits and add support for discs

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedEnchantments#464]
can you add a code that I will send you to gkits?
```
fm.addItemFlags(ItemFlag.HIDE_ENCHANTS);
    fm.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
    fm.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
    fm.addItemFlags(ItemFlag.HIDE_DESTROYS);
         fm.addItemFlags(ItemFlag.HIDE_PLACED_ON);
         fm.addItemFlags(ItemFlag.HIDE_POTION_EFFECTS);
```
I want to set a disc as the item
but that have a annoying lore and you can remove that with the code that I sent you
that Important please let me know if you can add that or not
please that super important
and to add support for disc items :3

**Comment by Jok3rTV** [comment]
fm.addItemFlags(ItemFlag.HIDE_ENCHANTS);
    fm.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
    fm.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
    fm.addItemFlags(ItemFlag.HIDE_DESTROYS);
         fm.addItemFlags(ItemFlag.HIDE_PLACED_ON);
         fm.addItemFlags(ItemFlag.HIDE_POTION_EFFECTS);

**Comment by GC-spigot** [comment]
Not going to hide all attributes. Are you seeing what you're adding here?
Hiding enchants, hiding damage, things that would be useful to see for
others. Will not be added.

**Comment by Jok3rTV** [comment]
ammm k I got it thanks but can you add that I can set disc on the menu?

**Comment by GC-spigot** [comment]
No.

**Comment by Jok3rTV** [comment]
What.. why not? I just want to set the item as a icon...... can you set the code on enchanter GUI?
