### ISSUE TITLE
REPEATING cause lag

### ISSUE THREAD

**Issue by AleMastro** [GC-spigot/AdvancedEnchantments#4640]
### Describe the bug

The server always has very low TPS and by running various sparks we have noticed (confirmed in a ticket on your discord) that the problem affects enchants with REPEATING.

By performing reload (advancedenchantments reload) the tps seem to return more or less stable for a handful of minutes and then go back down again.

### How to reproduce

You could simply reproduce it with a good number of players normally using an enchant with REPEATING

### Screenshots / Videos

https://spark.lucko.me/zckj2WZNKP
https://spark.lucko.me/Tl945Y028a
https://spark.lucko.me/T2chk6CJ8y

### "/ae plinfo" link

https://paste.md-5.net/kehemipima

**Comment by ThomasWega** [comment]
If you move to a newer minecraft version the performance should be improved, because we've moved from NBT to PDC

**Comment by ThomasWega** [comment]
If you cannot move, it's understandable. There are some improvements to performance coming to next version anyways, although they are not specific to REPEATING.

**Comment by ThomasWega** [comment]
I'll keep working on improving performance and hopefully improve the REPEATING enough to your liking

**Comment by AleMastro** [comment]
REPEATING has some problems.
Using the plugin reload for a short time there are no delays. (We are talking about tens of minutes, not a few seconds).

It is not just optimization, there is really some problem.



Also I wanted to ask something **offtopic**, unfortunately I can't find any other way to contact you.
I left discord server by mistake and I can't verify myself again.
This makes it impossible for me to open a ticket and communicate with you.
This is my spigot account:
- https://www.spigotmc.org/members/_alemastro_.34285/

**Comment by ThomasWega** [comment]
The bot was probably broken at that moment. Try again now, or create a prepurchase ticket and someone will verify you manually :)
