### ISSUE TITLE
I can't add the fish tracker on my fishing rod

### ISSUE THREAD

**Issue by Leteckk** [GC-spigot/AdvancedEnchantments#4642]
### Describe the bug

I can't put the tracker on my fishing rod

### How to reproduce

Put the tracker on the rod

### "/ae plinfo" link

https://paste.md-5.net/kesisazuhu

### Server Log

no log

**Comment by ThomasWega** [comment]
We need more info. Any errors? What's your config? Any messages in chat? If possible, send a video showcase

**Comment by Leteckk** [comment]
When i try to put the Fishtracker on my rod, the mobtrack stay in my hand and not apply on my fishing rod

**Comment by SirJben** [comment]
After testing this in latest version of AE and 1.21.1, it works fine on my end.

**Comment by Leteckk** [comment]
i play on 1.20.1

**Comment by ThomasWega** [comment]
Are you using a fishing rod without any enchantments? Try a fishing rod with at least one custom enchantment
