### ISSUE TITLE
Plugin enables and disables at the same time

### ISSUE THREAD

**Issue by DuanDuan4017** [GC-spigot/AdvancedEnchantments#4644]
### Describe the bug

just like the title, plugin loads and enable and disable at the same time.

### How to reproduce

Paper 1.20.4 #497
Plugin 9.11.5

### "/ae plinfo" link

Unable to platform.

### Server Log

https://mcpaste.io/7e0ff9c934c7d897

**Comment by SirJben** [comment]
@DuanDuan4017 send your /ae plinfo

**Comment by SirJben** [comment]
or open a ticket through our Discord and send your plugin and `/ae plinfo` there. Thank you.

**Comment by ThomasWega** [comment]
Will most likely be a license issue, which needs to be handled on discord
