### ISSUE TITLE
the default "Overload" enchantment is removing hearts instead of adding them

### ISSUE THREAD

**Issue by Vehzx** [GC-spigot/AdvancedEnchantments#4645]
### Describe the bug

 "Overload" enchantment is removing hearts instead of adding them.

In the video provided, I was told in my ticket to add

`MESSAGE:Heart @Self`

to test, and as we see if does print in chat, so the effects are working, it's just removing the hearts instead of adding them.

### How to reproduce

just enchant a piece of gear with overload, and equip it.

See ticket transcript if needed: 
ae-sirjben-7453

**Paper version: 1.21.1-77-master
AE version: 9.11.6**

### Screenshots / Videos

https://www.youtube.com/watch?v=1VzHnu-Ehxc

### "/ae plinfo" link

https://paste.md-5.net/geduzoxaji

### Server Log

https://mcpaste.io/1ed957cf87737f97

**Comment by ThomasWega** [comment]
This needs to be some other plugin causing it. The only thing that overload does, is that it applies a health boost potion
