### ISSUE TITLE
enchantbook was disappeared when using anvil

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4646]
### Describe the bug

1. If player put enchantment books on anvil and try the combine, it will disappear regardless of the number.
2. It also shows that non-applies-to tools are combined, but it disappears when combined.

3. If you combine 1 level of tool + 1 level of enchantbook, it becomes 2 level of tool,
but if you combine 1 level of tool 2 + 1 level of enchant book, the enchantbook disappears.

### How to reproduce

https://github.com/user-attachments/assets/13d54b10-6ebf-4bcd-8397-a9412ce3ec01

1. enable "anvil-application: true" / "drag-drop-application: false"
2. "enabled: true" in anvil.yml

### "/ae plinfo" link

https://paste.md-5.net/asumevafis

**Comment by ThomasWega** [comment]
> 3\. If you combine 1 level of tool + 1 level of enchantbook, it becomes 2 level of tool,
>         but if you combine 1 level of tool 2 + 1 level of enchant book, the enchantbook disappears.

I might be understanding this incorrectly, but isn't this how it works in vanilla? If you have a pickaxe with efficiency 2 and you combine it with book with efficiency 1 it will just not use the book, but will still allow you do the enchant

**Comment by ThomasWega** [comment]
oh I understand now, you mean even if it has 15 books inside, okay

**Comment by ThomasWega** [comment]
How are you even able to stack books? They should not be stackable as far as I know

**Comment by ThomasWega** [comment]
Will be fixed in the next update
