### ISSUE TITLE
AE enchanted books canceling anvil interact event

### ISSUE THREAD

**Issue by TheCashFire** [GC-spigot/AdvancedEnchantments#4647]
### Describe the bug

There is a feature that, when you have a book enchanted with an AE enchantment, allows you to right click with said book on an anvil and have it give you details about that enchantment. 

The setting in the config, display-right-click-message: true/false, toggles this behavior. The issue is that, when set to false, it prevents the information message from popping up in chat correctly, but the interaction with the anvil is still canceled. 

This should not be the behavior, as turning off this functionality should result in being able to right click on an anvil with an AE book.

### How to reproduce

1 - Use /ae givebook to give yourself any AE book with the correct AE components.
2 - Hold the item in your main hand
3 - Attempt to interact with an anvil using right click

Setting display-right-click-message: false in the config will have this issue appear. You won't be able to open the anvil while holding an AE book since the event is canceled.

### "/ae plinfo" link

https://paste.md-5.net/jowafaguxi

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
