### ISSUE TITLE
Per-Book Lore

### ISSUE THREAD

**Issue by NymWasThere** [GC-spigot/AdvancedEnchantments#4648]
### Describe the bug

I was trying to see if there was a way to make customize lore per book group (Simple, Unique, Elite, Ultimate, Legendary), instead of the universal one in config.yml, like the physical item you get from /ce

### How to reproduce

.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/c9bbb7a2-e332-42c2-9956-bf8e9246412d)
![image](https://github.com/user-attachments/assets/cd72b571-5f0d-4949-9293-0199871577bb)

### "/ae plinfo" link

/ae plinfo skipPlugin

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
