### ISSUE TITLE
Lore Bug

### ISSUE THREAD

**Issue by mysticcraftnetwork** [GC-spigot/AdvancedEnchantments#4650]
### Describe the bug

Hello, I have the following problem. I changed the color of the Simple Book, and now when I add a Simple enchant to a specific item, the lore gets duplicated. When I add another type of enchant, for example, a legendary one, the lore gets tripled.

### How to reproduce

Put a Simple Enchant on an item with a changed color of the Simple Book

### Screenshots / Videos

![bug](https://github.com/user-attachments/assets/ad648bea-df93-43cf-abf1-1f5ec9b218af)
![bug1](https://github.com/user-attachments/assets/c1d003fc-9b24-4905-b6a4-46fbba396d52)

https://github.com/user-attachments/assets/8a5ec635-d652-4e70-bce6-51a1e4f781ac

### "/ae plinfo" link

https://paste.md-5.net/velawavuli

### Server Log

No errors

_No response_

**Comment by ThomasWega** [comment]
Try with default config on server with only AE please
