### ISSUE TITLE
Events for /enchanter and random orb open

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4651]
### Describe the bug

Could you add the console for when someone buys enchantments in the /enchanter or opens a random orb of any kind?

Since this way we could have a way to check events and errors for the bug with the enchanter

### How to reproduce

*

### "/ae plinfo" link

*

**Comment by ThomasWega** [comment]
We will add events for these

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
