### ISSUE TITLE
/ea editor bug

### ISSUE THREAD

**Issue by DennisWolff** [GC-spigot/AdvancedEnchantments#4652]
### Describe the bug

Can't use the command getting unexpected error occured.

### How to reproduce

I just wrote /ae editor

### Screenshots / Videos

![afbeelding_2024-09-23_192613977](https://github.com/user-attachments/assets/b3c0cea7-1cde-4b41-a8c0-5e973e9a1809)

### "/ae plinfo" link

https://paste.md-5.net/uhizatohom

### Server Log

https://mcpaste.io/e7a8d577f8d7401b

**Comment by ThomasWega** [comment]
will be fixed in the next update
