### ISSUE TITLE
Anvil permissions

### ISSUE THREAD

**Issue by Duplimon** [GC-spigot/AdvancedEnchantments#4653]
### Describe the bug

New feature for anvil via permissions.

### How to reproduce

Hello, I wanted to know if I could make a request to add some permissions for the anvil.yml document, the request is the following:

I would like to know if you add some permissions in which, let's say, ae.vanilla-books: this does not allow joining books of the same level, that is, sharpness 5 + sharpness 5 = sharpness 6

I would like to know if you add some permissions in which, let's say, ae.vanilla-items: this does not allow joining books and items of the same level, that is, item + sharpness 5 + book sharpness 5 = item sharpness 6

I don't want my users to start joining books just like that, I just want them to buy them through a trading store or from the same website

I would also like to be able to add a permission, let's say that a book can be joined with an item even if it is already enchanted, this is all with vanilla enchantments.

### "/ae plinfo" link

https://paste.md-5.net/wijonibomu

**Comment by GC-spigot** [comment]
Feature requests have been moved to Discord, and will be now picked by community with votes. Please post your request here instead: https://discord.com/channels/376425582139015168/1292004436952219690/1293177616576024687
