### ISSUE TITLE
Soulbound doesn't work properly

### ISSUE THREAD

**Issue by Nekossendo** [GC-spigot/AdvancedEnchantments#4654]
### Describe the bug

If I enchant e.g. my sword with soulbound and die through any other way than being killed by mobs, soulbound doesn't take effect. No matter how high the chances are.
Even with no changes to the original config for it, it doesn't work.
I've tried:
- Being killed by zombies
- Falling into the void
- /kill
- Fall damage

(For context, the provided video does use a modied version of soulbound with a 100% chance.)

### How to reproduce

Enchant soulbound and try to die.

### Screenshots / Videos

https://www.youtube.com/watch?v=yD4L3roTxN8

### "/ae plinfo" link

https://paste.md-5.net/fusuwociwa

**Comment by TheLaoming** [comment]
Hey, iirc there was (or still is) a bug with soulbound if you put cooldown there. If you doesn't use soulbound with cooldown option, no matter what value it is, it should be fine (at least for me it works). But I tested it a month or two ago with a different version so..

**Comment by Nekossendo** [comment]
> Hey, iirc there was (or still is) a bug with soulbound if you put cooldown there. If you doesn't use soulbound with cooldown option, no matter what value it is, it should be fine (at least for me it works). But I tested it a month or two ago with a different version so..

Hey there! Thank you for your reply. ^^
Unfortunately, I did not use a cooldown in the first place.
It does work fine, but only if I so happen to get killed by an enemy.

**Comment by ThomasWega** [comment]
Send your enchantment and also send a video with `/ae debug enable` please

**Comment by Nekossendo** [comment]
Hello there!
I am sorry, this bug seems to be fixed now.
I have switched version in the meantime, from 9.11.0 to 9.12.2.
I just found out when testing it for you.

**Comment by ThomasWega** [comment]
Okay, glad to hear that
