### ISSUE TITLE
You can get materials from /tinker

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4656]
### Describe the bug

You can get the crystals from menus like /tinker

### How to reproduce

run /tinker and move the crystals to your inventory

### Screenshots / Videos

https://youtu.be/AtxwsHi44_Q

### "/ae plinfo" link

https://paste.md-5.net/uxejekeyox

**Comment by minemalia** [comment]
Same for me. 

able to replicate on a paper 1.21.1 build 99 server with just AdvancedEnchantments 9.11.8 installed.

**Comment by DangCongThang** [comment]
did u fix it?

**Comment by ThomasWega** [comment]
Will be fixed asap. Already have a fix, just waiting for a push
