### ISSUE TITLE
Can steal items from the tinkerer menu

### ISSUE THREAD

**Issue by iLemon** [GC-spigot/AdvancedEnchantments#4657]
### Describe the bug

Since updating to 9.11.8, the tinker doesnt work and you can just take the items out of it.

### How to reproduce

- /tinker
- take item

### Screenshots / Videos

https://github.com/user-attachments/assets/9ecc9aef-3ebc-45e1-98e4-e9f330cf82fd

### "/ae plinfo" link

https://paste.md-5.net/ojecuxeher.css

**Comment by DangCongThang** [comment]
did u fix it?

**Comment by ThomasWega** [comment]
Will be fixed asap. Already have a fix, just waiting for a push
