### ISSUE TITLE
Blackscrolls are not working sense i updated to 1.21

### ISSUE THREAD

**Issue by Teddy293** [GC-spigot/AdvancedEnchantments#4658]
### Describe the bug

So players are trying to use blackscroll and they just disappear and don't give them the book it should and doesnt give them anything it just vanishes 

### How to reproduce

All I do is just have a blackscroll click something that has a custom enchant on it and it just vanishes 

### Screenshots / Videos

https://github.com/user-attachments/assets/8dc85fed-e4cb-4bf4-b8a3-3cd88011a01d

### "/ae plinfo" link

https://paste.md-5.net/lozihiduve

**Comment by SirJben** [comment]
Update your plugin.
