### ISSUE TITLE
 Excessive consumption with advancedenchants

### ISSUE THREAD

**Issue by TheAndresGG** [GC-spigot/AdvancedEnchantments#4659]
### Describe the bug

Hi how are things.

I acquired the AdvancedEnchants plugin for one of my modalities. but unfortunately I have problems

In a test with spark with +70 players online, there is excessive CPU consumption. 
Link: https://spark.lucko.me/KogQznNU5D

I also saw that some plugin processes were causing some small problems. I don't know how to solve it.

How can I optimize this plugin for a BOXPVP modality?

### How to reproduce

CPU Excessive Consumption Happens Like +30 Players Up

### "/ae plinfo" link

https://paste.md-5.net/ixabuxuhuj

![por](https://github.com/user-attachments/assets/7a6eb299-a9d6-4c02-a84f-e5cecf872483)

**Comment by ThomasWega** [comment]
Will be improved in the next update
