### ISSUE TITLE
The effects of enchantments are preserved without having the armor on.

### ISSUE THREAD

**Issue by BeilorDA** [GC-spigot/AdvancedEnchantments#4660]
### Describe the bug

When putting on armor that has an enchantment that gives effects as long as you wear the piece, changing it for another armor of the same type with a right click preserves the effects of the armor that was just changed.

### How to reproduce

By having the armor with effect enchantment on and by changing the armor for another one with right click

### Screenshots / Videos

https://imgur.com/a/Bb2HUSr

### "/ae plinfo" link

https://paste.md-5.net/osanogaqix

**Comment by SirJben** [comment]
Send the enchantment.

**Comment by BeilorDA** [comment]
Lose the configuration
