### ISSUE TITLE
player cann't unlock more enchantment slot

### ISSUE THREAD

**Issue by albedo092** [GC-spigot/AdvancedEnchantments#4666]
### Describe the bug

I already set max unlock slot enchantment to 4 slot.
but when player use mmoitem and apply gem-stone to item. 
Player cann't unlock slot anymore Even though the slot hasn't reached limit 4 yet.

### How to reproduce

none

### Screenshots / Videos

![Screenshot_2](https://github.com/user-attachments/assets/149914ef-7d1c-4120-b65e-f4fe7bf76bc8)

### "/ae plinfo" link

https://paste.md-5.net/junifocefu

### Server Log

nothing  error in log.

**Comment by albedo092** [comment]
![Uploading Screenshot_2.png…]()

**Comment by albedo092** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/5824af14-bba6-4a36-b1c2-36efbe5d3a7b)

**Comment by albedo092** [comment]
here is my config.
and some player can apply 5 enchant to item.

![Screenshot_3](https://github.com/user-attachments/assets/9e2e82e3-7aca-435e-8ee9-a095ef6c018f)
![Screenshot_4](https://github.com/user-attachments/assets/abca1ab6-22bb-4fa1-9306-184fe74dd680)

**Comment by ThomasWega** [comment]
Send the output of `/data get entity @s SelectedItem` while holding the item please

**Comment by albedo092** [comment]
![image](https://github.com/user-attachments/assets/b5227bc1-75c8-4590-8bd9-250e66982f1a)
![image](https://github.com/user-attachments/assets/6c0f0e2b-e565-4b62-abd4-1fa8fcf76c67)
![image](https://github.com/user-attachments/assets/0035b9d3-7ecc-4095-9ab3-9d222f89f4ae)
![image](https://github.com/user-attachments/assets/99d3db9e-f47c-431a-a284-01a2b1a9b198)
![image](https://github.com/user-attachments/assets/356dd54e-922c-4dda-a5ed-cd1e7c10e971)

**Comment by albedo092** [comment]
sorry for late reply

**Comment by albedo092** [comment]
![image](https://github.com/user-attachments/assets/ea3631eb-c85d-4a7e-aba2-1093362420a8)

Can be used to remove gem-stones from mmoitem and add new encharges over time. There are no limits as shown in the picture.

**Comment by albedo092** [comment]
https://youtu.be/x0ecU7D8FVg

Here is a video of how to make a bug.

**Comment by ThomasWega** [comment]
We've had issue with MMOItems because they were using NBT and PDC incorrectly. This is most likely the exact same issue
