### ISSUE TITLE
Plugin is lagging the server

### ISSUE THREAD

**Issue by xProMDFKx** [GC-spigot/AdvancedEnchantments#4668]
### Describe the bug

So basically when there are more than 60/70 players, AdvancedEnchantments is lagging the server a lot
Here is the spark: https://spark.lucko.me/vA2HfFwfoG

### How to reproduce

Just use the plugin with many players

### Screenshots / Videos

https://spark.lucko.me/vA2HfFwfoG

### "/ae plinfo" link

https://paste.md-5.net/hazukukejo

### Server Log

https://mclo.gs/xQKRolZ

**Comment by xProMDFKx** [comment]
Another spark: https://spark.lucko.me/UPelXq5jH5

**Comment by ThomasWega** [comment]
Improved performance by more than 17%. Available next update!
