### ISSUE TITLE
Diploid Dupe

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#4669]
### Describe the bug

https://cdn.discordapp.com/attachments/1293775444524404747/1293775491752398878/IMG_0618.mov?ex=670899d2&is=67074852&hm=aa2ad6432ac560ac3a71596d0abb7a206ac7ecd947608c96f61ac21d313b2b27&

Diploid enchant can dupe the item mobs are holding in their items, so basically if you throw 10000m cheque or vanilla items like 64 netherite blocks u can dupe them

### How to reproduce

https://cdn.discordapp.com/attachments/1293775444524404747/1293775491752398878/IMG_0618.mov?ex=670899d2&is=67074852&hm=aa2ad6432ac560ac3a71596d0abb7a206ac7ecd947608c96f61ac21d313b2b27&

Diploid enchant can dupe the item mobs are holding in their items, so basically if you throw 10000m cheque or vanilla items like 64 netherite blocks u can dupe them

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1293775444524404747/1293775491752398878/IMG_0618.mov?ex=670899d2&is=67074852&hm=aa2ad6432ac560ac3a71596d0abb7a206ac7ecd947608c96f61ac21d313b2b27&

### "/ae plinfo" link

https://paste.md-5.net/ofobuwavic

**Comment by ThomasWega** [comment]
That seems really weird. It used to be a bug but we are already removing the equipment of the mob from the MORE_DROPS effect bonus drops 
![image](https://github.com/user-attachments/assets/9ab171ef-3ceb-48bb-814a-67c8760a3545)

**Comment by Rexmen1** [comment]
ty

**Comment by Rexmen1** [comment]
> Something needs to be adding the drops to the event drops. Some other plugin. Which is not the correct way

Are you saying its some other plugin's fault not AE? Cmon really? Again?

**Comment by ThomasWega** [comment]
There was this issue 800 issues ago. It was fixed, tested and worked completely fine from that point on. Now I've retested it, debugged it and every equipment the mob has is removed the loot. I cannot reproduce your issue, but did all the debugging anyways to make sure. If you have any other idea what I can do, feel free to let me know. I'd like to help you more

**Comment by GC-spigot** [comment]
![image](https://github.com/user-attachments/assets/80bc25ef-df5f-41f0-bc3c-9c0325babbf8)
We may be able to help further if we get to see this video, linking content from discord is just not the right way to do it - it gets removed almost instantly or links expire. What enchantment combination do you have on the items?
