### ISSUE TITLE
Switching ranged items causes issues

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4670]
### Describe the bug

If you damage someone with a ranged item (like a bow) but JUST after firing the projectile, you switch the item in your hand (so when the EntityDamageByEntityEvent is fired, you're holding a different item) it has a chance to fire the custom enchants of the item you switched to

### How to reproduce

- Hold a range weapon
- Fire it at a player
- Switch the item in your hand to another item (with a custom enchant) BEFORE the projectile hits the player
- It can activate the custom enchant of the switched item. I have attached a video where you can see me switching to the Axe which has the "Morale" enchant that has a 100% chance to give absoroption

https://github.com/user-attachments/assets/216f7e7b-9cd9-4ce0-a845-85dd95ed3046

### "/ae plinfo" link

https://paste.md-5.net/pawotumatu

**Comment by ThomasWega** [comment]
Can you please send your enchantments?

**Comment by ThomasWega** [comment]
retest on the latest version. Seems to be fixed. If not, please send the enchantments

**Comment by JHarris12345** [comment]
@ThomasWega It's fixed for arrow projectiles but not for other projectiles. I have custom items where people can shoot fireballs etc

Here is my enchantments https://paste.md-5.net/ralonapuna.bash
