### ISSUE TITLE
VERY HIGH LOAD! MiningTrigger.onBlockBreak() [LATEST]

### ISSUE THREAD

**Issue by GG-MD** [GC-spigot/AdvancedEnchantments#4672]
### Describe the bug

Hey, there's too much load on the server from enchantments...
`[18:21:39] [Paper Async Task Handler Thread - 0/INFO]: [⚡] Tick #164290 lasted 385.52 ms. (676.48% increase from avg)`

`/spark profiler start --only-ticks-over 200`: https://spark.lucko.me/hKTd8xEMpR

### How to reproduce

-

### "/ae plinfo" link

https://paste.md-5.net/onerobeyiw

### Server Log

https://pastes.dev/8dtcE8Va09

**Comment by GG-MD** [comment]
two profiler: https://spark.lucko.me/yYLX91yflE

**Comment by ThomasWega** [comment]
Confirmed. Currently discussing possible solutions

**Comment by ThomasWega** [comment]
Actually, after second look, every plugin has this issue on your report. So is cannot possible be only us. It needs to either be a global issue or a server issue. We only have the most listeners and that's why we rank the highest

**Comment by ThomasWega** [comment]
It also doesn't seem to be affecting TPS at all

**Comment by GG-MD** [comment]
> It also doesn't seem to be affecting TPS at all

In the TPS reports, it isn't visible, but it dropped to 10-15, rarely, but accurately. I don't know :)

**Comment by GG-MD** [comment]
Wait for the next messages then :)  
The problem is definitely with you.  
This is evident from the last report: everyone is at 5%, but you are at 20%. Therefore, this is a huge spike for you, since the measurement was from 200 mspt. It shows how much each one exceeded :)  
Alright, we’ll keep an eye on it.

**Comment by ThomasWega** [comment]
It is on 20% because in one listener we check 4 or 5 inventories, thus 4 or 5 of the same method which in your case causes performance issue. The math seems to align there. The weird thing is that these checks are causing so much performance issues to you even though the shouldn't. That is not only case with our plugin in your report

**Comment by ThomasWega** [comment]
I am not denying we are not more performance intensive in this case. What I am saying is that these checks should be pretty cheap to make and shouldn't make any difference

**Comment by GG-MD** [comment]
> I am not denying we are not more performance intensive in this case. What I am saying is that these checks should be pretty cheap to make and shouldn't make any difference. In your case even one check seems to be causing huge performance issues on every plugin. We just have more of these checks

A, okay, thx u
