### ISSUE TITLE
Incompatibility EliteMobs 

### ISSUE THREAD

**Issue by servicomcr** [GC-spigot/AdvancedEnchantments#4673]
### Describe the bug

En español:

Hola,

Quería reportar una incompatibilidad entre el plugin AdvancedEnchantments y el comando /ag. He notado que el comando /ag es utilizado por EliteMobs para teletransportar a los jugadores a su gremio. Cuando los jugadores intentan ejecutar este comando, no pueden teletransportarse al mundo del gremio de EliteMobs.

¿Hay alguna manera de resolver este conflicto o considerar cambiar el comando en futuras actualizaciones?

Gracias por tu atención.

In English:

Hello,

I wanted to report an incompatibility between the AdvancedEnchantments plugin and the /ag command. I have noticed that the /ag command is used by EliteMobs to teleport players to their guild. When players try to execute this command, they are unable to teleport to the EliteMobs guild world.

Is there any way to resolve this conflict or consider changing the command in future updates?

Thank you for your attention.

### How to reproduce

Install EliteMobs and AdvancedEnchantments 

### "/ae plinfo" link

https://paste.md-5.net/cavagowuni

**Comment by ThomasWega** [comment]
This should be a suggestion. Something to allow to change the commands name. Suggestions are supposed to be on the discord starting few weeks ago. Please post it there. Github is only for issues

**Comment by servicomcr** [comment]
??

hello
