### ISSUE TITLE
Newest versions no longer work with version 1.8.x even though this plugin used to

### ISSUE THREAD

**Issue by Jabhacker** [GC-spigot/AdvancedEnchantments#4674]
### Describe the bug

new versions of AE dont support 1.8, even though old versions of it did, how would I download an older version to be able to use it again? or is it gone forever

### How to reproduce

go to the website
only the newest version of the plugin is availble
it no longer supports 1.8

### "/ae plinfo" link

https://paste.md-5.net/upomefofif

**Comment by GC-spigot** [comment]
1.8 support has been dropped 1.5 year ago on `Mar 31, 2023`. We do not provide any support or help with it anymore. Move on.

**Comment by Jabhacker** [comment]
then is there anyway to access whatever version from 2023 supported 1.8?
