### ISSUE TITLE
1.20.4 > 1.21.1 messed up enchants

### ISSUE THREAD

**Issue by sennby** [GC-spigot/AdvancedEnchantments#4679]
### Describe the bug

Description of the Bug:so i tried to apply a trench ce book on my shovel it had 99% and was max lvl i applied it to my shovel it didnt say success or fail but the book vanished and the pics trench lvl was still the same as before i applied it then i tried to recreate it with a telepathy cebook same scenario max lvl 100% tried to put it on another tool applied it book vanished didnt say anything in chat and the book vanished but the lvl stayed the same 

### How to reproduce

Report from player was this:

 
Description of the Bug:so i tried to apply a trench ce book on my shovel it had 99% and was max lvl i applied it to my shovel it didnt say success or fail but the book vanished and the pics trench lvl was still the same as before i applied it then i tried to recreate it with a telepathy cebook same scenario max lvl 100% tried to put it on another tool applied it book vanished didnt say anything in chat and the book vanished but the lvl stayed the same 

I then wanted to see if the pickaxe (a normal netherite pickaxe..) had the enchant so i grabbed the pickaxe from him and then: /advancedenchantments enchant telepathy 1 as it stated it had it on it already. So i ran it, and got an error. Couldnt do anything with that command to apply (or remove) whatever it wouldve been. Somethings messed up here.

### Screenshots / Videos

![{63654035-A32F-4028-AD8A-863547FD986E}](https://github.com/user-attachments/assets/ffa5e4c0-f6f0-4aef-bfd0-6e372c1a6903)

### "/ae plinfo" link

https://paste.md-5.net/cupogunosa

### Server Log

https://mclo.gs/T4tV70P

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Can you send a video of this happening please?

**Comment by ThomasWega** [comment]
also, some fixes were made in the latest version of the plugin, so update first and then re-test please
