### ISSUE TITLE
GodlyOverload bug Health boost

### ISSUE THREAD

**Issue by mrsandia23** [GC-spigot/AdvancedEnchantments#4680]
### Describe the bug

So when I take off a piece of armor that has godlyoverload and I have it also in another part like the boots it takes my hearts like the heal boost disappears and it appears.

### How to reproduce

I use 2 godly overload enchants in my armor and I take off one piece.

### Screenshots / Videos

https://github.com/user-attachments/assets/c181a673-9f00-45ba-b05e-ca31134bf304

### "/ae plinfo" link

https://paste.md-5.net/gifofemaco

### Server Log

file:///C:/Users/lazzy/Downloads/latest.log

### Filled out form correct and using latest version

I confirm

**Comment by mrsandia23** [comment]
https://youtu.be/ol4weS-gwII

**Comment by ThomasWega** [comment]
Should be fixed in the next update
