### ISSUE TITLE
Multiplication Enchant doesn't appear to be working?

### ISSUE THREAD

**Issue by Jmichaelz** [GC-spigot/AdvancedEnchantments#4681]
### Describe the bug

It doesn't seem that the multiplication enchant is working? I even modified it in the enchantments.yml for 100% chance and removed the conditions so it doesnt require you to have souls to activate it, and it doesn't seem to multiply the ores. I have sat here using deepslate and regular stone diamond ore and was trying to see if it would multiply the drops, but it doesn't.

### How to reproduce

1. grab a pickaxe
2. do /ae enchant multiplication 5 while holding the said pickaxe
3. start mining away

### "/ae plinfo" link

https://paste.md-5.net/ebodulogil

### Server Log

https://paste.md-5.net/ebodulogil

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Are you mining natural blocks or player placed blocks?
