### ISSUE TITLE
Can the whole config not get reset due to one extra space not being there in config?

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#4682]
### Describe the bug

![image](https://github.com/user-attachments/assets/c16f2704-2001-4e28-9708-88d860f70ed9)
Can the whole config not get reset due to one extra space not being there in config?

### How to reproduce

Can the whole config not get reset due to one extra space not being there in config?

### "/ae plinfo" link

not needed

### Filled out form correct and using latest version

I Confirm

**Comment by Rexmen1** [comment]
can't seem to figure out whats the issue in this config
harvest:
  display: '%group-color%Harvest'
  description: 'Chance to multiply farm drops.'
  applies-to: Hoe
  type: MINING
  group: LEGENDARY
  applies:
    - ALL_HOE
  levels:
    '1':
      chance: 10
      settings:
        whitelist:
          - "WHEAT"
          - "POTATOES"
          - "BEETROOTS"
          - "CARROTS"
          - "NETHER_WART"
          - "SUGAR_CANE"
          - "BAMBOO"
          - "COCOA_BEANS"
          - "PUMPKINS"
          - "MELONS"
          - "SEEDS"
      effects:
        - MORE_DROPS:2

**Comment by ThomasWega** [comment]
Send your enchantments file

**Comment by GC-spigot** [comment]
This is how .yml files work, we do not do this. The parsing system is done by YAML system, not us. You should verify YAML files using this: https://yaml-online-parser.appspot.com
