### ISSUE TITLE
Trench enchant is causing server lagg

### ISSUE THREAD

**Issue by xProMDFKx** [GC-spigot/AdvancedEnchantments#4684]
### Describe the bug

Trench enchant is causing server lagg

### How to reproduce

You just need players to use that trench enchant

### Screenshots / Videos

https://spark.lucko.me/k8K2I5f4LE

### "/ae plinfo" link

https://paste.md-5.net/ijirucoluh

### Server Log

https://mclo.gs/QTOtSzR

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
We are basically at the limit of trench optimizations. We are already using NMS to remove the blocks and the only thing that is causing performance issues in your case is us calling BlockBreakEvents, so other plugins can listen to that and we keep compatibility. Not much there to optimize as well. I'll try looking into it more, and see if I am able to do at least some more. In the meantime, I recommend you try to limit the radius of the trench to lower numbers
