### ISSUE TITLE
Console Error: CAVE_VINES_PLANT isn't an item

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#4689]
### Describe the bug

Console Error:
- CAVE_VINES_PLANT isn't an item
- CAVE_VINES isn't an item

https://mclo.gs/x37mhae

### How to reproduce

- Use latest version of AE
- Check console

### "/ae plinfo" link

https://paste.md-5.net/igulebusih

### Filled out form correct and using latest version

I confirm

**Comment by GC-spigot** [comment]
Fixed next update!
