### ISSUE TITLE
inques haviing problem

### ISSUE THREAD

**Issue by report101** [GC-spigot/AdvancedEnchantments#469]
i get spam in my chat | console whenever someone useing an inquisitive enchant to GRIND
server ver:1.8.9
plugin ver: 5.6.5

https://cdn.discordapp.com/attachments/579584270771945472/579584372685144074/JPEG_20190519_153619.jpg

19.05 12:38:46 [Server] INFO Could not pass IllegalStateException: Asynchronous entity add!
19.05 12:38:46 [Server] INFO Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.f(RunnableEffect.java:793)
19.05 12:38:46 [Server] INFO Extra info: effect[EXP:8]; enchant[inquisitive]; mc[188]; ae[5.6.5]
19.05 12:38:46 [Server] INFO If you cannot indentify cause of this, contact developer providing this report.

**Comment by GC-spigot** [comment]
Issue caused by WildStacker http://prntscr.com/nr09q7 - set this to false
