### ISSUE TITLE
Minecraft Bedrock Anvil Enchanting Issue

### ISSUE THREAD

**Issue by servicomcr** [GC-spigot/AdvancedEnchantments#4690]
### Describe the bug

**Español:**

"Hola, buenos días. Tengo una consulta: ¿cómo puedo hacer para que las personas usen el yunque para encantar? Los jugadores de la edición Bedrock están teniendo problemas, ya que no pueden arrastrar el libro encantado sobre el ítem para encantarlo, y cuando intentan usar el yunque, tampoco los deja hacerlo. ¿Hay alguna solución para esto?"

**Inglés:**

"Hello, good morning. I have a question: how can I allow players to use the anvil for enchanting? Bedrock edition players are having trouble because they can't drag the enchanted book onto the item to enchant it, and when they try to use the anvil, it doesn't let them either. Is there any way to fix this?"

### How to reproduce

**Español:**

1. Inicia sesión en Minecraft Bedrock Edition como jugador normal (no administrador).
2. Intenta encantar un ítem con un libro encantado arrastrando el libro sobre el ítem en el inventario.
3. Observa que el ítem no se encanta.
4. Ahora intenta usar un yunque:
   - Coloca el ítem en el primer espacio del yunque.
   - Coloca el libro encantado en el segundo espacio del yunque.
5. Observa que tampoco se puede encantar desde el yunque.

**Notas adicionales**:
- No se encontró ningún permiso específico relacionado con el encantamiento desde el yunque que pueda estar afectando a los jugadores normales.

**Inglés:**

1. Log into Minecraft Bedrock Edition as a regular player (not admin).
2. Try to enchant an item with an enchanted book by dragging the book onto the item in the inventory.
3. Notice that the item does not get enchanted.
4. Now try using an anvil:
   - Place the item in the first slot of the anvil.
   - Place the enchanted book in the second slot of the anvil.
5. Notice that enchanting still doesn't work with the anvil either.

**Additional Notes**:
- No specific permissions related to enchanting via an anvil were found that might be affecting regular players.

https://github.com/user-attachments/assets/88c4e975-e941-4fdb-8d95-b0521dbfa7db

### "/ae plinfo" link

https://paste.md-5.net/nosiceyufo

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
If you are using bedrock you are basically on your own. If we were able to fix this, we would already. It's just impossible for us. There were some people who had this issue as well and fixed it, although no one ever told us how unfortunately.

**Comment by Folas1337** [comment]
No need to reopen but I still wanted to let @servicomcr know that this is a fix that actually works (requires PacketEvents however): https://modrinth.com/plugin/geyser-recipe-fix
