### ISSUE TITLE
Bait drops fish in water

### ISSUE THREAD

**Issue by Sckaletz** [GC-spigot/AdvancedEnchantments#4691]
### Describe the bug

With Bait enchant on the fishing rod, the extra fish you get from Bait is dropped in the water. This happens to all our players, if they have Bait on their fishing rods.

Video clip: https://medal.tv/games/minecraft/clips/iWF6apBvbthsTqNxZ?invite=cr-MSx1TXcsNzM1MDU0Myw

### How to reproduce

Using Paper 1.21.1 (latest version as of today) and AE latest version add Bait to a fishing rod and fish.

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/iWF6apBvbthsTqNxZ?invite=cr-MSx1TXcsNzM1MDU0Myw

### "/ae plinfo" link

https://paste.md-5.net/oxokizokuc

### Server Log

https://mcpaste.io/707847715c855167

### Filled out form correct and using latest version

I Confirm

**Comment by ThomasWega** [comment]
We know about this and as far as we've tested we were not able to add item to the hook, so it goes in the same direction as the original caught item. This is a limitation for now. You can suggest this a feature request on our github
