### ISSUE TITLE
Dupe bug with the 'SMELT' effect.

### ISSUE THREAD

**Issue by Joaofixe** [GC-spigot/AdvancedEnchantments#4692]
### Describe the bug

Shulker boxes can be duplicated when broken with an item enchanted with an enchantment that has a SMELT effect.

### How to reproduce

Enchant a tool (pickaxe) with an enchantment that has a SMELT effect, place a shulker, break it, and then place it again, a copy will appear in your inventory.

### "/ae plinfo" link

https://paste.md-5.net/awayufoyog

### Server Log

https://mcpaste.io/bed954ba15c9479d

### Filled out form correct and using latest version

I confirm

**Comment by Joaofixe** [comment]
Video to explain the bug

https://www.youtube.com/watch?v=abUTkjSuMS0

**Comment by GC-spigot** [comment]
Thank you for the video, we are thinking it could be an incompatibility with other plugin. Here is my testing, first pickaxe has SMELT and second pickaxe has no enchants - just like your tools
https://gyazo.com/e91248e4de186a15bf70d17999b46c68

That protection plugin may be a problem. Is this user an OP in this video?

**Comment by Joaofixe** [comment]
Yes, the user in the video is an OP, but regular players are also able to do it.

**Comment by ThomasWega** [comment]
Removing plugins in parts and re-testing

**Comment by ThomasWega** [comment]
first I'd start with having just AE on the server, so you can see if it happens with no other plugins
