### ISSUE TITLE
Gemify enchant + Silk touch bug

### ISSUE THREAD

**Issue by StayRelentless** [GC-spigot/AdvancedEnchantments#4693]
### Describe the bug

By using both enchants it will result in infinite ores.

### How to reproduce

Basically by using this combination on an ore block it will pop out the ore block aswell as a diamondblock sometimes

### "/ae plinfo" link

https://paste.md-5.net/gapeciwocu

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Will be fixed in the next update
