### ISSUE TITLE
problem with fill-item on customcommands.yml

### ISSUE THREAD

**Issue by MysticNetworkServer** [GC-spigot/AdvancedEnchantments#4694]
### Describe the bug

    fill-item:
      type: PAPER
      id: 0
      force-glow: false
      name: ' '

      lore: []
      custom-model-data: 18000
      material: PAPER
      
      
      --------------------------------
      
      If I place the fill-item like this and click on it, an error message appears in the chat.
      
![image](https://github.com/user-attachments/assets/9d25a84e-927a-4fe0-80ff-76e53fade722)

![image](https://github.com/user-attachments/assets/3c830ba3-b05e-4afc-a135-514a9b56742a)

### How to reproduce

set fill-item to a type other than glass pane
![image](https://github.com/user-attachments/assets/718ec8c6-3832-4819-a69e-f760ec98bf84)

### "/ae plinfo" link

https://paste.md-5.net/xoguzibaki

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Thanks for reporting
