### ISSUE TITLE
enchants fail to activate and missing

### ISSUE THREAD

**Issue by leblub** [GC-spigot/AdvancedEnchantments#4695]
### Describe the bug

when starting, the console send the attached text

also ingame, some effects fail to activate because of false target = mob or smth like that

![WhatsApp Bild 2024-10-26 um 08 52 36_f74c62e6](https://github.com/user-attachments/assets/0366e5a3-9b0a-4c92-80e2-5fc4e9ec6ce2)

### How to reproduce

fixxing the activation of enchantments and missing ones

### "/ae plinfo" link

https://paste.md-5.net/ilipahuqiy

### Filled out form correct and using latest version

I confirm

**Comment by SirJben** [comment]
@shaunwah it means you don't have those groups in your groups.yml. Either you change it to your existing groups or add those missing groups in groups.yml to make it work. It's not a bug, open a ticket in Discord Server for further assistance.
