### ISSUE TITLE
Whitescroll as an ordinary map.

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#4696]
### Describe the bug

![image](https://github.com/user-attachments/assets/0bcb598f-c7a1-4ccd-8a9e-f842bf3eca12)

### How to reproduce

Get an ordinary map, rename it "White Scroll," and it will function like an AE White Scroll—apply it to any item.

### "/ae plinfo" link

https://paste.md-5.net/ogekajiyof

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Fixed in the next update
