### ISSUE TITLE
License exceeded maximum number of unique IPs

### ISSUE THREAD

**Issue by MFRCraft** [GC-spigot/AdvancedEnchantments#4698]
### Describe the bug

Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### How to reproduce

hello, this is the owner of the ae plugin, right, can I ask about the licensing problem, because I have paid for the plugin 2 months ago, 3 days after this suddenly the IP limit has reached the maximum, so can you find a solution to the problem of the licensing part of the ae plugin?

### "/ae plinfo" link

-

### Server Log

https://mcpaste.io/c93a43736e9c5d86

### Filled out form correct and using latest version

I confirm

**Comment by SirJben** [comment]
Join in our Discord Server and open a ticket. https://discord.com/invite/advancedplugins
