### ISSUE TITLE
Cant Create Ticket Support Discord

### ISSUE THREAD

**Issue by MFRCraft** [GC-spigot/AdvancedEnchantments#4699]
### Describe the bug

**Sorry, you have to buy the plugin on ae on the main website or spigot directly**
forgot to screenshot the verification error section

![image](https://github.com/user-attachments/assets/fbe27c88-0f56-44ab-9278-1edf39e048eb)

### How to reproduce

hello, I've tried verification from discord, but it says you have to buy the plugin on ae on the main website or spigot directly even though I already bought the ae plugin on buildbybit, does buildbybit not include verification?
![image](https://github.com/user-attachments/assets/796b719b-ebd5-4ce4-8fdd-9d6f45b28ca3)

### "/ae plinfo" link

-

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
The bot had some issues. Should be fixed now. If you cannot verify yourself with the bot, you can always open a ticket of any type and someone will verify you manually
