### ISSUE TITLE
Stealing item from gui

### ISSUE THREAD

**Issue by newbie029** [GC-spigot/AdvancedEnchantments#470]
https://streamable.com/mfztg
How to produce this
Shift + left click on the gui item, then fast press ESC

work with all AdvancedEnchantments GUI

paperspigot 1.12.2
advancedenchantments 5.6.5
#468

**Comment by newbie029** [comment]
I used 1.14.1 client on the video, so I retest it with 1.12.2 (which same with the server version)
https://i.imgur.com/KczEvs9.png
the bug still happening

**Comment by GC-spigot** [comment]
Are you sure this is not a visual glitch? If it happens WITH all GUIs then it's an issue on your server.

**Comment by newbie029** [comment]
All GUI from advancedenchaments, such as tinkerer, alchemist, etc

**Comment by newbie029** [comment]
Its not a visual glitch, I can get all things from all /gkit /tinkerer /alchemist (all gui from advancedenchantments) etc
https://i.imgur.com/9ZR5xpB.png
https://i.imgur.com/WQsrls7.png

**Comment by newbie029** [comment]
Tested with a fresh server
https://i.imgur.com/UDuJHs9.png

**Comment by GC-spigot** [comment]
@newbie029 contact me on discord GC#0830
