### ISSUE TITLE
suggestion books custom model

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#4702]
### Describe the bug

add the possibility of creating customized books so that we can create various skins for the books

replanter:
  display: '%group-color%Replanter'
  custom-model-data: 0 <------------------------------------ here
  description: |- 
  Replant seeds.
  applies-to: Hoes
  type: MINING
  group: UNIQUE
  applies:
    - ALL_HOE
  levels:
    '1':
      conditions:
        - '%is crop% = false : %stop%'
        - '%is fully grown% = false : %stop%'
      effects:
        - PLANT_SEEDS:0:%block drop type%
        
        some examples of how it would look: 
        1°https://prnt.sc/SmOoJsCN-mbk
        2° https://prnt.sc/H8If_4bNbvoL

### How to reproduce

no error

### "/ae plinfo" link

no error

### Server Log

no error

### Filled out form correct and using latest version

no error

**Comment by ThomasWega** [comment]
Suggestions have been moved to discord. I also think it's already suggested there, but if it's not, feel free to add it
