### ISSUE TITLE
Mobs from Spawners

### ISSUE THREAD

**Issue by Jmichaelz** [GC-spigot/AdvancedEnchantments#4703]
### Describe the bug

Mobs from spawners do not drop the custom enchanted books, but natural generated mobs do.

### How to reproduce

Grab a spawned and put mob in there to see that it doesn’t drop any custom advanced enchantment books.

### "/ae plinfo" link

https://paste.md-5.net/zutuludeze

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Check config.yml
![image](https://github.com/user-attachments/assets/36f46a0a-1535-423e-a6ae-154a9c55ed81)
