### ISSUE TITLE
items don't get enchant glow after disenchanting them (with a custom enchant with or without vanilla enchants) on grindstone

### ISSUE THREAD

**Issue by kingakis2** [GC-spigot/AdvancedEnchantments#4704]
### Describe the bug

if you enchant a item like a diamond helmet, pickaxe or bow you will get the glow effect but, if you get a custom enchant with that enchanting too and you go and disenchant the item on a grindstone and enchant it again it will don't get the glow effect

### How to reproduce

enchant a item like a bow, you will get the glow effect and the enchantments, make sure you get a custom enchant like bowmaster 5

disenchant him on a grindstone

enchant it again, it will not get any glow effect now, it will get glow effect if the item only was disenchanted with vanilla enchants

### "/ae plinfo" link

https://paste.md-5.net/boqorayupo

### Filled out form correct and using latest version

I confirm

**Comment by kingakis2** [comment]
i have tested it more and it seems that it occurs with all items when they have a custom enchant on it

**Comment by ThomasWega** [comment]
Can you send a video please? They both get glow just fine for me

https://github.com/user-attachments/assets/a50fe8f3-03fb-4805-b32f-b624ed7224e6

**Comment by kingakis2** [comment]
hello, try it on a enchanting table

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thanks for reporting
