### ISSUE TITLE
java.lang.IllegalArgumentException: Health value (210.0) must be between 0 and 44.0. (attribute base value: 44.0, player: ydeptraiso1)

### ISSUE THREAD

**Issue by tuanhp0** [GC-spigot/AdvancedEnchantments#4705]
### Describe the bug

![image](https://github.com/user-attachments/assets/c491d09b-c98c-4656-8c11-fd6a6b838ea4)
godlyoverload:
  display: '%group-color%Quá tải thần thánh'
  description: "Cho người mặc hiệu ứng\nHEALTH_BOOST IV(+1/level)(tăng máu tối đa) vĩnh viễn.\nYêu cầu Quá tải V mê hoặc trên vật phẩm để áp dụng.\nKhông thể dùng cuộn đen để tháo CE này."
  applies-to: 'Giáp'
  type: 'EFFECT_STATIC'
  group: 'FABLED'
  settings:
    required-enchants:
      - 'overload:3'
    removed-enchants:
      - 'overload'
    removeable: false
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - 'POTION:HEALTH_BOOST:4'
    2:
      effects:
        - 'POTION:HEALTH_BOOST:5'
    3:
      effects:
        - 'POTION:HEALTH_BOOST:6'
    4:
      effects:
        - 'POTION:HEALTH_BOOST:7'
    5:
      effects:
        - 'POTION:HEALTH_BOOST:8'

### How to reproduce

join Corearena and out
I unfortunately cannot reproduce the issue, the health is properly reduced upon leaving the arena, you dont need to set any command to edit any attributes: https://www.loom.com/share/a3bc41159b6a45c4b6196ead081cbc40

The only issue I have is that the health is only given then I take and give again the equipment to myself, but this is something you need to contact the enchant plugin author about.

Looks like an issue with the other plugin. I unfortunately dont have that much time to debug issues with third party plugins. I hope you understand. Thank you.

### "/ae plinfo" link

https://paste.md-5.net/ohoyatedat

### Server Log

(https://mcpaste.io/18449f4af5f9a915)

### Filled out form correct and using latest version

Ic confirm

**Comment by GC-spigot** [comment]
We cannot fix this, only that plugin can unfortunately. They are setting the wrong amount of health player uses, as you can see error is from them.

**Comment by kangarko** [comment]
Apologizes, I responded on the ticket I have at my plugin.
