### ISSUE TITLE
When I use a specific kernel, resource usage increases too much. Is there a way to resolve this?

### ISSUE THREAD

**Issue by ii109** [GC-spigot/AdvancedEnchantments#4707]
### Describe the bug

When I use a specific kernel, resource usage increases too much. Is there a way to resolve this?
![image](https://github.com/user-attachments/assets/2722088b-c496-4272-a005-702c5b76923b)

### How to reproduce

It generates too many resources. This happens when you upgrade to the latest version.

### "/ae plinfo" link

https://paste.md-5.net/axutemoxev

### Filled out form correct and using latest version

confirm

**Comment by ThomasWega** [comment]
We need the full spark report
