### ISSUE TITLE
Telepathy Durability Bug & Shulker Box Bug

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#471]
Bukkit: Paperspigot 1.13.2
Plugin Version: Lastest Version

- Items with telepathy enchantment have a durable enchant effect
It does not work. 
https://youtu.be/b3v9t6_KCKI

- Items with telepathy can not break a Shulker box.
https://youtu.be/sUeg83nsMHY

**Comment by GC-spigot** [comment]
2nd issue - intentionally made that way so shulker boxes do not lose their items.
1st issue - fixed!
