### ISSUE TITLE
player can get farmland with silktouch + TP_DROPS

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4712]
### Describe the bug

player can get farmland with silktouch + TP_DROPS.
farmland is not vanilla items that player can't get.

### How to reproduce

1. make tools 100% TP_DROPS + silktouch
2. break farm land

### "/ae plinfo" link

https://paste.md-5.net/repikadiqu

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Wasn't this issue already here not that long ago?

**Comment by Ecilpse** [comment]
> Wasn't this issue already here not that long ago?

it's another issues. this issues problems with silktouch

**Comment by ThomasWega** [comment]
Fixed in the next update
