### ISSUE TITLE
Inconsistent placeholders naming for locale and menus

### ISSUE THREAD

**Issue by qwerio** [GC-spigot/AdvancedEnchantments#4713]
### Describe the bug

%description% in locale is %desc% in the menus
%max-level% in locale is %max-lvl% in the menus

There may be more..

### How to reproduce

Just try using the same placeholder name in the two config files.

### "/ae plinfo" link

https://paste.md-5.net/uwiwurupah

### Filled out form correct and using latest version

confirm

**Comment by GC-spigot** [comment]
We are aware, but due to the sheer number of users its not possible to change them. This isn't a bug report just an insight.
