### ISSUE TITLE
EAT with DeluxeCombat

### ISSUE THREAD

**Issue by leogianfagna** [GC-spigot/AdvancedEnchantments#4715]
### Describe the bug

DeluxeCombat changes the enchanted golden apple recipe and behavior. Using DeluxeCombat custom apple, will not trigger the "EAT" trigger.

### How to reproduce

1. Use deluxecombat and modify the enchanted golden apple (like to 1.8 cap)
2. Create a "EAT" enchantment
3. EAT the golden apple and see

### "/ae plinfo" link

https://paste.md-5.net/jinuguboxi.css

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
We just listen to PlayerItemConsumeEvent on priority HIGHEST. If DeluxeCombat cancels it or modifies it in any way I see it more of their issue then ours. I will be happy to do something about it but I'd need to see their code first
