### ISSUE TITLE
You can apply the holy whitescrolls to the holy whitescrolls

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4717]
### Describe the bug

You can apply the holy whitescrolls to the holy-whitescrolls, that is, if by mistake you click on another You can apply the holy whitescrolls to the holy-whitescrolls with a You can apply the holy whitescrolls to the holy-whitescrolls, it will be added with the protection.

### How to reproduce

click with a holy-whitescrolls on top of another holy-whitescrolls

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/78e957d9-2a6c-4ea2-b609-357ae6cf2547)

### "/ae plinfo" link

https://paste.md-5.net/otoqebarim

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
The item just stacks as usual for me. Do you mind sending a showcase video please?

**Comment by Z3r0xh** [comment]
Sorry for the delay in replying, I've been away for a while.

https://youtu.be/4PS816nBNyg

> The item just stacks as usual for me. Do you mind sending a showcase video please?

**Comment by ThomasWega** [comment]
Send your config.yml please

**Comment by Z3r0xh** [comment]
> Send your config.yml please

https://mclo.gs/xUT5gSa

**Comment by ThomasWega** [comment]
Should be fixed in the next update
