### ISSUE TITLE
Bug when putting the same charm on the item

### ISSUE THREAD

**Issue by hotbonnix** [GC-spigot/AdvancedEnchantments#4718]
### Describe the bug

Does anyone know why I'm using Advacendenchant the soulbound enchantment so you don't lose the item with 1 item with that enchantment it works and you don't lose it but when you have 2 items with that enchantment in the inventory you still lose them

### How to reproduce

When I place the soulbound charm in an item so that I don't lose it when I die with 1 item it works but when I have 2 or more items in the inventory they don't go with you and I have the probability set to 100 so that yes or yes I don't lose it when I die

### "/ae plinfo" link

 https://paste.md-5.net/uladibafec

### Filled out form correct and using latest version

l confirm

**Comment by ThomasWega** [comment]
Can you send a video showcase please?

**Comment by hotbonnix** [comment]
@ThomasWega 

Uploading lv_0_20241116115741.mp4…

**Comment by hotbonnix** [comment]
@ThomasWega 
https://github.com/user-attachments/assets/96bd6f6e-1e05-4f42-8c8b-861138481a97

**Comment by ThomasWega** [comment]
Can you please try setting up your server in a way that when you die it doesn't teleport you to a different world but you stay on the same one? That might cause the issue. Just for testing now

**Comment by hotbonnix** [comment]
hello I tell you I have just tried that and the same thing happens in the video

@ThomasWega

**Comment by ThomasWega** [comment]
That is weird. I am not able to reproduce it. Works completely fine. Am I doing something wrong?

https://github.com/user-attachments/assets/ea408ace-18b0-48d6-af88-7d7fe1b21a0c
