### ISSUE TITLE
Double enchantments by mistake

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4720]
### Describe the bug

Describe the bug
If you enchant at the enchantment table using the AE stand, sometimes the enchantments in the books are repeated, making them able to be disenchanted twice.
![image](https://github.com/user-attachments/assets/5c75c9ee-ea24-497c-8294-386c010edce6)

This disenchants it and there is still 1 of the 2 left and also the skin of the book is of one without enchantments

![image](https://github.com/user-attachments/assets/e7e987bb-a856-4b5b-81ae-6ab9a9d1ad68)

### How to reproduce

Enchant books on the enchantment table until one enchantment is duplicated

### "/ae plinfo" link

https://paste.md-5.net/sorivunoho

### Filled out form correct and using latest version

I confirm

**Comment by Z3r0xh** [comment]
This bug was supposedly fixed in version 9.12.9, but it still happens.

**Comment by ThomasWega** [comment]
Can't reproduce this. Can you try on a fresh server with only AE with fresh files please? It might be a plugin conflict
