### ISSUE TITLE
Duping Glitch

### ISSUE THREAD

**Issue by BlazzeKiller** [GC-spigot/AdvancedEnchantments#4721]
### Describe the bug

When player equips armor from hot bar and he is wearing diamond not enchanted armor ,
With enchanted armor from his hot bar he equips and then the unechanted armor becomes enchanted !
I have tried with client LabyMod and without on Tlauncher , can someone help me stop this duplicating glitch on my server?
I have video the plugin that does this is Advanced Enchantments!
https://youtu.be/ftmASKhlzE4

### How to reproduce

When player equips armor from hot bar and he is wearing diamond not enchanted armor ,
With enchanted armor from his hot bar he equips and then the unechanted armor becomes enchanted !
I have tried with client LabyMod and without on Tlauncher , can someone help me stop this duplicating glitch on my server?
I have video the plugin that does this is Advanced Enchantments!
https://youtu.be/ftmASKhlzE4

### Screenshots / Videos

https://youtu.be/ftmASKhlzE4

### "/ae plinfo" link

https://youtu.be/ftmASKhlzE4

### Server Log

no log

### Filled out form correct and using latest version

I Confirm

**Comment by ThomasWega** [comment]
Create the ticket again after verifying. Thank you
