### ISSUE TITLE
placeholder not showing up on '"%group-color%

### ISSUE THREAD

**Issue by XavierFunez** [GC-spigot/AdvancedEnchantments#4722]
### Describe the bug

placeholder not showing up on '"%group-color%, when you get any type of book

### How to reproduce

right clicking a book in your hand

### Screenshots / Videos

![df33fg3](https://github.com/user-attachments/assets/6efdbb0b-bf29-4f70-b9d4-187e11f2bfc9)

### "/ae plinfo" link

https://pastebin.com/2nLq8j0Q

### Server Log

https://pastebin.com/2nLq8j0Q

### Filled out form correct and using latest version

I confirm

**Comment by XavierFunez** [comment]
https://paste.md-5.net/ipuvumipog

**Comment by ThomasWega** [comment]
I've tried this and it seems to parse the color correctly
![image](https://github.com/user-attachments/assets/9657e8dd-960f-4b63-a571-af7b46d8a3a7)
![image](https://github.com/user-attachments/assets/b000ea90-e2db-4035-822c-4b7aacc42286)

**Comment by ThomasWega** [comment]
Send your configuration please
