### ISSUE TITLE
Black Scrolls not working 

### ISSUE THREAD

**Issue by huntingzap** [GC-spigot/AdvancedEnchantments#4723]
### Describe the bug

Put the black scroll on a piece of armor and they don't give the book, and just disappear. This was used on a custom armor set made by ExecutableItems

### How to reproduce

On Purpur Version: 1.21.1-2327-4b57bed (MC: 1.21.1)
On AE: 9.12.7
On ExecutableItems: 7.24.10.28
Create a custom set with custom lore and put a custom enchant on it and then remove. Seems to work for some players, but others it doesn't. Not sure why

### Screenshots / Videos

https://github.com/user-attachments/assets/11dd0b70-d5e2-45ba-af41-fab8dff35f6c
https://youtu.be/mEaKWjqND9o

### "/ae plinfo" link

https://paste.md-5.net/egepisevoc

### Server Log

https://mcpaste.io/54517d8017a6883f

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Then the issue needs to be with ExecutableItems not us
