### ISSUE TITLE
BUG - custom model data on gkit menu not working

### ISSUE THREAD

**Issue by serpentoi2** [GC-spigot/AdvancedEnchantments#4724]
### How to reproduce

already tried many ways deleting data or setting data to 0
made paper material with custom model is working well on other plugins that support custom model

 im using the newer version and already tried downgrading or upgrading to latest still no fixed
but the alchemist and tinkerer is working well with custom model

currently im using deluxemenu for gkits menu for temporary ....

### "/ae plinfo" link

s

### Filled out form correct and using latest version

 I confirm to acknowledge the following

**Comment by ThomasWega** [comment]
You haven't provided any showcase nor any of your configs

**Comment by ThomasWega** [comment]
Gkits currently don't support custom model data. You can request this feature on our discord server
