### ISSUE TITLE
This plugin need re-code.

### ISSUE THREAD

**Issue by szeryfABC** [GC-spigot/AdvancedEnchantments#4725]
### Describe the bug

Hello, i use this plugin since version 8 and we are now... every update getting my server more destroyed because of errors.
Lets begin.

**ENCHANTS:**

1. Your default configuration of VeinMiner doasn't works and don't tell me about naturally generated blocks, i use wand and this should works.
2. Your default configuration of TP_DROPS @Block doasn't works.
3. MORE_DROPS doasn't work or condition block type idk.
4. @Trench doasn't work and this is first thing maybe i spell up

**CONFIGURATION**
Well, main problem is for example i need to add enchant for a world that enchant be not work and really... this shouldn't need a restart server to be work, i have peaple who play on this server and really? Server restart?

I'm from Poland and i use in one of enchant "ó" or "ż" and "_" i get errorr when i try to enchant item with it. The same enchant but with name VeinMiner works fine.

### How to reproduce

almost of this errors is YOUR DEFAULT CONFIGURATION

well get the plugin, and try use VeinMiner or something else. I don't really know where i can post a enchants from config well i paste here.

https://pastebin.com/6M54z2vU 

And for end, ALL ENCHANTS WORKS FINE ON VERSION 9.6.16 [but something else is total mess up haha] in any other version for example VeinMiner doasn't works.

### Screenshots / Videos

https://youtu.be/6ZURuHmLKb4

### "/ae plinfo" link

https://paste.md-5.net/umabiwuley

### Server Log

https://mcpaste.io/3211565d8431feb3

### Filled out form correct and using latest version

I confirm

**Comment by GC-spigot** [comment]
That is the limit of Spigot. NBT was removed by Mojang few versions ago, and we had to move to a different system, and Spigot has a replacement for NBT system - which does not support your characters. There is nothing we can do.
