### ISSUE TITLE
Trench and VeinMiner don't work 

### ISSUE THREAD

**Issue by Tchoupi007** [GC-spigot/AdvancedEnchantments#4726]
### Describe the bug

When i use vein miner and trench the advancement don't work 

### How to reproduce

i'm on 1.21.3, i use geysermc for play with bedrock player and i have ae enchantment version : 9.13.0

### Screenshots / Videos

https://prnt.sc/djMoVxxfOgKI

https://prnt.sc/rVpAytBRsJFa

### "/ae plinfo" link

https://paste.md-5.net/wepebepumu

### Server Log

i can't create link in mcpaste, i'm sorry .

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Try updating to latest first please

**Comment by Tchoupi007** [comment]
i have update for 1.13.4 and same problem

**Comment by ThomasWega** [comment]
Seems like issue on 1.21.3. We're investigating right now. Are already able to reproduce it, so now just finding a fix

**Comment by Tchoupi007** [comment]
okay, and u can send me a message when the plugin is update ?

**Comment by ThomasWega** [comment]
Should be fixed next update

**Comment by Tchoupi007** [comment]
okay and u have idea when next update ? ( sorry for my english i'm french )
