### ISSUE TITLE
Devour (pvp premade pack)

### ISSUE THREAD

**Issue by deathwalker7119** [GC-spigot/AdvancedEnchantments#4728]
### Describe the bug

Using Devour 3 on the pvp premade pack, I occasionally get an error saying failed to actviate effect 'EXTRA_DAMAGE:(Number from 1 - 4 here)'

### How to reproduce

I literally just hit someone else and I get the error in chat. 

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/b9b54260-803d-4970-81c2-cbe0d50251a6)
![image](https://github.com/user-attachments/assets/42009390-650f-4fec-a894-4ca8a4bea29a)

### "/ae plinfo" link

https://paste.md-5.net/viginibimo

### Server Log

https://mcpaste.io/0382688ed7867c11

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
That would be because EXTRA_DAMAGE effect doesn't exist anymore. Either you are using an old version of the premade or we've forgot to update that effect. So try to re-download it and if it still happens, let me know and I will update it
