### ISSUE TITLE
Detonate does not work properly with Worldguard

### ISSUE THREAD

**Issue by Besotted0** [GC-spigot/AdvancedEnchantments#4729]
### Describe the bug

I own a Box Server where I want to use Detonate, or Trench, in a large scale. Because people are only allowed to mine in specific areas the enchantment doesn't seem to work. As soon a any player on the server tries to mine a block with the detonate enchantment, a text message from Worldguard is sent to me, the owner. It says "Failed to activate effect 'BREAK_BLOCK_BLOCK ' Additional information: Failedto activate effects as advancedEffect is null or invalid: 'BREAK_BLOCK_BLOCK'. BREAK_BLOCK_BLOCK , trigger:MINING, entity: _Playername_" I'm guessing it's some problem with Worldguard and AE not interlocking, but could someone help me?

### How to reproduce

...

### "/ae plinfo" link

https://paste.md-5.net/foconedesu

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
You are using a really old effect. Either regenerate your files or use `BREAK_BLOCK @Block`
