### ISSUE TITLE
PROJECTILE velocity

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#4732]
### Describe the bug

`PROJECTILE:TYPE` is described as 'Spawn a shooting projectile with **velocity** (requires EntityType Projectile)'. Tried to add parameters `PROJECTILE:ARROW:10`, etc., but it did not work.

### How to reproduce

N/A

### "/ae plinfo" link

https://paste.md-5.net/jocemixuja

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
I could add that though

**Comment by ThomasWega** [comment]
![image](https://github.com/user-attachments/assets/49b0b5c6-0a32-4b46-86bc-98bfc69f194d)
