### ISSUE TITLE
Soulgem placeholder %count% always displays 1 in lore but works correctly in name

### ISSUE THREAD

**Issue by KrazyxWolf** [GC-spigot/AdvancedEnchantments#4734]
### Describe the bug

For some reason when moving the placeholder of the soulgem section (%count%) from name to lore, the amount displayed in lore is always 1, I tried with values of 1, 10 and 1000 but the amount displayed never goes over 1, contrary to the soulgem name the value is displayed correctly.

### How to reproduce

1. Go to config.yml
2. Edit the soulgem section and move the %count% placeholder to lore

### Screenshots / Videos

![Captura de pantalla 2024-11-29 105255](https://github.com/user-attachments/assets/cf0be23d-32eb-45d8-b91f-fd820e4945b8)
![Captura de pantalla 2024-11-29 105326](https://github.com/user-attachments/assets/3c483b88-6e70-4843-851b-cd1c9aa6f3db)
![imagen_2024-11-29_105502959](https://github.com/user-attachments/assets/0fc5e275-813e-4e38-8390-1246533e8e2d)
![2024-11-29_10 54 32](https://github.com/user-attachments/assets/baa5cb7f-3044-401e-99b9-cfd3c67d0f9f)

### "/ae plinfo" link

https://paste.md-5.net/qowufayono

### Server Log

https://mcpaste.io/026eb0e3348aa5c6

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
I've did one small fix now for the same issue, but that was in SlotIncreaser. The gem seems to work completely fine for me?
![image](https://github.com/user-attachments/assets/b0f37f43-fd00-459a-b185-a35848dd9b08)

**Comment by ThomasWega** [comment]
![image](https://github.com/user-attachments/assets/20435795-44a9-4d8c-bb00-b7d38f58cc3f)
![image](https://github.com/user-attachments/assets/328331bd-c9b7-4d85-aaa4-56d0f6f22566)

**Comment by KrazyxWolf** [comment]
@ThomasWega In my case the value of %count% in the lore is stuck in the value of the first soulgem generated, I just made several tests with a value of 20, 10, 40 and 4000, in that order remaining as default value of 20. This was tested in a clean installation of the plugin and apparently is fixed in each restart

![2024-12-01_12 08 59](https://github.com/user-attachments/assets/49f15b0c-0c06-4dbf-a0ce-1565f9a0f244)
![2024-12-01_12 09 01](https://github.com/user-attachments/assets/6035c928-9654-4a17-b20e-620a5236075f)
![2024-12-01_12 09 02](https://github.com/user-attachments/assets/378ba9e4-5eb0-4d85-b5c5-a89bdb339868)
![2024-12-01_12 12 02](https://github.com/user-attachments/assets/9edd1b7b-24b2-44ac-b894-8562e28f9f2e)

**Comment by ThomasWega** [comment]
Aha, I understand better now. I will re-test
