### ISSUE TITLE
After the Improved GriefDefender support, mining enchants stopped working

### ISSUE THREAD

**Issue by KanielOutisx** [GC-spigot/AdvancedEnchantments#4735]
### Describe the bug

After the Improved GriefDefender support, mining enchants stopped working, specially trench and telepathy

### How to reproduce

Enchant pick with trench or telepathy and/or both, and try to use it with griefdefender on some claim. Even when its your own and all flags are aproved.

### Screenshots / Videos

https://pastebin.com/Z6T2Pp8u

### "/ae plinfo" link

https://paste.md-5.net/arepagucaz

### Server Log

https://pastebin.com/Z6T2Pp8u

### Filled out form correct and using latest version

I confirm

**Comment by GC-spigot** [comment]
Hey. We tried at least 6 different iterations of GriefDefender support, and it never worked like it should. I personally reached out to their discord, their support staff and the plugin owner - no one replied. There is no documentation on how to add support for it either. Neither do they follow practices by Bukkit or land protection plugins and do not cancel original block breaks, therefore forcing every plugin to try adding support for them when it is undocumented.

If they decide to reply to me I will gladly re-add support back, but if they do not we'll completely remove it next update.
