### ISSUE TITLE
Fat enchantment bug absorption 4

### ISSUE THREAD

**Issue by mrsandia23** [GC-spigot/AdvancedEnchantments#4736]
### Describe the bug

I just updated my server to 1.20.4 everything works good I use the advancedenchantments on 1.18.2 before everything works but when I updated to 1.20.4 the enchant fat did not work really well because when it starts the absorption and you hit the player the absorption goes from 8 golden hearts to 2 golden hearts like eat a golden enchant apple and it works like a normal golden apple. I also try on the 1.20 and it didn't work also.

### How to reproduce

You just need to have the fat enchant on the armor and after that you just got to hit the player with a bleed enchant or another enchant the fat will not work.

### Screenshots / Videos

https://youtu.be/x9KYrd9Ku_I?si=XJcnDj1vEX72KaAy

### "/ae plinfo" link

https://paste.md-5.net/gecarahoro

### Server Log

https://mcpaste.io/317c4600b718ade6

### Filled out form correct and using latest version

confirm

**Comment by ThomasWega** [comment]
Please send your enchantment as well

**Comment by mrsandia23** [comment]
Any update?

**Comment by ThomasWega** [comment]
It seems to work completely fine for me. Although do note that your POTION effect has exteremely low duration (one fourth of a second = 4 ticks), so I did change that.
