### ISSUE TITLE
Trench will drop an additional noteblock when destroying the itemsadder custom block

### ISSUE THREAD

**Issue by Hiddenmn** [GC-spigot/AdvancedEnchantments#4737]
### Describe the bug

When mining a custom block created with a noteblock using an itemsadder with the trench enchantment, the custom block will drop an additional noteblock.And there is no error in the background

### How to reproduce

Enchant the pickaxe with trench. Mine a custom block created by itemsadder using noteblock. When a custom block is broken, it drops an additional noteblock.

### "/ae plinfo" link

https://paste.md-5.net/fohiseniyo

### Filled out form correct and using latest version

confirm

**Comment by Hiddenmn** [comment]
In addition, there must be a block that can be mined with a pickaxe, such as stone, next to the custom block in order to trigger the trench.

**Comment by Hiddenmn** [comment]
Uploading testvideo.mp4…

**Comment by Hiddenmn** [comment]
https://v.afbcs.cn/dGNi8G

**Comment by Hiddenmn** [comment]
Video:https://github.com/user-attachments/assets/6349019a-24b5-48d4-846b-fb40683bc45d
I don't know why the video can't be watched online, but it can be watched after downloading
The pickaxe is only enchanted with trench
https://paste.md-5.net/muluqecipo

**Comment by ThomasWega** [comment]
Upload somewhere else please. For example imgur. I cannot play it

**Comment by Hiddenmn** [comment]
https://github.com/user-attachments/assets/0e7b3bd8-9d16-438b-a09d-0075d0da7ebb

**Comment by ThomasWega** [comment]
Should hopefully be fixed in the next update.
