### ISSUE TITLE
Telepathy on filled cauldrons don't work

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4738]
### Describe the bug

If you use a telepathy pickaxe on a cauldron filled with water, it just deletes the cauldron

### How to reproduce

- Fill cauldron
- Mine with telpeathy pickaxe

### "/ae plinfo" link

https://paste.md-5.net/oqabagapes

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Seems to work completely fine for me?

https://github.com/user-attachments/assets/4cce1bcd-b470-42df-a0db-8cb3a852571c

**Comment by ThomasWega** [comment]
also update your plugin...
