### ISSUE TITLE
Telepathy issue with McMMO crops

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4739]
### Describe the bug

If you have level 1000 herbalism in McMMO, then sometimes (not all the time and I think it's only for auto replanted crops), and then harvest the crops with a telepathy hoe, they will drop on the floor and not go into your inventory

### How to reproduce

- Plants loads of carrots and bonemeal them up
- Set McMMO herbalism to 1000
- Get a telepathy hoe
- Keep farming the carrots and re-planting, re-bonemealing
- Sometimes they drop and don't go into your inv

### "/ae plinfo" link

https://paste.md-5.net/iqixekumev

### Filled out form correct and using latest version

Confirm

**Comment by ThomasWega** [comment]
update your plugin.
