### ISSUE TITLE
Telepathy issue with turtle eggs

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4740]
### Describe the bug

- If you harvest turtle eggs with a telepathy tool, it will always give you 1 turtle egg regardless of how many eggs were in the patch you mined

### How to reproduce

- Get telepathy tool
- Harvest turtle eggs
- You always get 1

### Screenshots / Videos

https://github.com/user-attachments/assets/cd441d22-9791-45a8-9dbe-7aaa53a5d62a

### "/ae plinfo" link

https://paste.md-5.net/iqixekumev

### Filled out form correct and using latest version

Confirm

**Comment by ThomasWega** [comment]
creating multiple issues with outdated plugin. Don't please
