### ISSUE TITLE
Why this is closed if its not fixed ? #4711

### ISSUE THREAD

**Issue by KanielOutisx** [GC-spigot/AdvancedEnchantments#4741]
### Describe the bug

Check the original issue

### How to reproduce

Check the original issue

### "/ae plinfo" link

https://paste.md-5.net/hecovifujo

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
It's not fixed because spigot produces incorrect event results. We have a fix in place but spigot needs to fix their stuff first
