### ISSUE TITLE
TP_DROPS @Block effect dropping melon slices and melon blocks

### ISSUE THREAD

**Issue by hvtess** [GC-spigot/AdvancedEnchantments#4742]
### Describe the bug

Axes with the default telepathy custom enchant applied will directly move melon blocks into the inventory while still giving players the melon slices.

Silk touch prevents this from happening, but axes without silk touch or with fortune applied will drop both.

### How to reproduce

Add an axe to your inventory without silk touch and apply the default telepathy custom enchant to it.
Destroy a melon block.

### Screenshots / Videos

https://www.youtube.com/watch?v=kZEwJ9DdFbw

### "/ae plinfo" link

https://paste.md-5.net/woxoniyexo

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Seems to work completely fine for me. Also tried with fortune and telepathy and works the exact same way (works okay)
https://github.com/user-attachments/assets/c055f7b1-a09a-4cf9-99f6-b1bc7aeba115
