### ISSUE TITLE
Haste enchantment not working

### ISSUE THREAD

**Issue by Paceski** [GC-spigot/AdvancedEnchantments#4743]
### Describe the bug

Haste enchant is no longer working after updating AE to latest

### How to reproduce

Try using Haste enchant, it will not work.

### Screenshots / Videos

haste:
  display: '%group-color%Haste'
  description: Allows you to swing your tools faster.
  applies-to: 'Tools, Weapons'
  type: HELD
  group: FABLED
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
    - ALL_SWORD
    - ALL_TOOLS
    - ALL_HOE
  levels:
    '1':
      effects:
        - 'POTION:FAST_DIGGING:0'
    '2':
      effects:
        - 'POTION:FAST_DIGGING:1'
    '3':
      effects:
        - 'POTION:FAST_DIGGING:2'
        
        

### "/ae plinfo" link

https://paste.md-5.net/ziceyiwutu

### Filled out form correct and using latest version

I confirm

**Comment by Paceski** [comment]
I also tried using @Self target, didn't work.

**Comment by ThomasWega** [comment]
Works absolutely fine for me 

https://github.com/user-attachments/assets/d6aebf4f-3aad-4b3f-a2bb-c72eaedbf95b
