### ISSUE TITLE
Bug with interaction + enchantments

### ISSUE THREAD

**Issue by Olavvvv** [GC-spigot/AdvancedEnchantments#4744]
### Describe the bug

Works with any piece of armor.

When you have armor that gives you some effect, and you have another breastplate that does nothing, you can swap them and the breastplate that has no effects will still take it as effects.

It's like having an infinite effect.

### How to reproduce

1- Put on the armor with effect
2- In your hand, put on the armor without effect
3- Shift + click on an oven/table/chest (whatever)
4- The chest is exchanged and you have the effect

### Screenshots / Videos

https://github.com/user-attachments/assets/cf73ffb4-4fdb-4b1a-a202-9e1dec74ab72

### "/ae plinfo" link

LATEST

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Thanks for reporting
