### ISSUE TITLE
Issue with Magic Dust Success Rate>=100% NOT WORK

### ISSUE THREAD

**Issue by Highrii** [GC-spigot/AdvancedEnchantments#4745]
### Describe the bug

Hello,

I have encountered an issue with the Magic Dust synthesized through the alchemist menu. Even when the success rate is greater than or equal to 100% (displayed as 100% success rate, as shown in the image), it does not work properly. There are no error messages during the process, but it behaves as if the group does not match, and I am unable to click on the enchantment book.

Thank you.

### How to reproduce

Synthesize Magic Dust for any group.
When the success rate exceeds 100%, the Magic Dust becomes unusable.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/7686b521-0324-40d5-a211-0b37b496fc7f)

### "/ae plinfo" link

https://paste.md-5.net/gagogayiso

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Thanks for reporting
