### ISSUE TITLE
customcommands.yml can not reload

### ISSUE THREAD

**Issue by Highrii** [GC-spigot/AdvancedEnchantments#4746]
### Describe the bug

Hello,

It seems that many configuration items in customcommands.yml are no longer working. I have marked them with red lines in the attached image. The issue arose when I tried to disable the click-to-enchant feature from entering the info screen in the group-enchantment section, but it does not seem to work even after restarting the server.

Thank you.

### How to reproduce

**open customcommands.yml** 
**Line 197**: command: "/enchant %enchantment%" **->** command: "" **or** command: [] **or** command: "/say hello"
**reload server**
**open** /enchantments menu 
**click group enchantment**
**click any one enchantment**
**the command:** "/enchant %enchantment%" **still runing**

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/e1de65b6-706e-4b5f-889d-2b642bb0b273)
![image](https://github.com/user-attachments/assets/8cba2795-2731-4b40-a1a9-18fb8c302bcd)

### "/ae plinfo" link

https://paste.md-5.net/gagogayiso

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
![image](https://github.com/user-attachments/assets/ca80dcd0-1644-45c1-a73b-f3479d72b20c)

these worked completely fine for me.

The only thing I don't see working is the last command value you've sent in your screenshots. We'll be taking a look at that, but the whole customcommands might be remade at some point, so we might just wait until then to fix that
