### ISSUE TITLE
Rain of Arrows enchantment breaks armor stands and item frames in protected areas

### ISSUE THREAD

**Issue by onlyv1** [GC-spigot/AdvancedEnchantments#4747]
### Describe the bug

The Rain of Arrows enchantment can break armor stands and item frames, even if they are placed in protected areas (like WorldGuard or other protection systems). This causes problems as it allows players to unintentionally (or intentionally) bypass protections.

### How to reproduce

Equip a bow with the Rain of Arrows enchantment.
Shoot an arrow near an armor stand or item frame placed inside a protected area.
Observe that the armor stand or item frame is destroyed, despite being in a protected region.

### Screenshots / Videos

lluvia_de_flechas:
  display: '&7Lluvia de Flechas&6'
  description: Rain arrows over opponent.
  applies-to: Bow
  type: SHOOT;SHOOT_MOB
  settings:
    showActionBar: true
  group: ULTIMATE
  applies:
    - BOW
  levels:
    '1':
      chance: 15
      cooldown: 8
      effects:
        - SPAWN_ARROWS @Victim
    '2':
      chance: 18
      cooldown: 8
      effects:
        - SPAWN_ARROWS @Victim
    '3':
      chance: 22
      cooldown: 8
      effects:
        - SPAWN_ARROWS @Victim

### "/ae plinfo" link

https://paste.md-5.net/yizuviqaqu

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thanks for reporting
