### ISSUE TITLE
Offhand Fishing Not tracking

### ISSUE THREAD

**Issue by groovyloopylou** [GC-spigot/AdvancedEnchantments#4748]
### Describe the bug

when fishing in offhand, fish caught tracker isn't updating

having issues with mcpaste.io - let me know if you still need latest.log for this issue and I can try again another time (its not saving)

### How to reproduce

place rod in offhand
fish
observe no increase to tracker
(fishing in main hand all works as expected)

### "/ae plinfo" link

https://paste.md-5.net/osepamoges

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thanks for reporting
