### ISSUE TITLE
Fortune and smelt, duplication 

### ISSUE THREAD

**Issue by CryLegende** [GC-spigot/AdvancedEnchantments#475]
Hello ^^
My players reported a bug in version 5.2.6 :
The vanilla enchantment, Fortune, combined with a custom enchantment that has the effect of "SMELT" will duplicate the cobblestone.

Only tested in 1.12

**Comment by CryLegende** [comment]
Fortune III + a custom enchantment that has the effect of "SMELT" will drop 3 stone when a player break a cobblestone

**Comment by GC-spigot** [comment]
Fixed
