### ISSUE TITLE
SMELTING BUG WITH BENTOBOX LIMITS ADDON

### ISSUE THREAD

**Issue by mcwal18** [GC-spigot/AdvancedEnchantments#4750]
### Describe the bug

Hey! Sorry for bother you but I found the bug.
I use this plugin: BentoBox, AOneBloc.
So there is an enchantment called SMELTING which is causing this bug.

Here the proof: https://i.imgur.com/pxaMvCR.mp4

Do I need to report to them as well?
Thanks!

### How to reproduce

.

### Screenshots / Videos

.

### "/ae plinfo" link

.

### Server Log

.

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Their plugin needs to ignore block break events with blocks with metadata `blockbreakevent-ignore`. Nothing more we can do here. Actions needs to be taken from them
