### ISSUE TITLE
Issues with AE and Aurelium Skills

### ISSUE THREAD

**Issue by stormyhollow** [GC-spigot/AdvancedEnchantments#4752]
### Describe the bug

I was told to post this by GC the founder of the plugin. It appears that some bug between Aurelium Skills and Advanced Enchantments is causing an infinite loop between the plugins. 

### How to reproduce

First time we crashed: https://hastebin.com/share/nazayamega.wasm
Second time we crashed: https://mcpaste.io/f5b30daea219a06a

### Screenshots / Videos

First time we crashed: https://hastebin.com/share/nazayamega.wasm
Second time we crashed: https://mcpaste.io/f5b30daea219a06a

### "/ae plinfo" link

/ae plinfo skipPlugins

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
You are using outdated versions of both plugins. + We only support AuraSkills now
