### ISSUE TITLE
Telepathy Bug with Turtle Eggs

### ISSUE THREAD

**Issue by groovyloopylou** [GC-spigot/AdvancedEnchantments#4753]
### Describe the bug

When breaking turtle eggs you only receive one egg 

### How to reproduce

- either place eggs in a cluster manually or breed turtles in game (more than one egg)
-  break it with a silk tool with telepathy on
- only receive one egg no matter how many are in the cluster

Same issue as reported [here](https://github.com/GC-spigot/AdvancedEnchantments/issues/4740) but confirmed on latest version

### "/ae plinfo" link

https://paste.md-5.net/ratecanato

### Server Log

https://mcpaste.io/5d3a84c3346236ef

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thanks for reporting
