### ISSUE TITLE
Trench not working with NoCheatPlus

### ISSUE THREAD

**Issue by iLemon** [GC-spigot/AdvancedEnchantments#4755]
### Describe the bug

When AdvancedEnchantments is installed alongside NoCheatPlus, players will flag various checks such as WrongBlock and Frequency in NCP, preventing Trench from working.

### How to reproduce

Install AdvancedEnchantments and NoCheatPlus (https://ci.codemc.io/job/Updated-NoCheatPlus/job/Updated-NoCheatPlus/)

On an account with no admin permissions, try mine with the Trench enchantment.

### Screenshots / Videos

![CleanShot 2024-12-13 at 16 02 31@2x](https://github.com/user-attachments/assets/defff780-b6d4-46b9-8ac3-eb1288fb7419)

### "/ae plinfo" link

https://paste.md-5.net/lepunifife.css

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
I feel like this is more of a feature request than a bug. We just need to add support for this anticheat. Please post this as a feature request on our discord server. Thank you
