### ISSUE TITLE
YamlFile.c removed?

### ISSUE THREAD

**Issue by Sniperkaos** [GC-spigot/AdvancedEnchantments#4756]
### Describe the bug

YamlFile.c, where the gkits were handled prior to 9.14 is now gone. Where would they be now?

### How to reproduce

Use a build of 9.13 vs 9.14. A lot of things have changed.

### "/ae plinfo" link

not a server problem

### Filled out form correct and using latest version

I confirm

**Comment by GC-spigot** [comment]
Of course it would change, so as anything else can. It's not an official API method. You can get the gkits file yourself easily without relying on our methods.

If you do however want to request new API methods feel free to do so via discord feature requests.
