### ISSUE TITLE
tps drop

### ISSUE THREAD

**Issue by LautaKooh** [GC-spigot/AdvancedEnchantments#4757]
### Describe the bug

When a player has spikes or spades with speed enchantments to mine, the tps go down, it has been tested and this happens on spades and spades with those enchantments that help to mine faster.

I wanted to know if there is a solution or is this a problem that is being fixed.  

Sorry for my English

### How to reproduce

With picks or shovels with mining incantations

### Screenshots / Videos

![2024-12-14_06 23 30](https://github.com/user-attachments/assets/229c0119-7beb-4470-89fd-5e2bab6430a1)

### "/ae plinfo" link

https://paste.md-5.net/jahujalesa

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Send your spark report
