### ISSUE TITLE
EntityDamageByEntityEvent error

### ISSUE THREAD

**Issue by newbie029** [GC-spigot/AdvancedEnchantments#476]
https://pastebin.com/DVuhSQMQ

running paperspigot 1.12.2
with advancedenchantments 5.6.6

**Comment by GC-spigot** [comment]
Are you able to find the full error? Its the first error in latest.log as this one is cut off

**Comment by newbie029** [comment]
https://pastebin.com/j0WHrTUx
i also found this on the log
ill try to produce this

**Comment by GC-spigot** [comment]
This is not the full error. Just pm me the latest.log on discord so I could
find it.

**Comment by newbie029** [comment]
sent it to you

**Comment by GC-spigot** [comment]
Fixed.
