### ISSUE TITLE
java.lang.IllegalArgumentException: durationMillis must not be negative issued server command: /gkit

### ISSUE THREAD

**Issue by servicomcr** [GC-spigot/AdvancedEnchantments#4761]
### Describe the bug

When executing the /gkit command in the server, an error occurs: java.lang.IllegalArgumentException: durationMillis must not be negative. This seems to be triggered when calculating the remaining cooldown time for a gkit. The error originates from the getLeftDelay method in the AdvancedEnchantments plugin.

Steps to Reproduce:

Install the AdvancedEnchantments plugin (version 9.14.3) on a Minecraft Paper server.
Configure gkits in the plugin.
Execute the /gkit command in-game as a player.
Observe the console/logs for the error message.

Al ejecutar el comando /gkit en el servidor, se genera un error: java.lang.IllegalArgumentException: durationMillis must not be negative. Esto parece ocurrir al calcular el tiempo restante de espera para un gkit. El error se origina en el método getLeftDelay del plugin AdvancedEnchantments.

Pasos para Reproducir:

Instalar el plugin AdvancedEnchantments (versión 9.14.3) en un servidor Minecraft Paper.
Configurar gkits en el plugin.
Ejecutar el comando /gkit dentro del juego como jugador.
Observar la consola o los registros para identificar el mensaje de error.

### How to reproduce

java.lang.IllegalArgumentException: durationMillis must not be negative
at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:337)
at org.apache.commons.lang3.time.DurationFormatUtils.formatDuration(DurationFormatUtils.java:352)
at net.advancedplugins.ae.features.gkits.Gapi.getLeftDelay(Gapi.java:34)

### "/ae plinfo" link

https://paste.md-5.net/uyeyubevux

### Server Log

https://mcpaste.io/eb42b784e12565c4

### Filled out form correct and using latest version

I confirm

**Comment by GC-spigot** [comment]
Should be solved next update
