### ISSUE TITLE
Could not pass event PlayerInteractEvent to AdvancedEnchantments v9.14.4

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4765]
### Describe the bug

Spam on console
https://mclo.gs/WX0uyII

### How to reproduce

Use the last version

### "/ae plinfo" link

https://paste.md-5.net/hutubehebu

### Server Log

https://mclo.gs/KBPnV1E

### Filled out form correct and using latest version

I confirm

**Comment by GC-spigot** [comment]
Fixed next update
