### ISSUE TITLE
Gkits not work latest version of plugin

### ISSUE THREAD

**Issue by Yamiru** [GC-spigot/AdvancedEnchantments#4766]
### Describe the bug

https://mcpaste.io/148f54c070813d0e

### How to reproduce

not works kits

### Screenshots / Videos

https://mcpaste.io/148f54c070813d0e

### "/ae plinfo" link

https://paste.md-5.net/etihejadeg

### Filled out form correct and using latest version

I confirm

**Comment by GC-spigot** [comment]
Seems to be fixed!
