### ISSUE TITLE
"Server performance will be affected"

### ISSUE THREAD

**Issue by PanchitohMC** [GC-spigot/AdvancedEnchantments#4767]
### Describe the bug

has registered a listener for net.advancedplugins.ae.api.EnchantActivateEvent on method "public void nl.marido.deluxecombat.hooks.plugins.itemplugins.AEHook.onEnchantActivateEvent(net.advancedplugins.ae.api.EnchantActivateEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Marido, timderspieler].

### How to reproduce

on start server

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/713943c5-afac-4a6d-a0fc-a0ac8fe26386)

### "/ae plinfo" link

https://paste.md-5.net/orudiwofig

### Filled out form correct and using latest version

9.13.7

**Comment by ThomasWega** [comment]
EffectsActivateEvent should be used instead. The other plugin is using outdated API. Go talk to them
