### ISSUE TITLE
Enchantments stopped working after updating AE

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#4773]
### Describe the bug

After updating AE, enchantments does not work on current items.

### How to reproduce

1. Enchant items using AE 9.11.2
2. Update AE to 9.14.5
3. Items with from the old AE's version stopped working unless you enchant them again

### "/ae plinfo" link

https://paste.md-5.net/kegeworaxi

### Filled out form correct and using latest version

I confirm

**Comment by GC-spigot** [comment]
My guess is that you were using an old version of the plugin and did not get enchants updated from NBT to new data holding system for items. We had a grace period of ~6 months when they were converted automatically.

**Comment by daniel-skopek** [comment]
What version should I update to update NBT to new data?

EDIT: 9.12.2 is last working version. After this version I can update the AE to the latest version.
