### ISSUE TITLE
Issue with Plugin Compatibility on Java 21 (Unsupported class file major version 65)

### ISSUE THREAD

**Issue by VeroonPL** [GC-spigot/AdvancedEnchantments#4775]
### Describe the bug

Hi,

I'm currently encountering an issue with Java 21 while using the latest version of your plugin (9.14.5). The same issue also occurred with version 9.14.4. Unfortunately, downgrading to a version below Java 21 isn’t an option for me, as CMI relies on Java 21 to function correctly.

The recurring errors are creating a significant roadblock, preventing me from properly configuring and launching my servers. Since this plugin is crucial to my setup, I wanted to ask if there are plans to address this compatibility issue or if there’s a workaround I could try in the meantime.

Your assistance would mean a lot, as this is currently the only obstacle delaying the completion of my project.

Thank you for your time and support.

Best regards,
Veroon

### How to reproduce

The problem occurs when using an Event, such as during startup, while using the plugin, or attempting to use an enchantment.

### "/ae plinfo" link

/ae plinfo skipPlugins

### Server Log

https://mcpaste.io/cf82fc18318b87cc

### Filled out form correct and using latest version

I confirm

**Comment by GC-spigot** [comment]
We support Java 21 or newer currently. If you are having issues now try with our next update today and let us know.

**Comment by VeroonPL** [comment]
Currently, Java 21 does not work on server version 1.19.4...

**Comment by f4a1led** [comment]
I have the exact same issue and error. In 1.19.4 even if you update to Java 21 this plugin just won't work. I guess as I see on official sites, Java 21 will only work with 1.20+

**Comment by GC-spigot** [comment]
We're having problems adding support for latest minecraft version functions otherwise if we do not enforce java 21, but I've done some hacky changes now to let it go backwards with compatibility. Will be solved next update.
