### ISSUE TITLE
EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by report101** [GC-spigot/AdvancedEnchantments#486]
spigot ver > >1.8.8
plugin ver >> 5.6.6
running with wildstacker ver2.8.0>> not sure if this info is needed but seems to having a few issues when AE and Wildstacker are together 
------------------------------------------------------------------------------------------
attempts to find out whats the issue is >> i started making a copy of my previous set not with all the enchants [did it in gamemode survival not gamemode creative got books by/ae admin] i only copied half the enchants then spawn a zombie [spawnmob zombie] and let it attack me and when over to the console to take a look and revived this spam. 
------------------------------------------------------------------------------------------
26.05 15:56:51 [Server] ERROR Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v5.6.6
26.05 15:56:51 [Server] INFO org.bukkit.event.EventException
26.05 15:56:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.r(EntityMonster.java:72) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.r(EntityZombie.java:225) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.PathfinderGoalMeleeAttack.e(SourceFile:122) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:91) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:473) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1626) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:338) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.m(EntityMonster.java:20) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.m(EntityZombie.java:163) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1487) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.t_(EntityMonster.java:24) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.t_(EntityZombie.java:221) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
26.05 15:56:51 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
26.05 15:56:51 [Server] INFO Caused by: java.lang.NullPointerException
------------------------------------------------------------------------------------------
>>HERES a SS of the gear << if it helps you narrow down the issue 
+I know your job its not easy so im just trying my best to help make it  ezier* :)+
------------------------------------------------------------------------------------------
![2019-05-27_00 00 25](https://user-images.githubusercontent.com/50795064/58384356-7d834680-8013-11e9-8d87-b6a22325ca9f.png)
![2019-05-27_00 00 26](https://user-images.githubusercontent.com/50795064/58384360-81af6400-8013-11e9-98b3-68f1311404ac.png)
![2019-05-27_00 00 28](https://user-images.githubusercontent.com/50795064/58384361-87a54500-8013-11e9-88f6-6f917225a135.png)
![2019-05-27_00 00 29](https://user-images.githubusercontent.com/50795064/58384362-8aa03580-8013-11e9-8b9e-a2af340a8ed6.png)

**Comment by GC-spigot** [comment]
Not full error, find first error in logs or send latest.log via discord

**Comment by report101** [comment]
29.05 03:47:23 [Server] ERROR Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v5.6.6
29.05 03:47:23 [Server] INFO org.bukkit.event.EventException
29.05 03:47:23 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.r(EntityMonster.java:72) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.r(EntityZombie.java:225) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.PathfinderGoalMeleeAttack.e(SourceFile:122) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:91) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:473) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1626) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:338) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.m(EntityMonster.java:20) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.m(EntityZombie.java:163) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1487) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.t_(EntityMonster.java:24) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.t_(EntityZombie.java:221) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
29.05 03:47:23 [Server] INFO Caused by: java.lang.NullPointerException
29.05 03:47:23 [Server] INFO at n3kas.ae.utils.AECooldown.a(AECooldown.java:17) ~[?:?]
29.05 03:47:23 [Server] INFO at n3kas.ae.enchanthandler.effectsreader.EnchantsReader.b(EnchantsReader.java:155) ~[?:?]
29.05 03:47:23 [Server] INFO at n3kas.ae.enchanthandler.enchanttypes.DEFENSE_MOB.a(DEFENSE_MOB.java:49) ~[?:?]
29.05 03:47:23 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
29.05 03:47:23 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
29.05 03:47:23 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
29.05 03:47:23 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
29.05 03:47:23 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
29.05 03:47:23 [Server] INFO ... 34 more
