### ISSUE TITLE
Enchant information GUI issue. Can be use as a chest

### ISSUE THREAD

**Issue by maxlehot1234** [GC-spigot/AdvancedEnchantments#487]
Hey GC,

I just realized that players can use the enchant information GUI as a chest.

They can put items in it and use it as a portable enderchest for example that was supposed to be for donator.

Any way to prevent interaction with the inventory when the gui was open?

I just test and players can logout and login again and items stay in the enchant GUI.

AdvancedEnchantments-5.6.6

Thanks again GC :)

**Comment by GC-spigot** [comment]
Which inventory are you talking about? Can you take a screenshot?
