### ISSUE TITLE
Enchant description GUI small problem with the enchant description

### ISSUE THREAD

**Issue by maxlehot1234** [GC-spigot/AdvancedEnchantments#488]
Hey GC,

I just realized that the plugtin offer a really nice GUI so players can see the enchantments.

But I also realized this:
![image](https://user-images.githubusercontent.com/5159244/58398143-fe493f00-8021-11e9-9b75-bfa7a5578e54.png)
Occured with the default config.
I try to put the description in the enchantments.ymlin 'descriptionhere' but change nothing.

Any fix for this since it occured with all enchants.

Thanks again

**Comment by GC-spigot** [comment]
Will fix, thank you!
