### ISSUE TITLE
[Feature] Implement a +1 for the ae givebook command

### ISSUE THREAD

**Issue by maxlehot1234** [GC-spigot/AdvancedEnchantments#490]
Hey GC,

I have a feature for AE.

Is it possible for you to implement a command that will apply an enchant directly on the in-hand item of the player?

So for example, I have a custom GUI made with BSP.

I want to "sell" enchants for coins.

So now players pay 50 coins to get an enchant book and than apply it on their item. If they want to buy the item, multiple times, they lost money, since they need to put it in the alchimist and lost 1 book each time :(

With the new command, I will be able to apply the enchant directly on the player in-hand item.
The command will look like this:
./ae givebook <playername> <enchantname> <+><level> <count> <success> <destroy>
./ae givebook maxlehot1234 blessed +1 1 100 0
This command will give +1 blessed enchant on the player in-hand item.

If the player want to buy it again to have II on his item, this command will increase the enchant by one automatically instead of using the alchemist again and again. Not so cool on a prison server with OP enchants and a lot of enchants.

If I doesn't specify the +, an enchantbook will drop instead.

Thanks again GC if you can develop this. It could be really nice

**Comment by GC-spigot** [comment]
Problem with this is that it's extremely specific and I don't add specific features unless it's obviously going to be used widely.
