### ISSUE TITLE
autosmelt & telepathy bug

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#495]
bukkit: paperspigot 1.13.2

**telepathy**
- When you mined ore, you do not have experience to get mined.
- Iron ore and gold ore are not affected by telepathy.

**autosmelt**
- When you mined ore, you do not have experience to get mined.

**Comment by GC-spigot** [comment]
Fixed!

**Comment by geumu** [comment]
> Fixed!
**telepathy**

When you mined ore, you do not have experience to get mined.
https://youtu.be/nzFa4U_-N18

This bug has not been fixed yet.
