### ISSUE TITLE
Effects fail to work with no error

### ISSUE THREAD

**Issue by Movey11** [GC-spigot/AdvancedEnchantments#496]
I am having a weird issue with a few of the enchantment effects. They don't seem to work at all and there are no errors being displayed in the console or player chat.

The enchantment effects not working for me are: TRENCH, CUSTOM_TRENCH, PULL_AWAY, SMELT, EXP, TNT and basically every other effect that modifies entities or blocks. All effects that add potion effects/buffs like Haste and Fire work just fine...

I have version 5.6.6 running on a 1.14.2 Spigot server and have tried the same version and a few others on 1.14, 1.14.1 and 1.14.2 and I get no fixes. If you need more information I am happy to provide it.

**Comment by GC-spigot** [comment]
Fixed!
