### ISSUE TITLE
enchant that are not working

### ISSUE THREAD

**Issue by report101** [GC-spigot/AdvancedEnchantments#497]
spigot ver >> 1.8.9
AE ver >> 5.6.6

>BLESS<
enchant not working tell me in chat i have been blessed but i still have slowness 
>IMPLANTS<
does  not regen my hunger
>TICKSTER<
some reason when this enchant activates it teleports me behid a person and if the person is standing near the wall is teleports me into the wall >>> also when ever i get teleported i cant hit the player for about 5 secs not sure if its a teleport thing with essentials safe teleport [will not take damage for 5secs after teleport] 
>>NO error in console

**Comment by GC-spigot** [comment]
Implants has a chance of doing that, as well as a cooldown after.
Trickster hit cooldown is caused by essentials pvp cooldown after teleporting, fixed teleporting into walls.
