### ISSUE TITLE
Attack enchantments aren't working in 1.14.2

### ISSUE THREAD

**Issue by MrWardy** [GC-spigot/AdvancedEnchantments#498]
Version: 5.6.6
Spigot Version: git-Paper-51 1.14.2-R0.1-SNAPSHOT

Attack enchantments aren't working. They do nothing.

Also, the AdvancedBot on discord doesn't work, I have AdvancedEnchantments purchased, but it won't let me verify.

**Comment by lukemango** [comment]
None do that arent potion effects for me

**Comment by diamondwelsh** [comment]
We have multiple enchantments that are not working in 1.14.1 & 1.14.2, but were working in 1.14.0 (according to my players).
The following is what we've found not working so far:
Auto Smelt
Reforged
Lightning
Angelic
Ragdoll
Oxygenate
Inquisitive
Master inquisitive
Telepathy
Experience
Demon Lifesteal
Double Strike
Epicness
Obliterate
Hellfire
Explosive

I would agree with the statement that potion effects seem to work fine while the others are having issues.

**Comment by MrWardy** [comment]
I don't know about working on 1.14, I do know these enchantments were working in 1.13.2 though.

**Comment by GC-spigot** [comment]
Fixed!
