### ISSUE TITLE
Money alternative not working

### ISSUE THREAD

**Issue by Whist34** [GC-spigot/AdvancedEnchantments#499]
Server Paper-1.14.2-b59.jar
AdvancedEnchantments-5.6.6
The New Economy: TNE-0.1.1.8c
Vault-1.7.2

I have changed the config to not use exp. Set it to false, 
Then I changed all references from exp to money in the configs (as suggested on the Discord). 
The result - enchants are free.

The currency system I have in place using TNE which links through Vault is working fine, but AE does not use the currency. 

Either there is a bug with the code, or I need some more information on how to switch from experience purchases to a currency based purchase system - because updating the config to use money did not work.

Pastbin of my edited confg.yml  https://pastebin.com/3wzJQs5i

Thank you

**Comment by GC-spigot** [comment]
Everything works perfectly with your Config and normal Vault, issue seems to be coming from The New Economy. It's currently not supported.
