### ISSUE TITLE
Secret Dust Issue

### ISSUE THREAD

**Issue by matthew-wiggins** [GC-spigot/AdvancedEnchantments#506]
So I was testing the tinkerer with my new enchants and group, and I found that my common group was the only group whose secret dust did not open. I tried changing the name and changing the dust items but I still couldn't figure it out. Weirdly there are no errors or messages that pop up when this happens. I gave a link to my config files, hoping that is enough to solve my issue; thanks!

FILES: https://www.mediafire.com/file/mtx7p2c2xc22sp7/issue_post.rar/file

**Comment by GC-spigot** [comment]
Fixed.
