### ISSUE TITLE
enchant bugs

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#507]
Bukkit: Paperspigot 1.13.2
Plugin Version: Lastest Version

**telepathy + autosmelt**
If both enchantments are in one item, Ore comes into inventory. It is right for the ingot to come in.

https://www.youtube.com/watch?v=dEaxqFNJIZ8&feature=youtu.be

**detonate + reforged**
Reforged does not work. Durability reduction is the same.

https://youtu.be/E97OSdjBzh0

**Comment by GC-spigot** [comment]
Added support between those effects!
