### ISSUE TITLE
Enchants not working

### ISSUE THREAD

**Issue by PengBread** [GC-spigot/AdvancedEnchantments#509]
Spigot Version - PaperSpigot 1.13.2
Plugin Version - 5.8.8

Custom enchants aren't working for things I created customly using configs etc for example a special op equipment with Custom enchants added in lore doesn't give the enchants. Only CE's that enchant by players using those books only work.

**Comment by GC-spigot** [comment]
This is not an issue - enchantments work by NBT tags (in-item information rather than lore), lore is just text and to provide better customizability lore is just for display and not to store enchantments. If you're trying to add enchants to essentials kits - I have an addon on Spigot for that.

**Comment by PengBread** [comment]
Not for essentials kit, for some other item creator plugin like Mythicmobs etc.
