### ISSUE TITLE
[Feature] Implement enchant slot add directly in the enchantments.yml

### ISSUE THREAD

**Issue by maxlehot1234** [GC-spigot/AdvancedEnchantments#512]
Hey I have a problem with enchant slots and "multi-level enchants"

For example, if I have 3 enchants:
booster#1, booster#2, booster#3
booster#2 require booster#1
booster#3 require booster#2

But I doesn't want to remove previous enchant, since all of them of specific booster, but cause of this, it will take 3 enchants slots.

Any way to add a config that add enchant slots if players take enchants?
So when players have booster#3, player will get +2 enchant slots.

Of course without players to use the enchant slots item.

It could be really useful for me and maybe lot more servers.

Thanks a lot

**Comment by GC-spigot** [comment]
No, slot increasers (items) are for this, cannot be done with enchants.

**Comment by maxlehot1234** [comment]
Really sad, so I can't have multiple enchants "tiers" cause of this :(

I will allow players ot have unlimited enchants on their items??

Could you at least do something to limit the enchant per tools?
pickaxes are limited to 15 enchants
diamond_swords are limited to 8 enchants
diamond_helmet are limited to 8 enchants
diamond_chestplates are limited to 9 enchants
diamond_boots are limited to 7 enchants

This allow a little bit more customisation of the enchant slots limit.


Thanks again @GC-spigot
