### ISSUE TITLE
[Feature] Full numbers instead of roman numeral

### ISSUE THREAD

**Issue by maxlehot1234** [GC-spigot/AdvancedEnchantments#516]
Hey GC,

Is it possible to set a number instead of I, II, III, IV, VI, VII, etc for enchants level?
Maybe a config section true/false?

It could be much better.

Some of my enchants are level 50 and display L, doesn't looks so good :P
It will be much better to have, 1,2,3,4,5,6,7,8,9,10,...,50 

Thanks again

**Comment by GC-spigot** [comment]
Added!
