### ISSUE TITLE
Armor Effects removed if armor is shift-clicked out of armor slot while inventory is still full

### ISSUE THREAD

**Issue by FuneralSuits** [GC-spigot/AdvancedEnchantments#517]
When your inventory is full and you try to shift click armor out of your armor slot and it has custom enchantments, the enchantments on said selected item immediately stops working.

The armor is still left on your body, but you no longer have the effect associated with the custom enchantments on the armor. 

This is by far not a critical bug, thanks for reading!

**Comment by GC-spigot** [comment]
Fixed!
