### ISSUE TITLE
Telepathy, Silktouch, and MergedSpawner

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#518]
I'm using [MergedSpawner](https://www.spigotmc.org/resources/mergedspawner.31982/), which merges multiple spawners into one and showing the quantity above the spawner with armour stands. When a player mines a merged spawners with a Telepathy Silktouch pickaxe, it drops the spawner, but removes the entire stack. I'm not sure if this is an issue on AdvancedEnchantments' side, or MergedSpawner's.

**Comment by GC-spigot** [comment]
MergedSpawner is not supported.
