### ISSUE TITLE
SHIFT effect..

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedEnchantments#520]
When I add a cooldown to the enchants that never stop.. 
      effects:
        - 'POTION:SPEED:4:140'
        - 'POTION:CONFUSION:2:140'
that's the effects on the enchantment and if I active that without the cooldown the effect working just when I hold it and not when keep running the 140 ticks

**Comment by GC-spigot** [comment]
SHIFT acts like EFFECT_STATIC / HELD, it's a permanent enchant type

**Comment by Jok3rTV** [comment]
So can you please add a timer for that or something? so when I shift that will active the effect with the timer on it
