### ISSUE TITLE
telekinesis durability problem

### ISSUE THREAD

**Issue by dodieboy** [GC-spigot/AdvancedEnchantments#524]
Telekinesis has an invert durability formula(i think). The higher you unbreaking, the faster the durability drop

**Comment by GC-spigot** [comment]
What is Telekinesis?

**Comment by dodieboy** [comment]
TP_DROPS

**Comment by dodieboy** [comment]
telekinesis:
  display: '%group-color%Telekinesis'
  description: "Have mined ores instantly teleport to your inventory"
  applies-to: 'Tools'
  type: 'MINING'
  group: 'BASIC'
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
  levels:
    1:
      effects:
        - 'TP_DROPS'
