### ISSUE TITLE
TP_DROPS durability problem

### ISSUE THREAD

**Issue by dodieboy** [GC-spigot/AdvancedEnchantments#530]
Sorry for the late reply and post this issue, cause never see the reply and you close it
TP_DROPS has an invert durability formula(i think). The higher you unbreaking, the faster the durability drop

**Comment by dodieboy** [comment]
This is the enchant config if you need 
https://pastebin.com/uGbXV8cH

**Comment by GC-spigot** [comment]
Fixed
