### ISSUE TITLE
[Feature] Add new enchants in a separate file in a ZIP file with the plugin

### ISSUE THREAD

**Issue by maxlehot1234** [GC-spigot/AdvancedEnchantments#532]
Hey why not adding a new file with new enchants each time you push an update?

I remove some enchants from the enchantments file, reorder them, etc.

I can't regenerate the file each time you add an enchant :(

Maybe put the plugin.jar in a ZIP file and add a new.yml file with new enchants in it :wink: so we can simply add them in our enchantments.yml will be much better I think :)

Thanks again GC

**Comment by GC-spigot** [comment]
I will be posting enchantments within the update in spoiler tags so you will be able to open them and see the enchant code.
