### ISSUE TITLE
Problem with tools' durability, especially "unbreakable" tools 

### ISSUE THREAD

**Issue by Yukyxy** [GC-spigot/AdvancedEnchantments#535]
Hello, I have just bought your plugin AdvancedEnchantments and i have a problem with several enchants (like detonate) that affect the durability of my tools with the tag "unbreakable". 

What is problematic for us is compared to the unbreakable tools that we have created with fixed durability (eg DIAMOND_AXE {Unbreakable: 1} which have 1559/1561 of durability must keep 1559/1561 are custom texture from custom texturepack) that are not meant to take durability damage. Your enchants add damage to the tool and affects unbreakable tools hence our problem ^^" (we have managed several authors like mcmmo to add the tag unbreakable so that ability no longer affects the tools with this tag "unbreakable"). 
To overcome this problem no negligible for custom texture pack users relate to the durability of items (which are becoming more numerous), could you add please the tag "unbreakable" (similar to a ntb tag) as did mcmmo to make sure that doesn't affect the durability of unbreakable tools where I have defined a custom texture pack on it, thanking you in advance for your response and for your help.

https://www.youtube.com/watch?v=IqFPo14RynA

**Comment by GC-spigot** [comment]
Fixed
