### ISSUE TITLE
DEFENSE_MOB no work

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#541]
i test no work "DEFENSE_MOB"
![image](https://user-images.githubusercontent.com/5382252/60315390-fec65400-9998-11e9-8fb7-37c2efd7cbcb.png)

DEFENSE have work
but DEFENSE_MOB no work
Or where do I use the error?
The console has no errors

I think this is a plugin bug

Paper 1.13.2
AE 5.7.5

**Comment by p82183645** [comment]
hallo GC?
AE 5.7.6 still

**Comment by GC-spigot** [comment]
Fixed!
