### ISSUE TITLE
/ae spams me with /AdvancedEnchantments

### ISSUE THREAD

**Issue by ExidusMC** [GC-spigot/AdvancedEnchantments#550]
plugin isnt loading properly, everytime i type a command, any command through AE is just says /AdvancedEnchantments, ive downlaoded many versions to see if it fixes the issue but nothing has i really need help!

**Comment by ExidusMC** [comment]
https://gyazo.com/dc09ec99444c7572ff5d0991c4ece9cc

**Comment by GC-spigot** [comment]
@ExidusMC post the error on start up here. Plugin requires Vault to start up.
