### ISSUE TITLE
"Cannot measure distance between world1 and world2"

### ISSUE THREAD

**Issue by FuneralSuits** [GC-spigot/AdvancedEnchantments#553]
So I recently began getting this error spammed in my console:

> [04:12:35] [Server thread/INFO]: [AdvancedEnchantments ERROR] Could not pass IllegalArgumentException: Cannot measure distance between world and MainWorld
> [04:12:35] [Server thread/INFO]: [AdvancedEnchantments]    Class: n3kas.ae.utils.AreaUtils.a(AreaUtils.java:27)
> [04:12:35] [Server thread/INFO]: [AdvancedEnchantments]    Extra info: cannot read radius[R=10;RT:ALL]; mc[114]; ae[5.8.0]
> [04:12:35] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 

I have no idea what enchantment could be causing it. If you have any ideas which enchantment might be the cause please let me know so I can temp-disable it until the issue is solved.

Thanks,
- Funeral

**Comment by GC-spigot** [comment]
Fixed
