### ISSUE TITLE
DIsabled_worlds for selected enchants 

### ISSUE THREAD

**Issue by youseemerunning1** [GC-spigot/AdvancedEnchantments#557]
Would be nice if we could do something like this for selected enchants

strongarm:
  display: '%group-color%Strong Arm'
  description: Permanent strength
  applies-to: 'SWORD'
 disabled_worlds:
 - world
 - arena
  type: EFFECT_STATIC
  group: MYTHIC
  applies:
  - ALL_SWORD
  levels:
    '1':
      effects:
      - POTION:STRENGTH:0

**Comment by SuperIsSuper** [comment]
+1

**Comment by GC-spigot** [comment]
Added
