### ISSUE TITLE
Feature suggestion for not-applyable-with option

### ISSUE THREAD

**Issue by digital-r** [GC-spigot/AdvancedEnchantments#562]
Currently not-applyable-with enchant option support only list of enchants.
If this possible, please, add option to define not-applyable-with for enchants group. 
So, say, we can made all fire enchants incompatible with all water enchants without define dozen incompatibles in each incompatible enchant, and rewrite whole list, if new enchant are added.

**Comment by GC-spigot** [comment]
Currently not possible due to how it works, possibly in future!
