### ISSUE TITLE
Magic Dust Config "true/false" Issue

### ISSUE THREAD

**Issue by xxJinxedxx** [GC-spigot/AdvancedEnchantments#568]
AE: 5.8.4
Server: PaperSpigot 1.8.8-R0.1

```
magic-dust:
  # When applying, does dust lower destroy rates
  lower-destroy: false
```
This has no effect. In both cases when the dust is applied, success is boosted and destroy is lowered.

**Comment by GC-spigot** [comment]
That has been removed, use 'settings.lower-destroy-with-magic-dust' now
