### ISSUE TITLE
Usage: Transmog -> RenameTag -> Transmog Issue

### ISSUE THREAD

**Issue by xxJinxedxx** [GC-spigot/AdvancedEnchantments#570]
AE: 5.8.4
Server: PaperSpigot 1.8.8-R0.1

After using a transmog scroll on an item, then using a rename tag on it and afterwards applying few more enchantments to the item, you can not apply anymore transmog scrolls to it. Also there is that error:
 - http://pasted.co/f578824d

And further, when the first transmog scroll is applied then the rename tag, the number of random enchantments placeholder vanishes. Of course i guess that that should be normal, but i'm just adding it to the info.

**Comment by xxJinxedxx** [comment]
EDIT: The error happens just after trying to apply a second transmog on the same item more than once.

**Comment by GC-spigot** [comment]
Fixed
