### ISSUE TITLE
Soul Tracker Applying Issue

### ISSUE THREAD

**Issue by xxJinxedxx** [GC-spigot/AdvancedEnchantments#571]
AE: 5.8.4
Server: PaperSpigot 1.8.8-R0.1

The soul tracker can be applied to:
 - All armor types and peaces except "chain"
 - Book
 - Custom Enchanted Book (AE custom enchanted)

**Comment by xxJinxedxx** [comment]
UPDATE:
When applying the soul tracker it uses the message from "applying -> cosmetics" rather than its own.

**Comment by GC-spigot** [comment]
1st part - can't fix as it allows application to all items listed in config.yml
2nd part (message) - fixed
