### ISSUE TITLE
Issue with ADD_DURABILITY and REPEATING

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#590]
Hey GC,

We experienced the following issues with those two features:

ADD_DURABILITY: It doesn't seem to have any effect. E.g. when using the Master Blacksmith enchantment you get the message that is triggered along with the effect, but there doesn't seem to be any effect on the durability of the player's armor (neither the attacked nor the attacking player). This is the case for other enchantments with ADD_DURABILITY as well.

REPEATING: It works as expected for armor but doesn't seem to have an effect when added to held items (both left and right hand), like pickaxes or swords. 

Plugin versions:
AdvancedEnchantments: 5.8.6
Paper: 1.13.2-639

Thanks a lot!

sh1mrr4

**Comment by GC-spigot** [comment]
Thanks for reporting! Fixed Durability issues, but Repeating for now is only armor-based 😃
