### ISSUE TITLE
[Feature request] Enchants excluded from taking up a slot

### ISSUE THREAD

**Issue by HzKanon** [GC-spigot/AdvancedEnchantments#591]
Hi GC, can we get an option or a list to add enchants that when applied, won't take up a slot on the item. My rationale for this is that I have cosmetic enchants and functional enchants, I want only the functional ones to count as taking up slots. Thanks! :)

**Comment by GC-spigot** [comment]
This cannot be done due to how enchantments are currently calculated, sorry!
