### ISSUE TITLE
[Issue] Alchem combining books to over max level

### ISSUE THREAD

**Issue by HzKanon** [GC-spigot/AdvancedEnchantments#595]
Title says it all. My config is at https://pastebin.com/5DcMy7PK.
Thanks! :)

**Comment by xxJinxedxx** [comment]
Provide more info.
Server version, plugin version and how did it happen. Can you reproduce it? And if you can, how?

**Comment by HzKanon** [comment]
PaperSpigot 1.13.2 ver-455
AE 5.8.7; Reproducible
I tested it again on an account with basic permissions and could still replicate the bug.
For example I have pummel configured to max level 3 in enchantments.yml here. But combining 2 Pummel 3 books in the alchemist gives me a Pummel 4
https://imgur.com/a/NuauMD3

**Comment by GC-spigot** [comment]
Thank you! Fixed :)
