### ISSUE TITLE
[Issue] Trench dupe with silktouch

### ISSUE THREAD

**Issue by HzKanon** [GC-spigot/AdvancedEnchantments#597]
PaperSpigot 1.13.2 ver-455
AE 5.8.7
CMI 8.2.2.0
I'm using CMI to handle Spawner dropping, as you can see from the attached video, a pickaxe with both silktouch and detonate V which uses trench doesn't break the spawner. 
I've tried all sorts of settings including removing SPAWNER from trench-blacklist, setting trench-autoadd-items to true and so on. I've also tried adding the condition  - '%block type% = SPAWNER : %stop%' but that doesn't work either
Sorry for the many issues I've been opening but thanks for all the quick responses!

Video: https://imgur.com/a/j5C6MD8

**Comment by GC-spigot** [comment]
Fixed
