### ISSUE TITLE
Glow Error On Disable

### ISSUE THREAD

**Issue by xxJinxedxx** [GC-spigot/AdvancedEnchantments#598]
AE: 5.8.8
Server: PaperSpigot 1.8.8-R0.1
Just couple of errors on reload and giverandombook.
Glow on books is disabled, still applies a glow on the book that i hold when when give myself another one.

 - https://hasteb.in/lugupubu.bash
 - https://hasteb.in/zekulipi.bash _(this error pops up regardless the glow thing, always when /ae reload is used)_

**Comment by GC-spigot** [comment]
Fixed
