### ISSUE TITLE
Alchemist Issues - Magic Dust Upgrade & Gui "inv-size"

### ISSUE THREAD

**Issue by xxJinxedxx** [GC-spigot/AdvancedEnchantments#599]
AE: 5.8.8
Server: PaperSpigot 1.8.8-R0.1

The issue of ticket [#581](https://github.com/GC-spigot/AdvancedEnchantments/issues/581) still persist.
Its a dust upgrading issue _via alchemist_, not a dust applying one e.g. on a book.

 - 2'nd Issue
`inv-size` does not shrink the GUI, only removes the dummy items up to the set in the tinkerer.yml slots/size.

**Comment by GC-spigot** [comment]
1st - fixed.
2nd issue - http://prntscr.com/olluyu
