### ISSUE TITLE
New /enchanter payment

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedEnchantments#601]
Add a option to pay with MobCoins or Tokens, maybe even add a API for that so we could create our own /enchanter payment or even GUI, Anyways.. add a option to pay with mobcoins (SuperMobCoins) and tokens (TokenManager)

**Comment by Nedjii** [comment]
There is a command to give a random book from a category so you can make your own gui using placeholders to check tokens.
