### ISSUE TITLE
[Feature] BlackScroll Command +

### ISSUE THREAD

**Issue by xxJinxedxx** [GC-spigot/AdvancedEnchantments#603]
Improvement to the command with adding **%random%** chance placeholder _(plugin rolls from 1 to 100)_, or/and **%37-84%** placeholder _(specific predefined lower range and upper range)_ to the command instead of required to input a predefined success rate.

`/ae giveitem %player% blackscroll 1 %random%`
---
or

`/ae giveitem %player% blackscroll 1 %37-84%`
---

If applicable and taken in to consideration only `%random%` will also be just perfect.

Thanks.

**Comment by GC-spigot** [comment]
Use /ae giveitem %player% blackscroll 1 0
