### ISSUE TITLE
BOOST doesnt work with %victim%

### ISSUE THREAD

**Issue by mlefeb01** [GC-spigot/AdvancedEnchantments#604]
- When using the %victim% placeholder with the BOOST effect, it doesn't work and there is an error
- Error
`> [03:02:01 WARN]: Excessive velocity set detected: tried to set velocity of entity #6696 to (0.0,20.0,0.0).
> [03:02:01 WARN]: java.lang.Exception: Stack trace
> [03:02:01 WARN]: at java.lang.Thread.dumpStack(Thread.java:1336)
> [03:02:01 WARN]: at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setVelocity(CraftEntity.java:213)
> [03:02:01 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:598)
> [03:02:01 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:104)
> [03:02:01 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:240)
> [03:02:01 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:120)
> [03:02:01 WARN]: at n3kas.ae.enchanthandler.enchanttypes.ATTACK.playerHitPlayer(ATTACK.java:54)
> [03:02:01 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [03:02:01 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [03:02:01 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [03:02:01 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [03:02:01 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307)
> [03:02:01 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
> [03:02:01 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [03:02:01 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508)
> [03:02:01 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493)
> [03:02:01 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:93)
> [03:02:01 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:594)
> [03:02:01 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:507)
> [03:02:01 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:626)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1160)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:871)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:794)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:812)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:507)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1013)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1089)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1371)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [03:02:01 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [03:02:01 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:427)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724)
> [03:02:01 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627)
> [03:02:01 WARN]: at java.lang.Thread.run(Thread.java:748)
> [03:02:01 INFO]: [Server] working
> [03:03:29 INFO]: mlefeb01 issued server command: /ae reload
> [03:03:31 WARN]: Excessive velocity set detected: tried to set velocity of entity #6877 to (0.0,5.0,0.0).
> [03:03:31 WARN]: java.lang.Exception: Stack trace
> [03:03:31 WARN]: at java.lang.Thread.dumpStack(Thread.java:1336)
> [03:03:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setVelocity(CraftEntity.java:213)
> [03:03:31 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:598)
> [03:03:31 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:104)
> [03:03:31 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:240)
> [03:03:31 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:120)
> [03:03:31 WARN]: at n3kas.ae.enchanthandler.enchanttypes.ATTACK.playerHitPlayer(ATTACK.java:54)
> [03:03:31 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [03:03:31 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [03:03:31 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [03:03:31 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [03:03:31 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307)
> [03:03:31 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
> [03:03:31 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [03:03:31 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508)
> [03:03:31 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493)
> [03:03:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:93)
> [03:03:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:594)
> [03:03:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:507)
> [03:03:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:626)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1160)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:871)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:794)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:812)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:507)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1013)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1089)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1371)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [03:03:31 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [03:03:31 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:427)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627)
> [03:03:31 WARN]: at java.lang.Thread.run(Thread.java:748)
> [03:03:31 WARN]: Excessive velocity set detected: tried to set velocity of entity #6696 to (0.0,5.0,0.0).
> [03:03:31 WARN]: java.lang.Exception: Stack trace
> [03:03:31 WARN]: at java.lang.Thread.dumpStack(Thread.java:1336)
> [03:03:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setVelocity(CraftEntity.java:213)
> [03:03:31 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:598)
> [03:03:31 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:104)
> [03:03:31 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:240)
> [03:03:31 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:120)
> [03:03:31 WARN]: at n3kas.ae.enchanthandler.enchanttypes.ATTACK.playerHitPlayer(ATTACK.java:54)
> [03:03:31 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [03:03:31 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [03:03:31 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [03:03:31 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [03:03:31 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307)
> [03:03:31 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
> [03:03:31 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [03:03:31 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508)
> [03:03:31 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493)
> [03:03:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:93)
> [03:03:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:594)
> [03:03:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:507)
> [03:03:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:626)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1160)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:871)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:794)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:812)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:507)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1013)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1089)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1371)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [03:03:31 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [03:03:31 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:427)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724)
> [03:03:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627)
> [03:03:31 WARN]: at java.lang.Thread.run(Thread.java:748)
> [03:03:31 INFO]: [Server] working`
- Enchant
`  levels:
    1:
      chance: 100
      #cooldown: 5
      effects:
      - 'BOOST:5 %attacker%'
      - 'BOOST:5 %victim%'
      - 'CONSOLE_COMMAND:say working'`

**Comment by GC-spigot** [comment]
Fixed
