### ISSUE TITLE
Compatibility with AAC [FEATURE REQUEST]

### ISSUE THREAD

**Issue by WalkingPixel1** [GC-spigot/AdvancedEnchantments#612]
Never know how todo these so apologies if done wrong.

I currently have the AAC plugin and wanted to know if you could add compatibility for the AAC plugin with your enchants plugin. apparently you can get an API or some sort to work with it?

Please do request more info is needed but i dont think there needs to be.

Thank you
Pixel

**Comment by GC-spigot** [comment]
What issues are you having?

**Comment by WalkingPixel1** [comment]
When a player has jump boost on boots and they're in the water they get stuck and cannot move. I did ask the owner of aac if I could do something their side but they said it's best asking you, but yeah they get stuff in water when trying to jump out of it.

Thank you
Pix
