### ISSUE TITLE
EXP error

### ISSUE THREAD

**Issue by LilDevs** [GC-spigot/AdvancedEnchantments#613]
02.08 19:44:45 [Server] INFO [AdvancedEnchantments ERROR] Could not pass IllegalStateException: Asynchronous entity add!
02.08 19:44:45 [Server] INFO [AdvancedEnchantments]    Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:846)
02.08 19:44:45 [Server] INFO [AdvancedEnchantments]    Extra info: effect[EXP:139]; enchant[experience]; mc[188]; ae[5.8.9]
02.08 19:44:45 [Server] INFO [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.

**Comment by GC-spigot** [comment]
Issue with wildstacker, disable async death event
