### ISSUE TITLE
custom enchantment stops working when the player dies

### ISSUE THREAD

**Issue by Devillion** [GC-spigot/AdvancedEnchantments#614]
this enchantment stops working when a player dies and then goes back to get their dropped items.

https://pastebin.com/TKstYrGJ

**Comment by GC-spigot** [comment]
Minecraft version? AE version?

**Comment by Devillion** [comment]
Sorry, this is happening on 1.13.2 and AE 5.8.6

**Comment by GC-spigot** [comment]
Try updating to latest.
