### ISSUE TITLE
MCMMO not working with custom trench

### ISSUE THREAD

**Issue by ArathiaMC** [GC-spigot/AdvancedEnchantments#618]
Custom trench enchantment does not work with McMMO. 
All McMMO experience is not properly calculated. It only gives for the 1 block broken and not every block broken with the trench enchantment.

Running AE version 5.9.0 and McMMO-overhaul version 2.1.100

**Comment by GC-spigot** [comment]
This is at the moment not possible to do due to how mcmmo works with blocks, sorry!
