### ISSUE TITLE
Telepathy Enchant does not ignore default shulker box.

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#620]
Latest AE.jar
Paperspigot 1.13.2

As the title says, Telepathy Enchant does not ignore default (purple) shulker box. It only ignores colored shulker boxes. 

I have reported this previously but GC closed my ticket and said it was fix but it isn't. Please take a look and test it out. Isn't fixed for me.

**Comment by GC-spigot** [comment]
Fixed, sorry about this.
