### ISSUE TITLE
EXP?? 

### ISSUE THREAD

**Issue by Kapakulia** [GC-spigot/AdvancedEnchantments#624]
Hey, I have an issue with EXP, I am using WildStacker and every time I kill Blaze it gives me 10 EXP both with and without enchants

mobster:
  display: '%group-color%Mobster'
  description: 'Increases EXP drops from mobs'
  applies-to: 'Weapon'
  type: 'KILL_MOB'
  group: 'LEGENDARY'
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    1:
      chance: 20
      effects:
        - 'EXP:<random number>3-6</random number>'
    2:
      chance: 40
      effects:
        - 'EXP:<random number>3-6</random number>'
    3:
      chance: 60
      effects:
        - 'EXP:<random number>4-8</random number>'
    4:
      chance: 80
      effects:
        - 'EXP:<random number>22-40</random number>'

**Comment by GC-spigot** [comment]
Update your wildstacker
