### ISSUE TITLE
Telepathy Enchantment does not ignore default Shulker Box.

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#626]
Latest AE.jar 6.0.1
Paperspigot 1.13.2

As the title says, Telepathy Enchant does not ignore default (purple) shulker box. It only ignores colored shulker boxes.

I have reported this issue twice and was told it was fixed but it wasn't. Please please take a look. Thank you.

**Comment by GC-spigot** [comment]
https://i.imgur.com/nB09F5q.gif 6.0.1
