### ISSUE TITLE
Failed Initialising plugin

### ISSUE THREAD

**Issue by Lastphysics** [GC-spigot/AdvancedEnchantments#627]
Hey, I bought the plugin not a long time ago, and for some Reason it disabled itself. (CODE 122)

It could be related to 1 fact. Cause i have a test server (local) to make the files work properly. And i also have a server on which one i will be playing on with some of my friends.

The prbl could be related that the plugin was on 2 servers at the time I suppose. Anyway, i deleted it from the playing server to continue on the test server. But it still doesnt work :/

Plz help.

**Comment by GC-spigot** [comment]
Fixed in next update
