### ISSUE TITLE
InventoryCloseEvent

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#631]
Paper 1.14.4
AE v6.0.5

Two InventoryCloseEvent errors. These get super spammy. We are experiencing crashes and extreme lag spikes during this time. Cannot confirm if this is the cause of it.

It looks like its conflicting with another plugin as well. I will report it to that developer also.

https://pastebin.com/ZRKjXwjy

**Comment by GC-spigot** [comment]
Fixed
