### ISSUE TITLE
'F key' with Haste enchant bug

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#633]
**Bukkit**: 1.13.2 Paperspigot
**Plugin**: Advanced Enchantment 6.0.5
**Description**: If you change the pickaxe with haste enchant effect to your left hand by pressing F, the effect remains.
**Video**: https://www.youtube.com/watch?v=vhnMb3YSGrU&feature=youtu.be

**Comment by GC-spigot** [comment]
Fixed
