### ISSUE TITLE
Silk touch does not work when silk touch and telepathy are attached.

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#634]
**Bukkit**: 1.13.2 Paperspigot
**Plugin**: AdvancedEnchantments 6.0.5
**Description**: Silk touch does not work when silk touch and telepathy are attached.
**Video**: https://www.youtube.com/watch?v=drM43IGR3N4&feature=youtu.be

**Comment by BboyZeroOne** [comment]
This applies to Shovel too.

**Comment by GC-spigot** [comment]
Added
