### ISSUE TITLE
Silk touch does not work when silk touch and Detonate and  Atomicdetonate are attached.

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#635]
**Bukkit**: 1.13.2 Paperspigot
**Plugin**: AdvancedEnchantments 6.0.5
**Description**: Silk touch does not work when silk touch and Detonate and  Atomicdetonate are attached.
**Video**: https://www.youtube.com/watch?v=GCYTz96M6lA&feature=youtu.be

**Comment by GC-spigot** [comment]
Added
