### ISSUE TITLE
Item disappears when using tinker

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#636]
**Bukkit**: 1.13.2 Paperspigot
**Plugin**: AdvancedEnchantments 6.0.5
**Description**: 
This bug is generated only under very special conditions.

1. Make a transaction with Tinkerer once. (You must trade with Tinkerer once for this bug to be reproduced.)

2. Open the Tinker GUI.

3. Put the item into the Tinker GUI.

4. Turn off the Tinker GUI without proceeding with the transaction.

5. The item disappears.

**Video**: https://youtu.be/QttuG4CyCM0

**Comment by GC-spigot** [comment]
Fixed
