### ISSUE TITLE
ADD_DURABILITY,ADD_DURABILITY_ITEM causes error

### ISSUE THREAD

**Issue by 1onedd1** [GC-spigot/AdvancedEnchantments#639]
Help...
I enchanted armor on sqdreforged 6 lvl and:

![image](https://user-images.githubusercontent.com/48379233/63745205-40488200-c8aa-11e9-8fea-4e3516aeb3fb.png)

![image](https://user-images.githubusercontent.com/48379233/63744783-0fb41880-c8a9-11e9-83a3-19cb22e72f5a.png)
![image](https://user-images.githubusercontent.com/48379233/63744847-3a05d600-c8a9-11e9-8faa-6a5961732c76.png)
![image](https://user-images.githubusercontent.com/48379233/63744874-530e8700-c8a9-11e9-9151-d47687a01023.png)
![image](https://user-images.githubusercontent.com/48379233/63745005-bac4d200-c8a9-11e9-8f40-adb889b97127.png)

**Comment by GC-spigot** [comment]
Use 'ADD_DURABILITY:1 %attacker%', right now it's by default going for victim, which in most of the case is either a mob or, by that error, a wither skeleton skull
