### ISSUE TITLE
AdvancedEnchantments caught an error with an action involving inventories.

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#640]
Bukkit: 1.13.2 Paperspigot
Plugin: AdvancedEnchantments 6.0.6
Description:

When right clicking to preview enchantments info in /enchanter, it does not work and gives this error. It was not fixed in the last update.

https://pastebin.com/8As6B4HZ

**Comment by GC-spigot** [comment]
regen your customcommands.yml
