### ISSUE TITLE
AE Enchants disabled... for no apparent reason

### ISSUE THREAD

**Issue by Lastphysics** [GC-spigot/AdvancedEnchantments#641]
Hey, im still having the issue where my plugin is disabled.
It shows me this : 
https://www.dropbox.com/s/tw94o04vd6q57i9/AE%20galere1.PNG?dl=0

Can you help ?

**Comment by GC-spigot** [comment]
What is your spigot username @Lastphysics ?

**Comment by Lastphysics** [comment]
Lovichi is my spigot username ^^

**Comment by Lastphysics** [comment]
For what do you need it for ???

**Comment by GC-spigot** [comment]
Just restart and it will be fixed!
