### ISSUE TITLE
fishing

### ISSUE THREAD

**Issue by osnapitzjamie** [GC-spigot/AdvancedEnchantments#642]
Please add a "FISHING" type that triggers when something is caught with the fishing rod.

For example when I catch a fish I want a random chance to give money or an enchantment book.

**Comment by GC-spigot** [comment]
Added

**Comment by osnapitzjamie** [comment]
@GC-spigot 

> book:
  display: '%group-color%Book Finder'
  description: Chance to find enchantment books when fishing
  applies-to: Fishing Rod
  type: FISHING
  group: DIVINE
  applies:
  - FISHING_ROD
  levels:
    '1':
      chance: 100
      cooldown: 4
      effects:
      - CONSOLE_COMMAND:say test

doesnt work, any idea why?
