### ISSUE TITLE
Directivity problem (NEED FIX)

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#646]
if use "DEFENSE_MOB"  "LIGHTNING %victim%"  will Trigger on the monster (good work)
if use  "DEFENSE"   "LIGHTNING %victim%" will Trigger on the self  (WTF THIS?)  (trigger self)

![image](https://user-images.githubusercontent.com/5382252/64063251-5d6fae80-cc24-11e9-8a09-b8641e163274.png)

**Comment by GC-spigot** [comment]
It was an issue with DEFENSE_MOB rather than DEFENSE, use logic when deciding who is victim and who is the attacker.

In DEFENSE, %victim% is the one who got attacked and %attacker% is the one who hit. I made it the same for DEFENSE_MOB for next update.
