### ISSUE TITLE
Exception Thrown during the launching of 6.0.7

### ISSUE THREAD

**Issue by Odogo** [GC-spigot/AdvancedEnchantments#649]
When launching the server with the AdvancedEnchants plugin, the plugin throws an exception of the following:
"java.lang.IllegalArgumentException: No enum constant n3kas.ae.api.AEnchantmentType.EFFECT STATIC"
 
Full Stacktrace: https://pastebin.com/XZj26m8h

**Comment by Odogo** [comment]
Deleting all of the configuration files (from what I can tell) works.

**Comment by GC-spigot** [comment]
It was an issue with your configuration, somewhere you had 'EFFECT STATIC' instead of 'EFFECT_STATIC'
