### ISSUE TITLE
TP_DROPS bugs

### ISSUE THREAD

**Issue by CryLegende** [GC-spigot/AdvancedEnchantments#650]
Hello ^^
TP_DROPS alone or with another enchantment makes the pick unbreakable
TP_DROPS with Unbreaking removes the pickaxe after 1-2 uses
https://youtu.be/hrzwOrjP57M

Server: PaperSpigot 1.12.2 (Latest build)
Plugin: Version 6.0.7

**Comment by GC-spigot** [comment]
Fixed
