### ISSUE TITLE
Can't right click to preview enchantments in gui

### ISSUE THREAD

**Issue by vox4455** [GC-spigot/AdvancedEnchantments#652]
paper 1.14.4 build 186 with updated plugin jar.

[Tue, 3. Sep 2019 16:38:38 UTC INFO] AdvancedEnchantments caught an error with an action involving inventories
[Tue, 3. Sep 2019 16:38:38 UTC WARN] java.lang.NullPointerException
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at n3kas.ae.features.usercommands.Enchantments.open(Enchantments.java:79)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at n3kas.ae.features.enchanter.InventoryEvent.onClick(InventoryEvent.java:90)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at n3kas.ae.globallisteners.InventoryClicks.onInvClix(InventoryClicks.java:26)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor978.execute(Unknown Source)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923)
[Tue, 3. Sep 2019 16:38:38 UTC WARN]     at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by geumu** [comment]
reinstall customcommands.yml

**Comment by vox4455** [comment]
just remove the file and reboot the server and let it replace it?
