### ISSUE TITLE
[BUG] DEFENSE_MOB no work , please check

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#656]
![image](https://user-images.githubusercontent.com/5382252/64335438-63db9d00-d00d-11e9-885b-a4a61a2fff87.png)

![image](https://user-images.githubusercontent.com/5382252/64335458-73f37c80-d00d-11e9-8175-792fa1a38f0b.png)

![image](https://user-images.githubusercontent.com/5382252/64335477-7e157b00-d00d-11e9-8378-ba9468a62f72.png)

![image](https://user-images.githubusercontent.com/5382252/64335609-c6cd3400-d00d-11e9-9ea1-73cc1db43659.png)

ok , you say Is caused by the pvp plugin
I am testing the server test, not like you said
Can you check and fix it?

have try 
"ADD_HEALTH:25 %attacker%"   (no work)
"ADD_HEALTH:25 %victim%"  (no work)

**Please, Fix it , no just say "no bug"**
**I have provided all the information. Now, what do you need to fix?**

paper 1.14.4
ae 6.0.8

**Comment by GC-spigot** [comment]
Fixed
