### ISSUE TITLE
[BUG]  enchantments preview two bug

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#657]
1. 
![image](https://user-images.githubusercontent.com/5382252/64381113-083cfe00-d065-11e9-9a23-21e6bc1ecec2.png)

![image](https://user-images.githubusercontent.com/5382252/64381134-11c66600-d065-11e9-98c2-dec5d10f4abf.png)

some will show %desc% , some no show

2. 
![image](https://user-images.githubusercontent.com/5382252/64381166-2571cc80-d065-11e9-9de8-ed42514a0b9d.png)

I changed to /pw 
but , if bind other plugins , use this commands , will show "no this commands"
have full command?

**Comment by GC-spigot** [comment]
1st - check next update.
2nd - use 'chat' rather than 'commands' since it's configurable, it works from chat. If it's deluxe menus, use chat and say '/pw'
