### ISSUE TITLE
[Feature Request] Blacklist certain worlds for items

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#660]
Hello,

I currently have a duels setup that keeps inventory on death. If a player has piece of gear with a holy white scroll on it though, the item is duplicated. Is there any way of adding a world blacklist for holy white scrolls, or fixing this problem some other way?

Thanks in advance.

**Comment by GC-spigot** [comment]
Made holy whitescrolls not work in worlds with 'keepInventory' enabled, in addition to this I added holy whitescrolls world blacklist setting in config.yml
