### ISSUE TITLE
Hellfire (Bow enchantment) doesnt work

### ISSUE THREAD

**Issue by Lastphysics** [GC-spigot/AdvancedEnchantments#668]
Hey, i would really love to enable the transformation of arrows into fireballs, would be awesome.

The Hellfire enchantment should do it, but ut doesnt work :/

Could you fix it ?

Thanks for reading this

**Comment by GC-spigot** [comment]
It works by replacing the arrow last second to a fireball, that's due to how BOW enchant type works.

**Comment by Lastphysics** [comment]
Well, couldnt make it work :/
