### ISSUE TITLE
DISABLE_ACTIVATION doesn’t work.

### ISSUE THREAD

**Issue by FreeHunna** [GC-spigot/AdvancedEnchantments#672]
After testing with enchants such as silence I can’t seem to get the DISABLE_ACTIVATION effect to actually work? Could you take a look at it, the enchantment procs but the effect literally does nothing, seems to be an issue with the plugin itself.

**Comment by GC-spigot** [comment]
From my testing it works flawlessly, are you sure you are using it correctly? It's `DISABLE_ACTIVATION:<enchant name, in lower-case, same as in enchantments.yml>:<time, in seconds>`

**Comment by FreeHunna** [comment]
Yes, works perfectly. Reason why I believe in my testing it wasn’t working was because I was trying to disable activation of an enchantment with static effects.
