### ISSUE TITLE
!BUG! With plugin , Log Error 

### ISSUE THREAD

**Issue by SimplySounds** [GC-spigot/AdvancedEnchantments#674]
The plugin works wonderful and it is just what I needed for along time , the only problem is when I or anyone right clicks the GUI /enchanter there is a Spammed ERROR log inside the Config , 

(https://user-images.githubusercontent.com/55560263/65280168-ccdb0e80-dafd-11e9-831f-87efa523a096.png)

I don't know how these usually go but my Discord is Also : SimplySounds#1479

**Comment by GC-spigot** [comment]
Add me on Discord GC#0830 and PM your configuration.
