### ISSUE TITLE
[Feature Request] More Sound Features/Options and AoE.

### ISSUE THREAD

**Issue by Luraph** [GC-spigot/AdvancedEnchantments#675]
A cool feature would be having the ability to play sounds with:

- Different Pitch
- Different Speed
- Have the option to play the sound globally, and not just towards the attacker and the victim, etc.

AoE:
With natures wrath currently, to my knowledge, it only affects the person that attacks the player with that enchant. I suggest an option that affects ALL players in a radius like the CosmicPvP enchant.

This will allow people who wish to replicate CosmicPvP's enchant system to fully make the experience better.

**Comment by GC-spigot** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/wiki/Æ-Run-effects-in-Radius-(AOE) for AOE, will add this to nature's wrath in next update along with sound updates.
