### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by gravityplayz** [GC-spigot/AdvancedEnchantments#676]
version: latest
Minecraft version: tacoSpigot 1.8.8
config: im using the base config with no adjustments made to it.
description: the error occurred when I tried to apply a heroic tier book to an item without the enchant it needed.
Error:
`26.09 00:26:33 [Server] Startup [04:26:33 ERROR]: Could not pass event InventoryClickEvent to AdvancedEnchantments v6.1.7
26.09 00:26:33 [Server] INFO org.bukkit.event.EventException
26.09 00:26:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1662) [?:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
26.09 00:26:33 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
26.09 00:26:33 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
26.09 00:26:33 [Server] INFO Caused by: java.lang.NullPointerException
26.09 00:26:33 [Server] INFO at n3kas.ae.utils.nbt.NBTapi.removeEnchantment(NBTapi.java:209) ~[?:?]
26.09 00:26:33 [Server] INFO at n3kas.ae.globallisteners.listeners.ClickListener.onClicks(ClickListener.java:675) ~[?:?]
26.09 00:26:33 [Server] INFO at sun.reflect.GeneratedMethodAccessor188.invoke(Unknown Source) ~[?:?]
26.09 00:26:33 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
26.09 00:26:33 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
26.09 00:26:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 00:26:33 [Server] INFO ... 16 more`

**Comment by GC-spigot** [comment]
Fixed
