### ISSUE TITLE
EliteArmor & AdvancedEnchantments

### ISSUE THREAD

**Issue by SkyBeats21** [GC-spigot/AdvancedEnchantments#677]
So basically Heroic enchants MUST have their legendary counterpart on gear to apply, but this does not apply with EliteArmor sets? It can be made into an 20lore which is a issue for not just me but BlizzardMC who i'm positive also uses AdvancedEnchantments.

**Comment by GC-spigot** [comment]
Must be an issue with elite armor, contact that developer.
