### ISSUE TITLE
Default members can't open the GKit gui menu.

### ISSUE THREAD

**Issue by Comqlex** [GC-spigot/AdvancedEnchantments#682]
Whilst being opped, doing /gkit will open the GUI showing all of the gkits, however when not opped doing /gkit wont open the gui. 
I get this error code in console:
30.09 17:27:19 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to AdvancedEnchantments v6.1.0

**Comment by GC-spigot** [comment]
This seems to be an issue with one of the items for permissions, this happens usually for people who use an invalid material for items which display that player has no perms for gkits, look through those and you'll find the issue.
