### ISSUE TITLE
[Issue] Error Code with Knight enchantment

### ISSUE THREAD

**Issue by JavaCalorious** [GC-spigot/AdvancedEnchantments#685]
I am the owner of a server(1.8.9) that uses AdvancedEnchantments and for some reason, everytime I remove a piece of armor that has "Knight" enchantment, I get this.
![image](https://user-images.githubusercontent.com/40225169/66287636-1bafe300-e909-11e9-9c47-29d2bca4401d.png)
I look in Console and receive this:

`[INFO] [AdvancedEnchantments] Class: n3kas.ae.effectsreader.RunnableEffect.c(RunnableEffect.java:254)

[INFO] [AdvancedEnchantments] Extra info: effect[POTION:STRENGTH, 1]; enchant[Knight]; mc[188]; ae[5.3.5]

[INFO] [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.`

This makes me unable to use the Strength effect with the Knight enchantment.

**Comment by GC-spigot** [comment]
Use `INCREASE_DAMAGE` instead of `STRENGTH`
