### ISSUE TITLE
"NEGATE_DAMAGE" makes the player invincible

### ISSUE THREAD

**Issue by CryLegende** [GC-spigot/AdvancedEnchantments#688]
Hello ^^

The effect "NEGATE_DAMAGE" makes the player invincible.
He can be attacked but does not lose his life.

Version: 6.2.4
Server: PaperSpigot 1.12.2

Example of usage:
https://pastebin.com/raw/jn5xrs3m

**Comment by GC-spigot** [comment]
That negates 80 damage. Unless your attack did more than 80 damage, it won't work.
NEGATE_DAMAGE doesn't require a player so you can remove one of those lines as well.

**Comment by CryLegende** [comment]
"NEGATE_DAMAGE:40" I thought the "40" was a percentage like 40% of the damage received, thank you for answering ^^

**Comment by CryLegende** [comment]
I checked, the player is really invincible when it's another player who hits him
when he falls or goes into the lava, he takes the damage normally
