### ISSUE TITLE
"KEEP_ON_DEATH" not working

### ISSUE THREAD

**Issue by CryLegende** [GC-spigot/AdvancedEnchantments#689]
Hello :)
Effect "KEEP_ON_DEATH" does not work, item is dropped as a normal item.

Version: 6.2.4
Server: PaperSpigot 1.12.2

Example of usage:
https://pastebin.com/raw/C5WsWMpP

Thank for your help ^^

**Comment by GC-spigot** [comment]
Enchant names must be in lower-case, use `save:`, and KEEP_ON_DEATH only works for held item & armor.
