### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by LePtitFiloou** [GC-spigot/AdvancedEnchantments#694]
Yo !

I bought the plugin and put it in the folder plugins, idk if there is a special config to do. I did nothing more and got these errors.

Sorry if i did something wrong i rly don't know the plugin seems to be insane, i'm really hype to use it.

https://pastebin.com/nk43ZhSx

Filloou.

**Comment by GC-spigot** [comment]
@LePtitFiloou Make sure you are running latest 6.3.5 rather than 6.3.4 as it had an issue. If you are still having this, do these steps:
1st - stop your server.
2nd - delete 'AdvancedEnchantments' folder in plugins 
3rd - start your server back up.
