### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ZeddyOG** [GC-spigot/AdvancedEnchantments#695]
Some items from the newer version of the game do not work inside of GKits as a display or give item.
Items not working:
* Elytra
* Trident

When a user is wearing an enchantment that gives a static effect (speed, resistance, etc) and the user goes near a beacon giving of the exact same effect (regardless of level of the CE or Beacon) the effect will begin using the one given off by the beacon and once the timer runs out remove the effect entirely.  Meaning that if a user has Speed 2 applied and goes near a beacon with Speed 1/2 the permanent effect from the CE will then be replaced with the beacon effect and when the user leaves the range of the beacon it will then count down and completely remove the effect, resulting in the user having to reapply the item with the effect.

**Comment by GC-spigot** [comment]
Cannot be resolved at the moment due to how spigot handles materials for newer versions, any material from 1.13+ is something plugin doesn't have access to

**Comment by GC-spigot** [comment]
Will be fixed soon
