### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TheBigDude5** [GC-spigot/AdvancedEnchantments#699]
Dc#0808
So I think you should be able to use EFFECT_STATIC with other stuff like particle, half_damage, negate_damage, increase_damage. Since you could have flight but also half of the damage taken just a suggestion it would be pretty cool to do this.

EDIT: 10/20/2019
ADD a type called - WEARING : check if the enchant is worn can add alot of cool features aswell. like if you are whering something called Mythical Flight : allows you to fly when in faction land or ally land even if they disabled it in their perms.

**Comment by GC-spigot** [comment]
You can use REPEATING for some things, but EFFECT_STATIC is like this at the moment to preserve performance.
