### ISSUE TITLE
Detonate, Implants Bug + oversized GUI.

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#700]
Bukkit: 1.13.2 Paperspigot
Plugin: AdvancedEnchantments 6.2.9
Description:

Issue 1:
[Mon, 21. Oct 2019 12:54:21 UTC INFO] [AdvancedEnchantments ERROR] Could not pass IllegalArgumentException: Cannot drop air
[Mon, 21. Oct 2019 12:54:21 UTC INFO]    Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1104)
[Mon, 21. Oct 2019 12:54:21 UTC INFO]    Extra info: effect[TRENCH:3]; enchant[detonate]; mc]; ae[6.2.9]
[Mon, 21. Oct 2019 12:54:21 UTC INFO] If you cannot indentify cause of this, contact developer providing this report.

Issue 2: Implants Enchantment is buggy. It would not work for some players.

Issue 3: Titan Trap, Reflective Block and Arrow Break GUI description is out of the screen.

https://imgur.com/a/7tAqTnv
https://imgur.com/a/b0JcL0s
https://imgur.com/a/lWfCNpS

**Comment by GC-spigot** [comment]
Fixed the descs, but since enchantments.yml doesn't force-update you'd need to regenerate it.
Implants, due to changes, cooldown and 10 seconds activation time, it activates too rarely, i changed chances, again, you'll need to regen the same file ^

Fixed error with TRENCH
