### ISSUE TITLE
\n Doesn't work for /enchants

### ISSUE THREAD

**Issue by Andell4301** [GC-spigot/AdvancedEnchantments#701]
I did post this in discord which you may have seen, but I figured I would put it in github since I remember putting things here in the past. I noticed that new lines aren't represented in the /enchants menu, so thought I'd report it. They work in /ae admin and with enchantment books, but since normal players won't see /ae admin and /enchants is a great way to preview enchantments before getting the books, I was hoping you could make \n work here as well.

Either way, thank you for the excellent plugin 😄 
![newline](https://user-images.githubusercontent.com/56235026/67251948-efcf4a00-f43e-11e9-891f-646aff7147cb.png)

**Comment by GC-spigot** [comment]
Fixed
