### ISSUE TITLE
Issue with ATTACK_MOB and DEFENSE_MOB + enchantment conditions

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#702]
Hey GC,

Certain enchantment conditions like %attacker combo% or %victim health% generate a lot of warnings when triggered by ATTACK_MOB or DEFENSE_MOB. They work perfectly fine when triggered via ATTACK and DEFENSE in PvP though.

Exemples:
Enrage:
![grafik](https://user-images.githubusercontent.com/47902483/67519121-78035880-f6a6-11e9-8de0-97f24ac6225e.png)
![grafik](https://user-images.githubusercontent.com/47902483/67519217-b0a33200-f6a6-11e9-9529-9764a6eadeef.png)

Rage:
![grafik](https://user-images.githubusercontent.com/47902483/67519237-bdc02100-f6a6-11e9-83d2-231bedd1c287.png)
![grafik](https://user-images.githubusercontent.com/47902483/67519295-d597a500-f6a6-11e9-975d-f58121a6d9af.png)

Curse:
![grafik](https://user-images.githubusercontent.com/47902483/67519325-e6481b00-f6a6-11e9-949a-63c0ada7c3af.png)
![grafik](https://user-images.githubusercontent.com/47902483/67519407-1a234080-f6a7-11e9-8a74-7c21584deef0.png)

AE version: 6.3.0
Paper: 1.13.2

Thanks a lot!

**Comment by GC-spigot** [comment]
Currently conditions do not support %victim/%attacker starts with mobs, this is being reworked.
