### ISSUE TITLE
Telepathy and Detonate Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#703]
Bukkit: 1.13.2 Paperspigot
Plugin: AdvancedEnchantments 6.3.1
Description:

Issue 1:
Telepathy does not ignore default(purple) shulker boxes. I have reported this three times yet no fix.

Issue 2:
Detonate does not work on this pickaxe for some reason. Detonate enchant itself works except with this set of enchantments https://imgur.com/a/o0ULsff

**Comment by GC-spigot** [comment]
Make sure this is your TRENCH blacklist setting in config.yml:
```

  # Trench effect materials blacklist
  trench-blacklist:
    - 'AIR'
    - 'BEDROCK'
    - 'LAVA'
    - 'WATER'
    - 'STATIONARY_LAVA'
    - 'STATIONARY_WATER'
    - 'SPAWNER'
    - 'PORTAL'
    - 'SHULKER'
```

**Comment by Getblock** [comment]
It can still destroy default purple shulker boxes. i guess, it's been reported a lot but ignored a lot
