### ISSUE TITLE
Error and Questions

### ISSUE THREAD

**Issue by CaoTrongThang** [GC-spigot/AdvancedEnchantments#704]
PaperSpigot 1.12.2
AdvancedEnchants 6.3.1

(First of all, sorry about my bad English)

what is requirement enchant for "bidirectionalteleportation"?, i think you forgot to add require enchant for that echant

why i don't have the requirement enchant on my weapon but i still can use the enchant book?
    required-enchants:
    - 'assassin'
    removed-enchants:
    - 'assassin'

I can't set any Alchemist messages to my language

i already enabling this, but why i still can't using enchant table to open advanacedenchantments
  open-enchanter-by-right-clicking-enchantment-table: true

i already enabling this, but i still can't using /ae market, its keep telling "feature is disable"
  ae-market-enabled: true

**Comment by GC-spigot** [comment]
Added configuration for alchemist messages
To enable open-enchanter-by-right-clicking-enchantment-table, you need to restart
ae market is on-going a major revamp, I update about it in plugin updates, it's almost finished!

Is it formatted under settings for required enchants?
```  settings:
    required-enchants:
    - 'assassin'
    removed-enchants:
    - 'assassin'```

**Comment by GC-spigot** [comment]
Also sorry for late response, been away on a vacation.

**Comment by CaoTrongThang** [comment]
I think you forgot to add "Alchemist doesn't accept this item" message and when i can't afford to alchemist but i still click to combine glass, the items will disappear

yes, i didn't change anything about require enchants
https://ibb.co/gZ01XDF

**Comment by GC-spigot** [comment]
it's "alchemist.messages.doesnt-accept"

**Comment by GC-spigot** [comment]
No enchantment is required for `bidirectionalteleportation`
These do work for me: ```required-enchants:
- 'assassin'
removed-enchants:
- 'assassin'```
Make sure you actually have 'assassin' in your enchantments.yml file properly formatted
