### ISSUE TITLE
GKitz Problems

### ISSUE THREAD

**Issue by MatthewNoble** [GC-spigot/AdvancedEnchantments#705]
![image](https://user-images.githubusercontent.com/16277080/68115559-92cc9d00-fef0-11e9-80cc-c4ed0fbdaa9f.png)
[console.log](https://github.com/GC-spigot/AdvancedEnchantments/files/3803615/console.log)

**Comment by GC-spigot** [comment]
Seems like one of the gkit from gkits.yml was missing a permission, added a warning & check for that.
