### ISSUE TITLE
Broken Enchants/Features

### ISSUE THREAD

**Issue by NinetailsPlays** [GC-spigot/AdvancedEnchantments#707]
Some enchants the ones i have figured out are Rage and Enrage make it so no other enchants procs and randomization doesnt work
https://pastebin.com/gWmW4A7i

**Comment by GC-spigot** [comment]
How do you add the enchant? By applying with books or /ae enchant command?
Also what other enchant(s) do you add on item which stop working after rage is added?
or are you talking about the elite lootbox plugin?
According to my tests (applied rage & ravenous) enchants still work, so I need to find out more info to look into this.
@NinetailsPlays
