### ISSUE TITLE
SHOOT_BOW Type

### ISSUE THREAD

**Issue by Hellcode48** [GC-spigot/AdvancedEnchantments#708]
I would love a SHOOT_BOW type for enchantments that use EntityShootBowEvent because I am currently working on some custom effects that need that event.

**Comment by GC-spigot** [comment]
Sadly I'm not going to add this as there's no effects that would support it. Creating something like this yourself would be pretty simple. Just use EntityShootBowEvent, get the bow item, use AEAPI to get list of enchants on it and go from there.
