### ISSUE TITLE
StackOverflow causing server death

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#709]
Hello there,

Recently my server has been running into a weird problem where what I assume is AdvancedEnchantments suddenly crashes the server.

I have no idea why this happens but when it does, the console will spit out (literally) tens of thousands of lines of errors. It seems that this also has something to do with McMMO, as it is mentioned in the errors.

The error is here: https://pastebin.com/2SXvcE5Q

That is only a small portion of the massive output of the console.

Thank you for your help.

**Comment by GC-spigot** [comment]
Should be fixed in next update.
