### ISSUE TITLE
Entire plugin breaks when editing enchantments

### ISSUE THREAD

**Issue by Syrkulous** [GC-spigot/AdvancedEnchantments#711]
When editing the enchantment abilities and groups, the plugin will error.

I've tried both restarting after editing and starting up the server after editing and neither had a different outcome. I am unable to change groups of enchants such as Take Off from Legendary to Heroic. I am also unable to change abilities... removing enchant levels such as Haste 2 and 3, or decreasing detonate chance.

After editing and starting up the server, /ae still works, but enchants no longer exist even though they still show in the config. I am using AE version 6.3.4 on MC1.14.4

![2019-11-15_08 04 50](https://user-images.githubusercontent.com/55862273/68957664-5d8d3e00-077f-11ea-806f-ba473931ecdd.png)

**Comment by GC-spigot** [comment]
Have you contacted me via discord?
The reason you're having this is because of misconfiguration, I can help but here but it will be faster via discord GC#0830
