### ISSUE TITLE
Armor disappearing in inventory

### ISSUE THREAD

**Issue by Mineez** [GC-spigot/AdvancedEnchantments#714]
Hi! 
I experienced a little problem with your plugin this afternoon.
When a player equip and unequip a chestplate in his inventory very quickly, this one randomly disappear and he has to log out and then log in to get it back in an inventory slot.
When the chestplate is invisible in the inventory, if he equips an other chestplate (vanilla or not), he keeps the effect of the other chestplate that he previously removed ( screen below ).

Waiting for your answer,
Best regards, Mineez & his mates
 
![image](https://user-images.githubusercontent.com/44147434/69191908-bfed9200-0b23-11ea-9693-9bb395469836.png)

**Comment by EvanSchleret** [comment]
Hi !

Same bug for me :/

**Comment by GC-spigot** [comment]
There already was a cooldown, hence why had to relog to see items (visual glitch), I increased the cooldown.
