### ISSUE TITLE
Alchemist doesn't combine books 

### ISSUE THREAD

**Issue by iMCB4** [GC-spigot/AdvancedEnchantments#721]
Alchemist won't combine books unless they have the exact same success percentage, even on the newest update:

alchemist:
  settings:
    combine-books: true
    combine-dust: true
  books:
    add-up-chances: true
    pre-set-chances:
      enabled: false
      success: 50
      destroy: 50
  dusts:
    add-up: true
  price:
    exp: true
    let-plugin-count: true
    pre-set-pricing:
      price: 250

**Comment by GC-spigot** [comment]
Try latest update - works for me fine. If you're still having issues contact me on discord.
