### ISSUE TITLE
Telepathy Enchant Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#724]
Telepathy Enchantment does not work when used for harvesting crops.

When a player has telepathy enchanted on his tools and tries to harvest crops with it like potatoes, wheat etc, the items would just disappear instead of appearing in our inventory.

Latest version of Advanced Enchantments 6.5.1

PaperSpigot 1.13.2 and 1.14.4

**Comment by GC-spigot** [comment]
Looking into this

**Comment by GC-spigot** [comment]
Try updating, I'm not experiencing this in any of the versions from 1.8.8 up to 1.14.4 servers.advancedmarket.co/ae/tpworks.gif
