### ISSUE TITLE
Duplication of items.

### ISSUE THREAD

**Issue by MatthewNoble** [GC-spigot/AdvancedEnchantments#727]
[console.log](https://github.com/GC-spigot/AdvancedEnchantments/files/3929464/console.log)

[Minecraft 1.14.4 2019-12-05 22-42-25.zip](https://github.com/GC-spigot/AdvancedEnchantments/files/3929470/Minecraft.1.14.4.2019-12-05.22-42-25.zip)

**Comment by GC-spigot** [comment]
Don't use creative, as simple as that. It's buggy and doesn't properly work with spigot.
