### ISSUE TITLE
Glitch that allows stacking of same enchant type

### ISSUE THREAD

**Issue by iMCB4** [GC-spigot/AdvancedEnchantments#729]
The highest enchantment tier I have available is Mythic, and for some reason all of those enchantments in that category have italicized lores and are able to stack lower enchants with higher enchants of the same type on the same weapon. All of the enchantment tiers work perfectly and aren't italicized.

Example:
https://gyazo.com/e7ee6d0c6cb50c251085d7b6285f224f

This is running on the latest version to date, 6.5.5

Thanks for the help!

**Comment by GC-spigot** [comment]
Reply on discord, will be easier for us to communicate there.
