### ISSUE TITLE
Telepathy + Silk Touch Combination Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#731]
Issue:
When a player mines any colored block using a telepathy and silk touch enchantment combination, the mined colored block will change to white instead.

Example:
Mine a red wool block/carpet (Any color) with a silk touch + telepathy enchantment combination turns the red wool into white.

Any colored block. Wool/Carpet/Clay/Glass etc

Plugin Version: 6.5.5

Server Version: Paper Spigot 1.14.4 and 1.13.2

**Comment by GC-spigot** [comment]
Will be fixed soon
