### ISSUE TITLE
Telepathy + Silk Touch combination bug #2

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#732]
Issue:
When a player mines any colored block using a telepathy and silk touch enchantment combination, the mined colored block will change to white instead.

Example:
Using Telepathy II to IV together with Silk Touch duplicates the spawners they are mining. A spawner will drop but the original spawner placed will not break. Continuous mining will result in many duplicates of the spawner.

Telepathy I works fine.

Plugin Version: 6.5.5

Server Version: Paper Spigot 1.14.4 and 1.13.2

**Comment by GC-spigot** [comment]
Will be fixed soon
