### ISSUE TITLE
/gkit issue

### ISSUE THREAD

**Issue by kadenscott** [GC-spigot/AdvancedEnchantments#737]
When running /gkit and trying to activate the cannoner kit, this error is thrown: https://pastebin.com/Uej5NmE0

(note: cannoner says LOCKED while all other gkits show UNLOCKED for ops)

**/version**
```
[05:40:17 INFO]: This server is running Paper version git-Paper-8 (MC: 1.15) (Implementing API version 1.15-R0.1-SNAPSHOT)
```

**/ae about**
https://i.imgur.com/YCCJ0DF.png

**Comment by kadenscott** [comment]
Looks like every gkit throws this error. Dk what's going on with the cannoner lore, but it seems unrelated.

**Comment by GC-spigot** [comment]
Update
