### ISSUE TITLE
Autosmelt Enchantment Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#741]
Issue:
1. When a player mines granite / andesite / diorite (tested), it gives out cobblestone instead.
2. When a player mines stone, it gives out cobblestone but not stone.

Example:
Use a pickaxe with autosmelt 1, 2, 3. Mine the stone/granite/andesite/diorite. Does not work as expected.

Plugin Version: 6.5.8

Server Version: Paper Spigot 1.14.4 and 1.13.2

**Comment by GC-spigot** [comment]
Issue is due to spigot's changes with materials, cannot be resolved atm in any way without dropping 1.8 support

**Comment by markusew** [comment]
> Issue is due to spigot's changes with materials, cannot be resolved atm in any way without dropping 1.8 support

Wouldn't it be possible to branch the plugin into one 1.8 version and one that is up to date with the new mc releases? Or do you fear that it would add too much work for you?

**Comment by GC-spigot** [comment]
Might be fixed soon, working on a huge rework to allow such update for newer versions.

**Comment by BboyZeroOne** [comment]
@GC-spigot could you test this again? This issue doesn't seem to happen for 1.15.2. But may still exist in 1.13.2 and 1.14.4 servers.
