### ISSUE TITLE
advancedenchantments-item-repairing-fix

### ISSUE THREAD

**Issue by Faceless0102** [GC-spigot/AdvancedEnchantments#745]
https://www.spigotmc.org/resources/advancedenchantments-item-repairing-fix.48835/
There is a bug with this addon, where if you just type "repair" on the chat, the cooldown just starts, tho you didn't even run the command.

**Comment by Faceless0102** [comment]
![image](https://user-images.githubusercontent.com/41546701/71490282-5c453b80-282a-11ea-8a29-46b31e4eb9cf.png)
as I see it is already reported

**Comment by GC-spigot** [comment]
Fixed
