### ISSUE TITLE
Holywhitescroll issue with instant respawn

### ISSUE THREAD

**Issue by MrPungle** [GC-spigot/AdvancedEnchantments#746]
Hi,
I don't know if it's known, but I got an issue with the holywhitescroll,
I'm using a combat plugin (DeluxeCombat) which has a instant respawn feature, basically it skips the minecraft death screen
And when this feature is enabled, holywhitescrolls doesn't works
When I die with a protected item, it will remains protected but he will be at my death location like a normal item
So that's an issue with instant respawn feature

I tried too with an inventory of protected item + an protected item equipped on me, and the items on the inventory will stay on my inventory after the death, but because blessed equipped armor comes back on the inventory once you're dead, my equipped chestplate felt into the void and I never found it again 

> Maybe to improve it, make that protected equipped item stays on the player after death and does not come back in inventory

Thanks for your help

**Comment by GC-spigot** [comment]
Instant respawning is not supported as there's no way to properly detect it.
