### ISSUE TITLE
add max health

### ISSUE THREAD

**Issue by SrJuggernaut** [GC-spigot/AdvancedEnchantments#747]
Add or decrease player life using the NBT tags of the objects instead of the Health Boost effect.

**Reason**: when using the effect you can only add or decrease 4 points at a time in addition to making these advantages non-cumulative, allowing you to do it this way can make you put the same spell on for example boots, helmet, etc. make it cumulative and therefore easier to customize.

**Comment by GC-spigot** [comment]
This is harder for me to control with plugin though as I'm not able to access few important pieces and would have to update whole enchant applying system to make it work so for now at least the current system has to stay.
