### ISSUE TITLE
Items not showing up in /enchanter

### ISSUE THREAD

**Issue by Vomet** [GC-spigot/AdvancedEnchantments#748]
Aight so I'm trying to make a cosmictest server with a few custom features and addons.

Anyways, I'm adding a few thinks to /enchanter and 2 of them don't work, specifically Tinkerer and Mastery Enchants. Anyway I can get help with this? (It charges my xp when i buy the book and opens tinkerer and runs the command if you're wondering items just don't show up)

![image](https://user-images.githubusercontent.com/42255377/71598265-aba7a680-2b5f-11ea-9093-35895673245b.png)

EDIT: Also I edited what my soul gems look like and they don't update:
![image](https://user-images.githubusercontent.com/42255377/71598809-d3980980-2b61-11ea-92d9-31167664fb65.png)
![image](https://user-images.githubusercontent.com/42255377/71598822-df83cb80-2b61-11ea-96d2-7a7afa90479c.png)

config.yml: https://pastebin.com/rLcsyPkC

**Comment by GC-spigot** [comment]
Please use pastebin.com to post your config, right now it's utterly useless posted this way. Soul gems only update after restart.

**Comment by Vomet** [comment]
> Please use pastebin.com to post your config, right now it's utterly useless posted this way. Soul gems only update after restart.

Updated the post.

**Comment by SkriptDeveloper** [comment]
Please send me your config.yml and customcommands.yml on discord Abdullah#8409. I'll help you fix the issue,

**Comment by GC-spigot** [comment]
Config you linked shows your configuration as this: http://prntscr.com/qi5210
