### ISSUE TITLE
two bug

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#753]
AE 6.6.9
paper 1.14.4

1. updata enchant(Enchanted evolution) can't use black-scroll remove

2. black-scroll give 0 , no random , i have try

**Comment by GC-spigot** [comment]
I don't know what world you live in, but `/ae giveitem <player> blackscroll 1 0` works.

**Comment by p82183645** [comment]
1 ?

**Comment by p82183645** [comment]
@GC-spigot
