### ISSUE TITLE
Failed to show "x" particle

### ISSUE THREAD

**Issue by JustKavis** [GC-spigot/AdvancedEnchantments#755]
Issue is when a particle is meant to appear, whether from "unlocking" an enchantment book or from an enchantment effect, for example 'epicness' enchantment shows no particle effect.

https://pastebin.com/nDn7G8aM

No other plugins were loaded during this time.
As of right now, latest version of AE and 1.15.1 MC
Using paper-spigot build #33

**Comment by GC-spigot** [comment]
This isnt an error, it shows that your minecraft version has different particle names from base configuration, just switch them out with your minecraft version's
