### ISSUE TITLE
Dupe issue with /alchemist and NCP

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#757]
Hey GC,

We found a bug that allows players to dupe enchanted books (AE) when NoCheatPlus was running. Steps to reproduce the issue:

- Open the alchemist window: /alchemist
- Add one or two books of your choice, don't actually combine them
- Loose the connection to the server (close Minecraft/get kicked/etc.)
- Reconnect
- The books should now be doubled

In opposite to that, the bug does not seem to occur with the tinkerer.

Paper version: 1.13.2/1.15.1
AE version: 6.7.3
NCP version: 3.16.1-SNAPSHOT-b5.2.4 (https://www.mc-market.org/resources/475/)

Thanks in advance!

**Comment by GC-spigot** [comment]
@sh1mrr4 can you PM me (GC#0830) on spigot about this? I cannot reproduce it without that plugin
