### ISSUE TITLE
Request Feature: Better ADD_DURABILITY and DAMAGE_ARMOR

### ISSUE THREAD

**Issue by Danrique** [GC-spigot/AdvancedEnchantments#761]
If we use like this:

  type: 'REPEATING'
  group: 'LEGENDARY'
  applies:
  - ALL_BOOTS
  levels:
    1:
      chance: 100
      cooldown: 1
      effects:
      - 'ADD_DURABILITY:1'

It removes durability from all armors equiped each second. I should remove only from the piece that has this enchant no? With this we can create temporary armors or maybe this enchant is the requisit of another powerfull enchant like fly. You lose durability to fly, pretty nice?

I hope you can add this feature! Thanks!

**Comment by GC-spigot** [comment]
Added
