### ISSUE TITLE
DEFENSE_MOB suggestion

### ISSUE THREAD

**Issue by YanisDark20041** [GC-spigot/AdvancedEnchantments#762]
DEFENSE_MOB could also detect arrows from skeletons and strays, explosions from creepers, skulls from wither, guardian rays, guardian thorns and shulker missiles.

I hope this is possible and thanks a lot for answering my questions and not being pissed of by me :)

**Comment by GC-spigot** [comment]
I'm adding the projectile activations, but for explosions you can use the EXPLOSION enchant type as well! Here's how it would look: `type: 'DEFENSE_MOB;EXPLOSION'
