### ISSUE TITLE
Feature Request - Evolution Kits

### ISSUE THREAD

**Issue by SkriptDeveloper** [GC-spigot/AdvancedEnchantments#767]
One feature that would probably be highly wanted is **Evolution Kits or Vkits**

These are much better versions of Gkits but it has levels from 1-10 (1 being the worst and 10 being the best)

On cosmic it looks like this - https://gyazo.com/abc0aed3db450987c40de0c2e5c2f702

Each time someone uses their evolution kit it has a chance of evolving into the next level. - https://gyazo.com/875a4fb2f238a51e7fdbc8f4aa2c1e68

The cooldown depends on the vkit, 

An example of the Vkit Loot is (Level 10 Loot) - https://gyazo.com/7959253ecf01e961b5272481aa97f1c3

**Comment by GC-spigot** [comment]
What would you recommend for configuration? Should each level's content be configurable or allow usage of placeholders, i.e: %1-5% for each level to have a higher level for enchants that have such level provided?

**Comment by SkriptDeveloper** [comment]
I think usage of placeholders would be good.
