### ISSUE TITLE
Feature request, addon to SuperMobCoins

### ISSUE THREAD

**Issue by Faceless0102** [GC-spigot/AdvancedEnchantments#772]
It would be wonderful, if you would have an enchantment, that can increase the chance of getting mobcoins.
https://www.mc-market.org/resources/8309/

**Comment by SkriptDeveloper** [comment]
You can make this yourself.

**Comment by Faceless0102** [comment]
Okay. How? @SkriptDeveloper

**Comment by Jok3rTV** [comment]
chance: 2
      cooldown: 5
      effects:
        - 'CONSOLE_COMMAND:tm add %attacker name% 1'
        - 'MESSAGE:&a&l+ 1 Token &7(Tokens Enchantment)'

**Comment by Jok3rTV** [comment]
mobcoins:
  display: '%group-color%Mob Coins'
  description: "Has a chance to increase mobcoins"
  applies-to: 'Weapon'
  type: 'KILL_MOB'
  group: 'COMMON'
  applies:
    - ALL_AXE
    - ALL_SWORD
  levels:
    1:
      chance: 2
      cooldown: 5
      effects:
        - 'CONSOLE_COMMAND:mobcoins give %attacker name% 1'
        - 'MESSAGE:&a&l+ 1 MobCoin'

**Comment by Faceless0102** [comment]
and how can I specify the mobs? @Jok3rTV

**Comment by Jok3rTV** [comment]
that already... type: 'KILL_MOB' that enchant will work only when you kill a mob

**Comment by Faceless0102** [comment]
@Jok3rTV Yes, but how can I make it so the effects are only running if the player kills a specific mob?

**Comment by GC-spigot** [comment]
Use conditions, e.g.: `condition: '%mob type% = PIG : %allow%`
