### ISSUE TITLE
Issue with removing Heroic enchantments via black scrolls (after changing removeable status)

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#779]
Hey GC,

there seems to be an issue currently, when we try to remove enchantments like Vengeful Diminish or Master Blacksmith by using blackscrolls. No matter what the settings in the config are, the message: "Enchantment XY cannot be removed!" always appears. I tried both to just remove the `removeable: false` property as well as setting it to true (this also seems to be the case with the default config).

Paper: 1.13.2
AE: 6.8.6

**Comment by GC-spigot** [comment]
Fixed
