### ISSUE TITLE
Issue when hit by a mob's projectile

### ISSUE THREAD

**Issue by YanisDark20041** [GC-spigot/AdvancedEnchantments#780]
Hello, I have a major issue, it is that when I use the DEFENSE_MOB trigger, it works well but if I get shot by a skeleton arrow (and I assume also wither skulls, stray arrows etc), the enchantment doesn't work and it gives an error in chat, this error tells me to go look in the console. So I did and i'll post a screenshot of what I got.
![screen1](https://user-images.githubusercontent.com/34489966/72983416-8403d100-3de1-11ea-888d-a164a6b70e26.png)

And here is the enchantment that I used in order to recreate the bug (but the error actually happens in every enchantment using DEFENSE_MOB)
![screen2](https://user-images.githubusercontent.com/34489966/72983469-a695ea00-3de1-11ea-9912-075f6252462c.png)

I hope I gave all the information needed, please fix it as soon as possible since this is actually a major issue for a PvE server :/ Thanks in advance ^^

**Comment by GC-spigot** [comment]
Fixed
