### ISSUE TITLE
Enchantments spamming console + Bugs

### ISSUE THREAD

**Issue by ShabbirSheeps** [GC-spigot/AdvancedEnchantments#781]
We are running PaperMC 1.15.2 (latest version ) with AdvancedEnchantments-6.8.7 (latest version).
When a player mines a block with telepathy it doesn't give them the block in their inventory thus drops it like a normal pickaxe would. It only shows an error in console or to players that have OP.

The error can be reproduced one someone mines a block with a Pickaxe that has telepathy. I was mining a Coal Ore with a Diamond Pickaxe that had Telepathy 4.

A video reproducing the bug can be seen below
https://files.fm/f/dngnt42t

This is the error that is being shown in console
`>.... [06:46:15 INFO]: [Minecraft] [AdvancedEnchantments ERROR] Could not pass NullPointerException:
>.... [06:46:15 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:994)
>.... [06:46:15 INFO]: [AdvancedEnchantments] Extra info: effect[TP_DROPS:]; enchant[telepathy]; mc[115]; ae[6.8.7]
>.... [06:46:15 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.`

**Comment by GC-spigot** [comment]
Bug with paperspigot 1.15.2 - use spigot 1.15.2 or wait till it's fixed, I will announce it in an update
