### ISSUE TITLE
[Suggestion] Magic Wands

### ISSUE THREAD

**Issue by TheRobLP** [GC-spigot/AdvancedEnchantments#784]
I just thought about a nice feature, fitting for this plugin. Magic Wands. Those are wands (wooden sticks) with different effects. For example "Freezing" or "Fireball" (shoots a ghast fireball), or "Protection" (generates a shield). Basically Harry Potter in Minecraft.

**Comment by GC-spigot** [comment]
You can enchant sticks with AE already out of the box, make the enchantments you want and use them on the sticks :)
