### ISSUE TITLE
BLOCK_STEP:(block):(time in ticks) Effect + Step Condition

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedEnchantments#790]
BLOCK_STEP:GLASS:60
This effect will change any block that I step on into glass for 3 seconds

I am not sure if this condition is a thing or not but I am making sure
%victim under block% > LAVA : %stop%
So when player stand on Lava block the enchant will active

**Comment by SkriptDeveloper** [comment]
+1
