### ISSUE TITLE
Still having issue with the DAMAGE_MOB

### ISSUE THREAD

**Issue by YanisDark20041** [GC-spigot/AdvancedEnchantments#791]
Hello! I already wrote an issue in the past when the DAMAGE_MOB triggers doesn't detect arrows from skeletons, fireballs, wither skulls etc and generates an error

Well, now it doesn't generate an error but it still fails silently, when shot by an arrow, the player would still take the damage (even though I use the "STOP_ATTACK" effect with the trigger "DAMAGE_MOB" at 100% chance) but nothing would display in chat.

Please fix this when possible, thanks in advance ^^

**Comment by GC-spigot** [comment]
Fixed
