### ISSUE TITLE
Telepathy Enchant Issue

### ISSUE THREAD

**Issue by SupehSloht1** [GC-spigot/AdvancedEnchantments#792]
I do not know if this is possible to fix but the block break event with the telepathy enchant probably gets cancelled and interferes with some other plugins. (Example: Quest/Mission Plugins)

**Comment by GC-spigot** [comment]
Mc version? All blocks behave like this or only new ones (if using 1.13+)?

**Comment by SupehSloht1** [comment]
My server is running 1.12.2 and all blocks behave like this.

**Comment by GC-spigot** [comment]
No way to fix this at the moment, I will consider possibilities for it for future. Sorry!
