### ISSUE TITLE
WorldGuard Flag for Enchants

### ISSUE THREAD

**Issue by YanisDark20041** [GC-spigot/AdvancedEnchantments#793]
Suggestion: Add a worldguard flag for making the enchantments usable or not in a certain zone. Could be useful for parkours when the effects like Flying, Jump Boost etc should not be usable :)

**Comment by SkriptDeveloper** [comment]
Good suggestion but not suggested properly.

**Comment by YanisDark20041** [comment]
Oh i'm sorry! I'll try my best to not reproduce this again :/
