### ISSUE TITLE
How to get all the effects in the enchantment?

### ISSUE THREAD

**Issue by Bkm016** [GC-spigot/AdvancedEnchantments#795]
I registered a new effect, but the existing AEnchantmentType cannot support it. I need to create a new listener, but how to get the effect on the item.

原文：
我注册了一个新的effect，但是已有AEnchantmentType无法支持，我需要创建新的监听器，但是如何获取物品上的effect

**Comment by GC-spigot** [comment]
Do you want to use your custom effect for enchantment?
