### ISSUE TITLE
Auto Smelter

### ISSUE THREAD

**Issue by max0r4axor** [GC-spigot/AdvancedEnchantments#796]
Auto Smelter works but only for a few seconds it will completely stop a user from mining they'll still have the animation but no blocks break. This is using a Ore generator btw. If i remove the enchant they mine forever fine.

**Comment by GC-spigot** [comment]
Is it a basic ore generator or powered by a plugin?

**Comment by max0r4axor** [comment]
Its advanced orgenerator
