### ISSUE TITLE
6.9.3 version didn't load for anyone.

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#797]
6.9.3 version didn't load for anyone.
6.9.3 version didn't load for anyone.
6.9.3 version didn't load for anyone.

Very important so say three times
You ignore every time
Please test it
Please don't say no problem without testing

paper 1.14.4

**Comment by GC-spigot** [comment]
It did load, 6.9.2 did not. Seems like you had too many Ips with the antileak system, try restarting. If issue still happens tag me here.
