### ISSUE TITLE
Black Scrolls don't work anymore

### ISSUE THREAD

**Issue by iMCB4** [GC-spigot/AdvancedEnchantments#800]
Ever since updating to the latest versions of AdvancedEnchantments (Currently on 6.9.3) the black scroll can't remove any enchantments. In the past I had issues with Ethereal Dodge, Shadow Assassin, Master Inquisitive & Master Blacksmith. But now, you can't take any custom enchant off of an item.

https://i.gyazo.com/702d99371c209f996441cdfd797e7269.png

**Comment by GC-spigot** [comment]
Sorry about this! Fixed.
