### ISSUE TITLE
Error with DeluxeMenus

### ISSUE THREAD

**Issue by CaoTrongThang** [GC-spigot/AdvancedEnchantments#801]
AdvancedEnchantments-6.9.3
PaperSpigot 1.15.2

I got this error with DeluxeMenus, hope you will take a look about it
https://paste.md-5.net/wituganuve.sql

This is the command im using to give enchantments books
ae givercbook * %player_name% 1

I don't know what you meant and how to fix it
![image](https://user-images.githubusercontent.com/51023235/73569145-6c40e280-449c-11ea-838e-5ba7b617f102.png)

**Comment by GC-spigot** [comment]
I tested it, it works for me. I added informative error which will be shown in-game (similar to how enchantments show when one fails) which will tell you what group it's using and what issue you have. If you still cannot figure it out after this update please post on discord and I will get back to you.
