### ISSUE TITLE
Feature request - Effect that reduces damage by a specified percentage

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#803]
In the vanilla config, there are quite a few enchantments that are supposed to reduce the incoming damage by a certain percentage (e.g. Master Blacksmith, Heavy, Tank, Valor, Armored), however they use the NEGATE_DAMAGE/REMOVE_DAMAGE effect, which only reduces the damage by a certain amount.

While this makes the descriptions a bit misleading, it would also be very helpful to have the ability of adding enchantments that reduce damage by e.g. 10%, 25% or 75%.

I think adding an effect like that would allow users to customize to be more flexible when it comes to creating customized enchantments like this, since the only alternative currently seems to be HALF_DAMAGE, which isn't appropriate in all cases.

Thanks a lot!

sh1mrr4

**Comment by GC-spigot** [comment]
You can use `INCREASE_DAMAGE:-<value>`, negative values will decrease damage, this is based on percentages.
