### ISSUE TITLE
More versatility with the API towards souls

### ISSUE THREAD

**Issue by TasmanianNoob** [GC-spigot/AdvancedEnchantments#804]
Basically AEAPI.getSoulsOnItem(itemStack) returns the number of souls on that item currently there is only AEAPI.getSoulsOnGem(itemStack) which only returns the number of souls on a gem.
AEAPI.removeSoulsOnItem(Integer) removes souls from item/soulgem.

**Comment by GC-spigot** [comment]
As I've said on discord, since this is NBT you're better off just creating the new soulgem compared to this, either way you'll get an item you will need to override.
