### ISSUE TITLE
Feature Request - Update Holy White Scrolls

### ISSUE THREAD

**Issue by SkriptDeveloper** [GC-spigot/AdvancedEnchantments#808]
In my opinion holy white scrolls could have it's own section in the config or its own config. 

_**What i would like to see**_

An option like **require-whitescroll: true/false**
A /collect menu (configurable). On death players can have their gear safe in a menu and can collect within like a day or two (configurable) and the menu will reset

**Comment by GC-spigot** [comment]
Wouldn't want to trash people's current configuration for this move
