### ISSUE TITLE
Feature Request - XenZify

### ISSUE THREAD

**Issue by XenZify** [GC-spigot/AdvancedEnchantments#809]
I typed this asking about in the support discord AE channel:

> GC. Is there a way to add a Custom Enchant to an item using the essential command?
> When you do the command such as this:
> /give XenZify Diamond_Pickaxe efficiency:5 unbreaking:3 name:&b&lDiamond_Pickaxe

> You'd get such that, a Diamond pickaxe named &b&lDiamond Pickaxe with efi 5 unb3... but can you add an enchant from your plugin into that command to have it apply the custom enchant to that pickaxe?

Someone told me to request it...

I think this would be really cool to add as it would easily allow players to set up items in a Crate Plugin and have it run /give %Player% diamond_pickaxe 1 *vanilla enchants**AE Enchants* *name*! Please do add this! :)

**Comment by GC-spigot** [comment]
Added
