### ISSUE TITLE
Headless enchant issue

### ISSUE THREAD

**Issue by Deathinflames** [GC-spigot/AdvancedEnchantments#811]
Hello, we're running a spigot 1.13.2 server using AE 6.9.11 and we've discovered when killing a wither skeleton using the headless enchant a normal player head named "wither skeleton's Head" drops instead of an actual wither skeleton head. Other mobs seem to be dropping their head correctly and so far it's only been discovered that the wither skeleton entity is the only entity experiencing this issue. Unfortunately, there is no error displayed in the console nor any message displayed in-game that could be used to more accurately locate the issue within the code.

**Comment by Fyreheart** [comment]
When killing a mob, I get these errors.
So far I've tried Chicken, Sheep, Cow, Skeleton, Spider

In-game:
![](https://i.gyazo.com/1ba8e45ce2100b7e3742b1d83009277a.png)

In the console:
![](https://i.gyazo.com/f61488f6ef81a54bda726de7e786fa5e.png)

**Comment by GC-spigot** [comment]
This can only be used against players as only players have skins.
