### ISSUE TITLE
detonate doesnt work

### ISSUE THREAD

**Issue by Cawleeflower** [GC-spigot/AdvancedEnchantments#815]
updated the plugin to the latest and doesnt fix
10.02 00:59:39 [Server] INFO [AdvancedEnchantments ERROR] Could not pass NullPointerException: 
10.02 00:59:39 [Server] INFO [AdvancedEnchantments]    Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1132)
10.02 00:59:39 [Server] INFO [AdvancedEnchantments]    Extra info: effect[TRENCH:7]; enchant[atomicdetonate]; mc[115]; ae[6.9.14]
10.02 00:59:39 [Server] INFO [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
please help

**Comment by GC-spigot** [comment]
Fixed
