### ISSUE TITLE
[Request] Add a command /apply *

### ISSUE THREAD

**Issue by Zenya4** [GC-spigot/AdvancedEnchantments#821]
Currently, the `/apply` command only works for individual players. I'm requesting for a feature `/apply *` to apply armor CE effects for all players on the server.

This can be useful for KitPvP servers which have a separate kit plugin (other than Essentials) which causes the player to instantly wear armor pieces, resulting in enchantments not being applied properly until the armor is reworn. It would really be nice to see this feature for the AE plugin.

**Comment by GC-spigot** [comment]
Added
