### ISSUE TITLE
[Request] new require condition 

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedEnchantments#822]
I would like to have a condition that will work when you have have the enchantment on few parts of the armor.

for example
condition: '%jump% = 4 : %continue%' 

if you have 4 jump enchantment on your armor (helmet, chestplate, leggings, boots) the enchantment will activate

condition: '%jump% = 2 : %continue%' 

if you have 2 jump enchantment on your armor (helmet + chestplate for example) the enchantment will activate

**Comment by GC-spigot** [comment]
Use %has potion effect <potion effect name>% and a second conditon (adding this in today's update) %potion effect level <potion effect name>%, it will return a number of active potion effect's level

**Comment by Jok3rTV** [comment]
Ye but how the enchantments will know that there is 4 of the same jump enchant on my helmet chestplate leggings and boots? at the second that the enchant will find the potion the enchant will be activated and not when you have 4 times of it
