### ISSUE TITLE
Orb Bug

### ISSUE THREAD

**Issue by SkriptDeveloper** [GC-spigot/AdvancedEnchantments#826]
**Describe the bug**
Enchantment Orb lore bug

**To Reproduce**
Get 2 different orbs and place them on an item

**Screenshots / Video**
https://gyazo.com/0df707223448bec342b954902f3c30db

**Server Information (please complete the following information):**
 - Minecraft Version - Spigot 1.8.8
- V 7.0.0 pre-release 3

**Comment by GC-spigot** [comment]
Fixed
