### ISSUE TITLE
[Issue] Obsidian Destroyer bypasses worldguard flags

### ISSUE THREAD

**Issue by iMCB4** [GC-spigot/AdvancedEnchantments#828]
**Describe the bug**
Obsidian Destroyer bypasses worldguard flags and anyone can break obsidian with it (only obsidian)

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.15.2
- Plugin Version 6.9.4

**Comment by GC-spigot** [comment]
Fixed
