### ISSUE TITLE
telepathy issue with blocktrack and ice

### ISSUE THREAD

**Issue by Stoniasawsome** [GC-spigot/AdvancedEnchantments#829]
im having a problem when applying telepathy and blocktrack to a non silk pick and mining ice. Ice only mines with silk, so when i try to break it with a pick with telepathy it wont break the block, also the blocktracker tracks the block and adds blocks to the blocktrack even tho it didnt break. so a player can have 10000000 blocks broke on the picks in no time at all. and not break a block doing it.
this happens with alot of blocks that arent suppose to be broke with picks. also it does the same thing for axes and shovels

minecraftversion 1.15.1 spigot
plugin update 7.0.0-pre4

**Comment by GC-spigot** [comment]
Fixed

**Comment by Stoniasawsome** [comment]
wonderful, thank you
