### ISSUE TITLE
[Request] Enchants should only work on things the tools is meant for.

### ISSUE THREAD

**Issue by Ellendyra** [GC-spigot/AdvancedEnchantments#830]
** Describe the Request**
I would like it if when you used an enchant like detonate that clears blocks in (for example) a 5x5 radius it only cleared blocks that the tool is intended to break.  A pickaxe would only break stone/ores/etc, and not logs/dirt/leaves.

A Pickaxe isn't meant to level a tree just like you aren't meant to mine with an ax, so I propose that it either only breaks the one block you are looking at or it doesn't break leaves/log at all if that's possible. 

This would help balance the skills out as currently all enchants are fun but pretty OP.

**Comment by Pajlis** [comment]
I would like to second this feature request. Possibly adding a config option to choose the blocks you want like with a whitelist or blacklist option.

Example:
Pickaxe Blacklist:
- Dirt
- Sand

Shovel:
- Stone
