### ISSUE TITLE
[Issue] ADD_FOOD not giving saturation and thus not regening health

### ISSUE THREAD

**Issue by markusew** [GC-spigot/AdvancedEnchantments#831]
**Describe the bug**
At times, when ADD_FOOD from an enchantment adds food for a player, they don't get the saturation so they don't get healed similar to what eating minecraft food would. This makes them unable to regen health and they can't eat because they are at full food.

**Server Information**
 - Minecraft Version Paper 105 (1.15.2)
- Plugin Version 6.9.14

**Comment by GC-spigot** [comment]
If they aren't healing it must be some other fault, minecraft automatically assigns saturation to heal the player
