### ISSUE TITLE
Losing items in /enchanter menu[Issue]

### ISSUE THREAD

**Issue by CloudRealms** [GC-spigot/AdvancedEnchantments#832]
**Describe the bug**
In the /enchanter menu, if you hower over an empty slot with your mouse, and press a number f rom 1-9 (which is your slot keybind), if you have an item in it, it will put it in the GUI and you have officially lost the item.

**To Reproduce**
put an item in slot 1, for example. go in the /enchanter menu, press 1, and then your item should be placed in that slot you hovered over in the enchanter menu, until refresh (losing your item).

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/40527831/74958979-19f34180-540a-11ea-82e9-3fbb6bc71acc.png)

**Server Information (please complete the following information):**
 - PaperSpigot 1.14.4
- Plugin ver: 7.0.0-Pre 4

**Comment by GC-spigot** [comment]
Fixed
