### ISSUE TITLE
[Issue] Telepathy and Detonate randomly stop working and start working. Even with 100% chance.

### ISSUE THREAD

**Issue by kangaroozy12** [GC-spigot/AdvancedEnchantments#833]
**Describe the bug**
Telepathy and detonate work for some players and don't work for others at random points throughout the day. 

**To Reproduce**
Detonate working, adding telepathy stops it working. (Something else that happens)

**Screenshots / Video**
If applicable, add screenshots to help explain your problem. N/A

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.15.2]
- Plugin Version [7.0.0-pre5]

**Comment by GC-spigot** [comment]
Without really much details or errors it's hard to know, could be due to region or conflicting plugin. If you get more details please reopen a ticket otherwise I will change few things around just to see if it changes something.
