### ISSUE TITLE
obsidian destroyer

### ISSUE THREAD

**Issue by Stoniasawsome** [GC-spigot/AdvancedEnchantments#834]
I cant get obsidian destroyer to work at all, even at op lvl

i dont run factions or grief protection plugins. but i see its a part of that code (%player faction land%) in the enchant file
this is my obsidian destroyer enchant file. Is there something ive done wrong to make this enchant not work? Ive put the chance at 100% for lvl 5 with no cooldown but it still dont 1hit obsidian

obsidiandestroyer:
  display: '%group-color%&5Obsidian Destroyer'
  description: 'Chance to instantly break obsidian blocks.'
  applies-to: 'Pickaxe'
  type: 'SWING'
  group: 'UNIQUE'
  applies:
  - ALL_PICKAXE
  levels:
    1:
      chance: 15
      cooldown: 8
      condition:
        - '%block type% != OBSIDIAN : %stop%'
        - '%player faction land% != MEMBER : %stop%'
      effects:
        - 'BREAK'
    2:
      chance: 30
      cooldown: 6
      condition:
        - '%block type% != OBSIDIAN : %stop%'
        - '%player faction land% != MEMBER : %stop%'
      effects:
        - 'BREAK'
    3:
      chance: 50
      cooldown: 5
      condition:
        - '%block type% != OBSIDIAN : %stop%'
        - '%player faction land% != MEMBER : %stop%'
      effects:
        - 'BREAK'
    4:
      chance: 65
      cooldown: 4
      condition:
        - '%block type% != OBSIDIAN : %stop%'
        - '%player faction land% != MEMBER : %stop%'
      effects:
        - 'BREAK'
    5:
      chance: 100
      cooldown: 0
      condition:
        - '%block type% != OBSIDIAN : %stop%'
        - '%player faction land% != MEMBER : %stop%'
      effects:
        - 'BREAK'

**Server Information (please complete the following information):**
 - Minecraft Version [Spigot 1.15.1]
- Plugin Version [7.0.0-pre5]

**Comment by GC-spigot** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/commit/9f9d3be this was linked on an update which reworked obsidian destroyer, look at changes on the right and use them to fix it
