### ISSUE TITLE
Take off bug

### ISSUE THREAD

**Issue by Cawleeflower** [GC-spigot/AdvancedEnchantments#835]
**Describe the bug**
Players can fly without having to wear boots with takeoff

**To Reproduce**
Dk how to add video, since it cant support mp4
Drag the boots to the feet, quickly remove it by wearing and removing the boots from the feet.

**Screenshots / Video**

**Server Information (please complete the following information):**
 - PaperSpigot 1.15.2
AdvancedEnchantments-7.0.0pre4.

**Comment by GC-spigot** [comment]
I was able to reproduce it and now with changes I cannot, if there's still issues after update please reply to this
