### ISSUE TITLE
Poltergeist Problem

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#839]
**Describe the bug**
Poltergeist enchantment doesn't work, posts an error message in chat and console

**To Reproduce**
Fall from any height to activate poltergeist to see the bug

**Screenshots / Video**
https://gyazo.com/79b8c7f9e4576915ebc9c3b61c3ef4e5

**Server Information (please complete the following information):**
 - Minecraft Version [Beer Spigot 1.8.8]
- Plugin Version [6.9.14]

**Comment by GC-spigot** [comment]
Fixed
