### ISSUE TITLE
magic dust not working?

### ISSUE THREAD

**Issue by Stoniasawsome** [GC-spigot/AdvancedEnchantments#840]
i cant get the command /ae giveitem <player> <item> to work for magic dust

im using spigot 1.15.1
with your currecnt version of enchants 7.0.0pre6

when i type /ae giveitem stoniasawsome magic or magic 1 it gives me this error

Failed to execute command: Group name not set in command, must be in capitals.

so i try it with capitals MAGIC and nothing happens

**Comment by GC-spigot** [comment]
Put a group name at the end

**Comment by Stoniasawsome** [comment]
a group name like what? nothing seems to work. can i have an example of what command i would use to spawn magic dust?
