### ISSUE TITLE
[Issue] SMELT Issue

### ISSUE THREAD

**Issue by ZeddyOG** [GC-spigot/AdvancedEnchantments#842]
**Describe the bug**
When having a custom enchantment using the SMELT effect and you mine a piece of stone with a pickaxe that is enchanted with Silk Touch (and has the custom enchant) it will give you back cobblestone when it should just give the stone, as stone cannot smelt into cobblestone.

Vise versa if you use a pickaxe with just the custom enchantment and mine a piece of cobblestone it will give that piece of cobblestone back and not smelt it to stone.

**To Reproduce**
Issue 1: Enchant any pickaxe with silk touch and a custom enchantment using SMELT and mine a piece of stone.

Issue 2: Enchant any pickaxe with a custom enchantment using SMELT and mine a piece of cobblestone.

**Screenshots / Video**
I don't feel that any screenshots/vidoes are required.

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.15.2
- Plugin Version 7.0.0-Pre5

**Comment by GC-spigot** [comment]
Fixed
