### ISSUE TITLE
[Request] FALL_DAMAGE extension

### ISSUE THREAD

**Issue by ZeddyOG** [GC-spigot/AdvancedEnchantments#844]
** Describe the Request**
Make the effects that deal with damage output respect when you use FALL_DAMAGE, like have NEGATE_DAMAGE actually negate the fall damage or add a new effect like IGNORE_DAMAGE that will work with FALL_DAMAGE to negate the fall damage.

**Comment by GC-spigot** [comment]
Added support for STOP_ATTACK effect with FALL_DAMAGE
