### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [GC-spigot/AdvancedEnchantments#845]
**Describe the bug**
Deluxechat isn't supported when using rename scrolls. When a user tries to use colour codes it doesn't work

**To Reproduce**
Use deluxechat and a rename scroll

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
- 1.12.2 paper
- Latest

**Comment by YouSeeMeRunning2** [comment]
Forgot to note, the user doesn't have colour permissions

**Comment by GC-spigot** [comment]
Should be fixed
