### ISSUE TITLE
[Bug Report] Implants and Alien implants - ★★★

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#846]
**Bukkit**: Paperspigot 1.13.2
**Plugin**: AdvancedEnchantments 7.0.0-pre6
**Bug severity**: ★★★
**Explanation**: Implants and alien implants sometimes do not work.
It's my guess, but it doesn't trigger if you equip it while taking damage.

Once the effect doesn't work, the effect doesn't activate even if you take off the item with drag & drop.

In this case, take off the helmet, place items in slots 1-9 and place them with the right mouse button, and Implants and alien implants will work again.

**Video**: https://youtu.be/wTUW-7Upc18
**Config**: https://pastebin.com/rXy7vArr
**Additional Notes**: For this test I set Implants time to 1 and then set the probability to 100.

**Comment by FeroxDrood** [comment]
Also getting this issue, like said above, only works when you right click it the item with the enchant from your hotbar.
