### ISSUE TITLE
[Bug Report] There is a problem with the CURE series enchant. - ★★★★

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#847]
**Bukkit**: Paperspigot 1.13.2
**Plugin**: AdvancedEnchantments 7.0.0-pre6
**Bug severity**: ★★★★
**Explanation**: There is a problem with the CURE series enchant.
Enderwalker, Metaphysical, Polymorphicmetaphysical etc,
Incents entering Cure do not work.

**Video**: https://youtu.be/FM8632MriT8
**Additional Notes**: For this test I set set the probability to 100.

**Comment by GC-spigot** [comment]
They only heal when player receives PVP damage
