### ISSUE TITLE
[Bug Report] Right-click potion effects on Iron Block (Mcmmo Repair) to receive unlimited potion effects - ★★

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#848]
**Bukkit**: Paperspigot 1.13.2
**Plugin**: AdvancedEnchantments 7.0.0-pre6
**Bug severity**: ★★
**Explanation**: Right-click potion effects equipment on Iron Block (Mcmmo Repair) to receive unlimited potion effects.
**Video**: https://youtu.be/lf7fMRBk2mg

**Comment by GC-spigot** [comment]
Fixed
