### ISSUE TITLE
[Issue] Custom name and lore not showing

### ISSUE THREAD

**Issue by Vomet** [GC-spigot/AdvancedEnchantments#849]
**Describe the bug**
So I'm trying to change the soul gem's name and lore and when i load it in, nothing changes.

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/42255377/75577076-a345ec00-5a7a-11ea-9e8f-4636e860982b.png)
![image](https://user-images.githubusercontent.com/42255377/75577096-ac36bd80-5a7a-11ea-8265-b1e7b51dde69.png)

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.8.8]
- Plugin Version [7.0.0 pre-6]

**Comment by Vomet** [comment]
This also happened.
![image](https://user-images.githubusercontent.com/42255377/75601133-b3d58100-5ad1-11ea-9d53-76c22eea9803.png)

**Comment by GC-spigot** [comment]
PM GC#0830 on Discord with your configuration files, also for soul gems to update you need to restart.
