### ISSUE TITLE
TP_DROPS doesn't teleport exp.

### ISSUE THREAD

**Issue by flrping** [GC-spigot/AdvancedEnchantments#851]
**Describe the bug**
TP_DROPS teleports drops but deletes/doesn't give EXP.

**To Reproduce**
Just assign TP_DROPS to a pickaxe enchant and mine ores. 

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/34534419/75631110-1015cf00-5bbe-11ea-855a-54b1b06b2a7a.png)

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version [e.g. V7.0.0 pre-release latest]

**Comment by GC-spigot** [comment]
It is not designed to - "Blocks are automatically put in your inventory"
