### ISSUE TITLE
Bow enchants that currently don't work

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#853]
Longbow - doesn't work with 100% chance, player I was shooting was holding a bow

Virus - doesn't stop regeneration, no wither enchant for the bow to test

Hijack - doesn't steal enemy guardians, I put on 100% chance still won't work

Farcast enchant doesn't work - I put on 100% chance and it doesn't knockback attackers that hit me with swords

**Comment by GC-spigot** [comment]
Longbow works - remove uncontrollable factors and it will, here's what I used for testing it: https://pastebin.com/y1KqWmSJ

Virus worked as well, improved it to remove regeneration as well
Hijack and Farcast worked with patience as well.

Always remember to remove cooldowns/effects & add a message to enchants as they might be hard to notice.
