### ISSUE TITLE
ArmorEquipEvent doesn't register putting the helmet into the helmet slot [Issue]

### ISSUE THREAD

**Issue by TasmanianNoob** [GC-spigot/AdvancedEnchantments#855]
**Describe the bug**
If you click a helmet (Any helmet) and put it in your helmet slot the enchantments don't register.

**To Reproduce**
Grab a helmet and click it into your helmet slot.

**Screenshots / Video**
https://youtu.be/UmU87g93K3g

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.12.2
- Plugin Version: 7.0.0

**Comment by GC-spigot** [comment]
Is this for helmets only or for all armor pieces?

**Comment by TasmanianNoob** [comment]
> Is this for helmets only or for all armor pieces?

Only for the helmet armor piece.
