### ISSUE TITLE
[Bug Report] Attacking a citizen NPC with shackle enchant will allow you to drag and drop NPC. - ★★★★

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#856]
**Bukkit**: Paperspigot 1.13.2
**Plugin**: AdvancedEnchantments 7.0.0-pre6
**Bug Severity**: ★★★★
**Explanation**: Attacking a citizen npc with shackle enchant will allow you to drag and drop npc.
**Video**: https://youtu.be/5m6ZWo59XjU

**Comment by GC-spigot** [comment]
Fixed
