### ISSUE TITLE
[Bug Report] Infinite potion effect with /hat - ★★★

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#859]
**Bukkit**: Paperspigot 1.13.2
**Plugin**: AdvancedEnchantments 7.0.2
**Bug Severity**: ★★★
**Explanation**: Put a potion enchant on your head with / hat, then remove it to keep the potion effect. And you can get additional potions by wearing other gear.
**Video**: https://youtu.be/P0JwagamNMA

**Comment by GC-spigot** [comment]
Its not supported, its an essentials command
