### ISSUE TITLE
Updated Poltergeist enchant not working

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#860]
**Describe the bug**
When the player falls from great height and falls down to the ground poltergeist would show up in chat once they hit the ground but it doesn't negate all fall damage

**To Reproduce**
put 100% chance on poltergeist to work and apply to boots, go high up in the sky and fall and no fall damage will be negated

**Screenshots / Video**
https://gyazo.com/f1a5a74434399f83bbd4b26fd70ded71

**Server Information (please complete the following information):**
 - Minecraft Version [BeerSpigot 1.8]
- Plugin Version [7.0.2]

**Comment by GC-spigot** [comment]
Changed the description
