### ISSUE TITLE
Possible equipment duplication

### ISSUE THREAD

**Issue by toriato** [GC-spigot/AdvancedEnchantments#861]
**Describe the bug**
Duplication glitch

**To Reproduce**
1. Equip any item to helmet
2. Equip any item to offhand
3. Right click

**Screenshots / Video**
[Youtube](https://youtu.be/czoPKEdK2DE)

**Server Information (please complete the following information):**
- Paper 1.15.2 build 126
- AdvancedEnchantments 7.0.2 (default config)

**Comment by GC-spigot** [comment]
Fixed
