### ISSUE TITLE
[Issue] Head hot-swap issue

### ISSUE THREAD

**Issue by ZeddyOG** [GC-spigot/AdvancedEnchantments#866]
**Describe the bug**
When wearing a helmet and attempting to place a skull on the ground AE will hot swap the helmet and the head. This causes the head to be duplicated as it is both placed in game and placed on the player via AE and the helmet completely disappears.

**To Reproduce**
Place a helmet on your head and get any skull in game. Look at a block and place the skull on the block.

**Screenshots / Video**
https://www.youtube.com/watch?v=r5cA1n6pWa0

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.15.2
- Plugin Version: 7.0.3

**Comment by GC-spigot** [comment]
Fixed
