### ISSUE TITLE
[Issue] TP_DROPS effect does not work properly with Silk Touch

### ISSUE THREAD

**Issue by mammaknullare** [GC-spigot/AdvancedEnchantments#872]
**Describe the bug**
TP_DROPS effect in AdvancedEnchantments does not seem to work properly with Silk Touch enchant. Every time you break one of the blocks listed below, the block does not break. 

**Blocks** (only ones I could find)
- Glass
- Stained glass
- Glass pane
- Stained glass pane
- Leaves (all types)
- Ice
- Packed ice

**To Reproduce**
Break the blocks listed above with a silk touch pickaxe with an enchantment that has the TP_DROPS effect.

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.8.8

**Comment by GC-spigot** [comment]
Fixed
