### ISSUE TITLE
[Issue] ASets

### ISSUE THREAD

**Issue by ZeddyOG** [GC-spigot/AdvancedEnchantments#874]
**Describe the bug**
Bug 1: POTION doesn't get removed after set is removed / event is not happening

Bug 2: Effect only activates on first apply or /ae reload

**To Reproduce**
Bug 1: Make a custom set using POTION at a 100% chance (I used MINING for my set) apply it, mine some blocks, and then remove it or stop mining. 

Bug 2: Make a custom set using KILL_MOB + EXP at a 100% chance and kill some mobs (I used EXP:99), the EXP will only work the 1st time the set is applied or after you run /ae reload.

**Screenshots / Video**
Bug 1: https://youtu.be/vwz8l10XKPc

Bug 2: https://youtu.be/4RL6tJ4RVrU

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.15.2
- Plugin Version: 7.0.3

**Comment by GC-spigot** [comment]
For first use EFFECT_STATIC mining will just add permanent effects unless you set time for them
Second works fine for me when testing as well, could be some kind of a exp stacking plugin interfering
