### ISSUE TITLE
[Issue] Color codes in enchant item description don't get colored

### ISSUE THREAD

**Issue by Shawn11564** [GC-spigot/AdvancedEnchantments#875]
**Describe the bug**
When you add color codes to the description of your enchants, they remain the regular light gray color. In /ae admin, they are colored correctly, but not on the item itself.

**To Reproduce**
Add color codes to the description of an enchantment and then give yourself an enchant book.

**Screenshots / Video**
https://gyazo.com/fe238d6cd9501eea007b367c5c744611

**Server Information (please complete the following information):**
 - Minecraft Version: 1.15.2
- Plugin Version: 7.0.5

**Comment by GC-spigot** [comment]
Fixed
