### ISSUE TITLE
[Issue] Can't use dyes in config

### ISSUE THREAD

**Issue by Shawn11564** [GC-spigot/AdvancedEnchantments#877]
**Describe the bug**
Any dye used in config will result in an error that the material isn't found.

**To Reproduce**
Put a dye name (Ex: yellow_dye) or an item id (Ex: 351:1) in config and reload the plugin.

**Screenshots / Video**
https://gyazo.com/a8f56a9c513dce7d044200fca7f57d0f

**Server Information (please complete the following information):**
 - Minecraft Version: Paperspigot 1.15.2
- Plugin Version: 7.0.8

**Comment by Shawn11564** [comment]
To add to this, you can't use banner patterns either.

**Comment by GC-spigot** [comment]
Should be fixed
