### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Snowy654** [GC-spigot/AdvancedEnchantments#879]
**Describe the bug**
NPE when equipping enchanted boots

**Screenshots / Video**
https://gyazo.com/0e732054a934dd002992e5831b05afaa - Ingame
https://gyazo.com/0b7994691b34100d21359afa5181f3e4 - Console

**Server Information (please complete the following information):**
 - Minecraft Version - Paper 1.15.2
- Plugin Version 7.0.8

**Comment by GC-spigot** [comment]
Fixed
