### ISSUE TITLE
/gkits not opening the GUI

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#883]
**Describe the bug**
I recently updated to the most recent version of AdvancedEnchantments on my test server, tried out all commands and when I try to get the GUI open for gkits it doesn't show, I have checked the console and no errors come up.

**To Reproduce**
Update to most recent version and run the command /gkits

**Screenshots / Video**
https://gyazo.com/b265486fa8ad05291a46f661a70208ce
https://gyazo.com/5dd37ae2a1fc2fda34dbbe7d477cb015

**Server Information (please complete the following information):**
 - Minecraft Version [BeerSpigot 1.8]
- Plugin Version [7.0.9]

**Comment by GC-spigot** [comment]
Fixed
