### ISSUE TITLE
[Request] Configure enchanter-book rewards

### ISSUE THREAD

**Issue by fuzzybear3232** [GC-spigot/AdvancedEnchantments#885]
** Describe the Request**

I would love if it was an option to configure what level enchantment books can be given when using the enchanter books. Even if it was just a true/false switch for random levels or set levels if this is easier. 

 I'm fairly certain this is not already something I can do, if so please let me know how. I would love to only have tier/level 1 enchantments be rewarded.

**Comment by GC-spigot** [comment]
Added
