### ISSUE TITLE
[Issue]Items Disappearing

### ISSUE THREAD

**Issue by FlowZz99** [GC-spigot/AdvancedEnchantments#887]
**Describe the bug**
Whenever you apply a customenchant book on an item if you don't move the items before closing the inventory it deletes the first item it finds
**To Reproduce**
Take one item and a book, apply the book, close your inv.

**Screenshots / Video**
https://www.youtube.com/watch?v=z6V06swcl_w&feature=youtu.be

**Server Information (please complete the following information):**
 - Paper 1.8.8
- 7.0.9

**Comment by GC-spigot** [comment]
That must be another plugin removing the item, not mine. If you have any "illegalstack" plugins (i.e. ones that remove invalid items) or an old version of wildstacker update.
