### ISSUE TITLE
[Issue] TP_DROPS + SMELT caused pickaxe to be able to mine spawners

### ISSUE THREAD

**Issue by blek-id** [GC-spigot/AdvancedEnchantments#888]
**Describe the bug**
Pickaxe enchantment containing TP_DROPS and SMELT will make player able to mine spawners. 

**To Reproduce**
- Get the 2 books from /ae admin on this config https://paste.md-5.net/xaxegofaqe.bash
- Apply both of them to a pickaxe
- Mine spawners

**Server Information (please complete the following information):**
 - Minecraft Version -- PaperSpigot 1.15.2, build 143
- Plugin Version -- 7.0.9

**Comment by GC-spigot** [comment]
Update your SilkSpawners, it's the root cause of this issue, on newest version of SilkSpawners I'm not able to recreate it. Any other spawners plugin works fine.

**Comment by blek-id** [comment]
I don't have SilkSpawner plugin

**Comment by BboyZeroOne** [comment]
Same, I don't use silk spawner but cmi's built-in spawner.

https://pastebin.com/SwvxjjMJ

**Comment by blek-id** [comment]
Apparently it's because of using new paper build. I'm currently on paper build 145

**Comment by BboyZeroOne** [comment]
not really, even on my old 1.13.2 paper server, this issue still occurs

**Comment by GC-spigot** [comment]
Will reopen until issue is found

**Comment by blek-id** [comment]
> Will reopen until issue is found

Have you been able to reproduce the bug?
With latest version paper?

**Comment by blek-id** [comment]
Found another duplication bug with it,

you can mine iron doors, and they would duplicate on destroy. Same enchantment combination as the spawner

**Comment by blek-id** [comment]
Hi there, any update on this particular issue?

**Comment by BboyZeroOne** [comment]
@blek-id does the duplication still work for you in the latest version?

**Comment by blek-id** [comment]
It doesn't anymore, after latest paperspigot build on 1.15.2 @BboyZeroOne
