### ISSUE TITLE
[Issue] Command not firing properly

### ISSUE THREAD

**Issue by pvpstryker** [GC-spigot/AdvancedEnchantments#889]
**Describe the bug**
In the customcommands.yml file, I tried disabling the click command by doing this:
`  group-enchantment-inventory:
    item:
      command: []`
(That's just the cropped config)

And it fires brackets in chat when you click on a book.

Setting it to `[]` should just cancel the event and stay in the GUI, not even close it.

**To Reproduce**
Setting command to [] and clicking the books, watch the video.

**Screenshots / Video**
https://streamable.com/oetpg

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.8.8]
- Plugin Version [7.0.9]

**Comment by pvpstryker** [comment]
Also every time I press back the GUI it sends the "Showing the list of all custom enchants." message.

**Comment by pvpstryker** [comment]
Here's a video if I wasn't clear: https://streamable.com/ekjrh .

**Comment by GC-spigot** [comment]
I need the config, post it in pastebin.com

**Comment by pvpstryker** [comment]
https://pastebin.com/1jPDys2g

**Comment by pvpstryker** [comment]
Line 161

**Comment by GC-spigot** [comment]
Changed this for next update
