### ISSUE TITLE
[BUG] Telepathy x Silk Touch Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#890]
Issue:
When a player mines any spawner using a telepathy and silk touch enchantment combination, the spawner will be duplicated.

Example:
Using Telepathy II to IV together with Silk Touch duplicates the spawners they are mining. A spawner will drop but the original spawner placed will not break. Continuous mining will result in many duplicates of the spawner.

Telepathy 1 works fine.

Plugin Version: 6.5.5

Server Version: Paper Spigot 1.14.4 and 1.13.2

**Comment by blek-id** [comment]
Probably has something to do with my issue as well #888

**Comment by GC-spigot** [comment]
Update your SilkSpawners, it's the root cause of this issue, on newest version of SilkSpawners I'm not able to recreate it. Any other spawners plugin works fine.

**Comment by BboyZeroOne** [comment]
Sorry I'm not using any silk spawner or spawner plugin. I'm using cmi's one.

https://pastebin.com/SwvxjjMJ
