### ISSUE TITLE
Issue with Jobs Reborn and the Autosmelt enchantment

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#891]
**Describe the bug**
Jobs doesn't pay you anything if you have the Autosmelt enchantment on your pickaxe when you are breaking iron/gold ore. This also happens with the default config of both plugins.

**To Reproduce**
Install both Jobs Reborn and AdvancedEnchantments. Get one pickaxe with Autosmelt and one without (no other enchantments required). Then break iron/gold ore with both pickaxes and compare the income.

**Server Information (please complete the following information):**
- PaperSpigot 1.13.2
- AdvancedEnchantments 7.1.0
- Jobs Reborn 4.15.5

**Comment by GC-spigot** [comment]
Should be fixed
