### ISSUE TITLE
Explosive Enchant - Bypassing world guard flags

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#893]
**Describe the bug**
Players can use explosive enchant to blow up protected areas such as a spawn area even with the correct flags set up

**To Reproduce**
Apply explosive enchant to a bow then fire it at a world guard protected area, it will blow up

**Server Information (please complete the following information):**
 - Minecraft Version [BeerSpigot 1.8]
- Plugin Version [7.1.0]

**Comment by GC-spigot** [comment]
It literally does not create an explosion. It shows the particle, sound and pushes away players from the location, it cannot damage blocks. You might need to look for flags such as 'pvp' and 'invincible' and deny them.
