### ISSUE TITLE
[Issue] It automatically disables my plugin.

### ISSUE THREAD

**Issue by Jikooo** [GC-spigot/AdvancedEnchantments#895]
Hello. I bought the plugin AdvancedEnchantments and when I run it by itself it works great, but as soon as I swap the enchantments.yml with another one that I made(from pervious version of the plugin) the console says that it can't register 'level' of payment or something like that. I tried to just copy the old enchants and paste them and replace the enchants from the new enchantment.yml, but that didn't seem to work. I am wondering if you could help me somehow to fix it since I have spent quite some time configuring A LOT of custom enchants from the ground up. Also the game is asking me a rethorical question: 'Is it up to date?' although I am running the latest version out there.

SERVER INFORMATION:
 - Minecraft Server Version [StellarSpigot - 1.8.8] (Which is kinda the same as Paper)
-  Advanced Enchantments version 7.1.2
                      PICTURES FROM MY CONSOLE 
![20200326_194803](https://user-images.githubusercontent.com/62717081/77680630-e83b4080-6f9c-11ea-9fa3-358a18665e9e.jpg)
![20200326_194846](https://user-images.githubusercontent.com/62717081/77680653-f12c1200-6f9c-11ea-9b1b-9e3ce6cb0af4.jpg)

**Comment by GC-spigot** [comment]
Search for 'DEFFENSE' and replace it to 'DEFENSE', it's a mistake in your config

**Comment by Jikooo** [comment]
Thank you so much!
