### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Deadkid11** [GC-spigot/AdvancedEnchantments#896]
Holy white scrolls do not dissapear upon death. Is this intended? If so, can we get a feature of making it so once you die once, your set is saved, but you lose the holy white scroll on your set, meaning you have to apply another? Also, can we get a option to disable/enable armor switching by right clicking, and finally, Our enchants have heroic versions, For example Heroic Overload, We would like it so you have to have the max level of the Legendary version, before being able to add the Heroic version. For example, We want it so if you have level 1/2 of a enchantment, you can't attempt to add a heroic version of that enchant to it, but if you have level 3 (Maxed) you can. Currently you can take a level 1 of the legendary enchants and add heroic versions of it.

**Comment by GC-spigot** [comment]
1st - will fix
2nd - https://prnt.sc/rojwem
3rd - will add

Also please include server & plugin version when reporting issues, hard to test cause not always all mc versions ahve same issues
