### ISSUE TITLE
[Issue] Magical Dust

### ISSUE THREAD

**Issue by JoshhB** [GC-spigot/AdvancedEnchantments#898]
**Describe the bug**
I cannot add magical dust to any enchant books. Is there a permission node im missing?

**To Reproduce**
 V V V

**Screenshots / Video**
https://gyazo.com/00545f06c949881eb8560baef4a20efc  -Gif

**Server Information (please complete the following information):**
 - Minecraft Version: [Spigot 1.8.8]
- Plugin Version [AdvancedEnchantments-7.1.1.jar]

**Comment by GC-spigot** [comment]
The magic dust group (simple) must be the same as books (elite), now they are different so dust cannot be applied. You can disable this behavior in groups.yml https://prnt.sc/rpotss
