### ISSUE TITLE
[Issue]When shooting a player with an enchanted bow, this error pops up.

### ISSUE THREAD

**Issue by xMystik** [GC-spigot/AdvancedEnchantments#900]
**Describe the bug**
When shooting a player with an enchanted bow, this error pops up.

**Screenshots / Video**
https://pastebin.com/Vnx26Ase

**Server Information (please complete the following information):**
 - Minecraft Version CannonSpigot
- Plugin Version 7.1.7

**Comment by GC-spigot** [comment]
Added an error message for invalid conditions, this seems to be the case. Update and use the new jar then find the enchant which causes this issue and fix it! :)
