### ISSUE TITLE
[Request] API jar

### ISSUE THREAD

**Issue by Spazzinq** [GC-spigot/AdvancedEnchantments#901]
Hello, I'm the developer of FlightControl. I've contacted you multiple times over Discord and you haven't replied to any of those messages, so I thought it would be a good idea to come here.

One of my users requested that I add support for your flight enchant. Could you post an API jar or provide me with a plugin download?

If you could also tell me the best way to accomplish a check for the "FLY" effect that would be great, thank you.

**Comment by GC-spigot** [comment]
I'll post an API jar on Spigot. You can only check for enchants on items, so checking for enchants on boots is what you could have.
