### ISSUE TITLE
[Issue] Infinite effect

### ISSUE THREAD

**Issue by haeiven** [GC-spigot/AdvancedEnchantments#905]
**Describe the bug**
If you have an infinite effect on your weapon, and this one is removed from your inventory by an other plugin, the effect remain until you're healed or you die.

**To Reproduce**
Take a weapon with an infinite effect.
Clear your inventory with an other plugin like Essentials.

**Screenshots / Video**
https://youtu.be/P1krYxIxiK4

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.8.8
- Plugin Version: 7.2.0

**Comment by GC-spigot** [comment]
That's something I can't fix, it's exactly what you described - removed by another plugin. My plugin doesn't know when a random plugin decides to remove an item.
