### ISSUE TITLE
New issues with Autosmelt and McMMO, NCP

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#911]
**Describe the bug**
Since the update to the SMELT effect (7.1.2), some related plugins are not working correctly when Autosmelt is used.

McMMO: Even ores placed by hand grant double drops and McMMO experience (the double drops require a high Mining level). Normally McMMO keeps track of placed blocks to prevent such behaviour.

NoCheatPlus: Having NCP enabled prevents Autosmelt from working at all (you pick up the respective ores again)

The combination of these two bugs allows the duplication of placed ores, which is quite problematic.

**To Reproduce**
Install said plugins (default config is sufficient), place either iron or gold ore and mine them with a pickaxe having Autosmelt.

**Server Information (please complete the following information):**
- Paper: 1.13.2/1.15.2
- AdvancedEnchantments: 7.2.1
- McMMO Overhaul 2.1.125
- NoCheatPlus: 3.17.SNAPSHOT-b5.6 (the latest bukkit release displays the same behaviour)

**Comment by GC-spigot** [comment]
Tried to fix this, let me know if it's fixed

**Comment by sh1mrr4** [comment]
I tested this with AdvancedEnchantments version 7.2.5, but there doesn't seem to be any change in the behaviour.
