### ISSUE TITLE
Issue with INCREASE_DAMAGE and negative integers

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#912]
**Describe the bug**
You mentioned a while back that it was possible to reduce incoming damage by a percentual value by using the INCREASE_DAMAGE effect, however, even negative values seem to increase the damage instead.
[(](https://github.com/GC-spigot/AdvancedEnchantments/issues/803)

**To Reproduce**
Create an enchantment that modifies damage, e.g. with INCREASE_DAMAGE:-90 and hit the wearer of that enchantment.

**Screenshots / Video**
Exemplary enchantment (increased values to get a significant efect):
![grafik](https://user-images.githubusercontent.com/47902483/78403069-0a1b6f80-75fc-11ea-810d-064736020833.png)

**Server Information (please complete the following information):**
- Paper: 1.15.2
- AdvancedEnchantments: 7.2.1

**Comment by GC-spigot** [comment]
I reworked something with damage so that may be the case - adding new effect DECREASE_DAMAGE for this
