### ISSUE TITLE
Obsidian Shield and Glowing Enchantment Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#914]
**Describe the bug**
Applying ObsidianShield and Glowing enchantment using /ae enchant (name) on items does not work.

**To Reproduce**
/ae enchant (name)

**Screenshots / Video**
none

**Server Information (please complete the following information):**
- Minecraft Version: PaperSpigot 1.15.2
- Plugin Version: 7.2.2

**Comment by BboyZeroOne** [comment]
This issue is related to this.

https://github.com/GC-spigot/AdvancedEnchantments/issues/915#issuecomment-609402770

**Comment by GC-spigot** [comment]
https://prnt.sc/rtnrnm this is what you need to use
