### ISSUE TITLE
[Issue] Null Error on Console

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#915]
**Describe the bug**
When executing /ae enchant (enchant) (level) while holding nothing, it gives out "An internal error has occurred" message while spamming console with errors.

https://pastebin.com/dhzDS0Rp

**To Reproduce**
/ae enchant (enchant) (level) with empty hand

**Screenshots / Video**
-

**Server Information (please complete the following information):**
- Minecraft Version: PaperSpigot 1.15.2
- Plugin Version: 7.2.2

**Comment by GC-spigot** [comment]
Thanks will fix
