### ISSUE TITLE
[Issue] ObsidianDestroyer Enchantment is not compatible with SaberFactions

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#917]
**Describe the bug**
ObsidianDestroyer is not compatible with SaberFactions. Although using the pickaxe to mine in a faction land under SaberFactions plugin, it would not work despite re-enchanting multiple times with multiple methods. /ae admin, /ae enchant, /ae givebook

**To Reproduce**
Use an obsidiandestroyer enchanted pickaxe on a claimed faction land under SaberFaction plugin 

**Screenshots / Video**
None

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.15.2
- Plugin Version: 7.2.2

**Comment by BboyZeroOne** [comment]
Bump. Almost 2 weeks without update.

**Comment by GC-spigot** [comment]
Try latest versions
