### ISSUE TITLE
Mismatch between `applies:` and `applies-to:` fields

### ISSUE THREAD

**Issue by TimonKnigge** [GC-spigot/AdvancedEnchantments#922]
**Describe the bug**
The user displayed string `applies-to:` is not always very indicative of the contents of `applies:`.  For example, looking at [the config](https://raw.githubusercontent.com/GC-spigot/AdvancedEnchantments/master/enchantments.yml) in this repo, we see the following enchants:

```
poison:
(...)
  applies-to: 'Weapon'
(...)
  applies:
    - ALL_SWORD
reforged:
(...)
  applies-to: 'Weapons'
(...)
  applies:
    - ALL_AXE
    - ALL_SWORD
    - ALL_PICKAXE
    - ALL_SPADE
(...)
rage:
(...)
  applies-to: 'Weapon'
(...)
  applies:
    - ALL_AXE
    - ALL_SWORD
```

It seems the `applies-to` from _Reforged_ should say _Weapons/Tools_ and the `applies` of _Poison_ should include `ALL_AXE` as well.

I feel like deriving the `applies-to` field from the contents of `applied` would work much better (and also fix some inconsistency issues, there are now several items with `applies-to: Bow` and several with `applies-to: Bows` (or `Weapon` vs. `Weapons` above) which really grinds my gears.

**To Reproduce**
See [config](https://raw.githubusercontent.com/GC-spigot/AdvancedEnchantments/master/enchantments.yml).

**Server Information (please complete the following information):**
Irrelevant, see config.

**Comment by GC-spigot** [comment]
I want to keep it configurable just for translation purposes and broad use, I could make this automated but in the end someone would request something else added to 'replace' automatic system. I will try to correct these issues in configuration.
