### ISSUE TITLE
Small issue with DECREASE_DAMAGE

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#923]
**Describe the bug**
The new DECREASE_DAMAGE function works great with one exception. When the victim has full health (or very low health) the damage reduction does not seem to work.

**To Reproduce**
Enchant an axe with an enchantment like Masterblacksmith (configured like the one shown in the screenshot) and start hitting a player till they die (no other enchantments involved).

**Screenshots / Video**
Enchantment I used for the test:
![grafik](https://user-images.githubusercontent.com/47902483/78771594-b52b8080-7990-11ea-9150-e6eb1f43a21f.png)

**Server Information (please complete the following information):**
 - Paper: 1.15.2
 - AdvancedEnchantments: 7.2.5

**Comment by GC-spigot** [comment]
Fixed
