### ISSUE TITLE
Killaura enchant issue

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#929]
**Describe the bug**
When killing stacked mobs while using killaura enchant it spams the chat saying "failed to parse effect 'CUSTOM' "

**Screenshots / Video**
https://gyazo.com/013f8dc00191d5cd85301542852d17f5

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. BeerSpigot 1.8.8]
- Plugin Version [7.2.4]

**Comment by GC-spigot** [comment]
Remove this enchant, support hasn't been added yet for KILL_STACK
