### ISSUE TITLE
Player Join Error

### ISSUE THREAD

**Issue by FeroxDrood** [GC-spigot/AdvancedEnchantments#931]
Hello, i am getting this error when players join on paper 1.15.2

`10.04 16:54:35 [Server] ERROR Could not pass event PlayerJoinEvent to AdvancedEnchantments v7.2.7
10.04 16:54:35 [Server] INFO java.lang.NullPointerException: null
10.04 16:54:35 [Server] INFO at n3kas.ae.enchanthandler.enchanttypes.EFFECT_STATIC.lookup(EFFECT_STATIC.java:100) ~[?:?]
10.04 16:54:35 [Server] INFO at n3kas.ae.enchanthandler.enchanttypes.EFFECT_STATIC.runCheck(EFFECT_STATIC.java:57) ~[?:?]
10.04 16:54:35 [Server] INFO at n3kas.ae.enchanthandler.enchanttypes.EFFECT_STATIC.updateWornArmor(EFFECT_STATIC.java:35) ~[?:?]
10.04 16:54:35 [Server] INFO at n3kas.ae.globallisteners.listeners.JoinEvent.onPlayerJoin(JoinEvent.java:24) ~[?:?]
10.04 16:54:35 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor726.execute(Unknown Source) ~[?:?]
10.04 16:54:35 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1284) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1127) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:935) ~[patched_1.15.2.jar:git-Paper-165]
10.04 16:54:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Comment by GC-spigot** [comment]
Fixed
