### ISSUE TITLE
TP DROP does not work on golden pickaxe

### ISSUE THREAD

**Issue by FeroxDrood** [GC-spigot/AdvancedEnchantments#932]
**Describe the bug**
TP DROP does not work on golden pickaxe when mining ores

**To Reproduce**
put an enchant using TP Drop on a golden pickaxe

**Screenshots / Video**

**Server Information (please complete the following information):**
 - paper 1.15.2
- 7.2.7

**Comment by GC-spigot** [comment]
Golden pickaxe has no difference from any other pickaxes, if it doesn't work with Tp Drops then the cause is another plugin.
