### ISSUE TITLE
[Request] EnchantActivateEvent player support

### ISSUE THREAD

**Issue by TasmanianNoob** [GC-spigot/AdvancedEnchantments#933]
** Describe the Request**
Add the player that activated the enchant acitvate event to the API e.g.
```
        @EventHandler
	public void onEnchantActivate(final EnchantActivateEvent event) {
		if (event.getPlayer().getName().equals("notch") {
			event.getPlayer().sendMessage("Hello!");
		}
	}
```

**Comment by TasmanianNoob** [comment]
or could you make getFirstEntity() & getSecondEntity() return entities instead of objects?

**Comment by GC-spigot** [comment]
It just needs simple casting, e.g. `((Entity) getFirstEntity())`. I will however make them Entities now.
