### ISSUE TITLE
[Issue] JobsReborn + TRENCH

### ISSUE THREAD

**Issue by ZeddyOG** [GC-spigot/AdvancedEnchantments#934]
**Describe the bug**
When using JobsReborn (Miner job to be specific) and TRENCH from AE for some reason the effect seems to cause JobsReborn to pay multiple times for each block (Mining 1 diamond ore on my custom config with a normal pickaxe wielded $21 and with TRENCH it gave me $42)

**To Reproduce**
Install JobsReborn and have an enchantment using the TRENCH effect and a normal pickaxe (to compare) mine the same thing 2x (once with each pickaxe) and you will see the payment differences.

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
 - Minecraft Version: Paper 1.15.2
- Plugin Version: 7.2.8

**Comment by FeroxDrood** [comment]
Can confirm this is happening to me too

**Comment by GC-spigot** [comment]
Fixed
