### ISSUE TITLE
Trickster enchant Issue

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#936]
**Describe the bug**
When the effect of Trickster happens, the players can not hit each other for the next 5 seconds, this happens every time trickster effect goes off.

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version [BeerSpigot 1.8.8]
- Plugin Version [7.2.4]

**Comment by GC-spigot** [comment]
Set 'teleport-delay' in Essentials to 0
