### ISSUE TITLE
[Bug Report] Detonate and BlockTrak Issue - ★★★★

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#941]
**Bukkit**: Paperspigot 1.13.2
**Plugin**: AdvancedEnchantments 7.3.0
**Severity**: ★★★★
**Explanation**: 
After applying Detonate and BlockTrak to the pickaxe, digging increases the BlockTrak lore.
**Video**: https://youtu.be/lqD11EF1BNQ

**Comment by GC-spigot** [comment]
Fixed
