### ISSUE TITLE
[Bug Report] 'CUSTOM_TRENCH' lapis lazuli Issue - ★★

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#942]
**Bukkit**: Paperspigot 1.13.2
**Plugin**: AdvancedEnchantments 7.3.0
**Severity**: ★★
**Explanation**: If you dig Lapis Lazuli with 'CUSTOM_TRENCH' detonate, ink will come out.
**Video**: https://youtu.be/Nw_jAXIEiBM

**Comment by GC-spigot** [comment]
Fixed
