### ISSUE TITLE
[Issue] Trench & Detonate console issue.

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#943]
**Describe the bug**
Lots of console errors when using pickaxe with detonate and telepathy. Granite, Diorit, Andersite, Diamond Ore and Coal Ore will disappear when mined.

**To Reproduce**
Use pickaxe with detonate and telepathy. Autosmelt is also bugged with it.

**Screenshots / Video**
https://pastebin.com/QS1uK0X7
https://imgur.com/a/2AFiqZZ

**Server Information (please complete the following information):**
 - Minecraft Version: 1.15.2 Paper
- Plugin Version: 7.3.0

**Comment by GC-spigot** [comment]
Fixed!
