### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Lunatik934** [GC-spigot/AdvancedEnchantments#945]
**Describe the bug**

Look the error
https://paste.helpch.at/afahocuwip.md
**To Reproduce**
A way to reproduce the video

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version Paper 1.13.2
- Plugin Version 731

**Comment by GC-spigot** [comment]
Enchant is there because you don't give the level, i will add a warning message
