### ISSUE TITLE
[Issue] INCREASE_DAMAGE does not fully support MysticMobs and Skript

### ISSUE THREAD

**Issue by DavidVioMC** [GC-spigot/AdvancedEnchantments#946]
**Describe the bug**.
Sometimes, espically with vanilla mobs spawned by MysticMobs, using enchants that contain INCREASE_DAMAGE bug out the death event for MysticMobs and Skript. Basically the player in the death event is reported as < none > in Skript and MysticMobs thinks it was killed by a plugin and doesn't drop the correct drops. Not sure how INCREASE_DAMAGE is applied but pretty sure it just damages the mob instead of adding damage to the event.

**To Reproduce**
Add a cow to MysticMobs such as this
Cow:
  Mobtype: COW
  Display: 'Simple Cow'
  Health: 10
  Damage: 0
  Options:
    AlwaysShowName: true
    Despawn: true
    FollowRange: 30

and add this enchant:
    5:
      chance: 100
      cooldown: 0
      effects:
        - 'INCREASE_DAMAGE:<random number>115-245</random number> %attacker%'

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
 - Minecraft Version 1.12.2
- Plugin Version 7.3.1

**Comment by GC-spigot** [comment]
Should be fixed
