### ISSUE TITLE
[Issue] AutoSmelt not dropping correct items.

### ISSUE THREAD

**Issue by Snowy654** [GC-spigot/AdvancedEnchantments#951]
**Describe the bug**
When mining the following with ores/blocks with AutoSmelt, my players get the following:

Lapis Ore = Lapis Ore
Coal Ore = Coal Ore
Redstone Ore = Redstone Ore
Smooth Stone = Smooth stone slabs
Andesite, Granite, Diorite and their Polished counterparts = Stone

**To Reproduce**
Enchant with AutoSmelt then mine the above, blocks will duplicate if using fortune enchant.

**Server Information (please complete the following information):**
 - Paper 1.15.2 #192 but this has been a known issue by my players for some time. only now telling me...
- Plugin Version = 7.3.2 and 7.3.5

Cheers GC!

**Comment by GC-spigot** [comment]
Fixed
