### ISSUE TITLE
AutoSmelt Issue

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#955]
**Describe the bug**
The bug occurs when a non-opped player tries to break ore with autosmelt enchantment on pickaxe, what happens is the player has to break the block twice and it does not smelt the ore, instead gives the ore back.

**To Reproduce**
Get autosmelt III enchant, set to 100% chance to autosmelt and de-op yourself and try to mine ore.

**Screenshots / Video**
https://gyazo.com/6e2d48a328eaec38df1bc57131ce4fe7

**Server Information (please complete the following information):**
 - Minecraft Version [BeerSpigot 1.8]
- Plugin Version [7.3.3]

**Comment by GC-spigot** [comment]
Update
