### ISSUE TITLE
[Request] Lore

### ISSUE THREAD

**Issue by SlimeCody** [GC-spigot/AdvancedEnchantments#956]
** Describe the Request**

If you could add in a feature for the lore, relating to how many characters to cap each line at 

LoreLineCharacterMax: 35

and have it end on the word before it would hit the max.
https://cdn.discordapp.com/attachments/700535496518008935/700824154328531064/unknown.png
https://cdn.discordapp.com/attachments/700535496518008935/700823723883626607/unknown.png
Player is obviously using a smaller screen

**Comment by GC-spigot** [comment]
It actually has a cap now for /enchants but because of spaces (and can't split to new line mid word) this may happen sometimes, I recommend actually just changing where new line starts in `enchantments.yml` for enchants that have this issue
