### ISSUE TITLE
Kill Aura Enchantment Issue

### ISSUE THREAD

**Issue by DJGamer987654** [GC-spigot/AdvancedEnchantments#958]
**Describe the bug**
I get spammed with an error in game when a player uses a sword with the kill aura enchantment.

**To Reproduce**
They use a sword that has the kill aura enchantment

**Screenshots / Video**
https://imgur.com/a/XsPtbJ9

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]: Spigot 1.13.2
- Plugin Version [e.g. 6.7.8]L 7.1.0
[message (5).txt](https://github.com/GC-spigot/AdvancedEnchantments/files/4497938/message.5.txt)

**Comment by GC-spigot** [comment]
Remove the enchant, it's currently not supported
