### ISSUE TITLE
Auto Smelt Issue

### ISSUE THREAD

**Issue by Callum0508** [GC-spigot/AdvancedEnchantments#959]
**Describe the bug**
Autosmelt doesn't work properly for non-opped players, instead of dropping the ingot the player has to break the ore twice and after that it still drops the ore.

**To Reproduce**
Combine AutoSmelt III to a pickaxe, break some iron ore with a player that doesn't have op.

**Screenshots / Video**
Non opped player - https://gyazo.com/70d210aa068018b68d786d8eb1fec568
Opped Player - https://gyazo.com/89d9a1cb9982dc4f95a2f96ed7df3287

**Server Information (please complete the following information):**
 - Minecraft Version [BeerSpigot 1.8]
- Plugin Version [3.7.3]

**Comment by GC-spigot** [comment]
Fixed
