### ISSUE TITLE
[Issue] Pass Inventory Event Error on Books in ae admin (pg4)

### ISSUE THREAD

**Issue by EchocallingEarth** [GC-spigot/AdvancedEnchantments#960]
**Describe the bug**
When entering the admin GUI **ae admin** and access page 4 of enchantments noted that 3 icons are books verse firework stars. When clicking on any of these 3 books the console fills with errors. See attached for error base as well as full console log

AE error: https://pastebin.com/0NFEnZYF
(error here is for only 1 of the three books shown in GUI, can provide full error logs for each book upon request)

Full console log: https://pastebin.com/6vaBAHqv

**To Reproduce**
Use the fulling commands and directions to reproduce the error:
 - /ae admin
 - Move to page 4 of GUI
 - Click on any of the 3 books shown in lines 3 and 5 (see image below)
Doing the above 3 steps will cause error log in console.

**Screenshots / Video**
<img width="211" alt="ae book error" src="https://user-images.githubusercontent.com/47970978/79696580-6f51a080-824b-11ea-99b4-9bba897ac831.PNG">

**Server Information (please complete the following information):**
 - 1.15.2
 - Paper and Spigot (tested on both)
 - 7.3.7

Additional plugins on the server if this information helps:
Complete Plugins List pulled from Console:
Total Count: 66
EpicVouchers, UltimateFishing, ResourceWorld, PlaceholderAPI, ArmoredElytra, Item-Chest-Sorter, PlugMan, BackpacksRemastered, HorseOverhaul, NoPlugins, DangerousCaves, JoinMessagesGUI, PotionCreation, CombatPlus, NBTAPI, LuckPerms, WorldEdit, AcceptTheRules, VillagerOptimiser, ItemInChatFree, spark, CosmicVaults, ProtocolLib, ImageOnMap, LimitPillagers, BeehivesPro, Vault, BKCommonLib, AdminGUI-Premium, EpicHeads, PerWorldInventory, HolographicDisplays, AAC, My_Worlds, CMIEInjector, CoreProtect, UltimateRepairing, CustomCobbleGen, CustomEnderChest, ChatControl, HeadDatabase, CommandPanels, EpicLevels, CustomGUI, AuctionHouse, LWC, CMI, DisplayShops, UltimateKits, WorldGuard, WorldGuardExtraFlags, AdvancedEnchantments, Jobs, WolfyUtilities, GriefPrevention, BigDoors, GriefPreventionFlags, UltimateTimber, CustomCrafting, EpicFurnaces, EpicHoppers, EpicAnchors, UltimateStacker, EpicFarming, EpicSpawners, UltimateCatcher

**Comment by GC-spigot** [comment]
You have enchants which aren't same group as others. If you need help resolving this PM me on Discord GC#0830 and we'll resolve it
