### ISSUE TITLE
[Issue] AutoSmelt turn blocks to stone.

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#961]
**Describe the bug**
Mining Andesite/Diorite/Granite with AutoSmelt enchantment turns blocks to stone.

**To Reproduce**
As described above.

**Screenshots / Video**
None

**Server Information (please complete the following information):**
 - Minecraft Version: Paper Spigot 1.15.2
- Plugin Version: 7.3.7-1

**Comment by GC-spigot** [comment]
This issue is something I can't fix yet due to how Spigot enforces materials - either using 1.8 or 1.15, but using 1.15 would stop me from allowing 1.8 support, this is coming very soon and I'm aware of this issue but I can't fix it now
