### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Ma8ician** [GC-spigot/AdvancedEnchantments#962]
>.... [12:57:11 WARN]: java.lang.IllegalArgumentException: Cannot drop air
>.... [12:57:11 WARN]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.EntityItem.setItemStack(EntityItem.java:433)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.EntityItem.<init>(EntityItem.java:42)
>.... [12:57:11 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.dropItem(CraftWorld.java:712)
>.... [12:57:11 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1208)
>.... [12:57:11 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:105)
>.... [12:57:11 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:254)
>.... [12:57:11 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:123)
>.... [12:57:11 WARN]: at n3kas.ae.enchanthandler.enchanttypes.MINING.lambda$0(MINING.java:72)
>.... [12:57:11 WARN]: at java.util.ArrayList.forEach(ArrayList.java:1257)
>.... [12:57:11 WARN]: at n3kas.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:67)
>.... [12:57:11 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor963.execute(Unknown Source)
>.... [12:57:11 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [12:57:11 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [12:57:11 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [12:57:11 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:315)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:274)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:215)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1324)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1034)
>.... [12:57:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950)
>.... [12:57:11 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:57:11 INFO]: [AdvancedEnchantments ERROR] Could not pass IllegalArgumentException: Cannot drop air
>.... [12:57:11 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1208)
>.... [12:57:11 INFO]: [AdvancedEnchantments] Extra info: effect[TRENCH:3]; enchant[detonate]; mc[115]; ae[7.3.7]
>.... [12:57:11 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.

**Comment by Ma8ician** [comment]
version 7.3.7  paper 201

**Comment by GC-spigot** [comment]
Thanks will fix
