### ISSUE TITLE
Enchantment Orb [Issue]

### ISSUE THREAD

**Issue by Samington** [GC-spigot/AdvancedEnchantments#965]
Default players are only able to add one Enchantment Orb per item
Eg.
Adds Armor Enchantment Orb [10]
Later finds a Armor Enchantment Orb [11]
It says he cant add anymore Enchantment Orbs

**Server Information (please complete the following information):**
 - StellarSpigot 1.8
-  Plugin Version 7.4

**Comment by GC-spigot** [comment]
Fixed
