### ISSUE TITLE
[Issue] Haste Enchant Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#966]
**Describe the bug**
Players who aren't OP are not able to break blocks using the haste enchanted pickaxe. I've tested while in OP and not OP.

**To Reproduce**
De-OP yourself. Mine with a haste enchanted pickaxe.

**Screenshots / Video**
https://imgur.com/a/R4oY9rd

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.15.2
- Plugin Version: 7.4.0

**Comment by GC-spigot** [comment]
Fixed
