### ISSUE TITLE
A few bugs / Errors [Issue]

### ISSUE THREAD

**Issue by Samington** [GC-spigot/AdvancedEnchantments#969]
**Describe the bug**
Enchants: Lucky , Infinite Luck and Resilience are not added(Cosmic)

Any /ae giveitem (putting a quantity amount number doesnt register it just gives 1)

Chain Lifesteal is a chestplate enchant not a Sword enchant

**Server Information (please complete the following information):**
 - Minecraft Version StellarSpigot 1.8
- Plugin Version 7.4.2

**Comment by GC-spigot** [comment]
Fixed / changed
