### ISSUE TITLE
2 Bugs [Issue]

### ISSUE THREAD

**Issue by Samington** [GC-spigot/AdvancedEnchantments#970]
**Describe the bug**

1. Effects: TNT (Breaks surrounding area, in normal wilderness)
2. Once 1 enchant has been applied to to any tool/weapon it can one tap stone, giving stone bricks

**Server Information (please complete the following information):**
 - Minecraft Version StellarPvP 1.8
- Plugin Version 7.4.5

**Comment by GC-spigot** [comment]
For 1st, you might be talking about fireballs rather, TNT doesn't even explode tnt just shows particle & sound / pushes players away, no actual TNT.
