### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Samington** [GC-spigot/AdvancedEnchantments#974]
/ae giveitem Sweaty orb 2 Armor 15 100
Gives 4 Orbs
/ae giveitem Sweaty orb 4 Armor 15 100
Gives 16 Orbs

**Server Information (please complete the following information):**
 - Minecraft Version StellarSpigot 1.8
- Plugin Version -  Latest

**Comment by GC-spigot** [comment]
Fixed
