### ISSUE TITLE
Slot Increaser Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#975]
**Describe the bug**
Players who apply Simple Slot Increaser item to an item, they will be able to apply higher enchantment books to the item.

**To Reproduce**
1. Apply Simple Slot Increaser to any item.
2. Apply any enchanted books higher than Simple enchant.

**Screenshots / Video**
https://www.youtube.com/watch?v=GDDWoUj8LCM&feature=youtu.be

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.15.2
- Plugin Version: 7.4.6

**Comment by GC-spigot** [comment]
It's not supposed to limit what enchant types they can apply - the reason why different slot increasers exist is to customise how many new slots it can add, i.e. you can make simple one add 1 and legendary 2
