### ISSUE TITLE
[Issue] Autosmelt Enchantment Bug

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#976]
**Describe the bug**
Autosmelt pickaxe does not break certain blocks. 

Ok so here is a few tests i did:
1. Broke iron, gold, redstone, coal ores and cobblestone. Got respective smelted products. Auto smelt works.
2. Failed to break stone, stone brick, chiseled stone brick, prismarine, granite, diorite, andesite, netherrack. Notably these are non-smeltable blocks. Animation occurs normally, blocks disappear and reappear immediately. If left mouse button is held down, block disappears and reappears continuously with block breaking particles flying out of the block.
3. Breaking blocks in (2.) while in floating or moving in water works sometimes (not consistent). However if underwater and standing on solid ground same issue as (2.) occurs.
4. Breaking of smeltable blocks is noticeably slow. Haste enchant does not seem to work. Speed of block breaking is similar to a diamond pickaxe enchanted with efficiency 5 (bugged pickaxe has this enchant too).
5. When attempting to break un-smeltable blocks, speed is significantly faster. Haste enchant appears to work but no blocks are broken. Sometimes blocks behind the targeted block visually breaks as well, which happens normally due to how fast blocks are broken. Upon breaking of target block with vanilla pickaxe, blocks behind are unbroken as well.
6. When attempting to break un-smeltable blocks, hunger drops as if mining action was successful. Lose food bar relatively quickly with no actual work done. Suggests that this is not a visual bug.
7. Mining while jumping works as long as block is broken before player model touches the ground. 
8. Mining down while standing on the block may result in success. Possibly due to player model "phasing" through the block between the time when its broken and reappears, thus player is "mid air" or simply not considered in contact with the ground as y value is changing. 
9. Repeating (8.) while in water and holding shift has resulted in greater consistency albeit still not 100% occurrence. Possible due to faster decent of player model thus more instances of "phasing: through block underneath.

**To Reproduce**
Use an autosmelt enchanted pickaxe and mine affected blocks.

**Screenshots / Video**
None

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.15.2
- Plugin Version: 7.4.6

**Comment by GC-spigot** [comment]
Should be fixed
