### ISSUE TITLE
[Issue] Destroy chance of enchantments destroys items, even if the enchantment cannot be applied

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#977]
**Describe the bug**
It seems the destroy chance of an enchantment is checked, even if the respecitve enchantment cannot be applied to an item due reaching the maximum number of enchantments on that item. 

**To Reproduce**
Limit maximum number of enchantments per item to four for example. Add four different enchantments. Try adding a fith enchantment with a destroy chance >0. Even if the destroy chance is low, the item will eventually be destroyed if you try often enough.

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.15.2]
- Plugin Version [e.g. 7.4.6]

**Comment by GC-spigot** [comment]
Thanks will fix
