### ISSUE TITLE
[Request] Make DEATH type enchantments also work for non-PvP related deaths or add an option for it

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#979]
** Describe the Request**
Currently, enchantments with DEATH are only triggered if the player is killed by another player. I think it would be a great addition though, if it was possible to use it for other death types (or just dying in general) as well.  

That way, it would be possible to use this type of enchantments in PvE scenarios as well or to trigger effects like KEEP_ON_DEATH.

**Comment by jj136975** [comment]
+1

**Comment by GC-spigot** [comment]
Added
