### ISSUE TITLE
[Request] Throw Up

### ISSUE THREAD

**Issue by Pajlis** [GC-spigot/AdvancedEnchantments#982]
** Describe the Request**
You somewhat merged AdvancedSets to this plugin. I noticed that in AdvSets, there is an effect "Throw up". I am hoping that this EFFECT can also be introduced into AdvEnchantments.

From AdvSets:
THROW_UP: (number of blocks), Throws other player up in the air, e.g.: 'THROW_UP:5'

Spigot Username: Qpeety

**Comment by GC-spigot** [comment]
Use `BOOST:<number of blocks>`
