### ISSUE TITLE
[Issue] TP_DROPS Function not destroying blocks

### ISSUE THREAD

**Issue by Ashinos** [GC-spigot/AdvancedEnchantments#983]
**Describe the bug**
Some blocks do not break using tools that have an enchantment with the TP_DROPS function. It also causes issues with our Jobs plugin. For example people are able to break the same vine over and over (because it never actually breaks, just reappears) and get paid for it. I noticed this is an issue with blocks that don't drop anything without silktouch and 1.15 blocks, not sure if there are others.

**To Reproduce**
Use a TP_DROPS enchant on a vine or any other block mentioned above, it just reappears.

**Screenshots / Video**
None

**Server Information (please complete the following information):**
 - Minecraft Version Paper Spigot 1.15.2
- Version 7.3.7

**Comment by blek-id** [comment]
Some other blocks that I would add is Diorite, Andesite and Granite, they turn into stone instead.

And also, if the player's inventory is full, the item would be lost. It would be better to create a fail-safe and just drop the item instead when the inventory is full

**Comment by GC-spigot** [comment]
Update
