### ISSUE TITLE
Greater possibilities for overall customisability

### ISSUE THREAD

**Issue by Coolfire02** [GC-spigot/AdvancedEnchantments#992]
It'll be extremely powerful to use a general placeholder system for *most* of the configurable components so that this could be less of an issue for others that may want to configure other items to their likings as well
For me as of now, I would very much like to see these small but neat features added to AE:

(Item designing (aka lores, names, messages):
- firework-color: for (config.yml - enchantment-book:)
- %enchant-firework-color% for (config.yml - enchantment-book:)
- %max-level% for (config.yml - lore of enchantment-books under enchantment-book:)

Here are some of my ideas for new bigger features in AE

(Possible future features):
- "Power based" enchantment caps (Using total "power" of the gear to determine how many more enchantments can be added to the gear):
Power would basically represent the total "enchantment levels" there are on the gear for e.g. if there is Lifesteal V & Overload III on an armor piece,
the power = 8. This power system could be toggled on/off in conjunction with the max-enchants system that is already in AE

- New setting: Require supporting enchant to be maxed level on gear: true/false 
This setting would allow the configurator to determine whether or not for e.g. must you have Trap V to apply Titan Trap x or could you just have Trap I and still apply it

- "Pages" similar to magic dusts but instead, could give both destory & success rate modifier

- EXP Conversion for enchant books (toggleable from the currently used magic dust system), exp return amount per book modifiable by levels so for e.g.
Tinkerer XP Calculation: enchant-group-xpcost / 10 * enchant-level

Hope you do consider adding them!

Also ps: (minor bug) confirm button for top right /tinker dosen't work (u gotta use the top left one instead)

**Comment by GC-spigot** [comment]
"New setting: Require supporting enchant to be maxed level on gear: true/false" already possible
"Pages" similar to magic dusts but instead, could give both destory & success rate modifier - can be changed with config settings
EXP Conversion for enchant books (toggleable from the currently used magic dust system), exp return amount per book modifiable by levels so for e.g.
Tinkerer XP Calculation: enchant-group-xpcost / 10 * enchant-level - planned

Everything else seems to be added / will not be
