### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Deadkid11** [GC-spigot/AdvancedEnchantments#994]
I am currently using a plugin called EliteArmor. They have armor set effects that are not provided within AdvancedEnchantments, I would like these potentially added to AE if possible.

- Trap Effect; Upon damaging or being damaged (Make it so I can choose which event), chance to Trap your enemy, disabling all movement.

- Web Effect; Upon damaging or being damaged (Make it so I can choose which event), chance to spawn webs on enemy for (X) seconds in a horizontal  radius (X) around a player's feet with a (X) height option. (X) Being customize-able values. If possible make it so the webs only appear for and affect the enemy player, as EliteArmor does. After (X) seconds, webs are removed.

- Cage Effect; Upon damaging or being damaged (Make it so I can choose which event), chance to spawn a Cage of blocks around your enemy for (X) seconds, Size = 3 x 3 x 4, with each block being customize-able if possible, so I can design the cage as I want it to look, if not, then just a cage made from iron bars and some other customize-able block, and the two blocks in which the player is, be able to add blocks, for example stone to suffocate, or lava to burn, water to drown. After (X) seconds, cage is removed.

**Comment by EwansXD** [comment]
For web effect could be spawnblock effect and spawn a block for x amount of ticks at a players feet, that way it could be used in multiple ways
