### ISSUE TITLE
[Issue] customcommands.yml

### ISSUE THREAD

**Issue by ZeddyOG** [GC-spigot/AdvancedEnchantments#999]
**Describe the bug**
When modifying the "enchantments" section of the customcommands.yml the GUI bugs out when you set the size to 9 (which it supports) and it will not open up the groups.

I tested on all other GUIs 18, 27, 36, 45, + 54 and all of them allowed me to open up the groups from inside the GUI.

**To Reproduce**
In customcommands.yml set the "size" to 9, along with adjust the groups placeholders to be within the GUI, and try to open up any of the groups from the /enchants GUI.

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
 - Minecraft Version: 1.15.2
- Plugin Version: 7.5.0-Pre4

**Comment by GC-spigot** [comment]
That is because further inventory showing enchants uses more than 1 line with the go-back item, previous page item etc.
